In [1]:
import torch

### set up CUDA as device if available
if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")
    cuda_id = torch.cuda.current_device()
    print(f"ID of current CUDA device:{torch.cuda.current_device()}")
    print(f"Name of current CUDA device:{torch.cuda.get_device_name(cuda_id)}")
    print(f"CUDA version: {torch.version.cuda}")
else:
    print("GPU is not available, using CPU")
    device = torch.device("cpu")
print(f"device: {device}")

GPU is available
cuda
CUDA version: 12.4
ID of current CUDA device:0
Name of current CUDA device:NVIDIA H200

In [2]:
import numpy as np
import random
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm, trange
from IPython import display
from sklearn.metrics import average_precision_score
# from conf_and_plot import confusion_matrix_plots
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import KFold
from sklearn.model_selection import ParameterGrid
import seaborn as sns
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import kruskal
import torch.nn.functional as F
from IPython.display import clear_output
import statistics

def seed_all(seed):
    if not seed:
        seed = 10

    print("[ Using Seed : ", seed, " ]")

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

seed_all(2025)

[ Using Seed :  2025  ]

In [3]:
scint_thresh = 0.1 # set the phase scintillation threshold

### following variable not being used anywhere
scint_outlier_thresh = 5. # set the value that determines phase scintillation outliers (these data samples will be removed)

processed_data_2015 = pd.read_csv("processed_data_2015.csv")
processed_data_2015 = processed_data_2015.drop(processed_data_2015.columns[0], axis=1)
predicted_label = 'sigmaPhi projected to vertical at prediction time [radians]'
y = processed_data_2015[predicted_label].values
print(y.shape)

X_fSelect = processed_data_2015.drop(predicted_label, axis=1)
X_fSelect = X_fSelect.values
print(X_fSelect.shape)

(4465846,)
(4465846, 15)

In [4]:
class simple_timeSeries_CNN(nn.Module):
    def __init__(self, cnn_filters, fc_size, dropout_p, loss, sequence_length):
        super(simple_timeSeries_CNN, self).__init__()
        
        self.loss = loss
        self.sequence_length = sequence_length

        self.conv1 = nn.Conv1d(in_channels=15, out_channels=cnn_filters, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm1d(num_features=cnn_filters)
        self.dropout = nn.Dropout(dropout_p)
        self.conv2 = nn.Conv1d(in_channels=cnn_filters, out_channels=cnn_filters*2, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm1d(num_features=cnn_filters*2)
        self.pool = nn.MaxPool1d(2)
        
        ### for simple, non true time-series CNN:
        # num_features = 25, MaxPool1d_size=2
        # 12 = round(25 / 2)
        # 6 = round(12 / 2)
        # self.fc1 = nn.Linear(cnn_filters * 2 * 6, fc_size)
        
        ### for true time-series CNN:
        # sequence_length, MaxPool1d_size=2
        # round(sequence_length / 2) = sequence_length // 2
        # per maxpool layer = sequence_length // 4
        
        self.fc1 = nn.Linear(cnn_filters * 2 * (sequence_length // 4), fc_size)
        # self.fc2 = nn.Linear(fc_size, 1)
        self.fc2 = nn.Linear(fc_size, sequence_length)

    def forward(self, x):
        x = self.pool(torch.relu(self.bn1(self.conv1(x))))
        x = self.dropout(x)
        x = self.pool(torch.relu(self.bn2(self.conv2(x))))
        x = x.view(x.size(0), -1) # Flatten the output for the fully connected layers
        x = torch.relu(self.fc1(x))
        
        # second fully connected layer + reshape to [batch_size, sequence_length, 1]
        x = self.fc2(x).view(x.size(0), self.sequence_length, 1)

        if self.loss == 'focal':
            # x = torch.sigmoid(self.fc2(x))
            x = torch.sigmoid(x)
        elif self.loss == 'bce':
            # x = self.fc2(x)
            pass
        
        return x

In [5]:
def true_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    tss = (TP / (TP + FN)) - (FP / (FP + TN))
    return tss

def heidke_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    
    numerator = 2 * (TP * TN - FP * FN)
    denominator = (TP + FP) * (FP + TN) + (TP + FN) * (TN + FP)
    
    # Avoid division by zero
    if denominator == 0:
        return 0.0
    
    hss = numerator / denominator
    return hss

In [6]:
class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction  # 'mean', 'sum', or 'none'

    def forward(self, inputs, targets):
        BCE_loss = F.binary_cross_entropy(inputs, targets, reduction='none')
        p_t = inputs * targets + (1 - inputs) * (1 - targets)
        focal_loss = self.alpha * (1 - p_t) ** self.gamma * BCE_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        elif self.reduction == 'none':
            return focal_loss
        else:
            raise ValueError(f"Invalid reduction method: {self.reduction}")

In [7]:
def train_model_with_cv(model, train_dataloader, val_dataloader, criterion, optimizer, scheduler, num_epochs):

    epochs = []
    training_loss = []
    validation_loss = []
    training_tss = []
    validation_tss = []
    training_hss = []
    validation_hss = []

    for epoch in range(num_epochs):

        ### training loop
        model.train()
        running_loss = 0.0
        predicted_training_labels = np.array([])
        y_train = np.array([])

        # for batch_inputs, batch_labels in tqdm(train_dataloader):
        for batch_inputs, batch_labels in train_dataloader:
            
            batch_inputs = batch_inputs.to(device)
            batch_labels = batch_labels.to(device)
            
            optimizer.zero_grad()
            output = model(batch_inputs)
            
            output.to(device)
            
            loss = criterion(output, batch_labels.float())
            loss.backward()
            optimizer.step()
            
            if scheduler == False:
                pass
            else:
                scheduler.step()
            
            running_loss += loss.item()
            with torch.no_grad(): predicted_training_labels = np.append(predicted_training_labels, output.cpu())
            with torch.no_grad(): y_train = np.append(y_train, batch_labels.cpu())

        predicted_training_labels = np.where(predicted_training_labels > 0.1, 1, 0)

        train_loss = running_loss / len(train_dataloader)
        train_tss = true_skill_score(y_train.astype(int), predicted_training_labels.astype(int))
        train_hss = heidke_skill_score(y_train.astype(int), predicted_training_labels.astype(int))

        ### validation loop
        model.eval()
        with torch.no_grad():
            running_loss = 0.0
            predicted_val_labels = np.array([])
            y_val = np.array([])

            # for batch_inputs, labels in tqdm(val_dataloader):
            for batch_inputs, batch_labels in val_dataloader:
            
                batch_inputs = batch_inputs.to(device)
                batch_labels = batch_labels.to(device)
                
                outputs = model(batch_inputs)
            
                outputs.to(device)
                
                outputs = model(batch_inputs)
                loss = criterion(outputs, batch_labels.float())
                running_loss += loss.item()
                predicted_val_labels = np.append(predicted_val_labels, outputs.cpu())
                y_val = np.append(y_val, batch_labels.cpu())

        predicted_val_labels = np.where(predicted_val_labels > 0.1, 1, 0)

        val_loss = running_loss / len(val_dataloader)
        val_tss = true_skill_score(y_val.astype(int), predicted_val_labels.astype(int))
        val_hss = heidke_skill_score(y_val.astype(int), predicted_val_labels.astype(int))

        epochs.append(epoch)
        training_loss.append(train_loss)
        validation_loss.append(val_loss)
        training_tss.append(train_tss)
        validation_tss.append(val_tss)
        training_hss.append(train_hss)
        validation_hss.append(val_hss)

    return training_hss, validation_hss, training_tss, validation_tss

In [8]:
class CNNBinaryTimeSeriesClassifier():
    def __init__(self, cnn_filters=8, fc_size=64, sequence_length=60, dropout_p=0.1, batch_size=128, 
                 optimizer_type = 'adam', lr=0.001, sgd_momentum=0.9, weight_decay=0.0001,
                 loss='bce', bce_pos_class_weight=50, focal_alpha=0.25, focal_gamma=2,
                 num_epochs=5, cv_folds=5, scheduler_t=0):
        self.cnn_filters = cnn_filters
        self.fc_size = fc_size
        self.sequence_length = sequence_length
        self.dropout_p = dropout_p
        self.batch_size = batch_size
        self.optimizer_type = optimizer_type
        self.lr = lr        
        self.weight_decay = weight_decay
        self.sgd_momentum = sgd_momentum
        self.loss = loss
        self.bce_pos_class_weight = bce_pos_class_weight
        self.focal_alpha = focal_alpha
        self.focal_gamma = focal_gamma
        self.num_epochs = num_epochs
        self.cv_folds = cv_folds
        self.scheduler_t = scheduler_t
        
    def reshape_data_to_seq_length(self, data, seq_len):
        num_samples = data.shape[0]
        input_features = data.shape[1]
        num_batches = num_samples // seq_len
        data = data[:num_batches * seq_len] # truncate points that don't divide evenly
        reshaped_data = data.reshape(num_batches, seq_len, input_features)
        return reshaped_data

    def reshape_labels_to_seq_length(self, labels, seq_len):
        labels = torch.from_numpy(labels) if isinstance(labels, np.ndarray) else labels
        num_samples = labels.shape[0]
        num_batches = num_samples // seq_len
        labels = labels[:num_batches * seq_len] # truncate points that don't divide evenly
        labels = labels.view(num_batches, seq_len, -1)
        return labels
    
    def fit(self, X, y):

        cv_tss_values = []
        cv_hss_values = []

        tscv = TimeSeriesSplit(n_splits=self.cv_folds)
        for i, (train_index, val_index) in enumerate(tscv.split(X)):
            
            model = simple_timeSeries_CNN(cnn_filters=self.cnn_filters, 
                                          fc_size=self.fc_size, 
                                          dropout_p=self.dropout_p, 
                                          loss=self.loss, 
                                          sequence_length=self.sequence_length)
            model.to(device)
            
            if self.loss == 'bce':
                criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([self.bce_pos_class_weight]).to(device))
            elif self.loss == 'focal':
                criterion = FocalLoss(alpha=self.focal_alpha, gamma=self.focal_gamma)

            if self.optimizer_type == 'adam':
                optimizer = optim.Adam(model.parameters(), lr=self.lr, weight_decay=self.weight_decay)
            elif self.optimizer_type == 'sgd':
                optimizer = optim.SGD(model.parameters(), lr=self.lr, momentum=self.sgd_momentum, weight_decay=self.weight_decay)

            if self.scheduler_t > 0:
                scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=self.scheduler_t)
            else:
                scheduler = False

            X_train, X_val = X[train_index], X[val_index]
            y_train, y_val = y[train_index], y[val_index]
            
            scaler_X = RobustScaler()
            scaler_X = scaler_X.fit(X_train)

            X_train_scaled = scaler_X.transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            
            X_train_scaled = self.reshape_data_to_seq_length(X_train_scaled, self.sequence_length)
            X_val_scaled = self.reshape_data_to_seq_length(X_val_scaled, self.sequence_length)

            train_labels = self.reshape_labels_to_seq_length(y_train, self.sequence_length)
            val_labels = self.reshape_labels_to_seq_length(y_val, self.sequence_length)
            
            train_inputs = torch.tensor(X_train_scaled, dtype=torch.float32).transpose(1, 2)  # Shape: [batch_size, 15, 1]
            train_inputs = train_inputs.to(device)
            train_labels = train_labels.to(device)
            train_dataset = TensorDataset(train_inputs, train_labels)
            train_dataloader = DataLoader(train_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)

            val_inputs = torch.tensor(X_val_scaled, dtype=torch.float32).transpose(1, 2)  # Shape: [batch_size, 15, 1]
            val_inputs = val_inputs.to(device)
            val_labels = val_labels.to(device)
            val_dataset = TensorDataset(val_inputs, val_labels)
            val_dataloader = DataLoader(val_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)
            
            training_hss, validation_hss, training_tss, validation_tss = \
            train_model_with_cv(model, 
                 train_dataloader, val_dataloader, 
                 criterion, optimizer, scheduler,
                 num_epochs=self.num_epochs)
            cv_tss_values.append(validation_tss[-1])
            cv_hss_values.append(validation_hss[-1])

            if i == 0:
                total_params = sum(p.numel() for p in model.parameters())
                print(f'Total number of parameters: {total_params}')
                
            print(f"Fold {i}: train tss = {training_tss[-1]:.4f} : val tss = {validation_tss[-1]:.4f} ::: train hss = {training_hss[-1]:.4f} : val hss = {validation_hss[-1]:.4f}")
        
        return cv_hss_values, cv_tss_values

In [9]:
training_data_size = 50000

X_train, X_test, \
    y_train, y_test, \
        idx_train, idx_test = train_test_split(X_fSelect, y, range(len(y)), train_size=training_data_size, shuffle=False)

# ### small test
# param_grid = {
#     'cnn_filters': [256],   
#     'fc_size': [256, 1048],  
#     'sequence_length': [100],   
#     'dropout_p': [0.6],  
#     'batch_size': [64],  
#     'lr': [0.03],  
#     'optimizer_type': ['sgd'],  
#     'weight_decay':[0.05],  
#     'loss': ['bce'],
#     'bce_pos_class_weight': [35],  
#     'num_epochs': [20],  
#     'cv_folds': [5], 
# }

### strategic hypertune iteration 1
param_grid = {
    'cnn_filters': [16, 32],
    'fc_size': [64, 1048],
    'sequence_length': [15, 45],
    'dropout_p': [0.1, 0.5],
    'batch_size': [32, 512],
    'lr': [0.0001, 0.01],
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.0001, 0.01],
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 75],
#     'scheduler_t': [5],
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 2
param_grid = {
    'cnn_filters': [16, 64],
    'fc_size': [64, 1048],
    'sequence_length': [30, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [512, 1024],  ### changed
    'lr': [0.005, 0.03],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.001, 0.01],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 75],
#     'scheduler_t': [5],
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 3
param_grid = {
    'cnn_filters': [8, 16],  ### changed
    'fc_size': [128, 1536],  ### changed
    'sequence_length': [40, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [768, 1536],  ### changed
    'lr': [0.005, 0.01],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.001, 0.01],  
    'loss': ['bce'],
    'bce_pos_class_weight': [40, 65],  ### changed
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 4
param_grid = {
    'cnn_filters': [4, 8, 128],  ### changed, added 1 dimension
    'fc_size': [512, 2048],  ### changed
    'sequence_length': [15, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [1024, 2048],  ### changed
    'lr': [0.0005, 0.01],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.005, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [40, 65],  
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 5
param_grid = {
    'cnn_filters': [8, 64, 128],  ### changed
    'fc_size': [512, 2048],  
    'sequence_length': [15, 45],  
    'dropout_p': [0.1, 0.5],
    'batch_size': [128, 256],  ### changed
    'lr': [0.001, 0.025],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.005, 0.05],  
    'loss': ['bce'],
    'bce_pos_class_weight': [25, 50],  ### changed
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 6
param_grid = {
    'cnn_filters': [4, 8, 32],  ### changed
    'fc_size': [512, 1024],  ### changed
    'sequence_length': [30, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [128, 256],  
    'lr': [0.001, 0.025],  
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.005, 0.075],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 60],  ### changed
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 7
param_grid = {
    'cnn_filters': [4, 8, 16],  ### changed
    'fc_size': [512, 768],  ### changed
    'sequence_length': [15, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [128, 256],  
    'lr': [0.005, 0.025],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.01, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [45, 60],  ### changed
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 8
param_grid = {
    'cnn_filters': [8, 32, 64],  ### changed 
    'fc_size': [1024, 2560],  ### changed
    'sequence_length': [15, 45],  
    'dropout_p': [0.1, 0.25],  ### changed
    'batch_size': [128, 256],  
    'lr': [0.01, 0.025],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.05, 0.075],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [35, 55],  ### changed
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 9
param_grid = {
    'cnn_filters': [4, 8, 24],  ### changed
    'fc_size': [1024, 2560],  
    'sequence_length': [20, 45],  ### changed
    'dropout_p': [0.1, 0.35],  ### changed
    'batch_size': [128, 256],  
    'lr': [0.0075, 0.015],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.01, 0.025],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 60],  ### changed
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 10
param_grid = {
    'cnn_filters': [4, 8, 12],  ### changed
    'fc_size': [768, 1024],  ### changed
    'sequence_length': [20, 45],  
    'dropout_p': [0.05, 0.2],  ### changed
    'batch_size': [128, 256],  
    'lr': [0.0075, 0.015],  
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.025, 0.06],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [40, 70],  ### changed
    'num_epochs': [50],
    'cv_folds': [5], 
}

param_combinations = list(ParameterGrid(param_grid))

grid = pd.DataFrame()
tss_distributions = []
hss_distributions = []
mean_tss_scores = []
mean_hss_scores = []
for params in param_combinations:

    print(str(param_combinations.index(params)) + "/" + str(len(param_combinations)))
    print(params)

    cnn_time_series_classifier = CNNBinaryTimeSeriesClassifier(**params)
    cv_hss_values, cv_tss_values = cnn_time_series_classifier.fit(X_train, y_train)
    
    tss_distributions.append(cv_tss_values)
    hss_distributions.append(cv_hss_values)
    mean_cv_tss = sum(cv_tss_values)/len(cv_tss_values)
    mean_cv_hss = sum(cv_hss_values)/len(cv_hss_values)
    print(f"mean cv TSS: {mean_cv_tss:.4f}")
    print(f"mean cv HSS: {mean_cv_hss:.4f}")
    mean_tss_scores.append(mean_cv_tss)
    mean_hss_scores.append(mean_cv_hss)
    
    if params == param_combinations[0]:
        grid = pd.DataFrame(params, index=[0])
    else:
        grid = pd.concat([grid, pd.DataFrame([params])], ignore_index=True)

grid['tss'] = [round(num, 4) for num in mean_tss_scores]
grid['hss'] = [round(num, 4) for num in mean_hss_scores]
grid = grid.sort_values(by=['tss', 'hss'], ascending=False)
grid = grid.drop(columns=[col for col in ['num_epochs','cv_folds','loss','scheduler_t'] if col in grid.columns], axis=1)
grid.head(20)

0/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.6905 : val tss = -0.0261 ::: train hss = 0.2444 : val hss = -0.0116
Fold 1: train tss = 0.8327 : val tss = 0.1079 ::: train hss = 0.3659 : val hss = 0.0598
Fold 2: train tss = 0.6800 : val tss = 0.7256 ::: train hss = 0.2165 : val hss = 0.4379
Fold 3: train tss = 0.7608 : val tss = 0.1900 ::: train hss = 0.2491 : val hss = 0.0383
Fold 4: train tss = 0.7345 : val tss = 0.6415 ::: train hss = 0.2284 : val hss = 0.2074
mean cv TSS: 0.3278
mean cv HSS: 0.1464
1/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7793 : val tss = 0.1172 ::: train hss = 0.5088 : val hss = 0.0662
Fold 2: train tss = 0.7034 : val tss = 0.7110 ::: train hss = 0.1696 : val hss = 0.3168
Fold 3: train tss = 0.6462 : val tss = 0.1062 ::: train hss = 0.2256 : val hss = 0.0151
Fold 4: train tss = 0.7286 : val tss = 0.6899 ::: train hss = 0.2523 : val hss = 0.2810
mean cv TSS: 0.3249
mean cv HSS: 0.1358
2/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9430 : val tss = -0.0128 ::: train hss = 0.3889 : val hss = -0.0169
Fold 1: train tss = 0.8086 : val tss = 0.2551 ::: train hss = 0.3762 : val hss = 0.0936
Fold 2: train tss = 0.7680 : val tss = 0.6545 ::: train hss = 0.2484 : val hss = 0.2466
Fold 3: train tss = 0.8124 : val tss = 0.0662 ::: train hss = 0.2697 : val hss = 0.0880
Fold 4: train tss = 0.7609 : val tss = 0.6766 ::: train hss = 0.2396 : val hss = 0.2271
mean cv TSS: 0.3279
mean cv HSS: 0.1277
3/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.5469 : val tss = -0.0151 ::: train hss = 0.3838 : val hss = -0.0188
Fold 1: train tss = 0.7943 : val tss = 0.3432 ::: train hss = 0.3661 : val hss = 0.1252
Fold 2: train tss = 0.7141 : val tss = 0.6704 ::: train hss = 0.1406 : val hss = 0.2640
Fold 3: train tss = 0.7711 : val tss = 0.2614 ::: train hss = 0.2528 : val hss = 0.0488
Fold 4: train tss = 0.7731 : val tss = 0.6216 ::: train hss = 0.2574 : val hss = 0.1897
mean cv TSS: 0.3763
mean cv HSS: 0.1218
4/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.4981 : val tss = 0.0316 ::: train hss = 0.4331 : val hss = 0.0401
Fold 1: train tss = 0.8003 : val tss = 0.0191 ::: train hss = 0.4108 : val hss = 0.0085
Fold 2: train tss = 0.6546 : val tss = 0.7647 ::: train hss = 0.1942 : val hss = 0.4202
Fold 3: train tss = 0.7090 : val tss = 0.3618 ::: train hss = 0.1849 : val hss = 0.0469
Fold 4: train tss = 0.6292 : val tss = 0.6401 ::: train hss = 0.2015 : val hss = 0.2511
mean cv TSS: 0.3635
mean cv HSS: 0.1534
5/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6754 : val tss = 0.4071 ::: train hss = 0.1486 : val hss = 0.1669
Fold 2: train tss = 0.5977 : val tss = 0.6939 ::: train hss = 0.1148 : val hss = 0.2933
Fold 3: train tss = 0.7132 : val tss = 0.0528 ::: train hss = 0.2349 : val hss = 0.0203
Fold 4: train tss = 0.5609 : val tss = 0.6785 ::: train hss = 0.1100 : val hss = 0.2403
mean cv TSS: 0.3665
mean cv HSS: 0.1442
6/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7793 : val tss = 0.3345 ::: train hss = 0.4160 : val hss = 0.1272
Fold 2: train tss = 0.7164 : val tss = 0.7407 ::: train hss = 0.1959 : val hss = 0.3487
Fold 3: train tss = 0.7261 : val tss = 0.1354 ::: train hss = 0.1945 : val hss = 0.0241
Fold 4: train tss = 0.7475 : val tss = 0.7150 ::: train hss = 0.2313 : val hss = 0.3391
mean cv TSS: 0.3851
mean cv HSS: 0.1678
7/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7632 : val tss = 0.4530 ::: train hss = 0.3581 : val hss = 0.0902
Fold 2: train tss = 0.6703 : val tss = 0.7385 ::: train hss = 0.1534 : val hss = 0.3847
Fold 3: train tss = 0.7165 : val tss = 0.2734 ::: train hss = 0.2268 : val hss = 0.0849
Fold 4: train tss = 0.6277 : val tss = 0.6887 ::: train hss = 0.1682 : val hss = 0.2759
mean cv TSS: 0.4307
mean cv HSS: 0.1671
8/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.9375 : val tss = 0.3490 ::: train hss = 0.2622 : val hss = 0.2528
Fold 1: train tss = 0.7584 : val tss = 0.1948 ::: train hss = 0.4211 : val hss = 0.2471
Fold 2: train tss = 0.7256 : val tss = 0.6928 ::: train hss = 0.2164 : val hss = 0.3183
Fold 3: train tss = 0.6812 : val tss = 0.1435 ::: train hss = 0.2295 : val hss = 0.0361
Fold 4: train tss = 0.7026 : val tss = 0.5731 ::: train hss = 0.2202 : val hss = 0.1839
mean cv TSS: 0.3906
mean cv HSS: 0.2076
9/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.1000 : val tss = -0.0041 ::: train hss = 0.1818 : val hss = -0.0070
Fold 1: train tss = 0.4938 : val tss = 0.3822 ::: train hss = 0.2187 : val hss = 0.1916
Fold 2: train tss = 0.4751 : val tss = 0.6228 ::: train hss = 0.0855 : val hss = 0.2172
Fold 3: train tss = 0.6511 : val tss = 0.1447 ::: train hss = 0.1953 : val hss = 0.0445
Fold 4: train tss = 0.5424 : val tss = 0.6877 ::: train hss = 0.1187 : val hss = 0.2591
mean cv TSS: 0.3667
mean cv HSS: 0.1411
10/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9852 : val tss = -0.0211 ::: train hss = 0.2418 : val hss = -0.0205
Fold 1: train tss = 0.8040 : val tss = 0.3249 ::: train hss = 0.3741 : val hss = 0.1534
Fold 2: train tss = 0.7744 : val tss = 0.6636 ::: train hss = 0.2311 : val hss = 0.2470
Fold 3: train tss = 0.7528 : val tss = 0.0656 ::: train hss = 0.2864 : val hss = 0.0119
Fold 4: train tss = 0.7222 : val tss = 0.7303 ::: train hss = 0.2066 : val hss = 0.3246
mean cv TSS: 0.3527
mean cv HSS: 0.1433
11/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7830 : val tss = 0.2612 ::: train hss = 0.3766 : val hss = 0.1124
Fold 2: train tss = 0.6800 : val tss = 0.7611 ::: train hss = 0.2166 : val hss = 0.4180
Fold 3: train tss = 0.6606 : val tss = 0.5710 ::: train hss = 0.1668 : val hss = 0.0737
Fold 4: train tss = 0.6767 : val tss = 0.6475 ::: train hss = 0.1873 : val hss = 0.2520
mean cv TSS: 0.4482
mean cv HSS: 0.1712
12/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.3982 : val tss = 0.0028 ::: train hss = 0.3704 : val hss = 0.0050
Fold 1: train tss = 0.8014 : val tss = 0.2429 ::: train hss = 0.4618 : val hss = 0.2289
Fold 2: train tss = 0.6831 : val tss = 0.6658 ::: train hss = 0.1938 : val hss = 0.4241
Fold 3: train tss = 0.7168 : val tss = 0.0858 ::: train hss = 0.2456 : val hss = 0.0252
Fold 4: train tss = 0.6694 : val tss = 0.5892 ::: train hss = 0.1730 : val hss = 0.1719
mean cv TSS: 0.3173
mean cv HSS: 0.1710
13/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6819 : val tss = 0.3360 ::: train hss = 0.1469 : val hss = 0.1596
Fold 2: train tss = 0.4141 : val tss = 0.6578 ::: train hss = 0.0889 : val hss = 0.2579
Fold 3: train tss = 0.5751 : val tss = 0.0562 ::: train hss = 0.1147 : val hss = 0.0385
Fold 4: train tss = 0.4958 : val tss = 0.5579 ::: train hss = 0.0819 : val hss = 0.1409
mean cv TSS: 0.3216
mean cv HSS: 0.1194
14/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.1500 : val tss = 0.0000 ::: train hss = 0.2609 : val hss = 0.0000
Fold 1: train tss = 0.8544 : val tss = 0.2891 ::: train hss = 0.4721 : val hss = 0.1297
Fold 2: train tss = 0.7675 : val tss = 0.7463 ::: train hss = 0.2587 : val hss = 0.4618
Fold 3: train tss = 0.7487 : val tss = 0.2333 ::: train hss = 0.2239 : val hss = 0.0579
Fold 4: train tss = 0.7458 : val tss = 0.5798 ::: train hss = 0.2474 : val hss = 0.2237
mean cv TSS: 0.3697
mean cv HSS: 0.1746
15/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7263 : val tss = 0.4007 ::: train hss = 0.2742 : val hss = 0.0551
Fold 2: train tss = 0.6013 : val tss = 0.7224 ::: train hss = 0.1566 : val hss = 0.3593
Fold 3: train tss = 0.7313 : val tss = 0.4552 ::: train hss = 0.2385 : val hss = 0.0810
Fold 4: train tss = 0.6547 : val tss = 0.7602 ::: train hss = 0.1655 : val hss = 0.3969
mean cv TSS: 0.4677
mean cv HSS: 0.1785
16/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.5952 : val tss = 0.2278 ::: train hss = 0.3307 : val hss = 0.0997
Fold 1: train tss = 0.8303 : val tss = 0.3555 ::: train hss = 0.4475 : val hss = 0.1607
Fold 2: train tss = 0.7527 : val tss = 0.6965 ::: train hss = 0.2272 : val hss = 0.3950
Fold 3: train tss = 0.7687 : val tss = 0.3336 ::: train hss = 0.3168 : val hss = 0.0495
Fold 4: train tss = 0.7309 : val tss = 0.7068 ::: train hss = 0.2693 : val hss = 0.3321
mean cv TSS: 0.4640
mean cv HSS: 0.2074
17/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.6437 : val tss = 0.0739 ::: train hss = 0.3029 : val hss = 0.0632
Fold 1: train tss = 0.7519 : val tss = 0.3815 ::: train hss = 0.2943 : val hss = 0.1642
Fold 2: train tss = 0.4364 : val tss = 0.4022 ::: train hss = 0.1092 : val hss = 0.1645
Fold 3: train tss = 0.7169 : val tss = 0.1720 ::: train hss = 0.2291 : val hss = 0.0373
Fold 4: train tss = 0.6825 : val tss = 0.5222 ::: train hss = 0.1932 : val hss = 0.2175
mean cv TSS: 0.3104
mean cv HSS: 0.1294
18/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9446 : val tss = -0.0029 ::: train hss = 0.4498 : val hss = -0.0025
Fold 1: train tss = 0.8537 : val tss = 0.3946 ::: train hss = 0.3639 : val hss = 0.1798
Fold 2: train tss = 0.7947 : val tss = 0.7460 ::: train hss = 0.2122 : val hss = 0.3822
Fold 3: train tss = 0.7855 : val tss = 0.2861 ::: train hss = 0.3594 : val hss = 0.0760
Fold 4: train tss = 0.7418 : val tss = 0.7222 ::: train hss = 0.2177 : val hss = 0.3380
mean cv TSS: 0.4292
mean cv HSS: 0.1947
19/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7928 : val tss = 0.4715 ::: train hss = 0.4629 : val hss = 0.1647
Fold 2: train tss = 0.7197 : val tss = 0.6252 ::: train hss = 0.2063 : val hss = 0.2029
Fold 3: train tss = 0.7332 : val tss = 0.3389 ::: train hss = 0.2111 : val hss = 0.0699
Fold 4: train tss = 0.7432 : val tss = 0.6882 ::: train hss = 0.2197 : val hss = 0.2461
mean cv TSS: 0.4248
mean cv HSS: 0.1367
20/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.6840 : val tss = -0.0154 ::: train hss = 0.1638 : val hss = -0.0152
Fold 1: train tss = 0.7503 : val tss = 0.3852 ::: train hss = 0.4717 : val hss = 0.1598
Fold 2: train tss = 0.4030 : val tss = 0.6479 ::: train hss = 0.1232 : val hss = 0.2335
Fold 3: train tss = 0.7675 : val tss = 0.2429 ::: train hss = 0.2848 : val hss = 0.0426
Fold 4: train tss = 0.6604 : val tss = 0.6343 ::: train hss = 0.1817 : val hss = 0.2450
mean cv TSS: 0.3790
mean cv HSS: 0.1332
21/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.5484 : val tss = -0.0113 ::: train hss = 0.4986 : val hss = -0.0136
Fold 1: train tss = 0.5927 : val tss = 0.4164 ::: train hss = 0.1002 : val hss = 0.1388
Fold 2: train tss = 0.5370 : val tss = 0.6600 ::: train hss = 0.1022 : val hss = 0.2890
Fold 3: train tss = 0.7113 : val tss = 0.0153 ::: train hss = 0.2253 : val hss = 0.0067
Fold 4: train tss = 0.6392 : val tss = 0.6809 ::: train hss = 0.1762 : val hss = 0.2570
mean cv TSS: 0.3523
mean cv HSS: 0.1356
22/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 137573
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.8116 : val tss = 0.2831 ::: train hss = 0.4783 : val hss = 0.1097
Fold 2: train tss = 0.7480 : val tss = 0.6980 ::: train hss = 0.1929 : val hss = 0.3273
Fold 3: train tss = 0.7316 : val tss = 0.2950 ::: train hss = 0.2784 : val hss = 0.0858
Fold 4: train tss = 0.7580 : val tss = 0.6803 ::: train hss = 0.3046 : val hss = 0.2763
mean cv TSS: 0.3913
mean cv HSS: 0.1598
23/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.2498 : val tss = 0.0092 ::: train hss = 0.3700 : val hss = 0.0177
Fold 1: train tss = 0.7644 : val tss = 0.3594 ::: train hss = 0.3989 : val hss = 0.1904
Fold 2: train tss = 0.6846 : val tss = 0.7280 ::: train hss = 0.1572 : val hss = 0.3426
Fold 3: train tss = 0.7053 : val tss = 0.2435 ::: train hss = 0.1866 : val hss = 0.0734
Fold 4: train tss = 0.7261 : val tss = 0.7002 ::: train hss = 0.2614 : val hss = 0.2580
mean cv TSS: 0.4081
mean cv HSS: 0.1764
24/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.5423 : val tss = 0.1455 ::: train hss = 0.2283 : val hss = 0.1062
Fold 1: train tss = 0.7024 : val tss = 0.3596 ::: train hss = 0.4697 : val hss = 0.1033
Fold 2: train tss = 0.6875 : val tss = 0.7660 ::: train hss = 0.2430 : val hss = 0.4026
Fold 3: train tss = 0.6935 : val tss = 0.2313 ::: train hss = 0.2203 : val hss = 0.0358
Fold 4: train tss = 0.6278 : val tss = 0.6452 ::: train hss = 0.1670 : val hss = 0.2001
mean cv TSS: 0.4295
mean cv HSS: 0.1696
25/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.1492 : val tss = -0.0011 ::: train hss = 0.1989 : val hss = -0.0021
Fold 1: train tss = 0.5738 : val tss = 0.1953 ::: train hss = 0.1788 : val hss = 0.0396
Fold 2: train tss = 0.1309 : val tss = 0.3179 ::: train hss = 0.0798 : val hss = 0.2742
Fold 3: train tss = 0.6352 : val tss = 0.3833 ::: train hss = 0.1622 : val hss = 0.0688
Fold 4: train tss = 0.5890 : val tss = 0.6955 ::: train hss = 0.1519 : val hss = 0.2583
mean cv TSS: 0.3182
mean cv HSS: 0.1277
26/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.7911 : val tss = -0.0047 ::: train hss = 0.2877 : val hss = -0.0059
Fold 1: train tss = 0.8016 : val tss = 0.2642 ::: train hss = 0.4637 : val hss = 0.0963
Fold 2: train tss = 0.7695 : val tss = 0.6050 ::: train hss = 0.1985 : val hss = 0.2377
Fold 3: train tss = 0.7749 : val tss = 0.3707 ::: train hss = 0.2467 : val hss = 0.0691
Fold 4: train tss = 0.7247 : val tss = 0.6877 ::: train hss = 0.2122 : val hss = 0.3466
mean cv TSS: 0.3846
mean cv HSS: 0.1488
27/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7795 : val tss = 0.4159 ::: train hss = 0.4600 : val hss = 0.1496
Fold 2: train tss = 0.6890 : val tss = 0.7429 ::: train hss = 0.1478 : val hss = 0.3836
Fold 3: train tss = 0.6754 : val tss = 0.3684 ::: train hss = 0.2233 : val hss = 0.0772
Fold 4: train tss = 0.6782 : val tss = 0.6642 ::: train hss = 0.1919 : val hss = 0.2224
mean cv TSS: 0.4383
mean cv HSS: 0.1665
28/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.5982 : val tss = 0.0432 ::: train hss = 0.5091 : val hss = 0.0500
Fold 1: train tss = 0.7572 : val tss = 0.2724 ::: train hss = 0.2996 : val hss = 0.1773
Fold 2: train tss = 0.6105 : val tss = 0.5736 ::: train hss = 0.1211 : val hss = 0.2021
Fold 3: train tss = 0.6917 : val tss = 0.0983 ::: train hss = 0.2226 : val hss = 0.0272
Fold 4: train tss = 0.6566 : val tss = 0.6287 ::: train hss = 0.1615 : val hss = 0.2019
mean cv TSS: 0.3232
mean cv HSS: 0.1317
29/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.4470 : val tss = 0.0692 ::: train hss = 0.3311 : val hss = 0.0811
Fold 1: train tss = 0.6875 : val tss = 0.4092 ::: train hss = 0.1221 : val hss = 0.1606
Fold 2: train tss = 0.4468 : val tss = 0.6311 ::: train hss = 0.1038 : val hss = 0.2568
Fold 3: train tss = 0.5920 : val tss = 0.0785 ::: train hss = 0.1313 : val hss = 0.0196
Fold 4: train tss = 0.5978 : val tss = 0.5591 ::: train hss = 0.1065 : val hss = 0.1561
mean cv TSS: 0.3494
mean cv HSS: 0.1348
30/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.7480 : val tss = 0.0037 ::: train hss = 0.5753 : val hss = 0.0051
Fold 1: train tss = 0.7310 : val tss = 0.4009 ::: train hss = 0.2316 : val hss = 0.0635
Fold 2: train tss = 0.6968 : val tss = 0.6841 ::: train hss = 0.2031 : val hss = 0.2985
Fold 3: train tss = 0.7648 : val tss = 0.2008 ::: train hss = 0.2510 : val hss = 0.0384
Fold 4: train tss = 0.7177 : val tss = 0.7197 ::: train hss = 0.2232 : val hss = 0.2936
mean cv TSS: 0.4018
mean cv HSS: 0.1398
31/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7958 : val tss = 0.3053 ::: train hss = 0.4100 : val hss = 0.1391
Fold 2: train tss = 0.6757 : val tss = 0.7012 ::: train hss = 0.1543 : val hss = 0.3284
Fold 3: train tss = 0.6669 : val tss = 0.1068 ::: train hss = 0.1673 : val hss = 0.0360
Fold 4: train tss = 0.7237 : val tss = 0.7432 ::: train hss = 0.2029 : val hss = 0.4131
mean cv TSS: 0.3713
mean cv HSS: 0.1833
32/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.8827 : val tss = 0.0478 ::: train hss = 0.1940 : val hss = 0.0158
Fold 1: train tss = 0.7981 : val tss = 0.3577 ::: train hss = 0.4729 : val hss = 0.2251
Fold 2: train tss = 0.7399 : val tss = 0.6530 ::: train hss = 0.2567 : val hss = 0.2575
Fold 3: train tss = 0.7633 : val tss = 0.2625 ::: train hss = 0.3164 : val hss = 0.0465
Fold 4: train tss = 0.7161 : val tss = 0.6327 ::: train hss = 0.2796 : val hss = 0.2397
mean cv TSS: 0.3908
mean cv HSS: 0.1569
33/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 47180
Fold 0: train tss = 0.0500 : val tss = -0.0001 ::: train hss = 0.0952 : val hss = -0.0002
Fold 1: train tss = 0.7285 : val tss = 0.4239 ::: train hss = 0.2657 : val hss = 0.2039
Fold 2: train tss = 0.4735 : val tss = 0.4466 ::: train hss = 0.1867 : val hss = 0.3159
Fold 3: train tss = 0.6774 : val tss = 0.2959 ::: train hss = 0.2467 : val hss = 0.0726
Fold 4: train tss = 0.6809 : val tss = 0.4791 ::: train hss = 0.2424 : val hss = 0.2206
mean cv TSS: 0.3291
mean cv HSS: 0.1625
34/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.7939 : val tss = -0.0153 ::: train hss = 0.3650 : val hss = -0.0189
Fold 1: train tss = 0.8230 : val tss = 0.2955 ::: train hss = 0.4210 : val hss = 0.1062
Fold 2: train tss = 0.7686 : val tss = 0.6810 ::: train hss = 0.2325 : val hss = 0.3869
Fold 3: train tss = 0.7583 : val tss = 0.2859 ::: train hss = 0.2697 : val hss = 0.0695
Fold 4: train tss = 0.7320 : val tss = 0.6416 ::: train hss = 0.2637 : val hss = 0.2131
mean cv TSS: 0.3777
mean cv HSS: 0.1514
35/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8319 : val tss = 0.2309 ::: train hss = 0.4231 : val hss = 0.0977
Fold 2: train tss = 0.7167 : val tss = 0.6937 ::: train hss = 0.1826 : val hss = 0.2958
Fold 3: train tss = 0.7440 : val tss = 0.2127 ::: train hss = 0.2334 : val hss = 0.0685
Fold 4: train tss = 0.7260 : val tss = 0.7240 ::: train hss = 0.2202 : val hss = 0.3471
mean cv TSS: 0.3722
mean cv HSS: 0.1618
36/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.2977 : val tss = -0.0027 ::: train hss = 0.2646 : val hss = -0.0049
Fold 1: train tss = 0.7638 : val tss = 0.2259 ::: train hss = 0.3934 : val hss = 0.2718
Fold 2: train tss = 0.7194 : val tss = 0.7244 ::: train hss = 0.1930 : val hss = 0.3689
Fold 3: train tss = 0.7355 : val tss = 0.0809 ::: train hss = 0.2745 : val hss = 0.0519
Fold 4: train tss = 0.6958 : val tss = 0.6618 ::: train hss = 0.2133 : val hss = 0.2588
mean cv TSS: 0.3381
mean cv HSS: 0.1893
37/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7699 : val tss = 0.1669 ::: train hss = 0.4997 : val hss = 0.2377
Fold 2: train tss = 0.5617 : val tss = 0.7026 ::: train hss = 0.1263 : val hss = 0.3013
Fold 3: train tss = 0.6363 : val tss = 0.0935 ::: train hss = 0.1931 : val hss = 0.0270
Fold 4: train tss = 0.6192 : val tss = 0.6617 ::: train hss = 0.1442 : val hss = 0.2334
mean cv TSS: 0.3249
mean cv HSS: 0.1599
38/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5359 : val tss = 0.3035 ::: train hss = 0.3121 : val hss = 0.0891
Fold 2: train tss = 0.7594 : val tss = 0.7098 ::: train hss = 0.2052 : val hss = 0.3788
Fold 3: train tss = 0.7477 : val tss = 0.2743 ::: train hss = 0.2523 : val hss = 0.0710
Fold 4: train tss = 0.7306 : val tss = 0.7310 ::: train hss = 0.2477 : val hss = 0.3219
mean cv TSS: 0.4037
mean cv HSS: 0.1722
39/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7701 : val tss = 0.4344 ::: train hss = 0.3473 : val hss = 0.1153
Fold 2: train tss = 0.6511 : val tss = 0.7017 ::: train hss = 0.1492 : val hss = 0.2886
Fold 3: train tss = 0.7164 : val tss = 0.3548 ::: train hss = 0.2142 : val hss = 0.0832
Fold 4: train tss = 0.7270 : val tss = 0.7061 ::: train hss = 0.2405 : val hss = 0.2653
mean cv TSS: 0.4394
mean cv HSS: 0.1505
40/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.7736 : val tss = -0.0135 ::: train hss = 0.1214 : val hss = -0.0175
Fold 1: train tss = 0.7618 : val tss = 0.2061 ::: train hss = 0.2507 : val hss = 0.1051
Fold 2: train tss = 0.4991 : val tss = 0.6189 ::: train hss = 0.0938 : val hss = 0.2020
Fold 3: train tss = 0.6832 : val tss = 0.0698 ::: train hss = 0.2234 : val hss = 0.0210
Fold 4: train tss = 0.6944 : val tss = 0.6803 ::: train hss = 0.2393 : val hss = 0.2478
mean cv TSS: 0.3123
mean cv HSS: 0.1117
41/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.5027 : val tss = 0.3631 ::: train hss = 0.1451 : val hss = 0.1343
Fold 2: train tss = 0.4843 : val tss = 0.5889 ::: train hss = 0.1192 : val hss = 0.1924
Fold 3: train tss = 0.6686 : val tss = 0.1104 ::: train hss = 0.2383 : val hss = 0.0227
Fold 4: train tss = 0.4567 : val tss = 0.5569 ::: train hss = 0.0949 : val hss = 0.1391
mean cv TSS: 0.3239
mean cv HSS: 0.0977
42/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.6422 : val tss = -0.0237 ::: train hss = 0.2621 : val hss = -0.0219
Fold 1: train tss = 0.8025 : val tss = 0.2139 ::: train hss = 0.4736 : val hss = 0.0420
Fold 2: train tss = 0.7197 : val tss = 0.6579 ::: train hss = 0.1725 : val hss = 0.2426
Fold 3: train tss = 0.7364 : val tss = 0.1220 ::: train hss = 0.2208 : val hss = 0.0224
Fold 4: train tss = 0.7403 : val tss = 0.6591 ::: train hss = 0.1830 : val hss = 0.2554
mean cv TSS: 0.3258
mean cv HSS: 0.1081
43/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7823 : val tss = 0.2637 ::: train hss = 0.4919 : val hss = 0.1224
Fold 2: train tss = 0.7273 : val tss = 0.7368 ::: train hss = 0.2196 : val hss = 0.3376
Fold 3: train tss = 0.6987 : val tss = 0.2686 ::: train hss = 0.2071 : val hss = 0.0877
Fold 4: train tss = 0.7115 : val tss = 0.5066 ::: train hss = 0.1910 : val hss = 0.1208
mean cv TSS: 0.3552
mean cv HSS: 0.1337
44/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 47180
Fold 0: train tss = 0.0983 : val tss = -0.0043 ::: train hss = 0.1092 : val hss = -0.0062
Fold 1: train tss = 0.7507 : val tss = 0.1898 ::: train hss = 0.3922 : val hss = 0.1450
Fold 2: train tss = 0.6330 : val tss = 0.6422 ::: train hss = 0.1876 : val hss = 0.2498
Fold 3: train tss = 0.7412 : val tss = 0.2578 ::: train hss = 0.2913 : val hss = 0.0397
Fold 4: train tss = 0.6521 : val tss = 0.6754 ::: train hss = 0.1686 : val hss = 0.2501
mean cv TSS: 0.3522
mean cv HSS: 0.1357
45/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6911 : val tss = 0.3867 ::: train hss = 0.1435 : val hss = 0.2047
Fold 2: train tss = 0.5069 : val tss = 0.6955 ::: train hss = 0.0987 : val hss = 0.3459
Fold 3: train tss = 0.6539 : val tss = 0.2539 ::: train hss = 0.1767 : val hss = 0.0451
Fold 4: train tss = 0.6015 : val tss = 0.6986 ::: train hss = 0.1494 : val hss = 0.2982
mean cv TSS: 0.4069
mean cv HSS: 0.1788
46/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.0995 : val tss = -0.0025 ::: train hss = 0.1531 : val hss = -0.0045
Fold 1: train tss = 0.8170 : val tss = 0.3518 ::: train hss = 0.4447 : val hss = 0.1466
Fold 2: train tss = 0.7187 : val tss = 0.7196 ::: train hss = 0.2073 : val hss = 0.3588
Fold 3: train tss = 0.7367 : val tss = 0.1141 ::: train hss = 0.2284 : val hss = 0.0338
Fold 4: train tss = 0.7421 : val tss = 0.7509 ::: train hss = 0.2244 : val hss = 0.3818
mean cv TSS: 0.3868
mean cv HSS: 0.1833
47/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7872 : val tss = 0.2948 ::: train hss = 0.3479 : val hss = 0.1463
Fold 2: train tss = 0.6426 : val tss = 0.6986 ::: train hss = 0.1499 : val hss = 0.2933
Fold 3: train tss = 0.6440 : val tss = 0.2514 ::: train hss = 0.1875 : val hss = 0.0439
Fold 4: train tss = 0.6988 : val tss = 0.7767 ::: train hss = 0.1902 : val hss = 0.3992
mean cv TSS: 0.4043
mean cv HSS: 0.1765
48/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.8381 : val tss = -0.0283 ::: train hss = 0.2465 : val hss = -0.0191
Fold 1: train tss = 0.7789 : val tss = 0.2441 ::: train hss = 0.5033 : val hss = 0.2984
Fold 2: train tss = 0.7050 : val tss = 0.6988 ::: train hss = 0.2532 : val hss = 0.3574
Fold 3: train tss = 0.6940 : val tss = 0.0603 ::: train hss = 0.2348 : val hss = 0.0095
Fold 4: train tss = 0.6827 : val tss = 0.6202 ::: train hss = 0.1764 : val hss = 0.1979
mean cv TSS: 0.3190
mean cv HSS: 0.1688
49/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = -0.0001 ::: train hss = 0.0000 : val hss = -0.0002
Fold 1: train tss = 0.7855 : val tss = 0.0733 ::: train hss = 0.3647 : val hss = 0.0215
Fold 2: train tss = 0.5816 : val tss = 0.6815 ::: train hss = 0.1246 : val hss = 0.2762
Fold 3: train tss = 0.7109 : val tss = 0.0108 ::: train hss = 0.3119 : val hss = 0.0026
Fold 4: train tss = 0.6869 : val tss = 0.6759 ::: train hss = 0.2092 : val hss = 0.2622
mean cv TSS: 0.2883
mean cv HSS: 0.1124
50/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.8421 : val tss = -0.0254 ::: train hss = 0.3270 : val hss = -0.0228
Fold 1: train tss = 0.8528 : val tss = 0.2965 ::: train hss = 0.3858 : val hss = 0.0826
Fold 2: train tss = 0.7447 : val tss = 0.5781 ::: train hss = 0.2128 : val hss = 0.1731
Fold 3: train tss = 0.7867 : val tss = 0.2755 ::: train hss = 0.2536 : val hss = 0.0876
Fold 4: train tss = 0.7320 : val tss = 0.6384 ::: train hss = 0.2029 : val hss = 0.2633
mean cv TSS: 0.3526
mean cv HSS: 0.1168
51/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7855 : val tss = 0.3407 ::: train hss = 0.3647 : val hss = 0.1249
Fold 2: train tss = 0.7184 : val tss = 0.7411 ::: train hss = 0.1871 : val hss = 0.3513
Fold 3: train tss = 0.7692 : val tss = 0.1277 ::: train hss = 0.2786 : val hss = 0.0504
Fold 4: train tss = 0.7709 : val tss = 0.6357 ::: train hss = 0.2448 : val hss = 0.2575
mean cv TSS: 0.3691
mean cv HSS: 0.1568
52/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.2475 : val tss = -0.0053 ::: train hss = 0.2152 : val hss = -0.0087
Fold 1: train tss = 0.7989 : val tss = 0.2143 ::: train hss = 0.4370 : val hss = 0.2833
Fold 2: train tss = 0.6775 : val tss = 0.7109 ::: train hss = 0.1949 : val hss = 0.3166
Fold 3: train tss = 0.7092 : val tss = 0.0517 ::: train hss = 0.2302 : val hss = 0.0225
Fold 4: train tss = 0.6968 : val tss = 0.7139 ::: train hss = 0.2194 : val hss = 0.2981
mean cv TSS: 0.3371
mean cv HSS: 0.1823
53/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.3478 : val tss = 0.1195 ::: train hss = 0.3092 : val hss = 0.1565
Fold 1: train tss = 0.7508 : val tss = 0.4437 ::: train hss = 0.2716 : val hss = 0.1952
Fold 2: train tss = 0.6499 : val tss = 0.6958 ::: train hss = 0.1595 : val hss = 0.3483
Fold 3: train tss = 0.6334 : val tss = 0.1722 ::: train hss = 0.1877 : val hss = 0.0480
Fold 4: train tss = 0.6485 : val tss = 0.7133 ::: train hss = 0.1881 : val hss = 0.3164
mean cv TSS: 0.4289
mean cv HSS: 0.2129
54/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7806 : val tss = 0.3178 ::: train hss = 0.3907 : val hss = 0.1098
Fold 2: train tss = 0.7742 : val tss = 0.7262 ::: train hss = 0.2275 : val hss = 0.3437
Fold 3: train tss = 0.7193 : val tss = 0.2643 ::: train hss = 0.2316 : val hss = 0.0624
Fold 4: train tss = 0.7275 : val tss = 0.7392 ::: train hss = 0.2280 : val hss = 0.4259
mean cv TSS: 0.4095
mean cv HSS: 0.1884
55/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7559 : val tss = 0.2892 ::: train hss = 0.2939 : val hss = 0.1384
Fold 2: train tss = 0.6014 : val tss = 0.6735 ::: train hss = 0.1667 : val hss = 0.2648
Fold 3: train tss = 0.7164 : val tss = 0.3646 ::: train hss = 0.2345 : val hss = 0.1023
Fold 4: train tss = 0.6958 : val tss = 0.6281 ::: train hss = 0.2200 : val hss = 0.2465
mean cv TSS: 0.3911
mean cv HSS: 0.1504
56/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.7202 : val tss = -0.0666 ::: train hss = 0.1022 : val hss = -0.0270
Fold 1: train tss = 0.6964 : val tss = 0.3280 ::: train hss = 0.1165 : val hss = 0.0978
Fold 2: train tss = 0.4094 : val tss = 0.6813 ::: train hss = 0.1050 : val hss = 0.2772
Fold 3: train tss = 0.7188 : val tss = 0.2992 ::: train hss = 0.2735 : val hss = 0.0827
Fold 4: train tss = 0.6424 : val tss = 0.6499 ::: train hss = 0.1624 : val hss = 0.2402
mean cv TSS: 0.3783
mean cv HSS: 0.1342
57/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0999 : val tss = -0.0041 ::: train hss = 0.1737 : val hss = -0.0070
Fold 1: train tss = 0.3007 : val tss = 0.2287 ::: train hss = 0.0867 : val hss = 0.0587
Fold 2: train tss = 0.0374 : val tss = 0.1632 ::: train hss = 0.0394 : val hss = 0.1704
Fold 3: train tss = 0.5172 : val tss = 0.2426 ::: train hss = 0.1232 : val hss = 0.0425
Fold 4: train tss = 0.5293 : val tss = 0.6734 ::: train hss = 0.1433 : val hss = 0.2251
mean cv TSS: 0.2607
mean cv HSS: 0.0979
58/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.4923 : val tss = -0.0034 ::: train hss = 0.2095 : val hss = -0.0061
Fold 1: train tss = 0.8747 : val tss = 0.0411 ::: train hss = 0.4207 : val hss = 0.0110
Fold 2: train tss = 0.6672 : val tss = 0.6607 ::: train hss = 0.1583 : val hss = 0.2463
Fold 3: train tss = 0.7384 : val tss = 0.2128 ::: train hss = 0.2374 : val hss = 0.0367
Fold 4: train tss = 0.7107 : val tss = 0.6981 ::: train hss = 0.2027 : val hss = 0.2596
mean cv TSS: 0.3219
mean cv HSS: 0.1095
59/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.6466 : val tss = 0.7023 ::: train hss = 0.1795 : val hss = 0.2979
Fold 3: train tss = 0.6976 : val tss = 0.3644 ::: train hss = 0.2339 : val hss = 0.0740
Fold 4: train tss = 0.6924 : val tss = 0.6767 ::: train hss = 0.1757 : val hss = 0.2364
mean cv TSS: 0.3487
mean cv HSS: 0.1217
60/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.5448 : val tss = -0.0080 ::: train hss = 0.2945 : val hss = -0.0104
Fold 1: train tss = 0.7091 : val tss = 0.1870 ::: train hss = 0.1784 : val hss = 0.1488
Fold 2: train tss = 0.5040 : val tss = 0.7429 ::: train hss = 0.0694 : val hss = 0.3663
Fold 3: train tss = 0.6724 : val tss = 0.2774 ::: train hss = 0.2076 : val hss = 0.0282
Fold 4: train tss = 0.6552 : val tss = 0.6982 ::: train hss = 0.1987 : val hss = 0.2572
mean cv TSS: 0.3795
mean cv HSS: 0.1580
61/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.1993 : val tss = -0.0023 ::: train hss = 0.2657 : val hss = -0.0043
Fold 1: train tss = 0.5862 : val tss = 0.4241 ::: train hss = 0.0927 : val hss = 0.1074
Fold 2: train tss = 0.4135 : val tss = 0.6936 ::: train hss = 0.0753 : val hss = 0.3079
Fold 3: train tss = 0.6410 : val tss = 0.3318 ::: train hss = 0.1555 : val hss = 0.0407
Fold 4: train tss = 0.5743 : val tss = 0.4719 ::: train hss = 0.1120 : val hss = 0.1052
mean cv TSS: 0.3838
mean cv HSS: 0.1114
62/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.4996 : val tss = -0.0023 ::: train hss = 0.6056 : val hss = -0.0043
Fold 1: train tss = 0.7807 : val tss = 0.2431 ::: train hss = 0.5277 : val hss = 0.0983
Fold 2: train tss = 0.7424 : val tss = 0.7083 ::: train hss = 0.1895 : val hss = 0.3264
Fold 3: train tss = 0.7581 : val tss = 0.1538 ::: train hss = 0.2474 : val hss = 0.0334
Fold 4: train tss = 0.6983 : val tss = 0.7060 ::: train hss = 0.2188 : val hss = 0.3273
mean cv TSS: 0.3618
mean cv HSS: 0.1562
63/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7612 : val tss = 0.4418 ::: train hss = 0.4078 : val hss = 0.0964
Fold 2: train tss = 0.7015 : val tss = 0.5711 ::: train hss = 0.1588 : val hss = 0.4621
Fold 3: train tss = 0.7674 : val tss = 0.3520 ::: train hss = 0.2963 : val hss = 0.0953
Fold 4: train tss = 0.7358 : val tss = 0.7133 ::: train hss = 0.2305 : val hss = 0.2966
mean cv TSS: 0.4156
mean cv HSS: 0.1901
64/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.7458 : val tss = 0.2131 ::: train hss = 0.4262 : val hss = 0.2060
Fold 1: train tss = 0.8137 : val tss = 0.4433 ::: train hss = 0.3294 : val hss = 0.3245
Fold 2: train tss = 0.7271 : val tss = 0.7266 ::: train hss = 0.3143 : val hss = 0.4037
Fold 3: train tss = 0.7793 : val tss = 0.0843 ::: train hss = 0.3006 : val hss = 0.0400
Fold 4: train tss = 0.7481 : val tss = 0.6298 ::: train hss = 0.2401 : val hss = 0.2368
mean cv TSS: 0.4194
mean cv HSS: 0.2422
65/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.4959 : val tss = 0.0730 ::: train hss = 0.3099 : val hss = 0.0941
Fold 1: train tss = 0.7461 : val tss = 0.3094 ::: train hss = 0.3304 : val hss = 0.1743
Fold 2: train tss = 0.5884 : val tss = 0.7461 ::: train hss = 0.1903 : val hss = 0.4251
Fold 3: train tss = 0.6840 : val tss = 0.0081 ::: train hss = 0.2284 : val hss = 0.0037
Fold 4: train tss = 0.6892 : val tss = 0.5668 ::: train hss = 0.2350 : val hss = 0.2460
mean cv TSS: 0.3407
mean cv HSS: 0.1886
66/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 171357
Fold 0: train tss = 0.9931 : val tss = -0.0043 ::: train hss = 0.4095 : val hss = -0.0062
Fold 1: train tss = 0.8638 : val tss = 0.1841 ::: train hss = 0.4378 : val hss = 0.1530
Fold 2: train tss = 0.8227 : val tss = 0.6755 ::: train hss = 0.2742 : val hss = 0.2658
Fold 3: train tss = 0.8068 : val tss = 0.3058 ::: train hss = 0.3113 : val hss = 0.1296
Fold 4: train tss = 0.7591 : val tss = 0.7478 ::: train hss = 0.2399 : val hss = 0.3254
mean cv TSS: 0.3818
mean cv HSS: 0.1735
67/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8158 : val tss = 0.3884 ::: train hss = 0.3980 : val hss = 0.1639
Fold 2: train tss = 0.7491 : val tss = 0.7265 ::: train hss = 0.2472 : val hss = 0.3166
Fold 3: train tss = 0.7484 : val tss = 0.0605 ::: train hss = 0.2416 : val hss = 0.0202
Fold 4: train tss = 0.7262 : val tss = 0.6833 ::: train hss = 0.2393 : val hss = 0.2371
mean cv TSS: 0.3717
mean cv HSS: 0.1476
68/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.6984 : val tss = 0.0198 ::: train hss = 0.5944 : val hss = 0.0275
Fold 1: train tss = 0.7815 : val tss = 0.2178 ::: train hss = 0.3663 : val hss = 0.1614
Fold 2: train tss = 0.7661 : val tss = 0.7590 ::: train hss = 0.2908 : val hss = 0.3742
Fold 3: train tss = 0.7715 : val tss = 0.0253 ::: train hss = 0.2612 : val hss = 0.0055
Fold 4: train tss = 0.7693 : val tss = 0.6758 ::: train hss = 0.2624 : val hss = 0.2648
mean cv TSS: 0.3395
mean cv HSS: 0.1667
69/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.2998 : val tss = -0.0005 ::: train hss = 0.4282 : val hss = -0.0010
Fold 1: train tss = 0.7431 : val tss = 0.2735 ::: train hss = 0.2742 : val hss = 0.1744
Fold 2: train tss = 0.7064 : val tss = 0.7136 ::: train hss = 0.2446 : val hss = 0.5051
Fold 3: train tss = 0.7228 : val tss = 0.1735 ::: train hss = 0.2715 : val hss = 0.0312
Fold 4: train tss = 0.6979 : val tss = 0.5900 ::: train hss = 0.2200 : val hss = 0.1731
mean cv TSS: 0.3500
mean cv HSS: 0.1766
70/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0049 ::: train hss = 0.0952 : val hss = 0.0096
Fold 1: train tss = 0.7981 : val tss = 0.4054 ::: train hss = 0.3937 : val hss = 0.1326
Fold 2: train tss = 0.7974 : val tss = 0.7466 ::: train hss = 0.2788 : val hss = 0.3428
Fold 3: train tss = 0.7884 : val tss = 0.1941 ::: train hss = 0.2922 : val hss = 0.0698
Fold 4: train tss = 0.7867 : val tss = 0.7456 ::: train hss = 0.3020 : val hss = 0.3119
mean cv TSS: 0.4193
mean cv HSS: 0.1734
71/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7791 : val tss = 0.3170 ::: train hss = 0.4144 : val hss = 0.1294
Fold 2: train tss = 0.6943 : val tss = 0.6486 ::: train hss = 0.1990 : val hss = 0.2474
Fold 3: train tss = 0.7771 : val tss = 0.2096 ::: train hss = 0.2744 : val hss = 0.0825
Fold 4: train tss = 0.7239 : val tss = 0.7589 ::: train hss = 0.2453 : val hss = 0.3539
mean cv TSS: 0.3868
mean cv HSS: 0.1626
72/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.4314 : val tss = -0.0164 ::: train hss = 0.0943 : val hss = -0.0053
Fold 1: train tss = 0.7505 : val tss = 0.2933 ::: train hss = 0.2706 : val hss = 0.1806
Fold 2: train tss = 0.6085 : val tss = 0.6868 ::: train hss = 0.1340 : val hss = 0.3116
Fold 3: train tss = 0.7561 : val tss = 0.2518 ::: train hss = 0.2960 : val hss = 0.0537
Fold 4: train tss = 0.6704 : val tss = 0.6355 ::: train hss = 0.2010 : val hss = 0.2438
mean cv TSS: 0.3702
mean cv HSS: 0.1569
73/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.4957 : val tss = 0.0291 ::: train hss = 0.3004 : val hss = 0.0232
Fold 1: train tss = 0.6183 : val tss = 0.3271 ::: train hss = 0.2120 : val hss = 0.0741
Fold 2: train tss = 0.0640 : val tss = 0.2055 ::: train hss = 0.0480 : val hss = 0.2017
Fold 3: train tss = 0.6200 : val tss = 0.4325 ::: train hss = 0.1581 : val hss = 0.0365
Fold 4: train tss = 0.5490 : val tss = 0.6180 ::: train hss = 0.1209 : val hss = 0.1883
mean cv TSS: 0.3224
mean cv HSS: 0.1048
74/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.8883 : val tss = 0.0175 ::: train hss = 0.2632 : val hss = 0.0230
Fold 1: train tss = 0.8233 : val tss = 0.3968 ::: train hss = 0.4641 : val hss = 0.1462
Fold 2: train tss = 0.7993 : val tss = 0.6660 ::: train hss = 0.2625 : val hss = 0.4125
Fold 3: train tss = 0.7742 : val tss = 0.3121 ::: train hss = 0.2553 : val hss = 0.0534
Fold 4: train tss = 0.7388 : val tss = 0.6987 ::: train hss = 0.2312 : val hss = 0.2528
mean cv TSS: 0.4182
mean cv HSS: 0.1776
75/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7666 : val tss = 0.3042 ::: train hss = 0.3820 : val hss = 0.1406
Fold 2: train tss = 0.6788 : val tss = 0.7589 ::: train hss = 0.2027 : val hss = 0.4061
Fold 3: train tss = 0.7185 : val tss = 0.3167 ::: train hss = 0.2494 : val hss = 0.0868
Fold 4: train tss = 0.7047 : val tss = 0.6874 ::: train hss = 0.2040 : val hss = 0.2488
mean cv TSS: 0.4134
mean cv HSS: 0.1765
76/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.6965 : val tss = 0.0163 ::: train hss = 0.4422 : val hss = 0.0207
Fold 1: train tss = 0.7533 : val tss = 0.2625 ::: train hss = 0.4574 : val hss = 0.2942
Fold 2: train tss = 0.7114 : val tss = 0.7283 ::: train hss = 0.2567 : val hss = 0.3567
Fold 3: train tss = 0.6937 : val tss = 0.3725 ::: train hss = 0.2051 : val hss = 0.0385
Fold 4: train tss = 0.6649 : val tss = 0.7011 ::: train hss = 0.1759 : val hss = 0.2694
mean cv TSS: 0.4161
mean cv HSS: 0.1959
77/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 78404
Fold 0: train tss = 0.2970 : val tss = -0.0184 ::: train hss = 0.2329 : val hss = -0.0211
Fold 1: train tss = 0.6955 : val tss = 0.4141 ::: train hss = 0.1553 : val hss = 0.1554
Fold 2: train tss = 0.5689 : val tss = 0.7088 ::: train hss = 0.1275 : val hss = 0.3966
Fold 3: train tss = 0.6758 : val tss = 0.0774 ::: train hss = 0.1818 : val hss = 0.0191
Fold 4: train tss = 0.5539 : val tss = 0.5758 ::: train hss = 0.1180 : val hss = 0.1538
mean cv TSS: 0.3515
mean cv HSS: 0.1407
78/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.3500 : val tss = 0.0000 ::: train hss = 0.5185 : val hss = 0.0000
Fold 1: train tss = 0.6973 : val tss = 0.3818 ::: train hss = 0.1522 : val hss = 0.0450
Fold 2: train tss = 0.7619 : val tss = 0.7356 ::: train hss = 0.2230 : val hss = 0.3936
Fold 3: train tss = 0.7158 : val tss = 0.5236 ::: train hss = 0.2221 : val hss = 0.0571
Fold 4: train tss = 0.7521 : val tss = 0.7102 ::: train hss = 0.2293 : val hss = 0.2752
mean cv TSS: 0.4702
mean cv HSS: 0.1542
79/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7230 : val tss = 0.3156 ::: train hss = 0.2323 : val hss = 0.0646
Fold 2: train tss = 0.4920 : val tss = 0.6185 ::: train hss = 0.1197 : val hss = 0.2424
Fold 3: train tss = 0.7421 : val tss = 0.3534 ::: train hss = 0.2503 : val hss = 0.0971
Fold 4: train tss = 0.6813 : val tss = 0.5932 ::: train hss = 0.2070 : val hss = 0.1677
mean cv TSS: 0.3761
mean cv HSS: 0.1144
80/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.6919 : val tss = 0.0485 ::: train hss = 0.2740 : val hss = 0.0566
Fold 1: train tss = 0.8228 : val tss = 0.1840 ::: train hss = 0.4592 : val hss = 0.0974
Fold 2: train tss = 0.7523 : val tss = 0.6617 ::: train hss = 0.3182 : val hss = 0.3166
Fold 3: train tss = 0.7991 : val tss = 0.0231 ::: train hss = 0.3544 : val hss = 0.0138
Fold 4: train tss = 0.7747 : val tss = 0.6854 ::: train hss = 0.2674 : val hss = 0.3406
mean cv TSS: 0.3205
mean cv HSS: 0.1650
81/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.5461 : val tss = 0.2435 ::: train hss = 0.3468 : val hss = 0.2342
Fold 1: train tss = 0.8160 : val tss = 0.2332 ::: train hss = 0.4790 : val hss = 0.2678
Fold 2: train tss = 0.3249 : val tss = 0.3392 ::: train hss = 0.2117 : val hss = 0.2951
Fold 3: train tss = 0.7284 : val tss = 0.0703 ::: train hss = 0.2457 : val hss = 0.0268
Fold 4: train tss = 0.7158 : val tss = 0.6481 ::: train hss = 0.2123 : val hss = 0.2296
mean cv TSS: 0.3069
mean cv HSS: 0.2107
82/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9852 : val tss = -0.0174 ::: train hss = 0.2418 : val hss = -0.0204
Fold 1: train tss = 0.8841 : val tss = 0.3927 ::: train hss = 0.4658 : val hss = 0.2807
Fold 2: train tss = 0.8060 : val tss = 0.6808 ::: train hss = 0.1979 : val hss = 0.4024
Fold 3: train tss = 0.8263 : val tss = 0.1269 ::: train hss = 0.3454 : val hss = 0.0392
Fold 4: train tss = 0.7469 : val tss = 0.7167 ::: train hss = 0.2405 : val hss = 0.3668
mean cv TSS: 0.3800
mean cv HSS: 0.2137
83/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.6434 : val tss = -0.0019 ::: train hss = 0.2924 : val hss = -0.0020
Fold 1: train tss = 0.8204 : val tss = 0.2470 ::: train hss = 0.5333 : val hss = 0.1501
Fold 2: train tss = 0.7442 : val tss = 0.6892 ::: train hss = 0.2177 : val hss = 0.2862
Fold 3: train tss = 0.8044 : val tss = 0.3431 ::: train hss = 0.3141 : val hss = 0.0638
Fold 4: train tss = 0.7352 : val tss = 0.6724 ::: train hss = 0.2239 : val hss = 0.2325
mean cv TSS: 0.3900
mean cv HSS: 0.1461
84/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.5986 : val tss = -0.0042 ::: train hss = 0.5441 : val hss = -0.0072
Fold 1: train tss = 0.8071 : val tss = 0.3325 ::: train hss = 0.4763 : val hss = 0.1688
Fold 2: train tss = 0.6706 : val tss = 0.6791 ::: train hss = 0.2309 : val hss = 0.3175
Fold 3: train tss = 0.7999 : val tss = 0.0869 ::: train hss = 0.2914 : val hss = 0.0258
Fold 4: train tss = 0.7466 : val tss = 0.7385 ::: train hss = 0.2708 : val hss = 0.3505
mean cv TSS: 0.3666
mean cv HSS: 0.1711
85/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.3981 : val tss = -0.0048 ::: train hss = 0.3619 : val hss = -0.0080
Fold 1: train tss = 0.7929 : val tss = 0.2556 ::: train hss = 0.5154 : val hss = 0.2280
Fold 2: train tss = 0.7094 : val tss = 0.7427 ::: train hss = 0.1878 : val hss = 0.3640
Fold 3: train tss = 0.6778 : val tss = 0.0999 ::: train hss = 0.1995 : val hss = 0.0218
Fold 4: train tss = 0.6718 : val tss = 0.6863 ::: train hss = 0.1987 : val hss = 0.2431
mean cv TSS: 0.3559
mean cv HSS: 0.1698
86/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.2500 : val tss = 0.0000 ::: train hss = 0.4000 : val hss = 0.0000
Fold 1: train tss = 0.7860 : val tss = 0.2905 ::: train hss = 0.4839 : val hss = 0.1054
Fold 2: train tss = 0.7942 : val tss = 0.7211 ::: train hss = 0.3037 : val hss = 0.3786
Fold 3: train tss = 0.7910 : val tss = 0.1277 ::: train hss = 0.2959 : val hss = 0.0445
Fold 4: train tss = 0.7776 : val tss = 0.7880 ::: train hss = 0.2838 : val hss = 0.4189
mean cv TSS: 0.3855
mean cv HSS: 0.1895
87/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7695 : val tss = 0.4293 ::: train hss = 0.3721 : val hss = 0.1383
Fold 2: train tss = 0.7335 : val tss = 0.7374 ::: train hss = 0.1905 : val hss = 0.3573
Fold 3: train tss = 0.7469 : val tss = 0.2803 ::: train hss = 0.2781 : val hss = 0.0944
Fold 4: train tss = 0.7204 : val tss = 0.7311 ::: train hss = 0.2225 : val hss = 0.3885
mean cv TSS: 0.4356
mean cv HSS: 0.1957
88/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 104260
Fold 0: train tss = 0.9375 : val tss = 0.1797 ::: train hss = 0.2622 : val hss = 0.2030
Fold 1: train tss = 0.7667 : val tss = 0.1816 ::: train hss = 0.3829 : val hss = 0.1203
Fold 2: train tss = 0.5312 : val tss = 0.6104 ::: train hss = 0.1067 : val hss = 0.2129
Fold 3: train tss = 0.7471 : val tss = 0.4517 ::: train hss = 0.2928 : val hss = 0.0836
Fold 4: train tss = 0.7430 : val tss = 0.7073 ::: train hss = 0.2416 : val hss = 0.3190
mean cv TSS: 0.4261
mean cv HSS: 0.1878
89/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.5889 : val tss = 0.3409 ::: train hss = 0.1864 : val hss = 0.1444
Fold 2: train tss = 0.4284 : val tss = 0.7131 ::: train hss = 0.0804 : val hss = 0.3149
Fold 3: train tss = 0.6699 : val tss = 0.0530 ::: train hss = 0.2105 : val hss = 0.0094
Fold 4: train tss = 0.6528 : val tss = 0.7030 ::: train hss = 0.1815 : val hss = 0.2956
mean cv TSS: 0.3620
mean cv HSS: 0.1529
90/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.5937 : val tss = -0.0251 ::: train hss = 0.2827 : val hss = -0.0207
Fold 1: train tss = 0.8292 : val tss = 0.3127 ::: train hss = 0.4373 : val hss = 0.1372
Fold 2: train tss = 0.7726 : val tss = 0.6448 ::: train hss = 0.2132 : val hss = 0.2405
Fold 3: train tss = 0.7537 : val tss = 0.3181 ::: train hss = 0.2206 : val hss = 0.0977
Fold 4: train tss = 0.7241 : val tss = 0.7400 ::: train hss = 0.1989 : val hss = 0.3130
mean cv TSS: 0.3981
mean cv HSS: 0.1535
91/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0180 : val tss = -0.0001 ::: train hss = 0.0350 : val hss = -0.0002
Fold 2: train tss = 0.6998 : val tss = 0.6937 ::: train hss = 0.1750 : val hss = 0.2757
Fold 3: train tss = 0.7253 : val tss = 0.2805 ::: train hss = 0.2067 : val hss = 0.0851
Fold 4: train tss = 0.6220 : val tss = 0.6481 ::: train hss = 0.1609 : val hss = 0.2273
mean cv TSS: 0.3244
mean cv HSS: 0.1176
92/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.5461 : val tss = -0.0066 ::: train hss = 0.3468 : val hss = -0.0070
Fold 1: train tss = 0.7744 : val tss = 0.4200 ::: train hss = 0.4516 : val hss = 0.2578
Fold 2: train tss = 0.6970 : val tss = 0.7077 ::: train hss = 0.2628 : val hss = 0.3326
Fold 3: train tss = 0.7045 : val tss = 0.0505 ::: train hss = 0.2316 : val hss = 0.0167
Fold 4: train tss = 0.6551 : val tss = 0.6148 ::: train hss = 0.1520 : val hss = 0.2204
mean cv TSS: 0.3573
mean cv HSS: 0.1641
93/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6876 : val tss = 0.4029 ::: train hss = 0.1680 : val hss = 0.1285
Fold 2: train tss = 0.4672 : val tss = 0.6605 ::: train hss = 0.1252 : val hss = 0.2584
Fold 3: train tss = 0.6444 : val tss = 0.3157 ::: train hss = 0.1858 : val hss = 0.0786
Fold 4: train tss = 0.6045 : val tss = 0.5151 ::: train hss = 0.1305 : val hss = 0.1226
mean cv TSS: 0.3788
mean cv HSS: 0.1176
94/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.2000 : val tss = -0.0001 ::: train hss = 0.3333 : val hss = -0.0002
Fold 1: train tss = 0.8438 : val tss = 0.3467 ::: train hss = 0.4532 : val hss = 0.1309
Fold 2: train tss = 0.8103 : val tss = 0.7291 ::: train hss = 0.2815 : val hss = 0.3500
Fold 3: train tss = 0.7964 : val tss = 0.3338 ::: train hss = 0.2640 : val hss = 0.0905
Fold 4: train tss = 0.7893 : val tss = 0.6691 ::: train hss = 0.2539 : val hss = 0.2676
mean cv TSS: 0.4157
mean cv HSS: 0.1678
95/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7536 : val tss = 0.3265 ::: train hss = 0.3510 : val hss = 0.0906
Fold 2: train tss = 0.7100 : val tss = 0.6288 ::: train hss = 0.1959 : val hss = 0.2119
Fold 3: train tss = 0.6536 : val tss = 0.2546 ::: train hss = 0.1687 : val hss = 0.0598
Fold 4: train tss = 0.7097 : val tss = 0.6761 ::: train hss = 0.2000 : val hss = 0.2348
mean cv TSS: 0.3772
mean cv HSS: 0.1194
96/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.5447 : val tss = 0.1539 ::: train hss = 0.2905 : val hss = 0.0953
Fold 1: train tss = 0.8369 : val tss = 0.2466 ::: train hss = 0.4291 : val hss = 0.1853
Fold 2: train tss = 0.7339 : val tss = 0.6950 ::: train hss = 0.2166 : val hss = 0.3374
Fold 3: train tss = 0.7249 : val tss = 0.1595 ::: train hss = 0.2622 : val hss = 0.0337
Fold 4: train tss = 0.7363 : val tss = 0.6333 ::: train hss = 0.2601 : val hss = 0.2895
mean cv TSS: 0.3777
mean cv HSS: 0.1882
97/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.4436 : val tss = 0.1859 ::: train hss = 0.2164 : val hss = 0.1173
Fold 1: train tss = 0.7791 : val tss = 0.2122 ::: train hss = 0.4555 : val hss = 0.1129
Fold 2: train tss = 0.6821 : val tss = 0.7306 ::: train hss = 0.2459 : val hss = 0.3845
Fold 3: train tss = 0.7432 : val tss = 0.2634 ::: train hss = 0.2779 : val hss = 0.0734
Fold 4: train tss = 0.6568 : val tss = 0.5244 ::: train hss = 0.1912 : val hss = 0.1271
mean cv TSS: 0.3833
mean cv HSS: 0.1630
98/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9925 : val tss = -0.0056 ::: train hss = 0.3892 : val hss = -0.0078
Fold 1: train tss = 0.8663 : val tss = 0.4503 ::: train hss = 0.4226 : val hss = 0.1475
Fold 2: train tss = 0.7803 : val tss = 0.6981 ::: train hss = 0.2464 : val hss = 0.3014
Fold 3: train tss = 0.8127 : val tss = 0.3856 ::: train hss = 0.3459 : val hss = 0.0537
Fold 4: train tss = 0.7905 : val tss = 0.7415 ::: train hss = 0.2678 : val hss = 0.3392
mean cv TSS: 0.4540
mean cv HSS: 0.1668
99/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8151 : val tss = 0.2500 ::: train hss = 0.5206 : val hss = 0.1557
Fold 2: train tss = 0.6996 : val tss = 0.6988 ::: train hss = 0.1601 : val hss = 0.3968
Fold 3: train tss = 0.7845 : val tss = 0.0559 ::: train hss = 0.2920 : val hss = 0.0160
Fold 4: train tss = 0.7486 : val tss = 0.6847 ::: train hss = 0.2401 : val hss = 0.3025
mean cv TSS: 0.3379
mean cv HSS: 0.1742
100/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.4443 : val tss = -0.0162 ::: train hss = 0.2339 : val hss = -0.0174
Fold 1: train tss = 0.6951 : val tss = 0.4455 ::: train hss = 0.1823 : val hss = 0.1676
Fold 2: train tss = 0.7065 : val tss = 0.7150 ::: train hss = 0.2612 : val hss = 0.3308
Fold 3: train tss = 0.7643 : val tss = 0.2197 ::: train hss = 0.3134 : val hss = 0.0485
Fold 4: train tss = 0.6486 : val tss = 0.6742 ::: train hss = 0.1525 : val hss = 0.2278
mean cv TSS: 0.4076
mean cv HSS: 0.1515
101/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.4952 : val tss = 0.0982 ::: train hss = 0.2830 : val hss = 0.1258
Fold 1: train tss = 0.7908 : val tss = 0.2751 ::: train hss = 0.3715 : val hss = 0.2088
Fold 2: train tss = 0.5659 : val tss = 0.7088 ::: train hss = 0.1716 : val hss = 0.3940
Fold 3: train tss = 0.6485 : val tss = 0.0714 ::: train hss = 0.1698 : val hss = 0.0198
Fold 4: train tss = 0.6419 : val tss = 0.6898 ::: train hss = 0.1677 : val hss = 0.2749
mean cv TSS: 0.3687
mean cv HSS: 0.2047
102/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = -0.0002 ::: train hss = 0.0000 : val hss = -0.0005
Fold 1: train tss = 0.7741 : val tss = 0.2862 ::: train hss = 0.4078 : val hss = 0.1069
Fold 2: train tss = 0.7717 : val tss = 0.7148 ::: train hss = 0.2353 : val hss = 0.3431
Fold 3: train tss = 0.8026 : val tss = 0.2072 ::: train hss = 0.3026 : val hss = 0.1060
Fold 4: train tss = 0.7725 : val tss = 0.7707 ::: train hss = 0.2529 : val hss = 0.3555
mean cv TSS: 0.3957
mean cv HSS: 0.1822
103/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7718 : val tss = 0.3209 ::: train hss = 0.4259 : val hss = 0.1243
Fold 2: train tss = 0.6825 : val tss = 0.7040 ::: train hss = 0.1533 : val hss = 0.2970
Fold 3: train tss = 0.7311 : val tss = 0.3591 ::: train hss = 0.2256 : val hss = 0.0875
Fold 4: train tss = 0.6892 : val tss = 0.6956 ::: train hss = 0.2277 : val hss = 0.2533
mean cv TSS: 0.4159
mean cv HSS: 0.1524
104/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.8859 : val tss = 0.1307 ::: train hss = 0.2286 : val hss = 0.1757
Fold 1: train tss = 0.7690 : val tss = 0.2026 ::: train hss = 0.4884 : val hss = 0.2019
Fold 2: train tss = 0.5605 : val tss = 0.5037 ::: train hss = 0.0930 : val hss = 0.1419
Fold 3: train tss = 0.7039 : val tss = -0.0026 ::: train hss = 0.2257 : val hss = -0.0011
Fold 4: train tss = 0.5981 : val tss = 0.6337 ::: train hss = 0.2136 : val hss = 0.2337
mean cv TSS: 0.2936
mean cv HSS: 0.1504
105/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = 0.0029 ::: train hss = 0.0952 : val hss = 0.0053
Fold 1: train tss = 0.3216 : val tss = 0.2736 ::: train hss = 0.1744 : val hss = 0.1451
Fold 2: train tss = 0.0387 : val tss = 0.1110 ::: train hss = 0.0422 : val hss = 0.1409
Fold 3: train tss = 0.6352 : val tss = 0.3250 ::: train hss = 0.1684 : val hss = 0.0606
Fold 4: train tss = 0.5967 : val tss = 0.6068 ::: train hss = 0.1298 : val hss = 0.1928
mean cv TSS: 0.2638
mean cv HSS: 0.1089
106/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.8862 : val tss = -0.0023 ::: train hss = 0.2317 : val hss = -0.0013
Fold 1: train tss = 0.8515 : val tss = 0.2618 ::: train hss = 0.4875 : val hss = 0.0605
Fold 2: train tss = 0.7136 : val tss = 0.6302 ::: train hss = 0.1849 : val hss = 0.2339
Fold 3: train tss = 0.7819 : val tss = 0.3875 ::: train hss = 0.2777 : val hss = 0.0817
Fold 4: train tss = 0.7353 : val tss = 0.5617 ::: train hss = 0.2288 : val hss = 0.2309
mean cv TSS: 0.3678
mean cv HSS: 0.1211
107/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7673 : val tss = 0.3150 ::: train hss = 0.4245 : val hss = 0.1633
Fold 2: train tss = 0.7137 : val tss = 0.7188 ::: train hss = 0.2070 : val hss = 0.3052
Fold 3: train tss = 0.6887 : val tss = 0.0829 ::: train hss = 0.1533 : val hss = 0.0170
Fold 4: train tss = 0.6729 : val tss = 0.6683 ::: train hss = 0.2069 : val hss = 0.2441
mean cv TSS: 0.3570
mean cv HSS: 0.1459
108/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.5480 : val tss = 0.0370 ::: train hss = 0.4566 : val hss = 0.0375
Fold 1: train tss = 0.7293 : val tss = 0.3588 ::: train hss = 0.2691 : val hss = 0.1526
Fold 2: train tss = 0.6477 : val tss = 0.6365 ::: train hss = 0.1457 : val hss = 0.3718
Fold 3: train tss = 0.7009 : val tss = 0.0301 ::: train hss = 0.2356 : val hss = 0.0080
Fold 4: train tss = 0.5633 : val tss = 0.5717 ::: train hss = 0.1386 : val hss = 0.1500
mean cv TSS: 0.3268
mean cv HSS: 0.1440
109/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.3987 : val tss = 0.1968 ::: train hss = 0.4089 : val hss = 0.1561
Fold 1: train tss = 0.4980 : val tss = 0.4149 ::: train hss = 0.0674 : val hss = 0.0908
Fold 2: train tss = 0.5855 : val tss = 0.6974 ::: train hss = 0.1454 : val hss = 0.3511
Fold 3: train tss = 0.6403 : val tss = -0.0039 ::: train hss = 0.1789 : val hss = -0.0012
Fold 4: train tss = 0.5569 : val tss = 0.6501 ::: train hss = 0.1315 : val hss = 0.2046
mean cv TSS: 0.3911
mean cv HSS: 0.1603
110/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 171357
Fold 0: train tss = 0.1000 : val tss = -0.0002 ::: train hss = 0.1818 : val hss = -0.0005
Fold 1: train tss = 0.8247 : val tss = 0.2718 ::: train hss = 0.5321 : val hss = 0.1086
Fold 2: train tss = 0.7789 : val tss = 0.6855 ::: train hss = 0.2580 : val hss = 0.2692
Fold 3: train tss = 0.7455 : val tss = 0.2874 ::: train hss = 0.2226 : val hss = 0.0500
Fold 4: train tss = 0.7545 : val tss = 0.7748 ::: train hss = 0.2567 : val hss = 0.3495
mean cv TSS: 0.4039
mean cv HSS: 0.1554
111/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8061 : val tss = 0.2417 ::: train hss = 0.4657 : val hss = 0.1215
Fold 2: train tss = 0.6789 : val tss = 0.7586 ::: train hss = 0.1647 : val hss = 0.4105
Fold 3: train tss = 0.7525 : val tss = 0.3774 ::: train hss = 0.2710 : val hss = 0.0920
Fold 4: train tss = 0.6691 : val tss = 0.6219 ::: train hss = 0.2132 : val hss = 0.2134
mean cv TSS: 0.3999
mean cv HSS: 0.1675
112/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.7429 : val tss = 0.2236 ::: train hss = 0.3161 : val hss = 0.0944
Fold 1: train tss = 0.8335 : val tss = 0.2574 ::: train hss = 0.5324 : val hss = 0.2253
Fold 2: train tss = 0.7064 : val tss = 0.7775 ::: train hss = 0.2655 : val hss = 0.4360
Fold 3: train tss = 0.6662 : val tss = 0.1445 ::: train hss = 0.2482 : val hss = 0.0401
Fold 4: train tss = 0.7582 : val tss = 0.6328 ::: train hss = 0.2669 : val hss = 0.2295
mean cv TSS: 0.4072
mean cv HSS: 0.2051
113/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = -0.0005 ::: train hss = 0.0000 : val hss = -0.0010
Fold 1: train tss = 0.7750 : val tss = 0.1392 ::: train hss = 0.4157 : val hss = 0.1200
Fold 2: train tss = 0.2959 : val tss = 0.4328 ::: train hss = 0.1491 : val hss = 0.2973
Fold 3: train tss = 0.6663 : val tss = 0.0006 ::: train hss = 0.2103 : val hss = 0.0002
Fold 4: train tss = 0.6773 : val tss = 0.6610 ::: train hss = 0.1961 : val hss = 0.2186
mean cv TSS: 0.2466
mean cv HSS: 0.1270
114/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.8441 : val tss = -0.0086 ::: train hss = 0.3926 : val hss = -0.0110
Fold 1: train tss = 0.8804 : val tss = 0.2368 ::: train hss = 0.3991 : val hss = 0.1080
Fold 2: train tss = 0.7691 : val tss = 0.7215 ::: train hss = 0.1869 : val hss = 0.4036
Fold 3: train tss = 0.8008 : val tss = 0.4186 ::: train hss = 0.3210 : val hss = 0.0846
Fold 4: train tss = 0.7803 : val tss = 0.7203 ::: train hss = 0.2729 : val hss = 0.2754
mean cv TSS: 0.4177
mean cv HSS: 0.1721
115/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.5445 : val tss = -0.0110 ::: train hss = 0.2828 : val hss = -0.0152
Fold 1: train tss = 0.7794 : val tss = 0.2893 ::: train hss = 0.4171 : val hss = 0.1386
Fold 2: train tss = 0.8236 : val tss = 0.7251 ::: train hss = 0.2367 : val hss = 0.3956
Fold 3: train tss = 0.7375 : val tss = 0.3831 ::: train hss = 0.2239 : val hss = 0.0781
Fold 4: train tss = 0.7163 : val tss = 0.7553 ::: train hss = 0.1854 : val hss = 0.3196
mean cv TSS: 0.4284
mean cv HSS: 0.1833
116/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.5982 : val tss = 0.0189 ::: train hss = 0.5091 : val hss = 0.0226
Fold 1: train tss = 0.7443 : val tss = 0.3725 ::: train hss = 0.1928 : val hss = 0.1395
Fold 2: train tss = 0.6919 : val tss = 0.7468 ::: train hss = 0.2626 : val hss = 0.4323
Fold 3: train tss = 0.7686 : val tss = 0.1256 ::: train hss = 0.3235 : val hss = 0.0382
Fold 4: train tss = 0.7390 : val tss = 0.6938 ::: train hss = 0.2342 : val hss = 0.2590
mean cv TSS: 0.3915
mean cv HSS: 0.1783
117/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7172 : val tss = 0.3159 ::: train hss = 0.1867 : val hss = 0.1539
Fold 2: train tss = 0.5966 : val tss = 0.7486 ::: train hss = 0.1644 : val hss = 0.4013
Fold 3: train tss = 0.6984 : val tss = 0.1070 ::: train hss = 0.2371 : val hss = 0.0269
Fold 4: train tss = 0.6395 : val tss = 0.6584 ::: train hss = 0.1758 : val hss = 0.2337
mean cv TSS: 0.3660
mean cv HSS: 0.1632
118/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.8005 : val tss = 0.2992 ::: train hss = 0.5012 : val hss = 0.1314
Fold 2: train tss = 0.7716 : val tss = 0.7407 ::: train hss = 0.2258 : val hss = 0.3667
Fold 3: train tss = 0.7588 : val tss = 0.2297 ::: train hss = 0.2693 : val hss = 0.0659
Fold 4: train tss = 0.7629 : val tss = 0.7597 ::: train hss = 0.2449 : val hss = 0.4070
mean cv TSS: 0.4059
mean cv HSS: 0.1942
119/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7730 : val tss = 0.2921 ::: train hss = 0.4847 : val hss = 0.1209
Fold 2: train tss = 0.7221 : val tss = 0.7253 ::: train hss = 0.1773 : val hss = 0.3404
Fold 3: train tss = 0.7493 : val tss = 0.3140 ::: train hss = 0.2619 : val hss = 0.0710
Fold 4: train tss = 0.6981 : val tss = 0.6939 ::: train hss = 0.2335 : val hss = 0.2529
mean cv TSS: 0.4051
mean cv HSS: 0.1570
120/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.5460 : val tss = 0.2057 ::: train hss = 0.3413 : val hss = 0.0887
Fold 1: train tss = 0.8076 : val tss = 0.1495 ::: train hss = 0.4374 : val hss = 0.1288
Fold 2: train tss = 0.6057 : val tss = 0.5962 ::: train hss = 0.1062 : val hss = 0.1819
Fold 3: train tss = 0.7016 : val tss = 0.0243 ::: train hss = 0.2510 : val hss = 0.0049
Fold 4: train tss = 0.6693 : val tss = 0.5837 ::: train hss = 0.2135 : val hss = 0.1571
mean cv TSS: 0.3119
mean cv HSS: 0.1123
121/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 104260
Fold 0: train tss = 0.0500 : val tss = -0.0011 ::: train hss = 0.0952 : val hss = -0.0021
Fold 1: train tss = 0.7208 : val tss = 0.2014 ::: train hss = 0.3075 : val hss = 0.1743
Fold 2: train tss = 0.0753 : val tss = 0.2365 ::: train hss = 0.0561 : val hss = 0.2114
Fold 3: train tss = 0.6383 : val tss = 0.1060 ::: train hss = 0.2213 : val hss = 0.0264
Fold 4: train tss = 0.5879 : val tss = 0.5680 ::: train hss = 0.1807 : val hss = 0.2315
mean cv TSS: 0.2222
mean cv HSS: 0.1283
122/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9372 : val tss = 0.0398 ::: train hss = 0.2585 : val hss = 0.0481
Fold 1: train tss = 0.7921 : val tss = 0.2936 ::: train hss = 0.2870 : val hss = 0.1202
Fold 2: train tss = 0.7035 : val tss = 0.6395 ::: train hss = 0.1404 : val hss = 0.2171
Fold 3: train tss = 0.7223 : val tss = 0.0688 ::: train hss = 0.2120 : val hss = 0.0256
Fold 4: train tss = 0.7448 : val tss = 0.6697 ::: train hss = 0.2393 : val hss = 0.2312
mean cv TSS: 0.3423
mean cv HSS: 0.1284
123/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.7482 : val tss = 0.6192 ::: train hss = 0.2161 : val hss = 0.1984
Fold 3: train tss = 0.6435 : val tss = 0.2988 ::: train hss = 0.1899 : val hss = 0.0599
Fold 4: train tss = 0.6537 : val tss = 0.6206 ::: train hss = 0.2001 : val hss = 0.1867
mean cv TSS: 0.3077
mean cv HSS: 0.0890
124/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.7488 : val tss = 0.0217 ::: train hss = 0.6656 : val hss = 0.0320
Fold 1: train tss = 0.7562 : val tss = 0.1651 ::: train hss = 0.5525 : val hss = 0.2426
Fold 2: train tss = 0.6363 : val tss = 0.6918 ::: train hss = 0.2043 : val hss = 0.3185
Fold 3: train tss = 0.6918 : val tss = 0.3254 ::: train hss = 0.2119 : val hss = 0.0512
Fold 4: train tss = 0.7159 : val tss = 0.6448 ::: train hss = 0.2396 : val hss = 0.2287
mean cv TSS: 0.3698
mean cv HSS: 0.1746
125/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0500 : val tss = -0.0007 ::: train hss = 0.0952 : val hss = -0.0014
Fold 1: train tss = 0.7333 : val tss = 0.3481 ::: train hss = 0.2863 : val hss = 0.1877
Fold 2: train tss = 0.5499 : val tss = 0.7153 ::: train hss = 0.1043 : val hss = 0.3367
Fold 3: train tss = 0.5987 : val tss = 0.1418 ::: train hss = 0.1530 : val hss = 0.0263
Fold 4: train tss = 0.5773 : val tss = 0.6190 ::: train hss = 0.1282 : val hss = 0.1803
mean cv TSS: 0.3647
mean cv HSS: 0.1459
126/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.1998 : val tss = 0.0079 ::: train hss = 0.3073 : val hss = 0.0144
Fold 1: train tss = 0.7998 : val tss = 0.2714 ::: train hss = 0.5506 : val hss = 0.1101
Fold 2: train tss = 0.7884 : val tss = 0.7188 ::: train hss = 0.2568 : val hss = 0.3175
Fold 3: train tss = 0.7791 : val tss = 0.0794 ::: train hss = 0.2902 : val hss = 0.0240
Fold 4: train tss = 0.7534 : val tss = 0.7543 ::: train hss = 0.2303 : val hss = 0.3487
mean cv TSS: 0.3663
mean cv HSS: 0.1629
127/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7723 : val tss = 0.2568 ::: train hss = 0.3353 : val hss = 0.1121
Fold 2: train tss = 0.6689 : val tss = 0.7689 ::: train hss = 0.2051 : val hss = 0.4288
Fold 3: train tss = 0.7143 : val tss = 0.2527 ::: train hss = 0.2324 : val hss = 0.0693
Fold 4: train tss = 0.7163 : val tss = 0.7202 ::: train hss = 0.2131 : val hss = 0.2852
mean cv TSS: 0.3997
mean cv HSS: 0.1791
128/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.8919 : val tss = 0.0787 ::: train hss = 0.3398 : val hss = 0.0669
Fold 1: train tss = 0.8336 : val tss = 0.2490 ::: train hss = 0.4381 : val hss = 0.1583
Fold 2: train tss = 0.7943 : val tss = 0.7049 ::: train hss = 0.2586 : val hss = 0.4453
Fold 3: train tss = 0.7895 : val tss = 0.1424 ::: train hss = 0.2901 : val hss = 0.0613
Fold 4: train tss = 0.7673 : val tss = 0.6350 ::: train hss = 0.2850 : val hss = 0.2262
mean cv TSS: 0.3620
mean cv HSS: 0.1916
129/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.4960 : val tss = 0.0593 ::: train hss = 0.3149 : val hss = 0.0923
Fold 1: train tss = 0.5223 : val tss = 0.2575 ::: train hss = 0.3054 : val hss = 0.1313
Fold 2: train tss = 0.4406 : val tss = 0.7029 ::: train hss = 0.1129 : val hss = 0.3031
Fold 3: train tss = 0.7510 : val tss = 0.1172 ::: train hss = 0.2816 : val hss = 0.0274
Fold 4: train tss = 0.7041 : val tss = 0.5883 ::: train hss = 0.1969 : val hss = 0.2171
mean cv TSS: 0.3450
mean cv HSS: 0.1543
130/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9930 : val tss = -0.0079 ::: train hss = 0.4053 : val hss = -0.0104
Fold 1: train tss = 0.8845 : val tss = 0.2520 ::: train hss = 0.3977 : val hss = 0.1237
Fold 2: train tss = 0.8418 : val tss = 0.6412 ::: train hss = 0.3076 : val hss = 0.3146
Fold 3: train tss = 0.8654 : val tss = 0.2760 ::: train hss = 0.3840 : val hss = 0.0883
Fold 4: train tss = 0.7907 : val tss = 0.7868 ::: train hss = 0.2682 : val hss = 0.4054
mean cv TSS: 0.3896
mean cv HSS: 0.1843
131/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8549 : val tss = 0.2932 ::: train hss = 0.2572 : val hss = 0.0614
Fold 2: train tss = 0.7638 : val tss = 0.7182 ::: train hss = 0.2395 : val hss = 0.3151
Fold 3: train tss = 0.8029 : val tss = 0.2525 ::: train hss = 0.2973 : val hss = 0.1283
Fold 4: train tss = 0.7356 : val tss = 0.7336 ::: train hss = 0.2426 : val hss = 0.2982
mean cv TSS: 0.3995
mean cv HSS: 0.1606
132/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 109820
Fold 0: train tss = 0.6989 : val tss = -0.0009 ::: train hss = 0.6502 : val hss = -0.0015
Fold 1: train tss = 0.8034 : val tss = 0.2157 ::: train hss = 0.5397 : val hss = 0.2343
Fold 2: train tss = 0.7888 : val tss = 0.7539 ::: train hss = 0.3196 : val hss = 0.4955
Fold 3: train tss = 0.8183 : val tss = 0.2765 ::: train hss = 0.3181 : val hss = 0.1320
Fold 4: train tss = 0.5718 : val tss = 0.6027 ::: train hss = 0.1122 : val hss = 0.1801
mean cv TSS: 0.3696
mean cv HSS: 0.2081
133/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.4465 : val tss = -0.0097 ::: train hss = 0.3079 : val hss = -0.0140
Fold 1: train tss = 0.7915 : val tss = 0.2989 ::: train hss = 0.4969 : val hss = 0.2117
Fold 2: train tss = 0.5056 : val tss = 0.6694 ::: train hss = 0.1454 : val hss = 0.2715
Fold 3: train tss = 0.6726 : val tss = 0.1318 ::: train hss = 0.1930 : val hss = 0.0205
Fold 4: train tss = 0.7090 : val tss = 0.7184 ::: train hss = 0.2181 : val hss = 0.3508
mean cv TSS: 0.3617
mean cv HSS: 0.1681
134/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7894 : val tss = 0.2682 ::: train hss = 0.5262 : val hss = 0.1155
Fold 2: train tss = 0.7827 : val tss = 0.7261 ::: train hss = 0.2480 : val hss = 0.3675
Fold 3: train tss = 0.8104 : val tss = 0.3758 ::: train hss = 0.3497 : val hss = 0.0726
Fold 4: train tss = 0.7942 : val tss = 0.7459 ::: train hss = 0.2759 : val hss = 0.3339
mean cv TSS: 0.4232
mean cv HSS: 0.1779
135/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7814 : val tss = 0.2846 ::: train hss = 0.4803 : val hss = 0.1220
Fold 2: train tss = 0.6388 : val tss = 0.5470 ::: train hss = 0.1229 : val hss = 0.1556
Fold 3: train tss = 0.7599 : val tss = 0.0741 ::: train hss = 0.2511 : val hss = 0.0234
Fold 4: train tss = 0.7312 : val tss = 0.7403 ::: train hss = 0.2157 : val hss = 0.2970
mean cv TSS: 0.3292
mean cv HSS: 0.1196
136/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.7742 : val tss = 0.0386 ::: train hss = 0.1239 : val hss = 0.0161
Fold 1: train tss = 0.7500 : val tss = 0.1884 ::: train hss = 0.2056 : val hss = 0.1246
Fold 2: train tss = 0.6393 : val tss = 0.6868 ::: train hss = 0.1377 : val hss = 0.2782
Fold 3: train tss = 0.7279 : val tss = 0.0019 ::: train hss = 0.2742 : val hss = 0.0006
Fold 4: train tss = 0.7205 : val tss = 0.6977 ::: train hss = 0.2169 : val hss = 0.2971
mean cv TSS: 0.3227
mean cv HSS: 0.1433
137/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.2965 : val tss = 0.1127 ::: train hss = 0.2156 : val hss = 0.0933
Fold 1: train tss = 0.3663 : val tss = 0.3602 ::: train hss = 0.1426 : val hss = 0.1432
Fold 2: train tss = 0.0944 : val tss = 0.2694 ::: train hss = 0.0417 : val hss = 0.2076
Fold 3: train tss = 0.6090 : val tss = 0.1986 ::: train hss = 0.1441 : val hss = 0.0332
Fold 4: train tss = 0.5258 : val tss = 0.6589 ::: train hss = 0.1281 : val hss = 0.2330
mean cv TSS: 0.3200
mean cv HSS: 0.1420
138/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.5928 : val tss = -0.0027 ::: train hss = 0.2577 : val hss = -0.0036
Fold 1: train tss = 0.8356 : val tss = 0.2560 ::: train hss = 0.3855 : val hss = 0.1134
Fold 2: train tss = 0.7279 : val tss = 0.7242 ::: train hss = 0.1545 : val hss = 0.3119
Fold 3: train tss = 0.7923 : val tss = 0.1644 ::: train hss = 0.2716 : val hss = 0.0650
Fold 4: train tss = 0.7279 : val tss = 0.6562 ::: train hss = 0.2257 : val hss = 0.2167
mean cv TSS: 0.3596
mean cv HSS: 0.1407
139/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7712 : val tss = 0.2871 ::: train hss = 0.2872 : val hss = 0.1178
Fold 2: train tss = 0.0902 : val tss = 0.0932 ::: train hss = 0.0797 : val hss = 0.1321
Fold 3: train tss = 0.7581 : val tss = 0.2723 ::: train hss = 0.2656 : val hss = 0.0692
Fold 4: train tss = 0.5992 : val tss = 0.6471 ::: train hss = 0.1491 : val hss = 0.2026
mean cv TSS: 0.2600
mean cv HSS: 0.1043
140/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.6976 : val tss = 0.0938 ::: train hss = 0.5167 : val hss = 0.1220
Fold 1: train tss = 0.8004 : val tss = 0.2175 ::: train hss = 0.4997 : val hss = 0.2423
Fold 2: train tss = 0.7135 : val tss = 0.7346 ::: train hss = 0.1961 : val hss = 0.3194
Fold 3: train tss = 0.7583 : val tss = 0.0045 ::: train hss = 0.2973 : val hss = 0.0012
Fold 4: train tss = 0.6380 : val tss = 0.7020 ::: train hss = 0.1411 : val hss = 0.2599
mean cv TSS: 0.3504
mean cv HSS: 0.1890
141/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.4488 : val tss = 0.1220 ::: train hss = 0.4603 : val hss = 0.1193
Fold 1: train tss = 0.5240 : val tss = 0.3396 ::: train hss = 0.0688 : val hss = 0.0636
Fold 2: train tss = 0.5328 : val tss = 0.6746 ::: train hss = 0.1153 : val hss = 0.3654
Fold 3: train tss = 0.7143 : val tss = 0.0465 ::: train hss = 0.2323 : val hss = 0.0147
Fold 4: train tss = 0.5998 : val tss = 0.6168 ::: train hss = 0.1779 : val hss = 0.1796
mean cv TSS: 0.3599
mean cv HSS: 0.1485
142/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.4998 : val tss = 0.0046 ::: train hss = 0.6247 : val hss = 0.0090
Fold 1: train tss = 0.7795 : val tss = 0.2483 ::: train hss = 0.2866 : val hss = 0.0977
Fold 2: train tss = 0.7995 : val tss = 0.7359 ::: train hss = 0.2481 : val hss = 0.3589
Fold 3: train tss = 0.8163 : val tss = 0.1180 ::: train hss = 0.3123 : val hss = 0.0628
Fold 4: train tss = 0.7811 : val tss = 0.7129 ::: train hss = 0.3168 : val hss = 0.3221
mean cv TSS: 0.3639
mean cv HSS: 0.1701
143/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7838 : val tss = 0.2727 ::: train hss = 0.3535 : val hss = 0.1205
Fold 2: train tss = 0.7504 : val tss = 0.6988 ::: train hss = 0.2142 : val hss = 0.3068
Fold 3: train tss = 0.7081 : val tss = 0.2128 ::: train hss = 0.2100 : val hss = 0.0564
Fold 4: train tss = 0.6589 : val tss = 0.6226 ::: train hss = 0.2045 : val hss = 0.1919
mean cv TSS: 0.3614
mean cv HSS: 0.1351
144/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.9871 : val tss = 0.2404 ::: train hss = 0.2686 : val hss = 0.2404
Fold 1: train tss = 0.7911 : val tss = 0.1785 ::: train hss = 0.4448 : val hss = 0.1304
Fold 2: train tss = 0.7508 : val tss = 0.7207 ::: train hss = 0.1878 : val hss = 0.3628
Fold 3: train tss = 0.7948 : val tss = 0.2236 ::: train hss = 0.3470 : val hss = 0.0552
Fold 4: train tss = 0.7709 : val tss = 0.6176 ::: train hss = 0.3005 : val hss = 0.2786
mean cv TSS: 0.3961
mean cv HSS: 0.2134
145/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.6936 : val tss = -0.0058 ::: train hss = 0.3189 : val hss = -0.0094
Fold 1: train tss = 0.5176 : val tss = 0.4372 ::: train hss = 0.0977 : val hss = 0.0991
Fold 2: train tss = 0.2150 : val tss = 0.2334 ::: train hss = 0.1350 : val hss = 0.2253
Fold 3: train tss = 0.7371 : val tss = 0.2267 ::: train hss = 0.2492 : val hss = 0.0877
Fold 4: train tss = 0.6667 : val tss = 0.5548 ::: train hss = 0.2125 : val hss = 0.1830
mean cv TSS: 0.2892
mean cv HSS: 0.1171
146/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9934 : val tss = -0.0105 ::: train hss = 0.4183 : val hss = -0.0129
Fold 1: train tss = 0.8995 : val tss = 0.2807 ::: train hss = 0.4129 : val hss = 0.0988
Fold 2: train tss = 0.8035 : val tss = 0.7031 ::: train hss = 0.2645 : val hss = 0.4031
Fold 3: train tss = 0.8105 : val tss = 0.0735 ::: train hss = 0.2920 : val hss = 0.0339
Fold 4: train tss = 0.8219 : val tss = 0.7696 ::: train hss = 0.2901 : val hss = 0.4216
mean cv TSS: 0.3633
mean cv HSS: 0.1889
147/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8190 : val tss = 0.2936 ::: train hss = 0.4647 : val hss = 0.1249
Fold 2: train tss = 0.7545 : val tss = 0.6551 ::: train hss = 0.1954 : val hss = 0.2294
Fold 3: train tss = 0.7887 : val tss = 0.2846 ::: train hss = 0.2846 : val hss = 0.0905
Fold 4: train tss = 0.7591 : val tss = 0.7429 ::: train hss = 0.2675 : val hss = 0.3186
mean cv TSS: 0.3952
mean cv HSS: 0.1527
148/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.6488 : val tss = 0.0251 ::: train hss = 0.6035 : val hss = 0.0352
Fold 1: train tss = 0.7955 : val tss = 0.2068 ::: train hss = 0.4462 : val hss = 0.1200
Fold 2: train tss = 0.7952 : val tss = 0.6856 ::: train hss = 0.3723 : val hss = 0.3836
Fold 3: train tss = 0.7667 : val tss = 0.0216 ::: train hss = 0.2793 : val hss = 0.0058
Fold 4: train tss = 0.7624 : val tss = 0.6742 ::: train hss = 0.2863 : val hss = 0.2477
mean cv TSS: 0.3227
mean cv HSS: 0.1584
149/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.5486 : val tss = 0.0601 ::: train hss = 0.5103 : val hss = 0.0963
Fold 1: train tss = 0.7522 : val tss = 0.2030 ::: train hss = 0.2333 : val hss = 0.1276
Fold 2: train tss = 0.7553 : val tss = 0.7213 ::: train hss = 0.2497 : val hss = 0.4224
Fold 3: train tss = 0.6770 : val tss = 0.0787 ::: train hss = 0.1804 : val hss = 0.0236
Fold 4: train tss = 0.6959 : val tss = 0.6952 ::: train hss = 0.1918 : val hss = 0.3039
mean cv TSS: 0.3517
mean cv HSS: 0.1948
150/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.5994 : val tss = 0.0024 ::: train hss = 0.6480 : val hss = 0.0043
Fold 1: train tss = 0.8095 : val tss = 0.2430 ::: train hss = 0.5643 : val hss = 0.1261
Fold 2: train tss = 0.7627 : val tss = 0.7322 ::: train hss = 0.2131 : val hss = 0.3629
Fold 3: train tss = 0.8330 : val tss = 0.2512 ::: train hss = 0.3432 : val hss = 0.1245
Fold 4: train tss = 0.8166 : val tss = 0.6263 ::: train hss = 0.2684 : val hss = 0.4256
mean cv TSS: 0.3710
mean cv HSS: 0.2087
151/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7911 : val tss = 0.3312 ::: train hss = 0.4925 : val hss = 0.1381
Fold 2: train tss = 0.7541 : val tss = 0.7319 ::: train hss = 0.2208 : val hss = 0.3412
Fold 3: train tss = 0.7365 : val tss = 0.3524 ::: train hss = 0.2348 : val hss = 0.0959
Fold 4: train tss = 0.7011 : val tss = 0.7332 ::: train hss = 0.2362 : val hss = 0.3074
mean cv TSS: 0.4297
mean cv HSS: 0.1765
152/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8904 : val tss = 0.0225 ::: train hss = 0.3018 : val hss = 0.0294
Fold 1: train tss = 0.7472 : val tss = 0.2365 ::: train hss = 0.3134 : val hss = 0.2148
Fold 2: train tss = 0.6104 : val tss = 0.7319 ::: train hss = 0.1821 : val hss = 0.4091
Fold 3: train tss = 0.6121 : val tss = 0.2227 ::: train hss = 0.1932 : val hss = 0.0468
Fold 4: train tss = 0.7156 : val tss = 0.6601 ::: train hss = 0.2339 : val hss = 0.2518
mean cv TSS: 0.3747
mean cv HSS: 0.1904
153/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.4455 : val tss = 0.2087 ::: train hss = 0.2700 : val hss = 0.1856
Fold 1: train tss = 0.4173 : val tss = 0.3536 ::: train hss = 0.1169 : val hss = 0.1173
Fold 2: train tss = 0.0687 : val tss = 0.3010 ::: train hss = 0.0314 : val hss = 0.1979
Fold 3: train tss = 0.6636 : val tss = -0.0036 ::: train hss = 0.1884 : val hss = -0.0012
Fold 4: train tss = 0.5524 : val tss = 0.6195 ::: train hss = 0.1401 : val hss = 0.1835
mean cv TSS: 0.2958
mean cv HSS: 0.1366
154/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 318997
Fold 0: train tss = 0.9429 : val tss = 0.0018 ::: train hss = 0.3849 : val hss = 0.0031
Fold 1: train tss = 0.6454 : val tss = 0.3207 ::: train hss = 0.3380 : val hss = 0.1055
Fold 2: train tss = 0.6943 : val tss = 0.6818 ::: train hss = 0.1500 : val hss = 0.2843
Fold 3: train tss = 0.7942 : val tss = 0.2902 ::: train hss = 0.2993 : val hss = 0.0988
Fold 4: train tss = 0.7428 : val tss = 0.6462 ::: train hss = 0.2435 : val hss = 0.3415
mean cv TSS: 0.3882
mean cv HSS: 0.1667
155/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0089 : val tss = 0.0011 ::: train hss = 0.0175 : val hss = 0.0020
Fold 2: train tss = 0.6689 : val tss = 0.7034 ::: train hss = 0.2110 : val hss = 0.3351
Fold 3: train tss = 0.7051 : val tss = 0.0807 ::: train hss = 0.1826 : val hss = 0.0360
Fold 4: train tss = 0.6694 : val tss = 0.7213 ::: train hss = 0.1951 : val hss = 0.3515
mean cv TSS: 0.3013
mean cv HSS: 0.1449
156/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8476 : val tss = 0.0193 ::: train hss = 0.5948 : val hss = 0.0310
Fold 1: train tss = 0.8063 : val tss = 0.2244 ::: train hss = 0.2613 : val hss = 0.1847
Fold 2: train tss = 0.6700 : val tss = 0.6835 ::: train hss = 0.1688 : val hss = 0.3633
Fold 3: train tss = 0.6962 : val tss = 0.3582 ::: train hss = 0.2288 : val hss = 0.0581
Fold 4: train tss = 0.6720 : val tss = 0.6458 ::: train hss = 0.2155 : val hss = 0.2146
mean cv TSS: 0.3863
mean cv HSS: 0.1703
157/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.4980 : val tss = 0.0505 ::: train hss = 0.4238 : val hss = 0.0617
Fold 1: train tss = 0.7122 : val tss = 0.3931 ::: train hss = 0.1629 : val hss = 0.1704
Fold 2: train tss = 0.5053 : val tss = 0.6298 ::: train hss = 0.1041 : val hss = 0.2367
Fold 3: train tss = 0.6862 : val tss = 0.1682 ::: train hss = 0.2102 : val hss = 0.0310
Fold 4: train tss = 0.5996 : val tss = 0.6762 ::: train hss = 0.1498 : val hss = 0.2349
mean cv TSS: 0.3836
mean cv HSS: 0.1469
158/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.3999 : val tss = -0.0002 ::: train hss = 0.5516 : val hss = -0.0005
Fold 1: train tss = 0.8397 : val tss = 0.2875 ::: train hss = 0.5581 : val hss = 0.1392
Fold 2: train tss = 0.7710 : val tss = 0.7173 ::: train hss = 0.2478 : val hss = 0.3123
Fold 3: train tss = 0.8046 : val tss = 0.4047 ::: train hss = 0.2787 : val hss = 0.0985
Fold 4: train tss = 0.7371 : val tss = 0.7054 ::: train hss = 0.2335 : val hss = 0.2672
mean cv TSS: 0.4229
mean cv HSS: 0.1633
159/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7761 : val tss = 0.3651 ::: train hss = 0.4699 : val hss = 0.1548
Fold 2: train tss = 0.6974 : val tss = 0.7003 ::: train hss = 0.2125 : val hss = 0.2939
Fold 3: train tss = 0.7340 : val tss = 0.0847 ::: train hss = 0.2104 : val hss = 0.0246
Fold 4: train tss = 0.7190 : val tss = 0.7130 ::: train hss = 0.2051 : val hss = 0.2675
mean cv TSS: 0.3726
mean cv HSS: 0.1481
160/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.7414 : val tss = 0.0089 ::: train hss = 0.2798 : val hss = 0.0141
Fold 1: train tss = 0.7854 : val tss = 0.3024 ::: train hss = 0.3370 : val hss = 0.1659
Fold 2: train tss = 0.6787 : val tss = 0.4798 ::: train hss = 0.1409 : val hss = 0.1316
Fold 3: train tss = 0.7606 : val tss = 0.0876 ::: train hss = 0.3318 : val hss = 0.0201
Fold 4: train tss = 0.7362 : val tss = 0.6491 ::: train hss = 0.2331 : val hss = 0.2990
mean cv TSS: 0.3055
mean cv HSS: 0.1261
161/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.5435 : val tss = 0.2363 ::: train hss = 0.2558 : val hss = 0.2184
Fold 1: train tss = 0.7193 : val tss = 0.3441 ::: train hss = 0.1617 : val hss = 0.1578
Fold 2: train tss = 0.3078 : val tss = 0.3593 ::: train hss = 0.1116 : val hss = 0.2304
Fold 3: train tss = 0.7267 : val tss = 0.0916 ::: train hss = 0.2432 : val hss = 0.0260
Fold 4: train tss = 0.7038 : val tss = 0.5522 ::: train hss = 0.2510 : val hss = 0.2678
mean cv TSS: 0.3167
mean cv HSS: 0.1801
162/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9889 : val tss = 0.0075 ::: train hss = 0.2997 : val hss = 0.0087
Fold 1: train tss = 0.8805 : val tss = 0.2729 ::: train hss = 0.4334 : val hss = 0.1208
Fold 2: train tss = 0.7593 : val tss = 0.6344 ::: train hss = 0.2184 : val hss = 0.2998
Fold 3: train tss = 0.8124 : val tss = 0.3756 ::: train hss = 0.2887 : val hss = 0.0980
Fold 4: train tss = 0.7875 : val tss = 0.6728 ::: train hss = 0.2613 : val hss = 0.3329
mean cv TSS: 0.3927
mean cv HSS: 0.1720
163/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.6928 : val tss = -0.0066 ::: train hss = 0.2948 : val hss = -0.0105
Fold 1: train tss = 0.8143 : val tss = 0.2715 ::: train hss = 0.4608 : val hss = 0.1027
Fold 2: train tss = 0.7625 : val tss = 0.6970 ::: train hss = 0.1805 : val hss = 0.4120
Fold 3: train tss = 0.7668 : val tss = 0.1090 ::: train hss = 0.2585 : val hss = 0.0427
Fold 4: train tss = 0.7672 : val tss = 0.7157 ::: train hss = 0.2331 : val hss = 0.3578
mean cv TSS: 0.3573
mean cv HSS: 0.1809
164/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.5964 : val tss = 0.0178 ::: train hss = 0.3848 : val hss = 0.0207
Fold 1: train tss = 0.7978 : val tss = 0.2867 ::: train hss = 0.4702 : val hss = 0.2920
Fold 2: train tss = 0.5649 : val tss = 0.7101 ::: train hss = 0.0885 : val hss = 0.3221
Fold 3: train tss = 0.7641 : val tss = -0.0255 ::: train hss = 0.2926 : val hss = -0.0067
Fold 4: train tss = 0.6833 : val tss = 0.6253 ::: train hss = 0.1692 : val hss = 0.1959
mean cv TSS: 0.3229
mean cv HSS: 0.1648
165/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 109820
Fold 0: train tss = 0.1498 : val tss = -0.0033 ::: train hss = 0.2396 : val hss = -0.0059
Fold 1: train tss = 0.7131 : val tss = 0.2205 ::: train hss = 0.3364 : val hss = 0.1950
Fold 2: train tss = 0.6071 : val tss = 0.6745 ::: train hss = 0.1475 : val hss = 0.2545
Fold 3: train tss = 0.7449 : val tss = 0.2680 ::: train hss = 0.2642 : val hss = 0.0713
Fold 4: train tss = 0.6410 : val tss = 0.7009 ::: train hss = 0.1749 : val hss = 0.2836
mean cv TSS: 0.3721
mean cv HSS: 0.1597
166/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7943 : val tss = 0.3457 ::: train hss = 0.4345 : val hss = 0.1299
Fold 2: train tss = 0.7450 : val tss = 0.7006 ::: train hss = 0.2283 : val hss = 0.3311
Fold 3: train tss = 0.7770 : val tss = 0.1317 ::: train hss = 0.2416 : val hss = 0.0484
Fold 4: train tss = 0.7796 : val tss = 0.7176 ::: train hss = 0.2640 : val hss = 0.3412
mean cv TSS: 0.3791
mean cv HSS: 0.1701
167/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7927 : val tss = 0.2925 ::: train hss = 0.4623 : val hss = 0.1108
Fold 2: train tss = 0.7441 : val tss = 0.7308 ::: train hss = 0.2265 : val hss = 0.3432
Fold 3: train tss = 0.7369 : val tss = 0.2284 ::: train hss = 0.2353 : val hss = 0.1045
Fold 4: train tss = 0.7479 : val tss = 0.7261 ::: train hss = 0.2604 : val hss = 0.2819
mean cv TSS: 0.3956
mean cv HSS: 0.1681
168/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.6410 : val tss = 0.3282 ::: train hss = 0.2374 : val hss = 0.2364
Fold 1: train tss = 0.7687 : val tss = 0.1030 ::: train hss = 0.2606 : val hss = 0.0551
Fold 2: train tss = 0.5130 : val tss = 0.4047 ::: train hss = 0.0830 : val hss = 0.0917
Fold 3: train tss = 0.7017 : val tss = 0.0632 ::: train hss = 0.2523 : val hss = 0.0149
Fold 4: train tss = 0.6618 : val tss = 0.6614 ::: train hss = 0.2542 : val hss = 0.2229
mean cv TSS: 0.3121
mean cv HSS: 0.1242
169/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.4467 : val tss = 0.1098 ::: train hss = 0.3191 : val hss = 0.1143
Fold 1: train tss = 0.5979 : val tss = 0.3479 ::: train hss = 0.1997 : val hss = 0.1447
Fold 2: train tss = 0.0844 : val tss = 0.2111 ::: train hss = 0.0602 : val hss = 0.2097
Fold 3: train tss = 0.6630 : val tss = 0.3136 ::: train hss = 0.1829 : val hss = 0.0486
Fold 4: train tss = 0.5596 : val tss = 0.6151 ::: train hss = 0.1227 : val hss = 0.1933
mean cv TSS: 0.3195
mean cv HSS: 0.1421
170/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.7380 : val tss = -0.0095 ::: train hss = 0.2187 : val hss = -0.0137
Fold 1: train tss = 0.7601 : val tss = 0.3379 ::: train hss = 0.3383 : val hss = 0.1202
Fold 2: train tss = 0.7970 : val tss = 0.6957 ::: train hss = 0.2612 : val hss = 0.3422
Fold 3: train tss = 0.7777 : val tss = 0.3223 ::: train hss = 0.2644 : val hss = 0.0723
Fold 4: train tss = 0.7294 : val tss = 0.6602 ::: train hss = 0.2005 : val hss = 0.2299
mean cv TSS: 0.4013
mean cv HSS: 0.1502
171/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.7183 : val tss = 0.5973 ::: train hss = 0.1893 : val hss = 0.1831
Fold 3: train tss = 0.7063 : val tss = 0.0782 ::: train hss = 0.1843 : val hss = 0.0292
Fold 4: train tss = 0.7024 : val tss = 0.7014 ::: train hss = 0.2463 : val hss = 0.3168
mean cv TSS: 0.2754
mean cv HSS: 0.1058
172/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.5970 : val tss = 0.0869 ::: train hss = 0.4189 : val hss = 0.0861
Fold 1: train tss = 0.6752 : val tss = 0.4019 ::: train hss = 0.1430 : val hss = 0.1075
Fold 2: train tss = 0.7004 : val tss = 0.7346 ::: train hss = 0.2009 : val hss = 0.3757
Fold 3: train tss = 0.7107 : val tss = 0.3622 ::: train hss = 0.2199 : val hss = 0.0679
Fold 4: train tss = 0.6917 : val tss = 0.7334 ::: train hss = 0.2104 : val hss = 0.3066
mean cv TSS: 0.4638
mean cv HSS: 0.1887
173/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.3984 : val tss = -0.0023 ::: train hss = 0.3887 : val hss = -0.0035
Fold 1: train tss = 0.7016 : val tss = 0.2499 ::: train hss = 0.2580 : val hss = 0.1185
Fold 2: train tss = 0.5813 : val tss = 0.6978 ::: train hss = 0.1393 : val hss = 0.3104
Fold 3: train tss = 0.6536 : val tss = 0.1013 ::: train hss = 0.2082 : val hss = 0.0209
Fold 4: train tss = 0.5907 : val tss = 0.5991 ::: train hss = 0.1357 : val hss = 0.1672
mean cv TSS: 0.3292
mean cv HSS: 0.1227
174/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.1500 : val tss = -0.0005 ::: train hss = 0.2609 : val hss = -0.0010
Fold 1: train tss = 0.7755 : val tss = 0.4614 ::: train hss = 0.4200 : val hss = 0.1336
Fold 2: train tss = 0.7840 : val tss = 0.7151 ::: train hss = 0.2793 : val hss = 0.3035
Fold 3: train tss = 0.8192 : val tss = 0.2782 ::: train hss = 0.3286 : val hss = 0.0822
Fold 4: train tss = 0.6804 : val tss = 0.5684 ::: train hss = 0.1923 : val hss = 0.1544
mean cv TSS: 0.4045
mean cv HSS: 0.1346
175/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7658 : val tss = 0.3278 ::: train hss = 0.3765 : val hss = 0.1096
Fold 2: train tss = 0.5990 : val tss = 0.6828 ::: train hss = 0.1235 : val hss = 0.2856
Fold 3: train tss = 0.7332 : val tss = 0.3184 ::: train hss = 0.2629 : val hss = 0.0747
Fold 4: train tss = 0.6920 : val tss = 0.6815 ::: train hss = 0.1784 : val hss = 0.2500
mean cv TSS: 0.4021
mean cv HSS: 0.1440
176/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 145916
Fold 0: train tss = 0.4978 : val tss = 0.2495 ::: train hss = 0.4149 : val hss = 0.1874
Fold 1: train tss = 0.8093 : val tss = 0.2721 ::: train hss = 0.5024 : val hss = 0.3179
Fold 2: train tss = 0.7254 : val tss = 0.7359 ::: train hss = 0.2103 : val hss = 0.4527
Fold 3: train tss = 0.7454 : val tss = 0.0572 ::: train hss = 0.2753 : val hss = 0.0166
Fold 4: train tss = 0.7447 : val tss = 0.6112 ::: train hss = 0.2534 : val hss = 0.2203
mean cv TSS: 0.3852
mean cv HSS: 0.2390
177/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.2910 : val tss = -0.0235 ::: train hss = 0.1152 : val hss = -0.0169
Fold 1: train tss = 0.5204 : val tss = 0.4227 ::: train hss = 0.4100 : val hss = 0.1600
Fold 2: train tss = 0.6533 : val tss = 0.7228 ::: train hss = 0.1801 : val hss = 0.3663
Fold 3: train tss = 0.6955 : val tss = 0.0650 ::: train hss = 0.2517 : val hss = 0.0169
Fold 4: train tss = 0.6346 : val tss = 0.4486 ::: train hss = 0.1420 : val hss = 0.0946
mean cv TSS: 0.3271
mean cv HSS: 0.1242
178/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.7933 : val tss = -0.0180 ::: train hss = 0.3449 : val hss = -0.0208
Fold 1: train tss = 0.8738 : val tss = 0.2379 ::: train hss = 0.4501 : val hss = 0.0989
Fold 2: train tss = 0.7913 : val tss = 0.7219 ::: train hss = 0.2229 : val hss = 0.3427
Fold 3: train tss = 0.8443 : val tss = 0.2565 ::: train hss = 0.3253 : val hss = 0.1410
Fold 4: train tss = 0.8100 : val tss = 0.7340 ::: train hss = 0.2984 : val hss = 0.3051
mean cv TSS: 0.3865
mean cv HSS: 0.1734
179/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.5946 : val tss = 0.0117 ::: train hss = 0.3089 : val hss = 0.0150
Fold 1: train tss = 0.8470 : val tss = 0.2778 ::: train hss = 0.3492 : val hss = 0.1215
Fold 2: train tss = 0.7559 : val tss = 0.6735 ::: train hss = 0.2211 : val hss = 0.3362
Fold 3: train tss = 0.7570 : val tss = 0.3859 ::: train hss = 0.2544 : val hss = 0.0865
Fold 4: train tss = 0.7638 : val tss = 0.6551 ::: train hss = 0.2311 : val hss = 0.2512
mean cv TSS: 0.4008
mean cv HSS: 0.1621
180/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.6476 : val tss = 0.0561 ::: train hss = 0.4887 : val hss = 0.0694
Fold 1: train tss = 0.7666 : val tss = 0.4280 ::: train hss = 0.2852 : val hss = 0.1580
Fold 2: train tss = 0.7376 : val tss = 0.7397 ::: train hss = 0.2636 : val hss = 0.4015
Fold 3: train tss = 0.8148 : val tss = 0.1043 ::: train hss = 0.3324 : val hss = 0.0341
Fold 4: train tss = 0.7584 : val tss = 0.6332 ::: train hss = 0.2958 : val hss = 0.2611
mean cv TSS: 0.3923
mean cv HSS: 0.1848
181/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.1986 : val tss = -0.0014 ::: train hss = 0.2206 : val hss = -0.0026
Fold 1: train tss = 0.7603 : val tss = 0.4943 ::: train hss = 0.3677 : val hss = 0.2120
Fold 2: train tss = 0.6839 : val tss = 0.7470 ::: train hss = 0.2003 : val hss = 0.3689
Fold 3: train tss = 0.7170 : val tss = 0.2254 ::: train hss = 0.2503 : val hss = 0.0423
Fold 4: train tss = 0.6933 : val tss = 0.5682 ::: train hss = 0.2162 : val hss = 0.1487
mean cv TSS: 0.4067
mean cv HSS: 0.1539
182/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.3000 : val tss = -0.0010 ::: train hss = 0.4615 : val hss = -0.0019
Fold 1: train tss = 0.7790 : val tss = 0.3247 ::: train hss = 0.4542 : val hss = 0.1238
Fold 2: train tss = 0.8008 : val tss = 0.6662 ::: train hss = 0.2621 : val hss = 0.3144
Fold 3: train tss = 0.8199 : val tss = 0.2625 ::: train hss = 0.3215 : val hss = 0.0662
Fold 4: train tss = 0.7918 : val tss = 0.6900 ::: train hss = 0.2641 : val hss = 0.3310
mean cv TSS: 0.3885
mean cv HSS: 0.1667
183/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7935 : val tss = 0.4681 ::: train hss = 0.4272 : val hss = 0.1718
Fold 2: train tss = 0.7389 : val tss = 0.7251 ::: train hss = 0.1869 : val hss = 0.3596
Fold 3: train tss = 0.7294 : val tss = 0.0813 ::: train hss = 0.2440 : val hss = 0.0366
Fold 4: train tss = 0.7266 : val tss = 0.7383 ::: train hss = 0.2336 : val hss = 0.3041
mean cv TSS: 0.4026
mean cv HSS: 0.1744
184/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.6807 : val tss = 0.0583 ::: train hss = 0.1404 : val hss = 0.0544
Fold 1: train tss = 0.7995 : val tss = 0.2162 ::: train hss = 0.3212 : val hss = 0.1392
Fold 2: train tss = 0.5240 : val tss = 0.6656 ::: train hss = 0.1162 : val hss = 0.2711
Fold 3: train tss = 0.7200 : val tss = 0.0732 ::: train hss = 0.2529 : val hss = 0.0229
Fold 4: train tss = 0.6810 : val tss = 0.5707 ::: train hss = 0.1790 : val hss = 0.1624
mean cv TSS: 0.3168
mean cv HSS: 0.1300
185/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0499 : val tss = -0.0004 ::: train hss = 0.0907 : val hss = -0.0007
Fold 1: train tss = 0.6087 : val tss = 0.3677 ::: train hss = 0.1539 : val hss = 0.0917
Fold 2: train tss = 0.0400 : val tss = 0.0650 ::: train hss = 0.0389 : val hss = 0.0939
Fold 3: train tss = 0.6356 : val tss = 0.1269 ::: train hss = 0.1900 : val hss = 0.0438
Fold 4: train tss = 0.5847 : val tss = 0.7139 ::: train hss = 0.1497 : val hss = 0.3065
mean cv TSS: 0.2546
mean cv HSS: 0.1070
186/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.8921 : val tss = 0.0155 ::: train hss = 0.3431 : val hss = 0.0221
Fold 1: train tss = 0.8268 : val tss = 0.2648 ::: train hss = 0.2469 : val hss = 0.1492
Fold 2: train tss = 0.7697 : val tss = 0.6916 ::: train hss = 0.2562 : val hss = 0.3006
Fold 3: train tss = 0.7877 : val tss = 0.1260 ::: train hss = 0.3206 : val hss = 0.0486
Fold 4: train tss = 0.7120 : val tss = 0.6814 ::: train hss = 0.2226 : val hss = 0.3122
mean cv TSS: 0.3559
mean cv HSS: 0.1665
187/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7682 : val tss = 0.2729 ::: train hss = 0.4789 : val hss = 0.1313
Fold 2: train tss = 0.7331 : val tss = 0.7363 ::: train hss = 0.2526 : val hss = 0.3459
Fold 3: train tss = 0.7290 : val tss = 0.3338 ::: train hss = 0.2656 : val hss = 0.1108
Fold 4: train tss = 0.6799 : val tss = 0.6571 ::: train hss = 0.1846 : val hss = 0.2147
mean cv TSS: 0.4000
mean cv HSS: 0.1605
188/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.6459 : val tss = 0.0267 ::: train hss = 0.3856 : val hss = 0.0300
Fold 1: train tss = 0.7659 : val tss = 0.2376 ::: train hss = 0.3770 : val hss = 0.1942
Fold 2: train tss = 0.6378 : val tss = 0.7319 ::: train hss = 0.1983 : val hss = 0.3626
Fold 3: train tss = 0.7425 : val tss = 0.1134 ::: train hss = 0.3085 : val hss = 0.0197
Fold 4: train tss = 0.6311 : val tss = 0.6103 ::: train hss = 0.1649 : val hss = 0.1890
mean cv TSS: 0.3440
mean cv HSS: 0.1591
189/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5962 : val tss = 0.3761 ::: train hss = 0.0815 : val hss = 0.0618
Fold 2: train tss = 0.6208 : val tss = 0.7519 ::: train hss = 0.1399 : val hss = 0.4128
Fold 3: train tss = 0.6367 : val tss = 0.0700 ::: train hss = 0.1586 : val hss = 0.0191
Fold 4: train tss = 0.6141 : val tss = 0.5792 ::: train hss = 0.1402 : val hss = 0.1557
mean cv TSS: 0.3554
mean cv HSS: 0.1299
190/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.1500 : val tss = -0.0011 ::: train hss = 0.2609 : val hss = -0.0021
Fold 1: train tss = 0.8111 : val tss = 0.4427 ::: train hss = 0.3382 : val hss = 0.0858
Fold 2: train tss = 0.7890 : val tss = 0.7291 ::: train hss = 0.2543 : val hss = 0.3862
Fold 3: train tss = 0.8047 : val tss = 0.0788 ::: train hss = 0.2881 : val hss = 0.0398
Fold 4: train tss = 0.7444 : val tss = 0.7746 ::: train hss = 0.2144 : val hss = 0.4421
mean cv TSS: 0.4048
mean cv HSS: 0.1903
191/768
{'batch_size': 128, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7837 : val tss = 0.3009 ::: train hss = 0.4582 : val hss = 0.1392
Fold 2: train tss = 0.6637 : val tss = 0.7119 ::: train hss = 0.1962 : val hss = 0.3010
Fold 3: train tss = 0.7402 : val tss = 0.2235 ::: train hss = 0.2145 : val hss = 0.0945
Fold 4: train tss = 0.7096 : val tss = 0.6945 ::: train hss = 0.2095 : val hss = 0.2498
mean cv TSS: 0.3862
mean cv HSS: 0.1569
192/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.8941 : val tss = -0.0027 ::: train hss = 0.4111 : val hss = -0.0036
Fold 1: train tss = 0.8197 : val tss = 0.3249 ::: train hss = 0.3167 : val hss = 0.1442
Fold 2: train tss = 0.7703 : val tss = 0.6688 ::: train hss = 0.2390 : val hss = 0.2624
Fold 3: train tss = 0.7327 : val tss = 0.5581 ::: train hss = 0.1883 : val hss = 0.0652
Fold 4: train tss = 0.7045 : val tss = 0.5859 ::: train hss = 0.2037 : val hss = 0.2079
mean cv TSS: 0.4270
mean cv HSS: 0.1352
193/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.8331 : val tss = -0.0219 ::: train hss = 0.1883 : val hss = -0.0161
Fold 1: train tss = 0.8183 : val tss = 0.2283 ::: train hss = 0.4177 : val hss = 0.1236
Fold 2: train tss = 0.7260 : val tss = 0.7572 ::: train hss = 0.1887 : val hss = 0.3957
Fold 3: train tss = 0.7010 : val tss = 0.3566 ::: train hss = 0.1951 : val hss = 0.0451
Fold 4: train tss = 0.6829 : val tss = 0.5583 ::: train hss = 0.1666 : val hss = 0.1641
mean cv TSS: 0.3757
mean cv HSS: 0.1425
194/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9803 : val tss = 0.1577 ::: train hss = 0.1922 : val hss = 0.0808
Fold 1: train tss = 0.9168 : val tss = 0.4214 ::: train hss = 0.3841 : val hss = 0.1584
Fold 2: train tss = 0.7727 : val tss = 0.6781 ::: train hss = 0.1795 : val hss = 0.2673
Fold 3: train tss = 0.7523 : val tss = 0.2322 ::: train hss = 0.2033 : val hss = 0.0381
Fold 4: train tss = 0.7746 : val tss = 0.6965 ::: train hss = 0.2148 : val hss = 0.2507
mean cv TSS: 0.4372
mean cv HSS: 0.1591
195/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.8335 : val tss = -0.0075 ::: train hss = 0.1916 : val hss = -0.0071
Fold 1: train tss = 0.8504 : val tss = 0.2627 ::: train hss = 0.2559 : val hss = 0.0597
Fold 2: train tss = 0.7483 : val tss = 0.6518 ::: train hss = 0.1440 : val hss = 0.2473
Fold 3: train tss = 0.7197 : val tss = 0.3253 ::: train hss = 0.1857 : val hss = 0.0511
Fold 4: train tss = 0.7586 : val tss = 0.5796 ::: train hss = 0.1876 : val hss = 0.1935
mean cv TSS: 0.3624
mean cv HSS: 0.1089
196/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.8861 : val tss = 0.0022 ::: train hss = 0.2317 : val hss = 0.0012
Fold 1: train tss = 0.8017 : val tss = 0.1092 ::: train hss = 0.3330 : val hss = 0.0915
Fold 2: train tss = 0.7274 : val tss = 0.6088 ::: train hss = 0.2166 : val hss = 0.1931
Fold 3: train tss = 0.7383 : val tss = 0.2882 ::: train hss = 0.1886 : val hss = 0.0782
Fold 4: train tss = 0.7079 : val tss = 0.6748 ::: train hss = 0.1619 : val hss = 0.2677
mean cv TSS: 0.3366
mean cv HSS: 0.1264
197/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.5305 : val tss = 0.0762 ::: train hss = 0.1099 : val hss = 0.0621
Fold 1: train tss = 0.7432 : val tss = 0.0512 ::: train hss = 0.2090 : val hss = 0.0184
Fold 2: train tss = 0.5207 : val tss = 0.6745 ::: train hss = 0.0650 : val hss = 0.2625
Fold 3: train tss = 0.6458 : val tss = 0.3401 ::: train hss = 0.1510 : val hss = 0.0661
Fold 4: train tss = 0.5732 : val tss = 0.5840 ::: train hss = 0.1066 : val hss = 0.1556
mean cv TSS: 0.3452
mean cv HSS: 0.1130
198/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 103269
Fold 0: train tss = 0.6440 : val tss = -0.0112 ::: train hss = 0.3104 : val hss = -0.0154
Fold 1: train tss = 0.8009 : val tss = 0.2836 ::: train hss = 0.3073 : val hss = 0.1012
Fold 2: train tss = 0.7421 : val tss = 0.7079 ::: train hss = 0.1426 : val hss = 0.3125
Fold 3: train tss = 0.7316 : val tss = 0.3936 ::: train hss = 0.1831 : val hss = 0.0498
Fold 4: train tss = 0.7389 : val tss = 0.6957 ::: train hss = 0.1841 : val hss = 0.2660
mean cv TSS: 0.4139
mean cv HSS: 0.1428
199/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.5952 : val tss = 0.0942 ::: train hss = 0.3307 : val hss = 0.0880
Fold 1: train tss = 0.7763 : val tss = 0.2502 ::: train hss = 0.3334 : val hss = 0.1072
Fold 2: train tss = 0.6401 : val tss = 0.6218 ::: train hss = 0.0849 : val hss = 0.2003
Fold 3: train tss = 0.6531 : val tss = 0.2861 ::: train hss = 0.1217 : val hss = 0.0351
Fold 4: train tss = 0.6243 : val tss = 0.5854 ::: train hss = 0.1021 : val hss = 0.1672
mean cv TSS: 0.3675
mean cv HSS: 0.1196
200/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.6812 : val tss = 0.2458 ::: train hss = 0.1434 : val hss = 0.0864
Fold 1: train tss = 0.8305 : val tss = 0.4039 ::: train hss = 0.2585 : val hss = 0.2192
Fold 2: train tss = 0.7027 : val tss = 0.6948 ::: train hss = 0.1583 : val hss = 0.3161
Fold 3: train tss = 0.7182 : val tss = 0.3094 ::: train hss = 0.2270 : val hss = 0.0424
Fold 4: train tss = 0.7002 : val tss = 0.6582 ::: train hss = 0.1591 : val hss = 0.2368
mean cv TSS: 0.4624
mean cv HSS: 0.1802
201/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.1470 : val tss = 0.0012 ::: train hss = 0.1225 : val hss = 0.0018
Fold 1: train tss = 0.8139 : val tss = 0.2603 ::: train hss = 0.3088 : val hss = 0.2972
Fold 2: train tss = 0.5219 : val tss = 0.6317 ::: train hss = 0.0590 : val hss = 0.2063
Fold 3: train tss = 0.6329 : val tss = 0.2507 ::: train hss = 0.1457 : val hss = 0.0232
Fold 4: train tss = 0.6150 : val tss = 0.6402 ::: train hss = 0.1314 : val hss = 0.2100
mean cv TSS: 0.3568
mean cv HSS: 0.1477
202/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9318 : val tss = -0.0403 ::: train hss = 0.1962 : val hss = -0.0265
Fold 1: train tss = 0.9084 : val tss = 0.2967 ::: train hss = 0.3366 : val hss = 0.0827
Fold 2: train tss = 0.7812 : val tss = 0.6450 ::: train hss = 0.1403 : val hss = 0.2736
Fold 3: train tss = 0.7754 : val tss = 0.0693 ::: train hss = 0.2198 : val hss = 0.0207
Fold 4: train tss = 0.6636 : val tss = 0.6348 ::: train hss = 0.1292 : val hss = 0.1921
mean cv TSS: 0.3211
mean cv HSS: 0.1085
203/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.4942 : val tss = -0.0091 ::: train hss = 0.2534 : val hss = -0.0037
Fold 1: train tss = 0.6381 : val tss = 0.3680 ::: train hss = 0.1018 : val hss = 0.0448
Fold 2: train tss = 0.6725 : val tss = 0.6761 ::: train hss = 0.1086 : val hss = 0.2751
Fold 3: train tss = 0.6671 : val tss = 0.2755 ::: train hss = 0.1346 : val hss = 0.0533
Fold 4: train tss = 0.6855 : val tss = 0.6014 ::: train hss = 0.1513 : val hss = 0.1753
mean cv TSS: 0.3824
mean cv HSS: 0.1090
204/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.5919 : val tss = -0.0173 ::: train hss = 0.2392 : val hss = -0.0182
Fold 1: train tss = 0.7581 : val tss = 0.3372 ::: train hss = 0.2674 : val hss = 0.1400
Fold 2: train tss = 0.6189 : val tss = 0.6460 ::: train hss = 0.0947 : val hss = 0.2192
Fold 3: train tss = 0.6362 : val tss = 0.2975 ::: train hss = 0.1518 : val hss = 0.0268
Fold 4: train tss = 0.6835 : val tss = 0.6188 ::: train hss = 0.1592 : val hss = 0.1944
mean cv TSS: 0.3764
mean cv HSS: 0.1124
205/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.4196 : val tss = 0.1815 ::: train hss = 0.0597 : val hss = 0.1084
Fold 1: train tss = 0.4243 : val tss = 0.3565 ::: train hss = 0.0601 : val hss = 0.0765
Fold 2: train tss = 0.4990 : val tss = 0.6919 ::: train hss = 0.0599 : val hss = 0.2867
Fold 3: train tss = 0.5774 : val tss = 0.3199 ::: train hss = 0.1034 : val hss = 0.0513
Fold 4: train tss = 0.4718 : val tss = 0.5591 ::: train hss = 0.0637 : val hss = 0.1439
mean cv TSS: 0.4217
mean cv HSS: 0.1334
206/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.8428 : val tss = 0.0142 ::: train hss = 0.3475 : val hss = 0.0137
Fold 1: train tss = 0.8700 : val tss = 0.3071 ::: train hss = 0.3865 : val hss = 0.1280
Fold 2: train tss = 0.7763 : val tss = 0.6613 ::: train hss = 0.1819 : val hss = 0.2546
Fold 3: train tss = 0.7547 : val tss = 0.2784 ::: train hss = 0.1902 : val hss = 0.0589
Fold 4: train tss = 0.7284 : val tss = 0.6828 ::: train hss = 0.1758 : val hss = 0.2346
mean cv TSS: 0.3888
mean cv HSS: 0.1380
207/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.2000 : val tss = -0.0002 ::: train hss = 0.3333 : val hss = -0.0005
Fold 1: train tss = 0.8052 : val tss = 0.3315 ::: train hss = 0.3827 : val hss = 0.1286
Fold 2: train tss = 0.4736 : val tss = 0.5489 ::: train hss = 0.0495 : val hss = 0.1547
Fold 3: train tss = 0.6332 : val tss = 0.1052 ::: train hss = 0.1281 : val hss = 0.0208
Fold 4: train tss = 0.6150 : val tss = 0.4859 ::: train hss = 0.0992 : val hss = 0.1134
mean cv TSS: 0.2942
mean cv HSS: 0.0834
208/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.6854 : val tss = 0.0554 ::: train hss = 0.1769 : val hss = 0.0154
Fold 1: train tss = 0.7381 : val tss = 0.3982 ::: train hss = 0.1804 : val hss = 0.1178
Fold 2: train tss = 0.7301 : val tss = 0.5382 ::: train hss = 0.1629 : val hss = 0.1589
Fold 3: train tss = 0.7455 : val tss = 0.1074 ::: train hss = 0.2125 : val hss = 0.0190
Fold 4: train tss = 0.7346 : val tss = 0.6393 ::: train hss = 0.1751 : val hss = 0.2120
mean cv TSS: 0.3477
mean cv HSS: 0.1046
209/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 62796
Fold 0: train tss = 0.7340 : val tss = 0.3647 ::: train hss = 0.1748 : val hss = 0.1743
Fold 1: train tss = 0.7832 : val tss = 0.4216 ::: train hss = 0.2847 : val hss = 0.1804
Fold 2: train tss = 0.7236 : val tss = 0.6660 ::: train hss = 0.1752 : val hss = 0.2850
Fold 3: train tss = 0.7523 : val tss = 0.1228 ::: train hss = 0.2321 : val hss = 0.0363
Fold 4: train tss = 0.6911 : val tss = 0.5787 ::: train hss = 0.1590 : val hss = 0.1641
mean cv TSS: 0.4308
mean cv HSS: 0.1680
210/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9880 : val tss = -0.0164 ::: train hss = 0.2823 : val hss = -0.0158
Fold 1: train tss = 0.9242 : val tss = 0.3950 ::: train hss = 0.4044 : val hss = 0.1043
Fold 2: train tss = 0.7943 : val tss = 0.6238 ::: train hss = 0.1827 : val hss = 0.2381
Fold 3: train tss = 0.7722 : val tss = 0.5174 ::: train hss = 0.2194 : val hss = 0.0736
Fold 4: train tss = 0.7537 : val tss = 0.7232 ::: train hss = 0.1839 : val hss = 0.3813
mean cv TSS: 0.4486
mean cv HSS: 0.1563
211/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.9388 : val tss = 0.0264 ::: train hss = 0.2845 : val hss = 0.0334
Fold 1: train tss = 0.8361 : val tss = 0.3952 ::: train hss = 0.2500 : val hss = 0.1256
Fold 2: train tss = 0.6896 : val tss = 0.6638 ::: train hss = 0.1137 : val hss = 0.2430
Fold 3: train tss = 0.7158 : val tss = 0.2317 ::: train hss = 0.1659 : val hss = 0.0379
Fold 4: train tss = 0.7147 : val tss = 0.6295 ::: train hss = 0.1683 : val hss = 0.2132
mean cv TSS: 0.3893
mean cv HSS: 0.1306
212/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.6975 : val tss = 0.0023 ::: train hss = 0.5073 : val hss = 0.0024
Fold 1: train tss = 0.8176 : val tss = 0.2311 ::: train hss = 0.3515 : val hss = 0.3223
Fold 2: train tss = 0.6603 : val tss = 0.6830 ::: train hss = 0.1080 : val hss = 0.2666
Fold 3: train tss = 0.7663 : val tss = 0.2063 ::: train hss = 0.2406 : val hss = 0.0341
Fold 4: train tss = 0.6952 : val tss = 0.6623 ::: train hss = 0.1550 : val hss = 0.2764
mean cv TSS: 0.3570
mean cv HSS: 0.1804
213/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.5951 : val tss = 0.0683 ::: train hss = 0.3261 : val hss = 0.0785
Fold 1: train tss = 0.7454 : val tss = 0.1155 ::: train hss = 0.2253 : val hss = 0.0382
Fold 2: train tss = 0.6526 : val tss = 0.7108 ::: train hss = 0.1476 : val hss = 0.3011
Fold 3: train tss = 0.6584 : val tss = 0.1024 ::: train hss = 0.1465 : val hss = 0.0120
Fold 4: train tss = 0.5977 : val tss = 0.6060 ::: train hss = 0.1145 : val hss = 0.1760
mean cv TSS: 0.3206
mean cv HSS: 0.1211
214/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.7465 : val tss = -0.0122 ::: train hss = 0.4666 : val hss = -0.0163
Fold 1: train tss = 0.8158 : val tss = 0.2665 ::: train hss = 0.3408 : val hss = 0.0936
Fold 2: train tss = 0.7324 : val tss = 0.6718 ::: train hss = 0.1305 : val hss = 0.3139
Fold 3: train tss = 0.6338 : val tss = 0.3523 ::: train hss = 0.1056 : val hss = 0.0499
Fold 4: train tss = 0.7089 : val tss = 0.6166 ::: train hss = 0.1551 : val hss = 0.1884
mean cv TSS: 0.3790
mean cv HSS: 0.1259
215/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.7433 : val tss = 0.0202 ::: train hss = 0.3267 : val hss = 0.0333
Fold 1: train tss = 0.7893 : val tss = 0.3181 ::: train hss = 0.2462 : val hss = 0.1066
Fold 2: train tss = 0.6126 : val tss = 0.6292 ::: train hss = 0.0749 : val hss = 0.2098
Fold 3: train tss = 0.6722 : val tss = 0.4127 ::: train hss = 0.1422 : val hss = 0.0417
Fold 4: train tss = 0.6778 : val tss = 0.6535 ::: train hss = 0.1345 : val hss = 0.2145
mean cv TSS: 0.4068
mean cv HSS: 0.1212
216/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.7893 : val tss = 0.0624 ::: train hss = 0.2526 : val hss = 0.0915
Fold 1: train tss = 0.8050 : val tss = 0.1564 ::: train hss = 0.3279 : val hss = 0.1250
Fold 2: train tss = 0.6184 : val tss = 0.6532 ::: train hss = 0.0965 : val hss = 0.2687
Fold 3: train tss = 0.7140 : val tss = 0.2634 ::: train hss = 0.2104 : val hss = 0.0469
Fold 4: train tss = 0.6560 : val tss = 0.6034 ::: train hss = 0.1399 : val hss = 0.1704
mean cv TSS: 0.3477
mean cv HSS: 0.1405
217/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.8711 : val tss = 0.0434 ::: train hss = 0.1253 : val hss = 0.0154
Fold 1: train tss = 0.7824 : val tss = 0.1663 ::: train hss = 0.3448 : val hss = 0.2203
Fold 2: train tss = 0.6994 : val tss = 0.5772 ::: train hss = 0.1474 : val hss = 0.1763
Fold 3: train tss = 0.6080 : val tss = 0.1041 ::: train hss = 0.1248 : val hss = 0.0181
Fold 4: train tss = 0.6185 : val tss = 0.6109 ::: train hss = 0.1169 : val hss = 0.2431
mean cv TSS: 0.3004
mean cv HSS: 0.1346
218/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9895 : val tss = -0.0214 ::: train hss = 0.3117 : val hss = -0.0148
Fold 1: train tss = 0.8416 : val tss = 0.2418 ::: train hss = 0.2544 : val hss = 0.1137
Fold 2: train tss = 0.6892 : val tss = 0.5814 ::: train hss = 0.1055 : val hss = 0.1842
Fold 3: train tss = 0.7584 : val tss = 0.2736 ::: train hss = 0.2011 : val hss = 0.0522
Fold 4: train tss = 0.6974 : val tss = 0.6644 ::: train hss = 0.1495 : val hss = 0.2275
mean cv TSS: 0.3479
mean cv HSS: 0.1126
219/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.7918 : val tss = -0.0130 ::: train hss = 0.3045 : val hss = -0.0150
Fold 1: train tss = 0.8162 : val tss = 0.3486 ::: train hss = 0.2528 : val hss = 0.1642
Fold 2: train tss = 0.6575 : val tss = 0.6572 ::: train hss = 0.0933 : val hss = 0.2419
Fold 3: train tss = 0.6464 : val tss = 0.5205 ::: train hss = 0.1302 : val hss = 0.0582
Fold 4: train tss = 0.6975 : val tss = 0.6438 ::: train hss = 0.1497 : val hss = 0.2043
mean cv TSS: 0.4314
mean cv HSS: 0.1307
220/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 62796
Fold 0: train tss = 0.9899 : val tss = 0.0135 ::: train hss = 0.3193 : val hss = 0.0081
Fold 1: train tss = 0.7924 : val tss = 0.1061 ::: train hss = 0.4169 : val hss = 0.1652
Fold 2: train tss = 0.5999 : val tss = 0.4653 ::: train hss = 0.0919 : val hss = 0.1133
Fold 3: train tss = 0.6176 : val tss = 0.3557 ::: train hss = 0.1154 : val hss = 0.0369
Fold 4: train tss = 0.6394 : val tss = 0.5123 ::: train hss = 0.1209 : val hss = 0.1299
mean cv TSS: 0.2906
mean cv HSS: 0.0907
221/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.4902 : val tss = 0.2331 ::: train hss = 0.1767 : val hss = 0.2479
Fold 1: train tss = 0.7554 : val tss = 0.3519 ::: train hss = 0.2914 : val hss = 0.2111
Fold 2: train tss = 0.5149 : val tss = 0.6120 ::: train hss = 0.0682 : val hss = 0.1955
Fold 3: train tss = 0.5492 : val tss = 0.3560 ::: train hss = 0.0931 : val hss = 0.0414
Fold 4: train tss = 0.5402 : val tss = 0.5417 ::: train hss = 0.0860 : val hss = 0.1357
mean cv TSS: 0.4189
mean cv HSS: 0.1663
222/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9423 : val tss = -0.0161 ::: train hss = 0.3659 : val hss = -0.0195
Fold 1: train tss = 0.8074 : val tss = 0.2755 ::: train hss = 0.2810 : val hss = 0.0918
Fold 2: train tss = 0.7459 : val tss = 0.6821 ::: train hss = 0.1433 : val hss = 0.2553
Fold 3: train tss = 0.6662 : val tss = 0.4075 ::: train hss = 0.1319 : val hss = 0.0485
Fold 4: train tss = 0.7490 : val tss = 0.6412 ::: train hss = 0.2178 : val hss = 0.2350
mean cv TSS: 0.3980
mean cv HSS: 0.1222
223/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.5928 : val tss = -0.0160 ::: train hss = 0.2577 : val hss = -0.0156
Fold 1: train tss = 0.7875 : val tss = 0.2744 ::: train hss = 0.3783 : val hss = 0.1053
Fold 2: train tss = 0.6940 : val tss = 0.6006 ::: train hss = 0.1173 : val hss = 0.1922
Fold 3: train tss = 0.6987 : val tss = 0.4373 ::: train hss = 0.1546 : val hss = 0.0780
Fold 4: train tss = 0.6545 : val tss = 0.7217 ::: train hss = 0.1242 : val hss = 0.3393
mean cv TSS: 0.4036
mean cv HSS: 0.1399
224/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.8373 : val tss = 0.2472 ::: train hss = 0.2359 : val hss = 0.1382
Fold 1: train tss = 0.8115 : val tss = 0.1930 ::: train hss = 0.2649 : val hss = 0.1182
Fold 2: train tss = 0.6825 : val tss = 0.5933 ::: train hss = 0.1153 : val hss = 0.2033
Fold 3: train tss = 0.7092 : val tss = 0.3604 ::: train hss = 0.2040 : val hss = 0.0485
Fold 4: train tss = 0.6731 : val tss = 0.5806 ::: train hss = 0.1358 : val hss = 0.1641
mean cv TSS: 0.3949
mean cv HSS: 0.1344
225/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.4453 : val tss = 0.0027 ::: train hss = 0.2619 : val hss = 0.0031
Fold 1: train tss = 0.7852 : val tss = 0.3916 ::: train hss = 0.2602 : val hss = 0.1718
Fold 2: train tss = 0.6554 : val tss = 0.6946 ::: train hss = 0.1312 : val hss = 0.3485
Fold 3: train tss = 0.6657 : val tss = 0.0579 ::: train hss = 0.1640 : val hss = 0.0141
Fold 4: train tss = 0.6473 : val tss = 0.6270 ::: train hss = 0.1318 : val hss = 0.2075
mean cv TSS: 0.3548
mean cv HSS: 0.1490
226/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9352 : val tss = -0.0228 ::: train hss = 0.2309 : val hss = -0.0166
Fold 1: train tss = 0.8804 : val tss = 0.3504 ::: train hss = 0.2878 : val hss = 0.1324
Fold 2: train tss = 0.7688 : val tss = 0.6456 ::: train hss = 0.1541 : val hss = 0.2267
Fold 3: train tss = 0.7566 : val tss = 0.3111 ::: train hss = 0.1993 : val hss = 0.0451
Fold 4: train tss = 0.7310 : val tss = 0.6202 ::: train hss = 0.1565 : val hss = 0.1948
mean cv TSS: 0.3809
mean cv HSS: 0.1165
227/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.8400 : val tss = -0.0297 ::: train hss = 0.2800 : val hss = -0.0247
Fold 1: train tss = 0.7617 : val tss = 0.3061 ::: train hss = 0.5055 : val hss = 0.1245
Fold 2: train tss = 0.6957 : val tss = 0.5510 ::: train hss = 0.1025 : val hss = 0.1832
Fold 3: train tss = 0.7187 : val tss = 0.1931 ::: train hss = 0.1804 : val hss = 0.0268
Fold 4: train tss = 0.6864 : val tss = 0.6186 ::: train hss = 0.1324 : val hss = 0.1936
mean cv TSS: 0.3278
mean cv HSS: 0.1007
228/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.6382 : val tss = 0.1801 ::: train hss = 0.1949 : val hss = 0.1293
Fold 1: train tss = 0.8164 : val tss = 0.2190 ::: train hss = 0.3713 : val hss = 0.1984
Fold 2: train tss = 0.6740 : val tss = 0.6901 ::: train hss = 0.1308 : val hss = 0.3247
Fold 3: train tss = 0.7041 : val tss = 0.2205 ::: train hss = 0.2270 : val hss = 0.0456
Fold 4: train tss = 0.6390 : val tss = 0.6619 ::: train hss = 0.1280 : val hss = 0.2487
mean cv TSS: 0.3943
mean cv HSS: 0.1893
229/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.6388 : val tss = 0.0950 ::: train hss = 0.2028 : val hss = 0.0755
Fold 1: train tss = 0.7528 : val tss = 0.2105 ::: train hss = 0.2028 : val hss = 0.1162
Fold 2: train tss = 0.6421 : val tss = 0.6905 ::: train hss = 0.1010 : val hss = 0.2811
Fold 3: train tss = 0.6403 : val tss = 0.0999 ::: train hss = 0.1595 : val hss = 0.0256
Fold 4: train tss = 0.6224 : val tss = 0.6466 ::: train hss = 0.1194 : val hss = 0.2143
mean cv TSS: 0.3485
mean cv HSS: 0.1425
230/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.3970 : val tss = -0.0069 ::: train hss = 0.2996 : val hss = -0.0108
Fold 1: train tss = 0.7793 : val tss = 0.3450 ::: train hss = 0.2286 : val hss = 0.1119
Fold 2: train tss = 0.7261 : val tss = 0.7078 ::: train hss = 0.1291 : val hss = 0.2890
Fold 3: train tss = 0.7185 : val tss = 0.3103 ::: train hss = 0.1701 : val hss = 0.0471
Fold 4: train tss = 0.6717 : val tss = 0.6968 ::: train hss = 0.1392 : val hss = 0.2620
mean cv TSS: 0.4106
mean cv HSS: 0.1398
231/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 103269
Fold 0: train tss = 0.0998 : val tss = 0.0142 ::: train hss = 0.1663 : val hss = 0.0272
Fold 1: train tss = 0.7509 : val tss = 0.3842 ::: train hss = 0.1682 : val hss = 0.1473
Fold 2: train tss = 0.6447 : val tss = 0.5916 ::: train hss = 0.0955 : val hss = 0.1800
Fold 3: train tss = 0.6967 : val tss = 0.1915 ::: train hss = 0.1568 : val hss = 0.0366
Fold 4: train tss = 0.6400 : val tss = 0.5814 ::: train hss = 0.1207 : val hss = 0.1845
mean cv TSS: 0.3526
mean cv HSS: 0.1151
232/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.9789 : val tss = -0.0467 ::: train hss = 0.1821 : val hss = -0.0266
Fold 1: train tss = 0.8153 : val tss = 0.3354 ::: train hss = 0.2159 : val hss = 0.1142
Fold 2: train tss = 0.6768 : val tss = 0.6696 ::: train hss = 0.1393 : val hss = 0.2705
Fold 3: train tss = 0.6581 : val tss = 0.1331 ::: train hss = 0.1540 : val hss = 0.0180
Fold 4: train tss = 0.6712 : val tss = 0.6280 ::: train hss = 0.1753 : val hss = 0.2039
mean cv TSS: 0.3439
mean cv HSS: 0.1160
233/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.3918 : val tss = 0.2597 ::: train hss = 0.1633 : val hss = 0.2118
Fold 1: train tss = 0.7622 : val tss = 0.2214 ::: train hss = 0.4169 : val hss = 0.1978
Fold 2: train tss = 0.4885 : val tss = 0.6192 ::: train hss = 0.0743 : val hss = 0.2169
Fold 3: train tss = 0.6555 : val tss = 0.0978 ::: train hss = 0.1498 : val hss = 0.0246
Fold 4: train tss = 0.4114 : val tss = 0.5058 ::: train hss = 0.0484 : val hss = 0.1407
mean cv TSS: 0.3408
mean cv HSS: 0.1584
234/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9837 : val tss = -0.0358 ::: train hss = 0.2249 : val hss = -0.0270
Fold 1: train tss = 0.8862 : val tss = 0.3033 ::: train hss = 0.2941 : val hss = 0.0997
Fold 2: train tss = 0.7569 : val tss = 0.6559 ::: train hss = 0.1262 : val hss = 0.2823
Fold 3: train tss = 0.7469 : val tss = 0.3154 ::: train hss = 0.1720 : val hss = 0.0854
Fold 4: train tss = 0.7276 : val tss = 0.6691 ::: train hss = 0.1716 : val hss = 0.2327
mean cv TSS: 0.3816
mean cv HSS: 0.1346
235/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0992 : val tss = -0.0005 ::: train hss = 0.1368 : val hss = -0.0010
Fold 1: train tss = 0.7687 : val tss = 0.3763 ::: train hss = 0.2117 : val hss = 0.1241
Fold 2: train tss = 0.6404 : val tss = 0.5798 ::: train hss = 0.0988 : val hss = 0.1713
Fold 3: train tss = 0.6658 : val tss = 0.2929 ::: train hss = 0.1331 : val hss = 0.0529
Fold 4: train tss = 0.5630 : val tss = 0.5678 ::: train hss = 0.0985 : val hss = 0.1478
mean cv TSS: 0.3633
mean cv HSS: 0.0990
236/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.7729 : val tss = -0.0431 ::: train hss = 0.1185 : val hss = -0.0292
Fold 1: train tss = 0.6522 : val tss = 0.3738 ::: train hss = 0.0963 : val hss = 0.0802
Fold 2: train tss = 0.6358 : val tss = 0.5181 ::: train hss = 0.1146 : val hss = 0.3438
Fold 3: train tss = 0.6371 : val tss = 0.3152 ::: train hss = 0.1286 : val hss = 0.0334
Fold 4: train tss = 0.6426 : val tss = 0.6270 ::: train hss = 0.1243 : val hss = 0.2075
mean cv TSS: 0.3582
mean cv HSS: 0.1271
237/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.5278 : val tss = -0.0365 ::: train hss = 0.0982 : val hss = -0.0253
Fold 1: train tss = 0.5001 : val tss = 0.4166 ::: train hss = 0.0377 : val hss = 0.0602
Fold 2: train tss = 0.5392 : val tss = 0.5919 ::: train hss = 0.0752 : val hss = 0.1809
Fold 3: train tss = 0.5426 : val tss = 0.2653 ::: train hss = 0.0912 : val hss = 0.0350
Fold 4: train tss = 0.5489 : val tss = 0.4846 ::: train hss = 0.0852 : val hss = 0.1073
mean cv TSS: 0.3444
mean cv HSS: 0.0716
238/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.7975 : val tss = 0.0576 ::: train hss = 0.5596 : val hss = 0.0584
Fold 1: train tss = 0.8234 : val tss = 0.3035 ::: train hss = 0.2493 : val hss = 0.1174
Fold 2: train tss = 0.7346 : val tss = 0.6961 ::: train hss = 0.1550 : val hss = 0.2989
Fold 3: train tss = 0.7123 : val tss = 0.2480 ::: train hss = 0.1627 : val hss = 0.0596
Fold 4: train tss = 0.7054 : val tss = 0.6428 ::: train hss = 0.1511 : val hss = 0.2104
mean cv TSS: 0.3896
mean cv HSS: 0.1489
239/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.3976 : val tss = 0.0110 ::: train hss = 0.3313 : val hss = 0.0187
Fold 1: train tss = 0.6995 : val tss = 0.3374 ::: train hss = 0.1554 : val hss = 0.0833
Fold 2: train tss = 0.5723 : val tss = 0.4218 ::: train hss = 0.0765 : val hss = 0.0947
Fold 3: train tss = 0.6236 : val tss = 0.3550 ::: train hss = 0.1112 : val hss = 0.0565
Fold 4: train tss = 0.6660 : val tss = 0.7310 ::: train hss = 0.1377 : val hss = 0.3030
mean cv TSS: 0.3712
mean cv HSS: 0.1112
240/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.9761 : val tss = 0.1957 ::: train hss = 0.1641 : val hss = 0.1153
Fold 1: train tss = 0.8078 : val tss = 0.1184 ::: train hss = 0.4021 : val hss = 0.0514
Fold 2: train tss = 0.6723 : val tss = 0.5859 ::: train hss = 0.1152 : val hss = 0.2014
Fold 3: train tss = 0.7241 : val tss = 0.0433 ::: train hss = 0.2158 : val hss = 0.0147
Fold 4: train tss = 0.6951 : val tss = 0.6278 ::: train hss = 0.1722 : val hss = 0.1994
mean cv TSS: 0.3142
mean cv HSS: 0.1165
241/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.6835 : val tss = 0.2727 ::: train hss = 0.1599 : val hss = 0.1525
Fold 1: train tss = 0.7638 : val tss = 0.3960 ::: train hss = 0.1636 : val hss = 0.1616
Fold 2: train tss = 0.6784 : val tss = 0.6790 ::: train hss = 0.1658 : val hss = 0.2938
Fold 3: train tss = 0.7017 : val tss = 0.6211 ::: train hss = 0.1787 : val hss = 0.0504
Fold 4: train tss = 0.6419 : val tss = 0.6226 ::: train hss = 0.1263 : val hss = 0.2040
mean cv TSS: 0.5183
mean cv HSS: 0.1725
242/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 137573
Fold 0: train tss = 0.9772 : val tss = -0.0346 ::: train hss = 0.1707 : val hss = -0.0191
Fold 1: train tss = 0.8556 : val tss = 0.4306 ::: train hss = 0.2734 : val hss = 0.1438
Fold 2: train tss = 0.7715 : val tss = 0.6823 ::: train hss = 0.1658 : val hss = 0.2694
Fold 3: train tss = 0.7031 : val tss = 0.2985 ::: train hss = 0.1532 : val hss = 0.0470
Fold 4: train tss = 0.7423 : val tss = 0.6619 ::: train hss = 0.1701 : val hss = 0.2195
mean cv TSS: 0.4077
mean cv HSS: 0.1321
243/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.9741 : val tss = -0.0359 ::: train hss = 0.1528 : val hss = -0.0293
Fold 1: train tss = 0.8521 : val tss = 0.3703 ::: train hss = 0.2486 : val hss = 0.1124
Fold 2: train tss = 0.7032 : val tss = 0.6240 ::: train hss = 0.1086 : val hss = 0.2081
Fold 3: train tss = 0.7312 : val tss = 0.0628 ::: train hss = 0.1769 : val hss = 0.0194
Fold 4: train tss = 0.6775 : val tss = 0.5567 ::: train hss = 0.1381 : val hss = 0.1465
mean cv TSS: 0.3156
mean cv HSS: 0.0914
244/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.5386 : val tss = 0.1499 ::: train hss = 0.1710 : val hss = 0.1082
Fold 1: train tss = 0.8362 : val tss = 0.1647 ::: train hss = 0.3363 : val hss = 0.1503
Fold 2: train tss = 0.6920 : val tss = 0.6733 ::: train hss = 0.1357 : val hss = 0.2623
Fold 3: train tss = 0.7007 : val tss = 0.2816 ::: train hss = 0.1809 : val hss = 0.0385
Fold 4: train tss = 0.6743 : val tss = 0.6188 ::: train hss = 0.1485 : val hss = 0.2091
mean cv TSS: 0.3777
mean cv HSS: 0.1537
245/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.6743 : val tss = -0.0209 ::: train hss = 0.1092 : val hss = -0.0204
Fold 1: train tss = 0.7451 : val tss = 0.3120 ::: train hss = 0.1592 : val hss = 0.1392
Fold 2: train tss = 0.6196 : val tss = 0.6955 ::: train hss = 0.0978 : val hss = 0.2856
Fold 3: train tss = 0.5945 : val tss = 0.2397 ::: train hss = 0.1269 : val hss = 0.0177
Fold 4: train tss = 0.5753 : val tss = 0.5452 ::: train hss = 0.0928 : val hss = 0.1402
mean cv TSS: 0.3543
mean cv HSS: 0.1125
246/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.5969 : val tss = -0.0016 ::: train hss = 0.4116 : val hss = -0.0022
Fold 1: train tss = 0.7739 : val tss = 0.3562 ::: train hss = 0.2252 : val hss = 0.1412
Fold 2: train tss = 0.7269 : val tss = 0.6762 ::: train hss = 0.1364 : val hss = 0.2630
Fold 3: train tss = 0.7285 : val tss = 0.1997 ::: train hss = 0.1845 : val hss = 0.0379
Fold 4: train tss = 0.7451 : val tss = 0.7294 ::: train hss = 0.2018 : val hss = 0.3179
mean cv TSS: 0.3920
mean cv HSS: 0.1515
247/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.1482 : val tss = -0.0071 ::: train hss = 0.1560 : val hss = -0.0111
Fold 1: train tss = 0.8085 : val tss = 0.4483 ::: train hss = 0.2416 : val hss = 0.1394
Fold 2: train tss = 0.6411 : val tss = 0.6310 ::: train hss = 0.0938 : val hss = 0.2096
Fold 3: train tss = 0.5794 : val tss = 0.3378 ::: train hss = 0.0931 : val hss = 0.0607
Fold 4: train tss = 0.6192 : val tss = 0.5466 ::: train hss = 0.1156 : val hss = 0.1394
mean cv TSS: 0.3913
mean cv HSS: 0.1076
248/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.6280 : val tss = 0.1300 ::: train hss = 0.1163 : val hss = 0.0519
Fold 1: train tss = 0.8006 : val tss = 0.2507 ::: train hss = 0.2870 : val hss = 0.1486
Fold 2: train tss = 0.6423 : val tss = 0.6313 ::: train hss = 0.0997 : val hss = 0.2245
Fold 3: train tss = 0.7175 : val tss = 0.3562 ::: train hss = 0.1925 : val hss = 0.0399
Fold 4: train tss = 0.5043 : val tss = 0.5506 ::: train hss = 0.0892 : val hss = 0.1470
mean cv TSS: 0.3838
mean cv HSS: 0.1224
249/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.6745 : val tss = 0.0627 ::: train hss = 0.1097 : val hss = 0.0368
Fold 1: train tss = 0.7511 : val tss = 0.3542 ::: train hss = 0.2187 : val hss = 0.0904
Fold 2: train tss = -0.0217 : val tss = -0.0084 ::: train hss = -0.0011 : val hss = -0.0013
Fold 3: train tss = 0.6362 : val tss = 0.0817 ::: train hss = 0.1481 : val hss = 0.0179
Fold 4: train tss = 0.5612 : val tss = 0.5127 ::: train hss = 0.1096 : val hss = 0.1219
mean cv TSS: 0.2006
mean cv HSS: 0.0531
250/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.7399 : val tss = -0.0172 ::: train hss = 0.2487 : val hss = -0.0136
Fold 1: train tss = 0.8774 : val tss = 0.2301 ::: train hss = 0.2766 : val hss = 0.0742
Fold 2: train tss = 0.6100 : val tss = 0.5119 ::: train hss = 0.0807 : val hss = 0.1328
Fold 3: train tss = 0.7602 : val tss = 0.1108 ::: train hss = 0.1860 : val hss = 0.0317
Fold 4: train tss = 0.6659 : val tss = 0.6001 ::: train hss = 0.1204 : val hss = 0.1695
mean cv TSS: 0.2871
mean cv HSS: 0.0789
251/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.9775 : val tss = -0.0144 ::: train hss = 0.1722 : val hss = -0.0182
Fold 1: train tss = 0.7985 : val tss = 0.4070 ::: train hss = 0.3390 : val hss = 0.0975
Fold 2: train tss = 0.6677 : val tss = 0.5988 ::: train hss = 0.0956 : val hss = 0.1835
Fold 3: train tss = 0.6829 : val tss = 0.4375 ::: train hss = 0.1519 : val hss = 0.0738
Fold 4: train tss = 0.6467 : val tss = 0.5485 ::: train hss = 0.1169 : val hss = 0.1418
mean cv TSS: 0.3955
mean cv HSS: 0.0957
252/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.9071 : val tss = -0.0301 ::: train hss = 0.0919 : val hss = -0.0271
Fold 1: train tss = 0.6915 : val tss = 0.3718 ::: train hss = 0.1036 : val hss = 0.1076
Fold 2: train tss = 0.5231 : val tss = 0.6396 ::: train hss = 0.0841 : val hss = 0.2408
Fold 3: train tss = 0.6617 : val tss = 0.0330 ::: train hss = 0.1597 : val hss = 0.0038
Fold 4: train tss = 0.6266 : val tss = 0.6177 ::: train hss = 0.1206 : val hss = 0.1993
mean cv TSS: 0.3264
mean cv HSS: 0.1049
253/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 62796
Fold 0: train tss = 0.4920 : val tss = -0.0230 ::: train hss = 0.2050 : val hss = -0.0215
Fold 1: train tss = 0.6689 : val tss = 0.2583 ::: train hss = 0.1031 : val hss = 0.0630
Fold 2: train tss = 0.4832 : val tss = 0.6296 ::: train hss = 0.0631 : val hss = 0.2375
Fold 3: train tss = 0.5984 : val tss = 0.0400 ::: train hss = 0.1227 : val hss = 0.0107
Fold 4: train tss = 0.5141 : val tss = 0.4979 ::: train hss = 0.0777 : val hss = 0.1159
mean cv TSS: 0.2806
mean cv HSS: 0.0811
254/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.8359 : val tss = -0.0009 ::: train hss = 0.2171 : val hss = -0.0008
Fold 1: train tss = 0.8119 : val tss = 0.2669 ::: train hss = 0.4010 : val hss = 0.1119
Fold 2: train tss = 0.7163 : val tss = 0.6230 ::: train hss = 0.1104 : val hss = 0.2081
Fold 3: train tss = 0.7177 : val tss = 0.1417 ::: train hss = 0.1766 : val hss = 0.0421
Fold 4: train tss = 0.6926 : val tss = 0.6624 ::: train hss = 0.1310 : val hss = 0.2602
mean cv TSS: 0.3386
mean cv HSS: 0.1243
255/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7832 : val tss = 0.4280 ::: train hss = 0.2682 : val hss = 0.1244
Fold 2: train tss = 0.6856 : val tss = 0.6279 ::: train hss = 0.1066 : val hss = 0.2128
Fold 3: train tss = 0.6660 : val tss = 0.5239 ::: train hss = 0.1379 : val hss = 0.0498
Fold 4: train tss = 0.5798 : val tss = 0.5660 ::: train hss = 0.0886 : val hss = 0.1520
mean cv TSS: 0.4292
mean cv HSS: 0.1078
256/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.9917 : val tss = 0.1528 ::: train hss = 0.3639 : val hss = 0.1669
Fold 1: train tss = 0.8328 : val tss = 0.3493 ::: train hss = 0.3666 : val hss = 0.2448
Fold 2: train tss = 0.7328 : val tss = 0.7137 ::: train hss = 0.1658 : val hss = 0.3255
Fold 3: train tss = 0.7651 : val tss = 0.3953 ::: train hss = 0.2558 : val hss = 0.1046
Fold 4: train tss = 0.6667 : val tss = 0.6201 ::: train hss = 0.1417 : val hss = 0.1839
mean cv TSS: 0.4462
mean cv HSS: 0.2051
257/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.9349 : val tss = 0.3722 ::: train hss = 0.2280 : val hss = 0.2433
Fold 1: train tss = 0.8360 : val tss = 0.1809 ::: train hss = 0.3881 : val hss = 0.1190
Fold 2: train tss = 0.6715 : val tss = 0.6268 ::: train hss = 0.1359 : val hss = 0.2261
Fold 3: train tss = 0.7081 : val tss = 0.1802 ::: train hss = 0.1899 : val hss = 0.0270
Fold 4: train tss = 0.6823 : val tss = 0.5789 ::: train hss = 0.1475 : val hss = 0.1834
mean cv TSS: 0.3878
mean cv HSS: 0.1598
258/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.7451 : val tss = -0.0267 ::: train hss = 0.3921 : val hss = -0.0233
Fold 1: train tss = 0.9447 : val tss = 0.2454 ::: train hss = 0.3715 : val hss = 0.1155
Fold 2: train tss = 0.8521 : val tss = 0.6212 ::: train hss = 0.2231 : val hss = 0.3171
Fold 3: train tss = 0.8381 : val tss = 0.1458 ::: train hss = 0.2794 : val hss = 0.0320
Fold 4: train tss = 0.7513 : val tss = 0.7326 ::: train hss = 0.1793 : val hss = 0.3050
mean cv TSS: 0.3437
mean cv HSS: 0.1492
259/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.8435 : val tss = 0.0060 ::: train hss = 0.3708 : val hss = 0.0037
Fold 1: train tss = 0.9060 : val tss = 0.4175 ::: train hss = 0.3248 : val hss = 0.1229
Fold 2: train tss = 0.6954 : val tss = 0.5533 ::: train hss = 0.1051 : val hss = 0.1561
Fold 3: train tss = 0.7403 : val tss = 0.3591 ::: train hss = 0.1925 : val hss = 0.0480
Fold 4: train tss = 0.7233 : val tss = 0.6407 ::: train hss = 0.1689 : val hss = 0.2027
mean cv TSS: 0.3953
mean cv HSS: 0.1067
260/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.7454 : val tss = 0.0413 ::: train hss = 0.4085 : val hss = 0.0411
Fold 1: train tss = 0.8529 : val tss = 0.3747 ::: train hss = 0.3867 : val hss = 0.1915
Fold 2: train tss = 0.7082 : val tss = 0.7026 ::: train hss = 0.1514 : val hss = 0.2742
Fold 3: train tss = 0.7158 : val tss = 0.3021 ::: train hss = 0.1813 : val hss = 0.0399
Fold 4: train tss = 0.6844 : val tss = 0.6193 ::: train hss = 0.1599 : val hss = 0.2023
mean cv TSS: 0.4080
mean cv HSS: 0.1498
261/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.6358 : val tss = -0.0209 ::: train hss = 0.1684 : val hss = -0.0146
Fold 1: train tss = 0.7872 : val tss = 0.4482 ::: train hss = 0.2836 : val hss = 0.2159
Fold 2: train tss = 0.6788 : val tss = 0.6276 ::: train hss = 0.1643 : val hss = 0.2047
Fold 3: train tss = 0.6802 : val tss = 0.1739 ::: train hss = 0.1632 : val hss = 0.0279
Fold 4: train tss = 0.5829 : val tss = 0.6373 ::: train hss = 0.1034 : val hss = 0.1951
mean cv TSS: 0.3732
mean cv HSS: 0.1258
262/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.7988 : val tss = 0.0048 ::: train hss = 0.6946 : val hss = 0.0078
Fold 1: train tss = 0.7992 : val tss = 0.4382 ::: train hss = 0.3200 : val hss = 0.1137
Fold 2: train tss = 0.7951 : val tss = 0.7179 ::: train hss = 0.1983 : val hss = 0.3752
Fold 3: train tss = 0.6896 : val tss = 0.2384 ::: train hss = 0.1890 : val hss = 0.0149
Fold 4: train tss = 0.7786 : val tss = 0.6857 ::: train hss = 0.2166 : val hss = 0.3128
mean cv TSS: 0.4170
mean cv HSS: 0.1649
263/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.3496 : val tss = -0.0007 ::: train hss = 0.4662 : val hss = -0.0014
Fold 1: train tss = 0.7918 : val tss = 0.4098 ::: train hss = 0.3503 : val hss = 0.1672
Fold 2: train tss = 0.6653 : val tss = 0.6207 ::: train hss = 0.0926 : val hss = 0.2120
Fold 3: train tss = 0.6623 : val tss = 0.0868 ::: train hss = 0.1314 : val hss = 0.0151
Fold 4: train tss = 0.6995 : val tss = 0.7444 ::: train hss = 0.1447 : val hss = 0.3171
mean cv TSS: 0.3722
mean cv HSS: 0.1420
264/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 78404
Fold 0: train tss = 0.7883 : val tss = 0.0277 ::: train hss = 0.2371 : val hss = 0.0098
Fold 1: train tss = 0.8085 : val tss = 0.3379 ::: train hss = 0.2416 : val hss = 0.1264
Fold 2: train tss = 0.6051 : val tss = 0.6544 ::: train hss = 0.0987 : val hss = 0.2467
Fold 3: train tss = 0.6854 : val tss = 0.3723 ::: train hss = 0.1741 : val hss = 0.0702
Fold 4: train tss = 0.4767 : val tss = 0.6030 ::: train hss = 0.0786 : val hss = 0.1748
mean cv TSS: 0.3991
mean cv HSS: 0.1256
265/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.9220 : val tss = 0.1628 ::: train hss = 0.1361 : val hss = 0.0882
Fold 1: train tss = 0.7587 : val tss = 0.1895 ::: train hss = 0.1679 : val hss = 0.1019
Fold 2: train tss = 0.4547 : val tss = 0.4430 ::: train hss = 0.0469 : val hss = 0.1026
Fold 3: train tss = 0.6138 : val tss = 0.3773 ::: train hss = 0.1368 : val hss = 0.0383
Fold 4: train tss = 0.5843 : val tss = 0.5765 ::: train hss = 0.0990 : val hss = 0.1717
mean cv TSS: 0.3498
mean cv HSS: 0.1005
266/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9927 : val tss = 0.0182 ::: train hss = 0.3931 : val hss = 0.0213
Fold 1: train tss = 0.8266 : val tss = 0.3506 ::: train hss = 0.1752 : val hss = 0.0986
Fold 2: train tss = 0.6964 : val tss = 0.5334 ::: train hss = 0.1135 : val hss = 0.1422
Fold 3: train tss = 0.7229 : val tss = 0.2833 ::: train hss = 0.1587 : val hss = 0.0623
Fold 4: train tss = 0.6968 : val tss = 0.5875 ::: train hss = 0.1629 : val hss = 0.1613
mean cv TSS: 0.3546
mean cv HSS: 0.0972
267/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.6412 : val tss = -0.0289 ::: train hss = 0.2420 : val hss = -0.0224
Fold 1: train tss = 0.8432 : val tss = 0.2537 ::: train hss = 0.2898 : val hss = 0.0881
Fold 2: train tss = 0.6942 : val tss = 0.4660 ::: train hss = 0.1316 : val hss = 0.1132
Fold 3: train tss = 0.6230 : val tss = 0.3992 ::: train hss = 0.1067 : val hss = 0.0477
Fold 4: train tss = 0.6848 : val tss = 0.7402 ::: train hss = 0.1463 : val hss = 0.3203
mean cv TSS: 0.3660
mean cv HSS: 0.1094
268/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.7437 : val tss = -0.0119 ::: train hss = 0.0591 : val hss = -0.0041
Fold 1: train tss = 0.6686 : val tss = 0.4085 ::: train hss = 0.1028 : val hss = 0.0942
Fold 2: train tss = 0.7171 : val tss = 0.6703 ::: train hss = 0.1692 : val hss = 0.2676
Fold 3: train tss = 0.7159 : val tss = 0.2496 ::: train hss = 0.1896 : val hss = 0.0609
Fold 4: train tss = 0.6173 : val tss = 0.5722 ::: train hss = 0.1117 : val hss = 0.1591
mean cv TSS: 0.3778
mean cv HSS: 0.1155
269/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.7892 : val tss = 0.2379 ::: train hss = 0.2505 : val hss = 0.2266
Fold 1: train tss = 0.6935 : val tss = 0.3047 ::: train hss = 0.1206 : val hss = 0.2542
Fold 2: train tss = 0.2147 : val tss = 0.4939 ::: train hss = 0.0711 : val hss = 0.1203
Fold 3: train tss = 0.5873 : val tss = 0.3216 ::: train hss = 0.1185 : val hss = 0.0337
Fold 4: train tss = 0.5905 : val tss = 0.5889 ::: train hss = 0.1040 : val hss = 0.1648
mean cv TSS: 0.3894
mean cv HSS: 0.1599
270/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.8919 : val tss = -0.0093 ::: train hss = 0.3398 : val hss = -0.0118
Fold 1: train tss = 0.9206 : val tss = 0.2794 ::: train hss = 0.3810 : val hss = 0.1062
Fold 2: train tss = 0.7364 : val tss = 0.6941 ::: train hss = 0.1774 : val hss = 0.2761
Fold 3: train tss = 0.7679 : val tss = 0.0656 ::: train hss = 0.2151 : val hss = 0.0189
Fold 4: train tss = 0.7321 : val tss = 0.6553 ::: train hss = 0.1615 : val hss = 0.2246
mean cv TSS: 0.3370
mean cv HSS: 0.1228
271/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.5977 : val tss = 0.0704 ::: train hss = 0.4688 : val hss = 0.1133
Fold 1: train tss = 0.7517 : val tss = 0.2669 ::: train hss = 0.3146 : val hss = 0.0844
Fold 2: train tss = 0.6755 : val tss = 0.6554 ::: train hss = 0.1027 : val hss = 0.2278
Fold 3: train tss = 0.6760 : val tss = 0.4494 ::: train hss = 0.1399 : val hss = 0.0728
Fold 4: train tss = 0.6685 : val tss = 0.7219 ::: train hss = 0.1410 : val hss = 0.3238
mean cv TSS: 0.4328
mean cv HSS: 0.1644
272/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.9922 : val tss = 0.2893 ::: train hss = 0.3780 : val hss = 0.1992
Fold 1: train tss = 0.8686 : val tss = 0.1767 ::: train hss = 0.2909 : val hss = 0.1191
Fold 2: train tss = 0.7336 : val tss = 0.6571 ::: train hss = 0.1569 : val hss = 0.2619
Fold 3: train tss = 0.7699 : val tss = 0.1453 ::: train hss = 0.2683 : val hss = 0.0317
Fold 4: train tss = 0.6721 : val tss = 0.6118 ::: train hss = 0.1344 : val hss = 0.1957
mean cv TSS: 0.3761
mean cv HSS: 0.1615
273/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.7881 : val tss = 0.0970 ::: train hss = 0.2335 : val hss = 0.0958
Fold 1: train tss = 0.8679 : val tss = 0.3442 ::: train hss = 0.4364 : val hss = 0.2622
Fold 2: train tss = 0.6152 : val tss = 0.6347 ::: train hss = 0.1259 : val hss = 0.2134
Fold 3: train tss = 0.7028 : val tss = 0.3410 ::: train hss = 0.1984 : val hss = 0.0335
Fold 4: train tss = 0.7075 : val tss = 0.6424 ::: train hss = 0.1807 : val hss = 0.2013
mean cv TSS: 0.4119
mean cv HSS: 0.1612
274/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9923 : val tss = -0.0246 ::: train hss = 0.3817 : val hss = -0.0128
Fold 1: train tss = 0.8883 : val tss = 0.3439 ::: train hss = 0.3027 : val hss = 0.1095
Fold 2: train tss = 0.8186 : val tss = 0.6776 ::: train hss = 0.2019 : val hss = 0.2680
Fold 3: train tss = 0.8271 : val tss = 0.2014 ::: train hss = 0.2734 : val hss = 0.0363
Fold 4: train tss = 0.7619 : val tss = 0.7329 ::: train hss = 0.1871 : val hss = 0.3139
mean cv TSS: 0.3862
mean cv HSS: 0.1430
275/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 228189
Fold 0: train tss = 0.9706 : val tss = 0.0073 ::: train hss = 0.1367 : val hss = 0.0076
Fold 1: train tss = 0.8655 : val tss = 0.2914 ::: train hss = 0.2190 : val hss = 0.1158
Fold 2: train tss = 0.6909 : val tss = 0.6502 ::: train hss = 0.1111 : val hss = 0.2326
Fold 3: train tss = 0.7739 : val tss = 0.2064 ::: train hss = 0.2023 : val hss = 0.0440
Fold 4: train tss = 0.7138 : val tss = 0.6472 ::: train hss = 0.1670 : val hss = 0.2121
mean cv TSS: 0.3605
mean cv HSS: 0.1224
276/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.7442 : val tss = -0.0163 ::: train hss = 0.3587 : val hss = -0.0196
Fold 1: train tss = 0.7704 : val tss = 0.3731 ::: train hss = 0.2267 : val hss = 0.1977
Fold 2: train tss = 0.7067 : val tss = 0.6160 ::: train hss = 0.1431 : val hss = 0.1976
Fold 3: train tss = 0.8223 : val tss = 0.1324 ::: train hss = 0.3121 : val hss = 0.0327
Fold 4: train tss = 0.7254 : val tss = 0.6760 ::: train hss = 0.1729 : val hss = 0.3060
mean cv TSS: 0.3562
mean cv HSS: 0.1429
277/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.5839 : val tss = -0.0082 ::: train hss = 0.1407 : val hss = -0.0084
Fold 1: train tss = 0.6494 : val tss = 0.3093 ::: train hss = 0.0921 : val hss = 0.0492
Fold 2: train tss = 0.5657 : val tss = 0.5968 ::: train hss = 0.0792 : val hss = 0.1895
Fold 3: train tss = 0.6660 : val tss = 0.1326 ::: train hss = 0.1479 : val hss = 0.0246
Fold 4: train tss = 0.6315 : val tss = 0.5951 ::: train hss = 0.1244 : val hss = 0.1704
mean cv TSS: 0.3251
mean cv HSS: 0.0851
278/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.7484 : val tss = 0.0300 ::: train hss = 0.6237 : val hss = 0.0489
Fold 1: train tss = 0.8371 : val tss = 0.2343 ::: train hss = 0.3966 : val hss = 0.1053
Fold 2: train tss = 0.8008 : val tss = 0.6909 ::: train hss = 0.1909 : val hss = 0.3293
Fold 3: train tss = 0.7525 : val tss = 0.4909 ::: train hss = 0.1965 : val hss = 0.0737
Fold 4: train tss = 0.7276 : val tss = 0.6442 ::: train hss = 0.1684 : val hss = 0.2062
mean cv TSS: 0.4181
mean cv HSS: 0.1527
279/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.6957 : val tss = -0.0114 ::: train hss = 0.3975 : val hss = -0.0137
Fold 1: train tss = 0.8284 : val tss = 0.2900 ::: train hss = 0.2812 : val hss = 0.1165
Fold 2: train tss = 0.7125 : val tss = 0.6727 ::: train hss = 0.1278 : val hss = 0.2582
Fold 3: train tss = 0.6445 : val tss = 0.3671 ::: train hss = 0.1242 : val hss = 0.0594
Fold 4: train tss = 0.7219 : val tss = 0.6529 ::: train hss = 0.1493 : val hss = 0.2159
mean cv TSS: 0.3943
mean cv HSS: 0.1273
280/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.8861 : val tss = -0.0259 ::: train hss = 0.2317 : val hss = -0.0168
Fold 1: train tss = 0.7694 : val tss = 0.2770 ::: train hss = 0.2134 : val hss = 0.1718
Fold 2: train tss = 0.7389 : val tss = 0.6013 ::: train hss = 0.1912 : val hss = 0.2775
Fold 3: train tss = 0.7235 : val tss = 0.1863 ::: train hss = 0.2032 : val hss = 0.0323
Fold 4: train tss = 0.6808 : val tss = 0.6205 ::: train hss = 0.1531 : val hss = 0.1933
mean cv TSS: 0.3318
mean cv HSS: 0.1316
281/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.8231 : val tss = 0.3619 ::: train hss = 0.1266 : val hss = 0.1358
Fold 1: train tss = 0.7062 : val tss = 0.3268 ::: train hss = 0.1383 : val hss = 0.0897
Fold 2: train tss = 0.5307 : val tss = 0.6456 ::: train hss = 0.0678 : val hss = 0.2205
Fold 3: train tss = 0.6973 : val tss = 0.0811 ::: train hss = 0.2038 : val hss = 0.0137
Fold 4: train tss = 0.5320 : val tss = 0.5257 ::: train hss = 0.0847 : val hss = 0.1388
mean cv TSS: 0.3882
mean cv HSS: 0.1197
282/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9912 : val tss = -0.0093 ::: train hss = 0.3509 : val hss = -0.0118
Fold 1: train tss = 0.8903 : val tss = 0.2480 ::: train hss = 0.2292 : val hss = 0.2385
Fold 2: train tss = 0.8309 : val tss = 0.5740 ::: train hss = 0.2129 : val hss = 0.3124
Fold 3: train tss = 0.7815 : val tss = 0.3947 ::: train hss = 0.2352 : val hss = 0.0766
Fold 4: train tss = 0.7452 : val tss = 0.6279 ::: train hss = 0.1961 : val hss = 0.1941
mean cv TSS: 0.3671
mean cv HSS: 0.1620
283/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.9848 : val tss = -0.0067 ::: train hss = 0.2373 : val hss = -0.0091
Fold 1: train tss = 0.7005 : val tss = 0.2876 ::: train hss = 0.1168 : val hss = 0.0283
Fold 2: train tss = 0.6211 : val tss = 0.5446 ::: train hss = 0.1016 : val hss = 0.1499
Fold 3: train tss = 0.6436 : val tss = 0.5054 ::: train hss = 0.1276 : val hss = 0.0708
Fold 4: train tss = 0.7036 : val tss = 0.5484 ::: train hss = 0.1484 : val hss = 0.1513
mean cv TSS: 0.3758
mean cv HSS: 0.0783
284/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.9458 : val tss = 0.1257 ::: train hss = 0.5112 : val hss = 0.1326
Fold 1: train tss = 0.7061 : val tss = 0.4088 ::: train hss = 0.1480 : val hss = 0.1868
Fold 2: train tss = 0.6273 : val tss = 0.6641 ::: train hss = 0.1137 : val hss = 0.3066
Fold 3: train tss = 0.7664 : val tss = -0.0127 ::: train hss = 0.2358 : val hss = -0.0024
Fold 4: train tss = 0.6529 : val tss = 0.5868 ::: train hss = 0.1431 : val hss = 0.1623
mean cv TSS: 0.3545
mean cv HSS: 0.1572
285/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.5410 : val tss = 0.2230 ::: train hss = 0.2041 : val hss = 0.1949
Fold 1: train tss = 0.4776 : val tss = 0.3049 ::: train hss = 0.0396 : val hss = 0.0445
Fold 2: train tss = 0.6070 : val tss = 0.7392 ::: train hss = 0.0948 : val hss = 0.3543
Fold 3: train tss = 0.6040 : val tss = 0.3002 ::: train hss = 0.1276 : val hss = 0.0454
Fold 4: train tss = 0.5755 : val tss = 0.4030 ::: train hss = 0.0923 : val hss = 0.0799
mean cv TSS: 0.3941
mean cv HSS: 0.1438
286/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 228189
Fold 0: train tss = 0.9966 : val tss = -0.0055 ::: train hss = 0.5863 : val hss = -0.0077
Fold 1: train tss = 0.9009 : val tss = 0.2871 ::: train hss = 0.5047 : val hss = 0.1520
Fold 2: train tss = 0.7734 : val tss = 0.6379 ::: train hss = 0.1678 : val hss = 0.2142
Fold 3: train tss = 0.6922 : val tss = 0.3786 ::: train hss = 0.1484 : val hss = 0.0361
Fold 4: train tss = 0.6948 : val tss = 0.7189 ::: train hss = 0.1511 : val hss = 0.2850
mean cv TSS: 0.4034
mean cv HSS: 0.1359
287/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.5981 : val tss = 0.0015 ::: train hss = 0.4984 : val hss = 0.0022
Fold 1: train tss = 0.7746 : val tss = 0.2848 ::: train hss = 0.2837 : val hss = 0.1094
Fold 2: train tss = 0.5796 : val tss = 0.6359 ::: train hss = 0.1048 : val hss = 0.2265
Fold 3: train tss = 0.7040 : val tss = 0.1225 ::: train hss = 0.1791 : val hss = 0.0277
Fold 4: train tss = 0.6820 : val tss = 0.6388 ::: train hss = 0.1403 : val hss = 0.1997
mean cv TSS: 0.3367
mean cv HSS: 0.1131
288/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.7323 : val tss = 0.2218 ::: train hss = 0.1609 : val hss = 0.1173
Fold 1: train tss = 0.7770 : val tss = 0.3143 ::: train hss = 0.3966 : val hss = 0.1085
Fold 2: train tss = 0.5606 : val tss = 0.4999 ::: train hss = 0.0653 : val hss = 0.1403
Fold 3: train tss = 0.7809 : val tss = 0.1880 ::: train hss = 0.2430 : val hss = 0.0374
Fold 4: train tss = 0.7554 : val tss = 0.6860 ::: train hss = 0.1939 : val hss = 0.2886
mean cv TSS: 0.3820
mean cv HSS: 0.1384
289/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.9317 : val tss = 0.1931 ::: train hss = 0.1951 : val hss = 0.0987
Fold 1: train tss = 0.7770 : val tss = 0.3989 ::: train hss = 0.2338 : val hss = 0.1512
Fold 2: train tss = 0.6358 : val tss = 0.7171 ::: train hss = 0.1217 : val hss = 0.3252
Fold 3: train tss = 0.6894 : val tss = 0.3708 ::: train hss = 0.1609 : val hss = 0.0368
Fold 4: train tss = 0.6617 : val tss = 0.6078 ::: train hss = 0.1318 : val hss = 0.1960
mean cv TSS: 0.4575
mean cv HSS: 0.1616
290/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9902 : val tss = 0.0640 ::: train hss = 0.3274 : val hss = 0.0435
Fold 1: train tss = 0.9356 : val tss = 0.3318 ::: train hss = 0.3246 : val hss = 0.1129
Fold 2: train tss = 0.8089 : val tss = 0.6407 ::: train hss = 0.1600 : val hss = 0.2173
Fold 3: train tss = 0.7193 : val tss = 0.3720 ::: train hss = 0.1703 : val hss = 0.0939
Fold 4: train tss = 0.7751 : val tss = 0.5801 ::: train hss = 0.2091 : val hss = 0.1665
mean cv TSS: 0.3977
mean cv HSS: 0.1268
291/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.7418 : val tss = 0.0076 ::: train hss = 0.2881 : val hss = 0.0045
Fold 1: train tss = 0.8634 : val tss = 0.3446 ::: train hss = 0.3457 : val hss = 0.0948
Fold 2: train tss = 0.7546 : val tss = 0.6914 ::: train hss = 0.1455 : val hss = 0.3451
Fold 3: train tss = 0.7552 : val tss = 0.5653 ::: train hss = 0.1863 : val hss = 0.0855
Fold 4: train tss = 0.6838 : val tss = 0.6968 ::: train hss = 0.1256 : val hss = 0.2685
mean cv TSS: 0.4611
mean cv HSS: 0.1597
292/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.6882 : val tss = -0.0162 ::: train hss = 0.2085 : val hss = -0.0157
Fold 1: train tss = 0.8377 : val tss = 0.3333 ::: train hss = 0.2425 : val hss = 0.2615
Fold 2: train tss = 0.6740 : val tss = 0.6728 ::: train hss = 0.1624 : val hss = 0.2540
Fold 3: train tss = 0.6468 : val tss = 0.3218 ::: train hss = 0.1499 : val hss = 0.0429
Fold 4: train tss = 0.5876 : val tss = 0.5868 ::: train hss = 0.1031 : val hss = 0.1685
mean cv TSS: 0.3797
mean cv HSS: 0.1422
293/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.5427 : val tss = 0.1264 ::: train hss = 0.2359 : val hss = 0.1019
Fold 1: train tss = 0.7135 : val tss = 0.4433 ::: train hss = 0.1530 : val hss = 0.1105
Fold 2: train tss = 0.5214 : val tss = 0.5805 ::: train hss = 0.0809 : val hss = 0.1949
Fold 3: train tss = 0.6441 : val tss = 0.1355 ::: train hss = 0.1349 : val hss = 0.0215
Fold 4: train tss = 0.6012 : val tss = 0.5674 ::: train hss = 0.1120 : val hss = 0.1492
mean cv TSS: 0.3706
mean cv HSS: 0.1156
294/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.8482 : val tss = -0.0089 ::: train hss = 0.6525 : val hss = -0.0131
Fold 1: train tss = 0.7901 : val tss = 0.4030 ::: train hss = 0.2785 : val hss = 0.1250
Fold 2: train tss = 0.7178 : val tss = 0.6532 ::: train hss = 0.1492 : val hss = 0.2434
Fold 3: train tss = 0.7866 : val tss = 0.2978 ::: train hss = 0.2421 : val hss = 0.0636
Fold 4: train tss = 0.7290 : val tss = 0.7210 ::: train hss = 0.1746 : val hss = 0.2890
mean cv TSS: 0.4132
mean cv HSS: 0.1416
295/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7467 : val tss = 0.4346 ::: train hss = 0.1408 : val hss = 0.1065
Fold 2: train tss = 0.6303 : val tss = 0.5902 ::: train hss = 0.0836 : val hss = 0.1784
Fold 3: train tss = 0.6482 : val tss = 0.2609 ::: train hss = 0.1209 : val hss = 0.0408
Fold 4: train tss = 0.7093 : val tss = 0.5995 ::: train hss = 0.1637 : val hss = 0.1824
mean cv TSS: 0.3770
mean cv HSS: 0.1016
296/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.8264 : val tss = 0.0862 ::: train hss = 0.1419 : val hss = 0.0841
Fold 1: train tss = 0.7297 : val tss = 0.3152 ::: train hss = 0.3342 : val hss = 0.1432
Fold 2: train tss = 0.6529 : val tss = 0.6703 ::: train hss = 0.1085 : val hss = 0.2960
Fold 3: train tss = 0.6973 : val tss = 0.3965 ::: train hss = 0.1772 : val hss = 0.0616
Fold 4: train tss = 0.5613 : val tss = 0.4453 ::: train hss = 0.0877 : val hss = 0.0984
mean cv TSS: 0.3827
mean cv HSS: 0.1367
297/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 78404
Fold 0: train tss = 0.5906 : val tss = 0.1591 ::: train hss = 0.2148 : val hss = 0.1132
Fold 1: train tss = 0.8229 : val tss = 0.0635 ::: train hss = 0.3865 : val hss = 0.1115
Fold 2: train tss = 0.4919 : val tss = 0.6418 ::: train hss = 0.0622 : val hss = 0.2192
Fold 3: train tss = 0.6480 : val tss = 0.1256 ::: train hss = 0.1467 : val hss = 0.0210
Fold 4: train tss = 0.5463 : val tss = 0.5390 ::: train hss = 0.0891 : val hss = 0.1348
mean cv TSS: 0.3058
mean cv HSS: 0.1199
298/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9877 : val tss = -0.0092 ::: train hss = 0.2782 : val hss = -0.0134
Fold 1: train tss = 0.9045 : val tss = 0.2485 ::: train hss = 0.3379 : val hss = 0.0997
Fold 2: train tss = 0.7528 : val tss = 0.6303 ::: train hss = 0.1254 : val hss = 0.2895
Fold 3: train tss = 0.7680 : val tss = 0.2636 ::: train hss = 0.2098 : val hss = 0.0419
Fold 4: train tss = 0.6946 : val tss = 0.5352 ::: train hss = 0.1492 : val hss = 0.1347
mean cv TSS: 0.3337
mean cv HSS: 0.1105
299/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.6404 : val tss = -0.0205 ::: train hss = 0.2267 : val hss = -0.0168
Fold 1: train tss = 0.7769 : val tss = 0.3112 ::: train hss = 0.3956 : val hss = 0.1439
Fold 2: train tss = 0.6338 : val tss = 0.6220 ::: train hss = 0.0865 : val hss = 0.2005
Fold 3: train tss = 0.6947 : val tss = 0.4262 ::: train hss = 0.1549 : val hss = 0.0471
Fold 4: train tss = 0.6736 : val tss = 0.6160 ::: train hss = 0.1323 : val hss = 0.1851
mean cv TSS: 0.3910
mean cv HSS: 0.1120
300/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.9457 : val tss = 0.1621 ::: train hss = 0.5044 : val hss = 0.1423
Fold 1: train tss = 0.6205 : val tss = 0.3549 ::: train hss = 0.0854 : val hss = 0.0582
Fold 2: train tss = 0.7513 : val tss = 0.7606 ::: train hss = 0.1928 : val hss = 0.3878
Fold 3: train tss = 0.6397 : val tss = 0.0689 ::: train hss = 0.1448 : val hss = 0.0128
Fold 4: train tss = 0.6227 : val tss = 0.6050 ::: train hss = 0.1169 : val hss = 0.1906
mean cv TSS: 0.3903
mean cv HSS: 0.1584
301/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.4880 : val tss = 0.0432 ::: train hss = 0.1501 : val hss = 0.0256
Fold 1: train tss = 0.5767 : val tss = 0.4161 ::: train hss = 0.0602 : val hss = 0.1451
Fold 2: train tss = 0.5357 : val tss = 0.6528 ::: train hss = 0.0660 : val hss = 0.2331
Fold 3: train tss = 0.6078 : val tss = 0.2637 ::: train hss = 0.1199 : val hss = 0.0208
Fold 4: train tss = 0.3638 : val tss = 0.5447 ::: train hss = 0.0352 : val hss = 0.1376
mean cv TSS: 0.3841
mean cv HSS: 0.1124
302/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.4000 : val tss = -0.0016 ::: train hss = 0.5714 : val hss = -0.0030
Fold 1: train tss = 0.8573 : val tss = 0.3254 ::: train hss = 0.3595 : val hss = 0.1183
Fold 2: train tss = 0.6871 : val tss = 0.6354 ::: train hss = 0.1037 : val hss = 0.2155
Fold 3: train tss = 0.7395 : val tss = 0.1629 ::: train hss = 0.1905 : val hss = 0.0329
Fold 4: train tss = 0.7484 : val tss = 0.7356 ::: train hss = 0.1907 : val hss = 0.3508
mean cv TSS: 0.3715
mean cv HSS: 0.1429
303/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.5953 : val tss = -0.0155 ::: train hss = 0.3354 : val hss = -0.0191
Fold 1: train tss = 0.7833 : val tss = 0.3353 ::: train hss = 0.2536 : val hss = 0.1217
Fold 2: train tss = 0.5673 : val tss = 0.4322 ::: train hss = 0.0799 : val hss = 0.0998
Fold 3: train tss = 0.6535 : val tss = 0.4232 ::: train hss = 0.1480 : val hss = 0.0445
Fold 4: train tss = 0.6536 : val tss = 0.5917 ::: train hss = 0.1348 : val hss = 0.1644
mean cv TSS: 0.3534
mean cv HSS: 0.0823
304/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.9429 : val tss = 0.0044 ::: train hss = 0.3849 : val hss = 0.0031
Fold 1: train tss = 0.8390 : val tss = 0.3762 ::: train hss = 0.3285 : val hss = 0.2392
Fold 2: train tss = 0.7114 : val tss = 0.7316 ::: train hss = 0.1594 : val hss = 0.3426
Fold 3: train tss = 0.7171 : val tss = -0.0419 ::: train hss = 0.1869 : val hss = -0.0088
Fold 4: train tss = 0.7233 : val tss = 0.6763 ::: train hss = 0.1683 : val hss = 0.2287
mean cv TSS: 0.3493
mean cv HSS: 0.1609
305/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.7818 : val tss = 0.3803 ::: train hss = 0.1672 : val hss = 0.2022
Fold 1: train tss = 0.8283 : val tss = 0.4565 ::: train hss = 0.3396 : val hss = 0.2171
Fold 2: train tss = 0.7348 : val tss = 0.6896 ::: train hss = 0.1969 : val hss = 0.2750
Fold 3: train tss = 0.7089 : val tss = 0.0598 ::: train hss = 0.1921 : val hss = 0.0111
Fold 4: train tss = 0.6272 : val tss = 0.6063 ::: train hss = 0.1137 : val hss = 0.1769
mean cv TSS: 0.4385
mean cv HSS: 0.1765
306/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9905 : val tss = -0.0176 ::: train hss = 0.3329 : val hss = -0.0183
Fold 1: train tss = 0.8752 : val tss = 0.3116 ::: train hss = 0.2557 : val hss = 0.0619
Fold 2: train tss = 0.8112 : val tss = 0.6717 ::: train hss = 0.2006 : val hss = 0.2505
Fold 3: train tss = 0.8189 : val tss = 0.2688 ::: train hss = 0.2542 : val hss = 0.0990
Fold 4: train tss = 0.7499 : val tss = 0.6276 ::: train hss = 0.1667 : val hss = 0.2028
mean cv TSS: 0.3724
mean cv HSS: 0.1192
307/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.8872 : val tss = 0.0086 ::: train hss = 0.2465 : val hss = 0.0059
Fold 1: train tss = 0.8849 : val tss = 0.2759 ::: train hss = 0.2891 : val hss = 0.0714
Fold 2: train tss = 0.7732 : val tss = 0.6030 ::: train hss = 0.1485 : val hss = 0.1883
Fold 3: train tss = 0.7351 : val tss = 0.3582 ::: train hss = 0.1839 : val hss = 0.0800
Fold 4: train tss = 0.7404 : val tss = 0.4627 ::: train hss = 0.1813 : val hss = 0.2177
mean cv TSS: 0.3417
mean cv HSS: 0.1127
308/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 104260
Fold 0: train tss = 0.8413 : val tss = 0.0026 ::: train hss = 0.3087 : val hss = 0.0025
Fold 1: train tss = 0.8481 : val tss = 0.2760 ::: train hss = 0.3317 : val hss = 0.2191
Fold 2: train tss = 0.7442 : val tss = 0.7111 ::: train hss = 0.1875 : val hss = 0.3433
Fold 3: train tss = 0.6799 : val tss = 0.0350 ::: train hss = 0.1484 : val hss = 0.0097
Fold 4: train tss = 0.6805 : val tss = 0.6251 ::: train hss = 0.1678 : val hss = 0.2115
mean cv TSS: 0.3300
mean cv HSS: 0.1572
309/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.5428 : val tss = 0.1015 ::: train hss = 0.2386 : val hss = 0.0990
Fold 1: train tss = 0.6415 : val tss = 0.3382 ::: train hss = 0.0939 : val hss = 0.0898
Fold 2: train tss = 0.6086 : val tss = 0.7129 ::: train hss = 0.0936 : val hss = 0.2965
Fold 3: train tss = 0.5502 : val tss = 0.3088 ::: train hss = 0.0959 : val hss = 0.0465
Fold 4: train tss = 0.6381 : val tss = 0.6194 ::: train hss = 0.1260 : val hss = 0.1849
mean cv TSS: 0.4161
mean cv HSS: 0.1433
310/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.6974 : val tss = -0.0121 ::: train hss = 0.4981 : val hss = -0.0162
Fold 1: train tss = 0.8119 : val tss = 0.3141 ::: train hss = 0.3198 : val hss = 0.1100
Fold 2: train tss = 0.7179 : val tss = 0.6677 ::: train hss = 0.1615 : val hss = 0.2447
Fold 3: train tss = 0.7703 : val tss = 0.2296 ::: train hss = 0.2139 : val hss = 0.0416
Fold 4: train tss = 0.7729 : val tss = 0.6648 ::: train hss = 0.1964 : val hss = 0.3766
mean cv TSS: 0.3728
mean cv HSS: 0.1513
311/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.5492 : val tss = -0.0020 ::: train hss = 0.5781 : val hss = -0.0036
Fold 1: train tss = 0.7776 : val tss = 0.4378 ::: train hss = 0.2356 : val hss = 0.1287
Fold 2: train tss = 0.7432 : val tss = 0.6906 ::: train hss = 0.1516 : val hss = 0.2799
Fold 3: train tss = 0.6706 : val tss = 0.2617 ::: train hss = 0.1385 : val hss = 0.0391
Fold 4: train tss = 0.7160 : val tss = 0.7264 ::: train hss = 0.1627 : val hss = 0.2794
mean cv TSS: 0.4229
mean cv HSS: 0.1447
312/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.9299 : val tss = 0.1931 ::: train hss = 0.1806 : val hss = 0.0987
Fold 1: train tss = 0.6827 : val tss = 0.3638 ::: train hss = 0.0678 : val hss = 0.0996
Fold 2: train tss = 0.6541 : val tss = 0.6690 ::: train hss = 0.0987 : val hss = 0.2389
Fold 3: train tss = 0.6977 : val tss = 0.3650 ::: train hss = 0.1707 : val hss = 0.0408
Fold 4: train tss = 0.4545 : val tss = 0.4795 ::: train hss = 0.0610 : val hss = 0.1053
mean cv TSS: 0.4141
mean cv HSS: 0.1167
313/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.8761 : val tss = 0.1655 ::: train hss = 0.1485 : val hss = 0.0687
Fold 1: train tss = 0.7544 : val tss = 0.2963 ::: train hss = 0.4248 : val hss = 0.2524
Fold 2: train tss = -0.0198 : val tss = -0.0084 ::: train hss = -0.0010 : val hss = -0.0013
Fold 3: train tss = 0.6355 : val tss = 0.0939 ::: train hss = 0.1391 : val hss = 0.0131
Fold 4: train tss = 0.5352 : val tss = 0.4820 ::: train hss = 0.0792 : val hss = 0.1235
mean cv TSS: 0.2058
mean cv HSS: 0.0913
314/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9881 : val tss = -0.0014 ::: train hss = 0.2843 : val hss = -0.0023
Fold 1: train tss = 0.9115 : val tss = 0.2814 ::: train hss = 0.3116 : val hss = 0.1044
Fold 2: train tss = 0.7337 : val tss = 0.6528 ::: train hss = 0.1359 : val hss = 0.2329
Fold 3: train tss = 0.7874 : val tss = 0.4334 ::: train hss = 0.2152 : val hss = 0.1068
Fold 4: train tss = 0.7552 : val tss = 0.6704 ::: train hss = 0.1918 : val hss = 0.2393
mean cv TSS: 0.4073
mean cv HSS: 0.1362
315/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.8876 : val tss = -0.0009 ::: train hss = 0.2518 : val hss = -0.0012
Fold 1: train tss = 0.8579 : val tss = 0.4041 ::: train hss = 0.3176 : val hss = 0.0873
Fold 2: train tss = 0.6895 : val tss = 0.6064 ::: train hss = 0.1200 : val hss = 0.1907
Fold 3: train tss = 0.6710 : val tss = 0.1725 ::: train hss = 0.1330 : val hss = 0.0441
Fold 4: train tss = 0.6266 : val tss = 0.5344 ::: train hss = 0.1108 : val hss = 0.1357
mean cv TSS: 0.3433
mean cv HSS: 0.0913
316/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.7443 : val tss = 0.0599 ::: train hss = 0.3631 : val hss = 0.0412
Fold 1: train tss = 0.7814 : val tss = 0.1903 ::: train hss = 0.4350 : val hss = 0.2680
Fold 2: train tss = 0.7026 : val tss = 0.6649 ::: train hss = 0.1462 : val hss = 0.3127
Fold 3: train tss = 0.6166 : val tss = 0.1385 ::: train hss = 0.1461 : val hss = 0.0237
Fold 4: train tss = 0.6260 : val tss = 0.5253 ::: train hss = 0.1252 : val hss = 0.1288
mean cv TSS: 0.3158
mean cv HSS: 0.1549
317/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.6842 : val tss = 0.0594 ::: train hss = 0.1659 : val hss = 0.0380
Fold 1: train tss = 0.6537 : val tss = 0.2371 ::: train hss = 0.0949 : val hss = 0.1369
Fold 2: train tss = 0.5671 : val tss = 0.6292 ::: train hss = 0.0764 : val hss = 0.2075
Fold 3: train tss = 0.5859 : val tss = 0.0743 ::: train hss = 0.1115 : val hss = 0.0153
Fold 4: train tss = 0.5174 : val tss = 0.5043 ::: train hss = 0.0703 : val hss = 0.1183
mean cv TSS: 0.3009
mean cv HSS: 0.1032
318/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.6978 : val tss = -0.0096 ::: train hss = 0.5368 : val hss = -0.0138
Fold 1: train tss = 0.9112 : val tss = 0.2377 ::: train hss = 0.3508 : val hss = 0.0780
Fold 2: train tss = 0.7342 : val tss = 0.6400 ::: train hss = 0.1503 : val hss = 0.2151
Fold 3: train tss = 0.7691 : val tss = 0.4332 ::: train hss = 0.2074 : val hss = 0.0533
Fold 4: train tss = 0.7397 : val tss = 0.7443 ::: train hss = 0.1783 : val hss = 0.3317
mean cv TSS: 0.4091
mean cv HSS: 0.1328
319/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 228189
Fold 0: train tss = 0.5977 : val tss = -0.0113 ::: train hss = 0.4688 : val hss = -0.0155
Fold 1: train tss = 0.8270 : val tss = 0.2736 ::: train hss = 0.3114 : val hss = 0.1486
Fold 2: train tss = 0.6366 : val tss = 0.6182 ::: train hss = 0.1202 : val hss = 0.1991
Fold 3: train tss = 0.6952 : val tss = 0.2915 ::: train hss = 0.1585 : val hss = 0.0817
Fold 4: train tss = 0.6618 : val tss = 0.6731 ::: train hss = 0.1316 : val hss = 0.2331
mean cv TSS: 0.3690
mean cv HSS: 0.1294
320/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.9413 : val tss = 0.0049 ::: train hss = 0.3392 : val hss = 0.0044
Fold 1: train tss = 0.8832 : val tss = 0.2864 ::: train hss = 0.3615 : val hss = 0.2551
Fold 2: train tss = 0.8119 : val tss = 0.7183 ::: train hss = 0.2426 : val hss = 0.3852
Fold 3: train tss = 0.7932 : val tss = 0.2484 ::: train hss = 0.2601 : val hss = 0.0363
Fold 4: train tss = 0.6717 : val tss = 0.6268 ::: train hss = 0.1444 : val hss = 0.2188
mean cv TSS: 0.3769
mean cv HSS: 0.1800
321/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0995 : val tss = 0.0938 ::: train hss = 0.1531 : val hss = 0.1077
Fold 1: train tss = 0.8011 : val tss = 0.3886 ::: train hss = 0.2893 : val hss = 0.2376
Fold 2: train tss = 0.5925 : val tss = 0.6545 ::: train hss = 0.1122 : val hss = 0.2591
Fold 3: train tss = 0.6512 : val tss = 0.1326 ::: train hss = 0.1485 : val hss = 0.0197
Fold 4: train tss = 0.6945 : val tss = 0.6156 ::: train hss = 0.1728 : val hss = 0.2222
mean cv TSS: 0.3770
mean cv HSS: 0.1693
322/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9864 : val tss = -0.0065 ::: train hss = 0.2579 : val hss = -0.0088
Fold 1: train tss = 0.8888 : val tss = 0.3634 ::: train hss = 0.3045 : val hss = 0.1417
Fold 2: train tss = 0.8715 : val tss = 0.6576 ::: train hss = 0.2821 : val hss = 0.2697
Fold 3: train tss = 0.8181 : val tss = 0.3367 ::: train hss = 0.2627 : val hss = 0.0940
Fold 4: train tss = 0.8061 : val tss = 0.5601 ::: train hss = 0.2217 : val hss = 0.2103
mean cv TSS: 0.3823
mean cv HSS: 0.1414
323/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9863 : val tss = 0.0287 ::: train hss = 0.2562 : val hss = 0.0302
Fold 1: train tss = 0.8809 : val tss = 0.2770 ::: train hss = 0.2742 : val hss = 0.0929
Fold 2: train tss = 0.6884 : val tss = 0.6914 ::: train hss = 0.1037 : val hss = 0.2781
Fold 3: train tss = 0.7664 : val tss = 0.2739 ::: train hss = 0.1917 : val hss = 0.0560
Fold 4: train tss = 0.7466 : val tss = 0.6452 ::: train hss = 0.1941 : val hss = 0.2459
mean cv TSS: 0.3832
mean cv HSS: 0.1406
324/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.7472 : val tss = 0.0406 ::: train hss = 0.5153 : val hss = 0.0444
Fold 1: train tss = 0.7258 : val tss = 0.3977 ::: train hss = 0.1799 : val hss = 0.0897
Fold 2: train tss = 0.7397 : val tss = 0.6874 ::: train hss = 0.1666 : val hss = 0.2714
Fold 3: train tss = 0.6394 : val tss = 0.2731 ::: train hss = 0.1404 : val hss = 0.0393
Fold 4: train tss = 0.7907 : val tss = 0.6749 ::: train hss = 0.2383 : val hss = 0.2693
mean cv TSS: 0.4147
mean cv HSS: 0.1428
325/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.6467 : val tss = 0.0091 ::: train hss = 0.4312 : val hss = 0.0110
Fold 1: train tss = 0.7882 : val tss = 0.2254 ::: train hss = 0.3544 : val hss = 0.3018
Fold 2: train tss = 0.6780 : val tss = 0.7053 ::: train hss = 0.1144 : val hss = 0.2797
Fold 3: train tss = 0.6772 : val tss = 0.3494 ::: train hss = 0.1624 : val hss = 0.0427
Fold 4: train tss = 0.6028 : val tss = 0.5747 ::: train hss = 0.1074 : val hss = 0.1521
mean cv TSS: 0.3728
mean cv HSS: 0.1575
326/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.8482 : val tss = -0.0063 ::: train hss = 0.6525 : val hss = -0.0100
Fold 1: train tss = 0.8033 : val tss = 0.3189 ::: train hss = 0.4384 : val hss = 0.1366
Fold 2: train tss = 0.7781 : val tss = 0.6951 ::: train hss = 0.1528 : val hss = 0.2919
Fold 3: train tss = 0.7156 : val tss = 0.2520 ::: train hss = 0.1502 : val hss = 0.0442
Fold 4: train tss = 0.7769 : val tss = 0.7207 ::: train hss = 0.1987 : val hss = 0.3167
mean cv TSS: 0.3961
mean cv HSS: 0.1559
327/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.4999 : val tss = -0.0004 ::: train hss = 0.6450 : val hss = -0.0007
Fold 1: train tss = 0.8010 : val tss = 0.2846 ::: train hss = 0.3544 : val hss = 0.1073
Fold 2: train tss = 0.7090 : val tss = 0.6783 ::: train hss = 0.1295 : val hss = 0.2639
Fold 3: train tss = 0.7064 : val tss = 0.0498 ::: train hss = 0.1813 : val hss = 0.0123
Fold 4: train tss = 0.7117 : val tss = 0.6501 ::: train hss = 0.1536 : val hss = 0.2424
mean cv TSS: 0.3325
mean cv HSS: 0.1250
328/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.8161 : val tss = 0.2363 ::: train hss = 0.1027 : val hss = 0.0685
Fold 1: train tss = 0.3517 : val tss = 0.3659 ::: train hss = 0.0311 : val hss = 0.0592
Fold 2: train tss = 0.5733 : val tss = 0.5816 ::: train hss = 0.0792 : val hss = 0.1914
Fold 3: train tss = 0.6347 : val tss = 0.3723 ::: train hss = 0.1645 : val hss = 0.0533
Fold 4: train tss = 0.6563 : val tss = 0.5811 ::: train hss = 0.1335 : val hss = 0.1668
mean cv TSS: 0.4274
mean cv HSS: 0.1078
329/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.8119 : val tss = 0.0590 ::: train hss = 0.0920 : val hss = 0.0556
Fold 1: train tss = 0.6193 : val tss = 0.3465 ::: train hss = 0.0910 : val hss = 0.0643
Fold 2: train tss = 0.5440 : val tss = 0.5923 ::: train hss = 0.0715 : val hss = 0.1799
Fold 3: train tss = 0.4481 : val tss = 0.0101 ::: train hss = 0.0776 : val hss = 0.0003
Fold 4: train tss = 0.4980 : val tss = 0.3924 ::: train hss = 0.0818 : val hss = 0.0781
mean cv TSS: 0.2801
mean cv HSS: 0.0757
330/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 239637
Fold 0: train tss = 0.9907 : val tss = 0.0090 ::: train hss = 0.3387 : val hss = 0.0097
Fold 1: train tss = 0.8253 : val tss = 0.3360 ::: train hss = 0.2206 : val hss = 0.1080
Fold 2: train tss = 0.7421 : val tss = 0.6660 ::: train hss = 0.1402 : val hss = 0.2677
Fold 3: train tss = 0.8103 : val tss = 0.1757 ::: train hss = 0.2532 : val hss = 0.0463
Fold 4: train tss = 0.7678 : val tss = 0.6756 ::: train hss = 0.1999 : val hss = 0.2695
mean cv TSS: 0.3725
mean cv HSS: 0.1402
331/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9833 : val tss = -0.0056 ::: train hss = 0.2197 : val hss = -0.0054
Fold 1: train tss = 0.8777 : val tss = 0.3047 ::: train hss = 0.3313 : val hss = 0.0950
Fold 2: train tss = 0.7090 : val tss = 0.4699 ::: train hss = 0.1233 : val hss = 0.1136
Fold 3: train tss = 0.7204 : val tss = 0.5942 ::: train hss = 0.1717 : val hss = 0.0527
Fold 4: train tss = 0.6699 : val tss = 0.6552 ::: train hss = 0.1286 : val hss = 0.2070
mean cv TSS: 0.4037
mean cv HSS: 0.0926
332/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.9427 : val tss = -0.0176 ::: train hss = 0.3771 : val hss = -0.0206
Fold 1: train tss = 0.6757 : val tss = 0.4026 ::: train hss = 0.1113 : val hss = 0.1135
Fold 2: train tss = 0.7579 : val tss = 0.7262 ::: train hss = 0.1731 : val hss = 0.3614
Fold 3: train tss = 0.6547 : val tss = 0.2601 ::: train hss = 0.1388 : val hss = 0.0257
Fold 4: train tss = 0.6491 : val tss = 0.6168 ::: train hss = 0.1252 : val hss = 0.1824
mean cv TSS: 0.3976
mean cv HSS: 0.1325
333/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.5912 : val tss = 0.1077 ::: train hss = 0.2252 : val hss = 0.1074
Fold 1: train tss = 0.6721 : val tss = 0.4012 ::: train hss = 0.1147 : val hss = 0.1309
Fold 2: train tss = 0.4430 : val tss = 0.6393 ::: train hss = 0.0664 : val hss = 0.2197
Fold 3: train tss = 0.5884 : val tss = 0.0769 ::: train hss = 0.1116 : val hss = 0.0073
Fold 4: train tss = 0.5630 : val tss = 0.5589 ::: train hss = 0.0889 : val hss = 0.1448
mean cv TSS: 0.3568
mean cv HSS: 0.1220
334/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.8957 : val tss = 0.0674 ::: train hss = 0.4841 : val hss = 0.0858
Fold 1: train tss = 0.8908 : val tss = 0.2689 ::: train hss = 0.3135 : val hss = 0.1058
Fold 2: train tss = 0.8561 : val tss = 0.6642 ::: train hss = 0.2548 : val hss = 0.3891
Fold 3: train tss = 0.8041 : val tss = 0.3092 ::: train hss = 0.2416 : val hss = 0.0520
Fold 4: train tss = 0.7929 : val tss = 0.6668 ::: train hss = 0.2293 : val hss = 0.2955
mean cv TSS: 0.3953
mean cv HSS: 0.1856
335/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.5943 : val tss = 0.0971 ::: train hss = 0.3009 : val hss = 0.1209
Fold 1: train tss = 0.8318 : val tss = 0.2876 ::: train hss = 0.3601 : val hss = 0.1207
Fold 2: train tss = 0.7116 : val tss = 0.6593 ::: train hss = 0.1271 : val hss = 0.2408
Fold 3: train tss = 0.6646 : val tss = 0.3976 ::: train hss = 0.1405 : val hss = 0.0369
Fold 4: train tss = 0.6768 : val tss = 0.6625 ::: train hss = 0.1452 : val hss = 0.2200
mean cv TSS: 0.4208
mean cv HSS: 0.1478
336/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8888 : val tss = 0.1712 ::: train hss = 0.2714 : val hss = 0.0963
Fold 1: train tss = 0.7118 : val tss = 0.3944 ::: train hss = 0.2117 : val hss = 0.1626
Fold 2: train tss = 0.7734 : val tss = 0.7412 ::: train hss = 0.2228 : val hss = 0.3635
Fold 3: train tss = 0.7906 : val tss = 0.2828 ::: train hss = 0.2476 : val hss = 0.0727
Fold 4: train tss = 0.7341 : val tss = 0.6499 ::: train hss = 0.1799 : val hss = 0.2209
mean cv TSS: 0.4479
mean cv HSS: 0.1832
337/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.6330 : val tss = 0.2000 ::: train hss = 0.1455 : val hss = 0.1101
Fold 1: train tss = 0.8271 : val tss = 0.2120 ::: train hss = 0.3117 : val hss = 0.1487
Fold 2: train tss = 0.6590 : val tss = 0.6038 ::: train hss = 0.1177 : val hss = 0.2005
Fold 3: train tss = 0.7032 : val tss = 0.0946 ::: train hss = 0.2050 : val hss = 0.0127
Fold 4: train tss = 0.6128 : val tss = 0.5111 ::: train hss = 0.1089 : val hss = 0.1186
mean cv TSS: 0.3243
mean cv HSS: 0.1181
338/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9888 : val tss = 0.0992 ::: train hss = 0.2974 : val hss = 0.0587
Fold 1: train tss = 0.8890 : val tss = 0.1199 ::: train hss = 0.3462 : val hss = 0.0495
Fold 2: train tss = 0.8423 : val tss = 0.7043 ::: train hss = 0.2539 : val hss = 0.3384
Fold 3: train tss = 0.8160 : val tss = 0.3315 ::: train hss = 0.2663 : val hss = 0.0745
Fold 4: train tss = 0.7917 : val tss = 0.6637 ::: train hss = 0.2151 : val hss = 0.2501
mean cv TSS: 0.3837
mean cv HSS: 0.1542
339/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.8406 : val tss = -0.0082 ::: train hss = 0.2924 : val hss = -0.0043
Fold 1: train tss = 0.8323 : val tss = 0.3584 ::: train hss = 0.2513 : val hss = 0.1317
Fold 2: train tss = 0.7439 : val tss = 0.5830 ::: train hss = 0.1303 : val hss = 0.1999
Fold 3: train tss = 0.8112 : val tss = 0.2475 ::: train hss = 0.2426 : val hss = 0.1149
Fold 4: train tss = 0.6732 : val tss = 0.5006 ::: train hss = 0.1487 : val hss = 0.1223
mean cv TSS: 0.3363
mean cv HSS: 0.1129
340/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.7970 : val tss = -0.0096 ::: train hss = 0.5226 : val hss = -0.0138
Fold 1: train tss = 0.7898 : val tss = 0.2580 ::: train hss = 0.1953 : val hss = 0.1577
Fold 2: train tss = 0.7561 : val tss = 0.6749 ::: train hss = 0.1784 : val hss = 0.2664
Fold 3: train tss = 0.6680 : val tss = 0.2498 ::: train hss = 0.1463 : val hss = 0.0283
Fold 4: train tss = 0.7650 : val tss = 0.5794 ::: train hss = 0.1995 : val hss = 0.1801
mean cv TSS: 0.3505
mean cv HSS: 0.1237
341/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 145916
Fold 0: train tss = 0.6952 : val tss = 0.0465 ::: train hss = 0.3758 : val hss = 0.0384
Fold 1: train tss = 0.7874 : val tss = 0.3478 ::: train hss = 0.2679 : val hss = 0.2020
Fold 2: train tss = 0.6188 : val tss = 0.6700 ::: train hss = 0.0940 : val hss = 0.2567
Fold 3: train tss = 0.6448 : val tss = 0.1422 ::: train hss = 0.1334 : val hss = 0.0163
Fold 4: train tss = 0.6242 : val tss = 0.5551 ::: train hss = 0.1183 : val hss = 0.1429
mean cv TSS: 0.3523
mean cv HSS: 0.1312
342/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.7987 : val tss = 0.0161 ::: train hss = 0.6797 : val hss = 0.0234
Fold 1: train tss = 0.8205 : val tss = 0.3202 ::: train hss = 0.4369 : val hss = 0.1468
Fold 2: train tss = 0.7981 : val tss = 0.6065 ::: train hss = 0.2074 : val hss = 0.1901
Fold 3: train tss = 0.8129 : val tss = 0.2686 ::: train hss = 0.2571 : val hss = 0.0495
Fold 4: train tss = 0.7631 : val tss = 0.6453 ::: train hss = 0.1968 : val hss = 0.2098
mean cv TSS: 0.3713
mean cv HSS: 0.1239
343/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.5981 : val tss = -0.0059 ::: train hss = 0.4984 : val hss = -0.0095
Fold 1: train tss = 0.8385 : val tss = 0.3479 ::: train hss = 0.4073 : val hss = 0.1321
Fold 2: train tss = 0.7155 : val tss = 0.6323 ::: train hss = 0.1289 : val hss = 0.2106
Fold 3: train tss = 0.7104 : val tss = 0.4708 ::: train hss = 0.1678 : val hss = 0.0559
Fold 4: train tss = 0.7061 : val tss = 0.7400 ::: train hss = 0.1562 : val hss = 0.3410
mean cv TSS: 0.4370
mean cv HSS: 0.1460
344/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.9839 : val tss = 0.1397 ::: train hss = 0.2262 : val hss = 0.1437
Fold 1: train tss = 0.8158 : val tss = 0.2219 ::: train hss = 0.3412 : val hss = 0.3161
Fold 2: train tss = 0.5092 : val tss = 0.6148 ::: train hss = 0.0752 : val hss = 0.2027
Fold 3: train tss = 0.6513 : val tss = 0.2684 ::: train hss = 0.1352 : val hss = 0.0283
Fold 4: train tss = 0.5997 : val tss = 0.4674 ::: train hss = 0.1051 : val hss = 0.1025
mean cv TSS: 0.3424
mean cv HSS: 0.1587
345/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.7337 : val tss = 0.1787 ::: train hss = 0.1726 : val hss = 0.1172
Fold 1: train tss = 0.5731 : val tss = 0.3708 ::: train hss = 0.0909 : val hss = 0.0611
Fold 2: train tss = 0.4394 : val tss = 0.4814 ::: train hss = 0.0439 : val hss = 0.1634
Fold 3: train tss = 0.6079 : val tss = 0.1300 ::: train hss = 0.1282 : val hss = 0.0342
Fold 4: train tss = 0.5917 : val tss = 0.5561 ::: train hss = 0.1099 : val hss = 0.1463
mean cv TSS: 0.3434
mean cv HSS: 0.1044
346/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9436 : val tss = 0.0215 ::: train hss = 0.4103 : val hss = 0.0217
Fold 1: train tss = 0.8647 : val tss = 0.2901 ::: train hss = 0.2620 : val hss = 0.1309
Fold 2: train tss = 0.7633 : val tss = 0.6726 ::: train hss = 0.1392 : val hss = 0.2831
Fold 3: train tss = 0.6459 : val tss = 0.1943 ::: train hss = 0.1253 : val hss = 0.0334
Fold 4: train tss = 0.6954 : val tss = 0.6761 ::: train hss = 0.1330 : val hss = 0.2413
mean cv TSS: 0.3709
mean cv HSS: 0.1421
347/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9815 : val tss = -0.0108 ::: train hss = 0.2024 : val hss = -0.0151
Fold 1: train tss = 0.8601 : val tss = 0.3535 ::: train hss = 0.2904 : val hss = 0.0782
Fold 2: train tss = 0.6970 : val tss = 0.6219 ::: train hss = 0.1201 : val hss = 0.2088
Fold 3: train tss = 0.7101 : val tss = 0.2403 ::: train hss = 0.1573 : val hss = 0.0371
Fold 4: train tss = 0.6838 : val tss = 0.6247 ::: train hss = 0.1312 : val hss = 0.2238
mean cv TSS: 0.3659
mean cv HSS: 0.1066
348/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.9469 : val tss = -0.0141 ::: train hss = 0.5827 : val hss = -0.0142
Fold 1: train tss = 0.7385 : val tss = 0.3204 ::: train hss = 0.1672 : val hss = 0.1769
Fold 2: train tss = 0.7286 : val tss = 0.7101 ::: train hss = 0.1681 : val hss = 0.3062
Fold 3: train tss = 0.6934 : val tss = 0.4059 ::: train hss = 0.1629 : val hss = 0.0546
Fold 4: train tss = 0.6842 : val tss = 0.5552 ::: train hss = 0.1562 : val hss = 0.1511
mean cv TSS: 0.3955
mean cv HSS: 0.1349
349/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.6449 : val tss = 0.1246 ::: train hss = 0.3440 : val hss = 0.1162
Fold 1: train tss = 0.7839 : val tss = 0.2527 ::: train hss = 0.3284 : val hss = 0.3011
Fold 2: train tss = 0.4329 : val tss = 0.6739 ::: train hss = 0.0566 : val hss = 0.2703
Fold 3: train tss = 0.6124 : val tss = 0.3327 ::: train hss = 0.1240 : val hss = 0.0317
Fold 4: train tss = 0.5920 : val tss = 0.6140 ::: train hss = 0.1013 : val hss = 0.1827
mean cv TSS: 0.3996
mean cv HSS: 0.1804
350/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9970 : val tss = 0.0110 ::: train hss = 0.6135 : val hss = 0.0160
Fold 1: train tss = 0.9272 : val tss = 0.2770 ::: train hss = 0.4631 : val hss = 0.1138
Fold 2: train tss = 0.7432 : val tss = 0.6295 ::: train hss = 0.1475 : val hss = 0.2117
Fold 3: train tss = 0.7442 : val tss = 0.3706 ::: train hss = 0.1836 : val hss = 0.0551
Fold 4: train tss = 0.7601 : val tss = 0.7224 ::: train hss = 0.1872 : val hss = 0.3555
mean cv TSS: 0.4021
mean cv HSS: 0.1504
351/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.5981 : val tss = -0.0063 ::: train hss = 0.4984 : val hss = -0.0100
Fold 1: train tss = 0.7819 : val tss = 0.2792 ::: train hss = 0.2045 : val hss = 0.1042
Fold 2: train tss = 0.6420 : val tss = 0.6840 ::: train hss = 0.0867 : val hss = 0.2561
Fold 3: train tss = 0.7206 : val tss = 0.5327 ::: train hss = 0.1937 : val hss = 0.0746
Fold 4: train tss = 0.6663 : val tss = 0.7099 ::: train hss = 0.1209 : val hss = 0.3178
mean cv TSS: 0.4399
mean cv HSS: 0.1485
352/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 109820
Fold 0: train tss = 0.7745 : val tss = 0.0299 ::: train hss = 0.1249 : val hss = 0.0182
Fold 1: train tss = 0.8719 : val tss = 0.1890 ::: train hss = 0.3994 : val hss = 0.1185
Fold 2: train tss = 0.6880 : val tss = 0.4342 ::: train hss = 0.1608 : val hss = 0.1036
Fold 3: train tss = 0.7472 : val tss = 0.0672 ::: train hss = 0.2001 : val hss = 0.0132
Fold 4: train tss = 0.7013 : val tss = 0.5705 ::: train hss = 0.1551 : val hss = 0.1520
mean cv TSS: 0.2582
mean cv HSS: 0.0811
353/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.9781 : val tss = 0.0283 ::: train hss = 0.1762 : val hss = 0.0224
Fold 1: train tss = 0.8201 : val tss = 0.2505 ::: train hss = 0.3979 : val hss = 0.1338
Fold 2: train tss = 0.7288 : val tss = 0.6406 ::: train hss = 0.1974 : val hss = 0.2156
Fold 3: train tss = 0.6149 : val tss = 0.0946 ::: train hss = 0.1409 : val hss = 0.0107
Fold 4: train tss = 0.6594 : val tss = 0.6140 ::: train hss = 0.1394 : val hss = 0.2034
mean cv TSS: 0.3256
mean cv HSS: 0.1172
354/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9943 : val tss = 0.0111 ::: train hss = 0.4572 : val hss = 0.0101
Fold 1: train tss = 0.9131 : val tss = 0.2081 ::: train hss = 0.3877 : val hss = 0.0657
Fold 2: train tss = 0.8176 : val tss = 0.6755 ::: train hss = 0.1639 : val hss = 0.2732
Fold 3: train tss = 0.8091 : val tss = 0.2587 ::: train hss = 0.2416 : val hss = 0.0940
Fold 4: train tss = 0.7435 : val tss = 0.6335 ::: train hss = 0.1778 : val hss = 0.2277
mean cv TSS: 0.3574
mean cv HSS: 0.1341
355/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9786 : val tss = 0.0361 ::: train hss = 0.1796 : val hss = 0.0177
Fold 1: train tss = 0.8596 : val tss = 0.2476 ::: train hss = 0.1836 : val hss = 0.0715
Fold 2: train tss = 0.6770 : val tss = 0.7169 ::: train hss = 0.1035 : val hss = 0.2970
Fold 3: train tss = 0.7815 : val tss = 0.2747 ::: train hss = 0.2245 : val hss = 0.0565
Fold 4: train tss = 0.7369 : val tss = 0.7145 ::: train hss = 0.1620 : val hss = 0.3098
mean cv TSS: 0.3980
mean cv HSS: 0.1505
356/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.7417 : val tss = 0.0850 ::: train hss = 0.2853 : val hss = 0.0626
Fold 1: train tss = 0.8148 : val tss = 0.2805 ::: train hss = 0.3897 : val hss = 0.2250
Fold 2: train tss = 0.6864 : val tss = 0.7099 ::: train hss = 0.1348 : val hss = 0.2943
Fold 3: train tss = 0.7714 : val tss = 0.0125 ::: train hss = 0.2437 : val hss = 0.0024
Fold 4: train tss = 0.7127 : val tss = 0.6564 ::: train hss = 0.1743 : val hss = 0.2085
mean cv TSS: 0.3488
mean cv HSS: 0.1586
357/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.6412 : val tss = 0.1647 ::: train hss = 0.2420 : val hss = 0.1385
Fold 1: train tss = 0.6475 : val tss = 0.1359 ::: train hss = 0.0812 : val hss = 0.1173
Fold 2: train tss = 0.6501 : val tss = 0.6573 ::: train hss = 0.1147 : val hss = 0.2452
Fold 3: train tss = 0.6850 : val tss = 0.3338 ::: train hss = 0.1634 : val hss = 0.0496
Fold 4: train tss = 0.6176 : val tss = 0.5785 ::: train hss = 0.1205 : val hss = 0.1542
mean cv TSS: 0.3741
mean cv HSS: 0.1410
358/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.7934 : val tss = 0.0008 ::: train hss = 0.3487 : val hss = 0.0009
Fold 1: train tss = 0.7979 : val tss = 0.3233 ::: train hss = 0.3918 : val hss = 0.1184
Fold 2: train tss = 0.7774 : val tss = 0.7130 ::: train hss = 0.1593 : val hss = 0.3114
Fold 3: train tss = 0.7869 : val tss = 0.3489 ::: train hss = 0.2154 : val hss = 0.0778
Fold 4: train tss = 0.7692 : val tss = 0.6815 ::: train hss = 0.1980 : val hss = 0.2254
mean cv TSS: 0.4135
mean cv HSS: 0.1468
359/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.4493 : val tss = -0.0037 ::: train hss = 0.5135 : val hss = -0.0064
Fold 1: train tss = 0.8018 : val tss = 0.4434 ::: train hss = 0.2232 : val hss = 0.1452
Fold 2: train tss = 0.7046 : val tss = 0.6345 ::: train hss = 0.1329 : val hss = 0.2132
Fold 3: train tss = 0.6436 : val tss = 0.2516 ::: train hss = 0.1250 : val hss = 0.0535
Fold 4: train tss = 0.7277 : val tss = 0.6515 ::: train hss = 0.1799 : val hss = 0.2094
mean cv TSS: 0.3955
mean cv HSS: 0.1230
360/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.8361 : val tss = -0.0102 ::: train hss = 0.2200 : val hss = -0.0077
Fold 1: train tss = 0.5075 : val tss = 0.3118 ::: train hss = 0.0688 : val hss = 0.0615
Fold 2: train tss = 0.4348 : val tss = 0.5551 ::: train hss = 0.0497 : val hss = 0.1636
Fold 3: train tss = 0.6664 : val tss = 0.1820 ::: train hss = 0.1546 : val hss = 0.0229
Fold 4: train tss = 0.6698 : val tss = 0.5695 ::: train hss = 0.1439 : val hss = 0.1494
mean cv TSS: 0.3216
mean cv HSS: 0.0779
361/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.5743 : val tss = 0.3038 ::: train hss = 0.0938 : val hss = 0.1932
Fold 1: train tss = 0.6223 : val tss = 0.2685 ::: train hss = 0.0638 : val hss = 0.0491
Fold 2: train tss = 0.5627 : val tss = 0.6235 ::: train hss = 0.1418 : val hss = 0.3345
Fold 3: train tss = 0.6199 : val tss = 0.1282 ::: train hss = 0.1365 : val hss = 0.0218
Fold 4: train tss = 0.5881 : val tss = 0.5733 ::: train hss = 0.0935 : val hss = 0.1597
mean cv TSS: 0.3795
mean cv HSS: 0.1517
362/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.8440 : val tss = -0.0260 ::: train hss = 0.3880 : val hss = -0.0133
Fold 1: train tss = 0.9245 : val tss = 0.2404 ::: train hss = 0.2804 : val hss = 0.0864
Fold 2: train tss = 0.8012 : val tss = 0.6608 ::: train hss = 0.1894 : val hss = 0.2842
Fold 3: train tss = 0.6787 : val tss = 0.3348 ::: train hss = 0.1273 : val hss = 0.0839
Fold 4: train tss = 0.7224 : val tss = 0.6385 ::: train hss = 0.1772 : val hss = 0.2061
mean cv TSS: 0.3697
mean cv HSS: 0.1294
363/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 239637
Fold 0: train tss = 0.5865 : val tss = -0.0166 ::: train hss = 0.1629 : val hss = -0.0089
Fold 1: train tss = 0.8570 : val tss = 0.2919 ::: train hss = 0.3133 : val hss = 0.1254
Fold 2: train tss = 0.7098 : val tss = 0.7138 ::: train hss = 0.1595 : val hss = 0.3156
Fold 3: train tss = 0.6984 : val tss = 0.3567 ::: train hss = 0.1634 : val hss = 0.0451
Fold 4: train tss = 0.6716 : val tss = 0.5852 ::: train hss = 0.1675 : val hss = 0.1612
mean cv TSS: 0.3862
mean cv HSS: 0.1277
364/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.8929 : val tss = 0.0842 ::: train hss = 0.3682 : val hss = 0.0874
Fold 1: train tss = 0.8023 : val tss = 0.3393 ::: train hss = 0.3141 : val hss = 0.1347
Fold 2: train tss = 0.7015 : val tss = 0.7190 ::: train hss = 0.1604 : val hss = 0.3011
Fold 3: train tss = 0.6557 : val tss = 0.3022 ::: train hss = 0.1570 : val hss = 0.0339
Fold 4: train tss = 0.5831 : val tss = 0.5975 ::: train hss = 0.0949 : val hss = 0.1681
mean cv TSS: 0.4084
mean cv HSS: 0.1451
365/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.5920 : val tss = 0.1618 ::: train hss = 0.2417 : val hss = 0.0917
Fold 1: train tss = 0.5664 : val tss = 0.4098 ::: train hss = 0.0965 : val hss = 0.0969
Fold 2: train tss = 0.5141 : val tss = 0.6287 ::: train hss = 0.0655 : val hss = 0.2079
Fold 3: train tss = 0.5220 : val tss = 0.2890 ::: train hss = 0.0800 : val hss = 0.0359
Fold 4: train tss = 0.5073 : val tss = 0.4764 ::: train hss = 0.0801 : val hss = 0.1044
mean cv TSS: 0.3931
mean cv HSS: 0.1074
366/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.8971 : val tss = 0.0188 ::: train hss = 0.5788 : val hss = 0.0224
Fold 1: train tss = 0.9091 : val tss = 0.3076 ::: train hss = 0.3897 : val hss = 0.0971
Fold 2: train tss = 0.7594 : val tss = 0.6773 ::: train hss = 0.1497 : val hss = 0.2653
Fold 3: train tss = 0.7695 : val tss = 0.3776 ::: train hss = 0.2056 : val hss = 0.0505
Fold 4: train tss = 0.7013 : val tss = 0.7056 ::: train hss = 0.1443 : val hss = 0.2798
mean cv TSS: 0.4174
mean cv HSS: 0.1430
367/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.1500 : val tss = -0.0010 ::: train hss = 0.2609 : val hss = -0.0019
Fold 1: train tss = 0.7780 : val tss = 0.3879 ::: train hss = 0.2368 : val hss = 0.1196
Fold 2: train tss = 0.6630 : val tss = 0.7058 ::: train hss = 0.1537 : val hss = 0.3585
Fold 3: train tss = 0.7025 : val tss = 0.3341 ::: train hss = 0.1611 : val hss = 0.0523
Fold 4: train tss = 0.6581 : val tss = 0.6862 ::: train hss = 0.1273 : val hss = 0.2453
mean cv TSS: 0.4226
mean cv HSS: 0.1548
368/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8341 : val tss = 0.0279 ::: train hss = 0.1974 : val hss = 0.0089
Fold 1: train tss = 0.8853 : val tss = 0.2831 ::: train hss = 0.3491 : val hss = 0.1278
Fold 2: train tss = 0.7464 : val tss = 0.7280 ::: train hss = 0.2186 : val hss = 0.3270
Fold 3: train tss = 0.7892 : val tss = 0.0428 ::: train hss = 0.2651 : val hss = 0.0129
Fold 4: train tss = 0.7419 : val tss = 0.5904 ::: train hss = 0.2094 : val hss = 0.1840
mean cv TSS: 0.3344
mean cv HSS: 0.1321
369/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.9681 : val tss = 0.0263 ::: train hss = 0.1270 : val hss = 0.0186
Fold 1: train tss = 0.7509 : val tss = 0.4323 ::: train hss = 0.1563 : val hss = 0.2099
Fold 2: train tss = 0.7196 : val tss = 0.6080 ::: train hss = 0.1600 : val hss = 0.3270
Fold 3: train tss = 0.6175 : val tss = 0.3892 ::: train hss = 0.1258 : val hss = 0.0504
Fold 4: train tss = 0.6083 : val tss = 0.5188 ::: train hss = 0.1110 : val hss = 0.1339
mean cv TSS: 0.3949
mean cv HSS: 0.1480
370/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9415 : val tss = -0.0372 ::: train hss = 0.3423 : val hss = -0.0188
Fold 1: train tss = 0.9367 : val tss = 0.1904 ::: train hss = 0.3296 : val hss = 0.0600
Fold 2: train tss = 0.8554 : val tss = 0.6444 ::: train hss = 0.2232 : val hss = 0.3158
Fold 3: train tss = 0.8340 : val tss = 0.3776 ::: train hss = 0.2740 : val hss = 0.1377
Fold 4: train tss = 0.7750 : val tss = 0.6900 ::: train hss = 0.1967 : val hss = 0.2850
mean cv TSS: 0.3730
mean cv HSS: 0.1559
371/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9804 : val tss = -0.0581 ::: train hss = 0.1932 : val hss = -0.0200
Fold 1: train tss = 0.8700 : val tss = 0.2667 ::: train hss = 0.2803 : val hss = 0.1002
Fold 2: train tss = 0.7824 : val tss = 0.5941 ::: train hss = 0.1597 : val hss = 0.1939
Fold 3: train tss = 0.6763 : val tss = 0.2963 ::: train hss = 0.1312 : val hss = 0.0302
Fold 4: train tss = 0.7425 : val tss = 0.6965 ::: train hss = 0.1583 : val hss = 0.2852
mean cv TSS: 0.3591
mean cv HSS: 0.1179
372/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.7392 : val tss = 0.0262 ::: train hss = 0.2365 : val hss = 0.0217
Fold 1: train tss = 0.8615 : val tss = 0.2754 ::: train hss = 0.3589 : val hss = 0.2172
Fold 2: train tss = 0.7102 : val tss = 0.6804 ::: train hss = 0.1614 : val hss = 0.2911
Fold 3: train tss = 0.7593 : val tss = 0.3228 ::: train hss = 0.2041 : val hss = 0.0593
Fold 4: train tss = 0.7028 : val tss = 0.5944 ::: train hss = 0.1627 : val hss = 0.1700
mean cv TSS: 0.3798
mean cv HSS: 0.1519
373/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.6917 : val tss = 0.1231 ::: train hss = 0.2686 : val hss = 0.1117
Fold 1: train tss = 0.7858 : val tss = 0.4507 ::: train hss = 0.2353 : val hss = 0.2365
Fold 2: train tss = 0.5954 : val tss = 0.6293 ::: train hss = 0.1184 : val hss = 0.2099
Fold 3: train tss = 0.6706 : val tss = 0.4131 ::: train hss = 0.1654 : val hss = 0.0550
Fold 4: train tss = 0.6253 : val tss = 0.4661 ::: train hss = 0.1224 : val hss = 0.1100
mean cv TSS: 0.4165
mean cv HSS: 0.1446
374/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 318997
Fold 0: train tss = 0.7483 : val tss = 0.0053 ::: train hss = 0.6109 : val hss = 0.0076
Fold 1: train tss = 0.8229 : val tss = 0.3153 ::: train hss = 0.3865 : val hss = 0.1093
Fold 2: train tss = 0.7438 : val tss = 0.6583 ::: train hss = 0.1713 : val hss = 0.2493
Fold 3: train tss = 0.8165 : val tss = 0.3034 ::: train hss = 0.2581 : val hss = 0.0520
Fold 4: train tss = 0.7555 : val tss = 0.7376 ::: train hss = 0.1791 : val hss = 0.3609
mean cv TSS: 0.4040
mean cv HSS: 0.1558
375/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.3990 : val tss = -0.0030 ::: train hss = 0.4434 : val hss = -0.0053
Fold 1: train tss = 0.8034 : val tss = 0.3949 ::: train hss = 0.3431 : val hss = 0.1572
Fold 2: train tss = 0.7040 : val tss = 0.6794 ::: train hss = 0.1280 : val hss = 0.2559
Fold 3: train tss = 0.6934 : val tss = 0.4009 ::: train hss = 0.1586 : val hss = 0.0762
Fold 4: train tss = 0.7125 : val tss = 0.7116 ::: train hss = 0.1481 : val hss = 0.2810
mean cv TSS: 0.4368
mean cv HSS: 0.1530
376/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8324 : val tss = 0.2084 ::: train hss = 0.1819 : val hss = 0.1351
Fold 1: train tss = 0.7474 : val tss = 0.3725 ::: train hss = 0.2313 : val hss = 0.1209
Fold 2: train tss = 0.6708 : val tss = 0.6293 ::: train hss = 0.1447 : val hss = 0.2292
Fold 3: train tss = 0.5152 : val tss = -0.1327 ::: train hss = 0.0864 : val hss = -0.0045
Fold 4: train tss = 0.6488 : val tss = 0.6318 ::: train hss = 0.1517 : val hss = 0.2034
mean cv TSS: 0.3419
mean cv HSS: 0.1368
377/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.7792 : val tss = 0.0635 ::: train hss = 0.1491 : val hss = 0.0263
Fold 1: train tss = 0.6424 : val tss = 0.4029 ::: train hss = 0.0859 : val hss = 0.0868
Fold 2: train tss = 0.4807 : val tss = 0.4979 ::: train hss = 0.0612 : val hss = 0.1244
Fold 3: train tss = 0.6042 : val tss = 0.3403 ::: train hss = 0.1188 : val hss = 0.0370
Fold 4: train tss = 0.5530 : val tss = 0.4959 ::: train hss = 0.0866 : val hss = 0.1144
mean cv TSS: 0.3601
mean cv HSS: 0.0778
378/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9941 : val tss = 0.0093 ::: train hss = 0.4468 : val hss = 0.0129
Fold 1: train tss = 0.8745 : val tss = 0.2995 ::: train hss = 0.2536 : val hss = 0.0940
Fold 2: train tss = 0.5983 : val tss = 0.6066 ::: train hss = 0.0870 : val hss = 0.2033
Fold 3: train tss = 0.8048 : val tss = 0.4091 ::: train hss = 0.2343 : val hss = 0.0648
Fold 4: train tss = 0.7212 : val tss = 0.6923 ::: train hss = 0.1596 : val hss = 0.2477
mean cv TSS: 0.4033
mean cv HSS: 0.1246
379/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9809 : val tss = -0.0204 ::: train hss = 0.1972 : val hss = -0.0201
Fold 1: train tss = 0.7603 : val tss = 0.2705 ::: train hss = 0.2948 : val hss = 0.0603
Fold 2: train tss = 0.7035 : val tss = 0.6310 ::: train hss = 0.1153 : val hss = 0.2154
Fold 3: train tss = 0.6889 : val tss = 0.3482 ::: train hss = 0.1721 : val hss = 0.0594
Fold 4: train tss = 0.6152 : val tss = 0.6359 ::: train hss = 0.1089 : val hss = 0.2016
mean cv TSS: 0.3730
mean cv HSS: 0.1033
380/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8467 : val tss = -0.0028 ::: train hss = 0.5292 : val hss = -0.0032
Fold 1: train tss = 0.8718 : val tss = 0.3883 ::: train hss = 0.2867 : val hss = 0.1983
Fold 2: train tss = 0.6660 : val tss = 0.7277 ::: train hss = 0.1403 : val hss = 0.3598
Fold 3: train tss = 0.6945 : val tss = 0.1650 ::: train hss = 0.1884 : val hss = 0.0317
Fold 4: train tss = 0.5655 : val tss = 0.5131 ::: train hss = 0.0842 : val hss = 0.1221
mean cv TSS: 0.3583
mean cv HSS: 0.1417
381/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.6848 : val tss = 0.0696 ::: train hss = 0.1712 : val hss = 0.0319
Fold 1: train tss = 0.7245 : val tss = 0.3959 ::: train hss = 0.1637 : val hss = 0.1478
Fold 2: train tss = 0.4799 : val tss = 0.5747 ::: train hss = 0.0613 : val hss = 0.1693
Fold 3: train tss = 0.6224 : val tss = 0.0735 ::: train hss = 0.1327 : val hss = 0.0209
Fold 4: train tss = 0.6048 : val tss = 0.4572 ::: train hss = 0.1024 : val hss = 0.0994
mean cv TSS: 0.3142
mean cv HSS: 0.0938
382/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.8480 : val tss = -0.0263 ::: train hss = 0.6281 : val hss = -0.0255
Fold 1: train tss = 0.8739 : val tss = 0.3324 ::: train hss = 0.3570 : val hss = 0.1209
Fold 2: train tss = 0.7582 : val tss = 0.7206 ::: train hss = 0.1541 : val hss = 0.3336
Fold 3: train tss = 0.8195 : val tss = 0.0657 ::: train hss = 0.2767 : val hss = 0.0189
Fold 4: train tss = 0.6801 : val tss = 0.6321 ::: train hss = 0.1280 : val hss = 0.2004
mean cv TSS: 0.3449
mean cv HSS: 0.1297
383/768
{'batch_size': 128, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.5488 : val tss = -0.0141 ::: train hss = 0.5354 : val hss = -0.0159
Fold 1: train tss = 0.7944 : val tss = 0.2933 ::: train hss = 0.3169 : val hss = 0.1246
Fold 2: train tss = 0.6321 : val tss = 0.5354 ::: train hss = 0.0928 : val hss = 0.1463
Fold 3: train tss = 0.6602 : val tss = 0.3544 ::: train hss = 0.1362 : val hss = 0.0484
Fold 4: train tss = 0.6288 : val tss = 0.6732 ::: train hss = 0.1291 : val hss = 0.2828
mean cv TSS: 0.3684
mean cv HSS: 0.1172
384/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.8871 : val tss = 0.0474 ::: train hss = 0.2447 : val hss = 0.0609
Fold 1: train tss = 0.8428 : val tss = 0.2004 ::: train hss = 0.4435 : val hss = 0.1939
Fold 2: train tss = 0.7119 : val tss = 0.6516 ::: train hss = 0.2121 : val hss = 0.2694
Fold 3: train tss = 0.7873 : val tss = 0.2459 ::: train hss = 0.3301 : val hss = 0.0690
Fold 4: train tss = 0.7412 : val tss = 0.6573 ::: train hss = 0.2117 : val hss = 0.2348
mean cv TSS: 0.3605
mean cv HSS: 0.1656
385/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7692 : val tss = 0.1918 ::: train hss = 0.4028 : val hss = 0.2087
Fold 2: train tss = 0.7079 : val tss = 0.6603 ::: train hss = 0.1856 : val hss = 0.2923
Fold 3: train tss = 0.7460 : val tss = 0.1728 ::: train hss = 0.2322 : val hss = 0.0408
Fold 4: train tss = 0.6664 : val tss = 0.6335 ::: train hss = 0.1944 : val hss = 0.2559
mean cv TSS: 0.3317
mean cv HSS: 0.1595
386/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9945 : val tss = -0.0034 ::: train hss = 0.4625 : val hss = -0.0061
Fold 1: train tss = 0.8675 : val tss = 0.3526 ::: train hss = 0.3227 : val hss = 0.1422
Fold 2: train tss = 0.7605 : val tss = 0.7472 ::: train hss = 0.2069 : val hss = 0.3913
Fold 3: train tss = 0.7904 : val tss = 0.2912 ::: train hss = 0.3116 : val hss = 0.0634
Fold 4: train tss = 0.7916 : val tss = 0.6800 ::: train hss = 0.3005 : val hss = 0.2850
mean cv TSS: 0.4135
mean cv HSS: 0.1752
387/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7823 : val tss = 0.2816 ::: train hss = 0.4439 : val hss = 0.1436
Fold 2: train tss = 0.8149 : val tss = 0.7147 ::: train hss = 0.2600 : val hss = 0.3090
Fold 3: train tss = 0.7661 : val tss = 0.0475 ::: train hss = 0.2529 : val hss = 0.0125
Fold 4: train tss = 0.7754 : val tss = 0.6962 ::: train hss = 0.2969 : val hss = 0.2706
mean cv TSS: 0.3480
mean cv HSS: 0.1471
388/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.8027 : val tss = 0.3752 ::: train hss = 0.2964 : val hss = 0.1760
Fold 2: train tss = 0.6922 : val tss = 0.6862 ::: train hss = 0.2060 : val hss = 0.2926
Fold 3: train tss = 0.7723 : val tss = 0.2456 ::: train hss = 0.2711 : val hss = 0.0628
Fold 4: train tss = 0.7415 : val tss = 0.6780 ::: train hss = 0.2381 : val hss = 0.3089
mean cv TSS: 0.3970
mean cv HSS: 0.1681
389/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7657 : val tss = 0.2506 ::: train hss = 0.2646 : val hss = 0.2615
Fold 2: train tss = 0.6586 : val tss = 0.6950 ::: train hss = 0.1572 : val hss = 0.3512
Fold 3: train tss = 0.7552 : val tss = 0.0963 ::: train hss = 0.2549 : val hss = 0.0359
Fold 4: train tss = 0.7241 : val tss = 0.5982 ::: train hss = 0.2148 : val hss = 0.1806
mean cv TSS: 0.3280
mean cv HSS: 0.1658
390/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7393 : val tss = 0.3200 ::: train hss = 0.2318 : val hss = 0.1172
Fold 2: train tss = 0.6914 : val tss = 0.6929 ::: train hss = 0.1471 : val hss = 0.2920
Fold 3: train tss = 0.6832 : val tss = 0.0961 ::: train hss = 0.1718 : val hss = 0.0204
Fold 4: train tss = 0.7342 : val tss = 0.7293 ::: train hss = 0.2292 : val hss = 0.3177
mean cv TSS: 0.3676
mean cv HSS: 0.1495
391/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7328 : val tss = 0.3924 ::: train hss = 0.1942 : val hss = 0.1370
Fold 2: train tss = 0.6787 : val tss = 0.6967 ::: train hss = 0.1255 : val hss = 0.2764
Fold 3: train tss = 0.6451 : val tss = 0.4547 ::: train hss = 0.1394 : val hss = 0.0721
Fold 4: train tss = 0.6283 : val tss = 0.6707 ::: train hss = 0.1733 : val hss = 0.2289
mean cv TSS: 0.4429
mean cv HSS: 0.1429
392/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.7875 : val tss = -0.0018 ::: train hss = 0.2250 : val hss = -0.0034
Fold 1: train tss = 0.7826 : val tss = 0.4406 ::: train hss = 0.2819 : val hss = 0.3142
Fold 2: train tss = 0.7448 : val tss = 0.7295 ::: train hss = 0.1951 : val hss = 0.3671
Fold 3: train tss = 0.6867 : val tss = 0.0993 ::: train hss = 0.1760 : val hss = 0.0277
Fold 4: train tss = 0.7372 : val tss = 0.6541 ::: train hss = 0.2248 : val hss = 0.2696
mean cv TSS: 0.3843
mean cv HSS: 0.1950
393/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7463 : val tss = 0.4209 ::: train hss = 0.1973 : val hss = 0.1477
Fold 2: train tss = 0.5422 : val tss = 0.6078 ::: train hss = 0.1328 : val hss = 0.2160
Fold 3: train tss = 0.7053 : val tss = 0.2667 ::: train hss = 0.1939 : val hss = 0.0517
Fold 4: train tss = 0.6596 : val tss = 0.6441 ::: train hss = 0.1931 : val hss = 0.3068
mean cv TSS: 0.3879
mean cv HSS: 0.1444
394/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9960 : val tss = -0.0025 ::: train hss = 0.5458 : val hss = -0.0045
Fold 1: train tss = 0.8046 : val tss = 0.3403 ::: train hss = 0.3260 : val hss = 0.2579
Fold 2: train tss = 0.7790 : val tss = 0.7168 ::: train hss = 0.2273 : val hss = 0.3352
Fold 3: train tss = 0.7983 : val tss = 0.3918 ::: train hss = 0.2818 : val hss = 0.0564
Fold 4: train tss = 0.7350 : val tss = 0.4900 ::: train hss = 0.2374 : val hss = 0.1246
mean cv TSS: 0.3873
mean cv HSS: 0.1539
395/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7817 : val tss = 0.3855 ::: train hss = 0.3404 : val hss = 0.1229
Fold 2: train tss = 0.6917 : val tss = 0.6838 ::: train hss = 0.1133 : val hss = 0.2548
Fold 3: train tss = 0.7561 : val tss = 0.2666 ::: train hss = 0.2871 : val hss = 0.0643
Fold 4: train tss = 0.7141 : val tss = 0.6043 ::: train hss = 0.2022 : val hss = 0.1766
mean cv TSS: 0.3881
mean cv HSS: 0.1237
396/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 47180
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.8512 : val tss = 0.2209 ::: train hss = 0.4411 : val hss = 0.1579
Fold 2: train tss = 0.6700 : val tss = 0.7604 ::: train hss = 0.1790 : val hss = 0.4304
Fold 3: train tss = 0.6752 : val tss = 0.0924 ::: train hss = 0.1676 : val hss = 0.0292
Fold 4: train tss = 0.7039 : val tss = 0.6779 ::: train hss = 0.1902 : val hss = 0.2552
mean cv TSS: 0.3503
mean cv HSS: 0.1745
397/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7102 : val tss = 0.3934 ::: train hss = 0.1014 : val hss = 0.1451
Fold 2: train tss = 0.5949 : val tss = 0.7176 ::: train hss = 0.1191 : val hss = 0.3681
Fold 3: train tss = 0.6824 : val tss = 0.2412 ::: train hss = 0.1811 : val hss = 0.0395
Fold 4: train tss = 0.7003 : val tss = 0.7103 ::: train hss = 0.1823 : val hss = 0.3314
mean cv TSS: 0.4125
mean cv HSS: 0.1768
398/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.0498 : val tss = 0.0000 ::: train hss = 0.0865 : val hss = 0.0000
Fold 1: train tss = 0.7626 : val tss = 0.2769 ::: train hss = 0.2688 : val hss = 0.1229
Fold 2: train tss = 0.7656 : val tss = 0.7166 ::: train hss = 0.2023 : val hss = 0.3642
Fold 3: train tss = 0.7285 : val tss = 0.1981 ::: train hss = 0.2407 : val hss = 0.0349
Fold 4: train tss = 0.6788 : val tss = 0.6344 ::: train hss = 0.1757 : val hss = 0.2090
mean cv TSS: 0.3652
mean cv HSS: 0.1462
399/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7346 : val tss = 0.2907 ::: train hss = 0.2077 : val hss = 0.1131
Fold 2: train tss = 0.7014 : val tss = 0.7284 ::: train hss = 0.1902 : val hss = 0.3490
Fold 3: train tss = 0.7235 : val tss = 0.1490 ::: train hss = 0.2551 : val hss = 0.0541
Fold 4: train tss = 0.6913 : val tss = 0.5384 ::: train hss = 0.1783 : val hss = 0.1372
mean cv TSS: 0.3413
mean cv HSS: 0.1307
400/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.8348 : val tss = 0.0140 ::: train hss = 0.2049 : val hss = 0.0222
Fold 1: train tss = 0.8016 : val tss = 0.1977 ::: train hss = 0.5150 : val hss = 0.2488
Fold 2: train tss = 0.7598 : val tss = 0.7179 ::: train hss = 0.1600 : val hss = 0.3560
Fold 3: train tss = 0.7711 : val tss = 0.0325 ::: train hss = 0.2819 : val hss = 0.0245
Fold 4: train tss = 0.7198 : val tss = 0.7053 ::: train hss = 0.2059 : val hss = 0.2905
mean cv TSS: 0.3335
mean cv HSS: 0.1884
401/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7915 : val tss = 0.1868 ::: train hss = 0.3026 : val hss = 0.2089
Fold 2: train tss = 0.6842 : val tss = 0.7027 ::: train hss = 0.1671 : val hss = 0.3137
Fold 3: train tss = 0.7723 : val tss = 0.1032 ::: train hss = 0.2869 : val hss = 0.0374
Fold 4: train tss = 0.7241 : val tss = 0.7188 ::: train hss = 0.2502 : val hss = 0.3448
mean cv TSS: 0.3423
mean cv HSS: 0.1810
402/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.8961 : val tss = 0.0423 ::: train hss = 0.5121 : val hss = 0.0543
Fold 1: train tss = 0.8600 : val tss = 0.2473 ::: train hss = 0.3767 : val hss = 0.1004
Fold 2: train tss = 0.7852 : val tss = 0.6162 ::: train hss = 0.2237 : val hss = 0.3848
Fold 3: train tss = 0.8061 : val tss = 0.3058 ::: train hss = 0.2991 : val hss = 0.0906
Fold 4: train tss = 0.7881 : val tss = 0.7077 ::: train hss = 0.2828 : val hss = 0.2751
mean cv TSS: 0.3839
mean cv HSS: 0.1811
403/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7821 : val tss = 0.2549 ::: train hss = 0.4415 : val hss = 0.1169
Fold 2: train tss = 0.7447 : val tss = 0.7121 ::: train hss = 0.2075 : val hss = 0.3041
Fold 3: train tss = 0.7871 : val tss = 0.2773 ::: train hss = 0.2941 : val hss = 0.0812
Fold 4: train tss = 0.7580 : val tss = 0.6904 ::: train hss = 0.2706 : val hss = 0.2437
mean cv TSS: 0.3869
mean cv HSS: 0.1492
404/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.1000 : val tss = 0.0050 ::: train hss = 0.1818 : val hss = 0.0099
Fold 1: train tss = 0.8208 : val tss = 0.3273 ::: train hss = 0.4031 : val hss = 0.2337
Fold 2: train tss = 0.7042 : val tss = 0.6705 ::: train hss = 0.1745 : val hss = 0.3279
Fold 3: train tss = 0.7238 : val tss = 0.1839 ::: train hss = 0.2172 : val hss = 0.0653
Fold 4: train tss = 0.7375 : val tss = 0.6268 ::: train hss = 0.2414 : val hss = 0.2316
mean cv TSS: 0.3627
mean cv HSS: 0.1737
405/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7507 : val tss = 0.4433 ::: train hss = 0.2713 : val hss = 0.2027
Fold 2: train tss = 0.7000 : val tss = 0.7342 ::: train hss = 0.2001 : val hss = 0.4277
Fold 3: train tss = 0.5932 : val tss = 0.1181 ::: train hss = 0.1143 : val hss = 0.0170
Fold 4: train tss = 0.6875 : val tss = 0.6841 ::: train hss = 0.1793 : val hss = 0.2367
mean cv TSS: 0.3959
mean cv HSS: 0.1768
406/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7503 : val tss = 0.2991 ::: train hss = 0.3307 : val hss = 0.1288
Fold 2: train tss = 0.7093 : val tss = 0.7243 ::: train hss = 0.1924 : val hss = 0.3542
Fold 3: train tss = 0.7459 : val tss = 0.2508 ::: train hss = 0.2710 : val hss = 0.0741
Fold 4: train tss = 0.7513 : val tss = 0.6983 ::: train hss = 0.2487 : val hss = 0.2785
mean cv TSS: 0.3945
mean cv HSS: 0.1671
407/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0499 : val tss = 0.0000 ::: train hss = 0.0907 : val hss = 0.0000

Fold 1: train tss = 0.7278 : val tss = 0.3238 ::: train hss = 0.1920 : val hss = 0.1047
Fold 2: train tss = 0.7241 : val tss = 0.7255 ::: train hss = 0.1666 : val hss = 0.3371
Fold 3: train tss = 0.6697 : val tss = 0.3321 ::: train hss = 0.1647 : val hss = 0.0610
Fold 4: train tss = 0.7184 : val tss = 0.7152 ::: train hss = 0.2134 : val hss = 0.3198
mean cv TSS: 0.4193
mean cv HSS: 0.1645
408/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.8861 : val tss = -0.0135 ::: train hss = 0.2317 : val hss = -0.0154
Fold 1: train tss = 0.7969 : val tss = 0.2390 ::: train hss = 0.3081 : val hss = 0.1154
Fold 2: train tss = 0.7475 : val tss = 0.6464 ::: train hss = 0.1834 : val hss = 0.3085
Fold 3: train tss = 0.7218 : val tss = 0.0864 ::: train hss = 0.2114 : val hss = 0.0170
Fold 4: train tss = 0.7162 : val tss = 0.6839 ::: train hss = 0.1905 : val hss = 0.2628
mean cv TSS: 0.3284
mean cv HSS: 0.1377
409/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7644 : val tss = 0.2435 ::: train hss = 0.1928 : val hss = 0.1716
Fold 2: train tss = 0.6622 : val tss = 0.7445 ::: train hss = 0.1595 : val hss = 0.3710
Fold 3: train tss = 0.7577 : val tss = 0.1397 ::: train hss = 0.2672 : val hss = 0.0506
Fold 4: train tss = 0.7050 : val tss = 0.5677 ::: train hss = 0.1819 : val hss = 0.1642
mean cv TSS: 0.3391
mean cv HSS: 0.1515
410/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.6433 : val tss = 0.0000 ::: train hss = 0.2891 : val hss = 0.0000
Fold 1: train tss = 0.7782 : val tss = 0.3094 ::: train hss = 0.4942 : val hss = 0.1545
Fold 2: train tss = 0.7826 : val tss = 0.6700 ::: train hss = 0.1710 : val hss = 0.2577
Fold 3: train tss = 0.7941 : val tss = 0.3111 ::: train hss = 0.3005 : val hss = 0.0686
Fold 4: train tss = 0.7804 : val tss = 0.6599 ::: train hss = 0.2758 : val hss = 0.2802
mean cv TSS: 0.3901
mean cv HSS: 0.1522
411/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7784 : val tss = 0.2158 ::: train hss = 0.4480 : val hss = 0.0890
Fold 2: train tss = 0.6578 : val tss = 0.6122 ::: train hss = 0.1320 : val hss = 0.1913
Fold 3: train tss = 0.7561 : val tss = 0.2860 ::: train hss = 0.2857 : val hss = 0.0924
Fold 4: train tss = 0.7232 : val tss = 0.7399 ::: train hss = 0.2023 : val hss = 0.3408
mean cv TSS: 0.3708
mean cv HSS: 0.1427
412/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.8167 : val tss = 0.1792 ::: train hss = 0.3461 : val hss = 0.1889
Fold 2: train tss = 0.7416 : val tss = 0.7063 ::: train hss = 0.2489 : val hss = 0.3915
Fold 3: train tss = 0.7659 : val tss = 0.0519 ::: train hss = 0.3009 : val hss = 0.0092
Fold 4: train tss = 0.7116 : val tss = 0.6709 ::: train hss = 0.2287 : val hss = 0.2230
mean cv TSS: 0.3217
mean cv HSS: 0.1625
413/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7883 : val tss = 0.1615 ::: train hss = 0.2714 : val hss = 0.1612
Fold 2: train tss = 0.5991 : val tss = 0.6231 ::: train hss = 0.1169 : val hss = 0.2428
Fold 3: train tss = 0.7085 : val tss = 0.1104 ::: train hss = 0.1952 : val hss = 0.0287
Fold 4: train tss = 0.6135 : val tss = 0.6575 ::: train hss = 0.1745 : val hss = 0.2225
mean cv TSS: 0.3105
mean cv HSS: 0.1310
414/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.2000 : val tss = 0.0000 ::: train hss = 0.3333 : val hss = 0.0000
Fold 1: train tss = 0.7791 : val tss = 0.2754 ::: train hss = 0.3797 : val hss = 0.1516
Fold 2: train tss = 0.7839 : val tss = 0.7285 ::: train hss = 0.2007 : val hss = 0.3695
Fold 3: train tss = 0.7332 : val tss = 0.1191 ::: train hss = 0.2692 : val hss = 0.0418
Fold 4: train tss = 0.7720 : val tss = 0.6879 ::: train hss = 0.2687 : val hss = 0.2504
mean cv TSS: 0.3622
mean cv HSS: 0.1627
415/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7751 : val tss = 0.2270 ::: train hss = 0.4593 : val hss = 0.1999
Fold 2: train tss = 0.7251 : val tss = 0.7073 ::: train hss = 0.1695 : val hss = 0.3133
Fold 3: train tss = 0.7573 : val tss = 0.0817 ::: train hss = 0.2731 : val hss = 0.0370
Fold 4: train tss = 0.7124 : val tss = 0.7432 ::: train hss = 0.1942 : val hss = 0.3227
mean cv TSS: 0.3518
mean cv HSS: 0.1746
416/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.6854 : val tss = -0.0017 ::: train hss = 0.1769 : val hss = -0.0032
Fold 1: train tss = 0.8383 : val tss = 0.0730 ::: train hss = 0.3479 : val hss = 0.0413
Fold 2: train tss = 0.7707 : val tss = 0.6865 ::: train hss = 0.2894 : val hss = 0.3356
Fold 3: train tss = 0.7502 : val tss = 0.0227 ::: train hss = 0.2538 : val hss = 0.0084
Fold 4: train tss = 0.7301 : val tss = 0.6480 ::: train hss = 0.2358 : val hss = 0.2154
mean cv TSS: 0.2857
mean cv HSS: 0.1195
417/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7873 : val tss = 0.1202 ::: train hss = 0.3770 : val hss = 0.0399
Fold 2: train tss = 0.7276 : val tss = 0.7243 ::: train hss = 0.2032 : val hss = 0.4319
Fold 3: train tss = 0.7242 : val tss = 0.1475 ::: train hss = 0.2353 : val hss = 0.0226
Fold 4: train tss = 0.7378 : val tss = 0.5884 ::: train hss = 0.2091 : val hss = 0.1896
mean cv TSS: 0.3161
mean cv HSS: 0.1368
418/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.5436 : val tss = 0.0000 ::: train hss = 0.2589 : val hss = 0.0000

Fold 1: train tss = 0.7760 : val tss = 0.2750 ::: train hss = 0.4250 : val hss = 0.1472
Fold 2: train tss = 0.7603 : val tss = 0.6812 ::: train hss = 0.1968 : val hss = 0.3120
Fold 3: train tss = 0.7576 : val tss = 0.5407 ::: train hss = 0.2455 : val hss = 0.0719
Fold 4: train tss = 0.7868 : val tss = 0.7019 ::: train hss = 0.2886 : val hss = 0.2857
mean cv TSS: 0.4397
mean cv HSS: 0.1634
419/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7709 : val tss = 0.2892 ::: train hss = 0.3824 : val hss = 0.2367
Fold 2: train tss = 0.7525 : val tss = 0.7321 ::: train hss = 0.1994 : val hss = 0.3547
Fold 3: train tss = 0.7687 : val tss = 0.2687 ::: train hss = 0.2871 : val hss = 0.0791
Fold 4: train tss = 0.7437 : val tss = 0.7346 ::: train hss = 0.2554 : val hss = 0.3271
mean cv TSS: 0.4049
mean cv HSS: 0.1995
420/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7723 : val tss = 0.1892 ::: train hss = 0.3616 : val hss = 0.1984
Fold 2: train tss = 0.6441 : val tss = 0.7106 ::: train hss = 0.1451 : val hss = 0.3484
Fold 3: train tss = 0.7239 : val tss = 0.0260 ::: train hss = 0.2390 : val hss = 0.0101
Fold 4: train tss = 0.7306 : val tss = 0.6533 ::: train hss = 0.1981 : val hss = 0.2259
mean cv TSS: 0.3158
mean cv HSS: 0.1565
421/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8304 : val tss = 0.2718 ::: train hss = 0.2890 : val hss = 0.2727
Fold 2: train tss = 0.7165 : val tss = 0.7227 ::: train hss = 0.2147 : val hss = 0.3911
Fold 3: train tss = 0.7035 : val tss = 0.2782 ::: train hss = 0.1900 : val hss = 0.0686
Fold 4: train tss = 0.6703 : val tss = 0.6870 ::: train hss = 0.1751 : val hss = 0.2761
mean cv TSS: 0.3920
mean cv HSS: 0.2017
422/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.0492 : val tss = 0.0036 ::: train hss = 0.0702 : val hss = 0.0068
Fold 1: train tss = 0.7420 : val tss = 0.3725 ::: train hss = 0.2162 : val hss = 0.1227
Fold 2: train tss = 0.6704 : val tss = 0.6912 ::: train hss = 0.1217 : val hss = 0.2818
Fold 3: train tss = 0.7653 : val tss = 0.2627 ::: train hss = 0.2518 : val hss = 0.0664
Fold 4: train tss = 0.6670 : val tss = 0.6422 ::: train hss = 0.1416 : val hss = 0.2090
mean cv TSS: 0.3944
mean cv HSS: 0.1374
423/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0498 : val tss = -0.0004 ::: train hss = 0.0865 : val hss = -0.0007
Fold 1: train tss = 0.7219 : val tss = 0.3354 ::: train hss = 0.1802 : val hss = 0.1092
Fold 2: train tss = 0.6691 : val tss = 0.6761 ::: train hss = 0.1169 : val hss = 0.2549
Fold 3: train tss = 0.6573 : val tss = 0.2670 ::: train hss = 0.1559 : val hss = 0.0519
Fold 4: train tss = 0.7000 : val tss = 0.6876 ::: train hss = 0.1959 : val hss = 0.2574
mean cv TSS: 0.3931
mean cv HSS: 0.1345
424/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.8433 : val tss = 0.0114 ::: train hss = 0.3627 : val hss = 0.0196
Fold 1: train tss = 0.7254 : val tss = 0.3483 ::: train hss = 0.2155 : val hss = 0.0882
Fold 2: train tss = 0.7647 : val tss = 0.5371 ::: train hss = 0.1915 : val hss = 0.1845
Fold 3: train tss = 0.7711 : val tss = 0.0356 ::: train hss = 0.2171 : val hss = 0.0189
Fold 4: train tss = 0.6698 : val tss = 0.7040 ::: train hss = 0.1710 : val hss = 0.3088
mean cv TSS: 0.3273
mean cv HSS: 0.1240
425/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7965 : val tss = 0.2217 ::: train hss = 0.1851 : val hss = 0.2636
Fold 2: train tss = 0.6041 : val tss = 0.7121 ::: train hss = 0.1544 : val hss = 0.3135
Fold 3: train tss = 0.6996 : val tss = 0.2104 ::: train hss = 0.2201 : val hss = 0.0338
Fold 4: train tss = 0.6395 : val tss = 0.6861 ::: train hss = 0.1806 : val hss = 0.2904
mean cv TSS: 0.3661
mean cv HSS: 0.1802
426/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9434 : val tss = -0.0015 ::: train hss = 0.4014 : val hss = -0.0028
Fold 1: train tss = 0.8521 : val tss = 0.2480 ::: train hss = 0.3808 : val hss = 0.0573
Fold 2: train tss = 0.7700 : val tss = 0.6256 ::: train hss = 0.1880 : val hss = 0.3701
Fold 3: train tss = 0.7537 : val tss = 0.5108 ::: train hss = 0.2390 : val hss = 0.0774
Fold 4: train tss = 0.7316 : val tss = 0.6284 ::: train hss = 0.2554 : val hss = 0.2221
mean cv TSS: 0.4023
mean cv HSS: 0.1448
427/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8119 : val tss = 0.3642 ::: train hss = 0.4005 : val hss = 0.1050
Fold 2: train tss = 0.7377 : val tss = 0.7069 ::: train hss = 0.1612 : val hss = 0.3805
Fold 3: train tss = 0.7631 : val tss = 0.2757 ::: train hss = 0.2730 : val hss = 0.0880
Fold 4: train tss = 0.7080 : val tss = 0.6624 ::: train hss = 0.2115 : val hss = 0.2440
mean cv TSS: 0.4018
mean cv HSS: 0.1635
428/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7235 : val tss = 0.4111 ::: train hss = 0.1915 : val hss = 0.1573
Fold 2: train tss = 0.6577 : val tss = 0.7030 ::: train hss = 0.1272 : val hss = 0.3460
Fold 3: train tss = 0.7205 : val tss = 0.2411 ::: train hss = 0.2148 : val hss = 0.0885
Fold 4: train tss = 0.6939 : val tss = 0.6679 ::: train hss = 0.1821 : val hss = 0.2285
mean cv TSS: 0.4046
mean cv HSS: 0.1640
429/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000

Fold 1: train tss = 0.6625 : val tss = 0.3832 ::: train hss = 0.1235 : val hss = 0.1933
Fold 2: train tss = 0.6018 : val tss = 0.6130 ::: train hss = 0.1158 : val hss = 0.1983
Fold 3: train tss = 0.6811 : val tss = 0.0547 ::: train hss = 0.1799 : val hss = 0.0171
Fold 4: train tss = 0.6359 : val tss = 0.6431 ::: train hss = 0.1317 : val hss = 0.1977
mean cv TSS: 0.3388
mean cv HSS: 0.1213
430/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7428 : val tss = 0.2969 ::: train hss = 0.3364 : val hss = 0.1398
Fold 2: train tss = 0.6591 : val tss = 0.7054 ::: train hss = 0.1512 : val hss = 0.3518
Fold 3: train tss = 0.7581 : val tss = 0.1150 ::: train hss = 0.2706 : val hss = 0.0383
Fold 4: train tss = 0.7310 : val tss = 0.7174 ::: train hss = 0.2025 : val hss = 0.3036
mean cv TSS: 0.3670
mean cv HSS: 0.1667
431/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7696 : val tss = 0.2845 ::: train hss = 0.3730 : val hss = 0.1479
Fold 2: train tss = 0.6255 : val tss = 0.6715 ::: train hss = 0.1205 : val hss = 0.2592
Fold 3: train tss = 0.7162 : val tss = 0.1894 ::: train hss = 0.2331 : val hss = 0.0522
Fold 4: train tss = 0.7183 : val tss = 0.7045 ::: train hss = 0.2003 : val hss = 0.3121
mean cv TSS: 0.3700
mean cv HSS: 0.1543
432/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.0498 : val tss = -0.0002 ::: train hss = 0.0865 : val hss = -0.0005
Fold 1: train tss = 0.8004 : val tss = 0.3434 ::: train hss = 0.3788 : val hss = 0.3133
Fold 2: train tss = 0.7090 : val tss = 0.7197 ::: train hss = 0.2390 : val hss = 0.3610
Fold 3: train tss = 0.7944 : val tss = 0.0880 ::: train hss = 0.3151 : val hss = 0.0332
Fold 4: train tss = 0.7648 : val tss = 0.6108 ::: train hss = 0.2343 : val hss = 0.2252
mean cv TSS: 0.3523
mean cv HSS: 0.1865
433/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7804 : val tss = 0.4072 ::: train hss = 0.3326 : val hss = 0.1554
Fold 2: train tss = 0.6855 : val tss = 0.7358 ::: train hss = 0.1707 : val hss = 0.3941
Fold 3: train tss = 0.7118 : val tss = 0.0645 ::: train hss = 0.1979 : val hss = 0.0298
Fold 4: train tss = 0.7318 : val tss = 0.6202 ::: train hss = 0.2285 : val hss = 0.2754
mean cv TSS: 0.3655
mean cv HSS: 0.1709
434/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9921 : val tss = -0.0086 ::: train hss = 0.3744 : val hss = -0.0128
Fold 1: train tss = 0.8610 : val tss = 0.2570 ::: train hss = 0.4150 : val hss = 0.0760
Fold 2: train tss = 0.8016 : val tss = 0.7255 ::: train hss = 0.2181 : val hss = 0.3581
Fold 3: train tss = 0.7818 : val tss = 0.1849 ::: train hss = 0.2883 : val hss = 0.0448
Fold 4: train tss = 0.7749 : val tss = 0.6786 ::: train hss = 0.2840 : val hss = 0.2483
mean cv TSS: 0.3675
mean cv HSS: 0.1429
435/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.2483 : val tss = 0.0000 ::: train hss = 0.2547 : val hss = 0.0000
Fold 1: train tss = 0.7632 : val tss = 0.3528 ::: train hss = 0.3317 : val hss = 0.2324
Fold 2: train tss = 0.7339 : val tss = 0.7258 ::: train hss = 0.1744 : val hss = 0.3848
Fold 3: train tss = 0.7644 : val tss = 0.3426 ::: train hss = 0.2493 : val hss = 0.0782
Fold 4: train tss = 0.7727 : val tss = 0.6848 ::: train hss = 0.2701 : val hss = 0.3061
mean cv TSS: 0.4212
mean cv HSS: 0.2003
436/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7986 : val tss = 0.2164 ::: train hss = 0.3662 : val hss = 0.2261
Fold 2: train tss = 0.6947 : val tss = 0.6856 ::: train hss = 0.1919 : val hss = 0.3520
Fold 3: train tss = 0.6609 : val tss = 0.0342 ::: train hss = 0.1474 : val hss = 0.0094
Fold 4: train tss = 0.6841 : val tss = 0.6606 ::: train hss = 0.1705 : val hss = 0.2805
mean cv TSS: 0.3194
mean cv HSS: 0.1736
437/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7674 : val tss = 0.3488 ::: train hss = 0.2560 : val hss = 0.2041
Fold 2: train tss = 0.6560 : val tss = 0.7324 ::: train hss = 0.1393 : val hss = 0.3402
Fold 3: train tss = 0.7328 : val tss = 0.1908 ::: train hss = 0.2074 : val hss = 0.0388
Fold 4: train tss = 0.6378 : val tss = 0.6924 ::: train hss = 0.1715 : val hss = 0.2601
mean cv TSS: 0.3929
mean cv HSS: 0.1686
438/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7480 : val tss = 0.2987 ::: train hss = 0.2609 : val hss = 0.1148
Fold 2: train tss = 0.6872 : val tss = 0.6281 ::: train hss = 0.1286 : val hss = 0.2147
Fold 3: train tss = 0.6728 : val tss = 0.0477 ::: train hss = 0.1626 : val hss = 0.0107
Fold 4: train tss = 0.7239 : val tss = 0.7049 ::: train hss = 0.2238 : val hss = 0.2734
mean cv TSS: 0.3359
mean cv HSS: 0.1227
439/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7029 : val tss = 0.3108 ::: train hss = 0.1014 : val hss = 0.0879
Fold 2: train tss = 0.6601 : val tss = 0.7082 ::: train hss = 0.1004 : val hss = 0.3083
Fold 3: train tss = 0.6867 : val tss = 0.0629 ::: train hss = 0.1965 : val hss = 0.0161
Fold 4: train tss = 0.7075 : val tss = 0.7027 ::: train hss = 0.2180 : val hss = 0.2793
mean cv TSS: 0.3569
mean cv HSS: 0.1383
440/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 62796
Fold 0: train tss = 0.6907 : val tss = 0.1031 ::: train hss = 0.2489 : val hss = 0.1161
Fold 1: train tss = 0.8092 : val tss = 0.3498 ::: train hss = 0.2716 : val hss = 0.2631
Fold 2: train tss = 0.6782 : val tss = 0.6717 ::: train hss = 0.1862 : val hss = 0.4702
Fold 3: train tss = 0.7236 : val tss = 0.1377 ::: train hss = 0.2040 : val hss = 0.0234
Fold 4: train tss = 0.7058 : val tss = 0.6550 ::: train hss = 0.1847 : val hss = 0.2184
mean cv TSS: 0.3835
mean cv HSS: 0.2183
441/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7240 : val tss = 0.2985 ::: train hss = 0.3520 : val hss = 0.0735
Fold 2: train tss = 0.7093 : val tss = 0.7132 ::: train hss = 0.1947 : val hss = 0.3950
Fold 3: train tss = 0.7087 : val tss = 0.0462 ::: train hss = 0.1899 : val hss = 0.0083
Fold 4: train tss = 0.6972 : val tss = 0.6510 ::: train hss = 0.2430 : val hss = 0.2199
mean cv TSS: 0.3418
mean cv HSS: 0.1393
442/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.7951 : val tss = -0.0135 ::: train hss = 0.4130 : val hss = -0.0154
Fold 1: train tss = 0.7767 : val tss = 0.2879 ::: train hss = 0.2751 : val hss = 0.1397
Fold 2: train tss = 0.7767 : val tss = 0.7077 ::: train hss = 0.1824 : val hss = 0.3515
Fold 3: train tss = 0.7649 : val tss = 0.3393 ::: train hss = 0.2673 : val hss = 0.0754
Fold 4: train tss = 0.7640 : val tss = 0.7196 ::: train hss = 0.2616 : val hss = 0.2760
mean cv TSS: 0.4082
mean cv HSS: 0.1654
443/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7765 : val tss = 0.3328 ::: train hss = 0.3617 : val hss = 0.1692
Fold 2: train tss = 0.7492 : val tss = 0.7022 ::: train hss = 0.1970 : val hss = 0.2992
Fold 3: train tss = 0.7577 : val tss = 0.3305 ::: train hss = 0.2649 : val hss = 0.0737
Fold 4: train tss = 0.7287 : val tss = 0.7335 ::: train hss = 0.2092 : val hss = 0.3013
mean cv TSS: 0.4198
mean cv HSS: 0.1687
444/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.0499 : val tss = 0.0000 ::: train hss = 0.0907 : val hss = 0.0000
Fold 1: train tss = 0.7934 : val tss = 0.4599 ::: train hss = 0.3343 : val hss = 0.2955
Fold 2: train tss = 0.7019 : val tss = 0.6113 ::: train hss = 0.2178 : val hss = 0.2283
Fold 3: train tss = 0.7543 : val tss = 0.3199 ::: train hss = 0.2481 : val hss = 0.0828
Fold 4: train tss = 0.7015 : val tss = 0.6924 ::: train hss = 0.1896 : val hss = 0.3054
mean cv TSS: 0.4167
mean cv HSS: 0.1824
445/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6875 : val tss = 0.2675 ::: train hss = 0.1830 : val hss = 0.1772
Fold 2: train tss = 0.5955 : val tss = 0.7088 ::: train hss = 0.1464 : val hss = 0.3077
Fold 3: train tss = 0.6964 : val tss = 0.2993 ::: train hss = 0.1844 : val hss = 0.0829
Fold 4: train tss = 0.6859 : val tss = 0.6994 ::: train hss = 0.1771 : val hss = 0.2500
mean cv TSS: 0.3950
mean cv HSS: 0.1635
446/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7593 : val tss = 0.2913 ::: train hss = 0.3605 : val hss = 0.1325
Fold 2: train tss = 0.7370 : val tss = 0.7092 ::: train hss = 0.1931 : val hss = 0.3623
Fold 3: train tss = 0.7356 : val tss = 0.2635 ::: train hss = 0.2269 : val hss = 0.0671
Fold 4: train tss = 0.7624 : val tss = 0.7055 ::: train hss = 0.2440 : val hss = 0.3117
mean cv TSS: 0.3939
mean cv HSS: 0.1747
447/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7522 : val tss = 0.2863 ::: train hss = 0.2333 : val hss = 0.1170
Fold 2: train tss = 0.6519 : val tss = 0.6965 ::: train hss = 0.1426 : val hss = 0.2724
Fold 3: train tss = 0.6587 : val tss = 0.0343 ::: train hss = 0.1620 : val hss = 0.0087
Fold 4: train tss = 0.6185 : val tss = 0.5874 ::: train hss = 0.1352 : val hss = 0.1679
mean cv TSS: 0.3209
mean cv HSS: 0.1132
448/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.8902 : val tss = 0.0660 ::: train hss = 0.2992 : val hss = 0.0928
Fold 1: train tss = 0.7065 : val tss = 0.4202 ::: train hss = 0.1811 : val hss = 0.1597
Fold 2: train tss = 0.7771 : val tss = 0.6968 ::: train hss = 0.2576 : val hss = 0.3714
Fold 3: train tss = 0.8313 : val tss = 0.0104 ::: train hss = 0.3151 : val hss = 0.0058
Fold 4: train tss = 0.7667 : val tss = 0.7206 ::: train hss = 0.2169 : val hss = 0.3545
mean cv TSS: 0.3828
mean cv HSS: 0.1968
449/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7628 : val tss = 0.3776 ::: train hss = 0.4225 : val hss = 0.2951
Fold 2: train tss = 0.7803 : val tss = 0.7338 ::: train hss = 0.2393 : val hss = 0.3498
Fold 3: train tss = 0.7524 : val tss = 0.2679 ::: train hss = 0.2267 : val hss = 0.0783
Fold 4: train tss = 0.7101 : val tss = 0.6499 ::: train hss = 0.2528 : val hss = 0.2579
mean cv TSS: 0.4059
mean cv HSS: 0.1962
450/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9954 : val tss = -0.0015 ::: train hss = 0.5105 : val hss = -0.0024
Fold 1: train tss = 0.8645 : val tss = 0.2279 ::: train hss = 0.4868 : val hss = 0.1229
Fold 2: train tss = 0.8421 : val tss = 0.6945 ::: train hss = 0.2893 : val hss = 0.3292
Fold 3: train tss = 0.8292 : val tss = 0.3937 ::: train hss = 0.3470 : val hss = 0.1125
Fold 4: train tss = 0.8334 : val tss = 0.6512 ::: train hss = 0.3025 : val hss = 0.3795
mean cv TSS: 0.3932
mean cv HSS: 0.1883
451/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.9929 : val tss = -0.0009 ::: train hss = 0.4012 : val hss = -0.0017

Fold 1: train tss = 0.8645 : val tss = 0.2948 ::: train hss = 0.3783 : val hss = 0.1692
Fold 2: train tss = 0.7621 : val tss = 0.6630 ::: train hss = 0.1882 : val hss = 0.2563
Fold 3: train tss = 0.8086 : val tss = 0.3067 ::: train hss = 0.3057 : val hss = 0.0571
Fold 4: train tss = 0.7771 : val tss = 0.6834 ::: train hss = 0.2461 : val hss = 0.2784
mean cv TSS: 0.3894
mean cv HSS: 0.1519
452/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7960 : val tss = 0.2816 ::: train hss = 0.4115 : val hss = 0.2574
Fold 2: train tss = 0.7753 : val tss = 0.6970 ::: train hss = 0.2574 : val hss = 0.3224
Fold 3: train tss = 0.7565 : val tss = 0.0499 ::: train hss = 0.2524 : val hss = 0.0184
Fold 4: train tss = 0.7497 : val tss = 0.6938 ::: train hss = 0.2160 : val hss = 0.2905
mean cv TSS: 0.3445
mean cv HSS: 0.1777
453/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7817 : val tss = 0.3838 ::: train hss = 0.2963 : val hss = 0.2693
Fold 2: train tss = 0.6827 : val tss = 0.6854 ::: train hss = 0.1636 : val hss = 0.3163
Fold 3: train tss = 0.7579 : val tss = 0.2540 ::: train hss = 0.2501 : val hss = 0.0706
Fold 4: train tss = 0.7199 : val tss = 0.7229 ::: train hss = 0.1968 : val hss = 0.3584
mean cv TSS: 0.4092
mean cv HSS: 0.2029
454/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7338 : val tss = 0.2459 ::: train hss = 0.2705 : val hss = 0.0907
Fold 2: train tss = 0.7497 : val tss = 0.7127 ::: train hss = 0.2076 : val hss = 0.3495
Fold 3: train tss = 0.7458 : val tss = 0.3272 ::: train hss = 0.2585 : val hss = 0.0832
Fold 4: train tss = 0.7392 : val tss = 0.7225 ::: train hss = 0.2231 : val hss = 0.3102
mean cv TSS: 0.4017
mean cv HSS: 0.1667
455/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7367 : val tss = 0.3035 ::: train hss = 0.2030 : val hss = 0.1045
Fold 2: train tss = 0.6896 : val tss = 0.6807 ::: train hss = 0.1260 : val hss = 0.2714
Fold 3: train tss = 0.6948 : val tss = 0.2575 ::: train hss = 0.1929 : val hss = 0.0621
Fold 4: train tss = 0.7561 : val tss = 0.6591 ::: train hss = 0.2314 : val hss = 0.2163
mean cv TSS: 0.3801
mean cv HSS: 0.1308
456/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.6431 : val tss = 0.2228 ::: train hss = 0.2858 : val hss = 0.1429
Fold 1: train tss = 0.7801 : val tss = 0.3704 ::: train hss = 0.5844 : val hss = 0.1420
Fold 2: train tss = 0.7632 : val tss = 0.6753 ::: train hss = 0.2165 : val hss = 0.4967
Fold 3: train tss = 0.8057 : val tss = 0.2836 ::: train hss = 0.3027 : val hss = 0.0892
Fold 4: train tss = 0.7251 : val tss = 0.6612 ::: train hss = 0.2127 : val hss = 0.2530
mean cv TSS: 0.4427
mean cv HSS: 0.2247
457/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8067 : val tss = 0.1933 ::: train hss = 0.3940 : val hss = 0.2392
Fold 2: train tss = 0.6723 : val tss = 0.7480 ::: train hss = 0.1419 : val hss = 0.3770
Fold 3: train tss = 0.6871 : val tss = 0.3048 ::: train hss = 0.1877 : val hss = 0.0472
Fold 4: train tss = 0.6803 : val tss = 0.5317 ::: train hss = 0.1770 : val hss = 0.1420
mean cv TSS: 0.3555
mean cv HSS: 0.1611
458/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.7977 : val tss = 0.0040 ::: train hss = 0.5802 : val hss = 0.0076
Fold 1: train tss = 0.8958 : val tss = 0.2359 ::: train hss = 0.3871 : val hss = 0.1222
Fold 2: train tss = 0.8006 : val tss = 0.6746 ::: train hss = 0.2307 : val hss = 0.4172
Fold 3: train tss = 0.8039 : val tss = 0.2638 ::: train hss = 0.3247 : val hss = 0.0535
Fold 4: train tss = 0.7935 : val tss = 0.6548 ::: train hss = 0.2882 : val hss = 0.2667
mean cv TSS: 0.3666
mean cv HSS: 0.1735
459/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7863 : val tss = 0.2683 ::: train hss = 0.4022 : val hss = 0.1341
Fold 2: train tss = 0.7413 : val tss = 0.6987 ::: train hss = 0.2155 : val hss = 0.2906
Fold 3: train tss = 0.7886 : val tss = 0.2883 ::: train hss = 0.2857 : val hss = 0.0782
Fold 4: train tss = 0.7093 : val tss = 0.6208 ::: train hss = 0.2098 : val hss = 0.2214
mean cv TSS: 0.3752
mean cv HSS: 0.1449
460/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.8666 : val tss = 0.3823 ::: train hss = 0.4251 : val hss = 0.1834
Fold 2: train tss = 0.7774 : val tss = 0.7453 ::: train hss = 0.2367 : val hss = 0.4049
Fold 3: train tss = 0.8004 : val tss = 0.0712 ::: train hss = 0.3119 : val hss = 0.0315
Fold 4: train tss = 0.7378 : val tss = 0.6918 ::: train hss = 0.2193 : val hss = 0.2977
mean cv TSS: 0.3781
mean cv HSS: 0.1835
461/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6626 : val tss = 0.3218 ::: train hss = 0.0786 : val hss = 0.0837
Fold 2: train tss = 0.6257 : val tss = 0.7052 ::: train hss = 0.1788 : val hss = 0.3107
Fold 3: train tss = 0.6866 : val tss = 0.1237 ::: train hss = 0.1758 : val hss = 0.0528
Fold 4: train tss = 0.6691 : val tss = 0.6296 ::: train hss = 0.2290 : val hss = 0.2950
mean cv TSS: 0.3560
mean cv HSS: 0.1484
462/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000

Fold 1: train tss = 0.7663 : val tss = 0.3065 ::: train hss = 0.3801 : val hss = 0.1649
Fold 2: train tss = 0.7883 : val tss = 0.7343 ::: train hss = 0.2729 : val hss = 0.3774
Fold 3: train tss = 0.7497 : val tss = 0.1570 ::: train hss = 0.2477 : val hss = 0.0412
Fold 4: train tss = 0.7733 : val tss = 0.7730 ::: train hss = 0.2686 : val hss = 0.3682
mean cv TSS: 0.3942
mean cv HSS: 0.1903
463/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7721 : val tss = 0.3467 ::: train hss = 0.3913 : val hss = 0.1433
Fold 2: train tss = 0.5746 : val tss = 0.6329 ::: train hss = 0.1559 : val hss = 0.2305
Fold 3: train tss = 0.7282 : val tss = 0.3326 ::: train hss = 0.2570 : val hss = 0.0701
Fold 4: train tss = 0.7130 : val tss = 0.6719 ::: train hss = 0.2331 : val hss = 0.2396
mean cv TSS: 0.3968
mean cv HSS: 0.1367
464/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.8900 : val tss = -0.0068 ::: train hss = 0.2942 : val hss = -0.0106
Fold 1: train tss = 0.8412 : val tss = 0.1452 ::: train hss = 0.5200 : val hss = 0.0516
Fold 2: train tss = 0.7643 : val tss = 0.7448 ::: train hss = 0.2674 : val hss = 0.4518
Fold 3: train tss = 0.8060 : val tss = 0.0292 ::: train hss = 0.3004 : val hss = 0.0077
Fold 4: train tss = 0.7728 : val tss = 0.6991 ::: train hss = 0.2446 : val hss = 0.2699
mean cv TSS: 0.3223
mean cv HSS: 0.1541
465/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7885 : val tss = 0.2505 ::: train hss = 0.4628 : val hss = 0.2282
Fold 2: train tss = 0.7469 : val tss = 0.7016 ::: train hss = 0.2352 : val hss = 0.3015
Fold 3: train tss = 0.7884 : val tss = 0.0857 ::: train hss = 0.2908 : val hss = 0.0313
Fold 4: train tss = 0.7455 : val tss = 0.6988 ::: train hss = 0.2536 : val hss = 0.2710
mean cv TSS: 0.3473
mean cv HSS: 0.1664
466/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9922 : val tss = 0.0153 ::: train hss = 0.3780 : val hss = 0.0255
Fold 1: train tss = 0.8934 : val tss = 0.3155 ::: train hss = 0.4712 : val hss = 0.1301
Fold 2: train tss = 0.8531 : val tss = 0.6863 ::: train hss = 0.2423 : val hss = 0.3900
Fold 3: train tss = 0.8431 : val tss = 0.0538 ::: train hss = 0.3435 : val hss = 0.0185
Fold 4: train tss = 0.8270 : val tss = 0.7336 ::: train hss = 0.3617 : val hss = 0.2982
mean cv TSS: 0.3609
mean cv HSS: 0.1724
467/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.6954 : val tss = -0.0031 ::: train hss = 0.3863 : val hss = -0.0055
Fold 1: train tss = 0.7715 : val tss = 0.2369 ::: train hss = 0.4236 : val hss = 0.1365
Fold 2: train tss = 0.7803 : val tss = 0.7505 ::: train hss = 0.2575 : val hss = 0.3622
Fold 3: train tss = 0.7650 : val tss = 0.2087 ::: train hss = 0.3037 : val hss = 0.0531
Fold 4: train tss = 0.7778 : val tss = 0.6761 ::: train hss = 0.2734 : val hss = 0.2348
mean cv TSS: 0.3738
mean cv HSS: 0.1562
468/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.0500 : val tss = -0.0001 ::: train hss = 0.0952 : val hss = -0.0002
Fold 1: train tss = 0.8549 : val tss = 0.2871 ::: train hss = 0.3457 : val hss = 0.2005
Fold 2: train tss = 0.7194 : val tss = 0.7026 ::: train hss = 0.2231 : val hss = 0.3073
Fold 3: train tss = 0.7694 : val tss = 0.3025 ::: train hss = 0.2591 : val hss = 0.0725
Fold 4: train tss = 0.7879 : val tss = 0.6750 ::: train hss = 0.2809 : val hss = 0.3259
mean cv TSS: 0.3934
mean cv HSS: 0.1812
469/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7757 : val tss = 0.2794 ::: train hss = 0.3861 : val hss = 0.2139
Fold 2: train tss = 0.6747 : val tss = 0.7299 ::: train hss = 0.1956 : val hss = 0.4052
Fold 3: train tss = 0.7166 : val tss = 0.3065 ::: train hss = 0.2031 : val hss = 0.0609
Fold 4: train tss = 0.6468 : val tss = 0.6734 ::: train hss = 0.1839 : val hss = 0.2272
mean cv TSS: 0.3978
mean cv HSS: 0.1814
470/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.1000 : val tss = 0.0100 ::: train hss = 0.1818 : val hss = 0.0197
Fold 1: train tss = 0.7348 : val tss = 0.3324 ::: train hss = 0.2305 : val hss = 0.1230
Fold 2: train tss = 0.7157 : val tss = 0.7237 ::: train hss = 0.2162 : val hss = 0.3381
Fold 3: train tss = 0.7433 : val tss = 0.3282 ::: train hss = 0.2824 : val hss = 0.0718
Fold 4: train tss = 0.7540 : val tss = 0.7194 ::: train hss = 0.2630 : val hss = 0.3240
mean cv TSS: 0.4227
mean cv HSS: 0.1753
471/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0995 : val tss = -0.0001 ::: train hss = 0.1531 : val hss = -0.0002
Fold 1: train tss = 0.7346 : val tss = 0.3661 ::: train hss = 0.1982 : val hss = 0.1190
Fold 2: train tss = 0.7165 : val tss = 0.7417 ::: train hss = 0.1426 : val hss = 0.3621
Fold 3: train tss = 0.7018 : val tss = 0.2749 ::: train hss = 0.1820 : val hss = 0.0608
Fold 4: train tss = 0.7521 : val tss = 0.7077 ::: train hss = 0.2479 : val hss = 0.2866
mean cv TSS: 0.4180
mean cv HSS: 0.1657
472/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.8387 : val tss = 0.1365 ::: train hss = 0.2561 : val hss = 0.2177
Fold 1: train tss = 0.8477 : val tss = 0.0018 ::: train hss = 0.3531 : val hss = 0.0010
Fold 2: train tss = 0.7752 : val tss = 0.6865 ::: train hss = 0.2460 : val hss = 0.3493
Fold 3: train tss = 0.7546 : val tss = 0.1562 ::: train hss = 0.2551 : val hss = 0.0198
Fold 4: train tss = 0.7217 : val tss = 0.5811 ::: train hss = 0.1967 : val hss = 0.1748
mean cv TSS: 0.3124
mean cv HSS: 0.1525
473/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7494 : val tss = 0.3166 ::: train hss = 0.3821 : val hss = 0.1515
Fold 2: train tss = 0.6076 : val tss = 0.7538 ::: train hss = 0.1905 : val hss = 0.4194
Fold 3: train tss = 0.7793 : val tss = 0.3180 ::: train hss = 0.3102 : val hss = 0.0975
Fold 4: train tss = 0.6949 : val tss = 0.6924 ::: train hss = 0.1845 : val hss = 0.2640
mean cv TSS: 0.4162
mean cv HSS: 0.1865
474/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.8966 : val tss = 0.0043 ::: train hss = 0.5434 : val hss = 0.0069
Fold 1: train tss = 0.7714 : val tss = 0.2636 ::: train hss = 0.3297 : val hss = 0.1791
Fold 2: train tss = 0.8115 : val tss = 0.7096 ::: train hss = 0.2760 : val hss = 0.4196
Fold 3: train tss = 0.7992 : val tss = 0.2163 ::: train hss = 0.3111 : val hss = 0.0729
Fold 4: train tss = 0.8071 : val tss = 0.7481 ::: train hss = 0.3089 : val hss = 0.3649
mean cv TSS: 0.3884
mean cv HSS: 0.2087
475/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7756 : val tss = 0.1033 ::: train hss = 0.4211 : val hss = 0.0874
Fold 2: train tss = 0.7296 : val tss = 0.6686 ::: train hss = 0.2039 : val hss = 0.3232
Fold 3: train tss = 0.7319 : val tss = 0.3674 ::: train hss = 0.2570 : val hss = 0.0670
Fold 4: train tss = 0.7503 : val tss = 0.6738 ::: train hss = 0.2249 : val hss = 0.2286
mean cv TSS: 0.3626
mean cv HSS: 0.1412
476/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.1996 : val tss = -0.0009 ::: train hss = 0.2958 : val hss = -0.0017
Fold 1: train tss = 0.7360 : val tss = 0.2739 ::: train hss = 0.1766 : val hss = 0.1299
Fold 2: train tss = 0.7715 : val tss = 0.7154 ::: train hss = 0.2915 : val hss = 0.3730
Fold 3: train tss = 0.7467 : val tss = 0.0364 ::: train hss = 0.2540 : val hss = 0.0144
Fold 4: train tss = 0.7626 : val tss = 0.7084 ::: train hss = 0.2508 : val hss = 0.3388
mean cv TSS: 0.3466
mean cv HSS: 0.1709
477/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6013 : val tss = 0.2900 ::: train hss = 0.0722 : val hss = 0.0459
Fold 2: train tss = 0.6680 : val tss = 0.7497 ::: train hss = 0.1876 : val hss = 0.3476
Fold 3: train tss = 0.7601 : val tss = 0.3327 ::: train hss = 0.3159 : val hss = 0.0981
Fold 4: train tss = 0.7064 : val tss = 0.7334 ::: train hss = 0.1887 : val hss = 0.3341
mean cv TSS: 0.4212
mean cv HSS: 0.1651
478/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.2000 : val tss = 0.0000 ::: train hss = 0.3333 : val hss = 0.0000
Fold 1: train tss = 0.7835 : val tss = 0.2976 ::: train hss = 0.4556 : val hss = 0.1377
Fold 2: train tss = 0.7690 : val tss = 0.7080 ::: train hss = 0.2708 : val hss = 0.3540
Fold 3: train tss = 0.7841 : val tss = 0.2611 ::: train hss = 0.2912 : val hss = 0.0651
Fold 4: train tss = 0.7679 : val tss = 0.7714 ::: train hss = 0.2636 : val hss = 0.3771
mean cv TSS: 0.4076
mean cv HSS: 0.1868
479/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7432 : val tss = 0.3270 ::: train hss = 0.2746 : val hss = 0.1106
Fold 2: train tss = 0.7111 : val tss = 0.6752 ::: train hss = 0.1560 : val hss = 0.2691
Fold 3: train tss = 0.7339 : val tss = 0.3399 ::: train hss = 0.2510 : val hss = 0.0894
Fold 4: train tss = 0.7341 : val tss = 0.7620 ::: train hss = 0.2551 : val hss = 0.3524
mean cv TSS: 0.4208
mean cv HSS: 0.1643
480/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.2994 : val tss = -0.0022 ::: train hss = 0.3863 : val hss = -0.0041
Fold 1: train tss = 0.8351 : val tss = 0.3619 ::: train hss = 0.4988 : val hss = 0.2432
Fold 2: train tss = 0.7875 : val tss = 0.7017 ::: train hss = 0.2988 : val hss = 0.3581
Fold 3: train tss = 0.7924 : val tss = 0.0858 ::: train hss = 0.2754 : val hss = 0.0500
Fold 4: train tss = 0.7165 : val tss = 0.6931 ::: train hss = 0.1630 : val hss = 0.3100
mean cv TSS: 0.3681
mean cv HSS: 0.1914
481/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8450 : val tss = 0.3162 ::: train hss = 0.3162 : val hss = 0.3310
Fold 2: train tss = 0.5254 : val tss = 0.6049 ::: train hss = 0.2304 : val hss = 0.3691
Fold 3: train tss = 0.7801 : val tss = 0.0592 ::: train hss = 0.3136 : val hss = 0.0438
Fold 4: train tss = 0.7124 : val tss = 0.5471 ::: train hss = 0.1934 : val hss = 0.2005
mean cv TSS: 0.3055
mean cv HSS: 0.1889
482/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9942 : val tss = -0.0080 ::: train hss = 0.4519 : val hss = -0.0121
Fold 1: train tss = 0.8581 : val tss = 0.2558 ::: train hss = 0.2826 : val hss = 0.1156
Fold 2: train tss = 0.8107 : val tss = 0.6756 ::: train hss = 0.2507 : val hss = 0.4285
Fold 3: train tss = 0.8298 : val tss = 0.2447 ::: train hss = 0.3336 : val hss = 0.0748
Fold 4: train tss = 0.7767 : val tss = 0.7110 ::: train hss = 0.2520 : val hss = 0.2861
mean cv TSS: 0.3758
mean cv HSS: 0.1786
483/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8688 : val tss = 0.2187 ::: train hss = 0.3783 : val hss = 0.0934
Fold 2: train tss = 0.7928 : val tss = 0.6909 ::: train hss = 0.2518 : val hss = 0.4046
Fold 3: train tss = 0.8174 : val tss = 0.1855 ::: train hss = 0.3129 : val hss = 0.0767
Fold 4: train tss = 0.7549 : val tss = 0.7796 ::: train hss = 0.2325 : val hss = 0.4538
mean cv TSS: 0.3750
mean cv HSS: 0.2057
484/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7836 : val tss = 0.4055 ::: train hss = 0.4158 : val hss = 0.2620
Fold 2: train tss = 0.7508 : val tss = 0.7213 ::: train hss = 0.2149 : val hss = 0.4060
Fold 3: train tss = 0.8058 : val tss = 0.0172 ::: train hss = 0.3362 : val hss = 0.0053
Fold 4: train tss = 0.7308 : val tss = 0.6897 ::: train hss = 0.1991 : val hss = 0.3088
mean cv TSS: 0.3667
mean cv HSS: 0.1964
485/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7082 : val tss = 0.2761 ::: train hss = 0.1568 : val hss = 0.1151
Fold 2: train tss = 0.7374 : val tss = 0.6993 ::: train hss = 0.2034 : val hss = 0.3092
Fold 3: train tss = 0.6811 : val tss = 0.1918 ::: train hss = 0.1927 : val hss = 0.0455
Fold 4: train tss = 0.6716 : val tss = 0.6729 ::: train hss = 0.1593 : val hss = 0.2576
mean cv TSS: 0.3680
mean cv HSS: 0.1455
486/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7325 : val tss = 0.3285 ::: train hss = 0.2362 : val hss = 0.1325
Fold 2: train tss = 0.7029 : val tss = 0.7213 ::: train hss = 0.1555 : val hss = 0.3276
Fold 3: train tss = 0.7154 : val tss = 0.1227 ::: train hss = 0.1860 : val hss = 0.0213
Fold 4: train tss = 0.7634 : val tss = 0.7375 ::: train hss = 0.2604 : val hss = 0.3131
mean cv TSS: 0.3820
mean cv HSS: 0.1589
487/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7350 : val tss = 0.3522 ::: train hss = 0.1904 : val hss = 0.1321
Fold 2: train tss = 0.6808 : val tss = 0.7224 ::: train hss = 0.1260 : val hss = 0.3344
Fold 3: train tss = 0.6538 : val tss = 0.1314 ::: train hss = 0.1523 : val hss = 0.0227
Fold 4: train tss = 0.7025 : val tss = 0.6745 ::: train hss = 0.1901 : val hss = 0.2344
mean cv TSS: 0.3761
mean cv HSS: 0.1447
488/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.6936 : val tss = -0.0060 ::: train hss = 0.3189 : val hss = -0.0097
Fold 1: train tss = 0.8127 : val tss = 0.3415 ::: train hss = 0.4073 : val hss = 0.1425
Fold 2: train tss = 0.7394 : val tss = 0.7474 ::: train hss = 0.1989 : val hss = 0.3739
Fold 3: train tss = 0.7732 : val tss = 0.0117 ::: train hss = 0.2298 : val hss = 0.0056
Fold 4: train tss = 0.7251 : val tss = 0.6454 ::: train hss = 0.2085 : val hss = 0.2230
mean cv TSS: 0.3480
mean cv HSS: 0.1470
489/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7656 : val tss = 0.2962 ::: train hss = 0.4494 : val hss = 0.2428
Fold 2: train tss = 0.6825 : val tss = 0.6864 ::: train hss = 0.1670 : val hss = 0.3452
Fold 3: train tss = 0.6961 : val tss = 0.1505 ::: train hss = 0.1879 : val hss = 0.0297
Fold 4: train tss = 0.6586 : val tss = 0.5820 ::: train hss = 0.1726 : val hss = 0.1740
mean cv TSS: 0.3430
mean cv HSS: 0.1583
490/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9925 : val tss = -0.0012 ::: train hss = 0.3892 : val hss = -0.0023
Fold 1: train tss = 0.8711 : val tss = 0.1982 ::: train hss = 0.3941 : val hss = 0.0548
Fold 2: train tss = 0.7769 : val tss = 0.7148 ::: train hss = 0.2098 : val hss = 0.3490
Fold 3: train tss = 0.8131 : val tss = 0.3025 ::: train hss = 0.3570 : val hss = 0.0420
Fold 4: train tss = 0.7750 : val tss = 0.7425 ::: train hss = 0.2644 : val hss = 0.3216
mean cv TSS: 0.3914
mean cv HSS: 0.1530
491/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8082 : val tss = 0.2731 ::: train hss = 0.4432 : val hss = 0.1377
Fold 2: train tss = 0.6827 : val tss = 0.7251 ::: train hss = 0.1285 : val hss = 0.3438
Fold 3: train tss = 0.7796 : val tss = 0.3454 ::: train hss = 0.2736 : val hss = 0.0653
Fold 4: train tss = 0.7452 : val tss = 0.6787 ::: train hss = 0.2270 : val hss = 0.2634
mean cv TSS: 0.4045
mean cv HSS: 0.1620
492/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = -0.0004 ::: train hss = 0.0952 : val hss = -0.0007
Fold 1: train tss = 0.7837 : val tss = 0.4221 ::: train hss = 0.1701 : val hss = 0.1100
Fold 2: train tss = 0.7146 : val tss = 0.7057 ::: train hss = 0.1931 : val hss = 0.3855
Fold 3: train tss = 0.6852 : val tss = 0.0678 ::: train hss = 0.1878 : val hss = 0.0249
Fold 4: train tss = 0.7287 : val tss = 0.7261 ::: train hss = 0.2501 : val hss = 0.3372
mean cv TSS: 0.3843
mean cv HSS: 0.1714
493/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5987 : val tss = 0.4109 ::: train hss = 0.0697 : val hss = 0.0719
Fold 2: train tss = 0.6753 : val tss = 0.7266 ::: train hss = 0.1640 : val hss = 0.3664
Fold 3: train tss = 0.6747 : val tss = 0.2936 ::: train hss = 0.1860 : val hss = 0.0768
Fold 4: train tss = 0.7153 : val tss = 0.6030 ::: train hss = 0.2100 : val hss = 0.1839
mean cv TSS: 0.4068
mean cv HSS: 0.1398
494/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7842 : val tss = 0.3067 ::: train hss = 0.4212 : val hss = 0.1252
Fold 2: train tss = 0.7553 : val tss = 0.7352 ::: train hss = 0.1919 : val hss = 0.3929
Fold 3: train tss = 0.7578 : val tss = 0.1309 ::: train hss = 0.2591 : val hss = 0.0319
Fold 4: train tss = 0.7689 : val tss = 0.6628 ::: train hss = 0.2829 : val hss = 0.2203
mean cv TSS: 0.3671
mean cv HSS: 0.1541
495/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000

Fold 1: train tss = 0.7763 : val tss = 0.2895 ::: train hss = 0.3908 : val hss = 0.1599
Fold 2: train tss = 0.6569 : val tss = 0.6431 ::: train hss = 0.1554 : val hss = 0.2320
Fold 3: train tss = 0.7336 : val tss = 0.0539 ::: train hss = 0.2726 : val hss = 0.0167
Fold 4: train tss = 0.7336 : val tss = 0.6875 ::: train hss = 0.2263 : val hss = 0.2536
mean cv TSS: 0.3348
mean cv HSS: 0.1324
496/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.0500 : val tss = -0.0001 ::: train hss = 0.0952 : val hss = -0.0002
Fold 1: train tss = 0.8585 : val tss = 0.4376 ::: train hss = 0.3009 : val hss = 0.2423
Fold 2: train tss = 0.7905 : val tss = 0.6900 ::: train hss = 0.2740 : val hss = 0.3491
Fold 3: train tss = 0.7701 : val tss = 0.3352 ::: train hss = 0.2590 : val hss = 0.1017
Fold 4: train tss = 0.7097 : val tss = 0.6546 ::: train hss = 0.2021 : val hss = 0.2631
mean cv TSS: 0.4235
mean cv HSS: 0.1912
497/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8038 : val tss = 0.3730 ::: train hss = 0.4046 : val hss = 0.2246
Fold 2: train tss = 0.7290 : val tss = 0.7055 ::: train hss = 0.2028 : val hss = 0.3403
Fold 3: train tss = 0.7599 : val tss = 0.1267 ::: train hss = 0.2264 : val hss = 0.0391
Fold 4: train tss = 0.6723 : val tss = 0.6435 ::: train hss = 0.1810 : val hss = 0.2318
mean cv TSS: 0.3697
mean cv HSS: 0.1672
498/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9899 : val tss = -0.0063 ::: train hss = 0.3193 : val hss = -0.0087
Fold 1: train tss = 0.8036 : val tss = 0.2705 ::: train hss = 0.4859 : val hss = 0.1404
Fold 2: train tss = 0.8201 : val tss = 0.7358 ::: train hss = 0.2332 : val hss = 0.3668
Fold 3: train tss = 0.8068 : val tss = 0.2985 ::: train hss = 0.3426 : val hss = 0.0903
Fold 4: train tss = 0.7937 : val tss = 0.6622 ::: train hss = 0.2830 : val hss = 0.2769
mean cv TSS: 0.3921
mean cv HSS: 0.1731
499/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7933 : val tss = 0.4885 ::: train hss = 0.4681 : val hss = 0.1821
Fold 2: train tss = 0.7753 : val tss = 0.6369 ::: train hss = 0.2236 : val hss = 0.2402
Fold 3: train tss = 0.8040 : val tss = 0.2767 ::: train hss = 0.3133 : val hss = 0.0733
Fold 4: train tss = 0.7603 : val tss = 0.7312 ::: train hss = 0.2504 : val hss = 0.3759
mean cv TSS: 0.4267
mean cv HSS: 0.1743
500/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.0500 : val tss = -0.0006 ::: train hss = 0.0952 : val hss = -0.0012
Fold 1: train tss = 0.8156 : val tss = 0.2305 ::: train hss = 0.3660 : val hss = 0.1370
Fold 2: train tss = 0.7430 : val tss = 0.7211 ::: train hss = 0.2602 : val hss = 0.3697
Fold 3: train tss = 0.7725 : val tss = 0.0858 ::: train hss = 0.2873 : val hss = 0.0194
Fold 4: train tss = 0.7641 : val tss = 0.6797 ::: train hss = 0.2433 : val hss = 0.2855
mean cv TSS: 0.3433
mean cv HSS: 0.1621
501/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6153 : val tss = 0.3867 ::: train hss = 0.0956 : val hss = 0.1016
Fold 2: train tss = 0.6332 : val tss = 0.6850 ::: train hss = 0.1527 : val hss = 0.3060
Fold 3: train tss = 0.6767 : val tss = 0.3232 ::: train hss = 0.1746 : val hss = 0.0731
Fold 4: train tss = 0.7214 : val tss = 0.7090 ::: train hss = 0.2173 : val hss = 0.3159
mean cv TSS: 0.4208
mean cv HSS: 0.1593
502/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.0499 : val tss = -0.0001 ::: train hss = 0.0907 : val hss = -0.0002
Fold 1: train tss = 0.7595 : val tss = 0.3387 ::: train hss = 0.3111 : val hss = 0.1250
Fold 2: train tss = 0.7080 : val tss = 0.7071 ::: train hss = 0.1795 : val hss = 0.3115
Fold 3: train tss = 0.7208 : val tss = 0.0811 ::: train hss = 0.2326 : val hss = 0.0207
Fold 4: train tss = 0.7473 : val tss = 0.7287 ::: train hss = 0.2340 : val hss = 0.3049
mean cv TSS: 0.3711
mean cv HSS: 0.1524
503/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7251 : val tss = 0.3386 ::: train hss = 0.1864 : val hss = 0.1208
Fold 2: train tss = 0.6506 : val tss = 0.6558 ::: train hss = 0.1012 : val hss = 0.2376
Fold 3: train tss = 0.7170 : val tss = 0.3437 ::: train hss = 0.2060 : val hss = 0.0859
Fold 4: train tss = 0.7445 : val tss = 0.7210 ::: train hss = 0.2278 : val hss = 0.2906
mean cv TSS: 0.4118
mean cv HSS: 0.1470
504/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.7420 : val tss = 0.1671 ::: train hss = 0.2939 : val hss = 0.1786
Fold 1: train tss = 0.8161 : val tss = 0.2946 ::: train hss = 0.3195 : val hss = 0.2560
Fold 2: train tss = 0.7281 : val tss = 0.5883 ::: train hss = 0.1693 : val hss = 0.1978
Fold 3: train tss = 0.7213 : val tss = 0.1239 ::: train hss = 0.1904 : val hss = 0.0308
Fold 4: train tss = 0.7475 : val tss = 0.7246 ::: train hss = 0.2191 : val hss = 0.2938
mean cv TSS: 0.3797
mean cv HSS: 0.1914
505/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7936 : val tss = 0.3559 ::: train hss = 0.4278 : val hss = 0.1231
Fold 2: train tss = 0.6346 : val tss = 0.6559 ::: train hss = 0.1418 : val hss = 0.2292
Fold 3: train tss = 0.6530 : val tss = 0.1197 ::: train hss = 0.1437 : val hss = 0.0265
Fold 4: train tss = 0.6764 : val tss = 0.6361 ::: train hss = 0.1750 : val hss = 0.2121
mean cv TSS: 0.3535
mean cv HSS: 0.1182
506/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.8927 : val tss = 0.0000 ::: train hss = 0.3607 : val hss = 0.0000

Fold 1: train tss = 0.8603 : val tss = 0.2701 ::: train hss = 0.2912 : val hss = 0.1431
Fold 2: train tss = 0.7757 : val tss = 0.7298 ::: train hss = 0.2104 : val hss = 0.3226
Fold 3: train tss = 0.7866 : val tss = 0.2557 ::: train hss = 0.2860 : val hss = 0.0892
Fold 4: train tss = 0.7850 : val tss = 0.6918 ::: train hss = 0.2907 : val hss = 0.2496
mean cv TSS: 0.3895
mean cv HSS: 0.1609
507/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7754 : val tss = 0.2822 ::: train hss = 0.4625 : val hss = 0.1634
Fold 2: train tss = 0.7444 : val tss = 0.6351 ::: train hss = 0.1738 : val hss = 0.2375
Fold 3: train tss = 0.7585 : val tss = 0.3310 ::: train hss = 0.2874 : val hss = 0.0538
Fold 4: train tss = 0.7047 : val tss = 0.6344 ::: train hss = 0.2400 : val hss = 0.1973
mean cv TSS: 0.3765
mean cv HSS: 0.1304
508/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.0999 : val tss = -0.0004 ::: train hss = 0.1737 : val hss = -0.0007
Fold 1: train tss = 0.8262 : val tss = 0.2888 ::: train hss = 0.4503 : val hss = 0.1715
Fold 2: train tss = 0.7721 : val tss = 0.7400 ::: train hss = 0.2575 : val hss = 0.3479
Fold 3: train tss = 0.7768 : val tss = 0.0395 ::: train hss = 0.2776 : val hss = 0.0227
Fold 4: train tss = 0.6935 : val tss = 0.6093 ::: train hss = 0.1912 : val hss = 0.1980
mean cv TSS: 0.3355
mean cv HSS: 0.1479
509/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7717 : val tss = 0.1760 ::: train hss = 0.4692 : val hss = 0.2173
Fold 2: train tss = 0.6213 : val tss = 0.6881 ::: train hss = 0.1362 : val hss = 0.2920
Fold 3: train tss = 0.6832 : val tss = 0.1589 ::: train hss = 0.1956 : val hss = 0.0360
Fold 4: train tss = 0.6529 : val tss = 0.6899 ::: train hss = 0.1880 : val hss = 0.2466
mean cv TSS: 0.3426
mean cv HSS: 0.1584
510/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.1000 : val tss = -0.0002 ::: train hss = 0.1818 : val hss = -0.0005
Fold 1: train tss = 0.7648 : val tss = 0.3045 ::: train hss = 0.4419 : val hss = 0.1409
Fold 2: train tss = 0.7349 : val tss = 0.7336 ::: train hss = 0.2279 : val hss = 0.3456
Fold 3: train tss = 0.7588 : val tss = 0.3555 ::: train hss = 0.2797 : val hss = 0.0998
Fold 4: train tss = 0.7463 : val tss = 0.7108 ::: train hss = 0.2438 : val hss = 0.2903
mean cv TSS: 0.4208
mean cv HSS: 0.1752
511/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7672 : val tss = 0.2605 ::: train hss = 0.3871 : val hss = 0.1265
Fold 2: train tss = 0.6963 : val tss = 0.7284 ::: train hss = 0.1407 : val hss = 0.3432
Fold 3: train tss = 0.7401 : val tss = 0.2607 ::: train hss = 0.2598 : val hss = 0.0864
Fold 4: train tss = 0.7480 : val tss = 0.7615 ::: train hss = 0.2444 : val hss = 0.3888
mean cv TSS: 0.4022
mean cv HSS: 0.1890
512/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.8906 : val tss = 0.1505 ::: train hss = 0.3071 : val hss = 0.1754
Fold 1: train tss = 0.8635 : val tss = 0.1138 ::: train hss = 0.4357 : val hss = 0.0569
Fold 2: train tss = 0.8100 : val tss = 0.7368 ::: train hss = 0.2896 : val hss = 0.3936
Fold 3: train tss = 0.7672 : val tss = 0.3390 ::: train hss = 0.2438 : val hss = 0.0813
Fold 4: train tss = 0.7583 : val tss = 0.7177 ::: train hss = 0.2458 : val hss = 0.3029
mean cv TSS: 0.4116
mean cv HSS: 0.2020
513/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.8448 : val tss = 0.0000 ::: train hss = 0.4224 : val hss = 0.0000
Fold 1: train tss = 0.8449 : val tss = 0.2653 ::: train hss = 0.3622 : val hss = 0.1831
Fold 2: train tss = 0.7441 : val tss = 0.6922 ::: train hss = 0.1791 : val hss = 0.3000
Fold 3: train tss = 0.7998 : val tss = 0.0230 ::: train hss = 0.3257 : val hss = 0.0137
Fold 4: train tss = 0.7091 : val tss = 0.6998 ::: train hss = 0.1876 : val hss = 0.2749
mean cv TSS: 0.3360
mean cv HSS: 0.1543
514/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9959 : val tss = -0.0049 ::: train hss = 0.5383 : val hss = -0.0082
Fold 1: train tss = 0.8773 : val tss = 0.3181 ::: train hss = 0.4841 : val hss = 0.1282
Fold 2: train tss = 0.8353 : val tss = 0.6790 ::: train hss = 0.2941 : val hss = 0.3619
Fold 3: train tss = 0.8495 : val tss = 0.2754 ::: train hss = 0.3204 : val hss = 0.1887
Fold 4: train tss = 0.8496 : val tss = 0.6756 ::: train hss = 0.3184 : val hss = 0.4512
mean cv TSS: 0.3886
mean cv HSS: 0.2243
515/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9424 : val tss = -0.0036 ::: train hss = 0.3696 : val hss = -0.0062
Fold 1: train tss = 0.7995 : val tss = 0.3203 ::: train hss = 0.4428 : val hss = 0.1470
Fold 2: train tss = 0.7353 : val tss = 0.6520 ::: train hss = 0.1743 : val hss = 0.3079
Fold 3: train tss = 0.7798 : val tss = 0.2834 ::: train hss = 0.3563 : val hss = 0.0994
Fold 4: train tss = 0.7984 : val tss = 0.7256 ::: train hss = 0.2776 : val hss = 0.2962
mean cv TSS: 0.3956
mean cv HSS: 0.1688
516/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.8331 : val tss = 0.3508 ::: train hss = 0.5275 : val hss = 0.2493
Fold 2: train tss = 0.5813 : val tss = 0.5864 ::: train hss = 0.1015 : val hss = 0.2110
Fold 3: train tss = 0.8315 : val tss = -0.0022 ::: train hss = 0.3429 : val hss = -0.0010
Fold 4: train tss = 0.7821 : val tss = 0.7000 ::: train hss = 0.2887 : val hss = 0.2967
mean cv TSS: 0.3270
mean cv HSS: 0.1512
517/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 109820
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7799 : val tss = 0.3564 ::: train hss = 0.4209 : val hss = 0.1991
Fold 2: train tss = 0.5067 : val tss = 0.5603 ::: train hss = 0.0762 : val hss = 0.1858
Fold 3: train tss = 0.7634 : val tss = 0.0798 ::: train hss = 0.2659 : val hss = 0.0271
Fold 4: train tss = 0.7336 : val tss = 0.6716 ::: train hss = 0.2253 : val hss = 0.2428
mean cv TSS: 0.3336
mean cv HSS: 0.1310
518/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.0499 : val tss = -0.0001 ::: train hss = 0.0907 : val hss = -0.0002
Fold 1: train tss = 0.7795 : val tss = 0.3049 ::: train hss = 0.4600 : val hss = 0.1168
Fold 2: train tss = 0.7482 : val tss = 0.7340 ::: train hss = 0.2027 : val hss = 0.3598
Fold 3: train tss = 0.7681 : val tss = 0.3718 ::: train hss = 0.2948 : val hss = 0.1128
Fold 4: train tss = 0.7399 : val tss = 0.7027 ::: train hss = 0.2307 : val hss = 0.2710
mean cv TSS: 0.4227
mean cv HSS: 0.1720
519/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7649 : val tss = 0.2940 ::: train hss = 0.3415 : val hss = 0.1230
Fold 2: train tss = 0.7047 : val tss = 0.7244 ::: train hss = 0.1307 : val hss = 0.3235
Fold 3: train tss = 0.7028 : val tss = 0.2281 ::: train hss = 0.2078 : val hss = 0.0588
Fold 4: train tss = 0.7329 : val tss = 0.6630 ::: train hss = 0.2145 : val hss = 0.2224
mean cv TSS: 0.3819
mean cv HSS: 0.1455
520/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.8882 : val tss = 0.0981 ::: train hss = 0.2612 : val hss = 0.1439
Fold 1: train tss = 0.8025 : val tss = 0.1300 ::: train hss = 0.3375 : val hss = 0.1490
Fold 2: train tss = 0.7470 : val tss = 0.6726 ::: train hss = 0.1788 : val hss = 0.3619
Fold 3: train tss = 0.7862 : val tss = 0.2355 ::: train hss = 0.2559 : val hss = 0.1044
Fold 4: train tss = 0.7594 : val tss = 0.5388 ::: train hss = 0.2331 : val hss = 0.2663
mean cv TSS: 0.3350
mean cv HSS: 0.2051
521/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7185 : val tss = 0.3988 ::: train hss = 0.1812 : val hss = 0.1752
Fold 2: train tss = 0.4631 : val tss = 0.4537 ::: train hss = 0.1722 : val hss = 0.3554
Fold 3: train tss = 0.7496 : val tss = 0.3796 ::: train hss = 0.2634 : val hss = 0.0755
Fold 4: train tss = 0.6640 : val tss = 0.6684 ::: train hss = 0.1633 : val hss = 0.2181
mean cv TSS: 0.3801
mean cv HSS: 0.1648
522/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9828 : val tss = -0.0028 ::: train hss = 0.2148 : val hss = -0.0051
Fold 1: train tss = 0.8171 : val tss = 0.3080 ::: train hss = 0.4081 : val hss = 0.1457
Fold 2: train tss = 0.8290 : val tss = 0.6894 ::: train hss = 0.2438 : val hss = 0.2759
Fold 3: train tss = 0.8349 : val tss = 0.3117 ::: train hss = 0.3403 : val hss = 0.1454
Fold 4: train tss = 0.7790 : val tss = 0.7516 ::: train hss = 0.2654 : val hss = 0.3346
mean cv TSS: 0.4116
mean cv HSS: 0.1793
523/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.8947 : val tss = 0.0000 ::: train hss = 0.4364 : val hss = 0.0000
Fold 1: train tss = 0.7578 : val tss = 0.2920 ::: train hss = 0.3503 : val hss = 0.1231
Fold 2: train tss = 0.7589 : val tss = 0.5729 ::: train hss = 0.2150 : val hss = 0.2031
Fold 3: train tss = 0.7625 : val tss = 0.4035 ::: train hss = 0.3064 : val hss = 0.0691
Fold 4: train tss = 0.7507 : val tss = 0.7290 ::: train hss = 0.2210 : val hss = 0.3121
mean cv TSS: 0.3995
mean cv HSS: 0.1415
524/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.0999 : val tss = 0.0000 ::: train hss = 0.1737 : val hss = 0.0000
Fold 1: train tss = 0.6930 : val tss = 0.3585 ::: train hss = 0.0972 : val hss = 0.0877
Fold 2: train tss = 0.7757 : val tss = 0.6520 ::: train hss = 0.2750 : val hss = 0.4354
Fold 3: train tss = 0.8090 : val tss = 0.0426 ::: train hss = 0.3174 : val hss = 0.0117
Fold 4: train tss = 0.7532 : val tss = 0.4646 ::: train hss = 0.2602 : val hss = 0.2623
mean cv TSS: 0.3035
mean cv HSS: 0.1594
525/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7921 : val tss = 0.1801 ::: train hss = 0.3810 : val hss = 0.2385
Fold 2: train tss = 0.5869 : val tss = 0.6771 ::: train hss = 0.1084 : val hss = 0.2777
Fold 3: train tss = 0.6828 : val tss = 0.0965 ::: train hss = 0.1730 : val hss = 0.0414
Fold 4: train tss = 0.6642 : val tss = 0.6660 ::: train hss = 0.1384 : val hss = 0.2409
mean cv TSS: 0.3239
mean cv HSS: 0.1597
526/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7849 : val tss = 0.3552 ::: train hss = 0.4707 : val hss = 0.1481
Fold 2: train tss = 0.8125 : val tss = 0.7484 ::: train hss = 0.2920 : val hss = 0.3733
Fold 3: train tss = 0.7630 : val tss = 0.2152 ::: train hss = 0.2665 : val hss = 0.0535
Fold 4: train tss = 0.7703 : val tss = 0.6466 ::: train hss = 0.2644 : val hss = 0.2099
mean cv TSS: 0.3931
mean cv HSS: 0.1569
527/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7703 : val tss = 0.2984 ::: train hss = 0.3488 : val hss = 0.1359
Fold 2: train tss = 0.7452 : val tss = 0.7248 ::: train hss = 0.2032 : val hss = 0.3610
Fold 3: train tss = 0.7916 : val tss = 0.3263 ::: train hss = 0.2791 : val hss = 0.0758
Fold 4: train tss = 0.7422 : val tss = 0.7268 ::: train hss = 0.2237 : val hss = 0.3290
mean cv TSS: 0.4152
mean cv HSS: 0.1803
528/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 145916
Fold 0: train tss = 0.8896 : val tss = 0.0678 ::: train hss = 0.2870 : val hss = 0.1185
Fold 1: train tss = 0.8423 : val tss = 0.2454 ::: train hss = 0.4390 : val hss = 0.1005
Fold 2: train tss = 0.7908 : val tss = 0.6416 ::: train hss = 0.3530 : val hss = 0.4259
Fold 3: train tss = 0.7297 : val tss = 0.0235 ::: train hss = 0.1974 : val hss = 0.0101
Fold 4: train tss = 0.7504 : val tss = 0.7046 ::: train hss = 0.2268 : val hss = 0.2720
mean cv TSS: 0.3366
mean cv HSS: 0.1854
529/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8178 : val tss = 0.3371 ::: train hss = 0.4524 : val hss = 0.2655
Fold 2: train tss = 0.7240 : val tss = 0.7215 ::: train hss = 0.2134 : val hss = 0.4703
Fold 3: train tss = 0.7618 : val tss = 0.1331 ::: train hss = 0.3081 : val hss = 0.0443
Fold 4: train tss = 0.7426 : val tss = 0.6381 ::: train hss = 0.2452 : val hss = 0.2502
mean cv TSS: 0.3660
mean cv HSS: 0.2061
530/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9959 : val tss = -0.0102 ::: train hss = 0.5383 : val hss = -0.0145
Fold 1: train tss = 0.8918 : val tss = 0.2754 ::: train hss = 0.4562 : val hss = 0.1101
Fold 2: train tss = 0.8451 : val tss = 0.6580 ::: train hss = 0.2974 : val hss = 0.3491
Fold 3: train tss = 0.8427 : val tss = 0.2706 ::: train hss = 0.3979 : val hss = 0.0540
Fold 4: train tss = 0.7753 : val tss = 0.7200 ::: train hss = 0.2198 : val hss = 0.2893
mean cv TSS: 0.3827
mean cv HSS: 0.1576
531/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9931 : val tss = -0.0021 ::: train hss = 0.4095 : val hss = -0.0039
Fold 1: train tss = 0.8437 : val tss = 0.3621 ::: train hss = 0.4144 : val hss = 0.1481
Fold 2: train tss = 0.8224 : val tss = 0.6445 ::: train hss = 0.2822 : val hss = 0.2361
Fold 3: train tss = 0.8051 : val tss = 0.2963 ::: train hss = 0.3258 : val hss = 0.1093
Fold 4: train tss = 0.7748 : val tss = 0.7007 ::: train hss = 0.2615 : val hss = 0.2888
mean cv TSS: 0.4003
mean cv HSS: 0.1557
532/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7787 : val tss = 0.2725 ::: train hss = 0.3770 : val hss = 0.1338
Fold 2: train tss = 0.7938 : val tss = 0.7252 ::: train hss = 0.3024 : val hss = 0.4560
Fold 3: train tss = 0.8231 : val tss = 0.2607 ::: train hss = 0.3588 : val hss = 0.0865
Fold 4: train tss = 0.7288 : val tss = 0.6961 ::: train hss = 0.2457 : val hss = 0.2667
mean cv TSS: 0.3909
mean cv HSS: 0.1886
533/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7912 : val tss = 0.2518 ::: train hss = 0.3220 : val hss = 0.2668
Fold 2: train tss = 0.7681 : val tss = 0.7109 ::: train hss = 0.2379 : val hss = 0.3809
Fold 3: train tss = 0.7633 : val tss = 0.3155 ::: train hss = 0.2445 : val hss = 0.0723
Fold 4: train tss = 0.7097 : val tss = 0.6387 ::: train hss = 0.2087 : val hss = 0.2306
mean cv TSS: 0.3834
mean cv HSS: 0.1901
534/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7695 : val tss = 0.2611 ::: train hss = 0.3721 : val hss = 0.1168
Fold 2: train tss = 0.7707 : val tss = 0.7183 ::: train hss = 0.2471 : val hss = 0.3899
Fold 3: train tss = 0.7549 : val tss = 0.2666 ::: train hss = 0.2604 : val hss = 0.0768
Fold 4: train tss = 0.7364 : val tss = 0.6335 ::: train hss = 0.1999 : val hss = 0.2006
mean cv TSS: 0.3759
mean cv HSS: 0.1568
535/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7262 : val tss = 0.3358 ::: train hss = 0.2176 : val hss = 0.1183
Fold 2: train tss = 0.7083 : val tss = 0.7051 ::: train hss = 0.1488 : val hss = 0.3043
Fold 3: train tss = 0.7327 : val tss = 0.3047 ::: train hss = 0.2406 : val hss = 0.0812
Fold 4: train tss = 0.7357 : val tss = 0.7173 ::: train hss = 0.2485 : val hss = 0.2938
mean cv TSS: 0.4126
mean cv HSS: 0.1595
536/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.9377 : val tss = 0.2086 ::: train hss = 0.2660 : val hss = 0.1564
Fold 1: train tss = 0.6571 : val tss = 0.3123 ::: train hss = 0.0761 : val hss = 0.0684
Fold 2: train tss = 0.6885 : val tss = 0.7244 ::: train hss = 0.1786 : val hss = 0.3779
Fold 3: train tss = 0.7432 : val tss = 0.3100 ::: train hss = 0.2531 : val hss = 0.0524
Fold 4: train tss = 0.7409 : val tss = 0.4732 ::: train hss = 0.2273 : val hss = 0.2232
mean cv TSS: 0.4057
mean cv HSS: 0.1757
537/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7938 : val tss = 0.1604 ::: train hss = 0.3628 : val hss = 0.2301
Fold 2: train tss = 0.3855 : val tss = 0.4261 ::: train hss = 0.1466 : val hss = 0.2622
Fold 3: train tss = 0.7487 : val tss = 0.0999 ::: train hss = 0.3007 : val hss = 0.0393
Fold 4: train tss = 0.6740 : val tss = 0.6575 ::: train hss = 0.1828 : val hss = 0.2516
mean cv TSS: 0.2688
mean cv HSS: 0.1566
538/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9923 : val tss = -0.0004 ::: train hss = 0.3817 : val hss = -0.0007
Fold 1: train tss = 0.7940 : val tss = 0.3707 ::: train hss = 0.3381 : val hss = 0.1590
Fold 2: train tss = 0.8091 : val tss = 0.7161 ::: train hss = 0.2582 : val hss = 0.3415
Fold 3: train tss = 0.7662 : val tss = 0.3212 ::: train hss = 0.2839 : val hss = 0.0549
Fold 4: train tss = 0.7651 : val tss = 0.7188 ::: train hss = 0.2451 : val hss = 0.3562
mean cv TSS: 0.4253
mean cv HSS: 0.1822
539/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.5975 : val tss = -0.0005 ::: train hss = 0.4509 : val hss = -0.0010

Fold 1: train tss = 0.7750 : val tss = 0.2215 ::: train hss = 0.3262 : val hss = 0.2368
Fold 2: train tss = 0.7211 : val tss = 0.7332 ::: train hss = 0.1865 : val hss = 0.4038
Fold 3: train tss = 0.7709 : val tss = 0.2765 ::: train hss = 0.2974 : val hss = 0.0890
Fold 4: train tss = 0.7534 : val tss = 0.6985 ::: train hss = 0.2489 : val hss = 0.2587
mean cv TSS: 0.3858
mean cv HSS: 0.1975
540/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7499 : val tss = 0.2972 ::: train hss = 0.4675 : val hss = 0.1740
Fold 2: train tss = 0.6878 : val tss = 0.6116 ::: train hss = 0.1410 : val hss = 0.2057
Fold 3: train tss = 0.7611 : val tss = 0.3176 ::: train hss = 0.2474 : val hss = 0.1405
Fold 4: train tss = 0.7766 : val tss = 0.6862 ::: train hss = 0.2551 : val hss = 0.2708
mean cv TSS: 0.3825
mean cv HSS: 0.1582
541/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7243 : val tss = 0.2472 ::: train hss = 0.2237 : val hss = 0.1805
Fold 2: train tss = 0.7196 : val tss = 0.7651 ::: train hss = 0.2059 : val hss = 0.3937
Fold 3: train tss = 0.7076 : val tss = 0.3008 ::: train hss = 0.2085 : val hss = 0.0845
Fold 4: train tss = 0.6704 : val tss = 0.7302 ::: train hss = 0.1663 : val hss = 0.3501
mean cv TSS: 0.4086
mean cv HSS: 0.2018
542/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7699 : val tss = 0.3260 ::: train hss = 0.3752 : val hss = 0.1320
Fold 2: train tss = 0.8341 : val tss = 0.7468 ::: train hss = 0.3392 : val hss = 0.4078
Fold 3: train tss = 0.7758 : val tss = 0.2832 ::: train hss = 0.2840 : val hss = 0.0801
Fold 4: train tss = 0.8246 : val tss = 0.6852 ::: train hss = 0.3330 : val hss = 0.3686
mean cv TSS: 0.4082
mean cv HSS: 0.1977
543/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7744 : val tss = 0.3042 ::: train hss = 0.3765 : val hss = 0.1376
Fold 2: train tss = 0.7665 : val tss = 0.6966 ::: train hss = 0.2011 : val hss = 0.2701
Fold 3: train tss = 0.7630 : val tss = 0.2755 ::: train hss = 0.2629 : val hss = 0.0876
Fold 4: train tss = 0.7556 : val tss = 0.7678 ::: train hss = 0.2573 : val hss = 0.4091
mean cv TSS: 0.4088
mean cv HSS: 0.1809
544/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.8888 : val tss = -0.0023 ::: train hss = 0.2714 : val hss = -0.0043
Fold 1: train tss = 0.8407 : val tss = 0.1929 ::: train hss = 0.3160 : val hss = 0.0903
Fold 2: train tss = 0.6990 : val tss = 0.6997 ::: train hss = 0.2353 : val hss = 0.3245
Fold 3: train tss = 0.7847 : val tss = 0.0770 ::: train hss = 0.2638 : val hss = 0.0284
Fold 4: train tss = 0.7726 : val tss = 0.6105 ::: train hss = 0.2453 : val hss = 0.1989
mean cv TSS: 0.3155
mean cv HSS: 0.1276
545/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8585 : val tss = 0.2083 ::: train hss = 0.3666 : val hss = 0.2360
Fold 2: train tss = 0.6562 : val tss = 0.6283 ::: train hss = 0.1381 : val hss = 0.2811
Fold 3: train tss = 0.7438 : val tss = 0.2053 ::: train hss = 0.2360 : val hss = 0.0676
Fold 4: train tss = 0.7472 : val tss = 0.6895 ::: train hss = 0.2357 : val hss = 0.2898
mean cv TSS: 0.3463
mean cv HSS: 0.1749
546/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9935 : val tss = 0.0124 ::: train hss = 0.4228 : val hss = 0.0187
Fold 1: train tss = 0.8727 : val tss = 0.3362 ::: train hss = 0.4403 : val hss = 0.1247
Fold 2: train tss = 0.8291 : val tss = 0.6977 ::: train hss = 0.2377 : val hss = 0.3513
Fold 3: train tss = 0.8468 : val tss = 0.2518 ::: train hss = 0.3604 : val hss = 0.1262
Fold 4: train tss = 0.7943 : val tss = 0.7045 ::: train hss = 0.2749 : val hss = 0.2730
mean cv TSS: 0.4005
mean cv HSS: 0.1788
547/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.4970 : val tss = -0.0010 ::: train hss = 0.3614 : val hss = -0.0019
Fold 1: train tss = 0.8215 : val tss = 0.2207 ::: train hss = 0.3771 : val hss = 0.0868
Fold 2: train tss = 0.7869 : val tss = 0.6892 ::: train hss = 0.2181 : val hss = 0.4092
Fold 3: train tss = 0.8018 : val tss = 0.2849 ::: train hss = 0.3118 : val hss = 0.0909
Fold 4: train tss = 0.7951 : val tss = 0.7706 ::: train hss = 0.2726 : val hss = 0.3709
mean cv TSS: 0.3929
mean cv HSS: 0.1912
548/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7621 : val tss = 0.2315 ::: train hss = 0.3032 : val hss = 0.1067
Fold 2: train tss = 0.7855 : val tss = 0.7282 ::: train hss = 0.2926 : val hss = 0.4503
Fold 3: train tss = 0.8120 : val tss = 0.2286 ::: train hss = 0.3110 : val hss = 0.0591
Fold 4: train tss = 0.7723 : val tss = 0.6825 ::: train hss = 0.2437 : val hss = 0.2766
mean cv TSS: 0.3742
mean cv HSS: 0.1786
549/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.6476 : val tss = 0.3983 ::: train hss = 0.0910 : val hss = 0.1342
Fold 2: train tss = 0.6977 : val tss = 0.7243 ::: train hss = 0.1782 : val hss = 0.3800
Fold 3: train tss = 0.7007 : val tss = 0.3257 ::: train hss = 0.1803 : val hss = 0.0651
Fold 4: train tss = 0.7004 : val tss = 0.6882 ::: train hss = 0.1898 : val hss = 0.2621
mean cv TSS: 0.4273
mean cv HSS: 0.1683
550/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000

Fold 1: train tss = 0.7525 : val tss = 0.3509 ::: train hss = 0.3729 : val hss = 0.1377
Fold 2: train tss = 0.6919 : val tss = 0.7214 ::: train hss = 0.1710 : val hss = 0.3146
Fold 3: train tss = 0.7382 : val tss = 0.2905 ::: train hss = 0.2532 : val hss = 0.0806
Fold 4: train tss = 0.7659 : val tss = 0.7294 ::: train hss = 0.2663 : val hss = 0.3144
mean cv TSS: 0.4184
mean cv HSS: 0.1695
551/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7450 : val tss = 0.2745 ::: train hss = 0.2502 : val hss = 0.0969
Fold 2: train tss = 0.6975 : val tss = 0.7102 ::: train hss = 0.1417 : val hss = 0.2905
Fold 3: train tss = 0.6626 : val tss = 0.2874 ::: train hss = 0.1575 : val hss = 0.0473
Fold 4: train tss = 0.7534 : val tss = 0.7055 ::: train hss = 0.2284 : val hss = 0.2871
mean cv TSS: 0.3955
mean cv HSS: 0.1443
552/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.5889 : val tss = 0.0849 ::: train hss = 0.1900 : val hss = 0.0735
Fold 1: train tss = 0.8350 : val tss = 0.1807 ::: train hss = 0.3809 : val hss = 0.1263
Fold 2: train tss = 0.7686 : val tss = 0.6316 ::: train hss = 0.1782 : val hss = 0.2525
Fold 3: train tss = 0.7760 : val tss = 0.0427 ::: train hss = 0.2156 : val hss = 0.0333
Fold 4: train tss = 0.6755 : val tss = 0.6769 ::: train hss = 0.2051 : val hss = 0.2541
mean cv TSS: 0.3234
mean cv HSS: 0.1480
553/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7543 : val tss = 0.2022 ::: train hss = 0.2864 : val hss = 0.1765
Fold 2: train tss = 0.6449 : val tss = 0.7007 ::: train hss = 0.1310 : val hss = 0.4322
Fold 3: train tss = 0.6971 : val tss = 0.0097 ::: train hss = 0.1960 : val hss = 0.0039
Fold 4: train tss = 0.6770 : val tss = 0.6556 ::: train hss = 0.1690 : val hss = 0.2854
mean cv TSS: 0.3136
mean cv HSS: 0.1796
554/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9952 : val tss = -0.0002 ::: train hss = 0.4976 : val hss = -0.0005
Fold 1: train tss = 0.7804 : val tss = 0.2772 ::: train hss = 0.3898 : val hss = 0.1258
Fold 2: train tss = 0.7796 : val tss = 0.6612 ::: train hss = 0.2224 : val hss = 0.2544
Fold 3: train tss = 0.8156 : val tss = 0.2956 ::: train hss = 0.3272 : val hss = 0.0483
Fold 4: train tss = 0.8096 : val tss = 0.7688 ::: train hss = 0.3131 : val hss = 0.3547
mean cv TSS: 0.4005
mean cv HSS: 0.1565
555/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.3981 : val tss = 0.0000 ::: train hss = 0.3619 : val hss = 0.0000
Fold 1: train tss = 0.7594 : val tss = 0.2154 ::: train hss = 0.3609 : val hss = 0.2450
Fold 2: train tss = 0.7473 : val tss = 0.6809 ::: train hss = 0.1876 : val hss = 0.2632
Fold 3: train tss = 0.7674 : val tss = 0.3090 ::: train hss = 0.2833 : val hss = 0.0671
Fold 4: train tss = 0.7443 : val tss = 0.6968 ::: train hss = 0.2639 : val hss = 0.2659
mean cv TSS: 0.3804
mean cv HSS: 0.1682
556/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.0998 : val tss = 0.0000 ::: train hss = 0.1663 : val hss = 0.0000
Fold 1: train tss = 0.8591 : val tss = 0.2735 ::: train hss = 0.4759 : val hss = 0.1416
Fold 2: train tss = 0.8036 : val tss = 0.6969 ::: train hss = 0.3007 : val hss = 0.3670
Fold 3: train tss = 0.7241 : val tss = 0.0969 ::: train hss = 0.2424 : val hss = 0.0291
Fold 4: train tss = 0.7138 : val tss = 0.5840 ::: train hss = 0.2072 : val hss = 0.2286
mean cv TSS: 0.3302
mean cv HSS: 0.1533
557/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6222 : val tss = 0.3331 ::: train hss = 0.0741 : val hss = 0.0901
Fold 2: train tss = 0.5958 : val tss = 0.6498 ::: train hss = 0.1176 : val hss = 0.2954
Fold 3: train tss = 0.7393 : val tss = 0.2920 ::: train hss = 0.2735 : val hss = 0.1018
Fold 4: train tss = 0.6826 : val tss = 0.6964 ::: train hss = 0.1933 : val hss = 0.2644
mean cv TSS: 0.3943
mean cv HSS: 0.1503
558/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.0500 : val tss = -0.0001 ::: train hss = 0.0952 : val hss = -0.0002
Fold 1: train tss = 0.7786 : val tss = 0.3028 ::: train hss = 0.4102 : val hss = 0.1417
Fold 2: train tss = 0.7686 : val tss = 0.7188 ::: train hss = 0.2095 : val hss = 0.3225
Fold 3: train tss = 0.7512 : val tss = 0.3121 ::: train hss = 0.2849 : val hss = 0.0818
Fold 4: train tss = 0.7852 : val tss = 0.7221 ::: train hss = 0.2644 : val hss = 0.3421
mean cv TSS: 0.4112
mean cv HSS: 0.1776
559/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7639 : val tss = 0.2690 ::: train hss = 0.3631 : val hss = 0.1264
Fold 2: train tss = 0.7072 : val tss = 0.6620 ::: train hss = 0.1522 : val hss = 0.2486
Fold 3: train tss = 0.7556 : val tss = 0.2682 ::: train hss = 0.2806 : val hss = 0.0785
Fold 4: train tss = 0.7339 : val tss = 0.6964 ::: train hss = 0.2060 : val hss = 0.2667
mean cv TSS: 0.3791
mean cv HSS: 0.1440
560/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8412 : val tss = 0.1821 ::: train hss = 0.3059 : val hss = 0.1937
Fold 1: train tss = 0.7668 : val tss = 0.3634 ::: train hss = 0.1683 : val hss = 0.1222
Fold 2: train tss = 0.7992 : val tss = 0.7136 ::: train hss = 0.3197 : val hss = 0.3511
Fold 3: train tss = 0.8155 : val tss = 0.2152 ::: train hss = 0.3073 : val hss = 0.1079
Fold 4: train tss = 0.7442 : val tss = 0.6943 ::: train hss = 0.2492 : val hss = 0.2802
mean cv TSS: 0.4337
mean cv HSS: 0.2110
561/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8119 : val tss = 0.1273 ::: train hss = 0.2821 : val hss = 0.0538
Fold 2: train tss = 0.7442 : val tss = 0.6529 ::: train hss = 0.2266 : val hss = 0.2918
Fold 3: train tss = 0.7823 : val tss = 0.2955 ::: train hss = 0.2769 : val hss = 0.0866
Fold 4: train tss = 0.7300 : val tss = 0.6095 ::: train hss = 0.2336 : val hss = 0.2070
mean cv TSS: 0.3371
mean cv HSS: 0.1278
562/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9947 : val tss = -0.0023 ::: train hss = 0.4737 : val hss = -0.0043
Fold 1: train tss = 0.8606 : val tss = 0.3063 ::: train hss = 0.3308 : val hss = 0.0756
Fold 2: train tss = 0.8363 : val tss = 0.5753 ::: train hss = 0.3018 : val hss = 0.4273
Fold 3: train tss = 0.8390 : val tss = 0.2322 ::: train hss = 0.3522 : val hss = 0.1135
Fold 4: train tss = 0.7735 : val tss = 0.6933 ::: train hss = 0.2491 : val hss = 0.3020
mean cv TSS: 0.3610
mean cv HSS: 0.1828
563/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9931 : val tss = -0.0015 ::: train hss = 0.4095 : val hss = -0.0028
Fold 1: train tss = 0.8476 : val tss = 0.2873 ::: train hss = 0.4108 : val hss = 0.1026
Fold 2: train tss = 0.7790 : val tss = 0.6886 ::: train hss = 0.2006 : val hss = 0.3123
Fold 3: train tss = 0.7814 : val tss = 0.2644 ::: train hss = 0.2820 : val hss = 0.0625
Fold 4: train tss = 0.7729 : val tss = 0.6863 ::: train hss = 0.2667 : val hss = 0.2398
mean cv TSS: 0.3850
mean cv HSS: 0.1429
564/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7952 : val tss = 0.3860 ::: train hss = 0.3446 : val hss = 0.1549
Fold 2: train tss = 0.7593 : val tss = 0.6725 ::: train hss = 0.2303 : val hss = 0.3254
Fold 3: train tss = 0.7610 : val tss = 0.0131 ::: train hss = 0.2810 : val hss = 0.0035
Fold 4: train tss = 0.7910 : val tss = 0.6638 ::: train hss = 0.2686 : val hss = 0.3187
mean cv TSS: 0.3471
mean cv HSS: 0.1605
565/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6873 : val tss = 0.3014 ::: train hss = 0.1437 : val hss = 0.1564
Fold 2: train tss = 0.7470 : val tss = 0.7534 ::: train hss = 0.2196 : val hss = 0.4324
Fold 3: train tss = 0.7643 : val tss = 0.0821 ::: train hss = 0.2648 : val hss = 0.0287
Fold 4: train tss = 0.6805 : val tss = 0.6832 ::: train hss = 0.1804 : val hss = 0.2820
mean cv TSS: 0.3640
mean cv HSS: 0.1799
566/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7511 : val tss = 0.2864 ::: train hss = 0.3114 : val hss = 0.1149
Fold 2: train tss = 0.7697 : val tss = 0.7171 ::: train hss = 0.2253 : val hss = 0.3168
Fold 3: train tss = 0.7499 : val tss = 0.2717 ::: train hss = 0.2690 : val hss = 0.0750
Fold 4: train tss = 0.7453 : val tss = 0.7429 ::: train hss = 0.2512 : val hss = 0.3186
mean cv TSS: 0.4036
mean cv HSS: 0.1651
567/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7551 : val tss = 0.2789 ::: train hss = 0.3102 : val hss = 0.1095
Fold 2: train tss = 0.6994 : val tss = 0.7022 ::: train hss = 0.1346 : val hss = 0.2865
Fold 3: train tss = 0.6877 : val tss = 0.3310 ::: train hss = 0.1884 : val hss = 0.0741
Fold 4: train tss = 0.7280 : val tss = 0.7120 ::: train hss = 0.2221 : val hss = 0.2950
mean cv TSS: 0.4048
mean cv HSS: 0.1530
568/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.7931 : val tss = 0.0846 ::: train hss = 0.3411 : val hss = 0.1313
Fold 1: train tss = 0.8179 : val tss = 0.2000 ::: train hss = 0.4146 : val hss = 0.2112
Fold 2: train tss = 0.7926 : val tss = 0.7188 ::: train hss = 0.2547 : val hss = 0.4468
Fold 3: train tss = 0.7066 : val tss = 0.0382 ::: train hss = 0.1939 : val hss = 0.0180
Fold 4: train tss = 0.7249 : val tss = 0.6282 ::: train hss = 0.2298 : val hss = 0.2103
mean cv TSS: 0.3340
mean cv HSS: 0.2035
569/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7443 : val tss = 0.1682 ::: train hss = 0.2343 : val hss = 0.2048
Fold 2: train tss = 0.6116 : val tss = 0.7260 ::: train hss = 0.1443 : val hss = 0.4388
Fold 3: train tss = 0.7419 : val tss = 0.0938 ::: train hss = 0.2678 : val hss = 0.0302
Fold 4: train tss = 0.6772 : val tss = 0.6827 ::: train hss = 0.1610 : val hss = 0.2538
mean cv TSS: 0.3341
mean cv HSS: 0.1855
570/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9902 : val tss = -0.0001 ::: train hss = 0.3274 : val hss = -0.0002
Fold 1: train tss = 0.8028 : val tss = 0.3390 ::: train hss = 0.3396 : val hss = 0.1799
Fold 2: train tss = 0.8072 : val tss = 0.7409 ::: train hss = 0.2695 : val hss = 0.3845
Fold 3: train tss = 0.7876 : val tss = 0.2669 ::: train hss = 0.2396 : val hss = 0.0957
Fold 4: train tss = 0.8052 : val tss = 0.7444 ::: train hss = 0.2661 : val hss = 0.3243
mean cv TSS: 0.4182
mean cv HSS: 0.1968
571/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.4967 : val tss = -0.0001 ::: train hss = 0.3486 : val hss = -0.0002
Fold 1: train tss = 0.7615 : val tss = 0.1822 ::: train hss = 0.3221 : val hss = 0.2108
Fold 2: train tss = 0.7465 : val tss = 0.6947 ::: train hss = 0.1764 : val hss = 0.3991
Fold 3: train tss = 0.7543 : val tss = 0.2260 ::: train hss = 0.2641 : val hss = 0.0623
Fold 4: train tss = 0.7446 : val tss = 0.7047 ::: train hss = 0.2299 : val hss = 0.2731
mean cv TSS: 0.3615
mean cv HSS: 0.1890
572/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 145916
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7927 : val tss = 0.3835 ::: train hss = 0.4201 : val hss = 0.2771
Fold 2: train tss = 0.5389 : val tss = 0.7102 ::: train hss = 0.1123 : val hss = 0.3125
Fold 3: train tss = 0.7869 : val tss = 0.2196 ::: train hss = 0.3187 : val hss = 0.0771
Fold 4: train tss = 0.7012 : val tss = 0.6037 ::: train hss = 0.1819 : val hss = 0.2078
mean cv TSS: 0.3834
mean cv HSS: 0.1749
573/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7336 : val tss = 0.3368 ::: train hss = 0.1658 : val hss = 0.1643
Fold 2: train tss = 0.4757 : val tss = 0.5777 ::: train hss = 0.1027 : val hss = 0.1798
Fold 3: train tss = 0.7313 : val tss = 0.1104 ::: train hss = 0.2536 : val hss = 0.0348
Fold 4: train tss = 0.6970 : val tss = 0.7399 ::: train hss = 0.1847 : val hss = 0.3261
mean cv TSS: 0.3530
mean cv HSS: 0.1410
574/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7796 : val tss = 0.3047 ::: train hss = 0.3837 : val hss = 0.1355
Fold 2: train tss = 0.8199 : val tss = 0.7249 ::: train hss = 0.2328 : val hss = 0.4028
Fold 3: train tss = 0.7805 : val tss = 0.2375 ::: train hss = 0.3018 : val hss = 0.0830
Fold 4: train tss = 0.7800 : val tss = 0.6194 ::: train hss = 0.2948 : val hss = 0.1999
mean cv TSS: 0.3773
mean cv HSS: 0.1642
575/768
{'batch_size': 256, 'bce_pos_class_weight': 40, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7654 : val tss = 0.3187 ::: train hss = 0.3449 : val hss = 0.1545
Fold 2: train tss = 0.6872 : val tss = 0.7309 ::: train hss = 0.1749 : val hss = 0.3208
Fold 3: train tss = 0.7590 : val tss = 0.2964 ::: train hss = 0.2531 : val hss = 0.0797
Fold 4: train tss = 0.7376 : val tss = 0.7344 ::: train hss = 0.2590 : val hss = 0.3176
mean cv TSS: 0.4161
mean cv HSS: 0.1745
576/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.9807 : val tss = 0.1259 ::: train hss = 0.1961 : val hss = 0.1336
Fold 1: train tss = 0.8555 : val tss = 0.2403 ::: train hss = 0.3492 : val hss = 0.1285
Fold 2: train tss = 0.7520 : val tss = 0.5195 ::: train hss = 0.1584 : val hss = 0.1608
Fold 3: train tss = 0.7160 : val tss = 0.0446 ::: train hss = 0.1597 : val hss = 0.0114
Fold 4: train tss = 0.7603 : val tss = 0.6859 ::: train hss = 0.2000 : val hss = 0.2610
mean cv TSS: 0.3232
mean cv HSS: 0.1390
577/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = -0.0002 : val tss = 0.0000 ::: train hss = -0.0004 : val hss = 0.0000
Fold 1: train tss = 0.8316 : val tss = 0.3920 ::: train hss = 0.2489 : val hss = 0.1873
Fold 2: train tss = 0.7434 : val tss = 0.6505 ::: train hss = 0.1475 : val hss = 0.2561
Fold 3: train tss = 0.6649 : val tss = 0.3215 ::: train hss = 0.1450 : val hss = 0.0623
Fold 4: train tss = 0.7048 : val tss = 0.5359 ::: train hss = 0.1496 : val hss = 0.1334
mean cv TSS: 0.3800
mean cv HSS: 0.1278
578/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9916 : val tss = -0.0094 ::: train hss = 0.3606 : val hss = -0.0119
Fold 1: train tss = 0.9213 : val tss = 0.3554 ::: train hss = 0.3371 : val hss = 0.1059
Fold 2: train tss = 0.8292 : val tss = 0.5380 ::: train hss = 0.2260 : val hss = 0.2602
Fold 3: train tss = 0.8071 : val tss = 0.2016 ::: train hss = 0.2625 : val hss = 0.0343
Fold 4: train tss = 0.7323 : val tss = 0.6751 ::: train hss = 0.1693 : val hss = 0.2496
mean cv TSS: 0.3521
mean cv HSS: 0.1276
579/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.9916 : val tss = -0.0007 ::: train hss = 0.3606 : val hss = -0.0014
Fold 1: train tss = 0.8722 : val tss = 0.4102 ::: train hss = 0.2886 : val hss = 0.0727
Fold 2: train tss = 0.6974 : val tss = 0.6436 ::: train hss = 0.1168 : val hss = 0.2205
Fold 3: train tss = 0.7683 : val tss = 0.2663 ::: train hss = 0.1935 : val hss = 0.0846
Fold 4: train tss = 0.7480 : val tss = 0.6664 ::: train hss = 0.1889 : val hss = 0.2272
mean cv TSS: 0.3971
mean cv HSS: 0.1207
580/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.3413 : val tss = 0.0245 ::: train hss = 0.1379 : val hss = 0.0337
Fold 1: train tss = 0.7842 : val tss = 0.4012 ::: train hss = 0.2006 : val hss = 0.2573
Fold 2: train tss = 0.6982 : val tss = 0.6281 ::: train hss = 0.1324 : val hss = 0.2272
Fold 3: train tss = 0.6836 : val tss = 0.3622 ::: train hss = 0.1565 : val hss = 0.0515
Fold 4: train tss = 0.7129 : val tss = 0.5703 ::: train hss = 0.1530 : val hss = 0.2041
mean cv TSS: 0.3973
mean cv HSS: 0.1548
581/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0498 : val tss = -0.0005 ::: train hss = 0.0865 : val hss = -0.0010
Fold 1: train tss = 0.6629 : val tss = 0.2674 ::: train hss = 0.0838 : val hss = 0.0731
Fold 2: train tss = 0.6563 : val tss = 0.6411 ::: train hss = 0.0978 : val hss = 0.2160
Fold 3: train tss = 0.6684 : val tss = 0.4926 ::: train hss = 0.1385 : val hss = 0.0620
Fold 4: train tss = 0.6212 : val tss = 0.5857 ::: train hss = 0.1157 : val hss = 0.1599
mean cv TSS: 0.3973
mean cv HSS: 0.1020
582/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.1959 : val tss = 0.0094 ::: train hss = 0.1351 : val hss = 0.0152
Fold 1: train tss = 0.7322 : val tss = 0.3729 ::: train hss = 0.1254 : val hss = 0.1144
Fold 2: train tss = 0.5400 : val tss = 0.5180 ::: train hss = 0.0500 : val hss = 0.1382
Fold 3: train tss = 0.7004 : val tss = 0.1634 ::: train hss = 0.1666 : val hss = 0.0214
Fold 4: train tss = 0.7011 : val tss = 0.6314 ::: train hss = 0.1574 : val hss = 0.2057
mean cv TSS: 0.3390
mean cv HSS: 0.0990
583/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.2977 : val tss = 0.0033 ::: train hss = 0.2646 : val hss = 0.0061

Fold 1: train tss = 0.6419 : val tss = 0.3892 ::: train hss = 0.0608 : val hss = 0.0771
Fold 2: train tss = 0.6124 : val tss = 0.6336 ::: train hss = 0.0720 : val hss = 0.2157
Fold 3: train tss = 0.6191 : val tss = 0.4592 ::: train hss = 0.1099 : val hss = 0.0466
Fold 4: train tss = 0.6897 : val tss = 0.6152 ::: train hss = 0.1334 : val hss = 0.1859
mean cv TSS: 0.4201
mean cv HSS: 0.1063
584/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.8357 : val tss = 0.0231 ::: train hss = 0.2143 : val hss = 0.0182
Fold 1: train tss = 0.8304 : val tss = 0.0902 ::: train hss = 0.3071 : val hss = 0.0321
Fold 2: train tss = 0.7326 : val tss = 0.6859 ::: train hss = 0.1316 : val hss = 0.3153
Fold 3: train tss = 0.6862 : val tss = 0.2978 ::: train hss = 0.1368 : val hss = 0.0355
Fold 4: train tss = 0.6739 : val tss = 0.5826 ::: train hss = 0.1386 : val hss = 0.1737
mean cv TSS: 0.3359
mean cv HSS: 0.1150
585/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0002 : val hss = 0.0000
Fold 1: train tss = 0.8108 : val tss = 0.4088 ::: train hss = 0.2624 : val hss = 0.1446
Fold 2: train tss = 0.6799 : val tss = 0.7534 ::: train hss = 0.1155 : val hss = 0.3650
Fold 3: train tss = 0.6224 : val tss = 0.5064 ::: train hss = 0.1166 : val hss = 0.0577
Fold 4: train tss = 0.6546 : val tss = 0.5515 ::: train hss = 0.1220 : val hss = 0.1400
mean cv TSS: 0.4440
mean cv HSS: 0.1415
586/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9942 : val tss = 0.0416 ::: train hss = 0.4519 : val hss = 0.0346
Fold 1: train tss = 0.9305 : val tss = 0.1955 ::: train hss = 0.3206 : val hss = 0.0620
Fold 2: train tss = 0.7845 : val tss = 0.6370 ::: train hss = 0.1697 : val hss = 0.2424
Fold 3: train tss = 0.7421 : val tss = 0.5751 ::: train hss = 0.1734 : val hss = 0.0643
Fold 4: train tss = 0.7643 : val tss = 0.6660 ::: train hss = 0.2018 : val hss = 0.2249
mean cv TSS: 0.4230
mean cv HSS: 0.1256
587/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7742 : val tss = 0.3188 ::: train hss = 0.2655 : val hss = 0.1481
Fold 2: train tss = 0.7102 : val tss = 0.5491 ::: train hss = 0.1109 : val hss = 0.1589
Fold 3: train tss = 0.7261 : val tss = 0.3107 ::: train hss = 0.1835 : val hss = 0.0473
Fold 4: train tss = 0.6458 : val tss = 0.5476 ::: train hss = 0.1209 : val hss = 0.1408
mean cv TSS: 0.3452
mean cv HSS: 0.0990
588/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.5902 : val tss = -0.0126 ::: train hss = 0.2089 : val hss = -0.0147
Fold 1: train tss = 0.8259 : val tss = 0.3393 ::: train hss = 0.2571 : val hss = 0.1216
Fold 2: train tss = 0.7382 : val tss = 0.7475 ::: train hss = 0.1456 : val hss = 0.3698
Fold 3: train tss = 0.7283 : val tss = 0.2274 ::: train hss = 0.1988 : val hss = 0.0363
Fold 4: train tss = 0.6823 : val tss = 0.6730 ::: train hss = 0.1412 : val hss = 0.2298
mean cv TSS: 0.3949
mean cv HSS: 0.1485
589/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.6579 : val tss = 0.4100 ::: train hss = 0.0830 : val hss = 0.1507
Fold 2: train tss = 0.5741 : val tss = 0.6423 ::: train hss = 0.0879 : val hss = 0.2170
Fold 3: train tss = 0.7033 : val tss = 0.2529 ::: train hss = 0.1592 : val hss = 0.0475
Fold 4: train tss = 0.6245 : val tss = 0.6723 ::: train hss = 0.1076 : val hss = 0.2345
mean cv TSS: 0.3955
mean cv HSS: 0.1299
590/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.3500 : val tss = 0.0000 ::: train hss = 0.5185 : val hss = 0.0000
Fold 1: train tss = 0.7627 : val tss = 0.2690 ::: train hss = 0.2695 : val hss = 0.1187
Fold 2: train tss = 0.7416 : val tss = 0.6988 ::: train hss = 0.1398 : val hss = 0.2775
Fold 3: train tss = 0.7164 : val tss = 0.3965 ::: train hss = 0.1796 : val hss = 0.0468
Fold 4: train tss = 0.7412 : val tss = 0.7188 ::: train hss = 0.1728 : val hss = 0.2835
mean cv TSS: 0.4166
mean cv HSS: 0.1453
591/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.2499 : val tss = -0.0004 ::: train hss = 0.3844 : val hss = -0.0007
Fold 1: train tss = 0.7506 : val tss = 0.2958 ::: train hss = 0.2552 : val hss = 0.1274
Fold 2: train tss = 0.6498 : val tss = 0.6197 ::: train hss = 0.0974 : val hss = 0.2079
Fold 3: train tss = 0.6324 : val tss = 0.2458 ::: train hss = 0.1179 : val hss = 0.0175
Fold 4: train tss = 0.7076 : val tss = 0.6422 ::: train hss = 0.1564 : val hss = 0.2212
mean cv TSS: 0.3606
mean cv HSS: 0.1147
592/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.8890 : val tss = 0.2656 ::: train hss = 0.2757 : val hss = 0.1638
Fold 1: train tss = 0.7965 : val tss = 0.2440 ::: train hss = 0.2197 : val hss = 0.0957
Fold 2: train tss = 0.7551 : val tss = 0.6183 ::: train hss = 0.1433 : val hss = 0.2537
Fold 3: train tss = 0.7178 : val tss = 0.2084 ::: train hss = 0.1664 : val hss = 0.0452
Fold 4: train tss = 0.7498 : val tss = 0.6470 ::: train hss = 0.1861 : val hss = 0.2244
mean cv TSS: 0.3967
mean cv HSS: 0.1565
593/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.5910 : val tss = 0.0315 ::: train hss = 0.2209 : val hss = 0.0539
Fold 1: train tss = 0.8271 : val tss = 0.4716 ::: train hss = 0.2759 : val hss = 0.3162
Fold 2: train tss = 0.7801 : val tss = 0.6892 ::: train hss = 0.1908 : val hss = 0.2797
Fold 3: train tss = 0.7394 : val tss = 0.2402 ::: train hss = 0.1859 : val hss = 0.0414
Fold 4: train tss = 0.7127 : val tss = 0.6480 ::: train hss = 0.1432 : val hss = 0.2317
mean cv TSS: 0.4161
mean cv HSS: 0.1846
594/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9878 : val tss = 0.1033 ::: train hss = 0.2802 : val hss = 0.1521

Fold 1: train tss = 0.7984 : val tss = 0.2708 ::: train hss = 0.3156 : val hss = 0.1286
Fold 2: train tss = 0.7927 : val tss = 0.6570 ::: train hss = 0.1718 : val hss = 0.2524
Fold 3: train tss = 0.7887 : val tss = 0.3164 ::: train hss = 0.2392 : val hss = 0.0557
Fold 4: train tss = 0.7624 : val tss = 0.7200 ::: train hss = 0.1863 : val hss = 0.3884
mean cv TSS: 0.4135
mean cv HSS: 0.1954
595/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.9881 : val tss = -0.0002 ::: train hss = 0.2843 : val hss = -0.0005
Fold 1: train tss = 0.8846 : val tss = 0.2802 ::: train hss = 0.2591 : val hss = 0.0588
Fold 2: train tss = 0.6676 : val tss = 0.5252 ::: train hss = 0.1036 : val hss = 0.1415
Fold 3: train tss = 0.7736 : val tss = 0.3262 ::: train hss = 0.2270 : val hss = 0.0544
Fold 4: train tss = 0.7556 : val tss = 0.6507 ::: train hss = 0.2006 : val hss = 0.2396
mean cv TSS: 0.3564
mean cv HSS: 0.0987
596/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.4441 : val tss = 0.0201 ::: train hss = 0.2277 : val hss = 0.0283
Fold 1: train tss = 0.8107 : val tss = 0.1792 ::: train hss = 0.2619 : val hss = 0.1363
Fold 2: train tss = 0.7722 : val tss = 0.6650 ::: train hss = 0.1999 : val hss = 0.2631
Fold 3: train tss = 0.7390 : val tss = 0.4401 ::: train hss = 0.1938 : val hss = 0.0560
Fold 4: train tss = 0.6621 : val tss = 0.6407 ::: train hss = 0.1206 : val hss = 0.2077
mean cv TSS: 0.3890
mean cv HSS: 0.1383
597/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8081 : val tss = 0.3393 ::: train hss = 0.2676 : val hss = 0.1575
Fold 2: train tss = 0.6371 : val tss = 0.6392 ::: train hss = 0.0998 : val hss = 0.2512
Fold 3: train tss = 0.6370 : val tss = 0.1125 ::: train hss = 0.1258 : val hss = 0.0206
Fold 4: train tss = 0.6673 : val tss = 0.6714 ::: train hss = 0.1370 : val hss = 0.2437
mean cv TSS: 0.3525
mean cv HSS: 0.1346
598/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.3442 : val tss = 0.0265 ::: train hss = 0.1836 : val hss = 0.0456
Fold 1: train tss = 0.7587 : val tss = 0.3221 ::: train hss = 0.2172 : val hss = 0.1066
Fold 2: train tss = 0.6615 : val tss = 0.6563 ::: train hss = 0.0945 : val hss = 0.2332
Fold 3: train tss = 0.6369 : val tss = 0.2481 ::: train hss = 0.1202 : val hss = 0.0329
Fold 4: train tss = 0.7426 : val tss = 0.6662 ::: train hss = 0.1841 : val hss = 0.2353
mean cv TSS: 0.3839
mean cv HSS: 0.1307
599/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.1953 : val tss = -0.0048 ::: train hss = 0.1240 : val hss = -0.0080
Fold 1: train tss = 0.7545 : val tss = 0.4741 ::: train hss = 0.1410 : val hss = 0.1484
Fold 2: train tss = 0.6036 : val tss = 0.6119 ::: train hss = 0.0672 : val hss = 0.1996
Fold 3: train tss = 0.6576 : val tss = 0.4082 ::: train hss = 0.1304 : val hss = 0.0611
Fold 4: train tss = 0.6603 : val tss = 0.5654 ::: train hss = 0.1177 : val hss = 0.1544
mean cv TSS: 0.4110
mean cv HSS: 0.1111
600/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.7884 : val tss = -0.0302 ::: train hss = 0.2389 : val hss = -0.0165
Fold 1: train tss = 0.8057 : val tss = 0.3139 ::: train hss = 0.1949 : val hss = 0.2047
Fold 2: train tss = 0.7485 : val tss = 0.6492 ::: train hss = 0.1627 : val hss = 0.2668
Fold 3: train tss = 0.7487 : val tss = 0.3376 ::: train hss = 0.1889 : val hss = 0.0690
Fold 4: train tss = 0.7037 : val tss = 0.6433 ::: train hss = 0.1566 : val hss = 0.2011
mean cv TSS: 0.3828
mean cv HSS: 0.1450
601/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.1487 : val tss = -0.0015 ::: train hss = 0.1749 : val hss = -0.0028
Fold 1: train tss = 0.6974 : val tss = 0.3468 ::: train hss = 0.0892 : val hss = 0.0845
Fold 2: train tss = 0.6907 : val tss = 0.5693 ::: train hss = 0.1216 : val hss = 0.1677
Fold 3: train tss = 0.7129 : val tss = 0.3107 ::: train hss = 0.1880 : val hss = 0.0684
Fold 4: train tss = 0.6744 : val tss = 0.6833 ::: train hss = 0.1430 : val hss = 0.2596
mean cv TSS: 0.3817
mean cv HSS: 0.1155
602/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9943 : val tss = -0.0005 ::: train hss = 0.4572 : val hss = -0.0010
Fold 1: train tss = 0.8048 : val tss = 0.3162 ::: train hss = 0.2709 : val hss = 0.0990
Fold 2: train tss = 0.8134 : val tss = 0.6318 ::: train hss = 0.1773 : val hss = 0.2437
Fold 3: train tss = 0.7524 : val tss = 0.2159 ::: train hss = 0.1938 : val hss = 0.0339
Fold 4: train tss = 0.7449 : val tss = 0.6906 ::: train hss = 0.1839 : val hss = 0.2449
mean cv TSS: 0.3708
mean cv HSS: 0.1241
603/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.9895 : val tss = 0.0000 ::: train hss = 0.3117 : val hss = 0.0000
Fold 1: train tss = 0.8600 : val tss = 0.3738 ::: train hss = 0.2600 : val hss = 0.0693
Fold 2: train tss = 0.6536 : val tss = 0.6226 ::: train hss = 0.0836 : val hss = 0.2269
Fold 3: train tss = 0.7577 : val tss = 0.3151 ::: train hss = 0.1838 : val hss = 0.0623
Fold 4: train tss = 0.7303 : val tss = 0.6565 ::: train hss = 0.1830 : val hss = 0.2179
mean cv TSS: 0.3936
mean cv HSS: 0.1153
604/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.0993 : val tss = 0.0000 ::: train hss = 0.1418 : val hss = 0.0000
Fold 1: train tss = 0.7550 : val tss = 0.3475 ::: train hss = 0.1461 : val hss = 0.1739
Fold 2: train tss = 0.7233 : val tss = 0.6112 ::: train hss = 0.1513 : val hss = 0.2102
Fold 3: train tss = 0.6582 : val tss = 0.5517 ::: train hss = 0.1365 : val hss = 0.0604
Fold 4: train tss = 0.7084 : val tss = 0.6578 ::: train hss = 0.1579 : val hss = 0.2278
mean cv TSS: 0.4336
mean cv HSS: 0.1345
605/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 62796
Fold 0: train tss = 0.0999 : val tss = 0.0046 ::: train hss = 0.1737 : val hss = 0.0090
Fold 1: train tss = 0.6605 : val tss = 0.3101 ::: train hss = 0.0844 : val hss = 0.0822
Fold 2: train tss = 0.6565 : val tss = 0.7431 ::: train hss = 0.1133 : val hss = 0.3527
Fold 3: train tss = 0.6320 : val tss = 0.4148 ::: train hss = 0.1305 : val hss = 0.0490
Fold 4: train tss = 0.6170 : val tss = 0.5735 ::: train hss = 0.1155 : val hss = 0.1484
mean cv TSS: 0.4092
mean cv HSS: 0.1283
606/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.4495 : val tss = 0.0168 ::: train hss = 0.5449 : val hss = 0.0294
Fold 1: train tss = 0.7948 : val tss = 0.2818 ::: train hss = 0.3424 : val hss = 0.1212
Fold 2: train tss = 0.7382 : val tss = 0.6931 ::: train hss = 0.1419 : val hss = 0.3055
Fold 3: train tss = 0.7446 : val tss = 0.3394 ::: train hss = 0.2115 : val hss = 0.0520
Fold 4: train tss = 0.7552 : val tss = 0.6903 ::: train hss = 0.1912 : val hss = 0.2602
mean cv TSS: 0.4043
mean cv HSS: 0.1537
607/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.2498 : val tss = 0.0000 ::: train hss = 0.3700 : val hss = 0.0000
Fold 1: train tss = 0.7590 : val tss = 0.2939 ::: train hss = 0.1823 : val hss = 0.1253
Fold 2: train tss = 0.5779 : val tss = 0.6095 ::: train hss = 0.0758 : val hss = 0.1936
Fold 3: train tss = 0.6911 : val tss = 0.3220 ::: train hss = 0.1456 : val hss = 0.0496
Fold 4: train tss = 0.6306 : val tss = 0.6095 ::: train hss = 0.1125 : val hss = 0.1864
mean cv TSS: 0.3670
mean cv HSS: 0.1110
608/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.9204 : val tss = 0.0606 ::: train hss = 0.1292 : val hss = 0.0589
Fold 1: train tss = 0.8328 : val tss = 0.1866 ::: train hss = 0.2663 : val hss = 0.1252
Fold 2: train tss = 0.7695 : val tss = 0.5887 ::: train hss = 0.1873 : val hss = 0.2281
Fold 3: train tss = 0.6738 : val tss = 0.5963 ::: train hss = 0.1408 : val hss = 0.0605
Fold 4: train tss = 0.7171 : val tss = 0.6450 ::: train hss = 0.1677 : val hss = 0.2321
mean cv TSS: 0.4154
mean cv HSS: 0.1410
609/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7743 : val tss = 0.4555 ::: train hss = 0.1967 : val hss = 0.2250
Fold 2: train tss = 0.7398 : val tss = 0.6540 ::: train hss = 0.1470 : val hss = 0.2916
Fold 3: train tss = 0.7023 : val tss = 0.1435 ::: train hss = 0.1634 : val hss = 0.0309
Fold 4: train tss = 0.6851 : val tss = 0.6830 ::: train hss = 0.1469 : val hss = 0.2817
mean cv TSS: 0.3872
mean cv HSS: 0.1658
610/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9899 : val tss = -0.0227 ::: train hss = 0.3193 : val hss = -0.0214
Fold 1: train tss = 0.9047 : val tss = 0.3136 ::: train hss = 0.2344 : val hss = 0.1171
Fold 2: train tss = 0.7813 : val tss = 0.7004 ::: train hss = 0.1529 : val hss = 0.3237
Fold 3: train tss = 0.7815 : val tss = 0.3367 ::: train hss = 0.2110 : val hss = 0.0484
Fold 4: train tss = 0.7250 : val tss = 0.6825 ::: train hss = 0.1834 : val hss = 0.2649
mean cv TSS: 0.4021
mean cv HSS: 0.1465
611/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.6424 : val tss = 0.0000 ::: train hss = 0.2677 : val hss = 0.0000
Fold 1: train tss = 0.7738 : val tss = 0.2944 ::: train hss = 0.2639 : val hss = 0.1259
Fold 2: train tss = 0.6838 : val tss = 0.5582 ::: train hss = 0.1111 : val hss = 0.1638
Fold 3: train tss = 0.7702 : val tss = 0.3153 ::: train hss = 0.2138 : val hss = 0.0493
Fold 4: train tss = 0.7302 : val tss = 0.6338 ::: train hss = 0.1696 : val hss = 0.2068
mean cv TSS: 0.3604
mean cv HSS: 0.1091
612/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.1000 : val tss = -0.0002 ::: train hss = 0.1818 : val hss = -0.0005
Fold 1: train tss = 0.7746 : val tss = 0.3960 ::: train hss = 0.1514 : val hss = 0.1531
Fold 2: train tss = 0.7251 : val tss = 0.7377 ::: train hss = 0.1326 : val hss = 0.3599
Fold 3: train tss = 0.6789 : val tss = 0.1891 ::: train hss = 0.1491 : val hss = 0.0283
Fold 4: train tss = 0.6655 : val tss = 0.6592 ::: train hss = 0.1459 : val hss = 0.2260
mean cv TSS: 0.3964
mean cv HSS: 0.1534
613/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.1475 : val tss = 0.0306 ::: train hss = 0.1341 : val hss = 0.0433
Fold 1: train tss = 0.7835 : val tss = 0.3745 ::: train hss = 0.2287 : val hss = 0.1096
Fold 2: train tss = 0.7281 : val tss = 0.6255 ::: train hss = 0.1502 : val hss = 0.2408
Fold 3: train tss = 0.6358 : val tss = 0.1385 ::: train hss = 0.1220 : val hss = 0.0176
Fold 4: train tss = 0.6328 : val tss = 0.6006 ::: train hss = 0.1222 : val hss = 0.1875
mean cv TSS: 0.3539
mean cv HSS: 0.1197
614/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.3466 : val tss = -0.0047 ::: train hss = 0.2521 : val hss = -0.0079
Fold 1: train tss = 0.7521 : val tss = 0.3862 ::: train hss = 0.1382 : val hss = 0.1135
Fold 2: train tss = 0.5613 : val tss = 0.5854 ::: train hss = 0.0598 : val hss = 0.1772
Fold 3: train tss = 0.6243 : val tss = 0.3667 ::: train hss = 0.1206 : val hss = 0.0562
Fold 4: train tss = 0.7065 : val tss = 0.6436 ::: train hss = 0.1537 : val hss = 0.2254
mean cv TSS: 0.3955
mean cv HSS: 0.1129
615/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.0976 : val tss = -0.0007 ::: train hss = 0.0929 : val hss = -0.0014
Fold 1: train tss = 0.7159 : val tss = 0.4013 ::: train hss = 0.0826 : val hss = 0.0975
Fold 2: train tss = 0.5660 : val tss = 0.6202 ::: train hss = 0.0593 : val hss = 0.1999
Fold 3: train tss = 0.6165 : val tss = 0.5628 ::: train hss = 0.1044 : val hss = 0.0540
Fold 4: train tss = 0.6000 : val tss = 0.5076 ::: train hss = 0.0921 : val hss = 0.1216
mean cv TSS: 0.4182
mean cv HSS: 0.0943
616/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 47180
Fold 0: train tss = 0.9218 : val tss = -0.0025 ::: train hss = 0.1351 : val hss = -0.0026
Fold 1: train tss = 0.8183 : val tss = 0.3404 ::: train hss = 0.2042 : val hss = 0.0900
Fold 2: train tss = 0.7198 : val tss = 0.6577 ::: train hss = 0.1554 : val hss = 0.2566
Fold 3: train tss = 0.7316 : val tss = 0.1208 ::: train hss = 0.2001 : val hss = 0.0207
Fold 4: train tss = 0.7100 : val tss = 0.6744 ::: train hss = 0.1642 : val hss = 0.2917
mean cv TSS: 0.3581
mean cv HSS: 0.1313
617/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7330 : val tss = 0.3447 ::: train hss = 0.1587 : val hss = 0.2183
Fold 2: train tss = 0.6987 : val tss = 0.5711 ::: train hss = 0.1083 : val hss = 0.1799
Fold 3: train tss = 0.7031 : val tss = 0.5777 ::: train hss = 0.1523 : val hss = 0.0653
Fold 4: train tss = 0.6635 : val tss = 0.5821 ::: train hss = 0.1245 : val hss = 0.1700
mean cv TSS: 0.4151
mean cv HSS: 0.1267
618/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.9845 : val tss = 0.0019 ::: train hss = 0.2330 : val hss = 0.0034
Fold 1: train tss = 0.8808 : val tss = 0.4085 ::: train hss = 0.2259 : val hss = 0.0952
Fold 2: train tss = 0.7691 : val tss = 0.5766 ::: train hss = 0.1451 : val hss = 0.2455
Fold 3: train tss = 0.7350 : val tss = 0.5840 ::: train hss = 0.1926 : val hss = 0.0768
Fold 4: train tss = 0.7643 : val tss = 0.6566 ::: train hss = 0.2225 : val hss = 0.2107
mean cv TSS: 0.4455
mean cv HSS: 0.1263
619/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.3952 : val tss = 0.0000 ::: train hss = 0.2325 : val hss = 0.0000
Fold 1: train tss = 0.7781 : val tss = 0.2002 ::: train hss = 0.2993 : val hss = 0.2227
Fold 2: train tss = 0.7022 : val tss = 0.6312 ::: train hss = 0.0977 : val hss = 0.2181
Fold 3: train tss = 0.7554 : val tss = 0.3374 ::: train hss = 0.1927 : val hss = 0.0643
Fold 4: train tss = 0.7117 : val tss = 0.6355 ::: train hss = 0.1536 : val hss = 0.2029
mean cv TSS: 0.3608
mean cv HSS: 0.1416
620/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7600 : val tss = 0.3482 ::: train hss = 0.1842 : val hss = 0.2339
Fold 2: train tss = 0.7119 : val tss = 0.7416 ::: train hss = 0.1506 : val hss = 0.3906
Fold 3: train tss = 0.7631 : val tss = 0.0074 ::: train hss = 0.2234 : val hss = 0.0025
Fold 4: train tss = 0.7090 : val tss = 0.6461 ::: train hss = 0.1665 : val hss = 0.2067
mean cv TSS: 0.3487
mean cv HSS: 0.1667
621/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 47180
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5775 : val tss = 0.3936 ::: train hss = 0.1302 : val hss = 0.1086
Fold 2: train tss = 0.6259 : val tss = 0.6658 ::: train hss = 0.1075 : val hss = 0.2450
Fold 3: train tss = 0.6562 : val tss = 0.2786 ::: train hss = 0.1345 : val hss = 0.0690
Fold 4: train tss = 0.6466 : val tss = 0.5621 ::: train hss = 0.1206 : val hss = 0.1440
mean cv TSS: 0.3800
mean cv HSS: 0.1133
622/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 103269
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7719 : val tss = 0.2917 ::: train hss = 0.2573 : val hss = 0.1161
Fold 2: train tss = 0.6333 : val tss = 0.6441 ::: train hss = 0.0965 : val hss = 0.2358
Fold 3: train tss = 0.7189 : val tss = 0.3683 ::: train hss = 0.1754 : val hss = 0.0569
Fold 4: train tss = 0.7508 : val tss = 0.5827 ::: train hss = 0.2017 : val hss = 0.1586
mean cv TSS: 0.3773
mean cv HSS: 0.1135
623/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 103269
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7376 : val tss = 0.2733 ::: train hss = 0.2053 : val hss = 0.1318
Fold 2: train tss = 0.6131 : val tss = 0.6352 ::: train hss = 0.0738 : val hss = 0.2214
Fold 3: train tss = 0.6413 : val tss = 0.3711 ::: train hss = 0.1204 : val hss = 0.0527
Fold 4: train tss = 0.5752 : val tss = 0.4448 ::: train hss = 0.0803 : val hss = 0.0986
mean cv TSS: 0.3449
mean cv HSS: 0.1009
624/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.9264 : val tss = -0.0127 ::: train hss = 0.1577 : val hss = -0.0109
Fold 1: train tss = 0.8438 : val tss = 0.0801 ::: train hss = 0.2483 : val hss = 0.0267
Fold 2: train tss = 0.7233 : val tss = 0.7051 ::: train hss = 0.1335 : val hss = 0.3185
Fold 3: train tss = 0.7561 : val tss = 0.4318 ::: train hss = 0.2073 : val hss = 0.1142
Fold 4: train tss = 0.7321 : val tss = 0.6729 ::: train hss = 0.1638 : val hss = 0.2576
mean cv TSS: 0.3754
mean cv HSS: 0.1412
625/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7810 : val tss = 0.2588 ::: train hss = 0.2023 : val hss = 0.2747
Fold 2: train tss = 0.7325 : val tss = 0.6621 ::: train hss = 0.1559 : val hss = 0.2636
Fold 3: train tss = 0.6945 : val tss = 0.1572 ::: train hss = 0.1547 : val hss = 0.0270
Fold 4: train tss = 0.6856 : val tss = 0.5446 ::: train hss = 0.1347 : val hss = 0.1458
mean cv TSS: 0.3245
mean cv HSS: 0.1422
626/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9919 : val tss = 0.1788 ::: train hss = 0.3708 : val hss = 0.1473
Fold 1: train tss = 0.8515 : val tss = 0.3315 ::: train hss = 0.2895 : val hss = 0.1440
Fold 2: train tss = 0.7713 : val tss = 0.6070 ::: train hss = 0.1759 : val hss = 0.2188
Fold 3: train tss = 0.7605 : val tss = 0.4389 ::: train hss = 0.2077 : val hss = 0.0532
Fold 4: train tss = 0.7682 : val tss = 0.6720 ::: train hss = 0.2055 : val hss = 0.2489
mean cv TSS: 0.4457
mean cv HSS: 0.1624
627/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.5423 : val tss = 0.0000 ::: train hss = 0.2283 : val hss = 0.0000

Fold 1: train tss = 0.7913 : val tss = 0.2507 ::: train hss = 0.2525 : val hss = 0.1144
Fold 2: train tss = 0.7083 : val tss = 0.6745 ::: train hss = 0.1249 : val hss = 0.2500
Fold 3: train tss = 0.7525 : val tss = 0.2626 ::: train hss = 0.1926 : val hss = 0.0494
Fold 4: train tss = 0.7152 : val tss = 0.6638 ::: train hss = 0.1553 : val hss = 0.2310
mean cv TSS: 0.3703
mean cv HSS: 0.1290
628/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.0498 : val tss = -0.0001 ::: train hss = 0.0865 : val hss = -0.0002
Fold 1: train tss = 0.7368 : val tss = 0.4059 ::: train hss = 0.1159 : val hss = 0.1416
Fold 2: train tss = 0.6947 : val tss = 0.7124 ::: train hss = 0.1244 : val hss = 0.3017
Fold 3: train tss = 0.6937 : val tss = 0.5239 ::: train hss = 0.1632 : val hss = 0.0594
Fold 4: train tss = 0.7011 : val tss = 0.6294 ::: train hss = 0.1487 : val hss = 0.2023
mean cv TSS: 0.4543
mean cv HSS: 0.1410
629/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0999 : val tss = 0.0045 ::: train hss = 0.1737 : val hss = 0.0087
Fold 1: train tss = 0.7887 : val tss = 0.1815 ::: train hss = 0.1654 : val hss = 0.1201
Fold 2: train tss = 0.6384 : val tss = 0.6454 ::: train hss = 0.0970 : val hss = 0.2284
Fold 3: train tss = 0.6697 : val tss = 0.2633 ::: train hss = 0.1462 : val hss = 0.0317
Fold 4: train tss = 0.6509 : val tss = 0.5824 ::: train hss = 0.1230 : val hss = 0.1531
mean cv TSS: 0.3354
mean cv HSS: 0.1084
630/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.0499 : val tss = 0.0000 ::: train hss = 0.0907 : val hss = 0.0000
Fold 1: train tss = 0.7399 : val tss = 0.3455 ::: train hss = 0.1921 : val hss = 0.1319
Fold 2: train tss = 0.6245 : val tss = 0.6162 ::: train hss = 0.0763 : val hss = 0.2014
Fold 3: train tss = 0.6706 : val tss = 0.4099 ::: train hss = 0.1448 : val hss = 0.0619
Fold 4: train tss = 0.6972 : val tss = 0.6520 ::: train hss = 0.1427 : val hss = 0.2257
mean cv TSS: 0.4047
mean cv HSS: 0.1242
631/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.1484 : val tss = -0.0014 ::: train hss = 0.1649 : val hss = -0.0026
Fold 1: train tss = 0.7197 : val tss = 0.4173 ::: train hss = 0.1112 : val hss = 0.1244
Fold 2: train tss = 0.5392 : val tss = 0.5754 ::: train hss = 0.0528 : val hss = 0.1680
Fold 3: train tss = 0.5824 : val tss = 0.4252 ::: train hss = 0.0997 : val hss = 0.0632
Fold 4: train tss = 0.7046 : val tss = 0.6419 ::: train hss = 0.1438 : val hss = 0.2088
mean cv TSS: 0.4117
mean cv HSS: 0.1124
632/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.9102 : val tss = 0.1472 ::: train hss = 0.0987 : val hss = 0.0796
Fold 1: train tss = 0.8189 : val tss = 0.4266 ::: train hss = 0.2055 : val hss = 0.2349
Fold 2: train tss = 0.7451 : val tss = 0.6071 ::: train hss = 0.1844 : val hss = 0.2226
Fold 3: train tss = 0.7214 : val tss = 0.1993 ::: train hss = 0.1938 : val hss = 0.0273
Fold 4: train tss = 0.7144 : val tss = 0.5124 ::: train hss = 0.1502 : val hss = 0.1572
mean cv TSS: 0.3785
mean cv HSS: 0.1443
633/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7643 : val tss = 0.3467 ::: train hss = 0.1847 : val hss = 0.3158
Fold 2: train tss = 0.5724 : val tss = 0.3868 ::: train hss = 0.0681 : val hss = 0.0831
Fold 3: train tss = 0.6811 : val tss = 0.2043 ::: train hss = 0.1579 : val hss = 0.0301
Fold 4: train tss = 0.6353 : val tss = 0.5800 ::: train hss = 0.1180 : val hss = 0.1550
mean cv TSS: 0.3035
mean cv HSS: 0.1168
634/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.9917 : val tss = -0.0004 ::: train hss = 0.3639 : val hss = -0.0007
Fold 1: train tss = 0.8088 : val tss = 0.2945 ::: train hss = 0.2104 : val hss = 0.1168
Fold 2: train tss = 0.7545 : val tss = 0.6014 ::: train hss = 0.1536 : val hss = 0.2486
Fold 3: train tss = 0.7417 : val tss = 0.1372 ::: train hss = 0.1881 : val hss = 0.0247
Fold 4: train tss = 0.7267 : val tss = 0.7313 ::: train hss = 0.1541 : val hss = 0.3033
mean cv TSS: 0.3528
mean cv HSS: 0.1385
635/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.8323 : val tss = 0.0000 ::: train hss = 0.1809 : val hss = 0.0000
Fold 1: train tss = 0.8237 : val tss = 0.2566 ::: train hss = 0.2268 : val hss = 0.0519
Fold 2: train tss = 0.6084 : val tss = 0.3023 ::: train hss = 0.0693 : val hss = 0.0580
Fold 3: train tss = 0.7060 : val tss = 0.3014 ::: train hss = 0.1553 : val hss = 0.0778
Fold 4: train tss = 0.7300 : val tss = 0.6260 ::: train hss = 0.1705 : val hss = 0.1920
mean cv TSS: 0.2973
mean cv HSS: 0.0759
636/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 62796
Fold 0: train tss = 0.0998 : val tss = -0.0002 ::: train hss = 0.1663 : val hss = -0.0005
Fold 1: train tss = 0.7971 : val tss = 0.3738 ::: train hss = 0.1938 : val hss = 0.1991
Fold 2: train tss = 0.6750 : val tss = 0.6807 ::: train hss = 0.1169 : val hss = 0.2678
Fold 3: train tss = 0.6876 : val tss = 0.2753 ::: train hss = 0.1635 : val hss = 0.0470
Fold 4: train tss = 0.6877 : val tss = 0.5026 ::: train hss = 0.1371 : val hss = 0.1179
mean cv TSS: 0.3665
mean cv HSS: 0.1263
637/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 62796
Fold 0: train tss = 0.1966 : val tss = 0.0034 ::: train hss = 0.1513 : val hss = 0.0063
Fold 1: train tss = 0.7879 : val tss = 0.3718 ::: train hss = 0.1999 : val hss = 0.1953
Fold 2: train tss = 0.5526 : val tss = 0.6535 ::: train hss = 0.0952 : val hss = 0.2406
Fold 3: train tss = 0.5844 : val tss = 0.4947 ::: train hss = 0.1019 : val hss = 0.0286
Fold 4: train tss = 0.6208 : val tss = 0.5203 ::: train hss = 0.1110 : val hss = 0.1315
mean cv TSS: 0.4087
mean cv HSS: 0.1205
638/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 137573
Fold 0: train tss = 0.3978 : val tss = 0.0101 ::: train hss = 0.3459 : val hss = 0.0167

Fold 1: train tss = 0.7532 : val tss = 0.2980 ::: train hss = 0.1790 : val hss = 0.1001
Fold 2: train tss = 0.7033 : val tss = 0.6238 ::: train hss = 0.1308 : val hss = 0.2216
Fold 3: train tss = 0.7345 : val tss = 0.4498 ::: train hss = 0.2004 : val hss = 0.0659
Fold 4: train tss = 0.6679 : val tss = 0.6201 ::: train hss = 0.1221 : val hss = 0.1963
mean cv TSS: 0.4004
mean cv HSS: 0.1201
639/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 4, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 137573
Fold 0: train tss = 0.3463 : val tss = -0.0030 ::: train hss = 0.2388 : val hss = -0.0053
Fold 1: train tss = 0.7552 : val tss = 0.2908 ::: train hss = 0.1569 : val hss = 0.1152
Fold 2: train tss = 0.6538 : val tss = 0.6082 ::: train hss = 0.0894 : val hss = 0.1912
Fold 3: train tss = 0.6688 : val tss = 0.4321 ::: train hss = 0.1444 : val hss = 0.0667
Fold 4: train tss = 0.6544 : val tss = 0.4345 ::: train hss = 0.1274 : val hss = 0.0904
mean cv TSS: 0.3525
mean cv HSS: 0.0917
640/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.9869 : val tss = -0.0047 ::: train hss = 0.2649 : val hss = -0.0079
Fold 1: train tss = 0.8973 : val tss = 0.4402 ::: train hss = 0.3449 : val hss = 0.1862
Fold 2: train tss = 0.7815 : val tss = 0.7374 ::: train hss = 0.1768 : val hss = 0.3762
Fold 3: train tss = 0.7991 : val tss = 0.1855 ::: train hss = 0.2670 : val hss = 0.0492
Fold 4: train tss = 0.7727 : val tss = 0.6574 ::: train hss = 0.1955 : val hss = 0.2120
mean cv TSS: 0.4032
mean cv HSS: 0.1631
641/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.9366 : val tss = -0.0023 ::: train hss = 0.2498 : val hss = -0.0035
Fold 1: train tss = 0.7806 : val tss = 0.3786 ::: train hss = 0.1247 : val hss = 0.2141
Fold 2: train tss = 0.7430 : val tss = 0.6853 ::: train hss = 0.1556 : val hss = 0.2679
Fold 3: train tss = 0.7871 : val tss = 0.0180 ::: train hss = 0.2305 : val hss = 0.0051
Fold 4: train tss = 0.7027 : val tss = 0.5626 ::: train hss = 0.1535 : val hss = 0.1976
mean cv TSS: 0.3284
mean cv HSS: 0.1362
642/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9921 : val tss = -0.0098 ::: train hss = 0.3744 : val hss = -0.0122
Fold 1: train tss = 0.9397 : val tss = 0.2646 ::: train hss = 0.4238 : val hss = 0.1075
Fold 2: train tss = 0.8479 : val tss = 0.6292 ::: train hss = 0.2300 : val hss = 0.3024
Fold 3: train tss = 0.8366 : val tss = 0.4815 ::: train hss = 0.3092 : val hss = 0.0851
Fold 4: train tss = 0.8208 : val tss = 0.7401 ::: train hss = 0.2627 : val hss = 0.3114
mean cv TSS: 0.4211
mean cv HSS: 0.1588
643/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.6381 : val tss = 0.0000 ::: train hss = 0.1934 : val hss = 0.0000
Fold 1: train tss = 0.8810 : val tss = 0.2558 ::: train hss = 0.2608 : val hss = 0.1205
Fold 2: train tss = 0.7611 : val tss = 0.5462 ::: train hss = 0.1599 : val hss = 0.1517
Fold 3: train tss = 0.8118 : val tss = 0.3335 ::: train hss = 0.2377 : val hss = 0.0762
Fold 4: train tss = 0.7282 : val tss = 0.6434 ::: train hss = 0.1774 : val hss = 0.2371
mean cv TSS: 0.3558
mean cv HSS: 0.1171
644/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.2498 : val tss = 0.0044 ::: train hss = 0.3700 : val hss = 0.0085
Fold 1: train tss = 0.8383 : val tss = 0.2523 ::: train hss = 0.3247 : val hss = 0.1053
Fold 2: train tss = 0.7532 : val tss = 0.6980 ::: train hss = 0.1644 : val hss = 0.3028
Fold 3: train tss = 0.8008 : val tss = 0.2631 ::: train hss = 0.2686 : val hss = 0.1016
Fold 4: train tss = 0.7709 : val tss = 0.6622 ::: train hss = 0.2173 : val hss = 0.2874
mean cv TSS: 0.3760
mean cv HSS: 0.1611
645/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.8082 : val tss = 0.4408 ::: train hss = 0.2678 : val hss = 0.2213
Fold 2: train tss = 0.6898 : val tss = 0.7429 ::: train hss = 0.1058 : val hss = 0.4079
Fold 3: train tss = 0.7148 : val tss = 0.3045 ::: train hss = 0.1775 : val hss = 0.0638
Fold 4: train tss = 0.6418 : val tss = 0.6496 ::: train hss = 0.1304 : val hss = 0.2130
mean cv TSS: 0.4276
mean cv HSS: 0.1812
646/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.3500 : val tss = -0.0012 ::: train hss = 0.5185 : val hss = -0.0023
Fold 1: train tss = 0.7558 : val tss = 0.4015 ::: train hss = 0.1697 : val hss = 0.1187
Fold 2: train tss = 0.6217 : val tss = 0.6231 ::: train hss = 0.0758 : val hss = 0.2058
Fold 3: train tss = 0.6775 : val tss = 0.3794 ::: train hss = 0.1428 : val hss = 0.0512
Fold 4: train tss = 0.7040 : val tss = 0.6296 ::: train hss = 0.1523 : val hss = 0.2035
mean cv TSS: 0.4065
mean cv HSS: 0.1154
647/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.4959 : val tss = 0.0192 ::: train hss = 0.3099 : val hss = 0.0306
Fold 1: train tss = 0.7375 : val tss = 0.3259 ::: train hss = 0.1957 : val hss = 0.1150
Fold 2: train tss = 0.6114 : val tss = 0.5688 ::: train hss = 0.0713 : val hss = 0.1630
Fold 3: train tss = 0.6742 : val tss = 0.3263 ::: train hss = 0.1400 : val hss = 0.0489
Fold 4: train tss = 0.6823 : val tss = 0.6380 ::: train hss = 0.1270 : val hss = 0.2049
mean cv TSS: 0.3757
mean cv HSS: 0.1125
648/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.9325 : val tss = 0.0039 ::: train hss = 0.2027 : val hss = 0.0042
Fold 1: train tss = 0.8210 : val tss = 0.2253 ::: train hss = 0.1790 : val hss = 0.1802
Fold 2: train tss = 0.8056 : val tss = 0.6327 ::: train hss = 0.2192 : val hss = 0.2194
Fold 3: train tss = 0.7464 : val tss = 0.2901 ::: train hss = 0.1768 : val hss = 0.0733
Fold 4: train tss = 0.7550 : val tss = 0.6700 ::: train hss = 0.1882 : val hss = 0.2610
mean cv TSS: 0.3644
mean cv HSS: 0.1476
649/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 78404
Fold 0: train tss = 0.7895 : val tss = 0.0780 ::: train hss = 0.2568 : val hss = 0.0886
Fold 1: train tss = 0.7761 : val tss = 0.4646 ::: train hss = 0.1533 : val hss = 0.2329
Fold 2: train tss = 0.6685 : val tss = 0.6604 ::: train hss = 0.1055 : val hss = 0.2796
Fold 3: train tss = 0.7454 : val tss = 0.3852 ::: train hss = 0.1840 : val hss = 0.0591
Fold 4: train tss = 0.6602 : val tss = 0.5368 ::: train hss = 0.1316 : val hss = 0.1329
mean cv TSS: 0.4250
mean cv HSS: 0.1586
650/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9871 : val tss = 0.0013 ::: train hss = 0.2686 : val hss = 0.0022
Fold 1: train tss = 0.9015 : val tss = 0.3207 ::: train hss = 0.2478 : val hss = 0.1774
Fold 2: train tss = 0.8283 : val tss = 0.6594 ::: train hss = 0.2139 : val hss = 0.2440
Fold 3: train tss = 0.8448 : val tss = 0.3661 ::: train hss = 0.2950 : val hss = 0.0753
Fold 4: train tss = 0.8047 : val tss = 0.6823 ::: train hss = 0.2190 : val hss = 0.2341
mean cv TSS: 0.4059
mean cv HSS: 0.1466
651/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.8421 : val tss = -0.0021 ::: train hss = 0.3270 : val hss = -0.0039
Fold 1: train tss = 0.8609 : val tss = 0.2722 ::: train hss = 0.2776 : val hss = 0.1051
Fold 2: train tss = 0.6603 : val tss = 0.5627 ::: train hss = 0.0883 : val hss = 0.1610
Fold 3: train tss = 0.7684 : val tss = 0.1902 ::: train hss = 0.2197 : val hss = 0.0338
Fold 4: train tss = 0.7590 : val tss = 0.7267 ::: train hss = 0.1886 : val hss = 0.3160
mean cv TSS: 0.3499
mean cv HSS: 0.1224
652/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.8382 : val tss = 0.0113 ::: train hss = 0.2484 : val hss = 0.0144
Fold 1: train tss = 0.7903 : val tss = 0.3613 ::: train hss = 0.1884 : val hss = 0.1500
Fold 2: train tss = 0.7613 : val tss = 0.7019 ::: train hss = 0.1616 : val hss = 0.3174
Fold 3: train tss = 0.7351 : val tss = 0.0374 ::: train hss = 0.1802 : val hss = 0.0060
Fold 4: train tss = 0.7377 : val tss = 0.6456 ::: train hss = 0.1919 : val hss = 0.2045
mean cv TSS: 0.3515
mean cv HSS: 0.1385
653/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.2988 : val tss = 0.0000 ::: train hss = 0.3320 : val hss = 0.0000
Fold 1: train tss = 0.6548 : val tss = 0.4015 ::: train hss = 0.0832 : val hss = 0.1417
Fold 2: train tss = 0.5279 : val tss = 0.6256 ::: train hss = 0.0827 : val hss = 0.2078
Fold 3: train tss = 0.6800 : val tss = 0.3032 ::: train hss = 0.1521 : val hss = 0.0443
Fold 4: train tss = 0.6506 : val tss = 0.6481 ::: train hss = 0.1195 : val hss = 0.2006
mean cv TSS: 0.3957
mean cv HSS: 0.1189
654/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.2500 : val tss = 0.0000 ::: train hss = 0.4000 : val hss = 0.0000
Fold 1: train tss = 0.8507 : val tss = 0.2615 ::: train hss = 0.2866 : val hss = 0.1105
Fold 2: train tss = 0.6801 : val tss = 0.6464 ::: train hss = 0.1149 : val hss = 0.2369
Fold 3: train tss = 0.7345 : val tss = 0.4769 ::: train hss = 0.1914 : val hss = 0.0634
Fold 4: train tss = 0.7689 : val tss = 0.7095 ::: train hss = 0.2167 : val hss = 0.2613
mean cv TSS: 0.4189
mean cv HSS: 0.1344
655/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7826 : val tss = 0.2836 ::: train hss = 0.2821 : val hss = 0.1258
Fold 2: train tss = 0.6418 : val tss = 0.6105 ::: train hss = 0.0866 : val hss = 0.1915
Fold 3: train tss = 0.6815 : val tss = 0.3328 ::: train hss = 0.1400 : val hss = 0.0394
Fold 4: train tss = 0.7343 : val tss = 0.6835 ::: train hss = 0.1744 : val hss = 0.2416
mean cv TSS: 0.3821
mean cv HSS: 0.1196
656/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.8876 : val tss = 0.3262 ::: train hss = 0.2518 : val hss = 0.2460
Fold 1: train tss = 0.8802 : val tss = 0.3818 ::: train hss = 0.2065 : val hss = 0.1118
Fold 2: train tss = 0.8196 : val tss = 0.6485 ::: train hss = 0.2383 : val hss = 0.2552
Fold 3: train tss = 0.7409 : val tss = 0.2251 ::: train hss = 0.1842 : val hss = 0.0851
Fold 4: train tss = 0.7816 : val tss = 0.4875 ::: train hss = 0.2098 : val hss = 0.2380
mean cv TSS: 0.4138
mean cv HSS: 0.1872
657/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.8410 : val tss = -0.0073 ::: train hss = 0.3003 : val hss = -0.0069
Fold 1: train tss = 0.8668 : val tss = 0.1873 ::: train hss = 0.2838 : val hss = 0.0814
Fold 2: train tss = 0.7157 : val tss = 0.7155 ::: train hss = 0.1405 : val hss = 0.3149
Fold 3: train tss = 0.7492 : val tss = 0.2712 ::: train hss = 0.1881 : val hss = 0.0509
Fold 4: train tss = 0.7396 : val tss = 0.6646 ::: train hss = 0.1645 : val hss = 0.2527
mean cv TSS: 0.3663
mean cv HSS: 0.1386
658/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9939 : val tss = -0.0227 ::: train hss = 0.4369 : val hss = -0.0214
Fold 1: train tss = 0.9195 : val tss = 0.2781 ::: train hss = 0.3739 : val hss = 0.0910
Fold 2: train tss = 0.8452 : val tss = 0.6274 ::: train hss = 0.2496 : val hss = 0.2201
Fold 3: train tss = 0.8273 : val tss = 0.3514 ::: train hss = 0.2929 : val hss = 0.0867
Fold 4: train tss = 0.8196 : val tss = 0.4162 ::: train hss = 0.2399 : val hss = 0.1872
mean cv TSS: 0.3301
mean cv HSS: 0.1127
659/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.9868 : val tss = 0.0207 ::: train hss = 0.2631 : val hss = 0.0229
Fold 1: train tss = 0.8627 : val tss = 0.3233 ::: train hss = 0.2841 : val hss = 0.0825
Fold 2: train tss = 0.7223 : val tss = 0.5941 ::: train hss = 0.1138 : val hss = 0.1862
Fold 3: train tss = 0.7959 : val tss = 0.3924 ::: train hss = 0.2481 : val hss = 0.0540
Fold 4: train tss = 0.7625 : val tss = 0.7048 ::: train hss = 0.1902 : val hss = 0.2666
mean cv TSS: 0.4071
mean cv HSS: 0.1224
660/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 104260
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.8705 : val tss = 0.1907 ::: train hss = 0.3169 : val hss = 0.0754
Fold 2: train tss = 0.6875 : val tss = 0.7052 ::: train hss = 0.1224 : val hss = 0.3272
Fold 3: train tss = 0.7328 : val tss = 0.4447 ::: train hss = 0.1793 : val hss = 0.0634
Fold 4: train tss = 0.7465 : val tss = 0.6374 ::: train hss = 0.1872 : val hss = 0.2161
mean cv TSS: 0.3956
mean cv HSS: 0.1364
661/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7867 : val tss = 0.3069 ::: train hss = 0.1818 : val hss = 0.1443
Fold 2: train tss = 0.7269 : val tss = 0.7441 ::: train hss = 0.1662 : val hss = 0.3412
Fold 3: train tss = 0.7062 : val tss = 0.3385 ::: train hss = 0.1948 : val hss = 0.0696
Fold 4: train tss = 0.7026 : val tss = 0.6228 ::: train hss = 0.1641 : val hss = 0.2788
mean cv TSS: 0.4025
mean cv HSS: 0.1668
662/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.2999 : val tss = -0.0001 ::: train hss = 0.4443 : val hss = -0.0002
Fold 1: train tss = 0.7526 : val tss = 0.3311 ::: train hss = 0.2025 : val hss = 0.1141
Fold 2: train tss = 0.7341 : val tss = 0.6874 ::: train hss = 0.1340 : val hss = 0.2749
Fold 3: train tss = 0.7217 : val tss = 0.4304 ::: train hss = 0.1832 : val hss = 0.0597
Fold 4: train tss = 0.7306 : val tss = 0.6161 ::: train hss = 0.1627 : val hss = 0.1926
mean cv TSS: 0.4130
mean cv HSS: 0.1282
663/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.4943 : val tss = 0.0129 ::: train hss = 0.2568 : val hss = 0.0198
Fold 1: train tss = 0.7769 : val tss = 0.3969 ::: train hss = 0.1787 : val hss = 0.1234
Fold 2: train tss = 0.5788 : val tss = 0.5024 ::: train hss = 0.0614 : val hss = 0.1302
Fold 3: train tss = 0.6677 : val tss = 0.4116 ::: train hss = 0.1462 : val hss = 0.0569
Fold 4: train tss = 0.6058 : val tss = 0.5115 ::: train hss = 0.0928 : val hss = 0.1261
mean cv TSS: 0.3670
mean cv HSS: 0.0913
664/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.7890 : val tss = -0.0244 ::: train hss = 0.2485 : val hss = -0.0134
Fold 1: train tss = 0.8682 : val tss = 0.2416 ::: train hss = 0.2892 : val hss = 0.2564
Fold 2: train tss = 0.7948 : val tss = 0.5959 ::: train hss = 0.2149 : val hss = 0.2121
Fold 3: train tss = 0.7516 : val tss = 0.3813 ::: train hss = 0.1916 : val hss = 0.0476
Fold 4: train tss = 0.6858 : val tss = 0.5421 ::: train hss = 0.1524 : val hss = 0.1354
mean cv TSS: 0.3473
mean cv HSS: 0.1276
665/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.7400 : val tss = -0.0083 ::: train hss = 0.2508 : val hss = -0.0124
Fold 1: train tss = 0.8461 : val tss = 0.3505 ::: train hss = 0.2428 : val hss = 0.1304
Fold 2: train tss = 0.6881 : val tss = 0.5858 ::: train hss = 0.1087 : val hss = 0.1788
Fold 3: train tss = 0.7045 : val tss = 0.2727 ::: train hss = 0.1574 : val hss = 0.0459
Fold 4: train tss = 0.6836 : val tss = 0.5653 ::: train hss = 0.1327 : val hss = 0.1597
mean cv TSS: 0.3532
mean cv HSS: 0.1005
666/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9901 : val tss = 0.0000 ::: train hss = 0.3246 : val hss = 0.0000
Fold 1: train tss = 0.9368 : val tss = 0.2936 ::: train hss = 0.3299 : val hss = 0.1029
Fold 2: train tss = 0.7627 : val tss = 0.5972 ::: train hss = 0.1807 : val hss = 0.1818
Fold 3: train tss = 0.8058 : val tss = 0.2991 ::: train hss = 0.2337 : val hss = 0.0500
Fold 4: train tss = 0.7674 : val tss = 0.6845 ::: train hss = 0.2189 : val hss = 0.2404
mean cv TSS: 0.3749
mean cv HSS: 0.1150
667/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.6455 : val tss = -0.0018 ::: train hss = 0.3689 : val hss = -0.0034
Fold 1: train tss = 0.7853 : val tss = 0.3683 ::: train hss = 0.1866 : val hss = 0.0987
Fold 2: train tss = 0.6685 : val tss = 0.6141 ::: train hss = 0.0985 : val hss = 0.1947
Fold 3: train tss = 0.8013 : val tss = 0.3742 ::: train hss = 0.2436 : val hss = 0.0715
Fold 4: train tss = 0.7553 : val tss = 0.6247 ::: train hss = 0.2078 : val hss = 0.2075
mean cv TSS: 0.3959
mean cv HSS: 0.1138
668/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.3481 : val tss = -0.0036 ::: train hss = 0.3238 : val hss = -0.0062
Fold 1: train tss = 0.7885 : val tss = 0.3965 ::: train hss = 0.1595 : val hss = 0.1908
Fold 2: train tss = 0.5961 : val tss = 0.6463 ::: train hss = 0.0787 : val hss = 0.2410
Fold 3: train tss = 0.7642 : val tss = 0.4591 ::: train hss = 0.2180 : val hss = 0.0840
Fold 4: train tss = 0.7233 : val tss = 0.6751 ::: train hss = 0.1847 : val hss = 0.2360
mean cv TSS: 0.4347
mean cv HSS: 0.1491
669/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.0999 : val tss = 0.0000 ::: train hss = 0.1737 : val hss = 0.0000
Fold 1: train tss = 0.7235 : val tss = 0.3581 ::: train hss = 0.1111 : val hss = 0.2196
Fold 2: train tss = 0.7247 : val tss = 0.7736 ::: train hss = 0.1654 : val hss = 0.4224
Fold 3: train tss = 0.6464 : val tss = 0.5696 ::: train hss = 0.1344 : val hss = 0.0672
Fold 4: train tss = 0.6862 : val tss = 0.6505 ::: train hss = 0.1486 : val hss = 0.2049
mean cv TSS: 0.4704
mean cv HSS: 0.1828
670/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.2992 : val tss = -0.0014 ::: train hss = 0.3626 : val hss = -0.0026
Fold 1: train tss = 0.8842 : val tss = 0.2421 ::: train hss = 0.3431 : val hss = 0.1011
Fold 2: train tss = 0.7954 : val tss = 0.6544 ::: train hss = 0.1840 : val hss = 0.3147
Fold 3: train tss = 0.7418 : val tss = 0.4746 ::: train hss = 0.1895 : val hss = 0.0720
Fold 4: train tss = 0.7655 : val tss = 0.6777 ::: train hss = 0.2123 : val hss = 0.2406
mean cv TSS: 0.4095
mean cv HSS: 0.1452
671/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.2500 : val tss = -0.0002 ::: train hss = 0.4000 : val hss = -0.0005

Fold 1: train tss = 0.7340 : val tss = 0.4547 ::: train hss = 0.1882 : val hss = 0.0617
Fold 2: train tss = 0.6173 : val tss = 0.4561 ::: train hss = 0.0908 : val hss = 0.1095
Fold 3: train tss = 0.6662 : val tss = 0.6305 ::: train hss = 0.1302 : val hss = 0.0473
Fold 4: train tss = 0.6889 : val tss = 0.5649 ::: train hss = 0.1549 : val hss = 0.1541
mean cv TSS: 0.4212
mean cv HSS: 0.0744
672/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.9741 : val tss = 0.0773 ::: train hss = 0.1528 : val hss = 0.0863
Fold 1: train tss = 0.8998 : val tss = 0.1385 ::: train hss = 0.3586 : val hss = 0.0747
Fold 2: train tss = 0.8016 : val tss = 0.6873 ::: train hss = 0.2180 : val hss = 0.3139
Fold 3: train tss = 0.7285 : val tss = 0.1594 ::: train hss = 0.1627 : val hss = 0.0262
Fold 4: train tss = 0.7976 : val tss = 0.5881 ::: train hss = 0.2182 : val hss = 0.2497
mean cv TSS: 0.3301
mean cv HSS: 0.1502
673/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.8735 : val tss = -0.0091 ::: train hss = 0.1354 : val hss = -0.0115
Fold 1: train tss = 0.7963 : val tss = 0.3419 ::: train hss = 0.2006 : val hss = 0.1456
Fold 2: train tss = 0.6456 : val tss = 0.5937 ::: train hss = 0.0910 : val hss = 0.2210
Fold 3: train tss = 0.7175 : val tss = 0.1255 ::: train hss = 0.1607 : val hss = 0.0382
Fold 4: train tss = 0.7293 : val tss = 0.6110 ::: train hss = 0.1671 : val hss = 0.2432
mean cv TSS: 0.3326
mean cv HSS: 0.1273
674/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.9906 : val tss = -0.0168 ::: train hss = 0.3358 : val hss = -0.0178
Fold 1: train tss = 0.8966 : val tss = 0.3322 ::: train hss = 0.3413 : val hss = 0.1250
Fold 2: train tss = 0.8248 : val tss = 0.7169 ::: train hss = 0.1994 : val hss = 0.3103
Fold 3: train tss = 0.8149 : val tss = 0.2816 ::: train hss = 0.2447 : val hss = 0.0783
Fold 4: train tss = 0.8370 : val tss = 0.5074 ::: train hss = 0.2720 : val hss = 0.2326
mean cv TSS: 0.3643
mean cv HSS: 0.1457
675/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.9793 : val tss = -0.0033 ::: train hss = 0.1848 : val hss = -0.0059
Fold 1: train tss = 0.8316 : val tss = 0.2937 ::: train hss = 0.2774 : val hss = 0.1064
Fold 2: train tss = 0.7025 : val tss = 0.5552 ::: train hss = 0.1052 : val hss = 0.1552
Fold 3: train tss = 0.7697 : val tss = 0.2352 ::: train hss = 0.1995 : val hss = 0.0416
Fold 4: train tss = 0.7719 : val tss = 0.5630 ::: train hss = 0.2060 : val hss = 0.1483
mean cv TSS: 0.3288
mean cv HSS: 0.0892
676/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.1000 : val tss = -0.0014 ::: train hss = 0.1818 : val hss = -0.0026
Fold 1: train tss = 0.8097 : val tss = 0.3716 ::: train hss = 0.2736 : val hss = 0.1636
Fold 2: train tss = 0.7524 : val tss = 0.7144 ::: train hss = 0.1559 : val hss = 0.3133
Fold 3: train tss = 0.7877 : val tss = 0.0306 ::: train hss = 0.2396 : val hss = 0.0090
Fold 4: train tss = 0.7417 : val tss = 0.6901 ::: train hss = 0.1794 : val hss = 0.2696
mean cv TSS: 0.3611
mean cv HSS: 0.1506
677/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = -0.0004 ::: train hss = 0.0952 : val hss = -0.0007
Fold 1: train tss = 0.7834 : val tss = 0.4164 ::: train hss = 0.1907 : val hss = 0.1527
Fold 2: train tss = 0.5833 : val tss = 0.5437 ::: train hss = 0.0891 : val hss = 0.1612
Fold 3: train tss = 0.7091 : val tss = 0.1428 ::: train hss = 0.1704 : val hss = 0.0267
Fold 4: train tss = 0.7011 : val tss = 0.5085 ::: train hss = 0.1445 : val hss = 0.1325
mean cv TSS: 0.3222
mean cv HSS: 0.0945
678/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.3461 : val tss = 0.0031 ::: train hss = 0.2347 : val hss = 0.0047
Fold 1: train tss = 0.7698 : val tss = 0.3556 ::: train hss = 0.1958 : val hss = 0.1172
Fold 2: train tss = 0.6501 : val tss = 0.6056 ::: train hss = 0.0852 : val hss = 0.1894
Fold 3: train tss = 0.6244 : val tss = 0.4250 ::: train hss = 0.1101 : val hss = 0.0435
Fold 4: train tss = 0.6541 : val tss = 0.5860 ::: train hss = 0.1182 : val hss = 0.1683
mean cv TSS: 0.3951
mean cv HSS: 0.1046
679/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.1475 : val tss = -0.0049 ::: train hss = 0.1341 : val hss = -0.0082
Fold 1: train tss = 0.7335 : val tss = 0.4215 ::: train hss = 0.1230 : val hss = 0.1096
Fold 2: train tss = 0.5424 : val tss = 0.5905 ::: train hss = 0.0507 : val hss = 0.1825
Fold 3: train tss = 0.6159 : val tss = 0.2667 ::: train hss = 0.1146 : val hss = 0.0355
Fold 4: train tss = 0.6744 : val tss = 0.5815 ::: train hss = 0.1241 : val hss = 0.1643
mean cv TSS: 0.3711
mean cv HSS: 0.0967
680/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.6843 : val tss = 0.0575 ::: train hss = 0.1669 : val hss = 0.0528
Fold 1: train tss = 0.7946 : val tss = 0.3374 ::: train hss = 0.2370 : val hss = 0.1815
Fold 2: train tss = 0.7716 : val tss = 0.6091 ::: train hss = 0.2226 : val hss = 0.2333
Fold 3: train tss = 0.7251 : val tss = 0.2133 ::: train hss = 0.1767 : val hss = 0.0418
Fold 4: train tss = 0.6985 : val tss = 0.6002 ::: train hss = 0.1374 : val hss = 0.1737
mean cv TSS: 0.3635
mean cv HSS: 0.1366
681/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.6373 : val tss = -0.0042 ::: train hss = 0.1847 : val hss = -0.0072
Fold 1: train tss = 0.7730 : val tss = 0.4590 ::: train hss = 0.2122 : val hss = 0.2555
Fold 2: train tss = 0.7109 : val tss = 0.5359 ::: train hss = 0.1235 : val hss = 0.1495
Fold 3: train tss = 0.6511 : val tss = 0.3093 ::: train hss = 0.1389 : val hss = 0.0864
Fold 4: train tss = 0.5894 : val tss = 0.6602 ::: train hss = 0.0926 : val hss = 0.2268
mean cv TSS: 0.3920
mean cv HSS: 0.1422
682/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 171357
Fold 0: train tss = 0.9942 : val tss = 0.0000 ::: train hss = 0.4519 : val hss = 0.0000
Fold 1: train tss = 0.8669 : val tss = 0.2946 ::: train hss = 0.2129 : val hss = 0.1128
Fold 2: train tss = 0.7841 : val tss = 0.6699 ::: train hss = 0.1584 : val hss = 0.2622
Fold 3: train tss = 0.7799 : val tss = 0.3087 ::: train hss = 0.2043 : val hss = 0.0857
Fold 4: train tss = 0.7801 : val tss = 0.6835 ::: train hss = 0.2119 : val hss = 0.2406
mean cv TSS: 0.3914
mean cv HSS: 0.1403
683/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.9848 : val tss = 0.0000 ::: train hss = 0.2373 : val hss = 0.0000
Fold 1: train tss = 0.8407 : val tss = 0.3253 ::: train hss = 0.2970 : val hss = 0.1814
Fold 2: train tss = 0.6568 : val tss = 0.5375 ::: train hss = 0.0924 : val hss = 0.1479
Fold 3: train tss = 0.7419 : val tss = 0.3968 ::: train hss = 0.2107 : val hss = 0.0391
Fold 4: train tss = 0.7157 : val tss = 0.5772 ::: train hss = 0.1581 : val hss = 0.1583
mean cv TSS: 0.3673
mean cv HSS: 0.1053
684/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 78404
Fold 0: train tss = 0.3452 : val tss = 0.0308 ::: train hss = 0.2061 : val hss = 0.0439
Fold 1: train tss = 0.8002 : val tss = 0.3080 ::: train hss = 0.1710 : val hss = 0.1810
Fold 2: train tss = 0.6389 : val tss = 0.6390 ::: train hss = 0.1030 : val hss = 0.2168
Fold 3: train tss = 0.6670 : val tss = 0.0877 ::: train hss = 0.1513 : val hss = 0.0119
Fold 4: train tss = 0.7043 : val tss = 0.6061 ::: train hss = 0.1580 : val hss = 0.1907
mean cv TSS: 0.3343
mean cv HSS: 0.1289
685/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 78404
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.6426 : val tss = 0.3808 ::: train hss = 0.0641 : val hss = 0.0725
Fold 2: train tss = 0.6115 : val tss = 0.6822 ::: train hss = 0.0853 : val hss = 0.2809
Fold 3: train tss = 0.6168 : val tss = 0.3036 ::: train hss = 0.1093 : val hss = 0.0424
Fold 4: train tss = 0.6235 : val tss = 0.6513 ::: train hss = 0.1176 : val hss = 0.2072
mean cv TSS: 0.4036
mean cv HSS: 0.1206
686/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 171357
Fold 0: train tss = 0.4478 : val tss = 0.0261 ::: train hss = 0.3811 : val hss = 0.0376
Fold 1: train tss = 0.7770 : val tss = 0.2810 ::: train hss = 0.2940 : val hss = 0.0990
Fold 2: train tss = 0.7477 : val tss = 0.6381 ::: train hss = 0.1448 : val hss = 0.2606
Fold 3: train tss = 0.7371 : val tss = 0.3640 ::: train hss = 0.1856 : val hss = 0.0549
Fold 4: train tss = 0.7443 : val tss = 0.7095 ::: train hss = 0.2016 : val hss = 0.2843
mean cv TSS: 0.4037
mean cv HSS: 0.1473
687/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 171357
Fold 0: train tss = 0.0988 : val tss = 0.0138 ::: train hss = 0.1235 : val hss = 0.0261
Fold 1: train tss = 0.7798 : val tss = 0.2859 ::: train hss = 0.2559 : val hss = 0.1260
Fold 2: train tss = 0.6526 : val tss = 0.6413 ::: train hss = 0.0862 : val hss = 0.2313
Fold 3: train tss = 0.7407 : val tss = 0.2435 ::: train hss = 0.2019 : val hss = 0.0522
Fold 4: train tss = 0.7451 : val tss = 0.6220 ::: train hss = 0.1835 : val hss = 0.1899
mean cv TSS: 0.3613
mean cv HSS: 0.1251
688/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.7835 : val tss = 0.2563 ::: train hss = 0.1812 : val hss = 0.1977
Fold 1: train tss = 0.8898 : val tss = 0.1303 ::: train hss = 0.3090 : val hss = 0.0453
Fold 2: train tss = 0.7869 : val tss = 0.6950 ::: train hss = 0.1722 : val hss = 0.3638
Fold 3: train tss = 0.7480 : val tss = 0.0743 ::: train hss = 0.1846 : val hss = 0.0236
Fold 4: train tss = 0.7564 : val tss = 0.6732 ::: train hss = 0.2081 : val hss = 0.2230
mean cv TSS: 0.3658
mean cv HSS: 0.1707
689/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0002 : val hss = 0.0000
Fold 1: train tss = 0.8605 : val tss = 0.1637 ::: train hss = 0.2370 : val hss = 0.0686
Fold 2: train tss = 0.7785 : val tss = 0.6182 ::: train hss = 0.1846 : val hss = 0.2513
Fold 3: train tss = 0.7204 : val tss = 0.2828 ::: train hss = 0.1850 : val hss = 0.0669
Fold 4: train tss = 0.6858 : val tss = 0.5066 ::: train hss = 0.1404 : val hss = 0.2270
mean cv TSS: 0.3143
mean cv HSS: 0.1228
690/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9876 : val tss = 0.0287 ::: train hss = 0.2763 : val hss = 0.0447
Fold 1: train tss = 0.9280 : val tss = 0.2854 ::: train hss = 0.3497 : val hss = 0.1010
Fold 2: train tss = 0.8243 : val tss = 0.6629 ::: train hss = 0.1965 : val hss = 0.2757
Fold 3: train tss = 0.8249 : val tss = 0.2355 ::: train hss = 0.2576 : val hss = 0.1224
Fold 4: train tss = 0.8080 : val tss = 0.7139 ::: train hss = 0.2366 : val hss = 0.3216
mean cv TSS: 0.3853
mean cv HSS: 0.1731
691/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.9870 : val tss = -0.0012 ::: train hss = 0.2668 : val hss = -0.0023
Fold 1: train tss = 0.8826 : val tss = 0.2416 ::: train hss = 0.2034 : val hss = 0.1006
Fold 2: train tss = 0.7013 : val tss = 0.6352 ::: train hss = 0.1090 : val hss = 0.2406
Fold 3: train tss = 0.8125 : val tss = 0.2745 ::: train hss = 0.2554 : val hss = 0.0712
Fold 4: train tss = 0.7738 : val tss = 0.6733 ::: train hss = 0.2075 : val hss = 0.2443
mean cv TSS: 0.3647
mean cv HSS: 0.1309
692/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.1000 : val tss = -0.0009 ::: train hss = 0.1818 : val hss = -0.0017
Fold 1: train tss = 0.8306 : val tss = 0.3244 ::: train hss = 0.2233 : val hss = 0.1380
Fold 2: train tss = 0.7651 : val tss = 0.7229 ::: train hss = 0.1654 : val hss = 0.3135
Fold 3: train tss = 0.7720 : val tss = 0.2515 ::: train hss = 0.2189 : val hss = 0.0681
Fold 4: train tss = 0.7155 : val tss = 0.7144 ::: train hss = 0.1752 : val hss = 0.3237
mean cv TSS: 0.4025
mean cv HSS: 0.1683
693/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 104260
Fold 0: train tss = 0.0500 : val tss = 0.0046 ::: train hss = 0.0952 : val hss = 0.0090
Fold 1: train tss = 0.7891 : val tss = 0.3320 ::: train hss = 0.2118 : val hss = 0.1679
Fold 2: train tss = 0.5969 : val tss = 0.6364 ::: train hss = 0.0869 : val hss = 0.2131
Fold 3: train tss = 0.6703 : val tss = 0.3319 ::: train hss = 0.1360 : val hss = 0.0465
Fold 4: train tss = 0.6687 : val tss = 0.6190 ::: train hss = 0.1341 : val hss = 0.2012
mean cv TSS: 0.3848
mean cv HSS: 0.1276
694/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.3483 : val tss = -0.0030 ::: train hss = 0.3398 : val hss = -0.0053
Fold 1: train tss = 0.7750 : val tss = 0.2991 ::: train hss = 0.1754 : val hss = 0.0887
Fold 2: train tss = 0.5939 : val tss = 0.6035 ::: train hss = 0.0678 : val hss = 0.1921
Fold 3: train tss = 0.6432 : val tss = 0.3251 ::: train hss = 0.1226 : val hss = 0.0403
Fold 4: train tss = 0.7191 : val tss = 0.6909 ::: train hss = 0.1734 : val hss = 0.2621
mean cv TSS: 0.3831
mean cv HSS: 0.1156
695/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.1492 : val tss = 0.0090 ::: train hss = 0.1989 : val hss = 0.0171
Fold 1: train tss = 0.7310 : val tss = 0.4732 ::: train hss = 0.1242 : val hss = 0.1261
Fold 2: train tss = 0.6038 : val tss = 0.6140 ::: train hss = 0.0690 : val hss = 0.1946
Fold 3: train tss = 0.6791 : val tss = 0.4289 ::: train hss = 0.1447 : val hss = 0.0590
Fold 4: train tss = 0.6497 : val tss = 0.6404 ::: train hss = 0.1121 : val hss = 0.2042
mean cv TSS: 0.4331
mean cv HSS: 0.1202
696/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.5916 : val tss = -0.0359 ::: train hss = 0.2320 : val hss = -0.0175
Fold 1: train tss = 0.7868 : val tss = 0.3356 ::: train hss = 0.1383 : val hss = 0.0789
Fold 2: train tss = 0.7782 : val tss = 0.6945 ::: train hss = 0.1765 : val hss = 0.3091
Fold 3: train tss = 0.7489 : val tss = 0.0841 ::: train hss = 0.1866 : val hss = 0.0473
Fold 4: train tss = 0.7018 : val tss = 0.5915 ::: train hss = 0.1604 : val hss = 0.1701
mean cv TSS: 0.3340
mean cv HSS: 0.1176
697/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.8854 : val tss = 0.2117 ::: train hss = 0.2227 : val hss = 0.1259
Fold 1: train tss = 0.6921 : val tss = 0.3377 ::: train hss = 0.1040 : val hss = 0.1461
Fold 2: train tss = 0.7295 : val tss = 0.6473 ::: train hss = 0.1544 : val hss = 0.2420
Fold 3: train tss = 0.6122 : val tss = 0.2774 ::: train hss = 0.1179 : val hss = 0.0327
Fold 4: train tss = 0.6873 : val tss = 0.5342 ::: train hss = 0.1545 : val hss = 0.1536
mean cv TSS: 0.4017
mean cv HSS: 0.1401
698/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.9942 : val tss = 0.0979 ::: train hss = 0.4519 : val hss = 0.1682
Fold 1: train tss = 0.8603 : val tss = 0.2804 ::: train hss = 0.2074 : val hss = 0.1174
Fold 2: train tss = 0.8355 : val tss = 0.6651 ::: train hss = 0.2256 : val hss = 0.2810
Fold 3: train tss = 0.8171 : val tss = 0.2890 ::: train hss = 0.2589 : val hss = 0.0619
Fold 4: train tss = 0.7631 : val tss = 0.7418 ::: train hss = 0.2209 : val hss = 0.3054
mean cv TSS: 0.4149
mean cv HSS: 0.1868
699/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.9381 : val tss = -0.0004 ::: train hss = 0.2719 : val hss = -0.0007
Fold 1: train tss = 0.7592 : val tss = 0.2831 ::: train hss = 0.2423 : val hss = 0.1361
Fold 2: train tss = 0.6821 : val tss = 0.5447 ::: train hss = 0.0966 : val hss = 0.1548
Fold 3: train tss = 0.7714 : val tss = 0.3190 ::: train hss = 0.2054 : val hss = 0.0538
Fold 4: train tss = 0.7062 : val tss = 0.5807 ::: train hss = 0.1658 : val hss = 0.1603
mean cv TSS: 0.3454
mean cv HSS: 0.1009
700/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 104260
Fold 0: train tss = 0.5461 : val tss = 0.0015 ::: train hss = 0.3468 : val hss = 0.0019
Fold 1: train tss = 0.8066 : val tss = 0.2465 ::: train hss = 0.2361 : val hss = 0.1250
Fold 2: train tss = 0.5953 : val tss = 0.6413 ::: train hss = 0.0829 : val hss = 0.2373
Fold 3: train tss = 0.6844 : val tss = 0.3269 ::: train hss = 0.1432 : val hss = 0.0409
Fold 4: train tss = 0.6728 : val tss = 0.6364 ::: train hss = 0.1317 : val hss = 0.2061
mean cv TSS: 0.3705
mean cv HSS: 0.1222
701/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 104260
Fold 0: train tss = 0.2967 : val tss = 0.0133 ::: train hss = 0.2240 : val hss = 0.0247
Fold 1: train tss = 0.7628 : val tss = 0.4034 ::: train hss = 0.2072 : val hss = 0.1437
Fold 2: train tss = 0.5746 : val tss = 0.5559 ::: train hss = 0.0962 : val hss = 0.1556
Fold 3: train tss = 0.6361 : val tss = 0.4254 ::: train hss = 0.1197 : val hss = 0.0506
Fold 4: train tss = 0.6313 : val tss = 0.6132 ::: train hss = 0.1088 : val hss = 0.1766
mean cv TSS: 0.4022
mean cv HSS: 0.1102
702/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 228189
Fold 0: train tss = 0.3477 : val tss = -0.0021 ::: train hss = 0.3024 : val hss = -0.0039
Fold 1: train tss = 0.8129 : val tss = 0.3194 ::: train hss = 0.3492 : val hss = 0.1129
Fold 2: train tss = 0.7576 : val tss = 0.6697 ::: train hss = 0.1508 : val hss = 0.2837
Fold 3: train tss = 0.7551 : val tss = 0.3380 ::: train hss = 0.2006 : val hss = 0.0647
Fold 4: train tss = 0.7033 : val tss = 0.6734 ::: train hss = 0.1429 : val hss = 0.2421
mean cv TSS: 0.3997
mean cv HSS: 0.1399
703/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 8, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 228189
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7767 : val tss = 0.2878 ::: train hss = 0.2019 : val hss = 0.1186
Fold 2: train tss = 0.6250 : val tss = 0.6035 ::: train hss = 0.0792 : val hss = 0.1929
Fold 3: train tss = 0.7090 : val tss = 0.2967 ::: train hss = 0.1598 : val hss = 0.0463
Fold 4: train tss = 0.6943 : val tss = 0.6748 ::: train hss = 0.1416 : val hss = 0.2326
mean cv TSS: 0.3726
mean cv HSS: 0.1181
704/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 109820
Fold 0: train tss = 0.9871 : val tss = 0.1315 ::: train hss = 0.2686 : val hss = 0.1582
Fold 1: train tss = 0.9170 : val tss = 0.1628 ::: train hss = 0.2993 : val hss = 0.1130
Fold 2: train tss = 0.7865 : val tss = 0.6616 ::: train hss = 0.1700 : val hss = 0.3388
Fold 3: train tss = 0.8115 : val tss = 0.0565 ::: train hss = 0.2625 : val hss = 0.0201
Fold 4: train tss = 0.7595 : val tss = 0.6510 ::: train hss = 0.1956 : val hss = 0.2228
mean cv TSS: 0.3327
mean cv HSS: 0.1706
705/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.8776 : val tss = -0.0029 ::: train hss = 0.1567 : val hss = -0.0037
Fold 1: train tss = 0.8772 : val tss = 0.2308 ::: train hss = 0.2618 : val hss = 0.1211
Fold 2: train tss = 0.7810 : val tss = 0.7178 ::: train hss = 0.2010 : val hss = 0.3539
Fold 3: train tss = 0.7343 : val tss = 0.3077 ::: train hss = 0.1766 : val hss = 0.0774
Fold 4: train tss = 0.6814 : val tss = 0.5983 ::: train hss = 0.1324 : val hss = 0.1705
mean cv TSS: 0.3704
mean cv HSS: 0.1438
706/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9957 : val tss = 0.0845 ::: train hss = 0.5240 : val hss = 0.0990
Fold 1: train tss = 0.9205 : val tss = 0.2406 ::: train hss = 0.2814 : val hss = 0.1056
Fold 2: train tss = 0.8714 : val tss = 0.7190 ::: train hss = 0.2697 : val hss = 0.2981
Fold 3: train tss = 0.8333 : val tss = 0.2430 ::: train hss = 0.2739 : val hss = 0.1478
Fold 4: train tss = 0.8437 : val tss = 0.6951 ::: train hss = 0.2980 : val hss = 0.2517
mean cv TSS: 0.3965
mean cv HSS: 0.1804
707/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9906 : val tss = -0.0052 ::: train hss = 0.3358 : val hss = -0.0086
Fold 1: train tss = 0.9019 : val tss = 0.2513 ::: train hss = 0.3254 : val hss = 0.1005
Fold 2: train tss = 0.7309 : val tss = 0.5939 ::: train hss = 0.1198 : val hss = 0.2094
Fold 3: train tss = 0.8152 : val tss = 0.2860 ::: train hss = 0.2479 : val hss = 0.0643
Fold 4: train tss = 0.7726 : val tss = 0.6612 ::: train hss = 0.2039 : val hss = 0.2417
mean cv TSS: 0.3574
mean cv HSS: 0.1215
708/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.1500 : val tss = -0.0002 ::: train hss = 0.2609 : val hss = -0.0005
Fold 1: train tss = 0.9032 : val tss = 0.3597 ::: train hss = 0.3316 : val hss = 0.1634
Fold 2: train tss = 0.7948 : val tss = 0.7018 ::: train hss = 0.2023 : val hss = 0.4197
Fold 3: train tss = 0.7825 : val tss = 0.3614 ::: train hss = 0.2337 : val hss = 0.0566
Fold 4: train tss = 0.7971 : val tss = 0.6498 ::: train hss = 0.2286 : val hss = 0.2390
mean cv TSS: 0.4145
mean cv HSS: 0.1756
709/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0998 : val tss = 0.0088 ::: train hss = 0.1663 : val hss = 0.0168
Fold 1: train tss = 0.8387 : val tss = 0.2675 ::: train hss = 0.2726 : val hss = 0.1772
Fold 2: train tss = 0.6993 : val tss = 0.7035 ::: train hss = 0.1309 : val hss = 0.3591
Fold 3: train tss = 0.6912 : val tss = 0.1156 ::: train hss = 0.1598 : val hss = 0.0164
Fold 4: train tss = 0.6883 : val tss = 0.6120 ::: train hss = 0.1628 : val hss = 0.1820
mean cv TSS: 0.3415
mean cv HSS: 0.1503
710/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.3482 : val tss = -0.0007 ::: train hss = 0.3316 : val hss = -0.0014
Fold 1: train tss = 0.7821 : val tss = 0.3050 ::: train hss = 0.2641 : val hss = 0.0995
Fold 2: train tss = 0.7816 : val tss = 0.6509 ::: train hss = 0.1683 : val hss = 0.2422
Fold 3: train tss = 0.7008 : val tss = 0.3717 ::: train hss = 0.1598 : val hss = 0.0483
Fold 4: train tss = 0.7501 : val tss = 0.6778 ::: train hss = 0.1891 : val hss = 0.2429
mean cv TSS: 0.4009
mean cv HSS: 0.1263
711/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.2976 : val tss = -0.0011 ::: train hss = 0.2588 : val hss = -0.0021
Fold 1: train tss = 0.7925 : val tss = 0.3524 ::: train hss = 0.1780 : val hss = 0.1113
Fold 2: train tss = 0.5884 : val tss = 0.6117 ::: train hss = 0.0630 : val hss = 0.1930
Fold 3: train tss = 0.7044 : val tss = 0.2407 ::: train hss = 0.1582 : val hss = 0.0308
Fold 4: train tss = 0.7220 : val tss = 0.6153 ::: train hss = 0.1597 : val hss = 0.1875
mean cv TSS: 0.3638
mean cv HSS: 0.1041
712/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.9754 : val tss = 0.0040 ::: train hss = 0.1599 : val hss = 0.0048
Fold 1: train tss = 0.8314 : val tss = 0.2322 ::: train hss = 0.1703 : val hss = 0.1438
Fold 2: train tss = 0.8130 : val tss = 0.6630 ::: train hss = 0.2054 : val hss = 0.3185
Fold 3: train tss = 0.6866 : val tss = 0.2537 ::: train hss = 0.1381 : val hss = 0.0642
Fold 4: train tss = 0.7339 : val tss = 0.5811 ::: train hss = 0.1912 : val hss = 0.1858
mean cv TSS: 0.3468
mean cv HSS: 0.1434
713/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.9358 : val tss = 0.3241 ::: train hss = 0.2384 : val hss = 0.2369
Fold 1: train tss = 0.6881 : val tss = 0.2559 ::: train hss = 0.0899 : val hss = 0.2042
Fold 2: train tss = 0.6890 : val tss = 0.6353 ::: train hss = 0.1205 : val hss = 0.2367
Fold 3: train tss = 0.6715 : val tss = 0.3024 ::: train hss = 0.1445 : val hss = 0.0383
Fold 4: train tss = 0.6548 : val tss = 0.6292 ::: train hss = 0.1329 : val hss = 0.2189
mean cv TSS: 0.4294
mean cv HSS: 0.1870
714/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9922 : val tss = -0.0097 ::: train hss = 0.3780 : val hss = -0.0140
Fold 1: train tss = 0.9288 : val tss = 0.3263 ::: train hss = 0.4400 : val hss = 0.1212
Fold 2: train tss = 0.8151 : val tss = 0.6388 ::: train hss = 0.2062 : val hss = 0.2442
Fold 3: train tss = 0.8276 : val tss = 0.2747 ::: train hss = 0.2894 : val hss = 0.0782
Fold 4: train tss = 0.7676 : val tss = 0.6119 ::: train hss = 0.2056 : val hss = 0.1775
mean cv TSS: 0.3684
mean cv HSS: 0.1214
715/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9928 : val tss = -0.0011 ::: train hss = 0.3971 : val hss = -0.0021

Fold 1: train tss = 0.8660 : val tss = 0.2466 ::: train hss = 0.2409 : val hss = 0.1312
Fold 2: train tss = 0.7088 : val tss = 0.6159 ::: train hss = 0.1035 : val hss = 0.2050
Fold 3: train tss = 0.7480 : val tss = 0.2840 ::: train hss = 0.1870 : val hss = 0.0513
Fold 4: train tss = 0.7664 : val tss = 0.6751 ::: train hss = 0.1878 : val hss = 0.2339
mean cv TSS: 0.3641
mean cv HSS: 0.1239
716/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.7952 : val tss = 0.0391 ::: train hss = 0.4185 : val hss = 0.0414
Fold 1: train tss = 0.8755 : val tss = 0.1621 ::: train hss = 0.2700 : val hss = 0.1797
Fold 2: train tss = 0.7688 : val tss = 0.7276 ::: train hss = 0.1928 : val hss = 0.3537
Fold 3: train tss = 0.7482 : val tss = 0.4509 ::: train hss = 0.1910 : val hss = 0.0605
Fold 4: train tss = 0.7551 : val tss = 0.6922 ::: train hss = 0.1876 : val hss = 0.2574
mean cv TSS: 0.4144
mean cv HSS: 0.1785
717/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.7725 : val tss = 0.3884 ::: train hss = 0.1929 : val hss = 0.1168
Fold 2: train tss = 0.6221 : val tss = 0.6326 ::: train hss = 0.0976 : val hss = 0.2303
Fold 3: train tss = 0.6573 : val tss = 0.4419 ::: train hss = 0.1351 : val hss = 0.0450
Fold 4: train tss = 0.6469 : val tss = 0.6787 ::: train hss = 0.1166 : val hss = 0.2371
mean cv TSS: 0.4283
mean cv HSS: 0.1258
718/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.2500 : val tss = -0.0001 ::: train hss = 0.4000 : val hss = -0.0002
Fold 1: train tss = 0.8521 : val tss = 0.3114 ::: train hss = 0.3812 : val hss = 0.1473
Fold 2: train tss = 0.7921 : val tss = 0.6609 ::: train hss = 0.1921 : val hss = 0.2444
Fold 3: train tss = 0.7023 : val tss = 0.2824 ::: train hss = 0.1527 : val hss = 0.0341
Fold 4: train tss = 0.8195 : val tss = 0.6745 ::: train hss = 0.2407 : val hss = 0.2313
mean cv TSS: 0.3858
mean cv HSS: 0.1314
719/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.3495 : val tss = -0.0005 ::: train hss = 0.4510 : val hss = -0.0010
Fold 1: train tss = 0.7942 : val tss = 0.3366 ::: train hss = 0.2784 : val hss = 0.1419
Fold 2: train tss = 0.6452 : val tss = 0.6278 ::: train hss = 0.0853 : val hss = 0.2119
Fold 3: train tss = 0.7370 : val tss = 0.4983 ::: train hss = 0.1887 : val hss = 0.0592
Fold 4: train tss = 0.7583 : val tss = 0.6368 ::: train hss = 0.2030 : val hss = 0.2701
mean cv TSS: 0.4198
mean cv HSS: 0.1364
720/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.9382 : val tss = 0.1121 ::: train hss = 0.2739 : val hss = 0.0918
Fold 1: train tss = 0.8928 : val tss = 0.1695 ::: train hss = 0.3674 : val hss = 0.1394
Fold 2: train tss = 0.7951 : val tss = 0.6854 ::: train hss = 0.1744 : val hss = 0.3113
Fold 3: train tss = 0.7944 : val tss = 0.2237 ::: train hss = 0.2459 : val hss = 0.0664
Fold 4: train tss = 0.7682 : val tss = 0.6261 ::: train hss = 0.2039 : val hss = 0.1941
mean cv TSS: 0.3634
mean cv HSS: 0.1606
721/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.9301 : val tss = 0.1468 ::: train hss = 0.1824 : val hss = 0.1288
Fold 1: train tss = 0.8831 : val tss = 0.1914 ::: train hss = 0.2982 : val hss = 0.0888
Fold 2: train tss = 0.7441 : val tss = 0.7680 ::: train hss = 0.1468 : val hss = 0.3943
Fold 3: train tss = 0.7168 : val tss = 0.2170 ::: train hss = 0.1769 : val hss = 0.0738
Fold 4: train tss = 0.6725 : val tss = 0.6930 ::: train hss = 0.1494 : val hss = 0.2757
mean cv TSS: 0.4032
mean cv HSS: 0.1923
722/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9940 : val tss = 0.0017 ::: train hss = 0.4418 : val hss = 0.0025
Fold 1: train tss = 0.9456 : val tss = 0.3393 ::: train hss = 0.3769 : val hss = 0.2383
Fold 2: train tss = 0.8442 : val tss = 0.6518 ::: train hss = 0.2039 : val hss = 0.2350
Fold 3: train tss = 0.8662 : val tss = 0.1987 ::: train hss = 0.3531 : val hss = 0.0502
Fold 4: train tss = 0.8183 : val tss = 0.6612 ::: train hss = 0.2372 : val hss = 0.2199
mean cv TSS: 0.3705
mean cv HSS: 0.1492
723/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9934 : val tss = -0.0060 ::: train hss = 0.4183 : val hss = -0.0097
Fold 1: train tss = 0.8307 : val tss = 0.3767 ::: train hss = 0.2049 : val hss = 0.0638
Fold 2: train tss = 0.7728 : val tss = 0.6451 ::: train hss = 0.1444 : val hss = 0.2319
Fold 3: train tss = 0.8160 : val tss = 0.2077 ::: train hss = 0.2405 : val hss = 0.0704
Fold 4: train tss = 0.7951 : val tss = 0.5816 ::: train hss = 0.2113 : val hss = 0.1753
mean cv TSS: 0.3610
mean cv HSS: 0.1063
724/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.5960 : val tss = 0.0454 ::: train hss = 0.3668 : val hss = 0.0633
Fold 1: train tss = 0.8920 : val tss = 0.3031 ::: train hss = 0.3631 : val hss = 0.1858
Fold 2: train tss = 0.8214 : val tss = 0.6786 ::: train hss = 0.2238 : val hss = 0.3727
Fold 3: train tss = 0.8218 : val tss = 0.1527 ::: train hss = 0.2731 : val hss = 0.0385
Fold 4: train tss = 0.7780 : val tss = 0.6798 ::: train hss = 0.1998 : val hss = 0.2841
mean cv TSS: 0.3719
mean cv HSS: 0.1889
725/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.2492 : val tss = 0.0184 ::: train hss = 0.3114 : val hss = 0.0341
Fold 1: train tss = 0.6445 : val tss = 0.3950 ::: train hss = 0.0959 : val hss = 0.1110
Fold 2: train tss = 0.6837 : val tss = 0.5313 ::: train hss = 0.1326 : val hss = 0.1513
Fold 3: train tss = 0.6404 : val tss = 0.3250 ::: train hss = 0.1312 : val hss = 0.0509
Fold 4: train tss = 0.7222 : val tss = 0.6826 ::: train hss = 0.1574 : val hss = 0.2828
mean cv TSS: 0.3905
mean cv HSS: 0.1260
726/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}

Total number of parameters: 318997
Fold 0: train tss = 0.2494 : val tss = -0.0018 ::: train hss = 0.3325 : val hss = -0.0034
Fold 1: train tss = 0.7953 : val tss = 0.3282 ::: train hss = 0.2667 : val hss = 0.1230
Fold 2: train tss = 0.7049 : val tss = 0.6562 ::: train hss = 0.1152 : val hss = 0.2390
Fold 3: train tss = 0.7463 : val tss = 0.2319 ::: train hss = 0.1944 : val hss = 0.0427
Fold 4: train tss = 0.7512 : val tss = 0.7379 ::: train hss = 0.1858 : val hss = 0.3300
mean cv TSS: 0.3905
mean cv HSS: 0.1462
727/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.3484 : val tss = 0.0020 ::: train hss = 0.3484 : val hss = 0.0036
Fold 1: train tss = 0.7528 : val tss = 0.3183 ::: train hss = 0.2233 : val hss = 0.1138
Fold 2: train tss = 0.6123 : val tss = 0.6180 ::: train hss = 0.0708 : val hss = 0.2020
Fold 3: train tss = 0.6331 : val tss = 0.4542 ::: train hss = 0.1152 : val hss = 0.0452
Fold 4: train tss = 0.6457 : val tss = 0.5971 ::: train hss = 0.1069 : val hss = 0.1733
mean cv TSS: 0.3979
mean cv HSS: 0.1076
728/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.6399 : val tss = 0.2291 ::: train hss = 0.2188 : val hss = 0.1599
Fold 1: train tss = 0.8580 : val tss = 0.3076 ::: train hss = 0.2991 : val hss = 0.2552
Fold 2: train tss = 0.7539 : val tss = 0.6104 ::: train hss = 0.1757 : val hss = 0.2147
Fold 3: train tss = 0.7647 : val tss = 0.1416 ::: train hss = 0.2054 : val hss = 0.0263
Fold 4: train tss = 0.6283 : val tss = 0.5583 ::: train hss = 0.1273 : val hss = 0.1411
mean cv TSS: 0.3694
mean cv HSS: 0.1594
729/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.8792 : val tss = 0.1350 ::: train hss = 0.1667 : val hss = 0.1152
Fold 1: train tss = 0.7404 : val tss = 0.2906 ::: train hss = 0.1297 : val hss = 0.1373
Fold 2: train tss = 0.5779 : val tss = 0.6005 ::: train hss = 0.0781 : val hss = 0.2116
Fold 3: train tss = 0.6060 : val tss = 0.6626 ::: train hss = 0.1106 : val hss = 0.0596
Fold 4: train tss = 0.6587 : val tss = 0.5844 ::: train hss = 0.1286 : val hss = 0.1756
mean cv TSS: 0.4546
mean cv HSS: 0.1399
730/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9919 : val tss = 0.0000 ::: train hss = 0.3708 : val hss = 0.0000
Fold 1: train tss = 0.8867 : val tss = 0.2954 ::: train hss = 0.3141 : val hss = 0.1378
Fold 2: train tss = 0.8341 : val tss = 0.6614 ::: train hss = 0.1967 : val hss = 0.2339
Fold 3: train tss = 0.8104 : val tss = 0.3622 ::: train hss = 0.2631 : val hss = 0.0908
Fold 4: train tss = 0.8025 : val tss = 0.6649 ::: train hss = 0.2344 : val hss = 0.2220
mean cv TSS: 0.3968
mean cv HSS: 0.1369
731/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9847 : val tss = 0.0940 ::: train hss = 0.2359 : val hss = 0.1231
Fold 1: train tss = 0.8660 : val tss = 0.3382 ::: train hss = 0.2300 : val hss = 0.1923
Fold 2: train tss = 0.6844 : val tss = 0.6348 ::: train hss = 0.0970 : val hss = 0.2219
Fold 3: train tss = 0.7533 : val tss = 0.2904 ::: train hss = 0.1817 : val hss = 0.0515
Fold 4: train tss = 0.7248 : val tss = 0.7113 ::: train hss = 0.1697 : val hss = 0.2820
mean cv TSS: 0.4137
mean cv HSS: 0.1742
732/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.7452 : val tss = 0.0781 ::: train hss = 0.3974 : val hss = 0.1006
Fold 1: train tss = 0.7628 : val tss = 0.3237 ::: train hss = 0.1159 : val hss = 0.0635
Fold 2: train tss = 0.8141 : val tss = 0.6643 ::: train hss = 0.2580 : val hss = 0.4116
Fold 3: train tss = 0.7710 : val tss = 0.5086 ::: train hss = 0.2236 : val hss = 0.0474
Fold 4: train tss = 0.7359 : val tss = 0.6379 ::: train hss = 0.1810 : val hss = 0.1916
mean cv TSS: 0.4425
mean cv HSS: 0.1630
733/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.3983 : val tss = 0.0311 ::: train hss = 0.3793 : val hss = 0.0446
Fold 1: train tss = 0.6696 : val tss = 0.3977 ::: train hss = 0.0915 : val hss = 0.1279
Fold 2: train tss = 0.6822 : val tss = 0.6903 ::: train hss = 0.1101 : val hss = 0.2708
Fold 3: train tss = 0.7072 : val tss = 0.5222 ::: train hss = 0.1738 : val hss = 0.0694
Fold 4: train tss = 0.6835 : val tss = 0.6141 ::: train hss = 0.1370 : val hss = 0.1933
mean cv TSS: 0.4511
mean cv HSS: 0.1412
734/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.4995 : val tss = 0.0134 ::: train hss = 0.5877 : val hss = 0.0250
Fold 1: train tss = 0.8804 : val tss = 0.2844 ::: train hss = 0.3702 : val hss = 0.1172
Fold 2: train tss = 0.8329 : val tss = 0.7217 ::: train hss = 0.2325 : val hss = 0.3264
Fold 3: train tss = 0.7605 : val tss = 0.1682 ::: train hss = 0.2146 : val hss = 0.0292
Fold 4: train tss = 0.7495 : val tss = 0.6750 ::: train hss = 0.1966 : val hss = 0.2414
mean cv TSS: 0.3726
mean cv HSS: 0.1478
735/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.0998 : val tss = 0.0000 ::: train hss = 0.1663 : val hss = 0.0000
Fold 1: train tss = 0.8393 : val tss = 0.3182 ::: train hss = 0.2473 : val hss = 0.0964
Fold 2: train tss = 0.6720 : val tss = 0.6217 ::: train hss = 0.1108 : val hss = 0.2017
Fold 3: train tss = 0.7393 : val tss = 0.2365 ::: train hss = 0.1889 : val hss = 0.0325
Fold 4: train tss = 0.7168 : val tss = 0.6531 ::: train hss = 0.1765 : val hss = 0.2132
mean cv TSS: 0.3659
mean cv HSS: 0.1088
736/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.9781 : val tss = 0.2957 ::: train hss = 0.1762 : val hss = 0.1933
Fold 1: train tss = 0.8821 : val tss = 0.3526 ::: train hss = 0.2945 : val hss = 0.1165
Fold 2: train tss = 0.8250 : val tss = 0.6575 ::: train hss = 0.2299 : val hss = 0.2553
Fold 3: train tss = 0.8210 : val tss = 0.0013 ::: train hss = 0.2907 : val hss = 0.0012
Fold 4: train tss = 0.7654 : val tss = 0.6912 ::: train hss = 0.1912 : val hss = 0.2614
mean cv TSS: 0.3997
mean cv HSS: 0.1655
737/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}

Total number of parameters: 109820
Fold 0: train tss = 0.9631 : val tss = 0.1629 ::: train hss = 0.1113 : val hss = 0.1452
Fold 1: train tss = 0.8119 : val tss = 0.2653 ::: train hss = 0.1493 : val hss = 0.0550
Fold 2: train tss = 0.6657 : val tss = 0.6017 ::: train hss = 0.1063 : val hss = 0.1910
Fold 3: train tss = 0.7269 : val tss = 0.2069 ::: train hss = 0.1711 : val hss = 0.0566
Fold 4: train tss = 0.6804 : val tss = 0.6530 ::: train hss = 0.1399 : val hss = 0.2341
mean cv TSS: 0.3780
mean cv HSS: 0.1364
738/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9943 : val tss = 0.0971 ::: train hss = 0.4572 : val hss = 0.1069
Fold 1: train tss = 0.9483 : val tss = 0.2197 ::: train hss = 0.3936 : val hss = 0.0908
Fold 2: train tss = 0.8524 : val tss = 0.6505 ::: train hss = 0.2320 : val hss = 0.2408
Fold 3: train tss = 0.8275 : val tss = 0.3523 ::: train hss = 0.2670 : val hss = 0.0700
Fold 4: train tss = 0.8221 : val tss = 0.6859 ::: train hss = 0.2360 : val hss = 0.3459
mean cv TSS: 0.4011
mean cv HSS: 0.1709
739/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9931 : val tss = -0.0137 ::: train hss = 0.4095 : val hss = -0.0156
Fold 1: train tss = 0.8332 : val tss = 0.2543 ::: train hss = 0.2680 : val hss = 0.1073
Fold 2: train tss = 0.7181 : val tss = 0.6451 ::: train hss = 0.1114 : val hss = 0.2290
Fold 3: train tss = 0.7939 : val tss = 0.3399 ::: train hss = 0.2277 : val hss = 0.0497
Fold 4: train tss = 0.7613 : val tss = 0.6592 ::: train hss = 0.1909 : val hss = 0.2529
mean cv TSS: 0.3769
mean cv HSS: 0.1246
740/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.4445 : val tss = 0.0866 ::: train hss = 0.2370 : val hss = 0.0949
Fold 1: train tss = 0.8022 : val tss = 0.3203 ::: train hss = 0.1960 : val hss = 0.1102
Fold 2: train tss = 0.6403 : val tss = 0.6921 ::: train hss = 0.0859 : val hss = 0.2955
Fold 3: train tss = 0.6642 : val tss = 0.3516 ::: train hss = 0.1418 : val hss = 0.0453
Fold 4: train tss = 0.7299 : val tss = 0.6581 ::: train hss = 0.1864 : val hss = 0.2821
mean cv TSS: 0.4217
mean cv HSS: 0.1656
741/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7953 : val tss = 0.2448 ::: train hss = 0.2522 : val hss = 0.1352
Fold 2: train tss = 0.7042 : val tss = 0.7517 ::: train hss = 0.1249 : val hss = 0.3812
Fold 3: train tss = 0.7034 : val tss = 0.2480 ::: train hss = 0.1866 : val hss = 0.0259
Fold 4: train tss = 0.6799 : val tss = 0.6192 ::: train hss = 0.1479 : val hss = 0.1997
mean cv TSS: 0.3727
mean cv HSS: 0.1484
742/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.3481 : val tss = 0.0197 ::: train hss = 0.3238 : val hss = 0.0319
Fold 1: train tss = 0.7589 : val tss = 0.3525 ::: train hss = 0.1985 : val hss = 0.1097
Fold 2: train tss = 0.6749 : val tss = 0.6452 ::: train hss = 0.0970 : val hss = 0.2245
Fold 3: train tss = 0.7118 : val tss = 0.2345 ::: train hss = 0.1727 : val hss = 0.0318
Fold 4: train tss = 0.7482 : val tss = 0.6956 ::: train hss = 0.1931 : val hss = 0.2595
mean cv TSS: 0.3895
mean cv HSS: 0.1315
743/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.2975 : val tss = 0.0070 ::: train hss = 0.2532 : val hss = 0.0124
Fold 1: train tss = 0.7381 : val tss = 0.3444 ::: train hss = 0.1667 : val hss = 0.1082
Fold 2: train tss = 0.6441 : val tss = 0.6346 ::: train hss = 0.0824 : val hss = 0.2108
Fold 3: train tss = 0.5965 : val tss = 0.4876 ::: train hss = 0.1000 : val hss = 0.0464
Fold 4: train tss = 0.6771 : val tss = 0.6206 ::: train hss = 0.1292 : val hss = 0.1920
mean cv TSS: 0.4188
mean cv HSS: 0.1140
744/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 109820
Fold 0: train tss = 0.9341 : val tss = 0.1590 ::: train hss = 0.2185 : val hss = 0.1780
Fold 1: train tss = 0.8145 : val tss = 0.2948 ::: train hss = 0.1687 : val hss = 0.0701
Fold 2: train tss = 0.7767 : val tss = 0.6748 ::: train hss = 0.1949 : val hss = 0.3200
Fold 3: train tss = 0.6927 : val tss = 0.0954 ::: train hss = 0.1692 : val hss = 0.0313
Fold 4: train tss = 0.5917 : val tss = 0.5673 ::: train hss = 0.1069 : val hss = 0.1704
mean cv TSS: 0.3583
mean cv HSS: 0.1540
745/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.9190 : val tss = 0.1245 ::: train hss = 0.1242 : val hss = 0.1625
Fold 1: train tss = 0.7276 : val tss = 0.3288 ::: train hss = 0.1758 : val hss = 0.0765
Fold 2: train tss = 0.6146 : val tss = 0.6030 ::: train hss = 0.0795 : val hss = 0.1878
Fold 3: train tss = 0.6142 : val tss = 0.1292 ::: train hss = 0.1174 : val hss = 0.0115
Fold 4: train tss = 0.6273 : val tss = 0.6048 ::: train hss = 0.1105 : val hss = 0.1905
mean cv TSS: 0.3581
mean cv HSS: 0.1257
746/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.9941 : val tss = -0.0025 ::: train hss = 0.4468 : val hss = -0.0045
Fold 1: train tss = 0.7221 : val tss = 0.3298 ::: train hss = 0.1390 : val hss = 0.1063
Fold 2: train tss = 0.8373 : val tss = 0.6750 ::: train hss = 0.2375 : val hss = 0.3150
Fold 3: train tss = 0.8166 : val tss = 0.3206 ::: train hss = 0.2469 : val hss = 0.0834
Fold 4: train tss = 0.7730 : val tss = 0.6916 ::: train hss = 0.2168 : val hss = 0.3294
mean cv TSS: 0.4029
mean cv HSS: 0.1659
747/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.9675 : val tss = -0.0060 ::: train hss = 0.1248 : val hss = -0.0097
Fold 1: train tss = 0.7320 : val tss = 0.3524 ::: train hss = 0.1572 : val hss = 0.0873
Fold 2: train tss = 0.7062 : val tss = 0.6119 ::: train hss = 0.1095 : val hss = 0.1982
Fold 3: train tss = 0.7475 : val tss = 0.2568 ::: train hss = 0.1735 : val hss = 0.0414
Fold 4: train tss = 0.7121 : val tss = 0.6416 ::: train hss = 0.1666 : val hss = 0.2236
mean cv TSS: 0.3713
mean cv HSS: 0.1082
748/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}

Total number of parameters: 109820
Fold 0: train tss = 0.5441 : val tss = -0.0008 ::: train hss = 0.2720 : val hss = -0.0010
Fold 1: train tss = 0.8122 : val tss = 0.1635 ::: train hss = 0.2087 : val hss = 0.0726
Fold 2: train tss = 0.7944 : val tss = 0.7308 ::: train hss = 0.2253 : val hss = 0.4148
Fold 3: train tss = 0.7780 : val tss = 0.0736 ::: train hss = 0.2237 : val hss = 0.0259
Fold 4: train tss = 0.7682 : val tss = 0.5780 ::: train hss = 0.2053 : val hss = 0.1540
mean cv TSS: 0.3090
mean cv HSS: 0.1333
749/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 109820
Fold 0: train tss = 0.0998 : val tss = 0.0000 ::: train hss = 0.1663 : val hss = 0.0000
Fold 1: train tss = 0.8168 : val tss = 0.1785 ::: train hss = 0.2418 : val hss = 0.0799
Fold 2: train tss = 0.6360 : val tss = 0.6158 ::: train hss = 0.0926 : val hss = 0.1974
Fold 3: train tss = 0.6711 : val tss = 0.1579 ::: train hss = 0.1520 : val hss = 0.0244
Fold 4: train tss = 0.6626 : val tss = 0.5477 ::: train hss = 0.1342 : val hss = 0.1382
mean cv TSS: 0.3000
mean cv HSS: 0.0880
750/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 239637
Fold 0: train tss = 0.2494 : val tss = -0.0021 ::: train hss = 0.3325 : val hss = -0.0039
Fold 1: train tss = 0.8209 : val tss = 0.3018 ::: train hss = 0.3459 : val hss = 0.1200
Fold 2: train tss = 0.7642 : val tss = 0.6833 ::: train hss = 0.1647 : val hss = 0.2755
Fold 3: train tss = 0.7306 : val tss = 0.3439 ::: train hss = 0.1840 : val hss = 0.0467
Fold 4: train tss = 0.7586 : val tss = 0.6532 ::: train hss = 0.1863 : val hss = 0.2228
mean cv TSS: 0.3960
mean cv HSS: 0.1322
751/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 768, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 239637
Fold 0: train tss = 0.0993 : val tss = -0.0010 ::: train hss = 0.1418 : val hss = -0.0019
Fold 1: train tss = 0.8125 : val tss = 0.2952 ::: train hss = 0.2542 : val hss = 0.1267
Fold 2: train tss = 0.6697 : val tss = 0.6095 ::: train hss = 0.0911 : val hss = 0.1943
Fold 3: train tss = 0.7427 : val tss = 0.3640 ::: train hss = 0.1922 : val hss = 0.0690
Fold 4: train tss = 0.7285 : val tss = 0.7267 ::: train hss = 0.1770 : val hss = 0.2899
mean cv TSS: 0.3989
mean cv HSS: 0.1356
752/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.9766 : val tss = -0.0350 ::: train hss = 0.1669 : val hss = -0.0290
Fold 1: train tss = 0.8749 : val tss = 0.1998 ::: train hss = 0.1889 : val hss = 0.0862
Fold 2: train tss = 0.8206 : val tss = 0.6654 ::: train hss = 0.2070 : val hss = 0.3020
Fold 3: train tss = 0.7613 : val tss = 0.1743 ::: train hss = 0.1925 : val hss = 0.0335
Fold 4: train tss = 0.7244 : val tss = 0.6352 ::: train hss = 0.1501 : val hss = 0.2192
mean cv TSS: 0.3279
mean cv HSS: 0.1224
753/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.9260 : val tss = -0.0135 ::: train hss = 0.1556 : val hss = -0.0175
Fold 1: train tss = 0.8512 : val tss = 0.2431 ::: train hss = 0.2343 : val hss = 0.1106
Fold 2: train tss = 0.7405 : val tss = 0.7548 ::: train hss = 0.1532 : val hss = 0.4473
Fold 3: train tss = 0.7766 : val tss = 0.1098 ::: train hss = 0.2502 : val hss = 0.0384
Fold 4: train tss = 0.7565 : val tss = 0.6710 ::: train hss = 0.1805 : val hss = 0.2506
mean cv TSS: 0.3530
mean cv HSS: 0.1659
754/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9937 : val tss = -0.0038 ::: train hss = 0.4321 : val hss = -0.0055
Fold 1: train tss = 0.9318 : val tss = 0.2592 ::: train hss = 0.3476 : val hss = 0.0867
Fold 2: train tss = 0.8182 : val tss = 0.6575 ::: train hss = 0.2060 : val hss = 0.2761
Fold 3: train tss = 0.8407 : val tss = 0.4070 ::: train hss = 0.2788 : val hss = 0.1105
Fold 4: train tss = 0.8053 : val tss = 0.6323 ::: train hss = 0.2301 : val hss = 0.2166
mean cv TSS: 0.3905
mean cv HSS: 0.1369
755/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9927 : val tss = 0.0971 ::: train hss = 0.3931 : val hss = 0.0637
Fold 1: train tss = 0.8979 : val tss = 0.3116 ::: train hss = 0.3481 : val hss = 0.0820
Fold 2: train tss = 0.7360 : val tss = 0.6138 ::: train hss = 0.1096 : val hss = 0.2247
Fold 3: train tss = 0.7524 : val tss = 0.4505 ::: train hss = 0.1874 : val hss = 0.0631
Fold 4: train tss = 0.7762 : val tss = 0.6006 ::: train hss = 0.2081 : val hss = 0.1717
mean cv TSS: 0.4147
mean cv HSS: 0.1210
756/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.1499 : val tss = -0.0001 ::: train hss = 0.2498 : val hss = -0.0002
Fold 1: train tss = 0.8495 : val tss = 0.2831 ::: train hss = 0.3177 : val hss = 0.1745
Fold 2: train tss = 0.6781 : val tss = 0.6691 ::: train hss = 0.1047 : val hss = 0.2410
Fold 3: train tss = 0.7546 : val tss = 0.2328 ::: train hss = 0.2182 : val hss = 0.0531
Fold 4: train tss = 0.7306 : val tss = 0.6534 ::: train hss = 0.1574 : val hss = 0.2402
mean cv TSS: 0.3677
mean cv HSS: 0.1417
757/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.0999 : val tss = -0.0001 ::: train hss = 0.1737 : val hss = -0.0002
Fold 1: train tss = 0.8139 : val tss = 0.3758 ::: train hss = 0.2335 : val hss = 0.1256
Fold 2: train tss = 0.7463 : val tss = 0.6585 ::: train hss = 0.1448 : val hss = 0.2552
Fold 3: train tss = 0.6519 : val tss = 0.5172 ::: train hss = 0.1237 : val hss = 0.0671
Fold 4: train tss = 0.7018 : val tss = 0.5650 ::: train hss = 0.1446 : val hss = 0.1677
mean cv TSS: 0.4233
mean cv HSS: 0.1231
758/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.2000 : val tss = -0.0012 ::: train hss = 0.3333 : val hss = -0.0023
Fold 1: train tss = 0.7562 : val tss = 0.3242 ::: train hss = 0.2333 : val hss = 0.1117
Fold 2: train tss = 0.6992 : val tss = 0.6580 ::: train hss = 0.1087 : val hss = 0.2469
Fold 3: train tss = 0.7259 : val tss = 0.1189 ::: train hss = 0.1821 : val hss = 0.0191
Fold 4: train tss = 0.7452 : val tss = 0.6800 ::: train hss = 0.1940 : val hss = 0.2428
mean cv TSS: 0.3560
mean cv HSS: 0.1236
759/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.0075, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}

Total number of parameters: 318997
Fold 0: train tss = 0.2984 : val tss = -0.0043 ::: train hss = 0.3061 : val hss = -0.0073
Fold 1: train tss = 0.7405 : val tss = 0.3845 ::: train hss = 0.1777 : val hss = 0.1169
Fold 2: train tss = 0.6870 : val tss = 0.6495 ::: train hss = 0.0964 : val hss = 0.2329
Fold 3: train tss = 0.6547 : val tss = 0.4422 ::: train hss = 0.1278 : val hss = 0.0522
Fold 4: train tss = 0.6789 : val tss = 0.6395 ::: train hss = 0.1334 : val hss = 0.2122
mean cv TSS: 0.4223
mean cv HSS: 0.1214
760/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.6784 : val tss = 0.1788 ::: train hss = 0.1274 : val hss = 0.1775
Fold 1: train tss = 0.8796 : val tss = 0.2547 ::: train hss = 0.2331 : val hss = 0.0889
Fold 2: train tss = 0.7036 : val tss = 0.6790 ::: train hss = 0.1309 : val hss = 0.3412
Fold 3: train tss = 0.7318 : val tss = 0.2308 ::: train hss = 0.1724 : val hss = 0.0610
Fold 4: train tss = 0.7353 : val tss = 0.6245 ::: train hss = 0.1836 : val hss = 0.2218
mean cv TSS: 0.3936
mean cv HSS: 0.1781
761/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.5871 : val tss = 0.1059 ::: train hss = 0.1690 : val hss = 0.0683
Fold 1: train tss = 0.8229 : val tss = 0.3865 ::: train hss = 0.2611 : val hss = 0.2323
Fold 2: train tss = 0.6892 : val tss = 0.7060 ::: train hss = 0.1206 : val hss = 0.3040
Fold 3: train tss = 0.6555 : val tss = 0.3620 ::: train hss = 0.1316 : val hss = 0.0359
Fold 4: train tss = 0.6621 : val tss = 0.5747 ::: train hss = 0.1478 : val hss = 0.1673
mean cv TSS: 0.4270
mean cv HSS: 0.1616
762/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.9918 : val tss = 0.0037 ::: train hss = 0.3673 : val hss = 0.0071
Fold 1: train tss = 0.8374 : val tss = 0.3816 ::: train hss = 0.3427 : val hss = 0.1444
Fold 2: train tss = 0.7673 : val tss = 0.6644 ::: train hss = 0.1474 : val hss = 0.2697
Fold 3: train tss = 0.8198 : val tss = 0.3364 ::: train hss = 0.2822 : val hss = 0.0788
Fold 4: train tss = 0.7866 : val tss = 0.6830 ::: train hss = 0.2144 : val hss = 0.2456
mean cv TSS: 0.4138
mean cv HSS: 0.1491
763/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.9816 : val tss = 0.0000 ::: train hss = 0.2034 : val hss = 0.0000
Fold 1: train tss = 0.8699 : val tss = 0.2644 ::: train hss = 0.3349 : val hss = 0.1317
Fold 2: train tss = 0.6265 : val tss = 0.5133 ::: train hss = 0.0757 : val hss = 0.1359
Fold 3: train tss = 0.7102 : val tss = 0.3113 ::: train hss = 0.1914 : val hss = 0.0599
Fold 4: train tss = 0.7396 : val tss = 0.6421 ::: train hss = 0.1941 : val hss = 0.2153
mean cv TSS: 0.3462
mean cv HSS: 0.1085
764/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.025}
Total number of parameters: 145916
Fold 0: train tss = 0.8924 : val tss = -0.0121 ::: train hss = 0.3534 : val hss = -0.0143
Fold 1: train tss = 0.8408 : val tss = 0.3558 ::: train hss = 0.2284 : val hss = 0.1547
Fold 2: train tss = 0.7695 : val tss = 0.7425 ::: train hss = 0.1873 : val hss = 0.3517
Fold 3: train tss = 0.7598 : val tss = 0.2733 ::: train hss = 0.2113 : val hss = 0.0645
Fold 4: train tss = 0.7248 : val tss = 0.6501 ::: train hss = 0.1517 : val hss = 0.2037
mean cv TSS: 0.4019
mean cv HSS: 0.1520
765/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 20, 'weight_decay': 0.06}
Total number of parameters: 145916
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.5223 : val tss = 0.3540 ::: train hss = 0.0805 : val hss = 0.0593
Fold 2: train tss = 0.6958 : val tss = 0.6855 ::: train hss = 0.1139 : val hss = 0.2781
Fold 3: train tss = 0.6265 : val tss = 0.4536 ::: train hss = 0.1283 : val hss = 0.0564
Fold 4: train tss = 0.5897 : val tss = 0.5391 ::: train hss = 0.1041 : val hss = 0.1340
mean cv TSS: 0.4064
mean cv HSS: 0.1056
766/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.025}
Total number of parameters: 318997
Fold 0: train tss = 0.3499 : val tss = -0.0016 ::: train hss = 0.4998 : val hss = -0.0030
Fold 1: train tss = 0.8375 : val tss = 0.2598 ::: train hss = 0.3690 : val hss = 0.1154
Fold 2: train tss = 0.7785 : val tss = 0.6664 ::: train hss = 0.1650 : val hss = 0.2393
Fold 3: train tss = 0.7189 : val tss = 0.4736 ::: train hss = 0.1699 : val hss = 0.0649
Fold 4: train tss = 0.7729 : val tss = 0.6365 ::: train hss = 0.2143 : val hss = 0.2004
mean cv TSS: 0.4069
mean cv HSS: 0.1234
767/768
{'batch_size': 256, 'bce_pos_class_weight': 70, 'cnn_filters': 12, 'cv_folds': 5, 'dropout_p': 0.2, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.06}
Total number of parameters: 318997
Fold 0: train tss = 0.2000 : val tss = 0.0000 ::: train hss = 0.3333 : val hss = 0.0000
Fold 1: train tss = 0.8080 : val tss = 0.2972 ::: train hss = 0.3011 : val hss = 0.1290
Fold 2: train tss = 0.6685 : val tss = 0.6063 ::: train hss = 0.0947 : val hss = 0.1865
Fold 3: train tss = 0.7137 : val tss = 0.1668 ::: train hss = 0.1689 : val hss = 0.0325
Fold 4: train tss = 0.7241 : val tss = 0.6744 ::: train hss = 0.1590 : val hss = 0.2537
mean cv TSS: 0.3489
mean cv HSS: 0.1204

,batch_size,bce_pos_class_weight,cnn_filters,dropout_p,fc_size,lr,optimizer_type,sequence_length,weight_decay,tss,hss
241,128,70,4,0.20,1024,0.0075,adam,20,0.060,0.5183,0.1725
669,256,70,8,0.05,1024,0.0150,sgd,20,0.060,0.4704,0.1828
78,128,40,8,0.05,768,0.0150,sgd,45,0.025,0.4702,0.1542
15,128,40,4,0.05,768,0.0150,sgd,45,0.060,0.4677,0.1785
16,128,40,4,0.05,1024,0.0075,adam,20,0.025,0.4640,0.2074
172,128,40,12,0.20,768,0.0150,sgd,20,0.025,0.4638,0.1887
200,128,70,4,0.05,768,0.0150,adam,20,0.025,0.4624,0.1802
291,128,70,8,0.20,768,0.0075,adam,45,0.060,0.4611,0.1597
289,128,70,8,0.20,768,0.0075,adam,20,0.060,0.4575,0.1616
729,256,70,12,0.05,1024,0.0150,adam,20,0.060,0.4546,0.1399
628,256,70,4,0.20,1024,0.0075,sgd,20,0.025,0.4543,0.1410
98,128,40,8,0.20,768,0.0075,adam,45,0.025,0.4540,0.1668
733,256,70,12,0.05,1024,0.0150,sgd,20,0.060,0.4511,0.1412
210,128,70,4,0.05,1024,0.0075,adam,45,0.025,0.4486,0.1563
11,128,40,4,0.05,768,0.0150,adam,45,0.060,0.4482,0.1712
336,128,70,12,0.05,1024,0.0075,adam,20,0.025,0.4479,0.1832
256,128,70,8,0.05,768,0.0075,adam,20,0.025,0.4462,0.2051
626,256,70,4,0.20,1024,0.0075,adam,45,0.025,0.4457,0.1624
618,256,70,4,0.20,768,0.0150,adam,45,0.025,0.4455,0.1263
585,256,70,4,0.05,768,0.0150,adam,20,0.060,0.4440,0.1415

In [10]:
grid.sort_values(by=['hss', 'tss'], ascending=False).head(20)

,batch_size,bce_pos_class_weight,cnn_filters,dropout_p,fc_size,lr,optimizer_type,sequence_length,weight_decay,tss,hss
64,128,40,8,0.05,768,0.0075,adam,20,0.025,0.4194,0.2422
176,128,40,12,0.20,1024,0.0075,adam,20,0.025,0.3852,0.2390
456,256,40,8,0.05,768,0.0150,adam,20,0.025,0.4427,0.2247
514,256,40,12,0.05,768,0.0075,adam,45,0.025,0.3886,0.2243
440,256,40,4,0.20,1024,0.0150,adam,20,0.025,0.3835,0.2183
82,128,40,8,0.05,1024,0.0075,adam,45,0.025,0.3800,0.2137
144,128,40,12,0.05,1024,0.0075,adam,20,0.025,0.3961,0.2134
53,128,40,4,0.20,1024,0.0075,sgd,20,0.060,0.4289,0.2129
560,256,40,12,0.20,1024,0.0075,adam,20,0.025,0.4337,0.2110
81,128,40,8,0.05,1024,0.0075,adam,20,0.060,0.3069,0.2107
474,256,40,8,0.05,1024,0.0150,adam,45,0.025,0.3884,0.2087
150,128,40,12,0.05,1024,0.0075,sgd,45,0.025,0.3710,0.2087
132,128,40,12,0.05,768,0.0075,sgd,20,0.025,0.3696,0.2081
8,128,40,4,0.05,768,0.0150,adam,20,0.025,0.3906,0.2076
16,128,40,4,0.05,1024,0.0075,adam,20,0.025,0.4640,0.2074
529,256,40,12,0.05,1024,0.0075,adam,20,0.060,0.3660,0.2061
483,256,40,8,0.20,768,0.0075,adam,45,0.060,0.3750,0.2057
256,128,70,8,0.05,768,0.0075,adam,20,0.025,0.4462,0.2051
112,128,40,8,0.20,1024,0.0075,adam,20,0.025,0.4072,0.2051
520,256,40,12,0.05,768,0.0150,adam,20,0.025,0.3350,0.2051

In [11]:
if grid.empty:
    print("grid empty")
else:
    grid.to_csv("1_cnn_ts_hypertune_grid_output_10.csv")
    print("grid output successful, saved as 1_cnn_ts_hypertune_grid_output_10.csv")

grid output successful, saved as 1_cnn_ts_hypertune_grid_output_10.csv