In [1]:
import torch

### set up CUDA as device if available
if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")
    cuda_id = torch.cuda.current_device()
    print(f"ID of current CUDA device:{torch.cuda.current_device()}")
    print(f"Name of current CUDA device:{torch.cuda.get_device_name(cuda_id)}")
    print(f"CUDA version: {torch.version.cuda}")
else:
    print("GPU is not available, using CPU")
    device = torch.device("cpu")
print(f"device: {device}")

GPU is available
cuda
CUDA version: 12.4
ID of current CUDA device:0
Name of current CUDA device:NVIDIA H200

In [2]:
import numpy as np
import random
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm, trange
from IPython import display
from sklearn.metrics import average_precision_score
# from conf_and_plot import confusion_matrix_plots
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import KFold
from sklearn.model_selection import ParameterGrid
import seaborn as sns
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import kruskal
import torch.nn.functional as F
from IPython.display import clear_output
import statistics

def seed_all(seed):
    if not seed:
        seed = 10

    print("[ Using Seed : ", seed, " ]")

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

seed_all(2025)

[ Using Seed :  2025  ]

In [3]:
scint_thresh = 0.1 # set the phase scintillation threshold

### following variable not being used anywhere
scint_outlier_thresh = 5. # set the value that determines phase scintillation outliers (these data samples will be removed)

processed_data_2015 = pd.read_csv("processed_data_2015.csv")
processed_data_2015 = processed_data_2015.drop(processed_data_2015.columns[0], axis=1)
predicted_label = 'sigmaPhi projected to vertical at prediction time [radians]'
y = processed_data_2015[predicted_label].values
print(y.shape)

X_fSelect = processed_data_2015.drop(predicted_label, axis=1)
X_fSelect = X_fSelect.values
print(X_fSelect.shape)

(4465846,)
(4465846, 15)

In [4]:
class simple_timeSeries_CNN(nn.Module):
    def __init__(self, cnn_filters, fc_size, dropout_p, loss, sequence_length):
        super(simple_timeSeries_CNN, self).__init__()
        
        self.loss = loss
        self.sequence_length = sequence_length

        self.conv1 = nn.Conv1d(in_channels=15, out_channels=cnn_filters, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm1d(num_features=cnn_filters)
        self.dropout = nn.Dropout(dropout_p)
        self.conv2 = nn.Conv1d(in_channels=cnn_filters, out_channels=cnn_filters*2, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm1d(num_features=cnn_filters*2)
        self.pool = nn.MaxPool1d(2)
        
        ### for simple, non true time-series CNN:
        # num_features = 25, MaxPool1d_size=2
        # 12 = round(25 / 2)
        # 6 = round(12 / 2)
        # self.fc1 = nn.Linear(cnn_filters * 2 * 6, fc_size)
        
        ### for true time-series CNN:
        # sequence_length, MaxPool1d_size=2
        # round(sequence_length / 2) = sequence_length // 2
        # per maxpool layer = sequence_length // 4
        
        self.fc1 = nn.Linear(cnn_filters * 2 * (sequence_length // 4), fc_size)
        # self.fc2 = nn.Linear(fc_size, 1)
        self.fc2 = nn.Linear(fc_size, sequence_length)

    def forward(self, x):
        x = self.pool(torch.relu(self.bn1(self.conv1(x))))
        x = self.dropout(x)
        x = self.pool(torch.relu(self.bn2(self.conv2(x))))
        x = x.view(x.size(0), -1) # Flatten the output for the fully connected layers
        x = torch.relu(self.fc1(x))
        
        # second fully connected layer + reshape to [batch_size, sequence_length, 1]
        x = self.fc2(x).view(x.size(0), self.sequence_length, 1)

        if self.loss == 'focal':
            # x = torch.sigmoid(self.fc2(x))
            x = torch.sigmoid(x)
        elif self.loss == 'bce':
            # x = self.fc2(x)
            pass
        
        return x

In [5]:
def true_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    tss = (TP / (TP + FN)) - (FP / (FP + TN))
    return tss

def heidke_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    
    numerator = 2 * (TP * TN - FP * FN)
    denominator = (TP + FP) * (FP + TN) + (TP + FN) * (TN + FP)
    
    # Avoid division by zero
    if denominator == 0:
        return 0.0
    
    hss = numerator / denominator
    return hss

In [6]:
class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction  # 'mean', 'sum', or 'none'

    def forward(self, inputs, targets):
        BCE_loss = F.binary_cross_entropy(inputs, targets, reduction='none')
        p_t = inputs * targets + (1 - inputs) * (1 - targets)
        focal_loss = self.alpha * (1 - p_t) ** self.gamma * BCE_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        elif self.reduction == 'none':
            return focal_loss
        else:
            raise ValueError(f"Invalid reduction method: {self.reduction}")

In [7]:
def train_model_with_cv(model, train_dataloader, val_dataloader, criterion, optimizer, scheduler, num_epochs):

    epochs = []
    training_loss = []
    validation_loss = []
    training_tss = []
    validation_tss = []
    training_hss = []
    validation_hss = []

    for epoch in range(num_epochs):

        ### training loop
        model.train()
        running_loss = 0.0
        predicted_training_labels = np.array([])
        y_train = np.array([])

        # for batch_inputs, batch_labels in tqdm(train_dataloader):
        for batch_inputs, batch_labels in train_dataloader:
            
            batch_inputs = batch_inputs.to(device)
            batch_labels = batch_labels.to(device)
            
            optimizer.zero_grad()
            output = model(batch_inputs)
            
            output.to(device)
            
            loss = criterion(output, batch_labels.float())
            loss.backward()
            optimizer.step()
            
            if scheduler == False:
                pass
            else:
                scheduler.step()
            
            running_loss += loss.item()
            with torch.no_grad(): predicted_training_labels = np.append(predicted_training_labels, output.cpu())
            with torch.no_grad(): y_train = np.append(y_train, batch_labels.cpu())

        predicted_training_labels = np.where(predicted_training_labels > 0.1, 1, 0)

        train_loss = running_loss / len(train_dataloader)
        train_tss = true_skill_score(y_train.astype(int), predicted_training_labels.astype(int))
        train_hss = heidke_skill_score(y_train.astype(int), predicted_training_labels.astype(int))

        ### validation loop
        model.eval()
        with torch.no_grad():
            running_loss = 0.0
            predicted_val_labels = np.array([])
            y_val = np.array([])

            # for batch_inputs, labels in tqdm(val_dataloader):
            for batch_inputs, batch_labels in val_dataloader:
            
                batch_inputs = batch_inputs.to(device)
                batch_labels = batch_labels.to(device)
                
                outputs = model(batch_inputs)
            
                outputs.to(device)
                
                outputs = model(batch_inputs)
                loss = criterion(outputs, batch_labels.float())
                running_loss += loss.item()
                predicted_val_labels = np.append(predicted_val_labels, outputs.cpu())
                y_val = np.append(y_val, batch_labels.cpu())

        predicted_val_labels = np.where(predicted_val_labels > 0.1, 1, 0)

        val_loss = running_loss / len(val_dataloader)
        val_tss = true_skill_score(y_val.astype(int), predicted_val_labels.astype(int))
        val_hss = heidke_skill_score(y_val.astype(int), predicted_val_labels.astype(int))

        epochs.append(epoch)
        training_loss.append(train_loss)
        validation_loss.append(val_loss)
        training_tss.append(train_tss)
        validation_tss.append(val_tss)
        training_hss.append(train_hss)
        validation_hss.append(val_hss)

    return training_hss, validation_hss, training_tss, validation_tss

In [8]:
class CNNBinaryTimeSeriesClassifier():
    def __init__(self, cnn_filters=8, fc_size=64, sequence_length=60, dropout_p=0.1, batch_size=128, 
                 optimizer_type = 'adam', lr=0.001, sgd_momentum=0.9, weight_decay=0.0001,
                 loss='bce', bce_pos_class_weight=50, focal_alpha=0.25, focal_gamma=2,
                 num_epochs=5, cv_folds=5, scheduler_t=0):
        self.cnn_filters = cnn_filters
        self.fc_size = fc_size
        self.sequence_length = sequence_length
        self.dropout_p = dropout_p
        self.batch_size = batch_size
        self.optimizer_type = optimizer_type
        self.lr = lr        
        self.weight_decay = weight_decay
        self.sgd_momentum = sgd_momentum
        self.loss = loss
        self.bce_pos_class_weight = bce_pos_class_weight
        self.focal_alpha = focal_alpha
        self.focal_gamma = focal_gamma
        self.num_epochs = num_epochs
        self.cv_folds = cv_folds
        self.scheduler_t = scheduler_t
        
    def reshape_data_to_seq_length(self, data, seq_len):
        num_samples = data.shape[0]
        input_features = data.shape[1]
        num_batches = num_samples // seq_len
        data = data[:num_batches * seq_len] # truncate points that don't divide evenly
        reshaped_data = data.reshape(num_batches, seq_len, input_features)
        return reshaped_data

    def reshape_labels_to_seq_length(self, labels, seq_len):
        labels = torch.from_numpy(labels) if isinstance(labels, np.ndarray) else labels
        num_samples = labels.shape[0]
        num_batches = num_samples // seq_len
        labels = labels[:num_batches * seq_len] # truncate points that don't divide evenly
        labels = labels.view(num_batches, seq_len, -1)
        return labels
    
    def fit(self, X, y):

        cv_tss_values = []
        cv_hss_values = []

        tscv = TimeSeriesSplit(n_splits=self.cv_folds)
        for i, (train_index, val_index) in enumerate(tscv.split(X)):
            
            model = simple_timeSeries_CNN(cnn_filters=self.cnn_filters, 
                                          fc_size=self.fc_size, 
                                          dropout_p=self.dropout_p, 
                                          loss=self.loss, 
                                          sequence_length=self.sequence_length)
            model.to(device)
            
            if self.loss == 'bce':
                criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([self.bce_pos_class_weight]).to(device))
            elif self.loss == 'focal':
                criterion = FocalLoss(alpha=self.focal_alpha, gamma=self.focal_gamma)

            if self.optimizer_type == 'adam':
                optimizer = optim.Adam(model.parameters(), lr=self.lr, weight_decay=self.weight_decay)
            elif self.optimizer_type == 'sgd':
                optimizer = optim.SGD(model.parameters(), lr=self.lr, momentum=self.sgd_momentum, weight_decay=self.weight_decay)

            if self.scheduler_t > 0:
                scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=self.scheduler_t)
            else:
                scheduler = False

            X_train, X_val = X[train_index], X[val_index]
            y_train, y_val = y[train_index], y[val_index]
            
            scaler_X = RobustScaler()
            scaler_X = scaler_X.fit(X_train)

            X_train_scaled = scaler_X.transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            
            X_train_scaled = self.reshape_data_to_seq_length(X_train_scaled, self.sequence_length)
            X_val_scaled = self.reshape_data_to_seq_length(X_val_scaled, self.sequence_length)

            train_labels = self.reshape_labels_to_seq_length(y_train, self.sequence_length)
            val_labels = self.reshape_labels_to_seq_length(y_val, self.sequence_length)
            
            train_inputs = torch.tensor(X_train_scaled, dtype=torch.float32).transpose(1, 2)  # Shape: [batch_size, 15, 1]
            train_inputs = train_inputs.to(device)
            train_labels = train_labels.to(device)
            train_dataset = TensorDataset(train_inputs, train_labels)
            train_dataloader = DataLoader(train_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)

            val_inputs = torch.tensor(X_val_scaled, dtype=torch.float32).transpose(1, 2)  # Shape: [batch_size, 15, 1]
            val_inputs = val_inputs.to(device)
            val_labels = val_labels.to(device)
            val_dataset = TensorDataset(val_inputs, val_labels)
            val_dataloader = DataLoader(val_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)
            
            training_hss, validation_hss, training_tss, validation_tss = \
            train_model_with_cv(model, 
                 train_dataloader, val_dataloader, 
                 criterion, optimizer, scheduler,
                 num_epochs=self.num_epochs)
            cv_tss_values.append(validation_tss[-1])
            cv_hss_values.append(validation_hss[-1])

            if i == 0:
                total_params = sum(p.numel() for p in model.parameters())
                print(f'Total number of parameters: {total_params}')
                
            print(f"Fold {i}: train tss = {training_tss[-1]:.4f} : val tss = {validation_tss[-1]:.4f} ::: train hss = {training_hss[-1]:.4f} : val hss = {validation_hss[-1]:.4f}")
        
        return cv_hss_values, cv_tss_values

In [9]:
training_data_size = 50000
training_data_size = 500000

X_train, X_test, \
    y_train, y_test, \
        idx_train, idx_test = train_test_split(X_fSelect, y, range(len(y)), train_size=training_data_size, shuffle=False)

# ### small test
# param_grid = {
#     'cnn_filters': [256],   
#     'fc_size': [256, 1048],  
#     'sequence_length': [100],   
#     'dropout_p': [0.6],  
#     'batch_size': [64],  
#     'lr': [0.03],  
#     'optimizer_type': ['sgd'],  
#     'weight_decay':[0.05],  
#     'loss': ['bce'],
#     'bce_pos_class_weight': [35],  
#     'num_epochs': [20],  
#     'cv_folds': [5], 
# }

### iteration 1
param_grid = {
    'cnn_filters': [16, 64],   
    'fc_size': [256, 1048],  
    'sequence_length': [15, 45],   
    'dropout_p': [0.1, 0.5],  
    'batch_size': [64, 512],  
    'lr': [0.0001, 0.01],  
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.001, 0.01],  
    'loss': ['bce'],
    'bce_pos_class_weight': [35, 75],  
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 2
param_grid = {
    'cnn_filters': [16, 64],   
    'fc_size': [256, 1048],  
    'sequence_length': [30, 45],  ### changed
    'dropout_p': [0.1, 0.5],  
    'batch_size': [512, 1024],  ### changed
    'lr': [0.001, 0.01],  ### changed
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.001, 0.01],  
    'loss': ['bce'],
    'bce_pos_class_weight': [35, 65],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 3
param_grid = {
    'cnn_filters': [32, 128],   ### changed
    'fc_size': [512, 2048],  ### changed
    'sequence_length': [40, 45],  ### changed
    'dropout_p': [0.1, 0.5],  
    'batch_size': [512, 1024],  
    'lr': [0.005, 0.025],  ### changed
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.001, 0.025],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [25, 50],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 4
param_grid = {
    'cnn_filters': [64, 256],  ### changed
    'fc_size': [512, 2048],  
    'sequence_length': [40, 45],  
    'dropout_p': [0.1, 0.5],  
    'batch_size': [512, 1024],  
    'lr': [0.005, 0.05],  ### changed
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.01, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [40, 75],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 5
param_grid = {
    'cnn_filters': [192, 512],  ### changed
    'fc_size': [1536, 2560],  ### changed
    'sequence_length': [40, 45],  
    'dropout_p': [0.1, 0.25],  ### changed
    'batch_size': [512, 1024],  
    'lr': [0.005, 0.05],  
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.01, 0.05],  
    'loss': ['bce'],
    'bce_pos_class_weight': [15, 60],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 6
param_grid = {
    'cnn_filters': [320, 512],  ### changed
    'fc_size': [768, 1280],  ### changed
    'sequence_length': [40, 45],  
    'dropout_p': [0.2, 0.4],  ### changed
    'batch_size': [512, 1024],  
    'lr': [0.0025, 0.075],  ### changed
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.0075, 0.075],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [15, 60],  
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 7
param_grid = {
    'cnn_filters': [32, 512],  ### changed
    'fc_size': [1536, 2048],  ### changed
    'sequence_length': [35, 45],  ### changed
    'dropout_p': [0.1, 0.25],  ### changed
    'batch_size': [512, 1024],  
    'lr': [0.005, 0.01],  ### changed
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.01, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [10, 70],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 8
param_grid = {
    'cnn_filters': [96, 256],  ### changed
    'fc_size': [1536, 2048],  
    'sequence_length': [10, 45],  ### changed
    'dropout_p': [0.1, 0.25],  
    'batch_size': [512, 1024],  
    'lr': [0.005, 0.01],  
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.02, 0.04],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [5, 80],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 9
param_grid = {
    'cnn_filters': [32, 128],  ### changed
    'fc_size': [1024, 2048],  ### changed
    'sequence_length': [45],  ### changed, removed 1 dimension
    'dropout_p': [0.1, 0.25],  
    'batch_size': [512, 1024],  
    'lr': [0.005, 0.025],  ### changed
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.02, 0.04],  
    'loss': ['bce'],
    'bce_pos_class_weight': [10, 65],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

### iteration 10
param_grid = {
    'cnn_filters': [48, 256],  ### changed
    'fc_size': [1024, 2048],  
    'sequence_length': [45],  
    'dropout_p': [0.05, 0.35],  ### changed
    'batch_size': [512, 1024],  
    'lr': [0.005, 0.01],  ### changed
    'optimizer_type': ['sgd','adam'],  
    'weight_decay':[0.03, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [35, 50],  ### changed
    'num_epochs': [40],  
    'cv_folds': [5], 
}

param_combinations = list(ParameterGrid(param_grid))

grid = pd.DataFrame()
tss_distributions = []
hss_distributions = []
mean_tss_scores = []
mean_hss_scores = []
for params in param_combinations:

    print(str(param_combinations.index(params)) + "/" + str(len(param_combinations)))
    print(params)

    cnn_time_series_classifier = CNNBinaryTimeSeriesClassifier(**params)
    cv_hss_values, cv_tss_values = cnn_time_series_classifier.fit(X_train, y_train)
    
    tss_distributions.append(cv_tss_values)
    hss_distributions.append(cv_hss_values)
    mean_cv_tss = sum(cv_tss_values)/len(cv_tss_values)
    mean_cv_hss = sum(cv_hss_values)/len(cv_hss_values)
    print(f"mean cv TSS: {mean_cv_tss:.4f}")
    print(f"mean cv HSS: {mean_cv_hss:.4f}")
    mean_tss_scores.append(mean_cv_tss)
    mean_hss_scores.append(mean_cv_hss)
    
    if params == param_combinations[0]:
        grid = pd.DataFrame(params, index=[0])
    else:
        grid = pd.concat([grid, pd.DataFrame([params])], ignore_index=True)

grid['tss'] = [round(num, 4) for num in mean_tss_scores]
grid['hss'] = [round(num, 4) for num in mean_hss_scores]
grid = grid.sort_values(by=['tss', 'hss'], ascending=False)
grid = grid.drop(columns=[col for col in ['num_epochs','cv_folds','loss','scheduler_t'] if col in grid.columns], axis=1)
grid.head(20)

0/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6990 : val tss = 0.6736 ::: train hss = 0.2382 : val hss = 0.2715
Fold 1: train tss = 0.7045 : val tss = 0.6725 ::: train hss = 0.2405 : val hss = 0.2144
Fold 2: train tss = 0.6781 : val tss = 0.6260 ::: train hss = 0.1926 : val hss = 0.0753
Fold 3: train tss = 0.6647 : val tss = 0.5509 ::: train hss = 0.1756 : val hss = 0.1048
Fold 4: train tss = 0.7102 : val tss = 0.6360 ::: train hss = 0.2250 : val hss = 0.1864
mean cv TSS: 0.6318
mean cv HSS: 0.1705
1/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6721 : val tss = 0.6695 ::: train hss = 0.2112 : val hss = 0.2650
Fold 1: train tss = 0.6838 : val tss = 0.7357 ::: train hss = 0.2219 : val hss = 0.1438
Fold 2: train tss = 0.6627 : val tss = 0.5962 ::: train hss = 0.1856 : val hss = 0.0690
Fold 3: train tss = 0.6858 : val tss = 0.6439 ::: train hss = 0.1903 : val hss = 0.2381
Fold 4: train tss = 0.6770 : val tss = 0.5926 ::: train hss = 0.1952 : val hss = 0.2248
mean cv TSS: 0.6476
mean cv HSS: 0.1881
2/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7910 : val tss = 0.6385 ::: train hss = 0.3348 : val hss = 0.2486
Fold 1: train tss = 0.6380 : val tss = 0.6841 ::: train hss = 0.1822 : val hss = 0.2327
Fold 2: train tss = 0.6330 : val tss = 0.6749 ::: train hss = 0.1575 : val hss = 0.1502
Fold 3: train tss = 0.6153 : val tss = 0.6191 ::: train hss = 0.1471 : val hss = 0.1445
Fold 4: train tss = 0.6559 : val tss = 0.6528 ::: train hss = 0.1851 : val hss = 0.1296
mean cv TSS: 0.6539
mean cv HSS: 0.1811
3/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7523 : val tss = 0.6174 ::: train hss = 0.2842 : val hss = 0.2771
Fold 1: train tss = 0.6454 : val tss = 0.7492 ::: train hss = 0.2011 : val hss = 0.1398
Fold 2: train tss = 0.6228 : val tss = 0.6473 ::: train hss = 0.1509 : val hss = 0.1104
Fold 3: train tss = 0.6279 : val tss = 0.6518 ::: train hss = 0.1529 : val hss = 0.2633
Fold 4: train tss = 0.6114 : val tss = 0.6591 ::: train hss = 0.1615 : val hss = 0.1553
mean cv TSS: 0.6650
mean cv HSS: 0.1892
4/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7020 : val tss = 0.6558 ::: train hss = 0.2332 : val hss = 0.2325
Fold 1: train tss = 0.7078 : val tss = 0.7121 ::: train hss = 0.2591 : val hss = 0.1152
Fold 2: train tss = 0.6886 : val tss = 0.6498 ::: train hss = 0.1979 : val hss = 0.0909
Fold 3: train tss = 0.6848 : val tss = 0.6572 ::: train hss = 0.1884 : val hss = 0.2042
Fold 4: train tss = 0.6526 : val tss = 0.6535 ::: train hss = 0.1758 : val hss = 0.1791
mean cv TSS: 0.6657
mean cv HSS: 0.1644
5/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6899 : val tss = 0.6610 ::: train hss = 0.2263 : val hss = 0.2795
Fold 1: train tss = 0.6537 : val tss = 0.6648 ::: train hss = 0.1911 : val hss = 0.1966
Fold 2: train tss = 0.6436 : val tss = 0.6246 ::: train hss = 0.1762 : val hss = 0.0771
Fold 3: train tss = 0.6372 : val tss = 0.6511 ::: train hss = 0.1699 : val hss = 0.1657
Fold 4: train tss = 0.6488 : val tss = 0.6575 ::: train hss = 0.1847 : val hss = 0.1867
mean cv TSS: 0.6518
mean cv HSS: 0.1811
6/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7532 : val tss = 0.6666 ::: train hss = 0.3352 : val hss = 0.2427
Fold 1: train tss = 0.6132 : val tss = 0.6603 ::: train hss = 0.1870 : val hss = 0.1207
Fold 2: train tss = 0.6038 : val tss = 0.6384 ::: train hss = 0.1592 : val hss = 0.0968
Fold 3: train tss = 0.6100 : val tss = 0.5834 ::: train hss = 0.1478 : val hss = 0.1203
Fold 4: train tss = 0.6247 : val tss = 0.6614 ::: train hss = 0.1635 : val hss = 0.1410
mean cv TSS: 0.6420
mean cv HSS: 0.1443
7/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6943 : val tss = 0.6151 ::: train hss = 0.2301 : val hss = 0.3327
Fold 1: train tss = 0.6214 : val tss = 0.6654 ::: train hss = 0.1847 : val hss = 0.1591
Fold 2: train tss = 0.6257 : val tss = 0.6516 ::: train hss = 0.1562 : val hss = 0.1211
Fold 3: train tss = 0.6461 : val tss = 0.6515 ::: train hss = 0.1756 : val hss = 0.2200
Fold 4: train tss = 0.6001 : val tss = 0.6547 ::: train hss = 0.1452 : val hss = 0.1188
mean cv TSS: 0.6477
mean cv HSS: 0.1903
8/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6908 : val tss = 0.6680 ::: train hss = 0.2316 : val hss = 0.2510
Fold 1: train tss = 0.6976 : val tss = 0.6367 ::: train hss = 0.2274 : val hss = 0.2976
Fold 2: train tss = 0.7226 : val tss = 0.6651 ::: train hss = 0.2469 : val hss = 0.1125
Fold 3: train tss = 0.7067 : val tss = 0.6573 ::: train hss = 0.2078 : val hss = 0.2625
Fold 4: train tss = 0.6881 : val tss = 0.5000 ::: train hss = 0.1991 : val hss = 0.2402
mean cv TSS: 0.6254
mean cv HSS: 0.2328
9/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6794 : val tss = 0.6779 ::: train hss = 0.2226 : val hss = 0.2712
Fold 1: train tss = 0.6997 : val tss = 0.6542 ::: train hss = 0.2381 : val hss = 0.2228
Fold 2: train tss = 0.6781 : val tss = 0.6714 ::: train hss = 0.1869 : val hss = 0.1295
Fold 3: train tss = 0.6608 : val tss = 0.5964 ::: train hss = 0.1750 : val hss = 0.1367
Fold 4: train tss = 0.6516 : val tss = 0.6633 ::: train hss = 0.1743 : val hss = 0.1621
mean cv TSS: 0.6526
mean cv HSS: 0.1844
10/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7332 : val tss = 0.6455 ::: train hss = 0.2550 : val hss = 0.3536
Fold 1: train tss = 0.6728 : val tss = 0.7503 ::: train hss = 0.2167 : val hss = 0.1509
Fold 2: train tss = 0.6206 : val tss = 0.5937 ::: train hss = 0.1712 : val hss = 0.0679
Fold 3: train tss = 0.6494 : val tss = 0.6424 ::: train hss = 0.1662 : val hss = 0.2241
Fold 4: train tss = 0.6274 : val tss = 0.6486 ::: train hss = 0.1657 : val hss = 0.1614
mean cv TSS: 0.6561
mean cv HSS: 0.1916
11/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 2273357
Fold 0: train tss = 0.6927 : val tss = 0.6219 ::: train hss = 0.2376 : val hss = 0.1955
Fold 1: train tss = 0.6411 : val tss = 0.7150 ::: train hss = 0.2012 : val hss = 0.1486
Fold 2: train tss = 0.6161 : val tss = 0.6235 ::: train hss = 0.1515 : val hss = 0.0930
Fold 3: train tss = 0.6303 : val tss = 0.6591 ::: train hss = 0.1628 : val hss = 0.2194
Fold 4: train tss = 0.6103 : val tss = 0.6711 ::: train hss = 0.1505 : val hss = 0.1528
mean cv TSS: 0.6581
mean cv HSS: 0.1619
12/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7695 : val tss = 0.6760 ::: train hss = 0.3083 : val hss = 0.2794
Fold 1: train tss = 0.7173 : val tss = 0.6757 ::: train hss = 0.2506 : val hss = 0.1338
Fold 2: train tss = 0.6919 : val tss = 0.6606 ::: train hss = 0.2015 : val hss = 0.1384
Fold 3: train tss = 0.6542 : val tss = 0.6201 ::: train hss = 0.1612 : val hss = 0.1486
Fold 4: train tss = 0.6682 : val tss = 0.6291 ::: train hss = 0.1957 : val hss = 0.2374
mean cv TSS: 0.6523
mean cv HSS: 0.1875
13/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7161 : val tss = 0.6451 ::: train hss = 0.2541 : val hss = 0.2328
Fold 1: train tss = 0.6668 : val tss = 0.7119 ::: train hss = 0.2132 : val hss = 0.2000
Fold 2: train tss = 0.6303 : val tss = 0.6045 ::: train hss = 0.1737 : val hss = 0.0703
Fold 3: train tss = 0.6598 : val tss = 0.6397 ::: train hss = 0.1803 : val hss = 0.2183
Fold 4: train tss = 0.6592 : val tss = 0.6729 ::: train hss = 0.1890 : val hss = 0.1739
mean cv TSS: 0.6548
mean cv HSS: 0.1791
14/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7481 : val tss = 0.6585 ::: train hss = 0.2909 : val hss = 0.2901
Fold 1: train tss = 0.6490 : val tss = 0.7283 ::: train hss = 0.1962 : val hss = 0.1644
Fold 2: train tss = 0.6319 : val tss = 0.6455 ::: train hss = 0.1714 : val hss = 0.1305
Fold 3: train tss = 0.6450 : val tss = 0.6313 ::: train hss = 0.1727 : val hss = 0.1669
Fold 4: train tss = 0.6142 : val tss = 0.6577 ::: train hss = 0.1531 : val hss = 0.1842
mean cv TSS: 0.6642
mean cv HSS: 0.1872
15/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6724 : val tss = 0.6675 ::: train hss = 0.2139 : val hss = 0.2713
Fold 1: train tss = 0.6215 : val tss = 0.7375 ::: train hss = 0.1730 : val hss = 0.1772
Fold 2: train tss = 0.5722 : val tss = 0.5967 ::: train hss = 0.1477 : val hss = 0.0711
Fold 3: train tss = 0.6405 : val tss = 0.6281 ::: train hss = 0.1996 : val hss = 0.1550
Fold 4: train tss = 0.6075 : val tss = 0.6336 ::: train hss = 0.1549 : val hss = 0.1804
mean cv TSS: 0.6527
mean cv HSS: 0.1710
16/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6712 : val tss = 0.6718 ::: train hss = 0.2179 : val hss = 0.2583
Fold 1: train tss = 0.6861 : val tss = 0.7387 ::: train hss = 0.2263 : val hss = 0.1793
Fold 2: train tss = 0.6943 : val tss = 0.6763 ::: train hss = 0.2016 : val hss = 0.1223
Fold 3: train tss = 0.6603 : val tss = 0.5919 ::: train hss = 0.1775 : val hss = 0.1222
Fold 4: train tss = 0.6838 : val tss = 0.6364 ::: train hss = 0.2042 : val hss = 0.1871
mean cv TSS: 0.6630
mean cv HSS: 0.1739
17/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6633 : val tss = 0.6699 ::: train hss = 0.2094 : val hss = 0.2523
Fold 1: train tss = 0.6665 : val tss = 0.7408 ::: train hss = 0.2103 : val hss = 0.1617
Fold 2: train tss = 0.6805 : val tss = 0.6628 ::: train hss = 0.1977 : val hss = 0.1115
Fold 3: train tss = 0.6523 : val tss = 0.5963 ::: train hss = 0.1680 : val hss = 0.1343
Fold 4: train tss = 0.6780 : val tss = 0.6458 ::: train hss = 0.2011 : val hss = 0.1613
mean cv TSS: 0.6631
mean cv HSS: 0.1642
18/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7673 : val tss = 0.6644 ::: train hss = 0.3358 : val hss = 0.3315
Fold 1: train tss = 0.6375 : val tss = 0.7140 ::: train hss = 0.1850 : val hss = 0.1116
Fold 2: train tss = 0.6235 : val tss = 0.6632 ::: train hss = 0.1489 : val hss = 0.1104
Fold 3: train tss = 0.5953 : val tss = 0.5787 ::: train hss = 0.1377 : val hss = 0.1157
Fold 4: train tss = 0.6284 : val tss = 0.6427 ::: train hss = 0.1635 : val hss = 0.1873
mean cv TSS: 0.6526
mean cv HSS: 0.1713
19/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7373 : val tss = 0.6223 ::: train hss = 0.2759 : val hss = 0.3241
Fold 1: train tss = 0.6114 : val tss = 0.7383 ::: train hss = 0.1681 : val hss = 0.1292
Fold 2: train tss = 0.6303 : val tss = 0.6349 ::: train hss = 0.1565 : val hss = 0.0959
Fold 3: train tss = 0.6039 : val tss = 0.6276 ::: train hss = 0.1354 : val hss = 0.1538
Fold 4: train tss = 0.6129 : val tss = 0.6369 ::: train hss = 0.1572 : val hss = 0.1415
mean cv TSS: 0.6520
mean cv HSS: 0.1689
20/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7137 : val tss = 0.6675 ::: train hss = 0.2521 : val hss = 0.2656
Fold 1: train tss = 0.6762 : val tss = 0.6815 ::: train hss = 0.2124 : val hss = 0.2245
Fold 2: train tss = 0.6890 : val tss = 0.6346 ::: train hss = 0.2059 : val hss = 0.0907
Fold 3: train tss = 0.6734 : val tss = 0.6587 ::: train hss = 0.1786 : val hss = 0.2217
Fold 4: train tss = 0.6670 : val tss = 0.6385 ::: train hss = 0.1888 : val hss = 0.1575
mean cv TSS: 0.6562
mean cv HSS: 0.1920
21/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7079 : val tss = 0.6623 ::: train hss = 0.2492 : val hss = 0.2774
Fold 1: train tss = 0.6664 : val tss = 0.6484 ::: train hss = 0.2020 : val hss = 0.2400
Fold 2: train tss = 0.6033 : val tss = 0.5848 ::: train hss = 0.1602 : val hss = 0.0612
Fold 3: train tss = 0.6543 : val tss = 0.6616 ::: train hss = 0.1700 : val hss = 0.1935
Fold 4: train tss = 0.6447 : val tss = 0.6425 ::: train hss = 0.1801 : val hss = 0.1510
mean cv TSS: 0.6399
mean cv HSS: 0.1846
22/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 1144909
Fold 0: train tss = 0.7239 : val tss = 0.6676 ::: train hss = 0.2710 : val hss = 0.3055
Fold 1: train tss = 0.6181 : val tss = 0.7582 ::: train hss = 0.1736 : val hss = 0.1545
Fold 2: train tss = 0.6172 : val tss = 0.6551 ::: train hss = 0.1505 : val hss = 0.1241
Fold 3: train tss = 0.6251 : val tss = 0.6381 ::: train hss = 0.1547 : val hss = 0.2186
Fold 4: train tss = 0.6106 : val tss = 0.6517 ::: train hss = 0.1495 : val hss = 0.1415
mean cv TSS: 0.6742
mean cv HSS: 0.1888
23/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6945 : val tss = 0.6101 ::: train hss = 0.2521 : val hss = 0.2185
Fold 1: train tss = 0.6069 : val tss = 0.6647 ::: train hss = 0.1598 : val hss = 0.2021
Fold 2: train tss = 0.6042 : val tss = 0.6215 ::: train hss = 0.1458 : val hss = 0.0998
Fold 3: train tss = 0.6360 : val tss = 0.6093 ::: train hss = 0.1835 : val hss = 0.1384
Fold 4: train tss = 0.5982 : val tss = 0.6430 ::: train hss = 0.1454 : val hss = 0.1577
mean cv TSS: 0.6297
mean cv HSS: 0.1633
24/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6689 : val tss = 0.6763 ::: train hss = 0.2195 : val hss = 0.2658
Fold 1: train tss = 0.6887 : val tss = 0.7491 ::: train hss = 0.2308 : val hss = 0.1543
Fold 2: train tss = 0.6771 : val tss = 0.6689 ::: train hss = 0.1843 : val hss = 0.1168
Fold 3: train tss = 0.6733 : val tss = 0.6131 ::: train hss = 0.1851 : val hss = 0.1430
Fold 4: train tss = 0.6750 : val tss = 0.6363 ::: train hss = 0.1886 : val hss = 0.2057
mean cv TSS: 0.6688
mean cv HSS: 0.1771
25/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6619 : val tss = 0.6790 ::: train hss = 0.2087 : val hss = 0.2632
Fold 1: train tss = 0.6702 : val tss = 0.7116 ::: train hss = 0.2151 : val hss = 0.0945
Fold 2: train tss = 0.6795 : val tss = 0.6381 ::: train hss = 0.1975 : val hss = 0.0835
Fold 3: train tss = 0.6583 : val tss = 0.6168 ::: train hss = 0.1638 : val hss = 0.1415
Fold 4: train tss = 0.6649 : val tss = 0.6352 ::: train hss = 0.1865 : val hss = 0.1812
mean cv TSS: 0.6561
mean cv HSS: 0.1528
26/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7702 : val tss = 0.6840 ::: train hss = 0.3489 : val hss = 0.3003
Fold 1: train tss = 0.6653 : val tss = 0.6439 ::: train hss = 0.2126 : val hss = 0.2530
Fold 2: train tss = 0.6288 : val tss = 0.6461 ::: train hss = 0.1641 : val hss = 0.0952
Fold 3: train tss = 0.6414 : val tss = 0.5986 ::: train hss = 0.1605 : val hss = 0.1921
Fold 4: train tss = 0.6262 : val tss = 0.6641 ::: train hss = 0.1671 : val hss = 0.1541
mean cv TSS: 0.6473
mean cv HSS: 0.1989
27/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6906 : val tss = 0.6377 ::: train hss = 0.2235 : val hss = 0.2700
Fold 1: train tss = 0.6266 : val tss = 0.7598 ::: train hss = 0.1765 : val hss = 0.1566
Fold 2: train tss = 0.6108 : val tss = 0.6454 ::: train hss = 0.1450 : val hss = 0.0948
Fold 3: train tss = 0.6231 : val tss = 0.6192 ::: train hss = 0.1627 : val hss = 0.1536
Fold 4: train tss = 0.6036 : val tss = 0.6667 ::: train hss = 0.1510 : val hss = 0.1454
mean cv TSS: 0.6657
mean cv HSS: 0.1641
28/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7202 : val tss = 0.6743 ::: train hss = 0.2619 : val hss = 0.2791
Fold 1: train tss = 0.6755 : val tss = 0.7134 ::: train hss = 0.2132 : val hss = 0.2071
Fold 2: train tss = 0.6706 : val tss = 0.6498 ::: train hss = 0.1922 : val hss = 0.1072
Fold 3: train tss = 0.6833 : val tss = 0.6720 ::: train hss = 0.1941 : val hss = 0.2464
Fold 4: train tss = 0.6453 : val tss = 0.6672 ::: train hss = 0.1693 : val hss = 0.1436
mean cv TSS: 0.6753
mean cv HSS: 0.1967
29/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7061 : val tss = 0.6839 ::: train hss = 0.2452 : val hss = 0.2834
Fold 1: train tss = 0.6531 : val tss = 0.6864 ::: train hss = 0.2066 : val hss = 0.1386
Fold 2: train tss = 0.6326 : val tss = 0.6161 ::: train hss = 0.1668 : val hss = 0.0747
Fold 3: train tss = 0.6163 : val tss = 0.5728 ::: train hss = 0.1568 : val hss = 0.1354
Fold 4: train tss = 0.6283 : val tss = 0.6666 ::: train hss = 0.1639 : val hss = 0.1599
mean cv TSS: 0.6452
mean cv HSS: 0.1584
30/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7495 : val tss = 0.6678 ::: train hss = 0.3005 : val hss = 0.2671
Fold 1: train tss = 0.6393 : val tss = 0.7364 ::: train hss = 0.1898 : val hss = 0.1098
Fold 2: train tss = 0.6132 : val tss = 0.6314 ::: train hss = 0.1558 : val hss = 0.0892
Fold 3: train tss = 0.6017 : val tss = 0.6215 ::: train hss = 0.1454 : val hss = 0.1578
Fold 4: train tss = 0.6050 : val tss = 0.6629 ::: train hss = 0.1426 : val hss = 0.1477
mean cv TSS: 0.6640
mean cv HSS: 0.1543
31/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6646 : val tss = 0.6596 ::: train hss = 0.2081 : val hss = 0.2479
Fold 1: train tss = 0.6079 : val tss = 0.7579 ::: train hss = 0.1638 : val hss = 0.1531
Fold 2: train tss = 0.5957 : val tss = 0.6046 ::: train hss = 0.1517 : val hss = 0.0789
Fold 3: train tss = 0.6157 : val tss = 0.6394 ::: train hss = 0.1819 : val hss = 0.1844
Fold 4: train tss = 0.5862 : val tss = 0.6613 ::: train hss = 0.1439 : val hss = 0.1496
mean cv TSS: 0.6646
mean cv HSS: 0.1628
32/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7617 : val tss = 0.6541 ::: train hss = 0.3093 : val hss = 0.2808
Fold 1: train tss = 0.7809 : val tss = 0.6842 ::: train hss = 0.3324 : val hss = 0.2103
Fold 2: train tss = 0.7552 : val tss = 0.6476 ::: train hss = 0.2757 : val hss = 0.0936
Fold 3: train tss = 0.7514 : val tss = 0.6748 ::: train hss = 0.2526 : val hss = 0.2340
Fold 4: train tss = 0.7307 : val tss = 0.5476 ::: train hss = 0.2363 : val hss = 0.2475
mean cv TSS: 0.6417
mean cv HSS: 0.2132
33/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 6221357
Fold 0: train tss = 0.7496 : val tss = 0.6591 ::: train hss = 0.2933 : val hss = 0.2758
Fold 1: train tss = 0.7208 : val tss = 0.7191 ::: train hss = 0.2606 : val hss = 0.0982
Fold 2: train tss = 0.7245 : val tss = 0.6336 ::: train hss = 0.2611 : val hss = 0.1012
Fold 3: train tss = 0.7124 : val tss = 0.6504 ::: train hss = 0.2173 : val hss = 0.2804
Fold 4: train tss = 0.7070 : val tss = 0.6255 ::: train hss = 0.2220 : val hss = 0.2059
mean cv TSS: 0.6576
mean cv HSS: 0.1923
34/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7510 : val tss = 0.6024 ::: train hss = 0.2990 : val hss = 0.3466
Fold 1: train tss = 0.6228 : val tss = 0.7525 ::: train hss = 0.1763 : val hss = 0.1324
Fold 2: train tss = 0.5885 : val tss = 0.6223 ::: train hss = 0.1380 : val hss = 0.0781
Fold 3: train tss = 0.5922 : val tss = 0.6167 ::: train hss = 0.1290 : val hss = 0.1406
Fold 4: train tss = 0.6318 : val tss = 0.6537 ::: train hss = 0.1752 : val hss = 0.1960
mean cv TSS: 0.6495
mean cv HSS: 0.1787
35/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6812 : val tss = 0.7010 ::: train hss = 0.2176 : val hss = 0.2947
Fold 1: train tss = 0.6010 : val tss = 0.6359 ::: train hss = 0.1581 : val hss = 0.1539
Fold 2: train tss = 0.6062 : val tss = 0.6297 ::: train hss = 0.1471 : val hss = 0.0867
Fold 3: train tss = 0.6037 : val tss = 0.6449 ::: train hss = 0.1418 : val hss = 0.2532
Fold 4: train tss = 0.6081 : val tss = 0.6583 ::: train hss = 0.1541 : val hss = 0.1498
mean cv TSS: 0.6539
mean cv HSS: 0.1877
36/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.8330 : val tss = 0.6372 ::: train hss = 0.4121 : val hss = 0.2522
Fold 1: train tss = 0.7633 : val tss = 0.6497 ::: train hss = 0.3162 : val hss = 0.2635
Fold 2: train tss = 0.7463 : val tss = 0.6625 ::: train hss = 0.2960 : val hss = 0.1229
Fold 3: train tss = 0.7215 : val tss = 0.6635 ::: train hss = 0.2218 : val hss = 0.2100
Fold 4: train tss = 0.7397 : val tss = 0.6145 ::: train hss = 0.2562 : val hss = 0.2054
mean cv TSS: 0.6455
mean cv HSS: 0.2108
37/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7350 : val tss = 0.6644 ::: train hss = 0.2710 : val hss = 0.2953
Fold 1: train tss = 0.7274 : val tss = 0.6642 ::: train hss = 0.2587 : val hss = 0.1646
Fold 2: train tss = 0.6775 : val tss = 0.6457 ::: train hss = 0.2014 : val hss = 0.1097
Fold 3: train tss = 0.6551 : val tss = 0.6346 ::: train hss = 0.1631 : val hss = 0.1552
Fold 4: train tss = 0.6632 : val tss = 0.6564 ::: train hss = 0.1951 : val hss = 0.1857
mean cv TSS: 0.6530
mean cv HSS: 0.1821
38/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7361 : val tss = 0.6704 ::: train hss = 0.3064 : val hss = 0.2527
Fold 1: train tss = 0.6198 : val tss = 0.6963 ::: train hss = 0.1719 : val hss = 0.1980
Fold 2: train tss = 0.5951 : val tss = 0.6678 ::: train hss = 0.1375 : val hss = 0.1176
Fold 3: train tss = 0.6237 : val tss = 0.6383 ::: train hss = 0.1805 : val hss = 0.2082
Fold 4: train tss = 0.6303 : val tss = 0.6636 ::: train hss = 0.1748 : val hss = 0.1373
mean cv TSS: 0.6673
mean cv HSS: 0.1828
39/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6940 : val tss = 0.6437 ::: train hss = 0.2271 : val hss = 0.2265
Fold 1: train tss = 0.6268 : val tss = 0.7408 ::: train hss = 0.1752 : val hss = 0.1386
Fold 2: train tss = 0.6038 : val tss = 0.6194 ::: train hss = 0.1464 : val hss = 0.0782
Fold 3: train tss = 0.6659 : val tss = 0.6263 ::: train hss = 0.2016 : val hss = 0.1741
Fold 4: train tss = 0.6202 : val tss = 0.6611 ::: train hss = 0.1612 : val hss = 0.1359
mean cv TSS: 0.6582
mean cv HSS: 0.1507
40/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7684 : val tss = 0.6324 ::: train hss = 0.3165 : val hss = 0.2790
Fold 1: train tss = 0.7750 : val tss = 0.5573 ::: train hss = 0.3170 : val hss = 0.3427
Fold 2: train tss = 0.7530 : val tss = 0.6604 ::: train hss = 0.2749 : val hss = 0.1024
Fold 3: train tss = 0.7389 : val tss = 0.6693 ::: train hss = 0.2258 : val hss = 0.1989
Fold 4: train tss = 0.7485 : val tss = 0.6685 ::: train hss = 0.2706 : val hss = 0.1723
mean cv TSS: 0.6376
mean cv HSS: 0.2190
41/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7467 : val tss = 0.6524 ::: train hss = 0.2872 : val hss = 0.2738
Fold 1: train tss = 0.7568 : val tss = 0.7215 ::: train hss = 0.3011 : val hss = 0.1759
Fold 2: train tss = 0.7250 : val tss = 0.6752 ::: train hss = 0.2694 : val hss = 0.1412
Fold 3: train tss = 0.7187 : val tss = 0.6604 ::: train hss = 0.2237 : val hss = 0.2747
Fold 4: train tss = 0.7143 : val tss = 0.6399 ::: train hss = 0.2363 : val hss = 0.1903
mean cv TSS: 0.6699
mean cv HSS: 0.2112
42/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7182 : val tss = 0.5543 ::: train hss = 0.2665 : val hss = 0.1230
Fold 1: train tss = 0.6901 : val tss = 0.6836 ::: train hss = 0.2280 : val hss = 0.2171
Fold 2: train tss = 0.6032 : val tss = 0.6285 ::: train hss = 0.1472 : val hss = 0.0976
Fold 3: train tss = 0.5763 : val tss = 0.6173 ::: train hss = 0.1286 : val hss = 0.1431
Fold 4: train tss = 0.6362 : val tss = 0.6818 ::: train hss = 0.1798 : val hss = 0.1590
mean cv TSS: 0.6331
mean cv HSS: 0.1480
43/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7207 : val tss = 0.6792 ::: train hss = 0.2801 : val hss = 0.2397
Fold 1: train tss = 0.6147 : val tss = 0.6683 ::: train hss = 0.1680 : val hss = 0.1905
Fold 2: train tss = 0.5975 : val tss = 0.6258 ::: train hss = 0.1475 : val hss = 0.0863
Fold 3: train tss = 0.6065 : val tss = 0.6346 ::: train hss = 0.1501 : val hss = 0.1931
Fold 4: train tss = 0.6141 : val tss = 0.5910 ::: train hss = 0.1615 : val hss = 0.2002
mean cv TSS: 0.6398
mean cv HSS: 0.1820
44/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 12035629
Fold 0: train tss = 0.8210 : val tss = 0.6328 ::: train hss = 0.4050 : val hss = 0.2321
Fold 1: train tss = 0.7699 : val tss = 0.6742 ::: train hss = 0.3159 : val hss = 0.2691
Fold 2: train tss = 0.7695 : val tss = 0.6652 ::: train hss = 0.3013 : val hss = 0.1698
Fold 3: train tss = 0.7018 : val tss = 0.6477 ::: train hss = 0.2138 : val hss = 0.2516
Fold 4: train tss = 0.7425 : val tss = 0.5913 ::: train hss = 0.2529 : val hss = 0.2324
mean cv TSS: 0.6422
mean cv HSS: 0.2310
45/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7369 : val tss = 0.6439 ::: train hss = 0.2891 : val hss = 0.2518
Fold 1: train tss = 0.7363 : val tss = 0.6509 ::: train hss = 0.2714 : val hss = 0.2223
Fold 2: train tss = 0.6864 : val tss = 0.6515 ::: train hss = 0.2053 : val hss = 0.1242
Fold 3: train tss = 0.6634 : val tss = 0.6525 ::: train hss = 0.1808 : val hss = 0.2381
Fold 4: train tss = 0.6571 : val tss = 0.6637 ::: train hss = 0.1836 : val hss = 0.1717
mean cv TSS: 0.6525
mean cv HSS: 0.2016
46/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7167 : val tss = 0.6730 ::: train hss = 0.2502 : val hss = 0.2816
Fold 1: train tss = 0.6551 : val tss = 0.6454 ::: train hss = 0.2027 : val hss = 0.2350
Fold 2: train tss = 0.6081 : val tss = 0.6496 ::: train hss = 0.1477 : val hss = 0.0958
Fold 3: train tss = 0.6252 : val tss = 0.6640 ::: train hss = 0.1668 : val hss = 0.2323
Fold 4: train tss = 0.6173 : val tss = 0.6530 ::: train hss = 0.1603 : val hss = 0.1707
mean cv TSS: 0.6570
mean cv HSS: 0.2031
47/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7063 : val tss = 0.6729 ::: train hss = 0.2366 : val hss = 0.2414
Fold 1: train tss = 0.6067 : val tss = 0.7382 ::: train hss = 0.1616 : val hss = 0.1568
Fold 2: train tss = 0.5932 : val tss = 0.6799 ::: train hss = 0.1390 : val hss = 0.1264
Fold 3: train tss = 0.6570 : val tss = 0.6084 ::: train hss = 0.1853 : val hss = 0.1451
Fold 4: train tss = 0.6239 : val tss = 0.6227 ::: train hss = 0.1649 : val hss = 0.1418
mean cv TSS: 0.6644
mean cv HSS: 0.1623
48/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7035 : val tss = 0.6659 ::: train hss = 0.2482 : val hss = 0.2494
Fold 1: train tss = 0.7305 : val tss = 0.7303 ::: train hss = 0.2715 : val hss = 0.1521
Fold 2: train tss = 0.7495 : val tss = 0.6365 ::: train hss = 0.2710 : val hss = 0.0819
Fold 3: train tss = 0.6933 : val tss = 0.6180 ::: train hss = 0.1955 : val hss = 0.1424
Fold 4: train tss = 0.7228 : val tss = 0.6711 ::: train hss = 0.2421 : val hss = 0.1411
mean cv TSS: 0.6644
mean cv HSS: 0.1534
49/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7082 : val tss = 0.6657 ::: train hss = 0.2510 : val hss = 0.2340
Fold 1: train tss = 0.7167 : val tss = 0.7296 ::: train hss = 0.2575 : val hss = 0.1552
Fold 2: train tss = 0.7187 : val tss = 0.6690 ::: train hss = 0.2278 : val hss = 0.1339
Fold 3: train tss = 0.6925 : val tss = 0.6599 ::: train hss = 0.1877 : val hss = 0.2344
Fold 4: train tss = 0.6684 : val tss = 0.6494 ::: train hss = 0.1820 : val hss = 0.1561
mean cv TSS: 0.6747
mean cv HSS: 0.1827
50/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7393 : val tss = 0.6385 ::: train hss = 0.2848 : val hss = 0.2723
Fold 1: train tss = 0.6013 : val tss = 0.7169 ::: train hss = 0.1625 : val hss = 0.1128
Fold 2: train tss = 0.6189 : val tss = 0.6243 ::: train hss = 0.1457 : val hss = 0.0905
Fold 3: train tss = 0.6022 : val tss = 0.6236 ::: train hss = 0.1289 : val hss = 0.1772
Fold 4: train tss = 0.6328 : val tss = 0.6769 ::: train hss = 0.1664 : val hss = 0.1532
mean cv TSS: 0.6561
mean cv HSS: 0.1612
51/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6514 : val tss = 0.6502 ::: train hss = 0.1952 : val hss = 0.1960
Fold 1: train tss = 0.6062 : val tss = 0.7284 ::: train hss = 0.1685 : val hss = 0.1061
Fold 2: train tss = 0.6158 : val tss = 0.6299 ::: train hss = 0.1420 : val hss = 0.1771
Fold 3: train tss = 0.6027 : val tss = 0.6310 ::: train hss = 0.1429 : val hss = 0.1583
Fold 4: train tss = 0.6171 : val tss = 0.6415 ::: train hss = 0.1511 : val hss = 0.1691
mean cv TSS: 0.6562
mean cv HSS: 0.1613
52/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7670 : val tss = 0.6444 ::: train hss = 0.3090 : val hss = 0.2305
Fold 1: train tss = 0.7140 : val tss = 0.6582 ::: train hss = 0.2478 : val hss = 0.2659
Fold 2: train tss = 0.7198 : val tss = 0.6119 ::: train hss = 0.2166 : val hss = 0.0725
Fold 3: train tss = 0.6781 : val tss = 0.6611 ::: train hss = 0.1739 : val hss = 0.1833
Fold 4: train tss = 0.6981 : val tss = 0.6153 ::: train hss = 0.2150 : val hss = 0.2208
mean cv TSS: 0.6382
mean cv HSS: 0.1946
53/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7520 : val tss = 0.6515 ::: train hss = 0.2857 : val hss = 0.2504
Fold 1: train tss = 0.6959 : val tss = 0.6876 ::: train hss = 0.2275 : val hss = 0.1293
Fold 2: train tss = 0.6570 : val tss = 0.6587 ::: train hss = 0.1792 : val hss = 0.1269
Fold 3: train tss = 0.6538 : val tss = 0.6507 ::: train hss = 0.1605 : val hss = 0.1809
Fold 4: train tss = 0.6585 : val tss = 0.5864 ::: train hss = 0.1841 : val hss = 0.2040
mean cv TSS: 0.6470
mean cv HSS: 0.1783
54/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7129 : val tss = 0.6742 ::: train hss = 0.2715 : val hss = 0.2408
Fold 1: train tss = 0.6034 : val tss = 0.7060 ::: train hss = 0.1712 : val hss = 0.1071
Fold 2: train tss = 0.6032 : val tss = 0.6173 ::: train hss = 0.1480 : val hss = 0.0766
Fold 3: train tss = 0.6311 : val tss = 0.6453 ::: train hss = 0.1766 : val hss = 0.1976
Fold 4: train tss = 0.6165 : val tss = 0.6784 ::: train hss = 0.1605 : val hss = 0.1328
mean cv TSS: 0.6642
mean cv HSS: 0.1510
55/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 6221357
Fold 0: train tss = 0.6431 : val tss = 0.6279 ::: train hss = 0.1906 : val hss = 0.1938
Fold 1: train tss = 0.6105 : val tss = 0.7060 ::: train hss = 0.1701 : val hss = 0.1485
Fold 2: train tss = 0.6163 : val tss = 0.6578 ::: train hss = 0.1528 : val hss = 0.1492
Fold 3: train tss = 0.6407 : val tss = 0.6107 ::: train hss = 0.1731 : val hss = 0.1415
Fold 4: train tss = 0.5976 : val tss = 0.6882 ::: train hss = 0.1489 : val hss = 0.1759
mean cv TSS: 0.6581
mean cv HSS: 0.1618
56/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7144 : val tss = 0.6617 ::: train hss = 0.2548 : val hss = 0.2379
Fold 1: train tss = 0.7243 : val tss = 0.7250 ::: train hss = 0.2637 : val hss = 0.1663
Fold 2: train tss = 0.7448 : val tss = 0.6293 ::: train hss = 0.2667 : val hss = 0.0753
Fold 3: train tss = 0.7152 : val tss = 0.6471 ::: train hss = 0.2207 : val hss = 0.1764
Fold 4: train tss = 0.7189 : val tss = 0.6519 ::: train hss = 0.2350 : val hss = 0.1651
mean cv TSS: 0.6630
mean cv HSS: 0.1642
57/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7019 : val tss = 0.6624 ::: train hss = 0.2447 : val hss = 0.2439
Fold 1: train tss = 0.7115 : val tss = 0.7164 ::: train hss = 0.2517 : val hss = 0.1457
Fold 2: train tss = 0.7161 : val tss = 0.6774 ::: train hss = 0.2313 : val hss = 0.1320
Fold 3: train tss = 0.6926 : val tss = 0.6832 ::: train hss = 0.1842 : val hss = 0.2300
Fold 4: train tss = 0.6600 : val tss = 0.6740 ::: train hss = 0.1797 : val hss = 0.1698
mean cv TSS: 0.6827
mean cv HSS: 0.1843
58/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7521 : val tss = 0.6777 ::: train hss = 0.3006 : val hss = 0.2903
Fold 1: train tss = 0.6159 : val tss = 0.6751 ::: train hss = 0.1662 : val hss = 0.2241
Fold 2: train tss = 0.5801 : val tss = 0.5831 ::: train hss = 0.1408 : val hss = 0.0642
Fold 3: train tss = 0.6086 : val tss = 0.6701 ::: train hss = 0.1485 : val hss = 0.1989
Fold 4: train tss = 0.6232 : val tss = 0.6836 ::: train hss = 0.1631 : val hss = 0.1413
mean cv TSS: 0.6579
mean cv HSS: 0.1838
59/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6417 : val tss = 0.6663 ::: train hss = 0.1840 : val hss = 0.2895
Fold 1: train tss = 0.5990 : val tss = 0.7270 ::: train hss = 0.1526 : val hss = 0.1517
Fold 2: train tss = 0.5990 : val tss = 0.6531 ::: train hss = 0.1425 : val hss = 0.1325
Fold 3: train tss = 0.6134 : val tss = 0.6545 ::: train hss = 0.1574 : val hss = 0.2121
Fold 4: train tss = 0.6186 : val tss = 0.6698 ::: train hss = 0.1563 : val hss = 0.1702
mean cv TSS: 0.6741
mean cv HSS: 0.1912
60/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7738 : val tss = 0.6378 ::: train hss = 0.3199 : val hss = 0.2301
Fold 1: train tss = 0.7289 : val tss = 0.7074 ::: train hss = 0.2628 : val hss = 0.1191
Fold 2: train tss = 0.7032 : val tss = 0.6455 ::: train hss = 0.2319 : val hss = 0.1631
Fold 3: train tss = 0.6716 : val tss = 0.6298 ::: train hss = 0.1883 : val hss = 0.1588
Fold 4: train tss = 0.6709 : val tss = 0.6405 ::: train hss = 0.1883 : val hss = 0.1991
mean cv TSS: 0.6522
mean cv HSS: 0.1741
61/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7695 : val tss = 0.6727 ::: train hss = 0.3142 : val hss = 0.2418
Fold 1: train tss = 0.6679 : val tss = 0.7246 ::: train hss = 0.2007 : val hss = 0.1719
Fold 2: train tss = 0.6605 : val tss = 0.6473 ::: train hss = 0.1917 : val hss = 0.0930
Fold 3: train tss = 0.6455 : val tss = 0.6576 ::: train hss = 0.1672 : val hss = 0.1837
Fold 4: train tss = 0.6448 : val tss = 0.5861 ::: train hss = 0.1727 : val hss = 0.1878
mean cv TSS: 0.6576
mean cv HSS: 0.1756
62/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7160 : val tss = 0.6863 ::: train hss = 0.2482 : val hss = 0.2808
Fold 1: train tss = 0.6345 : val tss = 0.6801 ::: train hss = 0.1777 : val hss = 0.1477
Fold 2: train tss = 0.6094 : val tss = 0.6463 ::: train hss = 0.1471 : val hss = 0.0955
Fold 3: train tss = 0.6217 : val tss = 0.6548 ::: train hss = 0.1564 : val hss = 0.2190
Fold 4: train tss = 0.6110 : val tss = 0.6635 ::: train hss = 0.1484 : val hss = 0.1448
mean cv TSS: 0.6662
mean cv HSS: 0.1776
63/256
{'batch_size': 512, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6917 : val tss = 0.6706 ::: train hss = 0.2256 : val hss = 0.2693
Fold 1: train tss = 0.6279 : val tss = 0.7489 ::: train hss = 0.1800 : val hss = 0.1411
Fold 2: train tss = 0.6066 : val tss = 0.6542 ::: train hss = 0.1408 : val hss = 0.1378
Fold 3: train tss = 0.6334 : val tss = 0.5864 ::: train hss = 0.1662 : val hss = 0.1275
Fold 4: train tss = 0.6072 : val tss = 0.6349 ::: train hss = 0.1556 : val hss = 0.1806
mean cv TSS: 0.6590
mean cv HSS: 0.1713
64/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6340 : val tss = 0.6584 ::: train hss = 0.1727 : val hss = 0.2170
Fold 1: train tss = 0.6631 : val tss = 0.7218 ::: train hss = 0.1880 : val hss = 0.1865
Fold 2: train tss = 0.6862 : val tss = 0.6193 ::: train hss = 0.1833 : val hss = 0.0714
Fold 3: train tss = 0.6828 : val tss = 0.6563 ::: train hss = 0.1611 : val hss = 0.1949
Fold 4: train tss = 0.6977 : val tss = 0.6402 ::: train hss = 0.1839 : val hss = 0.1793
mean cv TSS: 0.6592
mean cv HSS: 0.1698
65/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6088 : val tss = 0.6385 ::: train hss = 0.1529 : val hss = 0.1911
Fold 1: train tss = 0.6343 : val tss = 0.7167 ::: train hss = 0.1685 : val hss = 0.1010
Fold 2: train tss = 0.6726 : val tss = 0.6393 ::: train hss = 0.1710 : val hss = 0.1049
Fold 3: train tss = 0.6437 : val tss = 0.5548 ::: train hss = 0.1404 : val hss = 0.1104
Fold 4: train tss = 0.6509 : val tss = 0.6712 ::: train hss = 0.1542 : val hss = 0.1354
mean cv TSS: 0.6441
mean cv HSS: 0.1286
66/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 1144909
Fold 0: train tss = 0.7512 : val tss = 0.6648 ::: train hss = 0.2734 : val hss = 0.2157
Fold 1: train tss = 0.6350 : val tss = 0.7463 ::: train hss = 0.1725 : val hss = 0.1298
Fold 2: train tss = 0.6139 : val tss = 0.6569 ::: train hss = 0.1302 : val hss = 0.0989
Fold 3: train tss = 0.6327 : val tss = 0.6300 ::: train hss = 0.1374 : val hss = 0.1506
Fold 4: train tss = 0.6304 : val tss = 0.6381 ::: train hss = 0.1424 : val hss = 0.1389
mean cv TSS: 0.6672
mean cv HSS: 0.1468
67/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6790 : val tss = 0.6668 ::: train hss = 0.1977 : val hss = 0.2567
Fold 1: train tss = 0.5960 : val tss = 0.6798 ::: train hss = 0.1587 : val hss = 0.0817
Fold 2: train tss = 0.6014 : val tss = 0.6461 ::: train hss = 0.1300 : val hss = 0.0918
Fold 3: train tss = 0.6176 : val tss = 0.5908 ::: train hss = 0.1286 : val hss = 0.1238
Fold 4: train tss = 0.6074 : val tss = 0.6328 ::: train hss = 0.1318 : val hss = 0.1417
mean cv TSS: 0.6433
mean cv HSS: 0.1392
68/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6960 : val tss = 0.6367 ::: train hss = 0.2189 : val hss = 0.2165
Fold 1: train tss = 0.6702 : val tss = 0.7025 ::: train hss = 0.1953 : val hss = 0.1046
Fold 2: train tss = 0.6584 : val tss = 0.6649 ::: train hss = 0.1535 : val hss = 0.1062
Fold 3: train tss = 0.6379 : val tss = 0.5458 ::: train hss = 0.1369 : val hss = 0.1014
Fold 4: train tss = 0.6612 : val tss = 0.6512 ::: train hss = 0.1585 : val hss = 0.1409
mean cv TSS: 0.6402
mean cv HSS: 0.1339
69/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6440 : val tss = 0.5391 ::: train hss = 0.1861 : val hss = 0.1234
Fold 1: train tss = 0.6406 : val tss = 0.7293 ::: train hss = 0.1757 : val hss = 0.1025
Fold 2: train tss = 0.6218 : val tss = 0.5793 ::: train hss = 0.1343 : val hss = 0.0601
Fold 3: train tss = 0.6259 : val tss = 0.6414 ::: train hss = 0.1345 : val hss = 0.1598
Fold 4: train tss = 0.6361 : val tss = 0.6543 ::: train hss = 0.1456 : val hss = 0.1255
mean cv TSS: 0.6287
mean cv HSS: 0.1143
70/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7506 : val tss = 0.6616 ::: train hss = 0.2801 : val hss = 0.2531
Fold 1: train tss = 0.5947 : val tss = 0.7430 ::: train hss = 0.1453 : val hss = 0.1161
Fold 2: train tss = 0.5798 : val tss = 0.5930 ::: train hss = 0.1210 : val hss = 0.0666
Fold 3: train tss = 0.6281 : val tss = 0.5961 ::: train hss = 0.1362 : val hss = 0.1314
Fold 4: train tss = 0.5981 : val tss = 0.6438 ::: train hss = 0.1258 : val hss = 0.1388
mean cv TSS: 0.6475
mean cv HSS: 0.1412
71/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7228 : val tss = 0.6892 ::: train hss = 0.2482 : val hss = 0.2701
Fold 1: train tss = 0.5973 : val tss = 0.7638 ::: train hss = 0.1496 : val hss = 0.1549
Fold 2: train tss = 0.5777 : val tss = 0.4960 ::: train hss = 0.1213 : val hss = 0.0388
Fold 3: train tss = 0.6182 : val tss = 0.6154 ::: train hss = 0.1364 : val hss = 0.2019
Fold 4: train tss = 0.5948 : val tss = 0.6577 ::: train hss = 0.1258 : val hss = 0.1014
mean cv TSS: 0.6444
mean cv HSS: 0.1534
72/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6581 : val tss = 0.6625 ::: train hss = 0.1887 : val hss = 0.2324
Fold 1: train tss = 0.6798 : val tss = 0.7369 ::: train hss = 0.2041 : val hss = 0.1107
Fold 2: train tss = 0.6985 : val tss = 0.6198 ::: train hss = 0.1893 : val hss = 0.0761
Fold 3: train tss = 0.6875 : val tss = 0.6590 ::: train hss = 0.1661 : val hss = 0.1951
Fold 4: train tss = 0.7030 : val tss = 0.6511 ::: train hss = 0.1860 : val hss = 0.1419
mean cv TSS: 0.6659
mean cv HSS: 0.1512
73/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6237 : val tss = 0.6546 ::: train hss = 0.1619 : val hss = 0.2162
Fold 1: train tss = 0.6649 : val tss = 0.6955 ::: train hss = 0.1907 : val hss = 0.0990
Fold 2: train tss = 0.6483 : val tss = 0.6441 ::: train hss = 0.1496 : val hss = 0.0892
Fold 3: train tss = 0.6597 : val tss = 0.6639 ::: train hss = 0.1493 : val hss = 0.1892
Fold 4: train tss = 0.6589 : val tss = 0.6368 ::: train hss = 0.1603 : val hss = 0.1370
mean cv TSS: 0.6590
mean cv HSS: 0.1461
74/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7741 : val tss = 0.6284 ::: train hss = 0.2969 : val hss = 0.2771
Fold 1: train tss = 0.6900 : val tss = 0.6950 ::: train hss = 0.2164 : val hss = 0.1868
Fold 2: train tss = 0.6108 : val tss = 0.6204 ::: train hss = 0.1299 : val hss = 0.0770
Fold 3: train tss = 0.6142 : val tss = 0.6477 ::: train hss = 0.1254 : val hss = 0.1681
Fold 4: train tss = 0.6402 : val tss = 0.6374 ::: train hss = 0.1494 : val hss = 0.1382
mean cv TSS: 0.6458
mean cv HSS: 0.1694
75/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7237 : val tss = 0.6543 ::: train hss = 0.2477 : val hss = 0.2452
Fold 1: train tss = 0.5913 : val tss = 0.7551 ::: train hss = 0.1453 : val hss = 0.1449
Fold 2: train tss = 0.5991 : val tss = 0.5595 ::: train hss = 0.1335 : val hss = 0.0529
Fold 3: train tss = 0.6237 : val tss = 0.6365 ::: train hss = 0.1371 : val hss = 0.1531
Fold 4: train tss = 0.6127 : val tss = 0.6520 ::: train hss = 0.1372 : val hss = 0.1131
mean cv TSS: 0.6515
mean cv HSS: 0.1419
76/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7151 : val tss = 0.6640 ::: train hss = 0.2302 : val hss = 0.2618
Fold 1: train tss = 0.6987 : val tss = 0.6754 ::: train hss = 0.2180 : val hss = 0.1571
Fold 2: train tss = 0.6912 : val tss = 0.6363 ::: train hss = 0.1808 : val hss = 0.0934
Fold 3: train tss = 0.6486 : val tss = 0.6304 ::: train hss = 0.1405 : val hss = 0.1557
Fold 4: train tss = 0.6630 : val tss = 0.6320 ::: train hss = 0.1637 : val hss = 0.1707
mean cv TSS: 0.6476
mean cv HSS: 0.1677
77/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 2273357
Fold 0: train tss = 0.7050 : val tss = 0.6800 ::: train hss = 0.2295 : val hss = 0.2624
Fold 1: train tss = 0.6238 : val tss = 0.7461 ::: train hss = 0.1601 : val hss = 0.1503
Fold 2: train tss = 0.6134 : val tss = 0.5968 ::: train hss = 0.1299 : val hss = 0.0663
Fold 3: train tss = 0.6308 : val tss = 0.6039 ::: train hss = 0.1340 : val hss = 0.1322
Fold 4: train tss = 0.6146 : val tss = 0.6854 ::: train hss = 0.1365 : val hss = 0.1325
mean cv TSS: 0.6624
mean cv HSS: 0.1487
78/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6932 : val tss = 0.5939 ::: train hss = 0.2153 : val hss = 0.1525
Fold 1: train tss = 0.6424 : val tss = 0.7229 ::: train hss = 0.1726 : val hss = 0.1268
Fold 2: train tss = 0.6140 : val tss = 0.5864 ::: train hss = 0.1410 : val hss = 0.0633
Fold 3: train tss = 0.6258 : val tss = 0.5994 ::: train hss = 0.1347 : val hss = 0.1308
Fold 4: train tss = 0.6141 : val tss = 0.6567 ::: train hss = 0.1337 : val hss = 0.1241
mean cv TSS: 0.6319
mean cv HSS: 0.1195
79/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6552 : val tss = 0.6397 ::: train hss = 0.1918 : val hss = 0.2192
Fold 1: train tss = 0.6072 : val tss = 0.7320 ::: train hss = 0.1556 : val hss = 0.1420
Fold 2: train tss = 0.5888 : val tss = 0.5654 ::: train hss = 0.1195 : val hss = 0.1671
Fold 3: train tss = 0.6234 : val tss = 0.6419 ::: train hss = 0.1383 : val hss = 0.1985
Fold 4: train tss = 0.5837 : val tss = 0.6605 ::: train hss = 0.1174 : val hss = 0.1057
mean cv TSS: 0.6479
mean cv HSS: 0.1665
80/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6258 : val tss = 0.6486 ::: train hss = 0.1681 : val hss = 0.2086
Fold 1: train tss = 0.6442 : val tss = 0.7379 ::: train hss = 0.1777 : val hss = 0.1607
Fold 2: train tss = 0.6609 : val tss = 0.6511 ::: train hss = 0.1619 : val hss = 0.0912
Fold 3: train tss = 0.6612 : val tss = 0.5703 ::: train hss = 0.1501 : val hss = 0.1138
Fold 4: train tss = 0.6740 : val tss = 0.6424 ::: train hss = 0.1678 : val hss = 0.1555
mean cv TSS: 0.6501
mean cv HSS: 0.1459
81/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.5810 : val tss = 0.6569 ::: train hss = 0.1378 : val hss = 0.1986
Fold 1: train tss = 0.6324 : val tss = 0.7095 ::: train hss = 0.1707 : val hss = 0.0855
Fold 2: train tss = 0.6344 : val tss = 0.5726 ::: train hss = 0.1463 : val hss = 0.0569
Fold 3: train tss = 0.6302 : val tss = 0.5495 ::: train hss = 0.1326 : val hss = 0.1044
Fold 4: train tss = 0.6570 : val tss = 0.6223 ::: train hss = 0.1529 : val hss = 0.1450
mean cv TSS: 0.6222
mean cv HSS: 0.1181
82/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7122 : val tss = 0.6377 ::: train hss = 0.2276 : val hss = 0.3402
Fold 1: train tss = 0.6302 : val tss = 0.7354 ::: train hss = 0.1676 : val hss = 0.1101
Fold 2: train tss = 0.6187 : val tss = 0.6146 ::: train hss = 0.1399 : val hss = 0.0700
Fold 3: train tss = 0.6057 : val tss = 0.5723 ::: train hss = 0.1230 : val hss = 0.1137
Fold 4: train tss = 0.6204 : val tss = 0.6651 ::: train hss = 0.1374 : val hss = 0.1272
mean cv TSS: 0.6450
mean cv HSS: 0.1522
83/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6833 : val tss = 0.6350 ::: train hss = 0.2109 : val hss = 0.2298
Fold 1: train tss = 0.5963 : val tss = 0.7416 ::: train hss = 0.1487 : val hss = 0.1127
Fold 2: train tss = 0.5968 : val tss = 0.5927 ::: train hss = 0.1277 : val hss = 0.0665
Fold 3: train tss = 0.5984 : val tss = 0.6062 ::: train hss = 0.1188 : val hss = 0.1391
Fold 4: train tss = 0.6047 : val tss = 0.6659 ::: train hss = 0.1307 : val hss = 0.1199
mean cv TSS: 0.6483
mean cv HSS: 0.1336
84/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6927 : val tss = 0.6552 ::: train hss = 0.2161 : val hss = 0.2335
Fold 1: train tss = 0.6464 : val tss = 0.7338 ::: train hss = 0.1815 : val hss = 0.1602
Fold 2: train tss = 0.6673 : val tss = 0.6232 ::: train hss = 0.1621 : val hss = 0.0778
Fold 3: train tss = 0.6488 : val tss = 0.5937 ::: train hss = 0.1464 : val hss = 0.1275
Fold 4: train tss = 0.6514 : val tss = 0.6421 ::: train hss = 0.1551 : val hss = 0.1182
mean cv TSS: 0.6496
mean cv HSS: 0.1434
85/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6677 : val tss = 0.6108 ::: train hss = 0.2041 : val hss = 0.1707
Fold 1: train tss = 0.6382 : val tss = 0.7064 ::: train hss = 0.1722 : val hss = 0.0866
Fold 2: train tss = 0.6269 : val tss = 0.5897 ::: train hss = 0.1422 : val hss = 0.0662
Fold 3: train tss = 0.6353 : val tss = 0.6060 ::: train hss = 0.1403 : val hss = 0.1338
Fold 4: train tss = 0.6226 : val tss = 0.6476 ::: train hss = 0.1370 : val hss = 0.1469
mean cv TSS: 0.6321
mean cv HSS: 0.1209
86/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7033 : val tss = 0.6436 ::: train hss = 0.2279 : val hss = 0.1916
Fold 1: train tss = 0.5988 : val tss = 0.7395 ::: train hss = 0.1496 : val hss = 0.1051
Fold 2: train tss = 0.5884 : val tss = 0.6169 ::: train hss = 0.1248 : val hss = 0.0729
Fold 3: train tss = 0.6016 : val tss = 0.6047 ::: train hss = 0.1227 : val hss = 0.1321
Fold 4: train tss = 0.6008 : val tss = 0.6551 ::: train hss = 0.1227 : val hss = 0.1313
mean cv TSS: 0.6520
mean cv HSS: 0.1266
87/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6657 : val tss = 0.6448 ::: train hss = 0.1977 : val hss = 0.2082
Fold 1: train tss = 0.5928 : val tss = 0.6962 ::: train hss = 0.1479 : val hss = 0.1638
Fold 2: train tss = 0.5786 : val tss = 0.5634 ::: train hss = 0.1183 : val hss = 0.0567
Fold 3: train tss = 0.5900 : val tss = 0.5947 ::: train hss = 0.1186 : val hss = 0.1255
Fold 4: train tss = 0.5842 : val tss = 0.6024 ::: train hss = 0.1168 : val hss = 0.1686
mean cv TSS: 0.6203
mean cv HSS: 0.1446
88/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 2273357
Fold 0: train tss = 0.6394 : val tss = 0.6602 ::: train hss = 0.1771 : val hss = 0.2201
Fold 1: train tss = 0.6379 : val tss = 0.7302 ::: train hss = 0.1704 : val hss = 0.1661
Fold 2: train tss = 0.6828 : val tss = 0.6736 ::: train hss = 0.1736 : val hss = 0.1135
Fold 3: train tss = 0.6552 : val tss = 0.5494 ::: train hss = 0.1503 : val hss = 0.1025
Fold 4: train tss = 0.6675 : val tss = 0.6394 ::: train hss = 0.1592 : val hss = 0.1551
mean cv TSS: 0.6506
mean cv HSS: 0.1515
89/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6160 : val tss = 0.6446 ::: train hss = 0.1602 : val hss = 0.2042
Fold 1: train tss = 0.6326 : val tss = 0.7298 ::: train hss = 0.1694 : val hss = 0.1163
Fold 2: train tss = 0.6656 : val tss = 0.6372 ::: train hss = 0.1626 : val hss = 0.0880
Fold 3: train tss = 0.6373 : val tss = 0.5433 ::: train hss = 0.1372 : val hss = 0.1002
Fold 4: train tss = 0.6581 : val tss = 0.6465 ::: train hss = 0.1589 : val hss = 0.1545
mean cv TSS: 0.6403
mean cv HSS: 0.1326
90/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7649 : val tss = 0.6429 ::: train hss = 0.2983 : val hss = 0.2932
Fold 1: train tss = 0.6503 : val tss = 0.7540 ::: train hss = 0.1834 : val hss = 0.1210
Fold 2: train tss = 0.6110 : val tss = 0.5454 ::: train hss = 0.1315 : val hss = 0.0491
Fold 3: train tss = 0.6090 : val tss = 0.6129 ::: train hss = 0.1211 : val hss = 0.1374
Fold 4: train tss = 0.6112 : val tss = 0.6650 ::: train hss = 0.1368 : val hss = 0.1228
mean cv TSS: 0.6440
mean cv HSS: 0.1447
91/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7272 : val tss = 0.6169 ::: train hss = 0.2419 : val hss = 0.1952
Fold 1: train tss = 0.6020 : val tss = 0.7502 ::: train hss = 0.1515 : val hss = 0.1568
Fold 2: train tss = 0.6219 : val tss = 0.6281 ::: train hss = 0.1371 : val hss = 0.0836
Fold 3: train tss = 0.6211 : val tss = 0.6508 ::: train hss = 0.1345 : val hss = 0.1707
Fold 4: train tss = 0.5988 : val tss = 0.6659 ::: train hss = 0.1287 : val hss = 0.1108
mean cv TSS: 0.6624
mean cv HSS: 0.1434
92/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6727 : val tss = 0.6497 ::: train hss = 0.2038 : val hss = 0.2181
Fold 1: train tss = 0.6633 : val tss = 0.6964 ::: train hss = 0.1923 : val hss = 0.0775
Fold 2: train tss = 0.6532 : val tss = 0.6331 ::: train hss = 0.1562 : val hss = 0.0886
Fold 3: train tss = 0.6559 : val tss = 0.6113 ::: train hss = 0.1460 : val hss = 0.1394
Fold 4: train tss = 0.6627 : val tss = 0.6373 ::: train hss = 0.1649 : val hss = 0.1704
mean cv TSS: 0.6456
mean cv HSS: 0.1388
93/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6581 : val tss = 0.6684 ::: train hss = 0.1873 : val hss = 0.2445
Fold 1: train tss = 0.6246 : val tss = 0.7243 ::: train hss = 0.1634 : val hss = 0.1011
Fold 2: train tss = 0.6293 : val tss = 0.5768 ::: train hss = 0.1394 : val hss = 0.0653
Fold 3: train tss = 0.6280 : val tss = 0.6014 ::: train hss = 0.1324 : val hss = 0.1270
Fold 4: train tss = 0.6336 : val tss = 0.6411 ::: train hss = 0.1428 : val hss = 0.1526
mean cv TSS: 0.6424
mean cv HSS: 0.1381
94/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7173 : val tss = 0.6738 ::: train hss = 0.2516 : val hss = 0.2541
Fold 1: train tss = 0.6063 : val tss = 0.6878 ::: train hss = 0.1563 : val hss = 0.1360
Fold 2: train tss = 0.6084 : val tss = 0.5773 ::: train hss = 0.1320 : val hss = 0.0615
Fold 3: train tss = 0.6190 : val tss = 0.5744 ::: train hss = 0.1283 : val hss = 0.1164
Fold 4: train tss = 0.6003 : val tss = 0.6496 ::: train hss = 0.1254 : val hss = 0.1157
mean cv TSS: 0.6326
mean cv HSS: 0.1368
95/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7222 : val tss = 0.6569 ::: train hss = 0.2509 : val hss = 0.2790
Fold 1: train tss = 0.6017 : val tss = 0.6741 ::: train hss = 0.1566 : val hss = 0.1023
Fold 2: train tss = 0.5761 : val tss = 0.6084 ::: train hss = 0.1214 : val hss = 0.0748
Fold 3: train tss = 0.6157 : val tss = 0.6164 ::: train hss = 0.1399 : val hss = 0.1491
Fold 4: train tss = 0.5602 : val tss = 0.6652 ::: train hss = 0.1069 : val hss = 0.0857
mean cv TSS: 0.6442
mean cv HSS: 0.1382
96/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7533 : val tss = 0.6302 ::: train hss = 0.2722 : val hss = 0.2344
Fold 1: train tss = 0.7653 : val tss = 0.7325 ::: train hss = 0.2832 : val hss = 0.1627
Fold 2: train tss = 0.7436 : val tss = 0.5986 ::: train hss = 0.2161 : val hss = 0.1788
Fold 3: train tss = 0.7419 : val tss = 0.6831 ::: train hss = 0.2100 : val hss = 0.2186
Fold 4: train tss = 0.7186 : val tss = 0.6796 ::: train hss = 0.2101 : val hss = 0.1289
mean cv TSS: 0.6648
mean cv HSS: 0.1847
97/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7329 : val tss = 0.6438 ::: train hss = 0.2523 : val hss = 0.2343
Fold 1: train tss = 0.7122 : val tss = 0.7417 ::: train hss = 0.2303 : val hss = 0.1150
Fold 2: train tss = 0.7333 : val tss = 0.6481 ::: train hss = 0.2243 : val hss = 0.1212
Fold 3: train tss = 0.6939 : val tss = 0.6764 ::: train hss = 0.1738 : val hss = 0.2252
Fold 4: train tss = 0.6955 : val tss = 0.6770 ::: train hss = 0.1787 : val hss = 0.1784
mean cv TSS: 0.6774
mean cv HSS: 0.1748
98/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7185 : val tss = 0.6370 ::: train hss = 0.2313 : val hss = 0.2014
Fold 1: train tss = 0.6289 : val tss = 0.7287 ::: train hss = 0.1661 : val hss = 0.1190
Fold 2: train tss = 0.6025 : val tss = 0.6106 ::: train hss = 0.1243 : val hss = 0.0862
Fold 3: train tss = 0.5825 : val tss = 0.5935 ::: train hss = 0.1122 : val hss = 0.1253
Fold 4: train tss = 0.6236 : val tss = 0.6688 ::: train hss = 0.1378 : val hss = 0.1425
mean cv TSS: 0.6477
mean cv HSS: 0.1349
99/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 6221357
Fold 0: train tss = 0.6336 : val tss = 0.6364 ::: train hss = 0.1703 : val hss = 0.2151
Fold 1: train tss = 0.5603 : val tss = 0.6756 ::: train hss = 0.1278 : val hss = 0.0710
Fold 2: train tss = 0.5736 : val tss = 0.5414 ::: train hss = 0.1169 : val hss = 0.0505
Fold 3: train tss = 0.5828 : val tss = 0.5894 ::: train hss = 0.1173 : val hss = 0.1240
Fold 4: train tss = 0.6022 : val tss = 0.6534 ::: train hss = 0.1314 : val hss = 0.1032
mean cv TSS: 0.6192
mean cv HSS: 0.1128
100/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7902 : val tss = 0.5694 ::: train hss = 0.3449 : val hss = 0.1545
Fold 1: train tss = 0.7543 : val tss = 0.6995 ::: train hss = 0.2698 : val hss = 0.1351
Fold 2: train tss = 0.7170 : val tss = 0.6322 ::: train hss = 0.2039 : val hss = 0.0869
Fold 3: train tss = 0.7297 : val tss = 0.6707 ::: train hss = 0.2036 : val hss = 0.2029
Fold 4: train tss = 0.7264 : val tss = 0.6613 ::: train hss = 0.2044 : val hss = 0.1615
mean cv TSS: 0.6466
mean cv HSS: 0.1482
101/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7484 : val tss = 0.6574 ::: train hss = 0.2840 : val hss = 0.2382
Fold 1: train tss = 0.7122 : val tss = 0.6867 ::: train hss = 0.2303 : val hss = 0.1283
Fold 2: train tss = 0.6542 : val tss = 0.6139 ::: train hss = 0.1502 : val hss = 0.0854
Fold 3: train tss = 0.6249 : val tss = 0.5307 ::: train hss = 0.1333 : val hss = 0.0953
Fold 4: train tss = 0.6387 : val tss = 0.6657 ::: train hss = 0.1470 : val hss = 0.1515
mean cv TSS: 0.6309
mean cv HSS: 0.1397
102/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7155 : val tss = 0.6271 ::: train hss = 0.2464 : val hss = 0.1810
Fold 1: train tss = 0.5585 : val tss = 0.4266 ::: train hss = 0.1345 : val hss = 0.0203
Fold 2: train tss = 0.5899 : val tss = 0.6040 ::: train hss = 0.1165 : val hss = 0.0766
Fold 3: train tss = 0.5969 : val tss = 0.6281 ::: train hss = 0.1176 : val hss = 0.1756
Fold 4: train tss = 0.6036 : val tss = 0.6587 ::: train hss = 0.1306 : val hss = 0.0935
mean cv TSS: 0.5889
mean cv HSS: 0.1094
103/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6454 : val tss = 0.6243 ::: train hss = 0.1856 : val hss = 0.1756
Fold 1: train tss = 0.5869 : val tss = 0.6868 ::: train hss = 0.1447 : val hss = 0.0714
Fold 2: train tss = 0.5856 : val tss = 0.6297 ::: train hss = 0.1195 : val hss = 0.0825
Fold 3: train tss = 0.6508 : val tss = 0.5475 ::: train hss = 0.1565 : val hss = 0.1040
Fold 4: train tss = 0.5918 : val tss = 0.6263 ::: train hss = 0.1260 : val hss = 0.0724
mean cv TSS: 0.6229
mean cv HSS: 0.1012
104/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7512 : val tss = 0.6429 ::: train hss = 0.2698 : val hss = 0.2460
Fold 1: train tss = 0.7519 : val tss = 0.7261 ::: train hss = 0.2693 : val hss = 0.1694
Fold 2: train tss = 0.7684 : val tss = 0.6593 ::: train hss = 0.2552 : val hss = 0.0980
Fold 3: train tss = 0.7629 : val tss = 0.6738 ::: train hss = 0.2301 : val hss = 0.2078
Fold 4: train tss = 0.7287 : val tss = 0.5896 ::: train hss = 0.2092 : val hss = 0.1729
mean cv TSS: 0.6583
mean cv HSS: 0.1788
105/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7385 : val tss = 0.6367 ::: train hss = 0.2586 : val hss = 0.2454
Fold 1: train tss = 0.7244 : val tss = 0.7318 ::: train hss = 0.2393 : val hss = 0.1849
Fold 2: train tss = 0.7297 : val tss = 0.6629 ::: train hss = 0.2170 : val hss = 0.1033
Fold 3: train tss = 0.6804 : val tss = 0.6704 ::: train hss = 0.1593 : val hss = 0.2084
Fold 4: train tss = 0.7155 : val tss = 0.6969 ::: train hss = 0.2035 : val hss = 0.1445
mean cv TSS: 0.6797
mean cv HSS: 0.1773
106/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7271 : val tss = 0.6901 ::: train hss = 0.2521 : val hss = 0.2555
Fold 1: train tss = 0.6784 : val tss = 0.7386 ::: train hss = 0.2071 : val hss = 0.1493
Fold 2: train tss = 0.5640 : val tss = 0.5095 ::: train hss = 0.1116 : val hss = 0.0408
Fold 3: train tss = 0.6102 : val tss = 0.6324 ::: train hss = 0.1191 : val hss = 0.1601
Fold 4: train tss = 0.6167 : val tss = 0.6278 ::: train hss = 0.1348 : val hss = 0.1251
mean cv TSS: 0.6397
mean cv HSS: 0.1462
107/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6723 : val tss = 0.6895 ::: train hss = 0.2045 : val hss = 0.3278
Fold 1: train tss = 0.6024 : val tss = 0.7204 ::: train hss = 0.1517 : val hss = 0.1363
Fold 2: train tss = 0.5763 : val tss = 0.5560 ::: train hss = 0.1141 : val hss = 0.0516
Fold 3: train tss = 0.5881 : val tss = 0.6222 ::: train hss = 0.1183 : val hss = 0.1477
Fold 4: train tss = 0.6136 : val tss = 0.6620 ::: train hss = 0.1410 : val hss = 0.1328
mean cv TSS: 0.6500
mean cv HSS: 0.1592
108/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7704 : val tss = 0.5255 ::: train hss = 0.3011 : val hss = 0.1097
Fold 1: train tss = 0.7595 : val tss = 0.7332 ::: train hss = 0.2904 : val hss = 0.1409
Fold 2: train tss = 0.7686 : val tss = 0.5701 ::: train hss = 0.2708 : val hss = 0.0618
Fold 3: train tss = 0.7204 : val tss = 0.6564 ::: train hss = 0.1881 : val hss = 0.1958
Fold 4: train tss = 0.7241 : val tss = 0.6720 ::: train hss = 0.2061 : val hss = 0.1605
mean cv TSS: 0.6315
mean cv HSS: 0.1338
109/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7705 : val tss = 0.6149 ::: train hss = 0.2903 : val hss = 0.3154
Fold 1: train tss = 0.6781 : val tss = 0.6935 ::: train hss = 0.1993 : val hss = 0.0935
Fold 2: train tss = 0.6673 : val tss = 0.6372 ::: train hss = 0.1671 : val hss = 0.0874
Fold 3: train tss = 0.6322 : val tss = 0.5831 ::: train hss = 0.1381 : val hss = 0.1218
Fold 4: train tss = 0.6246 : val tss = 0.6712 ::: train hss = 0.1397 : val hss = 0.1293
mean cv TSS: 0.6400
mean cv HSS: 0.1495
110/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 12035629
Fold 0: train tss = 0.6891 : val tss = 0.6319 ::: train hss = 0.2223 : val hss = 0.1745
Fold 1: train tss = 0.6815 : val tss = 0.7589 ::: train hss = 0.2072 : val hss = 0.1450
Fold 2: train tss = 0.6061 : val tss = 0.5660 ::: train hss = 0.1333 : val hss = 0.2348
Fold 3: train tss = 0.6126 : val tss = 0.6265 ::: train hss = 0.1307 : val hss = 0.1566
Fold 4: train tss = 0.6030 : val tss = 0.6328 ::: train hss = 0.1324 : val hss = 0.1418
mean cv TSS: 0.6432
mean cv HSS: 0.1705
111/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6595 : val tss = 0.4465 ::: train hss = 0.2078 : val hss = 0.0807
Fold 1: train tss = 0.6153 : val tss = 0.6969 ::: train hss = 0.1569 : val hss = 0.0782
Fold 2: train tss = 0.5846 : val tss = 0.6097 ::: train hss = 0.1212 : val hss = 0.0743
Fold 3: train tss = 0.5930 : val tss = 0.6038 ::: train hss = 0.1195 : val hss = 0.1335
Fold 4: train tss = 0.6027 : val tss = 0.6589 ::: train hss = 0.1313 : val hss = 0.0998
mean cv TSS: 0.6032
mean cv HSS: 0.0933
112/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6808 : val tss = 0.6444 ::: train hss = 0.2101 : val hss = 0.2022
Fold 1: train tss = 0.7106 : val tss = 0.7358 ::: train hss = 0.2300 : val hss = 0.1340
Fold 2: train tss = 0.7264 : val tss = 0.6009 ::: train hss = 0.2168 : val hss = 0.0644
Fold 3: train tss = 0.7051 : val tss = 0.6783 ::: train hss = 0.1855 : val hss = 0.2145
Fold 4: train tss = 0.7113 : val tss = 0.6557 ::: train hss = 0.1958 : val hss = 0.1613
mean cv TSS: 0.6630
mean cv HSS: 0.1553
113/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6750 : val tss = 0.6532 ::: train hss = 0.2058 : val hss = 0.2105
Fold 1: train tss = 0.6894 : val tss = 0.7407 ::: train hss = 0.2119 : val hss = 0.1393
Fold 2: train tss = 0.6869 : val tss = 0.6172 ::: train hss = 0.1732 : val hss = 0.0743
Fold 3: train tss = 0.6578 : val tss = 0.6526 ::: train hss = 0.1418 : val hss = 0.1756
Fold 4: train tss = 0.6554 : val tss = 0.6463 ::: train hss = 0.1516 : val hss = 0.1386
mean cv TSS: 0.6620
mean cv HSS: 0.1477
114/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7153 : val tss = 0.6526 ::: train hss = 0.2436 : val hss = 0.1888
Fold 1: train tss = 0.6023 : val tss = 0.7479 ::: train hss = 0.1486 : val hss = 0.1344
Fold 2: train tss = 0.6090 : val tss = 0.6356 ::: train hss = 0.1273 : val hss = 0.1010
Fold 3: train tss = 0.5752 : val tss = 0.5854 ::: train hss = 0.1065 : val hss = 0.1211
Fold 4: train tss = 0.6038 : val tss = 0.6625 ::: train hss = 0.1247 : val hss = 0.1420
mean cv TSS: 0.6568
mean cv HSS: 0.1375
115/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6457 : val tss = 0.5911 ::: train hss = 0.1900 : val hss = 0.1608
Fold 1: train tss = 0.5517 : val tss = 0.6495 ::: train hss = 0.1331 : val hss = 0.0614
Fold 2: train tss = 0.5997 : val tss = 0.6409 ::: train hss = 0.1236 : val hss = 0.0930
Fold 3: train tss = 0.5972 : val tss = 0.6284 ::: train hss = 0.1198 : val hss = 0.1863
Fold 4: train tss = 0.5882 : val tss = 0.6775 ::: train hss = 0.1275 : val hss = 0.1070
mean cv TSS: 0.6375
mean cv HSS: 0.1217
116/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7537 : val tss = 0.6277 ::: train hss = 0.2756 : val hss = 0.2085
Fold 1: train tss = 0.6965 : val tss = 0.7544 ::: train hss = 0.2141 : val hss = 0.1628
Fold 2: train tss = 0.6688 : val tss = 0.6538 ::: train hss = 0.1602 : val hss = 0.0943
Fold 3: train tss = 0.6893 : val tss = 0.6435 ::: train hss = 0.1641 : val hss = 0.1556
Fold 4: train tss = 0.6822 : val tss = 0.6623 ::: train hss = 0.1701 : val hss = 0.1370
mean cv TSS: 0.6684
mean cv HSS: 0.1516
117/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7488 : val tss = 0.6041 ::: train hss = 0.2687 : val hss = 0.1761
Fold 1: train tss = 0.6531 : val tss = 0.6920 ::: train hss = 0.1821 : val hss = 0.0844
Fold 2: train tss = 0.6186 : val tss = 0.5444 ::: train hss = 0.1318 : val hss = 0.0493
Fold 3: train tss = 0.6416 : val tss = 0.6164 ::: train hss = 0.1366 : val hss = 0.1473
Fold 4: train tss = 0.6333 : val tss = 0.6432 ::: train hss = 0.1440 : val hss = 0.1492
mean cv TSS: 0.6200
mean cv HSS: 0.1212
118/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6673 : val tss = 0.6709 ::: train hss = 0.2064 : val hss = 0.2344
Fold 1: train tss = 0.5819 : val tss = 0.4158 ::: train hss = 0.1466 : val hss = 0.0197
Fold 2: train tss = 0.5786 : val tss = 0.6012 ::: train hss = 0.1164 : val hss = 0.0740
Fold 3: train tss = 0.5762 : val tss = 0.5895 ::: train hss = 0.1032 : val hss = 0.1227
Fold 4: train tss = 0.5905 : val tss = 0.6795 ::: train hss = 0.1238 : val hss = 0.0895
mean cv TSS: 0.5914
mean cv HSS: 0.1081
119/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.5700 : val tss = 0.5871 ::: train hss = 0.1360 : val hss = 0.1406
Fold 1: train tss = 0.6002 : val tss = 0.6741 ::: train hss = 0.1563 : val hss = 0.2498
Fold 2: train tss = 0.5820 : val tss = 0.5067 ::: train hss = 0.1145 : val hss = 0.0421
Fold 3: train tss = 0.6346 : val tss = 0.5351 ::: train hss = 0.1457 : val hss = 0.0986
Fold 4: train tss = 0.5822 : val tss = 0.6514 ::: train hss = 0.1182 : val hss = 0.1047
mean cv TSS: 0.5909
mean cv HSS: 0.1272
120/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6918 : val tss = 0.6527 ::: train hss = 0.2189 : val hss = 0.2111
Fold 1: train tss = 0.7072 : val tss = 0.7436 ::: train hss = 0.2253 : val hss = 0.1385
Fold 2: train tss = 0.7182 : val tss = 0.6296 ::: train hss = 0.2064 : val hss = 0.0809
Fold 3: train tss = 0.6992 : val tss = 0.6443 ::: train hss = 0.1802 : val hss = 0.1779
Fold 4: train tss = 0.7069 : val tss = 0.6681 ::: train hss = 0.1918 : val hss = 0.1284
mean cv TSS: 0.6677
mean cv HSS: 0.1474
121/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 12035629
Fold 0: train tss = 0.6832 : val tss = 0.6418 ::: train hss = 0.2106 : val hss = 0.2004
Fold 1: train tss = 0.6928 : val tss = 0.7468 ::: train hss = 0.2132 : val hss = 0.1268
Fold 2: train tss = 0.6802 : val tss = 0.5644 ::: train hss = 0.1732 : val hss = 0.0535
Fold 3: train tss = 0.6737 : val tss = 0.6627 ::: train hss = 0.1532 : val hss = 0.1863
Fold 4: train tss = 0.6531 : val tss = 0.6322 ::: train hss = 0.1506 : val hss = 0.1570
mean cv TSS: 0.6496
mean cv HSS: 0.1448
122/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7228 : val tss = 0.6909 ::: train hss = 0.2485 : val hss = 0.2707
Fold 1: train tss = 0.5989 : val tss = 0.7039 ::: train hss = 0.1573 : val hss = 0.0844
Fold 2: train tss = 0.6257 : val tss = 0.5177 ::: train hss = 0.1451 : val hss = 0.0431
Fold 3: train tss = 0.5909 : val tss = 0.6198 ::: train hss = 0.1107 : val hss = 0.1453
Fold 4: train tss = 0.6152 : val tss = 0.6571 ::: train hss = 0.1330 : val hss = 0.1153
mean cv TSS: 0.6379
mean cv HSS: 0.1318
123/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7254 : val tss = 0.5598 ::: train hss = 0.2488 : val hss = 0.1311
Fold 1: train tss = 0.5688 : val tss = 0.7214 ::: train hss = 0.1314 : val hss = 0.1522
Fold 2: train tss = 0.5915 : val tss = 0.5980 ::: train hss = 0.1218 : val hss = 0.0715
Fold 3: train tss = 0.5868 : val tss = 0.6281 ::: train hss = 0.1241 : val hss = 0.1706
Fold 4: train tss = 0.5992 : val tss = 0.6325 ::: train hss = 0.1292 : val hss = 0.1303
mean cv TSS: 0.6280
mean cv HSS: 0.1311
124/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7707 : val tss = 0.6065 ::: train hss = 0.2978 : val hss = 0.1714
Fold 1: train tss = 0.7348 : val tss = 0.7033 ::: train hss = 0.2543 : val hss = 0.1449
Fold 2: train tss = 0.6888 : val tss = 0.5952 ::: train hss = 0.1799 : val hss = 0.0636
Fold 3: train tss = 0.6764 : val tss = 0.6338 ::: train hss = 0.1554 : val hss = 0.1610
Fold 4: train tss = 0.6871 : val tss = 0.6734 ::: train hss = 0.1822 : val hss = 0.1104
mean cv TSS: 0.6424
mean cv HSS: 0.1303
125/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7500 : val tss = 0.6419 ::: train hss = 0.2686 : val hss = 0.2187
Fold 1: train tss = 0.6540 : val tss = 0.6757 ::: train hss = 0.1817 : val hss = 0.0870
Fold 2: train tss = 0.6569 : val tss = 0.6402 ::: train hss = 0.1567 : val hss = 0.0989
Fold 3: train tss = 0.6241 : val tss = 0.5856 ::: train hss = 0.1339 : val hss = 0.1193
Fold 4: train tss = 0.6331 : val tss = 0.6733 ::: train hss = 0.1451 : val hss = 0.1450
mean cv TSS: 0.6434
mean cv HSS: 0.1338
126/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6939 : val tss = 0.3902 ::: train hss = 0.2316 : val hss = 0.0658
Fold 1: train tss = 0.6422 : val tss = 0.6629 ::: train hss = 0.1788 : val hss = 0.0614
Fold 2: train tss = 0.5989 : val tss = 0.5639 ::: train hss = 0.1262 : val hss = 0.0567
Fold 3: train tss = 0.6096 : val tss = 0.6016 ::: train hss = 0.1287 : val hss = 0.1334
Fold 4: train tss = 0.6020 : val tss = 0.6626 ::: train hss = 0.1274 : val hss = 0.1046
mean cv TSS: 0.5762
mean cv HSS: 0.0844
127/256
{'batch_size': 512, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6795 : val tss = 0.2227 ::: train hss = 0.2409 : val hss = 0.0275
Fold 1: train tss = 0.6061 : val tss = 0.7548 ::: train hss = 0.1543 : val hss = 0.1436
Fold 2: train tss = 0.5626 : val tss = 0.5863 ::: train hss = 0.1098 : val hss = 0.0635
Fold 3: train tss = 0.6305 : val tss = 0.5819 ::: train hss = 0.1372 : val hss = 0.1188
Fold 4: train tss = 0.5850 : val tss = 0.6568 ::: train hss = 0.1196 : val hss = 0.1143
mean cv TSS: 0.5605
mean cv HSS: 0.0935
128/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6291 : val tss = 0.6554 ::: train hss = 0.1818 : val hss = 0.2216
Fold 1: train tss = 0.6801 : val tss = 0.6974 ::: train hss = 0.2375 : val hss = 0.2042
Fold 2: train tss = 0.7086 : val tss = 0.6752 ::: train hss = 0.2416 : val hss = 0.1490
Fold 3: train tss = 0.7026 : val tss = 0.6503 ::: train hss = 0.2119 : val hss = 0.1915
Fold 4: train tss = 0.7053 : val tss = 0.5765 ::: train hss = 0.2226 : val hss = 0.1934
mean cv TSS: 0.6510
mean cv HSS: 0.1919
129/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6026 : val tss = 0.6694 ::: train hss = 0.1578 : val hss = 0.2234
Fold 1: train tss = 0.6736 : val tss = 0.7116 ::: train hss = 0.2235 : val hss = 0.1993
Fold 2: train tss = 0.6957 : val tss = 0.6724 ::: train hss = 0.2276 : val hss = 0.1446
Fold 3: train tss = 0.6967 : val tss = 0.6662 ::: train hss = 0.2086 : val hss = 0.2211
Fold 4: train tss = 0.7012 : val tss = 0.6125 ::: train hss = 0.2087 : val hss = 0.1930
mean cv TSS: 0.6664
mean cv HSS: 0.1963
130/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7779 : val tss = 0.6571 ::: train hss = 0.3145 : val hss = 0.3481
Fold 1: train tss = 0.7270 : val tss = 0.6738 ::: train hss = 0.2806 : val hss = 0.2516
Fold 2: train tss = 0.6518 : val tss = 0.6577 ::: train hss = 0.1694 : val hss = 0.1098
Fold 3: train tss = 0.6502 : val tss = 0.6359 ::: train hss = 0.1684 : val hss = 0.1657
Fold 4: train tss = 0.6820 : val tss = 0.5738 ::: train hss = 0.2098 : val hss = 0.1973
mean cv TSS: 0.6397
mean cv HSS: 0.2145
131/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7601 : val tss = 0.6646 ::: train hss = 0.3101 : val hss = 0.3609
Fold 1: train tss = 0.6967 : val tss = 0.6382 ::: train hss = 0.2410 : val hss = 0.2464
Fold 2: train tss = 0.6609 : val tss = 0.6622 ::: train hss = 0.1820 : val hss = 0.1413
Fold 3: train tss = 0.6523 : val tss = 0.6529 ::: train hss = 0.1673 : val hss = 0.2220
Fold 4: train tss = 0.6608 : val tss = 0.5778 ::: train hss = 0.1899 : val hss = 0.1827
mean cv TSS: 0.6392
mean cv HSS: 0.2306
132/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 1144909
Fold 0: train tss = 0.6806 : val tss = 0.6759 ::: train hss = 0.2291 : val hss = 0.3050
Fold 1: train tss = 0.7124 : val tss = 0.6781 ::: train hss = 0.2560 : val hss = 0.2192
Fold 2: train tss = 0.7361 : val tss = 0.6813 ::: train hss = 0.2664 : val hss = 0.1811
Fold 3: train tss = 0.7074 : val tss = 0.6590 ::: train hss = 0.2138 : val hss = 0.2020
Fold 4: train tss = 0.6981 : val tss = 0.5246 ::: train hss = 0.2069 : val hss = 0.2204
mean cv TSS: 0.6438
mean cv HSS: 0.2255
133/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6555 : val tss = 0.6721 ::: train hss = 0.2011 : val hss = 0.2922
Fold 1: train tss = 0.7024 : val tss = 0.7353 ::: train hss = 0.2440 : val hss = 0.1888
Fold 2: train tss = 0.7139 : val tss = 0.6061 ::: train hss = 0.2399 : val hss = 0.1918
Fold 3: train tss = 0.6837 : val tss = 0.6320 ::: train hss = 0.1947 : val hss = 0.2371
Fold 4: train tss = 0.6764 : val tss = 0.6214 ::: train hss = 0.2001 : val hss = 0.1905
mean cv TSS: 0.6534
mean cv HSS: 0.2201
134/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7747 : val tss = 0.6381 ::: train hss = 0.3188 : val hss = 0.3458
Fold 1: train tss = 0.6762 : val tss = 0.7694 ::: train hss = 0.2156 : val hss = 0.1595
Fold 2: train tss = 0.6496 : val tss = 0.6666 ::: train hss = 0.1863 : val hss = 0.1181
Fold 3: train tss = 0.6628 : val tss = 0.6010 ::: train hss = 0.1774 : val hss = 0.2517
Fold 4: train tss = 0.6698 : val tss = 0.6040 ::: train hss = 0.1973 : val hss = 0.1729
mean cv TSS: 0.6558
mean cv HSS: 0.2096
135/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7502 : val tss = 0.6064 ::: train hss = 0.2722 : val hss = 0.3418
Fold 1: train tss = 0.6683 : val tss = 0.6175 ::: train hss = 0.2141 : val hss = 0.3183
Fold 2: train tss = 0.6418 : val tss = 0.6471 ::: train hss = 0.1694 : val hss = 0.1379
Fold 3: train tss = 0.6386 : val tss = 0.5834 ::: train hss = 0.1619 : val hss = 0.1773
Fold 4: train tss = 0.6438 : val tss = 0.5832 ::: train hss = 0.1764 : val hss = 0.2017
mean cv TSS: 0.6075
mean cv HSS: 0.2354
136/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6411 : val tss = 0.6799 ::: train hss = 0.1902 : val hss = 0.2644
Fold 1: train tss = 0.6866 : val tss = 0.7095 ::: train hss = 0.2387 : val hss = 0.2111
Fold 2: train tss = 0.7166 : val tss = 0.6760 ::: train hss = 0.2498 : val hss = 0.1467
Fold 3: train tss = 0.6957 : val tss = 0.6608 ::: train hss = 0.2129 : val hss = 0.2206
Fold 4: train tss = 0.7094 : val tss = 0.5691 ::: train hss = 0.2290 : val hss = 0.1820
mean cv TSS: 0.6591
mean cv HSS: 0.2050
137/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6362 : val tss = 0.6842 ::: train hss = 0.1870 : val hss = 0.2566
Fold 1: train tss = 0.6689 : val tss = 0.6930 ::: train hss = 0.2197 : val hss = 0.2107
Fold 2: train tss = 0.6962 : val tss = 0.6668 ::: train hss = 0.2255 : val hss = 0.1444
Fold 3: train tss = 0.6995 : val tss = 0.6661 ::: train hss = 0.2082 : val hss = 0.2137
Fold 4: train tss = 0.7006 : val tss = 0.5815 ::: train hss = 0.2183 : val hss = 0.2183
mean cv TSS: 0.6583
mean cv HSS: 0.2087
138/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.8052 : val tss = 0.6625 ::: train hss = 0.3755 : val hss = 0.3303
Fold 1: train tss = 0.7180 : val tss = 0.7138 ::: train hss = 0.2758 : val hss = 0.1563
Fold 2: train tss = 0.6869 : val tss = 0.6596 ::: train hss = 0.2213 : val hss = 0.1527
Fold 3: train tss = 0.6449 : val tss = 0.6571 ::: train hss = 0.1655 : val hss = 0.1778
Fold 4: train tss = 0.6453 : val tss = 0.6109 ::: train hss = 0.1767 : val hss = 0.1680
mean cv TSS: 0.6608
mean cv HSS: 0.1970
139/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7847 : val tss = 0.6737 ::: train hss = 0.3308 : val hss = 0.3159
Fold 1: train tss = 0.6722 : val tss = 0.7208 ::: train hss = 0.2020 : val hss = 0.1816
Fold 2: train tss = 0.6517 : val tss = 0.6523 ::: train hss = 0.1869 : val hss = 0.1149
Fold 3: train tss = 0.6459 : val tss = 0.6372 ::: train hss = 0.1759 : val hss = 0.1680
Fold 4: train tss = 0.6673 : val tss = 0.5946 ::: train hss = 0.1973 : val hss = 0.2018
mean cv TSS: 0.6557
mean cv HSS: 0.1964
140/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6876 : val tss = 0.6881 ::: train hss = 0.2311 : val hss = 0.3225
Fold 1: train tss = 0.7187 : val tss = 0.7191 ::: train hss = 0.2672 : val hss = 0.2004
Fold 2: train tss = 0.7338 : val tss = 0.6396 ::: train hss = 0.2541 : val hss = 0.1985
Fold 3: train tss = 0.7072 : val tss = 0.6622 ::: train hss = 0.2085 : val hss = 0.2232
Fold 4: train tss = 0.6917 : val tss = 0.6426 ::: train hss = 0.2091 : val hss = 0.1607
mean cv TSS: 0.6703
mean cv HSS: 0.2211
141/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6678 : val tss = 0.6849 ::: train hss = 0.2112 : val hss = 0.3201
Fold 1: train tss = 0.7125 : val tss = 0.7039 ::: train hss = 0.2535 : val hss = 0.2379
Fold 2: train tss = 0.7106 : val tss = 0.6486 ::: train hss = 0.2275 : val hss = 0.1898
Fold 3: train tss = 0.6838 : val tss = 0.6554 ::: train hss = 0.1898 : val hss = 0.2955
Fold 4: train tss = 0.6674 : val tss = 0.6259 ::: train hss = 0.1971 : val hss = 0.1666
mean cv TSS: 0.6637
mean cv HSS: 0.2420
142/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7513 : val tss = 0.6400 ::: train hss = 0.2877 : val hss = 0.3796
Fold 1: train tss = 0.7112 : val tss = 0.7371 ::: train hss = 0.2644 : val hss = 0.1894
Fold 2: train tss = 0.6931 : val tss = 0.5478 ::: train hss = 0.2143 : val hss = 0.2493
Fold 3: train tss = 0.6595 : val tss = 0.5468 ::: train hss = 0.1749 : val hss = 0.3036
Fold 4: train tss = 0.6465 : val tss = 0.5876 ::: train hss = 0.1808 : val hss = 0.1886
mean cv TSS: 0.6119
mean cv HSS: 0.2621
143/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 2273357
Fold 0: train tss = 0.7294 : val tss = 0.6560 ::: train hss = 0.2737 : val hss = 0.3758
Fold 1: train tss = 0.7011 : val tss = 0.6785 ::: train hss = 0.2483 : val hss = 0.2076
Fold 2: train tss = 0.6515 : val tss = 0.6264 ::: train hss = 0.1814 : val hss = 0.1733
Fold 3: train tss = 0.6522 : val tss = 0.6534 ::: train hss = 0.1662 : val hss = 0.2663
Fold 4: train tss = 0.6477 : val tss = 0.6316 ::: train hss = 0.1768 : val hss = 0.1897
mean cv TSS: 0.6492
mean cv HSS: 0.2425
144/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.5854 : val tss = 0.6631 ::: train hss = 0.1460 : val hss = 0.2033
Fold 1: train tss = 0.6762 : val tss = 0.7240 ::: train hss = 0.2339 : val hss = 0.1848
Fold 2: train tss = 0.6854 : val tss = 0.6601 ::: train hss = 0.2249 : val hss = 0.1269
Fold 3: train tss = 0.6864 : val tss = 0.6496 ::: train hss = 0.2004 : val hss = 0.1815
Fold 4: train tss = 0.6917 : val tss = 0.6406 ::: train hss = 0.2116 : val hss = 0.1695
mean cv TSS: 0.6675
mean cv HSS: 0.1732
145/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.5905 : val tss = 0.6758 ::: train hss = 0.1528 : val hss = 0.2377
Fold 1: train tss = 0.6669 : val tss = 0.7178 ::: train hss = 0.2223 : val hss = 0.1924
Fold 2: train tss = 0.6798 : val tss = 0.6572 ::: train hss = 0.2120 : val hss = 0.1224
Fold 3: train tss = 0.6771 : val tss = 0.6455 ::: train hss = 0.1952 : val hss = 0.1805
Fold 4: train tss = 0.6915 : val tss = 0.6260 ::: train hss = 0.2144 : val hss = 0.1908
mean cv TSS: 0.6645
mean cv HSS: 0.1848
146/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7912 : val tss = 0.6169 ::: train hss = 0.3637 : val hss = 0.3329
Fold 1: train tss = 0.7023 : val tss = 0.6717 ::: train hss = 0.2391 : val hss = 0.2061
Fold 2: train tss = 0.6572 : val tss = 0.6246 ::: train hss = 0.1789 : val hss = 0.1593
Fold 3: train tss = 0.6440 : val tss = 0.6197 ::: train hss = 0.1633 : val hss = 0.1969
Fold 4: train tss = 0.6722 : val tss = 0.6413 ::: train hss = 0.1954 : val hss = 0.1502
mean cv TSS: 0.6348
mean cv HSS: 0.2091
147/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7531 : val tss = 0.6469 ::: train hss = 0.3257 : val hss = 0.3210
Fold 1: train tss = 0.6848 : val tss = 0.7267 ::: train hss = 0.2368 : val hss = 0.1256
Fold 2: train tss = 0.6423 : val tss = 0.6684 ::: train hss = 0.1699 : val hss = 0.1131
Fold 3: train tss = 0.6429 : val tss = 0.6181 ::: train hss = 0.1549 : val hss = 0.2008
Fold 4: train tss = 0.6648 : val tss = 0.6242 ::: train hss = 0.1922 : val hss = 0.1927
mean cv TSS: 0.6569
mean cv HSS: 0.1906
148/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6606 : val tss = 0.6828 ::: train hss = 0.2106 : val hss = 0.2817
Fold 1: train tss = 0.6989 : val tss = 0.6987 ::: train hss = 0.2433 : val hss = 0.2054
Fold 2: train tss = 0.6913 : val tss = 0.6745 ::: train hss = 0.1974 : val hss = 0.1153
Fold 3: train tss = 0.6815 : val tss = 0.5935 ::: train hss = 0.1935 : val hss = 0.1358
Fold 4: train tss = 0.6827 : val tss = 0.6426 ::: train hss = 0.1965 : val hss = 0.1607
mean cv TSS: 0.6584
mean cv HSS: 0.1798
149/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.6506 : val tss = 0.6836 ::: train hss = 0.1971 : val hss = 0.2846
Fold 1: train tss = 0.6940 : val tss = 0.7091 ::: train hss = 0.2367 : val hss = 0.2182
Fold 2: train tss = 0.6998 : val tss = 0.6508 ::: train hss = 0.2225 : val hss = 0.1048
Fold 3: train tss = 0.6843 : val tss = 0.6533 ::: train hss = 0.1903 : val hss = 0.2022
Fold 4: train tss = 0.6553 : val tss = 0.6345 ::: train hss = 0.1859 : val hss = 0.1448
mean cv TSS: 0.6663
mean cv HSS: 0.1909
150/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7549 : val tss = 0.6461 ::: train hss = 0.2857 : val hss = 0.3529
Fold 1: train tss = 0.6561 : val tss = 0.7069 ::: train hss = 0.1905 : val hss = 0.1889
Fold 2: train tss = 0.6513 : val tss = 0.6289 ::: train hss = 0.1789 : val hss = 0.0796
Fold 3: train tss = 0.6422 : val tss = 0.6312 ::: train hss = 0.1623 : val hss = 0.1675
Fold 4: train tss = 0.6465 : val tss = 0.5678 ::: train hss = 0.1946 : val hss = 0.2085
mean cv TSS: 0.6362
mean cv HSS: 0.1995
151/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7301 : val tss = 0.6301 ::: train hss = 0.2636 : val hss = 0.4094
Fold 1: train tss = 0.6530 : val tss = 0.6109 ::: train hss = 0.2239 : val hss = 0.1611
Fold 2: train tss = 0.6475 : val tss = 0.6622 ::: train hss = 0.1924 : val hss = 0.1176
Fold 3: train tss = 0.5996 : val tss = 0.6251 ::: train hss = 0.1554 : val hss = 0.1524
Fold 4: train tss = 0.6373 : val tss = 0.6389 ::: train hss = 0.1721 : val hss = 0.2004
mean cv TSS: 0.6335
mean cv HSS: 0.2082
152/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6034 : val tss = 0.6726 ::: train hss = 0.1604 : val hss = 0.2276
Fold 1: train tss = 0.6713 : val tss = 0.7044 ::: train hss = 0.2316 : val hss = 0.1952
Fold 2: train tss = 0.6918 : val tss = 0.6685 ::: train hss = 0.2265 : val hss = 0.1175
Fold 3: train tss = 0.6890 : val tss = 0.6560 ::: train hss = 0.2035 : val hss = 0.1856
Fold 4: train tss = 0.6994 : val tss = 0.6255 ::: train hss = 0.2132 : val hss = 0.1719
mean cv TSS: 0.6654
mean cv HSS: 0.1795
153/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6105 : val tss = 0.6784 ::: train hss = 0.1670 : val hss = 0.2486
Fold 1: train tss = 0.6687 : val tss = 0.6905 ::: train hss = 0.2258 : val hss = 0.1919
Fold 2: train tss = 0.6873 : val tss = 0.6597 ::: train hss = 0.2163 : val hss = 0.1240
Fold 3: train tss = 0.6779 : val tss = 0.6587 ::: train hss = 0.1928 : val hss = 0.1897
Fold 4: train tss = 0.6825 : val tss = 0.6295 ::: train hss = 0.2039 : val hss = 0.1686
mean cv TSS: 0.6634
mean cv HSS: 0.1846
154/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 2273357
Fold 0: train tss = 0.7767 : val tss = 0.6184 ::: train hss = 0.3028 : val hss = 0.2877
Fold 1: train tss = 0.7101 : val tss = 0.6498 ::: train hss = 0.2560 : val hss = 0.2261
Fold 2: train tss = 0.6775 : val tss = 0.6744 ::: train hss = 0.2000 : val hss = 0.1331
Fold 3: train tss = 0.6265 : val tss = 0.6182 ::: train hss = 0.1520 : val hss = 0.1693
Fold 4: train tss = 0.6673 : val tss = 0.6322 ::: train hss = 0.1953 : val hss = 0.1745
mean cv TSS: 0.6386
mean cv HSS: 0.1982
155/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7760 : val tss = 0.6178 ::: train hss = 0.3189 : val hss = 0.2910
Fold 1: train tss = 0.6772 : val tss = 0.6693 ::: train hss = 0.2060 : val hss = 0.2527
Fold 2: train tss = 0.6640 : val tss = 0.5981 ::: train hss = 0.1894 : val hss = 0.1922
Fold 3: train tss = 0.6418 : val tss = 0.5852 ::: train hss = 0.1582 : val hss = 0.1665
Fold 4: train tss = 0.6503 : val tss = 0.6366 ::: train hss = 0.1826 : val hss = 0.1523
mean cv TSS: 0.6214
mean cv HSS: 0.2109
156/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6710 : val tss = 0.6842 ::: train hss = 0.2266 : val hss = 0.2992
Fold 1: train tss = 0.6970 : val tss = 0.7118 ::: train hss = 0.2455 : val hss = 0.2015
Fold 2: train tss = 0.7226 : val tss = 0.6781 ::: train hss = 0.2451 : val hss = 0.1484
Fold 3: train tss = 0.7098 : val tss = 0.6744 ::: train hss = 0.2132 : val hss = 0.2027
Fold 4: train tss = 0.6812 : val tss = 0.6149 ::: train hss = 0.2041 : val hss = 0.1691
mean cv TSS: 0.6727
mean cv HSS: 0.2042
157/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6546 : val tss = 0.6794 ::: train hss = 0.2046 : val hss = 0.2976
Fold 1: train tss = 0.6898 : val tss = 0.6894 ::: train hss = 0.2372 : val hss = 0.2157
Fold 2: train tss = 0.7027 : val tss = 0.6568 ::: train hss = 0.2287 : val hss = 0.1529
Fold 3: train tss = 0.6972 : val tss = 0.6701 ::: train hss = 0.2025 : val hss = 0.2293
Fold 4: train tss = 0.6770 : val tss = 0.6290 ::: train hss = 0.2010 : val hss = 0.1703
mean cv TSS: 0.6649
mean cv HSS: 0.2132
158/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7620 : val tss = 0.6187 ::: train hss = 0.3151 : val hss = 0.2520
Fold 1: train tss = 0.7175 : val tss = 0.6728 ::: train hss = 0.2723 : val hss = 0.2883
Fold 2: train tss = 0.6558 : val tss = 0.6526 ::: train hss = 0.1996 : val hss = 0.0965
Fold 3: train tss = 0.6497 : val tss = 0.6338 ::: train hss = 0.1555 : val hss = 0.2314
Fold 4: train tss = 0.6610 : val tss = 0.6177 ::: train hss = 0.1874 : val hss = 0.1809
mean cv TSS: 0.6391
mean cv HSS: 0.2098
159/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7183 : val tss = 0.5388 ::: train hss = 0.2427 : val hss = 0.4801
Fold 1: train tss = 0.6586 : val tss = 0.6857 ::: train hss = 0.2162 : val hss = 0.2574
Fold 2: train tss = 0.6476 : val tss = 0.6312 ::: train hss = 0.1856 : val hss = 0.0919
Fold 3: train tss = 0.6267 : val tss = 0.6300 ::: train hss = 0.1610 : val hss = 0.1546
Fold 4: train tss = 0.6498 : val tss = 0.5819 ::: train hss = 0.1815 : val hss = 0.2136
mean cv TSS: 0.6135
mean cv HSS: 0.2395
160/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6938 : val tss = 0.6729 ::: train hss = 0.2507 : val hss = 0.3350
Fold 1: train tss = 0.7196 : val tss = 0.6848 ::: train hss = 0.2715 : val hss = 0.2297
Fold 2: train tss = 0.7556 : val tss = 0.6670 ::: train hss = 0.2909 : val hss = 0.1589
Fold 3: train tss = 0.7196 : val tss = 0.6054 ::: train hss = 0.2388 : val hss = 0.1343
Fold 4: train tss = 0.7425 : val tss = 0.5315 ::: train hss = 0.2606 : val hss = 0.2464
mean cv TSS: 0.6323
mean cv HSS: 0.2209
161/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6917 : val tss = 0.6671 ::: train hss = 0.2472 : val hss = 0.3395
Fold 1: train tss = 0.7107 : val tss = 0.6787 ::: train hss = 0.2601 : val hss = 0.2165
Fold 2: train tss = 0.7483 : val tss = 0.6847 ::: train hss = 0.2805 : val hss = 0.1342
Fold 3: train tss = 0.7190 : val tss = 0.6632 ::: train hss = 0.2369 : val hss = 0.1963
Fold 4: train tss = 0.7191 : val tss = 0.5779 ::: train hss = 0.2327 : val hss = 0.2256
mean cv TSS: 0.6543
mean cv HSS: 0.2224
162/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.8065 : val tss = 0.6723 ::: train hss = 0.3897 : val hss = 0.2970
Fold 1: train tss = 0.7022 : val tss = 0.7319 ::: train hss = 0.2444 : val hss = 0.1330
Fold 2: train tss = 0.6541 : val tss = 0.6309 ::: train hss = 0.1814 : val hss = 0.1762
Fold 3: train tss = 0.6280 : val tss = 0.6319 ::: train hss = 0.1524 : val hss = 0.1584
Fold 4: train tss = 0.6387 : val tss = 0.6659 ::: train hss = 0.1784 : val hss = 0.1820
mean cv TSS: 0.6666
mean cv HSS: 0.1893
163/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7422 : val tss = 0.6471 ::: train hss = 0.2858 : val hss = 0.2503
Fold 1: train tss = 0.6203 : val tss = 0.7424 ::: train hss = 0.1630 : val hss = 0.1248
Fold 2: train tss = 0.6501 : val tss = 0.5823 ::: train hss = 0.1702 : val hss = 0.2373
Fold 3: train tss = 0.6412 : val tss = 0.6541 ::: train hss = 0.1614 : val hss = 0.2874
Fold 4: train tss = 0.6517 : val tss = 0.4780 ::: train hss = 0.1833 : val hss = 0.2826
mean cv TSS: 0.6208
mean cv HSS: 0.2365
164/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7434 : val tss = 0.6577 ::: train hss = 0.2816 : val hss = 0.3107
Fold 1: train tss = 0.7671 : val tss = 0.6919 ::: train hss = 0.3134 : val hss = 0.2162
Fold 2: train tss = 0.7731 : val tss = 0.6581 ::: train hss = 0.3174 : val hss = 0.1533
Fold 3: train tss = 0.7006 : val tss = 0.5600 ::: train hss = 0.2136 : val hss = 0.1067
Fold 4: train tss = 0.7163 : val tss = 0.6064 ::: train hss = 0.2774 : val hss = 0.2246
mean cv TSS: 0.6348
mean cv HSS: 0.2023
165/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 6221357
Fold 0: train tss = 0.7296 : val tss = 0.6664 ::: train hss = 0.2704 : val hss = 0.3053
Fold 1: train tss = 0.7506 : val tss = 0.7366 ::: train hss = 0.2995 : val hss = 0.1884
Fold 2: train tss = 0.7068 : val tss = 0.6835 ::: train hss = 0.2082 : val hss = 0.1603
Fold 3: train tss = 0.7093 : val tss = 0.6475 ::: train hss = 0.2187 : val hss = 0.1955
Fold 4: train tss = 0.6787 : val tss = 0.6802 ::: train hss = 0.1916 : val hss = 0.1214
mean cv TSS: 0.6828
mean cv HSS: 0.1942
166/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.5847 : val tss = 0.0259 ::: train hss = 0.1390 : val hss = 0.0026
Fold 1: train tss = 0.6518 : val tss = 0.6943 ::: train hss = 0.1843 : val hss = 0.2373
Fold 2: train tss = 0.6415 : val tss = 0.6170 ::: train hss = 0.1826 : val hss = 0.0798
Fold 3: train tss = 0.6361 : val tss = 0.6274 ::: train hss = 0.1549 : val hss = 0.1786
Fold 4: train tss = 0.6562 : val tss = 0.5123 ::: train hss = 0.1815 : val hss = 0.2288
mean cv TSS: 0.4954
mean cv HSS: 0.1454
167/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7293 : val tss = 0.4545 ::: train hss = 0.3155 : val hss = 0.0797
Fold 1: train tss = 0.6590 : val tss = 0.6826 ::: train hss = 0.1947 : val hss = 0.2061
Fold 2: train tss = 0.6236 : val tss = 0.6631 ::: train hss = 0.1737 : val hss = 0.1202
Fold 3: train tss = 0.6153 : val tss = 0.6013 ::: train hss = 0.1502 : val hss = 0.1287
Fold 4: train tss = 0.6405 : val tss = 0.5489 ::: train hss = 0.1750 : val hss = 0.2206
mean cv TSS: 0.5901
mean cv HSS: 0.1511
168/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6992 : val tss = 0.6805 ::: train hss = 0.2530 : val hss = 0.3333
Fold 1: train tss = 0.7268 : val tss = 0.6866 ::: train hss = 0.2754 : val hss = 0.2212
Fold 2: train tss = 0.7541 : val tss = 0.6736 ::: train hss = 0.2882 : val hss = 0.1375
Fold 3: train tss = 0.7416 : val tss = 0.6667 ::: train hss = 0.2665 : val hss = 0.2301
Fold 4: train tss = 0.7385 : val tss = 0.5399 ::: train hss = 0.2543 : val hss = 0.2281
mean cv TSS: 0.6495
mean cv HSS: 0.2300
169/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6975 : val tss = 0.6829 ::: train hss = 0.2452 : val hss = 0.3266
Fold 1: train tss = 0.7138 : val tss = 0.6862 ::: train hss = 0.2643 : val hss = 0.2177
Fold 2: train tss = 0.7374 : val tss = 0.6746 ::: train hss = 0.2676 : val hss = 0.1435
Fold 3: train tss = 0.7173 : val tss = 0.6543 ::: train hss = 0.2515 : val hss = 0.2881
Fold 4: train tss = 0.7147 : val tss = 0.5460 ::: train hss = 0.2253 : val hss = 0.2159
mean cv TSS: 0.6488
mean cv HSS: 0.2384
170/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7892 : val tss = 0.6119 ::: train hss = 0.3205 : val hss = 0.3944
Fold 1: train tss = 0.7251 : val tss = 0.6663 ::: train hss = 0.2814 : val hss = 0.2881
Fold 2: train tss = 0.5719 : val tss = 0.4449 ::: train hss = 0.1502 : val hss = 0.0306
Fold 3: train tss = 0.6483 : val tss = 0.6549 ::: train hss = 0.1577 : val hss = 0.2309
Fold 4: train tss = 0.6475 : val tss = 0.6569 ::: train hss = 0.1749 : val hss = 0.1905
mean cv TSS: 0.6070
mean cv HSS: 0.2269
171/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7670 : val tss = 0.6956 ::: train hss = 0.3253 : val hss = 0.2965
Fold 1: train tss = 0.6858 : val tss = 0.6973 ::: train hss = 0.2386 : val hss = 0.1984
Fold 2: train tss = 0.5852 : val tss = 0.6602 ::: train hss = 0.1502 : val hss = 0.0963
Fold 3: train tss = 0.6244 : val tss = 0.6202 ::: train hss = 0.1530 : val hss = 0.1461
Fold 4: train tss = 0.6472 : val tss = 0.5938 ::: train hss = 0.1760 : val hss = 0.2002
mean cv TSS: 0.6534
mean cv HSS: 0.1875
172/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7418 : val tss = 0.6637 ::: train hss = 0.2803 : val hss = 0.3098
Fold 1: train tss = 0.7668 : val tss = 0.6912 ::: train hss = 0.3171 : val hss = 0.2062
Fold 2: train tss = 0.7649 : val tss = 0.6244 ::: train hss = 0.3000 : val hss = 0.2062
Fold 3: train tss = 0.7163 : val tss = 0.5994 ::: train hss = 0.2196 : val hss = 0.1304
Fold 4: train tss = 0.7343 : val tss = 0.5277 ::: train hss = 0.2537 : val hss = 0.2656
mean cv TSS: 0.6213
mean cv HSS: 0.2236
173/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7393 : val tss = 0.6693 ::: train hss = 0.2749 : val hss = 0.3070
Fold 1: train tss = 0.7429 : val tss = 0.7184 ::: train hss = 0.2905 : val hss = 0.2060
Fold 2: train tss = 0.7464 : val tss = 0.6057 ::: train hss = 0.2737 : val hss = 0.1813
Fold 3: train tss = 0.6918 : val tss = 0.6343 ::: train hss = 0.2096 : val hss = 0.2059
Fold 4: train tss = 0.7035 : val tss = 0.5306 ::: train hss = 0.2281 : val hss = 0.2539
mean cv TSS: 0.6317
mean cv HSS: 0.2308
174/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6492 : val tss = 0.6190 ::: train hss = 0.1840 : val hss = 0.1796
Fold 1: train tss = 0.6665 : val tss = 0.7028 ::: train hss = 0.2054 : val hss = 0.1697
Fold 2: train tss = 0.6904 : val tss = 0.6735 ::: train hss = 0.2110 : val hss = 0.1357
Fold 3: train tss = 0.6585 : val tss = 0.6127 ::: train hss = 0.1664 : val hss = 0.2709
Fold 4: train tss = 0.6482 : val tss = 0.5589 ::: train hss = 0.1741 : val hss = 0.2036
mean cv TSS: 0.6334
mean cv HSS: 0.1919
175/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6123 : val tss = 0.1179 ::: train hss = 0.1874 : val hss = 0.0136
Fold 1: train tss = 0.6831 : val tss = 0.7258 ::: train hss = 0.2525 : val hss = 0.1713
Fold 2: train tss = 0.6399 : val tss = 0.5974 ::: train hss = 0.1545 : val hss = 0.1978
Fold 3: train tss = 0.6380 : val tss = 0.6586 ::: train hss = 0.1492 : val hss = 0.2086
Fold 4: train tss = 0.6523 : val tss = 0.5750 ::: train hss = 0.1738 : val hss = 0.1765
mean cv TSS: 0.5349
mean cv HSS: 0.1536
176/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 6221357
Fold 0: train tss = 0.6826 : val tss = 0.6798 ::: train hss = 0.2476 : val hss = 0.2939
Fold 1: train tss = 0.6979 : val tss = 0.7380 ::: train hss = 0.2536 : val hss = 0.1911
Fold 2: train tss = 0.7178 : val tss = 0.6666 ::: train hss = 0.2498 : val hss = 0.1046
Fold 3: train tss = 0.7076 : val tss = 0.6493 ::: train hss = 0.2207 : val hss = 0.1769
Fold 4: train tss = 0.7104 : val tss = 0.5958 ::: train hss = 0.2300 : val hss = 0.1628
mean cv TSS: 0.6659
mean cv HSS: 0.1859
177/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6763 : val tss = 0.6879 ::: train hss = 0.2399 : val hss = 0.2951
Fold 1: train tss = 0.6946 : val tss = 0.7219 ::: train hss = 0.2512 : val hss = 0.1913
Fold 2: train tss = 0.7159 : val tss = 0.6717 ::: train hss = 0.2465 : val hss = 0.1123
Fold 3: train tss = 0.7042 : val tss = 0.6550 ::: train hss = 0.2163 : val hss = 0.1876
Fold 4: train tss = 0.7028 : val tss = 0.6235 ::: train hss = 0.2222 : val hss = 0.1722
mean cv TSS: 0.6720
mean cv HSS: 0.1917
178/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7489 : val tss = 0.6325 ::: train hss = 0.2803 : val hss = 0.3569
Fold 1: train tss = 0.6532 : val tss = 0.6109 ::: train hss = 0.1920 : val hss = 0.0565
Fold 2: train tss = 0.6155 : val tss = 0.6695 ::: train hss = 0.1337 : val hss = 0.1179
Fold 3: train tss = 0.6362 : val tss = 0.6394 ::: train hss = 0.1614 : val hss = 0.1642
Fold 4: train tss = 0.6629 : val tss = 0.4965 ::: train hss = 0.1872 : val hss = 0.2363
mean cv TSS: 0.6098
mean cv HSS: 0.1863
179/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7699 : val tss = 0.6545 ::: train hss = 0.3745 : val hss = 0.2282
Fold 1: train tss = 0.6601 : val tss = 0.7158 ::: train hss = 0.2283 : val hss = 0.1675
Fold 2: train tss = 0.6460 : val tss = 0.6637 ::: train hss = 0.1634 : val hss = 0.1130
Fold 3: train tss = 0.6194 : val tss = 0.6268 ::: train hss = 0.1491 : val hss = 0.1552
Fold 4: train tss = 0.6227 : val tss = 0.5688 ::: train hss = 0.1594 : val hss = 0.2230
mean cv TSS: 0.6459
mean cv HSS: 0.1774
180/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6970 : val tss = 0.6812 ::: train hss = 0.2415 : val hss = 0.3107
Fold 1: train tss = 0.7225 : val tss = 0.7440 ::: train hss = 0.2680 : val hss = 0.1848
Fold 2: train tss = 0.7571 : val tss = 0.6574 ::: train hss = 0.2940 : val hss = 0.0956
Fold 3: train tss = 0.7236 : val tss = 0.6714 ::: train hss = 0.2569 : val hss = 0.2492
Fold 4: train tss = 0.7002 : val tss = 0.5494 ::: train hss = 0.2087 : val hss = 0.1705
mean cv TSS: 0.6607
mean cv HSS: 0.2022
181/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6929 : val tss = 0.6661 ::: train hss = 0.2322 : val hss = 0.2788
Fold 1: train tss = 0.7163 : val tss = 0.7361 ::: train hss = 0.2626 : val hss = 0.1760
Fold 2: train tss = 0.7332 : val tss = 0.6639 ::: train hss = 0.2576 : val hss = 0.1132
Fold 3: train tss = 0.6701 : val tss = 0.6521 ::: train hss = 0.1723 : val hss = 0.1743
Fold 4: train tss = 0.6986 : val tss = 0.6172 ::: train hss = 0.2160 : val hss = 0.2334
mean cv TSS: 0.6671
mean cv HSS: 0.1951
182/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6097 : val tss = 0.5347 ::: train hss = 0.1675 : val hss = 0.1972
Fold 1: train tss = 0.6726 : val tss = 0.6585 ::: train hss = 0.2045 : val hss = 0.2895
Fold 2: train tss = 0.6399 : val tss = 0.6406 ::: train hss = 0.1808 : val hss = 0.0872
Fold 3: train tss = 0.6408 : val tss = 0.6133 ::: train hss = 0.1543 : val hss = 0.2077
Fold 4: train tss = 0.6466 : val tss = 0.6473 ::: train hss = 0.1696 : val hss = 0.1680
mean cv TSS: 0.6189
mean cv HSS: 0.1899
183/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6825 : val tss = 0.6649 ::: train hss = 0.2743 : val hss = 0.3296
Fold 1: train tss = 0.6337 : val tss = 0.6560 ::: train hss = 0.1732 : val hss = 0.2476
Fold 2: train tss = 0.6313 : val tss = 0.6559 ::: train hss = 0.1692 : val hss = 0.1427
Fold 3: train tss = 0.6486 : val tss = 0.6241 ::: train hss = 0.1671 : val hss = 0.2488
Fold 4: train tss = 0.6538 : val tss = 0.6265 ::: train hss = 0.1835 : val hss = 0.1918
mean cv TSS: 0.6455
mean cv HSS: 0.2321
184/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6935 : val tss = 0.6838 ::: train hss = 0.2554 : val hss = 0.3182
Fold 1: train tss = 0.6961 : val tss = 0.7400 ::: train hss = 0.2525 : val hss = 0.1890
Fold 2: train tss = 0.7147 : val tss = 0.6664 ::: train hss = 0.2467 : val hss = 0.1107
Fold 3: train tss = 0.7068 : val tss = 0.6505 ::: train hss = 0.2175 : val hss = 0.1814
Fold 4: train tss = 0.7140 : val tss = 0.6111 ::: train hss = 0.2320 : val hss = 0.1718
mean cv TSS: 0.6704
mean cv HSS: 0.1942
185/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6890 : val tss = 0.6832 ::: train hss = 0.2476 : val hss = 0.3116
Fold 1: train tss = 0.6908 : val tss = 0.7272 ::: train hss = 0.2462 : val hss = 0.1880
Fold 2: train tss = 0.7068 : val tss = 0.6682 ::: train hss = 0.2404 : val hss = 0.1141
Fold 3: train tss = 0.7008 : val tss = 0.6539 ::: train hss = 0.2135 : val hss = 0.1790
Fold 4: train tss = 0.7050 : val tss = 0.6356 ::: train hss = 0.2248 : val hss = 0.1809
mean cv TSS: 0.6736
mean cv HSS: 0.1947
186/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6969 : val tss = 0.6605 ::: train hss = 0.2070 : val hss = 0.2742
Fold 1: train tss = 0.7241 : val tss = 0.7350 ::: train hss = 0.2657 : val hss = 0.1741
Fold 2: train tss = 0.6444 : val tss = 0.5999 ::: train hss = 0.1896 : val hss = 0.0679
Fold 3: train tss = 0.6578 : val tss = 0.6264 ::: train hss = 0.1694 : val hss = 0.1558
Fold 4: train tss = 0.6514 : val tss = 0.4793 ::: train hss = 0.1727 : val hss = 0.2289
mean cv TSS: 0.6202
mean cv HSS: 0.1802
187/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 12035629
Fold 0: train tss = 0.7129 : val tss = 0.6910 ::: train hss = 0.2330 : val hss = 0.3505
Fold 1: train tss = 0.6857 : val tss = 0.7371 ::: train hss = 0.2388 : val hss = 0.1924
Fold 2: train tss = 0.6250 : val tss = 0.6291 ::: train hss = 0.1766 : val hss = 0.0785
Fold 3: train tss = 0.6271 : val tss = 0.5935 ::: train hss = 0.1531 : val hss = 0.1255
Fold 4: train tss = 0.6483 : val tss = 0.5820 ::: train hss = 0.1746 : val hss = 0.2124
mean cv TSS: 0.6465
mean cv HSS: 0.1919
188/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6983 : val tss = 0.6735 ::: train hss = 0.2422 : val hss = 0.3008
Fold 1: train tss = 0.7279 : val tss = 0.7387 ::: train hss = 0.2754 : val hss = 0.1807
Fold 2: train tss = 0.7540 : val tss = 0.6599 ::: train hss = 0.2857 : val hss = 0.1009
Fold 3: train tss = 0.7142 : val tss = 0.6497 ::: train hss = 0.2187 : val hss = 0.1691
Fold 4: train tss = 0.7131 : val tss = 0.5383 ::: train hss = 0.2180 : val hss = 0.2077
mean cv TSS: 0.6520
mean cv HSS: 0.1918
189/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7007 : val tss = 0.6657 ::: train hss = 0.2412 : val hss = 0.2885
Fold 1: train tss = 0.7196 : val tss = 0.7388 ::: train hss = 0.2657 : val hss = 0.1867
Fold 2: train tss = 0.7159 : val tss = 0.6669 ::: train hss = 0.2467 : val hss = 0.1548
Fold 3: train tss = 0.6911 : val tss = 0.6623 ::: train hss = 0.1974 : val hss = 0.1962
Fold 4: train tss = 0.6855 : val tss = 0.5791 ::: train hss = 0.1951 : val hss = 0.2081
mean cv TSS: 0.6626
mean cv HSS: 0.2069
190/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6606 : val tss = 0.6759 ::: train hss = 0.2227 : val hss = 0.3482
Fold 1: train tss = 0.4591 : val tss = 0.0933 ::: train hss = 0.1553 : val hss = 0.0029
Fold 2: train tss = 0.6204 : val tss = 0.6367 ::: train hss = 0.1700 : val hss = 0.0801
Fold 3: train tss = 0.6488 : val tss = 0.6323 ::: train hss = 0.1630 : val hss = 0.2244
Fold 4: train tss = 0.6654 : val tss = 0.6066 ::: train hss = 0.1884 : val hss = 0.1995
mean cv TSS: 0.5290
mean cv HSS: 0.1710
191/256
{'batch_size': 1024, 'bce_pos_class_weight': 35, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.5205 : val tss = 0.6289 ::: train hss = 0.1053 : val hss = 0.1803
Fold 1: train tss = 0.6106 : val tss = 0.0369 ::: train hss = 0.1542 : val hss = 0.0012
Fold 2: train tss = 0.5657 : val tss = 0.6467 ::: train hss = 0.1428 : val hss = 0.0923
Fold 3: train tss = 0.6389 : val tss = 0.6540 ::: train hss = 0.1502 : val hss = 0.1880
Fold 4: train tss = 0.6399 : val tss = 0.6118 ::: train hss = 0.1691 : val hss = 0.2045
mean cv TSS: 0.5156
mean cv HSS: 0.1332
192/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.5755 : val tss = 0.6383 ::: train hss = 0.1345 : val hss = 0.1838
Fold 1: train tss = 0.6568 : val tss = 0.7503 ::: train hss = 0.1869 : val hss = 0.1768
Fold 2: train tss = 0.6942 : val tss = 0.6491 ::: train hss = 0.1904 : val hss = 0.0994
Fold 3: train tss = 0.7004 : val tss = 0.6369 ::: train hss = 0.1795 : val hss = 0.1812
Fold 4: train tss = 0.6877 : val tss = 0.6140 ::: train hss = 0.1768 : val hss = 0.1669
mean cv TSS: 0.6577
mean cv HSS: 0.1616
193/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.5713 : val tss = 0.6527 ::: train hss = 0.1342 : val hss = 0.1934
Fold 1: train tss = 0.6373 : val tss = 0.7697 ::: train hss = 0.1693 : val hss = 0.1598
Fold 2: train tss = 0.6827 : val tss = 0.6379 ::: train hss = 0.1828 : val hss = 0.0902
Fold 3: train tss = 0.6677 : val tss = 0.6455 ::: train hss = 0.1522 : val hss = 0.1736
Fold 4: train tss = 0.6776 : val tss = 0.6251 ::: train hss = 0.1712 : val hss = 0.1646
mean cv TSS: 0.6662
mean cv HSS: 0.1563
194/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7870 : val tss = 0.6384 ::: train hss = 0.3246 : val hss = 0.3030
Fold 1: train tss = 0.7061 : val tss = 0.6796 ::: train hss = 0.2313 : val hss = 0.1819
Fold 2: train tss = 0.6854 : val tss = 0.6526 ::: train hss = 0.1848 : val hss = 0.1261
Fold 3: train tss = 0.6610 : val tss = 0.6294 ::: train hss = 0.1510 : val hss = 0.1719
Fold 4: train tss = 0.6527 : val tss = 0.6763 ::: train hss = 0.1587 : val hss = 0.1324
mean cv TSS: 0.6553
mean cv HSS: 0.1831
195/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7367 : val tss = 0.6565 ::: train hss = 0.2578 : val hss = 0.3168
Fold 1: train tss = 0.6747 : val tss = 0.7220 ::: train hss = 0.2069 : val hss = 0.1018
Fold 2: train tss = 0.6322 : val tss = 0.6655 ::: train hss = 0.1491 : val hss = 0.1018
Fold 3: train tss = 0.6284 : val tss = 0.6267 ::: train hss = 0.1332 : val hss = 0.1758
Fold 4: train tss = 0.6529 : val tss = 0.6384 ::: train hss = 0.1619 : val hss = 0.1462
mean cv TSS: 0.6618
mean cv HSS: 0.1685
196/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6416 : val tss = 0.6722 ::: train hss = 0.1757 : val hss = 0.2455
Fold 1: train tss = 0.6925 : val tss = 0.7440 ::: train hss = 0.2194 : val hss = 0.1586
Fold 2: train tss = 0.7025 : val tss = 0.6810 ::: train hss = 0.1933 : val hss = 0.1343
Fold 3: train tss = 0.6997 : val tss = 0.6474 ::: train hss = 0.1783 : val hss = 0.1725
Fold 4: train tss = 0.6900 : val tss = 0.6187 ::: train hss = 0.1791 : val hss = 0.1551
mean cv TSS: 0.6727
mean cv HSS: 0.1732
197/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.5907 : val tss = 0.6760 ::: train hss = 0.1414 : val hss = 0.2331
Fold 1: train tss = 0.6826 : val tss = 0.7206 ::: train hss = 0.2056 : val hss = 0.0970
Fold 2: train tss = 0.6805 : val tss = 0.6327 ::: train hss = 0.1820 : val hss = 0.0825
Fold 3: train tss = 0.6670 : val tss = 0.6121 ::: train hss = 0.1567 : val hss = 0.1456
Fold 4: train tss = 0.6764 : val tss = 0.6257 ::: train hss = 0.1742 : val hss = 0.1339
mean cv TSS: 0.6534
mean cv HSS: 0.1384
198/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 1144909
Fold 0: train tss = 0.7108 : val tss = 0.6227 ::: train hss = 0.2193 : val hss = 0.3418
Fold 1: train tss = 0.6638 : val tss = 0.7388 ::: train hss = 0.1962 : val hss = 0.1144
Fold 2: train tss = 0.6487 : val tss = 0.6636 ::: train hss = 0.1578 : val hss = 0.0964
Fold 3: train tss = 0.6200 : val tss = 0.6312 ::: train hss = 0.1290 : val hss = 0.1663
Fold 4: train tss = 0.6482 : val tss = 0.6225 ::: train hss = 0.1574 : val hss = 0.1490
mean cv TSS: 0.6558
mean cv HSS: 0.1736
199/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7424 : val tss = 0.5712 ::: train hss = 0.2596 : val hss = 0.3804
Fold 1: train tss = 0.6566 : val tss = 0.7522 ::: train hss = 0.1904 : val hss = 0.1736
Fold 2: train tss = 0.6374 : val tss = 0.6657 ::: train hss = 0.1560 : val hss = 0.1091
Fold 3: train tss = 0.6114 : val tss = 0.6546 ::: train hss = 0.1252 : val hss = 0.1950
Fold 4: train tss = 0.6503 : val tss = 0.6468 ::: train hss = 0.1625 : val hss = 0.1408
mean cv TSS: 0.6581
mean cv HSS: 0.1998
200/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.5876 : val tss = 0.6451 ::: train hss = 0.1411 : val hss = 0.1943
Fold 1: train tss = 0.6486 : val tss = 0.7462 ::: train hss = 0.1843 : val hss = 0.1676
Fold 2: train tss = 0.6972 : val tss = 0.6600 ::: train hss = 0.1954 : val hss = 0.1082
Fold 3: train tss = 0.7015 : val tss = 0.6227 ::: train hss = 0.1834 : val hss = 0.1466
Fold 4: train tss = 0.6930 : val tss = 0.6311 ::: train hss = 0.1866 : val hss = 0.1503
mean cv TSS: 0.6610
mean cv HSS: 0.1534
201/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.5836 : val tss = 0.6435 ::: train hss = 0.1406 : val hss = 0.1961
Fold 1: train tss = 0.6448 : val tss = 0.7474 ::: train hss = 0.1785 : val hss = 0.1591
Fold 2: train tss = 0.6965 : val tss = 0.6457 ::: train hss = 0.1895 : val hss = 0.0935
Fold 3: train tss = 0.6670 : val tss = 0.6274 ::: train hss = 0.1541 : val hss = 0.1556
Fold 4: train tss = 0.6703 : val tss = 0.6226 ::: train hss = 0.1661 : val hss = 0.1417
mean cv TSS: 0.6573
mean cv HSS: 0.1492
202/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7880 : val tss = 0.5961 ::: train hss = 0.3146 : val hss = 0.2461
Fold 1: train tss = 0.7066 : val tss = 0.7435 ::: train hss = 0.2186 : val hss = 0.1499
Fold 2: train tss = 0.6699 : val tss = 0.6296 ::: train hss = 0.1713 : val hss = 0.0918
Fold 3: train tss = 0.6414 : val tss = 0.6245 ::: train hss = 0.1403 : val hss = 0.1438
Fold 4: train tss = 0.6754 : val tss = 0.6400 ::: train hss = 0.1772 : val hss = 0.1720
mean cv TSS: 0.6468
mean cv HSS: 0.1607
203/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7371 : val tss = 0.6527 ::: train hss = 0.2590 : val hss = 0.3227
Fold 1: train tss = 0.6789 : val tss = 0.7096 ::: train hss = 0.2103 : val hss = 0.1867
Fold 2: train tss = 0.6420 : val tss = 0.6566 ::: train hss = 0.1499 : val hss = 0.1153
Fold 3: train tss = 0.6351 : val tss = 0.5264 ::: train hss = 0.1427 : val hss = 0.0972
Fold 4: train tss = 0.6537 : val tss = 0.5946 ::: train hss = 0.1609 : val hss = 0.1766
mean cv TSS: 0.6280
mean cv HSS: 0.1797
204/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.6589 : val tss = 0.6702 ::: train hss = 0.1846 : val hss = 0.2798
Fold 1: train tss = 0.7012 : val tss = 0.7544 ::: train hss = 0.2238 : val hss = 0.1514
Fold 2: train tss = 0.7020 : val tss = 0.5711 ::: train hss = 0.1982 : val hss = 0.0621
Fold 3: train tss = 0.6984 : val tss = 0.6644 ::: train hss = 0.1768 : val hss = 0.1905
Fold 4: train tss = 0.6758 : val tss = 0.6434 ::: train hss = 0.1688 : val hss = 0.1632
mean cv TSS: 0.6607
mean cv HSS: 0.1694
205/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6287 : val tss = 0.6679 ::: train hss = 0.1637 : val hss = 0.2714
Fold 1: train tss = 0.6878 : val tss = 0.7542 ::: train hss = 0.2078 : val hss = 0.1511
Fold 2: train tss = 0.6728 : val tss = 0.6628 ::: train hss = 0.1690 : val hss = 0.1058
Fold 3: train tss = 0.6792 : val tss = 0.6779 ::: train hss = 0.1619 : val hss = 0.2210
Fold 4: train tss = 0.6791 : val tss = 0.6371 ::: train hss = 0.1797 : val hss = 0.1137
mean cv TSS: 0.6800
mean cv HSS: 0.1726
206/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7496 : val tss = 0.6044 ::: train hss = 0.2587 : val hss = 0.2564
Fold 1: train tss = 0.6885 : val tss = 0.7539 ::: train hss = 0.2245 : val hss = 0.1401
Fold 2: train tss = 0.6389 : val tss = 0.6456 ::: train hss = 0.1613 : val hss = 0.1099
Fold 3: train tss = 0.6377 : val tss = 0.6144 ::: train hss = 0.1364 : val hss = 0.1374
Fold 4: train tss = 0.6396 : val tss = 0.6366 ::: train hss = 0.1497 : val hss = 0.1600
mean cv TSS: 0.6510
mean cv HSS: 0.1608
207/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7043 : val tss = 0.6156 ::: train hss = 0.2177 : val hss = 0.3511
Fold 1: train tss = 0.6774 : val tss = 0.6789 ::: train hss = 0.2129 : val hss = 0.1988
Fold 2: train tss = 0.5904 : val tss = 0.5857 ::: train hss = 0.1217 : val hss = 0.0670
Fold 3: train tss = 0.6300 : val tss = 0.6039 ::: train hss = 0.1371 : val hss = 0.1857
Fold 4: train tss = 0.6351 : val tss = 0.6590 ::: train hss = 0.1494 : val hss = 0.1458
mean cv TSS: 0.6286
mean cv HSS: 0.1897
208/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.5592 : val tss = 0.6585 ::: train hss = 0.1279 : val hss = 0.2007
Fold 1: train tss = 0.6444 : val tss = 0.7469 ::: train hss = 0.1846 : val hss = 0.1564
Fold 2: train tss = 0.6693 : val tss = 0.6549 ::: train hss = 0.1775 : val hss = 0.1006
Fold 3: train tss = 0.6697 : val tss = 0.6334 ::: train hss = 0.1613 : val hss = 0.1540
Fold 4: train tss = 0.6808 : val tss = 0.6512 ::: train hss = 0.1733 : val hss = 0.1278
mean cv TSS: 0.6690
mean cv HSS: 0.1479
209/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 1144909
Fold 0: train tss = 0.5547 : val tss = 0.6554 ::: train hss = 0.1249 : val hss = 0.1975
Fold 1: train tss = 0.6257 : val tss = 0.7621 ::: train hss = 0.1668 : val hss = 0.1527
Fold 2: train tss = 0.6575 : val tss = 0.6560 ::: train hss = 0.1678 : val hss = 0.1024
Fold 3: train tss = 0.6630 : val tss = 0.6348 ::: train hss = 0.1549 : val hss = 0.1575
Fold 4: train tss = 0.6638 : val tss = 0.6608 ::: train hss = 0.1617 : val hss = 0.1312
mean cv TSS: 0.6738
mean cv HSS: 0.1483
210/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7812 : val tss = 0.6117 ::: train hss = 0.3225 : val hss = 0.3313
Fold 1: train tss = 0.6842 : val tss = 0.7632 ::: train hss = 0.2117 : val hss = 0.1440
Fold 2: train tss = 0.6573 : val tss = 0.6515 ::: train hss = 0.1598 : val hss = 0.1047
Fold 3: train tss = 0.6334 : val tss = 0.6526 ::: train hss = 0.1362 : val hss = 0.1698
Fold 4: train tss = 0.6452 : val tss = 0.6342 ::: train hss = 0.1525 : val hss = 0.1508
mean cv TSS: 0.6626
mean cv HSS: 0.1801
211/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7388 : val tss = 0.5925 ::: train hss = 0.2526 : val hss = 0.3397
Fold 1: train tss = 0.6354 : val tss = 0.7318 ::: train hss = 0.1663 : val hss = 0.1726
Fold 2: train tss = 0.6029 : val tss = 0.5514 ::: train hss = 0.1404 : val hss = 0.0539
Fold 3: train tss = 0.6260 : val tss = 0.5671 ::: train hss = 0.1318 : val hss = 0.1111
Fold 4: train tss = 0.6384 : val tss = 0.6596 ::: train hss = 0.1484 : val hss = 0.1494
mean cv TSS: 0.6205
mean cv HSS: 0.1653
212/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.6197 : val tss = 0.6657 ::: train hss = 0.1639 : val hss = 0.2399
Fold 1: train tss = 0.6684 : val tss = 0.7387 ::: train hss = 0.1965 : val hss = 0.1766
Fold 2: train tss = 0.6832 : val tss = 0.6060 ::: train hss = 0.1823 : val hss = 0.0694
Fold 3: train tss = 0.6767 : val tss = 0.6339 ::: train hss = 0.1618 : val hss = 0.1582
Fold 4: train tss = 0.6720 : val tss = 0.6278 ::: train hss = 0.1637 : val hss = 0.1416
mean cv TSS: 0.6544
mean cv HSS: 0.1571
213/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.5886 : val tss = 0.6788 ::: train hss = 0.1436 : val hss = 0.2431
Fold 1: train tss = 0.6382 : val tss = 0.7274 ::: train hss = 0.1733 : val hss = 0.1795
Fold 2: train tss = 0.6530 : val tss = 0.5353 ::: train hss = 0.1660 : val hss = 0.0469
Fold 3: train tss = 0.6682 : val tss = 0.6472 ::: train hss = 0.1573 : val hss = 0.1827
Fold 4: train tss = 0.6707 : val tss = 0.5899 ::: train hss = 0.1685 : val hss = 0.1680
mean cv TSS: 0.6357
mean cv HSS: 0.1640
214/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 1144909
Fold 0: train tss = 0.7571 : val tss = 0.6387 ::: train hss = 0.2834 : val hss = 0.3506
Fold 1: train tss = 0.6477 : val tss = 0.7645 ::: train hss = 0.1820 : val hss = 0.1421
Fold 2: train tss = 0.6226 : val tss = 0.6260 ::: train hss = 0.1476 : val hss = 0.0870
Fold 3: train tss = 0.6227 : val tss = 0.5789 ::: train hss = 0.1383 : val hss = 0.1160
Fold 4: train tss = 0.6352 : val tss = 0.6273 ::: train hss = 0.1458 : val hss = 0.1791
mean cv TSS: 0.6471
mean cv HSS: 0.1750
215/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 1144909
Fold 0: train tss = 0.7017 : val tss = 0.6703 ::: train hss = 0.2187 : val hss = 0.3344
Fold 1: train tss = 0.6377 : val tss = 0.7106 ::: train hss = 0.1732 : val hss = 0.2061
Fold 2: train tss = 0.6236 : val tss = 0.6525 ::: train hss = 0.1394 : val hss = 0.1129
Fold 3: train tss = 0.6158 : val tss = 0.6287 ::: train hss = 0.1358 : val hss = 0.1509
Fold 4: train tss = 0.6244 : val tss = 0.6608 ::: train hss = 0.1426 : val hss = 0.1442
mean cv TSS: 0.6646
mean cv HSS: 0.1897
216/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.5778 : val tss = 0.6633 ::: train hss = 0.1393 : val hss = 0.2052
Fold 1: train tss = 0.6506 : val tss = 0.7425 ::: train hss = 0.1903 : val hss = 0.1642
Fold 2: train tss = 0.6709 : val tss = 0.6452 ::: train hss = 0.1784 : val hss = 0.0910
Fold 3: train tss = 0.6814 : val tss = 0.6279 ::: train hss = 0.1675 : val hss = 0.1529
Fold 4: train tss = 0.6787 : val tss = 0.6372 ::: train hss = 0.1737 : val hss = 0.1402
mean cv TSS: 0.6632
mean cv HSS: 0.1507
217/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.5782 : val tss = 0.6688 ::: train hss = 0.1395 : val hss = 0.2197
Fold 1: train tss = 0.6391 : val tss = 0.7401 ::: train hss = 0.1795 : val hss = 0.1700
Fold 2: train tss = 0.6677 : val tss = 0.6472 ::: train hss = 0.1716 : val hss = 0.0973
Fold 3: train tss = 0.6727 : val tss = 0.6386 ::: train hss = 0.1587 : val hss = 0.1650
Fold 4: train tss = 0.6775 : val tss = 0.6267 ::: train hss = 0.1715 : val hss = 0.1515
mean cv TSS: 0.6643
mean cv HSS: 0.1607
218/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7429 : val tss = 0.6310 ::: train hss = 0.2547 : val hss = 0.3056
Fold 1: train tss = 0.6821 : val tss = 0.7562 ::: train hss = 0.2086 : val hss = 0.1765
Fold 2: train tss = 0.6559 : val tss = 0.6049 ::: train hss = 0.1664 : val hss = 0.0756
Fold 3: train tss = 0.6514 : val tss = 0.6222 ::: train hss = 0.1424 : val hss = 0.1409
Fold 4: train tss = 0.6560 : val tss = 0.6585 ::: train hss = 0.1598 : val hss = 0.1659
mean cv TSS: 0.6546
mean cv HSS: 0.1729
219/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.7321 : val tss = 0.6130 ::: train hss = 0.2503 : val hss = 0.3763
Fold 1: train tss = 0.6800 : val tss = 0.7345 ::: train hss = 0.2141 : val hss = 0.1935
Fold 2: train tss = 0.6386 : val tss = 0.6200 ::: train hss = 0.1459 : val hss = 0.0783
Fold 3: train tss = 0.6418 : val tss = 0.6372 ::: train hss = 0.1387 : val hss = 0.1591
Fold 4: train tss = 0.6344 : val tss = 0.6357 ::: train hss = 0.1455 : val hss = 0.1688
mean cv TSS: 0.6481
mean cv HSS: 0.1952
220/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 2273357
Fold 0: train tss = 0.6217 : val tss = 0.6726 ::: train hss = 0.1677 : val hss = 0.2472
Fold 1: train tss = 0.6719 : val tss = 0.7615 ::: train hss = 0.1998 : val hss = 0.1739
Fold 2: train tss = 0.6824 : val tss = 0.6718 ::: train hss = 0.1847 : val hss = 0.1184
Fold 3: train tss = 0.6899 : val tss = 0.5968 ::: train hss = 0.1680 : val hss = 0.1336
Fold 4: train tss = 0.6630 : val tss = 0.6928 ::: train hss = 0.1598 : val hss = 0.1326
mean cv TSS: 0.6791
mean cv HSS: 0.1611
221/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6006 : val tss = 0.6805 ::: train hss = 0.1520 : val hss = 0.2542
Fold 1: train tss = 0.6609 : val tss = 0.7261 ::: train hss = 0.1883 : val hss = 0.1814
Fold 2: train tss = 0.6662 : val tss = 0.6812 ::: train hss = 0.1695 : val hss = 0.1242
Fold 3: train tss = 0.6503 : val tss = 0.5277 ::: train hss = 0.1480 : val hss = 0.1017
Fold 4: train tss = 0.6640 : val tss = 0.6860 ::: train hss = 0.1669 : val hss = 0.1281
mean cv TSS: 0.6603
mean cv HSS: 0.1579
222/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 2273357
Fold 0: train tss = 0.7287 : val tss = 0.6299 ::: train hss = 0.2586 : val hss = 0.2983
Fold 1: train tss = 0.6560 : val tss = 0.7176 ::: train hss = 0.1859 : val hss = 0.2080
Fold 2: train tss = 0.6319 : val tss = 0.6474 ::: train hss = 0.1402 : val hss = 0.0928
Fold 3: train tss = 0.6102 : val tss = 0.5759 ::: train hss = 0.1237 : val hss = 0.1690
Fold 4: train tss = 0.6325 : val tss = 0.6448 ::: train hss = 0.1448 : val hss = 0.1371
mean cv TSS: 0.6431
mean cv HSS: 0.1810
223/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2273357
Fold 0: train tss = 0.6576 : val tss = 0.6465 ::: train hss = 0.1907 : val hss = 0.3994
Fold 1: train tss = 0.6295 : val tss = 0.7303 ::: train hss = 0.1677 : val hss = 0.1792
Fold 2: train tss = 0.6363 : val tss = 0.5775 ::: train hss = 0.1619 : val hss = 0.0564
Fold 3: train tss = 0.6040 : val tss = 0.6222 ::: train hss = 0.1191 : val hss = 0.2004
Fold 4: train tss = 0.6154 : val tss = 0.6578 ::: train hss = 0.1357 : val hss = 0.1704
mean cv TSS: 0.6469
mean cv HSS: 0.2012
224/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6726 : val tss = 0.6810 ::: train hss = 0.2050 : val hss = 0.2927
Fold 1: train tss = 0.7033 : val tss = 0.7581 ::: train hss = 0.2255 : val hss = 0.1785
Fold 2: train tss = 0.7487 : val tss = 0.6733 ::: train hss = 0.2399 : val hss = 0.1139
Fold 3: train tss = 0.7249 : val tss = 0.6299 ::: train hss = 0.2021 : val hss = 0.1459
Fold 4: train tss = 0.7408 : val tss = 0.6704 ::: train hss = 0.2231 : val hss = 0.1420
mean cv TSS: 0.6826
mean cv HSS: 0.1746
225/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6593 : val tss = 0.6794 ::: train hss = 0.1955 : val hss = 0.2800
Fold 1: train tss = 0.6942 : val tss = 0.7593 ::: train hss = 0.2178 : val hss = 0.1820
Fold 2: train tss = 0.7346 : val tss = 0.6691 ::: train hss = 0.2256 : val hss = 0.1115
Fold 3: train tss = 0.7039 : val tss = 0.5848 ::: train hss = 0.1808 : val hss = 0.1191
Fold 4: train tss = 0.7225 : val tss = 0.6340 ::: train hss = 0.2080 : val hss = 0.1573
mean cv TSS: 0.6653
mean cv HSS: 0.1700
226/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7308 : val tss = 0.6623 ::: train hss = 0.2619 : val hss = 0.2634
Fold 1: train tss = 0.6896 : val tss = 0.7072 ::: train hss = 0.2206 : val hss = 0.2240
Fold 2: train tss = 0.6384 : val tss = 0.6584 ::: train hss = 0.1522 : val hss = 0.1472
Fold 3: train tss = 0.6394 : val tss = 0.6355 ::: train hss = 0.1324 : val hss = 0.1661
Fold 4: train tss = 0.6193 : val tss = 0.6834 ::: train hss = 0.1370 : val hss = 0.1508
mean cv TSS: 0.6694
mean cv HSS: 0.1903
227/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7532 : val tss = 0.5716 ::: train hss = 0.3020 : val hss = 0.1425
Fold 1: train tss = 0.5417 : val tss = 0.6507 ::: train hss = 0.1166 : val hss = 0.0575
Fold 2: train tss = 0.6204 : val tss = 0.5625 ::: train hss = 0.1355 : val hss = 0.0519
Fold 3: train tss = 0.6121 : val tss = 0.5725 ::: train hss = 0.1291 : val hss = 0.1130
Fold 4: train tss = 0.6261 : val tss = 0.6638 ::: train hss = 0.1404 : val hss = 0.1619
mean cv TSS: 0.6042
mean cv HSS: 0.1054
228/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7074 : val tss = 0.6594 ::: train hss = 0.2232 : val hss = 0.2718
Fold 1: train tss = 0.7511 : val tss = 0.7180 ::: train hss = 0.2680 : val hss = 0.1764
Fold 2: train tss = 0.7498 : val tss = 0.6702 ::: train hss = 0.2383 : val hss = 0.1874
Fold 3: train tss = 0.7122 : val tss = 0.6521 ::: train hss = 0.1805 : val hss = 0.2104
Fold 4: train tss = 0.6934 : val tss = 0.6115 ::: train hss = 0.1749 : val hss = 0.1779
mean cv TSS: 0.6622
mean cv HSS: 0.2048
229/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.7133 : val tss = 0.6468 ::: train hss = 0.2283 : val hss = 0.2649
Fold 1: train tss = 0.7386 : val tss = 0.7662 ::: train hss = 0.2580 : val hss = 0.1624
Fold 2: train tss = 0.7412 : val tss = 0.6696 ::: train hss = 0.2241 : val hss = 0.1344
Fold 3: train tss = 0.6841 : val tss = 0.6419 ::: train hss = 0.1683 : val hss = 0.1935
Fold 4: train tss = 0.6966 : val tss = 0.6290 ::: train hss = 0.1856 : val hss = 0.1890
mean cv TSS: 0.6707
mean cv HSS: 0.1888
230/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.7263 : val tss = 0.6356 ::: train hss = 0.2716 : val hss = 0.2749
Fold 1: train tss = 0.6676 : val tss = 0.7471 ::: train hss = 0.2002 : val hss = 0.1265
Fold 2: train tss = 0.6558 : val tss = 0.6187 ::: train hss = 0.1602 : val hss = 0.1746
Fold 3: train tss = 0.6338 : val tss = 0.6353 ::: train hss = 0.1358 : val hss = 0.1680
Fold 4: train tss = 0.6354 : val tss = 0.6590 ::: train hss = 0.1448 : val hss = 0.1539
mean cv TSS: 0.6591
mean cv HSS: 0.1796
231/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 6221357
Fold 0: train tss = 0.7157 : val tss = 0.5978 ::: train hss = 0.2671 : val hss = 0.1696
Fold 1: train tss = 0.6569 : val tss = 0.7212 ::: train hss = 0.1887 : val hss = 0.1688
Fold 2: train tss = 0.6240 : val tss = 0.6425 ::: train hss = 0.1374 : val hss = 0.0969
Fold 3: train tss = 0.6227 : val tss = 0.6679 ::: train hss = 0.1296 : val hss = 0.1947
Fold 4: train tss = 0.6275 : val tss = 0.6473 ::: train hss = 0.1426 : val hss = 0.1294
mean cv TSS: 0.6553
mean cv HSS: 0.1519
232/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6792 : val tss = 0.6739 ::: train hss = 0.2080 : val hss = 0.2734
Fold 1: train tss = 0.7113 : val tss = 0.7431 ::: train hss = 0.2318 : val hss = 0.1816
Fold 2: train tss = 0.7545 : val tss = 0.6625 ::: train hss = 0.2440 : val hss = 0.1072
Fold 3: train tss = 0.7350 : val tss = 0.6619 ::: train hss = 0.2116 : val hss = 0.2214
Fold 4: train tss = 0.7259 : val tss = 0.5313 ::: train hss = 0.2059 : val hss = 0.2457
mean cv TSS: 0.6545
mean cv HSS: 0.2059
233/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6630 : val tss = 0.6712 ::: train hss = 0.1962 : val hss = 0.2819
Fold 1: train tss = 0.6965 : val tss = 0.7579 ::: train hss = 0.2194 : val hss = 0.1793
Fold 2: train tss = 0.7426 : val tss = 0.6760 ::: train hss = 0.2381 : val hss = 0.1198
Fold 3: train tss = 0.7206 : val tss = 0.6185 ::: train hss = 0.2023 : val hss = 0.1389
Fold 4: train tss = 0.7034 : val tss = 0.6310 ::: train hss = 0.1906 : val hss = 0.1508
mean cv TSS: 0.6709
mean cv HSS: 0.1741
234/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7319 : val tss = 0.6525 ::: train hss = 0.2423 : val hss = 0.3177
Fold 1: train tss = 0.6959 : val tss = 0.7479 ::: train hss = 0.2243 : val hss = 0.1536
Fold 2: train tss = 0.6948 : val tss = 0.6423 ::: train hss = 0.1940 : val hss = 0.1603
Fold 3: train tss = 0.6170 : val tss = 0.6071 ::: train hss = 0.1280 : val hss = 0.1356
Fold 4: train tss = 0.6438 : val tss = 0.6448 ::: train hss = 0.1482 : val hss = 0.1545
mean cv TSS: 0.6589
mean cv HSS: 0.1843
235/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7205 : val tss = 0.5487 ::: train hss = 0.2854 : val hss = 0.2004
Fold 1: train tss = 0.6792 : val tss = 0.6953 ::: train hss = 0.2098 : val hss = 0.0762
Fold 2: train tss = 0.6175 : val tss = 0.5919 ::: train hss = 0.1483 : val hss = 0.0619
Fold 3: train tss = 0.6169 : val tss = 0.5912 ::: train hss = 0.1274 : val hss = 0.1322
Fold 4: train tss = 0.6342 : val tss = 0.6544 ::: train hss = 0.1443 : val hss = 0.1735
mean cv TSS: 0.6163
mean cv HSS: 0.1289
236/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7340 : val tss = 0.6381 ::: train hss = 0.2498 : val hss = 0.2646
Fold 1: train tss = 0.7480 : val tss = 0.7461 ::: train hss = 0.2666 : val hss = 0.1735
Fold 2: train tss = 0.7475 : val tss = 0.5921 ::: train hss = 0.2226 : val hss = 0.1807
Fold 3: train tss = 0.7188 : val tss = 0.6599 ::: train hss = 0.1857 : val hss = 0.2590
Fold 4: train tss = 0.6810 : val tss = 0.7025 ::: train hss = 0.1714 : val hss = 0.1052
mean cv TSS: 0.6677
mean cv HSS: 0.1966
237/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7102 : val tss = 0.6552 ::: train hss = 0.2255 : val hss = 0.2770
Fold 1: train tss = 0.7246 : val tss = 0.6564 ::: train hss = 0.2474 : val hss = 0.2685
Fold 2: train tss = 0.7370 : val tss = 0.6527 ::: train hss = 0.2236 : val hss = 0.1152
Fold 3: train tss = 0.6946 : val tss = 0.6582 ::: train hss = 0.1698 : val hss = 0.1693
Fold 4: train tss = 0.6980 : val tss = 0.5837 ::: train hss = 0.1924 : val hss = 0.1370
mean cv TSS: 0.6412
mean cv HSS: 0.1934
238/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6093 : val tss = 0.2117 ::: train hss = 0.1441 : val hss = 0.0266
Fold 1: train tss = 0.6865 : val tss = 0.7319 ::: train hss = 0.2169 : val hss = 0.1086
Fold 2: train tss = 0.6600 : val tss = 0.6073 ::: train hss = 0.1718 : val hss = 0.0757
Fold 3: train tss = 0.6450 : val tss = 0.6519 ::: train hss = 0.1420 : val hss = 0.1616
Fold 4: train tss = 0.6527 : val tss = 0.5918 ::: train hss = 0.1595 : val hss = 0.2124
mean cv TSS: 0.5589
mean cv HSS: 0.1170
239/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6182 : val tss = -0.0625 ::: train hss = 0.1660 : val hss = -0.0542
Fold 1: train tss = 0.6158 : val tss = 0.7002 ::: train hss = 0.1630 : val hss = 0.1429
Fold 2: train tss = 0.6361 : val tss = 0.6588 ::: train hss = 0.1471 : val hss = 0.1297
Fold 3: train tss = 0.6353 : val tss = 0.6098 ::: train hss = 0.1389 : val hss = 0.1370
Fold 4: train tss = 0.6230 : val tss = 0.6364 ::: train hss = 0.1354 : val hss = 0.1263
mean cv TSS: 0.5085
mean cv HSS: 0.0963
240/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6581 : val tss = 0.6727 ::: train hss = 0.2022 : val hss = 0.2626
Fold 1: train tss = 0.6719 : val tss = 0.7619 ::: train hss = 0.2055 : val hss = 0.1638
Fold 2: train tss = 0.6975 : val tss = 0.6370 ::: train hss = 0.1990 : val hss = 0.0818
Fold 3: train tss = 0.6979 : val tss = 0.6261 ::: train hss = 0.1805 : val hss = 0.1477
Fold 4: train tss = 0.7026 : val tss = 0.6193 ::: train hss = 0.1902 : val hss = 0.1452
mean cv TSS: 0.6634
mean cv HSS: 0.1602
241/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6504 : val tss = 0.6767 ::: train hss = 0.1915 : val hss = 0.2680
Fold 1: train tss = 0.6653 : val tss = 0.7530 ::: train hss = 0.2010 : val hss = 0.1737
Fold 2: train tss = 0.6978 : val tss = 0.6463 ::: train hss = 0.1966 : val hss = 0.0859
Fold 3: train tss = 0.6938 : val tss = 0.6430 ::: train hss = 0.1759 : val hss = 0.1554
Fold 4: train tss = 0.6920 : val tss = 0.6417 ::: train hss = 0.1828 : val hss = 0.1463
mean cv TSS: 0.6721
mean cv HSS: 0.1659
242/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}

Total number of parameters: 6221357
Fold 0: train tss = 0.7784 : val tss = 0.6634 ::: train hss = 0.3074 : val hss = 0.2402
Fold 1: train tss = 0.6745 : val tss = 0.7258 ::: train hss = 0.2066 : val hss = 0.1629
Fold 2: train tss = 0.6541 : val tss = 0.6301 ::: train hss = 0.1600 : val hss = 0.0814
Fold 3: train tss = 0.6275 : val tss = 0.6221 ::: train hss = 0.1315 : val hss = 0.1471
Fold 4: train tss = 0.6217 : val tss = 0.6687 ::: train hss = 0.1362 : val hss = 0.1284
mean cv TSS: 0.6620
mean cv HSS: 0.1520
243/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6769 : val tss = 0.6491 ::: train hss = 0.1903 : val hss = 0.1976
Fold 1: train tss = 0.6544 : val tss = 0.7476 ::: train hss = 0.1935 : val hss = 0.1290
Fold 2: train tss = 0.5850 : val tss = 0.6573 ::: train hss = 0.1113 : val hss = 0.1076
Fold 3: train tss = 0.5970 : val tss = 0.5688 ::: train hss = 0.1210 : val hss = 0.1126
Fold 4: train tss = 0.6207 : val tss = 0.6618 ::: train hss = 0.1383 : val hss = 0.1652
mean cv TSS: 0.6569
mean cv HSS: 0.1424
244/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.6689 : val tss = 0.6652 ::: train hss = 0.1963 : val hss = 0.2615
Fold 1: train tss = 0.7076 : val tss = 0.7571 ::: train hss = 0.2321 : val hss = 0.1601
Fold 2: train tss = 0.7402 : val tss = 0.6293 ::: train hss = 0.2338 : val hss = 0.0809
Fold 3: train tss = 0.6796 : val tss = 0.4994 ::: train hss = 0.1660 : val hss = 0.0842
Fold 4: train tss = 0.7104 : val tss = 0.5751 ::: train hss = 0.1921 : val hss = 0.1613
mean cv TSS: 0.6252
mean cv HSS: 0.1496
245/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6612 : val tss = 0.6702 ::: train hss = 0.1897 : val hss = 0.2643
Fold 1: train tss = 0.6956 : val tss = 0.7464 ::: train hss = 0.2186 : val hss = 0.1460
Fold 2: train tss = 0.6386 : val tss = 0.5781 ::: train hss = 0.1430 : val hss = 0.0568
Fold 3: train tss = 0.6792 : val tss = 0.6605 ::: train hss = 0.1645 : val hss = 0.1921
Fold 4: train tss = 0.6545 : val tss = 0.6740 ::: train hss = 0.1541 : val hss = 0.1067
mean cv TSS: 0.6659
mean cv HSS: 0.1532
246/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 6221357
Fold 0: train tss = 0.5869 : val tss = 0.1873 ::: train hss = 0.1386 : val hss = 0.0248
Fold 1: train tss = 0.6610 : val tss = 0.6668 ::: train hss = 0.1888 : val hss = 0.2379
Fold 2: train tss = 0.6190 : val tss = 0.6105 ::: train hss = 0.1445 : val hss = 0.0774
Fold 3: train tss = 0.6354 : val tss = 0.6062 ::: train hss = 0.1393 : val hss = 0.1331
Fold 4: train tss = 0.6318 : val tss = 0.6598 ::: train hss = 0.1422 : val hss = 0.1437
mean cv TSS: 0.5461
mean cv HSS: 0.1234
247/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 1024, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 6221357
Fold 0: train tss = 0.6078 : val tss = 0.5573 ::: train hss = 0.1569 : val hss = 0.1762
Fold 1: train tss = 0.6408 : val tss = 0.6323 ::: train hss = 0.1863 : val hss = 0.0533
Fold 2: train tss = 0.5453 : val tss = 0.6406 ::: train hss = 0.1215 : val hss = 0.0880
Fold 3: train tss = 0.6379 : val tss = 0.6131 ::: train hss = 0.1421 : val hss = 0.1473
Fold 4: train tss = 0.6260 : val tss = 0.6581 ::: train hss = 0.1428 : val hss = 0.1508
mean cv TSS: 0.6203
mean cv HSS: 0.1231
248/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6625 : val tss = 0.6747 ::: train hss = 0.2057 : val hss = 0.2672
Fold 1: train tss = 0.6770 : val tss = 0.7511 ::: train hss = 0.2084 : val hss = 0.1768
Fold 2: train tss = 0.7039 : val tss = 0.6417 ::: train hss = 0.2038 : val hss = 0.0879
Fold 3: train tss = 0.6989 : val tss = 0.6171 ::: train hss = 0.1817 : val hss = 0.1349
Fold 4: train tss = 0.7054 : val tss = 0.6135 ::: train hss = 0.1947 : val hss = 0.1400
mean cv TSS: 0.6596
mean cv HSS: 0.1613
249/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6425 : val tss = 0.6700 ::: train hss = 0.1874 : val hss = 0.2558
Fold 1: train tss = 0.6690 : val tss = 0.7648 ::: train hss = 0.1994 : val hss = 0.1670
Fold 2: train tss = 0.6863 : val tss = 0.6483 ::: train hss = 0.1905 : val hss = 0.0862
Fold 3: train tss = 0.6973 : val tss = 0.6463 ::: train hss = 0.1801 : val hss = 0.1636
Fold 4: train tss = 0.6920 : val tss = 0.6418 ::: train hss = 0.1823 : val hss = 0.1383
mean cv TSS: 0.6742
mean cv HSS: 0.1622
250/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.7180 : val tss = 0.6313 ::: train hss = 0.2374 : val hss = 0.2056
Fold 1: train tss = 0.6834 : val tss = 0.7608 ::: train hss = 0.2270 : val hss = 0.1342
Fold 2: train tss = 0.6505 : val tss = 0.6395 ::: train hss = 0.1635 : val hss = 0.0857
Fold 3: train tss = 0.6262 : val tss = 0.6013 ::: train hss = 0.1297 : val hss = 0.1323
Fold 4: train tss = 0.6079 : val tss = 0.6516 ::: train hss = 0.1280 : val hss = 0.1453
mean cv TSS: 0.6569
mean cv HSS: 0.1406
251/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.7043 : val tss = 0.0607 ::: train hss = 0.2804 : val hss = 0.0063
Fold 1: train tss = 0.6625 : val tss = 0.7553 ::: train hss = 0.2018 : val hss = 0.1360
Fold 2: train tss = 0.6177 : val tss = 0.6298 ::: train hss = 0.1398 : val hss = 0.0798
Fold 3: train tss = 0.6095 : val tss = 0.6155 ::: train hss = 0.1237 : val hss = 0.1800
Fold 4: train tss = 0.6274 : val tss = 0.6633 ::: train hss = 0.1409 : val hss = 0.1592
mean cv TSS: 0.5449
mean cv HSS: 0.1123
252/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.6645 : val tss = 0.6622 ::: train hss = 0.1932 : val hss = 0.2533
Fold 1: train tss = 0.7173 : val tss = 0.7515 ::: train hss = 0.2368 : val hss = 0.1459
Fold 2: train tss = 0.7336 : val tss = 0.6613 ::: train hss = 0.2230 : val hss = 0.1019
Fold 3: train tss = 0.7099 : val tss = 0.6065 ::: train hss = 0.1834 : val hss = 0.1362
Fold 4: train tss = 0.7300 : val tss = 0.6653 ::: train hss = 0.2169 : val hss = 0.1315
mean cv TSS: 0.6694
mean cv HSS: 0.1538
253/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'sgd', 'sequence_length': 45, 'weight_decay': 0.05}

Total number of parameters: 12035629
Fold 0: train tss = 0.6664 : val tss = 0.6709 ::: train hss = 0.1932 : val hss = 0.2560
Fold 1: train tss = 0.7020 : val tss = 0.7547 ::: train hss = 0.2239 : val hss = 0.1427
Fold 2: train tss = 0.6447 : val tss = 0.6098 ::: train hss = 0.1519 : val hss = 0.0692
Fold 3: train tss = 0.6398 : val tss = 0.5556 ::: train hss = 0.1317 : val hss = 0.1067
Fold 4: train tss = 0.6887 : val tss = 0.6345 ::: train hss = 0.1762 : val hss = 0.1492
mean cv TSS: 0.6451
mean cv HSS: 0.1448
254/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.03}
Total number of parameters: 12035629
Fold 0: train tss = 0.5279 : val tss = 0.4438 ::: train hss = 0.1110 : val hss = 0.0817
Fold 1: train tss = 0.6462 : val tss = 0.7484 ::: train hss = 0.1829 : val hss = 0.1523
Fold 2: train tss = 0.6646 : val tss = 0.6738 ::: train hss = 0.1665 : val hss = 0.1495
Fold 3: train tss = 0.6106 : val tss = 0.5229 ::: train hss = 0.1298 : val hss = 0.1020
Fold 4: train tss = 0.6283 : val tss = 0.6398 ::: train hss = 0.1448 : val hss = 0.1814
mean cv TSS: 0.6058
mean cv HSS: 0.1334
255/256
{'batch_size': 1024, 'bce_pos_class_weight': 50, 'cnn_filters': 256, 'cv_folds': 5, 'dropout_p': 0.35, 'fc_size': 2048, 'loss': 'bce', 'lr': 0.01, 'num_epochs': 40, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 12035629
Fold 0: train tss = 0.6153 : val tss = 0.4261 ::: train hss = 0.2145 : val hss = 0.1002
Fold 1: train tss = 0.6437 : val tss = 0.7443 ::: train hss = 0.1872 : val hss = 0.1718
Fold 2: train tss = 0.6399 : val tss = 0.6665 ::: train hss = 0.1534 : val hss = 0.1451
Fold 3: train tss = 0.6323 : val tss = 0.6444 ::: train hss = 0.1369 : val hss = 0.1742
Fold 4: train tss = 0.6298 : val tss = 0.6529 ::: train hss = 0.1477 : val hss = 0.1422
mean cv TSS: 0.6269
mean cv HSS: 0.1467

,batch_size,bce_pos_class_weight,cnn_filters,dropout_p,fc_size,lr,optimizer_type,sequence_length,weight_decay,tss,hss
165,1024,35,256,0.05,1024,0.010,sgd,45,0.05,0.6828,0.1942
57,512,35,256,0.35,2048,0.005,sgd,45,0.05,0.6827,0.1843
224,1024,50,256,0.05,1024,0.005,sgd,45,0.03,0.6826,0.1746
205,1024,50,48,0.05,2048,0.010,sgd,45,0.05,0.6800,0.1726
105,512,50,256,0.05,2048,0.005,sgd,45,0.05,0.6797,0.1773
220,1024,50,48,0.35,2048,0.010,sgd,45,0.03,0.6791,0.1611
97,512,50,256,0.05,1024,0.005,sgd,45,0.05,0.6774,0.1748
28,512,35,48,0.35,2048,0.010,sgd,45,0.03,0.6753,0.1967
49,512,35,256,0.35,1024,0.005,sgd,45,0.05,0.6747,0.1827
22,512,35,48,0.35,1024,0.010,adam,45,0.03,0.6742,0.1888
249,1024,50,256,0.35,2048,0.005,sgd,45,0.05,0.6742,0.1622
59,512,35,256,0.35,2048,0.005,adam,45,0.05,0.6741,0.1912
209,1024,50,48,0.35,1024,0.005,sgd,45,0.05,0.6738,0.1483
185,1024,35,256,0.35,2048,0.005,sgd,45,0.05,0.6736,0.1947
156,1024,35,48,0.35,2048,0.010,sgd,45,0.03,0.6727,0.2042
196,1024,50,48,0.05,1024,0.010,sgd,45,0.03,0.6727,0.1732
241,1024,50,256,0.35,1024,0.005,sgd,45,0.05,0.6721,0.1659
177,1024,35,256,0.35,1024,0.005,sgd,45,0.05,0.6720,0.1917
233,1024,50,256,0.05,2048,0.005,sgd,45,0.05,0.6709,0.1741
229,1024,50,256,0.05,1024,0.010,sgd,45,0.05,0.6707,0.1888

In [10]:
grid.sort_values(by=['hss', 'tss'], ascending=False).head(20)

,batch_size,bce_pos_class_weight,cnn_filters,dropout_p,fc_size,lr,optimizer_type,sequence_length,weight_decay,tss,hss
142,1024,35,48,0.05,2048,0.010,adam,45,0.03,0.6119,0.2621
143,1024,35,48,0.05,2048,0.010,adam,45,0.05,0.6492,0.2425
141,1024,35,48,0.05,2048,0.010,sgd,45,0.05,0.6637,0.2420
159,1024,35,48,0.35,2048,0.010,adam,45,0.05,0.6135,0.2395
169,1024,35,256,0.05,2048,0.005,sgd,45,0.05,0.6488,0.2384
163,1024,35,256,0.05,1024,0.005,adam,45,0.05,0.6208,0.2365
135,1024,35,48,0.05,1024,0.010,adam,45,0.05,0.6075,0.2354
8,512,35,48,0.05,2048,0.005,sgd,45,0.03,0.6254,0.2328
183,1024,35,256,0.35,1024,0.010,adam,45,0.05,0.6455,0.2321
44,512,35,256,0.05,2048,0.010,sgd,45,0.03,0.6422,0.2310
173,1024,35,256,0.05,2048,0.010,sgd,45,0.05,0.6317,0.2308
131,1024,35,48,0.05,1024,0.005,adam,45,0.05,0.6392,0.2306
168,1024,35,256,0.05,2048,0.005,sgd,45,0.03,0.6495,0.2300
170,1024,35,256,0.05,2048,0.005,adam,45,0.03,0.6070,0.2269
132,1024,35,48,0.05,1024,0.010,sgd,45,0.03,0.6438,0.2255
172,1024,35,256,0.05,2048,0.010,sgd,45,0.03,0.6213,0.2236
161,1024,35,256,0.05,1024,0.005,sgd,45,0.05,0.6543,0.2224
140,1024,35,48,0.05,2048,0.010,sgd,45,0.03,0.6703,0.2211
160,1024,35,256,0.05,1024,0.005,sgd,45,0.03,0.6323,0.2209
133,1024,35,48,0.05,1024,0.010,sgd,45,0.05,0.6534,0.2201

In [11]:
if grid.empty:
    print("grid empty")
else:
    grid.to_csv("1_big_cnn_ts_hypertune_grid_output_10.csv")
    print("grid output successful, saved as 1_big_cnn_ts_hypertune_grid_output_10.csv")

grid output successful, saved as 1_big_cnn_ts_hypertune_grid_output_10.csv