In [1]:
import torch

### set up CUDA as device if available
if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")
    cuda_id = torch.cuda.current_device()
    print(f"ID of current CUDA device:{torch.cuda.current_device()}")
    print(f"Name of current CUDA device:{torch.cuda.get_device_name(cuda_id)}")
    print(f"CUDA version: {torch.version.cuda}")
else:
    print("GPU is not available, using CPU")
    device = torch.device("cpu")
print(f"device: {device}")

GPU is available
cuda
CUDA version: 12.4
ID of current CUDA device:0
Name of current CUDA device:NVIDIA H200

In [2]:
import numpy as np
import random
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm, trange
from IPython import display
from sklearn.metrics import average_precision_score
# from conf_and_plot import confusion_matrix_plots
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import KFold
from sklearn.model_selection import ParameterGrid
import seaborn as sns
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import kruskal
import torch.nn.functional as F
from IPython.display import clear_output
import statistics

def seed_all(seed):
    if not seed:
        seed = 10

    print("[ Using Seed : ", seed, " ]")

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

seed_all(2025)

[ Using Seed :  2025  ]

In [3]:
scint_thresh = 0.1 # set the phase scintillation threshold

### following variable not being used anywhere
scint_outlier_thresh = 5. # set the value that determines phase scintillation outliers (these data samples will be removed)

processed_data_2015 = pd.read_csv("processed_data_2015.csv")
processed_data_2015 = processed_data_2015.drop(processed_data_2015.columns[0], axis=1)
predicted_label = 'sigmaPhi projected to vertical at prediction time [radians]'
y = processed_data_2015[predicted_label].values
print(y.shape)

X_fSelect = processed_data_2015.drop(predicted_label, axis=1)
X_fSelect = X_fSelect.values
print(X_fSelect.shape)

(4465846,)
(4465846, 15)

In [4]:
class LSTM_model(nn.Module):
    def __init__(self, hidden_layer_size, num_layers, dropout_p, loss, input_layer_norm, input_size=15, num_classes=1):
        super(LSTM_model, self).__init__()
        self.loss = loss
        self.input_layer_norm = input_layer_norm
        
        self.lstm = nn.LSTM(input_size, hidden_layer_size, num_layers, batch_first=True)
        self.dropout = nn.Dropout(dropout_p)
        self.fc = nn.Linear(hidden_layer_size, num_classes)
        self.sigmoid = nn.Sigmoid()

        self.layer_norm_input = nn.LayerNorm(input_size)
        self.layer_norm_output = nn.LayerNorm(hidden_layer_size)

    def forward(self, x):

        if self.input_layer_norm == True:
            x = self.layer_norm_input(x)
        elif self.input_layer_norm == False:
            pass
        
        lstm_out, _ = self.lstm(x)

        # lstm_out = self.layer_norm_output(lstm_out)
        lstm_out = self.dropout(lstm_out)
        output = self.fc(lstm_out)
        
        if self.loss == 'focal':
            output = self.sigmoid(output)
        elif self.loss == 'bce':
            pass
        return output

In [5]:
def true_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    tss = (TP / (TP + FN)) - (FP / (FP + TN))
    return tss

def heidke_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    
    numerator = 2 * (TP * TN - FP * FN)
    denominator = (TP + FP) * (FP + TN) + (TP + FN) * (TN + FP)
    
    # Avoid division by zero
    if denominator == 0:
        return 0.0
    
    hss = numerator / denominator
    return hss

In [6]:
class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction  # 'mean', 'sum', or 'none'

    def forward(self, inputs, targets):
        BCE_loss = F.binary_cross_entropy(inputs, targets, reduction='none')
        p_t = inputs * targets + (1 - inputs) * (1 - targets)
        focal_loss = self.alpha * (1 - p_t) ** self.gamma * BCE_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        elif self.reduction == 'none':
            return focal_loss
        else:
            raise ValueError(f"Invalid reduction method: {self.reduction}")

In [7]:
def train_model_with_cv(model, train_dataloader, val_dataloader, criterion, optimizer, scheduler, num_epochs):

    epochs = []
    training_loss = []
    validation_loss = []
    training_tss = []
    validation_tss = []
    training_hss = []
    validation_hss = []

    for epoch in range(num_epochs):

        ### training loop
        model.train()
        running_loss = 0.0
        predicted_training_labels = np.array([])
        y_train = np.array([])

        # for batch_inputs, batch_labels in tqdm(train_dataloader):
        for batch_inputs, batch_labels in train_dataloader:
            
            batch_inputs = batch_inputs.to(device)
            batch_labels = batch_labels.to(device)
            
            optimizer.zero_grad()
            output = model(batch_inputs)
            
            output.to(device)
            
            loss = criterion(output, batch_labels.float())
            loss.backward()
            optimizer.step()
            
            if scheduler == False:
                pass
            else:
                scheduler.step()
            
            running_loss += loss.item()
            with torch.no_grad(): predicted_training_labels = np.append(predicted_training_labels, output.cpu())
            with torch.no_grad(): y_train = np.append(y_train, batch_labels.cpu())

        predicted_training_labels = np.where(predicted_training_labels > 0.1, 1, 0)

        train_loss = running_loss / len(train_dataloader)
        train_tss = true_skill_score(y_train.astype(int), predicted_training_labels.astype(int))
        train_hss = heidke_skill_score(y_train.astype(int), predicted_training_labels.astype(int))

        ### validation loop
        model.eval()
        with torch.no_grad():
            running_loss = 0.0
            predicted_val_labels = np.array([])
            y_val = np.array([])

            # for batch_inputs, labels in tqdm(val_dataloader):
            for batch_inputs, batch_labels in val_dataloader:
            
                batch_inputs = batch_inputs.to(device)
                batch_labels = batch_labels.to(device)
                
                outputs = model(batch_inputs)
            
                outputs.to(device)
                
                outputs = model(batch_inputs)
                loss = criterion(outputs, batch_labels.float())
                running_loss += loss.item()
                predicted_val_labels = np.append(predicted_val_labels, outputs.cpu())
                y_val = np.append(y_val, batch_labels.cpu())

        predicted_val_labels = np.where(predicted_val_labels > 0.1, 1, 0)

        val_loss = running_loss / len(val_dataloader)
        val_tss = true_skill_score(y_val.astype(int), predicted_val_labels.astype(int))
        val_hss = heidke_skill_score(y_val.astype(int), predicted_val_labels.astype(int))

        epochs.append(epoch)
        training_loss.append(train_loss)
        validation_loss.append(val_loss)
        training_tss.append(train_tss)
        validation_tss.append(val_tss)
        training_hss.append(train_hss)
        validation_hss.append(val_hss)

    return training_hss, validation_hss, training_tss, validation_tss

In [8]:
class LSTMBinaryTimeSeriesClassifier():
    def __init__(self, hidden_layer_size=16, num_layers=2, sequence_length=60, dropout_p=0.1, 
                 batch_size=64, optimizer_type = 'adam', lr=0.001, sgd_momentum=0.9, weight_decay=0.0001, 
                 loss='bce', bce_pos_class_weight=50, focal_alpha=0.25, focal_gamma=2,
                 num_epochs=5, cv_folds=5, scheduler_t=0, input_layer_norm=False):
        self.hidden_layer_size = hidden_layer_size
        self.num_layers = num_layers
        self.sequence_length = sequence_length
        self.dropout_p = dropout_p
        self.batch_size = batch_size
        self.optimizer_type = optimizer_type
        self.lr = lr
        self.weight_decay = weight_decay
        self.sgd_momentum = sgd_momentum
        self.loss = loss
        self.bce_pos_class_weight = bce_pos_class_weight
        self.focal_alpha = focal_alpha
        self.focal_gamma = focal_gamma
        self.num_epochs = num_epochs
        self.cv_folds = cv_folds
        self.scheduler_t = scheduler_t
        self.input_layer_norm = input_layer_norm
        
    def reshape_data_to_seq_length(self, data, seq_len):
        num_samples = data.shape[0]
        input_features = data.shape[1]
        num_batches = num_samples // seq_len
        data = data[:num_batches * seq_len] # truncate points that don't divide evenly
        reshaped_data = data.reshape(num_batches, seq_len, input_features)
        return reshaped_data

    def reshape_labels_to_seq_length(self, labels, seq_len):
        labels = torch.from_numpy(labels) if isinstance(labels, np.ndarray) else labels
        num_samples = labels.shape[0]
        num_batches = num_samples // seq_len
        labels = labels[:num_batches * seq_len] # truncate points that don't divide evenly
        labels = labels.view(num_batches, seq_len, -1)
        return labels
    
    def fit(self, X, y):

        cv_tss_values = []
        cv_hss_values = []

        tscv = TimeSeriesSplit(n_splits=self.cv_folds)
        for i, (train_index, val_index) in enumerate(tscv.split(X)):
        
            model = LSTM_model(hidden_layer_size=self.hidden_layer_size, 
                               num_layers=self.num_layers, 
                               dropout_p=self.dropout_p, 
                               loss=self.loss, input_layer_norm=self.input_layer_norm)
            model.to(device)
            
            if self.loss == 'bce':
                criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([self.bce_pos_class_weight]).to(device))
            elif self.loss == 'focal':
                criterion = FocalLoss(alpha=self.focal_alpha, gamma=self.focal_gamma)

            if self.optimizer_type == 'adam':
                optimizer = optim.Adam(model.parameters(), lr=self.lr, weight_decay=self.weight_decay)
            elif self.optimizer_type == 'sgd':
                optimizer = optim.SGD(model.parameters(), lr=self.lr, momentum=self.sgd_momentum, weight_decay=self.weight_decay)

            if self.scheduler_t > 0:
                scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=self.scheduler_t)
            else:
                scheduler = False

            X_train, X_val = X[train_index], X[val_index]
            y_train, y_val = y[train_index], y[val_index]
            
            scaler_X = RobustScaler()
            scaler_X = scaler_X.fit(X_train)

            X_train_scaled = scaler_X.transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            
            X_train_scaled = self.reshape_data_to_seq_length(X_train_scaled, self.sequence_length)
            X_val_scaled = self.reshape_data_to_seq_length(X_val_scaled, self.sequence_length)

            train_labels = self.reshape_labels_to_seq_length(y_train, self.sequence_length)
            val_labels = self.reshape_labels_to_seq_length(y_val, self.sequence_length)
            
            train_inputs = torch.tensor(X_train_scaled, dtype=torch.float32)#.transpose(1, 2)  # Shape: [batch_size, 15, 1]
            train_inputs = train_inputs.to(device)
            train_labels = train_labels.to(device)
            train_dataset = TensorDataset(train_inputs, train_labels)
            train_dataloader = DataLoader(train_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)

            val_inputs = torch.tensor(X_val_scaled, dtype=torch.float32)#.transpose(1, 2)  # Shape: [batch_size, 15, 1]
            val_inputs = val_inputs.to(device)
            val_labels = val_labels.to(device)
            val_dataset = TensorDataset(val_inputs, val_labels)
            val_dataloader = DataLoader(val_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)
            
            training_hss, validation_hss, training_tss, validation_tss = \
            train_model_with_cv(model, 
                 train_dataloader, val_dataloader, 
                 criterion, optimizer, scheduler,
                 num_epochs=self.num_epochs)
            cv_tss_values.append(validation_tss[-1])
            cv_hss_values.append(validation_hss[-1])

            if i == 0:
                total_params = sum(p.numel() for p in model.parameters())
                print(f'Total number of parameters: {total_params}')
                
            print(f"Fold {i}: train tss = {training_tss[-1]:.4f} : val tss = {validation_tss[-1]:.4f} ::: train hss = {training_hss[-1]:.4f} : val hss = {validation_hss[-1]:.4f}")
        
        return cv_hss_values, cv_tss_values

In [9]:
training_data_size = 50000

X_train, X_test, \
    y_train, y_test, \
        idx_train, idx_test = train_test_split(X_fSelect, y, range(len(y)), train_size=training_data_size, shuffle=False)

### strategic hypertune iteration 1
param_grid = {
    'hidden_layer_size': [4, 16],
    'num_layers': [2, 4],
    'sequence_length': [15, 45],
    'dropout_p': [0.1, 0.5],
    'batch_size': [32, 512],
    'lr': [0.0001, 0.01],
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.0001, 0.01],
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 75],
    'input_layer_norm':[True, False],
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 2
param_grid = {
    'hidden_layer_size': [2, 8],  ### changed
    'num_layers': [1, 4],  ### changed
    'sequence_length': [15, 45],
    'dropout_p': [0.1, 0.5],
    'batch_size': [256, 1024],  ### changed
    'lr': [0.005, 0.01],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.0001, 0.01],
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 75],
    'input_layer_norm':[True, False],
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 3
param_grid = {
    'hidden_layer_size': [2, 4, 12],  ### changed, added 1 dimension
    'num_layers': [1, 2],  ### changed
    'sequence_length': [30, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [128, 256],  ### changed
    'lr': [0.005, 0.01],  
    'optimizer_type': ['adam'],  ### changed, removed 1 dimension
    'weight_decay':[0.0001, 0.01],
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 75],
    'input_layer_norm':[True, False],
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 4
param_grid = {
    'hidden_layer_size': [2, 4, 12],  
    'num_layers': [1, 2],  
    'sequence_length': [40, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [128, 256],  
    'lr': [0.005, 0.01],  
    'optimizer_type': ['adam'],  
    'weight_decay':[0.001, 0.01],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 50],  ### changed
    'input_layer_norm':[True, False],
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 5
param_grid = {
    'hidden_layer_size': [2, 4, 16],  ### changed
    'num_layers': [1, 2],  
    'sequence_length': [15, 30, 45],  ### changed, added 1 dimension
    'dropout_p': [0.1, 0.5],
    'batch_size': [128, 256],  
    'lr': [0.005, 0.0075],  ### changed
    'optimizer_type': ['adam'],  
    'weight_decay':[0.0075, 0.025],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [15, 30],  ### changed
    'input_layer_norm':[False],  ### changed, removed 1 dimension
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 6
param_grid = {
    'hidden_layer_size': [2, 4, 32],  ### changed
    'num_layers': [1, 2],  
    'sequence_length': [15, 40, 45],  ### changed
    'dropout_p': [0.1, 0.5],
    'batch_size': [128, 256],  
    'lr': [0.005, 0.0075],  
    'optimizer_type': ['adam'],  
    'weight_decay':[0.01, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [15, 30, 45],  ### changed, added 1 dimension
    'input_layer_norm':[False],  
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 7
param_grid = {
    'hidden_layer_size': [2, 4, 8],  ### changed
    'num_layers': [1, 2],  
    'sequence_length': [15, 40, 45],  
    'dropout_p': [0.1, 0.3],  ### changed
    'batch_size': [128, 256],  
    'lr': [0.0025, 0.01],  ### changed
    'optimizer_type': ['adam'],  
    'weight_decay':[0.005, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [20, 40, 60],  ### changed
    'input_layer_norm':[False],  
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 8
param_grid = {
    'hidden_layer_size': [2, 4, 64],  ### changed
    'num_layers': [1, 2],  
    'sequence_length': [15, 40, 45],  
    'dropout_p': [0.1, 0.3],  
    'batch_size': [128, 256],  
    'lr': [0.01, 0.025],  ### changed
    'optimizer_type': ['adam'],  
    'weight_decay':[0.001, 0.075],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [15, 35, 65],  ### changed
    'input_layer_norm':[False],  
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 9
param_grid = {
    'hidden_layer_size': [2, 4, 24],  ### changed
    'num_layers': [1, 2],  
    'sequence_length': [25, 35, 45],  ### changed
    'dropout_p': [0.1, 0.2],  ### changed
    'batch_size': [128, 256],  
    'lr': [0.005, 0.01],  ### changed
    'optimizer_type': ['adam'],  
    'weight_decay':[0.01, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [10, 30, 60],  ### changed
    'input_layer_norm':[False],  
    'num_epochs': [50],
    'cv_folds': [5], 
}

### strategic hypertune iteration 10
param_grid = {
    'hidden_layer_size': [2, 4, 16],  ### changed
    'num_layers': [1, 2],  
    'sequence_length': [10, 35, 45],  ### changed
    'dropout_p': [0.1, 0.2],  
    'batch_size': [128, 256],  
    'lr': [0.0065, 0.015],  ### changed
    'optimizer_type': ['adam'],  
    'weight_decay':[0.01, 0.05],  
    'loss': ['bce'],
    'bce_pos_class_weight': [5, 50, 80],  ### changed
    'input_layer_norm':[False],  
    'num_epochs': [50],
    'cv_folds': [5], 
}

param_combinations = list(ParameterGrid(param_grid))

grid = pd.DataFrame()
tss_distributions = []
hss_distributions = []
mean_tss_scores = []
mean_hss_scores = []
for params in param_combinations:

    print(str(param_combinations.index(params)) + "/" + str(len(param_combinations)))
    print(params)

    lstm_time_series_classifier = LSTMBinaryTimeSeriesClassifier(**params)
    cv_hss_values, cv_tss_values = lstm_time_series_classifier.fit(X_train, y_train)
    
    tss_distributions.append(cv_tss_values)
    hss_distributions.append(cv_hss_values)
    mean_cv_tss = sum(cv_tss_values)/len(cv_tss_values)
    mean_cv_hss = sum(cv_hss_values)/len(cv_hss_values)
    print(f"mean cv TSS: {mean_cv_tss:.4f}")
    print(f"mean cv HSS: {mean_cv_hss:.4f}")
    mean_tss_scores.append(mean_cv_tss)
    mean_hss_scores.append(mean_cv_hss)
    
    if params == param_combinations[0]:
        grid = pd.DataFrame(params, index=[0])
    else:
        grid = pd.concat([grid, pd.DataFrame([params])], ignore_index=True)

grid['tss'] = [round(num, 4) for num in mean_tss_scores]
grid['hss'] = [round(num, 4) for num in mean_hss_scores]
grid = grid.sort_values(by=['tss', 'hss'], ascending=False)
grid = grid.drop(columns=[col for col in ['num_epochs','cv_folds','loss','scheduler_t'] if col in grid.columns], axis=1)
grid.head(20)

0/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0500 : val tss = 0.0181 ::: train hss = 0.0952 : val hss = 0.0330
Fold 1: train tss = 0.5799 : val tss = 0.3466 ::: train hss = 0.6206 : val hss = 0.2443
Fold 2: train tss = 0.3356 : val tss = 0.6738 ::: train hss = 0.3479 : val hss = 0.5135
Fold 3: train tss = 0.5618 : val tss = 0.0262 ::: train hss = 0.4781 : val hss = 0.0297
Fold 4: train tss = 0.4661 : val tss = 0.4340 ::: train hss = 0.4137 : val hss = 0.4481
mean cv TSS: 0.2997
mean cv HSS: 0.2537
1/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3954 : val tss = 0.2363 ::: train hss = 0.4923 : val hss = 0.2234
Fold 2: train tss = 0.1812 : val tss = 0.4138 ::: train hss = 0.2452 : val hss = 0.4074
Fold 3: train tss = 0.3869 : val tss = -0.0041 ::: train hss = 0.3897 : val hss = -0.0063
Fold 4: train tss = 0.3019 : val tss = 0.5650 ::: train hss = 0.3483 : val hss = 0.4708
mean cv TSS: 0.2422
mean cv HSS: 0.2190
2/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6050 : val tss = 0.1456 ::: train hss = 0.7093 : val hss = 0.0849
Fold 2: train tss = 0.4893 : val tss = 0.5519 ::: train hss = 0.4573 : val hss = 0.5147
Fold 3: train tss = 0.6189 : val tss = 0.0267 ::: train hss = 0.5044 : val hss = 0.0222
Fold 4: train tss = 0.5082 : val tss = 0.3112 ::: train hss = 0.4770 : val hss = 0.3115
mean cv TSS: 0.2071
mean cv HSS: 0.1866
3/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4305 : val tss = 0.2557 ::: train hss = 0.4994 : val hss = 0.2380
Fold 2: train tss = 0.3706 : val tss = 0.5466 ::: train hss = 0.4017 : val hss = 0.4793
Fold 3: train tss = 0.5724 : val tss = 0.0224 ::: train hss = 0.4358 : val hss = 0.0219
Fold 4: train tss = 0.3979 : val tss = 0.5750 ::: train hss = 0.3868 : val hss = 0.4659
mean cv TSS: 0.2799
mean cv HSS: 0.2410
4/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = -0.0041 ::: train hss = 0.0000 : val hss = -0.0070
Fold 1: train tss = 0.6718 : val tss = 0.2773 ::: train hss = 0.5303 : val hss = 0.1437
Fold 2: train tss = 0.3330 : val tss = 0.5340 ::: train hss = 0.3958 : val hss = 0.5147
Fold 3: train tss = 0.6130 : val tss = 0.0583 ::: train hss = 0.5257 : val hss = 0.0422
Fold 4: train tss = 0.5589 : val tss = 0.4115 ::: train hss = 0.4589 : val hss = 0.3866
mean cv TSS: 0.2554
mean cv HSS: 0.2161
5/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5402 : val tss = 0.3352 ::: train hss = 0.6170 : val hss = 0.2267
Fold 2: train tss = 0.3498 : val tss = 0.5242 ::: train hss = 0.3677 : val hss = 0.4398
Fold 3: train tss = 0.6069 : val tss = 0.0360 ::: train hss = 0.5162 : val hss = 0.0421
Fold 4: train tss = 0.4999 : val tss = 0.5034 ::: train hss = 0.4820 : val hss = 0.4023
mean cv TSS: 0.2798
mean cv HSS: 0.2222
6/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5275 : val tss = 0.2563 ::: train hss = 0.5239 : val hss = 0.1980
Fold 2: train tss = 0.3433 : val tss = 0.6102 ::: train hss = 0.3391 : val hss = 0.4191
Fold 3: train tss = 0.5864 : val tss = 0.0358 ::: train hss = 0.4709 : val hss = 0.0414
Fold 4: train tss = 0.4685 : val tss = 0.3658 ::: train hss = 0.4003 : val hss = 0.3364
mean cv TSS: 0.2536
mean cv HSS: 0.1990
7/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.1071 : val tss = -0.0001 ::: train hss = 0.1749 : val hss = -0.0002
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: -0.0000
mean cv HSS: -0.0000
8/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5456 : val tss = 0.3782 ::: train hss = 0.5383 : val hss = 0.1978
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6511 : val tss = 0.0426 ::: train hss = 0.5089 : val hss = 0.0331
Fold 4: train tss = 0.4755 : val tss = 0.5976 ::: train hss = 0.4341 : val hss = 0.4947
mean cv TSS: 0.2037
mean cv HSS: 0.1451
9/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4815 : val tss = 0.0034 ::: train hss = 0.4377 : val hss = 0.0048
Fold 4: train tss = 0.1753 : val tss = 0.3281 ::: train hss = 0.2551 : val hss = 0.3459
mean cv TSS: 0.0663
mean cv HSS: 0.0701
10/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000

Fold 1: train tss = 0.5374 : val tss = 0.1325 ::: train hss = 0.6654 : val hss = 0.0896
Fold 2: train tss = 0.5712 : val tss = 0.6614 ::: train hss = 0.4550 : val hss = 0.4261
Fold 3: train tss = 0.5916 : val tss = 0.0720 ::: train hss = 0.4687 : val hss = 0.0819
Fold 4: train tss = 0.6607 : val tss = 0.4666 ::: train hss = 0.4100 : val hss = 0.3914
mean cv TSS: 0.2665
mean cv HSS: 0.1978
11/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5205 : val tss = -0.0054 ::: train hss = 0.4753 : val hss = -0.0077
Fold 4: train tss = 0.4244 : val tss = 0.4412 ::: train hss = 0.4225 : val hss = 0.3987
mean cv TSS: 0.0872
mean cv HSS: 0.0782
12/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.1527 ::: train hss = 0.0000 : val hss = 0.2146
Fold 1: train tss = 0.5714 : val tss = 0.1061 ::: train hss = 0.3246 : val hss = 0.0748
Fold 2: train tss = 0.2756 : val tss = 0.6779 ::: train hss = 0.2767 : val hss = 0.4371
Fold 3: train tss = 0.5207 : val tss = 0.0190 ::: train hss = 0.4206 : val hss = 0.0234
Fold 4: train tss = 0.4622 : val tss = 0.3512 ::: train hss = 0.3673 : val hss = 0.3931
mean cv TSS: 0.2614
mean cv HSS: 0.2286
13/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4317 : val tss = 0.2063 ::: train hss = 0.5270 : val hss = 0.1971
Fold 2: train tss = 0.0220 : val tss = 0.0109 ::: train hss = 0.0412 : val hss = 0.0212
Fold 3: train tss = 0.3467 : val tss = 0.0020 ::: train hss = 0.3326 : val hss = 0.0025
Fold 4: train tss = 0.2720 : val tss = 0.6235 ::: train hss = 0.3005 : val hss = 0.4705
mean cv TSS: 0.1685
mean cv HSS: 0.1383
14/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5890 : val tss = 0.3758 ::: train hss = 0.6288 : val hss = 0.2029
Fold 2: train tss = 0.5608 : val tss = 0.6562 ::: train hss = 0.4954 : val hss = 0.5097
Fold 3: train tss = 0.5834 : val tss = 0.0252 ::: train hss = 0.4826 : val hss = 0.0274
Fold 4: train tss = 0.5640 : val tss = 0.2359 ::: train hss = 0.4085 : val hss = 0.2661
mean cv TSS: 0.2586
mean cv HSS: 0.2012
15/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4367 : val tss = 0.3772 ::: train hss = 0.5453 : val hss = 0.2110
Fold 2: train tss = 0.3139 : val tss = 0.4554 ::: train hss = 0.3238 : val hss = 0.4208
Fold 3: train tss = 0.5047 : val tss = -0.0026 ::: train hss = 0.4109 : val hss = -0.0043
Fold 4: train tss = 0.4189 : val tss = 0.2271 ::: train hss = 0.3782 : val hss = 0.2503
mean cv TSS: 0.2114
mean cv HSS: 0.1756
16/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5363 : val tss = 0.1739 ::: train hss = 0.6322 : val hss = 0.1971
Fold 2: train tss = 0.4074 : val tss = 0.4284 ::: train hss = 0.3826 : val hss = 0.4477
Fold 3: train tss = 0.6712 : val tss = 0.0284 ::: train hss = 0.4981 : val hss = 0.0192
Fold 4: train tss = 0.5654 : val tss = 0.1029 ::: train hss = 0.4431 : val hss = 0.1298
mean cv TSS: 0.1467
mean cv HSS: 0.1588
17/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6049 : val tss = 0.2991 ::: train hss = 0.7054 : val hss = 0.2193
Fold 2: train tss = 0.2316 : val tss = 0.2487 ::: train hss = 0.3098 : val hss = 0.3403
Fold 3: train tss = 0.5878 : val tss = 0.0041 ::: train hss = 0.4554 : val hss = 0.0060
Fold 4: train tss = 0.4303 : val tss = 0.4261 ::: train hss = 0.3371 : val hss = 0.3720
mean cv TSS: 0.1956
mean cv HSS: 0.1875
18/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4657 : val tss = 0.2573 ::: train hss = 0.5083 : val hss = 0.1875
Fold 2: train tss = 0.3126 : val tss = 0.5663 ::: train hss = 0.3129 : val hss = 0.4204
Fold 3: train tss = 0.4653 : val tss = 0.0194 ::: train hss = 0.3752 : val hss = 0.0243
Fold 4: train tss = 0.4191 : val tss = 0.5624 ::: train hss = 0.3413 : val hss = 0.4261
mean cv TSS: 0.2811
mean cv HSS: 0.2116
19/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
20/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6661 : val tss = 0.2203 ::: train hss = 0.5841 : val hss = 0.2026
Fold 2: train tss = 0.3897 : val tss = 0.6557 ::: train hss = 0.3989 : val hss = 0.4413
Fold 3: train tss = 0.6719 : val tss = 0.0421 ::: train hss = 0.4973 : val hss = 0.0435
Fold 4: train tss = 0.3892 : val tss = 0.6247 ::: train hss = 0.3866 : val hss = 0.4287
mean cv TSS: 0.3086
mean cv HSS: 0.2232
21/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.2691 : val tss = 0.0000 ::: train hss = 0.3717 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2245 : val tss = -0.0004 ::: train hss = 0.2942 : val hss = -0.0007
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: -0.0001
mean cv HSS: -0.0001
22/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6230 : val tss = 0.2938 ::: train hss = 0.4529 : val hss = 0.2264
Fold 2: train tss = 0.4308 : val tss = 0.6311 ::: train hss = 0.4042 : val hss = 0.4735
Fold 3: train tss = 0.6684 : val tss = 0.0073 ::: train hss = 0.5161 : val hss = 0.0129
Fold 4: train tss = 0.5054 : val tss = 0.5522 ::: train hss = 0.4143 : val hss = 0.4544
mean cv TSS: 0.2969
mean cv HSS: 0.2334
23/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3445 : val tss = 0.2025 ::: train hss = 0.4194 : val hss = 0.2335
Fold 2: train tss = 0.0016 : val tss = 0.0000 ::: train hss = 0.0031 : val hss = 0.0000
Fold 3: train tss = 0.2683 : val tss = -0.0013 ::: train hss = 0.3376 : val hss = -0.0024
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0402
mean cv HSS: 0.0462
24/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0617 ::: train hss = 0.0000 : val hss = 0.1043
Fold 1: train tss = 0.5815 : val tss = 0.3294 ::: train hss = 0.6659 : val hss = 0.2663
Fold 2: train tss = 0.5160 : val tss = 0.6319 ::: train hss = 0.4570 : val hss = 0.4717
Fold 3: train tss = 0.5826 : val tss = 0.0257 ::: train hss = 0.4307 : val hss = 0.0285
Fold 4: train tss = 0.5565 : val tss = 0.4105 ::: train hss = 0.4848 : val hss = 0.4568
mean cv TSS: 0.2919
mean cv HSS: 0.2655
25/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5581 : val tss = 0.2460 ::: train hss = 0.6261 : val hss = 0.2044
Fold 2: train tss = 0.1998 : val tss = 0.4595 ::: train hss = 0.2625 : val hss = 0.4169
Fold 3: train tss = 0.4431 : val tss = -0.0045 ::: train hss = 0.4191 : val hss = -0.0068
Fold 4: train tss = 0.3324 : val tss = 0.5783 ::: train hss = 0.3695 : val hss = 0.4722
mean cv TSS: 0.2558
mean cv HSS: 0.2173
26/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6320 : val tss = 0.3263 ::: train hss = 0.7236 : val hss = 0.1987
Fold 2: train tss = 0.5372 : val tss = 0.6254 ::: train hss = 0.4726 : val hss = 0.5273
Fold 3: train tss = 0.7055 : val tss = 0.0240 ::: train hss = 0.5199 : val hss = 0.0249
Fold 4: train tss = 0.6548 : val tss = 0.5199 ::: train hss = 0.4558 : val hss = 0.4904
mean cv TSS: 0.2991
mean cv HSS: 0.2483
27/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5762 : val tss = 0.3519 ::: train hss = 0.6399 : val hss = 0.2233
Fold 2: train tss = 0.5153 : val tss = 0.6374 ::: train hss = 0.4322 : val hss = 0.5019
Fold 3: train tss = 0.5841 : val tss = -0.0043 ::: train hss = 0.5100 : val hss = -0.0065
Fold 4: train tss = 0.5279 : val tss = 0.4471 ::: train hss = 0.4636 : val hss = 0.4227
mean cv TSS: 0.2864
mean cv HSS: 0.2283
28/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6846 : val tss = 0.3500 ::: train hss = 0.7103 : val hss = 0.1701
Fold 2: train tss = 0.5515 : val tss = 0.5986 ::: train hss = 0.4918 : val hss = 0.4686
Fold 3: train tss = 0.6531 : val tss = 0.0463 ::: train hss = 0.5332 : val hss = 0.0401
Fold 4: train tss = 0.6156 : val tss = 0.4438 ::: train hss = 0.4892 : val hss = 0.4446
mean cv TSS: 0.2877
mean cv HSS: 0.2247
29/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6037 : val tss = 0.3508 ::: train hss = 0.6687 : val hss = 0.2271
Fold 2: train tss = 0.4323 : val tss = 0.5775 ::: train hss = 0.4386 : val hss = 0.4654
Fold 3: train tss = 0.5890 : val tss = -0.0047 ::: train hss = 0.5280 : val hss = -0.0070
Fold 4: train tss = 0.5313 : val tss = 0.5130 ::: train hss = 0.4309 : val hss = 0.4102
mean cv TSS: 0.2873
mean cv HSS: 0.2191
30/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5558 : val tss = 0.2126 ::: train hss = 0.5687 : val hss = 0.1934
Fold 2: train tss = 0.4487 : val tss = 0.6196 ::: train hss = 0.3902 : val hss = 0.4297
Fold 3: train tss = 0.5752 : val tss = 0.0331 ::: train hss = 0.4335 : val hss = 0.0344
Fold 4: train tss = 0.5337 : val tss = 0.4030 ::: train hss = 0.4471 : val hss = 0.3789
mean cv TSS: 0.2537
mean cv HSS: 0.2073
31/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.1608 : val tss = -0.0015 ::: train hss = 0.2299 : val hss = -0.0026

Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: -0.0003
mean cv HSS: -0.0005
32/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6876 : val tss = 0.3394 ::: train hss = 0.6724 : val hss = 0.2383
Fold 2: train tss = 0.5360 : val tss = 0.6317 ::: train hss = 0.4267 : val hss = 0.4442
Fold 3: train tss = 0.7196 : val tss = 0.0325 ::: train hss = 0.5025 : val hss = 0.0501
Fold 4: train tss = 0.5620 : val tss = 0.4906 ::: train hss = 0.4701 : val hss = 0.3818
mean cv TSS: 0.2988
mean cv HSS: 0.2229
33/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4234 : val tss = 0.2722 ::: train hss = 0.5393 : val hss = 0.2149
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.3238 : val tss = -0.0024 ::: train hss = 0.3729 : val hss = -0.0041
Fold 4: train tss = 0.1688 : val tss = 0.6268 ::: train hss = 0.2373 : val hss = 0.4544
mean cv TSS: 0.1793
mean cv HSS: 0.1330
34/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6629 : val tss = 0.3593 ::: train hss = 0.6091 : val hss = 0.2226
Fold 2: train tss = 0.4982 : val tss = 0.6610 ::: train hss = 0.4061 : val hss = 0.4100
Fold 3: train tss = 0.6998 : val tss = -0.0027 ::: train hss = 0.5696 : val hss = -0.0045
Fold 4: train tss = 0.6383 : val tss = 0.3227 ::: train hss = 0.5192 : val hss = 0.3557
mean cv TSS: 0.2681
mean cv HSS: 0.1968
35/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5495 : val tss = 0.2709 ::: train hss = 0.6325 : val hss = 0.2272
Fold 2: train tss = 0.2416 : val tss = 0.4010 ::: train hss = 0.2750 : val hss = 0.3941
Fold 3: train tss = 0.5216 : val tss = -0.0051 ::: train hss = 0.4834 : val hss = -0.0074
Fold 4: train tss = 0.3734 : val tss = 0.5472 ::: train hss = 0.3981 : val hss = 0.4426
mean cv TSS: 0.2428
mean cv HSS: 0.2113
36/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0500 : val tss = 0.0427 ::: train hss = 0.0952 : val hss = 0.0756
Fold 1: train tss = 0.6596 : val tss = 0.2614 ::: train hss = 0.5460 : val hss = 0.2400
Fold 2: train tss = 0.2612 : val tss = 0.6259 ::: train hss = 0.2694 : val hss = 0.4224
Fold 3: train tss = 0.5686 : val tss = 0.0142 ::: train hss = 0.4368 : val hss = 0.0220
Fold 4: train tss = 0.4918 : val tss = 0.2844 ::: train hss = 0.4061 : val hss = 0.3869
mean cv TSS: 0.2457
mean cv HSS: 0.2294
37/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5011 : val tss = 0.2539 ::: train hss = 0.4412 : val hss = 0.1424
Fold 2: train tss = 0.0250 : val tss = 0.3434 ::: train hss = 0.0450 : val hss = 0.3701
Fold 3: train tss = 0.3900 : val tss = 0.0022 ::: train hss = 0.3611 : val hss = 0.0029
Fold 4: train tss = 0.2738 : val tss = 0.6371 ::: train hss = 0.2981 : val hss = 0.4911
mean cv TSS: 0.2473
mean cv HSS: 0.2013
38/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0329 ::: train hss = 0.0000 : val hss = 0.0590
Fold 1: train tss = 0.6732 : val tss = 0.2912 ::: train hss = 0.5530 : val hss = 0.1714
Fold 2: train tss = 0.6054 : val tss = 0.4528 ::: train hss = 0.3794 : val hss = 0.3594
Fold 3: train tss = 0.5664 : val tss = 0.0331 ::: train hss = 0.4926 : val hss = 0.0344
Fold 4: train tss = 0.6299 : val tss = 0.5935 ::: train hss = 0.4082 : val hss = 0.5230
mean cv TSS: 0.2807
mean cv HSS: 0.2294
39/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6381 : val tss = 0.2983 ::: train hss = 0.5508 : val hss = 0.1551
Fold 2: train tss = 0.3337 : val tss = 0.5229 ::: train hss = 0.3640 : val hss = 0.4484
Fold 3: train tss = 0.5102 : val tss = -0.0011 ::: train hss = 0.4288 : val hss = -0.0020
Fold 4: train tss = 0.3780 : val tss = 0.7004 ::: train hss = 0.3734 : val hss = 0.4294
mean cv TSS: 0.3041
mean cv HSS: 0.2062
40/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.1577 ::: train hss = 0.0000 : val hss = 0.2208
Fold 1: train tss = 0.7226 : val tss = 0.3912 ::: train hss = 0.6668 : val hss = 0.2946
Fold 2: train tss = 0.3736 : val tss = 0.4302 ::: train hss = 0.4386 : val hss = 0.4496
Fold 3: train tss = 0.6591 : val tss = 0.0151 ::: train hss = 0.5354 : val hss = 0.0158
Fold 4: train tss = 0.6345 : val tss = 0.4856 ::: train hss = 0.4205 : val hss = 0.5066
mean cv TSS: 0.2959
mean cv HSS: 0.2975
41/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6298 : val tss = 0.3672 ::: train hss = 0.6612 : val hss = 0.2229
Fold 2: train tss = 0.3183 : val tss = 0.5128 ::: train hss = 0.3322 : val hss = 0.4413
Fold 3: train tss = 0.6141 : val tss = -0.0043 ::: train hss = 0.4467 : val hss = -0.0065
Fold 4: train tss = 0.4237 : val tss = 0.4726 ::: train hss = 0.4010 : val hss = 0.4151
mean cv TSS: 0.2696
mean cv HSS: 0.2146
42/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5480 : val tss = 0.2481 ::: train hss = 0.4994 : val hss = 0.1959
Fold 2: train tss = 0.0958 : val tss = 0.4672 ::: train hss = 0.1174 : val hss = 0.3677
Fold 3: train tss = 0.5639 : val tss = 0.0370 ::: train hss = 0.4282 : val hss = 0.0320
Fold 4: train tss = 0.3908 : val tss = 0.5485 ::: train hss = 0.3052 : val hss = 0.3878
mean cv TSS: 0.2602
mean cv HSS: 0.1967
43/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0005 : val tss = -0.0010 ::: train hss = 0.0009 : val hss = -0.0018
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: -0.0002
mean cv HSS: -0.0004
44/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6813 : val tss = 0.3111 ::: train hss = 0.5426 : val hss = 0.2102
Fold 2: train tss = 0.5371 : val tss = 0.6495 ::: train hss = 0.4721 : val hss = 0.4494
Fold 3: train tss = 0.6857 : val tss = 0.0150 ::: train hss = 0.4885 : val hss = 0.0156
Fold 4: train tss = 0.5892 : val tss = 0.6284 ::: train hss = 0.4699 : val hss = 0.4590
mean cv TSS: 0.3208
mean cv HSS: 0.2269
45/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4584 : val tss = 0.2552 ::: train hss = 0.5403 : val hss = 0.1613
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2881 : val tss = 0.0162 ::: train hss = 0.3230 : val hss = 0.0281
Fold 4: train tss = 0.1964 : val tss = 0.5062 ::: train hss = 0.2664 : val hss = 0.4341
mean cv TSS: 0.1555
mean cv HSS: 0.1247
46/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7147 : val tss = 0.3414 ::: train hss = 0.5187 : val hss = 0.2446
Fold 2: train tss = 0.4932 : val tss = 0.6712 ::: train hss = 0.3675 : val hss = 0.4183
Fold 3: train tss = 0.5099 : val tss = 0.0201 ::: train hss = 0.5329 : val hss = 0.0261
Fold 4: train tss = 0.6403 : val tss = 0.4528 ::: train hss = 0.4165 : val hss = 0.4050
mean cv TSS: 0.2971
mean cv HSS: 0.2188
47/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.2833 : val tss = 0.1828 ::: train hss = 0.4001 : val hss = 0.2136
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5318 : val tss = -0.0061 ::: train hss = 0.3927 : val hss = -0.0084
Fold 4: train tss = 0.2537 : val tss = 0.2291 ::: train hss = 0.2892 : val hss = 0.3184
mean cv TSS: 0.0812
mean cv HSS: 0.1047
48/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0500 : val tss = 0.0131 ::: train hss = 0.0952 : val hss = 0.0240
Fold 1: train tss = 0.5418 : val tss = 0.3006 ::: train hss = 0.6652 : val hss = 0.1758
Fold 2: train tss = 0.4980 : val tss = 0.6805 ::: train hss = 0.4549 : val hss = 0.4915
Fold 3: train tss = 0.6252 : val tss = -0.0026 ::: train hss = 0.4826 : val hss = -0.0043
Fold 4: train tss = 0.5317 : val tss = 0.5411 ::: train hss = 0.4701 : val hss = 0.4472
mean cv TSS: 0.3065
mean cv HSS: 0.2268
49/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5706 : val tss = 0.2599 ::: train hss = 0.6092 : val hss = 0.1660
Fold 2: train tss = 0.2768 : val tss = 0.4614 ::: train hss = 0.2855 : val hss = 0.4145
Fold 3: train tss = 0.4339 : val tss = -0.0011 ::: train hss = 0.4106 : val hss = -0.0020
Fold 4: train tss = 0.3386 : val tss = 0.6402 ::: train hss = 0.3520 : val hss = 0.4734
mean cv TSS: 0.2721
mean cv HSS: 0.2104
50/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0326 ::: train hss = 0.0000 : val hss = 0.0580
Fold 1: train tss = 0.6946 : val tss = 0.3980 ::: train hss = 0.7470 : val hss = 0.2802
Fold 2: train tss = 0.5841 : val tss = 0.6641 ::: train hss = 0.5589 : val hss = 0.5132
Fold 3: train tss = 0.7411 : val tss = 0.0381 ::: train hss = 0.4488 : val hss = 0.0489
Fold 4: train tss = 0.6766 : val tss = 0.5423 ::: train hss = 0.4858 : val hss = 0.5111
mean cv TSS: 0.3350
mean cv HSS: 0.2823
51/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6126 : val tss = 0.3142 ::: train hss = 0.6719 : val hss = 0.1699
Fold 2: train tss = 0.3720 : val tss = 0.5637 ::: train hss = 0.4184 : val hss = 0.4729
Fold 3: train tss = 0.5710 : val tss = 0.0095 ::: train hss = 0.4913 : val hss = 0.0115
Fold 4: train tss = 0.4397 : val tss = 0.7148 ::: train hss = 0.4588 : val hss = 0.4862
mean cv TSS: 0.3204
mean cv HSS: 0.2281
52/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0084 ::: train hss = 0.0000 : val hss = 0.0155
Fold 1: train tss = 0.7083 : val tss = 0.3345 ::: train hss = 0.7580 : val hss = 0.1806
Fold 2: train tss = 0.6379 : val tss = 0.6850 ::: train hss = 0.5313 : val hss = 0.5014
Fold 3: train tss = 0.7282 : val tss = -0.0096 ::: train hss = 0.4923 : val hss = -0.0112

Fold 4: train tss = 0.6644 : val tss = 0.5155 ::: train hss = 0.5488 : val hss = 0.5027
mean cv TSS: 0.3068
mean cv HSS: 0.2378
53/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6132 : val tss = 0.3459 ::: train hss = 0.6896 : val hss = 0.2089
Fold 2: train tss = 0.3640 : val tss = 0.5270 ::: train hss = 0.3692 : val hss = 0.4578
Fold 3: train tss = 0.5905 : val tss = 0.0185 ::: train hss = 0.5208 : val hss = 0.0223
Fold 4: train tss = 0.5016 : val tss = 0.5290 ::: train hss = 0.4771 : val hss = 0.4298
mean cv TSS: 0.2841
mean cv HSS: 0.2238
54/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = -0.0006 ::: train hss = 0.0000 : val hss = -0.0012
Fold 1: train tss = 0.5955 : val tss = 0.2940 ::: train hss = 0.5760 : val hss = 0.2537
Fold 2: train tss = 0.3930 : val tss = 0.5977 ::: train hss = 0.3625 : val hss = 0.4138
Fold 3: train tss = 0.5714 : val tss = 0.0056 ::: train hss = 0.4389 : val hss = 0.0089
Fold 4: train tss = 0.5105 : val tss = 0.4595 ::: train hss = 0.4434 : val hss = 0.4222
mean cv TSS: 0.2712
mean cv HSS: 0.2195
55/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0492 : val tss = 0.0708 ::: train hss = 0.0898 : val hss = 0.1162
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2405 : val tss = 0.0048 ::: train hss = 0.3014 : val hss = 0.0072
Fold 4: train tss = 0.0563 : val tss = 0.5154 ::: train hss = 0.0980 : val hss = 0.4319
mean cv TSS: 0.1182
mean cv HSS: 0.1111
56/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7153 : val tss = 0.2715 ::: train hss = 0.7041 : val hss = 0.1861
Fold 2: train tss = 0.6009 : val tss = 0.5645 ::: train hss = 0.5207 : val hss = 0.4537
Fold 3: train tss = 0.7338 : val tss = 0.0018 ::: train hss = 0.4753 : val hss = 0.0024
Fold 4: train tss = 0.6052 : val tss = 0.6260 ::: train hss = 0.5296 : val hss = 0.4606
mean cv TSS: 0.2928
mean cv HSS: 0.2205
57/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5271 : val tss = 0.2895 ::: train hss = 0.6196 : val hss = 0.2001
Fold 2: train tss = 0.3028 : val tss = 0.4499 ::: train hss = 0.3503 : val hss = 0.4110
Fold 3: train tss = 0.1568 : val tss = -0.0016 ::: train hss = 0.2407 : val hss = -0.0028
Fold 4: train tss = 0.3802 : val tss = 0.5986 ::: train hss = 0.3782 : val hss = 0.4378
mean cv TSS: 0.2673
mean cv HSS: 0.2092
58/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0148 ::: train hss = 0.0000 : val hss = 0.0290
Fold 1: train tss = 0.5017 : val tss = 0.4213 ::: train hss = 0.6503 : val hss = 0.2036
Fold 2: train tss = 0.4681 : val tss = 0.5889 ::: train hss = 0.5328 : val hss = 0.4551
Fold 3: train tss = 0.7080 : val tss = 0.0460 ::: train hss = 0.5643 : val hss = 0.0396
Fold 4: train tss = 0.5123 : val tss = 0.5754 ::: train hss = 0.4925 : val hss = 0.3947
mean cv TSS: 0.3293
mean cv HSS: 0.2244
59/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5676 : val tss = 0.2402 ::: train hss = 0.6466 : val hss = 0.2021
Fold 2: train tss = 0.2713 : val tss = 0.4429 ::: train hss = 0.2965 : val hss = 0.4052
Fold 3: train tss = 0.5911 : val tss = -0.0027 ::: train hss = 0.4964 : val hss = -0.0045
Fold 4: train tss = 0.4276 : val tss = 0.5009 ::: train hss = 0.3745 : val hss = 0.4400
mean cv TSS: 0.2363
mean cv HSS: 0.2086
60/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0127 ::: train hss = 0.0000 : val hss = 0.0230
Fold 1: train tss = 0.0353 : val tss = 0.1487 ::: train hss = 0.0639 : val hss = 0.1375
Fold 2: train tss = 0.3557 : val tss = 0.6936 ::: train hss = 0.3410 : val hss = 0.4748
Fold 3: train tss = 0.5693 : val tss = -0.0011 ::: train hss = 0.4546 : val hss = -0.0020
Fold 4: train tss = 0.4731 : val tss = 0.5083 ::: train hss = 0.3977 : val hss = 0.4842
mean cv TSS: 0.2725
mean cv HSS: 0.2235
61/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.1574 : val tss = 0.2552 ::: train hss = 0.2558 : val hss = 0.1444
Fold 2: train tss = 0.0915 : val tss = 0.4724 ::: train hss = 0.1247 : val hss = 0.4167
Fold 3: train tss = 0.3735 : val tss = -0.0060 ::: train hss = 0.3460 : val hss = -0.0083
Fold 4: train tss = 0.2692 : val tss = 0.5771 ::: train hss = 0.2867 : val hss = 0.4683
mean cv TSS: 0.2598
mean cv HSS: 0.2042
62/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0499 : val tss = 0.0901 ::: train hss = 0.0907 : val hss = 0.1415
Fold 1: train tss = 0.6542 : val tss = 0.2833 ::: train hss = 0.6113 : val hss = 0.1426
Fold 2: train tss = 0.5420 : val tss = 0.6771 ::: train hss = 0.4666 : val hss = 0.4897
Fold 3: train tss = 0.5530 : val tss = 0.0329 ::: train hss = 0.5128 : val hss = 0.0518
Fold 4: train tss = 0.4099 : val tss = 0.6381 ::: train hss = 0.4173 : val hss = 0.4462
mean cv TSS: 0.3443
mean cv HSS: 0.2543
63/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6636 : val tss = 0.3798 ::: train hss = 0.5392 : val hss = 0.1557
Fold 2: train tss = 0.3112 : val tss = 0.5330 ::: train hss = 0.3474 : val hss = 0.4465
Fold 3: train tss = 0.3239 : val tss = 0.0295 ::: train hss = 0.3677 : val hss = 0.0387
Fold 4: train tss = 0.1117 : val tss = 0.7036 ::: train hss = 0.1831 : val hss = 0.5143
mean cv TSS: 0.3292
mean cv HSS: 0.2311
64/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0500 : val tss = 0.0145 ::: train hss = 0.0952 : val hss = 0.0234
Fold 1: train tss = 0.6238 : val tss = 0.3519 ::: train hss = 0.6196 : val hss = 0.1295
Fold 2: train tss = 0.2559 : val tss = 0.3091 ::: train hss = 0.3131 : val hss = 0.3692
Fold 3: train tss = 0.6835 : val tss = 0.0094 ::: train hss = 0.5586 : val hss = 0.0113
Fold 4: train tss = 0.5675 : val tss = 0.6214 ::: train hss = 0.5135 : val hss = 0.4739
mean cv TSS: 0.2613
mean cv HSS: 0.2015
65/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6238 : val tss = 0.3071 ::: train hss = 0.6210 : val hss = 0.1509
Fold 2: train tss = 0.3351 : val tss = 0.4898 ::: train hss = 0.3433 : val hss = 0.4536
Fold 3: train tss = 0.5878 : val tss = -0.0022 ::: train hss = 0.5020 : val hss = -0.0038
Fold 4: train tss = 0.4456 : val tss = 0.6316 ::: train hss = 0.4124 : val hss = 0.4697
mean cv TSS: 0.2853
mean cv HSS: 0.2141
66/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5045 : val tss = 0.2364 ::: train hss = 0.3742 : val hss = 0.1981
Fold 2: train tss = 0.2635 : val tss = 0.5486 ::: train hss = 0.2506 : val hss = 0.4110
Fold 3: train tss = 0.5463 : val tss = 0.0093 ::: train hss = 0.3874 : val hss = 0.0111
Fold 4: train tss = 0.4416 : val tss = 0.4894 ::: train hss = 0.3481 : val hss = 0.4340
mean cv TSS: 0.2567
mean cv HSS: 0.2108
67/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0121 : val tss = -0.0028 ::: train hss = 0.0231 : val hss = -0.0046
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: -0.0006
mean cv HSS: -0.0009
68/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7222 : val tss = 0.3229 ::: train hss = 0.6582 : val hss = 0.1912
Fold 2: train tss = 0.5782 : val tss = 0.6385 ::: train hss = 0.4889 : val hss = 0.4793
Fold 3: train tss = 0.5021 : val tss = 0.0856 ::: train hss = 0.4644 : val hss = 0.0816
Fold 4: train tss = 0.5555 : val tss = 0.4051 ::: train hss = 0.4823 : val hss = 0.3479
mean cv TSS: 0.2904
mean cv HSS: 0.2200
69/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5306 : val tss = 0.3148 ::: train hss = 0.5952 : val hss = 0.2201
Fold 2: train tss = 0.1722 : val tss = 0.3089 ::: train hss = 0.2389 : val hss = 0.3493
Fold 3: train tss = 0.3957 : val tss = 0.0197 ::: train hss = 0.3811 : val hss = 0.0176
Fold 4: train tss = 0.2473 : val tss = 0.6509 ::: train hss = 0.3067 : val hss = 0.4388
mean cv TSS: 0.2589
mean cv HSS: 0.2051
70/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6158 : val tss = 0.3144 ::: train hss = 0.6405 : val hss = 0.2422
Fold 2: train tss = 0.4412 : val tss = 0.5698 ::: train hss = 0.4387 : val hss = 0.4580
Fold 3: train tss = 0.7264 : val tss = 0.0093 ::: train hss = 0.5003 : val hss = 0.0111
Fold 4: train tss = 0.5606 : val tss = 0.6721 ::: train hss = 0.3869 : val hss = 0.4534
mean cv TSS: 0.3131
mean cv HSS: 0.2329
71/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5135 : val tss = 0.3098 ::: train hss = 0.6085 : val hss = 0.2070
Fold 2: train tss = 0.1826 : val tss = 0.2682 ::: train hss = 0.2433 : val hss = 0.3395
Fold 3: train tss = 0.4209 : val tss = -0.0026 ::: train hss = 0.4025 : val hss = -0.0043
Fold 4: train tss = 0.3888 : val tss = 0.1023 ::: train hss = 0.4111 : val hss = 0.1188
mean cv TSS: 0.1355
mean cv HSS: 0.1322
72/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0050 ::: train hss = 0.0000 : val hss = 0.0099
Fold 1: train tss = 0.5106 : val tss = 0.3584 ::: train hss = 0.5361 : val hss = 0.2562
Fold 2: train tss = 0.4007 : val tss = 0.4689 ::: train hss = 0.3848 : val hss = 0.4136
Fold 3: train tss = 0.5083 : val tss = 0.0416 ::: train hss = 0.4267 : val hss = 0.0422
Fold 4: train tss = 0.4381 : val tss = 0.5234 ::: train hss = 0.3907 : val hss = 0.4495
mean cv TSS: 0.2795
mean cv HSS: 0.2343
73/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3412 : val tss = 0.2312 ::: train hss = 0.4409 : val hss = 0.2234
Fold 2: train tss = 0.1863 : val tss = 0.0749 ::: train hss = 0.2326 : val hss = 0.1313
Fold 3: train tss = 0.3386 : val tss = -0.0028 ::: train hss = 0.3577 : val hss = -0.0046

Fold 4: train tss = 0.2493 : val tss = 0.4332 ::: train hss = 0.3066 : val hss = 0.4076
mean cv TSS: 0.1473
mean cv HSS: 0.1515
74/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5317 : val tss = 0.1677 ::: train hss = 0.6268 : val hss = 0.0915
Fold 2: train tss = 0.4338 : val tss = 0.5299 ::: train hss = 0.4565 : val hss = 0.5092
Fold 3: train tss = 0.6083 : val tss = 0.0320 ::: train hss = 0.4931 : val hss = 0.0319
Fold 4: train tss = 0.5211 : val tss = 0.5284 ::: train hss = 0.4570 : val hss = 0.4521
mean cv TSS: 0.2516
mean cv HSS: 0.2169
75/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.3293 ::: train hss = 0.0000 : val hss = 0.3871
Fold 1: train tss = 0.5423 : val tss = 0.4008 ::: train hss = 0.5614 : val hss = 0.1896
Fold 2: train tss = 0.2538 : val tss = 0.4626 ::: train hss = 0.3087 : val hss = 0.4321
Fold 3: train tss = 0.3477 : val tss = -0.0026 ::: train hss = 0.3882 : val hss = -0.0043
Fold 4: train tss = 0.3364 : val tss = 0.5386 ::: train hss = 0.3619 : val hss = 0.4436
mean cv TSS: 0.3457
mean cv HSS: 0.2896
76/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = -0.0406 : val tss = 0.3911 ::: train hss = -0.0045 : val hss = 0.3411
Fold 1: train tss = 0.5848 : val tss = 0.3494 ::: train hss = 0.6335 : val hss = 0.2000
Fold 2: train tss = 0.4230 : val tss = 0.5279 ::: train hss = 0.3657 : val hss = 0.4517
Fold 3: train tss = 0.6463 : val tss = 0.0450 ::: train hss = 0.5258 : val hss = 0.0293
Fold 4: train tss = 0.4286 : val tss = 0.4997 ::: train hss = 0.4271 : val hss = 0.4170
mean cv TSS: 0.3626
mean cv HSS: 0.2878
77/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4773 : val tss = 0.3189 ::: train hss = 0.5780 : val hss = 0.2399
Fold 2: train tss = 0.3801 : val tss = 0.4773 ::: train hss = 0.4099 : val hss = 0.4777
Fold 3: train tss = 0.5936 : val tss = 0.0185 ::: train hss = 0.4811 : val hss = 0.0223
Fold 4: train tss = 0.4158 : val tss = 0.6571 ::: train hss = 0.3964 : val hss = 0.4861
mean cv TSS: 0.2944
mean cv HSS: 0.2452
78/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4248 : val tss = 0.1888 ::: train hss = 0.4706 : val hss = 0.1878
Fold 2: train tss = 0.3680 : val tss = 0.5156 ::: train hss = 0.3428 : val hss = 0.4095
Fold 3: train tss = 0.4754 : val tss = 0.0259 ::: train hss = 0.4341 : val hss = 0.0291
Fold 4: train tss = 0.3487 : val tss = 0.2615 ::: train hss = 0.3304 : val hss = 0.3069
mean cv TSS: 0.1984
mean cv HSS: 0.1867
79/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
80/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4425 : val tss = 0.2134 ::: train hss = 0.5856 : val hss = 0.1204
Fold 2: train tss = 0.3717 : val tss = 0.5126 ::: train hss = 0.3952 : val hss = 0.4198
Fold 3: train tss = 0.5858 : val tss = 0.0225 ::: train hss = 0.4880 : val hss = 0.0166
Fold 4: train tss = 0.5402 : val tss = 0.5183 ::: train hss = 0.4410 : val hss = 0.4419
mean cv TSS: 0.2534
mean cv HSS: 0.1997
81/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.1151 : val tss = 0.0045 ::: train hss = 0.1800 : val hss = 0.0088
Fold 3: train tss = 0.4565 : val tss = 0.0244 ::: train hss = 0.3781 : val hss = 0.0256
Fold 4: train tss = 0.1605 : val tss = 0.0000 ::: train hss = 0.2345 : val hss = 0.0000
mean cv TSS: 0.0058
mean cv HSS: 0.0069
82/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6100 : val tss = 0.3320 ::: train hss = 0.6059 : val hss = 0.2120
Fold 2: train tss = 0.3293 : val tss = 0.5041 ::: train hss = 0.3380 : val hss = 0.4434
Fold 3: train tss = 0.6537 : val tss = 0.0325 ::: train hss = 0.5098 : val hss = 0.0501
Fold 4: train tss = 0.4366 : val tss = 0.4355 ::: train hss = 0.3998 : val hss = 0.4514
mean cv TSS: 0.2608
mean cv HSS: 0.2314
83/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.3532 : val tss = -0.0023 ::: train hss = 0.3886 : val hss = -0.0040
Fold 4: train tss = 0.1768 : val tss = 0.0000 ::: train hss = 0.2419 : val hss = 0.0000
mean cv TSS: -0.0005
mean cv HSS: -0.0008
84/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 189
Fold 0: train tss = 0.0500 : val tss = 0.0889 ::: train hss = 0.0952 : val hss = 0.1343
Fold 1: train tss = 0.4362 : val tss = 0.1921 ::: train hss = 0.5326 : val hss = 0.1750
Fold 2: train tss = 0.2267 : val tss = 0.5327 ::: train hss = 0.2381 : val hss = 0.4138
Fold 3: train tss = 0.3909 : val tss = 0.0189 ::: train hss = 0.3488 : val hss = 0.0232
Fold 4: train tss = 0.3483 : val tss = 0.3508 ::: train hss = 0.3238 : val hss = 0.3655
mean cv TSS: 0.2367
mean cv HSS: 0.2223
85/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.2647 : val tss = 0.0000 ::: train hss = 0.3691 : val hss = 0.0000
Fold 2: train tss = 0.0694 : val tss = 0.0000 ::: train hss = 0.1135 : val hss = 0.0000
Fold 3: train tss = 0.2688 : val tss = 0.0049 ::: train hss = 0.2807 : val hss = 0.0074
Fold 4: train tss = 0.1965 : val tss = 0.5794 ::: train hss = 0.2401 : val hss = 0.4969
mean cv TSS: 0.1169
mean cv HSS: 0.1009
86/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5575 : val tss = 0.3879 ::: train hss = 0.5145 : val hss = 0.2495
Fold 2: train tss = 0.4622 : val tss = 0.6137 ::: train hss = 0.4352 : val hss = 0.4956
Fold 3: train tss = 0.5376 : val tss = 0.0275 ::: train hss = 0.4364 : val hss = 0.0330
Fold 4: train tss = 0.3217 : val tss = 0.4433 ::: train hss = 0.3812 : val hss = 0.4345
mean cv TSS: 0.2945
mean cv HSS: 0.2425
87/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4140 : val tss = 0.3431 ::: train hss = 0.5229 : val hss = 0.1971
Fold 2: train tss = 0.2993 : val tss = 0.3014 ::: train hss = 0.2768 : val hss = 0.3737
Fold 3: train tss = 0.4136 : val tss = -0.0073 ::: train hss = 0.3439 : val hss = -0.0095
Fold 4: train tss = 0.3216 : val tss = 0.6552 ::: train hss = 0.3104 : val hss = 0.5034
mean cv TSS: 0.2585
mean cv HSS: 0.2130
88/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5242 : val tss = 0.2950 ::: train hss = 0.5464 : val hss = 0.1741
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6107 : val tss = -0.0015 ::: train hss = 0.4984 : val hss = -0.0008
Fold 4: train tss = 0.4468 : val tss = 0.5138 ::: train hss = 0.4106 : val hss = 0.3704
mean cv TSS: 0.1615
mean cv HSS: 0.1088
89/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3696 : val tss = 0.2923 ::: train hss = 0.5012 : val hss = 0.2295
Fold 2: train tss = 0.2005 : val tss = 0.3485 ::: train hss = 0.2868 : val hss = 0.4106
Fold 3: train tss = 0.3951 : val tss = -0.0010 ::: train hss = 0.3823 : val hss = -0.0018
Fold 4: train tss = 0.3041 : val tss = 0.6791 ::: train hss = 0.3238 : val hss = 0.4959
mean cv TSS: 0.2638
mean cv HSS: 0.2268
90/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3923 : val tss = 0.1959 ::: train hss = 0.4271 : val hss = 0.1956
Fold 2: train tss = 0.2746 : val tss = 0.4708 ::: train hss = 0.2819 : val hss = 0.4288
Fold 3: train tss = 0.3777 : val tss = 0.0216 ::: train hss = 0.3359 : val hss = 0.0301
Fold 4: train tss = 0.3396 : val tss = 0.4027 ::: train hss = 0.3262 : val hss = 0.3917
mean cv TSS: 0.2182
mean cv HSS: 0.2092
91/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
92/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5773 : val tss = 0.3140 ::: train hss = 0.4815 : val hss = 0.2112
Fold 2: train tss = 0.4126 : val tss = 0.5058 ::: train hss = 0.3520 : val hss = 0.4112
Fold 3: train tss = 0.4009 : val tss = 0.0682 ::: train hss = 0.3997 : val hss = 0.0670
Fold 4: train tss = 0.3457 : val tss = 0.5102 ::: train hss = 0.3779 : val hss = 0.3627
mean cv TSS: 0.2796
mean cv HSS: 0.2104
93/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2425 : val tss = -0.0010 ::: train hss = 0.2905 : val hss = -0.0018
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: -0.0002
mean cv HSS: -0.0004
94/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5355 : val tss = 0.3992 ::: train hss = 0.5101 : val hss = 0.2200
Fold 2: train tss = 0.3714 : val tss = 0.4423 ::: train hss = 0.2827 : val hss = 0.4401
Fold 3: train tss = 0.6324 : val tss = -0.0034 ::: train hss = 0.4975 : val hss = -0.0054

Fold 4: train tss = 0.3411 : val tss = 0.6182 ::: train hss = 0.3705 : val hss = 0.4423
mean cv TSS: 0.2913
mean cv HSS: 0.2194
95/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.3042 : val tss = 0.0000 ::: train hss = 0.3712 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
96/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0500 : val tss = 0.0561 ::: train hss = 0.0952 : val hss = 0.0932
Fold 1: train tss = 0.5951 : val tss = 0.3175 ::: train hss = 0.6762 : val hss = 0.2437
Fold 2: train tss = 0.4404 : val tss = 0.6142 ::: train hss = 0.3792 : val hss = 0.4973
Fold 3: train tss = 0.5693 : val tss = 0.0308 ::: train hss = 0.4645 : val hss = 0.0294
Fold 4: train tss = 0.4853 : val tss = 0.5221 ::: train hss = 0.4359 : val hss = 0.4501
mean cv TSS: 0.3082
mean cv HSS: 0.2628
97/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5400 : val tss = 0.2648 ::: train hss = 0.6120 : val hss = 0.2080
Fold 2: train tss = 0.2389 : val tss = 0.4373 ::: train hss = 0.2808 : val hss = 0.4169
Fold 3: train tss = 0.4001 : val tss = 0.0044 ::: train hss = 0.3894 : val hss = 0.0065
Fold 4: train tss = 0.3105 : val tss = 0.5987 ::: train hss = 0.3438 : val hss = 0.4783
mean cv TSS: 0.2610
mean cv HSS: 0.2219
98/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6529 : val tss = 0.3547 ::: train hss = 0.6904 : val hss = 0.1908
Fold 2: train tss = 0.5448 : val tss = 0.6376 ::: train hss = 0.4977 : val hss = 0.5118
Fold 3: train tss = 0.6262 : val tss = 0.0497 ::: train hss = 0.5155 : val hss = 0.0364
Fold 4: train tss = 0.5877 : val tss = 0.4683 ::: train hss = 0.4408 : val hss = 0.4666
mean cv TSS: 0.3020
mean cv HSS: 0.2411
99/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5946 : val tss = 0.3243 ::: train hss = 0.6620 : val hss = 0.1750
Fold 2: train tss = 0.4654 : val tss = 0.5920 ::: train hss = 0.4703 : val hss = 0.4865
Fold 3: train tss = 0.5164 : val tss = 0.0285 ::: train hss = 0.4279 : val hss = 0.0357
Fold 4: train tss = 0.3392 : val tss = 0.6662 ::: train hss = 0.3896 : val hss = 0.4699
mean cv TSS: 0.3222
mean cv HSS: 0.2334
100/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6834 : val tss = 0.3570 ::: train hss = 0.6788 : val hss = 0.3003
Fold 2: train tss = 0.5610 : val tss = 0.6887 ::: train hss = 0.4439 : val hss = 0.4877
Fold 3: train tss = 0.6846 : val tss = 0.0155 ::: train hss = 0.5545 : val hss = 0.0121
Fold 4: train tss = 0.4853 : val tss = 0.4847 ::: train hss = 0.4903 : val hss = 0.4483
mean cv TSS: 0.3092
mean cv HSS: 0.2497
101/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5720 : val tss = 0.3632 ::: train hss = 0.6467 : val hss = 0.2548
Fold 2: train tss = 0.4273 : val tss = 0.5710 ::: train hss = 0.4425 : val hss = 0.5196
Fold 3: train tss = 0.5888 : val tss = -0.0063 ::: train hss = 0.5147 : val hss = -0.0086
Fold 4: train tss = 0.5030 : val tss = 0.5363 ::: train hss = 0.4084 : val hss = 0.4394
mean cv TSS: 0.2928
mean cv HSS: 0.2410
102/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6197 : val tss = 0.2501 ::: train hss = 0.5350 : val hss = 0.2473
Fold 2: train tss = 0.3288 : val tss = 0.6154 ::: train hss = 0.3188 : val hss = 0.3943
Fold 3: train tss = 0.5740 : val tss = 0.0200 ::: train hss = 0.4590 : val hss = 0.0258
Fold 4: train tss = 0.4915 : val tss = 0.3654 ::: train hss = 0.4386 : val hss = 0.3561
mean cv TSS: 0.2502
mean cv HSS: 0.2047
103/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.1218 : val tss = -0.0013 ::: train hss = 0.1828 : val hss = -0.0024
Fold 4: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0001 : val hss = 0.0000
mean cv TSS: -0.0003
mean cv HSS: -0.0005
104/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7411 : val tss = 0.3324 ::: train hss = 0.5934 : val hss = 0.1725
Fold 2: train tss = 0.5229 : val tss = 0.6280 ::: train hss = 0.4936 : val hss = 0.4311
Fold 3: train tss = 0.6761 : val tss = 0.0269 ::: train hss = 0.4172 : val hss = 0.0314
Fold 4: train tss = 0.3810 : val tss = 0.6341 ::: train hss = 0.4190 : val hss = 0.4429
mean cv TSS: 0.3243
mean cv HSS: 0.2156
105/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4540 : val tss = 0.2999 ::: train hss = 0.5409 : val hss = 0.2075
Fold 2: train tss = 0.1320 : val tss = 0.1725 ::: train hss = 0.2016 : val hss = 0.2580
Fold 3: train tss = 0.2788 : val tss = 0.0268 ::: train hss = 0.3418 : val hss = 0.0513
Fold 4: train tss = 0.2597 : val tss = 0.3984 ::: train hss = 0.2965 : val hss = 0.3814
mean cv TSS: 0.1795
mean cv HSS: 0.1796
106/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6851 : val tss = 0.3424 ::: train hss = 0.6155 : val hss = 0.2559
Fold 2: train tss = 0.4536 : val tss = 0.6566 ::: train hss = 0.4580 : val hss = 0.4239
Fold 3: train tss = 0.6572 : val tss = 0.0376 ::: train hss = 0.5332 : val hss = 0.0472
Fold 4: train tss = 0.5968 : val tss = 0.6540 ::: train hss = 0.5096 : val hss = 0.4633
mean cv TSS: 0.3381
mean cv HSS: 0.2380
107/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3962 : val tss = 0.2214 ::: train hss = 0.5120 : val hss = 0.2255
Fold 2: train tss = 0.0804 : val tss = 0.0000 ::: train hss = 0.1276 : val hss = 0.0000
Fold 3: train tss = 0.6000 : val tss = -0.0065 ::: train hss = 0.4661 : val hss = -0.0087
Fold 4: train tss = 0.3813 : val tss = 0.4013 ::: train hss = 0.3397 : val hss = 0.3798
mean cv TSS: 0.1232
mean cv HSS: 0.1193
108/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = -0.0012 ::: train hss = 0.0000 : val hss = -0.0023
Fold 1: train tss = 0.5270 : val tss = 0.2243 ::: train hss = 0.6179 : val hss = 0.1913
Fold 2: train tss = 0.3307 : val tss = 0.6328 ::: train hss = 0.2939 : val hss = 0.4825
Fold 3: train tss = 0.5139 : val tss = 0.0248 ::: train hss = 0.4137 : val hss = 0.0266
Fold 4: train tss = 0.4386 : val tss = 0.5035 ::: train hss = 0.3627 : val hss = 0.5066
mean cv TSS: 0.2768
mean cv HSS: 0.2409
109/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3916 : val tss = 0.1989 ::: train hss = 0.5061 : val hss = 0.1739
Fold 2: train tss = 0.1015 : val tss = 0.3288 ::: train hss = 0.1485 : val hss = 0.3629
Fold 3: train tss = 0.3458 : val tss = 0.0023 ::: train hss = 0.3408 : val hss = 0.0031
Fold 4: train tss = 0.2584 : val tss = 0.6067 ::: train hss = 0.2841 : val hss = 0.4810
mean cv TSS: 0.2274
mean cv HSS: 0.2042
110/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0952 ::: train hss = 0.0000 : val hss = 0.1495
Fold 1: train tss = 0.6559 : val tss = 0.3597 ::: train hss = 0.6530 : val hss = 0.2889
Fold 2: train tss = 0.3410 : val tss = 0.4327 ::: train hss = 0.4072 : val hss = 0.4239
Fold 3: train tss = 0.6618 : val tss = 0.0032 ::: train hss = 0.4764 : val hss = 0.0044
Fold 4: train tss = 0.4446 : val tss = 0.6178 ::: train hss = 0.4441 : val hss = 0.4706
mean cv TSS: 0.3017
mean cv HSS: 0.2675
111/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5665 : val tss = 0.3464 ::: train hss = 0.6152 : val hss = 0.2518
Fold 2: train tss = 0.3300 : val tss = 0.5371 ::: train hss = 0.3618 : val hss = 0.4346
Fold 3: train tss = 0.4932 : val tss = -0.0013 ::: train hss = 0.4169 : val hss = -0.0024
Fold 4: train tss = 0.4198 : val tss = 0.6476 ::: train hss = 0.3886 : val hss = 0.5228
mean cv TSS: 0.3059
mean cv HSS: 0.2413
112/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0957 ::: train hss = 0.0000 : val hss = 0.1526
Fold 1: train tss = 0.6766 : val tss = 0.2593 ::: train hss = 0.6218 : val hss = 0.2320
Fold 2: train tss = 0.4724 : val tss = 0.6770 ::: train hss = 0.4488 : val hss = 0.4775
Fold 3: train tss = 0.5563 : val tss = 0.0080 ::: train hss = 0.4901 : val hss = 0.0149
Fold 4: train tss = 0.4983 : val tss = 0.6124 ::: train hss = 0.4353 : val hss = 0.4590
mean cv TSS: 0.3305
mean cv HSS: 0.2672
113/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6100 : val tss = 0.2691 ::: train hss = 0.6059 : val hss = 0.2299
Fold 2: train tss = 0.3236 : val tss = 0.4438 ::: train hss = 0.3339 : val hss = 0.4309
Fold 3: train tss = 0.5124 : val tss = -0.0011 ::: train hss = 0.4810 : val hss = -0.0020
Fold 4: train tss = 0.4037 : val tss = 0.6629 ::: train hss = 0.4031 : val hss = 0.4641
mean cv TSS: 0.2749
mean cv HSS: 0.2246
114/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5061 : val tss = 0.3028 ::: train hss = 0.5326 : val hss = 0.1960
Fold 2: train tss = 0.0525 : val tss = 0.0837 ::: train hss = 0.0815 : val hss = 0.1436
Fold 3: train tss = 0.5427 : val tss = 0.0168 ::: train hss = 0.4081 : val hss = 0.0188
Fold 4: train tss = 0.2455 : val tss = 0.5728 ::: train hss = 0.2395 : val hss = 0.4085
mean cv TSS: 0.1952
mean cv HSS: 0.1534
115/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0109 : val tss = 0.0000 ::: train hss = 0.0212 : val hss = 0.0000

Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
116/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7042 : val tss = 0.2678 ::: train hss = 0.5608 : val hss = 0.2444
Fold 2: train tss = 0.5894 : val tss = 0.6186 ::: train hss = 0.4584 : val hss = 0.4762
Fold 3: train tss = 0.6381 : val tss = 0.0312 ::: train hss = 0.4603 : val hss = 0.0446
Fold 4: train tss = 0.5914 : val tss = 0.5243 ::: train hss = 0.4410 : val hss = 0.4904
mean cv TSS: 0.2884
mean cv HSS: 0.2511
117/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4324 : val tss = 0.2622 ::: train hss = 0.5460 : val hss = 0.2079
Fold 2: train tss = 0.0225 : val tss = 0.0000 ::: train hss = 0.0429 : val hss = 0.0000
Fold 3: train tss = 0.1779 : val tss = -0.0016 ::: train hss = 0.2195 : val hss = -0.0028
Fold 4: train tss = 0.1682 : val tss = 0.3268 ::: train hss = 0.2245 : val hss = 0.3765
mean cv TSS: 0.1175
mean cv HSS: 0.1163
118/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6533 : val tss = 0.3882 ::: train hss = 0.4050 : val hss = 0.1234
Fold 2: train tss = 0.5597 : val tss = 0.6205 ::: train hss = 0.4179 : val hss = 0.4221
Fold 3: train tss = 0.5993 : val tss = 0.0155 ::: train hss = 0.5266 : val hss = 0.0256
Fold 4: train tss = 0.6230 : val tss = 0.4794 ::: train hss = 0.3449 : val hss = 0.4012
mean cv TSS: 0.3007
mean cv HSS: 0.1945
119/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4547 : val tss = 0.2337 ::: train hss = 0.5583 : val hss = 0.2234
Fold 2: train tss = 0.0017 : val tss = 0.0000 ::: train hss = 0.0033 : val hss = 0.0000
Fold 3: train tss = 0.4102 : val tss = 0.0212 ::: train hss = 0.3754 : val hss = 0.0290
Fold 4: train tss = 0.1858 : val tss = 0.5735 ::: train hss = 0.2577 : val hss = 0.4587
mean cv TSS: 0.1657
mean cv HSS: 0.1422
120/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = -0.0001 : val tss = 0.0415 ::: train hss = -0.0002 : val hss = 0.0703
Fold 1: train tss = 0.5827 : val tss = 0.3065 ::: train hss = 0.7018 : val hss = 0.1988
Fold 2: train tss = 0.4640 : val tss = 0.6508 ::: train hss = 0.4008 : val hss = 0.4639
Fold 3: train tss = 0.5536 : val tss = 0.0370 ::: train hss = 0.4717 : val hss = 0.0452
Fold 4: train tss = 0.4824 : val tss = 0.5703 ::: train hss = 0.4312 : val hss = 0.4694
mean cv TSS: 0.3212
mean cv HSS: 0.2495
121/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5614 : val tss = 0.2780 ::: train hss = 0.5964 : val hss = 0.1689
Fold 2: train tss = 0.1602 : val tss = 0.4746 ::: train hss = 0.2202 : val hss = 0.4196
Fold 3: train tss = 0.4268 : val tss = -0.0022 ::: train hss = 0.4100 : val hss = -0.0038
Fold 4: train tss = 0.3338 : val tss = 0.6105 ::: train hss = 0.3484 : val hss = 0.4653
mean cv TSS: 0.2722
mean cv HSS: 0.2100
122/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0418 ::: train hss = 0.0000 : val hss = 0.0719
Fold 1: train tss = 0.6293 : val tss = 0.2532 ::: train hss = 0.6484 : val hss = 0.1450
Fold 2: train tss = 0.5603 : val tss = 0.6131 ::: train hss = 0.5328 : val hss = 0.5028
Fold 3: train tss = 0.7496 : val tss = 0.0317 ::: train hss = 0.4905 : val hss = 0.0465
Fold 4: train tss = 0.5711 : val tss = 0.6207 ::: train hss = 0.5252 : val hss = 0.4488
mean cv TSS: 0.3121
mean cv HSS: 0.2430
123/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6526 : val tss = 0.3773 ::: train hss = 0.5781 : val hss = 0.1268
Fold 2: train tss = 0.3793 : val tss = 0.5407 ::: train hss = 0.4212 : val hss = 0.4872
Fold 3: train tss = 0.5454 : val tss = 0.0261 ::: train hss = 0.4929 : val hss = 0.0294
Fold 4: train tss = 0.4620 : val tss = 0.6107 ::: train hss = 0.4541 : val hss = 0.4661
mean cv TSS: 0.3109
mean cv HSS: 0.2219
124/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0081 ::: train hss = 0.0000 : val hss = 0.0149
Fold 1: train tss = 0.3654 : val tss = 0.3495 ::: train hss = 0.5031 : val hss = 0.2619
Fold 2: train tss = 0.6555 : val tss = 0.7415 ::: train hss = 0.4189 : val hss = 0.4409
Fold 3: train tss = 0.6971 : val tss = 0.0279 ::: train hss = 0.5741 : val hss = 0.0340
Fold 4: train tss = 0.3670 : val tss = 0.5794 ::: train hss = 0.4303 : val hss = 0.4592
mean cv TSS: 0.3413
mean cv HSS: 0.2422
125/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5993 : val tss = 0.3202 ::: train hss = 0.6706 : val hss = 0.2724
Fold 2: train tss = 0.5547 : val tss = 0.5400 ::: train hss = 0.3383 : val hss = 0.4355
Fold 3: train tss = 0.6067 : val tss = 0.0101 ::: train hss = 0.4928 : val hss = 0.0126
Fold 4: train tss = 0.4928 : val tss = 0.6132 ::: train hss = 0.4432 : val hss = 0.4661
mean cv TSS: 0.2967
mean cv HSS: 0.2373
126/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = -0.0010 ::: train hss = 0.0000 : val hss = -0.0019
Fold 1: train tss = 0.5176 : val tss = 0.3036 ::: train hss = 0.5989 : val hss = 0.2410
Fold 2: train tss = 0.4026 : val tss = 0.6084 ::: train hss = 0.3550 : val hss = 0.4244
Fold 3: train tss = 0.5701 : val tss = 0.0296 ::: train hss = 0.4499 : val hss = 0.0391
Fold 4: train tss = 0.5012 : val tss = 0.4203 ::: train hss = 0.4298 : val hss = 0.4266
mean cv TSS: 0.2722
mean cv HSS: 0.2258
127/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0668 : val tss = 0.0740 ::: train hss = 0.1162 : val hss = 0.1208
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2290 : val tss = 0.0050 ::: train hss = 0.2948 : val hss = 0.0076
Fold 4: train tss = 0.0505 : val tss = 0.5025 ::: train hss = 0.0881 : val hss = 0.4309
mean cv TSS: 0.1163
mean cv HSS: 0.1119
128/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6892 : val tss = 0.2584 ::: train hss = 0.7168 : val hss = 0.1968
Fold 2: train tss = 0.5978 : val tss = 0.6199 ::: train hss = 0.5273 : val hss = 0.4847
Fold 3: train tss = 0.7093 : val tss = -0.0023 ::: train hss = 0.5283 : val hss = -0.0039
Fold 4: train tss = 0.5533 : val tss = 0.5612 ::: train hss = 0.4885 : val hss = 0.4309
mean cv TSS: 0.2874
mean cv HSS: 0.2217
129/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5361 : val tss = 0.2790 ::: train hss = 0.6252 : val hss = 0.2125
Fold 2: train tss = 0.3064 : val tss = 0.4473 ::: train hss = 0.3346 : val hss = 0.4025
Fold 3: train tss = 0.3997 : val tss = 0.0239 ::: train hss = 0.3967 : val hss = 0.0246
Fold 4: train tss = 0.4008 : val tss = 0.4506 ::: train hss = 0.4026 : val hss = 0.4011
mean cv TSS: 0.2401
mean cv HSS: 0.2082
130/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0729 ::: train hss = 0.0000 : val hss = 0.1274
Fold 1: train tss = 0.7070 : val tss = 0.3496 ::: train hss = 0.7200 : val hss = 0.2815
Fold 2: train tss = 0.5684 : val tss = 0.6515 ::: train hss = 0.5435 : val hss = 0.4550
Fold 3: train tss = 0.6689 : val tss = 0.0292 ::: train hss = 0.6056 : val hss = 0.0379
Fold 4: train tss = 0.6727 : val tss = 0.4996 ::: train hss = 0.4707 : val hss = 0.4614
mean cv TSS: 0.3206
mean cv HSS: 0.2727
131/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5723 : val tss = 0.2672 ::: train hss = 0.6536 : val hss = 0.1940
Fold 2: train tss = 0.2428 : val tss = 0.4472 ::: train hss = 0.2853 : val hss = 0.4107
Fold 3: train tss = 0.4322 : val tss = -0.0021 ::: train hss = 0.4424 : val hss = -0.0036
Fold 4: train tss = 0.4306 : val tss = 0.4683 ::: train hss = 0.4087 : val hss = 0.4100
mean cv TSS: 0.2361
mean cv HSS: 0.2022
132/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0499 : val tss = 0.0463 ::: train hss = 0.0907 : val hss = 0.0779
Fold 1: train tss = 0.3290 : val tss = 0.2913 ::: train hss = 0.4602 : val hss = 0.1477
Fold 2: train tss = 0.3119 : val tss = 0.6568 ::: train hss = 0.2820 : val hss = 0.4775
Fold 3: train tss = 0.5520 : val tss = 0.0038 ::: train hss = 0.4280 : val hss = 0.0054
Fold 4: train tss = 0.4429 : val tss = 0.2590 ::: train hss = 0.3669 : val hss = 0.3213
mean cv TSS: 0.2514
mean cv HSS: 0.2060
133/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5736 : val tss = 0.3029 ::: train hss = 0.4914 : val hss = 0.1756
Fold 2: train tss = 0.0650 : val tss = 0.3874 ::: train hss = 0.1041 : val hss = 0.3741
Fold 3: train tss = 0.3531 : val tss = -0.0055 ::: train hss = 0.3345 : val hss = -0.0078
Fold 4: train tss = 0.2744 : val tss = 0.5997 ::: train hss = 0.2935 : val hss = 0.4865
mean cv TSS: 0.2569
mean cv HSS: 0.2057
134/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0326 ::: train hss = 0.0000 : val hss = 0.0580
Fold 1: train tss = 0.6186 : val tss = 0.2487 ::: train hss = 0.6009 : val hss = 0.1057
Fold 2: train tss = 0.4542 : val tss = 0.7117 ::: train hss = 0.4449 : val hss = 0.4299
Fold 3: train tss = 0.6959 : val tss = 0.0196 ::: train hss = 0.4659 : val hss = 0.0249
Fold 4: train tss = 0.4346 : val tss = 0.6660 ::: train hss = 0.4113 : val hss = 0.5258
mean cv TSS: 0.3357
mean cv HSS: 0.2289
135/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6278 : val tss = 0.3724 ::: train hss = 0.4075 : val hss = 0.1325
Fold 2: train tss = 0.3620 : val tss = 0.5334 ::: train hss = 0.3222 : val hss = 0.4396
Fold 3: train tss = 0.1043 : val tss = -0.0034 ::: train hss = 0.1737 : val hss = -0.0054
Fold 4: train tss = 0.2070 : val tss = 0.7264 ::: train hss = 0.2792 : val hss = 0.4905
mean cv TSS: 0.3258
mean cv HSS: 0.2114
136/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = -0.0001 : val tss = 0.0351 ::: train hss = -0.0002 : val hss = 0.0572
Fold 1: train tss = 0.6484 : val tss = 0.3454 ::: train hss = 0.6873 : val hss = 0.1970
Fold 2: train tss = 0.3409 : val tss = 0.6473 ::: train hss = 0.3851 : val hss = 0.4986
Fold 3: train tss = 0.5515 : val tss = 0.0046 ::: train hss = 0.5202 : val hss = 0.0069

Fold 4: train tss = 0.5700 : val tss = 0.5985 ::: train hss = 0.4695 : val hss = 0.3600
mean cv TSS: 0.3262
mean cv HSS: 0.2240
137/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5995 : val tss = 0.3216 ::: train hss = 0.6760 : val hss = 0.2321
Fold 2: train tss = 0.2870 : val tss = 0.4404 ::: train hss = 0.3314 : val hss = 0.4054
Fold 3: train tss = 0.4340 : val tss = -0.0016 ::: train hss = 0.4380 : val hss = -0.0028
Fold 4: train tss = 0.4034 : val tss = 0.6395 ::: train hss = 0.4062 : val hss = 0.4954
mean cv TSS: 0.2800
mean cv HSS: 0.2260
138/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5249 : val tss = 0.2551 ::: train hss = 0.5631 : val hss = 0.2173
Fold 2: train tss = 0.3506 : val tss = 0.5901 ::: train hss = 0.2903 : val hss = 0.4212
Fold 3: train tss = 0.5268 : val tss = -0.0072 ::: train hss = 0.3833 : val hss = -0.0094
Fold 4: train tss = 0.4189 : val tss = 0.4520 ::: train hss = 0.3603 : val hss = 0.4306
mean cv TSS: 0.2580
mean cv HSS: 0.2119
139/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0001 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0118 : val tss = -0.0024 ::: train hss = 0.0224 : val hss = -0.0041
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: -0.0005
mean cv HSS: -0.0008
140/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7181 : val tss = 0.3791 ::: train hss = 0.6654 : val hss = 0.2267
Fold 2: train tss = 0.4965 : val tss = 0.5923 ::: train hss = 0.4067 : val hss = 0.4655
Fold 3: train tss = 0.4907 : val tss = 0.1466 ::: train hss = 0.4254 : val hss = 0.0980
Fold 4: train tss = 0.5698 : val tss = 0.3723 ::: train hss = 0.4579 : val hss = 0.3703
mean cv TSS: 0.2980
mean cv HSS: 0.2321
141/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5214 : val tss = 0.2865 ::: train hss = 0.5834 : val hss = 0.1816
Fold 2: train tss = 0.1134 : val tss = 0.2800 ::: train hss = 0.1793 : val hss = 0.3331
Fold 3: train tss = 0.3841 : val tss = 0.0251 ::: train hss = 0.3922 : val hss = 0.0272
Fold 4: train tss = 0.3574 : val tss = 0.6032 ::: train hss = 0.3689 : val hss = 0.4604
mean cv TSS: 0.2390
mean cv HSS: 0.2004
142/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5272 : val tss = 0.4018 ::: train hss = 0.6231 : val hss = 0.1661
Fold 2: train tss = 0.2426 : val tss = 0.5752 ::: train hss = 0.3384 : val hss = 0.4542
Fold 3: train tss = 0.6387 : val tss = 0.0151 ::: train hss = 0.5594 : val hss = 0.0245
Fold 4: train tss = 0.6104 : val tss = 0.5049 ::: train hss = 0.4634 : val hss = 0.4709
mean cv TSS: 0.2994
mean cv HSS: 0.2231
143/864
{'batch_size': 128, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4999 : val tss = 0.2638 ::: train hss = 0.5972 : val hss = 0.1982
Fold 2: train tss = 0.1344 : val tss = 0.2628 ::: train hss = 0.1944 : val hss = 0.3377
Fold 3: train tss = 0.5327 : val tss = 0.0225 ::: train hss = 0.3859 : val hss = 0.0331
Fold 4: train tss = 0.4245 : val tss = 0.5722 ::: train hss = 0.3597 : val hss = 0.4789
mean cv TSS: 0.2243
mean cv HSS: 0.2096
144/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4935 : val tss = -0.0165 ::: train hss = 0.2350 : val hss = -0.0159
Fold 1: train tss = 0.7637 : val tss = 0.3176 ::: train hss = 0.3346 : val hss = 0.1806
Fold 2: train tss = 0.7409 : val tss = 0.6979 ::: train hss = 0.2204 : val hss = 0.2951
Fold 3: train tss = 0.7492 : val tss = 0.3386 ::: train hss = 0.2580 : val hss = 0.0808
Fold 4: train tss = 0.7261 : val tss = 0.6960 ::: train hss = 0.1995 : val hss = 0.2610
mean cv TSS: 0.4067
mean cv HSS: 0.1603
145/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.3395 : val tss = 0.2227 ::: train hss = 0.1191 : val hss = 0.1777
Fold 1: train tss = 0.7664 : val tss = 0.3984 ::: train hss = 0.4162 : val hss = 0.2078
Fold 2: train tss = 0.6976 : val tss = 0.7143 ::: train hss = 0.1890 : val hss = 0.2966
Fold 3: train tss = 0.7281 : val tss = 0.1744 ::: train hss = 0.2329 : val hss = 0.0417
Fold 4: train tss = 0.6988 : val tss = 0.6537 ::: train hss = 0.1951 : val hss = 0.2344
mean cv TSS: 0.4327
mean cv HSS: 0.1916
146/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7611 : val tss = 0.4566 ::: train hss = 0.3734 : val hss = 0.2852
Fold 2: train tss = 0.7624 : val tss = 0.7122 ::: train hss = 0.2434 : val hss = 0.2997
Fold 3: train tss = 0.7444 : val tss = 0.3335 ::: train hss = 0.2177 : val hss = 0.0762
Fold 4: train tss = 0.7183 : val tss = 0.6793 ::: train hss = 0.1936 : val hss = 0.2357
mean cv TSS: 0.4363
mean cv HSS: 0.1794
147/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7573 : val tss = 0.4424 ::: train hss = 0.3002 : val hss = 0.1486
Fold 2: train tss = 0.7180 : val tss = 0.6896 ::: train hss = 0.1958 : val hss = 0.2616
Fold 3: train tss = 0.7127 : val tss = 0.1865 ::: train hss = 0.1952 : val hss = 0.0323
Fold 4: train tss = 0.7280 : val tss = 0.6864 ::: train hss = 0.2183 : val hss = 0.3035
mean cv TSS: 0.4010
mean cv HSS: 0.1492
148/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.2921 : val tss = 0.2787 ::: train hss = 0.1270 : val hss = 0.1340
Fold 1: train tss = 0.7562 : val tss = 0.2459 ::: train hss = 0.3404 : val hss = 0.0837
Fold 2: train tss = 0.7476 : val tss = 0.5861 ::: train hss = 0.1970 : val hss = 0.2081
Fold 3: train tss = 0.7419 : val tss = 0.3431 ::: train hss = 0.2077 : val hss = 0.0408
Fold 4: train tss = 0.7106 : val tss = 0.6619 ::: train hss = 0.1736 : val hss = 0.2224
mean cv TSS: 0.4231
mean cv HSS: 0.1378
149/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7615 : val tss = 0.4482 ::: train hss = 0.3761 : val hss = 0.1906
Fold 2: train tss = 0.6964 : val tss = 0.5940 ::: train hss = 0.1434 : val hss = 0.1829
Fold 3: train tss = 0.7411 : val tss = 0.1849 ::: train hss = 0.2511 : val hss = 0.0448
Fold 4: train tss = 0.7366 : val tss = 0.6710 ::: train hss = 0.2204 : val hss = 0.2756
mean cv TSS: 0.3796
mean cv HSS: 0.1388
150/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.8281 : val tss = 0.3210 ::: train hss = 0.1513 : val hss = 0.1423
Fold 1: train tss = 0.7933 : val tss = 0.3342 ::: train hss = 0.4250 : val hss = 0.1339
Fold 2: train tss = 0.7526 : val tss = 0.6971 ::: train hss = 0.2367 : val hss = 0.2859
Fold 3: train tss = 0.7578 : val tss = 0.4749 ::: train hss = 0.2590 : val hss = 0.0722
Fold 4: train tss = 0.7542 : val tss = 0.6277 ::: train hss = 0.2266 : val hss = 0.2610
mean cv TSS: 0.4910
mean cv HSS: 0.1790
151/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7632 : val tss = 0.3798 ::: train hss = 0.4259 : val hss = 0.1960
Fold 2: train tss = 0.7221 : val tss = 0.6914 ::: train hss = 0.2047 : val hss = 0.2718
Fold 3: train tss = 0.7262 : val tss = 0.1720 ::: train hss = 0.2246 : val hss = 0.0373
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.2486
mean cv HSS: 0.1010
152/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7643 : val tss = 0.3390 ::: train hss = 0.4370 : val hss = 0.1939
Fold 2: train tss = 0.7733 : val tss = 0.6938 ::: train hss = 0.2385 : val hss = 0.2915
Fold 3: train tss = 0.7853 : val tss = 0.1353 ::: train hss = 0.3364 : val hss = 0.0522
Fold 4: train tss = 0.7729 : val tss = 0.6779 ::: train hss = 0.2678 : val hss = 0.2908
mean cv TSS: 0.3692
mean cv HSS: 0.1657
153/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.7110 : val tss = 0.6335 ::: train hss = 0.1879 : val hss = 0.2147
Fold 3: train tss = 0.7625 : val tss = 0.1363 ::: train hss = 0.2811 : val hss = 0.0382
Fold 4: train tss = 0.7396 : val tss = 0.6694 ::: train hss = 0.2147 : val hss = 0.2660
mean cv TSS: 0.2878
mean cv HSS: 0.1038
154/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.3362 : val tss = 0.0000 ::: train hss = 0.0947 : val hss = 0.0000
Fold 1: train tss = 0.7582 : val tss = 0.3274 ::: train hss = 0.5171 : val hss = 0.1312
Fold 2: train tss = 0.7394 : val tss = 0.6655 ::: train hss = 0.2068 : val hss = 0.2478
Fold 3: train tss = 0.7808 : val tss = 0.1311 ::: train hss = 0.3009 : val hss = 0.0384
Fold 4: train tss = 0.7825 : val tss = 0.7169 ::: train hss = 0.2786 : val hss = 0.3299
mean cv TSS: 0.3682
mean cv HSS: 0.1495
155/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6827 : val tss = 0.4128 ::: train hss = 0.4425 : val hss = 0.2019
Fold 2: train tss = 0.7156 : val tss = 0.6449 ::: train hss = 0.1899 : val hss = 0.2437
Fold 3: train tss = 0.7690 : val tss = 0.1166 ::: train hss = 0.2782 : val hss = 0.0356
Fold 4: train tss = 0.7138 : val tss = 0.6421 ::: train hss = 0.1655 : val hss = 0.2392
mean cv TSS: 0.3633
mean cv HSS: 0.1441
156/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4425 : val tss = -0.0092 ::: train hss = 0.1945 : val hss = -0.0077
Fold 1: train tss = 0.7769 : val tss = 0.3538 ::: train hss = 0.3956 : val hss = 0.1937
Fold 2: train tss = 0.6613 : val tss = 0.6007 ::: train hss = 0.1503 : val hss = 0.1847
Fold 3: train tss = 0.7345 : val tss = 0.3205 ::: train hss = 0.2358 : val hss = 0.0516
Fold 4: train tss = 0.7101 : val tss = 0.6462 ::: train hss = 0.1820 : val hss = 0.2417
mean cv TSS: 0.3824
mean cv HSS: 0.1328
157/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.2907 : val tss = 0.0131 ::: train hss = 0.1129 : val hss = 0.0136
Fold 1: train tss = 0.7577 : val tss = 0.3592 ::: train hss = 0.3797 : val hss = 0.2049
Fold 2: train tss = 0.6756 : val tss = 0.6838 ::: train hss = 0.1493 : val hss = 0.2580
Fold 3: train tss = 0.6905 : val tss = 0.2068 ::: train hss = 0.2061 : val hss = 0.0477

Fold 4: train tss = 0.6898 : val tss = 0.6762 ::: train hss = 0.1851 : val hss = 0.2382
mean cv TSS: 0.3878
mean cv HSS: 0.1525
158/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5324 : val tss = 0.2891 ::: train hss = 0.1203 : val hss = 0.1466
Fold 1: train tss = 0.8060 : val tss = 0.2624 ::: train hss = 0.3591 : val hss = 0.1136
Fold 2: train tss = 0.7262 : val tss = 0.6642 ::: train hss = 0.1847 : val hss = 0.2474
Fold 3: train tss = 0.7484 : val tss = 0.1161 ::: train hss = 0.2715 : val hss = 0.0352
Fold 4: train tss = 0.7303 : val tss = 0.6508 ::: train hss = 0.2161 : val hss = 0.2382
mean cv TSS: 0.3965
mean cv HSS: 0.1562
159/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.3794 : val tss = 0.0054 ::: train hss = 0.0763 : val hss = 0.0049
Fold 1: train tss = 0.7681 : val tss = 0.4871 ::: train hss = 0.4314 : val hss = 0.2361
Fold 2: train tss = 0.7231 : val tss = 0.6777 ::: train hss = 0.1914 : val hss = 0.2575
Fold 3: train tss = 0.7175 : val tss = 0.2974 ::: train hss = 0.2206 : val hss = 0.0590
Fold 4: train tss = 0.7209 : val tss = 0.6872 ::: train hss = 0.2329 : val hss = 0.2710
mean cv TSS: 0.4310
mean cv HSS: 0.1657
160/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.3400 : val tss = -0.0124 ::: train hss = 0.1236 : val hss = -0.0084
Fold 1: train tss = 0.7860 : val tss = 0.4017 ::: train hss = 0.2047 : val hss = 0.0838
Fold 2: train tss = 0.7384 : val tss = 0.7054 ::: train hss = 0.2190 : val hss = 0.2987
Fold 3: train tss = 0.7565 : val tss = 0.1613 ::: train hss = 0.2525 : val hss = 0.0322
Fold 4: train tss = 0.6493 : val tss = 0.5837 ::: train hss = 0.1180 : val hss = 0.1787
mean cv TSS: 0.3679
mean cv HSS: 0.1170
161/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.3872 : val tss = 0.2077 ::: train hss = 0.1156 : val hss = 0.1252
Fold 1: train tss = 0.7524 : val tss = 0.3507 ::: train hss = 0.3724 : val hss = 0.1605
Fold 2: train tss = 0.7091 : val tss = 0.6271 ::: train hss = 0.1587 : val hss = 0.2138
Fold 3: train tss = 0.7527 : val tss = 0.4044 ::: train hss = 0.2741 : val hss = 0.0593
Fold 4: train tss = 0.6294 : val tss = 0.6192 ::: train hss = 0.1150 : val hss = 0.1829
mean cv TSS: 0.4418
mean cv HSS: 0.1483
162/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.7222 : val tss = -0.0242 ::: train hss = 0.1086 : val hss = -0.0221
Fold 1: train tss = 0.7432 : val tss = 0.3448 ::: train hss = 0.3390 : val hss = 0.1026
Fold 2: train tss = 0.7211 : val tss = 0.6480 ::: train hss = 0.2171 : val hss = 0.2259
Fold 3: train tss = 0.7644 : val tss = 0.0744 ::: train hss = 0.2350 : val hss = 0.0165
Fold 4: train tss = 0.7326 : val tss = 0.6677 ::: train hss = 0.2098 : val hss = 0.2422
mean cv TSS: 0.3421
mean cv HSS: 0.1130
163/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7302 : val tss = 0.3181 ::: train hss = 0.3373 : val hss = 0.1607
Fold 2: train tss = 0.6863 : val tss = 0.6224 ::: train hss = 0.1437 : val hss = 0.2060
Fold 3: train tss = 0.7055 : val tss = 0.1367 ::: train hss = 0.1920 : val hss = 0.0323
Fold 4: train tss = 0.7038 : val tss = 0.6573 ::: train hss = 0.1807 : val hss = 0.2422
mean cv TSS: 0.3469
mean cv HSS: 0.1282
164/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.5627 : val tss = -0.0066 ::: train hss = 0.0658 : val hss = -0.0029
Fold 1: train tss = 0.7401 : val tss = 0.4004 ::: train hss = 0.3458 : val hss = 0.0929
Fold 2: train tss = 0.7760 : val tss = 0.7108 ::: train hss = 0.2804 : val hss = 0.3213
Fold 3: train tss = 0.7857 : val tss = 0.0489 ::: train hss = 0.2714 : val hss = 0.0143
Fold 4: train tss = 0.7707 : val tss = 0.6943 ::: train hss = 0.2305 : val hss = 0.2791
mean cv TSS: 0.3695
mean cv HSS: 0.1409
165/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6137 : val tss = 0.1120 ::: train hss = 0.5060 : val hss = 0.0497
Fold 2: train tss = 0.7325 : val tss = 0.6629 ::: train hss = 0.2085 : val hss = 0.2361
Fold 3: train tss = 0.7575 : val tss = 0.1882 ::: train hss = 0.2974 : val hss = 0.0432
Fold 4: train tss = 0.6794 : val tss = 0.6409 ::: train hss = 0.1609 : val hss = 0.2144
mean cv TSS: 0.3208
mean cv HSS: 0.1087
166/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.4806 : val tss = 0.0269 ::: train hss = 0.1007 : val hss = 0.0127
Fold 1: train tss = 0.7692 : val tss = 0.3478 ::: train hss = 0.4906 : val hss = 0.1048
Fold 2: train tss = 0.7513 : val tss = 0.7177 ::: train hss = 0.2447 : val hss = 0.3052
Fold 3: train tss = 0.7827 : val tss = 0.0467 ::: train hss = 0.3032 : val hss = 0.0057
Fold 4: train tss = 0.7681 : val tss = 0.7101 ::: train hss = 0.2757 : val hss = 0.2880
mean cv TSS: 0.3698
mean cv HSS: 0.1433
167/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6367 : val tss = 0.4601 ::: train hss = 0.2854 : val hss = 0.0847
Fold 2: train tss = 0.6926 : val tss = 0.6123 ::: train hss = 0.1455 : val hss = 0.1963
Fold 3: train tss = 0.7471 : val tss = 0.1781 ::: train hss = 0.2855 : val hss = 0.0440
Fold 4: train tss = 0.7432 : val tss = 0.6712 ::: train hss = 0.2298 : val hss = 0.2773
mean cv TSS: 0.3843
mean cv HSS: 0.1205
168/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 379
Fold 0: train tss = 0.6330 : val tss = 0.2440 ::: train hss = 0.1455 : val hss = 0.1246
Fold 1: train tss = 0.7835 : val tss = 0.3279 ::: train hss = 0.4147 : val hss = 0.1342
Fold 2: train tss = 0.7670 : val tss = 0.6789 ::: train hss = 0.2536 : val hss = 0.2500
Fold 3: train tss = 0.7596 : val tss = 0.1627 ::: train hss = 0.2549 : val hss = 0.0328
Fold 4: train tss = 0.7479 : val tss = 0.6780 ::: train hss = 0.2206 : val hss = 0.2893
mean cv TSS: 0.4183
mean cv HSS: 0.1662
169/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3886 : val tss = 0.3309 ::: train hss = 0.1264 : val hss = 0.2012
Fold 1: train tss = 0.7669 : val tss = 0.4072 ::: train hss = 0.4206 : val hss = 0.2260
Fold 2: train tss = 0.7134 : val tss = 0.6887 ::: train hss = 0.1823 : val hss = 0.2618
Fold 3: train tss = 0.7328 : val tss = 0.1840 ::: train hss = 0.2324 : val hss = 0.0380
Fold 4: train tss = 0.7137 : val tss = 0.6576 ::: train hss = 0.1955 : val hss = 0.2276
mean cv TSS: 0.4537
mean cv HSS: 0.1909
170/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7215 : val tss = 0.2814 ::: train hss = 0.1061 : val hss = 0.1261
Fold 1: train tss = 0.8124 : val tss = 0.3687 ::: train hss = 0.4044 : val hss = 0.1564
Fold 2: train tss = 0.7411 : val tss = 0.6013 ::: train hss = 0.1568 : val hss = 0.1926
Fold 3: train tss = 0.7926 : val tss = 0.2056 ::: train hss = 0.3005 : val hss = 0.0435
Fold 4: train tss = 0.7473 : val tss = 0.6590 ::: train hss = 0.2105 : val hss = 0.2766
mean cv TSS: 0.4232
mean cv HSS: 0.1591
171/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4851 : val tss = 0.3350 ::: train hss = 0.1260 : val hss = 0.1897
Fold 1: train tss = 0.7687 : val tss = 0.4300 ::: train hss = 0.3988 : val hss = 0.1454
Fold 2: train tss = 0.7108 : val tss = 0.6936 ::: train hss = 0.1922 : val hss = 0.2716
Fold 3: train tss = 0.7559 : val tss = 0.1651 ::: train hss = 0.2595 : val hss = 0.0394
Fold 4: train tss = 0.6962 : val tss = 0.6691 ::: train hss = 0.1654 : val hss = 0.2359
mean cv TSS: 0.4586
mean cv HSS: 0.1764
172/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4862 : val tss = 0.0094 ::: train hss = 0.1341 : val hss = 0.0065
Fold 1: train tss = 0.8234 : val tss = 0.3559 ::: train hss = 0.3140 : val hss = 0.1336
Fold 2: train tss = 0.7506 : val tss = 0.7009 ::: train hss = 0.2015 : val hss = 0.2877
Fold 3: train tss = 0.7938 : val tss = 0.2238 ::: train hss = 0.2942 : val hss = 0.0553
Fold 4: train tss = 0.6554 : val tss = 0.4293 ::: train hss = 0.1180 : val hss = 0.0904
mean cv TSS: 0.3439
mean cv HSS: 0.1147
173/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4794 : val tss = 0.3525 ::: train hss = 0.0954 : val hss = 0.1651
Fold 1: train tss = 0.7766 : val tss = 0.2863 ::: train hss = 0.4307 : val hss = 0.2192
Fold 2: train tss = 0.7108 : val tss = 0.5840 ::: train hss = 0.1469 : val hss = 0.1769
Fold 3: train tss = 0.7617 : val tss = 0.1740 ::: train hss = 0.2704 : val hss = 0.0334
Fold 4: train tss = 0.7039 : val tss = 0.5910 ::: train hss = 0.1550 : val hss = 0.1823
mean cv TSS: 0.3976
mean cv HSS: 0.1554
174/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.9277 : val tss = 0.2796 ::: train hss = 0.1657 : val hss = 0.1696
Fold 1: train tss = 0.8154 : val tss = 0.3050 ::: train hss = 0.4301 : val hss = 0.1233
Fold 2: train tss = 0.7793 : val tss = 0.7102 ::: train hss = 0.2711 : val hss = 0.2973
Fold 3: train tss = 0.8047 : val tss = 0.1300 ::: train hss = 0.3195 : val hss = 0.0237
Fold 4: train tss = 0.7889 : val tss = 0.6512 ::: train hss = 0.2488 : val hss = 0.2592
mean cv TSS: 0.4152
mean cv HSS: 0.1746
175/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7550 : val tss = 0.4297 ::: train hss = 0.4760 : val hss = 0.2007
Fold 2: train tss = 0.7045 : val tss = 0.6554 ::: train hss = 0.1972 : val hss = 0.2286
Fold 3: train tss = 0.7307 : val tss = 0.1587 ::: train hss = 0.2306 : val hss = 0.0292
Fold 4: train tss = 0.7295 : val tss = 0.6901 ::: train hss = 0.2187 : val hss = 0.2649
mean cv TSS: 0.3868
mean cv HSS: 0.1447
176/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8402 : val tss = 0.2735 ::: train hss = 0.4211 : val hss = 0.1381
Fold 2: train tss = 0.7858 : val tss = 0.6391 ::: train hss = 0.2546 : val hss = 0.2391
Fold 3: train tss = 0.8045 : val tss = 0.1374 ::: train hss = 0.3737 : val hss = 0.0431
Fold 4: train tss = 0.8085 : val tss = 0.6826 ::: train hss = 0.2784 : val hss = 0.2843
mean cv TSS: 0.3465
mean cv HSS: 0.1409
177/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7682 : val tss = 0.4025 ::: train hss = 0.4789 : val hss = 0.1638
Fold 2: train tss = 0.7608 : val tss = 0.6949 ::: train hss = 0.2671 : val hss = 0.2743
Fold 3: train tss = 0.7789 : val tss = 0.1499 ::: train hss = 0.3263 : val hss = 0.0401
Fold 4: train tss = 0.7603 : val tss = 0.6965 ::: train hss = 0.2684 : val hss = 0.2891
mean cv TSS: 0.3888
mean cv HSS: 0.1535
178/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.4851 : val tss = 0.2006 ::: train hss = 0.1260 : val hss = 0.0950
Fold 1: train tss = 0.8138 : val tss = 0.2792 ::: train hss = 0.3088 : val hss = 0.0620
Fold 2: train tss = 0.7702 : val tss = 0.7339 ::: train hss = 0.3091 : val hss = 0.3300
Fold 3: train tss = 0.8084 : val tss = 0.1136 ::: train hss = 0.3547 : val hss = 0.0418

Fold 4: train tss = 0.7687 : val tss = 0.6769 ::: train hss = 0.2296 : val hss = 0.2889
mean cv TSS: 0.4008
mean cv HSS: 0.1635
179/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7684 : val tss = 0.4028 ::: train hss = 0.5391 : val hss = 0.1812
Fold 2: train tss = 0.7557 : val tss = 0.6865 ::: train hss = 0.2434 : val hss = 0.2703
Fold 3: train tss = 0.7880 : val tss = 0.1768 ::: train hss = 0.3265 : val hss = 0.0517
Fold 4: train tss = 0.7399 : val tss = 0.6714 ::: train hss = 0.2595 : val hss = 0.2688
mean cv TSS: 0.3875
mean cv HSS: 0.1544
180/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.8111 : val tss = -0.0013 ::: train hss = 0.0901 : val hss = -0.0013
Fold 1: train tss = 0.8241 : val tss = 0.2736 ::: train hss = 0.3398 : val hss = 0.1215
Fold 2: train tss = 0.7398 : val tss = 0.6840 ::: train hss = 0.1948 : val hss = 0.2628
Fold 3: train tss = 0.7191 : val tss = 0.1030 ::: train hss = 0.1894 : val hss = 0.0159
Fold 4: train tss = 0.7491 : val tss = 0.6740 ::: train hss = 0.2296 : val hss = 0.2555
mean cv TSS: 0.3467
mean cv HSS: 0.1309
181/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3380 : val tss = 0.3351 ::: train hss = 0.1064 : val hss = 0.2017
Fold 1: train tss = 0.7594 : val tss = 0.3625 ::: train hss = 0.3609 : val hss = 0.1639
Fold 2: train tss = 0.6660 : val tss = 0.6608 ::: train hss = 0.1389 : val hss = 0.2361
Fold 3: train tss = 0.6996 : val tss = 0.2989 ::: train hss = 0.1943 : val hss = 0.0389
Fold 4: train tss = 0.6859 : val tss = 0.6685 ::: train hss = 0.1729 : val hss = 0.2332
mean cv TSS: 0.4652
mean cv HSS: 0.1748
182/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4881 : val tss = 0.0936 ::: train hss = 0.1513 : val hss = 0.0586
Fold 1: train tss = 0.8033 : val tss = 0.4336 ::: train hss = 0.4008 : val hss = 0.1734
Fold 2: train tss = 0.7760 : val tss = 0.7090 ::: train hss = 0.1962 : val hss = 0.3154
Fold 3: train tss = 0.7751 : val tss = 0.0836 ::: train hss = 0.2450 : val hss = 0.0201
Fold 4: train tss = 0.7652 : val tss = 0.6568 ::: train hss = 0.2441 : val hss = 0.2654
mean cv TSS: 0.3953
mean cv HSS: 0.1666
183/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4350 : val tss = 0.3283 ::: train hss = 0.1130 : val hss = 0.1638
Fold 1: train tss = 0.8191 : val tss = 0.3999 ::: train hss = 0.3134 : val hss = 0.1356
Fold 2: train tss = 0.7204 : val tss = 0.7090 ::: train hss = 0.2074 : val hss = 0.3061
Fold 3: train tss = 0.7114 : val tss = 0.3489 ::: train hss = 0.1841 : val hss = 0.0464
Fold 4: train tss = 0.6816 : val tss = 0.6749 ::: train hss = 0.1533 : val hss = 0.2695
mean cv TSS: 0.4922
mean cv HSS: 0.1843
184/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.3930 : val tss = -0.0142 ::: train hss = 0.1828 : val hss = -0.0180
Fold 1: train tss = 0.8524 : val tss = 0.3038 ::: train hss = 0.3558 : val hss = 0.1267
Fold 2: train tss = 0.7820 : val tss = 0.7029 ::: train hss = 0.2463 : val hss = 0.3171
Fold 3: train tss = 0.6799 : val tss = 0.0863 ::: train hss = 0.1456 : val hss = 0.0111
Fold 4: train tss = 0.7468 : val tss = 0.6555 ::: train hss = 0.2302 : val hss = 0.2991
mean cv TSS: 0.3469
mean cv HSS: 0.1472
185/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4857 : val tss = 0.2644 ::: train hss = 0.1304 : val hss = 0.1284
Fold 1: train tss = 0.7666 : val tss = 0.4194 ::: train hss = 0.2530 : val hss = 0.1165
Fold 2: train tss = 0.7358 : val tss = 0.6870 ::: train hss = 0.1985 : val hss = 0.2625
Fold 3: train tss = 0.7010 : val tss = 0.0991 ::: train hss = 0.1800 : val hss = 0.0124
Fold 4: train tss = 0.7034 : val tss = 0.6723 ::: train hss = 0.1863 : val hss = 0.2456
mean cv TSS: 0.4284
mean cv HSS: 0.1531
186/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.5356 : val tss = 0.3037 ::: train hss = 0.1419 : val hss = 0.1384
Fold 1: train tss = 0.8459 : val tss = 0.3356 ::: train hss = 0.2423 : val hss = 0.1872
Fold 2: train tss = 0.7173 : val tss = 0.6603 ::: train hss = 0.1694 : val hss = 0.2490
Fold 3: train tss = 0.7804 : val tss = 0.0076 ::: train hss = 0.2483 : val hss = 0.0014
Fold 4: train tss = 0.7133 : val tss = 0.6620 ::: train hss = 0.1841 : val hss = 0.2493
mean cv TSS: 0.3938
mean cv HSS: 0.1650
187/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6249 : val tss = 0.4412 ::: train hss = 0.3789 : val hss = 0.1679
Fold 2: train tss = 0.6671 : val tss = 0.6547 ::: train hss = 0.1323 : val hss = 0.2327
Fold 3: train tss = 0.7063 : val tss = 0.1057 ::: train hss = 0.2135 : val hss = 0.0157
Fold 4: train tss = 0.6886 : val tss = 0.6768 ::: train hss = 0.1844 : val hss = 0.2365
mean cv TSS: 0.3757
mean cv HSS: 0.1306
188/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.9711 : val tss = 0.2432 ::: train hss = 0.1387 : val hss = 0.1300
Fold 1: train tss = 0.8691 : val tss = 0.2794 ::: train hss = 0.2928 : val hss = 0.1009
Fold 2: train tss = 0.8060 : val tss = 0.6658 ::: train hss = 0.2255 : val hss = 0.2686
Fold 3: train tss = 0.8023 : val tss = 0.0433 ::: train hss = 0.3298 : val hss = 0.0062
Fold 4: train tss = 0.7715 : val tss = 0.6789 ::: train hss = 0.2604 : val hss = 0.2451
mean cv TSS: 0.3821
mean cv HSS: 0.1502
189/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7702 : val tss = 0.4001 ::: train hss = 0.4527 : val hss = 0.2615
Fold 2: train tss = 0.7081 : val tss = 0.6500 ::: train hss = 0.1697 : val hss = 0.2276
Fold 3: train tss = 0.7669 : val tss = 0.1659 ::: train hss = 0.3061 : val hss = 0.0434
Fold 4: train tss = 0.7487 : val tss = 0.6551 ::: train hss = 0.2606 : val hss = 0.2284
mean cv TSS: 0.3742
mean cv HSS: 0.1522
190/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.6783 : val tss = 0.2175 ::: train hss = 0.1268 : val hss = 0.0996
Fold 1: train tss = 0.8069 : val tss = 0.2212 ::: train hss = 0.5268 : val hss = 0.1064
Fold 2: train tss = 0.7738 : val tss = 0.7284 ::: train hss = 0.2988 : val hss = 0.3360
Fold 3: train tss = 0.7652 : val tss = 0.0825 ::: train hss = 0.2820 : val hss = 0.0132
Fold 4: train tss = 0.7398 : val tss = 0.6592 ::: train hss = 0.2101 : val hss = 0.2839
mean cv TSS: 0.3818
mean cv HSS: 0.1678
191/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5573 : val tss = 0.4240 ::: train hss = 0.3474 : val hss = 0.1587
Fold 2: train tss = 0.7468 : val tss = 0.7093 ::: train hss = 0.2457 : val hss = 0.2880
Fold 3: train tss = 0.8193 : val tss = 0.2421 ::: train hss = 0.3591 : val hss = 0.0553
Fold 4: train tss = 0.7295 : val tss = 0.6855 ::: train hss = 0.1867 : val hss = 0.3053
mean cv TSS: 0.4122
mean cv HSS: 0.1615
192/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8324 : val tss = 0.0953 ::: train hss = 0.1820 : val hss = 0.0703
Fold 1: train tss = 0.8174 : val tss = 0.3700 ::: train hss = 0.4949 : val hss = 0.1521
Fold 2: train tss = 0.7687 : val tss = 0.6529 ::: train hss = 0.2499 : val hss = 0.2301
Fold 3: train tss = 0.7925 : val tss = 0.1387 ::: train hss = 0.2755 : val hss = 0.0309
Fold 4: train tss = 0.7649 : val tss = 0.6975 ::: train hss = 0.2344 : val hss = 0.3083
mean cv TSS: 0.3909
mean cv HSS: 0.1584
193/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.3878 : val tss = 0.2928 ::: train hss = 0.1203 : val hss = 0.2117
Fold 1: train tss = 0.7294 : val tss = 0.3747 ::: train hss = 0.5437 : val hss = 0.2006
Fold 2: train tss = 0.6882 : val tss = 0.6530 ::: train hss = 0.1825 : val hss = 0.2274
Fold 3: train tss = 0.7290 : val tss = 0.1641 ::: train hss = 0.2311 : val hss = 0.0277
Fold 4: train tss = 0.7065 : val tss = 0.6775 ::: train hss = 0.1931 : val hss = 0.2415
mean cv TSS: 0.4324
mean cv HSS: 0.1818
194/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5301 : val tss = -0.0161 ::: train hss = 0.1082 : val hss = -0.0087
Fold 1: train tss = 0.8232 : val tss = 0.3077 ::: train hss = 0.4635 : val hss = 0.1392
Fold 2: train tss = 0.7666 : val tss = 0.7283 ::: train hss = 0.2605 : val hss = 0.3606
Fold 3: train tss = 0.8315 : val tss = 0.0376 ::: train hss = 0.3606 : val hss = 0.0098
Fold 4: train tss = 0.8096 : val tss = 0.7192 ::: train hss = 0.3020 : val hss = 0.3421
mean cv TSS: 0.3553
mean cv HSS: 0.1686
195/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5752 : val tss = 0.3388 ::: train hss = 0.0967 : val hss = 0.1612
Fold 1: train tss = 0.7615 : val tss = 0.3867 ::: train hss = 0.1952 : val hss = 0.0781
Fold 2: train tss = 0.7501 : val tss = 0.6974 ::: train hss = 0.2494 : val hss = 0.2685
Fold 3: train tss = 0.7434 : val tss = 0.1675 ::: train hss = 0.2512 : val hss = 0.0350
Fold 4: train tss = 0.7428 : val tss = 0.6742 ::: train hss = 0.2456 : val hss = 0.2772
mean cv TSS: 0.4529
mean cv HSS: 0.1640
196/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.6687 : val tss = -0.0273 ::: train hss = 0.0910 : val hss = -0.0125
Fold 1: train tss = 0.7779 : val tss = 0.2912 ::: train hss = 0.3709 : val hss = 0.1043
Fold 2: train tss = 0.7957 : val tss = 0.6781 ::: train hss = 0.2248 : val hss = 0.2535
Fold 3: train tss = 0.8147 : val tss = 0.0833 ::: train hss = 0.3168 : val hss = 0.0335
Fold 4: train tss = 0.7739 : val tss = 0.6655 ::: train hss = 0.3181 : val hss = 0.2235
mean cv TSS: 0.3382
mean cv HSS: 0.1205
197/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.3371 : val tss = -0.0332 ::: train hss = 0.1006 : val hss = -0.0185
Fold 1: train tss = 0.7608 : val tss = 0.4501 ::: train hss = 0.3428 : val hss = 0.1189
Fold 2: train tss = 0.6502 : val tss = 0.6157 ::: train hss = 0.0956 : val hss = 0.2002
Fold 3: train tss = 0.7638 : val tss = 0.2098 ::: train hss = 0.2607 : val hss = 0.0460
Fold 4: train tss = 0.7302 : val tss = 0.6771 ::: train hss = 0.2161 : val hss = 0.2813
mean cv TSS: 0.3839
mean cv HSS: 0.1256
198/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7335 : val tss = 0.1307 ::: train hss = 0.1706 : val hss = 0.0958
Fold 1: train tss = 0.8506 : val tss = 0.2860 ::: train hss = 0.3712 : val hss = 0.1370
Fold 2: train tss = 0.7331 : val tss = 0.6495 ::: train hss = 0.1714 : val hss = 0.2367
Fold 3: train tss = 0.7937 : val tss = 0.0862 ::: train hss = 0.2689 : val hss = 0.0159
Fold 4: train tss = 0.7813 : val tss = 0.6577 ::: train hss = 0.2609 : val hss = 0.2521
mean cv TSS: 0.3620
mean cv HSS: 0.1475
199/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.3413 : val tss = 0.2091 ::: train hss = 0.1379 : val hss = 0.1872
Fold 1: train tss = 0.7502 : val tss = 0.4115 ::: train hss = 0.4257 : val hss = 0.1995
Fold 2: train tss = 0.7064 : val tss = 0.6695 ::: train hss = 0.1835 : val hss = 0.2483
Fold 3: train tss = 0.7200 : val tss = 0.1603 ::: train hss = 0.2211 : val hss = 0.0265

Fold 4: train tss = 0.7065 : val tss = 0.6993 ::: train hss = 0.1953 : val hss = 0.2670
mean cv TSS: 0.4300
mean cv HSS: 0.1857
200/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9173 : val tss = 0.2439 ::: train hss = 0.1180 : val hss = 0.1183
Fold 1: train tss = 0.9052 : val tss = 0.3010 ::: train hss = 0.3919 : val hss = 0.1213
Fold 2: train tss = 0.7790 : val tss = 0.7065 ::: train hss = 0.2792 : val hss = 0.3705
Fold 3: train tss = 0.8399 : val tss = 0.1256 ::: train hss = 0.4092 : val hss = 0.0346
Fold 4: train tss = 0.7809 : val tss = 0.6601 ::: train hss = 0.2366 : val hss = 0.3075
mean cv TSS: 0.4074
mean cv HSS: 0.1904
201/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.1155 : val tss = 0.1617 ::: train hss = 0.0149 : val hss = 0.0916
Fold 1: train tss = 0.8207 : val tss = 0.4157 ::: train hss = 0.3709 : val hss = 0.1544
Fold 2: train tss = 0.6900 : val tss = 0.5680 ::: train hss = 0.1222 : val hss = 0.1646
Fold 3: train tss = 0.7609 : val tss = 0.1986 ::: train hss = 0.2981 : val hss = 0.0501
Fold 4: train tss = 0.7231 : val tss = 0.6821 ::: train hss = 0.2189 : val hss = 0.2807
mean cv TSS: 0.4052
mean cv HSS: 0.1483
202/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9228 : val tss = -0.0530 ::: train hss = 0.1393 : val hss = -0.0282
Fold 1: train tss = 0.8985 : val tss = 0.4006 ::: train hss = 0.3764 : val hss = 0.1557
Fold 2: train tss = 0.7900 : val tss = 0.7231 ::: train hss = 0.3302 : val hss = 0.3687
Fold 3: train tss = 0.8180 : val tss = 0.1137 ::: train hss = 0.2753 : val hss = 0.0240
Fold 4: train tss = 0.8031 : val tss = 0.6414 ::: train hss = 0.2685 : val hss = 0.3140
mean cv TSS: 0.3651
mean cv HSS: 0.1668
203/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.5303 : val tss = -0.0127 ::: train hss = 0.1088 : val hss = -0.0093
Fold 1: train tss = 0.7642 : val tss = 0.4226 ::: train hss = 0.3136 : val hss = 0.1626
Fold 2: train tss = 0.7389 : val tss = 0.6790 ::: train hss = 0.2586 : val hss = 0.2624
Fold 3: train tss = 0.7891 : val tss = 0.3489 ::: train hss = 0.3152 : val hss = 0.0598
Fold 4: train tss = 0.7306 : val tss = 0.6698 ::: train hss = 0.2091 : val hss = 0.3013
mean cv TSS: 0.4215
mean cv HSS: 0.1554
204/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5372 : val tss = 0.1607 ::: train hss = 0.1569 : val hss = 0.0900
Fold 1: train tss = 0.8157 : val tss = 0.2969 ::: train hss = 0.3177 : val hss = 0.1428
Fold 2: train tss = 0.7223 : val tss = 0.6738 ::: train hss = 0.1974 : val hss = 0.2472
Fold 3: train tss = 0.7552 : val tss = 0.1856 ::: train hss = 0.2206 : val hss = 0.0260
Fold 4: train tss = 0.7430 : val tss = 0.6712 ::: train hss = 0.2201 : val hss = 0.2588
mean cv TSS: 0.3976
mean cv HSS: 0.1529
205/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.1945 : val tss = 0.2820 ::: train hss = 0.1111 : val hss = 0.2372
Fold 1: train tss = 0.7542 : val tss = 0.4358 ::: train hss = 0.4676 : val hss = 0.2027
Fold 2: train tss = 0.6730 : val tss = 0.6522 ::: train hss = 0.1412 : val hss = 0.2296
Fold 3: train tss = 0.6679 : val tss = 0.1554 ::: train hss = 0.1561 : val hss = 0.0225
Fold 4: train tss = 0.6791 : val tss = 0.6698 ::: train hss = 0.1704 : val hss = 0.2293
mean cv TSS: 0.4391
mean cv HSS: 0.1842
206/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.6800 : val tss = 0.1574 ::: train hss = 0.1360 : val hss = 0.0694
Fold 1: train tss = 0.8353 : val tss = 0.4156 ::: train hss = 0.3830 : val hss = 0.1750
Fold 2: train tss = 0.7994 : val tss = 0.6636 ::: train hss = 0.3091 : val hss = 0.2339
Fold 3: train tss = 0.8088 : val tss = 0.0799 ::: train hss = 0.3060 : val hss = 0.0243
Fold 4: train tss = 0.7616 : val tss = 0.6799 ::: train hss = 0.2656 : val hss = 0.2766
mean cv TSS: 0.3993
mean cv HSS: 0.1559
207/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.3409 : val tss = 0.3463 ::: train hss = 0.1324 : val hss = 0.1776
Fold 1: train tss = 0.7746 : val tss = 0.4479 ::: train hss = 0.3783 : val hss = 0.1830
Fold 2: train tss = 0.7128 : val tss = 0.6987 ::: train hss = 0.2082 : val hss = 0.2687
Fold 3: train tss = 0.7192 : val tss = 0.1682 ::: train hss = 0.2374 : val hss = 0.0236
Fold 4: train tss = 0.7299 : val tss = 0.6523 ::: train hss = 0.2325 : val hss = 0.2155
mean cv TSS: 0.4627
mean cv HSS: 0.1737
208/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8245 : val tss = -0.0551 ::: train hss = 0.0496 : val hss = -0.0272
Fold 1: train tss = 0.8738 : val tss = 0.3028 ::: train hss = 0.4140 : val hss = 0.1056
Fold 2: train tss = 0.7418 : val tss = 0.7198 ::: train hss = 0.2617 : val hss = 0.3205
Fold 3: train tss = 0.8274 : val tss = 0.0933 ::: train hss = 0.2987 : val hss = 0.0245
Fold 4: train tss = 0.6598 : val tss = 0.6628 ::: train hss = 0.1366 : val hss = 0.2138
mean cv TSS: 0.3447
mean cv HSS: 0.1274
209/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6782 : val tss = 0.2850 ::: train hss = 0.1262 : val hss = 0.1459
Fold 1: train tss = 0.7999 : val tss = 0.3976 ::: train hss = 0.3473 : val hss = 0.1577
Fold 2: train tss = 0.7300 : val tss = 0.7319 ::: train hss = 0.2381 : val hss = 0.3189
Fold 3: train tss = 0.7114 : val tss = 0.2232 ::: train hss = 0.1969 : val hss = 0.0347
Fold 4: train tss = 0.7193 : val tss = 0.6716 ::: train hss = 0.1833 : val hss = 0.2558
mean cv TSS: 0.4618
mean cv HSS: 0.1826
210/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 4367
Fold 0: train tss = 0.8776 : val tss = 0.1880 ::: train hss = 0.1567 : val hss = 0.1404
Fold 1: train tss = 0.8294 : val tss = 0.2837 ::: train hss = 0.3230 : val hss = 0.1046
Fold 2: train tss = 0.7494 : val tss = 0.6257 ::: train hss = 0.2303 : val hss = 0.2008
Fold 3: train tss = 0.7815 : val tss = 0.0889 ::: train hss = 0.2620 : val hss = 0.0127
Fold 4: train tss = 0.7566 : val tss = 0.6907 ::: train hss = 0.2300 : val hss = 0.3077
mean cv TSS: 0.3754
mean cv HSS: 0.1532
211/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.3369 : val tss = 0.1538 ::: train hss = 0.0991 : val hss = 0.1395
Fold 1: train tss = 0.7372 : val tss = 0.4585 ::: train hss = 0.3870 : val hss = 0.1313
Fold 2: train tss = 0.6584 : val tss = 0.5442 ::: train hss = 0.1444 : val hss = 0.1520
Fold 3: train tss = 0.6616 : val tss = 0.4312 ::: train hss = 0.1687 : val hss = 0.0505
Fold 4: train tss = 0.6104 : val tss = 0.6475 ::: train hss = 0.1330 : val hss = 0.2073
mean cv TSS: 0.4470
mean cv HSS: 0.1361
212/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8161 : val tss = 0.2414 ::: train hss = 0.1023 : val hss = 0.1265
Fold 1: train tss = 0.8457 : val tss = 0.3824 ::: train hss = 0.3668 : val hss = 0.1427
Fold 2: train tss = 0.7868 : val tss = 0.6916 ::: train hss = 0.2001 : val hss = 0.3394
Fold 3: train tss = 0.7455 : val tss = 0.0592 ::: train hss = 0.2603 : val hss = 0.0135
Fold 4: train tss = 0.7839 : val tss = 0.6848 ::: train hss = 0.2371 : val hss = 0.2795
mean cv TSS: 0.4119
mean cv HSS: 0.1803
213/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0780 : val tss = -0.0025 ::: train hss = 0.0152 : val hss = -0.0030
Fold 1: train tss = 0.7599 : val tss = 0.4212 ::: train hss = 0.4362 : val hss = 0.1311
Fold 2: train tss = 0.6923 : val tss = 0.6743 ::: train hss = 0.2035 : val hss = 0.2445
Fold 3: train tss = 0.7103 : val tss = 0.1659 ::: train hss = 0.2488 : val hss = 0.0230
Fold 4: train tss = 0.7092 : val tss = 0.6797 ::: train hss = 0.1912 : val hss = 0.2564
mean cv TSS: 0.3877
mean cv HSS: 0.1304
214/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9482 : val tss = 0.1328 ::: train hss = 0.0807 : val hss = 0.0619
Fold 1: train tss = 0.8602 : val tss = 0.3931 ::: train hss = 0.2907 : val hss = 0.1083
Fold 2: train tss = 0.8111 : val tss = 0.7114 ::: train hss = 0.2318 : val hss = 0.3495
Fold 3: train tss = 0.8257 : val tss = 0.1444 ::: train hss = 0.3639 : val hss = 0.0181
Fold 4: train tss = 0.7972 : val tss = 0.6282 ::: train hss = 0.2344 : val hss = 0.3742
mean cv TSS: 0.4020
mean cv HSS: 0.1824
215/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.7558 : val tss = -0.0116 ::: train hss = 0.0750 : val hss = -0.0158
Fold 1: train tss = 0.7680 : val tss = 0.3854 ::: train hss = 0.3615 : val hss = 0.1210
Fold 2: train tss = 0.7530 : val tss = 0.6909 ::: train hss = 0.2486 : val hss = 0.2713
Fold 3: train tss = 0.7188 : val tss = 0.3651 ::: train hss = 0.2328 : val hss = 0.0441
Fold 4: train tss = 0.7329 : val tss = 0.6847 ::: train hss = 0.2040 : val hss = 0.3043
mean cv TSS: 0.4229
mean cv HSS: 0.1450
216/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.3877 : val tss = 0.3374 ::: train hss = 0.1193 : val hss = 0.1752
Fold 1: train tss = 0.7882 : val tss = 0.3509 ::: train hss = 0.3072 : val hss = 0.1882
Fold 2: train tss = 0.6761 : val tss = 0.6581 ::: train hss = 0.1454 : val hss = 0.2319
Fold 3: train tss = 0.7107 : val tss = 0.4218 ::: train hss = 0.1918 : val hss = 0.0647
Fold 4: train tss = 0.6906 : val tss = 0.6849 ::: train hss = 0.1968 : val hss = 0.2826
mean cv TSS: 0.4906
mean cv HSS: 0.1885
217/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.4369 : val tss = 0.3535 ::: train hss = 0.1266 : val hss = 0.1957
Fold 1: train tss = 0.7171 : val tss = 0.4077 ::: train hss = 0.3982 : val hss = 0.2162
Fold 2: train tss = 0.6884 : val tss = 0.7050 ::: train hss = 0.1971 : val hss = 0.2897
Fold 3: train tss = 0.7040 : val tss = 0.1604 ::: train hss = 0.2328 : val hss = 0.0341
Fold 4: train tss = 0.6864 : val tss = 0.6554 ::: train hss = 0.1963 : val hss = 0.2405
mean cv TSS: 0.4564
mean cv HSS: 0.1952
218/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0459 : val tss = 0.0000 ::: train hss = 0.0334 : val hss = 0.0000
Fold 1: train tss = 0.7378 : val tss = 0.4909 ::: train hss = 0.3591 : val hss = 0.2824
Fold 2: train tss = 0.6938 : val tss = 0.6684 ::: train hss = 0.1906 : val hss = 0.2728
Fold 3: train tss = 0.7105 : val tss = 0.1817 ::: train hss = 0.1857 : val hss = 0.0427
Fold 4: train tss = 0.6981 : val tss = 0.6643 ::: train hss = 0.2112 : val hss = 0.2504
mean cv TSS: 0.4011
mean cv HSS: 0.1697
219/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = -0.0001 : val tss = -0.0002 ::: train hss = -0.0002 : val hss = -0.0005
Fold 1: train tss = 0.7259 : val tss = 0.5007 ::: train hss = 0.2166 : val hss = 0.2727
Fold 2: train tss = 0.6840 : val tss = 0.7091 ::: train hss = 0.1978 : val hss = 0.2837
Fold 3: train tss = 0.7219 : val tss = 0.1558 ::: train hss = 0.2173 : val hss = 0.0371
Fold 4: train tss = 0.7030 : val tss = 0.7024 ::: train hss = 0.2144 : val hss = 0.3170
mean cv TSS: 0.4136
mean cv HSS: 0.1820
220/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4334 : val tss = 0.2327 ::: train hss = 0.1038 : val hss = 0.1017
Fold 1: train tss = 0.4853 : val tss = 0.3839 ::: train hss = 0.2815 : val hss = 0.1198
Fold 2: train tss = 0.6971 : val tss = 0.5809 ::: train hss = 0.1388 : val hss = 0.1731
Fold 3: train tss = 0.7179 : val tss = 0.1206 ::: train hss = 0.1924 : val hss = 0.0176

Fold 4: train tss = 0.7132 : val tss = 0.6005 ::: train hss = 0.1841 : val hss = 0.2601
mean cv TSS: 0.3837
mean cv HSS: 0.1345
221/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.3883 : val tss = 0.3965 ::: train hss = 0.1243 : val hss = 0.1916
Fold 1: train tss = 0.7577 : val tss = 0.4615 ::: train hss = 0.4581 : val hss = 0.1997
Fold 2: train tss = 0.6844 : val tss = 0.6630 ::: train hss = 0.1774 : val hss = 0.2423
Fold 3: train tss = 0.7026 : val tss = 0.1835 ::: train hss = 0.1898 : val hss = 0.0377
Fold 4: train tss = 0.7034 : val tss = 0.6991 ::: train hss = 0.2244 : val hss = 0.3118
mean cv TSS: 0.4807
mean cv HSS: 0.1966
222/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.5293 : val tss = 0.2661 ::: train hss = 0.1043 : val hss = 0.1250
Fold 1: train tss = 0.7547 : val tss = 0.3827 ::: train hss = 0.4277 : val hss = 0.1259
Fold 2: train tss = 0.7338 : val tss = 0.6819 ::: train hss = 0.2583 : val hss = 0.2726
Fold 3: train tss = 0.7543 : val tss = 0.2655 ::: train hss = 0.2320 : val hss = 0.0545
Fold 4: train tss = 0.6921 : val tss = 0.6390 ::: train hss = 0.1613 : val hss = 0.2415
mean cv TSS: 0.4470
mean cv HSS: 0.1639
223/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7444 : val tss = 0.3389 ::: train hss = 0.4544 : val hss = 0.1754
Fold 2: train tss = 0.6566 : val tss = 0.6212 ::: train hss = 0.1584 : val hss = 0.2013
Fold 3: train tss = 0.7265 : val tss = 0.1509 ::: train hss = 0.2145 : val hss = 0.0373
Fold 4: train tss = 0.7127 : val tss = 0.6652 ::: train hss = 0.1875 : val hss = 0.2537
mean cv TSS: 0.3552
mean cv HSS: 0.1336
224/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7723 : val tss = 0.3345 ::: train hss = 0.3933 : val hss = 0.1643
Fold 2: train tss = 0.7162 : val tss = 0.6795 ::: train hss = 0.1565 : val hss = 0.2750
Fold 3: train tss = 0.7604 : val tss = 0.2220 ::: train hss = 0.3033 : val hss = 0.0499
Fold 4: train tss = 0.7513 : val tss = 0.6633 ::: train hss = 0.2923 : val hss = 0.2912
mean cv TSS: 0.3799
mean cv HSS: 0.1561
225/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6866 : val tss = 0.3348 ::: train hss = 0.4373 : val hss = 0.1685
Fold 2: train tss = 0.6706 : val tss = 0.6449 ::: train hss = 0.1536 : val hss = 0.2232
Fold 3: train tss = 0.7173 : val tss = 0.2163 ::: train hss = 0.2127 : val hss = 0.0543
Fold 4: train tss = 0.7153 : val tss = 0.6773 ::: train hss = 0.1909 : val hss = 0.2793
mean cv TSS: 0.3746
mean cv HSS: 0.1451
226/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.1383 : val tss = 0.2534 ::: train hss = 0.0461 : val hss = 0.2426
Fold 1: train tss = 0.6900 : val tss = 0.2475 ::: train hss = 0.5427 : val hss = 0.1941
Fold 2: train tss = 0.7251 : val tss = 0.6799 ::: train hss = 0.2155 : val hss = 0.2576
Fold 3: train tss = 0.7691 : val tss = 0.2958 ::: train hss = 0.3044 : val hss = 0.0869
Fold 4: train tss = 0.7388 : val tss = 0.6579 ::: train hss = 0.2301 : val hss = 0.3322
mean cv TSS: 0.4269
mean cv HSS: 0.2227
227/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7346 : val tss = 0.1910 ::: train hss = 0.2265 : val hss = 0.0591
Fold 4: train tss = 0.6775 : val tss = 0.5995 ::: train hss = 0.1392 : val hss = 0.1997
mean cv TSS: 0.1581
mean cv HSS: 0.0518
228/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4872 : val tss = 0.0811 ::: train hss = 0.1433 : val hss = 0.0465
Fold 1: train tss = 0.7639 : val tss = 0.3440 ::: train hss = 0.2097 : val hss = 0.1800
Fold 2: train tss = 0.6764 : val tss = 0.6273 ::: train hss = 0.1634 : val hss = 0.2051
Fold 3: train tss = 0.7080 : val tss = 0.2803 ::: train hss = 0.1839 : val hss = 0.0494
Fold 4: train tss = 0.6782 : val tss = 0.5824 ::: train hss = 0.1827 : val hss = 0.2541
mean cv TSS: 0.3830
mean cv HSS: 0.1470
229/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.3390 : val tss = 0.3245 ::: train hss = 0.1149 : val hss = 0.2385
Fold 1: train tss = 0.5699 : val tss = 0.4325 ::: train hss = 0.1356 : val hss = 0.1478
Fold 2: train tss = 0.6644 : val tss = 0.7005 ::: train hss = 0.1717 : val hss = 0.2754
Fold 3: train tss = 0.6933 : val tss = 0.1546 ::: train hss = 0.2104 : val hss = 0.0294
Fold 4: train tss = 0.6657 : val tss = 0.6588 ::: train hss = 0.1800 : val hss = 0.2393
mean cv TSS: 0.4542
mean cv HSS: 0.1861
230/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4852 : val tss = 0.1328 ::: train hss = 0.1268 : val hss = 0.0723
Fold 1: train tss = 0.7315 : val tss = 0.4478 ::: train hss = 0.2612 : val hss = 0.1518
Fold 2: train tss = 0.7215 : val tss = 0.6587 ::: train hss = 0.2064 : val hss = 0.2306
Fold 3: train tss = 0.7243 : val tss = 0.2504 ::: train hss = 0.2356 : val hss = 0.0492
Fold 4: train tss = 0.6851 : val tss = 0.6462 ::: train hss = 0.1763 : val hss = 0.3254
mean cv TSS: 0.4272
mean cv HSS: 0.1659
231/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 189
Fold 0: train tss = 0.5353 : val tss = 0.3254 ::: train hss = 0.1400 : val hss = 0.1502
Fold 1: train tss = 0.7055 : val tss = 0.4591 ::: train hss = 0.3159 : val hss = 0.1817
Fold 2: train tss = 0.6782 : val tss = 0.7018 ::: train hss = 0.1796 : val hss = 0.2913
Fold 3: train tss = 0.7237 : val tss = 0.1861 ::: train hss = 0.2651 : val hss = 0.0496
Fold 4: train tss = 0.6425 : val tss = 0.6254 ::: train hss = 0.1586 : val hss = 0.1933
mean cv TSS: 0.4595
mean cv HSS: 0.1732
232/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5281 : val tss = 0.1761 ::: train hss = 0.0992 : val hss = 0.0676
Fold 1: train tss = 0.7810 : val tss = 0.3672 ::: train hss = 0.3945 : val hss = 0.1544
Fold 2: train tss = 0.6882 : val tss = 0.6451 ::: train hss = 0.1376 : val hss = 0.2167
Fold 3: train tss = 0.7323 : val tss = 0.2933 ::: train hss = 0.2108 : val hss = 0.0605
Fold 4: train tss = 0.7143 : val tss = 0.6811 ::: train hss = 0.1777 : val hss = 0.2910
mean cv TSS: 0.4326
mean cv HSS: 0.1580
233/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.4393 : val tss = 0.1266 ::: train hss = 0.1489 : val hss = 0.0876
Fold 1: train tss = 0.7309 : val tss = 0.3694 ::: train hss = 0.4064 : val hss = 0.1706
Fold 2: train tss = 0.6249 : val tss = 0.6884 ::: train hss = 0.1504 : val hss = 0.2774
Fold 3: train tss = 0.6231 : val tss = 0.2896 ::: train hss = 0.1200 : val hss = 0.0279
Fold 4: train tss = 0.6723 : val tss = 0.6764 ::: train hss = 0.1530 : val hss = 0.2416
mean cv TSS: 0.4301
mean cv HSS: 0.1610
234/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.7479 : val tss = 0.2861 ::: train hss = 0.0638 : val hss = 0.1221
Fold 1: train tss = 0.7879 : val tss = 0.2891 ::: train hss = 0.2866 : val hss = 0.1632
Fold 2: train tss = 0.7226 : val tss = 0.6607 ::: train hss = 0.2168 : val hss = 0.2400
Fold 3: train tss = 0.6617 : val tss = 0.1618 ::: train hss = 0.1823 : val hss = 0.0231
Fold 4: train tss = 0.7229 : val tss = 0.6580 ::: train hss = 0.1896 : val hss = 0.2601
mean cv TSS: 0.4112
mean cv HSS: 0.1617
235/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6734 : val tss = 0.4396 ::: train hss = 0.2311 : val hss = 0.1301
Fold 2: train tss = 0.6513 : val tss = 0.6385 ::: train hss = 0.1558 : val hss = 0.2154
Fold 3: train tss = 0.6972 : val tss = 0.1516 ::: train hss = 0.1831 : val hss = 0.0412
Fold 4: train tss = 0.6597 : val tss = 0.6715 ::: train hss = 0.1460 : val hss = 0.2359
mean cv TSS: 0.3802
mean cv HSS: 0.1245
236/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8076 : val tss = 0.4299 ::: train hss = 0.4817 : val hss = 0.1928
Fold 2: train tss = 0.6906 : val tss = 0.6509 ::: train hss = 0.2350 : val hss = 0.2247
Fold 3: train tss = 0.7546 : val tss = 0.1528 ::: train hss = 0.2352 : val hss = 0.0464
Fold 4: train tss = 0.7525 : val tss = 0.6410 ::: train hss = 0.2082 : val hss = 0.2401
mean cv TSS: 0.3749
mean cv HSS: 0.1408
237/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7300 : val tss = 0.4177 ::: train hss = 0.3983 : val hss = 0.1110
Fold 2: train tss = 0.7127 : val tss = 0.6999 ::: train hss = 0.2026 : val hss = 0.2699
Fold 3: train tss = 0.7243 : val tss = 0.1698 ::: train hss = 0.2345 : val hss = 0.0390
Fold 4: train tss = 0.7103 : val tss = 0.6824 ::: train hss = 0.1774 : val hss = 0.3086
mean cv TSS: 0.3940
mean cv HSS: 0.1457
238/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.2405 : val tss = 0.0000 ::: train hss = 0.0925 : val hss = 0.0000
Fold 1: train tss = 0.7639 : val tss = 0.4767 ::: train hss = 0.4789 : val hss = 0.1211
Fold 2: train tss = 0.7374 : val tss = 0.6920 ::: train hss = 0.1985 : val hss = 0.2775
Fold 3: train tss = 0.7802 : val tss = 0.1530 ::: train hss = 0.2524 : val hss = 0.0423
Fold 4: train tss = 0.7170 : val tss = 0.5765 ::: train hss = 0.1861 : val hss = 0.2237
mean cv TSS: 0.3796
mean cv HSS: 0.1329
239/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7384 : val tss = 0.4312 ::: train hss = 0.4857 : val hss = 0.1991
Fold 2: train tss = 0.7028 : val tss = 0.6723 ::: train hss = 0.1997 : val hss = 0.2501
Fold 3: train tss = 0.7353 : val tss = 0.1684 ::: train hss = 0.2370 : val hss = 0.0414
Fold 4: train tss = 0.6984 : val tss = 0.6689 ::: train hss = 0.1737 : val hss = 0.2543
mean cv TSS: 0.3882
mean cv HSS: 0.1490
240/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5888 : val tss = 0.1801 ::: train hss = 0.1884 : val hss = 0.1203
Fold 1: train tss = 0.7917 : val tss = 0.3271 ::: train hss = 0.3492 : val hss = 0.1106
Fold 2: train tss = 0.7441 : val tss = 0.6902 ::: train hss = 0.1873 : val hss = 0.2693
Fold 3: train tss = 0.7470 : val tss = 0.1456 ::: train hss = 0.2288 : val hss = 0.0296
Fold 4: train tss = 0.7337 : val tss = 0.6519 ::: train hss = 0.2040 : val hss = 0.2416
mean cv TSS: 0.3990
mean cv HSS: 0.1543
241/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3400 : val tss = 0.3405 ::: train hss = 0.1236 : val hss = 0.2055
Fold 1: train tss = 0.7686 : val tss = 0.4201 ::: train hss = 0.3978 : val hss = 0.1683
Fold 2: train tss = 0.6891 : val tss = 0.6854 ::: train hss = 0.1815 : val hss = 0.2574
Fold 3: train tss = 0.7211 : val tss = 0.1579 ::: train hss = 0.2299 : val hss = 0.0307

Fold 4: train tss = 0.7125 : val tss = 0.6574 ::: train hss = 0.2025 : val hss = 0.2436
mean cv TSS: 0.4523
mean cv HSS: 0.1811
242/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4357 : val tss = 0.3102 ::: train hss = 0.1178 : val hss = 0.1504
Fold 1: train tss = 0.8070 : val tss = 0.4030 ::: train hss = 0.3655 : val hss = 0.1743
Fold 2: train tss = 0.7686 : val tss = 0.7187 ::: train hss = 0.2325 : val hss = 0.3222
Fold 3: train tss = 0.7750 : val tss = 0.1799 ::: train hss = 0.2521 : val hss = 0.0299
Fold 4: train tss = 0.7452 : val tss = 0.7044 ::: train hss = 0.2259 : val hss = 0.3436
mean cv TSS: 0.4632
mean cv HSS: 0.2041
243/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4326 : val tss = 0.3350 ::: train hss = 0.0994 : val hss = 0.1613
Fold 1: train tss = 0.7923 : val tss = 0.4356 ::: train hss = 0.4164 : val hss = 0.1612
Fold 2: train tss = 0.7063 : val tss = 0.7073 ::: train hss = 0.1950 : val hss = 0.2869
Fold 3: train tss = 0.7468 : val tss = 0.1759 ::: train hss = 0.2698 : val hss = 0.0394
Fold 4: train tss = 0.7313 : val tss = 0.6827 ::: train hss = 0.2347 : val hss = 0.2799
mean cv TSS: 0.4673
mean cv HSS: 0.1857
244/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4830 : val tss = 0.1581 ::: train hss = 0.1130 : val hss = 0.0773
Fold 1: train tss = 0.7919 : val tss = 0.3926 ::: train hss = 0.3796 : val hss = 0.1517
Fold 2: train tss = 0.7499 : val tss = 0.6945 ::: train hss = 0.2080 : val hss = 0.2740
Fold 3: train tss = 0.7620 : val tss = 0.1193 ::: train hss = 0.2357 : val hss = 0.0182
Fold 4: train tss = 0.7620 : val tss = 0.6934 ::: train hss = 0.2382 : val hss = 0.2987
mean cv TSS: 0.4116
mean cv HSS: 0.1640
245/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3327 : val tss = 0.2328 ::: train hss = 0.0778 : val hss = 0.1314
Fold 1: train tss = 0.7831 : val tss = 0.4216 ::: train hss = 0.4519 : val hss = 0.1839
Fold 2: train tss = 0.7359 : val tss = 0.6989 ::: train hss = 0.2146 : val hss = 0.2764
Fold 3: train tss = 0.7103 : val tss = 0.0780 ::: train hss = 0.2046 : val hss = 0.0233
Fold 4: train tss = 0.7402 : val tss = 0.6887 ::: train hss = 0.2332 : val hss = 0.3009
mean cv TSS: 0.4240
mean cv HSS: 0.1832
246/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.6291 : val tss = 0.2746 ::: train hss = 0.1216 : val hss = 0.1269
Fold 1: train tss = 0.8036 : val tss = 0.2986 ::: train hss = 0.3716 : val hss = 0.1764
Fold 2: train tss = 0.7618 : val tss = 0.6929 ::: train hss = 0.2420 : val hss = 0.2836
Fold 3: train tss = 0.7769 : val tss = 0.1665 ::: train hss = 0.2665 : val hss = 0.0286
Fold 4: train tss = 0.7609 : val tss = 0.6594 ::: train hss = 0.2344 : val hss = 0.2603
mean cv TSS: 0.4184
mean cv HSS: 0.1752
247/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7479 : val tss = 0.4192 ::: train hss = 0.4046 : val hss = 0.1802
Fold 2: train tss = 0.6757 : val tss = 0.6450 ::: train hss = 0.1450 : val hss = 0.2243
Fold 3: train tss = 0.7378 : val tss = 0.1116 ::: train hss = 0.2385 : val hss = 0.0203
Fold 4: train tss = 0.7242 : val tss = 0.6891 ::: train hss = 0.2141 : val hss = 0.2588
mean cv TSS: 0.3730
mean cv HSS: 0.1367
248/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.2898 : val tss = 0.0238 ::: train hss = 0.1044 : val hss = 0.0175
Fold 1: train tss = 0.7704 : val tss = 0.1689 ::: train hss = 0.6524 : val hss = 0.1062
Fold 2: train tss = 0.7744 : val tss = 0.6583 ::: train hss = 0.2342 : val hss = 0.2408
Fold 3: train tss = 0.7883 : val tss = 0.1840 ::: train hss = 0.2537 : val hss = 0.0380
Fold 4: train tss = 0.7576 : val tss = 0.6525 ::: train hss = 0.2353 : val hss = 0.2567
mean cv TSS: 0.3375
mean cv HSS: 0.1319
249/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7597 : val tss = 0.4177 ::: train hss = 0.5390 : val hss = 0.1746
Fold 2: train tss = 0.7334 : val tss = 0.7155 ::: train hss = 0.2347 : val hss = 0.2980
Fold 3: train tss = 0.7629 : val tss = 0.2221 ::: train hss = 0.2804 : val hss = 0.0589
Fold 4: train tss = 0.7561 : val tss = 0.6720 ::: train hss = 0.2720 : val hss = 0.2880
mean cv TSS: 0.4055
mean cv HSS: 0.1639
250/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.4281 : val tss = 0.2828 ::: train hss = 0.0812 : val hss = 0.1082
Fold 1: train tss = 0.8394 : val tss = 0.3576 ::: train hss = 0.3307 : val hss = 0.1481
Fold 2: train tss = 0.7679 : val tss = 0.6562 ::: train hss = 0.2815 : val hss = 0.2800
Fold 3: train tss = 0.8211 : val tss = 0.2425 ::: train hss = 0.3346 : val hss = 0.0657
Fold 4: train tss = 0.7974 : val tss = 0.5602 ::: train hss = 0.2633 : val hss = 0.2450
mean cv TSS: 0.4199
mean cv HSS: 0.1694
251/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7659 : val tss = 0.4202 ::: train hss = 0.5038 : val hss = 0.2264
Fold 2: train tss = 0.7422 : val tss = 0.6833 ::: train hss = 0.2035 : val hss = 0.2610
Fold 3: train tss = 0.7867 : val tss = 0.1090 ::: train hss = 0.3167 : val hss = 0.0338
Fold 4: train tss = 0.7590 : val tss = 0.6907 ::: train hss = 0.2376 : val hss = 0.3221
mean cv TSS: 0.3806
mean cv HSS: 0.1687
252/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 379
Fold 0: train tss = 0.6812 : val tss = 0.0197 ::: train hss = 0.1434 : val hss = 0.0159
Fold 1: train tss = 0.7694 : val tss = 0.4260 ::: train hss = 0.3428 : val hss = 0.1459
Fold 2: train tss = 0.7311 : val tss = 0.7252 ::: train hss = 0.1826 : val hss = 0.3312
Fold 3: train tss = 0.7407 : val tss = 0.2405 ::: train hss = 0.2156 : val hss = 0.0441
Fold 4: train tss = 0.7293 : val tss = 0.6515 ::: train hss = 0.1904 : val hss = 0.2435
mean cv TSS: 0.4126
mean cv HSS: 0.1561
253/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3900 : val tss = 0.3557 ::: train hss = 0.1405 : val hss = 0.2288
Fold 1: train tss = 0.7563 : val tss = 0.4136 ::: train hss = 0.4027 : val hss = 0.2078
Fold 2: train tss = 0.6801 : val tss = 0.6224 ::: train hss = 0.1697 : val hss = 0.2029
Fold 3: train tss = 0.7230 : val tss = 0.3995 ::: train hss = 0.2153 : val hss = 0.0599
Fold 4: train tss = 0.6742 : val tss = 0.6272 ::: train hss = 0.1637 : val hss = 0.1970
mean cv TSS: 0.4837
mean cv HSS: 0.1793
254/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5639 : val tss = 0.0748 ::: train hss = 0.0679 : val hss = 0.0551
Fold 1: train tss = 0.8208 : val tss = 0.3207 ::: train hss = 0.2193 : val hss = 0.1087
Fold 2: train tss = 0.7560 : val tss = 0.7168 ::: train hss = 0.2370 : val hss = 0.3148
Fold 3: train tss = 0.7547 : val tss = 0.1649 ::: train hss = 0.2334 : val hss = 0.0316
Fold 4: train tss = 0.7332 : val tss = 0.6757 ::: train hss = 0.2210 : val hss = 0.2650
mean cv TSS: 0.3906
mean cv HSS: 0.1550
255/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3848 : val tss = 0.3321 ::: train hss = 0.1000 : val hss = 0.1819
Fold 1: train tss = 0.7468 : val tss = 0.4074 ::: train hss = 0.2563 : val hss = 0.1153
Fold 2: train tss = 0.7287 : val tss = 0.6849 ::: train hss = 0.2051 : val hss = 0.2547
Fold 3: train tss = 0.7391 : val tss = 0.1677 ::: train hss = 0.2268 : val hss = 0.0328
Fold 4: train tss = 0.7351 : val tss = 0.6777 ::: train hss = 0.2236 : val hss = 0.2671
mean cv TSS: 0.4540
mean cv HSS: 0.1704
256/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5281 : val tss = 0.0333 ::: train hss = 0.0992 : val hss = 0.0159
Fold 1: train tss = 0.7626 : val tss = 0.2232 ::: train hss = 0.2279 : val hss = 0.1063
Fold 2: train tss = 0.7522 : val tss = 0.7157 ::: train hss = 0.2065 : val hss = 0.3335
Fold 3: train tss = 0.7786 : val tss = 0.0919 ::: train hss = 0.2448 : val hss = 0.0203
Fold 4: train tss = 0.7666 : val tss = 0.6909 ::: train hss = 0.2590 : val hss = 0.2845
mean cv TSS: 0.3510
mean cv HSS: 0.1521
257/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5831 : val tss = 0.1243 ::: train hss = 0.1356 : val hss = 0.0653
Fold 1: train tss = 0.7694 : val tss = 0.3971 ::: train hss = 0.4049 : val hss = 0.2102
Fold 2: train tss = 0.7191 : val tss = 0.6707 ::: train hss = 0.1881 : val hss = 0.2464
Fold 3: train tss = 0.7438 : val tss = 0.1662 ::: train hss = 0.2474 : val hss = 0.0302
Fold 4: train tss = 0.7255 : val tss = 0.6795 ::: train hss = 0.2213 : val hss = 0.2783
mean cv TSS: 0.4075
mean cv HSS: 0.1661
258/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8804 : val tss = 0.3290 ::: train hss = 0.1752 : val hss = 0.1743
Fold 1: train tss = 0.8051 : val tss = 0.3625 ::: train hss = 0.2719 : val hss = 0.1194
Fold 2: train tss = 0.7508 : val tss = 0.6911 ::: train hss = 0.1921 : val hss = 0.2791
Fold 3: train tss = 0.6967 : val tss = 0.0971 ::: train hss = 0.1677 : val hss = 0.0171
Fold 4: train tss = 0.7229 : val tss = 0.6833 ::: train hss = 0.1896 : val hss = 0.2721
mean cv TSS: 0.4326
mean cv HSS: 0.1724
259/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6152 : val tss = 0.4345 ::: train hss = 0.3344 : val hss = 0.1369
Fold 2: train tss = 0.6767 : val tss = 0.5483 ::: train hss = 0.1432 : val hss = 0.1542
Fold 3: train tss = 0.6967 : val tss = 0.2695 ::: train hss = 0.1977 : val hss = 0.0319
Fold 4: train tss = 0.6944 : val tss = 0.6578 ::: train hss = 0.1813 : val hss = 0.2417
mean cv TSS: 0.3820
mean cv HSS: 0.1129
260/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.4771 : val tss = -0.0221 ::: train hss = 0.0868 : val hss = -0.0141
Fold 1: train tss = 0.7787 : val tss = 0.2738 ::: train hss = 0.5003 : val hss = 0.1193
Fold 2: train tss = 0.7290 : val tss = 0.6143 ::: train hss = 0.2394 : val hss = 0.2060
Fold 3: train tss = 0.7642 : val tss = 0.0735 ::: train hss = 0.2042 : val hss = 0.0190
Fold 4: train tss = 0.8000 : val tss = 0.6757 ::: train hss = 0.2833 : val hss = 0.3192
mean cv TSS: 0.3230
mean cv HSS: 0.1299
261/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7249 : val tss = 0.4313 ::: train hss = 0.1945 : val hss = 0.0848
Fold 2: train tss = 0.7363 : val tss = 0.6625 ::: train hss = 0.1854 : val hss = 0.2447
Fold 3: train tss = 0.7689 : val tss = 0.1425 ::: train hss = 0.3189 : val hss = 0.0355
Fold 4: train tss = 0.7188 : val tss = 0.6775 ::: train hss = 0.2297 : val hss = 0.2670
mean cv TSS: 0.3828
mean cv HSS: 0.1264
262/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.5778 : val tss = 0.0666 ::: train hss = 0.1070 : val hss = 0.0363
Fold 1: train tss = 0.6725 : val tss = 0.3613 ::: train hss = 0.3210 : val hss = 0.0933
Fold 2: train tss = 0.7940 : val tss = 0.7184 ::: train hss = 0.2881 : val hss = 0.3488
Fold 3: train tss = 0.8149 : val tss = 0.0766 ::: train hss = 0.2975 : val hss = 0.0320

Fold 4: train tss = 0.7815 : val tss = 0.6798 ::: train hss = 0.2426 : val hss = 0.2817
mean cv TSS: 0.3805
mean cv HSS: 0.1584
263/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0895 : val tss = 0.0039 ::: train hss = 0.0329 : val hss = 0.0047
Fold 1: train tss = 0.7831 : val tss = 0.4192 ::: train hss = 0.3779 : val hss = 0.1642
Fold 2: train tss = 0.7070 : val tss = 0.6777 ::: train hss = 0.2540 : val hss = 0.2521
Fold 3: train tss = 0.7765 : val tss = 0.1299 ::: train hss = 0.2880 : val hss = 0.0211
Fold 4: train tss = 0.7118 : val tss = 0.5719 ::: train hss = 0.1685 : val hss = 0.2622
mean cv TSS: 0.3605
mean cv HSS: 0.1409
264/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9216 : val tss = 0.0284 ::: train hss = 0.1341 : val hss = 0.0193
Fold 1: train tss = 0.8256 : val tss = 0.4108 ::: train hss = 0.3046 : val hss = 0.1515
Fold 2: train tss = 0.7630 : val tss = 0.7097 ::: train hss = 0.2447 : val hss = 0.2924
Fold 3: train tss = 0.7849 : val tss = 0.0869 ::: train hss = 0.2688 : val hss = 0.0215
Fold 4: train tss = 0.7670 : val tss = 0.6831 ::: train hss = 0.2437 : val hss = 0.2705
mean cv TSS: 0.3838
mean cv HSS: 0.1510
265/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.3370 : val tss = 0.3165 ::: train hss = 0.0999 : val hss = 0.1831
Fold 1: train tss = 0.7683 : val tss = 0.4264 ::: train hss = 0.4337 : val hss = 0.1993
Fold 2: train tss = 0.6892 : val tss = 0.6946 ::: train hss = 0.1839 : val hss = 0.2703
Fold 3: train tss = 0.7208 : val tss = 0.1571 ::: train hss = 0.2186 : val hss = 0.0286
Fold 4: train tss = 0.7048 : val tss = 0.6757 ::: train hss = 0.1948 : val hss = 0.2454
mean cv TSS: 0.4541
mean cv HSS: 0.1853
266/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.6649 : val tss = 0.0508 ::: train hss = 0.0816 : val hss = 0.0292
Fold 1: train tss = 0.8997 : val tss = 0.4308 ::: train hss = 0.3842 : val hss = 0.1668
Fold 2: train tss = 0.7736 : val tss = 0.6715 ::: train hss = 0.2653 : val hss = 0.2900
Fold 3: train tss = 0.7267 : val tss = 0.0982 ::: train hss = 0.2029 : val hss = 0.0212
Fold 4: train tss = 0.7922 : val tss = 0.6959 ::: train hss = 0.2721 : val hss = 0.2824
mean cv TSS: 0.3894
mean cv HSS: 0.1579
267/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5306 : val tss = 0.3305 ::: train hss = 0.1105 : val hss = 0.1686
Fold 1: train tss = 0.7693 : val tss = 0.4166 ::: train hss = 0.3704 : val hss = 0.1222
Fold 2: train tss = 0.7344 : val tss = 0.7163 ::: train hss = 0.2065 : val hss = 0.2880
Fold 3: train tss = 0.7632 : val tss = 0.1515 ::: train hss = 0.2937 : val hss = 0.0323
Fold 4: train tss = 0.7177 : val tss = 0.7011 ::: train hss = 0.1894 : val hss = 0.3046
mean cv TSS: 0.4632
mean cv HSS: 0.1831
268/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5801 : val tss = -0.0261 ::: train hss = 0.1178 : val hss = -0.0169
Fold 1: train tss = 0.8674 : val tss = 0.2998 ::: train hss = 0.4323 : val hss = 0.1224
Fold 2: train tss = 0.7789 : val tss = 0.7119 ::: train hss = 0.2104 : val hss = 0.3298
Fold 3: train tss = 0.8373 : val tss = 0.0446 ::: train hss = 0.3352 : val hss = 0.0105
Fold 4: train tss = 0.8084 : val tss = 0.6951 ::: train hss = 0.2950 : val hss = 0.3097
mean cv TSS: 0.3451
mean cv HSS: 0.1511
269/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5841 : val tss = 0.2655 ::: train hss = 0.1425 : val hss = 0.1303
Fold 1: train tss = 0.7685 : val tss = 0.4026 ::: train hss = 0.3648 : val hss = 0.1195
Fold 2: train tss = 0.7379 : val tss = 0.6499 ::: train hss = 0.2044 : val hss = 0.2276
Fold 3: train tss = 0.7657 : val tss = 0.1611 ::: train hss = 0.2829 : val hss = 0.0344
Fold 4: train tss = 0.7464 : val tss = 0.7108 ::: train hss = 0.2472 : val hss = 0.3191
mean cv TSS: 0.4380
mean cv HSS: 0.1662
270/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8244 : val tss = 0.2768 ::: train hss = 0.1319 : val hss = 0.1980
Fold 1: train tss = 0.8458 : val tss = 0.3366 ::: train hss = 0.2682 : val hss = 0.1446
Fold 2: train tss = 0.7652 : val tss = 0.7207 ::: train hss = 0.2064 : val hss = 0.3318
Fold 3: train tss = 0.8162 : val tss = 0.1876 ::: train hss = 0.3013 : val hss = 0.0371
Fold 4: train tss = 0.7895 : val tss = 0.6598 ::: train hss = 0.2384 : val hss = 0.2648
mean cv TSS: 0.4363
mean cv HSS: 0.1953
271/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.4411 : val tss = 0.0897 ::: train hss = 0.1713 : val hss = 0.1055
Fold 1: train tss = 0.7469 : val tss = 0.4238 ::: train hss = 0.3351 : val hss = 0.1669
Fold 2: train tss = 0.6865 : val tss = 0.6569 ::: train hss = 0.1915 : val hss = 0.2327
Fold 3: train tss = 0.7263 : val tss = 0.4156 ::: train hss = 0.2185 : val hss = 0.0616
Fold 4: train tss = 0.7098 : val tss = 0.6849 ::: train hss = 0.1985 : val hss = 0.2582
mean cv TSS: 0.4542
mean cv HSS: 0.1649
272/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.5665 : val tss = -0.0291 ::: train hss = 0.0731 : val hss = -0.0115
Fold 1: train tss = 0.8626 : val tss = 0.3024 ::: train hss = 0.4279 : val hss = 0.1105
Fold 2: train tss = 0.8219 : val tss = 0.7006 ::: train hss = 0.2275 : val hss = 0.2985
Fold 3: train tss = 0.8401 : val tss = 0.0940 ::: train hss = 0.3850 : val hss = 0.0249
Fold 4: train tss = 0.7335 : val tss = 0.6856 ::: train hss = 0.1742 : val hss = 0.3519
mean cv TSS: 0.3507
mean cv HSS: 0.1548
273/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 4367
Fold 0: train tss = 0.1204 : val tss = 0.2737 ::: train hss = 0.0179 : val hss = 0.1548
Fold 1: train tss = 0.7583 : val tss = 0.4381 ::: train hss = 0.3839 : val hss = 0.1731
Fold 2: train tss = 0.7209 : val tss = 0.6683 ::: train hss = 0.2512 : val hss = 0.2440
Fold 3: train tss = 0.7549 : val tss = 0.2061 ::: train hss = 0.2950 : val hss = 0.0438
Fold 4: train tss = 0.7480 : val tss = 0.6564 ::: train hss = 0.2911 : val hss = 0.2558
mean cv TSS: 0.4485
mean cv HSS: 0.1743
274/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9130 : val tss = 0.0864 ::: train hss = 0.1056 : val hss = 0.0290
Fold 1: train tss = 0.9037 : val tss = 0.2965 ::: train hss = 0.3145 : val hss = 0.1037
Fold 2: train tss = 0.8026 : val tss = 0.6779 ::: train hss = 0.2376 : val hss = 0.3556
Fold 3: train tss = 0.8294 : val tss = 0.1290 ::: train hss = 0.3145 : val hss = 0.0249
Fold 4: train tss = 0.8164 : val tss = 0.7300 ::: train hss = 0.3063 : val hss = 0.3525
mean cv TSS: 0.3840
mean cv HSS: 0.1732
275/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.1798 : val tss = -0.0211 ::: train hss = 0.0375 : val hss = -0.0186
Fold 1: train tss = 0.7947 : val tss = 0.4132 ::: train hss = 0.3417 : val hss = 0.1597
Fold 2: train tss = 0.7062 : val tss = 0.5939 ::: train hss = 0.1623 : val hss = 0.1888
Fold 3: train tss = 0.7692 : val tss = 0.2863 ::: train hss = 0.2648 : val hss = 0.0495
Fold 4: train tss = 0.7531 : val tss = 0.6585 ::: train hss = 0.2730 : val hss = 0.2485
mean cv TSS: 0.3862
mean cv HSS: 0.1256
276/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8307 : val tss = -0.0171 ::: train hss = 0.1687 : val hss = -0.0136
Fold 1: train tss = 0.7936 : val tss = 0.3730 ::: train hss = 0.2342 : val hss = 0.1352
Fold 2: train tss = 0.7464 : val tss = 0.6909 ::: train hss = 0.2185 : val hss = 0.2629
Fold 3: train tss = 0.7669 : val tss = 0.1316 ::: train hss = 0.2609 : val hss = 0.0242
Fold 4: train tss = 0.6947 : val tss = 0.6560 ::: train hss = 0.1724 : val hss = 0.2605
mean cv TSS: 0.3668
mean cv HSS: 0.1338
277/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.2919 : val tss = 0.3448 ::: train hss = 0.1256 : val hss = 0.2529
Fold 1: train tss = 0.7656 : val tss = 0.3505 ::: train hss = 0.3211 : val hss = 0.1830
Fold 2: train tss = 0.6706 : val tss = 0.5877 ::: train hss = 0.1536 : val hss = 0.1774
Fold 3: train tss = 0.6679 : val tss = 0.3695 ::: train hss = 0.1626 : val hss = 0.0364
Fold 4: train tss = 0.6682 : val tss = 0.6940 ::: train hss = 0.1671 : val hss = 0.2517
mean cv TSS: 0.4693
mean cv HSS: 0.1803
278/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8070 : val tss = 0.0503 ::: train hss = 0.0819 : val hss = 0.0257
Fold 1: train tss = 0.7276 : val tss = 0.3385 ::: train hss = 0.1210 : val hss = 0.0970
Fold 2: train tss = 0.7300 : val tss = 0.6602 ::: train hss = 0.1330 : val hss = 0.2357
Fold 3: train tss = 0.7613 : val tss = 0.1430 ::: train hss = 0.2395 : val hss = 0.0330
Fold 4: train tss = 0.7535 : val tss = 0.6390 ::: train hss = 0.2143 : val hss = 0.2283
mean cv TSS: 0.3662
mean cv HSS: 0.1239
279/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.3912 : val tss = 0.3477 ::: train hss = 0.1549 : val hss = 0.1808
Fold 1: train tss = 0.7688 : val tss = 0.4291 ::: train hss = 0.3395 : val hss = 0.1401
Fold 2: train tss = 0.6874 : val tss = 0.6823 ::: train hss = 0.2281 : val hss = 0.2521
Fold 3: train tss = 0.7152 : val tss = 0.1665 ::: train hss = 0.2016 : val hss = 0.0402
Fold 4: train tss = 0.7161 : val tss = 0.7031 ::: train hss = 0.2094 : val hss = 0.3108
mean cv TSS: 0.4657
mean cv HSS: 0.1848
280/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.3869 : val tss = -0.0152 ::: train hss = 0.1130 : val hss = -0.0125
Fold 1: train tss = 0.8111 : val tss = 0.3058 ::: train hss = 0.2963 : val hss = 0.1678
Fold 2: train tss = 0.7289 : val tss = 0.6128 ::: train hss = 0.1482 : val hss = 0.1974
Fold 3: train tss = 0.8016 : val tss = 0.1049 ::: train hss = 0.3036 : val hss = 0.0207
Fold 4: train tss = 0.7717 : val tss = 0.6899 ::: train hss = 0.2301 : val hss = 0.2774
mean cv TSS: 0.3397
mean cv HSS: 0.1302
281/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6109 : val tss = 0.2240 ::: train hss = 0.0683 : val hss = 0.0531
Fold 1: train tss = 0.7159 : val tss = 0.3648 ::: train hss = 0.1280 : val hss = 0.0756
Fold 2: train tss = 0.7163 : val tss = 0.6555 ::: train hss = 0.1666 : val hss = 0.2306
Fold 3: train tss = 0.7352 : val tss = 0.2016 ::: train hss = 0.2442 : val hss = 0.0324
Fold 4: train tss = 0.6667 : val tss = 0.6659 ::: train hss = 0.1370 : val hss = 0.2524
mean cv TSS: 0.4224
mean cv HSS: 0.1288
282/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7718 : val tss = 0.3181 ::: train hss = 0.1143 : val hss = 0.1875
Fold 1: train tss = 0.8486 : val tss = 0.3417 ::: train hss = 0.3586 : val hss = 0.1258
Fold 2: train tss = 0.7311 : val tss = 0.6644 ::: train hss = 0.1914 : val hss = 0.2455
Fold 3: train tss = 0.7953 : val tss = 0.0684 ::: train hss = 0.2856 : val hss = 0.0126
Fold 4: train tss = 0.7298 : val tss = 0.6476 ::: train hss = 0.1972 : val hss = 0.2454
mean cv TSS: 0.4080
mean cv HSS: 0.1634
283/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.2454 : val tss = 0.2215 ::: train hss = 0.1558 : val hss = 0.2066
Fold 1: train tss = 0.7541 : val tss = 0.4123 ::: train hss = 0.4214 : val hss = 0.1807
Fold 2: train tss = 0.6761 : val tss = 0.6459 ::: train hss = 0.1454 : val hss = 0.2250
Fold 3: train tss = 0.6760 : val tss = 0.3868 ::: train hss = 0.1763 : val hss = 0.0474

Fold 4: train tss = 0.6372 : val tss = 0.6721 ::: train hss = 0.1414 : val hss = 0.2365
mean cv TSS: 0.4677
mean cv HSS: 0.1793
284/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9216 : val tss = 0.1386 ::: train hss = 0.1341 : val hss = 0.0985
Fold 1: train tss = 0.8939 : val tss = 0.1959 ::: train hss = 0.3497 : val hss = 0.0716
Fold 2: train tss = 0.7633 : val tss = 0.6791 ::: train hss = 0.2454 : val hss = 0.2523
Fold 3: train tss = 0.7749 : val tss = 0.1199 ::: train hss = 0.2416 : val hss = 0.0483
Fold 4: train tss = 0.7681 : val tss = 0.6570 ::: train hss = 0.2249 : val hss = 0.2443
mean cv TSS: 0.3581
mean cv HSS: 0.1430
285/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0889 : val tss = 0.3583 ::: train hss = 0.0312 : val hss = 0.2385
Fold 1: train tss = 0.7679 : val tss = 0.3019 ::: train hss = 0.3924 : val hss = 0.1404
Fold 2: train tss = 0.6731 : val tss = 0.6722 ::: train hss = 0.2038 : val hss = 0.2447
Fold 3: train tss = 0.7116 : val tss = 0.1844 ::: train hss = 0.2900 : val hss = 0.0269
Fold 4: train tss = 0.7194 : val tss = 0.6197 ::: train hss = 0.2640 : val hss = 0.1954
mean cv TSS: 0.4273
mean cv HSS: 0.1692
286/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7089 : val tss = -0.0137 ::: train hss = 0.0754 : val hss = -0.0115
Fold 1: train tss = 0.8510 : val tss = 0.2476 ::: train hss = 0.4394 : val hss = 0.1066
Fold 2: train tss = 0.8017 : val tss = 0.7302 ::: train hss = 0.2327 : val hss = 0.3333
Fold 3: train tss = 0.8376 : val tss = 0.1181 ::: train hss = 0.4016 : val hss = 0.0258
Fold 4: train tss = 0.7611 : val tss = 0.6276 ::: train hss = 0.2926 : val hss = 0.2265
mean cv TSS: 0.3420
mean cv HSS: 0.1361
287/864
{'batch_size': 128, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.8272 : val tss = -0.0656 ::: train hss = 0.0515 : val hss = -0.0280
Fold 1: train tss = 0.8325 : val tss = 0.2804 ::: train hss = 0.2979 : val hss = 0.1110
Fold 2: train tss = 0.7168 : val tss = 0.6931 ::: train hss = 0.2418 : val hss = 0.2688
Fold 3: train tss = 0.7380 : val tss = 0.1763 ::: train hss = 0.2399 : val hss = 0.0287
Fold 4: train tss = 0.7255 : val tss = 0.6640 ::: train hss = 0.2552 : val hss = 0.2223
mean cv TSS: 0.3496
mean cv HSS: 0.1206
288/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5345 : val tss = 0.3216 ::: train hss = 0.1336 : val hss = 0.1579
Fold 1: train tss = 0.7731 : val tss = 0.2988 ::: train hss = 0.2473 : val hss = 0.1393
Fold 2: train tss = 0.7112 : val tss = 0.5586 ::: train hss = 0.1310 : val hss = 0.1702
Fold 3: train tss = 0.7145 : val tss = 0.1220 ::: train hss = 0.1738 : val hss = 0.0189
Fold 4: train tss = 0.7056 : val tss = 0.6650 ::: train hss = 0.1543 : val hss = 0.2363
mean cv TSS: 0.3932
mean cv HSS: 0.1445
289/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.7164 : val tss = -0.0167 ::: train hss = 0.0913 : val hss = -0.0107
Fold 1: train tss = 0.7643 : val tss = 0.3693 ::: train hss = 0.2935 : val hss = 0.1542
Fold 2: train tss = 0.6802 : val tss = 0.5761 ::: train hss = 0.1276 : val hss = 0.1792
Fold 3: train tss = 0.6934 : val tss = 0.3908 ::: train hss = 0.1609 : val hss = 0.0403
Fold 4: train tss = 0.6827 : val tss = 0.6586 ::: train hss = 0.1440 : val hss = 0.2188
mean cv TSS: 0.3956
mean cv HSS: 0.1164
290/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0002 : val hss = 0.0000
Fold 1: train tss = 0.8289 : val tss = 0.4616 ::: train hss = 0.3006 : val hss = 0.1518
Fold 2: train tss = 0.7299 : val tss = 0.6063 ::: train hss = 0.1549 : val hss = 0.2030
Fold 3: train tss = 0.7123 : val tss = 0.3378 ::: train hss = 0.1687 : val hss = 0.0408
Fold 4: train tss = 0.7248 : val tss = 0.6649 ::: train hss = 0.1776 : val hss = 0.2584
mean cv TSS: 0.4141
mean cv HSS: 0.1308
291/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.4194 : val tss = 0.4132 ::: train hss = 0.0593 : val hss = 0.1758
Fold 1: train tss = 0.7767 : val tss = 0.4606 ::: train hss = 0.2751 : val hss = 0.1804
Fold 2: train tss = 0.7259 : val tss = 0.6298 ::: train hss = 0.1634 : val hss = 0.2069
Fold 3: train tss = 0.7008 : val tss = 0.4255 ::: train hss = 0.1744 : val hss = 0.0468
Fold 4: train tss = 0.7133 : val tss = 0.6517 ::: train hss = 0.1749 : val hss = 0.2369
mean cv TSS: 0.5161
mean cv HSS: 0.1694
292/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4219 : val tss = 0.3313 ::: train hss = 0.0644 : val hss = 0.1618
Fold 1: train tss = 0.8074 : val tss = 0.3157 ::: train hss = 0.2165 : val hss = 0.1771
Fold 2: train tss = 0.6840 : val tss = 0.5397 ::: train hss = 0.1146 : val hss = 0.1620
Fold 3: train tss = 0.6847 : val tss = 0.2828 ::: train hss = 0.1484 : val hss = 0.0304
Fold 4: train tss = 0.6894 : val tss = 0.6313 ::: train hss = 0.1422 : val hss = 0.2138
mean cv TSS: 0.4202
mean cv HSS: 0.1490
293/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0888 : val tss = 0.3920 ::: train hss = 0.0309 : val hss = 0.2541
Fold 1: train tss = 0.7586 : val tss = 0.4004 ::: train hss = 0.3556 : val hss = 0.1362
Fold 2: train tss = 0.6797 : val tss = 0.6400 ::: train hss = 0.1585 : val hss = 0.2202
Fold 3: train tss = 0.6937 : val tss = 0.2087 ::: train hss = 0.1653 : val hss = 0.0251
Fold 4: train tss = 0.7268 : val tss = 0.5961 ::: train hss = 0.1840 : val hss = 0.1905
mean cv TSS: 0.4474
mean cv HSS: 0.1652
294/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 237
Fold 0: train tss = 0.7744 : val tss = 0.2523 ::: train hss = 0.1244 : val hss = 0.1094
Fold 1: train tss = 0.8337 : val tss = 0.2776 ::: train hss = 0.2209 : val hss = 0.1317
Fold 2: train tss = 0.7168 : val tss = 0.6209 ::: train hss = 0.1482 : val hss = 0.1973
Fold 3: train tss = 0.7356 : val tss = 0.2715 ::: train hss = 0.2154 : val hss = 0.0353
Fold 4: train tss = 0.7139 : val tss = 0.6221 ::: train hss = 0.1599 : val hss = 0.2254
mean cv TSS: 0.4089
mean cv HSS: 0.1398
295/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7608 : val tss = 0.3606 ::: train hss = 0.3181 : val hss = 0.1645
Fold 2: train tss = 0.7160 : val tss = 0.6498 ::: train hss = 0.1578 : val hss = 0.2303
Fold 3: train tss = 0.7058 : val tss = 0.2234 ::: train hss = 0.1850 : val hss = 0.0275
Fold 4: train tss = 0.6915 : val tss = 0.6296 ::: train hss = 0.1499 : val hss = 0.2142
mean cv TSS: 0.3727
mean cv HSS: 0.1273
296/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7752 : val tss = 0.3768 ::: train hss = 0.1985 : val hss = 0.1141
Fold 2: train tss = 0.7392 : val tss = 0.6444 ::: train hss = 0.1678 : val hss = 0.2311
Fold 3: train tss = 0.7817 : val tss = 0.4319 ::: train hss = 0.2481 : val hss = 0.0969
Fold 4: train tss = 0.7256 : val tss = 0.5049 ::: train hss = 0.2109 : val hss = 0.2443
mean cv TSS: 0.3916
mean cv HSS: 0.1373
297/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7668 : val tss = 0.3540 ::: train hss = 0.3538 : val hss = 0.1252
Fold 2: train tss = 0.7324 : val tss = 0.6164 ::: train hss = 0.1621 : val hss = 0.1963
Fold 3: train tss = 0.7261 : val tss = 0.2362 ::: train hss = 0.2016 : val hss = 0.0375
Fold 4: train tss = 0.7334 : val tss = 0.6441 ::: train hss = 0.1985 : val hss = 0.2362
mean cv TSS: 0.3701
mean cv HSS: 0.1190
298/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.7273 : val tss = -0.0877 ::: train hss = 0.0455 : val hss = -0.0327
Fold 1: train tss = 0.7935 : val tss = 0.4143 ::: train hss = 0.4272 : val hss = 0.1733
Fold 2: train tss = 0.7374 : val tss = 0.6530 ::: train hss = 0.1711 : val hss = 0.2257
Fold 3: train tss = 0.7410 : val tss = 0.3759 ::: train hss = 0.1919 : val hss = 0.0522
Fold 4: train tss = 0.7423 : val tss = 0.6341 ::: train hss = 0.1909 : val hss = 0.2653
mean cv TSS: 0.3979
mean cv HSS: 0.1368
299/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7513 : val tss = 0.4100 ::: train hss = 0.2088 : val hss = 0.0939
Fold 2: train tss = 0.6872 : val tss = 0.5483 ::: train hss = 0.1203 : val hss = 0.1529
Fold 3: train tss = 0.7568 : val tss = 0.2055 ::: train hss = 0.2423 : val hss = 0.0469
Fold 4: train tss = 0.7347 : val tss = 0.6646 ::: train hss = 0.1843 : val hss = 0.2681
mean cv TSS: 0.3657
mean cv HSS: 0.1124
300/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.6792 : val tss = 0.1401 ::: train hss = 0.1312 : val hss = 0.0782
Fold 1: train tss = 0.8119 : val tss = 0.3335 ::: train hss = 0.2821 : val hss = 0.1408
Fold 2: train tss = 0.6967 : val tss = 0.4959 ::: train hss = 0.1180 : val hss = 0.1217
Fold 3: train tss = 0.7341 : val tss = 0.2682 ::: train hss = 0.1890 : val hss = 0.0464
Fold 4: train tss = 0.7055 : val tss = 0.6115 ::: train hss = 0.1524 : val hss = 0.2006
mean cv TSS: 0.3698
mean cv HSS: 0.1175
301/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.5292 : val tss = -0.0034 ::: train hss = 0.1038 : val hss = -0.0024
Fold 1: train tss = 0.7553 : val tss = 0.3718 ::: train hss = 0.2570 : val hss = 0.1637
Fold 2: train tss = 0.6694 : val tss = 0.5203 ::: train hss = 0.1161 : val hss = 0.1385
Fold 3: train tss = 0.6850 : val tss = 0.2893 ::: train hss = 0.1693 : val hss = 0.0319
Fold 4: train tss = 0.6506 : val tss = 0.5695 ::: train hss = 0.1271 : val hss = 0.1507
mean cv TSS: 0.3495
mean cv HSS: 0.0965
302/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5799 : val tss = 0.3247 ::: train hss = 0.1166 : val hss = 0.1360
Fold 1: train tss = 0.7080 : val tss = 0.2950 ::: train hss = 0.1927 : val hss = 0.1432
Fold 2: train tss = 0.7072 : val tss = 0.6143 ::: train hss = 0.1337 : val hss = 0.1948
Fold 3: train tss = 0.6781 : val tss = 0.4177 ::: train hss = 0.1328 : val hss = 0.0389
Fold 4: train tss = 0.6950 : val tss = 0.6565 ::: train hss = 0.1352 : val hss = 0.2509
mean cv TSS: 0.4617
mean cv HSS: 0.1528
303/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.5345 : val tss = 0.3293 ::: train hss = 0.1336 : val hss = 0.1503
Fold 1: train tss = 0.7708 : val tss = 0.4336 ::: train hss = 0.2070 : val hss = 0.1134
Fold 2: train tss = 0.6801 : val tss = 0.5960 ::: train hss = 0.1265 : val hss = 0.1828
Fold 3: train tss = 0.6947 : val tss = 0.2296 ::: train hss = 0.1671 : val hss = 0.0258
Fold 4: train tss = 0.6256 : val tss = 0.5947 ::: train hss = 0.1124 : val hss = 0.1800
mean cv TSS: 0.4366
mean cv HSS: 0.1305
304/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.7645 : val tss = 0.2109 ::: train hss = 0.0924 : val hss = 0.0718
Fold 1: train tss = 0.8024 : val tss = 0.3084 ::: train hss = 0.1813 : val hss = 0.1320
Fold 2: train tss = 0.7175 : val tss = 0.6135 ::: train hss = 0.1434 : val hss = 0.1950
Fold 3: train tss = 0.7070 : val tss = 0.4503 ::: train hss = 0.1491 : val hss = 0.0414

Fold 4: train tss = 0.7102 : val tss = 0.5598 ::: train hss = 0.1494 : val hss = 0.1633
mean cv TSS: 0.4286
mean cv HSS: 0.1207
305/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.5354 : val tss = 0.1817 ::: train hss = 0.1409 : val hss = 0.0917
Fold 1: train tss = 0.7700 : val tss = 0.3530 ::: train hss = 0.1327 : val hss = 0.0989
Fold 2: train tss = 0.7246 : val tss = 0.6126 ::: train hss = 0.1557 : val hss = 0.1923
Fold 3: train tss = 0.6584 : val tss = 0.2855 ::: train hss = 0.1253 : val hss = 0.0254
Fold 4: train tss = 0.6817 : val tss = 0.6316 ::: train hss = 0.1603 : val hss = 0.2113
mean cv TSS: 0.4129
mean cv HSS: 0.1239
306/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.6498 : val tss = 0.2895 ::: train hss = 0.0576 : val hss = 0.0719
Fold 1: train tss = 0.8275 : val tss = 0.3521 ::: train hss = 0.2159 : val hss = 0.1774
Fold 2: train tss = 0.7218 : val tss = 0.5925 ::: train hss = 0.1445 : val hss = 0.1780
Fold 3: train tss = 0.7433 : val tss = 0.0253 ::: train hss = 0.1940 : val hss = 0.0038
Fold 4: train tss = 0.7212 : val tss = 0.6234 ::: train hss = 0.1629 : val hss = 0.2184
mean cv TSS: 0.3766
mean cv HSS: 0.1299
307/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7484 : val tss = 0.3771 ::: train hss = 0.2225 : val hss = 0.1211
Fold 2: train tss = 0.6861 : val tss = 0.5322 ::: train hss = 0.1310 : val hss = 0.1446
Fold 3: train tss = 0.6197 : val tss = 0.3516 ::: train hss = 0.1184 : val hss = 0.0254
Fold 4: train tss = 0.6818 : val tss = 0.6064 ::: train hss = 0.1429 : val hss = 0.1866
mean cv TSS: 0.3734
mean cv HSS: 0.0955
308/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.5713 : val tss = 0.2395 ::: train hss = 0.0333 : val hss = 0.0568
Fold 1: train tss = 0.7797 : val tss = 0.1747 ::: train hss = 0.2553 : val hss = 0.0579
Fold 2: train tss = 0.7728 : val tss = 0.5346 ::: train hss = 0.1655 : val hss = 0.1604
Fold 3: train tss = 0.7508 : val tss = 0.1326 ::: train hss = 0.2082 : val hss = 0.0394
Fold 4: train tss = 0.7522 : val tss = 0.6273 ::: train hss = 0.2010 : val hss = 0.1955
mean cv TSS: 0.3418
mean cv HSS: 0.1020
309/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7620 : val tss = 0.4113 ::: train hss = 0.3501 : val hss = 0.1661
Fold 2: train tss = 0.7025 : val tss = 0.5710 ::: train hss = 0.1421 : val hss = 0.1664
Fold 3: train tss = 0.7242 : val tss = 0.2518 ::: train hss = 0.1800 : val hss = 0.0312
Fold 4: train tss = 0.6406 : val tss = 0.6433 ::: train hss = 0.1118 : val hss = 0.2092
mean cv TSS: 0.3755
mean cv HSS: 0.1146
310/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.6411 : val tss = -0.0508 ::: train hss = 0.0273 : val hss = -0.0146
Fold 1: train tss = 0.8059 : val tss = 0.3314 ::: train hss = 0.2342 : val hss = 0.0794
Fold 2: train tss = 0.7637 : val tss = 0.6833 ::: train hss = 0.2043 : val hss = 0.2598
Fold 3: train tss = 0.7072 : val tss = 0.0769 ::: train hss = 0.1820 : val hss = 0.0174
Fold 4: train tss = 0.7599 : val tss = 0.6939 ::: train hss = 0.2220 : val hss = 0.3249
mean cv TSS: 0.3470
mean cv HSS: 0.1334
311/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7727 : val tss = 0.3574 ::: train hss = 0.3967 : val hss = 0.2064
Fold 2: train tss = 0.7249 : val tss = 0.6532 ::: train hss = 0.1530 : val hss = 0.2277
Fold 3: train tss = 0.6679 : val tss = 0.2837 ::: train hss = 0.1406 : val hss = 0.0259
Fold 4: train tss = 0.7434 : val tss = 0.6441 ::: train hss = 0.2005 : val hss = 0.2343
mean cv TSS: 0.3877
mean cv HSS: 0.1389
312/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7252 : val tss = 0.3044 ::: train hss = 0.1204 : val hss = 0.1543
Fold 1: train tss = 0.8126 : val tss = 0.3450 ::: train hss = 0.2848 : val hss = 0.1438
Fold 2: train tss = 0.7670 : val tss = 0.6411 ::: train hss = 0.1726 : val hss = 0.2254
Fold 3: train tss = 0.7380 : val tss = 0.3057 ::: train hss = 0.1882 : val hss = 0.0452
Fold 4: train tss = 0.7334 : val tss = 0.6192 ::: train hss = 0.1763 : val hss = 0.2139
mean cv TSS: 0.4431
mean cv HSS: 0.1565
313/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.7669 : val tss = 0.3212 ::: train hss = 0.0986 : val hss = 0.1745
Fold 1: train tss = 0.7623 : val tss = 0.3905 ::: train hss = 0.3517 : val hss = 0.1667
Fold 2: train tss = 0.6884 : val tss = 0.5990 ::: train hss = 0.1251 : val hss = 0.1855
Fold 3: train tss = 0.7058 : val tss = 0.1556 ::: train hss = 0.1736 : val hss = 0.0215
Fold 4: train tss = 0.6883 : val tss = 0.5952 ::: train hss = 0.1506 : val hss = 0.1854
mean cv TSS: 0.4123
mean cv HSS: 0.1467
314/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7261 : val tss = 0.2467 ::: train hss = 0.1241 : val hss = 0.1116
Fold 1: train tss = 0.8608 : val tss = 0.3593 ::: train hss = 0.2174 : val hss = 0.1004
Fold 2: train tss = 0.7194 : val tss = 0.5877 ::: train hss = 0.1351 : val hss = 0.1744
Fold 3: train tss = 0.7478 : val tss = 0.1295 ::: train hss = 0.1965 : val hss = 0.0172
Fold 4: train tss = 0.7353 : val tss = 0.7071 ::: train hss = 0.1874 : val hss = 0.2841
mean cv TSS: 0.4061
mean cv HSS: 0.1375
315/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 379
Fold 0: train tss = 0.3764 : val tss = 0.3354 ::: train hss = 0.0672 : val hss = 0.1475
Fold 1: train tss = 0.8134 : val tss = 0.4350 ::: train hss = 0.2026 : val hss = 0.1335
Fold 2: train tss = 0.7477 : val tss = 0.6631 ::: train hss = 0.1759 : val hss = 0.2443
Fold 3: train tss = 0.7354 : val tss = 0.2293 ::: train hss = 0.2050 : val hss = 0.0369
Fold 4: train tss = 0.7332 : val tss = 0.6523 ::: train hss = 0.1905 : val hss = 0.2503
mean cv TSS: 0.4630
mean cv HSS: 0.1625
316/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.9141 : val tss = 0.2659 ::: train hss = 0.1085 : val hss = 0.0766
Fold 1: train tss = 0.8396 : val tss = 0.4184 ::: train hss = 0.2362 : val hss = 0.1406
Fold 2: train tss = 0.7379 : val tss = 0.6667 ::: train hss = 0.1899 : val hss = 0.2543
Fold 3: train tss = 0.7212 : val tss = 0.4403 ::: train hss = 0.1692 : val hss = 0.0561
Fold 4: train tss = 0.7513 : val tss = 0.6729 ::: train hss = 0.2015 : val hss = 0.2319
mean cv TSS: 0.4928
mean cv HSS: 0.1519
317/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.6274 : val tss = 0.2341 ::: train hss = 0.1135 : val hss = 0.1426
Fold 1: train tss = 0.8296 : val tss = 0.3619 ::: train hss = 0.2430 : val hss = 0.0996
Fold 2: train tss = 0.7479 : val tss = 0.6821 ::: train hss = 0.1638 : val hss = 0.2575
Fold 3: train tss = 0.7056 : val tss = 0.2370 ::: train hss = 0.1741 : val hss = 0.0298
Fold 4: train tss = 0.7374 : val tss = 0.6649 ::: train hss = 0.1864 : val hss = 0.2603
mean cv TSS: 0.4360
mean cv HSS: 0.1580
318/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8761 : val tss = 0.3041 ::: train hss = 0.1479 : val hss = 0.1219
Fold 1: train tss = 0.8318 : val tss = 0.3602 ::: train hss = 0.3140 : val hss = 0.1231
Fold 2: train tss = 0.6962 : val tss = 0.5998 ::: train hss = 0.1244 : val hss = 0.1922
Fold 3: train tss = 0.7926 : val tss = 0.0702 ::: train hss = 0.2453 : val hss = 0.0140
Fold 4: train tss = 0.7714 : val tss = 0.6599 ::: train hss = 0.1988 : val hss = 0.2507
mean cv TSS: 0.3988
mean cv HSS: 0.1404
319/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.6785 : val tss = 0.2146 ::: train hss = 0.1274 : val hss = 0.0915
Fold 1: train tss = 0.7686 : val tss = 0.3250 ::: train hss = 0.2762 : val hss = 0.1333
Fold 2: train tss = 0.7140 : val tss = 0.5925 ::: train hss = 0.1542 : val hss = 0.1799
Fold 3: train tss = 0.7381 : val tss = 0.2281 ::: train hss = 0.2004 : val hss = 0.0300
Fold 4: train tss = 0.6960 : val tss = 0.6247 ::: train hss = 0.1585 : val hss = 0.2015
mean cv TSS: 0.3970
mean cv HSS: 0.1272
320/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.9501 : val tss = 0.2054 ::: train hss = 0.0835 : val hss = 0.0750
Fold 1: train tss = 0.8294 : val tss = 0.2553 ::: train hss = 0.1796 : val hss = 0.0970
Fold 2: train tss = 0.7822 : val tss = 0.6769 ::: train hss = 0.1959 : val hss = 0.2683
Fold 3: train tss = 0.7774 : val tss = 0.1167 ::: train hss = 0.2196 : val hss = 0.0235
Fold 4: train tss = 0.7991 : val tss = 0.6448 ::: train hss = 0.2361 : val hss = 0.2380
mean cv TSS: 0.3798
mean cv HSS: 0.1404
321/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8113 : val tss = 0.4240 ::: train hss = 0.1980 : val hss = 0.1280
Fold 2: train tss = 0.7182 : val tss = 0.5833 ::: train hss = 0.1651 : val hss = 0.1740
Fold 3: train tss = 0.7649 : val tss = 0.1628 ::: train hss = 0.2577 : val hss = 0.0381
Fold 4: train tss = 0.7544 : val tss = 0.6224 ::: train hss = 0.2105 : val hss = 0.2196
mean cv TSS: 0.3585
mean cv HSS: 0.1119
322/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.5698 : val tss = 0.2429 ::: train hss = 0.0805 : val hss = 0.0781
Fold 1: train tss = 0.8026 : val tss = 0.3593 ::: train hss = 0.2489 : val hss = 0.1088
Fold 2: train tss = 0.7676 : val tss = 0.6158 ::: train hss = 0.1810 : val hss = 0.2097
Fold 3: train tss = 0.8011 : val tss = 0.1365 ::: train hss = 0.3026 : val hss = 0.0350
Fold 4: train tss = 0.6846 : val tss = 0.6473 ::: train hss = 0.1397 : val hss = 0.2216
mean cv TSS: 0.4004
mean cv HSS: 0.1307
323/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = -0.0007 : val tss = 0.3778 ::: train hss = -0.0011 : val hss = 0.3118
Fold 1: train tss = 0.7842 : val tss = 0.4311 ::: train hss = 0.2308 : val hss = 0.1870
Fold 2: train tss = 0.7236 : val tss = 0.6233 ::: train hss = 0.1594 : val hss = 0.2014
Fold 3: train tss = 0.7009 : val tss = 0.1224 ::: train hss = 0.1735 : val hss = 0.0139
Fold 4: train tss = 0.7152 : val tss = 0.6557 ::: train hss = 0.2108 : val hss = 0.2259
mean cv TSS: 0.4420
mean cv HSS: 0.1880
324/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7276 : val tss = 0.0783 ::: train hss = 0.1317 : val hss = 0.0490
Fold 1: train tss = 0.8226 : val tss = 0.3196 ::: train hss = 0.2468 : val hss = 0.0934
Fold 2: train tss = 0.7579 : val tss = 0.6295 ::: train hss = 0.1846 : val hss = 0.2067
Fold 3: train tss = 0.7659 : val tss = 0.2027 ::: train hss = 0.2152 : val hss = 0.0392
Fold 4: train tss = 0.7180 : val tss = 0.5847 ::: train hss = 0.1638 : val hss = 0.1839
mean cv TSS: 0.3629
mean cv HSS: 0.1144
325/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4708 : val tss = 0.3277 ::: train hss = 0.0690 : val hss = 0.1348
Fold 1: train tss = 0.7536 : val tss = 0.3633 ::: train hss = 0.2832 : val hss = 0.1584
Fold 2: train tss = 0.6860 : val tss = 0.5591 ::: train hss = 0.1298 : val hss = 0.1588
Fold 3: train tss = 0.6863 : val tss = 0.3892 ::: train hss = 0.1624 : val hss = 0.0445

Fold 4: train tss = 0.6663 : val tss = 0.5964 ::: train hss = 0.1394 : val hss = 0.1719
mean cv TSS: 0.4471
mean cv HSS: 0.1337
326/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5788 : val tss = -0.0048 ::: train hss = 0.1113 : val hss = -0.0031
Fold 1: train tss = 0.8701 : val tss = 0.2754 ::: train hss = 0.2407 : val hss = 0.1025
Fold 2: train tss = 0.8039 : val tss = 0.5978 ::: train hss = 0.1809 : val hss = 0.2171
Fold 3: train tss = 0.7637 : val tss = 0.1497 ::: train hss = 0.2190 : val hss = 0.0184
Fold 4: train tss = 0.7420 : val tss = 0.6145 ::: train hss = 0.1713 : val hss = 0.2257
mean cv TSS: 0.3265
mean cv HSS: 0.1121
327/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5216 : val tss = 0.2834 ::: train hss = 0.0781 : val hss = 0.1293
Fold 1: train tss = 0.7922 : val tss = 0.3684 ::: train hss = 0.1774 : val hss = 0.1591
Fold 2: train tss = 0.7162 : val tss = 0.5687 ::: train hss = 0.1490 : val hss = 0.1655
Fold 3: train tss = 0.7065 : val tss = 0.2532 ::: train hss = 0.1693 : val hss = 0.0344
Fold 4: train tss = 0.7304 : val tss = 0.6599 ::: train hss = 0.1819 : val hss = 0.2496
mean cv TSS: 0.4267
mean cv HSS: 0.1476
328/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4790 : val tss = 0.1435 ::: train hss = 0.0939 : val hss = 0.0834
Fold 1: train tss = 0.8547 : val tss = 0.3692 ::: train hss = 0.2224 : val hss = 0.0946
Fold 2: train tss = 0.7679 : val tss = 0.6924 ::: train hss = 0.1576 : val hss = 0.2717
Fold 3: train tss = 0.7684 : val tss = 0.2032 ::: train hss = 0.2126 : val hss = 0.0395
Fold 4: train tss = 0.6200 : val tss = 0.4307 ::: train hss = 0.0942 : val hss = 0.0929
mean cv TSS: 0.3678
mean cv HSS: 0.1164
329/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5769 : val tss = -0.0237 ::: train hss = 0.1030 : val hss = -0.0124
Fold 1: train tss = 0.8249 : val tss = 0.2899 ::: train hss = 0.2539 : val hss = 0.1231
Fold 2: train tss = 0.7307 : val tss = 0.6332 ::: train hss = 0.1557 : val hss = 0.2146
Fold 3: train tss = 0.7315 : val tss = 0.2529 ::: train hss = 0.1873 : val hss = 0.0315
Fold 4: train tss = 0.6807 : val tss = 0.6447 ::: train hss = 0.1360 : val hss = 0.2371
mean cv TSS: 0.3594
mean cv HSS: 0.1188
330/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.7693 : val tss = 0.2858 ::: train hss = 0.1057 : val hss = 0.1119
Fold 1: train tss = 0.8269 : val tss = 0.3757 ::: train hss = 0.3105 : val hss = 0.1380
Fold 2: train tss = 0.7629 : val tss = 0.6295 ::: train hss = 0.1849 : val hss = 0.2014
Fold 3: train tss = 0.7582 : val tss = 0.0358 ::: train hss = 0.2029 : val hss = 0.0047
Fold 4: train tss = 0.7150 : val tss = 0.6222 ::: train hss = 0.1618 : val hss = 0.2213
mean cv TSS: 0.3898
mean cv HSS: 0.1355
331/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.8143 : val tss = 0.1298 ::: train hss = 0.0975 : val hss = 0.0769
Fold 1: train tss = 0.7479 : val tss = 0.4388 ::: train hss = 0.2210 : val hss = 0.1451
Fold 2: train tss = 0.6583 : val tss = 0.4800 ::: train hss = 0.1076 : val hss = 0.1175
Fold 3: train tss = 0.6742 : val tss = 0.3095 ::: train hss = 0.1524 : val hss = 0.0273
Fold 4: train tss = 0.6692 : val tss = 0.6190 ::: train hss = 0.1418 : val hss = 0.1918
mean cv TSS: 0.3954
mean cv HSS: 0.1117
332/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8925 : val tss = -0.0537 ::: train hss = 0.0383 : val hss = -0.0223
Fold 1: train tss = 0.8120 : val tss = 0.2901 ::: train hss = 0.4382 : val hss = 0.1427
Fold 2: train tss = 0.7333 : val tss = 0.5953 ::: train hss = 0.1344 : val hss = 0.1870
Fold 3: train tss = 0.7760 : val tss = 0.1440 ::: train hss = 0.2254 : val hss = 0.0271
Fold 4: train tss = 0.7763 : val tss = 0.6924 ::: train hss = 0.2073 : val hss = 0.2798
mean cv TSS: 0.3336
mean cv HSS: 0.1229
333/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.7629 : val tss = 0.3212 ::: train hss = 0.0401 : val hss = 0.1494
Fold 1: train tss = 0.8260 : val tss = 0.4537 ::: train hss = 0.2328 : val hss = 0.1843
Fold 2: train tss = 0.6854 : val tss = 0.5702 ::: train hss = 0.1164 : val hss = 0.1665
Fold 3: train tss = 0.7264 : val tss = 0.1022 ::: train hss = 0.2011 : val hss = 0.0100
Fold 4: train tss = 0.7146 : val tss = 0.6509 ::: train hss = 0.1688 : val hss = 0.2372
mean cv TSS: 0.4196
mean cv HSS: 0.1495
334/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.5797 : val tss = -0.0445 ::: train hss = 0.1154 : val hss = -0.0233
Fold 1: train tss = 0.8082 : val tss = 0.2574 ::: train hss = 0.1845 : val hss = 0.1199
Fold 2: train tss = 0.7246 : val tss = 0.5153 ::: train hss = 0.1431 : val hss = 0.1398
Fold 3: train tss = 0.8073 : val tss = 0.2798 ::: train hss = 0.2848 : val hss = 0.0278
Fold 4: train tss = 0.7728 : val tss = 0.6419 ::: train hss = 0.2071 : val hss = 0.2311
mean cv TSS: 0.3299
mean cv HSS: 0.0991
335/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.7325 : val tss = -0.0893 ::: train hss = 0.0289 : val hss = -0.0260
Fold 1: train tss = 0.7836 : val tss = 0.4234 ::: train hss = 0.3054 : val hss = 0.1904
Fold 2: train tss = 0.7145 : val tss = 0.5215 ::: train hss = 0.1408 : val hss = 0.1379
Fold 3: train tss = 0.7253 : val tss = 0.3154 ::: train hss = 0.1747 : val hss = 0.0493
Fold 4: train tss = 0.7515 : val tss = 0.6633 ::: train hss = 0.2221 : val hss = 0.2652
mean cv TSS: 0.3669
mean cv HSS: 0.1234
336/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 2191
Fold 0: train tss = 0.7789 : val tss = 0.1176 ::: train hss = 0.1477 : val hss = 0.0723
Fold 1: train tss = 0.8579 : val tss = 0.3962 ::: train hss = 0.2986 : val hss = 0.1480
Fold 2: train tss = 0.7871 : val tss = 0.6701 ::: train hss = 0.1937 : val hss = 0.2532
Fold 3: train tss = 0.7657 : val tss = 0.0417 ::: train hss = 0.2095 : val hss = 0.0059
Fold 4: train tss = 0.7681 : val tss = 0.6696 ::: train hss = 0.1980 : val hss = 0.2690
mean cv TSS: 0.3791
mean cv HSS: 0.1497
337/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6257 : val tss = 0.2887 ::: train hss = 0.1065 : val hss = 0.1385
Fold 1: train tss = 0.7777 : val tss = 0.4397 ::: train hss = 0.3420 : val hss = 0.1783
Fold 2: train tss = 0.7047 : val tss = 0.6123 ::: train hss = 0.1454 : val hss = 0.1933
Fold 3: train tss = 0.6975 : val tss = 0.2129 ::: train hss = 0.1755 : val hss = 0.0241
Fold 4: train tss = 0.6890 : val tss = 0.6238 ::: train hss = 0.1520 : val hss = 0.2077
mean cv TSS: 0.4355
mean cv HSS: 0.1484
338/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5788 : val tss = 0.1006 ::: train hss = 0.1113 : val hss = 0.0571
Fold 1: train tss = 0.8935 : val tss = 0.3323 ::: train hss = 0.2898 : val hss = 0.1209
Fold 2: train tss = 0.6533 : val tss = 0.6214 ::: train hss = 0.0909 : val hss = 0.1977
Fold 3: train tss = 0.8062 : val tss = 0.0986 ::: train hss = 0.2556 : val hss = 0.0230
Fold 4: train tss = 0.7513 : val tss = 0.6469 ::: train hss = 0.1714 : val hss = 0.2346
mean cv TSS: 0.3600
mean cv HSS: 0.1266
339/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.7159 : val tss = 0.3208 ::: train hss = 0.0901 : val hss = 0.1645
Fold 1: train tss = 0.8140 : val tss = 0.4293 ::: train hss = 0.2456 : val hss = 0.1469
Fold 2: train tss = 0.7057 : val tss = 0.6136 ::: train hss = 0.1942 : val hss = 0.1915
Fold 3: train tss = 0.7006 : val tss = 0.2856 ::: train hss = 0.1737 : val hss = 0.0300
Fold 4: train tss = 0.7117 : val tss = 0.6718 ::: train hss = 0.1647 : val hss = 0.2620
mean cv TSS: 0.4642
mean cv HSS: 0.1590
340/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.7067 : val tss = 0.2201 ::: train hss = 0.0716 : val hss = 0.0720
Fold 1: train tss = 0.8825 : val tss = 0.3328 ::: train hss = 0.2030 : val hss = 0.0946
Fold 2: train tss = 0.7305 : val tss = 0.6162 ::: train hss = 0.1312 : val hss = 0.1970
Fold 3: train tss = 0.7619 : val tss = 0.2266 ::: train hss = 0.1971 : val hss = 0.0402
Fold 4: train tss = 0.8111 : val tss = 0.7056 ::: train hss = 0.2471 : val hss = 0.2841
mean cv TSS: 0.4203
mean cv HSS: 0.1376
341/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.7603 : val tss = 0.0609 ::: train hss = 0.0831 : val hss = 0.0237
Fold 1: train tss = 0.8457 : val tss = 0.3961 ::: train hss = 0.2204 : val hss = 0.1558
Fold 2: train tss = 0.7358 : val tss = 0.5633 ::: train hss = 0.1807 : val hss = 0.1603
Fold 3: train tss = 0.7268 : val tss = 0.3270 ::: train hss = 0.1737 : val hss = 0.0363
Fold 4: train tss = 0.7473 : val tss = 0.6710 ::: train hss = 0.2035 : val hss = 0.2491
mean cv TSS: 0.4036
mean cv HSS: 0.1250
342/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9283 : val tss = 0.1652 ::: train hss = 0.1696 : val hss = 0.1108
Fold 1: train tss = 0.8580 : val tss = 0.3767 ::: train hss = 0.2110 : val hss = 0.1323
Fold 2: train tss = 0.8068 : val tss = 0.6685 ::: train hss = 0.2011 : val hss = 0.2506
Fold 3: train tss = 0.7943 : val tss = 0.0578 ::: train hss = 0.2388 : val hss = 0.0100
Fold 4: train tss = 0.7301 : val tss = 0.6392 ::: train hss = 0.1663 : val hss = 0.2130
mean cv TSS: 0.3815
mean cv HSS: 0.1434
343/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.5190 : val tss = -0.0243 ::: train hss = 0.0718 : val hss = -0.0161
Fold 1: train tss = 0.7611 : val tss = 0.3745 ::: train hss = 0.2796 : val hss = 0.1391
Fold 2: train tss = 0.7096 : val tss = 0.5905 ::: train hss = 0.1575 : val hss = 0.1786
Fold 3: train tss = 0.6924 : val tss = 0.3410 ::: train hss = 0.1667 : val hss = 0.0436
Fold 4: train tss = 0.6935 : val tss = 0.6498 ::: train hss = 0.1556 : val hss = 0.2108
mean cv TSS: 0.3863
mean cv HSS: 0.1112
344/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9625 : val tss = 0.2861 ::: train hss = 0.1094 : val hss = 0.1079
Fold 1: train tss = 0.8591 : val tss = 0.3826 ::: train hss = 0.1545 : val hss = 0.0744
Fold 2: train tss = 0.7731 : val tss = 0.6443 ::: train hss = 0.1311 : val hss = 0.2726
Fold 3: train tss = 0.8327 : val tss = 0.0753 ::: train hss = 0.2973 : val hss = 0.0137
Fold 4: train tss = 0.7997 : val tss = 0.7107 ::: train hss = 0.2438 : val hss = 0.3039
mean cv TSS: 0.4198
mean cv HSS: 0.1545
345/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.8345 : val tss = 0.0108 ::: train hss = 0.0574 : val hss = 0.0108
Fold 1: train tss = 0.8503 : val tss = 0.4242 ::: train hss = 0.3019 : val hss = 0.1299
Fold 2: train tss = 0.7463 : val tss = 0.6696 ::: train hss = 0.2022 : val hss = 0.2402
Fold 3: train tss = 0.7709 : val tss = 0.2052 ::: train hss = 0.2371 : val hss = 0.0276
Fold 4: train tss = 0.7366 : val tss = 0.6712 ::: train hss = 0.1942 : val hss = 0.2433
mean cv TSS: 0.3962
mean cv HSS: 0.1304
346/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9575 : val tss = 0.0791 ::: train hss = 0.0975 : val hss = 0.0271
Fold 1: train tss = 0.8716 : val tss = 0.3344 ::: train hss = 0.2451 : val hss = 0.0920
Fold 2: train tss = 0.8299 : val tss = 0.6631 ::: train hss = 0.2331 : val hss = 0.2658
Fold 3: train tss = 0.8393 : val tss = 0.0056 ::: train hss = 0.3179 : val hss = 0.0019

Fold 4: train tss = 0.7689 : val tss = 0.6512 ::: train hss = 0.2150 : val hss = 0.2447
mean cv TSS: 0.3467
mean cv HSS: 0.1263
347/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.9314 : val tss = -0.0914 ::: train hss = 0.0611 : val hss = -0.0319
Fold 1: train tss = 0.8373 : val tss = 0.3763 ::: train hss = 0.2302 : val hss = 0.1223
Fold 2: train tss = 0.7356 : val tss = 0.6631 ::: train hss = 0.1846 : val hss = 0.2403
Fold 3: train tss = 0.7696 : val tss = 0.1012 ::: train hss = 0.2453 : val hss = 0.0134
Fold 4: train tss = 0.7405 : val tss = 0.6621 ::: train hss = 0.2001 : val hss = 0.2485
mean cv TSS: 0.3422
mean cv HSS: 0.1185
348/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5336 : val tss = 0.0227 ::: train hss = 0.1278 : val hss = 0.0108
Fold 1: train tss = 0.8468 : val tss = 0.3156 ::: train hss = 0.3478 : val hss = 0.1046
Fold 2: train tss = 0.7558 : val tss = 0.6508 ::: train hss = 0.1743 : val hss = 0.2212
Fold 3: train tss = 0.7599 : val tss = 0.1954 ::: train hss = 0.2033 : val hss = 0.0274
Fold 4: train tss = 0.7129 : val tss = 0.6615 ::: train hss = 0.1544 : val hss = 0.2260
mean cv TSS: 0.3692
mean cv HSS: 0.1180
349/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6145 : val tss = 0.3035 ::: train hss = 0.0749 : val hss = 0.1319
Fold 1: train tss = 0.7651 : val tss = 0.3965 ::: train hss = 0.3184 : val hss = 0.1789
Fold 2: train tss = 0.6573 : val tss = 0.5257 ::: train hss = 0.1071 : val hss = 0.1408
Fold 3: train tss = 0.6647 : val tss = 0.4140 ::: train hss = 0.1501 : val hss = 0.0393
Fold 4: train tss = 0.6284 : val tss = 0.6036 ::: train hss = 0.1121 : val hss = 0.1738
mean cv TSS: 0.4486
mean cv HSS: 0.1329
350/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9425 : val tss = 0.0015 ::: train hss = 0.0728 : val hss = 0.0008
Fold 1: train tss = 0.8900 : val tss = 0.3373 ::: train hss = 0.3292 : val hss = 0.1196
Fold 2: train tss = 0.7959 : val tss = 0.6750 ::: train hss = 0.1718 : val hss = 0.2559
Fold 3: train tss = 0.7878 : val tss = 0.2114 ::: train hss = 0.2407 : val hss = 0.0324
Fold 4: train tss = 0.7788 : val tss = 0.6706 ::: train hss = 0.2080 : val hss = 0.2582
mean cv TSS: 0.3792
mean cv HSS: 0.1334
351/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6987 : val tss = 0.2811 ::: train hss = 0.0606 : val hss = 0.1021
Fold 1: train tss = 0.8225 : val tss = 0.4249 ::: train hss = 0.2744 : val hss = 0.1363
Fold 2: train tss = 0.6484 : val tss = 0.5335 ::: train hss = 0.0916 : val hss = 0.1439
Fold 3: train tss = 0.7322 : val tss = 0.2113 ::: train hss = 0.2051 : val hss = 0.0341
Fold 4: train tss = 0.6907 : val tss = 0.6582 ::: train hss = 0.1407 : val hss = 0.2398
mean cv TSS: 0.4218
mean cv HSS: 0.1312
352/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8198 : val tss = -0.0373 ::: train hss = 0.1139 : val hss = -0.0163
Fold 1: train tss = 0.8842 : val tss = 0.3290 ::: train hss = 0.3219 : val hss = 0.1106
Fold 2: train tss = 0.7106 : val tss = 0.6188 ::: train hss = 0.1144 : val hss = 0.2049
Fold 3: train tss = 0.7996 : val tss = 0.0631 ::: train hss = 0.2433 : val hss = 0.0091
Fold 4: train tss = 0.7723 : val tss = 0.6951 ::: train hss = 0.2089 : val hss = 0.2553
mean cv TSS: 0.3338
mean cv HSS: 0.1127
353/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.4831 : val tss = 0.3349 ::: train hss = 0.1137 : val hss = 0.1404
Fold 1: train tss = 0.7874 : val tss = 0.3124 ::: train hss = 0.1989 : val hss = 0.0570
Fold 2: train tss = 0.7163 : val tss = 0.6084 ::: train hss = 0.1535 : val hss = 0.1893
Fold 3: train tss = 0.7437 : val tss = 0.1948 ::: train hss = 0.2221 : val hss = 0.0260
Fold 4: train tss = 0.6832 : val tss = 0.6577 ::: train hss = 0.1427 : val hss = 0.2384
mean cv TSS: 0.4216
mean cv HSS: 0.1302
354/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8157 : val tss = 0.3219 ::: train hss = 0.1013 : val hss = 0.1127
Fold 1: train tss = 0.8134 : val tss = 0.3223 ::: train hss = 0.2715 : val hss = 0.1051
Fold 2: train tss = 0.7559 : val tss = 0.6498 ::: train hss = 0.1623 : val hss = 0.2178
Fold 3: train tss = 0.7501 : val tss = 0.1115 ::: train hss = 0.2052 : val hss = 0.0126
Fold 4: train tss = 0.7425 : val tss = 0.6575 ::: train hss = 0.1839 : val hss = 0.2507
mean cv TSS: 0.4126
mean cv HSS: 0.1398
355/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.7129 : val tss = -0.0147 ::: train hss = 0.0831 : val hss = -0.0146
Fold 1: train tss = 0.7453 : val tss = 0.4727 ::: train hss = 0.3033 : val hss = 0.1559
Fold 2: train tss = 0.6384 : val tss = 0.4305 ::: train hss = 0.0983 : val hss = 0.0934
Fold 3: train tss = 0.6415 : val tss = 0.4441 ::: train hss = 0.1340 : val hss = 0.0440
Fold 4: train tss = 0.6482 : val tss = 0.5794 ::: train hss = 0.1167 : val hss = 0.1658
mean cv TSS: 0.3824
mean cv HSS: 0.0889
356/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7256 : val tss = 0.1098 ::: train hss = 0.1219 : val hss = 0.0582
Fold 1: train tss = 0.8937 : val tss = 0.3454 ::: train hss = 0.2753 : val hss = 0.1317
Fold 2: train tss = 0.6923 : val tss = 0.5502 ::: train hss = 0.0900 : val hss = 0.1649
Fold 3: train tss = 0.8195 : val tss = 0.0578 ::: train hss = 0.2670 : val hss = 0.0141
Fold 4: train tss = 0.7667 : val tss = 0.6548 ::: train hss = 0.2089 : val hss = 0.2456
mean cv TSS: 0.3436
mean cv HSS: 0.1229
357/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 4367
Fold 0: train tss = 0.6934 : val tss = 0.0336 ::: train hss = 0.0549 : val hss = 0.0140
Fold 1: train tss = 0.8100 : val tss = 0.3281 ::: train hss = 0.3321 : val hss = 0.1034
Fold 2: train tss = 0.6892 : val tss = 0.5662 ::: train hss = 0.1371 : val hss = 0.1598
Fold 3: train tss = 0.6814 : val tss = 0.1355 ::: train hss = 0.1591 : val hss = 0.0145
Fold 4: train tss = 0.7044 : val tss = 0.6256 ::: train hss = 0.1586 : val hss = 0.1920
mean cv TSS: 0.3378
mean cv HSS: 0.0967
358/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7250 : val tss = -0.0470 ::: train hss = 0.1193 : val hss = -0.0217
Fold 1: train tss = 0.8356 : val tss = 0.3180 ::: train hss = 0.3119 : val hss = 0.1258
Fold 2: train tss = 0.7942 : val tss = 0.6049 ::: train hss = 0.1971 : val hss = 0.1924
Fold 3: train tss = 0.7368 : val tss = 0.1161 ::: train hss = 0.1750 : val hss = 0.0145
Fold 4: train tss = 0.7684 : val tss = 0.6821 ::: train hss = 0.1761 : val hss = 0.3461
mean cv TSS: 0.3348
mean cv HSS: 0.1314
359/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.9157 : val tss = 0.2139 ::: train hss = 0.1130 : val hss = 0.0718
Fold 1: train tss = 0.8807 : val tss = 0.3523 ::: train hss = 0.2475 : val hss = 0.1096
Fold 2: train tss = 0.7035 : val tss = 0.5562 ::: train hss = 0.1320 : val hss = 0.1578
Fold 3: train tss = 0.6753 : val tss = 0.1629 ::: train hss = 0.1347 : val hss = 0.0204
Fold 4: train tss = 0.7250 : val tss = 0.6541 ::: train hss = 0.1809 : val hss = 0.2236
mean cv TSS: 0.3879
mean cv HSS: 0.1166
360/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.6918 : val tss = 0.1213 ::: train hss = 0.0533 : val hss = 0.0435
Fold 1: train tss = 0.7752 : val tss = 0.3080 ::: train hss = 0.2860 : val hss = 0.1066
Fold 2: train tss = 0.6960 : val tss = 0.4984 ::: train hss = 0.1416 : val hss = 0.1256
Fold 3: train tss = 0.6959 : val tss = 0.2382 ::: train hss = 0.1521 : val hss = 0.0405
Fold 4: train tss = 0.6603 : val tss = 0.6199 ::: train hss = 0.1208 : val hss = 0.2037
mean cv TSS: 0.3572
mean cv HSS: 0.1040
361/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.6233 : val tss = 0.2959 ::: train hss = 0.0978 : val hss = 0.1612
Fold 1: train tss = 0.7511 : val tss = 0.3898 ::: train hss = 0.2907 : val hss = 0.1626
Fold 2: train tss = 0.6568 : val tss = 0.5936 ::: train hss = 0.1191 : val hss = 0.1800
Fold 3: train tss = 0.6633 : val tss = 0.1561 ::: train hss = 0.1448 : val hss = 0.0175
Fold 4: train tss = 0.6487 : val tss = 0.6231 ::: train hss = 0.1209 : val hss = 0.1895
mean cv TSS: 0.4117
mean cv HSS: 0.1422
362/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5717 : val tss = 0.0479 ::: train hss = 0.0857 : val hss = 0.0321
Fold 1: train tss = 0.7635 : val tss = 0.4301 ::: train hss = 0.1910 : val hss = 0.1195
Fold 2: train tss = 0.7000 : val tss = 0.6100 ::: train hss = 0.1282 : val hss = 0.1938
Fold 3: train tss = 0.6645 : val tss = 0.4482 ::: train hss = 0.1329 : val hss = 0.0436
Fold 4: train tss = 0.6792 : val tss = 0.5946 ::: train hss = 0.1300 : val hss = 0.2167
mean cv TSS: 0.4261
mean cv HSS: 0.1212
363/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7397 : val tss = 0.4102 ::: train hss = 0.2211 : val hss = 0.1534
Fold 2: train tss = 0.6967 : val tss = 0.6295 ::: train hss = 0.1248 : val hss = 0.2067
Fold 3: train tss = 0.6899 : val tss = 0.2174 ::: train hss = 0.1872 : val hss = 0.0297
Fold 4: train tss = 0.6882 : val tss = 0.6598 ::: train hss = 0.1763 : val hss = 0.2448
mean cv TSS: 0.3834
mean cv HSS: 0.1269
364/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5322 : val tss = 0.0398 ::: train hss = 0.1189 : val hss = 0.0275
Fold 1: train tss = 0.7321 : val tss = 0.4305 ::: train hss = 0.2019 : val hss = 0.1373
Fold 2: train tss = 0.7091 : val tss = 0.6233 ::: train hss = 0.1414 : val hss = 0.2158
Fold 3: train tss = 0.6633 : val tss = 0.2760 ::: train hss = 0.1296 : val hss = 0.0246
Fold 4: train tss = 0.6837 : val tss = 0.6449 ::: train hss = 0.1350 : val hss = 0.2266
mean cv TSS: 0.4029
mean cv HSS: 0.1264
365/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.3787 : val tss = 0.3908 ::: train hss = 0.0739 : val hss = 0.1789
Fold 1: train tss = 0.7656 : val tss = 0.4428 ::: train hss = 0.2497 : val hss = 0.1671
Fold 2: train tss = 0.6973 : val tss = 0.6114 ::: train hss = 0.1499 : val hss = 0.1928
Fold 3: train tss = 0.6944 : val tss = 0.3514 ::: train hss = 0.1619 : val hss = 0.0520
Fold 4: train tss = 0.6631 : val tss = 0.6313 ::: train hss = 0.1231 : val hss = 0.1957
mean cv TSS: 0.4855
mean cv HSS: 0.1573
366/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.6710 : val tss = 0.2490 ::: train hss = 0.0976 : val hss = 0.0862
Fold 1: train tss = 0.8151 : val tss = 0.2699 ::: train hss = 0.3925 : val hss = 0.1012
Fold 2: train tss = 0.7250 : val tss = 0.5721 ::: train hss = 0.1303 : val hss = 0.1585
Fold 3: train tss = 0.7282 : val tss = 0.3272 ::: train hss = 0.1793 : val hss = 0.0549
Fold 4: train tss = 0.6985 : val tss = 0.6523 ::: train hss = 0.1489 : val hss = 0.2466
mean cv TSS: 0.4141
mean cv HSS: 0.1295
367/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7571 : val tss = 0.3911 ::: train hss = 0.1863 : val hss = 0.1941
Fold 2: train tss = 0.6600 : val tss = 0.5610 ::: train hss = 0.1062 : val hss = 0.1610
Fold 3: train tss = 0.6659 : val tss = 0.2657 ::: train hss = 0.1359 : val hss = 0.0386

Fold 4: train tss = 0.6686 : val tss = 0.6362 ::: train hss = 0.1301 : val hss = 0.2105
mean cv TSS: 0.3708
mean cv HSS: 0.1208
368/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7330 : val tss = 0.2865 ::: train hss = 0.2039 : val hss = 0.0670
Fold 2: train tss = 0.6927 : val tss = 0.6008 ::: train hss = 0.1363 : val hss = 0.1822
Fold 3: train tss = 0.7406 : val tss = 0.2077 ::: train hss = 0.2140 : val hss = 0.0346
Fold 4: train tss = 0.7335 : val tss = 0.5787 ::: train hss = 0.1901 : val hss = 0.2659
mean cv TSS: 0.3347
mean cv HSS: 0.1099
369/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7231 : val tss = 0.4063 ::: train hss = 0.1996 : val hss = 0.1354
Fold 2: train tss = 0.6922 : val tss = 0.6261 ::: train hss = 0.1258 : val hss = 0.2034
Fold 3: train tss = 0.7011 : val tss = 0.1853 ::: train hss = 0.1764 : val hss = 0.0286
Fold 4: train tss = 0.7105 : val tss = 0.6700 ::: train hss = 0.1657 : val hss = 0.2627
mean cv TSS: 0.3775
mean cv HSS: 0.1260
370/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.5706 : val tss = 0.2410 ::: train hss = 0.0827 : val hss = 0.1258
Fold 1: train tss = 0.7841 : val tss = 0.3584 ::: train hss = 0.3078 : val hss = 0.1178
Fold 2: train tss = 0.7207 : val tss = 0.6744 ::: train hss = 0.2136 : val hss = 0.2468
Fold 3: train tss = 0.7582 : val tss = 0.1327 ::: train hss = 0.2497 : val hss = 0.0395
Fold 4: train tss = 0.7377 : val tss = 0.6888 ::: train hss = 0.1900 : val hss = 0.3063
mean cv TSS: 0.4190
mean cv HSS: 0.1672
371/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7267 : val tss = 0.4493 ::: train hss = 0.1986 : val hss = 0.2449
Fold 2: train tss = 0.7030 : val tss = 0.6539 ::: train hss = 0.1363 : val hss = 0.2283
Fold 3: train tss = 0.7371 : val tss = 0.1730 ::: train hss = 0.2157 : val hss = 0.0276
Fold 4: train tss = 0.6603 : val tss = 0.6617 ::: train hss = 0.1525 : val hss = 0.2272
mean cv TSS: 0.3876
mean cv HSS: 0.1456
372/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4846 : val tss = 0.2100 ::: train hss = 0.1227 : val hss = 0.1092
Fold 1: train tss = 0.7715 : val tss = 0.3005 ::: train hss = 0.1909 : val hss = 0.1106
Fold 2: train tss = 0.6823 : val tss = 0.5355 ::: train hss = 0.1338 : val hss = 0.1449
Fold 3: train tss = 0.6487 : val tss = 0.0667 ::: train hss = 0.1239 : val hss = 0.0078
Fold 4: train tss = 0.6656 : val tss = 0.6361 ::: train hss = 0.1250 : val hss = 0.2004
mean cv TSS: 0.3498
mean cv HSS: 0.1146
373/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.4382 : val tss = 0.3455 ::: train hss = 0.1380 : val hss = 0.1962
Fold 1: train tss = 0.7210 : val tss = 0.3444 ::: train hss = 0.2387 : val hss = 0.1222
Fold 2: train tss = 0.6679 : val tss = 0.5363 ::: train hss = 0.1260 : val hss = 0.1468
Fold 3: train tss = 0.6395 : val tss = 0.2843 ::: train hss = 0.1275 : val hss = 0.0360
Fold 4: train tss = 0.6372 : val tss = 0.6099 ::: train hss = 0.1141 : val hss = 0.1799
mean cv TSS: 0.4241
mean cv HSS: 0.1362
374/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.7397 : val tss = 0.1636 ::: train hss = 0.0551 : val hss = 0.1007
Fold 1: train tss = 0.7736 : val tss = 0.4263 ::: train hss = 0.1730 : val hss = 0.1317
Fold 2: train tss = 0.6831 : val tss = 0.6203 ::: train hss = 0.1074 : val hss = 0.2159
Fold 3: train tss = 0.6294 : val tss = 0.2764 ::: train hss = 0.1110 : val hss = 0.0239
Fold 4: train tss = 0.6627 : val tss = 0.6386 ::: train hss = 0.1219 : val hss = 0.2399
mean cv TSS: 0.4250
mean cv HSS: 0.1424
375/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.6280 : val tss = 0.3133 ::: train hss = 0.1163 : val hss = 0.1566
Fold 1: train tss = 0.7288 : val tss = 0.4389 ::: train hss = 0.2669 : val hss = 0.1350
Fold 2: train tss = 0.6793 : val tss = 0.6030 ::: train hss = 0.1117 : val hss = 0.1938
Fold 3: train tss = 0.6838 : val tss = 0.1635 ::: train hss = 0.1456 : val hss = 0.0197
Fold 4: train tss = 0.6812 : val tss = 0.6444 ::: train hss = 0.1397 : val hss = 0.2376
mean cv TSS: 0.4326
mean cv HSS: 0.1486
376/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4336 : val tss = 0.1105 ::: train hss = 0.1051 : val hss = 0.0483
Fold 1: train tss = 0.6940 : val tss = 0.3739 ::: train hss = 0.1725 : val hss = 0.1775
Fold 2: train tss = 0.6954 : val tss = 0.5690 ::: train hss = 0.1229 : val hss = 0.1675
Fold 3: train tss = 0.7174 : val tss = 0.0890 ::: train hss = 0.1741 : val hss = 0.0225
Fold 4: train tss = 0.6850 : val tss = 0.6346 ::: train hss = 0.1358 : val hss = 0.2434
mean cv TSS: 0.3554
mean cv HSS: 0.1318
377/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.5757 : val tss = 0.0677 ::: train hss = 0.0984 : val hss = 0.0247
Fold 1: train tss = 0.7853 : val tss = 0.2577 ::: train hss = 0.2341 : val hss = 0.1315
Fold 2: train tss = 0.6134 : val tss = 0.4809 ::: train hss = 0.0825 : val hss = 0.1207
Fold 3: train tss = 0.6849 : val tss = 0.3993 ::: train hss = 0.1677 : val hss = 0.0498
Fold 4: train tss = 0.6447 : val tss = 0.6011 ::: train hss = 0.1150 : val hss = 0.1887
mean cv TSS: 0.3613
mean cv HSS: 0.1031
378/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 237
Fold 0: train tss = 0.5562 : val tss = 0.2867 ::: train hss = 0.0562 : val hss = 0.0720
Fold 1: train tss = 0.8061 : val tss = 0.2892 ::: train hss = 0.1345 : val hss = 0.1156
Fold 2: train tss = 0.6823 : val tss = 0.6279 ::: train hss = 0.1135 : val hss = 0.2250
Fold 3: train tss = 0.7145 : val tss = 0.1933 ::: train hss = 0.1832 : val hss = 0.0464
Fold 4: train tss = 0.6778 : val tss = 0.6741 ::: train hss = 0.1247 : val hss = 0.2606
mean cv TSS: 0.4142
mean cv HSS: 0.1439
379/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7549 : val tss = 0.2859 ::: train hss = 0.2416 : val hss = 0.1259
Fold 2: train tss = 0.6708 : val tss = 0.5194 ::: train hss = 0.1179 : val hss = 0.1380
Fold 3: train tss = 0.6372 : val tss = 0.3814 ::: train hss = 0.1269 : val hss = 0.0407
Fold 4: train tss = 0.6247 : val tss = 0.6036 ::: train hss = 0.1069 : val hss = 0.1778
mean cv TSS: 0.3581
mean cv HSS: 0.0965
380/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.8706 : val tss = 0.0629 ::: train hss = 0.1235 : val hss = 0.0370
Fold 1: train tss = 0.7583 : val tss = 0.1567 ::: train hss = 0.1613 : val hss = 0.0850
Fold 2: train tss = 0.7232 : val tss = 0.6212 ::: train hss = 0.1382 : val hss = 0.2005
Fold 3: train tss = 0.7549 : val tss = 0.1094 ::: train hss = 0.2229 : val hss = 0.0281
Fold 4: train tss = 0.6619 : val tss = 0.6874 ::: train hss = 0.1138 : val hss = 0.2522
mean cv TSS: 0.3275
mean cv HSS: 0.1206
381/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7816 : val tss = 0.3479 ::: train hss = 0.3164 : val hss = 0.1196
Fold 2: train tss = 0.6283 : val tss = 0.5283 ::: train hss = 0.0859 : val hss = 0.1430
Fold 3: train tss = 0.6979 : val tss = 0.1681 ::: train hss = 0.1725 : val hss = 0.0191
Fold 4: train tss = 0.6839 : val tss = 0.6508 ::: train hss = 0.1452 : val hss = 0.2394
mean cv TSS: 0.3390
mean cv HSS: 0.1042
382/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.6116 : val tss = 0.2425 ::: train hss = 0.0695 : val hss = 0.0895
Fold 1: train tss = 0.8139 : val tss = 0.3340 ::: train hss = 0.1806 : val hss = 0.0992
Fold 2: train tss = 0.7015 : val tss = 0.5865 ::: train hss = 0.1273 : val hss = 0.1792
Fold 3: train tss = 0.7639 : val tss = 0.1077 ::: train hss = 0.2443 : val hss = 0.0233
Fold 4: train tss = 0.7363 : val tss = 0.6347 ::: train hss = 0.1706 : val hss = 0.2236
mean cv TSS: 0.3811
mean cv HSS: 0.1230
383/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7439 : val tss = 0.3485 ::: train hss = 0.2463 : val hss = 0.2090
Fold 2: train tss = 0.7050 : val tss = 0.6586 ::: train hss = 0.1236 : val hss = 0.2372
Fold 3: train tss = 0.6455 : val tss = 0.4116 ::: train hss = 0.1264 : val hss = 0.0462
Fold 4: train tss = 0.6405 : val tss = 0.5986 ::: train hss = 0.1113 : val hss = 0.1916
mean cv TSS: 0.4035
mean cv HSS: 0.1368
384/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.8757 : val tss = -0.0289 ::: train hss = 0.1459 : val hss = -0.0193
Fold 1: train tss = 0.8328 : val tss = 0.3933 ::: train hss = 0.2291 : val hss = 0.1172
Fold 2: train tss = 0.6969 : val tss = 0.5632 ::: train hss = 0.1181 : val hss = 0.1612
Fold 3: train tss = 0.7443 : val tss = 0.1464 ::: train hss = 0.1957 : val hss = 0.0223
Fold 4: train tss = 0.7164 : val tss = 0.6298 ::: train hss = 0.1624 : val hss = 0.2315
mean cv TSS: 0.3408
mean cv HSS: 0.1026
385/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4841 : val tss = 0.3032 ::: train hss = 0.1195 : val hss = 0.1693
Fold 1: train tss = 0.7288 : val tss = 0.3451 ::: train hss = 0.3886 : val hss = 0.1912
Fold 2: train tss = 0.6902 : val tss = 0.6494 ::: train hss = 0.1307 : val hss = 0.2226
Fold 3: train tss = 0.7089 : val tss = 0.1365 ::: train hss = 0.1810 : val hss = 0.0207
Fold 4: train tss = 0.6939 : val tss = 0.6353 ::: train hss = 0.1583 : val hss = 0.2107
mean cv TSS: 0.4139
mean cv HSS: 0.1629
386/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7193 : val tss = 0.0070 ::: train hss = 0.0992 : val hss = 0.0035
Fold 1: train tss = 0.8138 : val tss = 0.2825 ::: train hss = 0.2733 : val hss = 0.0875
Fold 2: train tss = 0.7438 : val tss = 0.5293 ::: train hss = 0.1440 : val hss = 0.1405
Fold 3: train tss = 0.7431 : val tss = 0.0895 ::: train hss = 0.1945 : val hss = 0.0209
Fold 4: train tss = 0.7494 : val tss = 0.6528 ::: train hss = 0.1780 : val hss = 0.2678
mean cv TSS: 0.3122
mean cv HSS: 0.1040
387/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5240 : val tss = 0.3324 ::: train hss = 0.0849 : val hss = 0.1364
Fold 1: train tss = 0.7848 : val tss = 0.4442 ::: train hss = 0.2212 : val hss = 0.1438
Fold 2: train tss = 0.7236 : val tss = 0.6671 ::: train hss = 0.1547 : val hss = 0.2380
Fold 3: train tss = 0.7440 : val tss = 0.2536 ::: train hss = 0.2181 : val hss = 0.0401
Fold 4: train tss = 0.7231 : val tss = 0.6630 ::: train hss = 0.1808 : val hss = 0.2527
mean cv TSS: 0.4721
mean cv HSS: 0.1622
388/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4837 : val tss = 0.0881 ::: train hss = 0.1173 : val hss = 0.0379
Fold 1: train tss = 0.8110 : val tss = 0.4619 ::: train hss = 0.1824 : val hss = 0.1060
Fold 2: train tss = 0.6754 : val tss = 0.5230 ::: train hss = 0.1071 : val hss = 0.1417
Fold 3: train tss = 0.7045 : val tss = 0.3919 ::: train hss = 0.1556 : val hss = 0.0454

Fold 4: train tss = 0.7374 : val tss = 0.6591 ::: train hss = 0.1767 : val hss = 0.2443
mean cv TSS: 0.4248
mean cv HSS: 0.1150
389/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5340 : val tss = 0.2309 ::: train hss = 0.1302 : val hss = 0.1039
Fold 1: train tss = 0.8118 : val tss = 0.3346 ::: train hss = 0.2995 : val hss = 0.1901
Fold 2: train tss = 0.7011 : val tss = 0.5484 ::: train hss = 0.1269 : val hss = 0.1529
Fold 3: train tss = 0.7072 : val tss = 0.2603 ::: train hss = 0.1694 : val hss = 0.0249
Fold 4: train tss = 0.7396 : val tss = 0.6429 ::: train hss = 0.1934 : val hss = 0.2435
mean cv TSS: 0.4034
mean cv HSS: 0.1431
390/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.9180 : val tss = -0.0529 ::: train hss = 0.1204 : val hss = -0.0298
Fold 1: train tss = 0.8407 : val tss = 0.3136 ::: train hss = 0.3622 : val hss = 0.1440
Fold 2: train tss = 0.7827 : val tss = 0.6495 ::: train hss = 0.1921 : val hss = 0.2338
Fold 3: train tss = 0.7809 : val tss = 0.3036 ::: train hss = 0.2362 : val hss = 0.0404
Fold 4: train tss = 0.7443 : val tss = 0.6752 ::: train hss = 0.1767 : val hss = 0.2394
mean cv TSS: 0.3778
mean cv HSS: 0.1256
391/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.6528 : val tss = -0.0433 ::: train hss = 0.0613 : val hss = -0.0315
Fold 1: train tss = 0.7565 : val tss = 0.3741 ::: train hss = 0.2964 : val hss = 0.1487
Fold 2: train tss = 0.6923 : val tss = 0.6239 ::: train hss = 0.1312 : val hss = 0.2018
Fold 3: train tss = 0.6961 : val tss = 0.2893 ::: train hss = 0.1577 : val hss = 0.0308
Fold 4: train tss = 0.6953 : val tss = 0.6000 ::: train hss = 0.1566 : val hss = 0.1866
mean cv TSS: 0.3688
mean cv HSS: 0.1073
392/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.9502 : val tss = 0.3048 ::: train hss = 0.0837 : val hss = 0.0983
Fold 1: train tss = 0.8704 : val tss = 0.2668 ::: train hss = 0.4585 : val hss = 0.1057
Fold 2: train tss = 0.7459 : val tss = 0.6840 ::: train hss = 0.1471 : val hss = 0.2616
Fold 3: train tss = 0.7969 : val tss = 0.1038 ::: train hss = 0.3047 : val hss = 0.0253
Fold 4: train tss = 0.7959 : val tss = 0.6703 ::: train hss = 0.2262 : val hss = 0.3437
mean cv TSS: 0.4059
mean cv HSS: 0.1669
393/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.1974 : val tss = 0.0100 ::: train hss = 0.0171 : val hss = 0.0057
Fold 1: train tss = 0.7781 : val tss = 0.4357 ::: train hss = 0.4449 : val hss = 0.1443
Fold 2: train tss = 0.7425 : val tss = 0.6854 ::: train hss = 0.1832 : val hss = 0.2563
Fold 3: train tss = 0.7019 : val tss = 0.1412 ::: train hss = 0.1771 : val hss = 0.0261
Fold 4: train tss = 0.7115 : val tss = 0.5779 ::: train hss = 0.1773 : val hss = 0.1563
mean cv TSS: 0.3701
mean cv HSS: 0.1177
394/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.5097 : val tss = 0.2460 ::: train hss = 0.0557 : val hss = 0.0652
Fold 1: train tss = 0.8392 : val tss = 0.3813 ::: train hss = 0.2148 : val hss = 0.1085
Fold 2: train tss = 0.7568 : val tss = 0.5631 ::: train hss = 0.1684 : val hss = 0.1639
Fold 3: train tss = 0.7487 : val tss = 0.1601 ::: train hss = 0.2322 : val hss = 0.0397
Fold 4: train tss = 0.7924 : val tss = 0.6438 ::: train hss = 0.2252 : val hss = 0.2329
mean cv TSS: 0.3988
mean cv HSS: 0.1221
395/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7790 : val tss = 0.3644 ::: train hss = 0.2677 : val hss = 0.1012
Fold 2: train tss = 0.6903 : val tss = 0.6618 ::: train hss = 0.1879 : val hss = 0.2333
Fold 3: train tss = 0.7541 : val tss = 0.3786 ::: train hss = 0.2300 : val hss = 0.0533
Fold 4: train tss = 0.7304 : val tss = 0.6609 ::: train hss = 0.1801 : val hss = 0.2305
mean cv TSS: 0.4131
mean cv HSS: 0.1237
396/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.8584 : val tss = 0.0354 ::: train hss = 0.0894 : val hss = 0.0203
Fold 1: train tss = 0.7922 : val tss = 0.3707 ::: train hss = 0.2302 : val hss = 0.1308
Fold 2: train tss = 0.7122 : val tss = 0.6021 ::: train hss = 0.1400 : val hss = 0.1830
Fold 3: train tss = 0.7039 : val tss = 0.3618 ::: train hss = 0.1646 : val hss = 0.0371
Fold 4: train tss = 0.7136 : val tss = 0.6084 ::: train hss = 0.1592 : val hss = 0.1982
mean cv TSS: 0.3957
mean cv HSS: 0.1139
397/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5321 : val tss = 0.2953 ::: train hss = 0.1182 : val hss = 0.1598
Fold 1: train tss = 0.6598 : val tss = 0.4450 ::: train hss = 0.2144 : val hss = 0.1823
Fold 2: train tss = 0.6649 : val tss = 0.5483 ::: train hss = 0.1133 : val hss = 0.1513
Fold 3: train tss = 0.6656 : val tss = 0.3582 ::: train hss = 0.1443 : val hss = 0.0476
Fold 4: train tss = 0.6430 : val tss = 0.6146 ::: train hss = 0.1226 : val hss = 0.1823
mean cv TSS: 0.4523
mean cv HSS: 0.1447
398/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.8120 : val tss = 0.1340 ::: train hss = 0.0920 : val hss = 0.0602
Fold 1: train tss = 0.8367 : val tss = 0.4344 ::: train hss = 0.2397 : val hss = 0.0919
Fold 2: train tss = 0.7246 : val tss = 0.6125 ::: train hss = 0.1456 : val hss = 0.1956
Fold 3: train tss = 0.7243 : val tss = 0.1645 ::: train hss = 0.1705 : val hss = 0.0238
Fold 4: train tss = 0.7442 : val tss = 0.6361 ::: train hss = 0.1738 : val hss = 0.2188
mean cv TSS: 0.3963
mean cv HSS: 0.1181
399/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 379
Fold 0: train tss = 0.5850 : val tss = 0.3457 ::: train hss = 0.1490 : val hss = 0.2090
Fold 1: train tss = 0.7443 : val tss = 0.4883 ::: train hss = 0.2117 : val hss = 0.1429
Fold 2: train tss = 0.7131 : val tss = 0.5936 ::: train hss = 0.1476 : val hss = 0.1813
Fold 3: train tss = 0.5664 : val tss = 0.4428 ::: train hss = 0.0872 : val hss = 0.0524
Fold 4: train tss = 0.6937 : val tss = 0.6502 ::: train hss = 0.1511 : val hss = 0.2174
mean cv TSS: 0.5041
mean cv HSS: 0.1606
400/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.6270 : val tss = -0.0530 ::: train hss = 0.1120 : val hss = -0.0242
Fold 1: train tss = 0.8442 : val tss = 0.2937 ::: train hss = 0.2375 : val hss = 0.1100
Fold 2: train tss = 0.7258 : val tss = 0.6481 ::: train hss = 0.1403 : val hss = 0.2298
Fold 3: train tss = 0.7481 : val tss = 0.3651 ::: train hss = 0.1935 : val hss = 0.0441
Fold 4: train tss = 0.6476 : val tss = 0.5898 ::: train hss = 0.1156 : val hss = 0.1766
mean cv TSS: 0.3687
mean cv HSS: 0.1073
401/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.6288 : val tss = 0.1469 ::: train hss = 0.1203 : val hss = 0.0678
Fold 1: train tss = 0.7780 : val tss = 0.3787 ::: train hss = 0.2145 : val hss = 0.0935
Fold 2: train tss = 0.6345 : val tss = 0.5439 ::: train hss = 0.0885 : val hss = 0.1554
Fold 3: train tss = 0.6839 : val tss = 0.2649 ::: train hss = 0.1478 : val hss = 0.0242
Fold 4: train tss = 0.7089 : val tss = 0.6114 ::: train hss = 0.1692 : val hss = 0.2039
mean cv TSS: 0.3892
mean cv HSS: 0.1090
402/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.6469 : val tss = 0.2724 ::: train hss = 0.0545 : val hss = 0.1435
Fold 1: train tss = 0.8462 : val tss = 0.3912 ::: train hss = 0.2033 : val hss = 0.1500
Fold 2: train tss = 0.7094 : val tss = 0.5934 ::: train hss = 0.1402 : val hss = 0.1824
Fold 3: train tss = 0.7540 : val tss = 0.2037 ::: train hss = 0.1952 : val hss = 0.0285
Fold 4: train tss = 0.7384 : val tss = 0.5902 ::: train hss = 0.1753 : val hss = 0.1909
mean cv TSS: 0.4102
mean cv HSS: 0.1391
403/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.3143 : val tss = -0.0070 ::: train hss = 0.0388 : val hss = -0.0109
Fold 1: train tss = 0.7552 : val tss = 0.3214 ::: train hss = 0.2902 : val hss = 0.1248
Fold 2: train tss = 0.6696 : val tss = 0.5215 ::: train hss = 0.1144 : val hss = 0.1382
Fold 3: train tss = 0.6701 : val tss = 0.3895 ::: train hss = 0.1508 : val hss = 0.0414
Fold 4: train tss = 0.6509 : val tss = 0.6432 ::: train hss = 0.1224 : val hss = 0.2163
mean cv TSS: 0.3737
mean cv HSS: 0.1020
404/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8639 : val tss = 0.1561 ::: train hss = 0.1022 : val hss = 0.0932
Fold 1: train tss = 0.8549 : val tss = 0.3666 ::: train hss = 0.2444 : val hss = 0.1159
Fold 2: train tss = 0.7590 : val tss = 0.6587 ::: train hss = 0.1256 : val hss = 0.2353
Fold 3: train tss = 0.8199 : val tss = 0.0967 ::: train hss = 0.2955 : val hss = 0.0192
Fold 4: train tss = 0.7731 : val tss = 0.6554 ::: train hss = 0.2105 : val hss = 0.2450
mean cv TSS: 0.3867
mean cv HSS: 0.1417
405/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8238 : val tss = 0.3744 ::: train hss = 0.1837 : val hss = 0.0977
Fold 2: train tss = 0.6841 : val tss = 0.4923 ::: train hss = 0.1164 : val hss = 0.1198
Fold 3: train tss = 0.7180 : val tss = 0.1352 ::: train hss = 0.1839 : val hss = 0.0226
Fold 4: train tss = 0.7019 : val tss = 0.6514 ::: train hss = 0.1595 : val hss = 0.2377
mean cv TSS: 0.3307
mean cv HSS: 0.0956
406/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.7765 : val tss = -0.0478 ::: train hss = 0.1345 : val hss = -0.0255
Fold 1: train tss = 0.8302 : val tss = 0.3336 ::: train hss = 0.2225 : val hss = 0.0796
Fold 2: train tss = 0.7690 : val tss = 0.6618 ::: train hss = 0.1734 : val hss = 0.2278
Fold 3: train tss = 0.7767 : val tss = 0.0924 ::: train hss = 0.2282 : val hss = 0.0264
Fold 4: train tss = 0.7254 : val tss = 0.6565 ::: train hss = 0.1544 : val hss = 0.2297
mean cv TSS: 0.3393
mean cv HSS: 0.1076
407/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.8548 : val tss = -0.1701 ::: train hss = 0.0274 : val hss = -0.0316
Fold 1: train tss = 0.8078 : val tss = 0.3878 ::: train hss = 0.1324 : val hss = 0.1102
Fold 2: train tss = 0.7075 : val tss = 0.6367 ::: train hss = 0.1351 : val hss = 0.2124
Fold 3: train tss = 0.7852 : val tss = 0.1712 ::: train hss = 0.2442 : val hss = 0.0270
Fold 4: train tss = 0.7029 : val tss = 0.6457 ::: train hss = 0.1506 : val hss = 0.2202
mean cv TSS: 0.3342
mean cv HSS: 0.1077
408/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9292 : val tss = -0.0224 ::: train hss = 0.1753 : val hss = -0.0164
Fold 1: train tss = 0.8756 : val tss = 0.3057 ::: train hss = 0.2854 : val hss = 0.1264
Fold 2: train tss = 0.7611 : val tss = 0.6353 ::: train hss = 0.1732 : val hss = 0.2145
Fold 3: train tss = 0.7860 : val tss = 0.1162 ::: train hss = 0.2345 : val hss = 0.0194
Fold 4: train tss = 0.7641 : val tss = 0.6846 ::: train hss = 0.1979 : val hss = 0.2852
mean cv TSS: 0.3439
mean cv HSS: 0.1258
409/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6282 : val tss = 0.2702 ::: train hss = 0.1174 : val hss = 0.1391
Fold 1: train tss = 0.7699 : val tss = 0.4323 ::: train hss = 0.2815 : val hss = 0.1657
Fold 2: train tss = 0.6916 : val tss = 0.6222 ::: train hss = 0.1458 : val hss = 0.2005
Fold 3: train tss = 0.6915 : val tss = 0.1192 ::: train hss = 0.1655 : val hss = 0.0144

Fold 4: train tss = 0.6813 : val tss = 0.6284 ::: train hss = 0.1454 : val hss = 0.2035
mean cv TSS: 0.4145
mean cv HSS: 0.1446
410/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9004 : val tss = 0.1231 ::: train hss = 0.0799 : val hss = 0.0526
Fold 1: train tss = 0.8316 : val tss = 0.5069 ::: train hss = 0.1982 : val hss = 0.1577
Fold 2: train tss = 0.7579 : val tss = 0.5809 ::: train hss = 0.1351 : val hss = 0.1668
Fold 3: train tss = 0.8118 : val tss = 0.0582 ::: train hss = 0.2771 : val hss = 0.0101
Fold 4: train tss = 0.8008 : val tss = 0.6793 ::: train hss = 0.2231 : val hss = 0.2676
mean cv TSS: 0.3897
mean cv HSS: 0.1309
411/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5318 : val tss = 0.3287 ::: train hss = 0.1169 : val hss = 0.1646
Fold 1: train tss = 0.7791 : val tss = 0.4557 ::: train hss = 0.2848 : val hss = 0.1654
Fold 2: train tss = 0.7381 : val tss = 0.6842 ::: train hss = 0.1683 : val hss = 0.2540
Fold 3: train tss = 0.7257 : val tss = 0.2052 ::: train hss = 0.1961 : val hss = 0.0289
Fold 4: train tss = 0.7049 : val tss = 0.6581 ::: train hss = 0.1566 : val hss = 0.2397
mean cv TSS: 0.4664
mean cv HSS: 0.1705
412/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8626 : val tss = 0.1428 ::: train hss = 0.0989 : val hss = 0.0537
Fold 1: train tss = 0.8547 : val tss = 0.3779 ::: train hss = 0.2565 : val hss = 0.0998
Fold 2: train tss = 0.8032 : val tss = 0.6969 ::: train hss = 0.2236 : val hss = 0.3091
Fold 3: train tss = 0.7990 : val tss = 0.1256 ::: train hss = 0.2435 : val hss = 0.0222
Fold 4: train tss = 0.7768 : val tss = 0.6970 ::: train hss = 0.2043 : val hss = 0.2905
mean cv TSS: 0.4081
mean cv HSS: 0.1551
413/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.7860 : val tss = 0.1919 ::: train hss = 0.0319 : val hss = 0.0710
Fold 1: train tss = 0.8031 : val tss = 0.3420 ::: train hss = 0.1530 : val hss = 0.1095
Fold 2: train tss = 0.6478 : val tss = 0.4810 ::: train hss = 0.0885 : val hss = 0.1200
Fold 3: train tss = 0.7409 : val tss = 0.2364 ::: train hss = 0.2066 : val hss = 0.0297
Fold 4: train tss = 0.7489 : val tss = 0.6477 ::: train hss = 0.2047 : val hss = 0.2312
mean cv TSS: 0.3798
mean cv HSS: 0.1123
414/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9295 : val tss = 0.2672 ::: train hss = 0.1779 : val hss = 0.1678
Fold 1: train tss = 0.8952 : val tss = 0.2570 ::: train hss = 0.2533 : val hss = 0.1169
Fold 2: train tss = 0.8185 : val tss = 0.6102 ::: train hss = 0.2216 : val hss = 0.1826
Fold 3: train tss = 0.8007 : val tss = 0.1757 ::: train hss = 0.2427 : val hss = 0.0341
Fold 4: train tss = 0.7684 : val tss = 0.6496 ::: train hss = 0.2086 : val hss = 0.2451
mean cv TSS: 0.3919
mean cv HSS: 0.1493
415/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.6179 : val tss = -0.0170 ::: train hss = 0.0824 : val hss = -0.0180
Fold 1: train tss = 0.7641 : val tss = 0.4169 ::: train hss = 0.3133 : val hss = 0.1557
Fold 2: train tss = 0.7130 : val tss = 0.6328 ::: train hss = 0.1611 : val hss = 0.2125
Fold 3: train tss = 0.7052 : val tss = 0.3655 ::: train hss = 0.1742 : val hss = 0.0442
Fold 4: train tss = 0.6764 : val tss = 0.6542 ::: train hss = 0.1436 : val hss = 0.2143
mean cv TSS: 0.4105
mean cv HSS: 0.1218
416/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9705 : val tss = 0.1519 ::: train hss = 0.1362 : val hss = 0.0668
Fold 1: train tss = 0.8941 : val tss = 0.4278 ::: train hss = 0.3090 : val hss = 0.1659
Fold 2: train tss = 0.7842 : val tss = 0.6331 ::: train hss = 0.1629 : val hss = 0.2471
Fold 3: train tss = 0.8325 : val tss = 0.0572 ::: train hss = 0.2983 : val hss = 0.0098
Fold 4: train tss = 0.7895 : val tss = 0.6523 ::: train hss = 0.2247 : val hss = 0.2155
mean cv TSS: 0.3844
mean cv HSS: 0.1410
417/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.6854 : val tss = 0.2517 ::: train hss = 0.0479 : val hss = 0.1085
Fold 1: train tss = 0.8265 : val tss = 0.3474 ::: train hss = 0.2233 : val hss = 0.1074
Fold 2: train tss = 0.7074 : val tss = 0.6034 ::: train hss = 0.1252 : val hss = 0.1839
Fold 3: train tss = 0.7421 : val tss = 0.1379 ::: train hss = 0.2157 : val hss = 0.0222
Fold 4: train tss = 0.7218 : val tss = 0.6548 ::: train hss = 0.1754 : val hss = 0.2377
mean cv TSS: 0.3990
mean cv HSS: 0.1319
418/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9163 : val tss = 0.0238 ::: train hss = 0.1149 : val hss = 0.0104
Fold 1: train tss = 0.9197 : val tss = 0.2719 ::: train hss = 0.3507 : val hss = 0.1067
Fold 2: train tss = 0.8321 : val tss = 0.6710 ::: train hss = 0.2282 : val hss = 0.2909
Fold 3: train tss = 0.7602 : val tss = 0.0465 ::: train hss = 0.2001 : val hss = 0.0103
Fold 4: train tss = 0.8327 : val tss = 0.6960 ::: train hss = 0.2635 : val hss = 0.3280
mean cv TSS: 0.3418
mean cv HSS: 0.1493
419/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.8402 : val tss = -0.0435 ::: train hss = 0.0628 : val hss = -0.0243
Fold 1: train tss = 0.8388 : val tss = 0.4072 ::: train hss = 0.1821 : val hss = 0.1249
Fold 2: train tss = 0.7592 : val tss = 0.6735 ::: train hss = 0.2336 : val hss = 0.2459
Fold 3: train tss = 0.7507 : val tss = 0.2958 ::: train hss = 0.2548 : val hss = 0.0312
Fold 4: train tss = 0.6898 : val tss = 0.6374 ::: train hss = 0.1405 : val hss = 0.2200
mean cv TSS: 0.3941
mean cv HSS: 0.1196
420/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 2191
Fold 0: train tss = 0.8511 : val tss = -0.0392 ::: train hss = 0.0767 : val hss = -0.0217
Fold 1: train tss = 0.8251 : val tss = 0.4237 ::: train hss = 0.2200 : val hss = 0.1392
Fold 2: train tss = 0.7171 : val tss = 0.5733 ::: train hss = 0.1404 : val hss = 0.1639
Fold 3: train tss = 0.7205 : val tss = 0.2922 ::: train hss = 0.1738 : val hss = 0.0339
Fold 4: train tss = 0.7090 : val tss = 0.6380 ::: train hss = 0.1537 : val hss = 0.2233
mean cv TSS: 0.3776
mean cv HSS: 0.1077
421/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.4791 : val tss = 0.2865 ::: train hss = 0.0939 : val hss = 0.1490
Fold 1: train tss = 0.6894 : val tss = 0.3904 ::: train hss = 0.0996 : val hss = 0.0836
Fold 2: train tss = 0.6440 : val tss = 0.5933 ::: train hss = 0.0991 : val hss = 0.1798
Fold 3: train tss = 0.6451 : val tss = 0.4236 ::: train hss = 0.1329 : val hss = 0.0480
Fold 4: train tss = 0.6378 : val tss = 0.6344 ::: train hss = 0.1203 : val hss = 0.1944
mean cv TSS: 0.4656
mean cv HSS: 0.1310
422/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9314 : val tss = 0.0150 ::: train hss = 0.0611 : val hss = 0.0064
Fold 1: train tss = 0.8421 : val tss = 0.3970 ::: train hss = 0.2558 : val hss = 0.1515
Fold 2: train tss = 0.8033 : val tss = 0.6367 ::: train hss = 0.2358 : val hss = 0.2349
Fold 3: train tss = 0.7259 : val tss = 0.1113 ::: train hss = 0.1698 : val hss = 0.0231
Fold 4: train tss = 0.6947 : val tss = 0.6126 ::: train hss = 0.1336 : val hss = 0.2139
mean cv TSS: 0.3545
mean cv HSS: 0.1259
423/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.8446 : val tss = 0.3316 ::: train hss = 0.0369 : val hss = 0.1200
Fold 1: train tss = 0.8167 : val tss = 0.4567 ::: train hss = 0.2686 : val hss = 0.1786
Fold 2: train tss = 0.7133 : val tss = 0.6007 ::: train hss = 0.1520 : val hss = 0.1854
Fold 3: train tss = 0.7299 : val tss = 0.2466 ::: train hss = 0.2286 : val hss = 0.0311
Fold 4: train tss = 0.6615 : val tss = 0.5826 ::: train hss = 0.1464 : val hss = 0.1601
mean cv TSS: 0.4437
mean cv HSS: 0.1350
424/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.7193 : val tss = 0.0168 ::: train hss = 0.0992 : val hss = 0.0105
Fold 1: train tss = 0.8746 : val tss = 0.3473 ::: train hss = 0.2980 : val hss = 0.1104
Fold 2: train tss = 0.7004 : val tss = 0.6290 ::: train hss = 0.1265 : val hss = 0.2027
Fold 3: train tss = 0.7649 : val tss = 0.0724 ::: train hss = 0.2087 : val hss = 0.0095
Fold 4: train tss = 0.7685 : val tss = 0.6857 ::: train hss = 0.1986 : val hss = 0.2698
mean cv TSS: 0.3503
mean cv HSS: 0.1206
425/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6225 : val tss = 0.1553 ::: train hss = 0.0954 : val hss = 0.0618
Fold 1: train tss = 0.7541 : val tss = 0.3381 ::: train hss = 0.1883 : val hss = 0.0647
Fold 2: train tss = 0.6682 : val tss = 0.5386 ::: train hss = 0.0997 : val hss = 0.1471
Fold 3: train tss = 0.7250 : val tss = 0.2208 ::: train hss = 0.1756 : val hss = 0.0231
Fold 4: train tss = 0.6740 : val tss = 0.7007 ::: train hss = 0.1321 : val hss = 0.2661
mean cv TSS: 0.3907
mean cv HSS: 0.1126
426/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8247 : val tss = 0.2768 ::: train hss = 0.1336 : val hss = 0.1140
Fold 1: train tss = 0.8292 : val tss = 0.4451 ::: train hss = 0.2200 : val hss = 0.1327
Fold 2: train tss = 0.7227 : val tss = 0.4620 ::: train hss = 0.1413 : val hss = 0.1079
Fold 3: train tss = 0.7633 : val tss = 0.1266 ::: train hss = 0.2122 : val hss = 0.0159
Fold 4: train tss = 0.7219 : val tss = 0.6403 ::: train hss = 0.1615 : val hss = 0.2185
mean cv TSS: 0.3902
mean cv HSS: 0.1178
427/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.4771 : val tss = -0.0254 ::: train hss = 0.0868 : val hss = -0.0156
Fold 1: train tss = 0.6520 : val tss = 0.4498 ::: train hss = 0.4373 : val hss = 0.1216
Fold 2: train tss = 0.6182 : val tss = 0.5021 ::: train hss = 0.0818 : val hss = 0.1270
Fold 3: train tss = 0.6210 : val tss = 0.4448 ::: train hss = 0.1265 : val hss = 0.0442
Fold 4: train tss = 0.6310 : val tss = 0.5713 ::: train hss = 0.1152 : val hss = 0.1570
mean cv TSS: 0.3885
mean cv HSS: 0.0868
428/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9669 : val tss = -0.0040 ::: train hss = 0.1228 : val hss = -0.0028
Fold 1: train tss = 0.8568 : val tss = 0.3300 ::: train hss = 0.2275 : val hss = 0.1064
Fold 2: train tss = 0.8130 : val tss = 0.6436 ::: train hss = 0.2984 : val hss = 0.2295
Fold 3: train tss = 0.7930 : val tss = 0.0658 ::: train hss = 0.2248 : val hss = 0.0189
Fold 4: train tss = 0.7257 : val tss = 0.6262 ::: train hss = 0.1626 : val hss = 0.2078
mean cv TSS: 0.3323
mean cv HSS: 0.1120
429/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.9182 : val tss = -0.0311 ::: train hss = 0.0510 : val hss = -0.0151
Fold 1: train tss = 0.8729 : val tss = 0.3207 ::: train hss = 0.4065 : val hss = 0.1219
Fold 2: train tss = 0.7398 : val tss = 0.6398 ::: train hss = 0.1971 : val hss = 0.2148
Fold 3: train tss = 0.7280 : val tss = 0.2307 ::: train hss = 0.1999 : val hss = 0.0307
Fold 4: train tss = 0.7265 : val tss = 0.6279 ::: train hss = 0.1908 : val hss = 0.1959
mean cv TSS: 0.3576
mean cv HSS: 0.1096
430/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9630 : val tss = -0.0418 ::: train hss = 0.1110 : val hss = -0.0213
Fold 1: train tss = 0.9126 : val tss = 0.3129 ::: train hss = 0.4141 : val hss = 0.1056
Fold 2: train tss = 0.8108 : val tss = 0.5915 ::: train hss = 0.2071 : val hss = 0.1838
Fold 3: train tss = 0.7911 : val tss = 0.0186 ::: train hss = 0.2218 : val hss = 0.0027

Fold 4: train tss = 0.7694 : val tss = 0.7167 ::: train hss = 0.2047 : val hss = 0.2869
mean cv TSS: 0.3196
mean cv HSS: 0.1115
431/864
{'batch_size': 128, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.7236 : val tss = -0.0135 ::: train hss = 0.1140 : val hss = -0.0114
Fold 1: train tss = 0.8842 : val tss = 0.3008 ::: train hss = 0.3219 : val hss = 0.0830
Fold 2: train tss = 0.6984 : val tss = 0.6308 ::: train hss = 0.1211 : val hss = 0.2071
Fold 3: train tss = 0.7256 : val tss = 0.1348 ::: train hss = 0.1717 : val hss = 0.0176
Fold 4: train tss = 0.6513 : val tss = 0.5557 ::: train hss = 0.1199 : val hss = 0.1421
mean cv TSS: 0.3217
mean cv HSS: 0.0877
432/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6265 : val tss = 0.2105 ::: train hss = 0.6905 : val hss = 0.1256
Fold 2: train tss = 0.4382 : val tss = 0.6465 ::: train hss = 0.3908 : val hss = 0.4790
Fold 3: train tss = 0.6094 : val tss = 0.0203 ::: train hss = 0.5003 : val hss = 0.0185
Fold 4: train tss = 0.5330 : val tss = 0.5193 ::: train hss = 0.4686 : val hss = 0.4656
mean cv TSS: 0.2793
mean cv HSS: 0.2177
433/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5944 : val tss = 0.2644 ::: train hss = 0.6551 : val hss = 0.1608
Fold 2: train tss = 0.2649 : val tss = 0.4332 ::: train hss = 0.3002 : val hss = 0.4071
Fold 3: train tss = 0.4163 : val tss = -0.0043 ::: train hss = 0.4191 : val hss = -0.0065
Fold 4: train tss = 0.3197 : val tss = 0.4919 ::: train hss = 0.3647 : val hss = 0.4190
mean cv TSS: 0.2370
mean cv HSS: 0.1961
434/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5368 : val tss = 0.1484 ::: train hss = 0.6447 : val hss = 0.0884
Fold 2: train tss = 0.5436 : val tss = 0.6872 ::: train hss = 0.2793 : val hss = 0.3631
Fold 3: train tss = 0.6651 : val tss = 0.0256 ::: train hss = 0.5050 : val hss = 0.0206
Fold 4: train tss = 0.5636 : val tss = 0.2637 ::: train hss = 0.4713 : val hss = 0.2663
mean cv TSS: 0.2250
mean cv HSS: 0.1477
435/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0298 : val tss = 0.0019 ::: train hss = 0.0063 : val hss = 0.0034
Fold 1: train tss = 0.5197 : val tss = 0.2193 ::: train hss = 0.5430 : val hss = 0.0904
Fold 2: train tss = 0.5083 : val tss = 0.6664 ::: train hss = 0.5132 : val hss = 0.5611
Fold 3: train tss = 0.5747 : val tss = 0.0329 ::: train hss = 0.5004 : val hss = 0.0338
Fold 4: train tss = 0.3935 : val tss = 0.3618 ::: train hss = 0.4084 : val hss = 0.3321
mean cv TSS: 0.2564
mean cv HSS: 0.2042
436/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5599 : val tss = 0.0607 ::: train hss = 0.6799 : val hss = 0.0314
Fold 2: train tss = 0.0029 : val tss = -0.0040 ::: train hss = 0.0055 : val hss = -0.0076
Fold 3: train tss = 0.5849 : val tss = 0.0049 ::: train hss = 0.4819 : val hss = 0.0049
Fold 4: train tss = 0.4429 : val tss = 0.5276 ::: train hss = 0.4035 : val hss = 0.4693
mean cv TSS: 0.1178
mean cv HSS: 0.0996
437/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = -0.0068 : val tss = -0.0119 ::: train hss = -0.0006 : val hss = -0.0161
Fold 1: train tss = 0.5558 : val tss = 0.1622 ::: train hss = 0.6881 : val hss = 0.0873
Fold 2: train tss = 0.3514 : val tss = 0.3517 ::: train hss = 0.3345 : val hss = 0.3555
Fold 3: train tss = 0.5773 : val tss = -0.0077 ::: train hss = 0.5017 : val hss = -0.0098
Fold 4: train tss = 0.4608 : val tss = 0.4309 ::: train hss = 0.4831 : val hss = 0.4162
mean cv TSS: 0.1850
mean cv HSS: 0.1666
438/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6345 : val tss = 0.3367 ::: train hss = 0.4911 : val hss = 0.2381
Fold 2: train tss = 0.4609 : val tss = 0.5907 ::: train hss = 0.3746 : val hss = 0.4297
Fold 3: train tss = 0.5514 : val tss = 0.0515 ::: train hss = 0.4622 : val hss = 0.0397
Fold 4: train tss = 0.5004 : val tss = 0.4035 ::: train hss = 0.4345 : val hss = 0.3850
mean cv TSS: 0.2765
mean cv HSS: 0.2185
439/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2283 : val tss = 0.0000 ::: train hss = 0.2996 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
440/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5309 : val tss = 0.0740 ::: train hss = 0.4165 : val hss = 0.0650
Fold 4: train tss = 0.5478 : val tss = 0.2461 ::: train hss = 0.4430 : val hss = 0.2641
mean cv TSS: 0.0640
mean cv HSS: 0.0658
441/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4454 : val tss = 0.0259 ::: train hss = 0.4239 : val hss = 0.0291
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0052
mean cv HSS: 0.0058
442/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5564 : val tss = 0.0155 ::: train hss = 0.4740 : val hss = 0.0164
Fold 4: train tss = 0.5550 : val tss = 0.2607 ::: train hss = 0.4676 : val hss = 0.2491
mean cv TSS: 0.0552
mean cv HSS: 0.0531
443/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 4: train tss = 0.3800 : val tss = 0.4961 ::: train hss = 0.4044 : val hss = 0.3891
mean cv TSS: 0.0992
mean cv HSS: 0.0778
444/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.1499 : val tss = 0.0991 ::: train hss = 0.2498 : val hss = 0.1497
Fold 1: train tss = 0.1753 : val tss = 0.1805 ::: train hss = 0.2767 : val hss = 0.2406
Fold 2: train tss = 0.3213 : val tss = 0.6120 ::: train hss = 0.3617 : val hss = 0.5085
Fold 3: train tss = 0.5679 : val tss = 0.0223 ::: train hss = 0.4706 : val hss = 0.0217
Fold 4: train tss = 0.4881 : val tss = 0.3314 ::: train hss = 0.4402 : val hss = 0.3627
mean cv TSS: 0.2490
mean cv HSS: 0.2567
445/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4729 : val tss = 0.2888 ::: train hss = 0.5774 : val hss = 0.2189
Fold 2: train tss = 0.1928 : val tss = 0.3344 ::: train hss = 0.2450 : val hss = 0.3842
Fold 3: train tss = 0.4049 : val tss = 0.0096 ::: train hss = 0.3755 : val hss = 0.0117
Fold 4: train tss = 0.2752 : val tss = 0.4963 ::: train hss = 0.3123 : val hss = 0.4337
mean cv TSS: 0.2258
mean cv HSS: 0.2097
446/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5442 : val tss = 0.3399 ::: train hss = 0.6074 : val hss = 0.2125
Fold 2: train tss = 0.4538 : val tss = 0.4583 ::: train hss = 0.4212 : val hss = 0.4355
Fold 3: train tss = 0.6835 : val tss = 0.0195 ::: train hss = 0.5351 : val hss = 0.0133
Fold 4: train tss = 0.5366 : val tss = 0.2199 ::: train hss = 0.4139 : val hss = 0.2693
mean cv TSS: 0.2075
mean cv HSS: 0.1861
447/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3203 : val tss = 0.1167 ::: train hss = 0.4596 : val hss = 0.1707
Fold 2: train tss = 0.4047 : val tss = 0.5225 ::: train hss = 0.3588 : val hss = 0.4222
Fold 3: train tss = 0.6350 : val tss = 0.0253 ::: train hss = 0.5315 : val hss = 0.0277
Fold 4: train tss = 0.4098 : val tss = 0.6340 ::: train hss = 0.3794 : val hss = 0.4858
mean cv TSS: 0.2597
mean cv HSS: 0.2213
448/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6966 : val tss = 0.3659 ::: train hss = 0.6782 : val hss = 0.2199
Fold 2: train tss = 0.2223 : val tss = 0.2189 ::: train hss = 0.2846 : val hss = 0.2751
Fold 3: train tss = 0.6113 : val tss = 0.0163 ::: train hss = 0.4914 : val hss = 0.0131
Fold 4: train tss = 0.5320 : val tss = 0.5585 ::: train hss = 0.4615 : val hss = 0.4613
mean cv TSS: 0.2319
mean cv HSS: 0.1939
449/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6125 : val tss = 0.2601 ::: train hss = 0.6684 : val hss = 0.1348
Fold 2: train tss = 0.4196 : val tss = 0.4757 ::: train hss = 0.3983 : val hss = 0.4556
Fold 3: train tss = 0.5512 : val tss = -0.0047 ::: train hss = 0.4879 : val hss = -0.0070
Fold 4: train tss = 0.4621 : val tss = 0.3159 ::: train hss = 0.4110 : val hss = 0.2951
mean cv TSS: 0.2094
mean cv HSS: 0.1757
450/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5631 : val tss = 0.2568 ::: train hss = 0.5388 : val hss = 0.2322
Fold 2: train tss = 0.3330 : val tss = 0.5093 ::: train hss = 0.3246 : val hss = 0.4064
Fold 3: train tss = 0.5133 : val tss = 0.0426 ::: train hss = 0.4330 : val hss = 0.0448
Fold 4: train tss = 0.4472 : val tss = 0.3405 ::: train hss = 0.3756 : val hss = 0.3390
mean cv TSS: 0.2298
mean cv HSS: 0.2045
451/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0163 : val tss = 0.0000 ::: train hss = 0.0315 : val hss = 0.0000

Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
452/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6571 : val tss = 0.3362 ::: train hss = 0.5809 : val hss = 0.2820
Fold 2: train tss = 0.5385 : val tss = 0.4848 ::: train hss = 0.4503 : val hss = 0.4187
Fold 3: train tss = 0.7052 : val tss = 0.0318 ::: train hss = 0.5390 : val hss = 0.0314
Fold 4: train tss = 0.5332 : val tss = 0.4780 ::: train hss = 0.4245 : val hss = 0.4599
mean cv TSS: 0.2662
mean cv HSS: 0.2384
453/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.2129 : val tss = 0.1457 ::: train hss = 0.2931 : val hss = 0.2257
Fold 3: train tss = 0.4824 : val tss = 0.0002 ::: train hss = 0.4232 : val hss = 0.0003
Fold 4: train tss = 0.3427 : val tss = 0.2918 ::: train hss = 0.3768 : val hss = 0.3106
mean cv TSS: 0.0875
mean cv HSS: 0.1073
454/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5912 : val tss = 0.2263 ::: train hss = 0.6913 : val hss = 0.1237
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6142 : val tss = 0.0545 ::: train hss = 0.4559 : val hss = 0.0644
Fold 4: train tss = 0.4978 : val tss = 0.3928 ::: train hss = 0.3860 : val hss = 0.4522
mean cv TSS: 0.1347
mean cv HSS: 0.1281
455/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.3631 : val tss = -0.0013 ::: train hss = 0.3715 : val hss = -0.0024
Fold 4: train tss = 0.2972 : val tss = 0.5489 ::: train hss = 0.3559 : val hss = 0.4390
mean cv TSS: 0.1095
mean cv HSS: 0.0873
456/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6675 : val tss = 0.3619 ::: train hss = 0.6147 : val hss = 0.2164
Fold 2: train tss = 0.4863 : val tss = 0.6958 ::: train hss = 0.4641 : val hss = 0.5093
Fold 3: train tss = 0.6622 : val tss = 0.0250 ::: train hss = 0.5071 : val hss = 0.0269
Fold 4: train tss = 0.5743 : val tss = 0.5496 ::: train hss = 0.4904 : val hss = 0.4569
mean cv TSS: 0.3265
mean cv HSS: 0.2419
457/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5495 : val tss = 0.2802 ::: train hss = 0.6325 : val hss = 0.2238
Fold 2: train tss = 0.3310 : val tss = 0.5115 ::: train hss = 0.3727 : val hss = 0.4501
Fold 3: train tss = 0.4804 : val tss = -0.0034 ::: train hss = 0.4574 : val hss = -0.0054
Fold 4: train tss = 0.3697 : val tss = 0.4695 ::: train hss = 0.3916 : val hss = 0.4381
mean cv TSS: 0.2515
mean cv HSS: 0.2213
458/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6270 : val tss = 0.3073 ::: train hss = 0.7070 : val hss = 0.1511
Fold 2: train tss = 0.5910 : val tss = 0.6827 ::: train hss = 0.3767 : val hss = 0.4561
Fold 3: train tss = 0.6290 : val tss = 0.0248 ::: train hss = 0.5355 : val hss = 0.0266
Fold 4: train tss = 0.6037 : val tss = 0.3829 ::: train hss = 0.4998 : val hss = 0.3843
mean cv TSS: 0.2795
mean cv HSS: 0.2036
459/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = -0.0019 : val tss = 0.0000 ::: train hss = -0.0021 : val hss = 0.0000
Fold 1: train tss = 0.5489 : val tss = 0.3541 ::: train hss = 0.6142 : val hss = 0.2160
Fold 2: train tss = 0.5136 : val tss = 0.6389 ::: train hss = 0.5116 : val hss = 0.5114
Fold 3: train tss = 0.5860 : val tss = 0.0287 ::: train hss = 0.5297 : val hss = 0.0365
Fold 4: train tss = 0.5038 : val tss = 0.5042 ::: train hss = 0.4648 : val hss = 0.4678
mean cv TSS: 0.3052
mean cv HSS: 0.2464
460/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6007 : val tss = 0.2396 ::: train hss = 0.7138 : val hss = 0.1411
Fold 2: train tss = 0.3886 : val tss = 0.3940 ::: train hss = 0.3709 : val hss = 0.3709
Fold 3: train tss = 0.6424 : val tss = 0.0118 ::: train hss = 0.5383 : val hss = 0.0110
Fold 4: train tss = 0.5669 : val tss = 0.4587 ::: train hss = 0.4966 : val hss = 0.4527
mean cv TSS: 0.2208
mean cv HSS: 0.1951
461/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4881 : val tss = 0.2285 ::: train hss = 0.6383 : val hss = 0.1101
Fold 2: train tss = 0.2941 : val tss = 0.3504 ::: train hss = 0.3161 : val hss = 0.3513
Fold 3: train tss = 0.6122 : val tss = 0.0173 ::: train hss = 0.5316 : val hss = 0.0198
Fold 4: train tss = 0.5751 : val tss = 0.3285 ::: train hss = 0.5027 : val hss = 0.3171
mean cv TSS: 0.1849
mean cv HSS: 0.1597
462/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6323 : val tss = 0.2941 ::: train hss = 0.6129 : val hss = 0.2643
Fold 2: train tss = 0.4329 : val tss = 0.6700 ::: train hss = 0.4256 : val hss = 0.4578
Fold 3: train tss = 0.6115 : val tss = 0.0423 ::: train hss = 0.5202 : val hss = 0.0438
Fold 4: train tss = 0.5494 : val tss = 0.4923 ::: train hss = 0.4543 : val hss = 0.4773
mean cv TSS: 0.2997
mean cv HSS: 0.2486
463/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3599 : val tss = 0.1929 ::: train hss = 0.4734 : val hss = 0.1636
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2479 : val tss = -0.0007 ::: train hss = 0.3111 : val hss = -0.0014
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0384
mean cv HSS: 0.0324
464/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5978 : val tss = 0.3482 ::: train hss = 0.6291 : val hss = 0.2666
Fold 2: train tss = 0.5408 : val tss = 0.6625 ::: train hss = 0.4923 : val hss = 0.4667
Fold 3: train tss = 0.7057 : val tss = 0.0240 ::: train hss = 0.5475 : val hss = 0.0249
Fold 4: train tss = 0.5763 : val tss = 0.5778 ::: train hss = 0.4776 : val hss = 0.4610
mean cv TSS: 0.3225
mean cv HSS: 0.2438
465/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5239 : val tss = -0.0019 ::: train hss = 0.4767 : val hss = -0.0021
Fold 4: train tss = 0.3229 : val tss = 0.4856 ::: train hss = 0.3413 : val hss = 0.4212
mean cv TSS: 0.0967
mean cv HSS: 0.0838
466/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6167 : val tss = 0.2711 ::: train hss = 0.6632 : val hss = 0.1263
Fold 2: train tss = 0.4031 : val tss = 0.5532 ::: train hss = 0.3325 : val hss = 0.3834
Fold 3: train tss = 0.7344 : val tss = 0.0569 ::: train hss = 0.5089 : val hss = 0.0396
Fold 4: train tss = 0.5959 : val tss = 0.4967 ::: train hss = 0.4702 : val hss = 0.3947
mean cv TSS: 0.2756
mean cv HSS: 0.1888
467/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5702 : val tss = -0.0051 ::: train hss = 0.4805 : val hss = -0.0074
Fold 4: train tss = 0.4107 : val tss = 0.3034 ::: train hss = 0.4180 : val hss = 0.3031
mean cv TSS: 0.0597
mean cv HSS: 0.0591
468/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0999 : val tss = 0.0841 ::: train hss = 0.1737 : val hss = 0.1286
Fold 1: train tss = 0.6292 : val tss = 0.3051 ::: train hss = 0.6453 : val hss = 0.1848
Fold 2: train tss = 0.2669 : val tss = 0.5870 ::: train hss = 0.3380 : val hss = 0.5023
Fold 3: train tss = 0.6142 : val tss = 0.0161 ::: train hss = 0.5223 : val hss = 0.0277
Fold 4: train tss = 0.4583 : val tss = 0.5578 ::: train hss = 0.3864 : val hss = 0.4466
mean cv TSS: 0.3100
mean cv HSS: 0.2580
469/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5825 : val tss = 0.3037 ::: train hss = 0.5772 : val hss = 0.1925
Fold 2: train tss = 0.1870 : val tss = 0.4290 ::: train hss = 0.2527 : val hss = 0.4152
Fold 3: train tss = 0.4471 : val tss = -0.0039 ::: train hss = 0.4244 : val hss = -0.0060
Fold 4: train tss = 0.3514 : val tss = 0.6390 ::: train hss = 0.3777 : val hss = 0.4880
mean cv TSS: 0.2736
mean cv HSS: 0.2179
470/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6800 : val tss = 0.3382 ::: train hss = 0.7055 : val hss = 0.1741
Fold 2: train tss = 0.5868 : val tss = 0.6418 ::: train hss = 0.4852 : val hss = 0.4653
Fold 3: train tss = 0.6629 : val tss = 0.0886 ::: train hss = 0.5569 : val hss = 0.0695
Fold 4: train tss = 0.5516 : val tss = 0.5071 ::: train hss = 0.5048 : val hss = 0.4418
mean cv TSS: 0.3151
mean cv HSS: 0.2301
471/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6215 : val tss = 0.3336 ::: train hss = 0.6732 : val hss = 0.2037
Fold 2: train tss = 0.4756 : val tss = 0.5941 ::: train hss = 0.4450 : val hss = 0.4936
Fold 3: train tss = 0.6061 : val tss = -0.0060 ::: train hss = 0.4945 : val hss = -0.0083
Fold 4: train tss = 0.4347 : val tss = 0.6130 ::: train hss = 0.4351 : val hss = 0.4830
mean cv TSS: 0.3069
mean cv HSS: 0.2344
472/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6501 : val tss = 0.3379 ::: train hss = 0.7387 : val hss = 0.1779
Fold 2: train tss = 0.3334 : val tss = 0.4824 ::: train hss = 0.3610 : val hss = 0.4325
Fold 3: train tss = 0.6975 : val tss = 0.0121 ::: train hss = 0.5255 : val hss = 0.0113

Fold 4: train tss = 0.6205 : val tss = 0.6063 ::: train hss = 0.4574 : val hss = 0.4764
mean cv TSS: 0.2877
mean cv HSS: 0.2196
473/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5940 : val tss = 0.2364 ::: train hss = 0.6451 : val hss = 0.1612
Fold 2: train tss = 0.2143 : val tss = 0.2599 ::: train hss = 0.2896 : val hss = 0.3083
Fold 3: train tss = 0.5755 : val tss = -0.0038 ::: train hss = 0.5122 : val hss = -0.0059
Fold 4: train tss = 0.5120 : val tss = 0.2439 ::: train hss = 0.4550 : val hss = 0.2779
mean cv TSS: 0.1473
mean cv HSS: 0.1483
474/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3992 : val tss = 0.3442 ::: train hss = 0.4795 : val hss = 0.2448
Fold 2: train tss = 0.4794 : val tss = 0.5796 ::: train hss = 0.3233 : val hss = 0.4074
Fold 3: train tss = 0.5810 : val tss = 0.0393 ::: train hss = 0.4265 : val hss = 0.0536
Fold 4: train tss = 0.4904 : val tss = 0.4856 ::: train hss = 0.4156 : val hss = 0.4618
mean cv TSS: 0.2897
mean cv HSS: 0.2335
475/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.2382 : val tss = 0.1585 ::: train hss = 0.3510 : val hss = 0.1590
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.1728 : val tss = 0.0074 ::: train hss = 0.2426 : val hss = 0.0132
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0332
mean cv HSS: 0.0344
476/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7497 : val tss = 0.3060 ::: train hss = 0.5896 : val hss = 0.2404
Fold 2: train tss = 0.5471 : val tss = 0.6832 ::: train hss = 0.5250 : val hss = 0.4836
Fold 3: train tss = 0.7159 : val tss = 0.0303 ::: train hss = 0.4911 : val hss = 0.0284
Fold 4: train tss = 0.4563 : val tss = 0.5713 ::: train hss = 0.4818 : val hss = 0.4277
mean cv TSS: 0.3182
mean cv HSS: 0.2360
477/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.2064 : val tss = 0.0000 ::: train hss = 0.3093 : val hss = 0.0000
Fold 2: train tss = 0.2423 : val tss = 0.3832 ::: train hss = 0.3140 : val hss = 0.3854
Fold 3: train tss = 0.5626 : val tss = 0.0281 ::: train hss = 0.4257 : val hss = 0.0347
Fold 4: train tss = 0.2352 : val tss = 0.5718 ::: train hss = 0.2947 : val hss = 0.4696
mean cv TSS: 0.1966
mean cv HSS: 0.1779
478/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6002 : val tss = 0.2921 ::: train hss = 0.6982 : val hss = 0.1257
Fold 2: train tss = 0.5888 : val tss = 0.5918 ::: train hss = 0.3854 : val hss = 0.4121
Fold 3: train tss = 0.7427 : val tss = 0.0271 ::: train hss = 0.4924 : val hss = 0.0229
Fold 4: train tss = 0.6244 : val tss = 0.5503 ::: train hss = 0.4938 : val hss = 0.4388
mean cv TSS: 0.2923
mean cv HSS: 0.1999
479/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5225 : val tss = 0.2497 ::: train hss = 0.6142 : val hss = 0.1596
Fold 2: train tss = 0.0596 : val tss = 0.0110 ::: train hss = 0.1049 : val hss = 0.0215
Fold 3: train tss = 0.5557 : val tss = -0.0035 ::: train hss = 0.4860 : val hss = -0.0056
Fold 4: train tss = 0.2737 : val tss = 0.5859 ::: train hss = 0.3268 : val hss = 0.4969
mean cv TSS: 0.1686
mean cv HSS: 0.1345
480/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0499 : val tss = 0.0025 ::: train hss = 0.0907 : val hss = 0.0046
Fold 1: train tss = 0.6462 : val tss = 0.3201 ::: train hss = 0.5399 : val hss = 0.1280
Fold 2: train tss = 0.5097 : val tss = 0.6298 ::: train hss = 0.4855 : val hss = 0.5086
Fold 3: train tss = 0.5941 : val tss = 0.0230 ::: train hss = 0.5175 : val hss = 0.0230
Fold 4: train tss = 0.5661 : val tss = 0.5498 ::: train hss = 0.4904 : val hss = 0.5118
mean cv TSS: 0.3051
mean cv HSS: 0.2352
481/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5730 : val tss = 0.2401 ::: train hss = 0.6754 : val hss = 0.1543
Fold 2: train tss = 0.2725 : val tss = 0.4641 ::: train hss = 0.3235 : val hss = 0.4282
Fold 3: train tss = 0.4555 : val tss = -0.0018 ::: train hss = 0.4385 : val hss = -0.0032
Fold 4: train tss = 0.3753 : val tss = 0.5935 ::: train hss = 0.3960 : val hss = 0.4479
mean cv TSS: 0.2592
mean cv HSS: 0.2054
482/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7253 : val tss = 0.3991 ::: train hss = 0.7370 : val hss = 0.2442
Fold 2: train tss = 0.5532 : val tss = 0.6002 ::: train hss = 0.5591 : val hss = 0.5008
Fold 3: train tss = 0.6887 : val tss = 0.0270 ::: train hss = 0.5322 : val hss = 0.0227
Fold 4: train tss = 0.6181 : val tss = 0.5059 ::: train hss = 0.5307 : val hss = 0.4578
mean cv TSS: 0.3064
mean cv HSS: 0.2451
483/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6177 : val tss = 0.3399 ::: train hss = 0.6930 : val hss = 0.2011
Fold 2: train tss = 0.5153 : val tss = 0.6163 ::: train hss = 0.4882 : val hss = 0.4997
Fold 3: train tss = 0.6143 : val tss = -0.0073 ::: train hss = 0.5230 : val hss = -0.0095
Fold 4: train tss = 0.5359 : val tss = 0.5091 ::: train hss = 0.4679 : val hss = 0.4251
mean cv TSS: 0.2916
mean cv HSS: 0.2233
484/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6193 : val tss = 0.3359 ::: train hss = 0.7438 : val hss = 0.1666
Fold 2: train tss = 0.5379 : val tss = 0.5879 ::: train hss = 0.5005 : val hss = 0.4688
Fold 3: train tss = 0.6858 : val tss = 0.0396 ::: train hss = 0.5513 : val hss = 0.0372
Fold 4: train tss = 0.6461 : val tss = 0.3353 ::: train hss = 0.5338 : val hss = 0.3573
mean cv TSS: 0.2597
mean cv HSS: 0.2060
485/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6238 : val tss = 0.3202 ::: train hss = 0.7451 : val hss = 0.1604
Fold 2: train tss = 0.3493 : val tss = 0.4190 ::: train hss = 0.3624 : val hss = 0.3985
Fold 3: train tss = 0.6319 : val tss = -0.0062 ::: train hss = 0.5272 : val hss = -0.0085
Fold 4: train tss = 0.5185 : val tss = 0.5806 ::: train hss = 0.4824 : val hss = 0.4491
mean cv TSS: 0.2627
mean cv HSS: 0.1999
486/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = -0.0006 ::: train hss = 0.0000 : val hss = -0.0009
Fold 1: train tss = 0.4669 : val tss = 0.2956 ::: train hss = 0.5361 : val hss = 0.2497
Fold 2: train tss = 0.3462 : val tss = 0.5791 ::: train hss = 0.4291 : val hss = 0.4495
Fold 3: train tss = 0.5690 : val tss = 0.0258 ::: train hss = 0.4941 : val hss = 0.0288
Fold 4: train tss = 0.5049 : val tss = 0.4879 ::: train hss = 0.4625 : val hss = 0.4828
mean cv TSS: 0.2776
mean cv HSS: 0.2420
487/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4723 : val tss = 0.2426 ::: train hss = 0.5596 : val hss = 0.1547
Fold 2: train tss = 0.0148 : val tss = 0.0818 ::: train hss = 0.0285 : val hss = 0.1430
Fold 3: train tss = 0.2776 : val tss = 0.0061 ::: train hss = 0.3231 : val hss = 0.0099
Fold 4: train tss = 0.1049 : val tss = 0.5029 ::: train hss = 0.1677 : val hss = 0.4322
mean cv TSS: 0.1667
mean cv HSS: 0.1480
488/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6973 : val tss = 0.3199 ::: train hss = 0.6973 : val hss = 0.1804
Fold 2: train tss = 0.6511 : val tss = 0.6492 ::: train hss = 0.5578 : val hss = 0.4916
Fold 3: train tss = 0.7203 : val tss = 0.0365 ::: train hss = 0.5581 : val hss = 0.0436
Fold 4: train tss = 0.6041 : val tss = 0.5590 ::: train hss = 0.5456 : val hss = 0.4503
mean cv TSS: 0.3129
mean cv HSS: 0.2332
489/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5270 : val tss = 0.3004 ::: train hss = 0.6179 : val hss = 0.2155
Fold 2: train tss = 0.3695 : val tss = 0.4883 ::: train hss = 0.4313 : val hss = 0.4301
Fold 3: train tss = 0.4989 : val tss = 0.0268 ::: train hss = 0.4818 : val hss = 0.0311
Fold 4: train tss = 0.3720 : val tss = 0.5521 ::: train hss = 0.3814 : val hss = 0.4288
mean cv TSS: 0.2735
mean cv HSS: 0.2211
490/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7423 : val tss = 0.3723 ::: train hss = 0.5396 : val hss = 0.2429
Fold 2: train tss = 0.5982 : val tss = 0.5667 ::: train hss = 0.4915 : val hss = 0.4251
Fold 3: train tss = 0.6944 : val tss = 0.0408 ::: train hss = 0.5791 : val hss = 0.0600
Fold 4: train tss = 0.6189 : val tss = 0.5784 ::: train hss = 0.5193 : val hss = 0.4216
mean cv TSS: 0.3116
mean cv HSS: 0.2299
491/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5772 : val tss = 0.2542 ::: train hss = 0.6678 : val hss = 0.1689
Fold 2: train tss = 0.1776 : val tss = 0.3122 ::: train hss = 0.2595 : val hss = 0.3433
Fold 3: train tss = 0.5993 : val tss = -0.0039 ::: train hss = 0.4919 : val hss = -0.0060
Fold 4: train tss = 0.4085 : val tss = 0.4762 ::: train hss = 0.4176 : val hss = 0.4042
mean cv TSS: 0.2077
mean cv HSS: 0.1821
492/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.1498 : val tss = 0.0074 ::: train hss = 0.2396 : val hss = 0.0113
Fold 1: train tss = 0.6323 : val tss = 0.3118 ::: train hss = 0.6129 : val hss = 0.1836
Fold 2: train tss = 0.4953 : val tss = 0.6431 ::: train hss = 0.4122 : val hss = 0.5165
Fold 3: train tss = 0.5548 : val tss = 0.0370 ::: train hss = 0.4739 : val hss = 0.0320
Fold 4: train tss = 0.5157 : val tss = 0.4180 ::: train hss = 0.4440 : val hss = 0.4026
mean cv TSS: 0.2835
mean cv HSS: 0.2292
493/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6100 : val tss = 0.2858 ::: train hss = 0.6045 : val hss = 0.1338
Fold 2: train tss = 0.1262 : val tss = 0.4086 ::: train hss = 0.1927 : val hss = 0.3980
Fold 3: train tss = 0.4324 : val tss = -0.0044 ::: train hss = 0.4105 : val hss = -0.0066

Fold 4: train tss = 0.3355 : val tss = 0.6740 ::: train hss = 0.3713 : val hss = 0.4759
mean cv TSS: 0.2728
mean cv HSS: 0.2002
494/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0097 ::: train hss = 0.0000 : val hss = 0.0190
Fold 1: train tss = 0.6794 : val tss = 0.2820 ::: train hss = 0.6887 : val hss = 0.1512
Fold 2: train tss = 0.3903 : val tss = 0.4559 ::: train hss = 0.4719 : val hss = 0.4567
Fold 3: train tss = 0.7248 : val tss = 0.0265 ::: train hss = 0.5389 : val hss = 0.0305
Fold 4: train tss = 0.6467 : val tss = 0.5643 ::: train hss = 0.4788 : val hss = 0.5001
mean cv TSS: 0.2677
mean cv HSS: 0.2315
495/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5944 : val tss = 0.3969 ::: train hss = 0.6551 : val hss = 0.2454
Fold 2: train tss = 0.3607 : val tss = 0.4934 ::: train hss = 0.4106 : val hss = 0.4620
Fold 3: train tss = 0.5454 : val tss = 0.0104 ::: train hss = 0.5046 : val hss = 0.0131
Fold 4: train tss = 0.3977 : val tss = 0.7168 ::: train hss = 0.4181 : val hss = 0.4964
mean cv TSS: 0.3235
mean cv HSS: 0.2434
496/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.1568 ::: train hss = 0.0000 : val hss = 0.2144
Fold 1: train tss = 0.6853 : val tss = 0.3254 ::: train hss = 0.7335 : val hss = 0.1865
Fold 2: train tss = 0.4879 : val tss = 0.5796 ::: train hss = 0.4618 : val hss = 0.4552
Fold 3: train tss = 0.7115 : val tss = 0.0309 ::: train hss = 0.5969 : val hss = 0.0296
Fold 4: train tss = 0.6465 : val tss = 0.5621 ::: train hss = 0.4927 : val hss = 0.4540
mean cv TSS: 0.3310
mean cv HSS: 0.2679
497/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.2669 : val tss = 0.1169 ::: train hss = 0.4198 : val hss = 0.0675
Fold 2: train tss = 0.3939 : val tss = 0.5083 ::: train hss = 0.3712 : val hss = 0.4441
Fold 3: train tss = 0.4511 : val tss = -0.0015 ::: train hss = 0.4849 : val hss = -0.0026
Fold 4: train tss = 0.5366 : val tss = 0.6211 ::: train hss = 0.4015 : val hss = 0.4731
mean cv TSS: 0.2490
mean cv HSS: 0.1964
498/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.1286 ::: train hss = 0.0000 : val hss = 0.1636
Fold 1: train tss = 0.5723 : val tss = 0.3056 ::: train hss = 0.6554 : val hss = 0.2029
Fold 2: train tss = 0.4900 : val tss = 0.5276 ::: train hss = 0.3348 : val hss = 0.3928
Fold 3: train tss = 0.5467 : val tss = -0.0039 ::: train hss = 0.4125 : val hss = -0.0060
Fold 4: train tss = 0.4786 : val tss = 0.4620 ::: train hss = 0.4100 : val hss = 0.4263
mean cv TSS: 0.2840
mean cv HSS: 0.2359
499/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4401 : val tss = 0.2429 ::: train hss = 0.5201 : val hss = 0.1510
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2276 : val tss = 0.0038 ::: train hss = 0.2899 : val hss = 0.0054
Fold 4: train tss = 0.0021 : val tss = 0.5183 ::: train hss = 0.0040 : val hss = 0.4106
mean cv TSS: 0.1530
mean cv HSS: 0.1134
500/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7421 : val tss = 0.3728 ::: train hss = 0.6119 : val hss = 0.2516
Fold 2: train tss = 0.5974 : val tss = 0.6517 ::: train hss = 0.5438 : val hss = 0.4950
Fold 3: train tss = 0.7038 : val tss = 0.0027 ::: train hss = 0.5634 : val hss = 0.0036
Fold 4: train tss = 0.5796 : val tss = 0.7056 ::: train hss = 0.5413 : val hss = 0.5067
mean cv TSS: 0.3466
mean cv HSS: 0.2514
501/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5263 : val tss = 0.3377 ::: train hss = 0.5980 : val hss = 0.2411
Fold 2: train tss = 0.2970 : val tss = 0.4111 ::: train hss = 0.3642 : val hss = 0.4024
Fold 3: train tss = 0.5831 : val tss = 0.0298 ::: train hss = 0.4339 : val hss = 0.0399
Fold 4: train tss = 0.2985 : val tss = 0.6013 ::: train hss = 0.3442 : val hss = 0.4774
mean cv TSS: 0.2760
mean cv HSS: 0.2322
502/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7428 : val tss = 0.3468 ::: train hss = 0.7312 : val hss = 0.1999
Fold 2: train tss = 0.5428 : val tss = 0.6384 ::: train hss = 0.4755 : val hss = 0.4792
Fold 3: train tss = 0.7183 : val tss = 0.0587 ::: train hss = 0.3839 : val hss = 0.0569
Fold 4: train tss = 0.5474 : val tss = 0.6329 ::: train hss = 0.5135 : val hss = 0.4436
mean cv TSS: 0.3354
mean cv HSS: 0.2359
503/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5763 : val tss = 0.2872 ::: train hss = 0.6433 : val hss = 0.1558
Fold 2: train tss = 0.1736 : val tss = 0.3135 ::: train hss = 0.2526 : val hss = 0.3571
Fold 3: train tss = 0.6140 : val tss = -0.0033 ::: train hss = 0.5094 : val hss = -0.0053
Fold 4: train tss = 0.3457 : val tss = 0.6690 ::: train hss = 0.3727 : val hss = 0.4450
mean cv TSS: 0.2533
mean cv HSS: 0.1905
504/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6187 : val tss = 0.2570 ::: train hss = 0.7234 : val hss = 0.1699
Fold 2: train tss = 0.4474 : val tss = 0.5450 ::: train hss = 0.3943 : val hss = 0.5204
Fold 3: train tss = 0.5977 : val tss = 0.0285 ::: train hss = 0.5027 : val hss = 0.0357
Fold 4: train tss = 0.4735 : val tss = 0.4739 ::: train hss = 0.4464 : val hss = 0.4337
mean cv TSS: 0.2609
mean cv HSS: 0.2319
505/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4627 : val tss = 0.2963 ::: train hss = 0.5381 : val hss = 0.2260
Fold 2: train tss = 0.2679 : val tss = 0.5274 ::: train hss = 0.3128 : val hss = 0.4639
Fold 3: train tss = 0.3574 : val tss = -0.0016 ::: train hss = 0.3598 : val hss = -0.0028
Fold 4: train tss = 0.2700 : val tss = 0.4017 ::: train hss = 0.3311 : val hss = 0.3931
mean cv TSS: 0.2448
mean cv HSS: 0.2160
506/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = -0.1186 : val tss = 0.2186 ::: train hss = -0.0021 : val hss = 0.0408
Fold 1: train tss = 0.5262 : val tss = 0.3903 ::: train hss = 0.5964 : val hss = 0.2817
Fold 2: train tss = 0.4019 : val tss = 0.5793 ::: train hss = 0.3797 : val hss = 0.5197
Fold 3: train tss = 0.6014 : val tss = 0.0171 ::: train hss = 0.4602 : val hss = 0.0109
Fold 4: train tss = 0.5053 : val tss = 0.2775 ::: train hss = 0.4543 : val hss = 0.3665
mean cv TSS: 0.2965
mean cv HSS: 0.2439
507/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.1245 : val tss = 0.2479 ::: train hss = 0.1917 : val hss = 0.3168
Fold 3: train tss = 0.5939 : val tss = 0.0298 ::: train hss = 0.5222 : val hss = 0.0399
Fold 4: train tss = 0.5354 : val tss = 0.4239 ::: train hss = 0.4698 : val hss = 0.4089
mean cv TSS: 0.1403
mean cv HSS: 0.1531
508/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6057 : val tss = 0.0379 ::: train hss = 0.7335 : val hss = 0.0181
Fold 2: train tss = 0.2760 : val tss = 0.3919 ::: train hss = 0.3077 : val hss = 0.4452
Fold 3: train tss = 0.6101 : val tss = 0.0189 ::: train hss = 0.4790 : val hss = 0.0231
Fold 4: train tss = 0.5693 : val tss = 0.4096 ::: train hss = 0.4919 : val hss = 0.3994
mean cv TSS: 0.1717
mean cv HSS: 0.1772
509/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5358 : val tss = 0.2904 ::: train hss = 0.6167 : val hss = 0.1262
Fold 2: train tss = 0.0914 : val tss = 0.0000 ::: train hss = 0.1519 : val hss = 0.0000
Fold 3: train tss = 0.4296 : val tss = 0.0257 ::: train hss = 0.4354 : val hss = 0.0456
Fold 4: train tss = 0.5344 : val tss = 0.3778 ::: train hss = 0.5104 : val hss = 0.3693
mean cv TSS: 0.1388
mean cv HSS: 0.1082
510/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5724 : val tss = 0.3027 ::: train hss = 0.5488 : val hss = 0.2297
Fold 2: train tss = 0.4849 : val tss = 0.5772 ::: train hss = 0.3836 : val hss = 0.4560
Fold 3: train tss = 0.5531 : val tss = 0.0382 ::: train hss = 0.4734 : val hss = 0.0344
Fold 4: train tss = 0.5151 : val tss = 0.3777 ::: train hss = 0.4501 : val hss = 0.3800
mean cv TSS: 0.2592
mean cv HSS: 0.2200
511/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.1664 : val tss = 0.0000 ::: train hss = 0.2382 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
512/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.4733 : val tss = 0.5744 ::: train hss = 0.4797 : val hss = 0.5063
Fold 3: train tss = 0.6572 : val tss = 0.0302 ::: train hss = 0.5014 : val hss = 0.0282
Fold 4: train tss = 0.5491 : val tss = 0.5224 ::: train hss = 0.4625 : val hss = 0.3984
mean cv TSS: 0.2254
mean cv HSS: 0.1866
513/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.1353 : val tss = 0.0064 ::: train hss = 0.0030 : val hss = 0.0059
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.3655 : val tss = -0.0022 ::: train hss = 0.4043 : val hss = -0.0038
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0008
mean cv HSS: 0.0004
514/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000

Fold 4: train tss = 0.5276 : val tss = 0.5010 ::: train hss = 0.3836 : val hss = 0.4212
mean cv TSS: 0.1002
mean cv HSS: 0.0842
515/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
516/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0499 : val tss = 0.0262 ::: train hss = 0.0907 : val hss = 0.0444
Fold 1: train tss = 0.6235 : val tss = 0.3054 ::: train hss = 0.6138 : val hss = 0.1484
Fold 2: train tss = 0.2018 : val tss = 0.4611 ::: train hss = 0.2662 : val hss = 0.4459
Fold 3: train tss = 0.5189 : val tss = 0.0220 ::: train hss = 0.4337 : val hss = 0.0316
Fold 4: train tss = 0.4133 : val tss = 0.1261 ::: train hss = 0.3937 : val hss = 0.1596
mean cv TSS: 0.1882
mean cv HSS: 0.1660
517/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3902 : val tss = 0.2870 ::: train hss = 0.4725 : val hss = 0.2211
Fold 2: train tss = 0.1841 : val tss = 0.2043 ::: train hss = 0.2279 : val hss = 0.2942
Fold 3: train tss = 0.3383 : val tss = -0.0011 ::: train hss = 0.3508 : val hss = -0.0020
Fold 4: train tss = 0.2333 : val tss = 0.6199 ::: train hss = 0.2814 : val hss = 0.4724
mean cv TSS: 0.2220
mean cv HSS: 0.1971
518/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = -0.0007 : val tss = 0.0000 ::: train hss = -0.0011 : val hss = 0.0000
Fold 1: train tss = 0.6298 : val tss = 0.3837 ::: train hss = 0.6596 : val hss = 0.2971
Fold 2: train tss = 0.4580 : val tss = 0.5821 ::: train hss = 0.4277 : val hss = 0.4850
Fold 3: train tss = 0.5907 : val tss = 0.0546 ::: train hss = 0.4730 : val hss = 0.0460
Fold 4: train tss = 0.5636 : val tss = 0.3714 ::: train hss = 0.4658 : val hss = 0.3497
mean cv TSS: 0.2783
mean cv HSS: 0.2356
519/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5179 : val tss = 0.3301 ::: train hss = 0.6072 : val hss = 0.2593
Fold 2: train tss = 0.2981 : val tss = 0.4628 ::: train hss = 0.3563 : val hss = 0.4237
Fold 3: train tss = 0.5032 : val tss = -0.0038 ::: train hss = 0.4719 : val hss = -0.0059
Fold 4: train tss = 0.3309 : val tss = 0.5030 ::: train hss = 0.3524 : val hss = 0.4326
mean cv TSS: 0.2584
mean cv HSS: 0.2219
520/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5986 : val tss = 0.2496 ::: train hss = 0.6517 : val hss = 0.1110
Fold 2: train tss = 0.4211 : val tss = 0.5487 ::: train hss = 0.3954 : val hss = 0.4868
Fold 3: train tss = 0.6026 : val tss = 0.0312 ::: train hss = 0.4536 : val hss = 0.0227
Fold 4: train tss = 0.5246 : val tss = 0.5858 ::: train hss = 0.4396 : val hss = 0.4432
mean cv TSS: 0.2830
mean cv HSS: 0.2127
521/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5107 : val tss = 0.3915 ::: train hss = 0.5374 : val hss = 0.1994
Fold 2: train tss = 0.1958 : val tss = 0.2945 ::: train hss = 0.2574 : val hss = 0.2980
Fold 3: train tss = 0.5774 : val tss = -0.0030 ::: train hss = 0.5078 : val hss = -0.0050
Fold 4: train tss = 0.3743 : val tss = 0.4664 ::: train hss = 0.3991 : val hss = 0.4437
mean cv TSS: 0.2299
mean cv HSS: 0.1872
522/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5902 : val tss = 0.3380 ::: train hss = 0.5550 : val hss = 0.2502
Fold 2: train tss = 0.3866 : val tss = 0.5246 ::: train hss = 0.3137 : val hss = 0.3985
Fold 3: train tss = 0.3925 : val tss = 0.0386 ::: train hss = 0.3666 : val hss = 0.0507
Fold 4: train tss = 0.3528 : val tss = 0.5030 ::: train hss = 0.3295 : val hss = 0.4578
mean cv TSS: 0.2808
mean cv HSS: 0.2314
523/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0380 : val tss = 0.0000 ::: train hss = 0.0708 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0000
mean cv HSS: 0.0000
524/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4060 : val tss = 0.3571 ::: train hss = 0.4421 : val hss = 0.2605
Fold 2: train tss = 0.4323 : val tss = 0.4185 ::: train hss = 0.4595 : val hss = 0.4564
Fold 3: train tss = 0.5634 : val tss = 0.0247 ::: train hss = 0.4831 : val hss = 0.0194
Fold 4: train tss = 0.6488 : val tss = 0.4825 ::: train hss = 0.3915 : val hss = 0.3898
mean cv TSS: 0.2566
mean cv HSS: 0.2252
525/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.1960 : val tss = 0.2889 ::: train hss = 0.2589 : val hss = 0.3438
Fold 3: train tss = 0.3724 : val tss = -0.0037 ::: train hss = 0.3528 : val hss = -0.0057
Fold 4: train tss = 0.1930 : val tss = 0.0000 ::: train hss = 0.2567 : val hss = 0.0000
mean cv TSS: 0.0571
mean cv HSS: 0.0676
526/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5413 : val tss = 0.3020 ::: train hss = 0.4601 : val hss = 0.1322
Fold 2: train tss = 0.2943 : val tss = 0.4880 ::: train hss = 0.3036 : val hss = 0.4086
Fold 3: train tss = 0.5562 : val tss = 0.0156 ::: train hss = 0.5008 : val hss = 0.0122
Fold 4: train tss = 0.5543 : val tss = 0.5673 ::: train hss = 0.4424 : val hss = 0.4769
mean cv TSS: 0.2746
mean cv HSS: 0.2060
527/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4694 : val tss = 0.2690 ::: train hss = 0.6032 : val hss = 0.1449
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0538
mean cv HSS: 0.0290
528/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6273 : val tss = 0.2863 ::: train hss = 0.7165 : val hss = 0.1866
Fold 2: train tss = 0.4427 : val tss = 0.6334 ::: train hss = 0.4553 : val hss = 0.5527
Fold 3: train tss = 0.5789 : val tss = 0.0385 ::: train hss = 0.4956 : val hss = 0.0349
Fold 4: train tss = 0.5484 : val tss = 0.4360 ::: train hss = 0.4678 : val hss = 0.4391
mean cv TSS: 0.2789
mean cv HSS: 0.2426
529/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6026 : val tss = 0.3017 ::: train hss = 0.6387 : val hss = 0.1646
Fold 2: train tss = 0.2297 : val tss = 0.4429 ::: train hss = 0.2902 : val hss = 0.4229
Fold 3: train tss = 0.4620 : val tss = -0.0035 ::: train hss = 0.4514 : val hss = -0.0056
Fold 4: train tss = 0.3365 : val tss = 0.5564 ::: train hss = 0.3735 : val hss = 0.4467
mean cv TSS: 0.2595
mean cv HSS: 0.2057
530/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = -0.0077 : val tss = 0.0000 ::: train hss = -0.0037 : val hss = 0.0000
Fold 1: train tss = 0.6172 : val tss = 0.3211 ::: train hss = 0.6786 : val hss = 0.2232
Fold 2: train tss = 0.5677 : val tss = 0.6674 ::: train hss = 0.4557 : val hss = 0.5151
Fold 3: train tss = 0.6577 : val tss = 0.0214 ::: train hss = 0.5369 : val hss = 0.0202
Fold 4: train tss = 0.5708 : val tss = 0.5220 ::: train hss = 0.4593 : val hss = 0.4401
mean cv TSS: 0.3064
mean cv HSS: 0.2397
531/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4134 : val tss = 0.3032 ::: train hss = 0.5061 : val hss = 0.2236
Fold 2: train tss = 0.4684 : val tss = 0.6212 ::: train hss = 0.5098 : val hss = 0.5540
Fold 3: train tss = 0.6139 : val tss = 0.0309 ::: train hss = 0.5088 : val hss = 0.0296
Fold 4: train tss = 0.4911 : val tss = 0.4942 ::: train hss = 0.4696 : val hss = 0.4044
mean cv TSS: 0.2899
mean cv HSS: 0.2423
532/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = -0.0045 : val tss = 0.0000 ::: train hss = -0.0031 : val hss = 0.0000
Fold 1: train tss = 0.6164 : val tss = 0.2863 ::: train hss = 0.6549 : val hss = 0.1264
Fold 2: train tss = 0.4599 : val tss = 0.5655 ::: train hss = 0.4115 : val hss = 0.4657
Fold 3: train tss = 0.6594 : val tss = 0.0153 ::: train hss = 0.5495 : val hss = 0.0162
Fold 4: train tss = 0.5194 : val tss = 0.5162 ::: train hss = 0.4499 : val hss = 0.4485
mean cv TSS: 0.2767
mean cv HSS: 0.2114
533/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5812 : val tss = 0.2090 ::: train hss = 0.6553 : val hss = 0.1341
Fold 2: train tss = 0.3454 : val tss = 0.3719 ::: train hss = 0.3421 : val hss = 0.3606
Fold 3: train tss = 0.6055 : val tss = 0.0082 ::: train hss = 0.5303 : val hss = 0.0093
Fold 4: train tss = 0.4950 : val tss = 0.4718 ::: train hss = 0.4776 : val hss = 0.3990
mean cv TSS: 0.2122
mean cv HSS: 0.1806
534/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6178 : val tss = 0.3665 ::: train hss = 0.5835 : val hss = 0.2565
Fold 2: train tss = 0.4328 : val tss = 0.5685 ::: train hss = 0.3742 : val hss = 0.4089
Fold 3: train tss = 0.5922 : val tss = 0.0287 ::: train hss = 0.4774 : val hss = 0.0365
Fold 4: train tss = 0.4479 : val tss = 0.6582 ::: train hss = 0.4350 : val hss = 0.4396
mean cv TSS: 0.3244
mean cv HSS: 0.2283
535/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3729 : val tss = 0.2097 ::: train hss = 0.4736 : val hss = 0.1645
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.1525 : val tss = -0.0012 ::: train hss = 0.2177 : val hss = -0.0022

Fold 4: train tss = 0.0237 : val tss = 0.0000 ::: train hss = 0.0453 : val hss = 0.0000
mean cv TSS: 0.0417
mean cv HSS: 0.0325
536/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = -0.0083 : val tss = 0.0000 ::: train hss = -0.0037 : val hss = 0.0000
Fold 1: train tss = 0.5405 : val tss = 0.3018 ::: train hss = 0.6254 : val hss = 0.2125
Fold 2: train tss = 0.4956 : val tss = 0.6000 ::: train hss = 0.4688 : val hss = 0.4728
Fold 3: train tss = 0.6936 : val tss = 0.0274 ::: train hss = 0.5378 : val hss = 0.0233
Fold 4: train tss = 0.6422 : val tss = 0.3412 ::: train hss = 0.5093 : val hss = 0.3548
mean cv TSS: 0.2541
mean cv HSS: 0.2127
537/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.1673 : val tss = 0.1911 ::: train hss = 0.2401 : val hss = 0.2782
Fold 3: train tss = 0.5573 : val tss = 0.0251 ::: train hss = 0.4750 : val hss = 0.0272
Fold 4: train tss = 0.2897 : val tss = 0.4829 ::: train hss = 0.3417 : val hss = 0.4214
mean cv TSS: 0.1398
mean cv HSS: 0.1454
538/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5420 : val tss = 0.1990 ::: train hss = 0.6691 : val hss = 0.1014
Fold 2: train tss = 0.4294 : val tss = 0.5413 ::: train hss = 0.3608 : val hss = 0.4162
Fold 3: train tss = 0.6957 : val tss = 0.0336 ::: train hss = 0.4816 : val hss = 0.0262
Fold 4: train tss = 0.5905 : val tss = 0.3793 ::: train hss = 0.4688 : val hss = 0.3609
mean cv TSS: 0.2307
mean cv HSS: 0.1809
539/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4247 : val tss = 0.2197 ::: train hss = 0.5776 : val hss = 0.1414
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2268 : val tss = 0.0000 ::: train hss = 0.2946 : val hss = 0.0000
Fold 4: train tss = 0.4237 : val tss = 0.4511 ::: train hss = 0.4010 : val hss = 0.3696
mean cv TSS: 0.1342
mean cv HSS: 0.1022
540/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.1492 : val tss = 0.0807 ::: train hss = 0.1989 : val hss = 0.1115
Fold 1: train tss = 0.6732 : val tss = 0.3349 ::: train hss = 0.5541 : val hss = 0.2127
Fold 2: train tss = 0.4806 : val tss = 0.6655 ::: train hss = 0.4067 : val hss = 0.4998
Fold 3: train tss = 0.5833 : val tss = 0.0205 ::: train hss = 0.4771 : val hss = 0.0270
Fold 4: train tss = 0.4781 : val tss = 0.4943 ::: train hss = 0.4017 : val hss = 0.4467
mean cv TSS: 0.3192
mean cv HSS: 0.2595
541/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5616 : val tss = 0.2905 ::: train hss = 0.6025 : val hss = 0.1962
Fold 2: train tss = 0.1301 : val tss = 0.3662 ::: train hss = 0.1990 : val hss = 0.3841
Fold 3: train tss = 0.4230 : val tss = -0.0012 ::: train hss = 0.3957 : val hss = -0.0022
Fold 4: train tss = 0.3300 : val tss = 0.5801 ::: train hss = 0.3617 : val hss = 0.4637
mean cv TSS: 0.2471
mean cv HSS: 0.2084
542/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6930 : val tss = 0.3348 ::: train hss = 0.5971 : val hss = 0.1766
Fold 2: train tss = 0.5228 : val tss = 0.6539 ::: train hss = 0.4530 : val hss = 0.5160
Fold 3: train tss = 0.6834 : val tss = 0.0227 ::: train hss = 0.4940 : val hss = 0.0224
Fold 4: train tss = 0.6141 : val tss = 0.1115 ::: train hss = 0.4325 : val hss = 0.1541
mean cv TSS: 0.2246
mean cv HSS: 0.1738
543/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6437 : val tss = 0.3308 ::: train hss = 0.5760 : val hss = 0.1698
Fold 2: train tss = 0.4900 : val tss = 0.5968 ::: train hss = 0.4655 : val hss = 0.4846
Fold 3: train tss = 0.4774 : val tss = -0.0051 ::: train hss = 0.4898 : val hss = -0.0074
Fold 4: train tss = 0.4504 : val tss = 0.6417 ::: train hss = 0.4208 : val hss = 0.4875
mean cv TSS: 0.3129
mean cv HSS: 0.2269
544/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6183 : val tss = 0.3098 ::: train hss = 0.7098 : val hss = 0.1550
Fold 2: train tss = 0.4319 : val tss = 0.5194 ::: train hss = 0.3977 : val hss = 0.4327
Fold 3: train tss = 0.6698 : val tss = 0.0242 ::: train hss = 0.5419 : val hss = 0.0254
Fold 4: train tss = 0.5620 : val tss = 0.2986 ::: train hss = 0.4930 : val hss = 0.3002
mean cv TSS: 0.2304
mean cv HSS: 0.1827
545/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6235 : val tss = 0.3775 ::: train hss = 0.6124 : val hss = 0.1588
Fold 2: train tss = 0.3842 : val tss = 0.5325 ::: train hss = 0.3627 : val hss = 0.4453
Fold 3: train tss = 0.3504 : val tss = -0.0032 ::: train hss = 0.3853 : val hss = -0.0051
Fold 4: train tss = 0.4571 : val tss = 0.5202 ::: train hss = 0.4388 : val hss = 0.4380
mean cv TSS: 0.2854
mean cv HSS: 0.2074
546/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7328 : val tss = 0.3475 ::: train hss = 0.4701 : val hss = 0.2554
Fold 2: train tss = 0.4506 : val tss = 0.5267 ::: train hss = 0.3626 : val hss = 0.4271
Fold 3: train tss = 0.5600 : val tss = 0.0376 ::: train hss = 0.4468 : val hss = 0.0331
Fold 4: train tss = 0.4478 : val tss = 0.5997 ::: train hss = 0.3839 : val hss = 0.4175
mean cv TSS: 0.3023
mean cv HSS: 0.2266
547/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.2291 : val tss = 0.1180 ::: train hss = 0.3387 : val hss = 0.1390
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.1150 : val tss = -0.0013 ::: train hss = 0.1748 : val hss = -0.0024
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0233
mean cv HSS: 0.0273
548/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6349 : val tss = 0.3082 ::: train hss = 0.5751 : val hss = 0.2571
Fold 2: train tss = 0.5701 : val tss = 0.6331 ::: train hss = 0.4793 : val hss = 0.4711
Fold 3: train tss = 0.6404 : val tss = 0.0386 ::: train hss = 0.5413 : val hss = 0.0507
Fold 4: train tss = 0.6447 : val tss = 0.2563 ::: train hss = 0.4705 : val hss = 0.2805
mean cv TSS: 0.2472
mean cv HSS: 0.2119
549/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4819 : val tss = 0.3563 ::: train hss = 0.5819 : val hss = 0.2347
Fold 2: train tss = 0.0726 : val tss = 0.0000 ::: train hss = 0.1245 : val hss = 0.0000
Fold 3: train tss = 0.5335 : val tss = 0.0263 ::: train hss = 0.4548 : val hss = 0.0299
Fold 4: train tss = 0.1138 : val tss = 0.2063 ::: train hss = 0.1844 : val hss = 0.2875
mean cv TSS: 0.1178
mean cv HSS: 0.1104
550/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6926 : val tss = 0.1400 ::: train hss = 0.6895 : val hss = 0.0664
Fold 2: train tss = 0.5156 : val tss = 0.6709 ::: train hss = 0.4532 : val hss = 0.4497
Fold 3: train tss = 0.6002 : val tss = 0.0967 ::: train hss = 0.4491 : val hss = 0.0989
Fold 4: train tss = 0.4501 : val tss = 0.5323 ::: train hss = 0.4189 : val hss = 0.3794
mean cv TSS: 0.2880
mean cv HSS: 0.1989
551/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5184 : val tss = 0.2398 ::: train hss = 0.6209 : val hss = 0.1867
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4785 : val tss = -0.0022 ::: train hss = 0.4233 : val hss = -0.0038
Fold 4: train tss = 0.3213 : val tss = 0.5169 ::: train hss = 0.3307 : val hss = 0.4723
mean cv TSS: 0.1509
mean cv HSS: 0.1310
552/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0500 : val tss = 0.0033 ::: train hss = 0.0952 : val hss = 0.0061
Fold 1: train tss = 0.6684 : val tss = 0.3551 ::: train hss = 0.6339 : val hss = 0.1705
Fold 2: train tss = 0.4323 : val tss = 0.6866 ::: train hss = 0.4386 : val hss = 0.5019
Fold 3: train tss = 0.5984 : val tss = 0.0348 ::: train hss = 0.5192 : val hss = 0.0387
Fold 4: train tss = 0.5401 : val tss = 0.5328 ::: train hss = 0.4558 : val hss = 0.5075
mean cv TSS: 0.3225
mean cv HSS: 0.2449
553/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6043 : val tss = 0.2560 ::: train hss = 0.6866 : val hss = 0.1459
Fold 2: train tss = 0.2581 : val tss = 0.4685 ::: train hss = 0.3180 : val hss = 0.4342
Fold 3: train tss = 0.4500 : val tss = -0.0013 ::: train hss = 0.4390 : val hss = -0.0024
Fold 4: train tss = 0.3640 : val tss = 0.6016 ::: train hss = 0.3919 : val hss = 0.4510
mean cv TSS: 0.2650
mean cv HSS: 0.2057
554/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7425 : val tss = 0.3715 ::: train hss = 0.7245 : val hss = 0.2640
Fold 2: train tss = 0.5666 : val tss = 0.5818 ::: train hss = 0.5688 : val hss = 0.4937
Fold 3: train tss = 0.7009 : val tss = 0.0666 ::: train hss = 0.5115 : val hss = 0.0619
Fold 4: train tss = 0.6396 : val tss = 0.3935 ::: train hss = 0.5011 : val hss = 0.4034
mean cv TSS: 0.2827
mean cv HSS: 0.2446
555/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6317 : val tss = 0.3113 ::: train hss = 0.6005 : val hss = 0.2586
Fold 2: train tss = 0.4742 : val tss = 0.6198 ::: train hss = 0.4911 : val hss = 0.4932
Fold 3: train tss = 0.6171 : val tss = 0.0016 ::: train hss = 0.4974 : val hss = 0.0020
Fold 4: train tss = 0.4716 : val tss = 0.5845 ::: train hss = 0.4802 : val hss = 0.4506
mean cv TSS: 0.3034
mean cv HSS: 0.2409
556/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6280 : val tss = 0.3475 ::: train hss = 0.7382 : val hss = 0.1911
Fold 2: train tss = 0.5169 : val tss = 0.5917 ::: train hss = 0.4475 : val hss = 0.4638
Fold 3: train tss = 0.6176 : val tss = 0.0062 ::: train hss = 0.5120 : val hss = 0.0048

Fold 4: train tss = 0.5905 : val tss = 0.4441 ::: train hss = 0.4953 : val hss = 0.4135
mean cv TSS: 0.2779
mean cv HSS: 0.2147
557/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6186 : val tss = 0.3086 ::: train hss = 0.7215 : val hss = 0.1531
Fold 2: train tss = 0.3164 : val tss = 0.4939 ::: train hss = 0.3481 : val hss = 0.4268
Fold 3: train tss = 0.6249 : val tss = 0.0112 ::: train hss = 0.5416 : val hss = 0.0147
Fold 4: train tss = 0.5140 : val tss = 0.5756 ::: train hss = 0.5010 : val hss = 0.4381
mean cv TSS: 0.2778
mean cv HSS: 0.2066
558/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0999 : val tss = 0.0535 ::: train hss = 0.1737 : val hss = 0.0705
Fold 1: train tss = 0.6334 : val tss = 0.3898 ::: train hss = 0.6392 : val hss = 0.2892
Fold 2: train tss = 0.5124 : val tss = 0.5831 ::: train hss = 0.4220 : val hss = 0.4619
Fold 3: train tss = 0.5968 : val tss = 0.0402 ::: train hss = 0.4966 : val hss = 0.0572
Fold 4: train tss = 0.5565 : val tss = 0.2749 ::: train hss = 0.4734 : val hss = 0.3332
mean cv TSS: 0.2683
mean cv HSS: 0.2424
559/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4363 : val tss = 0.2186 ::: train hss = 0.5342 : val hss = 0.1528
Fold 2: train tss = 0.0057 : val tss = 0.0266 ::: train hss = 0.0112 : val hss = 0.0506
Fold 3: train tss = 0.2748 : val tss = 0.0062 ::: train hss = 0.3201 : val hss = 0.0102
Fold 4: train tss = 0.1092 : val tss = 0.4985 ::: train hss = 0.1752 : val hss = 0.4317
mean cv TSS: 0.1500
mean cv HSS: 0.1291
560/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6962 : val tss = 0.3828 ::: train hss = 0.6675 : val hss = 0.2837
Fold 2: train tss = 0.5958 : val tss = 0.6108 ::: train hss = 0.5251 : val hss = 0.4816
Fold 3: train tss = 0.6771 : val tss = 0.0435 ::: train hss = 0.5474 : val hss = 0.0473
Fold 4: train tss = 0.5511 : val tss = 0.6090 ::: train hss = 0.5338 : val hss = 0.4698
mean cv TSS: 0.3292
mean cv HSS: 0.2565
561/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5406 : val tss = 0.3207 ::: train hss = 0.6271 : val hss = 0.2295
Fold 2: train tss = 0.2957 : val tss = 0.4543 ::: train hss = 0.3691 : val hss = 0.4214
Fold 3: train tss = 0.5484 : val tss = 0.0007 ::: train hss = 0.4850 : val hss = 0.0009
Fold 4: train tss = 0.4633 : val tss = 0.2924 ::: train hss = 0.4093 : val hss = 0.2818
mean cv TSS: 0.2136
mean cv HSS: 0.1867
562/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6100 : val tss = 0.3740 ::: train hss = 0.7287 : val hss = 0.1818
Fold 2: train tss = 0.6257 : val tss = 0.6466 ::: train hss = 0.4206 : val hss = 0.4561
Fold 3: train tss = 0.7057 : val tss = -0.0022 ::: train hss = 0.5591 : val hss = -0.0038
Fold 4: train tss = 0.6044 : val tss = 0.3715 ::: train hss = 0.5170 : val hss = 0.3574
mean cv TSS: 0.2780
mean cv HSS: 0.1983
563/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5734 : val tss = 0.2582 ::: train hss = 0.6868 : val hss = 0.1386
Fold 2: train tss = 0.3173 : val tss = 0.4117 ::: train hss = 0.3090 : val hss = 0.3956
Fold 3: train tss = 0.5912 : val tss = -0.0041 ::: train hss = 0.5025 : val hss = -0.0063
Fold 4: train tss = 0.4646 : val tss = 0.4755 ::: train hss = 0.4289 : val hss = 0.4063
mean cv TSS: 0.2282
mean cv HSS: 0.1868
564/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.1492 : val tss = 0.0955 ::: train hss = 0.1989 : val hss = 0.1301
Fold 1: train tss = 0.6814 : val tss = 0.3691 ::: train hss = 0.4796 : val hss = 0.1511
Fold 2: train tss = 0.5680 : val tss = 0.6133 ::: train hss = 0.3998 : val hss = 0.4641
Fold 3: train tss = 0.5661 : val tss = 0.0318 ::: train hss = 0.4500 : val hss = 0.0470
Fold 4: train tss = 0.4353 : val tss = 0.6339 ::: train hss = 0.3915 : val hss = 0.4950
mean cv TSS: 0.3487
mean cv HSS: 0.2575
565/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5489 : val tss = 0.2651 ::: train hss = 0.6142 : val hss = 0.1826
Fold 2: train tss = 0.1276 : val tss = 0.4110 ::: train hss = 0.1916 : val hss = 0.3974
Fold 3: train tss = 0.4258 : val tss = 0.0049 ::: train hss = 0.3985 : val hss = 0.0074
Fold 4: train tss = 0.3277 : val tss = 0.6727 ::: train hss = 0.3551 : val hss = 0.4765
mean cv TSS: 0.2707
mean cv HSS: 0.2128
566/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0137 ::: train hss = 0.0000 : val hss = 0.0257
Fold 1: train tss = 0.6307 : val tss = 0.3867 ::: train hss = 0.6849 : val hss = 0.2697
Fold 2: train tss = 0.5957 : val tss = 0.6434 ::: train hss = 0.5456 : val hss = 0.5126
Fold 3: train tss = 0.5819 : val tss = 0.0049 ::: train hss = 0.5705 : val hss = 0.0074
Fold 4: train tss = 0.6096 : val tss = 0.5453 ::: train hss = 0.4730 : val hss = 0.5238
mean cv TSS: 0.3188
mean cv HSS: 0.2679
567/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000

Fold 1: train tss = 0.6367 : val tss = 0.3459 ::: train hss = 0.6131 : val hss = 0.2421
Fold 2: train tss = 0.4747 : val tss = 0.5601 ::: train hss = 0.4752 : val hss = 0.4793
Fold 3: train tss = 0.5180 : val tss = 0.0004 ::: train hss = 0.5052 : val hss = 0.0004
Fold 4: train tss = 0.2261 : val tss = 0.4568 ::: train hss = 0.3041 : val hss = 0.4790
mean cv TSS: 0.2726
mean cv HSS: 0.2402
568/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0376 ::: train hss = 0.0000 : val hss = 0.0666
Fold 1: train tss = 0.6711 : val tss = 0.2792 ::: train hss = 0.7046 : val hss = 0.1369
Fold 2: train tss = 0.5565 : val tss = 0.6030 ::: train hss = 0.4206 : val hss = 0.4575
Fold 3: train tss = 0.6721 : val tss = 0.0217 ::: train hss = 0.5647 : val hss = 0.0304
Fold 4: train tss = 0.6239 : val tss = 0.5696 ::: train hss = 0.5004 : val hss = 0.4853
mean cv TSS: 0.3022
mean cv HSS: 0.2353
569/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5951 : val tss = 0.3339 ::: train hss = 0.6762 : val hss = 0.2456
Fold 2: train tss = 0.3820 : val tss = 0.4620 ::: train hss = 0.3580 : val hss = 0.3962
Fold 3: train tss = 0.6175 : val tss = -0.0072 ::: train hss = 0.5287 : val hss = -0.0094
Fold 4: train tss = 0.5410 : val tss = 0.6023 ::: train hss = 0.3977 : val hss = 0.4879
mean cv TSS: 0.2782
mean cv HSS: 0.2241
570/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = -0.0001 : val tss = 0.2029 ::: train hss = -0.0002 : val hss = 0.2442
Fold 1: train tss = 0.4952 : val tss = 0.2349 ::: train hss = 0.5884 : val hss = 0.2093
Fold 2: train tss = 0.4647 : val tss = 0.5753 ::: train hss = 0.3636 : val hss = 0.4165
Fold 3: train tss = 0.5613 : val tss = 0.0276 ::: train hss = 0.4641 : val hss = 0.0333
Fold 4: train tss = 0.4669 : val tss = 0.5392 ::: train hss = 0.4297 : val hss = 0.4552
mean cv TSS: 0.3160
mean cv HSS: 0.2717
571/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4533 : val tss = 0.2591 ::: train hss = 0.5231 : val hss = 0.1512
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.2142 : val tss = 0.0037 ::: train hss = 0.2753 : val hss = 0.0052
Fold 4: train tss = 0.0036 : val tss = 0.5103 ::: train hss = 0.0068 : val hss = 0.4114
mean cv TSS: 0.1546
mean cv HSS: 0.1136
572/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7350 : val tss = 0.4018 ::: train hss = 0.6471 : val hss = 0.1956
Fold 2: train tss = 0.5507 : val tss = 0.5164 ::: train hss = 0.4641 : val hss = 0.4724
Fold 3: train tss = 0.6897 : val tss = 0.0231 ::: train hss = 0.5801 : val hss = 0.0352
Fold 4: train tss = 0.6556 : val tss = 0.2478 ::: train hss = 0.4889 : val hss = 0.2520
mean cv TSS: 0.2378
mean cv HSS: 0.1910
573/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5092 : val tss = 0.3311 ::: train hss = 0.6116 : val hss = 0.2296
Fold 2: train tss = 0.2884 : val tss = 0.4083 ::: train hss = 0.3657 : val hss = 0.4063
Fold 3: train tss = 0.5492 : val tss = 0.0244 ::: train hss = 0.3863 : val hss = 0.0256
Fold 4: train tss = 0.3853 : val tss = 0.4633 ::: train hss = 0.3550 : val hss = 0.4210
mean cv TSS: 0.2454
mean cv HSS: 0.2165
574/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7246 : val tss = 0.4190 ::: train hss = 0.7181 : val hss = 0.1765
Fold 2: train tss = 0.5134 : val tss = 0.6302 ::: train hss = 0.4486 : val hss = 0.4077
Fold 3: train tss = 0.6953 : val tss = 0.0611 ::: train hss = 0.5491 : val hss = 0.0649
Fold 4: train tss = 0.6412 : val tss = 0.3197 ::: train hss = 0.5129 : val hss = 0.3264
mean cv TSS: 0.2860
mean cv HSS: 0.1951
575/864
{'batch_size': 256, 'bce_pos_class_weight': 5, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5508 : val tss = 0.3376 ::: train hss = 0.6707 : val hss = 0.1585
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4135 : val tss = -0.0044 ::: train hss = 0.4161 : val hss = -0.0066
Fold 4: train tss = 0.4222 : val tss = 0.5361 ::: train hss = 0.3510 : val hss = 0.4534
mean cv TSS: 0.1739
mean cv HSS: 0.1210
576/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.7162 : val tss = -0.0311 ::: train hss = 0.0907 : val hss = -0.0233
Fold 1: train tss = 0.7964 : val tss = 0.3993 ::: train hss = 0.3524 : val hss = 0.1597
Fold 2: train tss = 0.7432 : val tss = 0.7035 ::: train hss = 0.2075 : val hss = 0.3051
Fold 3: train tss = 0.7610 : val tss = 0.0939 ::: train hss = 0.2595 : val hss = 0.0183
Fold 4: train tss = 0.7169 : val tss = 0.6863 ::: train hss = 0.1993 : val hss = 0.2904
mean cv TSS: 0.3704
mean cv HSS: 0.1500
577/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.2415 : val tss = 0.2274 ::: train hss = 0.1006 : val hss = 0.1665
Fold 1: train tss = 0.7563 : val tss = 0.4420 ::: train hss = 0.4027 : val hss = 0.1963
Fold 2: train tss = 0.7243 : val tss = 0.7013 ::: train hss = 0.2005 : val hss = 0.2867
Fold 3: train tss = 0.7404 : val tss = 0.1444 ::: train hss = 0.2486 : val hss = 0.0366
Fold 4: train tss = 0.7203 : val tss = 0.6908 ::: train hss = 0.2123 : val hss = 0.2868
mean cv TSS: 0.4412
mean cv HSS: 0.1946
578/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.3360 : val tss = 0.3059 ::: train hss = 0.0940 : val hss = 0.2142

Fold 1: train tss = 0.7620 : val tss = 0.4203 ::: train hss = 0.3026 : val hss = 0.1625
Fold 2: train tss = 0.6918 : val tss = 0.6761 ::: train hss = 0.1534 : val hss = 0.2687
Fold 3: train tss = 0.7255 : val tss = 0.0968 ::: train hss = 0.2167 : val hss = 0.0131
Fold 4: train tss = 0.6936 : val tss = 0.6495 ::: train hss = 0.1819 : val hss = 0.2295
mean cv TSS: 0.4297
mean cv HSS: 0.1776
579/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7667 : val tss = 0.4480 ::: train hss = 0.4617 : val hss = 0.2418
Fold 2: train tss = 0.6988 : val tss = 0.6698 ::: train hss = 0.2037 : val hss = 0.2434
Fold 3: train tss = 0.7470 : val tss = 0.1833 ::: train hss = 0.2489 : val hss = 0.0521
Fold 4: train tss = 0.7132 : val tss = 0.6506 ::: train hss = 0.1880 : val hss = 0.2187
mean cv TSS: 0.3903
mean cv HSS: 0.1512
580/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = -0.0002 ::: train hss = 0.0000 : val hss = -0.0005
Fold 1: train tss = 0.7480 : val tss = 0.3780 ::: train hss = 0.3710 : val hss = 0.1105
Fold 2: train tss = 0.6993 : val tss = 0.5818 ::: train hss = 0.1345 : val hss = 0.1708
Fold 3: train tss = 0.7505 : val tss = 0.2677 ::: train hss = 0.2317 : val hss = 0.0436
Fold 4: train tss = 0.7224 : val tss = 0.6913 ::: train hss = 0.1858 : val hss = 0.2491
mean cv TSS: 0.3837
mean cv HSS: 0.1147
581/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7598 : val tss = 0.4629 ::: train hss = 0.3638 : val hss = 0.2294
Fold 2: train tss = 0.7246 : val tss = 0.6661 ::: train hss = 0.1785 : val hss = 0.2391
Fold 3: train tss = 0.7266 : val tss = 0.2604 ::: train hss = 0.2252 : val hss = 0.0454
Fold 4: train tss = 0.7145 : val tss = 0.6491 ::: train hss = 0.1797 : val hss = 0.2414
mean cv TSS: 0.4077
mean cv HSS: 0.1511
582/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.3907 : val tss = 0.2829 ::: train hss = 0.1489 : val hss = 0.1677
Fold 1: train tss = 0.7632 : val tss = 0.3540 ::: train hss = 0.4711 : val hss = 0.1766
Fold 2: train tss = 0.7650 : val tss = 0.6992 ::: train hss = 0.2317 : val hss = 0.2925
Fold 3: train tss = 0.7668 : val tss = 0.1034 ::: train hss = 0.2716 : val hss = 0.0202
Fold 4: train tss = 0.7577 : val tss = 0.6902 ::: train hss = 0.2503 : val hss = 0.3088
mean cv TSS: 0.4260
mean cv HSS: 0.1932
583/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7668 : val tss = 0.4180 ::: train hss = 0.4630 : val hss = 0.1936
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7524 : val tss = 0.1286 ::: train hss = 0.2561 : val hss = 0.0334
Fold 4: train tss = 0.7431 : val tss = 0.6817 ::: train hss = 0.2365 : val hss = 0.2663
mean cv TSS: 0.2457
mean cv HSS: 0.0987
584/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.7404 : val tss = 0.6425 ::: train hss = 0.1846 : val hss = 0.2153
Fold 3: train tss = 0.7640 : val tss = 0.1547 ::: train hss = 0.2719 : val hss = 0.0480
Fold 4: train tss = 0.7624 : val tss = 0.6803 ::: train hss = 0.2377 : val hss = 0.2955
mean cv TSS: 0.2955
mean cv HSS: 0.1117
585/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6430 : val tss = 0.3768 ::: train hss = 0.3877 : val hss = 0.1952
Fold 2: train tss = 0.6172 : val tss = 0.5954 ::: train hss = 0.1591 : val hss = 0.1941
Fold 3: train tss = 0.7767 : val tss = 0.1951 ::: train hss = 0.2841 : val hss = 0.0476
Fold 4: train tss = 0.7509 : val tss = 0.6440 ::: train hss = 0.2324 : val hss = 0.2660
mean cv TSS: 0.3623
mean cv HSS: 0.1406
586/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7541 : val tss = 0.3679 ::: train hss = 0.3052 : val hss = 0.1554
Fold 2: train tss = 0.5320 : val tss = 0.6884 ::: train hss = 0.1751 : val hss = 0.3204
Fold 3: train tss = 0.7598 : val tss = 0.1423 ::: train hss = 0.2901 : val hss = 0.0354
Fold 4: train tss = 0.7070 : val tss = 0.5769 ::: train hss = 0.2029 : val hss = 0.2144
mean cv TSS: 0.3551
mean cv HSS: 0.1451
587/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6970 : val tss = 0.4035 ::: train hss = 0.4571 : val hss = 0.1901
Fold 2: train tss = 0.0007 : val tss = 0.0073 ::: train hss = 0.0000 : val hss = 0.0010
Fold 3: train tss = 0.7459 : val tss = 0.1969 ::: train hss = 0.2634 : val hss = 0.0489
Fold 4: train tss = 0.7194 : val tss = 0.6621 ::: train hss = 0.1935 : val hss = 0.2450
mean cv TSS: 0.2540
mean cv HSS: 0.0970
588/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4842 : val tss = 0.0790 ::: train hss = 0.1203 : val hss = 0.0442
Fold 1: train tss = 0.7674 : val tss = 0.3290 ::: train hss = 0.3086 : val hss = 0.1306
Fold 2: train tss = 0.7403 : val tss = 0.6994 ::: train hss = 0.2318 : val hss = 0.2767
Fold 3: train tss = 0.7329 : val tss = 0.1644 ::: train hss = 0.2207 : val hss = 0.0361
Fold 4: train tss = 0.7385 : val tss = 0.6637 ::: train hss = 0.2256 : val hss = 0.2611
mean cv TSS: 0.3871
mean cv HSS: 0.1497
589/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}

Total number of parameters: 189
Fold 0: train tss = 0.3369 : val tss = -0.0122 ::: train hss = 0.0991 : val hss = -0.0105
Fold 1: train tss = 0.7602 : val tss = 0.4235 ::: train hss = 0.3668 : val hss = 0.1905
Fold 2: train tss = 0.6812 : val tss = 0.6414 ::: train hss = 0.1418 : val hss = 0.2178
Fold 3: train tss = 0.7290 : val tss = 0.1680 ::: train hss = 0.2422 : val hss = 0.0353
Fold 4: train tss = 0.7011 : val tss = 0.6777 ::: train hss = 0.1927 : val hss = 0.2671
mean cv TSS: 0.3797
mean cv HSS: 0.1400
590/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7551 : val tss = 0.3775 ::: train hss = 0.4775 : val hss = 0.2172
Fold 2: train tss = 0.7259 : val tss = 0.6166 ::: train hss = 0.1669 : val hss = 0.2415
Fold 3: train tss = 0.7578 : val tss = 0.2973 ::: train hss = 0.2196 : val hss = 0.0384
Fold 4: train tss = 0.7191 : val tss = 0.6402 ::: train hss = 0.1876 : val hss = 0.2439
mean cv TSS: 0.3863
mean cv HSS: 0.1482
591/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = -0.0025 : val tss = 0.3961 ::: train hss = -0.0025 : val hss = 0.3159
Fold 1: train tss = 0.7644 : val tss = 0.4088 ::: train hss = 0.3989 : val hss = 0.1690
Fold 2: train tss = 0.7348 : val tss = 0.7009 ::: train hss = 0.2213 : val hss = 0.3018
Fold 3: train tss = 0.7506 : val tss = 0.1834 ::: train hss = 0.2511 : val hss = 0.0476
Fold 4: train tss = 0.7246 : val tss = 0.6617 ::: train hss = 0.2236 : val hss = 0.2539
mean cv TSS: 0.4702
mean cv HSS: 0.2176
592/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.2884 : val tss = 0.3337 ::: train hss = 0.0946 : val hss = 0.1587
Fold 1: train tss = 0.7889 : val tss = 0.4744 ::: train hss = 0.3327 : val hss = 0.1894
Fold 2: train tss = 0.7522 : val tss = 0.6943 ::: train hss = 0.2295 : val hss = 0.3136
Fold 3: train tss = 0.7520 : val tss = 0.0853 ::: train hss = 0.2406 : val hss = 0.0157
Fold 4: train tss = 0.7378 : val tss = 0.5553 ::: train hss = 0.2084 : val hss = 0.2595
mean cv TSS: 0.4286
mean cv HSS: 0.1874
593/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.3968 ::: train hss = 0.0000 : val hss = 0.5481
Fold 1: train tss = 0.7510 : val tss = 0.4632 ::: train hss = 0.4811 : val hss = 0.2299
Fold 2: train tss = 0.7038 : val tss = 0.6811 ::: train hss = 0.1781 : val hss = 0.2565
Fold 3: train tss = 0.7614 : val tss = 0.1775 ::: train hss = 0.2700 : val hss = 0.0523
Fold 4: train tss = 0.7206 : val tss = 0.6759 ::: train hss = 0.1892 : val hss = 0.2698
mean cv TSS: 0.4789
mean cv HSS: 0.2713
594/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.5310 : val tss = 0.2050 ::: train hss = 0.1124 : val hss = 0.0919
Fold 1: train tss = 0.8196 : val tss = 0.3467 ::: train hss = 0.4711 : val hss = 0.1764
Fold 2: train tss = 0.7118 : val tss = 0.6434 ::: train hss = 0.1536 : val hss = 0.2275
Fold 3: train tss = 0.7523 : val tss = 0.1405 ::: train hss = 0.2349 : val hss = 0.0412
Fold 4: train tss = 0.7450 : val tss = 0.6803 ::: train hss = 0.2117 : val hss = 0.2786
mean cv TSS: 0.4032
mean cv HSS: 0.1631
595/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7680 : val tss = 0.4084 ::: train hss = 0.4308 : val hss = 0.1716
Fold 2: train tss = 0.7113 : val tss = 0.6981 ::: train hss = 0.2056 : val hss = 0.2843
Fold 3: train tss = 0.7335 : val tss = 0.1634 ::: train hss = 0.2344 : val hss = 0.0356
Fold 4: train tss = 0.7130 : val tss = 0.6818 ::: train hss = 0.2038 : val hss = 0.2379
mean cv TSS: 0.3903
mean cv HSS: 0.1459
596/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7667 : val tss = 0.2653 ::: train hss = 0.3829 : val hss = 0.1329
Fold 2: train tss = 0.7649 : val tss = 0.7107 ::: train hss = 0.2526 : val hss = 0.3022
Fold 3: train tss = 0.8019 : val tss = 0.1018 ::: train hss = 0.3664 : val hss = 0.0292
Fold 4: train tss = 0.7476 : val tss = 0.6638 ::: train hss = 0.2314 : val hss = 0.2749
mean cv TSS: 0.3483
mean cv HSS: 0.1478
597/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7609 : val tss = 0.4014 ::: train hss = 0.4953 : val hss = 0.1827
Fold 2: train tss = 0.7277 : val tss = 0.6793 ::: train hss = 0.2114 : val hss = 0.2747
Fold 3: train tss = 0.7679 : val tss = 0.1316 ::: train hss = 0.3115 : val hss = 0.0430
Fold 4: train tss = 0.7350 : val tss = 0.6699 ::: train hss = 0.2105 : val hss = 0.2764
mean cv TSS: 0.3764
mean cv HSS: 0.1554
598/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7403 : val tss = 0.3421 ::: train hss = 0.3774 : val hss = 0.1183
Fold 2: train tss = 0.7349 : val tss = 0.7024 ::: train hss = 0.2416 : val hss = 0.3024
Fold 3: train tss = 0.7993 : val tss = 0.0894 ::: train hss = 0.3335 : val hss = 0.0344
Fold 4: train tss = 0.7648 : val tss = 0.6805 ::: train hss = 0.2785 : val hss = 0.2840
mean cv TSS: 0.3629
mean cv HSS: 0.1478
599/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7449 : val tss = 0.2551 ::: train hss = 0.2819 : val hss = 0.1763
Fold 2: train tss = 0.6579 : val tss = 0.6555 ::: train hss = 0.1125 : val hss = 0.2344
Fold 3: train tss = 0.7575 : val tss = 0.0866 ::: train hss = 0.2842 : val hss = 0.0285

Fold 4: train tss = 0.7450 : val tss = 0.6886 ::: train hss = 0.2077 : val hss = 0.2975
mean cv TSS: 0.3371
mean cv HSS: 0.1473
600/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5370 : val tss = 0.0490 ::: train hss = 0.1545 : val hss = 0.0334
Fold 1: train tss = 0.7732 : val tss = 0.3837 ::: train hss = 0.2779 : val hss = 0.1088
Fold 2: train tss = 0.7317 : val tss = 0.6951 ::: train hss = 0.2155 : val hss = 0.2673
Fold 3: train tss = 0.7647 : val tss = 0.1619 ::: train hss = 0.2608 : val hss = 0.0407
Fold 4: train tss = 0.7587 : val tss = 0.6815 ::: train hss = 0.2433 : val hss = 0.2906
mean cv TSS: 0.3942
mean cv HSS: 0.1482
601/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4380 : val tss = 0.3061 ::: train hss = 0.1358 : val hss = 0.1667
Fold 1: train tss = 0.7711 : val tss = 0.4337 ::: train hss = 0.4192 : val hss = 0.2172
Fold 2: train tss = 0.7063 : val tss = 0.6709 ::: train hss = 0.1622 : val hss = 0.2476
Fold 3: train tss = 0.7425 : val tss = 0.1208 ::: train hss = 0.2412 : val hss = 0.0318
Fold 4: train tss = 0.7274 : val tss = 0.6617 ::: train hss = 0.2184 : val hss = 0.2526
mean cv TSS: 0.4386
mean cv HSS: 0.1832
602/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.3898 : val tss = 0.0198 ::: train hss = 0.1380 : val hss = 0.0275
Fold 1: train tss = 0.8005 : val tss = 0.4364 ::: train hss = 0.3796 : val hss = 0.1914
Fold 2: train tss = 0.7667 : val tss = 0.7133 ::: train hss = 0.2491 : val hss = 0.2912
Fold 3: train tss = 0.7701 : val tss = 0.0945 ::: train hss = 0.2350 : val hss = 0.0132
Fold 4: train tss = 0.7564 : val tss = 0.6693 ::: train hss = 0.2279 : val hss = 0.2620
mean cv TSS: 0.3867
mean cv HSS: 0.1571
603/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.0050 ::: train hss = 0.0000 : val hss = 0.0099
Fold 1: train tss = 0.7705 : val tss = 0.4605 ::: train hss = 0.4138 : val hss = 0.1871
Fold 2: train tss = 0.7283 : val tss = 0.6992 ::: train hss = 0.2071 : val hss = 0.2692
Fold 3: train tss = 0.7604 : val tss = 0.2017 ::: train hss = 0.2746 : val hss = 0.0524
Fold 4: train tss = 0.7411 : val tss = 0.6737 ::: train hss = 0.2230 : val hss = 0.2615
mean cv TSS: 0.4080
mean cv HSS: 0.1560
604/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = -0.0025 : val tss = -0.0034 ::: train hss = -0.0025 : val hss = -0.0061
Fold 1: train tss = 0.7710 : val tss = 0.3399 ::: train hss = 0.3833 : val hss = 0.1459
Fold 2: train tss = 0.7068 : val tss = 0.7118 ::: train hss = 0.2179 : val hss = 0.3296
Fold 3: train tss = 0.7648 : val tss = 0.3460 ::: train hss = 0.2456 : val hss = 0.0702
Fold 4: train tss = 0.7418 : val tss = 0.6857 ::: train hss = 0.2250 : val hss = 0.2783
mean cv TSS: 0.4160
mean cv HSS: 0.1636
605/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = -0.0020 : val tss = 0.0981 ::: train hss = -0.0022 : val hss = 0.1252
Fold 1: train tss = 0.7746 : val tss = 0.4182 ::: train hss = 0.5043 : val hss = 0.1601
Fold 2: train tss = 0.7463 : val tss = 0.6872 ::: train hss = 0.2048 : val hss = 0.2748
Fold 3: train tss = 0.7070 : val tss = 0.1192 ::: train hss = 0.1838 : val hss = 0.0157
Fold 4: train tss = 0.7444 : val tss = 0.6782 ::: train hss = 0.2221 : val hss = 0.2905
mean cv TSS: 0.4002
mean cv HSS: 0.1733
606/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.7762 : val tss = 0.2580 ::: train hss = 0.1327 : val hss = 0.1450
Fold 1: train tss = 0.8452 : val tss = 0.4086 ::: train hss = 0.3174 : val hss = 0.1118
Fold 2: train tss = 0.7624 : val tss = 0.6700 ::: train hss = 0.2899 : val hss = 0.2599
Fold 3: train tss = 0.8014 : val tss = 0.3655 ::: train hss = 0.3046 : val hss = 0.0700
Fold 4: train tss = 0.7748 : val tss = 0.6712 ::: train hss = 0.2662 : val hss = 0.2902
mean cv TSS: 0.4747
mean cv HSS: 0.1754
607/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = -0.0010 : val tss = 0.3062 ::: train hss = -0.0014 : val hss = 0.3031
Fold 1: train tss = 0.7622 : val tss = 0.4522 ::: train hss = 0.4603 : val hss = 0.1968
Fold 2: train tss = 0.7182 : val tss = 0.6980 ::: train hss = 0.2411 : val hss = 0.2790
Fold 3: train tss = 0.7620 : val tss = 0.1218 ::: train hss = 0.2814 : val hss = 0.0238
Fold 4: train tss = 0.7373 : val tss = 0.6864 ::: train hss = 0.2347 : val hss = 0.2610
mean cv TSS: 0.4529
mean cv HSS: 0.2127
608/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7769 : val tss = 0.4208 ::: train hss = 0.5349 : val hss = 0.1901
Fold 2: train tss = 0.7261 : val tss = 0.6545 ::: train hss = 0.2558 : val hss = 0.2997
Fold 3: train tss = 0.8155 : val tss = 0.2336 ::: train hss = 0.3090 : val hss = 0.0497
Fold 4: train tss = 0.7995 : val tss = 0.6990 ::: train hss = 0.3058 : val hss = 0.3433
mean cv TSS: 0.4016
mean cv HSS: 0.1766
609/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7566 : val tss = 0.4314 ::: train hss = 0.4465 : val hss = 0.1737
Fold 2: train tss = 0.7270 : val tss = 0.6914 ::: train hss = 0.1949 : val hss = 0.2718
Fold 3: train tss = 0.7712 : val tss = 0.1463 ::: train hss = 0.2905 : val hss = 0.0511
Fold 4: train tss = 0.7505 : val tss = 0.6775 ::: train hss = 0.2398 : val hss = 0.3053
mean cv TSS: 0.3893
mean cv HSS: 0.1604
610/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000

Fold 1: train tss = 0.7263 : val tss = 0.4327 ::: train hss = 0.4465 : val hss = 0.1008
Fold 2: train tss = 0.7216 : val tss = 0.6989 ::: train hss = 0.2850 : val hss = 0.3149
Fold 3: train tss = 0.7788 : val tss = 0.1467 ::: train hss = 0.3493 : val hss = 0.0586
Fold 4: train tss = 0.7901 : val tss = 0.6847 ::: train hss = 0.2773 : val hss = 0.3529
mean cv TSS: 0.3926
mean cv HSS: 0.1654
611/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7596 : val tss = 0.4218 ::: train hss = 0.5381 : val hss = 0.2002
Fold 2: train tss = 0.6933 : val tss = 0.6843 ::: train hss = 0.1924 : val hss = 0.2741
Fold 3: train tss = 0.7743 : val tss = 0.1533 ::: train hss = 0.2968 : val hss = 0.0590
Fold 4: train tss = 0.7304 : val tss = 0.6732 ::: train hss = 0.2284 : val hss = 0.2828
mean cv TSS: 0.3865
mean cv HSS: 0.1632
612/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7650 : val tss = -0.0061 ::: train hss = 0.0412 : val hss = -0.0066
Fold 1: train tss = 0.8116 : val tss = 0.3406 ::: train hss = 0.3981 : val hss = 0.1665
Fold 2: train tss = 0.7613 : val tss = 0.6818 ::: train hss = 0.2558 : val hss = 0.2663
Fold 3: train tss = 0.7534 : val tss = 0.2904 ::: train hss = 0.2307 : val hss = 0.0515
Fold 4: train tss = 0.7624 : val tss = 0.6709 ::: train hss = 0.2428 : val hss = 0.2732
mean cv TSS: 0.3955
mean cv HSS: 0.1502
613/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4887 : val tss = 0.3145 ::: train hss = 0.1576 : val hss = 0.2013
Fold 1: train tss = 0.7615 : val tss = 0.4216 ::: train hss = 0.3761 : val hss = 0.1913
Fold 2: train tss = 0.6978 : val tss = 0.6638 ::: train hss = 0.1548 : val hss = 0.2360
Fold 3: train tss = 0.7355 : val tss = 0.3290 ::: train hss = 0.2362 : val hss = 0.0558
Fold 4: train tss = 0.7150 : val tss = 0.6486 ::: train hss = 0.2071 : val hss = 0.2383
mean cv TSS: 0.4755
mean cv HSS: 0.1846
614/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5387 : val tss = 0.3278 ::: train hss = 0.1724 : val hss = 0.1547
Fold 1: train tss = 0.8036 : val tss = 0.4554 ::: train hss = 0.4027 : val hss = 0.2149
Fold 2: train tss = 0.6591 : val tss = 0.6878 ::: train hss = 0.1544 : val hss = 0.3032
Fold 3: train tss = 0.7987 : val tss = 0.1185 ::: train hss = 0.3022 : val hss = 0.0334
Fold 4: train tss = 0.7470 : val tss = 0.6639 ::: train hss = 0.2151 : val hss = 0.2751
mean cv TSS: 0.4507
mean cv HSS: 0.1963
615/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4383 : val tss = 0.3264 ::: train hss = 0.1392 : val hss = 0.2000
Fold 1: train tss = 0.7856 : val tss = 0.4660 ::: train hss = 0.3964 : val hss = 0.2111
Fold 2: train tss = 0.7355 : val tss = 0.7231 ::: train hss = 0.2323 : val hss = 0.2987
Fold 3: train tss = 0.7657 : val tss = 0.3268 ::: train hss = 0.2774 : val hss = 0.0706
Fold 4: train tss = 0.7276 : val tss = 0.6921 ::: train hss = 0.2117 : val hss = 0.2498
mean cv TSS: 0.5069
mean cv HSS: 0.2061
616/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4847 : val tss = 0.2486 ::: train hss = 0.1235 : val hss = 0.1263
Fold 1: train tss = 0.8216 : val tss = 0.2840 ::: train hss = 0.3266 : val hss = 0.1015
Fold 2: train tss = 0.7797 : val tss = 0.7046 ::: train hss = 0.2681 : val hss = 0.3067
Fold 3: train tss = 0.8034 : val tss = 0.1042 ::: train hss = 0.2968 : val hss = 0.0306
Fold 4: train tss = 0.7812 : val tss = 0.6582 ::: train hss = 0.2517 : val hss = 0.2941
mean cv TSS: 0.3999
mean cv HSS: 0.1718
617/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5860 : val tss = 0.3640 ::: train hss = 0.1584 : val hss = 0.1916
Fold 1: train tss = 0.7484 : val tss = 0.3959 ::: train hss = 0.2476 : val hss = 0.1193
Fold 2: train tss = 0.7514 : val tss = 0.7028 ::: train hss = 0.2311 : val hss = 0.2872
Fold 3: train tss = 0.7577 : val tss = 0.1954 ::: train hss = 0.2489 : val hss = 0.0384
Fold 4: train tss = 0.6912 : val tss = 0.6594 ::: train hss = 0.1525 : val hss = 0.2166
mean cv TSS: 0.4635
mean cv HSS: 0.1706
618/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.7277 : val tss = 0.2517 ::: train hss = 0.1323 : val hss = 0.1192
Fold 1: train tss = 0.8222 : val tss = 0.3207 ::: train hss = 0.4144 : val hss = 0.1263
Fold 2: train tss = 0.7820 : val tss = 0.6569 ::: train hss = 0.2535 : val hss = 0.2663
Fold 3: train tss = 0.7144 : val tss = 0.0990 ::: train hss = 0.1800 : val hss = 0.0232
Fold 4: train tss = 0.7753 : val tss = 0.6604 ::: train hss = 0.2622 : val hss = 0.2575
mean cv TSS: 0.3977
mean cv HSS: 0.1585
619/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.4378 : val tss = 0.1729 ::: train hss = 0.1347 : val hss = 0.0842
Fold 1: train tss = 0.7592 : val tss = 0.4243 ::: train hss = 0.2717 : val hss = 0.2137
Fold 2: train tss = 0.6925 : val tss = 0.6902 ::: train hss = 0.2218 : val hss = 0.2693
Fold 3: train tss = 0.7330 : val tss = 0.3657 ::: train hss = 0.2226 : val hss = 0.0658
Fold 4: train tss = 0.7275 : val tss = 0.7034 ::: train hss = 0.2159 : val hss = 0.2930
mean cv TSS: 0.4713
mean cv HSS: 0.1852
620/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.2859 : val tss = 0.0200 ::: train hss = 0.0800 : val hss = 0.0139
Fold 1: train tss = 0.7747 : val tss = 0.3709 ::: train hss = 0.4548 : val hss = 0.1562
Fold 2: train tss = 0.7941 : val tss = 0.7037 ::: train hss = 0.2930 : val hss = 0.3374
Fold 3: train tss = 0.8241 : val tss = 0.2414 ::: train hss = 0.3382 : val hss = 0.0375
Fold 4: train tss = 0.7914 : val tss = 0.7023 ::: train hss = 0.2455 : val hss = 0.2932
mean cv TSS: 0.4077
mean cv HSS: 0.1677
621/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7580 : val tss = 0.4282 ::: train hss = 0.4608 : val hss = 0.1863
Fold 2: train tss = 0.7360 : val tss = 0.7121 ::: train hss = 0.2175 : val hss = 0.2871
Fold 3: train tss = 0.7643 : val tss = 0.2339 ::: train hss = 0.2829 : val hss = 0.0637
Fold 4: train tss = 0.7329 : val tss = 0.6976 ::: train hss = 0.2136 : val hss = 0.2859
mean cv TSS: 0.4144
mean cv HSS: 0.1646
622/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7785 : val tss = 0.2906 ::: train hss = 0.5586 : val hss = 0.1851
Fold 2: train tss = 0.7755 : val tss = 0.7043 ::: train hss = 0.2989 : val hss = 0.2946
Fold 3: train tss = 0.8285 : val tss = 0.0138 ::: train hss = 0.3452 : val hss = 0.0058
Fold 4: train tss = 0.8022 : val tss = 0.7004 ::: train hss = 0.3056 : val hss = 0.3136
mean cv TSS: 0.3418
mean cv HSS: 0.1598
623/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7700 : val tss = 0.3983 ::: train hss = 0.5625 : val hss = 0.1710
Fold 2: train tss = 0.7481 : val tss = 0.6714 ::: train hss = 0.2188 : val hss = 0.2557
Fold 3: train tss = 0.7890 : val tss = 0.1522 ::: train hss = 0.3134 : val hss = 0.0459
Fold 4: train tss = 0.7003 : val tss = 0.6613 ::: train hss = 0.1899 : val hss = 0.2643
mean cv TSS: 0.3766
mean cv HSS: 0.1474
624/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8864 : val tss = 0.0146 ::: train hss = 0.2348 : val hss = 0.0118
Fold 1: train tss = 0.8440 : val tss = 0.3490 ::: train hss = 0.3842 : val hss = 0.1266
Fold 2: train tss = 0.7613 : val tss = 0.6701 ::: train hss = 0.2004 : val hss = 0.2721
Fold 3: train tss = 0.7651 : val tss = 0.0914 ::: train hss = 0.2322 : val hss = 0.0236
Fold 4: train tss = 0.7779 : val tss = 0.6698 ::: train hss = 0.2695 : val hss = 0.2419
mean cv TSS: 0.3590
mean cv HSS: 0.1352
625/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5854 : val tss = 0.0690 ::: train hss = 0.1531 : val hss = 0.0437
Fold 1: train tss = 0.7699 : val tss = 0.4462 ::: train hss = 0.4090 : val hss = 0.1990
Fold 2: train tss = 0.7196 : val tss = 0.6933 ::: train hss = 0.1864 : val hss = 0.2701
Fold 3: train tss = 0.7395 : val tss = 0.1727 ::: train hss = 0.2349 : val hss = 0.0377
Fold 4: train tss = 0.7226 : val tss = 0.6646 ::: train hss = 0.2136 : val hss = 0.2607
mean cv TSS: 0.4091
mean cv HSS: 0.1622
626/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.6310 : val tss = 0.2236 ::: train hss = 0.1321 : val hss = 0.1142
Fold 1: train tss = 0.8182 : val tss = 0.4095 ::: train hss = 0.4566 : val hss = 0.1553
Fold 2: train tss = 0.7999 : val tss = 0.6843 ::: train hss = 0.2489 : val hss = 0.2642
Fold 3: train tss = 0.8232 : val tss = 0.0547 ::: train hss = 0.3020 : val hss = 0.0191
Fold 4: train tss = 0.7533 : val tss = 0.6507 ::: train hss = 0.1822 : val hss = 0.2179
mean cv TSS: 0.4046
mean cv HSS: 0.1541
627/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.4329 : val tss = 0.3554 ::: train hss = 0.1013 : val hss = 0.1900
Fold 1: train tss = 0.7959 : val tss = 0.3256 ::: train hss = 0.2290 : val hss = 0.0719
Fold 2: train tss = 0.7447 : val tss = 0.7183 ::: train hss = 0.2562 : val hss = 0.2958
Fold 3: train tss = 0.7613 : val tss = 0.2625 ::: train hss = 0.2748 : val hss = 0.0610
Fold 4: train tss = 0.7410 : val tss = 0.6703 ::: train hss = 0.2149 : val hss = 0.2505
mean cv TSS: 0.4664
mean cv HSS: 0.1738
628/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5789 : val tss = 0.3282 ::: train hss = 0.1119 : val hss = 0.1301
Fold 1: train tss = 0.7770 : val tss = 0.3327 ::: train hss = 0.2340 : val hss = 0.1299
Fold 2: train tss = 0.7636 : val tss = 0.6267 ::: train hss = 0.2358 : val hss = 0.2297
Fold 3: train tss = 0.8441 : val tss = 0.0701 ::: train hss = 0.3556 : val hss = 0.0176
Fold 4: train tss = 0.6808 : val tss = 0.6672 ::: train hss = 0.1555 : val hss = 0.2396
mean cv TSS: 0.4050
mean cv HSS: 0.1494
629/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.3813 : val tss = 0.3755 ::: train hss = 0.0834 : val hss = 0.1899
Fold 1: train tss = 0.7906 : val tss = 0.4361 ::: train hss = 0.4407 : val hss = 0.1872
Fold 2: train tss = 0.7681 : val tss = 0.7130 ::: train hss = 0.2918 : val hss = 0.2965
Fold 3: train tss = 0.7858 : val tss = 0.1169 ::: train hss = 0.2974 : val hss = 0.0324
Fold 4: train tss = 0.7562 : val tss = 0.6830 ::: train hss = 0.2480 : val hss = 0.2985
mean cv TSS: 0.4649
mean cv HSS: 0.2009
630/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.6854 : val tss = 0.2328 ::: train hss = 0.1769 : val hss = 0.1315
Fold 1: train tss = 0.8554 : val tss = 0.3030 ::: train hss = 0.3256 : val hss = 0.1190
Fold 2: train tss = 0.8007 : val tss = 0.7234 ::: train hss = 0.2783 : val hss = 0.3322
Fold 3: train tss = 0.8275 : val tss = 0.1063 ::: train hss = 0.3029 : val hss = 0.0401
Fold 4: train tss = 0.7832 : val tss = 0.6797 ::: train hss = 0.2390 : val hss = 0.3703
mean cv TSS: 0.4090
mean cv HSS: 0.1986
631/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.4389 : val tss = 0.0690 ::: train hss = 0.1451 : val hss = 0.0468
Fold 1: train tss = 0.7649 : val tss = 0.4360 ::: train hss = 0.3695 : val hss = 0.1766
Fold 2: train tss = 0.6867 : val tss = 0.6863 ::: train hss = 0.2137 : val hss = 0.2712
Fold 3: train tss = 0.7388 : val tss = 0.3382 ::: train hss = 0.2451 : val hss = 0.0648

Fold 4: train tss = 0.7337 : val tss = 0.6693 ::: train hss = 0.2226 : val hss = 0.2507
mean cv TSS: 0.4398
mean cv HSS: 0.1620
632/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.5239 : val tss = 0.2692 ::: train hss = 0.0845 : val hss = 0.1241
Fold 1: train tss = 0.8059 : val tss = 0.3534 ::: train hss = 0.5148 : val hss = 0.1544
Fold 2: train tss = 0.8090 : val tss = 0.6888 ::: train hss = 0.2919 : val hss = 0.3333
Fold 3: train tss = 0.8441 : val tss = 0.1022 ::: train hss = 0.3152 : val hss = 0.0325
Fold 4: train tss = 0.8067 : val tss = 0.6561 ::: train hss = 0.2815 : val hss = 0.2389
mean cv TSS: 0.4139
mean cv HSS: 0.1767
633/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7401 : val tss = 0.4350 ::: train hss = 0.2791 : val hss = 0.1171
Fold 2: train tss = 0.7343 : val tss = 0.6907 ::: train hss = 0.2437 : val hss = 0.2650
Fold 3: train tss = 0.7780 : val tss = 0.1998 ::: train hss = 0.2838 : val hss = 0.0435
Fold 4: train tss = 0.7489 : val tss = 0.6711 ::: train hss = 0.2426 : val hss = 0.2838
mean cv TSS: 0.3993
mean cv HSS: 0.1419
634/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7216 : val tss = -0.0449 ::: train hss = 0.1065 : val hss = -0.0201
Fold 1: train tss = 0.8376 : val tss = 0.3504 ::: train hss = 0.3998 : val hss = 0.1372
Fold 2: train tss = 0.8154 : val tss = 0.7351 ::: train hss = 0.3612 : val hss = 0.3615
Fold 3: train tss = 0.8495 : val tss = 0.0835 ::: train hss = 0.4318 : val hss = 0.0265
Fold 4: train tss = 0.8326 : val tss = 0.7173 ::: train hss = 0.2964 : val hss = 0.3702
mean cv TSS: 0.3683
mean cv HSS: 0.1751
635/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8099 : val tss = 0.4154 ::: train hss = 0.3858 : val hss = 0.1818
Fold 2: train tss = 0.7340 : val tss = 0.6894 ::: train hss = 0.2170 : val hss = 0.2673
Fold 3: train tss = 0.7930 : val tss = 0.1926 ::: train hss = 0.3295 : val hss = 0.0460
Fold 4: train tss = 0.7302 : val tss = 0.6555 ::: train hss = 0.2000 : val hss = 0.2647
mean cv TSS: 0.3906
mean cv HSS: 0.1520
636/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9363 : val tss = 0.0268 ::: train hss = 0.2448 : val hss = 0.0206
Fold 1: train tss = 0.8420 : val tss = 0.4121 ::: train hss = 0.4011 : val hss = 0.1479
Fold 2: train tss = 0.6939 : val tss = 0.6077 ::: train hss = 0.1280 : val hss = 0.1902
Fold 3: train tss = 0.7814 : val tss = 0.1615 ::: train hss = 0.2643 : val hss = 0.0373
Fold 4: train tss = 0.7648 : val tss = 0.6345 ::: train hss = 0.2717 : val hss = 0.2294
mean cv TSS: 0.3685
mean cv HSS: 0.1251
637/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5368 : val tss = 0.0012 ::: train hss = 0.1523 : val hss = 0.0008
Fold 1: train tss = 0.7421 : val tss = 0.4230 ::: train hss = 0.2882 : val hss = 0.1118
Fold 2: train tss = 0.6666 : val tss = 0.6535 ::: train hss = 0.1929 : val hss = 0.2297
Fold 3: train tss = 0.7166 : val tss = 0.3405 ::: train hss = 0.2194 : val hss = 0.0554
Fold 4: train tss = 0.7141 : val tss = 0.6497 ::: train hss = 0.1982 : val hss = 0.2247
mean cv TSS: 0.4136
mean cv HSS: 0.1245
638/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9245 : val tss = 0.1681 ::: train hss = 0.1473 : val hss = 0.0745
Fold 1: train tss = 0.8817 : val tss = 0.3700 ::: train hss = 0.3787 : val hss = 0.1751
Fold 2: train tss = 0.7938 : val tss = 0.7478 ::: train hss = 0.2781 : val hss = 0.3680
Fold 3: train tss = 0.8369 : val tss = 0.1465 ::: train hss = 0.3307 : val hss = 0.0323
Fold 4: train tss = 0.8134 : val tss = 0.6892 ::: train hss = 0.2937 : val hss = 0.2956
mean cv TSS: 0.4243
mean cv HSS: 0.1891
639/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5274 : val tss = 0.3011 ::: train hss = 0.0963 : val hss = 0.1051
Fold 1: train tss = 0.8149 : val tss = 0.4255 ::: train hss = 0.2773 : val hss = 0.1476
Fold 2: train tss = 0.7438 : val tss = 0.6855 ::: train hss = 0.2008 : val hss = 0.2585
Fold 3: train tss = 0.7748 : val tss = 0.1850 ::: train hss = 0.3203 : val hss = 0.0448
Fold 4: train tss = 0.7282 : val tss = 0.6832 ::: train hss = 0.2169 : val hss = 0.2777
mean cv TSS: 0.4560
mean cv HSS: 0.1667
640/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.6777 : val tss = 0.0639 ::: train hss = 0.1238 : val hss = 0.0380
Fold 1: train tss = 0.8657 : val tss = 0.2021 ::: train hss = 0.4550 : val hss = 0.0883
Fold 2: train tss = 0.7229 : val tss = 0.6864 ::: train hss = 0.1689 : val hss = 0.2871
Fold 3: train tss = 0.8390 : val tss = 0.1036 ::: train hss = 0.3504 : val hss = 0.0303
Fold 4: train tss = 0.7775 : val tss = 0.7092 ::: train hss = 0.2152 : val hss = 0.3343
mean cv TSS: 0.3531
mean cv HSS: 0.1556
641/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5650 : val tss = 0.2073 ::: train hss = 0.0306 : val hss = 0.0907
Fold 1: train tss = 0.7870 : val tss = 0.4443 ::: train hss = 0.4078 : val hss = 0.2001
Fold 2: train tss = 0.7340 : val tss = 0.6624 ::: train hss = 0.1935 : val hss = 0.2397
Fold 3: train tss = 0.7126 : val tss = 0.1042 ::: train hss = 0.1912 : val hss = 0.0219
Fold 4: train tss = 0.7033 : val tss = 0.6495 ::: train hss = 0.2293 : val hss = 0.2418
mean cv TSS: 0.4135
mean cv HSS: 0.1588
642/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 4367
Fold 0: train tss = 0.6919 : val tss = 0.2253 ::: train hss = 0.2740 : val hss = 0.1313
Fold 1: train tss = 0.8227 : val tss = 0.2581 ::: train hss = 0.3565 : val hss = 0.1050
Fold 2: train tss = 0.7840 : val tss = 0.6787 ::: train hss = 0.2619 : val hss = 0.2655
Fold 3: train tss = 0.8000 : val tss = 0.1758 ::: train hss = 0.3158 : val hss = 0.0224
Fold 4: train tss = 0.7892 : val tss = 0.6613 ::: train hss = 0.2715 : val hss = 0.2678
mean cv TSS: 0.3998
mean cv HSS: 0.1584
643/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.4378 : val tss = 0.1581 ::: train hss = 0.1347 : val hss = 0.0910
Fold 1: train tss = 0.7553 : val tss = 0.4228 ::: train hss = 0.3946 : val hss = 0.1546
Fold 2: train tss = 0.6882 : val tss = 0.6638 ::: train hss = 0.1645 : val hss = 0.2440
Fold 3: train tss = 0.7516 : val tss = 0.3775 ::: train hss = 0.2549 : val hss = 0.0790
Fold 4: train tss = 0.7175 : val tss = 0.6426 ::: train hss = 0.2120 : val hss = 0.2224
mean cv TSS: 0.4530
mean cv HSS: 0.1582
644/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.4399 : val tss = -0.0159 ::: train hss = 0.1557 : val hss = -0.0110
Fold 1: train tss = 0.8708 : val tss = 0.3846 ::: train hss = 0.3397 : val hss = 0.1380
Fold 2: train tss = 0.7887 : val tss = 0.7013 ::: train hss = 0.2395 : val hss = 0.2980
Fold 3: train tss = 0.8192 : val tss = 0.0774 ::: train hss = 0.3014 : val hss = 0.0163
Fold 4: train tss = 0.7518 : val tss = 0.6959 ::: train hss = 0.1826 : val hss = 0.2869
mean cv TSS: 0.3687
mean cv HSS: 0.1456
645/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0769 : val tss = 0.1673 ::: train hss = 0.0144 : val hss = 0.1155
Fold 1: train tss = 0.7059 : val tss = 0.4196 ::: train hss = 0.3764 : val hss = 0.1335
Fold 2: train tss = 0.7298 : val tss = 0.7078 ::: train hss = 0.2608 : val hss = 0.2848
Fold 3: train tss = 0.7869 : val tss = 0.0782 ::: train hss = 0.2799 : val hss = 0.0155
Fold 4: train tss = 0.7333 : val tss = 0.6251 ::: train hss = 0.2596 : val hss = 0.2035
mean cv TSS: 0.3996
mean cv HSS: 0.1506
646/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9565 : val tss = 0.2105 ::: train hss = 0.0954 : val hss = 0.0948
Fold 1: train tss = 0.8789 : val tss = 0.2677 ::: train hss = 0.3885 : val hss = 0.1085
Fold 2: train tss = 0.7722 : val tss = 0.7017 ::: train hss = 0.2505 : val hss = 0.2900
Fold 3: train tss = 0.8273 : val tss = 0.0953 ::: train hss = 0.3405 : val hss = 0.0256
Fold 4: train tss = 0.7305 : val tss = 0.5523 ::: train hss = 0.1704 : val hss = 0.3339
mean cv TSS: 0.3655
mean cv HSS: 0.1705
647/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.4171 : val tss = -0.0022 ::: train hss = 0.0552 : val hss = -0.0026
Fold 1: train tss = 0.7998 : val tss = 0.4085 ::: train hss = 0.2839 : val hss = 0.1442
Fold 2: train tss = 0.7474 : val tss = 0.7071 ::: train hss = 0.2811 : val hss = 0.2869
Fold 3: train tss = 0.7790 : val tss = 0.1327 ::: train hss = 0.3380 : val hss = 0.0246
Fold 4: train tss = 0.7480 : val tss = 0.6744 ::: train hss = 0.2029 : val hss = 0.2812
mean cv TSS: 0.3841
mean cv HSS: 0.1469
648/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.6382 : val tss = 0.1875 ::: train hss = 0.1949 : val hss = 0.0954
Fold 1: train tss = 0.7524 : val tss = 0.3618 ::: train hss = 0.2339 : val hss = 0.2050
Fold 2: train tss = 0.6801 : val tss = 0.6343 ::: train hss = 0.1623 : val hss = 0.2104
Fold 3: train tss = 0.6874 : val tss = 0.1589 ::: train hss = 0.1730 : val hss = 0.0234
Fold 4: train tss = 0.6918 : val tss = 0.6691 ::: train hss = 0.1908 : val hss = 0.2657
mean cv TSS: 0.4023
mean cv HSS: 0.1600
649/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.4376 : val tss = 0.2951 ::: train hss = 0.1326 : val hss = 0.1792
Fold 1: train tss = 0.7198 : val tss = 0.4099 ::: train hss = 0.3257 : val hss = 0.1530
Fold 2: train tss = 0.6909 : val tss = 0.6951 ::: train hss = 0.2038 : val hss = 0.2708
Fold 3: train tss = 0.7173 : val tss = 0.1686 ::: train hss = 0.2450 : val hss = 0.0383
Fold 4: train tss = 0.7016 : val tss = 0.6806 ::: train hss = 0.2133 : val hss = 0.2690
mean cv TSS: 0.4498
mean cv HSS: 0.1821
650/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6667 : val tss = 0.3941 ::: train hss = 0.1813 : val hss = 0.0925
Fold 2: train tss = 0.6323 : val tss = 0.6434 ::: train hss = 0.1342 : val hss = 0.2331
Fold 3: train tss = 0.7131 : val tss = 0.1751 ::: train hss = 0.1950 : val hss = 0.0458
Fold 4: train tss = 0.6784 : val tss = 0.6284 ::: train hss = 0.1789 : val hss = 0.2123
mean cv TSS: 0.3682
mean cv HSS: 0.1168
651/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = -0.0187 : val tss = 0.1795 ::: train hss = -0.0043 : val hss = 0.1277
Fold 1: train tss = 0.7387 : val tss = 0.3160 ::: train hss = 0.4400 : val hss = 0.1473
Fold 2: train tss = 0.6908 : val tss = 0.6998 ::: train hss = 0.1933 : val hss = 0.2710
Fold 3: train tss = 0.7223 : val tss = 0.1637 ::: train hss = 0.2129 : val hss = 0.0357
Fold 4: train tss = 0.7152 : val tss = 0.6647 ::: train hss = 0.1915 : val hss = 0.2703
mean cv TSS: 0.4047
mean cv HSS: 0.1704
652/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0315 : val tss = -0.2084 ::: train hss = 0.0002 : val hss = -0.0188
Fold 1: train tss = 0.7328 : val tss = 0.3026 ::: train hss = 0.2371 : val hss = 0.0830
Fold 2: train tss = 0.5883 : val tss = 0.6611 ::: train hss = 0.1361 : val hss = 0.2385
Fold 3: train tss = 0.6991 : val tss = 0.2408 ::: train hss = 0.1844 : val hss = 0.0355

Fold 4: train tss = 0.6932 : val tss = 0.6189 ::: train hss = 0.1765 : val hss = 0.2336
mean cv TSS: 0.3230
mean cv HSS: 0.1144
653/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0002 : val hss = 0.0000
Fold 1: train tss = 0.5565 : val tss = 0.3761 ::: train hss = 0.2238 : val hss = 0.1037
Fold 2: train tss = 0.6780 : val tss = 0.7078 ::: train hss = 0.1519 : val hss = 0.3047
Fold 3: train tss = 0.6978 : val tss = 0.2160 ::: train hss = 0.1884 : val hss = 0.0404
Fold 4: train tss = 0.6849 : val tss = 0.6559 ::: train hss = 0.1846 : val hss = 0.2282
mean cv TSS: 0.3912
mean cv HSS: 0.1354
654/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.4382 : val tss = 0.1626 ::: train hss = 0.1380 : val hss = 0.0930
Fold 1: train tss = 0.7629 : val tss = 0.4067 ::: train hss = 0.3867 : val hss = 0.1495
Fold 2: train tss = 0.7210 : val tss = 0.6950 ::: train hss = 0.2199 : val hss = 0.2744
Fold 3: train tss = 0.7619 : val tss = 0.3563 ::: train hss = 0.2289 : val hss = 0.0920
Fold 4: train tss = 0.7306 : val tss = 0.6244 ::: train hss = 0.1904 : val hss = 0.2494
mean cv TSS: 0.4490
mean cv HSS: 0.1717
655/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7473 : val tss = 0.4199 ::: train hss = 0.2310 : val hss = 0.1743
Fold 2: train tss = 0.6837 : val tss = 0.6473 ::: train hss = 0.1561 : val hss = 0.2253
Fold 3: train tss = 0.7287 : val tss = 0.1777 ::: train hss = 0.2278 : val hss = 0.0437
Fold 4: train tss = 0.7205 : val tss = 0.6725 ::: train hss = 0.1975 : val hss = 0.2682
mean cv TSS: 0.3835
mean cv HSS: 0.1423
656/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.5613 : val tss = 0.6262 ::: train hss = 0.1606 : val hss = 0.2155
Fold 3: train tss = 0.7178 : val tss = 0.1784 ::: train hss = 0.2099 : val hss = 0.0312
Fold 4: train tss = 0.7330 : val tss = 0.6817 ::: train hss = 0.2449 : val hss = 0.3075
mean cv TSS: 0.2973
mean cv HSS: 0.1108
657/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6060 : val tss = 0.3765 ::: train hss = 0.2117 : val hss = 0.1438
Fold 2: train tss = 0.6587 : val tss = 0.6672 ::: train hss = 0.1810 : val hss = 0.2483
Fold 3: train tss = 0.7423 : val tss = 0.1403 ::: train hss = 0.2483 : val hss = 0.0410
Fold 4: train tss = 0.6783 : val tss = 0.6750 ::: train hss = 0.1641 : val hss = 0.2436
mean cv TSS: 0.3718
mean cv HSS: 0.1353
658/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0113 : val tss = 0.0000 ::: train hss = 0.0013 : val hss = 0.0000
Fold 1: train tss = 0.7365 : val tss = 0.3825 ::: train hss = 0.5192 : val hss = 0.1878
Fold 2: train tss = 0.7092 : val tss = 0.7099 ::: train hss = 0.2291 : val hss = 0.3268
Fold 3: train tss = 0.7351 : val tss = 0.1850 ::: train hss = 0.2882 : val hss = 0.0488
Fold 4: train tss = 0.7378 : val tss = 0.6439 ::: train hss = 0.1992 : val hss = 0.2640
mean cv TSS: 0.3843
mean cv HSS: 0.1655
659/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6961 : val tss = 0.4357 ::: train hss = 0.4472 : val hss = 0.1942
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6795 : val tss = 0.1570 ::: train hss = 0.1731 : val hss = 0.0350
Fold 4: train tss = 0.6823 : val tss = 0.6544 ::: train hss = 0.2136 : val hss = 0.2268
mean cv TSS: 0.2494
mean cv HSS: 0.0912
660/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5344 : val tss = 0.3100 ::: train hss = 0.1328 : val hss = 0.1429
Fold 1: train tss = 0.7524 : val tss = 0.4159 ::: train hss = 0.1849 : val hss = 0.1546
Fold 2: train tss = 0.6788 : val tss = 0.6832 ::: train hss = 0.1848 : val hss = 0.2608
Fold 3: train tss = 0.7262 : val tss = 0.1382 ::: train hss = 0.2478 : val hss = 0.0361
Fold 4: train tss = 0.6951 : val tss = 0.6551 ::: train hss = 0.1938 : val hss = 0.2544
mean cv TSS: 0.4405
mean cv HSS: 0.1697
661/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.6364 : val tss = -0.0181 ::: train hss = 0.1744 : val hss = -0.0169
Fold 1: train tss = 0.7616 : val tss = 0.4552 ::: train hss = 0.4115 : val hss = 0.2056
Fold 2: train tss = 0.6922 : val tss = 0.6589 ::: train hss = 0.1570 : val hss = 0.2364
Fold 3: train tss = 0.6958 : val tss = 0.3962 ::: train hss = 0.2059 : val hss = 0.0777
Fold 4: train tss = 0.6533 : val tss = 0.6634 ::: train hss = 0.1820 : val hss = 0.2297
mean cv TSS: 0.4311
mean cv HSS: 0.1465
662/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4834 : val tss = 0.3935 ::: train hss = 0.1151 : val hss = 0.1941
Fold 1: train tss = 0.7864 : val tss = 0.4201 ::: train hss = 0.3195 : val hss = 0.1746
Fold 2: train tss = 0.7181 : val tss = 0.7030 ::: train hss = 0.2238 : val hss = 0.3273
Fold 3: train tss = 0.7280 : val tss = 0.3547 ::: train hss = 0.2155 : val hss = 0.0717
Fold 4: train tss = 0.7075 : val tss = 0.6643 ::: train hss = 0.1801 : val hss = 0.2845
mean cv TSS: 0.5071
mean cv HSS: 0.2105
663/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 189
Fold 0: train tss = 0.2375 : val tss = 0.3663 ::: train hss = 0.0736 : val hss = 0.2221
Fold 1: train tss = 0.7762 : val tss = 0.4369 ::: train hss = 0.3898 : val hss = 0.1685
Fold 2: train tss = 0.6831 : val tss = 0.7099 ::: train hss = 0.2016 : val hss = 0.2913
Fold 3: train tss = 0.7175 : val tss = 0.3532 ::: train hss = 0.2401 : val hss = 0.0706
Fold 4: train tss = 0.7044 : val tss = 0.6825 ::: train hss = 0.2172 : val hss = 0.2796
mean cv TSS: 0.5098
mean cv HSS: 0.2064
664/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4822 : val tss = 0.2576 ::: train hss = 0.1084 : val hss = 0.1532
Fold 1: train tss = 0.7490 : val tss = 0.3977 ::: train hss = 0.2241 : val hss = 0.1928
Fold 2: train tss = 0.5154 : val tss = 0.7251 ::: train hss = 0.1567 : val hss = 0.3596
Fold 3: train tss = 0.6891 : val tss = 0.1238 ::: train hss = 0.2112 : val hss = 0.0217
Fold 4: train tss = 0.6576 : val tss = 0.6534 ::: train hss = 0.1547 : val hss = 0.2481
mean cv TSS: 0.4315
mean cv HSS: 0.1951
665/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6957 : val tss = 0.3551 ::: train hss = 0.2681 : val hss = 0.0920
Fold 2: train tss = 0.6402 : val tss = 0.6581 ::: train hss = 0.1360 : val hss = 0.2319
Fold 3: train tss = 0.7195 : val tss = 0.2083 ::: train hss = 0.2041 : val hss = 0.0528
Fold 4: train tss = 0.6884 : val tss = 0.6348 ::: train hss = 0.1950 : val hss = 0.2437
mean cv TSS: 0.3713
mean cv HSS: 0.1241
666/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.7246 : val tss = 0.0701 ::: train hss = 0.1178 : val hss = 0.0376
Fold 1: train tss = 0.7789 : val tss = 0.2519 ::: train hss = 0.3245 : val hss = 0.0720
Fold 2: train tss = 0.6884 : val tss = 0.6503 ::: train hss = 0.1684 : val hss = 0.2316
Fold 3: train tss = 0.7494 : val tss = 0.1278 ::: train hss = 0.2128 : val hss = 0.0398
Fold 4: train tss = 0.7024 : val tss = 0.6491 ::: train hss = 0.1666 : val hss = 0.2506
mean cv TSS: 0.3498
mean cv HSS: 0.1263
667/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0002 : val hss = 0.0000
Fold 1: train tss = 0.7073 : val tss = 0.4692 ::: train hss = 0.3549 : val hss = 0.1548
Fold 2: train tss = 0.6744 : val tss = 0.6739 ::: train hss = 0.2062 : val hss = 0.2473
Fold 3: train tss = 0.7154 : val tss = 0.1426 ::: train hss = 0.2103 : val hss = 0.0250
Fold 4: train tss = 0.7075 : val tss = 0.6745 ::: train hss = 0.1879 : val hss = 0.2512
mean cv TSS: 0.3921
mean cv HSS: 0.1357
668/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7387 : val tss = 0.2724 ::: train hss = 0.2299 : val hss = 0.1306
Fold 2: train tss = 0.7256 : val tss = 0.6919 ::: train hss = 0.2165 : val hss = 0.2880
Fold 3: train tss = 0.7523 : val tss = 0.2055 ::: train hss = 0.2537 : val hss = 0.0763
Fold 4: train tss = 0.7250 : val tss = 0.6654 ::: train hss = 0.1919 : val hss = 0.2739
mean cv TSS: 0.3670
mean cv HSS: 0.1537
669/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7205 : val tss = 0.3453 ::: train hss = 0.4796 : val hss = 0.1593
Fold 2: train tss = 0.6894 : val tss = 0.6917 ::: train hss = 0.1716 : val hss = 0.2685
Fold 3: train tss = 0.7413 : val tss = 0.2370 ::: train hss = 0.2374 : val hss = 0.0608
Fold 4: train tss = 0.7208 : val tss = 0.6910 ::: train hss = 0.1894 : val hss = 0.2980
mean cv TSS: 0.3930
mean cv HSS: 0.1573
670/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7256 : val tss = 0.3643 ::: train hss = 0.5530 : val hss = 0.1427
Fold 2: train tss = 0.5781 : val tss = 0.7171 ::: train hss = 0.2077 : val hss = 0.3761
Fold 3: train tss = 0.7571 : val tss = 0.0444 ::: train hss = 0.2535 : val hss = 0.0137
Fold 4: train tss = 0.7521 : val tss = 0.6734 ::: train hss = 0.2184 : val hss = 0.2893
mean cv TSS: 0.3598
mean cv HSS: 0.1643
671/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7303 : val tss = 0.3300 ::: train hss = 0.2423 : val hss = 0.1542
Fold 2: train tss = 0.6486 : val tss = 0.6577 ::: train hss = 0.1655 : val hss = 0.2476
Fold 3: train tss = 0.7403 : val tss = 0.2055 ::: train hss = 0.2361 : val hss = 0.0508
Fold 4: train tss = 0.6672 : val tss = 0.6590 ::: train hss = 0.1434 : val hss = 0.2228
mean cv TSS: 0.3704
mean cv HSS: 0.1351
672/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5370 : val tss = 0.1406 ::: train hss = 0.1545 : val hss = 0.0789
Fold 1: train tss = 0.8071 : val tss = 0.3193 ::: train hss = 0.3659 : val hss = 0.1092
Fold 2: train tss = 0.7440 : val tss = 0.6814 ::: train hss = 0.1962 : val hss = 0.2613
Fold 3: train tss = 0.7619 : val tss = 0.1158 ::: train hss = 0.2622 : val hss = 0.0317
Fold 4: train tss = 0.7389 : val tss = 0.6624 ::: train hss = 0.2146 : val hss = 0.2558
mean cv TSS: 0.3839
mean cv HSS: 0.1474
673/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4358 : val tss = 0.2160 ::: train hss = 0.1186 : val hss = 0.1352
Fold 1: train tss = 0.7624 : val tss = 0.4341 ::: train hss = 0.3525 : val hss = 0.1807
Fold 2: train tss = 0.7089 : val tss = 0.6739 ::: train hss = 0.1705 : val hss = 0.2493
Fold 3: train tss = 0.7273 : val tss = 0.1615 ::: train hss = 0.2407 : val hss = 0.0303

Fold 4: train tss = 0.7156 : val tss = 0.6699 ::: train hss = 0.2121 : val hss = 0.2680
mean cv TSS: 0.4311
mean cv HSS: 0.1727
674/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4856 : val tss = 0.0928 ::: train hss = 0.1295 : val hss = 0.0772
Fold 1: train tss = 0.7766 : val tss = 0.3304 ::: train hss = 0.3932 : val hss = 0.1037
Fold 2: train tss = 0.7634 : val tss = 0.6941 ::: train hss = 0.2651 : val hss = 0.2992
Fold 3: train tss = 0.7588 : val tss = 0.2440 ::: train hss = 0.2538 : val hss = 0.0614
Fold 4: train tss = 0.7547 : val tss = 0.6637 ::: train hss = 0.2433 : val hss = 0.2572
mean cv TSS: 0.4050
mean cv HSS: 0.1597
675/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0488 : val tss = 0.1151 ::: train hss = 0.0630 : val hss = 0.1780
Fold 1: train tss = 0.7806 : val tss = 0.4556 ::: train hss = 0.4275 : val hss = 0.1836
Fold 2: train tss = 0.7400 : val tss = 0.7066 ::: train hss = 0.2219 : val hss = 0.2835
Fold 3: train tss = 0.7637 : val tss = 0.2134 ::: train hss = 0.2792 : val hss = 0.0521
Fold 4: train tss = 0.7481 : val tss = 0.6918 ::: train hss = 0.2424 : val hss = 0.2879
mean cv TSS: 0.4365
mean cv HSS: 0.1970
676/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0494 : val tss = -0.0005 ::: train hss = 0.0760 : val hss = -0.0010
Fold 1: train tss = 0.7534 : val tss = 0.4029 ::: train hss = 0.2827 : val hss = 0.1614
Fold 2: train tss = 0.7389 : val tss = 0.6879 ::: train hss = 0.2085 : val hss = 0.2847
Fold 3: train tss = 0.7274 : val tss = 0.1042 ::: train hss = 0.1980 : val hss = 0.0123
Fold 4: train tss = 0.7707 : val tss = 0.7156 ::: train hss = 0.2510 : val hss = 0.2886
mean cv TSS: 0.3820
mean cv HSS: 0.1492
677/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = -0.0089 : val tss = -0.0002 ::: train hss = -0.0038 : val hss = -0.0003
Fold 1: train tss = 0.7767 : val tss = 0.4732 ::: train hss = 0.4313 : val hss = 0.2514
Fold 2: train tss = 0.7184 : val tss = 0.6404 ::: train hss = 0.1786 : val hss = 0.2154
Fold 3: train tss = 0.7694 : val tss = 0.2049 ::: train hss = 0.2844 : val hss = 0.0549
Fold 4: train tss = 0.6872 : val tss = 0.6406 ::: train hss = 0.1517 : val hss = 0.2019
mean cv TSS: 0.3918
mean cv HSS: 0.1446
678/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.6839 : val tss = -0.0065 ::: train hss = 0.1628 : val hss = -0.0037
Fold 1: train tss = 0.7769 : val tss = 0.3765 ::: train hss = 0.5349 : val hss = 0.2267
Fold 2: train tss = 0.7761 : val tss = 0.6959 ::: train hss = 0.2034 : val hss = 0.2832
Fold 3: train tss = 0.8005 : val tss = 0.2487 ::: train hss = 0.3186 : val hss = 0.0363
Fold 4: train tss = 0.7774 : val tss = 0.6830 ::: train hss = 0.2444 : val hss = 0.2802
mean cv TSS: 0.3995
mean cv HSS: 0.1646
679/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7672 : val tss = 0.4138 ::: train hss = 0.4671 : val hss = 0.1794
Fold 2: train tss = 0.7298 : val tss = 0.6905 ::: train hss = 0.2180 : val hss = 0.2661
Fold 3: train tss = 0.7430 : val tss = 0.2309 ::: train hss = 0.2387 : val hss = 0.0560
Fold 4: train tss = 0.7393 : val tss = 0.7024 ::: train hss = 0.2298 : val hss = 0.2949
mean cv TSS: 0.4075
mean cv HSS: 0.1593
680/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0488 : val tss = 0.0000 ::: train hss = 0.0630 : val hss = 0.0000
Fold 1: train tss = 0.7744 : val tss = 0.3484 ::: train hss = 0.4509 : val hss = 0.1712
Fold 2: train tss = 0.7992 : val tss = 0.6884 ::: train hss = 0.2835 : val hss = 0.2879
Fold 3: train tss = 0.8106 : val tss = 0.0851 ::: train hss = 0.3563 : val hss = 0.0309
Fold 4: train tss = 0.7886 : val tss = 0.7078 ::: train hss = 0.2692 : val hss = 0.3365
mean cv TSS: 0.3659
mean cv HSS: 0.1653
681/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7461 : val tss = 0.4428 ::: train hss = 0.5310 : val hss = 0.2104
Fold 2: train tss = 0.7343 : val tss = 0.7016 ::: train hss = 0.2366 : val hss = 0.2717
Fold 3: train tss = 0.7790 : val tss = 0.1452 ::: train hss = 0.2913 : val hss = 0.0448
Fold 4: train tss = 0.7610 : val tss = 0.6780 ::: train hss = 0.2527 : val hss = 0.3060
mean cv TSS: 0.3935
mean cv HSS: 0.1666
682/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7729 : val tss = 0.3536 ::: train hss = 0.5405 : val hss = 0.1488
Fold 2: train tss = 0.7138 : val tss = 0.7091 ::: train hss = 0.2425 : val hss = 0.3079
Fold 3: train tss = 0.8193 : val tss = 0.0702 ::: train hss = 0.3982 : val hss = 0.0359
Fold 4: train tss = 0.7428 : val tss = 0.6919 ::: train hss = 0.2075 : val hss = 0.2712
mean cv TSS: 0.3650
mean cv HSS: 0.1528
683/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7702 : val tss = 0.4516 ::: train hss = 0.4527 : val hss = 0.2638
Fold 2: train tss = 0.7408 : val tss = 0.7248 ::: train hss = 0.2203 : val hss = 0.3144
Fold 3: train tss = 0.7668 : val tss = 0.1577 ::: train hss = 0.2717 : val hss = 0.0457
Fold 4: train tss = 0.7224 : val tss = 0.6620 ::: train hss = 0.2343 : val hss = 0.2572
mean cv TSS: 0.3992
mean cv HSS: 0.1762
684/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 379
Fold 0: train tss = 0.7803 : val tss = 0.0445 ::: train hss = 0.1561 : val hss = 0.0285
Fold 1: train tss = 0.7719 : val tss = 0.3755 ::: train hss = 0.3591 : val hss = 0.1451
Fold 2: train tss = 0.7419 : val tss = 0.6990 ::: train hss = 0.2495 : val hss = 0.2763
Fold 3: train tss = 0.7575 : val tss = 0.2064 ::: train hss = 0.2361 : val hss = 0.0514
Fold 4: train tss = 0.7345 : val tss = 0.6695 ::: train hss = 0.2132 : val hss = 0.2703
mean cv TSS: 0.3990
mean cv HSS: 0.1543
685/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3895 : val tss = 0.3154 ::: train hss = 0.1355 : val hss = 0.2042
Fold 1: train tss = 0.7192 : val tss = 0.4090 ::: train hss = 0.1616 : val hss = 0.0741
Fold 2: train tss = 0.7154 : val tss = 0.6431 ::: train hss = 0.1587 : val hss = 0.2174
Fold 3: train tss = 0.7294 : val tss = 0.3671 ::: train hss = 0.2242 : val hss = 0.0761
Fold 4: train tss = 0.7018 : val tss = 0.6554 ::: train hss = 0.1935 : val hss = 0.2297
mean cv TSS: 0.4780
mean cv HSS: 0.1603
686/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.3905 : val tss = 0.3334 ::: train hss = 0.1460 : val hss = 0.1752
Fold 1: train tss = 0.7891 : val tss = 0.3845 ::: train hss = 0.3114 : val hss = 0.2052
Fold 2: train tss = 0.7671 : val tss = 0.6849 ::: train hss = 0.2361 : val hss = 0.2936
Fold 3: train tss = 0.7873 : val tss = 0.1387 ::: train hss = 0.2831 : val hss = 0.0364
Fold 4: train tss = 0.7540 : val tss = 0.6720 ::: train hss = 0.2227 : val hss = 0.2676
mean cv TSS: 0.4427
mean cv HSS: 0.1956
687/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3371 : val tss = 0.3544 ::: train hss = 0.1006 : val hss = 0.1779
Fold 1: train tss = 0.7591 : val tss = 0.4557 ::: train hss = 0.3592 : val hss = 0.1983
Fold 2: train tss = 0.7235 : val tss = 0.7062 ::: train hss = 0.2099 : val hss = 0.2780
Fold 3: train tss = 0.7539 : val tss = 0.2871 ::: train hss = 0.2735 : val hss = 0.0770
Fold 4: train tss = 0.7088 : val tss = 0.6470 ::: train hss = 0.1696 : val hss = 0.2304
mean cv TSS: 0.4901
mean cv HSS: 0.1923
688/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4683 : val tss = 0.2910 ::: train hss = 0.0639 : val hss = 0.1017
Fold 1: train tss = 0.8223 : val tss = 0.3445 ::: train hss = 0.3091 : val hss = 0.1115
Fold 2: train tss = 0.7192 : val tss = 0.7624 ::: train hss = 0.2294 : val hss = 0.3672
Fold 3: train tss = 0.7743 : val tss = 0.1893 ::: train hss = 0.2600 : val hss = 0.0270
Fold 4: train tss = 0.7643 : val tss = 0.6725 ::: train hss = 0.2481 : val hss = 0.2947
mean cv TSS: 0.4519
mean cv HSS: 0.1804
689/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4340 : val tss = 0.3598 ::: train hss = 0.1072 : val hss = 0.1911
Fold 1: train tss = 0.7745 : val tss = 0.4236 ::: train hss = 0.3482 : val hss = 0.1638
Fold 2: train tss = 0.7135 : val tss = 0.7241 ::: train hss = 0.1915 : val hss = 0.3134
Fold 3: train tss = 0.7746 : val tss = 0.1949 ::: train hss = 0.2776 : val hss = 0.0381
Fold 4: train tss = 0.6257 : val tss = 0.5997 ::: train hss = 0.1050 : val hss = 0.1674
mean cv TSS: 0.4604
mean cv HSS: 0.1748
690/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8326 : val tss = 0.1952 ::: train hss = 0.1830 : val hss = 0.1078
Fold 1: train tss = 0.7711 : val tss = 0.4133 ::: train hss = 0.1468 : val hss = 0.0703
Fold 2: train tss = 0.7561 : val tss = 0.6433 ::: train hss = 0.1803 : val hss = 0.2320
Fold 3: train tss = 0.8024 : val tss = 0.1877 ::: train hss = 0.2920 : val hss = 0.0430
Fold 4: train tss = 0.7752 : val tss = 0.6672 ::: train hss = 0.2551 : val hss = 0.2649
mean cv TSS: 0.4213
mean cv HSS: 0.1436
691/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.3870 : val tss = 0.1896 ::: train hss = 0.1138 : val hss = 0.1041
Fold 1: train tss = 0.7584 : val tss = 0.3729 ::: train hss = 0.4217 : val hss = 0.1558
Fold 2: train tss = 0.7018 : val tss = 0.6558 ::: train hss = 0.1816 : val hss = 0.2299
Fold 3: train tss = 0.7443 : val tss = 0.3797 ::: train hss = 0.2416 : val hss = 0.0808
Fold 4: train tss = 0.7241 : val tss = 0.6406 ::: train hss = 0.2193 : val hss = 0.2179
mean cv TSS: 0.4477
mean cv HSS: 0.1577
692/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.3390 : val tss = 0.2850 ::: train hss = 0.1149 : val hss = 0.1632
Fold 1: train tss = 0.7589 : val tss = 0.2730 ::: train hss = 0.5266 : val hss = 0.1097
Fold 2: train tss = 0.7890 : val tss = 0.6707 ::: train hss = 0.2401 : val hss = 0.2549
Fold 3: train tss = 0.8239 : val tss = 0.0870 ::: train hss = 0.3358 : val hss = 0.0199
Fold 4: train tss = 0.8051 : val tss = 0.6863 ::: train hss = 0.2533 : val hss = 0.3314
mean cv TSS: 0.4004
mean cv HSS: 0.1758
693/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7799 : val tss = 0.3125 ::: train hss = 0.5160 : val hss = 0.1801
Fold 2: train tss = 0.7382 : val tss = 0.6834 ::: train hss = 0.2413 : val hss = 0.2657
Fold 3: train tss = 0.7549 : val tss = 0.2345 ::: train hss = 0.2637 : val hss = 0.0469
Fold 4: train tss = 0.7509 : val tss = 0.6740 ::: train hss = 0.2446 : val hss = 0.2843
mean cv TSS: 0.3809
mean cv HSS: 0.1554
694/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7749 : val tss = 0.3069 ::: train hss = 0.5718 : val hss = 0.1541
Fold 2: train tss = 0.7794 : val tss = 0.7094 ::: train hss = 0.3110 : val hss = 0.3177
Fold 3: train tss = 0.8300 : val tss = 0.0541 ::: train hss = 0.3609 : val hss = 0.0118

Fold 4: train tss = 0.8090 : val tss = 0.6820 ::: train hss = 0.2863 : val hss = 0.3112
mean cv TSS: 0.3505
mean cv HSS: 0.1590
695/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7686 : val tss = 0.3468 ::: train hss = 0.4367 : val hss = 0.1070
Fold 2: train tss = 0.7650 : val tss = 0.6836 ::: train hss = 0.2879 : val hss = 0.2613
Fold 3: train tss = 0.7937 : val tss = 0.0799 ::: train hss = 0.3222 : val hss = 0.0306
Fold 4: train tss = 0.7372 : val tss = 0.6615 ::: train hss = 0.2221 : val hss = 0.2731
mean cv TSS: 0.3543
mean cv HSS: 0.1344
696/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.7892 : val tss = -0.0097 ::: train hss = 0.2505 : val hss = -0.0068
Fold 1: train tss = 0.8326 : val tss = 0.2985 ::: train hss = 0.3944 : val hss = 0.1306
Fold 2: train tss = 0.7687 : val tss = 0.7197 ::: train hss = 0.2699 : val hss = 0.3002
Fold 3: train tss = 0.8086 : val tss = 0.1746 ::: train hss = 0.3150 : val hss = 0.0387
Fold 4: train tss = 0.7788 : val tss = 0.7090 ::: train hss = 0.2424 : val hss = 0.3265
mean cv TSS: 0.3784
mean cv HSS: 0.1578
697/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.3889 : val tss = 0.1750 ::: train hss = 0.1296 : val hss = 0.1169
Fold 1: train tss = 0.7635 : val tss = 0.4394 ::: train hss = 0.3915 : val hss = 0.2001
Fold 2: train tss = 0.7060 : val tss = 0.6894 ::: train hss = 0.1830 : val hss = 0.2648
Fold 3: train tss = 0.7332 : val tss = 0.1756 ::: train hss = 0.2311 : val hss = 0.0392
Fold 4: train tss = 0.7247 : val tss = 0.6734 ::: train hss = 0.2130 : val hss = 0.2432
mean cv TSS: 0.4306
mean cv HSS: 0.1728
698/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5271 : val tss = 0.2495 ::: train hss = 0.0954 : val hss = 0.1352
Fold 1: train tss = 0.8161 : val tss = 0.4390 ::: train hss = 0.3999 : val hss = 0.1878
Fold 2: train tss = 0.7651 : val tss = 0.6914 ::: train hss = 0.1857 : val hss = 0.2743
Fold 3: train tss = 0.7925 : val tss = 0.1114 ::: train hss = 0.2472 : val hss = 0.0191
Fold 4: train tss = 0.8023 : val tss = 0.6818 ::: train hss = 0.2645 : val hss = 0.3168
mean cv TSS: 0.4346
mean cv HSS: 0.1866
699/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5330 : val tss = 0.3490 ::: train hss = 0.1240 : val hss = 0.1946
Fold 1: train tss = 0.7769 : val tss = 0.4218 ::: train hss = 0.3370 : val hss = 0.1354
Fold 2: train tss = 0.7460 : val tss = 0.7188 ::: train hss = 0.2270 : val hss = 0.2991
Fold 3: train tss = 0.7528 : val tss = 0.1946 ::: train hss = 0.2347 : val hss = 0.0380
Fold 4: train tss = 0.7407 : val tss = 0.6867 ::: train hss = 0.2289 : val hss = 0.2989
mean cv TSS: 0.4742
mean cv HSS: 0.1932
700/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5223 : val tss = 0.3212 ::: train hss = 0.0800 : val hss = 0.1161
Fold 1: train tss = 0.8245 : val tss = 0.3113 ::: train hss = 0.3681 : val hss = 0.1355
Fold 2: train tss = 0.7472 : val tss = 0.6525 ::: train hss = 0.1917 : val hss = 0.2426
Fold 3: train tss = 0.6141 : val tss = 0.3483 ::: train hss = 0.1029 : val hss = 0.0351
Fold 4: train tss = 0.8127 : val tss = 0.7224 ::: train hss = 0.3107 : val hss = 0.3625
mean cv TSS: 0.4711
mean cv HSS: 0.1784
701/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.4309 : val tss = 0.3718 ::: train hss = 0.0917 : val hss = 0.2264
Fold 1: train tss = 0.8026 : val tss = 0.4004 ::: train hss = 0.4310 : val hss = 0.1583
Fold 2: train tss = 0.7669 : val tss = 0.7032 ::: train hss = 0.2654 : val hss = 0.2824
Fold 3: train tss = 0.7686 : val tss = 0.1964 ::: train hss = 0.2885 : val hss = 0.0448
Fold 4: train tss = 0.7537 : val tss = 0.6754 ::: train hss = 0.2215 : val hss = 0.2764
mean cv TSS: 0.4694
mean cv HSS: 0.1977
702/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.5417 : val tss = 0.2958 ::: train hss = 0.2167 : val hss = 0.1609
Fold 1: train tss = 0.8415 : val tss = 0.3275 ::: train hss = 0.3422 : val hss = 0.0948
Fold 2: train tss = 0.7950 : val tss = 0.6677 ::: train hss = 0.2355 : val hss = 0.3017
Fold 3: train tss = 0.8136 : val tss = 0.1599 ::: train hss = 0.2920 : val hss = 0.0431
Fold 4: train tss = 0.7845 : val tss = 0.6537 ::: train hss = 0.2504 : val hss = 0.3292
mean cv TSS: 0.4209
mean cv HSS: 0.1859
703/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.3877 : val tss = 0.0816 ::: train hss = 0.1193 : val hss = 0.0499
Fold 1: train tss = 0.7507 : val tss = 0.4302 ::: train hss = 0.3095 : val hss = 0.1551
Fold 2: train tss = 0.7083 : val tss = 0.6853 ::: train hss = 0.1737 : val hss = 0.2596
Fold 3: train tss = 0.7347 : val tss = 0.1530 ::: train hss = 0.2371 : val hss = 0.0288
Fold 4: train tss = 0.7375 : val tss = 0.6836 ::: train hss = 0.2371 : val hss = 0.2429
mean cv TSS: 0.4067
mean cv HSS: 0.1473
704/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.4782 : val tss = 0.2888 ::: train hss = 0.0907 : val hss = 0.1387
Fold 1: train tss = 0.8429 : val tss = 0.3423 ::: train hss = 0.4440 : val hss = 0.1285
Fold 2: train tss = 0.8340 : val tss = 0.6850 ::: train hss = 0.2651 : val hss = 0.3122
Fold 3: train tss = 0.8398 : val tss = 0.1018 ::: train hss = 0.3581 : val hss = 0.0226
Fold 4: train tss = 0.8193 : val tss = 0.6500 ::: train hss = 0.2834 : val hss = 0.3358
mean cv TSS: 0.4136
mean cv HSS: 0.1876
705/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 4367
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7910 : val tss = 0.4258 ::: train hss = 0.3210 : val hss = 0.1580
Fold 2: train tss = 0.7353 : val tss = 0.7045 ::: train hss = 0.2319 : val hss = 0.2864
Fold 3: train tss = 0.7525 : val tss = 0.2644 ::: train hss = 0.2529 : val hss = 0.0504
Fold 4: train tss = 0.7611 : val tss = 0.6677 ::: train hss = 0.2687 : val hss = 0.2796
mean cv TSS: 0.4125
mean cv HSS: 0.1549
706/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.5293 : val tss = 0.2978 ::: train hss = 0.1043 : val hss = 0.1183
Fold 1: train tss = 0.7651 : val tss = 0.3043 ::: train hss = 0.5553 : val hss = 0.1323
Fold 2: train tss = 0.7662 : val tss = 0.6488 ::: train hss = 0.2558 : val hss = 0.2422
Fold 3: train tss = 0.8261 : val tss = 0.0722 ::: train hss = 0.3374 : val hss = 0.0249
Fold 4: train tss = 0.8011 : val tss = 0.6243 ::: train hss = 0.2602 : val hss = 0.2824
mean cv TSS: 0.3895
mean cv HSS: 0.1600
707/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0461 : val tss = 0.3607 ::: train hss = 0.0348 : val hss = 0.3152
Fold 1: train tss = 0.8120 : val tss = 0.4049 ::: train hss = 0.4015 : val hss = 0.1671
Fold 2: train tss = 0.7678 : val tss = 0.6920 ::: train hss = 0.2961 : val hss = 0.2841
Fold 3: train tss = 0.8061 : val tss = 0.1841 ::: train hss = 0.3525 : val hss = 0.0442
Fold 4: train tss = 0.7178 : val tss = 0.6602 ::: train hss = 0.2043 : val hss = 0.2527
mean cv TSS: 0.4604
mean cv HSS: 0.2126
708/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8265 : val tss = -0.0112 ::: train hss = 0.1425 : val hss = -0.0090
Fold 1: train tss = 0.8136 : val tss = 0.3587 ::: train hss = 0.3529 : val hss = 0.1585
Fold 2: train tss = 0.7608 : val tss = 0.6761 ::: train hss = 0.1883 : val hss = 0.2750
Fold 3: train tss = 0.7670 : val tss = 0.1837 ::: train hss = 0.2541 : val hss = 0.0243
Fold 4: train tss = 0.7394 : val tss = 0.6701 ::: train hss = 0.2390 : val hss = 0.2378
mean cv TSS: 0.3755
mean cv HSS: 0.1373
709/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.4868 : val tss = 0.2172 ::: train hss = 0.1391 : val hss = 0.1590
Fold 1: train tss = 0.7579 : val tss = 0.4393 ::: train hss = 0.3256 : val hss = 0.1656
Fold 2: train tss = 0.6909 : val tss = 0.6785 ::: train hss = 0.1466 : val hss = 0.2528
Fold 3: train tss = 0.7279 : val tss = 0.1541 ::: train hss = 0.2307 : val hss = 0.0292
Fold 4: train tss = 0.7012 : val tss = 0.6917 ::: train hss = 0.1943 : val hss = 0.2495
mean cv TSS: 0.4362
mean cv HSS: 0.1712
710/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.7597 : val tss = 0.2435 ::: train hss = 0.0819 : val hss = 0.0906
Fold 1: train tss = 0.8559 : val tss = 0.2937 ::: train hss = 0.3779 : val hss = 0.1249
Fold 2: train tss = 0.7974 : val tss = 0.7046 ::: train hss = 0.2506 : val hss = 0.2879
Fold 3: train tss = 0.8038 : val tss = 0.1371 ::: train hss = 0.2975 : val hss = 0.0301
Fold 4: train tss = 0.8017 : val tss = 0.7134 ::: train hss = 0.2759 : val hss = 0.3519
mean cv TSS: 0.4185
mean cv HSS: 0.1771
711/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.4906 : val tss = 0.3090 ::: train hss = 0.1817 : val hss = 0.1846
Fold 1: train tss = 0.7723 : val tss = 0.4641 ::: train hss = 0.2920 : val hss = 0.1886
Fold 2: train tss = 0.7068 : val tss = 0.6987 ::: train hss = 0.1957 : val hss = 0.2747
Fold 3: train tss = 0.7338 : val tss = 0.1804 ::: train hss = 0.2210 : val hss = 0.0419
Fold 4: train tss = 0.7195 : val tss = 0.6811 ::: train hss = 0.2088 : val hss = 0.2710
mean cv TSS: 0.4667
mean cv HSS: 0.1922
712/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5831 : val tss = 0.0870 ::: train hss = 0.1356 : val hss = 0.0503
Fold 1: train tss = 0.8775 : val tss = 0.3322 ::: train hss = 0.4091 : val hss = 0.1228
Fold 2: train tss = 0.7801 : val tss = 0.7040 ::: train hss = 0.2495 : val hss = 0.3399
Fold 3: train tss = 0.8323 : val tss = 0.1168 ::: train hss = 0.3610 : val hss = 0.0323
Fold 4: train tss = 0.7834 : val tss = 0.6567 ::: train hss = 0.2404 : val hss = 0.3138
mean cv TSS: 0.3793
mean cv HSS: 0.1718
713/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.7633 : val tss = 0.2880 ::: train hss = 0.0895 : val hss = 0.1196
Fold 1: train tss = 0.7758 : val tss = 0.3715 ::: train hss = 0.3310 : val hss = 0.1408
Fold 2: train tss = 0.6663 : val tss = 0.5796 ::: train hss = 0.1099 : val hss = 0.1706
Fold 3: train tss = 0.7641 : val tss = 0.2631 ::: train hss = 0.2684 : val hss = 0.0441
Fold 4: train tss = 0.7358 : val tss = 0.6760 ::: train hss = 0.2258 : val hss = 0.2742
mean cv TSS: 0.4356
mean cv HSS: 0.1498
714/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7888 : val tss = 0.1933 ::: train hss = 0.2446 : val hss = 0.1450
Fold 1: train tss = 0.8355 : val tss = 0.3532 ::: train hss = 0.1981 : val hss = 0.1512
Fold 2: train tss = 0.7706 : val tss = 0.6902 ::: train hss = 0.2542 : val hss = 0.2693
Fold 3: train tss = 0.7456 : val tss = 0.2332 ::: train hss = 0.1956 : val hss = 0.0462
Fold 4: train tss = 0.7531 : val tss = 0.6759 ::: train hss = 0.2179 : val hss = 0.2837
mean cv TSS: 0.4292
mean cv HSS: 0.1791
715/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.4377 : val tss = 0.1164 ::: train hss = 0.1337 : val hss = 0.0664
Fold 1: train tss = 0.7609 : val tss = 0.4286 ::: train hss = 0.3716 : val hss = 0.1946
Fold 2: train tss = 0.7068 : val tss = 0.7137 ::: train hss = 0.1840 : val hss = 0.2917
Fold 3: train tss = 0.7177 : val tss = 0.3205 ::: train hss = 0.2114 : val hss = 0.0444

Fold 4: train tss = 0.7153 : val tss = 0.6711 ::: train hss = 0.2051 : val hss = 0.2388
mean cv TSS: 0.4501
mean cv HSS: 0.1672
716/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8498 : val tss = 0.1485 ::: train hss = 0.0390 : val hss = 0.0607
Fold 1: train tss = 0.8821 : val tss = 0.3799 ::: train hss = 0.3807 : val hss = 0.1588
Fold 2: train tss = 0.8345 : val tss = 0.6907 ::: train hss = 0.2918 : val hss = 0.3201
Fold 3: train tss = 0.8488 : val tss = 0.1214 ::: train hss = 0.3369 : val hss = 0.0581
Fold 4: train tss = 0.7843 : val tss = 0.6459 ::: train hss = 0.2500 : val hss = 0.2547
mean cv TSS: 0.3973
mean cv HSS: 0.1705
717/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.1244 : val tss = -0.0017 ::: train hss = 0.0211 : val hss = -0.0014
Fold 1: train tss = 0.7818 : val tss = 0.4354 ::: train hss = 0.2969 : val hss = 0.1695
Fold 2: train tss = 0.7439 : val tss = 0.6496 ::: train hss = 0.3192 : val hss = 0.2264
Fold 3: train tss = 0.7744 : val tss = 0.2989 ::: train hss = 0.2721 : val hss = 0.0823
Fold 4: train tss = 0.7288 : val tss = 0.6465 ::: train hss = 0.2028 : val hss = 0.2342
mean cv TSS: 0.4058
mean cv HSS: 0.1422
718/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8724 : val tss = 0.0965 ::: train hss = 0.1307 : val hss = 0.0628
Fold 1: train tss = 0.9097 : val tss = 0.3012 ::: train hss = 0.3938 : val hss = 0.1215
Fold 2: train tss = 0.8024 : val tss = 0.6676 ::: train hss = 0.2581 : val hss = 0.2564
Fold 3: train tss = 0.8457 : val tss = 0.2890 ::: train hss = 0.3998 : val hss = 0.0667
Fold 4: train tss = 0.7820 : val tss = 0.6470 ::: train hss = 0.2648 : val hss = 0.2553
mean cv TSS: 0.4003
mean cv HSS: 0.1525
719/864
{'batch_size': 256, 'bce_pos_class_weight': 50, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0957 : val tss = 0.0000 ::: train hss = 0.0660 : val hss = 0.0000
Fold 1: train tss = 0.8032 : val tss = 0.3568 ::: train hss = 0.3687 : val hss = 0.1444
Fold 2: train tss = 0.7600 : val tss = 0.6783 ::: train hss = 0.2531 : val hss = 0.2652
Fold 3: train tss = 0.7565 : val tss = 0.1272 ::: train hss = 0.2571 : val hss = 0.0175
Fold 4: train tss = 0.7389 : val tss = 0.6539 ::: train hss = 0.2051 : val hss = 0.2628
mean cv TSS: 0.3632
mean cv HSS: 0.1380
720/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5251 : val tss = 0.0572 ::: train hss = 0.0883 : val hss = 0.0269
Fold 1: train tss = 0.7522 : val tss = 0.3968 ::: train hss = 0.2610 : val hss = 0.1999
Fold 2: train tss = 0.7323 : val tss = 0.5885 ::: train hss = 0.1669 : val hss = 0.1897
Fold 3: train tss = 0.7203 : val tss = 0.4281 ::: train hss = 0.1946 : val hss = 0.0647
Fold 4: train tss = 0.6930 : val tss = 0.6393 ::: train hss = 0.1442 : val hss = 0.2078
mean cv TSS: 0.4220
mean cv HSS: 0.1378
721/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.5322 : val tss = 0.3236 ::: train hss = 0.1189 : val hss = 0.1468
Fold 1: train tss = 0.7687 : val tss = 0.4166 ::: train hss = 0.3152 : val hss = 0.1954
Fold 2: train tss = 0.7095 : val tss = 0.6304 ::: train hss = 0.1456 : val hss = 0.2074
Fold 3: train tss = 0.6958 : val tss = 0.1267 ::: train hss = 0.1638 : val hss = 0.0191
Fold 4: train tss = 0.6940 : val tss = 0.6132 ::: train hss = 0.1522 : val hss = 0.1930
mean cv TSS: 0.4221
mean cv HSS: 0.1523
722/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.2847 : val tss = 0.2330 ::: train hss = 0.0744 : val hss = 0.1069
Fold 1: train tss = 0.7698 : val tss = 0.2704 ::: train hss = 0.2644 : val hss = 0.0663
Fold 2: train tss = 0.6869 : val tss = 0.5789 ::: train hss = 0.1231 : val hss = 0.1785
Fold 3: train tss = 0.6876 : val tss = 0.1795 ::: train hss = 0.1571 : val hss = 0.0191
Fold 4: train tss = 0.6461 : val tss = 0.6131 ::: train hss = 0.1087 : val hss = 0.1985
mean cv TSS: 0.3750
mean cv HSS: 0.1139
723/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.3691 : val tss = 0.4042 ::: train hss = 0.0518 : val hss = 0.1663
Fold 1: train tss = 0.7622 : val tss = 0.4360 ::: train hss = 0.3035 : val hss = 0.1514
Fold 2: train tss = 0.7131 : val tss = 0.6019 ::: train hss = 0.1533 : val hss = 0.1868
Fold 3: train tss = 0.6714 : val tss = 0.5356 ::: train hss = 0.1428 : val hss = 0.0613
Fold 4: train tss = 0.7219 : val tss = 0.6400 ::: train hss = 0.1737 : val hss = 0.2281
mean cv TSS: 0.5235
mean cv HSS: 0.1588
724/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.3422 : val tss = -0.0365 ::: train hss = 0.0269 : val hss = -0.0236
Fold 1: train tss = 0.7599 : val tss = 0.3785 ::: train hss = 0.3372 : val hss = 0.1633
Fold 2: train tss = 0.6937 : val tss = 0.6297 ::: train hss = 0.1324 : val hss = 0.2070
Fold 3: train tss = 0.7312 : val tss = 0.5198 ::: train hss = 0.1821 : val hss = 0.0399
Fold 4: train tss = 0.7089 : val tss = 0.6868 ::: train hss = 0.1665 : val hss = 0.2448
mean cv TSS: 0.4357
mean cv HSS: 0.1263
725/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7347 : val tss = 0.4930 ::: train hss = 0.2740 : val hss = 0.0897
Fold 2: train tss = 0.7131 : val tss = 0.6461 ::: train hss = 0.1491 : val hss = 0.2209
Fold 3: train tss = 0.6547 : val tss = 0.2928 ::: train hss = 0.1344 : val hss = 0.0232
Fold 4: train tss = 0.6843 : val tss = 0.5746 ::: train hss = 0.1411 : val hss = 0.1585
mean cv TSS: 0.4013
mean cv HSS: 0.0984
726/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}

Total number of parameters: 237
Fold 0: train tss = 0.8119 : val tss = 0.2968 ::: train hss = 0.0917 : val hss = 0.1169
Fold 1: train tss = 0.8164 : val tss = 0.2898 ::: train hss = 0.2186 : val hss = 0.0828
Fold 2: train tss = 0.7454 : val tss = 0.6512 ::: train hss = 0.1807 : val hss = 0.2324
Fold 3: train tss = 0.7692 : val tss = 0.1830 ::: train hss = 0.2197 : val hss = 0.0252
Fold 4: train tss = 0.7384 : val tss = 0.6158 ::: train hss = 0.1708 : val hss = 0.2279
mean cv TSS: 0.4073
mean cv HSS: 0.1370
727/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.3392 : val tss = 0.3246 ::: train hss = 0.1160 : val hss = 0.1833
Fold 1: train tss = 0.7798 : val tss = 0.3820 ::: train hss = 0.3550 : val hss = 0.1789
Fold 2: train tss = 0.7215 : val tss = 0.5797 ::: train hss = 0.1482 : val hss = 0.1778
Fold 3: train tss = 0.6739 : val tss = 0.1308 ::: train hss = 0.1508 : val hss = 0.0202
Fold 4: train tss = 0.6955 : val tss = 0.6703 ::: train hss = 0.1596 : val hss = 0.2391
mean cv TSS: 0.4175
mean cv HSS: 0.1598
728/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7510 : val tss = 0.3090 ::: train hss = 0.2723 : val hss = 0.0676
Fold 2: train tss = 0.7344 : val tss = 0.6618 ::: train hss = 0.1871 : val hss = 0.2391
Fold 3: train tss = 0.7593 : val tss = 0.4348 ::: train hss = 0.2358 : val hss = 0.0811
Fold 4: train tss = 0.7333 : val tss = 0.5596 ::: train hss = 0.1893 : val hss = 0.1952
mean cv TSS: 0.3930
mean cv HSS: 0.1166
729/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = -0.0492 : val tss = 0.0000 ::: train hss = -0.0023 : val hss = 0.0000
Fold 1: train tss = 0.7287 : val tss = 0.4055 ::: train hss = 0.3047 : val hss = 0.1617
Fold 2: train tss = 0.7291 : val tss = 0.6484 ::: train hss = 0.1705 : val hss = 0.2218
Fold 3: train tss = 0.6983 : val tss = 0.2205 ::: train hss = 0.1798 : val hss = 0.0321
Fold 4: train tss = 0.7160 : val tss = 0.6116 ::: train hss = 0.1616 : val hss = 0.2179
mean cv TSS: 0.3772
mean cv HSS: 0.1267
730/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7632 : val tss = 0.4073 ::: train hss = 0.3086 : val hss = 0.1806
Fold 2: train tss = 0.7396 : val tss = 0.6882 ::: train hss = 0.1924 : val hss = 0.2979
Fold 3: train tss = 0.7269 : val tss = 0.2723 ::: train hss = 0.1927 : val hss = 0.0372
Fold 4: train tss = 0.7341 : val tss = 0.6499 ::: train hss = 0.2110 : val hss = 0.2558
mean cv TSS: 0.4036
mean cv HSS: 0.1543
731/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.7196 : val tss = 0.6236 ::: train hss = 0.1495 : val hss = 0.2016
Fold 3: train tss = 0.7210 : val tss = 0.1259 ::: train hss = 0.2164 : val hss = 0.0199
Fold 4: train tss = 0.7332 : val tss = 0.6394 ::: train hss = 0.1792 : val hss = 0.2354
mean cv TSS: 0.2778
mean cv HSS: 0.0914
732/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.8617 : val tss = -0.0560 ::: train hss = 0.0968 : val hss = -0.0323
Fold 1: train tss = 0.7541 : val tss = 0.4548 ::: train hss = 0.1404 : val hss = 0.1150
Fold 2: train tss = 0.6808 : val tss = 0.5736 ::: train hss = 0.1218 : val hss = 0.1674
Fold 3: train tss = 0.7181 : val tss = 0.1078 ::: train hss = 0.1636 : val hss = 0.0191
Fold 4: train tss = 0.6938 : val tss = 0.5773 ::: train hss = 0.1444 : val hss = 0.1892
mean cv TSS: 0.3315
mean cv HSS: 0.0917
733/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.5334 : val tss = 0.3025 ::: train hss = 0.1262 : val hss = 0.1503
Fold 1: train tss = 0.7544 : val tss = 0.4013 ::: train hss = 0.2402 : val hss = 0.1511
Fold 2: train tss = 0.7149 : val tss = 0.6243 ::: train hss = 0.1424 : val hss = 0.2021
Fold 3: train tss = 0.6878 : val tss = 0.1588 ::: train hss = 0.1587 : val hss = 0.0292
Fold 4: train tss = 0.6663 : val tss = 0.6271 ::: train hss = 0.1333 : val hss = 0.2025
mean cv TSS: 0.4228
mean cv HSS: 0.1470
734/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4287 : val tss = 0.3835 ::: train hss = 0.0832 : val hss = 0.1997
Fold 1: train tss = 0.8088 : val tss = 0.2973 ::: train hss = 0.2865 : val hss = 0.1838
Fold 2: train tss = 0.7589 : val tss = 0.6858 ::: train hss = 0.1689 : val hss = 0.2659
Fold 3: train tss = 0.6403 : val tss = 0.1508 ::: train hss = 0.1181 : val hss = 0.0106
Fold 4: train tss = 0.7129 : val tss = 0.6126 ::: train hss = 0.1531 : val hss = 0.2066
mean cv TSS: 0.4260
mean cv HSS: 0.1733
735/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.4397 : val tss = 0.3494 ::: train hss = 0.1529 : val hss = 0.1851
Fold 1: train tss = 0.7670 : val tss = 0.4534 ::: train hss = 0.1900 : val hss = 0.1601
Fold 2: train tss = 0.7029 : val tss = 0.6138 ::: train hss = 0.1524 : val hss = 0.1952
Fold 3: train tss = 0.6859 : val tss = 0.2977 ::: train hss = 0.1483 : val hss = 0.0305
Fold 4: train tss = 0.6927 : val tss = 0.6384 ::: train hss = 0.1495 : val hss = 0.2132
mean cv TSS: 0.4705
mean cv HSS: 0.1568
736/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.3752 : val tss = -0.0172 ::: train hss = 0.0641 : val hss = -0.0149
Fold 1: train tss = 0.7270 : val tss = 0.1707 ::: train hss = 0.1823 : val hss = 0.0281
Fold 2: train tss = 0.6503 : val tss = 0.5405 ::: train hss = 0.1228 : val hss = 0.1402
Fold 3: train tss = 0.6444 : val tss = 0.3081 ::: train hss = 0.1235 : val hss = 0.0224

Fold 4: train tss = 0.6474 : val tss = 0.6168 ::: train hss = 0.1120 : val hss = 0.1900
mean cv TSS: 0.3238
mean cv HSS: 0.0732
737/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.1374 : val tss = 0.4043 ::: train hss = 0.0429 : val hss = 0.2006
Fold 1: train tss = 0.7477 : val tss = 0.4529 ::: train hss = 0.2948 : val hss = 0.2199
Fold 2: train tss = 0.7180 : val tss = 0.6415 ::: train hss = 0.1465 : val hss = 0.2171
Fold 3: train tss = 0.6083 : val tss = 0.2283 ::: train hss = 0.1006 : val hss = 0.0149
Fold 4: train tss = 0.6988 : val tss = 0.6513 ::: train hss = 0.1467 : val hss = 0.2413
mean cv TSS: 0.4757
mean cv HSS: 0.1788
738/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.8255 : val tss = 0.3366 ::: train hss = 0.1370 : val hss = 0.1646
Fold 1: train tss = 0.8319 : val tss = 0.3384 ::: train hss = 0.2951 : val hss = 0.1468
Fold 2: train tss = 0.7249 : val tss = 0.6314 ::: train hss = 0.1371 : val hss = 0.2114
Fold 3: train tss = 0.7469 : val tss = 0.2842 ::: train hss = 0.1969 : val hss = 0.0435
Fold 4: train tss = 0.7434 : val tss = 0.6257 ::: train hss = 0.1793 : val hss = 0.2166
mean cv TSS: 0.4433
mean cv HSS: 0.1566
739/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.4877 : val tss = 0.0635 ::: train hss = 0.1478 : val hss = 0.0335
Fold 1: train tss = 0.8083 : val tss = 0.2658 ::: train hss = 0.2537 : val hss = 0.0915
Fold 2: train tss = 0.6825 : val tss = 0.6128 ::: train hss = 0.1181 : val hss = 0.1944
Fold 3: train tss = 0.6702 : val tss = 0.5123 ::: train hss = 0.1517 : val hss = 0.0597
Fold 4: train tss = 0.6965 : val tss = 0.6254 ::: train hss = 0.1537 : val hss = 0.2107
mean cv TSS: 0.4160
mean cv HSS: 0.1180
740/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7922 : val tss = 0.4833 ::: train hss = 0.2194 : val hss = 0.2504
Fold 2: train tss = 0.7339 : val tss = 0.6585 ::: train hss = 0.1671 : val hss = 0.2303
Fold 3: train tss = 0.7573 : val tss = 0.0659 ::: train hss = 0.2117 : val hss = 0.0113
Fold 4: train tss = 0.7327 : val tss = 0.6614 ::: train hss = 0.1810 : val hss = 0.2638
mean cv TSS: 0.3738
mean cv HSS: 0.1512
741/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6577 : val tss = 0.4245 ::: train hss = 0.1573 : val hss = 0.1444
Fold 2: train tss = 0.7308 : val tss = 0.6692 ::: train hss = 0.1572 : val hss = 0.2662
Fold 3: train tss = 0.7291 : val tss = 0.1747 ::: train hss = 0.2041 : val hss = 0.0254
Fold 4: train tss = 0.7285 : val tss = 0.5915 ::: train hss = 0.1782 : val hss = 0.1772
mean cv TSS: 0.3720
mean cv HSS: 0.1226
742/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7655 : val tss = 0.4033 ::: train hss = 0.2808 : val hss = 0.1590
Fold 2: train tss = 0.7554 : val tss = 0.6954 ::: train hss = 0.1877 : val hss = 0.2713
Fold 3: train tss = 0.7834 : val tss = 0.1371 ::: train hss = 0.2842 : val hss = 0.0301
Fold 4: train tss = 0.7767 : val tss = 0.5710 ::: train hss = 0.2353 : val hss = 0.2522
mean cv TSS: 0.3614
mean cv HSS: 0.1425
743/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7482 : val tss = 0.2171 ::: train hss = 0.2971 : val hss = 0.1452
Fold 2: train tss = 0.7084 : val tss = 0.6061 ::: train hss = 0.1461 : val hss = 0.1884
Fold 3: train tss = 0.7557 : val tss = 0.1861 ::: train hss = 0.2547 : val hss = 0.0365
Fold 4: train tss = 0.7235 : val tss = 0.6095 ::: train hss = 0.1863 : val hss = 0.2042
mean cv TSS: 0.3238
mean cv HSS: 0.1149
744/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7244 : val tss = 0.1306 ::: train hss = 0.1168 : val hss = 0.0694
Fold 1: train tss = 0.8201 : val tss = 0.4169 ::: train hss = 0.1995 : val hss = 0.1458
Fold 2: train tss = 0.7431 : val tss = 0.6335 ::: train hss = 0.1588 : val hss = 0.2067
Fold 3: train tss = 0.7655 : val tss = 0.0827 ::: train hss = 0.2212 : val hss = 0.0159
Fold 4: train tss = 0.7496 : val tss = 0.6477 ::: train hss = 0.1835 : val hss = 0.2290
mean cv TSS: 0.3823
mean cv HSS: 0.1334
745/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5336 : val tss = 0.3240 ::: train hss = 0.1278 : val hss = 0.1549
Fold 1: train tss = 0.7587 : val tss = 0.4156 ::: train hss = 0.2406 : val hss = 0.1358
Fold 2: train tss = 0.7011 : val tss = 0.5916 ::: train hss = 0.1335 : val hss = 0.1799
Fold 3: train tss = 0.7109 : val tss = 0.2739 ::: train hss = 0.1805 : val hss = 0.0345
Fold 4: train tss = 0.7123 : val tss = 0.6251 ::: train hss = 0.1711 : val hss = 0.2027
mean cv TSS: 0.4460
mean cv HSS: 0.1416
746/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.0939 : val tss = 0.0022 ::: train hss = 0.0514 : val hss = 0.0025
Fold 1: train tss = 0.8335 : val tss = 0.4441 ::: train hss = 0.2550 : val hss = 0.1552
Fold 2: train tss = 0.7374 : val tss = 0.6383 ::: train hss = 0.1642 : val hss = 0.2248
Fold 3: train tss = 0.7122 : val tss = 0.5376 ::: train hss = 0.1671 : val hss = 0.0576
Fold 4: train tss = 0.6865 : val tss = 0.6070 ::: train hss = 0.1390 : val hss = 0.1827
mean cv TSS: 0.4458
mean cv HSS: 0.1246
747/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.0000 : val tss = 0.1448 ::: train hss = 0.0000 : val hss = 0.2181

Fold 1: train tss = 0.7709 : val tss = 0.4062 ::: train hss = 0.3048 : val hss = 0.1313
Fold 2: train tss = 0.7364 : val tss = 0.6620 ::: train hss = 0.1681 : val hss = 0.2334
Fold 3: train tss = 0.7348 : val tss = 0.2649 ::: train hss = 0.2035 : val hss = 0.0383
Fold 4: train tss = 0.7276 : val tss = 0.6340 ::: train hss = 0.1797 : val hss = 0.2366
mean cv TSS: 0.4224
mean cv HSS: 0.1715
748/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.2448 : val tss = 0.1158 ::: train hss = 0.1440 : val hss = 0.1010
Fold 1: train tss = 0.7425 : val tss = 0.3042 ::: train hss = 0.2558 : val hss = 0.1051
Fold 2: train tss = 0.7189 : val tss = 0.6448 ::: train hss = 0.1395 : val hss = 0.2198
Fold 3: train tss = 0.7709 : val tss = 0.1049 ::: train hss = 0.2334 : val hss = 0.0194
Fold 4: train tss = 0.7544 : val tss = 0.6259 ::: train hss = 0.1858 : val hss = 0.2140
mean cv TSS: 0.3591
mean cv HSS: 0.1319
749/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = -0.0007 : val tss = 0.2422 ::: train hss = -0.0011 : val hss = 0.2814
Fold 1: train tss = 0.7791 : val tss = 0.4222 ::: train hss = 0.4139 : val hss = 0.1621
Fold 2: train tss = 0.6109 : val tss = 0.4757 ::: train hss = 0.0755 : val hss = 0.1194
Fold 3: train tss = 0.7281 : val tss = 0.1724 ::: train hss = 0.1945 : val hss = 0.0226
Fold 4: train tss = 0.7133 : val tss = 0.6481 ::: train hss = 0.1630 : val hss = 0.2156
mean cv TSS: 0.3921
mean cv HSS: 0.1602
750/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.5359 : val tss = 0.2999 ::: train hss = 0.1448 : val hss = 0.1614
Fold 1: train tss = 0.8391 : val tss = 0.2869 ::: train hss = 0.3796 : val hss = 0.1197
Fold 2: train tss = 0.7600 : val tss = 0.6421 ::: train hss = 0.1916 : val hss = 0.2310
Fold 3: train tss = 0.7756 : val tss = 0.0890 ::: train hss = 0.2667 : val hss = 0.0167
Fold 4: train tss = 0.7705 : val tss = 0.6856 ::: train hss = 0.2050 : val hss = 0.2775
mean cv TSS: 0.4007
mean cv HSS: 0.1613
751/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.6262 : val tss = 0.0805 ::: train hss = 0.1084 : val hss = 0.0371
Fold 1: train tss = 0.7668 : val tss = 0.4349 ::: train hss = 0.2690 : val hss = 0.1457
Fold 2: train tss = 0.7304 : val tss = 0.6361 ::: train hss = 0.1649 : val hss = 0.2119
Fold 3: train tss = 0.7017 : val tss = 0.3344 ::: train hss = 0.1664 : val hss = 0.0525
Fold 4: train tss = 0.7269 : val tss = 0.6406 ::: train hss = 0.1732 : val hss = 0.2169
mean cv TSS: 0.4253
mean cv HSS: 0.1328
752/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7794 : val tss = 0.4351 ::: train hss = 0.3819 : val hss = 0.1662
Fold 2: train tss = 0.7412 : val tss = 0.6144 ::: train hss = 0.1774 : val hss = 0.1955
Fold 3: train tss = 0.8150 : val tss = 0.0560 ::: train hss = 0.2739 : val hss = 0.0108
Fold 4: train tss = 0.7723 : val tss = 0.6435 ::: train hss = 0.2318 : val hss = 0.2801
mean cv TSS: 0.3498
mean cv HSS: 0.1305
753/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7759 : val tss = 0.4270 ::: train hss = 0.4672 : val hss = 0.1491
Fold 2: train tss = 0.7316 : val tss = 0.6813 ::: train hss = 0.1735 : val hss = 0.2511
Fold 3: train tss = 0.7416 : val tss = 0.2222 ::: train hss = 0.2151 : val hss = 0.0311
Fold 4: train tss = 0.7476 : val tss = 0.6723 ::: train hss = 0.2031 : val hss = 0.2679
mean cv TSS: 0.4005
mean cv HSS: 0.1398
754/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7822 : val tss = 0.2933 ::: train hss = 0.5488 : val hss = 0.1270
Fold 2: train tss = 0.7739 : val tss = 0.7147 ::: train hss = 0.2468 : val hss = 0.2971
Fold 3: train tss = 0.7569 : val tss = 0.1360 ::: train hss = 0.2405 : val hss = 0.0196
Fold 4: train tss = 0.8056 : val tss = 0.6690 ::: train hss = 0.2419 : val hss = 0.2622
mean cv TSS: 0.3626
mean cv HSS: 0.1412
755/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7668 : val tss = 0.4290 ::: train hss = 0.3838 : val hss = 0.1564
Fold 2: train tss = 0.7292 : val tss = 0.6753 ::: train hss = 0.1745 : val hss = 0.2487
Fold 3: train tss = 0.7770 : val tss = 0.2129 ::: train hss = 0.2847 : val hss = 0.0518
Fold 4: train tss = 0.7498 : val tss = 0.6588 ::: train hss = 0.2012 : val hss = 0.2576
mean cv TSS: 0.3952
mean cv HSS: 0.1429
756/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.8144 : val tss = -0.0266 ::: train hss = 0.0978 : val hss = -0.0161
Fold 1: train tss = 0.8606 : val tss = 0.3188 ::: train hss = 0.2620 : val hss = 0.1141
Fold 2: train tss = 0.7418 : val tss = 0.5962 ::: train hss = 0.1488 : val hss = 0.1810
Fold 3: train tss = 0.7668 : val tss = 0.3467 ::: train hss = 0.2271 : val hss = 0.0477
Fold 4: train tss = 0.7269 : val tss = 0.6553 ::: train hss = 0.1631 : val hss = 0.2472
mean cv TSS: 0.3781
mean cv HSS: 0.1148
757/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.7738 : val tss = 0.3195 ::: train hss = 0.1219 : val hss = 0.1463
Fold 1: train tss = 0.7776 : val tss = 0.3977 ::: train hss = 0.2481 : val hss = 0.1497
Fold 2: train tss = 0.6783 : val tss = 0.5910 ::: train hss = 0.1154 : val hss = 0.1777
Fold 3: train tss = 0.6934 : val tss = 0.3528 ::: train hss = 0.1629 : val hss = 0.0554
Fold 4: train tss = 0.6991 : val tss = 0.6361 ::: train hss = 0.1582 : val hss = 0.2123
mean cv TSS: 0.4594
mean cv HSS: 0.1483
758/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.8034 : val tss = 0.3077 ::: train hss = 0.0758 : val hss = 0.1127

Fold 1: train tss = 0.8637 : val tss = 0.3898 ::: train hss = 0.2725 : val hss = 0.1010
Fold 2: train tss = 0.7064 : val tss = 0.5897 ::: train hss = 0.1319 : val hss = 0.1845
Fold 3: train tss = 0.7901 : val tss = 0.1699 ::: train hss = 0.2597 : val hss = 0.0462
Fold 4: train tss = 0.7333 : val tss = 0.6622 ::: train hss = 0.1620 : val hss = 0.2381
mean cv TSS: 0.4239
mean cv HSS: 0.1365
759/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.7088 : val tss = 0.3042 ::: train hss = 0.0752 : val hss = 0.1221
Fold 1: train tss = 0.7946 : val tss = 0.4357 ::: train hss = 0.2496 : val hss = 0.1421
Fold 2: train tss = 0.7602 : val tss = 0.6581 ::: train hss = 0.2013 : val hss = 0.2468
Fold 3: train tss = 0.7443 : val tss = 0.0753 ::: train hss = 0.2005 : val hss = 0.0129
Fold 4: train tss = 0.6875 : val tss = 0.6036 ::: train hss = 0.1496 : val hss = 0.1819
mean cv TSS: 0.4154
mean cv HSS: 0.1412
760/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5274 : val tss = 0.3003 ::: train hss = 0.0963 : val hss = 0.1082
Fold 1: train tss = 0.8359 : val tss = 0.3504 ::: train hss = 0.2946 : val hss = 0.1182
Fold 2: train tss = 0.7545 : val tss = 0.6713 ::: train hss = 0.1728 : val hss = 0.2567
Fold 3: train tss = 0.7537 : val tss = 0.1094 ::: train hss = 0.2040 : val hss = 0.0158
Fold 4: train tss = 0.7430 : val tss = 0.6828 ::: train hss = 0.1863 : val hss = 0.2639
mean cv TSS: 0.4229
mean cv HSS: 0.1526
761/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.8428 : val tss = 0.2932 ::: train hss = 0.0657 : val hss = 0.1122
Fold 1: train tss = 0.7514 : val tss = 0.4517 ::: train hss = 0.2743 : val hss = 0.1445
Fold 2: train tss = 0.7275 : val tss = 0.6682 ::: train hss = 0.1470 : val hss = 0.2461
Fold 3: train tss = 0.7259 : val tss = 0.2609 ::: train hss = 0.1851 : val hss = 0.0353
Fold 4: train tss = 0.6552 : val tss = 0.6055 ::: train hss = 0.1129 : val hss = 0.1709
mean cv TSS: 0.4559
mean cv HSS: 0.1418
762/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8807 : val tss = 0.3127 ::: train hss = 0.1779 : val hss = 0.1347
Fold 1: train tss = 0.8515 : val tss = 0.2296 ::: train hss = 0.4073 : val hss = 0.0850
Fold 2: train tss = 0.7674 : val tss = 0.5885 ::: train hss = 0.1749 : val hss = 0.1798
Fold 3: train tss = 0.7550 : val tss = 0.1911 ::: train hss = 0.1996 : val hss = 0.0262
Fold 4: train tss = 0.7570 : val tss = 0.6157 ::: train hss = 0.1883 : val hss = 0.2074
mean cv TSS: 0.3875
mean cv HSS: 0.1266
763/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.6263 : val tss = 0.0477 ::: train hss = 0.1089 : val hss = 0.0237
Fold 1: train tss = 0.7516 : val tss = 0.5298 ::: train hss = 0.1190 : val hss = 0.1909
Fold 2: train tss = 0.7196 : val tss = 0.5738 ::: train hss = 0.1452 : val hss = 0.1681
Fold 3: train tss = 0.7466 : val tss = 0.3573 ::: train hss = 0.2202 : val hss = 0.0387
Fold 4: train tss = 0.7085 : val tss = 0.6206 ::: train hss = 0.1677 : val hss = 0.1953
mean cv TSS: 0.4258
mean cv HSS: 0.1233
764/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8092 : val tss = 0.3032 ::: train hss = 0.0861 : val hss = 0.0938
Fold 1: train tss = 0.7581 : val tss = 0.3073 ::: train hss = 0.4622 : val hss = 0.1027
Fold 2: train tss = 0.7717 : val tss = 0.7092 ::: train hss = 0.2386 : val hss = 0.3033
Fold 3: train tss = 0.8019 : val tss = 0.0374 ::: train hss = 0.2600 : val hss = 0.0083
Fold 4: train tss = 0.7898 : val tss = 0.6380 ::: train hss = 0.2504 : val hss = 0.2605
mean cv TSS: 0.3990
mean cv HSS: 0.1537
765/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7685 : val tss = 0.4731 ::: train hss = 0.3973 : val hss = 0.2290
Fold 2: train tss = 0.7330 : val tss = 0.6613 ::: train hss = 0.1678 : val hss = 0.2376
Fold 3: train tss = 0.7790 : val tss = 0.1373 ::: train hss = 0.2319 : val hss = 0.0209
Fold 4: train tss = 0.7360 : val tss = 0.6214 ::: train hss = 0.1921 : val hss = 0.2258
mean cv TSS: 0.3786
mean cv HSS: 0.1426
766/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.7511 : val tss = 0.2248 ::: train hss = 0.0680 : val hss = 0.0709
Fold 1: train tss = 0.8245 : val tss = 0.2477 ::: train hss = 0.3681 : val hss = 0.1184
Fold 2: train tss = 0.7693 : val tss = 0.6630 ::: train hss = 0.1936 : val hss = 0.2325
Fold 3: train tss = 0.7855 : val tss = 0.0881 ::: train hss = 0.2496 : val hss = 0.0189
Fold 4: train tss = 0.7847 : val tss = 0.6572 ::: train hss = 0.2519 : val hss = 0.2572
mean cv TSS: 0.3762
mean cv HSS: 0.1396
767/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0940 : val tss = 0.3739 ::: train hss = 0.0522 : val hss = 0.2684
Fold 1: train tss = 0.8220 : val tss = 0.3682 ::: train hss = 0.2580 : val hss = 0.1446
Fold 2: train tss = 0.7469 : val tss = 0.6659 ::: train hss = 0.1731 : val hss = 0.2409
Fold 3: train tss = 0.7512 : val tss = 0.1393 ::: train hss = 0.2435 : val hss = 0.0254
Fold 4: train tss = 0.7419 : val tss = 0.6391 ::: train hss = 0.1967 : val hss = 0.2340
mean cv TSS: 0.4373
mean cv HSS: 0.1827
768/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.7387 : val tss = -0.0213 ::: train hss = 0.2291 : val hss = -0.0159
Fold 1: train tss = 0.8742 : val tss = 0.3959 ::: train hss = 0.2656 : val hss = 0.1300
Fold 2: train tss = 0.7766 : val tss = 0.6538 ::: train hss = 0.1630 : val hss = 0.2300
Fold 3: train tss = 0.7964 : val tss = 0.1092 ::: train hss = 0.2507 : val hss = 0.0208
Fold 4: train tss = 0.7761 : val tss = 0.6999 ::: train hss = 0.2157 : val hss = 0.2949
mean cv TSS: 0.3675
mean cv HSS: 0.1320
769/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}

Total number of parameters: 2191
Fold 0: train tss = 0.7253 : val tss = 0.2581 ::: train hss = 0.1209 : val hss = 0.1302
Fold 1: train tss = 0.7747 : val tss = 0.4323 ::: train hss = 0.2842 : val hss = 0.1657
Fold 2: train tss = 0.7200 : val tss = 0.6536 ::: train hss = 0.1671 : val hss = 0.2270
Fold 3: train tss = 0.7297 : val tss = 0.3357 ::: train hss = 0.1953 : val hss = 0.0504
Fold 4: train tss = 0.6964 : val tss = 0.6477 ::: train hss = 0.1619 : val hss = 0.2220
mean cv TSS: 0.4655
mean cv HSS: 0.1591
770/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9661 : val tss = 0.1025 ::: train hss = 0.1200 : val hss = 0.0479
Fold 1: train tss = 0.8495 : val tss = 0.4639 ::: train hss = 0.2532 : val hss = 0.1641
Fold 2: train tss = 0.7889 : val tss = 0.6919 ::: train hss = 0.2031 : val hss = 0.2550
Fold 3: train tss = 0.8004 : val tss = 0.0406 ::: train hss = 0.2503 : val hss = 0.0109
Fold 4: train tss = 0.8039 : val tss = 0.6904 ::: train hss = 0.2281 : val hss = 0.2988
mean cv TSS: 0.3978
mean cv HSS: 0.1553
771/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.8604 : val tss = 0.3190 ::: train hss = 0.0938 : val hss = 0.1178
Fold 1: train tss = 0.8158 : val tss = 0.4014 ::: train hss = 0.2076 : val hss = 0.1111
Fold 2: train tss = 0.7557 : val tss = 0.6761 ::: train hss = 0.1902 : val hss = 0.2462
Fold 3: train tss = 0.7471 : val tss = 0.2594 ::: train hss = 0.2050 : val hss = 0.0450
Fold 4: train tss = 0.7400 : val tss = 0.6460 ::: train hss = 0.1931 : val hss = 0.2403
mean cv TSS: 0.4604
mean cv HSS: 0.1521
772/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8272 : val tss = 0.3004 ::: train hss = 0.1464 : val hss = 0.1330
Fold 1: train tss = 0.8513 : val tss = 0.2931 ::: train hss = 0.2728 : val hss = 0.1077
Fold 2: train tss = 0.7664 : val tss = 0.6194 ::: train hss = 0.1721 : val hss = 0.2007
Fold 3: train tss = 0.8258 : val tss = 0.0614 ::: train hss = 0.2914 : val hss = 0.0115
Fold 4: train tss = 0.7914 : val tss = 0.6713 ::: train hss = 0.2229 : val hss = 0.2518
mean cv TSS: 0.3891
mean cv HSS: 0.1410
773/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5227 : val tss = 0.3390 ::: train hss = 0.0810 : val hss = 0.1472
Fold 1: train tss = 0.7530 : val tss = 0.3003 ::: train hss = 0.1653 : val hss = 0.0642
Fold 2: train tss = 0.7639 : val tss = 0.6541 ::: train hss = 0.2020 : val hss = 0.2267
Fold 3: train tss = 0.5629 : val tss = 0.3652 ::: train hss = 0.0856 : val hss = 0.0314
Fold 4: train tss = 0.7316 : val tss = 0.6743 ::: train hss = 0.1737 : val hss = 0.2600
mean cv TSS: 0.4666
mean cv HSS: 0.1459
774/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9307 : val tss = -0.0010 ::: train hss = 0.1871 : val hss = -0.0007
Fold 1: train tss = 0.8508 : val tss = 0.3387 ::: train hss = 0.2711 : val hss = 0.1316
Fold 2: train tss = 0.7648 : val tss = 0.6603 ::: train hss = 0.1589 : val hss = 0.2283
Fold 3: train tss = 0.8240 : val tss = 0.1118 ::: train hss = 0.2765 : val hss = 0.0204
Fold 4: train tss = 0.7826 : val tss = 0.6906 ::: train hss = 0.2027 : val hss = 0.3148
mean cv TSS: 0.3601
mean cv HSS: 0.1389
775/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.6775 : val tss = 0.0522 ::: train hss = 0.1226 : val hss = 0.0246
Fold 1: train tss = 0.7770 : val tss = 0.4152 ::: train hss = 0.2940 : val hss = 0.1355
Fold 2: train tss = 0.7034 : val tss = 0.6111 ::: train hss = 0.1307 : val hss = 0.1932
Fold 3: train tss = 0.7405 : val tss = 0.2173 ::: train hss = 0.1966 : val hss = 0.0363
Fold 4: train tss = 0.7051 : val tss = 0.6551 ::: train hss = 0.1658 : val hss = 0.2234
mean cv TSS: 0.3902
mean cv HSS: 0.1226
776/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.6093 : val tss = -0.0028 ::: train hss = 0.0657 : val hss = -0.0012
Fold 1: train tss = 0.8798 : val tss = 0.3660 ::: train hss = 0.2853 : val hss = 0.1326
Fold 2: train tss = 0.8086 : val tss = 0.6608 ::: train hss = 0.1948 : val hss = 0.2495
Fold 3: train tss = 0.8385 : val tss = 0.0953 ::: train hss = 0.3224 : val hss = 0.0148
Fold 4: train tss = 0.8398 : val tss = 0.5898 ::: train hss = 0.2770 : val hss = 0.2931
mean cv TSS: 0.3418
mean cv HSS: 0.1378
777/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.4484 : val tss = 0.3429 ::: train hss = 0.0391 : val hss = 0.1616
Fold 1: train tss = 0.8245 : val tss = 0.4229 ::: train hss = 0.2286 : val hss = 0.1428
Fold 2: train tss = 0.7412 : val tss = 0.6637 ::: train hss = 0.1857 : val hss = 0.2378
Fold 3: train tss = 0.7837 : val tss = 0.1595 ::: train hss = 0.2500 : val hss = 0.0262
Fold 4: train tss = 0.7540 : val tss = 0.6612 ::: train hss = 0.2038 : val hss = 0.2609
mean cv TSS: 0.4500
mean cv HSS: 0.1659
778/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8509 : val tss = 0.2242 ::: train hss = 0.0763 : val hss = 0.0662
Fold 1: train tss = 0.8500 : val tss = 0.2744 ::: train hss = 0.3203 : val hss = 0.0938
Fold 2: train tss = 0.7621 : val tss = 0.6849 ::: train hss = 0.1743 : val hss = 0.2516
Fold 3: train tss = 0.8124 : val tss = 0.1224 ::: train hss = 0.2491 : val hss = 0.0359
Fold 4: train tss = 0.7917 : val tss = 0.7163 ::: train hss = 0.2216 : val hss = 0.3232
mean cv TSS: 0.4044
mean cv HSS: 0.1541
779/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.2646 : val tss = 0.3626 ::: train hss = 0.0331 : val hss = 0.1697
Fold 1: train tss = 0.7970 : val tss = 0.3811 ::: train hss = 0.2899 : val hss = 0.1517
Fold 2: train tss = 0.6981 : val tss = 0.6241 ::: train hss = 0.1360 : val hss = 0.2035
Fold 3: train tss = 0.7787 : val tss = 0.0605 ::: train hss = 0.2362 : val hss = 0.0113

Fold 4: train tss = 0.7364 : val tss = 0.6508 ::: train hss = 0.1873 : val hss = 0.2568
mean cv TSS: 0.4158
mean cv HSS: 0.1586
780/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8776 : val tss = -0.0209 ::: train hss = 0.1567 : val hss = -0.0157
Fold 1: train tss = 0.8918 : val tss = 0.3427 ::: train hss = 0.3380 : val hss = 0.1268
Fold 2: train tss = 0.7610 : val tss = 0.6936 ::: train hss = 0.1644 : val hss = 0.2645
Fold 3: train tss = 0.7671 : val tss = 0.0444 ::: train hss = 0.2102 : val hss = 0.0071
Fold 4: train tss = 0.7466 : val tss = 0.6695 ::: train hss = 0.1782 : val hss = 0.2362
mean cv TSS: 0.3458
mean cv HSS: 0.1238
781/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6781 : val tss = -0.0181 ::: train hss = 0.1256 : val hss = -0.0122
Fold 1: train tss = 0.7589 : val tss = 0.4439 ::: train hss = 0.2288 : val hss = 0.1683
Fold 2: train tss = 0.7084 : val tss = 0.5641 ::: train hss = 0.1595 : val hss = 0.1617
Fold 3: train tss = 0.7013 : val tss = 0.3232 ::: train hss = 0.1720 : val hss = 0.0414
Fold 4: train tss = 0.6843 : val tss = 0.5822 ::: train hss = 0.1463 : val hss = 0.1604
mean cv TSS: 0.3791
mean cv HSS: 0.1039
782/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.5335 : val tss = 0.1389 ::: train hss = 0.1270 : val hss = 0.0724
Fold 1: train tss = 0.8697 : val tss = 0.4697 ::: train hss = 0.2644 : val hss = 0.1707
Fold 2: train tss = 0.8018 : val tss = 0.7171 ::: train hss = 0.1964 : val hss = 0.2985
Fold 3: train tss = 0.7130 : val tss = 0.3870 ::: train hss = 0.1693 : val hss = 0.0475
Fold 4: train tss = 0.7841 : val tss = 0.6445 ::: train hss = 0.2030 : val hss = 0.2597
mean cv TSS: 0.4714
mean cv HSS: 0.1698
783/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.9165 : val tss = 0.3218 ::: train hss = 0.1157 : val hss = 0.1373
Fold 1: train tss = 0.8145 : val tss = 0.4255 ::: train hss = 0.2240 : val hss = 0.1208
Fold 2: train tss = 0.7362 : val tss = 0.5851 ::: train hss = 0.1645 : val hss = 0.1722
Fold 3: train tss = 0.7596 : val tss = 0.1491 ::: train hss = 0.2200 : val hss = 0.0257
Fold 4: train tss = 0.6754 : val tss = 0.6236 ::: train hss = 0.1288 : val hss = 0.2024
mean cv TSS: 0.4210
mean cv HSS: 0.1317
784/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.8221 : val tss = 0.2363 ::: train hss = 0.1222 : val hss = 0.1066
Fold 1: train tss = 0.8682 : val tss = 0.3685 ::: train hss = 0.2596 : val hss = 0.1268
Fold 2: train tss = 0.7257 : val tss = 0.5988 ::: train hss = 0.1343 : val hss = 0.1861
Fold 3: train tss = 0.7424 : val tss = 0.1304 ::: train hss = 0.1868 : val hss = 0.0191
Fold 4: train tss = 0.8054 : val tss = 0.6740 ::: train hss = 0.2476 : val hss = 0.3145
mean cv TSS: 0.4016
mean cv HSS: 0.1506
785/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.8168 : val tss = 0.1205 ::: train hss = 0.1044 : val hss = 0.0679
Fold 1: train tss = 0.7754 : val tss = 0.4319 ::: train hss = 0.2873 : val hss = 0.1624
Fold 2: train tss = 0.7238 : val tss = 0.6704 ::: train hss = 0.1477 : val hss = 0.2420
Fold 3: train tss = 0.7312 : val tss = 0.2934 ::: train hss = 0.1956 : val hss = 0.0357
Fold 4: train tss = 0.6824 : val tss = 0.5546 ::: train hss = 0.1640 : val hss = 0.1425
mean cv TSS: 0.4142
mean cv HSS: 0.1301
786/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.7863 : val tss = 0.2567 ::: train hss = 0.2097 : val hss = 0.1277
Fold 1: train tss = 0.8543 : val tss = 0.3787 ::: train hss = 0.3206 : val hss = 0.1040
Fold 2: train tss = 0.8050 : val tss = 0.6833 ::: train hss = 0.1963 : val hss = 0.2680
Fold 3: train tss = 0.7909 : val tss = 0.0253 ::: train hss = 0.2430 : val hss = 0.0048
Fold 4: train tss = 0.7735 : val tss = 0.6283 ::: train hss = 0.2041 : val hss = 0.2227
mean cv TSS: 0.3945
mean cv HSS: 0.1454
787/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.6747 : val tss = 0.2651 ::: train hss = 0.1106 : val hss = 0.1035
Fold 1: train tss = 0.7556 : val tss = 0.3976 ::: train hss = 0.2583 : val hss = 0.1157
Fold 2: train tss = 0.6126 : val tss = 0.5065 ::: train hss = 0.0831 : val hss = 0.1272
Fold 3: train tss = 0.7146 : val tss = 0.3241 ::: train hss = 0.1851 : val hss = 0.0436
Fold 4: train tss = 0.6685 : val tss = 0.6412 ::: train hss = 0.1389 : val hss = 0.2041
mean cv TSS: 0.4269
mean cv HSS: 0.1188
788/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9714 : val tss = -0.0064 ::: train hss = 0.1398 : val hss = -0.0036
Fold 1: train tss = 0.8791 : val tss = 0.3508 ::: train hss = 0.3625 : val hss = 0.1605
Fold 2: train tss = 0.7815 : val tss = 0.6498 ::: train hss = 0.1587 : val hss = 0.2350
Fold 3: train tss = 0.8277 : val tss = 0.0463 ::: train hss = 0.2719 : val hss = 0.0102
Fold 4: train tss = 0.7300 : val tss = 0.6572 ::: train hss = 0.1471 : val hss = 0.2566
mean cv TSS: 0.3395
mean cv HSS: 0.1317
789/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.8712 : val tss = 0.3069 ::: train hss = 0.0502 : val hss = 0.1259
Fold 1: train tss = 0.7839 : val tss = 0.3521 ::: train hss = 0.2555 : val hss = 0.0816
Fold 2: train tss = 0.7570 : val tss = 0.6201 ::: train hss = 0.1988 : val hss = 0.1961
Fold 3: train tss = 0.7554 : val tss = 0.1310 ::: train hss = 0.2191 : val hss = 0.0192
Fold 4: train tss = 0.7163 : val tss = 0.6143 ::: train hss = 0.1742 : val hss = 0.1970
mean cv TSS: 0.4049
mean cv HSS: 0.1240
790/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}

Total number of parameters: 4367
Fold 0: train tss = 0.9274 : val tss = 0.2828 ::: train hss = 0.1634 : val hss = 0.1226
Fold 1: train tss = 0.8869 : val tss = 0.3411 ::: train hss = 0.2665 : val hss = 0.1121
Fold 2: train tss = 0.7488 : val tss = 0.6299 ::: train hss = 0.1484 : val hss = 0.1926
Fold 3: train tss = 0.8206 : val tss = 0.0930 ::: train hss = 0.2621 : val hss = 0.0207
Fold 4: train tss = 0.8164 : val tss = 0.7005 ::: train hss = 0.2533 : val hss = 0.3372
mean cv TSS: 0.4095
mean cv HSS: 0.1570
791/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.1, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.8004 : val tss = -0.0320 ::: train hss = 0.0713 : val hss = -0.0205
Fold 1: train tss = 0.8529 : val tss = 0.3365 ::: train hss = 0.2279 : val hss = 0.1271
Fold 2: train tss = 0.7421 : val tss = 0.6206 ::: train hss = 0.1768 : val hss = 0.2047
Fold 3: train tss = 0.7553 : val tss = 0.2090 ::: train hss = 0.1980 : val hss = 0.0233
Fold 4: train tss = 0.7055 : val tss = 0.6335 ::: train hss = 0.1646 : val hss = 0.2246
mean cv TSS: 0.3535
mean cv HSS: 0.1118
792/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.4833 : val tss = 0.1126 ::: train hss = 0.1144 : val hss = 0.0740
Fold 1: train tss = 0.7584 : val tss = 0.3627 ::: train hss = 0.1887 : val hss = 0.1294
Fold 2: train tss = 0.6838 : val tss = 0.5909 ::: train hss = 0.1189 : val hss = 0.1795
Fold 3: train tss = 0.6889 : val tss = 0.0702 ::: train hss = 0.1490 : val hss = 0.0087
Fold 4: train tss = 0.6667 : val tss = 0.6118 ::: train hss = 0.1328 : val hss = 0.2329
mean cv TSS: 0.3497
mean cv HSS: 0.1249
793/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.6270 : val tss = 0.1672 ::: train hss = 0.1120 : val hss = 0.0851
Fold 1: train tss = 0.7553 : val tss = 0.4300 ::: train hss = 0.2730 : val hss = 0.1601
Fold 2: train tss = 0.6728 : val tss = 0.6435 ::: train hss = 0.1138 : val hss = 0.2177
Fold 3: train tss = 0.6763 : val tss = 0.1456 ::: train hss = 0.1543 : val hss = 0.0220
Fold 4: train tss = 0.6758 : val tss = 0.6382 ::: train hss = 0.1416 : val hss = 0.2206
mean cv TSS: 0.4049
mean cv HSS: 0.1411
794/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6374 : val tss = 0.2432 ::: train hss = 0.0832 : val hss = 0.0656
Fold 2: train tss = 0.6799 : val tss = 0.5571 ::: train hss = 0.1096 : val hss = 0.1603
Fold 3: train tss = 0.6865 : val tss = 0.2256 ::: train hss = 0.1458 : val hss = 0.0198
Fold 4: train tss = 0.6484 : val tss = 0.5756 ::: train hss = 0.1192 : val hss = 0.1545
mean cv TSS: 0.3203
mean cv HSS: 0.0800
795/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0711 : val tss = -0.0220 ::: train hss = 0.0109 : val hss = -0.0191
Fold 1: train tss = 0.7393 : val tss = 0.4670 ::: train hss = 0.4464 : val hss = 0.1928
Fold 2: train tss = 0.5886 : val tss = 0.6539 ::: train hss = 0.0730 : val hss = 0.2255
Fold 3: train tss = 0.6697 : val tss = 0.2921 ::: train hss = 0.1663 : val hss = 0.0274
Fold 4: train tss = 0.6349 : val tss = 0.5599 ::: train hss = 0.1272 : val hss = 0.1522
mean cv TSS: 0.3902
mean cv HSS: 0.1158
796/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.2626 : val tss = 0.1218 ::: train hss = 0.0066 : val hss = 0.0263
Fold 1: train tss = 0.6502 : val tss = 0.3349 ::: train hss = 0.1517 : val hss = 0.0683
Fold 2: train tss = 0.5795 : val tss = 0.4875 ::: train hss = 0.0664 : val hss = 0.1237
Fold 3: train tss = 0.6403 : val tss = 0.2594 ::: train hss = 0.1319 : val hss = 0.0284
Fold 4: train tss = 0.6364 : val tss = 0.6124 ::: train hss = 0.1103 : val hss = 0.1826
mean cv TSS: 0.3632
mean cv HSS: 0.0858
797/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = -0.1200 : val tss = 0.3746 ::: train hss = -0.0010 : val hss = 0.0315
Fold 1: train tss = 0.7433 : val tss = 0.4211 ::: train hss = 0.2936 : val hss = 0.1208
Fold 2: train tss = 0.6596 : val tss = 0.5646 ::: train hss = 0.1202 : val hss = 0.1616
Fold 3: train tss = 0.6799 : val tss = 0.2053 ::: train hss = 0.1839 : val hss = 0.0380
Fold 4: train tss = 0.6689 : val tss = 0.6332 ::: train hss = 0.1287 : val hss = 0.2098
mean cv TSS: 0.4397
mean cv HSS: 0.1123
798/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.7698 : val tss = 0.1082 ::: train hss = 0.1073 : val hss = 0.0444
Fold 1: train tss = 0.7314 : val tss = 0.4028 ::: train hss = 0.1911 : val hss = 0.0994
Fold 2: train tss = 0.7236 : val tss = 0.6353 ::: train hss = 0.1304 : val hss = 0.2112
Fold 3: train tss = 0.6827 : val tss = 0.5057 ::: train hss = 0.1521 : val hss = 0.0677
Fold 4: train tss = 0.6945 : val tss = 0.6756 ::: train hss = 0.1683 : val hss = 0.3529
mean cv TSS: 0.4655
mean cv HSS: 0.1551
799/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.3878 : val tss = 0.0572 ::: train hss = 0.1203 : val hss = 0.0314
Fold 1: train tss = 0.7462 : val tss = 0.4240 ::: train hss = 0.2164 : val hss = 0.1614
Fold 2: train tss = 0.6937 : val tss = 0.6502 ::: train hss = 0.1247 : val hss = 0.2306
Fold 3: train tss = 0.6863 : val tss = 0.1709 ::: train hss = 0.1529 : val hss = 0.0256
Fold 4: train tss = 0.6748 : val tss = 0.6390 ::: train hss = 0.1354 : val hss = 0.2242
mean cv TSS: 0.3883
mean cv HSS: 0.1346
800/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0964 : val tss = 0.0000 ::: train hss = 0.0741 : val hss = 0.0000
Fold 1: train tss = 0.7555 : val tss = 0.4107 ::: train hss = 0.1421 : val hss = 0.0923
Fold 2: train tss = 0.6231 : val tss = 0.5692 ::: train hss = 0.0935 : val hss = 0.1647
Fold 3: train tss = 0.6962 : val tss = 0.1583 ::: train hss = 0.1716 : val hss = 0.0356

Fold 4: train tss = 0.7283 : val tss = 0.6760 ::: train hss = 0.1848 : val hss = 0.2667
mean cv TSS: 0.3628
mean cv HSS: 0.1119
801/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0108 : val tss = 0.0000 ::: train hss = 0.0012 : val hss = 0.0000
Fold 1: train tss = 0.6728 : val tss = 0.4787 ::: train hss = 0.2052 : val hss = 0.1170
Fold 2: train tss = 0.5510 : val tss = 0.5686 ::: train hss = 0.0598 : val hss = 0.1644
Fold 3: train tss = 0.6974 : val tss = 0.2425 ::: train hss = 0.1992 : val hss = 0.0277
Fold 4: train tss = 0.6583 : val tss = 0.6369 ::: train hss = 0.1284 : val hss = 0.2244
mean cv TSS: 0.3854
mean cv HSS: 0.1067
802/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.0473 : val tss = 0.0078 ::: train hss = 0.0041 : val hss = 0.0081
Fold 1: train tss = 0.7567 : val tss = 0.3073 ::: train hss = 0.2347 : val hss = 0.0744
Fold 2: train tss = 0.7128 : val tss = 0.6960 ::: train hss = 0.2055 : val hss = 0.3279
Fold 3: train tss = 0.7141 : val tss = 0.2197 ::: train hss = 0.1906 : val hss = 0.0451
Fold 4: train tss = 0.6175 : val tss = 0.6682 ::: train hss = 0.1034 : val hss = 0.2548
mean cv TSS: 0.3798
mean cv HSS: 0.1421
803/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7343 : val tss = 0.3698 ::: train hss = 0.4392 : val hss = 0.1961
Fold 2: train tss = 0.5404 : val tss = 0.6535 ::: train hss = 0.0588 : val hss = 0.2262
Fold 3: train tss = 0.6951 : val tss = 0.2635 ::: train hss = 0.1675 : val hss = 0.0397
Fold 4: train tss = 0.6157 : val tss = 0.5985 ::: train hss = 0.1024 : val hss = 0.1735
mean cv TSS: 0.3771
mean cv HSS: 0.1271
804/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.5354 : val tss = 0.2017 ::: train hss = 0.1409 : val hss = 0.1015
Fold 1: train tss = 0.7534 : val tss = 0.3772 ::: train hss = 0.1354 : val hss = 0.1525
Fold 2: train tss = 0.6755 : val tss = 0.6108 ::: train hss = 0.1394 : val hss = 0.1966
Fold 3: train tss = 0.6846 : val tss = 0.3342 ::: train hss = 0.1441 : val hss = 0.0452
Fold 4: train tss = 0.6740 : val tss = 0.6477 ::: train hss = 0.1368 : val hss = 0.2432
mean cv TSS: 0.4343
mean cv HSS: 0.1478
805/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.4848 : val tss = 0.1159 ::: train hss = 0.1243 : val hss = 0.0657
Fold 1: train tss = 0.7225 : val tss = 0.3421 ::: train hss = 0.1981 : val hss = 0.1163
Fold 2: train tss = 0.6762 : val tss = 0.6200 ::: train hss = 0.1325 : val hss = 0.1982
Fold 3: train tss = 0.6669 : val tss = 0.1674 ::: train hss = 0.1423 : val hss = 0.0224
Fold 4: train tss = 0.6573 : val tss = 0.6572 ::: train hss = 0.1264 : val hss = 0.2177
mean cv TSS: 0.3805
mean cv HSS: 0.1241
806/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.3350 : val tss = 0.0282 ::: train hss = 0.0881 : val hss = 0.0192
Fold 1: train tss = 0.7812 : val tss = 0.2986 ::: train hss = 0.2029 : val hss = 0.1188
Fold 2: train tss = 0.6336 : val tss = 0.5180 ::: train hss = 0.0892 : val hss = 0.1386
Fold 3: train tss = 0.7021 : val tss = 0.3183 ::: train hss = 0.1738 : val hss = 0.0691
Fold 4: train tss = 0.7077 : val tss = 0.6234 ::: train hss = 0.1608 : val hss = 0.2128
mean cv TSS: 0.3573
mean cv HSS: 0.1117
807/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.0451 : val tss = 0.2205 ::: train hss = 0.0291 : val hss = 0.2227
Fold 1: train tss = 0.7255 : val tss = 0.4050 ::: train hss = 0.1261 : val hss = 0.1107
Fold 2: train tss = 0.6800 : val tss = 0.6546 ::: train hss = 0.1193 : val hss = 0.2279
Fold 3: train tss = 0.6904 : val tss = 0.2450 ::: train hss = 0.1554 : val hss = 0.0294
Fold 4: train tss = 0.6557 : val tss = 0.5775 ::: train hss = 0.1214 : val hss = 0.1824
mean cv TSS: 0.4205
mean cv HSS: 0.1546
808/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 189
Fold 0: train tss = 0.3810 : val tss = 0.0343 ::: train hss = 0.0819 : val hss = 0.0253
Fold 1: train tss = 0.7668 : val tss = 0.4064 ::: train hss = 0.1750 : val hss = 0.1629
Fold 2: train tss = 0.6117 : val tss = 0.4776 ::: train hss = 0.0844 : val hss = 0.1166
Fold 3: train tss = 0.6660 : val tss = 0.4272 ::: train hss = 0.1350 : val hss = 0.0426
Fold 4: train tss = 0.6795 : val tss = 0.6524 ::: train hss = 0.1382 : val hss = 0.2508
mean cv TSS: 0.3996
mean cv HSS: 0.1196
809/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 189
Fold 0: train tss = 0.5133 : val tss = 0.2308 ::: train hss = 0.0611 : val hss = 0.1781
Fold 1: train tss = 0.7635 : val tss = 0.3235 ::: train hss = 0.1761 : val hss = 0.1423
Fold 2: train tss = 0.6886 : val tss = 0.6774 ::: train hss = 0.1274 : val hss = 0.2496
Fold 3: train tss = 0.5646 : val tss = 0.2217 ::: train hss = 0.0886 : val hss = 0.0152
Fold 4: train tss = 0.6437 : val tss = 0.5867 ::: train hss = 0.1159 : val hss = 0.1808
mean cv TSS: 0.4080
mean cv HSS: 0.1532
810/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.8862 : val tss = 0.2864 ::: train hss = 0.0623 : val hss = 0.1282
Fold 1: train tss = 0.7640 : val tss = 0.3665 ::: train hss = 0.1841 : val hss = 0.1126
Fold 2: train tss = 0.6901 : val tss = 0.6460 ::: train hss = 0.1156 : val hss = 0.2365
Fold 3: train tss = 0.7233 : val tss = 0.2976 ::: train hss = 0.1785 : val hss = 0.0443
Fold 4: train tss = 0.7252 : val tss = 0.6446 ::: train hss = 0.1673 : val hss = 0.2401
mean cv TSS: 0.4482
mean cv HSS: 0.1523
811/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}

Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7562 : val tss = 0.3332 ::: train hss = 0.2107 : val hss = 0.1351
Fold 2: train tss = 0.6593 : val tss = 0.5406 ::: train hss = 0.1006 : val hss = 0.1467
Fold 3: train tss = 0.6471 : val tss = 0.4455 ::: train hss = 0.1236 : val hss = 0.0429
Fold 4: train tss = 0.6628 : val tss = 0.6148 ::: train hss = 0.1290 : val hss = 0.1941
mean cv TSS: 0.3868
mean cv HSS: 0.1038
812/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.4289 : val tss = 0.2896 ::: train hss = 0.0841 : val hss = 0.1219
Fold 1: train tss = 0.7371 : val tss = 0.4935 ::: train hss = 0.2252 : val hss = 0.0979
Fold 2: train tss = 0.7359 : val tss = 0.6741 ::: train hss = 0.1518 : val hss = 0.2753
Fold 3: train tss = 0.7009 : val tss = 0.0847 ::: train hss = 0.1659 : val hss = 0.0108
Fold 4: train tss = 0.7166 : val tss = 0.6494 ::: train hss = 0.1564 : val hss = 0.2158
mean cv TSS: 0.4382
mean cv HSS: 0.1444
813/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7486 : val tss = 0.3696 ::: train hss = 0.2482 : val hss = 0.1783
Fold 2: train tss = 0.6739 : val tss = 0.6203 ::: train hss = 0.1262 : val hss = 0.1999
Fold 3: train tss = 0.6769 : val tss = 0.2498 ::: train hss = 0.1539 : val hss = 0.0334
Fold 4: train tss = 0.6826 : val tss = 0.6005 ::: train hss = 0.1399 : val hss = 0.1899
mean cv TSS: 0.3680
mean cv HSS: 0.1203
814/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 237
Fold 0: train tss = 0.8027 : val tss = -0.0195 ::: train hss = 0.0747 : val hss = -0.0102
Fold 1: train tss = 0.7438 : val tss = 0.4137 ::: train hss = 0.2607 : val hss = 0.1548
Fold 2: train tss = 0.7304 : val tss = 0.6078 ::: train hss = 0.1740 : val hss = 0.2004
Fold 3: train tss = 0.7447 : val tss = 0.1703 ::: train hss = 0.2181 : val hss = 0.0365
Fold 4: train tss = 0.7387 : val tss = 0.6585 ::: train hss = 0.1865 : val hss = 0.2815
mean cv TSS: 0.3662
mean cv HSS: 0.1326
815/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 2, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 237
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6486 : val tss = 0.3799 ::: train hss = 0.0836 : val hss = 0.0577
Fold 2: train tss = 0.6852 : val tss = 0.6392 ::: train hss = 0.1260 : val hss = 0.2178
Fold 3: train tss = 0.7131 : val tss = 0.1624 ::: train hss = 0.1877 : val hss = 0.0306
Fold 4: train tss = 0.6907 : val tss = 0.6254 ::: train hss = 0.1415 : val hss = 0.2204
mean cv TSS: 0.3614
mean cv HSS: 0.1053
816/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.7720 : val tss = -0.0555 ::: train hss = 0.1148 : val hss = -0.0304
Fold 1: train tss = 0.8449 : val tss = 0.3423 ::: train hss = 0.2395 : val hss = 0.1051
Fold 2: train tss = 0.7173 : val tss = 0.5422 ::: train hss = 0.1259 : val hss = 0.1495
Fold 3: train tss = 0.6881 : val tss = 0.4015 ::: train hss = 0.1480 : val hss = 0.0485
Fold 4: train tss = 0.7140 : val tss = 0.6526 ::: train hss = 0.1547 : val hss = 0.2233
mean cv TSS: 0.3766
mean cv HSS: 0.0992
817/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5341 : val tss = 0.2959 ::: train hss = 0.1311 : val hss = 0.1449
Fold 1: train tss = 0.7791 : val tss = 0.4156 ::: train hss = 0.2073 : val hss = 0.1167
Fold 2: train tss = 0.7027 : val tss = 0.6128 ::: train hss = 0.1551 : val hss = 0.1951
Fold 3: train tss = 0.6962 : val tss = 0.1495 ::: train hss = 0.1677 : val hss = 0.0231
Fold 4: train tss = 0.7047 : val tss = 0.6326 ::: train hss = 0.1648 : val hss = 0.2113
mean cv TSS: 0.4213
mean cv HSS: 0.1382
818/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.1880 : val tss = 0.0905 ::: train hss = 0.0606 : val hss = 0.1082
Fold 1: train tss = 0.7623 : val tss = 0.3492 ::: train hss = 0.2391 : val hss = 0.0837
Fold 2: train tss = 0.7197 : val tss = 0.5938 ::: train hss = 0.1331 : val hss = 0.1807
Fold 3: train tss = 0.7403 : val tss = 0.1289 ::: train hss = 0.1993 : val hss = 0.0157
Fold 4: train tss = 0.7389 : val tss = 0.6644 ::: train hss = 0.1792 : val hss = 0.2567
mean cv TSS: 0.3653
mean cv HSS: 0.1290
819/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.3287 : val tss = 0.3576 ::: train hss = 0.0645 : val hss = 0.1855
Fold 1: train tss = 0.7611 : val tss = 0.4420 ::: train hss = 0.2031 : val hss = 0.1482
Fold 2: train tss = 0.7364 : val tss = 0.6731 ::: train hss = 0.1664 : val hss = 0.2434
Fold 3: train tss = 0.7299 : val tss = 0.2793 ::: train hss = 0.1955 : val hss = 0.0361
Fold 4: train tss = 0.7196 : val tss = 0.6378 ::: train hss = 0.1792 : val hss = 0.2293
mean cv TSS: 0.4780
mean cv HSS: 0.1685
820/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.4830 : val tss = -0.0148 ::: train hss = 0.1130 : val hss = -0.0086
Fold 1: train tss = 0.8084 : val tss = 0.3125 ::: train hss = 0.2543 : val hss = 0.1342
Fold 2: train tss = 0.7303 : val tss = 0.6650 ::: train hss = 0.1509 : val hss = 0.2538
Fold 3: train tss = 0.7341 : val tss = 0.1907 ::: train hss = 0.1878 : val hss = 0.0168
Fold 4: train tss = 0.7093 : val tss = 0.5989 ::: train hss = 0.1446 : val hss = 0.1820
mean cv TSS: 0.3504
mean cv HSS: 0.1156
821/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5272 : val tss = 0.3788 ::: train hss = 0.0959 : val hss = 0.1983
Fold 1: train tss = 0.7643 : val tss = 0.3450 ::: train hss = 0.2214 : val hss = 0.0950
Fold 2: train tss = 0.6920 : val tss = 0.6205 ::: train hss = 0.1257 : val hss = 0.2001
Fold 3: train tss = 0.6841 : val tss = 0.2090 ::: train hss = 0.1569 : val hss = 0.0202

Fold 4: train tss = 0.6982 : val tss = 0.6175 ::: train hss = 0.1493 : val hss = 0.1905
mean cv TSS: 0.4342
mean cv HSS: 0.1408
822/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.6734 : val tss = 0.1915 ::: train hss = 0.1056 : val hss = 0.0833
Fold 1: train tss = 0.8708 : val tss = 0.3058 ::: train hss = 0.3394 : val hss = 0.1368
Fold 2: train tss = 0.7561 : val tss = 0.6248 ::: train hss = 0.1709 : val hss = 0.1938
Fold 3: train tss = 0.7906 : val tss = 0.1040 ::: train hss = 0.2978 : val hss = 0.0219
Fold 4: train tss = 0.7399 : val tss = 0.6281 ::: train hss = 0.1796 : val hss = 0.2158
mean cv TSS: 0.3708
mean cv HSS: 0.1303
823/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7861 : val tss = 0.3596 ::: train hss = 0.3410 : val hss = 0.1351
Fold 2: train tss = 0.7416 : val tss = 0.6206 ::: train hss = 0.1705 : val hss = 0.2023
Fold 3: train tss = 0.7225 : val tss = 0.3563 ::: train hss = 0.1875 : val hss = 0.0491
Fold 4: train tss = 0.6990 : val tss = 0.6545 ::: train hss = 0.1538 : val hss = 0.2320
mean cv TSS: 0.3982
mean cv HSS: 0.1237
824/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7750 : val tss = 0.2979 ::: train hss = 0.4573 : val hss = 0.1325
Fold 2: train tss = 0.7482 : val tss = 0.6594 ::: train hss = 0.1803 : val hss = 0.2378
Fold 3: train tss = 0.7820 : val tss = 0.1127 ::: train hss = 0.2234 : val hss = 0.0299
Fold 4: train tss = 0.7656 : val tss = 0.6457 ::: train hss = 0.2108 : val hss = 0.2459
mean cv TSS: 0.3431
mean cv HSS: 0.1292
825/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7669 : val tss = 0.4037 ::: train hss = 0.3843 : val hss = 0.1944
Fold 2: train tss = 0.7404 : val tss = 0.6778 ::: train hss = 0.1825 : val hss = 0.2489
Fold 3: train tss = 0.7601 : val tss = 0.2175 ::: train hss = 0.2580 : val hss = 0.0386
Fold 4: train tss = 0.6919 : val tss = 0.6195 ::: train hss = 0.1430 : val hss = 0.1984
mean cv TSS: 0.3837
mean cv HSS: 0.1361
826/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8165 : val tss = 0.4723 ::: train hss = 0.3450 : val hss = 0.1030
Fold 2: train tss = 0.7858 : val tss = 0.7067 ::: train hss = 0.2707 : val hss = 0.3063
Fold 3: train tss = 0.8180 : val tss = 0.2884 ::: train hss = 0.3021 : val hss = 0.0614
Fold 4: train tss = 0.7865 : val tss = 0.6667 ::: train hss = 0.2608 : val hss = 0.2763
mean cv TSS: 0.4268
mean cv HSS: 0.1494
827/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7690 : val tss = 0.4224 ::: train hss = 0.4409 : val hss = 0.1850
Fold 2: train tss = 0.7347 : val tss = 0.6613 ::: train hss = 0.1646 : val hss = 0.2358
Fold 3: train tss = 0.7707 : val tss = 0.2210 ::: train hss = 0.2709 : val hss = 0.0533
Fold 4: train tss = 0.7588 : val tss = 0.6372 ::: train hss = 0.2105 : val hss = 0.2525
mean cv TSS: 0.3884
mean cv HSS: 0.1453
828/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.8050 : val tss = -0.0050 ::: train hss = 0.0783 : val hss = -0.0045
Fold 1: train tss = 0.8066 : val tss = 0.2928 ::: train hss = 0.1686 : val hss = 0.0723
Fold 2: train tss = 0.7400 : val tss = 0.6313 ::: train hss = 0.1687 : val hss = 0.2180
Fold 3: train tss = 0.7167 : val tss = 0.2790 ::: train hss = 0.1723 : val hss = 0.0395
Fold 4: train tss = 0.7052 : val tss = 0.5937 ::: train hss = 0.1540 : val hss = 0.1912
mean cv TSS: 0.3584
mean cv HSS: 0.1033
829/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4858 : val tss = 0.3332 ::: train hss = 0.1313 : val hss = 0.1658
Fold 1: train tss = 0.7617 : val tss = 0.3444 ::: train hss = 0.2505 : val hss = 0.1131
Fold 2: train tss = 0.7031 : val tss = 0.6191 ::: train hss = 0.1587 : val hss = 0.1983
Fold 3: train tss = 0.6954 : val tss = 0.3520 ::: train hss = 0.1698 : val hss = 0.0373
Fold 4: train tss = 0.6959 : val tss = 0.6305 ::: train hss = 0.1556 : val hss = 0.1962
mean cv TSS: 0.4558
mean cv HSS: 0.1421
830/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5781 : val tss = 0.3261 ::: train hss = 0.1081 : val hss = 0.1272
Fold 1: train tss = 0.8336 : val tss = 0.4079 ::: train hss = 0.1868 : val hss = 0.0938
Fold 2: train tss = 0.6854 : val tss = 0.5620 ::: train hss = 0.1120 : val hss = 0.1660
Fold 3: train tss = 0.7690 : val tss = 0.0777 ::: train hss = 0.2272 : val hss = 0.0092
Fold 4: train tss = 0.6264 : val tss = 0.5778 ::: train hss = 0.1041 : val hss = 0.1601
mean cv TSS: 0.3903
mean cv HSS: 0.1112
831/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.4798 : val tss = 0.3347 ::: train hss = 0.0969 : val hss = 0.1462
Fold 1: train tss = 0.8022 : val tss = 0.4272 ::: train hss = 0.2476 : val hss = 0.1425
Fold 2: train tss = 0.7383 : val tss = 0.6719 ::: train hss = 0.1668 : val hss = 0.2424
Fold 3: train tss = 0.7432 : val tss = 0.3760 ::: train hss = 0.1927 : val hss = 0.0548
Fold 4: train tss = 0.6843 : val tss = 0.5954 ::: train hss = 0.1335 : val hss = 0.1713
mean cv TSS: 0.4811
mean cv HSS: 0.1514
832/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 379
Fold 0: train tss = 0.5679 : val tss = 0.3212 ::: train hss = 0.0760 : val hss = 0.0979

Fold 1: train tss = 0.7806 : val tss = 0.4603 ::: train hss = 0.1653 : val hss = 0.2018
Fold 2: train tss = 0.7502 : val tss = 0.6234 ::: train hss = 0.1614 : val hss = 0.1971
Fold 3: train tss = 0.6983 : val tss = 0.0878 ::: train hss = 0.1525 : val hss = 0.0097
Fold 4: train tss = 0.6914 : val tss = 0.5941 ::: train hss = 0.1400 : val hss = 0.1946
mean cv TSS: 0.4174
mean cv HSS: 0.1402
833/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 379
Fold 0: train tss = 0.5221 : val tss = 0.3115 ::: train hss = 0.0794 : val hss = 0.1390
Fold 1: train tss = 0.8043 : val tss = 0.3504 ::: train hss = 0.1777 : val hss = 0.0844
Fold 2: train tss = 0.6914 : val tss = 0.5728 ::: train hss = 0.1329 : val hss = 0.1664
Fold 3: train tss = 0.7294 : val tss = 0.1745 ::: train hss = 0.1917 : val hss = 0.0242
Fold 4: train tss = 0.7019 : val tss = 0.5980 ::: train hss = 0.1481 : val hss = 0.1896
mean cv TSS: 0.4014
mean cv HSS: 0.1207
834/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.7809 : val tss = 0.0730 ::: train hss = 0.1602 : val hss = 0.0329
Fold 1: train tss = 0.8462 : val tss = 0.2874 ::: train hss = 0.2851 : val hss = 0.1138
Fold 2: train tss = 0.7557 : val tss = 0.6135 ::: train hss = 0.1742 : val hss = 0.2031
Fold 3: train tss = 0.7559 : val tss = 0.1120 ::: train hss = 0.1985 : val hss = 0.0204
Fold 4: train tss = 0.7670 : val tss = 0.6363 ::: train hss = 0.2010 : val hss = 0.2332
mean cv TSS: 0.3445
mean cv HSS: 0.1207
835/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7586 : val tss = 0.3688 ::: train hss = 0.2540 : val hss = 0.1112
Fold 2: train tss = 0.7189 : val tss = 0.5983 ::: train hss = 0.1459 : val hss = 0.1844
Fold 3: train tss = 0.7270 : val tss = 0.3199 ::: train hss = 0.1919 : val hss = 0.0372
Fold 4: train tss = 0.7111 : val tss = 0.6330 ::: train hss = 0.1700 : val hss = 0.1981
mean cv TSS: 0.3840
mean cv HSS: 0.1062
836/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8925 : val tss = 0.2553 ::: train hss = 0.0691 : val hss = 0.0832
Fold 1: train tss = 0.7556 : val tss = 0.3962 ::: train hss = 0.3646 : val hss = 0.1408
Fold 2: train tss = 0.7101 : val tss = 0.6162 ::: train hss = 0.1183 : val hss = 0.1940
Fold 3: train tss = 0.8076 : val tss = 0.0390 ::: train hss = 0.2853 : val hss = 0.0071
Fold 4: train tss = 0.7540 : val tss = 0.6415 ::: train hss = 0.1847 : val hss = 0.2264
mean cv TSS: 0.3896
mean cv HSS: 0.1303
837/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.4510 : val tss = 0.1357 ::: train hss = 0.0413 : val hss = 0.0764
Fold 1: train tss = 0.7701 : val tss = 0.3808 ::: train hss = 0.2510 : val hss = 0.1769
Fold 2: train tss = 0.7402 : val tss = 0.6906 ::: train hss = 0.1930 : val hss = 0.2615
Fold 3: train tss = 0.7259 : val tss = 0.1691 ::: train hss = 0.1757 : val hss = 0.0251
Fold 4: train tss = 0.7401 : val tss = 0.6527 ::: train hss = 0.1925 : val hss = 0.2273
mean cv TSS: 0.4058
mean cv HSS: 0.1534
838/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 539
Fold 0: train tss = 0.8165 : val tss = -0.0549 ::: train hss = 0.1037 : val hss = -0.0302
Fold 1: train tss = 0.8271 : val tss = 0.4223 ::: train hss = 0.3577 : val hss = 0.2149
Fold 2: train tss = 0.7422 : val tss = 0.6349 ::: train hss = 0.1788 : val hss = 0.2168
Fold 3: train tss = 0.8207 : val tss = 0.0878 ::: train hss = 0.2890 : val hss = 0.0164
Fold 4: train tss = 0.8121 : val tss = 0.7034 ::: train hss = 0.2572 : val hss = 0.3159
mean cv TSS: 0.3587
mean cv HSS: 0.1467
839/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 4, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 539
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8002 : val tss = 0.3879 ::: train hss = 0.2857 : val hss = 0.1768
Fold 2: train tss = 0.7418 : val tss = 0.6718 ::: train hss = 0.1955 : val hss = 0.2550
Fold 3: train tss = 0.7574 : val tss = 0.1775 ::: train hss = 0.2252 : val hss = 0.0262
Fold 4: train tss = 0.7214 : val tss = 0.6302 ::: train hss = 0.1861 : val hss = 0.2186
mean cv TSS: 0.3735
mean cv HSS: 0.1353
840/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.6751 : val tss = 0.0591 ::: train hss = 0.1120 : val hss = 0.0227
Fold 1: train tss = 0.8284 : val tss = 0.3655 ::: train hss = 0.2655 : val hss = 0.1300
Fold 2: train tss = 0.7701 : val tss = 0.6653 ::: train hss = 0.1596 : val hss = 0.2403
Fold 3: train tss = 0.7937 : val tss = 0.0369 ::: train hss = 0.2519 : val hss = 0.0059
Fold 4: train tss = 0.7839 : val tss = 0.6742 ::: train hss = 0.2189 : val hss = 0.2772
mean cv TSS: 0.3602
mean cv HSS: 0.1352
841/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.6747 : val tss = 0.0817 ::: train hss = 0.1106 : val hss = 0.0471
Fold 1: train tss = 0.7800 : val tss = 0.4217 ::: train hss = 0.3084 : val hss = 0.1586
Fold 2: train tss = 0.7044 : val tss = 0.6436 ::: train hss = 0.1361 : val hss = 0.2170
Fold 3: train tss = 0.7112 : val tss = 0.1456 ::: train hss = 0.1789 : val hss = 0.0220
Fold 4: train tss = 0.6887 : val tss = 0.6354 ::: train hss = 0.1532 : val hss = 0.2126
mean cv TSS: 0.3856
mean cv HSS: 0.1315
842/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9517 : val tss = 0.0843 ::: train hss = 0.0863 : val hss = 0.0336
Fold 1: train tss = 0.8267 : val tss = 0.4276 ::: train hss = 0.1889 : val hss = 0.1387
Fold 2: train tss = 0.7944 : val tss = 0.6977 ::: train hss = 0.2169 : val hss = 0.2787
Fold 3: train tss = 0.8058 : val tss = 0.1469 ::: train hss = 0.2627 : val hss = 0.0236
Fold 4: train tss = 0.7770 : val tss = 0.6796 ::: train hss = 0.2067 : val hss = 0.2851
mean cv TSS: 0.4072
mean cv HSS: 0.1519
843/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}

Total number of parameters: 2191
Fold 0: train tss = 0.6629 : val tss = 0.3259 ::: train hss = 0.0775 : val hss = 0.1268
Fold 1: train tss = 0.7918 : val tss = 0.3068 ::: train hss = 0.1438 : val hss = 0.0571
Fold 2: train tss = 0.7511 : val tss = 0.6830 ::: train hss = 0.1883 : val hss = 0.2550
Fold 3: train tss = 0.7398 : val tss = 0.2912 ::: train hss = 0.1973 : val hss = 0.0365
Fold 4: train tss = 0.7193 : val tss = 0.6421 ::: train hss = 0.1676 : val hss = 0.2434
mean cv TSS: 0.4498
mean cv HSS: 0.1438
844/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.7166 : val tss = 0.2578 ::: train hss = 0.0919 : val hss = 0.1030
Fold 1: train tss = 0.7650 : val tss = 0.3758 ::: train hss = 0.2125 : val hss = 0.1455
Fold 2: train tss = 0.8063 : val tss = 0.6639 ::: train hss = 0.2416 : val hss = 0.2865
Fold 3: train tss = 0.7613 : val tss = 0.1365 ::: train hss = 0.1985 : val hss = 0.0207
Fold 4: train tss = 0.7976 : val tss = 0.6789 ::: train hss = 0.2242 : val hss = 0.2836
mean cv TSS: 0.4226
mean cv HSS: 0.1678
845/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.7974 : val tss = 0.2953 ::: train hss = 0.0673 : val hss = 0.1514
Fold 1: train tss = 0.8072 : val tss = 0.3580 ::: train hss = 0.1981 : val hss = 0.1250
Fold 2: train tss = 0.7200 : val tss = 0.6309 ::: train hss = 0.1527 : val hss = 0.2072
Fold 3: train tss = 0.7392 : val tss = 0.2760 ::: train hss = 0.2017 : val hss = 0.0351
Fold 4: train tss = 0.7528 : val tss = 0.6410 ::: train hss = 0.2032 : val hss = 0.2526
mean cv TSS: 0.4402
mean cv HSS: 0.1543
846/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9399 : val tss = 0.1785 ::: train hss = 0.3057 : val hss = 0.1167
Fold 1: train tss = 0.8671 : val tss = 0.3684 ::: train hss = 0.3210 : val hss = 0.1422
Fold 2: train tss = 0.7543 : val tss = 0.6636 ::: train hss = 0.1426 : val hss = 0.2387
Fold 3: train tss = 0.7887 : val tss = 0.0938 ::: train hss = 0.2307 : val hss = 0.0272
Fold 4: train tss = 0.7344 : val tss = 0.6718 ::: train hss = 0.1628 : val hss = 0.2595
mean cv TSS: 0.3952
mean cv HSS: 0.1568
847/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.6785 : val tss = 0.0603 ::: train hss = 0.1274 : val hss = 0.0292
Fold 1: train tss = 0.7749 : val tss = 0.4285 ::: train hss = 0.2682 : val hss = 0.1484
Fold 2: train tss = 0.7061 : val tss = 0.6405 ::: train hss = 0.1709 : val hss = 0.2162
Fold 3: train tss = 0.7337 : val tss = 0.1519 ::: train hss = 0.1912 : val hss = 0.0216
Fold 4: train tss = 0.7056 : val tss = 0.6250 ::: train hss = 0.1694 : val hss = 0.2086
mean cv TSS: 0.3812
mean cv HSS: 0.1248
848/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9639 : val tss = 0.2819 ::: train hss = 0.1134 : val hss = 0.1070
Fold 1: train tss = 0.8567 : val tss = 0.4333 ::: train hss = 0.2935 : val hss = 0.1641
Fold 2: train tss = 0.8278 : val tss = 0.6417 ::: train hss = 0.2156 : val hss = 0.2620
Fold 3: train tss = 0.7884 : val tss = 0.0924 ::: train hss = 0.2101 : val hss = 0.0292
Fold 4: train tss = 0.8257 : val tss = 0.7083 ::: train hss = 0.2530 : val hss = 0.3479
mean cv TSS: 0.4315
mean cv HSS: 0.1821
849/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.0442 : val tss = 0.3883 ::: train hss = 0.0256 : val hss = 0.2967
Fold 1: train tss = 0.8188 : val tss = 0.3984 ::: train hss = 0.2611 : val hss = 0.1196
Fold 2: train tss = 0.7647 : val tss = 0.6445 ::: train hss = 0.2137 : val hss = 0.2144
Fold 3: train tss = 0.7798 : val tss = 0.1979 ::: train hss = 0.2476 : val hss = 0.0329
Fold 4: train tss = 0.7571 : val tss = 0.6390 ::: train hss = 0.1917 : val hss = 0.2242
mean cv TSS: 0.4536
mean cv HSS: 0.1776
850/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9495 : val tss = 0.2315 ::: train hss = 0.0827 : val hss = 0.0715
Fold 1: train tss = 0.8491 : val tss = 0.3464 ::: train hss = 0.2519 : val hss = 0.1305
Fold 2: train tss = 0.7999 : val tss = 0.7093 ::: train hss = 0.2490 : val hss = 0.3161
Fold 3: train tss = 0.8054 : val tss = 0.0470 ::: train hss = 0.2463 : val hss = 0.0076
Fold 4: train tss = 0.8203 : val tss = 0.6476 ::: train hss = 0.2630 : val hss = 0.2508
mean cv TSS: 0.3964
mean cv HSS: 0.1553
851/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.0065, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.2544 : val tss = 0.3520 ::: train hss = 0.0251 : val hss = 0.1497
Fold 1: train tss = 0.8356 : val tss = 0.3174 ::: train hss = 0.3119 : val hss = 0.1402
Fold 2: train tss = 0.7664 : val tss = 0.6438 ::: train hss = 0.2010 : val hss = 0.2172
Fold 3: train tss = 0.7498 : val tss = 0.2615 ::: train hss = 0.2035 : val hss = 0.0354
Fold 4: train tss = 0.7092 : val tss = 0.5515 ::: train hss = 0.1535 : val hss = 0.1582
mean cv TSS: 0.4252
mean cv HSS: 0.1402
852/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.7763 : val tss = -0.0511 ::: train hss = 0.1333 : val hss = -0.0312
Fold 1: train tss = 0.8432 : val tss = 0.3402 ::: train hss = 0.2593 : val hss = 0.1096
Fold 2: train tss = 0.7259 : val tss = 0.5351 ::: train hss = 0.1554 : val hss = 0.1416
Fold 3: train tss = 0.7820 : val tss = 0.0606 ::: train hss = 0.2293 : val hss = 0.0095
Fold 4: train tss = 0.7348 : val tss = 0.6919 ::: train hss = 0.1770 : val hss = 0.2896
mean cv TSS: 0.3153
mean cv HSS: 0.1038
853/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.5764 : val tss = 0.1900 ::: train hss = 0.1011 : val hss = 0.0749
Fold 1: train tss = 0.7704 : val tss = 0.4249 ::: train hss = 0.3027 : val hss = 0.1343
Fold 2: train tss = 0.6878 : val tss = 0.6072 ::: train hss = 0.1384 : val hss = 0.1898
Fold 3: train tss = 0.6911 : val tss = 0.3750 ::: train hss = 0.1723 : val hss = 0.0420

Fold 4: train tss = 0.6782 : val tss = 0.6310 ::: train hss = 0.1428 : val hss = 0.1913
mean cv TSS: 0.4456
mean cv HSS: 0.1265
854/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9202 : val tss = 0.0209 ::: train hss = 0.1282 : val hss = 0.0121
Fold 1: train tss = 0.8516 : val tss = 0.3425 ::: train hss = 0.2598 : val hss = 0.1287
Fold 2: train tss = 0.7562 : val tss = 0.6460 ::: train hss = 0.1296 : val hss = 0.2355
Fold 3: train tss = 0.8066 : val tss = 0.0989 ::: train hss = 0.2662 : val hss = 0.0166
Fold 4: train tss = 0.7857 : val tss = 0.6657 ::: train hss = 0.2078 : val hss = 0.2471
mean cv TSS: 0.3548
mean cv HSS: 0.1280
855/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.8264 : val tss = 0.2923 ::: train hss = 0.0509 : val hss = 0.1031
Fold 1: train tss = 0.8019 : val tss = 0.4181 ::: train hss = 0.2038 : val hss = 0.1216
Fold 2: train tss = 0.7211 : val tss = 0.6512 ::: train hss = 0.1552 : val hss = 0.2242
Fold 3: train tss = 0.7288 : val tss = 0.1654 ::: train hss = 0.1884 : val hss = 0.0341
Fold 4: train tss = 0.7184 : val tss = 0.6239 ::: train hss = 0.1705 : val hss = 0.2001
mean cv TSS: 0.4302
mean cv HSS: 0.1366
856/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 2191
Fold 0: train tss = 0.9446 : val tss = 0.2454 ::: train hss = 0.0756 : val hss = 0.0891
Fold 1: train tss = 0.8218 : val tss = 0.3181 ::: train hss = 0.3272 : val hss = 0.1155
Fold 2: train tss = 0.7283 : val tss = 0.6449 ::: train hss = 0.1477 : val hss = 0.2225
Fold 3: train tss = 0.7359 : val tss = 0.0735 ::: train hss = 0.1798 : val hss = 0.0067
Fold 4: train tss = 0.7687 : val tss = 0.6770 ::: train hss = 0.1914 : val hss = 0.2798
mean cv TSS: 0.3918
mean cv HSS: 0.1427
857/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 1, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 2191
Fold 0: train tss = 0.9061 : val tss = 0.2708 ::: train hss = 0.0897 : val hss = 0.0855
Fold 1: train tss = 0.7623 : val tss = 0.4230 ::: train hss = 0.2526 : val hss = 0.1222
Fold 2: train tss = 0.7018 : val tss = 0.5869 ::: train hss = 0.1403 : val hss = 0.1782
Fold 3: train tss = 0.6273 : val tss = 0.1170 ::: train hss = 0.1157 : val hss = 0.0106
Fold 4: train tss = 0.7048 : val tss = 0.6117 ::: train hss = 0.1520 : val hss = 0.1965
mean cv TSS: 0.4019
mean cv HSS: 0.1186
858/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8845 : val tss = 0.1486 ::: train hss = 0.2119 : val hss = 0.0981
Fold 1: train tss = 0.8523 : val tss = 0.4074 ::: train hss = 0.1916 : val hss = 0.1385
Fold 2: train tss = 0.7819 : val tss = 0.6759 ::: train hss = 0.1620 : val hss = 0.2420
Fold 3: train tss = 0.7478 : val tss = 0.3069 ::: train hss = 0.2050 : val hss = 0.0415
Fold 4: train tss = 0.6940 : val tss = 0.6453 ::: train hss = 0.1374 : val hss = 0.2341
mean cv TSS: 0.4368
mean cv HSS: 0.1509
859/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 10, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.7268 : val tss = 0.2846 ::: train hss = 0.1275 : val hss = 0.1314
Fold 1: train tss = 0.7519 : val tss = 0.3931 ::: train hss = 0.2763 : val hss = 0.1155
Fold 2: train tss = 0.7138 : val tss = 0.6188 ::: train hss = 0.1540 : val hss = 0.1987
Fold 3: train tss = 0.7183 : val tss = 0.3203 ::: train hss = 0.1893 : val hss = 0.0405
Fold 4: train tss = 0.6922 : val tss = 0.6332 ::: train hss = 0.1531 : val hss = 0.1959
mean cv TSS: 0.4500
mean cv HSS: 0.1364
860/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.8576 : val tss = -0.0140 ::: train hss = 0.0880 : val hss = -0.0053
Fold 1: train tss = 0.8388 : val tss = 0.3790 ::: train hss = 0.1229 : val hss = 0.0896
Fold 2: train tss = 0.7361 : val tss = 0.5937 ::: train hss = 0.1230 : val hss = 0.1689
Fold 3: train tss = 0.8163 : val tss = 0.1460 ::: train hss = 0.2929 : val hss = 0.0211
Fold 4: train tss = 0.7874 : val tss = 0.6481 ::: train hss = 0.2098 : val hss = 0.2737
mean cv TSS: 0.3506
mean cv HSS: 0.1096
861/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 35, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.6862 : val tss = 0.1405 ::: train hss = 0.0486 : val hss = 0.0891
Fold 1: train tss = 0.8616 : val tss = 0.4024 ::: train hss = 0.2291 : val hss = 0.1668
Fold 2: train tss = 0.6933 : val tss = 0.6044 ::: train hss = 0.1406 : val hss = 0.1892
Fold 3: train tss = 0.7660 : val tss = 0.3825 ::: train hss = 0.2288 : val hss = 0.0442
Fold 4: train tss = 0.7398 : val tss = 0.6243 ::: train hss = 0.1902 : val hss = 0.2263
mean cv TSS: 0.4308
mean cv HSS: 0.1431
862/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.01}
Total number of parameters: 4367
Fold 0: train tss = 0.9180 : val tss = -0.0403 ::: train hss = 0.0509 : val hss = -0.0189
Fold 1: train tss = 0.9241 : val tss = 0.3267 ::: train hss = 0.3302 : val hss = 0.1380
Fold 2: train tss = 0.8123 : val tss = 0.6769 ::: train hss = 0.1955 : val hss = 0.3143
Fold 3: train tss = 0.8332 : val tss = 0.0206 ::: train hss = 0.3226 : val hss = 0.0035
Fold 4: train tss = 0.7787 : val tss = 0.6209 ::: train hss = 0.1945 : val hss = 0.2403
mean cv TSS: 0.3209
mean cv HSS: 0.1355
863/864
{'batch_size': 256, 'bce_pos_class_weight': 80, 'cv_folds': 5, 'dropout_p': 0.2, 'hidden_layer_size': 16, 'input_layer_norm': False, 'loss': 'bce', 'lr': 0.015, 'num_epochs': 50, 'num_layers': 2, 'optimizer_type': 'adam', 'sequence_length': 45, 'weight_decay': 0.05}
Total number of parameters: 4367
Fold 0: train tss = 0.8385 : val tss = 0.2941 ::: train hss = 0.0611 : val hss = 0.1883
Fold 1: train tss = 0.8324 : val tss = 0.3585 ::: train hss = 0.2653 : val hss = 0.1128
Fold 2: train tss = 0.5989 : val tss = 0.3827 ::: train hss = 0.0658 : val hss = 0.0788
Fold 3: train tss = 0.7359 : val tss = 0.2938 ::: train hss = 0.1983 : val hss = 0.0287
Fold 4: train tss = 0.6374 : val tss = 0.4615 ::: train hss = 0.0999 : val hss = 0.1129
mean cv TSS: 0.3581
mean cv HSS: 0.1043

,batch_size,bce_pos_class_weight,dropout_p,hidden_layer_size,input_layer_norm,lr,num_layers,optimizer_type,sequence_length,weight_decay,tss,hss
723,256,80,0.1,2,False,0.0065,1,adam,35,0.05,0.5235,0.1588
291,128,80,0.1,2,False,0.0065,1,adam,35,0.05,0.5161,0.1694
663,256,50,0.2,2,False,0.0150,1,adam,35,0.05,0.5098,0.2064
662,256,50,0.2,2,False,0.0150,1,adam,35,0.01,0.5071,0.2105
615,256,50,0.1,4,False,0.0150,1,adam,35,0.05,0.5069,0.2061
399,128,80,0.2,4,False,0.0150,1,adam,35,0.05,0.5041,0.1606
316,128,80,0.1,4,False,0.0065,1,adam,45,0.01,0.4928,0.1519
183,128,50,0.1,4,False,0.0150,1,adam,35,0.05,0.4922,0.1843
150,128,50,0.1,2,False,0.0065,2,adam,10,0.01,0.4910,0.1790
216,128,50,0.2,2,False,0.0065,1,adam,10,0.01,0.4906,0.1885
687,256,50,0.2,4,False,0.0150,1,adam,35,0.05,0.4901,0.1923
365,128,80,0.2,2,False,0.0065,1,adam,45,0.05,0.4855,0.1573
253,128,50,0.2,4,False,0.0150,1,adam,10,0.05,0.4837,0.1793
831,256,80,0.2,4,False,0.0150,1,adam,35,0.05,0.4811,0.1514
221,128,50,0.2,2,False,0.0065,1,adam,45,0.05,0.4807,0.1966
593,256,50,0.1,2,False,0.0150,1,adam,45,0.05,0.4789,0.2713
819,256,80,0.2,4,False,0.0065,1,adam,35,0.05,0.4780,0.1685
685,256,50,0.2,4,False,0.0150,1,adam,10,0.05,0.4780,0.1603
737,256,80,0.1,2,False,0.0150,1,adam,45,0.05,0.4757,0.1788
613,256,50,0.1,4,False,0.0150,1,adam,10,0.05,0.4755,0.1846

In [10]:
grid.sort_values(by=['hss', 'tss'], ascending=False).head(20)

,batch_size,bce_pos_class_weight,dropout_p,hidden_layer_size,input_layer_norm,lr,num_layers,optimizer_type,sequence_length,weight_decay,tss,hss
40,128,5,0.1,4,False,0.0150,1,adam,45,0.01,0.2959,0.2975
75,128,5,0.2,2,False,0.0065,1,adam,35,0.05,0.3457,0.2896
76,128,5,0.2,2,False,0.0065,1,adam,45,0.01,0.3626,0.2878
50,128,5,0.1,16,False,0.0065,1,adam,35,0.01,0.3350,0.2823
130,128,5,0.2,16,False,0.0065,2,adam,45,0.01,0.3206,0.2727
570,256,5,0.2,16,False,0.0150,2,adam,10,0.01,0.3160,0.2717
593,256,50,0.1,2,False,0.0150,1,adam,45,0.05,0.4789,0.2713
496,256,5,0.1,16,False,0.0150,1,adam,45,0.01,0.3310,0.2679
566,256,5,0.2,16,False,0.0150,1,adam,35,0.01,0.3188,0.2679
110,128,5,0.2,4,False,0.0150,1,adam,35,0.01,0.3017,0.2675
112,128,5,0.2,4,False,0.0150,1,adam,45,0.01,0.3305,0.2672
24,128,5,0.1,4,False,0.0065,1,adam,10,0.01,0.2919,0.2655
96,128,5,0.2,4,False,0.0065,1,adam,10,0.01,0.3082,0.2628
540,256,5,0.2,4,False,0.0150,1,adam,10,0.01,0.3192,0.2595
468,256,5,0.1,4,False,0.0150,1,adam,10,0.01,0.3100,0.2580
564,256,5,0.2,16,False,0.0150,1,adam,10,0.01,0.3487,0.2575
444,256,5,0.1,2,False,0.0150,1,adam,10,0.01,0.2490,0.2567
560,256,5,0.2,16,False,0.0065,2,adam,35,0.01,0.3292,0.2565
62,128,5,0.1,16,False,0.0150,1,adam,35,0.01,0.3443,0.2543
0,128,5,0.1,2,False,0.0065,1,adam,10,0.01,0.2997,0.2537

In [11]:
if grid.empty:
    print("grid empty")
else:
    grid.to_csv("1_lstm_hypertune_grid_output_10.csv")
    print("grid output successful, saved as 1_lstm_hypertune_grid_output_10.csv")

grid output successful, saved as 1_lstm_hypertune_grid_output_10.csv