In [1]:
import torch

### set up CUDA as device if available
if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")
    cuda_id = torch.cuda.current_device()
    print(f"ID of current CUDA device:{torch.cuda.current_device()}")
    print(f"Name of current CUDA device:{torch.cuda.get_device_name(cuda_id)}")
    print(f"CUDA version: {torch.version.cuda}")
else:
    print("GPU is not available, using CPU")
    device = torch.device("cpu")
print(f"device: {device}")

GPU is available
cuda
CUDA version: 12.4
ID of current CUDA device:0
Name of current CUDA device:NVIDIA H200

In [2]:
import numpy as np
import random
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm, trange
from IPython import display
from sklearn.metrics import average_precision_score
# from conf_and_plot import confusion_matrix_plots
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import KFold
from sklearn.model_selection import ParameterGrid
import seaborn as sns
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import kruskal
import torch.nn.functional as F
from IPython.display import clear_output
import statistics

def seed_all(seed):
    if not seed:
        seed = 10

    print("[ Using Seed : ", seed, " ]")

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

seed_all(2025)

[ Using Seed :  2025  ]

In [3]:
scint_thresh = 0.1 # set the phase scintillation threshold

### following variable not being used anywhere
scint_outlier_thresh = 5. # set the value that determines phase scintillation outliers (these data samples will be removed)

processed_data_2015 = pd.read_csv("processed_data_2015.csv")
processed_data_2015 = processed_data_2015.drop(processed_data_2015.columns[0], axis=1)
predicted_label = 'sigmaPhi projected to vertical at prediction time [radians]'
y = processed_data_2015[predicted_label].values
print(y.shape)

X_fSelect = processed_data_2015.drop(predicted_label, axis=1)
X_fSelect = X_fSelect.values
print(X_fSelect.shape)

(4465846,)
(4465846, 15)

In [4]:
class simple_timeSeries_CNN(nn.Module):
    def __init__(self, cnn_filters, fc_size, dropout_p, loss, sequence_length):
        super(simple_timeSeries_CNN, self).__init__()
        
        self.loss = loss
        self.sequence_length = sequence_length

        self.conv1 = nn.Conv1d(in_channels=15, out_channels=cnn_filters, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm1d(num_features=cnn_filters)
        self.dropout = nn.Dropout(dropout_p)
        self.conv2 = nn.Conv1d(in_channels=cnn_filters, out_channels=cnn_filters*2, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm1d(num_features=cnn_filters*2)
        self.pool = nn.MaxPool1d(2)
        
        ### for simple, non true time-series CNN:
        # num_features = 25, MaxPool1d_size=2
        # 12 = round(25 / 2)
        # 6 = round(12 / 2)
        # self.fc1 = nn.Linear(cnn_filters * 2 * 6, fc_size)
        
        ### for true time-series CNN:
        # sequence_length, MaxPool1d_size=2
        # round(sequence_length / 2) = sequence_length // 2
        # per maxpool layer = sequence_length // 4
        
        self.fc1 = nn.Linear(cnn_filters * 2 * (sequence_length // 4), fc_size)
        # self.fc2 = nn.Linear(fc_size, 1)
        self.fc2 = nn.Linear(fc_size, sequence_length)

    def forward(self, x):
        x = self.pool(torch.relu(self.bn1(self.conv1(x))))
        x = self.dropout(x)
        x = self.pool(torch.relu(self.bn2(self.conv2(x))))
        x = x.view(x.size(0), -1) # Flatten the output for the fully connected layers
        x = torch.relu(self.fc1(x))
        
        # second fully connected layer + reshape to [batch_size, sequence_length, 1]
        x = self.fc2(x).view(x.size(0), self.sequence_length, 1)

        if self.loss == 'focal':
            # x = torch.sigmoid(self.fc2(x))
            x = torch.sigmoid(x)
        elif self.loss == 'bce':
            # x = self.fc2(x)
            pass
        
        return x

In [5]:
class simple_timeSeries_CNN(nn.Module):
    def __init__(self, cnn_filters, fc_size, dropout_p, loss, sequence_length):
        super(simple_timeSeries_CNN, self).__init__()
        
        self.loss = loss
#         self.seq_length = sequence_length

        self.conv1 = nn.Conv1d(in_channels=15, out_channels=cnn_filters, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm1d(num_features=cnn_filters)
        self.dropout = nn.Dropout(dropout_p)
        self.conv2 = nn.Conv1d(in_channels=cnn_filters, out_channels=cnn_filters*2, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm1d(num_features=cnn_filters*2)
        self.pool = nn.MaxPool1d(2)

        # Adjusted for sequence-to-one classification
        self.fc1 = nn.Linear(cnn_filters * 2 * (sequence_length // 4), fc_size)
        self.fc2 = nn.Linear(fc_size, 1)  # Output a single value per sequence

    def forward(self, x):
        x = self.pool(torch.relu(self.bn1(self.conv1(x))))
        x = self.dropout(x)
        x = self.pool(torch.relu(self.bn2(self.conv2(x))))
        x = x.view(x.size(0), -1)  # Flatten the output for the fully connected layers
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)  # Output shape: (batch_size, 1)

        if self.loss == 'focal':
            x = torch.sigmoid(x)
        elif self.loss == 'bce':
            pass  # Assume BCEWithLogitsLoss applied externally

        return x

In [6]:
def true_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    tss = (TP / (TP + FN)) - (FP / (FP + TN))
    return tss

def heidke_skill_score(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    
    numerator = 2 * (TP * TN - FP * FN)
    denominator = (TP + FP) * (FP + TN) + (TP + FN) * (TN + FP)
    
    # Avoid division by zero
    if denominator == 0:
        return 0.0
    
    hss = numerator / denominator
    return hss

In [7]:
class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction  # 'mean', 'sum', or 'none'

    def forward(self, inputs, targets):
        BCE_loss = F.binary_cross_entropy(inputs, targets, reduction='none')
        p_t = inputs * targets + (1 - inputs) * (1 - targets)
        focal_loss = self.alpha * (1 - p_t) ** self.gamma * BCE_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        elif self.reduction == 'none':
            return focal_loss
        else:
            raise ValueError(f"Invalid reduction method: {self.reduction}")

In [8]:
def train_model_with_cv(model, train_dataloader, val_dataloader, criterion, optimizer, scheduler, num_epochs):

    epochs = []
    training_loss = []
    validation_loss = []
    training_tss = []
    validation_tss = []
    training_hss = []
    validation_hss = []

    for epoch in range(num_epochs):

        ### training loop
        model.train()
        running_loss = 0.0
        predicted_training_labels = np.array([])
        y_train = np.array([])

        # for batch_inputs, batch_labels in tqdm(train_dataloader):
        for batch_inputs, batch_labels in train_dataloader:
            
            batch_inputs = batch_inputs.to(device)
            batch_labels = batch_labels.to(device)
            
            optimizer.zero_grad()
            output = model(batch_inputs)
            
            output.to(device)
            
            loss = criterion(output, batch_labels.float())
            loss.backward()
            optimizer.step()
            
            if scheduler == False:
                pass
            else:
                scheduler.step()
            
            running_loss += loss.item()
            with torch.no_grad(): predicted_training_labels = np.append(predicted_training_labels, output.cpu())
            with torch.no_grad(): y_train = np.append(y_train, batch_labels.cpu())

        predicted_training_labels = np.where(predicted_training_labels > 0.1, 1, 0)

        train_loss = running_loss / len(train_dataloader)
        train_tss = true_skill_score(y_train.astype(int), predicted_training_labels.astype(int))
        train_hss = heidke_skill_score(y_train.astype(int), predicted_training_labels.astype(int))

        ### validation loop
        model.eval()
        with torch.no_grad():
            running_loss = 0.0
            predicted_val_labels = np.array([])
            y_val = np.array([])

            # for batch_inputs, labels in tqdm(val_dataloader):
            for batch_inputs, batch_labels in val_dataloader:
            
                batch_inputs = batch_inputs.to(device)
                batch_labels = batch_labels.to(device)
                
                outputs = model(batch_inputs)
            
                outputs.to(device)
                
                outputs = model(batch_inputs)
                loss = criterion(outputs, batch_labels.float())
                running_loss += loss.item()
                predicted_val_labels = np.append(predicted_val_labels, outputs.cpu())
                y_val = np.append(y_val, batch_labels.cpu())

        predicted_val_labels = np.where(predicted_val_labels > 0.1, 1, 0)

        val_loss = running_loss / len(val_dataloader)
        val_tss = true_skill_score(y_val.astype(int), predicted_val_labels.astype(int))
        val_hss = heidke_skill_score(y_val.astype(int), predicted_val_labels.astype(int))

        epochs.append(epoch)
        training_loss.append(train_loss)
        validation_loss.append(val_loss)
        training_tss.append(train_tss)
        validation_tss.append(val_tss)
        training_hss.append(train_hss)
        validation_hss.append(val_hss)

    return training_hss, validation_hss, training_tss, validation_tss

In [9]:
class CNNBinaryTimeSeriesClassifier():
    def __init__(self, cnn_filters=8, fc_size=64, sequence_length=60, dropout_p=0.1, batch_size=128, 
                 optimizer_type = 'adam', lr=0.001, sgd_momentum=0.9, weight_decay=0.0001,
                 loss='bce', bce_pos_class_weight=50, focal_alpha=0.25, focal_gamma=2,
                 num_epochs=5, cv_folds=5, scheduler_t=0):
        self.cnn_filters = cnn_filters
        self.fc_size = fc_size
        self.sequence_length = sequence_length
        self.dropout_p = dropout_p
        self.batch_size = batch_size
        self.optimizer_type = optimizer_type
        self.lr = lr        
        self.weight_decay = weight_decay
        self.sgd_momentum = sgd_momentum
        self.loss = loss
        self.bce_pos_class_weight = bce_pos_class_weight
        self.focal_alpha = focal_alpha
        self.focal_gamma = focal_gamma
        self.num_epochs = num_epochs
        self.cv_folds = cv_folds
        self.scheduler_t = scheduler_t

    def reshape_data_to_overlapping_seq(self, data, seq_len):
        num_samples, input_features = data.shape
        num_sequences = num_samples - seq_len + 1
        sequences = np.zeros((num_sequences, seq_len, input_features), dtype=data.dtype)
        for i in range(num_sequences):
            sequences[i] = data[i:i + seq_len]
        return sequences
    
    def fit(self, X, y):

        cv_tss_values = []
        cv_hss_values = []

        tscv = TimeSeriesSplit(n_splits=self.cv_folds)
        for i, (train_index, val_index) in enumerate(tscv.split(X)):
            
            model = simple_timeSeries_CNN(cnn_filters=self.cnn_filters, 
                                          fc_size=self.fc_size, 
                                          dropout_p=self.dropout_p, 
                                          loss=self.loss, 
                                          sequence_length=self.sequence_length)
            model.to(device)
            
            if self.loss == 'bce':
                criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([self.bce_pos_class_weight]).to(device))
            elif self.loss == 'focal':
                criterion = FocalLoss(alpha=self.focal_alpha, gamma=self.focal_gamma)

            if self.optimizer_type == 'adam':
                optimizer = optim.Adam(model.parameters(), lr=self.lr, weight_decay=self.weight_decay)
            elif self.optimizer_type == 'sgd':
                optimizer = optim.SGD(model.parameters(), lr=self.lr, momentum=self.sgd_momentum, weight_decay=self.weight_decay)

            if self.scheduler_t > 0:
                scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=self.scheduler_t)
            else:
                scheduler = False

            X_train, X_val = X[train_index], X[val_index]
            y_train, y_val = y[train_index], y[val_index]
            
            scaler_X = RobustScaler()
            scaler_X = scaler_X.fit(X_train)

            X_train_scaled = scaler_X.transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            
            X_train_scaled = self.reshape_data_to_overlapping_seq(X_train_scaled, self.sequence_length)
            X_val_scaled = self.reshape_data_to_overlapping_seq(X_val_scaled, self.sequence_length)
            
            train_inputs = torch.tensor(X_train_scaled, dtype=torch.float32).transpose(1, 2)
            train_labels = torch.tensor(y_train[self.sequence_length - 1:], dtype=torch.float32).unsqueeze(1)
            train_dataset = TensorDataset(train_inputs, train_labels)
            train_dataloader = DataLoader(train_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)

            val_inputs = torch.tensor(X_val_scaled, dtype=torch.float32).transpose(1, 2)
            val_labels = torch.tensor(y_val[self.sequence_length - 1:], dtype=torch.float32).unsqueeze(1)
            val_dataset = TensorDataset(val_inputs, val_labels)
            val_dataloader = DataLoader(val_dataset, batch_size=self.batch_size, shuffle=False, worker_init_fn=seed_worker)
            
            training_hss, validation_hss, training_tss, validation_tss = \
            train_model_with_cv(model, 
                 train_dataloader, val_dataloader, 
                 criterion, optimizer, scheduler,
                 num_epochs=self.num_epochs)
            cv_tss_values.append(validation_tss[-1])
            cv_hss_values.append(validation_hss[-1])

            if i == 0:
                total_params = sum(p.numel() for p in model.parameters())
                print(f'Total number of parameters: {total_params}')
                
            print(f"Fold {i}: train tss = {training_tss[-1]:.4f} : val tss = {validation_tss[-1]:.4f} ::: train hss = {training_hss[-1]:.4f} : val hss = {validation_hss[-1]:.4f}")
        
        return cv_hss_values, cv_tss_values

In [10]:
training_data_size = 50000

X_train, X_test, \
    y_train, y_test, \
        idx_train, idx_test = train_test_split(X_fSelect, y, range(len(y)), train_size=training_data_size, shuffle=False)

# ### small test
# param_grid = {
#     'cnn_filters': [4],   
#     'fc_size': [64, 256],  
#     'sequence_length': [120],   
#     'dropout_p': [0.3],  
#     'batch_size': [512],  
#     'lr': [0.001],  
#     'optimizer_type': ['adam'],  
#     'weight_decay':[0.01],  
#     'loss': ['bce'],
#     'bce_pos_class_weight': [30],  
#     'num_epochs': [15],  
#     'cv_folds': [5], 
# }

### strategic hypertune iteration 1
param_grid = {
    'cnn_filters': [4, 32],
    'fc_size': [64, 1048],
    'sequence_length': [60, 120, 180],
    'dropout_p': [0.1, 0.3],
    'batch_size': [1024, 2048],
    'lr': [0.001, 0.01],
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.001, 0.01],
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 60],
#     'scheduler_t': [5],
    'num_epochs': [15],
    'cv_folds': [5], 
}

### strategic hypertune iteration 2
param_grid = {
    'cnn_filters': [4, 16, 64],  ### changed, added 1 dimension
    'fc_size': [128, 2048],  ### changed
    'sequence_length': [60, 180],  ### changed, removed 1 dimension
    'dropout_p': [0.1, 0.3],
    'batch_size': [2048, 4096],  ### changed
    'lr': [0.0075, 0.025],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.001, 0.01],
    'loss': ['bce'],
    'bce_pos_class_weight': [30, 60],  ### changed
#     'scheduler_t': [5],
    'num_epochs': [15],
    'cv_folds': [5], 
}

### strategic hypertune iteration 3
param_grid = {
    'cnn_filters': [64, 256],  ### changed, removed 1 dimension
    'fc_size': [512, 2048],  ### changed
    'sequence_length': [60, 120, 300],  ### changed, added 1 dimension
    'dropout_p': [0.1, 0.3],
    'batch_size': [1024, 4096],  ### changed
    'lr': [0.005, 0.05],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.001, 0.01],
    'loss': ['bce'],
    'bce_pos_class_weight': [20, 60],  ### changed
#     'scheduler_t': [5],
    'num_epochs': [15],
    'cv_folds': [5], 
}

### strategic hypertune iteration 4
param_grid = {
    'cnn_filters': [8, 32],  ### changed
    'fc_size': [128, 512],  ### changed
    'sequence_length': [30, 60, 120],  ### changed
    'dropout_p': [0.1, 0.3],
    'batch_size': [2048, 4096],  ### changed
    'lr': [0.0075, 0.03],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.001, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [15, 50],  ### changed
#     'scheduler_t': [5],
    'num_epochs': [15],
    'cv_folds': [5], 
}

### strategic hypertune iteration 5
param_grid = {
    'cnn_filters': [16, 48],  ### changed
    'fc_size': [256, 768],  ### changed
    'sequence_length': [30, 60, 120],  
    'dropout_p': [0.05, 0.4],  ### changed
    'batch_size': [3584, 4864],  ### changed
    'lr': [0.005, 0.025],  ### changed
    'optimizer_type': ['adam', 'sgd'],
    'weight_decay':[0.0025, 0.05],  ### changed
    'loss': ['bce'],
    'bce_pos_class_weight': [15, 50],  
#     'scheduler_t': [5],
    'num_epochs': [15],
    'cv_folds': [5], 
}

param_combinations = list(ParameterGrid(param_grid))

grid = pd.DataFrame()
tss_distributions = []
hss_distributions = []
mean_tss_scores = []
mean_hss_scores = []
for params in param_combinations:

    print(str(param_combinations.index(params)) + "/" + str(len(param_combinations)))
    print(params)

    cnn_time_series_classifier = CNNBinaryTimeSeriesClassifier(**params)
    cv_hss_values, cv_tss_values = cnn_time_series_classifier.fit(X_train, y_train)
    
    tss_distributions.append(cv_tss_values)
    hss_distributions.append(cv_hss_values)
    mean_cv_tss = sum(cv_tss_values)/len(cv_tss_values)
    mean_cv_hss = sum(cv_hss_values)/len(cv_hss_values)
    print(f"mean cv TSS: {mean_cv_tss:.4f}")
    print(f"mean cv HSS: {mean_cv_hss:.4f}")
    mean_tss_scores.append(mean_cv_tss)
    mean_hss_scores.append(mean_cv_hss)
    
    if params == param_combinations[0]:
        grid = pd.DataFrame(params, index=[0])
    else:
        grid = pd.concat([grid, pd.DataFrame([params])], ignore_index=True)

grid['tss'] = [round(num, 4) for num in mean_tss_scores]
grid['hss'] = [round(num, 4) for num in mean_hss_scores]
grid = grid.sort_values(by=['tss', 'hss'], ascending=False)
grid = grid.drop(columns=[col for col in ['num_epochs','cv_folds','loss','scheduler_t'] if col in grid.columns], axis=1)
grid.head(20)

0/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = -0.0001 ::: train hss = 0.0000 : val hss = -0.0002
Fold 1: train tss = 0.7628 : val tss = 0.0987 ::: train hss = 0.5894 : val hss = 0.0686
Fold 2: train tss = 0.6556 : val tss = 0.6117 ::: train hss = 0.3959 : val hss = 0.3510
Fold 3: train tss = 0.7061 : val tss = 0.0237 ::: train hss = 0.4946 : val hss = 0.0244
Fold 4: train tss = 0.7266 : val tss = 0.5673 ::: train hss = 0.3802 : val hss = 0.4174
mean cv TSS: 0.2603
mean cv HSS: 0.1722
1/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7749 : val tss = 0.1918 ::: train hss = 0.4152 : val hss = 0.0884
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7041 : val tss = -0.0042 ::: train hss = 0.4193 : val hss = -0.0042
Fold 4: train tss = 0.5369 : val tss = 0.6256 ::: train hss = 0.2720 : val hss = 0.3322
mean cv TSS: 0.1627
mean cv HSS: 0.0833
2/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7728 : val tss = 0.1098 ::: train hss = 0.5396 : val hss = 0.0853
Fold 2: train tss = 0.6202 : val tss = 0.6827 ::: train hss = 0.4196 : val hss = 0.3942
Fold 3: train tss = 0.7130 : val tss = 0.2111 ::: train hss = 0.3872 : val hss = 0.0606
Fold 4: train tss = 0.7315 : val tss = 0.5662 ::: train hss = 0.3457 : val hss = 0.4918
mean cv TSS: 0.3140
mean cv HSS: 0.2064
3/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7714 : val tss = 0.2900 ::: train hss = 0.4230 : val hss = 0.1340
Fold 2: train tss = 0.5722 : val tss = 0.7017 ::: train hss = 0.3303 : val hss = 0.3551
Fold 3: train tss = 0.7219 : val tss = -0.0090 ::: train hss = 0.3581 : val hss = -0.0077
Fold 4: train tss = 0.5428 : val tss = 0.6808 ::: train hss = 0.2914 : val hss = 0.3539
mean cv TSS: 0.3327
mean cv HSS: 0.1671
4/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0499 : val tss = -0.0014 ::: train hss = 0.0907 : val hss = -0.0026
Fold 1: train tss = 0.8402 : val tss = 0.2339 ::: train hss = 0.7339 : val hss = 0.1250
Fold 2: train tss = 0.7445 : val tss = 0.4165 ::: train hss = 0.4112 : val hss = 0.3441
Fold 3: train tss = 0.7233 : val tss = 0.0000 ::: train hss = 0.3751 : val hss = 0.0000
Fold 4: train tss = 0.7839 : val tss = 0.5346 ::: train hss = 0.4942 : val hss = 0.2921
mean cv TSS: 0.2367
mean cv HSS: 0.1517
5/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7116 : val tss = 0.1804 ::: train hss = 0.2122 : val hss = 0.0871
Fold 2: train tss = 0.4399 : val tss = 0.5396 ::: train hss = 0.1944 : val hss = 0.2975
Fold 3: train tss = 0.6933 : val tss = 0.0365 ::: train hss = 0.4420 : val hss = 0.0313
Fold 4: train tss = 0.6534 : val tss = 0.7112 ::: train hss = 0.3177 : val hss = 0.3409
mean cv TSS: 0.2936
mean cv HSS: 0.1514
6/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7347 : val tss = 0.1767 ::: train hss = 0.5579 : val hss = 0.1093
Fold 2: train tss = 0.6171 : val tss = 0.6566 ::: train hss = 0.3757 : val hss = 0.3650
Fold 3: train tss = 0.7475 : val tss = 0.0250 ::: train hss = 0.4676 : val hss = 0.0156
Fold 4: train tss = 0.6831 : val tss = 0.5625 ::: train hss = 0.3996 : val hss = 0.3649
mean cv TSS: 0.2842
mean cv HSS: 0.1710
7/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7358 : val tss = 0.2280 ::: train hss = 0.5777 : val hss = 0.1189
Fold 2: train tss = 0.6105 : val tss = 0.5809 ::: train hss = 0.3160 : val hss = 0.4181
Fold 3: train tss = 0.6595 : val tss = 0.0278 ::: train hss = 0.3880 : val hss = 0.0186
Fold 4: train tss = 0.6574 : val tss = 0.7417 ::: train hss = 0.3568 : val hss = 0.3213
mean cv TSS: 0.3157
mean cv HSS: 0.1754
8/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7439 : val tss = 0.0856 ::: train hss = 0.6498 : val hss = 0.0475
Fold 2: train tss = 0.6845 : val tss = 0.6178 ::: train hss = 0.4619 : val hss = 0.4262
Fold 3: train tss = 0.7136 : val tss = 0.0592 ::: train hss = 0.4261 : val hss = 0.0352
Fold 4: train tss = 0.6507 : val tss = 0.7281 ::: train hss = 0.4214 : val hss = 0.3894
mean cv TSS: 0.2981
mean cv HSS: 0.1797
9/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6561 : val tss = 0.2427 ::: train hss = 0.6576 : val hss = 0.1042
Fold 2: train tss = 0.6614 : val tss = 0.6514 ::: train hss = 0.4493 : val hss = 0.4911
Fold 3: train tss = 0.7214 : val tss = 0.0483 ::: train hss = 0.4291 : val hss = 0.0343
Fold 4: train tss = 0.6812 : val tss = 0.6957 ::: train hss = 0.3977 : val hss = 0.2689
mean cv TSS: 0.3276
mean cv HSS: 0.1797
10/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7761 : val tss = 0.2025 ::: train hss = 0.6806 : val hss = 0.0962
Fold 2: train tss = 0.6833 : val tss = 0.6874 ::: train hss = 0.2675 : val hss = 0.3473
Fold 3: train tss = 0.7921 : val tss = -0.0079 ::: train hss = 0.5429 : val hss = -0.0054

Fold 4: train tss = 0.7029 : val tss = 0.2800 ::: train hss = 0.4706 : val hss = 0.2605
mean cv TSS: 0.2324
mean cv HSS: 0.1397
11/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7759 : val tss = 0.1724 ::: train hss = 0.6778 : val hss = 0.0640
Fold 2: train tss = 0.5086 : val tss = 0.6081 ::: train hss = 0.4202 : val hss = 0.2797
Fold 3: train tss = 0.7826 : val tss = 0.0251 ::: train hss = 0.4868 : val hss = 0.0428
Fold 4: train tss = 0.7527 : val tss = 0.4841 ::: train hss = 0.4572 : val hss = 0.4461
mean cv TSS: 0.2579
mean cv HSS: 0.1665
12/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5031 : val tss = 0.4053 ::: train hss = 0.2076 : val hss = 0.1174
Fold 2: train tss = 0.4047 : val tss = 0.6139 ::: train hss = 0.2551 : val hss = 0.3648
Fold 3: train tss = 0.7107 : val tss = 0.1055 ::: train hss = 0.2977 : val hss = 0.0527
Fold 4: train tss = 0.6019 : val tss = 0.5643 ::: train hss = 0.2891 : val hss = 0.2647
mean cv TSS: 0.3378
mean cv HSS: 0.1599
13/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5191 : val tss = 0.3520 ::: train hss = 0.2840 : val hss = 0.1513
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5436 : val tss = -0.0022 ::: train hss = 0.2151 : val hss = -0.0038
Fold 4: train tss = 0.1414 : val tss = 0.6781 ::: train hss = 0.0909 : val hss = 0.2309
mean cv TSS: 0.2056
mean cv HSS: 0.0757
14/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7882 : val tss = 0.1984 ::: train hss = 0.6561 : val hss = 0.0934
Fold 2: train tss = 0.2885 : val tss = 0.4699 ::: train hss = 0.2504 : val hss = 0.2829
Fold 3: train tss = 0.7550 : val tss = -0.0109 ::: train hss = 0.3743 : val hss = -0.0121
Fold 4: train tss = 0.6621 : val tss = 0.5388 ::: train hss = 0.3723 : val hss = 0.3690
mean cv TSS: 0.2392
mean cv HSS: 0.1466
15/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3061 : val tss = 0.1513 ::: train hss = 0.2501 : val hss = 0.0931
Fold 2: train tss = 0.1564 : val tss = 0.3975 ::: train hss = 0.1726 : val hss = 0.3227
Fold 3: train tss = 0.5019 : val tss = 0.0489 ::: train hss = 0.2680 : val hss = 0.0238
Fold 4: train tss = 0.4703 : val tss = 0.7394 ::: train hss = 0.2036 : val hss = 0.4152
mean cv TSS: 0.2674
mean cv HSS: 0.1710
16/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7749 : val tss = 0.1170 ::: train hss = 0.3524 : val hss = 0.0577
Fold 2: train tss = 0.2129 : val tss = 0.2771 ::: train hss = 0.1512 : val hss = 0.1532
Fold 3: train tss = 0.6844 : val tss = 0.0649 ::: train hss = 0.3045 : val hss = 0.0157
Fold 4: train tss = 0.5407 : val tss = 0.5302 ::: train hss = 0.2068 : val hss = 0.2759
mean cv TSS: 0.1978
mean cv HSS: 0.1005
17/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.3476 : val tss = 0.0000 ::: train hss = 0.2958 : val hss = 0.0000
Fold 1: train tss = 0.6266 : val tss = 0.0924 ::: train hss = 0.2135 : val hss = 0.0302
Fold 2: train tss = 0.2899 : val tss = 0.5324 ::: train hss = 0.2019 : val hss = 0.3030
Fold 3: train tss = 0.4293 : val tss = 0.0671 ::: train hss = 0.2159 : val hss = 0.0391
Fold 4: train tss = 0.4883 : val tss = 0.6772 ::: train hss = 0.3202 : val hss = 0.3920
mean cv TSS: 0.2738
mean cv HSS: 0.1528
18/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7760 : val tss = 0.2090 ::: train hss = 0.5229 : val hss = 0.1164
Fold 2: train tss = 0.6006 : val tss = 0.6377 ::: train hss = 0.3178 : val hss = 0.3554
Fold 3: train tss = 0.7625 : val tss = 0.0438 ::: train hss = 0.4386 : val hss = 0.0195
Fold 4: train tss = 0.7138 : val tss = 0.6959 ::: train hss = 0.3596 : val hss = 0.3786
mean cv TSS: 0.3173
mean cv HSS: 0.1740
19/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6764 : val tss = 0.1149 ::: train hss = 0.6164 : val hss = 0.1643
Fold 2: train tss = 0.3279 : val tss = 0.5699 ::: train hss = 0.2392 : val hss = 0.4384
Fold 3: train tss = 0.6253 : val tss = 0.0702 ::: train hss = 0.3486 : val hss = 0.0549
Fold 4: train tss = 0.6044 : val tss = 0.5672 ::: train hss = 0.2567 : val hss = 0.3494
mean cv TSS: 0.2644
mean cv HSS: 0.2014
20/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7732 : val tss = 0.3440 ::: train hss = 0.4398 : val hss = 0.1364
Fold 2: train tss = 0.5944 : val tss = 0.6115 ::: train hss = 0.2681 : val hss = 0.4074
Fold 3: train tss = 0.7090 : val tss = 0.0293 ::: train hss = 0.4633 : val hss = 0.0165
Fold 4: train tss = 0.7733 : val tss = 0.4506 ::: train hss = 0.4326 : val hss = 0.4051
mean cv TSS: 0.2871
mean cv HSS: 0.1931
21/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6215 : val tss = 0.3253 ::: train hss = 0.5699 : val hss = 0.1173
Fold 2: train tss = 0.5245 : val tss = 0.6171 ::: train hss = 0.3551 : val hss = 0.3330

Fold 3: train tss = 0.6715 : val tss = 0.0435 ::: train hss = 0.3315 : val hss = 0.0347
Fold 4: train tss = 0.6034 : val tss = 0.5666 ::: train hss = 0.3097 : val hss = 0.4161
mean cv TSS: 0.3105
mean cv HSS: 0.1802
22/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.2494 : val tss = 0.0000 ::: train hss = 0.3325 : val hss = 0.0000
Fold 1: train tss = 0.7964 : val tss = 0.1065 ::: train hss = 0.6447 : val hss = 0.0578
Fold 2: train tss = 0.6096 : val tss = 0.5659 ::: train hss = 0.4641 : val hss = 0.3556
Fold 3: train tss = 0.7603 : val tss = 0.0510 ::: train hss = 0.5326 : val hss = 0.0140
Fold 4: train tss = 0.7235 : val tss = 0.2410 ::: train hss = 0.3966 : val hss = 0.2327
mean cv TSS: 0.1929
mean cv HSS: 0.1320
23/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.1989 : val tss = 0.0000 ::: train hss = 0.2411 : val hss = 0.0000
Fold 1: train tss = 0.7868 : val tss = 0.1282 ::: train hss = 0.6289 : val hss = 0.0580
Fold 2: train tss = 0.2744 : val tss = 0.5086 ::: train hss = 0.2366 : val hss = 0.3151
Fold 3: train tss = 0.4918 : val tss = 0.0912 ::: train hss = 0.2441 : val hss = 0.0127
Fold 4: train tss = 0.6135 : val tss = 0.7244 ::: train hss = 0.3367 : val hss = 0.4706
mean cv TSS: 0.2905
mean cv HSS: 0.1713
24/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7184 : val tss = 0.2645 ::: train hss = 0.2761 : val hss = 0.1327
Fold 2: train tss = 0.6738 : val tss = 0.5800 ::: train hss = 0.4110 : val hss = 0.4157
Fold 3: train tss = 0.7067 : val tss = 0.0522 ::: train hss = 0.3956 : val hss = 0.0177
Fold 4: train tss = 0.7796 : val tss = 0.4722 ::: train hss = 0.4009 : val hss = 0.3996
mean cv TSS: 0.2738
mean cv HSS: 0.1931
25/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4032 : val tss = 0.1873 ::: train hss = 0.4727 : val hss = 0.1359
Fold 2: train tss = 0.7202 : val tss = 0.5907 ::: train hss = 0.3740 : val hss = 0.3741
Fold 3: train tss = 0.6898 : val tss = 0.1060 ::: train hss = 0.3539 : val hss = 0.0318
Fold 4: train tss = 0.6986 : val tss = 0.7272 ::: train hss = 0.3072 : val hss = 0.3977
mean cv TSS: 0.3222
mean cv HSS: 0.1879
26/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7730 : val tss = 0.1376 ::: train hss = 0.6168 : val hss = 0.0705
Fold 2: train tss = 0.5148 : val tss = 0.6576 ::: train hss = 0.2869 : val hss = 0.2734
Fold 3: train tss = 0.7884 : val tss = -0.0029 ::: train hss = 0.4471 : val hss = -0.0031
Fold 4: train tss = 0.7773 : val tss = 0.5489 ::: train hss = 0.4441 : val hss = 0.3172
mean cv TSS: 0.2682
mean cv HSS: 0.1316
27/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7444 : val tss = 0.2336 ::: train hss = 0.4557 : val hss = 0.0885
Fold 2: train tss = 0.0016 : val tss = 0.1049 ::: train hss = 0.0032 : val hss = 0.1759
Fold 3: train tss = 0.5084 : val tss = 0.4370 ::: train hss = 0.2441 : val hss = 0.0575
Fold 4: train tss = 0.6377 : val tss = 0.6463 ::: train hss = 0.3421 : val hss = 0.4566
mean cv TSS: 0.2844
mean cv HSS: 0.1557
28/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = -0.0005 ::: train hss = 0.0000 : val hss = -0.0010
Fold 1: train tss = 0.8332 : val tss = 0.1470 ::: train hss = 0.6770 : val hss = 0.1269
Fold 2: train tss = 0.7483 : val tss = 0.7255 ::: train hss = 0.4236 : val hss = 0.4627
Fold 3: train tss = 0.7811 : val tss = 0.2651 ::: train hss = 0.4759 : val hss = 0.0693
Fold 4: train tss = 0.7212 : val tss = 0.5734 ::: train hss = 0.4146 : val hss = 0.2928
mean cv TSS: 0.3421
mean cv HSS: 0.1901
29/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7464 : val tss = 0.1698 ::: train hss = 0.6121 : val hss = 0.0555
Fold 2: train tss = 0.4439 : val tss = 0.6476 ::: train hss = 0.4295 : val hss = 0.4579
Fold 3: train tss = 0.7260 : val tss = -0.0059 ::: train hss = 0.4037 : val hss = -0.0083
Fold 4: train tss = 0.6753 : val tss = 0.7015 ::: train hss = 0.3763 : val hss = 0.3281
mean cv TSS: 0.3026
mean cv HSS: 0.1666
30/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6887 : val tss = 0.2910 ::: train hss = 0.5980 : val hss = 0.1380
Fold 2: train tss = 0.6690 : val tss = 0.6799 ::: train hss = 0.3720 : val hss = 0.3930
Fold 3: train tss = 0.7369 : val tss = 0.0260 ::: train hss = 0.4309 : val hss = 0.0137
Fold 4: train tss = 0.7226 : val tss = 0.5239 ::: train hss = 0.3192 : val hss = 0.4032
mean cv TSS: 0.3041
mean cv HSS: 0.1896
31/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7075 : val tss = 0.3732 ::: train hss = 0.5429 : val hss = 0.1575
Fold 2: train tss = 0.6574 : val tss = 0.6863 ::: train hss = 0.3322 : val hss = 0.4175
Fold 3: train tss = 0.7189 : val tss = 0.0362 ::: train hss = 0.4317 : val hss = 0.0238
Fold 4: train tss = 0.6440 : val tss = 0.6841 ::: train hss = 0.3297 : val hss = 0.3688
mean cv TSS: 0.3560
mean cv HSS: 0.1935
32/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7301 : val tss = 0.2860 ::: train hss = 0.6365 : val hss = 0.1289

Fold 2: train tss = 0.7044 : val tss = 0.6157 ::: train hss = 0.4507 : val hss = 0.4529
Fold 3: train tss = 0.7728 : val tss = 0.0264 ::: train hss = 0.4663 : val hss = 0.0141
Fold 4: train tss = 0.7383 : val tss = 0.4533 ::: train hss = 0.4070 : val hss = 0.3468
mean cv TSS: 0.2763
mean cv HSS: 0.1885
33/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7708 : val tss = 0.3063 ::: train hss = 0.6616 : val hss = 0.1294
Fold 2: train tss = 0.7105 : val tss = 0.5592 ::: train hss = 0.4194 : val hss = 0.4592
Fold 3: train tss = 0.6821 : val tss = 0.0879 ::: train hss = 0.4133 : val hss = 0.0203
Fold 4: train tss = 0.6371 : val tss = 0.4933 ::: train hss = 0.2877 : val hss = 0.2986
mean cv TSS: 0.2893
mean cv HSS: 0.1815
34/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7671 : val tss = 0.1786 ::: train hss = 0.6767 : val hss = 0.0816
Fold 2: train tss = 0.6818 : val tss = 0.7234 ::: train hss = 0.6024 : val hss = 0.5340
Fold 3: train tss = 0.7464 : val tss = 0.2426 ::: train hss = 0.6262 : val hss = 0.0918
Fold 4: train tss = 0.7478 : val tss = 0.7028 ::: train hss = 0.4367 : val hss = 0.3863
mean cv TSS: 0.3695
mean cv HSS: 0.2187
35/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7663 : val tss = 0.2241 ::: train hss = 0.6589 : val hss = 0.1069
Fold 2: train tss = 0.3673 : val tss = 0.5386 ::: train hss = 0.3376 : val hss = 0.4109
Fold 3: train tss = 0.7515 : val tss = -0.0019 ::: train hss = 0.4464 : val hss = -0.0006
Fold 4: train tss = 0.7195 : val tss = 0.6760 ::: train hss = 0.3507 : val hss = 0.5509
mean cv TSS: 0.2874
mean cv HSS: 0.2136
36/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7381 : val tss = 0.2229 ::: train hss = 0.3950 : val hss = 0.1309
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7044 : val tss = 0.0789 ::: train hss = 0.3037 : val hss = 0.0298
Fold 4: train tss = 0.5338 : val tss = 0.6740 ::: train hss = 0.1915 : val hss = 0.2450
mean cv TSS: 0.1952
mean cv HSS: 0.0811
37/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7141 : val tss = 0.3547 ::: train hss = 0.2302 : val hss = 0.1379
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4083 : val tss = 0.0988 ::: train hss = 0.1403 : val hss = 0.0275
Fold 4: train tss = 0.2921 : val tss = 0.6882 ::: train hss = 0.1496 : val hss = 0.3233
mean cv TSS: 0.2283
mean cv HSS: 0.0977
38/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7230 : val tss = 0.1586 ::: train hss = 0.3202 : val hss = 0.0368
Fold 2: train tss = 0.4134 : val tss = 0.4553 ::: train hss = 0.2002 : val hss = 0.2530
Fold 3: train tss = 0.5821 : val tss = 0.1506 ::: train hss = 0.2470 : val hss = 0.0408
Fold 4: train tss = 0.6150 : val tss = 0.5354 ::: train hss = 0.2414 : val hss = 0.2258
mean cv TSS: 0.2600
mean cv HSS: 0.1113
39/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4588 : val tss = 0.3539 ::: train hss = 0.2093 : val hss = 0.1453
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5392 : val tss = 0.0803 ::: train hss = 0.2072 : val hss = 0.0357
Fold 4: train tss = 0.2144 : val tss = 0.0000 ::: train hss = 0.0853 : val hss = 0.0000
mean cv TSS: 0.0868
mean cv HSS: 0.0362
40/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0489 : val tss = -0.0037 ::: train hss = 0.0652 : val hss = -0.0065
Fold 1: train tss = 0.7293 : val tss = 0.1212 ::: train hss = 0.2402 : val hss = 0.0416
Fold 2: train tss = 0.3167 : val tss = 0.4213 ::: train hss = 0.1625 : val hss = 0.1402
Fold 3: train tss = 0.6143 : val tss = 0.0237 ::: train hss = 0.2372 : val hss = 0.0065
Fold 4: train tss = 0.6159 : val tss = 0.6913 ::: train hss = 0.2811 : val hss = 0.4397
mean cv TSS: 0.2508
mean cv HSS: 0.1243
41/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = -0.0005 ::: train hss = 0.0000 : val hss = -0.0010
Fold 1: train tss = 0.5219 : val tss = 0.0879 ::: train hss = 0.2176 : val hss = 0.0192
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5964 : val tss = 0.0950 ::: train hss = 0.2540 : val hss = 0.0236
Fold 4: train tss = -0.0011 : val tss = 0.7049 ::: train hss = -0.0009 : val hss = 0.2818
mean cv TSS: 0.1775
mean cv HSS: 0.0647
42/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6805 : val tss = 0.1984 ::: train hss = 0.4678 : val hss = 0.1165
Fold 2: train tss = 0.6386 : val tss = 0.6581 ::: train hss = 0.2915 : val hss = 0.3542
Fold 3: train tss = 0.7656 : val tss = 0.1026 ::: train hss = 0.3759 : val hss = 0.0420
Fold 4: train tss = 0.7239 : val tss = 0.5993 ::: train hss = 0.4231 : val hss = 0.3586
mean cv TSS: 0.3117
mean cv HSS: 0.1743
43/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000

Fold 1: train tss = 0.7572 : val tss = 0.1845 ::: train hss = 0.5692 : val hss = 0.1864
Fold 2: train tss = 0.5328 : val tss = 0.5655 ::: train hss = 0.2909 : val hss = 0.3984
Fold 3: train tss = 0.5988 : val tss = 0.0652 ::: train hss = 0.3181 : val hss = 0.0232
Fold 4: train tss = 0.5391 : val tss = 0.7204 ::: train hss = 0.2424 : val hss = 0.3015
mean cv TSS: 0.3071
mean cv HSS: 0.1819
44/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7673 : val tss = 0.1485 ::: train hss = 0.6810 : val hss = 0.1008
Fold 2: train tss = 0.7155 : val tss = 0.7183 ::: train hss = 0.4068 : val hss = 0.4144
Fold 3: train tss = 0.6151 : val tss = 0.1262 ::: train hss = 0.4396 : val hss = 0.0434
Fold 4: train tss = 0.6835 : val tss = 0.7375 ::: train hss = 0.3561 : val hss = 0.5109
mean cv TSS: 0.3461
mean cv HSS: 0.2139
45/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3192 : val tss = 0.2809 ::: train hss = 0.0923 : val hss = 0.1114
Fold 2: train tss = 0.4428 : val tss = 0.6302 ::: train hss = 0.3111 : val hss = 0.3970
Fold 3: train tss = 0.6221 : val tss = 0.0557 ::: train hss = 0.3509 : val hss = 0.0224
Fold 4: train tss = 0.5961 : val tss = 0.6507 ::: train hss = 0.2845 : val hss = 0.3194
mean cv TSS: 0.3235
mean cv HSS: 0.1700
46/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.3977 : val tss = -0.0007 ::: train hss = 0.3385 : val hss = -0.0015
Fold 1: train tss = 0.7766 : val tss = 0.1379 ::: train hss = 0.6920 : val hss = 0.1077
Fold 2: train tss = 0.5852 : val tss = 0.6251 ::: train hss = 0.4385 : val hss = 0.4044
Fold 3: train tss = 0.6660 : val tss = 0.0458 ::: train hss = 0.3469 : val hss = 0.0120
Fold 4: train tss = 0.7411 : val tss = 0.7107 ::: train hss = 0.4502 : val hss = 0.4924
mean cv TSS: 0.3037
mean cv HSS: 0.2030
47/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.1988 : val tss = 0.0000 ::: train hss = 0.2339 : val hss = 0.0000
Fold 1: train tss = 0.7788 : val tss = 0.1450 ::: train hss = 0.6446 : val hss = 0.0699
Fold 2: train tss = 0.3418 : val tss = 0.5629 ::: train hss = 0.2782 : val hss = 0.3401
Fold 3: train tss = 0.6717 : val tss = 0.0160 ::: train hss = 0.3681 : val hss = 0.0129
Fold 4: train tss = 0.6053 : val tss = 0.6017 ::: train hss = 0.3182 : val hss = 0.3954
mean cv TSS: 0.2651
mean cv HSS: 0.1636
48/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7327 : val tss = 0.2820 ::: train hss = 0.4701 : val hss = 0.0944
Fold 2: train tss = 0.5975 : val tss = 0.6772 ::: train hss = 0.3194 : val hss = 0.3614
Fold 3: train tss = 0.6955 : val tss = 0.0901 ::: train hss = 0.4335 : val hss = 0.0404
Fold 4: train tss = 0.7035 : val tss = 0.5190 ::: train hss = 0.4035 : val hss = 0.2066
mean cv TSS: 0.3137
mean cv HSS: 0.1406
49/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6925 : val tss = 0.3426 ::: train hss = 0.5136 : val hss = 0.1482
Fold 2: train tss = 0.7237 : val tss = 0.7304 ::: train hss = 0.3416 : val hss = 0.4432
Fold 3: train tss = 0.6761 : val tss = 0.0525 ::: train hss = 0.3861 : val hss = 0.0201
Fold 4: train tss = 0.6596 : val tss = 0.7030 ::: train hss = 0.3172 : val hss = 0.2633
mean cv TSS: 0.3657
mean cv HSS: 0.1750
50/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7298 : val tss = 0.2542 ::: train hss = 0.5495 : val hss = 0.0928
Fold 2: train tss = 0.6900 : val tss = 0.7030 ::: train hss = 0.3387 : val hss = 0.3573
Fold 3: train tss = 0.7463 : val tss = 0.0022 ::: train hss = 0.3974 : val hss = 0.0020
Fold 4: train tss = 0.7111 : val tss = 0.5394 ::: train hss = 0.3901 : val hss = 0.2576
mean cv TSS: 0.2998
mean cv HSS: 0.1419
51/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7466 : val tss = 0.2894 ::: train hss = 0.6145 : val hss = 0.1095
Fold 2: train tss = 0.6287 : val tss = 0.6003 ::: train hss = 0.2416 : val hss = 0.2943
Fold 3: train tss = 0.5284 : val tss = 0.0550 ::: train hss = 0.4431 : val hss = 0.0253
Fold 4: train tss = 0.6656 : val tss = 0.5661 ::: train hss = 0.3529 : val hss = 0.2406
mean cv TSS: 0.3022
mean cv HSS: 0.1339
52/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7600 : val tss = 0.2748 ::: train hss = 0.6198 : val hss = 0.2152
Fold 2: train tss = 0.6598 : val tss = 0.6664 ::: train hss = 0.4123 : val hss = 0.3373
Fold 3: train tss = 0.7549 : val tss = 0.0889 ::: train hss = 0.4213 : val hss = 0.0394
Fold 4: train tss = 0.7221 : val tss = 0.6174 ::: train hss = 0.3940 : val hss = 0.3498
mean cv TSS: 0.3295
mean cv HSS: 0.1883
53/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = -0.0004 ::: train hss = 0.0000 : val hss = -0.0007
Fold 1: train tss = 0.6696 : val tss = 0.2275 ::: train hss = 0.6635 : val hss = 0.1688
Fold 2: train tss = 0.4037 : val tss = 0.6798 ::: train hss = 0.3137 : val hss = 0.3594
Fold 3: train tss = 0.7357 : val tss = -0.0099 ::: train hss = 0.4171 : val hss = -0.0017
Fold 4: train tss = 0.6435 : val tss = 0.6726 ::: train hss = 0.3875 : val hss = 0.2444
mean cv TSS: 0.3139
mean cv HSS: 0.1540
54/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6656 : val tss = 0.2861 ::: train hss = 0.4444 : val hss = 0.1141
Fold 2: train tss = 0.5474 : val tss = 0.6877 ::: train hss = 0.3023 : val hss = 0.3476
Fold 3: train tss = 0.6959 : val tss = 0.1030 ::: train hss = 0.3399 : val hss = 0.0273
Fold 4: train tss = 0.6630 : val tss = 0.6035 ::: train hss = 0.3210 : val hss = 0.3025
mean cv TSS: 0.3360
mean cv HSS: 0.1583
55/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6146 : val tss = 0.3021 ::: train hss = 0.5214 : val hss = 0.1242
Fold 2: train tss = 0.6044 : val tss = 0.7024 ::: train hss = 0.3195 : val hss = 0.3454
Fold 3: train tss = 0.6735 : val tss = 0.0418 ::: train hss = 0.3606 : val hss = 0.0139
Fold 4: train tss = 0.6589 : val tss = 0.6712 ::: train hss = 0.3677 : val hss = 0.2468
mean cv TSS: 0.3435
mean cv HSS: 0.1461
56/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6944 : val tss = 0.2788 ::: train hss = 0.5432 : val hss = 0.1093
Fold 2: train tss = 0.5911 : val tss = 0.6812 ::: train hss = 0.3478 : val hss = 0.3342
Fold 3: train tss = 0.6953 : val tss = 0.0342 ::: train hss = 0.3967 : val hss = 0.0132
Fold 4: train tss = 0.6747 : val tss = 0.6973 ::: train hss = 0.3684 : val hss = 0.3874
mean cv TSS: 0.3383
mean cv HSS: 0.1688
57/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7479 : val tss = 0.3248 ::: train hss = 0.5593 : val hss = 0.1077
Fold 2: train tss = 0.6138 : val tss = 0.6333 ::: train hss = 0.3669 : val hss = 0.3690
Fold 3: train tss = 0.7103 : val tss = 0.0522 ::: train hss = 0.4188 : val hss = 0.0270
Fold 4: train tss = 0.6737 : val tss = 0.6949 ::: train hss = 0.3874 : val hss = 0.3403
mean cv TSS: 0.3410
mean cv HSS: 0.1688
58/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7698 : val tss = 0.2106 ::: train hss = 0.6395 : val hss = 0.1031
Fold 2: train tss = 0.6552 : val tss = 0.6454 ::: train hss = 0.4294 : val hss = 0.2777
Fold 3: train tss = 0.7557 : val tss = -0.0048 ::: train hss = 0.4581 : val hss = -0.0011
Fold 4: train tss = 0.6896 : val tss = 0.0930 ::: train hss = 0.3652 : val hss = 0.1198
mean cv TSS: 0.1888
mean cv HSS: 0.0999
59/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7641 : val tss = 0.1963 ::: train hss = 0.6140 : val hss = 0.0561
Fold 2: train tss = 0.6031 : val tss = 0.6875 ::: train hss = 0.3769 : val hss = 0.3577
Fold 3: train tss = 0.7117 : val tss = 0.0020 ::: train hss = 0.4652 : val hss = 0.0008
Fold 4: train tss = 0.6965 : val tss = 0.5303 ::: train hss = 0.3953 : val hss = 0.3147
mean cv TSS: 0.2832
mean cv HSS: 0.1459
60/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6127 : val tss = 0.1927 ::: train hss = 0.4915 : val hss = 0.0933
Fold 2: train tss = 0.4836 : val tss = 0.6637 ::: train hss = 0.2391 : val hss = 0.3130
Fold 3: train tss = 0.6988 : val tss = 0.2930 ::: train hss = 0.3251 : val hss = 0.0356
Fold 4: train tss = 0.6397 : val tss = 0.5462 ::: train hss = 0.2587 : val hss = 0.1963
mean cv TSS: 0.3391
mean cv HSS: 0.1277
61/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4511 : val tss = 0.0082 ::: train hss = 0.3070 : val hss = 0.0023
Fold 4: train tss = 0.5397 : val tss = 0.4584 ::: train hss = 0.2351 : val hss = 0.3708
mean cv TSS: 0.0933
mean cv HSS: 0.0746
62/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6302 : val tss = 0.1025 ::: train hss = 0.3896 : val hss = 0.0243
Fold 2: train tss = 0.3579 : val tss = 0.5219 ::: train hss = 0.2474 : val hss = 0.3587
Fold 3: train tss = 0.6289 : val tss = 0.2177 ::: train hss = 0.2191 : val hss = 0.0348
Fold 4: train tss = 0.6306 : val tss = 0.4848 ::: train hss = 0.3118 : val hss = 0.2756
mean cv TSS: 0.2654
mean cv HSS: 0.1387
63/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5238 : val tss = 0.2154 ::: train hss = 0.2243 : val hss = 0.0456
Fold 2: train tss = 0.2540 : val tss = 0.6402 ::: train hss = 0.2152 : val hss = 0.4944
Fold 3: train tss = 0.5299 : val tss = 0.0724 ::: train hss = 0.2240 : val hss = 0.0252
Fold 4: train tss = 0.4864 : val tss = 0.5895 ::: train hss = 0.2159 : val hss = 0.2349
mean cv TSS: 0.3035
mean cv HSS: 0.1600
64/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0496 : val tss = -0.0051 ::: train hss = 0.0827 : val hss = -0.0085
Fold 1: train tss = 0.6953 : val tss = 0.0841 ::: train hss = 0.5588 : val hss = 0.0393
Fold 2: train tss = 0.3486 : val tss = 0.2697 ::: train hss = 0.2357 : val hss = 0.1539
Fold 3: train tss = 0.7319 : val tss = 0.1064 ::: train hss = 0.2942 : val hss = 0.0153
Fold 4: train tss = 0.6119 : val tss = 0.6033 ::: train hss = 0.3084 : val hss = 0.2482
mean cv TSS: 0.2117
mean cv HSS: 0.0896
65/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 248673
Fold 0: train tss = 0.3446 : val tss = 0.0000 ::: train hss = 0.1942 : val hss = 0.0000
Fold 1: train tss = 0.4858 : val tss = 0.2113 ::: train hss = 0.1507 : val hss = 0.0759
Fold 2: train tss = 0.2457 : val tss = 0.2412 ::: train hss = 0.1730 : val hss = 0.2643
Fold 3: train tss = 0.4686 : val tss = -0.0046 ::: train hss = 0.2180 : val hss = -0.0034
Fold 4: train tss = 0.3393 : val tss = 0.7652 ::: train hss = 0.1522 : val hss = 0.3754
mean cv TSS: 0.2426
mean cv HSS: 0.1424
66/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7399 : val tss = 0.2895 ::: train hss = 0.4103 : val hss = 0.1055
Fold 2: train tss = 0.5443 : val tss = 0.6521 ::: train hss = 0.3700 : val hss = 0.4393
Fold 3: train tss = 0.7315 : val tss = 0.0766 ::: train hss = 0.3589 : val hss = 0.0320
Fold 4: train tss = 0.6465 : val tss = 0.4414 ::: train hss = 0.2998 : val hss = 0.3881
mean cv TSS: 0.2919
mean cv HSS: 0.1930
67/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6628 : val tss = 0.4102 ::: train hss = 0.2703 : val hss = 0.1162
Fold 2: train tss = 0.4955 : val tss = 0.6681 ::: train hss = 0.2401 : val hss = 0.4238
Fold 3: train tss = 0.5941 : val tss = 0.0162 ::: train hss = 0.3607 : val hss = 0.0050
Fold 4: train tss = 0.3938 : val tss = 0.5755 ::: train hss = 0.1611 : val hss = 0.1560
mean cv TSS: 0.3340
mean cv HSS: 0.1402
68/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7542 : val tss = 0.2323 ::: train hss = 0.5932 : val hss = 0.0998
Fold 2: train tss = 0.6020 : val tss = 0.4643 ::: train hss = 0.3698 : val hss = 0.4210
Fold 3: train tss = 0.7832 : val tss = 0.0527 ::: train hss = 0.4666 : val hss = 0.0422
Fold 4: train tss = 0.7075 : val tss = 0.5672 ::: train hss = 0.3412 : val hss = 0.4747
mean cv TSS: 0.2633
mean cv HSS: 0.2075
69/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7644 : val tss = 0.3452 ::: train hss = 0.3994 : val hss = 0.1141
Fold 2: train tss = 0.4633 : val tss = 0.5269 ::: train hss = 0.1570 : val hss = 0.3505
Fold 3: train tss = 0.6292 : val tss = 0.0915 ::: train hss = 0.3188 : val hss = 0.0422
Fold 4: train tss = 0.5377 : val tss = 0.7248 ::: train hss = 0.2425 : val hss = 0.2894
mean cv TSS: 0.3377
mean cv HSS: 0.1592
70/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7659 : val tss = 0.2108 ::: train hss = 0.6497 : val hss = 0.0872
Fold 2: train tss = 0.6960 : val tss = 0.5818 ::: train hss = 0.3766 : val hss = 0.4685
Fold 3: train tss = 0.7475 : val tss = 0.0370 ::: train hss = 0.4023 : val hss = 0.0118
Fold 4: train tss = 0.7202 : val tss = 0.5911 ::: train hss = 0.4268 : val hss = 0.3419
mean cv TSS: 0.2841
mean cv HSS: 0.1819
71/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7622 : val tss = 0.0475 ::: train hss = 0.6672 : val hss = 0.0098
Fold 2: train tss = 0.5466 : val tss = 0.5415 ::: train hss = 0.1790 : val hss = 0.2861
Fold 3: train tss = 0.6594 : val tss = 0.0201 ::: train hss = 0.3504 : val hss = 0.0114
Fold 4: train tss = 0.4839 : val tss = 0.6700 ::: train hss = 0.1929 : val hss = 0.3549
mean cv TSS: 0.2558
mean cv HSS: 0.1324
72/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7322 : val tss = 0.3008 ::: train hss = 0.5195 : val hss = 0.1101
Fold 2: train tss = 0.7028 : val tss = 0.6993 ::: train hss = 0.3659 : val hss = 0.4450
Fold 3: train tss = 0.7095 : val tss = 0.2753 ::: train hss = 0.3972 : val hss = 0.0500
Fold 4: train tss = 0.7216 : val tss = 0.6543 ::: train hss = 0.4128 : val hss = 0.2239
mean cv TSS: 0.3860
mean cv HSS: 0.1658
73/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7310 : val tss = 0.1920 ::: train hss = 0.5025 : val hss = 0.0886
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7449 : val tss = 0.1119 ::: train hss = 0.3692 : val hss = 0.0635
Fold 4: train tss = 0.5940 : val tss = 0.6996 ::: train hss = 0.2392 : val hss = 0.2925
mean cv TSS: 0.2007
mean cv HSS: 0.0889
74/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7575 : val tss = 0.0842 ::: train hss = 0.5089 : val hss = 0.0375
Fold 2: train tss = 0.6929 : val tss = 0.6571 ::: train hss = 0.3518 : val hss = 0.2503
Fold 3: train tss = 0.7339 : val tss = 0.3159 ::: train hss = 0.4187 : val hss = 0.0791
Fold 4: train tss = 0.6837 : val tss = 0.5822 ::: train hss = 0.3374 : val hss = 0.3112
mean cv TSS: 0.3279
mean cv HSS: 0.1356
75/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6456 : val tss = 0.2278 ::: train hss = 0.6163 : val hss = 0.0736
Fold 2: train tss = 0.5080 : val tss = 0.6455 ::: train hss = 0.3199 : val hss = 0.4054
Fold 3: train tss = 0.7274 : val tss = 0.0758 ::: train hss = 0.3782 : val hss = 0.0171
Fold 4: train tss = 0.5003 : val tss = 0.5708 ::: train hss = 0.3683 : val hss = 0.2913
mean cv TSS: 0.3040
mean cv HSS: 0.1575
76/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 741217
Fold 0: train tss = 0.0499 : val tss = -0.0006 ::: train hss = 0.0907 : val hss = -0.0012
Fold 1: train tss = 0.7726 : val tss = 0.0805 ::: train hss = 0.6098 : val hss = 0.0456
Fold 2: train tss = 0.5151 : val tss = 0.6238 ::: train hss = 0.2743 : val hss = 0.2423
Fold 3: train tss = 0.7650 : val tss = 0.2044 ::: train hss = 0.4364 : val hss = 0.0265
Fold 4: train tss = 0.7024 : val tss = 0.5528 ::: train hss = 0.4118 : val hss = 0.2840
mean cv TSS: 0.2922
mean cv HSS: 0.1194
77/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7673 : val tss = 0.1263 ::: train hss = 0.5929 : val hss = 0.0411
Fold 2: train tss = 0.3559 : val tss = 0.5773 ::: train hss = 0.3034 : val hss = 0.3587
Fold 3: train tss = 0.6898 : val tss = -0.0049 ::: train hss = 0.4095 : val hss = -0.0025
Fold 4: train tss = 0.5323 : val tss = 0.6187 ::: train hss = 0.2425 : val hss = 0.1973
mean cv TSS: 0.2635
mean cv HSS: 0.1189
78/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7103 : val tss = 0.3745 ::: train hss = 0.5181 : val hss = 0.1395
Fold 2: train tss = 0.5272 : val tss = 0.6803 ::: train hss = 0.3300 : val hss = 0.3231
Fold 3: train tss = 0.7212 : val tss = -0.0011 ::: train hss = 0.3581 : val hss = -0.0009
Fold 4: train tss = 0.6506 : val tss = 0.6964 ::: train hss = 0.3425 : val hss = 0.2947
mean cv TSS: 0.3500
mean cv HSS: 0.1513
79/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6771 : val tss = 0.3677 ::: train hss = 0.4796 : val hss = 0.1565
Fold 2: train tss = 0.5847 : val tss = 0.7145 ::: train hss = 0.3324 : val hss = 0.3834
Fold 3: train tss = 0.6998 : val tss = 0.0604 ::: train hss = 0.3873 : val hss = 0.0305
Fold 4: train tss = 0.6482 : val tss = 0.7250 ::: train hss = 0.2912 : val hss = 0.3379
mean cv TSS: 0.3735
mean cv HSS: 0.1817
80/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7488 : val tss = 0.2817 ::: train hss = 0.5756 : val hss = 0.0944
Fold 2: train tss = 0.6401 : val tss = 0.6853 ::: train hss = 0.3772 : val hss = 0.3942
Fold 3: train tss = 0.6898 : val tss = 0.1694 ::: train hss = 0.4553 : val hss = 0.0253
Fold 4: train tss = 0.6623 : val tss = 0.6700 ::: train hss = 0.3565 : val hss = 0.3337
mean cv TSS: 0.3613
mean cv HSS: 0.1695
81/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7715 : val tss = 0.2836 ::: train hss = 0.5879 : val hss = 0.0862
Fold 2: train tss = 0.5844 : val tss = 0.6494 ::: train hss = 0.3802 : val hss = 0.3381
Fold 3: train tss = 0.7200 : val tss = 0.0406 ::: train hss = 0.4232 : val hss = 0.0300
Fold 4: train tss = 0.6450 : val tss = 0.6497 ::: train hss = 0.3665 : val hss = 0.3364
mean cv TSS: 0.3247
mean cv HSS: 0.1581
82/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7561 : val tss = 0.2402 ::: train hss = 0.6293 : val hss = 0.0787
Fold 2: train tss = 0.6152 : val tss = 0.7051 ::: train hss = 0.4366 : val hss = 0.3580
Fold 3: train tss = 0.7771 : val tss = 0.0063 ::: train hss = 0.4759 : val hss = 0.0039
Fold 4: train tss = 0.7234 : val tss = 0.7663 ::: train hss = 0.4317 : val hss = 0.3476
mean cv TSS: 0.3436
mean cv HSS: 0.1577
83/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7604 : val tss = 0.1456 ::: train hss = 0.6270 : val hss = 0.0646
Fold 2: train tss = 0.6492 : val tss = 0.7029 ::: train hss = 0.4247 : val hss = 0.4192
Fold 3: train tss = 0.7281 : val tss = 0.0664 ::: train hss = 0.4377 : val hss = 0.0242
Fold 4: train tss = 0.6784 : val tss = 0.6074 ::: train hss = 0.3921 : val hss = 0.4026
mean cv TSS: 0.3045
mean cv HSS: 0.1821
84/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = -0.0004 : val tss = -0.0007 ::: train hss = -0.0006 : val hss = -0.0014
Fold 1: train tss = 0.6189 : val tss = 0.3557 ::: train hss = 0.2800 : val hss = 0.1120
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6950 : val tss = 0.2123 ::: train hss = 0.2233 : val hss = 0.0311
Fold 4: train tss = 0.5748 : val tss = 0.5350 ::: train hss = 0.2289 : val hss = 0.2043
mean cv TSS: 0.2204
mean cv HSS: 0.0692
85/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5628 : val tss = 0.2893 ::: train hss = 0.1921 : val hss = 0.0848
Fold 2: train tss = 0.2540 : val tss = 0.2547 ::: train hss = 0.1595 : val hss = 0.3070
Fold 3: train tss = 0.4723 : val tss = 0.0571 ::: train hss = 0.1524 : val hss = 0.0128
Fold 4: train tss = 0.3299 : val tss = 0.6599 ::: train hss = 0.1705 : val hss = 0.2072
mean cv TSS: 0.2522
mean cv HSS: 0.1224
86/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4932 : val tss = 0.0671 ::: train hss = 0.3455 : val hss = 0.0211
Fold 2: train tss = 0.4866 : val tss = 0.6399 ::: train hss = 0.1984 : val hss = 0.2956
Fold 3: train tss = 0.6369 : val tss = 0.0340 ::: train hss = 0.2449 : val hss = 0.0130
Fold 4: train tss = 0.5869 : val tss = 0.5903 ::: train hss = 0.1851 : val hss = 0.2481
mean cv TSS: 0.2663
mean cv HSS: 0.1156
87/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3263 : val tss = 0.2232 ::: train hss = 0.1962 : val hss = 0.0831
Fold 2: train tss = 0.3214 : val tss = 0.4998 ::: train hss = 0.1588 : val hss = 0.3452
Fold 3: train tss = 0.5756 : val tss = 0.2271 ::: train hss = 0.2747 : val hss = 0.0328
Fold 4: train tss = 0.5722 : val tss = 0.6170 ::: train hss = 0.2480 : val hss = 0.3104
mean cv TSS: 0.3134
mean cv HSS: 0.1543
88/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6273 : val tss = 0.1299 ::: train hss = 0.2441 : val hss = 0.0436
Fold 2: train tss = 0.5206 : val tss = 0.6034 ::: train hss = 0.1517 : val hss = 0.2261
Fold 3: train tss = 0.6118 : val tss = 0.1019 ::: train hss = 0.2329 : val hss = 0.0229
Fold 4: train tss = 0.6756 : val tss = 0.3858 ::: train hss = 0.3154 : val hss = 0.3416
mean cv TSS: 0.2442
mean cv HSS: 0.1268
89/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5824 : val tss = 0.0794 ::: train hss = 0.2411 : val hss = 0.0070
Fold 4: train tss = 0.4723 : val tss = 0.6025 ::: train hss = 0.2341 : val hss = 0.3276
mean cv TSS: 0.1364
mean cv HSS: 0.0669
90/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6259 : val tss = 0.2928 ::: train hss = 0.2107 : val hss = 0.1066
Fold 2: train tss = 0.4269 : val tss = 0.5444 ::: train hss = 0.2157 : val hss = 0.3401
Fold 3: train tss = 0.6775 : val tss = 0.0930 ::: train hss = 0.4235 : val hss = 0.0244
Fold 4: train tss = 0.6456 : val tss = 0.5827 ::: train hss = 0.3302 : val hss = 0.3223
mean cv TSS: 0.3026
mean cv HSS: 0.1587
91/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5733 : val tss = 0.3426 ::: train hss = 0.2256 : val hss = 0.1370
Fold 2: train tss = 0.3218 : val tss = 0.5492 ::: train hss = 0.1800 : val hss = 0.3867
Fold 3: train tss = 0.6225 : val tss = 0.0134 ::: train hss = 0.3371 : val hss = 0.0033
Fold 4: train tss = 0.5995 : val tss = 0.6321 ::: train hss = 0.2754 : val hss = 0.2059
mean cv TSS: 0.3075
mean cv HSS: 0.1466
92/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7255 : val tss = 0.3549 ::: train hss = 0.3636 : val hss = 0.0972
Fold 2: train tss = 0.3762 : val tss = 0.6297 ::: train hss = 0.3018 : val hss = 0.3358
Fold 3: train tss = 0.7596 : val tss = 0.0584 ::: train hss = 0.4301 : val hss = 0.0425
Fold 4: train tss = 0.6915 : val tss = 0.7198 ::: train hss = 0.3445 : val hss = 0.5190
mean cv TSS: 0.3526
mean cv HSS: 0.1989
93/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5768 : val tss = 0.2658 ::: train hss = 0.2394 : val hss = 0.1048
Fold 2: train tss = 0.1525 : val tss = 0.5779 ::: train hss = 0.1683 : val hss = 0.3461
Fold 3: train tss = 0.6103 : val tss = 0.0731 ::: train hss = 0.3301 : val hss = 0.0291
Fold 4: train tss = 0.4335 : val tss = 0.6361 ::: train hss = 0.1704 : val hss = 0.1958
mean cv TSS: 0.3106
mean cv HSS: 0.1352
94/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8209 : val tss = 0.1397 ::: train hss = 0.6964 : val hss = 0.0651
Fold 2: train tss = 0.7159 : val tss = 0.6255 ::: train hss = 0.2839 : val hss = 0.3098
Fold 3: train tss = 0.7676 : val tss = 0.0170 ::: train hss = 0.4371 : val hss = 0.0141
Fold 4: train tss = 0.7423 : val tss = 0.6614 ::: train hss = 0.4723 : val hss = 0.3926
mean cv TSS: 0.2887
mean cv HSS: 0.1563
95/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7753 : val tss = 0.1750 ::: train hss = 0.6628 : val hss = 0.0799
Fold 2: train tss = 0.4009 : val tss = 0.5763 ::: train hss = 0.2399 : val hss = 0.2626
Fold 3: train tss = 0.6378 : val tss = 0.0253 ::: train hss = 0.2827 : val hss = 0.0278
Fold 4: train tss = 0.6272 : val tss = 0.6996 ::: train hss = 0.3190 : val hss = 0.3495
mean cv TSS: 0.2952
mean cv HSS: 0.1440
96/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6451 : val tss = 0.1782 ::: train hss = 0.5213 : val hss = 0.0925
Fold 2: train tss = 0.6348 : val tss = 0.7105 ::: train hss = 0.2176 : val hss = 0.3649
Fold 3: train tss = 0.7826 : val tss = 0.0666 ::: train hss = 0.4011 : val hss = 0.0618
Fold 4: train tss = 0.7557 : val tss = 0.6385 ::: train hss = 0.3950 : val hss = 0.2747
mean cv TSS: 0.3188
mean cv HSS: 0.1588
97/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6790 : val tss = 0.1642 ::: train hss = 0.5070 : val hss = 0.1960
Fold 2: train tss = 0.5303 : val tss = 0.6077 ::: train hss = 0.2502 : val hss = 0.4640
Fold 3: train tss = 0.5887 : val tss = 0.0927 ::: train hss = 0.3665 : val hss = 0.0516
Fold 4: train tss = 0.6535 : val tss = 0.7338 ::: train hss = 0.3116 : val hss = 0.3999
mean cv TSS: 0.3197
mean cv HSS: 0.2223
98/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 385569
Fold 0: train tss = 0.0500 : val tss = 0.0000 ::: train hss = 0.0952 : val hss = 0.0000
Fold 1: train tss = 0.7500 : val tss = 0.2308 ::: train hss = 0.5962 : val hss = 0.0963
Fold 2: train tss = 0.7174 : val tss = 0.3445 ::: train hss = 0.4298 : val hss = 0.3844
Fold 3: train tss = 0.7197 : val tss = 0.0173 ::: train hss = 0.3864 : val hss = 0.0200
Fold 4: train tss = 0.7573 : val tss = 0.5058 ::: train hss = 0.4294 : val hss = 0.3731
mean cv TSS: 0.2197
mean cv HSS: 0.1748
99/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7715 : val tss = -0.0404 ::: train hss = 0.4678 : val hss = -0.0355
Fold 2: train tss = 0.4512 : val tss = 0.5843 ::: train hss = 0.2609 : val hss = 0.3207
Fold 3: train tss = 0.7408 : val tss = 0.0474 ::: train hss = 0.4341 : val hss = 0.0428
Fold 4: train tss = 0.6054 : val tss = 0.6391 ::: train hss = 0.2651 : val hss = 0.2192
mean cv TSS: 0.2461
mean cv HSS: 0.1094
100/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8952 : val tss = 0.2104 ::: train hss = 0.6822 : val hss = 0.1259
Fold 2: train tss = 0.7437 : val tss = 0.5931 ::: train hss = 0.3537 : val hss = 0.4622
Fold 3: train tss = 0.7030 : val tss = 0.1132 ::: train hss = 0.4153 : val hss = 0.0280
Fold 4: train tss = 0.7132 : val tss = 0.4468 ::: train hss = 0.4426 : val hss = 0.3697
mean cv TSS: 0.2727
mean cv HSS: 0.1972
101/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = -0.0001 : val tss = -0.0005 ::: train hss = -0.0002 : val hss = -0.0010
Fold 1: train tss = 0.5973 : val tss = 0.1633 ::: train hss = 0.6168 : val hss = 0.0570
Fold 2: train tss = 0.4848 : val tss = 0.6142 ::: train hss = 0.2748 : val hss = 0.3857
Fold 3: train tss = 0.5812 : val tss = 0.0325 ::: train hss = 0.3004 : val hss = 0.0140
Fold 4: train tss = 0.6417 : val tss = 0.6748 ::: train hss = 0.3859 : val hss = 0.3284
mean cv TSS: 0.2968
mean cv HSS: 0.1568
102/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7422 : val tss = 0.1667 ::: train hss = 0.6143 : val hss = 0.0978
Fold 2: train tss = 0.4228 : val tss = 0.6515 ::: train hss = 0.3254 : val hss = 0.2485
Fold 3: train tss = 0.7988 : val tss = 0.0025 ::: train hss = 0.4313 : val hss = 0.0034
Fold 4: train tss = 0.7224 : val tss = 0.4844 ::: train hss = 0.4371 : val hss = 0.3147
mean cv TSS: 0.2610
mean cv HSS: 0.1329
103/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7348 : val tss = 0.2424 ::: train hss = 0.6444 : val hss = 0.1180
Fold 2: train tss = 0.7033 : val tss = 0.6618 ::: train hss = 0.4695 : val hss = 0.4616
Fold 3: train tss = 0.6553 : val tss = 0.0289 ::: train hss = 0.4194 : val hss = 0.0135
Fold 4: train tss = 0.6930 : val tss = 0.6482 ::: train hss = 0.4254 : val hss = 0.4132
mean cv TSS: 0.3163
mean cv HSS: 0.2013
104/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7743 : val tss = 0.2542 ::: train hss = 0.6409 : val hss = 0.1169
Fold 2: train tss = 0.3802 : val tss = 0.6088 ::: train hss = 0.3918 : val hss = 0.3464
Fold 3: train tss = 0.7596 : val tss = 0.0062 ::: train hss = 0.4145 : val hss = 0.0102
Fold 4: train tss = 0.7333 : val tss = 0.5560 ::: train hss = 0.4166 : val hss = 0.4653
mean cv TSS: 0.2850
mean cv HSS: 0.1878
105/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7748 : val tss = 0.1731 ::: train hss = 0.6523 : val hss = 0.0890
Fold 2: train tss = 0.7287 : val tss = 0.6747 ::: train hss = 0.2672 : val hss = 0.3091
Fold 3: train tss = 0.7849 : val tss = -0.0039 ::: train hss = 0.4298 : val hss = -0.0061
Fold 4: train tss = 0.7203 : val tss = 0.4317 ::: train hss = 0.3704 : val hss = 0.4158
mean cv TSS: 0.2551
mean cv HSS: 0.1616
106/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.2985 : val tss = -0.0019 ::: train hss = 0.3142 : val hss = -0.0035
Fold 1: train tss = 0.7722 : val tss = 0.1555 ::: train hss = 0.6937 : val hss = 0.0732
Fold 2: train tss = 0.7838 : val tss = 0.6816 ::: train hss = 0.2988 : val hss = 0.3152
Fold 3: train tss = 0.7850 : val tss = -0.0089 ::: train hss = 0.6308 : val hss = -0.0108
Fold 4: train tss = 0.7507 : val tss = 0.4709 ::: train hss = 0.5043 : val hss = 0.4056
mean cv TSS: 0.2595
mean cv HSS: 0.1560
107/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7722 : val tss = 0.1998 ::: train hss = 0.6937 : val hss = 0.0876
Fold 2: train tss = 0.7211 : val tss = 0.7106 ::: train hss = 0.5148 : val hss = 0.3376
Fold 3: train tss = 0.7874 : val tss = -0.0028 ::: train hss = 0.4947 : val hss = -0.0047
Fold 4: train tss = 0.7439 : val tss = 0.6780 ::: train hss = 0.4690 : val hss = 0.3418
mean cv TSS: 0.3171
mean cv HSS: 0.1525
108/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7193 : val tss = 0.0494 ::: train hss = 0.6942 : val hss = 0.0410
Fold 2: train tss = 0.3721 : val tss = 0.6301 ::: train hss = 0.1876 : val hss = 0.3111
Fold 3: train tss = 0.6996 : val tss = 0.1026 ::: train hss = 0.2835 : val hss = 0.0297
Fold 4: train tss = 0.6669 : val tss = 0.6082 ::: train hss = 0.2815 : val hss = 0.2947
mean cv TSS: 0.2781
mean cv HSS: 0.1353
109/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6007 : val tss = 0.3552 ::: train hss = 0.1862 : val hss = 0.1624
Fold 2: train tss = 0.1364 : val tss = 0.2652 ::: train hss = 0.0827 : val hss = 0.3583
Fold 3: train tss = 0.5083 : val tss = 0.2782 ::: train hss = 0.2551 : val hss = 0.0306
Fold 4: train tss = 0.5371 : val tss = 0.7380 ::: train hss = 0.1899 : val hss = 0.3213
mean cv TSS: 0.3273
mean cv HSS: 0.1745
110/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6490 : val tss = 0.2376 ::: train hss = 0.5150 : val hss = 0.0655
Fold 2: train tss = 0.4744 : val tss = 0.4022 ::: train hss = 0.1890 : val hss = 0.3410
Fold 3: train tss = 0.5913 : val tss = 0.0843 ::: train hss = 0.1936 : val hss = 0.0165
Fold 4: train tss = 0.4902 : val tss = 0.6514 ::: train hss = 0.1887 : val hss = 0.2510
mean cv TSS: 0.2751
mean cv HSS: 0.1348
111/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6277 : val tss = 0.2819 ::: train hss = 0.1840 : val hss = 0.1045
Fold 2: train tss = 0.0000 : val tss = 0.0672 ::: train hss = 0.0000 : val hss = 0.0781
Fold 3: train tss = 0.5915 : val tss = 0.0383 ::: train hss = 0.2570 : val hss = 0.0266
Fold 4: train tss = 0.2999 : val tss = 0.7588 ::: train hss = 0.1819 : val hss = 0.3965
mean cv TSS: 0.2292
mean cv HSS: 0.1211
112/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6607 : val tss = 0.1363 ::: train hss = 0.2456 : val hss = 0.0143
Fold 2: train tss = 0.2133 : val tss = 0.4643 ::: train hss = 0.0759 : val hss = 0.3470
Fold 3: train tss = 0.5193 : val tss = 0.0470 ::: train hss = 0.2938 : val hss = 0.0169
Fold 4: train tss = 0.5737 : val tss = 0.6662 ::: train hss = 0.1760 : val hss = 0.3331
mean cv TSS: 0.2628
mean cv HSS: 0.1423
113/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = -0.0010 : val tss = 0.0000 ::: train hss = -0.0014 : val hss = 0.0000
Fold 1: train tss = 0.4242 : val tss = 0.2064 ::: train hss = 0.2185 : val hss = 0.1585
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5156 : val tss = -0.0020 ::: train hss = 0.2372 : val hss = -0.0035
Fold 4: train tss = 0.0042 : val tss = 0.6020 ::: train hss = 0.0039 : val hss = 0.3003
mean cv TSS: 0.1613
mean cv HSS: 0.0911
114/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6595 : val tss = 0.2206 ::: train hss = 0.4250 : val hss = 0.1429
Fold 2: train tss = 0.3623 : val tss = 0.5472 ::: train hss = 0.1382 : val hss = 0.1555
Fold 3: train tss = 0.7865 : val tss = 0.0428 ::: train hss = 0.3758 : val hss = 0.0335
Fold 4: train tss = 0.6832 : val tss = 0.7233 ::: train hss = 0.3818 : val hss = 0.3315
mean cv TSS: 0.3068
mean cv HSS: 0.1327
115/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7739 : val tss = 0.1131 ::: train hss = 0.5562 : val hss = 0.0983
Fold 2: train tss = 0.4973 : val tss = 0.6834 ::: train hss = 0.2702 : val hss = 0.4693
Fold 3: train tss = 0.6430 : val tss = 0.0397 ::: train hss = 0.3214 : val hss = 0.0116
Fold 4: train tss = 0.6336 : val tss = 0.6885 ::: train hss = 0.2964 : val hss = 0.4481
mean cv TSS: 0.3049
mean cv HSS: 0.2055
116/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.3469 : val tss = 0.0000 ::: train hss = 0.2618 : val hss = 0.0000
Fold 1: train tss = 0.6926 : val tss = 0.2463 ::: train hss = 0.5887 : val hss = 0.1152
Fold 2: train tss = 0.5461 : val tss = 0.6709 ::: train hss = 0.3702 : val hss = 0.4045
Fold 3: train tss = 0.6732 : val tss = 0.0984 ::: train hss = 0.3871 : val hss = 0.0513
Fold 4: train tss = 0.6934 : val tss = 0.7402 ::: train hss = 0.3797 : val hss = 0.4288
mean cv TSS: 0.3512
mean cv HSS: 0.1999
117/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7597 : val tss = 0.2815 ::: train hss = 0.5399 : val hss = 0.1317
Fold 2: train tss = 0.5714 : val tss = 0.6020 ::: train hss = 0.3754 : val hss = 0.2693
Fold 3: train tss = 0.7073 : val tss = 0.0042 ::: train hss = 0.3559 : val hss = 0.0025
Fold 4: train tss = 0.4851 : val tss = 0.6073 ::: train hss = 0.2741 : val hss = 0.1804
mean cv TSS: 0.2990
mean cv HSS: 0.1168
118/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.3976 : val tss = -0.0030 ::: train hss = 0.3313 : val hss = -0.0054
Fold 1: train tss = 0.7646 : val tss = 0.1944 ::: train hss = 0.7236 : val hss = 0.1086
Fold 2: train tss = 0.6842 : val tss = 0.6742 ::: train hss = 0.5640 : val hss = 0.4441
Fold 3: train tss = 0.7239 : val tss = 0.0617 ::: train hss = 0.3961 : val hss = 0.0322
Fold 4: train tss = 0.6790 : val tss = 0.6670 ::: train hss = 0.3631 : val hss = 0.2878
mean cv TSS: 0.3189
mean cv HSS: 0.1735
119/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.1495 : val tss = 0.0000 ::: train hss = 0.2215 : val hss = 0.0000
Fold 1: train tss = 0.7745 : val tss = 0.1682 ::: train hss = 0.6472 : val hss = 0.0737
Fold 2: train tss = 0.6950 : val tss = 0.6490 ::: train hss = 0.3173 : val hss = 0.4089
Fold 3: train tss = 0.7120 : val tss = -0.0063 ::: train hss = 0.3187 : val hss = -0.0086
Fold 4: train tss = 0.5213 : val tss = 0.7010 ::: train hss = 0.2233 : val hss = 0.2669
mean cv TSS: 0.3024
mean cv HSS: 0.1482
120/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8017 : val tss = 0.2938 ::: train hss = 0.2921 : val hss = 0.1273
Fold 2: train tss = 0.7592 : val tss = 0.6299 ::: train hss = 0.4351 : val hss = 0.4297
Fold 3: train tss = 0.7501 : val tss = 0.0397 ::: train hss = 0.4806 : val hss = 0.0230
Fold 4: train tss = 0.7404 : val tss = 0.5453 ::: train hss = 0.3536 : val hss = 0.2975
mean cv TSS: 0.3017
mean cv HSS: 0.1755
121/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7233 : val tss = 0.1426 ::: train hss = 0.1755 : val hss = 0.1044
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6430 : val tss = 0.0332 ::: train hss = 0.3728 : val hss = 0.0203
Fold 4: train tss = 0.5645 : val tss = 0.5682 ::: train hss = 0.3775 : val hss = 0.2832
mean cv TSS: 0.1488
mean cv HSS: 0.0816
122/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7396 : val tss = 0.1739 ::: train hss = 0.6525 : val hss = 0.1942
Fold 2: train tss = 0.7377 : val tss = 0.5851 ::: train hss = 0.4124 : val hss = 0.4127
Fold 3: train tss = 0.7566 : val tss = -0.0121 ::: train hss = 0.4474 : val hss = -0.0128
Fold 4: train tss = 0.7464 : val tss = 0.4572 ::: train hss = 0.4134 : val hss = 0.4002
mean cv TSS: 0.2408
mean cv HSS: 0.1989
123/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6899 : val tss = 0.2487 ::: train hss = 0.5407 : val hss = 0.0948
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6881 : val tss = 0.0224 ::: train hss = 0.4219 : val hss = 0.0083
Fold 4: train tss = 0.6158 : val tss = 0.7110 ::: train hss = 0.3250 : val hss = 0.2725
mean cv TSS: 0.1964
mean cv HSS: 0.0751
124/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.9005 : val tss = 0.1344 ::: train hss = 0.6995 : val hss = 0.2005
Fold 2: train tss = 0.5565 : val tss = 0.6186 ::: train hss = 0.4071 : val hss = 0.4786
Fold 3: train tss = 0.7325 : val tss = -0.0022 ::: train hss = 0.3533 : val hss = -0.0038
Fold 4: train tss = 0.7224 : val tss = 0.4602 ::: train hss = 0.4011 : val hss = 0.3362
mean cv TSS: 0.2422
mean cv HSS: 0.2023
125/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5441 : val tss = 0.2021 ::: train hss = 0.4388 : val hss = 0.1486
Fold 2: train tss = 0.3485 : val tss = 0.5058 ::: train hss = 0.2352 : val hss = 0.3357
Fold 3: train tss = 0.6806 : val tss = -0.0100 ::: train hss = 0.3645 : val hss = -0.0065
Fold 4: train tss = 0.6535 : val tss = 0.7562 ::: train hss = 0.2893 : val hss = 0.4353
mean cv TSS: 0.2908
mean cv HSS: 0.1826
126/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7570 : val tss = 0.2098 ::: train hss = 0.6472 : val hss = 0.1175
Fold 2: train tss = 0.6982 : val tss = 0.5872 ::: train hss = 0.3876 : val hss = 0.4627
Fold 3: train tss = 0.7671 : val tss = 0.0121 ::: train hss = 0.3758 : val hss = 0.0114
Fold 4: train tss = 0.7518 : val tss = 0.5738 ::: train hss = 0.4447 : val hss = 0.2860
mean cv TSS: 0.2766
mean cv HSS: 0.1755
127/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7392 : val tss = 0.1647 ::: train hss = 0.6445 : val hss = 0.1036
Fold 2: train tss = 0.4742 : val tss = 0.5712 ::: train hss = 0.2876 : val hss = 0.2333
Fold 3: train tss = 0.6577 : val tss = 0.0916 ::: train hss = 0.4231 : val hss = 0.0288
Fold 4: train tss = 0.6610 : val tss = 0.7039 ::: train hss = 0.3130 : val hss = 0.3760
mean cv TSS: 0.3063
mean cv HSS: 0.1483
128/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7745 : val tss = 0.1827 ::: train hss = 0.6459 : val hss = 0.1464
Fold 2: train tss = 0.7663 : val tss = 0.6922 ::: train hss = 0.5155 : val hss = 0.5079
Fold 3: train tss = 0.7923 : val tss = -0.0111 ::: train hss = 0.4678 : val hss = -0.0123
Fold 4: train tss = 0.7095 : val tss = 0.6068 ::: train hss = 0.3433 : val hss = 0.2899
mean cv TSS: 0.2941
mean cv HSS: 0.1864
129/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7659 : val tss = 0.1629 ::: train hss = 0.6511 : val hss = 0.0839
Fold 2: train tss = 0.6518 : val tss = 0.6389 ::: train hss = 0.2499 : val hss = 0.3585
Fold 3: train tss = 0.7661 : val tss = 0.0277 ::: train hss = 0.5052 : val hss = 0.0336
Fold 4: train tss = 0.6482 : val tss = 0.5817 ::: train hss = 0.2624 : val hss = 0.4316
mean cv TSS: 0.2822
mean cv HSS: 0.1815
130/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.3480 : val tss = -0.0001 ::: train hss = 0.3238 : val hss = -0.0002
Fold 1: train tss = 0.7808 : val tss = 0.1704 ::: train hss = 0.6889 : val hss = 0.0789
Fold 2: train tss = 0.6814 : val tss = 0.4962 ::: train hss = 0.2624 : val hss = 0.3798
Fold 3: train tss = 0.8424 : val tss = -0.0005 ::: train hss = 0.5512 : val hss = -0.0010
Fold 4: train tss = 0.6816 : val tss = 0.5911 ::: train hss = 0.3674 : val hss = 0.2542
mean cv TSS: 0.2514
mean cv HSS: 0.1423
131/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 2229793
Fold 0: train tss = 0.1493 : val tss = -0.0004 ::: train hss = 0.2059 : val hss = -0.0007
Fold 1: train tss = 0.7947 : val tss = 0.1626 ::: train hss = 0.7039 : val hss = 0.0931
Fold 2: train tss = 0.7975 : val tss = 0.7218 ::: train hss = 0.3676 : val hss = 0.4150
Fold 3: train tss = 0.7991 : val tss = -0.0036 ::: train hss = 0.5008 : val hss = -0.0057
Fold 4: train tss = 0.6995 : val tss = 0.6662 ::: train hss = 0.5481 : val hss = 0.3648
mean cv TSS: 0.3093
mean cv HSS: 0.1733
132/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7352 : val tss = 0.3337 ::: train hss = 0.3170 : val hss = 0.1322
Fold 2: train tss = 0.5677 : val tss = 0.6828 ::: train hss = 0.2064 : val hss = 0.3180
Fold 3: train tss = 0.7507 : val tss = 0.0417 ::: train hss = 0.3188 : val hss = 0.0251
Fold 4: train tss = 0.6998 : val tss = 0.6071 ::: train hss = 0.3161 : val hss = 0.2879
mean cv TSS: 0.3331
mean cv HSS: 0.1526
133/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5670 : val tss = 0.2760 ::: train hss = 0.1266 : val hss = 0.0758
Fold 2: train tss = 0.2565 : val tss = 0.5807 ::: train hss = 0.1133 : val hss = 0.3535
Fold 3: train tss = 0.4262 : val tss = 0.0613 ::: train hss = 0.1792 : val hss = 0.0169
Fold 4: train tss = 0.4233 : val tss = 0.6734 ::: train hss = 0.1816 : val hss = 0.2877
mean cv TSS: 0.3183
mean cv HSS: 0.1468
134/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7459 : val tss = 0.1666 ::: train hss = 0.2694 : val hss = 0.0953
Fold 2: train tss = 0.0065 : val tss = -0.0022 ::: train hss = 0.0124 : val hss = -0.0043
Fold 3: train tss = 0.6480 : val tss = 0.1887 ::: train hss = 0.2329 : val hss = 0.0379
Fold 4: train tss = 0.4719 : val tss = 0.7695 ::: train hss = 0.2570 : val hss = 0.4580
mean cv TSS: 0.2245
mean cv HSS: 0.1174
135/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5658 : val tss = 0.2481 ::: train hss = 0.1619 : val hss = 0.0592
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.3885 : val tss = 0.0665 ::: train hss = 0.1600 : val hss = 0.0241
Fold 4: train tss = 0.4643 : val tss = 0.6847 ::: train hss = 0.1777 : val hss = 0.2826
mean cv TSS: 0.1998
mean cv HSS: 0.0732
136/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0495 : val tss = -0.0009 ::: train hss = 0.0792 : val hss = -0.0017
Fold 1: train tss = 0.4394 : val tss = -0.0127 ::: train hss = 0.0922 : val hss = -0.0047
Fold 2: train tss = -0.0016 : val tss = -0.0106 ::: train hss = -0.0029 : val hss = -0.0183
Fold 3: train tss = 0.6122 : val tss = 0.1601 ::: train hss = 0.2077 : val hss = 0.0253
Fold 4: train tss = 0.4674 : val tss = 0.6858 ::: train hss = 0.1885 : val hss = 0.2795
mean cv TSS: 0.1643
mean cv HSS: 0.0560
137/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.1958 : val tss = -0.0026 ::: train hss = 0.2203 : val hss = -0.0026
Fold 2: train tss = 0.0000 : val tss = 0.0042 ::: train hss = 0.0000 : val hss = 0.0080
Fold 3: train tss = -0.0719 : val tss = 0.0589 ::: train hss = -0.0338 : val hss = 0.0147
Fold 4: train tss = 0.1493 : val tss = 0.5684 ::: train hss = 0.1069 : val hss = 0.3308
mean cv TSS: 0.1258
mean cv HSS: 0.0702
138/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.2487 : val tss = 0.0000 ::: train hss = 0.2763 : val hss = 0.0000
Fold 1: train tss = 0.7545 : val tss = 0.1990 ::: train hss = 0.3882 : val hss = 0.1282
Fold 2: train tss = 0.7480 : val tss = 0.6956 ::: train hss = 0.4320 : val hss = 0.3586
Fold 3: train tss = 0.7465 : val tss = 0.0135 ::: train hss = 0.3952 : val hss = 0.0037
Fold 4: train tss = 0.6416 : val tss = 0.6297 ::: train hss = 0.3286 : val hss = 0.3862
mean cv TSS: 0.3075
mean cv HSS: 0.1753
139/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6763 : val tss = 0.3688 ::: train hss = 0.2568 : val hss = 0.1270
Fold 2: train tss = 0.6162 : val tss = 0.6337 ::: train hss = 0.2393 : val hss = 0.3768
Fold 3: train tss = 0.6409 : val tss = 0.0944 ::: train hss = 0.3422 : val hss = 0.0344
Fold 4: train tss = 0.4411 : val tss = 0.6395 ::: train hss = 0.2162 : val hss = 0.3253
mean cv TSS: 0.3473
mean cv HSS: 0.1727
140/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.3989 : val tss = 0.0000 ::: train hss = 0.4313 : val hss = 0.0000
Fold 1: train tss = 0.7772 : val tss = 0.2349 ::: train hss = 0.4832 : val hss = 0.0984
Fold 2: train tss = 0.5799 : val tss = 0.6627 ::: train hss = 0.3176 : val hss = 0.3798
Fold 3: train tss = 0.7932 : val tss = 0.0076 ::: train hss = 0.5121 : val hss = 0.0085
Fold 4: train tss = 0.7315 : val tss = 0.7570 ::: train hss = 0.3769 : val hss = 0.4355
mean cv TSS: 0.3324
mean cv HSS: 0.1844
141/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7737 : val tss = 0.2379 ::: train hss = 0.6286 : val hss = 0.1239
Fold 2: train tss = 0.4103 : val tss = 0.6258 ::: train hss = 0.3227 : val hss = 0.3960
Fold 3: train tss = 0.7126 : val tss = 0.0240 ::: train hss = 0.3778 : val hss = 0.0250
Fold 4: train tss = 0.5784 : val tss = 0.7943 ::: train hss = 0.3691 : val hss = 0.4885
mean cv TSS: 0.3364
mean cv HSS: 0.2067
142/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 2229793
Fold 0: train tss = 0.4474 : val tss = -0.0009 ::: train hss = 0.3580 : val hss = -0.0017
Fold 1: train tss = 0.8263 : val tss = 0.0527 ::: train hss = 0.7189 : val hss = 0.0315
Fold 2: train tss = 0.6995 : val tss = 0.4812 ::: train hss = 0.3284 : val hss = 0.3275
Fold 3: train tss = 0.7473 : val tss = 0.0041 ::: train hss = 0.4490 : val hss = 0.0040
Fold 4: train tss = 0.7175 : val tss = 0.5357 ::: train hss = 0.4210 : val hss = 0.4077
mean cv TSS: 0.2146
mean cv HSS: 0.1538
143/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.3976 : val tss = 0.0000 ::: train hss = 0.3313 : val hss = 0.0000
Fold 1: train tss = 0.7711 : val tss = 0.1574 ::: train hss = 0.6669 : val hss = 0.0804
Fold 2: train tss = 0.5955 : val tss = 0.6126 ::: train hss = 0.2969 : val hss = 0.3823
Fold 3: train tss = 0.5991 : val tss = 0.0892 ::: train hss = 0.3286 : val hss = 0.0228
Fold 4: train tss = 0.6612 : val tss = 0.6589 ::: train hss = 0.3289 : val hss = 0.3932
mean cv TSS: 0.3036
mean cv HSS: 0.1758
144/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7698 : val tss = 0.1066 ::: train hss = 0.5606 : val hss = 0.0895
Fold 2: train tss = 0.6543 : val tss = 0.5897 ::: train hss = 0.2208 : val hss = 0.3775
Fold 3: train tss = 0.7432 : val tss = 0.0579 ::: train hss = 0.4002 : val hss = 0.0169
Fold 4: train tss = 0.7178 : val tss = 0.6546 ::: train hss = 0.4252 : val hss = 0.2987
mean cv TSS: 0.2818
mean cv HSS: 0.1565
145/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5166 : val tss = 0.0684 ::: train hss = 0.3231 : val hss = 0.0185
Fold 4: train tss = 0.6091 : val tss = 0.7234 ::: train hss = 0.3123 : val hss = 0.3607
mean cv TSS: 0.1584
mean cv HSS: 0.0758
146/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7600 : val tss = 0.2921 ::: train hss = 0.4855 : val hss = 0.0949
Fold 2: train tss = 0.6517 : val tss = 0.6582 ::: train hss = 0.3733 : val hss = 0.3939
Fold 3: train tss = 0.7228 : val tss = 0.0498 ::: train hss = 0.4420 : val hss = 0.0295
Fold 4: train tss = 0.6716 : val tss = 0.6689 ::: train hss = 0.3672 : val hss = 0.4143
mean cv TSS: 0.3338
mean cv HSS: 0.1865
147/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7062 : val tss = 0.2845 ::: train hss = 0.5229 : val hss = 0.1015
Fold 2: train tss = 0.0035 : val tss = 0.1697 ::: train hss = 0.0070 : val hss = 0.1327
Fold 3: train tss = 0.6765 : val tss = 0.0307 ::: train hss = 0.3125 : val hss = 0.0179
Fold 4: train tss = 0.4550 : val tss = 0.5779 ::: train hss = 0.3671 : val hss = 0.3889
mean cv TSS: 0.2126
mean cv HSS: 0.1282
148/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7265 : val tss = 0.2820 ::: train hss = 0.6553 : val hss = 0.2132
Fold 2: train tss = 0.4821 : val tss = 0.6489 ::: train hss = 0.3514 : val hss = 0.3893
Fold 3: train tss = 0.7682 : val tss = 0.1506 ::: train hss = 0.4566 : val hss = 0.0322
Fold 4: train tss = 0.7236 : val tss = 0.5735 ::: train hss = 0.4548 : val hss = 0.3482
mean cv TSS: 0.3310
mean cv HSS: 0.1966
149/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6619 : val tss = 0.3025 ::: train hss = 0.5898 : val hss = 0.0585
Fold 2: train tss = 0.3676 : val tss = 0.6858 ::: train hss = 0.3134 : val hss = 0.3409
Fold 3: train tss = 0.6681 : val tss = 0.1219 ::: train hss = 0.4106 : val hss = 0.0191
Fold 4: train tss = 0.5454 : val tss = 0.6313 ::: train hss = 0.2244 : val hss = 0.3105
mean cv TSS: 0.3483
mean cv HSS: 0.1458
150/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7171 : val tss = 0.3437 ::: train hss = 0.5560 : val hss = 0.1180
Fold 2: train tss = 0.6265 : val tss = 0.6822 ::: train hss = 0.3692 : val hss = 0.3139
Fold 3: train tss = 0.7478 : val tss = 0.0901 ::: train hss = 0.4205 : val hss = 0.0278
Fold 4: train tss = 0.7031 : val tss = 0.6181 ::: train hss = 0.3923 : val hss = 0.3000
mean cv TSS: 0.3468
mean cv HSS: 0.1519
151/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6908 : val tss = 0.3675 ::: train hss = 0.5562 : val hss = 0.1594
Fold 2: train tss = 0.5805 : val tss = 0.6743 ::: train hss = 0.3462 : val hss = 0.3564
Fold 3: train tss = 0.7313 : val tss = 0.0609 ::: train hss = 0.4306 : val hss = 0.0265
Fold 4: train tss = 0.6764 : val tss = 0.7058 ::: train hss = 0.3720 : val hss = 0.2989
mean cv TSS: 0.3617
mean cv HSS: 0.1682
152/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7543 : val tss = 0.2475 ::: train hss = 0.5954 : val hss = 0.0990
Fold 2: train tss = 0.6461 : val tss = 0.6916 ::: train hss = 0.4151 : val hss = 0.3018
Fold 3: train tss = 0.7609 : val tss = 0.0392 ::: train hss = 0.4783 : val hss = 0.0278
Fold 4: train tss = 0.7212 : val tss = 0.5840 ::: train hss = 0.4245 : val hss = 0.3576
mean cv TSS: 0.3125
mean cv HSS: 0.1572
153/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7576 : val tss = 0.3189 ::: train hss = 0.5753 : val hss = 0.1079
Fold 2: train tss = 0.6435 : val tss = 0.6365 ::: train hss = 0.3978 : val hss = 0.2958
Fold 3: train tss = 0.7339 : val tss = 0.2301 ::: train hss = 0.4526 : val hss = 0.0607
Fold 4: train tss = 0.7197 : val tss = 0.5679 ::: train hss = 0.4140 : val hss = 0.3747
mean cv TSS: 0.3507
mean cv HSS: 0.1678
154/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7752 : val tss = 0.1728 ::: train hss = 0.6615 : val hss = 0.0547
Fold 2: train tss = 0.7281 : val tss = 0.7147 ::: train hss = 0.4420 : val hss = 0.4032
Fold 3: train tss = 0.7339 : val tss = 0.0478 ::: train hss = 0.5254 : val hss = 0.0229
Fold 4: train tss = 0.7666 : val tss = 0.6502 ::: train hss = 0.4495 : val hss = 0.3547
mean cv TSS: 0.3171
mean cv HSS: 0.1671
155/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7565 : val tss = 0.1671 ::: train hss = 0.6381 : val hss = 0.0566
Fold 2: train tss = 0.6236 : val tss = 0.7295 ::: train hss = 0.4613 : val hss = 0.3829
Fold 3: train tss = 0.7429 : val tss = -0.0062 ::: train hss = 0.4616 : val hss = -0.0020
Fold 4: train tss = 0.7284 : val tss = 0.7141 ::: train hss = 0.4380 : val hss = 0.3374
mean cv TSS: 0.3209
mean cv HSS: 0.1550
156/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3177 : val tss = 0.1771 ::: train hss = 0.1751 : val hss = 0.0498
Fold 2: train tss = 0.0000 : val tss = 0.4759 ::: train hss = 0.0000 : val hss = 0.2887
Fold 3: train tss = 0.7046 : val tss = 0.0622 ::: train hss = 0.2704 : val hss = 0.0213
Fold 4: train tss = 0.6168 : val tss = 0.6229 ::: train hss = 0.2632 : val hss = 0.2089
mean cv TSS: 0.2676
mean cv HSS: 0.1137
157/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5759 : val tss = 0.3305 ::: train hss = 0.1333 : val hss = 0.1158
Fold 2: train tss = 0.2097 : val tss = 0.2038 ::: train hss = 0.1222 : val hss = 0.2925
Fold 3: train tss = 0.3376 : val tss = 0.0479 ::: train hss = 0.1665 : val hss = 0.0228
Fold 4: train tss = 0.4089 : val tss = 0.6353 ::: train hss = 0.1872 : val hss = 0.1896
mean cv TSS: 0.2435
mean cv HSS: 0.1242
158/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7015 : val tss = 0.2223 ::: train hss = 0.5917 : val hss = 0.0854
Fold 2: train tss = 0.3707 : val tss = 0.5370 ::: train hss = 0.2025 : val hss = 0.3761
Fold 3: train tss = 0.5147 : val tss = 0.0418 ::: train hss = 0.2785 : val hss = 0.0254
Fold 4: train tss = 0.6239 : val tss = 0.6157 ::: train hss = 0.2229 : val hss = 0.2504
mean cv TSS: 0.2834
mean cv HSS: 0.1474
159/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5702 : val tss = 0.2952 ::: train hss = 0.2890 : val hss = 0.0852
Fold 2: train tss = 0.2586 : val tss = 0.4719 ::: train hss = 0.1689 : val hss = 0.3523
Fold 3: train tss = 0.3250 : val tss = 0.0444 ::: train hss = 0.1263 : val hss = 0.0365
Fold 4: train tss = 0.0009 : val tss = 0.7302 ::: train hss = 0.0015 : val hss = 0.3255
mean cv TSS: 0.3083
mean cv HSS: 0.1599
160/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7522 : val tss = 0.0279 ::: train hss = 0.2622 : val hss = 0.0097
Fold 2: train tss = -0.0152 : val tss = -0.0868 ::: train hss = -0.0125 : val hss = -0.0828
Fold 3: train tss = 0.5422 : val tss = 0.1006 ::: train hss = 0.1441 : val hss = 0.0208
Fold 4: train tss = 0.4244 : val tss = 0.6591 ::: train hss = 0.2016 : val hss = 0.2766
mean cv TSS: 0.1402
mean cv HSS: 0.0449
161/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0928 : val tss = 0.0000 ::: train hss = 0.0458 : val hss = 0.0000
Fold 1: train tss = 0.3163 : val tss = 0.0604 ::: train hss = 0.1872 : val hss = 0.0437
Fold 2: train tss = 0.2139 : val tss = 0.4425 ::: train hss = 0.2003 : val hss = 0.2975
Fold 3: train tss = 0.4512 : val tss = -0.0074 ::: train hss = 0.1902 : val hss = -0.0096
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0991
mean cv HSS: 0.0663
162/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.4049 : val tss = 0.3309 ::: train hss = 0.5128 : val hss = 0.0691
Fold 2: train tss = 0.6281 : val tss = 0.6720 ::: train hss = 0.4130 : val hss = 0.3926
Fold 3: train tss = 0.6886 : val tss = 0.0641 ::: train hss = 0.2440 : val hss = 0.0225
Fold 4: train tss = 0.7064 : val tss = 0.7165 ::: train hss = 0.4132 : val hss = 0.3603
mean cv TSS: 0.3567
mean cv HSS: 0.1689
163/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7607 : val tss = 0.2591 ::: train hss = 0.4930 : val hss = 0.1283
Fold 2: train tss = 0.3863 : val tss = 0.6019 ::: train hss = 0.2341 : val hss = 0.4056
Fold 3: train tss = 0.5424 : val tss = 0.1620 ::: train hss = 0.2686 : val hss = 0.0211
Fold 4: train tss = 0.5671 : val tss = 0.7241 ::: train hss = 0.2561 : val hss = 0.3347
mean cv TSS: 0.3494
mean cv HSS: 0.1780
164/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6107 : val tss = 0.3569 ::: train hss = 0.3672 : val hss = 0.1168
Fold 2: train tss = 0.6015 : val tss = 0.6967 ::: train hss = 0.4126 : val hss = 0.3966
Fold 3: train tss = 0.5170 : val tss = 0.0342 ::: train hss = 0.2808 : val hss = 0.0069
Fold 4: train tss = 0.7360 : val tss = 0.7201 ::: train hss = 0.4186 : val hss = 0.4273
mean cv TSS: 0.3616
mean cv HSS: 0.1895
165/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6928 : val tss = 0.2165 ::: train hss = 0.5923 : val hss = 0.1001
Fold 2: train tss = 0.4987 : val tss = 0.5475 ::: train hss = 0.1466 : val hss = 0.3421
Fold 3: train tss = 0.5797 : val tss = 0.0600 ::: train hss = 0.3000 : val hss = 0.0363
Fold 4: train tss = 0.4666 : val tss = 0.6863 ::: train hss = 0.2378 : val hss = 0.2831
mean cv TSS: 0.3021
mean cv HSS: 0.1523
166/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7892 : val tss = 0.1661 ::: train hss = 0.6773 : val hss = 0.0641
Fold 2: train tss = 0.3840 : val tss = 0.5618 ::: train hss = 0.2871 : val hss = 0.2887
Fold 3: train tss = 0.7418 : val tss = 0.1087 ::: train hss = 0.5011 : val hss = 0.0223
Fold 4: train tss = 0.7074 : val tss = 0.4171 ::: train hss = 0.3989 : val hss = 0.3721
mean cv TSS: 0.2507
mean cv HSS: 0.1494
167/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.3480 : val tss = 0.0000 ::: train hss = 0.3238 : val hss = 0.0000
Fold 1: train tss = 0.7900 : val tss = 0.1761 ::: train hss = 0.6062 : val hss = 0.0583
Fold 2: train tss = 0.6508 : val tss = 0.5809 ::: train hss = 0.4000 : val hss = 0.5824
Fold 3: train tss = 0.7219 : val tss = 0.0123 ::: train hss = 0.4318 : val hss = 0.0089
Fold 4: train tss = 0.4572 : val tss = 0.7022 ::: train hss = 0.2617 : val hss = 0.3076
mean cv TSS: 0.2943
mean cv HSS: 0.1914
168/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7304 : val tss = 0.2204 ::: train hss = 0.5595 : val hss = 0.1173
Fold 2: train tss = 0.6576 : val tss = 0.6188 ::: train hss = 0.3869 : val hss = 0.3854
Fold 3: train tss = 0.7757 : val tss = 0.0722 ::: train hss = 0.4128 : val hss = 0.0283
Fold 4: train tss = 0.7329 : val tss = 0.6177 ::: train hss = 0.3478 : val hss = 0.2823
mean cv TSS: 0.3058
mean cv HSS: 0.1627
169/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5592 : val tss = 0.1727 ::: train hss = 0.2948 : val hss = 0.0408
Fold 4: train tss = 0.4403 : val tss = 0.3982 ::: train hss = 0.3030 : val hss = 0.2917
mean cv TSS: 0.1142
mean cv HSS: 0.0665
170/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7724 : val tss = 0.1791 ::: train hss = 0.5343 : val hss = 0.0938
Fold 2: train tss = 0.3279 : val tss = 0.6021 ::: train hss = 0.2870 : val hss = 0.3571
Fold 3: train tss = 0.6406 : val tss = 0.2453 ::: train hss = 0.3390 : val hss = 0.0440
Fold 4: train tss = 0.6808 : val tss = 0.6965 ::: train hss = 0.3724 : val hss = 0.2527
mean cv TSS: 0.3446
mean cv HSS: 0.1495
171/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5904 : val tss = 0.3125 ::: train hss = 0.5600 : val hss = 0.0982
Fold 2: train tss = 0.5123 : val tss = 0.4513 ::: train hss = 0.2635 : val hss = 0.3664
Fold 3: train tss = 0.6921 : val tss = 0.1215 ::: train hss = 0.4119 : val hss = 0.0255
Fold 4: train tss = 0.5820 : val tss = 0.6851 ::: train hss = 0.3081 : val hss = 0.2418
mean cv TSS: 0.3141
mean cv HSS: 0.1464
172/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.3976 : val tss = -0.0059 ::: train hss = 0.3313 : val hss = -0.0095
Fold 1: train tss = 0.8222 : val tss = 0.2267 ::: train hss = 0.6331 : val hss = 0.1937
Fold 2: train tss = 0.3281 : val tss = 0.6858 ::: train hss = 0.2887 : val hss = 0.3226
Fold 3: train tss = 0.7401 : val tss = 0.3141 ::: train hss = 0.4521 : val hss = 0.0624
Fold 4: train tss = 0.7198 : val tss = 0.6955 ::: train hss = 0.4249 : val hss = 0.3004
mean cv TSS: 0.3832
mean cv HSS: 0.1739
173/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7304 : val tss = 0.2197 ::: train hss = 0.4967 : val hss = 0.0997
Fold 2: train tss = 0.3490 : val tss = 0.5941 ::: train hss = 0.2810 : val hss = 0.3701
Fold 3: train tss = 0.7035 : val tss = -0.0492 ::: train hss = 0.4174 : val hss = -0.0115
Fold 4: train tss = 0.6089 : val tss = 0.6578 ::: train hss = 0.2721 : val hss = 0.3279
mean cv TSS: 0.2845
mean cv HSS: 0.1572
174/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7161 : val tss = 0.2097 ::: train hss = 0.5401 : val hss = 0.0948
Fold 2: train tss = 0.5726 : val tss = 0.6640 ::: train hss = 0.3413 : val hss = 0.2829
Fold 3: train tss = 0.7561 : val tss = 0.0422 ::: train hss = 0.4417 : val hss = 0.0159
Fold 4: train tss = 0.7013 : val tss = 0.5921 ::: train hss = 0.3941 : val hss = 0.3123
mean cv TSS: 0.3016
mean cv HSS: 0.1412
175/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6954 : val tss = 0.3182 ::: train hss = 0.5599 : val hss = 0.1274
Fold 2: train tss = 0.6180 : val tss = 0.6797 ::: train hss = 0.3706 : val hss = 0.3204
Fold 3: train tss = 0.7379 : val tss = 0.0595 ::: train hss = 0.4158 : val hss = 0.0222
Fold 4: train tss = 0.6872 : val tss = 0.7242 ::: train hss = 0.3953 : val hss = 0.3408
mean cv TSS: 0.3563
mean cv HSS: 0.1621
176/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7493 : val tss = 0.3303 ::: train hss = 0.5830 : val hss = 0.1122
Fold 2: train tss = 0.6139 : val tss = 0.6992 ::: train hss = 0.4001 : val hss = 0.3319
Fold 3: train tss = 0.7131 : val tss = 0.1825 ::: train hss = 0.4082 : val hss = 0.0835
Fold 4: train tss = 0.7229 : val tss = 0.6777 ::: train hss = 0.4187 : val hss = 0.2938
mean cv TSS: 0.3779
mean cv HSS: 0.1643
177/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7630 : val tss = 0.3301 ::: train hss = 0.5938 : val hss = 0.1240
Fold 2: train tss = 0.6140 : val tss = 0.6622 ::: train hss = 0.3892 : val hss = 0.3330
Fold 3: train tss = 0.7519 : val tss = 0.0040 ::: train hss = 0.4817 : val hss = 0.0010
Fold 4: train tss = 0.7107 : val tss = 0.6682 ::: train hss = 0.4196 : val hss = 0.2775
mean cv TSS: 0.3329
mean cv HSS: 0.1471
178/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7711 : val tss = 0.1377 ::: train hss = 0.6669 : val hss = 0.0436
Fold 2: train tss = 0.6937 : val tss = 0.6799 ::: train hss = 0.4950 : val hss = 0.2915
Fold 3: train tss = 0.7936 : val tss = 0.0025 ::: train hss = 0.5100 : val hss = 0.0008
Fold 4: train tss = 0.7471 : val tss = 0.5694 ::: train hss = 0.4367 : val hss = 0.3796
mean cv TSS: 0.2779
mean cv HSS: 0.1431
179/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = -0.0005 ::: train hss = 0.0000 : val hss = -0.0010
Fold 1: train tss = 0.7611 : val tss = 0.1946 ::: train hss = 0.6433 : val hss = 0.0726
Fold 2: train tss = 0.5785 : val tss = 0.6708 ::: train hss = 0.4742 : val hss = 0.2717
Fold 3: train tss = 0.7869 : val tss = 0.0141 ::: train hss = 0.4483 : val hss = 0.0143
Fold 4: train tss = 0.7383 : val tss = 0.5529 ::: train hss = 0.4511 : val hss = 0.3660
mean cv TSS: 0.2864
mean cv HSS: 0.1447
180/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5727 : val tss = 0.2182 ::: train hss = 0.3711 : val hss = 0.0881
Fold 2: train tss = 0.3326 : val tss = 0.5108 ::: train hss = 0.1791 : val hss = 0.2556
Fold 3: train tss = 0.5610 : val tss = 0.2009 ::: train hss = 0.1555 : val hss = 0.0322
Fold 4: train tss = 0.6312 : val tss = 0.5904 ::: train hss = 0.2621 : val hss = 0.2464
mean cv TSS: 0.3041
mean cv HSS: 0.1245
181/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.2890 : val tss = 0.4705 ::: train hss = 0.1174 : val hss = 0.3235
Fold 3: train tss = 0.4200 : val tss = 0.0831 ::: train hss = 0.1730 : val hss = 0.0237
Fold 4: train tss = 0.3625 : val tss = 0.6465 ::: train hss = 0.1623 : val hss = 0.3460
mean cv TSS: 0.2400
mean cv HSS: 0.1386
182/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = -0.0021 : val tss = -0.0006 ::: train hss = -0.0022 : val hss = -0.0012
Fold 1: train tss = 0.3941 : val tss = 0.2356 ::: train hss = 0.1546 : val hss = 0.0775
Fold 2: train tss = 0.0176 : val tss = 0.0005 ::: train hss = 0.0297 : val hss = 0.0009
Fold 3: train tss = 0.4547 : val tss = 0.0341 ::: train hss = 0.2772 : val hss = 0.0370
Fold 4: train tss = 0.5548 : val tss = 0.7110 ::: train hss = 0.1131 : val hss = 0.2686
mean cv TSS: 0.1961
mean cv HSS: 0.0766
183/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = -0.0190 : val tss = -0.0033 ::: train hss = -0.0158 : val hss = -0.0055
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.3736 : val tss = 0.1581 ::: train hss = 0.1195 : val hss = 0.0246
Fold 4: train tss = 0.4227 : val tss = 0.5479 ::: train hss = 0.1452 : val hss = 0.2011
mean cv TSS: 0.1406
mean cv HSS: 0.0440
184/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.1735 : val tss = 0.0000 ::: train hss = 0.0288 : val hss = 0.0000
Fold 1: train tss = 0.6551 : val tss = -0.0444 ::: train hss = 0.0989 : val hss = -0.0087
Fold 2: train tss = 0.2553 : val tss = 0.3824 ::: train hss = 0.1430 : val hss = 0.1836
Fold 3: train tss = 0.4388 : val tss = 0.0700 ::: train hss = 0.2101 : val hss = 0.0238
Fold 4: train tss = 0.4586 : val tss = 0.6752 ::: train hss = 0.2110 : val hss = 0.3394
mean cv TSS: 0.2166
mean cv HSS: 0.1076
185/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = -0.0011 : val tss = 0.0000 ::: train hss = -0.0015 : val hss = 0.0000
Fold 1: train tss = 0.5475 : val tss = 0.0468 ::: train hss = 0.1839 : val hss = 0.0078
Fold 2: train tss = 0.0358 : val tss = 0.1342 ::: train hss = 0.0501 : val hss = 0.1872
Fold 3: train tss = 0.5101 : val tss = 0.0887 ::: train hss = 0.2049 : val hss = 0.0226
Fold 4: train tss = 0.4253 : val tss = 0.6938 ::: train hss = 0.1935 : val hss = 0.3206
mean cv TSS: 0.1927
mean cv HSS: 0.1076
186/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7208 : val tss = 0.1990 ::: train hss = 0.6272 : val hss = 0.1112
Fold 2: train tss = 0.6029 : val tss = 0.6950 ::: train hss = 0.3854 : val hss = 0.3514
Fold 3: train tss = 0.7278 : val tss = 0.0599 ::: train hss = 0.5079 : val hss = 0.0137
Fold 4: train tss = 0.6973 : val tss = 0.6946 ::: train hss = 0.3987 : val hss = 0.4386
mean cv TSS: 0.3297
mean cv HSS: 0.1830
187/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6932 : val tss = 0.2983 ::: train hss = 0.4163 : val hss = 0.1274
Fold 2: train tss = 0.4516 : val tss = 0.6327 ::: train hss = 0.2696 : val hss = 0.4020
Fold 3: train tss = 0.5657 : val tss = 0.1145 ::: train hss = 0.2324 : val hss = 0.0428
Fold 4: train tss = 0.4973 : val tss = 0.6773 ::: train hss = 0.1938 : val hss = 0.2528
mean cv TSS: 0.3446
mean cv HSS: 0.1650
188/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.1985 : val tss = -0.0113 ::: train hss = 0.2206 : val hss = -0.0155
Fold 1: train tss = 0.7601 : val tss = 0.1440 ::: train hss = 0.7225 : val hss = 0.0792
Fold 2: train tss = 0.6290 : val tss = 0.6910 ::: train hss = 0.4467 : val hss = 0.4033
Fold 3: train tss = 0.6638 : val tss = 0.1063 ::: train hss = 0.4977 : val hss = 0.0267
Fold 4: train tss = 0.6745 : val tss = 0.7379 ::: train hss = 0.3876 : val hss = 0.3593
mean cv TSS: 0.3336
mean cv HSS: 0.1706
189/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7767 : val tss = 0.3115 ::: train hss = 0.4775 : val hss = 0.1252
Fold 2: train tss = 0.5591 : val tss = 0.5525 ::: train hss = 0.2371 : val hss = 0.3769
Fold 3: train tss = 0.6473 : val tss = 0.0286 ::: train hss = 0.2745 : val hss = 0.0195
Fold 4: train tss = 0.5549 : val tss = 0.6579 ::: train hss = 0.2352 : val hss = 0.3703
mean cv TSS: 0.3101
mean cv HSS: 0.1784
190/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.3968 : val tss = -0.0054 ::: train hss = 0.2939 : val hss = -0.0088
Fold 1: train tss = 0.7597 : val tss = 0.1787 ::: train hss = 0.7130 : val hss = 0.0873
Fold 2: train tss = 0.6691 : val tss = 0.5425 ::: train hss = 0.3037 : val hss = 0.3182
Fold 3: train tss = 0.7175 : val tss = 0.0146 ::: train hss = 0.4624 : val hss = 0.0074
Fold 4: train tss = 0.7046 : val tss = 0.6197 ::: train hss = 0.4117 : val hss = 0.3645
mean cv TSS: 0.2700
mean cv HSS: 0.1537
191/768
{'batch_size': 3584, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.3473 : val tss = -0.0030 ::: train hss = 0.2835 : val hss = -0.0054
Fold 1: train tss = 0.7693 : val tss = 0.1637 ::: train hss = 0.7312 : val hss = 0.0728
Fold 2: train tss = 0.5093 : val tss = 0.5992 ::: train hss = 0.3090 : val hss = 0.3150
Fold 3: train tss = 0.6532 : val tss = 0.0090 ::: train hss = 0.3316 : val hss = 0.0060
Fold 4: train tss = 0.4625 : val tss = 0.5533 ::: train hss = 0.1930 : val hss = 0.2469
mean cv TSS: 0.2644
mean cv HSS: 0.1271
192/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.7844 : val tss = -0.0434 ::: train hss = 0.1902 : val hss = -0.0258
Fold 1: train tss = 0.7820 : val tss = 0.1935 ::: train hss = 0.5460 : val hss = 0.1189
Fold 2: train tss = 0.7418 : val tss = 0.7143 ::: train hss = 0.2386 : val hss = 0.3137
Fold 3: train tss = 0.7744 : val tss = 0.0428 ::: train hss = 0.2984 : val hss = 0.0117
Fold 4: train tss = 0.7752 : val tss = 0.6402 ::: train hss = 0.2947 : val hss = 0.2196
mean cv TSS: 0.3095
mean cv HSS: 0.1276
193/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.1000 : val tss = 0.0000 ::: train hss = 0.1818 : val hss = 0.0000
Fold 1: train tss = 0.8666 : val tss = 0.0796 ::: train hss = 0.2833 : val hss = 0.0306
Fold 2: train tss = 0.7230 : val tss = 0.6689 ::: train hss = 0.1914 : val hss = 0.2652
Fold 3: train tss = 0.7603 : val tss = 0.2908 ::: train hss = 0.2506 : val hss = 0.0633
Fold 4: train tss = 0.6483 : val tss = 0.6415 ::: train hss = 0.1574 : val hss = 0.2055
mean cv TSS: 0.3362
mean cv HSS: 0.1129
194/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.8845 : val tss = -0.0014 ::: train hss = 0.2131 : val hss = -0.0026
Fold 1: train tss = 0.7347 : val tss = 0.3183 ::: train hss = 0.2438 : val hss = 0.1110
Fold 2: train tss = 0.7353 : val tss = 0.7139 ::: train hss = 0.2321 : val hss = 0.3587
Fold 3: train tss = 0.7460 : val tss = 0.2528 ::: train hss = 0.2297 : val hss = 0.0545
Fold 4: train tss = 0.6749 : val tss = 0.5031 ::: train hss = 0.1897 : val hss = 0.1205
mean cv TSS: 0.3573
mean cv HSS: 0.1284
195/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.6933 : val tss = 0.0000 ::: train hss = 0.3116 : val hss = 0.0000
Fold 1: train tss = 0.8017 : val tss = 0.2896 ::: train hss = 0.5165 : val hss = 0.1396
Fold 2: train tss = 0.5951 : val tss = 0.6280 ::: train hss = 0.1123 : val hss = 0.2694
Fold 3: train tss = 0.7551 : val tss = 0.3923 ::: train hss = 0.2473 : val hss = 0.0496
Fold 4: train tss = 0.7202 : val tss = 0.5878 ::: train hss = 0.2034 : val hss = 0.1876
mean cv TSS: 0.3795
mean cv HSS: 0.1292
196/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.5435 : val tss = -0.0006 ::: train hss = 0.2588 : val hss = -0.0012
Fold 1: train tss = 0.8458 : val tss = 0.2103 ::: train hss = 0.4332 : val hss = 0.0904
Fold 2: train tss = 0.7062 : val tss = 0.5121 ::: train hss = 0.1311 : val hss = 0.2926
Fold 3: train tss = 0.6713 : val tss = 0.1151 ::: train hss = 0.1658 : val hss = 0.0165
Fold 4: train tss = 0.7904 : val tss = 0.3359 ::: train hss = 0.3078 : val hss = 0.1760
mean cv TSS: 0.2346
mean cv HSS: 0.1149
197/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 248673
Fold 0: train tss = 0.4945 : val tss = -0.0093 ::: train hss = 0.2637 : val hss = -0.0118
Fold 1: train tss = 0.7896 : val tss = 0.1570 ::: train hss = 0.4768 : val hss = 0.0486
Fold 2: train tss = 0.7405 : val tss = 0.6559 ::: train hss = 0.1965 : val hss = 0.2677
Fold 3: train tss = 0.7717 : val tss = 0.1651 ::: train hss = 0.2809 : val hss = 0.0231
Fold 4: train tss = 0.7051 : val tss = 0.5597 ::: train hss = 0.1844 : val hss = 0.1747
mean cv TSS: 0.3057
mean cv HSS: 0.1005
198/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8338 : val tss = 0.1768 ::: train hss = 0.4843 : val hss = 0.1430
Fold 2: train tss = 0.6479 : val tss = 0.6249 ::: train hss = 0.1034 : val hss = 0.2184
Fold 3: train tss = 0.7937 : val tss = 0.0498 ::: train hss = 0.2997 : val hss = 0.0184
Fold 4: train tss = 0.7759 : val tss = 0.6693 ::: train hss = 0.2517 : val hss = 0.2631
mean cv TSS: 0.3041
mean cv HSS: 0.1286
199/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8012 : val tss = 0.2046 ::: train hss = 0.3849 : val hss = 0.1163
Fold 2: train tss = 0.7010 : val tss = 0.6861 ::: train hss = 0.1600 : val hss = 0.2972
Fold 3: train tss = 0.6803 : val tss = 0.2603 ::: train hss = 0.1805 : val hss = 0.0430
Fold 4: train tss = 0.7067 : val tss = 0.6254 ::: train hss = 0.1956 : val hss = 0.1937
mean cv TSS: 0.3553
mean cv HSS: 0.1300
200/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.3455 : val tss = -0.0237 ::: train hss = 0.2159 : val hss = -0.0243
Fold 1: train tss = 0.7767 : val tss = 0.1218 ::: train hss = 0.6034 : val hss = 0.0488
Fold 2: train tss = 0.6079 : val tss = 0.6304 ::: train hss = 0.1061 : val hss = 0.2117
Fold 3: train tss = 0.7530 : val tss = 0.2487 ::: train hss = 0.2268 : val hss = 0.0406
Fold 4: train tss = 0.7791 : val tss = 0.7023 ::: train hss = 0.2746 : val hss = 0.2670
mean cv TSS: 0.3359
mean cv HSS: 0.1087
201/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7773 : val tss = 0.2599 ::: train hss = 0.4846 : val hss = 0.0942
Fold 2: train tss = 0.7133 : val tss = 0.6223 ::: train hss = 0.2379 : val hss = 0.2429
Fold 3: train tss = 0.7704 : val tss = 0.0725 ::: train hss = 0.2809 : val hss = 0.0226
Fold 4: train tss = 0.7071 : val tss = 0.6253 ::: train hss = 0.1870 : val hss = 0.2916
mean cv TSS: 0.3160
mean cv HSS: 0.1303
202/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.3962 : val tss = -0.0046 ::: train hss = 0.2686 : val hss = -0.0078
Fold 1: train tss = 0.8967 : val tss = 0.1763 ::: train hss = 0.4630 : val hss = 0.0932
Fold 2: train tss = 0.6762 : val tss = 0.5172 ::: train hss = 0.2016 : val hss = 0.1836
Fold 3: train tss = 0.8043 : val tss = 0.0852 ::: train hss = 0.3464 : val hss = 0.0168
Fold 4: train tss = 0.6537 : val tss = 0.5743 ::: train hss = 0.1402 : val hss = 0.2999
mean cv TSS: 0.2697
mean cv HSS: 0.1171
203/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.3965 : val tss = -0.0040 ::: train hss = 0.2782 : val hss = -0.0069
Fold 1: train tss = 0.8570 : val tss = 0.1806 ::: train hss = 0.5571 : val hss = 0.0893
Fold 2: train tss = 0.5203 : val tss = 0.4281 ::: train hss = 0.0998 : val hss = 0.2095
Fold 3: train tss = 0.8057 : val tss = 0.0691 ::: train hss = 0.2932 : val hss = 0.0420
Fold 4: train tss = 0.7330 : val tss = 0.5580 ::: train hss = 0.2202 : val hss = 0.1998
mean cv TSS: 0.2464
mean cv HSS: 0.1068
204/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8109 : val tss = 0.1433 ::: train hss = 0.1975 : val hss = 0.0454
Fold 2: train tss = 0.4344 : val tss = 0.5026 ::: train hss = 0.0928 : val hss = 0.1415
Fold 3: train tss = 0.6257 : val tss = 0.5086 ::: train hss = 0.1175 : val hss = 0.0726
Fold 4: train tss = 0.6732 : val tss = 0.6240 ::: train hss = 0.1876 : val hss = 0.2577
mean cv TSS: 0.3557
mean cv HSS: 0.1034
205/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6177 : val tss = 0.4080 ::: train hss = 0.0752 : val hss = 0.1102
Fold 2: train tss = 0.3151 : val tss = 0.5627 ::: train hss = 0.0563 : val hss = 0.1908
Fold 3: train tss = 0.6045 : val tss = 0.2584 ::: train hss = 0.1313 : val hss = 0.0446
Fold 4: train tss = 0.5214 : val tss = 0.5638 ::: train hss = 0.0851 : val hss = 0.1501
mean cv TSS: 0.3586
mean cv HSS: 0.0992
206/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.1458 : val tss = -0.0225 ::: train hss = 0.1005 : val hss = -0.0237
Fold 1: train tss = 0.7825 : val tss = 0.2356 ::: train hss = 0.3217 : val hss = 0.0918
Fold 2: train tss = 0.6956 : val tss = 0.5679 ::: train hss = 0.1140 : val hss = 0.2007
Fold 3: train tss = 0.6892 : val tss = 0.1104 ::: train hss = 0.1584 : val hss = 0.0288
Fold 4: train tss = 0.6210 : val tss = 0.6940 ::: train hss = 0.1243 : val hss = 0.2491
mean cv TSS: 0.3171
mean cv HSS: 0.1094
207/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6441 : val tss = 0.1606 ::: train hss = 0.1098 : val hss = 0.0334
Fold 2: train tss = 0.5651 : val tss = 0.6586 ::: train hss = 0.0857 : val hss = 0.3066
Fold 3: train tss = 0.5733 : val tss = 0.2396 ::: train hss = 0.1326 : val hss = 0.0272
Fold 4: train tss = 0.5727 : val tss = 0.5846 ::: train hss = 0.1140 : val hss = 0.1698
mean cv TSS: 0.3287
mean cv HSS: 0.1074
208/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 248673
Fold 0: train tss = 0.4944 : val tss = 0.0006 ::: train hss = 0.2602 : val hss = 0.0010
Fold 1: train tss = 0.7845 : val tss = 0.1282 ::: train hss = 0.2914 : val hss = 0.0276
Fold 2: train tss = 0.6440 : val tss = 0.6410 ::: train hss = 0.0936 : val hss = 0.2661
Fold 3: train tss = 0.5807 : val tss = 0.0265 ::: train hss = 0.0979 : val hss = 0.0017
Fold 4: train tss = 0.6161 : val tss = 0.6267 ::: train hss = 0.1196 : val hss = 0.1917
mean cv TSS: 0.2846
mean cv HSS: 0.0976
209/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.4398 : val tss = -0.0076 ::: train hss = 0.1557 : val hss = -0.0117
Fold 1: train tss = 0.6896 : val tss = 0.0138 ::: train hss = 0.1144 : val hss = 0.0028
Fold 2: train tss = 0.6337 : val tss = 0.5167 ::: train hss = 0.0913 : val hss = 0.1382
Fold 3: train tss = 0.5968 : val tss = 0.0803 ::: train hss = 0.1208 : val hss = 0.0081
Fold 4: train tss = 0.4830 : val tss = 0.4583 ::: train hss = 0.0653 : val hss = 0.1048
mean cv TSS: 0.2123
mean cv HSS: 0.0484
210/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.6860 : val tss = -0.0209 ::: train hss = 0.1829 : val hss = -0.0227
Fold 1: train tss = 0.7771 : val tss = 0.1777 ::: train hss = 0.2946 : val hss = 0.1018
Fold 2: train tss = 0.7187 : val tss = 0.5868 ::: train hss = 0.2317 : val hss = 0.1830
Fold 3: train tss = 0.7152 : val tss = 0.2245 ::: train hss = 0.2070 : val hss = 0.0291
Fold 4: train tss = 0.7370 : val tss = 0.6952 ::: train hss = 0.2139 : val hss = 0.2828
mean cv TSS: 0.3327
mean cv HSS: 0.1148
211/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7307 : val tss = 0.3797 ::: train hss = 0.3403 : val hss = 0.1426
Fold 2: train tss = 0.4903 : val tss = 0.5737 ::: train hss = 0.0741 : val hss = 0.1969
Fold 3: train tss = 0.4896 : val tss = 0.1099 ::: train hss = 0.0758 : val hss = 0.0107
Fold 4: train tss = 0.5396 : val tss = 0.5529 ::: train hss = 0.0920 : val hss = 0.1416
mean cv TSS: 0.3232
mean cv HSS: 0.0984
212/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.7398 : val tss = -0.0139 ::: train hss = 0.2487 : val hss = -0.0178
Fold 1: train tss = 0.6781 : val tss = 0.2935 ::: train hss = 0.1206 : val hss = 0.0468
Fold 2: train tss = 0.7769 : val tss = 0.6419 ::: train hss = 0.3090 : val hss = 0.2527
Fold 3: train tss = 0.6135 : val tss = 0.0756 ::: train hss = 0.1234 : val hss = 0.0148
Fold 4: train tss = 0.7453 : val tss = 0.6376 ::: train hss = 0.2191 : val hss = 0.2099
mean cv TSS: 0.3269
mean cv HSS: 0.1013
213/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.5439 : val tss = -0.0097 ::: train hss = 0.2686 : val hss = -0.0139
Fold 1: train tss = 0.6299 : val tss = 0.2508 ::: train hss = 0.2943 : val hss = 0.0506
Fold 2: train tss = 0.4384 : val tss = 0.5585 ::: train hss = 0.1138 : val hss = 0.2811
Fold 3: train tss = 0.6223 : val tss = 0.3882 ::: train hss = 0.1299 : val hss = 0.0579
Fold 4: train tss = 0.6031 : val tss = 0.5711 ::: train hss = 0.1422 : val hss = 0.1551
mean cv TSS: 0.3518
mean cv HSS: 0.1061
214/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.9919 : val tss = -0.0050 ::: train hss = 0.3743 : val hss = -0.0083
Fold 1: train tss = 0.7964 : val tss = 0.1648 ::: train hss = 0.5058 : val hss = 0.0787
Fold 2: train tss = 0.7133 : val tss = 0.6278 ::: train hss = 0.3151 : val hss = 0.2358
Fold 3: train tss = 0.7722 : val tss = 0.3781 ::: train hss = 0.3728 : val hss = 0.0419
Fold 4: train tss = 0.7628 : val tss = 0.4792 ::: train hss = 0.2356 : val hss = 0.1770
mean cv TSS: 0.3290
mean cv HSS: 0.1050
215/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.7423 : val tss = -0.0067 ::: train hss = 0.3030 : val hss = -0.0106
Fold 1: train tss = 0.7733 : val tss = 0.1903 ::: train hss = 0.2795 : val hss = 0.1217
Fold 2: train tss = 0.5169 : val tss = 0.5416 ::: train hss = 0.1089 : val hss = 0.2583
Fold 3: train tss = 0.6411 : val tss = 0.1437 ::: train hss = 0.1654 : val hss = 0.0313
Fold 4: train tss = 0.5635 : val tss = 0.4637 ::: train hss = 0.1001 : val hss = 0.1078
mean cv TSS: 0.2665
mean cv HSS: 0.1017
216/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.2448 : val tss = -0.0016 ::: train hss = 0.1440 : val hss = -0.0030
Fold 1: train tss = 0.6825 : val tss = 0.2644 ::: train hss = 0.2653 : val hss = 0.0961
Fold 2: train tss = 0.6443 : val tss = 0.6011 ::: train hss = 0.1855 : val hss = 0.1995
Fold 3: train tss = 0.7727 : val tss = 0.0550 ::: train hss = 0.2768 : val hss = 0.0105
Fold 4: train tss = 0.6681 : val tss = 0.5259 ::: train hss = 0.1589 : val hss = 0.1311
mean cv TSS: 0.2890
mean cv HSS: 0.0869
217/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7824 : val tss = 0.2791 ::: train hss = 0.4934 : val hss = 0.0952
Fold 2: train tss = 0.6284 : val tss = 0.6820 ::: train hss = 0.1579 : val hss = 0.2601
Fold 3: train tss = 0.7299 : val tss = 0.1181 ::: train hss = 0.2259 : val hss = 0.0189
Fold 4: train tss = 0.7157 : val tss = 0.6520 ::: train hss = 0.1958 : val hss = 0.2155
mean cv TSS: 0.3462
mean cv HSS: 0.1179
218/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.8864 : val tss = -0.0166 ::: train hss = 0.2364 : val hss = -0.0199
Fold 1: train tss = 0.8131 : val tss = 0.1293 ::: train hss = 0.4112 : val hss = 0.0551
Fold 2: train tss = 0.6200 : val tss = 0.3837 ::: train hss = 0.1353 : val hss = 0.0856
Fold 3: train tss = 0.8004 : val tss = 0.3350 ::: train hss = 0.2742 : val hss = 0.1278
Fold 4: train tss = 0.7538 : val tss = 0.6158 ::: train hss = 0.2420 : val hss = 0.2938
mean cv TSS: 0.2894
mean cv HSS: 0.1085
219/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 372577
Fold 0: train tss = 0.7853 : val tss = -0.0141 ::: train hss = 0.2001 : val hss = -0.0180
Fold 1: train tss = 0.8115 : val tss = 0.1856 ::: train hss = 0.4342 : val hss = 0.0747
Fold 2: train tss = 0.6760 : val tss = 0.7007 ::: train hss = 0.1651 : val hss = 0.3306
Fold 3: train tss = 0.7046 : val tss = 0.2268 ::: train hss = 0.1907 : val hss = 0.0362
Fold 4: train tss = 0.6925 : val tss = 0.6017 ::: train hss = 0.1827 : val hss = 0.2082
mean cv TSS: 0.3401
mean cv HSS: 0.1263
220/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.8438 : val tss = -0.0052 ::: train hss = 0.3835 : val hss = -0.0087
Fold 1: train tss = 0.9423 : val tss = 0.1212 ::: train hss = 0.4843 : val hss = 0.0697
Fold 2: train tss = 0.6738 : val tss = 0.7704 ::: train hss = 0.1397 : val hss = 0.4434
Fold 3: train tss = 0.8394 : val tss = -0.0320 ::: train hss = 0.3202 : val hss = -0.0056
Fold 4: train tss = 0.7519 : val tss = 0.5578 ::: train hss = 0.2303 : val hss = 0.2363
mean cv TSS: 0.2824
mean cv HSS: 0.1470
221/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.4922 : val tss = -0.0235 ::: train hss = 0.2094 : val hss = -0.0242
Fold 1: train tss = 0.8001 : val tss = 0.2293 ::: train hss = 0.4505 : val hss = 0.1035
Fold 2: train tss = 0.6551 : val tss = 0.7119 ::: train hss = 0.1590 : val hss = 0.3205
Fold 3: train tss = 0.6965 : val tss = 0.1455 ::: train hss = 0.1638 : val hss = 0.0248
Fold 4: train tss = 0.6861 : val tss = 0.5177 ::: train hss = 0.1746 : val hss = 0.2039
mean cv TSS: 0.3162
mean cv HSS: 0.1257
222/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.2954 : val tss = 0.0005 ::: train hss = 0.1846 : val hss = 0.0009
Fold 1: train tss = 0.8044 : val tss = 0.1711 ::: train hss = 0.4101 : val hss = 0.0648
Fold 2: train tss = 0.6827 : val tss = 0.6939 ::: train hss = 0.2221 : val hss = 0.3419
Fold 3: train tss = 0.7563 : val tss = 0.3360 ::: train hss = 0.2386 : val hss = 0.0854
Fold 4: train tss = 0.6797 : val tss = 0.5774 ::: train hss = 0.1528 : val hss = 0.2601
mean cv TSS: 0.3558
mean cv HSS: 0.1506
223/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.2487 : val tss = 0.0000 ::: train hss = 0.2763 : val hss = 0.0000
Fold 1: train tss = 0.7922 : val tss = 0.2255 ::: train hss = 0.5060 : val hss = 0.1156
Fold 2: train tss = 0.7000 : val tss = 0.6628 ::: train hss = 0.1589 : val hss = 0.2774
Fold 3: train tss = 0.7547 : val tss = 0.0968 ::: train hss = 0.2623 : val hss = 0.0131
Fold 4: train tss = 0.7254 : val tss = 0.7026 ::: train hss = 0.2066 : val hss = 0.2605
mean cv TSS: 0.3375
mean cv HSS: 0.1333
224/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.3455 : val tss = -0.0030 ::: train hss = 0.2159 : val hss = -0.0053
Fold 1: train tss = 0.7892 : val tss = 0.1558 ::: train hss = 0.3915 : val hss = 0.0996
Fold 2: train tss = 0.7065 : val tss = 0.6439 ::: train hss = 0.1419 : val hss = 0.2669
Fold 3: train tss = 0.6302 : val tss = 0.1304 ::: train hss = 0.1402 : val hss = 0.0213
Fold 4: train tss = 0.7556 : val tss = 0.5008 ::: train hss = 0.2287 : val hss = 0.2261
mean cv TSS: 0.2856
mean cv HSS: 0.1217
225/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.3452 : val tss = -0.0254 ::: train hss = 0.2061 : val hss = -0.0251
Fold 1: train tss = 0.8280 : val tss = 0.2068 ::: train hss = 0.5800 : val hss = 0.0982
Fold 2: train tss = 0.6411 : val tss = 0.5952 ::: train hss = 0.1369 : val hss = 0.2751
Fold 3: train tss = 0.6603 : val tss = 0.4432 ::: train hss = 0.1742 : val hss = 0.0441
Fold 4: train tss = 0.7326 : val tss = 0.6742 ::: train hss = 0.1893 : val hss = 0.2626
mean cv TSS: 0.3788
mean cv HSS: 0.1310
226/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.6951 : val tss = -0.0035 ::: train hss = 0.3757 : val hss = -0.0061
Fold 1: train tss = 0.8782 : val tss = 0.2072 ::: train hss = 0.5483 : val hss = 0.0970
Fold 2: train tss = 0.8079 : val tss = 0.6179 ::: train hss = 0.3832 : val hss = 0.3700
Fold 3: train tss = 0.8331 : val tss = 0.2534 ::: train hss = 0.3882 : val hss = 0.0320
Fold 4: train tss = 0.7737 : val tss = 0.5452 ::: train hss = 0.2711 : val hss = 0.3464
mean cv TSS: 0.3240
mean cv HSS: 0.1679
227/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.3967 : val tss = -0.0035 ::: train hss = 0.2885 : val hss = -0.0061
Fold 1: train tss = 0.8406 : val tss = 0.2158 ::: train hss = 0.5734 : val hss = 0.1094
Fold 2: train tss = 0.7904 : val tss = 0.7357 ::: train hss = 0.2404 : val hss = 0.4549
Fold 3: train tss = 0.7270 : val tss = 0.1713 ::: train hss = 0.2173 : val hss = 0.0140
Fold 4: train tss = 0.7369 : val tss = 0.5682 ::: train hss = 0.2346 : val hss = 0.3257
mean cv TSS: 0.3375
mean cv HSS: 0.1796
228/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.3373 : val tss = -0.0355 ::: train hss = 0.1022 : val hss = -0.0233
Fold 1: train tss = 0.7767 : val tss = 0.2866 ::: train hss = 0.2595 : val hss = 0.1047
Fold 2: train tss = 0.5895 : val tss = 0.5130 ::: train hss = 0.0683 : val hss = 0.1254
Fold 3: train tss = 0.5478 : val tss = 0.1128 ::: train hss = 0.0874 : val hss = 0.0139
Fold 4: train tss = 0.7115 : val tss = 0.6305 ::: train hss = 0.1889 : val hss = 0.2080
mean cv TSS: 0.3015
mean cv HSS: 0.0857
229/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7884 : val tss = 0.1740 ::: train hss = 0.2433 : val hss = 0.0783
Fold 2: train tss = 0.4735 : val tss = 0.5477 ::: train hss = 0.0505 : val hss = 0.1937
Fold 3: train tss = 0.5226 : val tss = 0.0877 ::: train hss = 0.0932 : val hss = 0.0082
Fold 4: train tss = 0.6048 : val tss = 0.4783 ::: train hss = 0.1089 : val hss = 0.2017
mean cv TSS: 0.2575
mean cv HSS: 0.0964
230/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 372577
Fold 0: train tss = 0.6852 : val tss = -0.0136 ::: train hss = 0.1757 : val hss = -0.0176
Fold 1: train tss = 0.6860 : val tss = 0.2218 ::: train hss = 0.0871 : val hss = 0.0434
Fold 2: train tss = 0.6035 : val tss = 0.6083 ::: train hss = 0.0844 : val hss = 0.2047
Fold 3: train tss = 0.6439 : val tss = 0.2015 ::: train hss = 0.1275 : val hss = 0.0256
Fold 4: train tss = 0.6834 : val tss = 0.4951 ::: train hss = 0.1471 : val hss = 0.1583
mean cv TSS: 0.3026
mean cv HSS: 0.0829
231/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.1922 : val tss = -0.0079 ::: train hss = 0.0874 : val hss = -0.0104
Fold 1: train tss = 0.6178 : val tss = 0.1812 ::: train hss = 0.5848 : val hss = 0.0534
Fold 2: train tss = 0.5648 : val tss = 0.5070 ::: train hss = 0.0893 : val hss = 0.1292
Fold 3: train tss = 0.5385 : val tss = 0.4579 ::: train hss = 0.0938 : val hss = 0.0276
Fold 4: train tss = 0.5709 : val tss = 0.5915 ::: train hss = 0.1115 : val hss = 0.1656
mean cv TSS: 0.3459
mean cv HSS: 0.0731
232/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.7422 : val tss = -0.0091 ::: train hss = 0.2999 : val hss = -0.0134
Fold 1: train tss = 0.7323 : val tss = 0.0212 ::: train hss = 0.1645 : val hss = 0.0048
Fold 2: train tss = 0.6318 : val tss = 0.5481 ::: train hss = 0.0899 : val hss = 0.1643
Fold 3: train tss = 0.5756 : val tss = 0.3611 ::: train hss = 0.0991 : val hss = 0.0374
Fold 4: train tss = 0.6064 : val tss = 0.4492 ::: train hss = 0.1111 : val hss = 0.1060
mean cv TSS: 0.2741
mean cv HSS: 0.0598
233/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.6372 : val tss = -0.0241 ::: train hss = 0.0464 : val hss = -0.0223
Fold 1: train tss = 0.7039 : val tss = 0.0684 ::: train hss = 0.1139 : val hss = 0.0140
Fold 2: train tss = 0.5440 : val tss = 0.3119 ::: train hss = 0.0727 : val hss = 0.0610
Fold 3: train tss = 0.5809 : val tss = 0.0580 ::: train hss = 0.1021 : val hss = 0.0037
Fold 4: train tss = 0.5460 : val tss = 0.4803 ::: train hss = 0.0828 : val hss = 0.1379
mean cv TSS: 0.1789
mean cv HSS: 0.0389
234/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.6842 : val tss = -0.0201 ::: train hss = 0.1659 : val hss = -0.0199
Fold 1: train tss = 0.7530 : val tss = 0.2935 ::: train hss = 0.4547 : val hss = 0.1297
Fold 2: train tss = 0.4605 : val tss = 0.5103 ::: train hss = 0.0787 : val hss = 0.2009
Fold 3: train tss = 0.7579 : val tss = 0.1819 ::: train hss = 0.2689 : val hss = 0.0326
Fold 4: train tss = 0.7260 : val tss = 0.6006 ::: train hss = 0.1741 : val hss = 0.2352
mean cv TSS: 0.3133
mean cv HSS: 0.1157
235/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.7906 : val tss = -0.0027 ::: train hss = 0.2774 : val hss = -0.0049
Fold 1: train tss = 0.7515 : val tss = 0.3536 ::: train hss = 0.2587 : val hss = 0.1392
Fold 2: train tss = 0.5607 : val tss = 0.6235 ::: train hss = 0.1268 : val hss = 0.2714
Fold 3: train tss = 0.6122 : val tss = 0.0263 ::: train hss = 0.1647 : val hss = 0.0074
Fold 4: train tss = 0.5712 : val tss = 0.5157 ::: train hss = 0.1062 : val hss = 0.1256
mean cv TSS: 0.3033
mean cv HSS: 0.1077
236/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.8908 : val tss = -0.0282 ::: train hss = 0.3126 : val hss = -0.0265
Fold 1: train tss = 0.7901 : val tss = 0.0510 ::: train hss = 0.4817 : val hss = 0.0263
Fold 2: train tss = 0.7468 : val tss = 0.5996 ::: train hss = 0.1370 : val hss = 0.2108
Fold 3: train tss = 0.5422 : val tss = 0.2581 ::: train hss = 0.1050 : val hss = 0.0163
Fold 4: train tss = 0.7069 : val tss = 0.6336 ::: train hss = 0.2068 : val hss = 0.2845
mean cv TSS: 0.3028
mean cv HSS: 0.1023
237/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.8317 : val tss = -0.0338 ::: train hss = 0.1770 : val hss = -0.0287
Fold 1: train tss = 0.7786 : val tss = 0.1427 ::: train hss = 0.4511 : val hss = 0.0740
Fold 2: train tss = 0.6425 : val tss = 0.5596 ::: train hss = 0.1269 : val hss = 0.1981
Fold 3: train tss = 0.6098 : val tss = 0.2279 ::: train hss = 0.1615 : val hss = 0.0176
Fold 4: train tss = 0.5576 : val tss = 0.6157 ::: train hss = 0.0946 : val hss = 0.1867
mean cv TSS: 0.3024
mean cv HSS: 0.0895
238/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.9933 : val tss = -0.0045 ::: train hss = 0.4182 : val hss = -0.0076
Fold 1: train tss = 0.8891 : val tss = 0.1509 ::: train hss = 0.4010 : val hss = 0.1019
Fold 2: train tss = 0.7839 : val tss = 0.5785 ::: train hss = 0.2279 : val hss = 0.3143
Fold 3: train tss = 0.5597 : val tss = 0.1316 ::: train hss = 0.1189 : val hss = 0.0046
Fold 4: train tss = 0.7078 : val tss = 0.7056 ::: train hss = 0.1928 : val hss = 0.2706
mean cv TSS: 0.3124
mean cv HSS: 0.1368
239/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.9922 : val tss = -0.0026 ::: train hss = 0.3816 : val hss = -0.0047
Fold 1: train tss = 0.7913 : val tss = 0.1804 ::: train hss = 0.5552 : val hss = 0.0871
Fold 2: train tss = 0.6676 : val tss = 0.6236 ::: train hss = 0.1465 : val hss = 0.2721
Fold 3: train tss = 0.6579 : val tss = 0.2120 ::: train hss = 0.1997 : val hss = 0.0299
Fold 4: train tss = 0.6267 : val tss = 0.5910 ::: train hss = 0.1435 : val hss = 0.1917
mean cv TSS: 0.3209
mean cv HSS: 0.1152
240/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.1492 : val tss = 0.0015 ::: train hss = 0.1989 : val hss = 0.0019
Fold 1: train tss = 0.8194 : val tss = 0.1327 ::: train hss = 0.2634 : val hss = 0.0427
Fold 2: train tss = 0.6940 : val tss = 0.6263 ::: train hss = 0.1453 : val hss = 0.2103
Fold 3: train tss = 0.6542 : val tss = 0.3558 ::: train hss = 0.1463 : val hss = 0.0515
Fold 4: train tss = 0.7302 : val tss = 0.6506 ::: train hss = 0.2053 : val hss = 0.2209
mean cv TSS: 0.3534
mean cv HSS: 0.1054
241/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7554 : val tss = 0.2444 ::: train hss = 0.3633 : val hss = 0.0941
Fold 2: train tss = 0.6803 : val tss = 0.6794 ::: train hss = 0.1702 : val hss = 0.2820
Fold 3: train tss = 0.7324 : val tss = 0.1025 ::: train hss = 0.2264 : val hss = 0.0167
Fold 4: train tss = 0.6805 : val tss = 0.5738 ::: train hss = 0.1678 : val hss = 0.1867
mean cv TSS: 0.3200
mean cv HSS: 0.1159
242/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.4439 : val tss = -0.0097 ::: train hss = 0.2248 : val hss = -0.0097
Fold 1: train tss = 0.7686 : val tss = 0.1905 ::: train hss = 0.2465 : val hss = 0.0787
Fold 2: train tss = 0.6974 : val tss = 0.7238 ::: train hss = 0.1721 : val hss = 0.3306
Fold 3: train tss = 0.7287 : val tss = 0.3898 ::: train hss = 0.2166 : val hss = 0.0509
Fold 4: train tss = 0.7095 : val tss = 0.6463 ::: train hss = 0.1917 : val hss = 0.2434
mean cv TSS: 0.3881
mean cv HSS: 0.1388
243/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.4893 : val tss = -0.0198 ::: train hss = 0.1659 : val hss = -0.0164
Fold 1: train tss = 0.7323 : val tss = 0.2327 ::: train hss = 0.4650 : val hss = 0.0639
Fold 2: train tss = 0.6693 : val tss = 0.6931 ::: train hss = 0.1356 : val hss = 0.3068
Fold 3: train tss = 0.6892 : val tss = 0.0443 ::: train hss = 0.1742 : val hss = 0.0137
Fold 4: train tss = 0.6665 : val tss = 0.6434 ::: train hss = 0.1567 : val hss = 0.2067
mean cv TSS: 0.3188
mean cv HSS: 0.1149
244/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.2488 : val tss = -0.0037 ::: train hss = 0.2843 : val hss = -0.0065
Fold 1: train tss = 0.7499 : val tss = 0.2255 ::: train hss = 0.2693 : val hss = 0.1085
Fold 2: train tss = 0.6968 : val tss = 0.6716 ::: train hss = 0.1643 : val hss = 0.3145
Fold 3: train tss = 0.7564 : val tss = 0.2361 ::: train hss = 0.2261 : val hss = 0.0256
Fold 4: train tss = 0.7579 : val tss = 0.5492 ::: train hss = 0.2373 : val hss = 0.1634
mean cv TSS: 0.3357
mean cv HSS: 0.1211
245/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.3952 : val tss = -0.0104 ::: train hss = 0.2360 : val hss = -0.0147
Fold 1: train tss = 0.7819 : val tss = 0.0948 ::: train hss = 0.2803 : val hss = 0.0199
Fold 2: train tss = 0.5505 : val tss = 0.6551 ::: train hss = 0.1406 : val hss = 0.2693
Fold 3: train tss = 0.6569 : val tss = 0.1372 ::: train hss = 0.1714 : val hss = 0.0250
Fold 4: train tss = 0.6518 : val tss = 0.6388 ::: train hss = 0.1474 : val hss = 0.2051
mean cv TSS: 0.3031
mean cv HSS: 0.1009
246/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7343 : val tss = 0.2801 ::: train hss = 0.3651 : val hss = 0.1082
Fold 2: train tss = 0.6797 : val tss = 0.5921 ::: train hss = 0.1840 : val hss = 0.1965
Fold 3: train tss = 0.7598 : val tss = 0.1090 ::: train hss = 0.2885 : val hss = 0.0150
Fold 4: train tss = 0.7133 : val tss = 0.6484 ::: train hss = 0.1951 : val hss = 0.2521
mean cv TSS: 0.3259
mean cv HSS: 0.1144
247/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7485 : val tss = 0.3558 ::: train hss = 0.2989 : val hss = 0.1251
Fold 2: train tss = 0.6744 : val tss = 0.6816 ::: train hss = 0.1561 : val hss = 0.2553
Fold 3: train tss = 0.7406 : val tss = 0.2608 ::: train hss = 0.2385 : val hss = 0.0649
Fold 4: train tss = 0.7165 : val tss = 0.6320 ::: train hss = 0.1868 : val hss = 0.2066
mean cv TSS: 0.3860
mean cv HSS: 0.1304
248/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0999 : val tss = -0.0022 ::: train hss = 0.1737 : val hss = -0.0041
Fold 1: train tss = 0.7634 : val tss = 0.2747 ::: train hss = 0.4288 : val hss = 0.0893
Fold 2: train tss = 0.6189 : val tss = 0.6560 ::: train hss = 0.0983 : val hss = 0.2836
Fold 3: train tss = 0.6943 : val tss = 0.1307 ::: train hss = 0.1953 : val hss = 0.0241
Fold 4: train tss = 0.6996 : val tss = 0.7222 ::: train hss = 0.1905 : val hss = 0.2907
mean cv TSS: 0.3563
mean cv HSS: 0.1367
249/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0984 : val tss = -0.0104 ::: train hss = 0.1125 : val hss = -0.0128
Fold 1: train tss = 0.7640 : val tss = 0.2673 ::: train hss = 0.2449 : val hss = 0.0672
Fold 2: train tss = 0.5645 : val tss = 0.6622 ::: train hss = 0.1770 : val hss = 0.2647
Fold 3: train tss = 0.6900 : val tss = 0.0351 ::: train hss = 0.1842 : val hss = 0.0090
Fold 4: train tss = 0.7031 : val tss = 0.6222 ::: train hss = 0.1841 : val hss = 0.1965
mean cv TSS: 0.3153
mean cv HSS: 0.1049
250/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.3433 : val tss = -0.0104 ::: train hss = 0.1675 : val hss = -0.0103
Fold 1: train tss = 0.7998 : val tss = 0.2234 ::: train hss = 0.4082 : val hss = 0.0994
Fold 2: train tss = 0.7403 : val tss = 0.6966 ::: train hss = 0.1536 : val hss = 0.2948
Fold 3: train tss = 0.7155 : val tss = 0.2661 ::: train hss = 0.2267 : val hss = 0.0646
Fold 4: train tss = 0.7228 : val tss = 0.6085 ::: train hss = 0.1976 : val hss = 0.3226
mean cv TSS: 0.3568
mean cv HSS: 0.1542
251/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.3451 : val tss = -0.0195 ::: train hss = 0.2060 : val hss = -0.0219
Fold 1: train tss = 0.8239 : val tss = 0.2898 ::: train hss = 0.4299 : val hss = 0.0896
Fold 2: train tss = 0.7303 : val tss = 0.6455 ::: train hss = 0.1823 : val hss = 0.2612
Fold 3: train tss = 0.7805 : val tss = 0.1703 ::: train hss = 0.3255 : val hss = 0.0198
Fold 4: train tss = 0.7125 : val tss = 0.3396 ::: train hss = 0.1975 : val hss = 0.1768
mean cv TSS: 0.2851
mean cv HSS: 0.1051
252/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 60257
Fold 0: train tss = 0.0469 : val tss = -0.0056 ::: train hss = 0.0399 : val hss = -0.0055
Fold 1: train tss = 0.6078 : val tss = 0.3557 ::: train hss = 0.0929 : val hss = 0.0591
Fold 2: train tss = 0.5707 : val tss = 0.4632 ::: train hss = 0.0696 : val hss = 0.1090
Fold 3: train tss = 0.7149 : val tss = 0.3229 ::: train hss = 0.1855 : val hss = 0.0289
Fold 4: train tss = 0.6342 : val tss = 0.5964 ::: train hss = 0.1248 : val hss = 0.1686
mean cv TSS: 0.3465
mean cv HSS: 0.0720
253/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5899 : val tss = 0.3063 ::: train hss = 0.0702 : val hss = 0.0517
Fold 2: train tss = 0.5683 : val tss = 0.6397 ::: train hss = 0.0922 : val hss = 0.2423
Fold 3: train tss = 0.5057 : val tss = 0.1673 ::: train hss = 0.1038 : val hss = 0.0408
Fold 4: train tss = 0.4672 : val tss = 0.5285 ::: train hss = 0.0629 : val hss = 0.1287
mean cv TSS: 0.3284
mean cv HSS: 0.0927
254/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0495 : val tss = 0.0000 ::: train hss = 0.0792 : val hss = 0.0000
Fold 1: train tss = 0.7118 : val tss = 0.2328 ::: train hss = 0.1279 : val hss = 0.0411
Fold 2: train tss = 0.5283 : val tss = 0.5119 ::: train hss = 0.0664 : val hss = 0.1350
Fold 3: train tss = 0.6567 : val tss = 0.2560 ::: train hss = 0.1304 : val hss = 0.0228
Fold 4: train tss = 0.5436 : val tss = 0.5855 ::: train hss = 0.0843 : val hss = 0.1802
mean cv TSS: 0.3172
mean cv HSS: 0.0758
255/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6491 : val tss = 0.2295 ::: train hss = 0.1021 : val hss = 0.0426
Fold 2: train tss = 0.5956 : val tss = 0.5483 ::: train hss = 0.1320 : val hss = 0.3065
Fold 3: train tss = 0.5469 : val tss = 0.1873 ::: train hss = 0.0994 : val hss = 0.0096
Fold 4: train tss = 0.4406 : val tss = 0.3680 ::: train hss = 0.0554 : val hss = 0.0707
mean cv TSS: 0.2666
mean cv HSS: 0.0859
256/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0483 : val tss = 0.0020 ::: train hss = 0.0552 : val hss = 0.0030
Fold 1: train tss = 0.7381 : val tss = 0.0782 ::: train hss = 0.2293 : val hss = 0.0276
Fold 2: train tss = 0.5134 : val tss = 0.5286 ::: train hss = 0.0591 : val hss = 0.1494
Fold 3: train tss = 0.6282 : val tss = 0.0190 ::: train hss = 0.1139 : val hss = 0.0015
Fold 4: train tss = 0.5214 : val tss = 0.3593 ::: train hss = 0.0757 : val hss = 0.0697
mean cv TSS: 0.1974
mean cv HSS: 0.0502
257/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.2460 : val tss = -0.0115 ::: train hss = 0.1696 : val hss = -0.0158
Fold 1: train tss = 0.7244 : val tss = -0.0022 ::: train hss = 0.0972 : val hss = -0.0003
Fold 2: train tss = 0.5197 : val tss = 0.5068 ::: train hss = 0.0653 : val hss = 0.1269
Fold 3: train tss = 0.6150 : val tss = -0.0005 ::: train hss = 0.1524 : val hss = -0.0001
Fold 4: train tss = 0.4236 : val tss = 0.3485 ::: train hss = 0.0521 : val hss = 0.0703
mean cv TSS: 0.1682
mean cv HSS: 0.0362
258/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.6245 : val tss = -0.0301 ::: train hss = 0.1024 : val hss = -0.0249
Fold 1: train tss = 0.7193 : val tss = 0.3320 ::: train hss = 0.2799 : val hss = 0.0901
Fold 2: train tss = 0.6979 : val tss = 0.5837 ::: train hss = 0.2331 : val hss = 0.1924
Fold 3: train tss = 0.7467 : val tss = 0.0344 ::: train hss = 0.2411 : val hss = 0.0058
Fold 4: train tss = 0.6980 : val tss = 0.6145 ::: train hss = 0.1958 : val hss = 0.2675
mean cv TSS: 0.3069
mean cv HSS: 0.1062
259/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.2944 : val tss = 0.0000 ::: train hss = 0.1636 : val hss = 0.0000
Fold 1: train tss = 0.7395 : val tss = 0.3784 ::: train hss = 0.2605 : val hss = 0.1438
Fold 2: train tss = 0.4892 : val tss = 0.5641 ::: train hss = 0.0652 : val hss = 0.1904
Fold 3: train tss = 0.5416 : val tss = 0.0934 ::: train hss = 0.1066 : val hss = 0.0182
Fold 4: train tss = 0.5778 : val tss = 0.5770 ::: train hss = 0.1108 : val hss = 0.1590
mean cv TSS: 0.3226
mean cv HSS: 0.1023
260/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.5364 : val tss = -0.0569 ::: train hss = 0.1501 : val hss = -0.0346
Fold 1: train tss = 0.7694 : val tss = 0.2354 ::: train hss = 0.4936 : val hss = 0.0900
Fold 2: train tss = 0.4853 : val tss = 0.5728 ::: train hss = 0.0914 : val hss = 0.2064
Fold 3: train tss = 0.7604 : val tss = 0.1427 ::: train hss = 0.2273 : val hss = 0.0225
Fold 4: train tss = 0.6182 : val tss = 0.5964 ::: train hss = 0.1134 : val hss = 0.1747
mean cv TSS: 0.2981
mean cv HSS: 0.0918
261/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = -0.0001 : val tss = -0.0104 ::: train hss = -0.0002 : val hss = -0.0147
Fold 1: train tss = 0.7545 : val tss = 0.3105 ::: train hss = 0.3574 : val hss = 0.1290
Fold 2: train tss = 0.4161 : val tss = 0.4902 ::: train hss = 0.0461 : val hss = 0.1544
Fold 3: train tss = 0.5722 : val tss = 0.0741 ::: train hss = 0.1196 : val hss = 0.0264
Fold 4: train tss = 0.5471 : val tss = 0.4270 ::: train hss = 0.0991 : val hss = 0.0918
mean cv TSS: 0.2583
mean cv HSS: 0.0774
262/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.8350 : val tss = -0.0140 ::: train hss = 0.2087 : val hss = -0.0094
Fold 1: train tss = 0.7874 : val tss = 0.1797 ::: train hss = 0.5632 : val hss = 0.0999
Fold 2: train tss = 0.7622 : val tss = 0.6205 ::: train hss = 0.2671 : val hss = 0.2122
Fold 3: train tss = 0.7351 : val tss = 0.2571 ::: train hss = 0.2205 : val hss = 0.0225
Fold 4: train tss = 0.6790 : val tss = 0.5571 ::: train hss = 0.2025 : val hss = 0.1999
mean cv TSS: 0.3201
mean cv HSS: 0.1050
263/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 248673
Fold 0: train tss = 0.8854 : val tss = -0.0061 ::: train hss = 0.2241 : val hss = -0.0098
Fold 1: train tss = 0.8483 : val tss = 0.1706 ::: train hss = 0.4562 : val hss = 0.0650
Fold 2: train tss = 0.5642 : val tss = 0.4974 ::: train hss = 0.1588 : val hss = 0.1323
Fold 3: train tss = 0.6824 : val tss = 0.5809 ::: train hss = 0.2044 : val hss = 0.0648
Fold 4: train tss = 0.5597 : val tss = 0.5033 ::: train hss = 0.1017 : val hss = 0.1350
mean cv TSS: 0.3492
mean cv HSS: 0.0775
264/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.4911 : val tss = -0.0320 ::: train hss = 0.1889 : val hss = -0.0237
Fold 1: train tss = 0.7666 : val tss = 0.1363 ::: train hss = 0.2685 : val hss = 0.0375
Fold 2: train tss = 0.7402 : val tss = 0.6397 ::: train hss = 0.1909 : val hss = 0.2294
Fold 3: train tss = 0.7848 : val tss = 0.0787 ::: train hss = 0.2788 : val hss = 0.0112
Fold 4: train tss = 0.7346 : val tss = 0.6788 ::: train hss = 0.2326 : val hss = 0.2376
mean cv TSS: 0.3003
mean cv HSS: 0.0984
265/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8190 : val tss = 0.0998 ::: train hss = 0.4239 : val hss = 0.0319
Fold 2: train tss = 0.6999 : val tss = 0.6367 ::: train hss = 0.1731 : val hss = 0.2607
Fold 3: train tss = 0.6625 : val tss = 0.1487 ::: train hss = 0.1545 : val hss = 0.0230
Fold 4: train tss = 0.6473 : val tss = 0.5500 ::: train hss = 0.1421 : val hss = 0.2071
mean cv TSS: 0.2871
mean cv HSS: 0.1045
266/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.5897 : val tss = -0.0385 ::: train hss = 0.2016 : val hss = -0.0243
Fold 1: train tss = 0.7713 : val tss = 0.1376 ::: train hss = 0.2420 : val hss = 0.0468
Fold 2: train tss = 0.6362 : val tss = 0.6502 ::: train hss = 0.1190 : val hss = 0.2355
Fold 3: train tss = 0.7395 : val tss = 0.4092 ::: train hss = 0.2145 : val hss = 0.0590
Fold 4: train tss = 0.7466 : val tss = 0.6389 ::: train hss = 0.2181 : val hss = 0.2109
mean cv TSS: 0.3595
mean cv HSS: 0.1056
267/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7725 : val tss = 0.2751 ::: train hss = 0.2599 : val hss = 0.0685
Fold 2: train tss = 0.6777 : val tss = 0.6207 ::: train hss = 0.1549 : val hss = 0.2034
Fold 3: train tss = 0.7246 : val tss = 0.2889 ::: train hss = 0.2255 : val hss = 0.0309
Fold 4: train tss = 0.6633 : val tss = 0.6327 ::: train hss = 0.1666 : val hss = 0.2035
mean cv TSS: 0.3635
mean cv HSS: 0.1013
268/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.6883 : val tss = -0.0109 ::: train hss = 0.2118 : val hss = -0.0107
Fold 1: train tss = 0.8302 : val tss = 0.0452 ::: train hss = 0.3285 : val hss = 0.0211
Fold 2: train tss = 0.6262 : val tss = 0.5811 ::: train hss = 0.1632 : val hss = 0.1806
Fold 3: train tss = 0.7619 : val tss = 0.4545 ::: train hss = 0.2492 : val hss = 0.0335
Fold 4: train tss = 0.7258 : val tss = 0.4894 ::: train hss = 0.2050 : val hss = 0.1495
mean cv TSS: 0.3119
mean cv HSS: 0.0748
269/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.4858 : val tss = -0.0116 ::: train hss = 0.1331 : val hss = -0.0159
Fold 1: train tss = 0.8285 : val tss = 0.1621 ::: train hss = 0.3198 : val hss = 0.0686
Fold 2: train tss = 0.6851 : val tss = 0.4843 ::: train hss = 0.1810 : val hss = 0.1232
Fold 3: train tss = 0.7356 : val tss = 0.2052 ::: train hss = 0.2126 : val hss = 0.0176
Fold 4: train tss = 0.6621 : val tss = 0.4732 ::: train hss = 0.1508 : val hss = 0.1197
mean cv TSS: 0.2626
mean cv HSS: 0.0626
270/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7639 : val tss = 0.2374 ::: train hss = 0.3123 : val hss = 0.0838
Fold 2: train tss = 0.6761 : val tss = 0.6513 ::: train hss = 0.1470 : val hss = 0.2302
Fold 3: train tss = 0.7111 : val tss = 0.0294 ::: train hss = 0.2120 : val hss = 0.0061
Fold 4: train tss = 0.6965 : val tss = 0.6744 ::: train hss = 0.1791 : val hss = 0.2409
mean cv TSS: 0.3185
mean cv HSS: 0.1122
271/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7507 : val tss = 0.3557 ::: train hss = 0.2558 : val hss = 0.1250
Fold 2: train tss = 0.7076 : val tss = 0.6494 ::: train hss = 0.2023 : val hss = 0.2223
Fold 3: train tss = 0.7000 : val tss = 0.4278 ::: train hss = 0.2014 : val hss = 0.0587
Fold 4: train tss = 0.6403 : val tss = 0.6218 ::: train hss = 0.1309 : val hss = 0.1897
mean cv TSS: 0.4109
mean cv HSS: 0.1191
272/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.3482 : val tss = -0.0082 ::: train hss = 0.3316 : val hss = -0.0123
Fold 1: train tss = 0.7807 : val tss = 0.3360 ::: train hss = 0.4286 : val hss = 0.1118
Fold 2: train tss = 0.7144 : val tss = 0.6693 ::: train hss = 0.2005 : val hss = 0.2558
Fold 3: train tss = 0.7056 : val tss = 0.1296 ::: train hss = 0.1980 : val hss = 0.0200
Fold 4: train tss = 0.6841 : val tss = 0.6854 ::: train hss = 0.1798 : val hss = 0.2557
mean cv TSS: 0.3624
mean cv HSS: 0.1262
273/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7843 : val tss = 0.2532 ::: train hss = 0.4647 : val hss = 0.1065
Fold 2: train tss = 0.6822 : val tss = 0.7177 ::: train hss = 0.1458 : val hss = 0.3508
Fold 3: train tss = 0.7382 : val tss = 0.0766 ::: train hss = 0.2424 : val hss = 0.0119
Fold 4: train tss = 0.6850 : val tss = 0.6447 ::: train hss = 0.1722 : val hss = 0.3434
mean cv TSS: 0.3384
mean cv HSS: 0.1625
274/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 741217
Fold 0: train tss = 0.3476 : val tss = -0.0066 ::: train hss = 0.2958 : val hss = -0.0105
Fold 1: train tss = 0.8275 : val tss = 0.1896 ::: train hss = 0.4648 : val hss = 0.0728
Fold 2: train tss = 0.7441 : val tss = 0.6517 ::: train hss = 0.2974 : val hss = 0.2441
Fold 3: train tss = 0.7573 : val tss = 0.1749 ::: train hss = 0.2697 : val hss = 0.0628
Fold 4: train tss = 0.7084 : val tss = 0.6054 ::: train hss = 0.2033 : val hss = 0.2808
mean cv TSS: 0.3230
mean cv HSS: 0.1300
275/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.3900 : val tss = -0.0246 ::: train hss = 0.1418 : val hss = -0.0248
Fold 1: train tss = 0.7792 : val tss = 0.2024 ::: train hss = 0.5080 : val hss = 0.0786
Fold 2: train tss = 0.7060 : val tss = 0.6392 ::: train hss = 0.1444 : val hss = 0.2260
Fold 3: train tss = 0.7884 : val tss = 0.2641 ::: train hss = 0.3031 : val hss = 0.0385
Fold 4: train tss = 0.7172 : val tss = 0.6131 ::: train hss = 0.2088 : val hss = 0.3039
mean cv TSS: 0.3388
mean cv HSS: 0.1244
276/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6733 : val tss = 0.3230 ::: train hss = 0.0961 : val hss = 0.0666
Fold 2: train tss = 0.5510 : val tss = 0.4819 ::: train hss = 0.0633 : val hss = 0.1166
Fold 3: train tss = 0.6850 : val tss = 0.2793 ::: train hss = 0.1775 : val hss = 0.0347
Fold 4: train tss = 0.5976 : val tss = 0.5615 ::: train hss = 0.1110 : val hss = 0.1573
mean cv TSS: 0.3291
mean cv HSS: 0.0750
277/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7394 : val tss = 0.3163 ::: train hss = 0.2955 : val hss = 0.1023
Fold 2: train tss = 0.5105 : val tss = 0.6678 ::: train hss = 0.0714 : val hss = 0.2739
Fold 3: train tss = 0.6366 : val tss = 0.1234 ::: train hss = 0.1596 : val hss = 0.0175
Fold 4: train tss = 0.5267 : val tss = 0.4872 ::: train hss = 0.0861 : val hss = 0.1114
mean cv TSS: 0.3189
mean cv HSS: 0.1010
278/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.5243 : val tss = -0.0199 ::: train hss = 0.0863 : val hss = -0.0199
Fold 1: train tss = 0.7198 : val tss = 0.0657 ::: train hss = 0.0962 : val hss = 0.0155
Fold 2: train tss = 0.5390 : val tss = 0.4741 ::: train hss = 0.0639 : val hss = 0.1281
Fold 3: train tss = 0.4968 : val tss = 0.2778 ::: train hss = 0.0641 : val hss = 0.0165
Fold 4: train tss = 0.5105 : val tss = 0.5006 ::: train hss = 0.0718 : val hss = 0.1162
mean cv TSS: 0.2597
mean cv HSS: 0.0513
279/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6257 : val tss = 0.2866 ::: train hss = 0.3500 : val hss = 0.0733
Fold 2: train tss = 0.4223 : val tss = 0.5391 ::: train hss = 0.0546 : val hss = 0.1890
Fold 3: train tss = 0.5852 : val tss = 0.2004 ::: train hss = 0.1210 : val hss = 0.0305
Fold 4: train tss = 0.4919 : val tss = 0.4709 ::: train hss = 0.0771 : val hss = 0.1063
mean cv TSS: 0.2994
mean cv HSS: 0.0798
280/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.8273 : val tss = -0.0122 ::: train hss = 0.1484 : val hss = -0.0164
Fold 1: train tss = 0.7445 : val tss = 0.1048 ::: train hss = 0.1484 : val hss = 0.0264
Fold 2: train tss = 0.6521 : val tss = 0.4480 ::: train hss = 0.0988 : val hss = 0.1295
Fold 3: train tss = 0.6244 : val tss = 0.2287 ::: train hss = 0.1156 : val hss = 0.0112
Fold 4: train tss = 0.5755 : val tss = 0.4521 ::: train hss = 0.1062 : val hss = 0.1143
mean cv TSS: 0.2443
mean cv HSS: 0.0530
281/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0937 : val tss = 0.0302 ::: train hss = 0.0506 : val hss = 0.0271
Fold 1: train tss = 0.6507 : val tss = 0.1412 ::: train hss = 0.0650 : val hss = 0.0204
Fold 2: train tss = 0.3869 : val tss = 0.5803 ::: train hss = 0.0398 : val hss = 0.1739
Fold 3: train tss = 0.4916 : val tss = -0.0508 ::: train hss = 0.0757 : val hss = -0.0028
Fold 4: train tss = 0.4104 : val tss = 0.2613 ::: train hss = 0.0470 : val hss = 0.0445
mean cv TSS: 0.1924
mean cv HSS: 0.0526
282/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.7744 : val tss = -0.0216 ::: train hss = 0.1249 : val hss = -0.0160
Fold 1: train tss = 0.7581 : val tss = 0.3352 ::: train hss = 0.4188 : val hss = 0.1364
Fold 2: train tss = 0.6742 : val tss = 0.6097 ::: train hss = 0.1511 : val hss = 0.1927
Fold 3: train tss = 0.6927 : val tss = 0.3589 ::: train hss = 0.1880 : val hss = 0.0392
Fold 4: train tss = 0.6962 : val tss = 0.5892 ::: train hss = 0.1880 : val hss = 0.1632
mean cv TSS: 0.3743
mean cv HSS: 0.1031
283/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7548 : val tss = 0.3603 ::: train hss = 0.2712 : val hss = 0.1341
Fold 2: train tss = 0.6485 : val tss = 0.6481 ::: train hss = 0.1293 : val hss = 0.2551
Fold 3: train tss = 0.4510 : val tss = 0.2084 ::: train hss = 0.0889 : val hss = 0.0184
Fold 4: train tss = 0.5898 : val tss = 0.5972 ::: train hss = 0.1098 : val hss = 0.1753
mean cv TSS: 0.3628
mean cv HSS: 0.1166
284/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.3907 : val tss = -0.0015 ::: train hss = 0.1488 : val hss = -0.0014
Fold 1: train tss = 0.7736 : val tss = 0.2608 ::: train hss = 0.4441 : val hss = 0.1001
Fold 2: train tss = 0.6601 : val tss = 0.6211 ::: train hss = 0.1140 : val hss = 0.2375
Fold 3: train tss = 0.7453 : val tss = 0.4297 ::: train hss = 0.2477 : val hss = 0.0450
Fold 4: train tss = 0.7261 : val tss = 0.6279 ::: train hss = 0.1954 : val hss = 0.2032
mean cv TSS: 0.3876
mean cv HSS: 0.1169
285/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 372577
Fold 0: train tss = 0.3406 : val tss = -0.0744 ::: train hss = 0.1297 : val hss = -0.0309
Fold 1: train tss = 0.6712 : val tss = 0.3276 ::: train hss = 0.1109 : val hss = 0.1237
Fold 2: train tss = 0.5550 : val tss = 0.6047 ::: train hss = 0.1326 : val hss = 0.2646
Fold 3: train tss = 0.5944 : val tss = 0.4001 ::: train hss = 0.1277 : val hss = 0.0354
Fold 4: train tss = 0.6113 : val tss = 0.5936 ::: train hss = 0.1228 : val hss = 0.1686
mean cv TSS: 0.3703
mean cv HSS: 0.1123
286/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.7898 : val tss = -0.0373 ::: train hss = 0.2633 : val hss = -0.0213
Fold 1: train tss = 0.8502 : val tss = 0.1119 ::: train hss = 0.4751 : val hss = 0.0461
Fold 2: train tss = 0.7067 : val tss = 0.6193 ::: train hss = 0.4181 : val hss = 0.2207
Fold 3: train tss = 0.7843 : val tss = 0.2852 ::: train hss = 0.2920 : val hss = 0.0250
Fold 4: train tss = 0.6789 : val tss = 0.6364 ::: train hss = 0.1730 : val hss = 0.2563
mean cv TSS: 0.3231
mean cv HSS: 0.1053
287/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.6885 : val tss = -0.0222 ::: train hss = 0.2152 : val hss = -0.0213
Fold 1: train tss = 0.8660 : val tss = 0.0341 ::: train hss = 0.4601 : val hss = 0.0064
Fold 2: train tss = 0.4294 : val tss = 0.4631 ::: train hss = 0.1096 : val hss = 0.1290
Fold 3: train tss = 0.5870 : val tss = 0.1599 ::: train hss = 0.1331 : val hss = 0.0185
Fold 4: train tss = 0.5827 : val tss = 0.5523 ::: train hss = 0.1149 : val hss = 0.2108
mean cv TSS: 0.2374
mean cv HSS: 0.0687
288/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.1486 : val tss = -0.0009 ::: train hss = 0.1698 : val hss = -0.0017
Fold 1: train tss = 0.7722 : val tss = 0.1882 ::: train hss = 0.3928 : val hss = 0.1174
Fold 2: train tss = 0.7520 : val tss = 0.6959 ::: train hss = 0.2706 : val hss = 0.3892
Fold 3: train tss = 0.7664 : val tss = 0.0793 ::: train hss = 0.2685 : val hss = 0.0346
Fold 4: train tss = 0.7601 : val tss = 0.5520 ::: train hss = 0.2353 : val hss = 0.2866
mean cv TSS: 0.3029
mean cv HSS: 0.1652
289/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.6505 : val tss = -0.0005 ::: train hss = 0.0586 : val hss = -0.0010
Fold 1: train tss = 0.7710 : val tss = 0.1781 ::: train hss = 0.3056 : val hss = 0.1223
Fold 2: train tss = 0.6420 : val tss = 0.6727 ::: train hss = 0.1200 : val hss = 0.2891
Fold 3: train tss = 0.7269 : val tss = 0.2449 ::: train hss = 0.2343 : val hss = 0.0412
Fold 4: train tss = 0.6892 : val tss = 0.6057 ::: train hss = 0.1685 : val hss = 0.1731
mean cv TSS: 0.3402
mean cv HSS: 0.1249
290/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.3462 : val tss = -0.0014 ::: train hss = 0.2388 : val hss = -0.0026
Fold 1: train tss = 0.7844 : val tss = 0.1500 ::: train hss = 0.4667 : val hss = 0.0760
Fold 2: train tss = 0.7641 : val tss = 0.6849 ::: train hss = 0.2513 : val hss = 0.3101
Fold 3: train tss = 0.7766 : val tss = 0.1417 ::: train hss = 0.2912 : val hss = 0.0353
Fold 4: train tss = 0.7777 : val tss = 0.6571 ::: train hss = 0.2644 : val hss = 0.2340
mean cv TSS: 0.3265
mean cv HSS: 0.1306
291/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = -0.0004 : val tss = -0.0004 ::: train hss = -0.0006 : val hss = -0.0007
Fold 1: train tss = 0.7807 : val tss = 0.1356 ::: train hss = 0.4734 : val hss = 0.0612
Fold 2: train tss = 0.6919 : val tss = 0.6663 ::: train hss = 0.1673 : val hss = 0.2691
Fold 3: train tss = 0.7210 : val tss = 0.0989 ::: train hss = 0.2227 : val hss = 0.0177
Fold 4: train tss = 0.5264 : val tss = 0.5202 ::: train hss = 0.0915 : val hss = 0.1351
mean cv TSS: 0.2841
mean cv HSS: 0.0965
292/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.6946 : val tss = -0.0040 ::: train hss = 0.3562 : val hss = -0.0069
Fold 1: train tss = 0.9276 : val tss = 0.1879 ::: train hss = 0.5647 : val hss = 0.0742
Fold 2: train tss = 0.7674 : val tss = 0.6247 ::: train hss = 0.2277 : val hss = 0.2954
Fold 3: train tss = 0.7895 : val tss = -0.0354 ::: train hss = 0.3234 : val hss = -0.0102
Fold 4: train tss = 0.7215 : val tss = 0.4969 ::: train hss = 0.1976 : val hss = 0.1956
mean cv TSS: 0.2540
mean cv HSS: 0.1096
293/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.4465 : val tss = -0.0059 ::: train hss = 0.3079 : val hss = -0.0095
Fold 1: train tss = 0.7590 : val tss = 0.1572 ::: train hss = 0.4284 : val hss = 0.0502
Fold 2: train tss = 0.6086 : val tss = 0.6067 ::: train hss = 0.1307 : val hss = 0.3311
Fold 3: train tss = 0.6672 : val tss = 0.3783 ::: train hss = 0.2281 : val hss = 0.0323
Fold 4: train tss = 0.7070 : val tss = 0.5203 ::: train hss = 0.1831 : val hss = 0.1912
mean cv TSS: 0.3313
mean cv HSS: 0.1191
294/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.2966 : val tss = -0.0025 ::: train hss = 0.2197 : val hss = -0.0045
Fold 1: train tss = 0.8096 : val tss = 0.2689 ::: train hss = 0.4570 : val hss = 0.1096
Fold 2: train tss = 0.7213 : val tss = 0.6397 ::: train hss = 0.1403 : val hss = 0.2718
Fold 3: train tss = 0.7986 : val tss = 0.0487 ::: train hss = 0.3229 : val hss = 0.0143
Fold 4: train tss = 0.7874 : val tss = 0.5312 ::: train hss = 0.2531 : val hss = 0.2603
mean cv TSS: 0.2972
mean cv HSS: 0.1303
295/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.3472 : val tss = -0.0016 ::: train hss = 0.2778 : val hss = -0.0030
Fold 1: train tss = 0.8065 : val tss = 0.1637 ::: train hss = 0.5227 : val hss = 0.1021
Fold 2: train tss = 0.6876 : val tss = 0.6160 ::: train hss = 0.1300 : val hss = 0.2321
Fold 3: train tss = 0.7011 : val tss = 0.0430 ::: train hss = 0.1890 : val hss = 0.0131
Fold 4: train tss = 0.5947 : val tss = 0.4916 ::: train hss = 0.1297 : val hss = 0.1298
mean cv TSS: 0.2626
mean cv HSS: 0.0948
296/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 385569
Fold 0: train tss = 0.3956 : val tss = -0.0056 ::: train hss = 0.2473 : val hss = -0.0091
Fold 1: train tss = 0.7930 : val tss = 0.1501 ::: train hss = 0.5823 : val hss = 0.0842
Fold 2: train tss = 0.7855 : val tss = 0.7060 ::: train hss = 0.3461 : val hss = 0.4050
Fold 3: train tss = 0.7039 : val tss = 0.0998 ::: train hss = 0.2261 : val hss = 0.0072
Fold 4: train tss = 0.7334 : val tss = 0.5855 ::: train hss = 0.2251 : val hss = 0.2986
mean cv TSS: 0.3072
mean cv HSS: 0.1572
297/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.3955 : val tss = -0.0012 ::: train hss = 0.2434 : val hss = -0.0024
Fold 1: train tss = 0.8009 : val tss = 0.1439 ::: train hss = 0.5682 : val hss = 0.0858
Fold 2: train tss = 0.7141 : val tss = 0.6161 ::: train hss = 0.1459 : val hss = 0.2231
Fold 3: train tss = 0.7999 : val tss = 0.0192 ::: train hss = 0.3698 : val hss = 0.0055
Fold 4: train tss = 0.7398 : val tss = 0.6754 ::: train hss = 0.2250 : val hss = 0.2847
mean cv TSS: 0.2907
mean cv HSS: 0.1193
298/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.8445 : val tss = -0.0039 ::: train hss = 0.4120 : val hss = -0.0067
Fold 1: train tss = 0.8563 : val tss = 0.1878 ::: train hss = 0.6145 : val hss = 0.0909
Fold 2: train tss = 0.7785 : val tss = 0.6537 ::: train hss = 0.1873 : val hss = 0.2616
Fold 3: train tss = 0.7940 : val tss = 0.0655 ::: train hss = 0.2922 : val hss = 0.0236
Fold 4: train tss = 0.7655 : val tss = 0.6335 ::: train hss = 0.2861 : val hss = 0.4063
mean cv TSS: 0.3073
mean cv HSS: 0.1552
299/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.5937 : val tss = -0.0040 ::: train hss = 0.2827 : val hss = -0.0059
Fold 1: train tss = 0.8418 : val tss = 0.1873 ::: train hss = 0.5915 : val hss = 0.0883
Fold 2: train tss = 0.7918 : val tss = 0.7031 ::: train hss = 0.3312 : val hss = 0.2985
Fold 3: train tss = 0.8432 : val tss = 0.0379 ::: train hss = 0.3659 : val hss = 0.0122
Fold 4: train tss = 0.7538 : val tss = 0.6298 ::: train hss = 0.2667 : val hss = 0.3584
mean cv TSS: 0.3108
mean cv HSS: 0.1503
300/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.3391 : val tss = -0.0172 ::: train hss = 0.1159 : val hss = -0.0203
Fold 1: train tss = 0.6260 : val tss = 0.3222 ::: train hss = 0.0729 : val hss = 0.0533
Fold 2: train tss = 0.6585 : val tss = 0.5239 ::: train hss = 0.1040 : val hss = 0.1411
Fold 3: train tss = 0.7875 : val tss = 0.1067 ::: train hss = 0.2734 : val hss = 0.0268
Fold 4: train tss = 0.6588 : val tss = 0.6494 ::: train hss = 0.1375 : val hss = 0.2391
mean cv TSS: 0.3170
mean cv HSS: 0.0880
301/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5439 : val tss = 0.3134 ::: train hss = 0.0424 : val hss = 0.0435
Fold 2: train tss = 0.4832 : val tss = 0.6114 ::: train hss = 0.0577 : val hss = 0.2287
Fold 3: train tss = 0.6165 : val tss = 0.1741 ::: train hss = 0.1416 : val hss = 0.0221
Fold 4: train tss = 0.5218 : val tss = 0.4870 ::: train hss = 0.0992 : val hss = 0.1104
mean cv TSS: 0.3172
mean cv HSS: 0.0809
302/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.4369 : val tss = -0.0186 ::: train hss = 0.1276 : val hss = -0.0213
Fold 1: train tss = 0.7121 : val tss = 0.1255 ::: train hss = 0.1283 : val hss = 0.0376
Fold 2: train tss = 0.4827 : val tss = 0.5191 ::: train hss = 0.0599 : val hss = 0.1457
Fold 3: train tss = 0.5617 : val tss = 0.1262 ::: train hss = 0.0936 : val hss = 0.0123
Fold 4: train tss = 0.5340 : val tss = 0.5112 ::: train hss = 0.0704 : val hss = 0.1644
mean cv TSS: 0.2527
mean cv HSS: 0.0677
303/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6345 : val tss = 0.1723 ::: train hss = 0.0876 : val hss = 0.0266
Fold 2: train tss = 0.5043 : val tss = 0.6001 ::: train hss = 0.0667 : val hss = 0.1913
Fold 3: train tss = 0.6226 : val tss = 0.2560 ::: train hss = 0.1648 : val hss = 0.0204
Fold 4: train tss = 0.6130 : val tss = 0.5416 ::: train hss = 0.1354 : val hss = 0.1427
mean cv TSS: 0.3140
mean cv HSS: 0.0762
304/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.5471 : val tss = -0.0097 ::: train hss = 0.3979 : val hss = -0.0140
Fold 1: train tss = 0.7442 : val tss = 0.1536 ::: train hss = 0.2990 : val hss = 0.0301
Fold 2: train tss = 0.5884 : val tss = 0.5294 ::: train hss = 0.0635 : val hss = 0.1493
Fold 3: train tss = 0.4930 : val tss = 0.1798 ::: train hss = 0.0731 : val hss = 0.0104
Fold 4: train tss = 0.5743 : val tss = 0.4126 ::: train hss = 0.0876 : val hss = 0.1139
mean cv TSS: 0.2531
mean cv HSS: 0.0579
305/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.4459 : val tss = -0.0059 ::: train hss = 0.2831 : val hss = -0.0095
Fold 1: train tss = 0.7031 : val tss = 0.1161 ::: train hss = 0.1401 : val hss = 0.0308
Fold 2: train tss = 0.4837 : val tss = 0.4967 ::: train hss = 0.0515 : val hss = 0.1267
Fold 3: train tss = 0.5046 : val tss = -0.1050 ::: train hss = 0.0698 : val hss = -0.0055
Fold 4: train tss = 0.4535 : val tss = 0.5149 ::: train hss = 0.0681 : val hss = 0.1264
mean cv TSS: 0.2034
mean cv HSS: 0.0538
306/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.9807 : val tss = -0.0370 ::: train hss = 0.1961 : val hss = -0.0297
Fold 1: train tss = 0.8564 : val tss = 0.2667 ::: train hss = 0.3816 : val hss = 0.1053
Fold 2: train tss = 0.7662 : val tss = 0.6728 ::: train hss = 0.1737 : val hss = 0.2784
Fold 3: train tss = 0.7696 : val tss = 0.0637 ::: train hss = 0.2204 : val hss = 0.0164
Fold 4: train tss = 0.6590 : val tss = 0.4584 ::: train hss = 0.1417 : val hss = 0.1072
mean cv TSS: 0.2849
mean cv HSS: 0.0955
307/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 188961
Fold 0: train tss = 0.7372 : val tss = -0.0266 ::: train hss = 0.2091 : val hss = -0.0234
Fold 1: train tss = 0.6675 : val tss = 0.3405 ::: train hss = 0.1210 : val hss = 0.1191
Fold 2: train tss = 0.6394 : val tss = 0.6107 ::: train hss = 0.1718 : val hss = 0.2178
Fold 3: train tss = 0.6261 : val tss = 0.0728 ::: train hss = 0.1690 : val hss = 0.0139
Fold 4: train tss = 0.6169 : val tss = 0.4974 ::: train hss = 0.1377 : val hss = 0.1146
mean cv TSS: 0.2990
mean cv HSS: 0.0884
308/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.8807 : val tss = -0.0208 ::: train hss = 0.1788 : val hss = -0.0227
Fold 1: train tss = 0.7933 : val tss = 0.1276 ::: train hss = 0.4261 : val hss = 0.1487
Fold 2: train tss = 0.5113 : val tss = 0.5851 ::: train hss = 0.1435 : val hss = 0.2393
Fold 3: train tss = 0.6533 : val tss = -0.0531 ::: train hss = 0.1657 : val hss = -0.0097
Fold 4: train tss = 0.7316 : val tss = 0.6698 ::: train hss = 0.2146 : val hss = 0.2900
mean cv TSS: 0.2617
mean cv HSS: 0.1291
309/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.3977 : val tss = -0.0230 ::: train hss = 0.3385 : val hss = -0.0168
Fold 1: train tss = 0.7730 : val tss = 0.2920 ::: train hss = 0.4380 : val hss = 0.1100
Fold 2: train tss = 0.6810 : val tss = 0.6711 ::: train hss = 0.1551 : val hss = 0.2694
Fold 3: train tss = 0.5624 : val tss = 0.0387 ::: train hss = 0.1274 : val hss = 0.0140
Fold 4: train tss = 0.5635 : val tss = 0.5033 ::: train hss = 0.0967 : val hss = 0.1433
mean cv TSS: 0.2964
mean cv HSS: 0.1040
310/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.7951 : val tss = -0.0071 ::: train hss = 0.4185 : val hss = -0.0111
Fold 1: train tss = 0.8210 : val tss = 0.1269 ::: train hss = 0.1619 : val hss = 0.0570
Fold 2: train tss = 0.6924 : val tss = 0.6894 ::: train hss = 0.2016 : val hss = 0.3611
Fold 3: train tss = 0.7082 : val tss = 0.0605 ::: train hss = 0.1968 : val hss = 0.0122
Fold 4: train tss = 0.5330 : val tss = 0.6897 ::: train hss = 0.0849 : val hss = 0.2979
mean cv TSS: 0.3119
mean cv HSS: 0.1434
311/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.9948 : val tss = -0.0002 ::: train hss = 0.4794 : val hss = -0.0005
Fold 1: train tss = 0.7728 : val tss = 0.2228 ::: train hss = 0.4831 : val hss = 0.0912
Fold 2: train tss = 0.7176 : val tss = 0.6230 ::: train hss = 0.1934 : val hss = 0.3261
Fold 3: train tss = 0.4275 : val tss = 0.0437 ::: train hss = 0.0768 : val hss = 0.0015
Fold 4: train tss = 0.6129 : val tss = 0.4491 ::: train hss = 0.1323 : val hss = 0.1242
mean cv TSS: 0.2677
mean cv HSS: 0.1085
312/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.2483 : val tss = 0.0038 ::: train hss = 0.2547 : val hss = 0.0052
Fold 1: train tss = 0.8613 : val tss = 0.0890 ::: train hss = 0.2956 : val hss = 0.0398
Fold 2: train tss = 0.7237 : val tss = 0.5090 ::: train hss = 0.1519 : val hss = 0.1336
Fold 3: train tss = 0.7773 : val tss = 0.0650 ::: train hss = 0.2968 : val hss = 0.0206
Fold 4: train tss = 0.7603 : val tss = 0.6045 ::: train hss = 0.2609 : val hss = 0.2175
mean cv TSS: 0.2542
mean cv HSS: 0.0833
313/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = -0.0001 : val tss = -0.0033 ::: train hss = -0.0002 : val hss = -0.0059
Fold 1: train tss = 0.7592 : val tss = 0.3014 ::: train hss = 0.2086 : val hss = 0.1068
Fold 2: train tss = 0.6628 : val tss = 0.7345 ::: train hss = 0.1416 : val hss = 0.3920
Fold 3: train tss = 0.6079 : val tss = 0.0817 ::: train hss = 0.1534 : val hss = 0.0156
Fold 4: train tss = 0.7323 : val tss = 0.6258 ::: train hss = 0.2137 : val hss = 0.2256
mean cv TSS: 0.3480
mean cv HSS: 0.1468
314/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.6932 : val tss = -0.0077 ::: train hss = 0.3081 : val hss = -0.0117
Fold 1: train tss = 0.7096 : val tss = 0.2460 ::: train hss = 0.4532 : val hss = 0.0908
Fold 2: train tss = 0.7609 : val tss = 0.6558 ::: train hss = 0.1910 : val hss = 0.2700
Fold 3: train tss = 0.7991 : val tss = 0.2482 ::: train hss = 0.2889 : val hss = 0.0890
Fold 4: train tss = 0.7767 : val tss = 0.3956 ::: train hss = 0.2625 : val hss = 0.2673
mean cv TSS: 0.3076
mean cv HSS: 0.1411
315/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.4893 : val tss = 0.0000 ::: train hss = 0.1659 : val hss = 0.0000
Fold 1: train tss = 0.7366 : val tss = 0.2309 ::: train hss = 0.2242 : val hss = 0.0806
Fold 2: train tss = 0.6746 : val tss = 0.5954 ::: train hss = 0.1217 : val hss = 0.2152
Fold 3: train tss = 0.6889 : val tss = 0.0798 ::: train hss = 0.1812 : val hss = 0.0202
Fold 4: train tss = 0.6656 : val tss = 0.5551 ::: train hss = 0.1535 : val hss = 0.1499
mean cv TSS: 0.2922
mean cv HSS: 0.0932
316/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.9932 : val tss = -0.0039 ::: train hss = 0.4138 : val hss = -0.0067
Fold 1: train tss = 0.8986 : val tss = 0.1636 ::: train hss = 0.3786 : val hss = 0.1665
Fold 2: train tss = 0.7562 : val tss = 0.6491 ::: train hss = 0.1811 : val hss = 0.3217
Fold 3: train tss = 0.8071 : val tss = 0.2647 ::: train hss = 0.2944 : val hss = 0.0369
Fold 4: train tss = 0.7205 : val tss = 0.4584 ::: train hss = 0.1875 : val hss = 0.1481
mean cv TSS: 0.3064
mean cv HSS: 0.1333
317/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.8707 : val tss = -0.0070 ::: train hss = 0.1253 : val hss = -0.0109
Fold 1: train tss = 0.8503 : val tss = 0.2036 ::: train hss = 0.4345 : val hss = 0.0933
Fold 2: train tss = 0.6331 : val tss = 0.5711 ::: train hss = 0.1423 : val hss = 0.1735
Fold 3: train tss = 0.7222 : val tss = 0.0360 ::: train hss = 0.2052 : val hss = 0.0035
Fold 4: train tss = 0.6094 : val tss = 0.6523 ::: train hss = 0.1241 : val hss = 0.3965
mean cv TSS: 0.2912
mean cv HSS: 0.1312
318/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 534049
Fold 0: train tss = 0.3466 : val tss = -0.0016 ::: train hss = 0.2521 : val hss = -0.0030
Fold 1: train tss = 0.8048 : val tss = 0.1740 ::: train hss = 0.4526 : val hss = 0.1317
Fold 2: train tss = 0.7869 : val tss = 0.6661 ::: train hss = 0.3190 : val hss = 0.2720
Fold 3: train tss = 0.8159 : val tss = 0.1094 ::: train hss = 0.3113 : val hss = 0.0224
Fold 4: train tss = 0.7768 : val tss = 0.6092 ::: train hss = 0.2355 : val hss = 0.2808
mean cv TSS: 0.3114
mean cv HSS: 0.1408
319/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.3429 : val tss = -0.0017 ::: train hss = 0.1595 : val hss = -0.0032
Fold 1: train tss = 0.7874 : val tss = 0.1633 ::: train hss = 0.5613 : val hss = 0.1079
Fold 2: train tss = 0.6474 : val tss = 0.5859 ::: train hss = 0.1296 : val hss = 0.2258
Fold 3: train tss = 0.6499 : val tss = 0.0431 ::: train hss = 0.2230 : val hss = 0.0048
Fold 4: train tss = 0.7170 : val tss = 0.6022 ::: train hss = 0.1841 : val hss = 0.2356
mean cv TSS: 0.2786
mean cv HSS: 0.1142
320/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.5903 : val tss = -0.0053 ::: train hss = 0.2108 : val hss = -0.0088
Fold 1: train tss = 0.8108 : val tss = 0.1044 ::: train hss = 0.5216 : val hss = 0.0517
Fold 2: train tss = 0.8076 : val tss = 0.7219 ::: train hss = 0.2931 : val hss = 0.4307
Fold 3: train tss = 0.8542 : val tss = 0.2714 ::: train hss = 0.3832 : val hss = 0.0687
Fold 4: train tss = 0.8245 : val tss = 0.4384 ::: train hss = 0.3329 : val hss = 0.3118
mean cv TSS: 0.3062
mean cv HSS: 0.1708
321/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.6915 : val tss = -0.0055 ::: train hss = 0.2660 : val hss = -0.0089
Fold 1: train tss = 0.8131 : val tss = 0.1639 ::: train hss = 0.5538 : val hss = 0.0810
Fold 2: train tss = 0.7440 : val tss = 0.7096 ::: train hss = 0.2146 : val hss = 0.4070
Fold 3: train tss = 0.6620 : val tss = 0.2434 ::: train hss = 0.2060 : val hss = 0.0182
Fold 4: train tss = 0.7060 : val tss = 0.5708 ::: train hss = 0.1927 : val hss = 0.1559
mean cv TSS: 0.3364
mean cv HSS: 0.1306
322/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.8944 : val tss = -0.0039 ::: train hss = 0.4259 : val hss = -0.0067
Fold 1: train tss = 0.9155 : val tss = 0.1786 ::: train hss = 0.5797 : val hss = 0.1011
Fold 2: train tss = 0.8466 : val tss = 0.6807 ::: train hss = 0.2840 : val hss = 0.3722
Fold 3: train tss = 0.8186 : val tss = 0.2024 ::: train hss = 0.2684 : val hss = 0.1819
Fold 4: train tss = 0.7972 : val tss = 0.6333 ::: train hss = 0.2585 : val hss = 0.2871
mean cv TSS: 0.3382
mean cv HSS: 0.1871
323/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.7435 : val tss = -0.0039 ::: train hss = 0.3380 : val hss = -0.0067
Fold 1: train tss = 0.9023 : val tss = 0.1627 ::: train hss = 0.5780 : val hss = 0.0751
Fold 2: train tss = 0.8154 : val tss = 0.6597 ::: train hss = 0.2543 : val hss = 0.4011
Fold 3: train tss = 0.8508 : val tss = 0.1803 ::: train hss = 0.3827 : val hss = 0.0554
Fold 4: train tss = 0.7900 : val tss = 0.5325 ::: train hss = 0.2710 : val hss = 0.3285
mean cv TSS: 0.3063
mean cv HSS: 0.1707
324/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.6353 : val tss = -0.0053 ::: train hss = 0.1639 : val hss = -0.0087
Fold 1: train tss = 0.6369 : val tss = 0.3158 ::: train hss = 0.0718 : val hss = 0.0527
Fold 2: train tss = 0.6127 : val tss = 0.4851 ::: train hss = 0.1008 : val hss = 0.1636
Fold 3: train tss = 0.7222 : val tss = 0.2238 ::: train hss = 0.2003 : val hss = 0.0476
Fold 4: train tss = 0.7101 : val tss = 0.5983 ::: train hss = 0.1766 : val hss = 0.1692
mean cv TSS: 0.3235
mean cv HSS: 0.0849
325/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5824 : val tss = 0.3389 ::: train hss = 0.0535 : val hss = 0.0487
Fold 2: train tss = 0.5411 : val tss = 0.6381 ::: train hss = 0.1396 : val hss = 0.2494
Fold 3: train tss = 0.5891 : val tss = 0.1989 ::: train hss = 0.1342 : val hss = 0.0192
Fold 4: train tss = 0.5425 : val tss = 0.5466 ::: train hss = 0.0921 : val hss = 0.1376
mean cv TSS: 0.3445
mean cv HSS: 0.0910
326/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7098 : val tss = -0.0207 ::: train hss = 0.1066 : val hss = -0.0035
Fold 2: train tss = 0.6037 : val tss = 0.5800 ::: train hss = 0.0961 : val hss = 0.1993
Fold 3: train tss = 0.6060 : val tss = 0.0838 ::: train hss = 0.1097 : val hss = 0.0099
Fold 4: train tss = 0.5739 : val tss = 0.6319 ::: train hss = 0.0905 : val hss = 0.1878
mean cv TSS: 0.2550
mean cv HSS: 0.0787
327/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5657 : val tss = 0.2351 ::: train hss = 0.0345 : val hss = 0.0318
Fold 2: train tss = 0.4520 : val tss = 0.4472 ::: train hss = 0.0407 : val hss = 0.0991
Fold 3: train tss = 0.5523 : val tss = 0.3432 ::: train hss = 0.0912 : val hss = 0.0223
Fold 4: train tss = 0.6071 : val tss = 0.6148 ::: train hss = 0.1193 : val hss = 0.1813
mean cv TSS: 0.3281
mean cv HSS: 0.0669
328/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.9603 : val tss = -0.0039 ::: train hss = 0.1052 : val hss = -0.0067
Fold 1: train tss = 0.6813 : val tss = 0.0251 ::: train hss = 0.0655 : val hss = 0.0057
Fold 2: train tss = 0.5179 : val tss = 0.5073 ::: train hss = 0.0467 : val hss = 0.1279
Fold 3: train tss = 0.6643 : val tss = 0.2154 ::: train hss = 0.1305 : val hss = 0.0209
Fold 4: train tss = 0.4952 : val tss = 0.4023 ::: train hss = 0.0646 : val hss = 0.0930
mean cv TSS: 0.2292
mean cv HSS: 0.0482
329/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 2229793
Fold 0: train tss = 0.8780 : val tss = -0.0925 ::: train hss = 0.0338 : val hss = -0.0378
Fold 1: train tss = 0.5518 : val tss = 0.1983 ::: train hss = 0.4907 : val hss = 0.0191
Fold 2: train tss = 0.5329 : val tss = 0.4546 ::: train hss = 0.0525 : val hss = 0.1071
Fold 3: train tss = 0.5672 : val tss = 0.1910 ::: train hss = 0.0968 : val hss = 0.0161
Fold 4: train tss = 0.4638 : val tss = 0.4222 ::: train hss = 0.0563 : val hss = 0.0903
mean cv TSS: 0.2347
mean cv HSS: 0.0390
330/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.9446 : val tss = -0.0109 ::: train hss = 0.4498 : val hss = -0.0151
Fold 1: train tss = 0.7716 : val tss = 0.3906 ::: train hss = 0.1171 : val hss = 0.0947
Fold 2: train tss = 0.6608 : val tss = 0.6449 ::: train hss = 0.2206 : val hss = 0.2359
Fold 3: train tss = 0.7657 : val tss = 0.1531 ::: train hss = 0.3220 : val hss = 0.0309
Fold 4: train tss = 0.6735 : val tss = 0.6751 ::: train hss = 0.1511 : val hss = 0.2332
mean cv TSS: 0.3706
mean cv HSS: 0.1159
331/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.8970 : val tss = -0.0077 ::: train hss = 0.5695 : val hss = -0.0117
Fold 1: train tss = 0.7222 : val tss = 0.2746 ::: train hss = 0.2298 : val hss = 0.1442
Fold 2: train tss = 0.5981 : val tss = 0.6152 ::: train hss = 0.1026 : val hss = 0.2532
Fold 3: train tss = 0.5936 : val tss = 0.3254 ::: train hss = 0.1398 : val hss = 0.0323
Fold 4: train tss = 0.6053 : val tss = 0.6067 ::: train hss = 0.1252 : val hss = 0.1775
mean cv TSS: 0.3628
mean cv HSS: 0.1191
332/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.7985 : val tss = -0.0069 ::: train hss = 0.6655 : val hss = -0.0109
Fold 1: train tss = 0.7224 : val tss = 0.3294 ::: train hss = 0.1550 : val hss = 0.1080
Fold 2: train tss = 0.5975 : val tss = 0.6712 ::: train hss = 0.1120 : val hss = 0.2824
Fold 3: train tss = 0.7659 : val tss = 0.1075 ::: train hss = 0.2115 : val hss = 0.0299
Fold 4: train tss = 0.6626 : val tss = 0.5921 ::: train hss = 0.1378 : val hss = 0.2529
mean cv TSS: 0.3386
mean cv HSS: 0.1325
333/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.9876 : val tss = -0.0006 ::: train hss = 0.2782 : val hss = -0.0012
Fold 1: train tss = 0.7474 : val tss = 0.2291 ::: train hss = 0.2447 : val hss = 0.1149
Fold 2: train tss = 0.5187 : val tss = 0.6470 ::: train hss = 0.0684 : val hss = 0.2912
Fold 3: train tss = 0.5817 : val tss = 0.0929 ::: train hss = 0.1020 : val hss = 0.0170
Fold 4: train tss = 0.4972 : val tss = 0.6149 ::: train hss = 0.0757 : val hss = 0.1943
mean cv TSS: 0.3167
mean cv HSS: 0.1232
334/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.9948 : val tss = -0.0034 ::: train hss = 0.4794 : val hss = -0.0059
Fold 1: train tss = 0.6190 : val tss = 0.1759 ::: train hss = 0.2033 : val hss = 0.0927
Fold 2: train tss = 0.5647 : val tss = 0.5857 ::: train hss = 0.1727 : val hss = 0.2345
Fold 3: train tss = 0.6060 : val tss = 0.1847 ::: train hss = 0.1689 : val hss = 0.0086
Fold 4: train tss = 0.6568 : val tss = 0.5334 ::: train hss = 0.1808 : val hss = 0.1346
mean cv TSS: 0.2953
mean cv HSS: 0.0929
335/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.9866 : val tss = -0.0002 ::: train hss = 0.2631 : val hss = -0.0005
Fold 1: train tss = 0.8073 : val tss = 0.2078 ::: train hss = 0.4802 : val hss = 0.0917
Fold 2: train tss = 0.6661 : val tss = 0.5911 ::: train hss = 0.1628 : val hss = 0.1929
Fold 3: train tss = 0.6269 : val tss = 0.2620 ::: train hss = 0.1481 : val hss = 0.0219
Fold 4: train tss = 0.4812 : val tss = 0.6745 ::: train hss = 0.0932 : val hss = 0.2376
mean cv TSS: 0.3470
mean cv HSS: 0.1087
336/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.3465 : val tss = 0.0065 ::: train hss = 0.2475 : val hss = 0.0097
Fold 1: train tss = 0.7411 : val tss = 0.3273 ::: train hss = 0.3039 : val hss = 0.1045
Fold 2: train tss = 0.7036 : val tss = 0.6701 ::: train hss = 0.1645 : val hss = 0.2641
Fold 3: train tss = 0.7710 : val tss = 0.5898 ::: train hss = 0.2931 : val hss = 0.0549
Fold 4: train tss = 0.7248 : val tss = 0.5831 ::: train hss = 0.2034 : val hss = 0.2554
mean cv TSS: 0.4354
mean cv HSS: 0.1377
337/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7871 : val tss = 0.1650 ::: train hss = 0.3757 : val hss = 0.1885
Fold 2: train tss = 0.7000 : val tss = 0.7068 ::: train hss = 0.1605 : val hss = 0.3567
Fold 3: train tss = 0.6815 : val tss = 0.0465 ::: train hss = 0.1868 : val hss = 0.0111
Fold 4: train tss = 0.6901 : val tss = 0.7269 ::: train hss = 0.1795 : val hss = 0.2986
mean cv TSS: 0.3290
mean cv HSS: 0.1710
338/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7310 : val tss = 0.2282 ::: train hss = 0.2451 : val hss = 0.0813
Fold 2: train tss = 0.6581 : val tss = 0.5916 ::: train hss = 0.2624 : val hss = 0.1874
Fold 3: train tss = 0.7647 : val tss = 0.1106 ::: train hss = 0.2565 : val hss = 0.0351
Fold 4: train tss = 0.6287 : val tss = 0.5835 ::: train hss = 0.1375 : val hss = 0.2161
mean cv TSS: 0.3028
mean cv HSS: 0.1040
339/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.2478 : val tss = -0.0136 ::: train hss = 0.2305 : val hss = -0.0176
Fold 1: train tss = 0.7842 : val tss = 0.2281 ::: train hss = 0.3086 : val hss = 0.0855
Fold 2: train tss = 0.6295 : val tss = 0.6051 ::: train hss = 0.1507 : val hss = 0.2137
Fold 3: train tss = 0.6817 : val tss = 0.0629 ::: train hss = 0.1872 : val hss = 0.0079
Fold 4: train tss = 0.6885 : val tss = 0.6589 ::: train hss = 0.1697 : val hss = 0.2305
mean cv TSS: 0.3083
mean cv HSS: 0.1040
340/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 754209
Fold 0: train tss = 0.0977 : val tss = -0.0011 ::: train hss = 0.0953 : val hss = -0.0022
Fold 1: train tss = 0.8060 : val tss = 0.2512 ::: train hss = 0.3898 : val hss = 0.1374
Fold 2: train tss = 0.7282 : val tss = 0.6673 ::: train hss = 0.2457 : val hss = 0.2767
Fold 3: train tss = 0.7750 : val tss = 0.5789 ::: train hss = 0.2593 : val hss = 0.0495
Fold 4: train tss = 0.7039 : val tss = 0.5747 ::: train hss = 0.2066 : val hss = 0.1695
mean cv TSS: 0.4142
mean cv HSS: 0.1262
341/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.5900 : val tss = -0.0125 ::: train hss = 0.2070 : val hss = -0.0167
Fold 1: train tss = 0.7513 : val tss = 0.2323 ::: train hss = 0.2445 : val hss = 0.1116
Fold 2: train tss = 0.5601 : val tss = 0.6169 ::: train hss = 0.1241 : val hss = 0.2241
Fold 3: train tss = 0.7189 : val tss = 0.1719 ::: train hss = 0.2117 : val hss = 0.0276
Fold 4: train tss = 0.6415 : val tss = 0.5861 ::: train hss = 0.1406 : val hss = 0.1912
mean cv TSS: 0.3189
mean cv HSS: 0.1076
342/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.1493 : val tss = -0.0041 ::: train hss = 0.2059 : val hss = -0.0052
Fold 1: train tss = 0.7685 : val tss = 0.3544 ::: train hss = 0.4355 : val hss = 0.1259
Fold 2: train tss = 0.5946 : val tss = 0.6178 ::: train hss = 0.0961 : val hss = 0.2186
Fold 3: train tss = 0.7670 : val tss = 0.0461 ::: train hss = 0.3016 : val hss = 0.0074
Fold 4: train tss = 0.7330 : val tss = 0.6462 ::: train hss = 0.2190 : val hss = 0.2752
mean cv TSS: 0.3321
mean cv HSS: 0.1244
343/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0496 : val tss = -0.0099 ::: train hss = 0.0827 : val hss = -0.0141
Fold 1: train tss = 0.7952 : val tss = 0.3447 ::: train hss = 0.3453 : val hss = 0.1037
Fold 2: train tss = 0.6606 : val tss = 0.6800 ::: train hss = 0.1991 : val hss = 0.2558
Fold 3: train tss = 0.7511 : val tss = 0.1963 ::: train hss = 0.2543 : val hss = 0.0307
Fold 4: train tss = 0.6720 : val tss = 0.6395 ::: train hss = 0.1788 : val hss = 0.2715
mean cv TSS: 0.3701
mean cv HSS: 0.1295
344/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.3926 : val tss = -0.0741 ::: train hss = 0.1765 : val hss = -0.0354
Fold 1: train tss = 0.7952 : val tss = 0.3078 ::: train hss = 0.4438 : val hss = 0.0828
Fold 2: train tss = 0.7185 : val tss = 0.6695 ::: train hss = 0.2218 : val hss = 0.3101
Fold 3: train tss = 0.7819 : val tss = 0.0432 ::: train hss = 0.2928 : val hss = 0.0077
Fold 4: train tss = 0.6964 : val tss = 0.7431 ::: train hss = 0.1869 : val hss = 0.3329
mean cv TSS: 0.3379
mean cv HSS: 0.1396
345/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.3445 : val tss = -0.0297 ::: train hss = 0.1914 : val hss = -0.0248
Fold 1: train tss = 0.7935 : val tss = 0.2523 ::: train hss = 0.4277 : val hss = 0.0841
Fold 2: train tss = 0.6526 : val tss = 0.7095 ::: train hss = 0.2565 : val hss = 0.3275
Fold 3: train tss = 0.6754 : val tss = 0.3698 ::: train hss = 0.2031 : val hss = 0.0367
Fold 4: train tss = 0.6920 : val tss = 0.6615 ::: train hss = 0.1855 : val hss = 0.2725
mean cv TSS: 0.3927
mean cv HSS: 0.1392
346/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.4457 : val tss = 0.0021 ::: train hss = 0.2786 : val hss = 0.0024
Fold 1: train tss = 0.8169 : val tss = 0.1964 ::: train hss = 0.4452 : val hss = 0.0727
Fold 2: train tss = 0.7589 : val tss = 0.6042 ::: train hss = 0.2050 : val hss = 0.2074
Fold 3: train tss = 0.7984 : val tss = 0.4068 ::: train hss = 0.3374 : val hss = 0.0470
Fold 4: train tss = 0.7513 : val tss = 0.6007 ::: train hss = 0.2609 : val hss = 0.3040
mean cv TSS: 0.3620
mean cv HSS: 0.1267
347/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.4455 : val tss = -0.0129 ::: train hss = 0.2700 : val hss = -0.0150
Fold 1: train tss = 0.8031 : val tss = 0.1628 ::: train hss = 0.5362 : val hss = 0.0541
Fold 2: train tss = 0.7168 : val tss = 0.6607 ::: train hss = 0.3502 : val hss = 0.2952
Fold 3: train tss = 0.7486 : val tss = 0.0386 ::: train hss = 0.2860 : val hss = 0.0071
Fold 4: train tss = 0.7213 : val tss = 0.5687 ::: train hss = 0.2360 : val hss = 0.2323
mean cv TSS: 0.2836
mean cv HSS: 0.1147
348/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6295 : val tss = 0.2903 ::: train hss = 0.0792 : val hss = 0.0699
Fold 2: train tss = 0.5641 : val tss = 0.5016 ::: train hss = 0.0650 : val hss = 0.1201
Fold 3: train tss = 0.5634 : val tss = -0.0048 ::: train hss = 0.0914 : val hss = -0.0007
Fold 4: train tss = 0.5884 : val tss = 0.5772 ::: train hss = 0.1028 : val hss = 0.1538
mean cv TSS: 0.2728
mean cv HSS: 0.0686
349/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5900 : val tss = 0.3194 ::: train hss = 0.1270 : val hss = 0.1098
Fold 2: train tss = 0.5277 : val tss = 0.5263 ::: train hss = 0.0524 : val hss = 0.1437
Fold 3: train tss = 0.5112 : val tss = 0.2528 ::: train hss = 0.0961 : val hss = 0.0303
Fold 4: train tss = 0.5126 : val tss = 0.6137 ::: train hss = 0.0838 : val hss = 0.1788
mean cv TSS: 0.3424
mean cv HSS: 0.0925
350/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.1479 : val tss = -0.0052 ::: train hss = 0.1479 : val hss = -0.0086
Fold 1: train tss = 0.6550 : val tss = 0.1342 ::: train hss = 0.0873 : val hss = 0.0231
Fold 2: train tss = 0.5139 : val tss = 0.5531 ::: train hss = 0.0542 : val hss = 0.1548
Fold 3: train tss = 0.5445 : val tss = 0.1982 ::: train hss = 0.0872 : val hss = 0.0192
Fold 4: train tss = 0.5988 : val tss = 0.4445 ::: train hss = 0.1112 : val hss = 0.1026
mean cv TSS: 0.2649
mean cv HSS: 0.0582
351/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 385569
Fold 0: train tss = 0.2965 : val tss = -0.0078 ::: train hss = 0.2156 : val hss = -0.0119
Fold 1: train tss = 0.6927 : val tss = 0.3290 ::: train hss = 0.1461 : val hss = 0.1112
Fold 2: train tss = 0.5034 : val tss = 0.4862 ::: train hss = 0.0613 : val hss = 0.1141
Fold 3: train tss = 0.6060 : val tss = 0.0514 ::: train hss = 0.1413 : val hss = 0.0111
Fold 4: train tss = 0.5021 : val tss = 0.5801 ::: train hss = 0.0782 : val hss = 0.1596
mean cv TSS: 0.2878
mean cv HSS: 0.0768
352/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.6405 : val tss = -0.0132 ::: train hss = 0.2308 : val hss = -0.0153
Fold 1: train tss = 0.6939 : val tss = 0.0838 ::: train hss = 0.0939 : val hss = 0.0219
Fold 2: train tss = 0.4512 : val tss = 0.2857 ::: train hss = 0.0422 : val hss = 0.0538
Fold 3: train tss = 0.6219 : val tss = 0.2609 ::: train hss = 0.1084 : val hss = 0.0224
Fold 4: train tss = 0.4193 : val tss = 0.3972 ::: train hss = 0.0515 : val hss = 0.0814
mean cv TSS: 0.2029
mean cv HSS: 0.0328
353/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.3174 : val tss = -0.1137 ::: train hss = 0.0432 : val hss = -0.0301
Fold 1: train tss = 0.6811 : val tss = 0.0972 ::: train hss = 0.1103 : val hss = 0.0127
Fold 2: train tss = 0.4012 : val tss = 0.4801 ::: train hss = 0.0328 : val hss = 0.1132
Fold 3: train tss = 0.3154 : val tss = 0.2328 ::: train hss = 0.0366 : val hss = 0.0118
Fold 4: train tss = 0.3503 : val tss = 0.3177 ::: train hss = 0.0434 : val hss = 0.0575
mean cv TSS: 0.2028
mean cv HSS: 0.0330
354/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.7779 : val tss = -0.0576 ::: train hss = 0.1421 : val hss = -0.0278
Fold 1: train tss = 0.7660 : val tss = 0.3215 ::: train hss = 0.3779 : val hss = 0.1261
Fold 2: train tss = 0.5595 : val tss = 0.6121 ::: train hss = 0.2429 : val hss = 0.2096
Fold 3: train tss = 0.7494 : val tss = 0.4068 ::: train hss = 0.2760 : val hss = 0.0466
Fold 4: train tss = 0.6997 : val tss = 0.6433 ::: train hss = 0.1686 : val hss = 0.2147
mean cv TSS: 0.3852
mean cv HSS: 0.1138
355/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.5401 : val tss = -0.0757 ::: train hss = 0.1912 : val hss = -0.0286
Fold 1: train tss = 0.5457 : val tss = 0.3296 ::: train hss = 0.0917 : val hss = 0.0550
Fold 2: train tss = 0.6658 : val tss = 0.7332 ::: train hss = 0.1458 : val hss = 0.3715
Fold 3: train tss = 0.5538 : val tss = 0.1066 ::: train hss = 0.1111 : val hss = 0.0178
Fold 4: train tss = 0.5804 : val tss = 0.6142 ::: train hss = 0.1162 : val hss = 0.1791
mean cv TSS: 0.3416
mean cv HSS: 0.1190
356/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.7421 : val tss = -0.0236 ::: train hss = 0.2969 : val hss = -0.0219
Fold 1: train tss = 0.4455 : val tss = 0.1016 ::: train hss = 0.3853 : val hss = 0.0530
Fold 2: train tss = 0.5454 : val tss = 0.5605 ::: train hss = 0.1143 : val hss = 0.2021
Fold 3: train tss = 0.7127 : val tss = 0.2443 ::: train hss = 0.1991 : val hss = 0.0369
Fold 4: train tss = 0.7172 : val tss = 0.6554 ::: train hss = 0.1680 : val hss = 0.2410
mean cv TSS: 0.3076
mean cv HSS: 0.1022
357/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.6351 : val tss = -0.0392 ::: train hss = 0.1628 : val hss = -0.0246
Fold 1: train tss = 0.7738 : val tss = 0.2128 ::: train hss = 0.4459 : val hss = 0.1131
Fold 2: train tss = 0.3664 : val tss = 0.4417 ::: train hss = 0.0964 : val hss = 0.0999
Fold 3: train tss = 0.1110 : val tss = 0.4364 ::: train hss = 0.0100 : val hss = 0.0201
Fold 4: train tss = 0.5837 : val tss = 0.6254 ::: train hss = 0.1135 : val hss = 0.1927
mean cv TSS: 0.3354
mean cv HSS: 0.0802
358/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.9634 : val tss = -0.0469 ::: train hss = 0.1133 : val hss = -0.0327
Fold 1: train tss = 0.7775 : val tss = 0.1568 ::: train hss = 0.6192 : val hss = 0.0632
Fold 2: train tss = 0.6600 : val tss = 0.5000 ::: train hss = 0.2415 : val hss = 0.1344
Fold 3: train tss = 0.7298 : val tss = 0.1267 ::: train hss = 0.3920 : val hss = 0.0154
Fold 4: train tss = 0.5955 : val tss = 0.6545 ::: train hss = 0.2022 : val hss = 0.2308
mean cv TSS: 0.2782
mean cv HSS: 0.0822
359/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.8434 : val tss = -0.0135 ::: train hss = 0.3707 : val hss = -0.0126
Fold 1: train tss = 0.8043 : val tss = 0.2017 ::: train hss = 0.5537 : val hss = 0.0826
Fold 2: train tss = 0.6887 : val tss = 0.6676 ::: train hss = 0.2315 : val hss = 0.3190
Fold 3: train tss = 0.5930 : val tss = 0.1845 ::: train hss = 0.1304 : val hss = 0.0171
Fold 4: train tss = 0.5407 : val tss = 0.4435 ::: train hss = 0.1065 : val hss = 0.0973
mean cv TSS: 0.2968
mean cv HSS: 0.1007
360/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0489 : val tss = 0.0067 ::: train hss = 0.0652 : val hss = 0.0099
Fold 1: train tss = 0.7432 : val tss = 0.1742 ::: train hss = 0.2933 : val hss = 0.0709
Fold 2: train tss = 0.6772 : val tss = 0.7027 ::: train hss = 0.1542 : val hss = 0.2987
Fold 3: train tss = 0.7768 : val tss = 0.3146 ::: train hss = 0.2594 : val hss = 0.0424
Fold 4: train tss = 0.7228 : val tss = 0.5835 ::: train hss = 0.2017 : val hss = 0.1645
mean cv TSS: 0.3563
mean cv HSS: 0.1173
361/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7700 : val tss = 0.1803 ::: train hss = 0.3006 : val hss = 0.0808
Fold 2: train tss = 0.6752 : val tss = 0.7163 ::: train hss = 0.1393 : val hss = 0.3116
Fold 3: train tss = 0.6827 : val tss = 0.2614 ::: train hss = 0.1828 : val hss = 0.0211
Fold 4: train tss = 0.6083 : val tss = 0.6115 ::: train hss = 0.1219 : val hss = 0.1793
mean cv TSS: 0.3539
mean cv HSS: 0.1185
362/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 1123873
Fold 0: train tss = 0.5403 : val tss = -0.0375 ::: train hss = 0.1947 : val hss = -0.0299
Fold 1: train tss = 0.7847 : val tss = 0.3171 ::: train hss = 0.3335 : val hss = 0.1048
Fold 2: train tss = 0.7083 : val tss = 0.6459 ::: train hss = 0.2063 : val hss = 0.2512
Fold 3: train tss = 0.7703 : val tss = 0.4159 ::: train hss = 0.2947 : val hss = 0.0517
Fold 4: train tss = 0.7123 : val tss = 0.6636 ::: train hss = 0.1807 : val hss = 0.2390
mean cv TSS: 0.4010
mean cv HSS: 0.1234
363/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7831 : val tss = 0.1751 ::: train hss = 0.3493 : val hss = 0.0796
Fold 2: train tss = 0.6619 : val tss = 0.6076 ::: train hss = 0.1528 : val hss = 0.2042
Fold 3: train tss = 0.6881 : val tss = 0.1891 ::: train hss = 0.1876 : val hss = 0.0271
Fold 4: train tss = 0.6630 : val tss = 0.5300 ::: train hss = 0.1693 : val hss = 0.1343
mean cv TSS: 0.3004
mean cv HSS: 0.0890
364/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.6448 : val tss = -0.0097 ::: train hss = 0.3393 : val hss = -0.0140
Fold 1: train tss = 0.8650 : val tss = 0.2312 ::: train hss = 0.3124 : val hss = 0.1183
Fold 2: train tss = 0.6673 : val tss = 0.5609 ::: train hss = 0.1367 : val hss = 0.1994
Fold 3: train tss = 0.7301 : val tss = 0.4464 ::: train hss = 0.2220 : val hss = 0.0281
Fold 4: train tss = 0.7335 : val tss = 0.5625 ::: train hss = 0.1982 : val hss = 0.2054
mean cv TSS: 0.3582
mean cv HSS: 0.1074
365/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.4400 : val tss = -0.0557 ::: train hss = 0.1586 : val hss = -0.0346
Fold 1: train tss = 0.6854 : val tss = 0.1426 ::: train hss = 0.1419 : val hss = 0.0376
Fold 2: train tss = 0.6104 : val tss = 0.5369 ::: train hss = 0.1336 : val hss = 0.1496
Fold 3: train tss = 0.6452 : val tss = 0.3169 ::: train hss = 0.1390 : val hss = 0.0212
Fold 4: train tss = 0.6657 : val tss = 0.5504 ::: train hss = 0.1562 : val hss = 0.1944
mean cv TSS: 0.2982
mean cv HSS: 0.0736
366/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.3408 : val tss = -0.0489 ::: train hss = 0.1324 : val hss = -0.0289
Fold 1: train tss = 0.7748 : val tss = 0.2284 ::: train hss = 0.3797 : val hss = 0.0631
Fold 2: train tss = 0.6241 : val tss = 0.6033 ::: train hss = 0.1065 : val hss = 0.2059
Fold 3: train tss = 0.7815 : val tss = 0.3399 ::: train hss = 0.2977 : val hss = 0.0498
Fold 4: train tss = 0.7313 : val tss = 0.6380 ::: train hss = 0.2132 : val hss = 0.2523
mean cv TSS: 0.3521
mean cv HSS: 0.1084
367/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.3442 : val tss = -0.0659 ::: train hss = 0.1836 : val hss = -0.0294
Fold 1: train tss = 0.7758 : val tss = 0.3684 ::: train hss = 0.3870 : val hss = 0.1542
Fold 2: train tss = 0.7065 : val tss = 0.7244 ::: train hss = 0.2086 : val hss = 0.3451
Fold 3: train tss = 0.7258 : val tss = 0.1410 ::: train hss = 0.2172 : val hss = 0.0278
Fold 4: train tss = 0.6980 : val tss = 0.6242 ::: train hss = 0.1693 : val hss = 0.1990
mean cv TSS: 0.3584
mean cv HSS: 0.1394
368/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.4898 : val tss = -0.0924 ::: train hss = 0.1719 : val hss = -0.0322
Fold 1: train tss = 0.7803 : val tss = 0.2616 ::: train hss = 0.4693 : val hss = 0.0957
Fold 2: train tss = 0.7282 : val tss = 0.5924 ::: train hss = 0.2749 : val hss = 0.1907
Fold 3: train tss = 0.7620 : val tss = 0.4754 ::: train hss = 0.2930 : val hss = 0.0465
Fold 4: train tss = 0.7411 : val tss = 0.5331 ::: train hss = 0.2031 : val hss = 0.1913
mean cv TSS: 0.3540
mean cv HSS: 0.0984
369/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.4902 : val tss = -0.0188 ::: train hss = 0.1766 : val hss = -0.0056
Fold 1: train tss = 0.7844 : val tss = 0.2565 ::: train hss = 0.4667 : val hss = 0.0871
Fold 2: train tss = 0.7262 : val tss = 0.6805 ::: train hss = 0.2119 : val hss = 0.2923
Fold 3: train tss = 0.7624 : val tss = 0.1668 ::: train hss = 0.3016 : val hss = 0.0258
Fold 4: train tss = 0.7272 : val tss = 0.6145 ::: train hss = 0.2247 : val hss = 0.1924
mean cv TSS: 0.3399
mean cv HSS: 0.1184
370/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.4437 : val tss = -0.0204 ::: train hss = 0.2191 : val hss = -0.0202
Fold 1: train tss = 0.8101 : val tss = 0.2012 ::: train hss = 0.5137 : val hss = 0.0871
Fold 2: train tss = 0.7146 : val tss = 0.6023 ::: train hss = 0.1467 : val hss = 0.1961
Fold 3: train tss = 0.8139 : val tss = 0.2711 ::: train hss = 0.3494 : val hss = 0.0328
Fold 4: train tss = 0.6498 : val tss = 0.5612 ::: train hss = 0.1340 : val hss = 0.1590
mean cv TSS: 0.3231
mean cv HSS: 0.0910
371/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.4465 : val tss = -0.0125 ::: train hss = 0.3079 : val hss = -0.0167
Fold 1: train tss = 0.8176 : val tss = 0.1862 ::: train hss = 0.4984 : val hss = 0.0703
Fold 2: train tss = 0.7524 : val tss = 0.6355 ::: train hss = 0.1765 : val hss = 0.2256
Fold 3: train tss = 0.7709 : val tss = 0.3351 ::: train hss = 0.3833 : val hss = 0.0361
Fold 4: train tss = 0.7697 : val tss = 0.4672 ::: train hss = 0.2863 : val hss = 0.1577
mean cv TSS: 0.3223
mean cv HSS: 0.0946
372/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5539 : val tss = 0.2943 ::: train hss = 0.0457 : val hss = 0.0442
Fold 2: train tss = 0.5132 : val tss = 0.4718 ::: train hss = 0.0545 : val hss = 0.1345
Fold 3: train tss = 0.5937 : val tss = 0.1339 ::: train hss = 0.1083 : val hss = 0.0211
Fold 4: train tss = 0.5136 : val tss = 0.5703 ::: train hss = 0.0702 : val hss = 0.1573
mean cv TSS: 0.2940
mean cv HSS: 0.0714
373/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5682 : val tss = 0.2218 ::: train hss = 0.1587 : val hss = 0.0507
Fold 2: train tss = 0.5474 : val tss = 0.6174 ::: train hss = 0.0765 : val hss = 0.2057
Fold 3: train tss = 0.5159 : val tss = 0.2045 ::: train hss = 0.0801 : val hss = 0.0129
Fold 4: train tss = 0.4172 : val tss = 0.5084 ::: train hss = 0.0636 : val hss = 0.1188
mean cv TSS: 0.3104
mean cv HSS: 0.0776
374/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.1942 : val tss = 0.0144 ::: train hss = 0.1079 : val hss = 0.0279
Fold 1: train tss = 0.6672 : val tss = 0.1351 ::: train hss = 0.0695 : val hss = 0.0189
Fold 2: train tss = 0.4716 : val tss = 0.4046 ::: train hss = 0.0385 : val hss = 0.0854
Fold 3: train tss = 0.5025 : val tss = 0.1024 ::: train hss = 0.0715 : val hss = 0.0072
Fold 4: train tss = 0.6548 : val tss = 0.7237 ::: train hss = 0.1584 : val hss = 0.3329
mean cv TSS: 0.2761
mean cv HSS: 0.0945
375/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5887 : val tss = 0.2453 ::: train hss = 0.0452 : val hss = 0.0340
Fold 2: train tss = 0.4537 : val tss = 0.4580 ::: train hss = 0.0412 : val hss = 0.1105
Fold 3: train tss = 0.5180 : val tss = 0.4708 ::: train hss = 0.0787 : val hss = 0.0287
Fold 4: train tss = 0.4961 : val tss = 0.5512 ::: train hss = 0.0706 : val hss = 0.1425
mean cv TSS: 0.3451
mean cv HSS: 0.0631
376/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.6526 : val tss = -0.0773 ::: train hss = 0.0313 : val hss = -0.0217
Fold 1: train tss = 0.6417 : val tss = 0.1047 ::: train hss = 0.0557 : val hss = 0.0224
Fold 2: train tss = 0.3271 : val tss = 0.4339 ::: train hss = 0.0203 : val hss = 0.1129
Fold 3: train tss = 0.5922 : val tss = -0.0508 ::: train hss = 0.0982 : val hss = -0.0034
Fold 4: train tss = 0.4997 : val tss = 0.5589 ::: train hss = 0.0643 : val hss = 0.1483
mean cv TSS: 0.1939
mean cv HSS: 0.0517
377/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.3760 : val tss = -0.0215 ::: train hss = 0.0668 : val hss = -0.0190
Fold 1: train tss = 0.6611 : val tss = -0.1027 ::: train hss = 0.0699 : val hss = -0.0164
Fold 2: train tss = 0.4842 : val tss = 0.4574 ::: train hss = 0.0461 : val hss = 0.1112
Fold 3: train tss = 0.4047 : val tss = 0.2329 ::: train hss = 0.0506 : val hss = 0.0084
Fold 4: train tss = 0.3449 : val tss = 0.3253 ::: train hss = 0.0373 : val hss = 0.0603
mean cv TSS: 0.1783
mean cv HSS: 0.0289
378/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.6399 : val tss = -0.0359 ::: train hss = 0.2188 : val hss = -0.0220
Fold 1: train tss = 0.7226 : val tss = 0.3944 ::: train hss = 0.2952 : val hss = 0.1156
Fold 2: train tss = 0.5928 : val tss = 0.5846 ::: train hss = 0.0938 : val hss = 0.2015
Fold 3: train tss = 0.7392 : val tss = 0.1096 ::: train hss = 0.1921 : val hss = 0.0260
Fold 4: train tss = 0.7311 : val tss = 0.6056 ::: train hss = 0.1951 : val hss = 0.1762
mean cv TSS: 0.3317
mean cv HSS: 0.0995
379/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.7814 : val tss = -0.0312 ::: train hss = 0.1645 : val hss = -0.0253
Fold 1: train tss = 0.5923 : val tss = 0.3220 ::: train hss = 0.0744 : val hss = 0.0490
Fold 2: train tss = 0.6374 : val tss = 0.7517 ::: train hss = 0.1187 : val hss = 0.4376
Fold 3: train tss = 0.4582 : val tss = 0.0919 ::: train hss = 0.0628 : val hss = 0.0140
Fold 4: train tss = 0.5704 : val tss = 0.4594 ::: train hss = 0.1171 : val hss = 0.1025
mean cv TSS: 0.3188
mean cv HSS: 0.1156
380/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.9234 : val tss = -0.0175 ::: train hss = 0.1426 : val hss = -0.0151
Fold 1: train tss = 0.7789 : val tss = 0.1699 ::: train hss = 0.5033 : val hss = 0.0653
Fold 2: train tss = 0.6964 : val tss = 0.6425 ::: train hss = 0.1409 : val hss = 0.2568
Fold 3: train tss = 0.7631 : val tss = 0.3429 ::: train hss = 0.3112 : val hss = 0.0512
Fold 4: train tss = 0.7697 : val tss = 0.6528 ::: train hss = 0.2539 : val hss = 0.2301
mean cv TSS: 0.3581
mean cv HSS: 0.1177
381/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.9203 : val tss = -0.0218 ::: train hss = 0.1296 : val hss = -0.0232
Fold 1: train tss = 0.6087 : val tss = 0.2604 ::: train hss = 0.0792 : val hss = 0.0351
Fold 2: train tss = 0.5078 : val tss = 0.4692 ::: train hss = 0.0568 : val hss = 0.1202
Fold 3: train tss = 0.6321 : val tss = 0.2396 ::: train hss = 0.1561 : val hss = 0.0634
Fold 4: train tss = 0.5051 : val tss = 0.5800 ::: train hss = 0.0832 : val hss = 0.1579
mean cv TSS: 0.3055
mean cv HSS: 0.0707
382/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.9839 : val tss = -0.0080 ::: train hss = 0.2288 : val hss = -0.0093
Fold 1: train tss = 0.8716 : val tss = 0.1003 ::: train hss = 0.5785 : val hss = 0.0578
Fold 2: train tss = 0.6277 : val tss = 0.6103 ::: train hss = 0.1144 : val hss = 0.2324
Fold 3: train tss = 0.7504 : val tss = 0.3943 ::: train hss = 0.2925 : val hss = 0.0355
Fold 4: train tss = 0.6980 : val tss = 0.5462 ::: train hss = 0.2665 : val hss = 0.3721
mean cv TSS: 0.3286
mean cv HSS: 0.1377
383/768
{'batch_size': 3584, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.9356 : val tss = -0.0052 ::: train hss = 0.2384 : val hss = -0.0087
Fold 1: train tss = 0.7849 : val tss = 0.1517 ::: train hss = 0.5930 : val hss = 0.0630
Fold 2: train tss = 0.4738 : val tss = 0.5524 ::: train hss = 0.1754 : val hss = 0.1912
Fold 3: train tss = 0.7040 : val tss = 0.3146 ::: train hss = 0.2375 : val hss = 0.0205
Fold 4: train tss = 0.5645 : val tss = 0.2411 ::: train hss = 0.1090 : val hss = 0.0402
mean cv TSS: 0.2509
mean cv HSS: 0.0612
384/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7595 : val tss = 0.1440 ::: train hss = 0.5363 : val hss = 0.1149
Fold 2: train tss = 0.6682 : val tss = 0.5909 ::: train hss = 0.2623 : val hss = 0.3112
Fold 3: train tss = 0.6941 : val tss = -0.0076 ::: train hss = 0.2579 : val hss = -0.0068
Fold 4: train tss = 0.7304 : val tss = 0.6667 ::: train hss = 0.3603 : val hss = 0.2933
mean cv TSS: 0.2788
mean cv HSS: 0.1425
385/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7365 : val tss = 0.1849 ::: train hss = 0.5192 : val hss = 0.1514
Fold 2: train tss = 0.5911 : val tss = 0.4709 ::: train hss = 0.2628 : val hss = 0.4532
Fold 3: train tss = 0.7158 : val tss = 0.0304 ::: train hss = 0.4154 : val hss = 0.0217
Fold 4: train tss = 0.6331 : val tss = 0.6822 ::: train hss = 0.3217 : val hss = 0.3702
mean cv TSS: 0.2737
mean cv HSS: 0.1993
386/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7668 : val tss = 0.0919 ::: train hss = 0.5834 : val hss = 0.0460
Fold 2: train tss = 0.4834 : val tss = 0.5593 ::: train hss = 0.3485 : val hss = 0.4472
Fold 3: train tss = 0.7774 : val tss = 0.0014 ::: train hss = 0.3969 : val hss = 0.0008
Fold 4: train tss = 0.7069 : val tss = 0.5917 ::: train hss = 0.3847 : val hss = 0.4404
mean cv TSS: 0.2489
mean cv HSS: 0.1869
387/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7652 : val tss = 0.3223 ::: train hss = 0.2636 : val hss = 0.1090
Fold 2: train tss = 0.6568 : val tss = 0.5141 ::: train hss = 0.3086 : val hss = 0.5011
Fold 3: train tss = 0.7174 : val tss = -0.0054 ::: train hss = 0.3657 : val hss = -0.0053
Fold 4: train tss = 0.5779 : val tss = 0.5990 ::: train hss = 0.2415 : val hss = 0.4218
mean cv TSS: 0.2860
mean cv HSS: 0.2053
388/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8120 : val tss = 0.1997 ::: train hss = 0.6062 : val hss = 0.1303
Fold 2: train tss = 0.6856 : val tss = 0.7089 ::: train hss = 0.3679 : val hss = 0.4715
Fold 3: train tss = 0.8185 : val tss = 0.0189 ::: train hss = 0.5011 : val hss = 0.0060
Fold 4: train tss = 0.7758 : val tss = 0.5936 ::: train hss = 0.4343 : val hss = 0.3955
mean cv TSS: 0.3042
mean cv HSS: 0.2007
389/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6911 : val tss = 0.1425 ::: train hss = 0.3624 : val hss = 0.0741
Fold 2: train tss = 0.4594 : val tss = 0.6637 ::: train hss = 0.3916 : val hss = 0.4100
Fold 3: train tss = 0.7082 : val tss = -0.0058 ::: train hss = 0.3131 : val hss = -0.0081
Fold 4: train tss = 0.6100 : val tss = 0.6144 ::: train hss = 0.3110 : val hss = 0.3934
mean cv TSS: 0.2830
mean cv HSS: 0.1739
390/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6800 : val tss = 0.2958 ::: train hss = 0.3427 : val hss = 0.1271
Fold 2: train tss = 0.5562 : val tss = 0.6025 ::: train hss = 0.3567 : val hss = 0.4486
Fold 3: train tss = 0.7421 : val tss = 0.0158 ::: train hss = 0.4168 : val hss = 0.0098
Fold 4: train tss = 0.7029 : val tss = 0.6052 ::: train hss = 0.3859 : val hss = 0.3654
mean cv TSS: 0.3039
mean cv HSS: 0.1902
391/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7439 : val tss = -0.0163 ::: train hss = 0.6498 : val hss = -0.0142
Fold 2: train tss = 0.4778 : val tss = 0.5517 ::: train hss = 0.3145 : val hss = 0.4648
Fold 3: train tss = 0.7104 : val tss = 0.0483 ::: train hss = 0.3488 : val hss = 0.0449
Fold 4: train tss = 0.6475 : val tss = 0.6460 ::: train hss = 0.3623 : val hss = 0.3006
mean cv TSS: 0.2459
mean cv HSS: 0.1592
392/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7560 : val tss = 0.1845 ::: train hss = 0.6281 : val hss = 0.0889
Fold 2: train tss = 0.6192 : val tss = 0.5491 ::: train hss = 0.3402 : val hss = 0.4843
Fold 3: train tss = 0.7306 : val tss = 0.0563 ::: train hss = 0.4449 : val hss = 0.0315
Fold 4: train tss = 0.7306 : val tss = 0.4597 ::: train hss = 0.4208 : val hss = 0.3251
mean cv TSS: 0.2499
mean cv HSS: 0.1860
393/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7582 : val tss = 0.2491 ::: train hss = 0.5180 : val hss = 0.1159
Fold 2: train tss = 0.5480 : val tss = 0.6224 ::: train hss = 0.3130 : val hss = 0.4566
Fold 3: train tss = 0.7291 : val tss = -0.0062 ::: train hss = 0.4350 : val hss = -0.0086
Fold 4: train tss = 0.6790 : val tss = 0.7493 ::: train hss = 0.3764 : val hss = 0.3628
mean cv TSS: 0.3229
mean cv HSS: 0.1854
394/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7772 : val tss = 0.2026 ::: train hss = 0.6135 : val hss = 0.1315
Fold 2: train tss = 0.5662 : val tss = 0.6584 ::: train hss = 0.3881 : val hss = 0.4617
Fold 3: train tss = 0.7940 : val tss = 0.0392 ::: train hss = 0.4725 : val hss = 0.0280
Fold 4: train tss = 0.7476 : val tss = 0.6500 ::: train hss = 0.4424 : val hss = 0.4301
mean cv TSS: 0.3100
mean cv HSS: 0.2103
395/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7524 : val tss = 0.1821 ::: train hss = 0.6445 : val hss = 0.0868
Fold 2: train tss = 0.6483 : val tss = 0.4416 ::: train hss = 0.4186 : val hss = 0.4710
Fold 3: train tss = 0.7637 : val tss = -0.0002 ::: train hss = 0.4769 : val hss = -0.0005
Fold 4: train tss = 0.7134 : val tss = 0.6625 ::: train hss = 0.3909 : val hss = 0.2319
mean cv TSS: 0.2572
mean cv HSS: 0.1579
396/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7519 : val tss = 0.2517 ::: train hss = 0.3402 : val hss = 0.1138
Fold 2: train tss = 0.4548 : val tss = 0.5990 ::: train hss = 0.2426 : val hss = 0.4425
Fold 3: train tss = 0.6347 : val tss = -0.0154 ::: train hss = 0.2650 : val hss = -0.0110
Fold 4: train tss = 0.7439 : val tss = 0.6620 ::: train hss = 0.3239 : val hss = 0.3480
mean cv TSS: 0.2995
mean cv HSS: 0.1786
397/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6129 : val tss = 0.3608 ::: train hss = 0.2709 : val hss = 0.1832
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5153 : val tss = 0.0948 ::: train hss = 0.1980 : val hss = 0.0347
Fold 4: train tss = 0.4553 : val tss = 0.7836 ::: train hss = 0.1708 : val hss = 0.4320
mean cv TSS: 0.2478
mean cv HSS: 0.1300
398/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6673 : val tss = 0.1884 ::: train hss = 0.1831 : val hss = 0.0444
Fold 2: train tss = 0.5595 : val tss = 0.5694 ::: train hss = 0.1995 : val hss = 0.4537
Fold 3: train tss = 0.7021 : val tss = 0.1491 ::: train hss = 0.2741 : val hss = 0.0545
Fold 4: train tss = 0.6791 : val tss = 0.6105 ::: train hss = 0.2829 : val hss = 0.3358
mean cv TSS: 0.3035
mean cv HSS: 0.1777
399/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5872 : val tss = 0.2753 ::: train hss = 0.2174 : val hss = 0.1079
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6061 : val tss = 0.0731 ::: train hss = 0.2843 : val hss = 0.0486
Fold 4: train tss = 0.4556 : val tss = 0.5952 ::: train hss = 0.1403 : val hss = 0.3315
mean cv TSS: 0.1887
mean cv HSS: 0.0976
400/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7794 : val tss = 0.1227 ::: train hss = 0.3065 : val hss = 0.0488
Fold 2: train tss = 0.0427 : val tss = -0.1653 ::: train hss = 0.0776 : val hss = -0.0540
Fold 3: train tss = 0.6346 : val tss = 0.2266 ::: train hss = 0.2727 : val hss = 0.0300
Fold 4: train tss = 0.6449 : val tss = 0.5800 ::: train hss = 0.3133 : val hss = 0.4444
mean cv TSS: 0.1528
mean cv HSS: 0.0938
401/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6891 : val tss = 0.0010 ::: train hss = 0.2590 : val hss = 0.0002
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5839 : val tss = 0.0170 ::: train hss = 0.2084 : val hss = 0.0110
Fold 4: train tss = 0.3192 : val tss = 0.5696 ::: train hss = 0.1597 : val hss = 0.3678
mean cv TSS: 0.1175
mean cv HSS: 0.0758
402/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7638 : val tss = 0.3061 ::: train hss = 0.4323 : val hss = 0.1287
Fold 2: train tss = 0.6325 : val tss = 0.6226 ::: train hss = 0.3738 : val hss = 0.4808
Fold 3: train tss = 0.6939 : val tss = 0.0908 ::: train hss = 0.3453 : val hss = 0.0282
Fold 4: train tss = 0.7619 : val tss = 0.5911 ::: train hss = 0.3584 : val hss = 0.4504
mean cv TSS: 0.3221
mean cv HSS: 0.2176
403/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7220 : val tss = 0.3494 ::: train hss = 0.3391 : val hss = 0.1370
Fold 2: train tss = 0.3634 : val tss = 0.4985 ::: train hss = 0.2049 : val hss = 0.3710
Fold 3: train tss = 0.6350 : val tss = 0.0470 ::: train hss = 0.3310 : val hss = 0.0262
Fold 4: train tss = 0.5567 : val tss = 0.6835 ::: train hss = 0.2537 : val hss = 0.2556
mean cv TSS: 0.3157
mean cv HSS: 0.1579
404/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7523 : val tss = 0.1442 ::: train hss = 0.4476 : val hss = 0.0971
Fold 2: train tss = 0.6729 : val tss = 0.5502 ::: train hss = 0.2484 : val hss = 0.3450
Fold 3: train tss = 0.7012 : val tss = 0.0693 ::: train hss = 0.3787 : val hss = 0.0422
Fold 4: train tss = 0.7471 : val tss = 0.6808 ::: train hss = 0.4131 : val hss = 0.4132
mean cv TSS: 0.2889
mean cv HSS: 0.1795
405/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6538 : val tss = 0.2037 ::: train hss = 0.4105 : val hss = 0.1152
Fold 2: train tss = 0.5163 : val tss = 0.5057 ::: train hss = 0.1323 : val hss = 0.2568
Fold 3: train tss = 0.6671 : val tss = 0.0428 ::: train hss = 0.3575 : val hss = 0.0336
Fold 4: train tss = 0.6256 : val tss = 0.7335 ::: train hss = 0.3157 : val hss = 0.3564
mean cv TSS: 0.2972
mean cv HSS: 0.1524
406/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7677 : val tss = 0.1417 ::: train hss = 0.6911 : val hss = 0.0568
Fold 2: train tss = 0.6058 : val tss = 0.5190 ::: train hss = 0.4188 : val hss = 0.5168
Fold 3: train tss = 0.7051 : val tss = -0.0267 ::: train hss = 0.4206 : val hss = -0.0125
Fold 4: train tss = 0.7656 : val tss = 0.6649 ::: train hss = 0.4627 : val hss = 0.3699
mean cv TSS: 0.2598
mean cv HSS: 0.1862
407/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7716 : val tss = 0.1455 ::: train hss = 0.6794 : val hss = 0.0773
Fold 2: train tss = 0.2829 : val tss = 0.2575 ::: train hss = 0.3429 : val hss = 0.3270
Fold 3: train tss = 0.7091 : val tss = -0.0072 ::: train hss = 0.4602 : val hss = -0.0065
Fold 4: train tss = 0.5994 : val tss = 0.5312 ::: train hss = 0.2756 : val hss = 0.4269
mean cv TSS: 0.1854
mean cv HSS: 0.1649
408/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7690 : val tss = 0.0048 ::: train hss = 0.6225 : val hss = 0.0062
Fold 2: train tss = 0.6288 : val tss = 0.6212 ::: train hss = 0.4179 : val hss = 0.4452
Fold 3: train tss = 0.7831 : val tss = 0.0586 ::: train hss = 0.4659 : val hss = 0.0246
Fold 4: train tss = 0.7354 : val tss = 0.6101 ::: train hss = 0.3629 : val hss = 0.3671
mean cv TSS: 0.2589
mean cv HSS: 0.1686
409/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7479 : val tss = 0.1307 ::: train hss = 0.6406 : val hss = 0.0944
Fold 2: train tss = 0.3585 : val tss = 0.5971 ::: train hss = 0.1393 : val hss = 0.3798
Fold 3: train tss = 0.7444 : val tss = -0.0192 ::: train hss = 0.3988 : val hss = -0.0159
Fold 4: train tss = 0.6558 : val tss = 0.5138 ::: train hss = 0.2880 : val hss = 0.3979
mean cv TSS: 0.2445
mean cv HSS: 0.1712
410/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7603 : val tss = 0.1750 ::: train hss = 0.4884 : val hss = 0.1989
Fold 2: train tss = 0.7046 : val tss = 0.6458 ::: train hss = 0.3580 : val hss = 0.4950
Fold 3: train tss = 0.7742 : val tss = 0.1216 ::: train hss = 0.3862 : val hss = 0.0395
Fold 4: train tss = 0.7082 : val tss = 0.5395 ::: train hss = 0.3482 : val hss = 0.3073
mean cv TSS: 0.2964
mean cv HSS: 0.2081
411/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7517 : val tss = 0.2097 ::: train hss = 0.3675 : val hss = 0.0876
Fold 2: train tss = 0.2075 : val tss = 0.6297 ::: train hss = 0.1532 : val hss = 0.3530
Fold 3: train tss = 0.6801 : val tss = 0.0050 ::: train hss = 0.3430 : val hss = 0.0019
Fold 4: train tss = 0.6423 : val tss = 0.6722 ::: train hss = 0.2705 : val hss = 0.3437
mean cv TSS: 0.3033
mean cv HSS: 0.1572
412/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7727 : val tss = 0.2059 ::: train hss = 0.6110 : val hss = 0.1159
Fold 2: train tss = 0.6987 : val tss = 0.5560 ::: train hss = 0.3636 : val hss = 0.4544
Fold 3: train tss = 0.7697 : val tss = 0.2564 ::: train hss = 0.4747 : val hss = 0.0442
Fold 4: train tss = 0.7909 : val tss = 0.5834 ::: train hss = 0.4603 : val hss = 0.3168
mean cv TSS: 0.3204
mean cv HSS: 0.1863
413/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8280 : val tss = 0.0822 ::: train hss = 0.3392 : val hss = 0.0695
Fold 2: train tss = 0.3577 : val tss = 0.4771 ::: train hss = 0.3169 : val hss = 0.3509
Fold 3: train tss = 0.7661 : val tss = -0.0081 ::: train hss = 0.4509 : val hss = -0.0102
Fold 4: train tss = 0.5251 : val tss = 0.5615 ::: train hss = 0.2699 : val hss = 0.3646
mean cv TSS: 0.2225
mean cv HSS: 0.1550
414/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7212 : val tss = 0.2460 ::: train hss = 0.5525 : val hss = 0.1145
Fold 2: train tss = 0.5594 : val tss = 0.6362 ::: train hss = 0.3452 : val hss = 0.4728
Fold 3: train tss = 0.7540 : val tss = 0.0481 ::: train hss = 0.4262 : val hss = 0.0339
Fold 4: train tss = 0.7104 : val tss = 0.5349 ::: train hss = 0.3841 : val hss = 0.3719
mean cv TSS: 0.2930
mean cv HSS: 0.1986
415/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7458 : val tss = 0.3234 ::: train hss = 0.5993 : val hss = 0.1476
Fold 2: train tss = 0.4823 : val tss = 0.5370 ::: train hss = 0.3111 : val hss = 0.4560
Fold 3: train tss = 0.7145 : val tss = 0.0282 ::: train hss = 0.4072 : val hss = 0.0246
Fold 4: train tss = 0.6779 : val tss = 0.6601 ::: train hss = 0.3413 : val hss = 0.3539
mean cv TSS: 0.3098
mean cv HSS: 0.1964
416/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7431 : val tss = 0.2243 ::: train hss = 0.6341 : val hss = 0.1090
Fold 2: train tss = 0.6322 : val tss = 0.5633 ::: train hss = 0.4050 : val hss = 0.4595
Fold 3: train tss = 0.7403 : val tss = 0.0071 ::: train hss = 0.4355 : val hss = 0.0078
Fold 4: train tss = 0.7444 : val tss = 0.6599 ::: train hss = 0.3991 : val hss = 0.4800
mean cv TSS: 0.2909
mean cv HSS: 0.2113
417/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6988 : val tss = 0.1377 ::: train hss = 0.6265 : val hss = 0.0674
Fold 2: train tss = 0.5968 : val tss = 0.5968 ::: train hss = 0.3598 : val hss = 0.4855
Fold 3: train tss = 0.7424 : val tss = 0.0319 ::: train hss = 0.4784 : val hss = 0.0318
Fold 4: train tss = 0.6952 : val tss = 0.6556 ::: train hss = 0.3296 : val hss = 0.4026
mean cv TSS: 0.2844
mean cv HSS: 0.1974
418/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7706 : val tss = 0.1740 ::: train hss = 0.6576 : val hss = 0.0825
Fold 2: train tss = 0.6636 : val tss = 0.5663 ::: train hss = 0.4393 : val hss = 0.4453
Fold 3: train tss = 0.8079 : val tss = 0.2230 ::: train hss = 0.5306 : val hss = 0.1100
Fold 4: train tss = 0.7711 : val tss = 0.6501 ::: train hss = 0.4843 : val hss = 0.3545
mean cv TSS: 0.3227
mean cv HSS: 0.1985
419/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7703 : val tss = 0.1604 ::: train hss = 0.6510 : val hss = 0.0745
Fold 2: train tss = 0.6140 : val tss = 0.5164 ::: train hss = 0.4719 : val hss = 0.5117
Fold 3: train tss = 0.7462 : val tss = 0.0181 ::: train hss = 0.4659 : val hss = 0.0155
Fold 4: train tss = 0.6404 : val tss = 0.6341 ::: train hss = 0.4865 : val hss = 0.3248
mean cv TSS: 0.2658
mean cv HSS: 0.1853
420/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = -0.0001 ::: train hss = 0.0000 : val hss = -0.0002
Fold 1: train tss = 0.6869 : val tss = 0.2139 ::: train hss = 0.3614 : val hss = 0.2202
Fold 2: train tss = 0.0033 : val tss = -0.0080 ::: train hss = 0.0048 : val hss = -0.0146
Fold 3: train tss = 0.6960 : val tss = -0.0171 ::: train hss = 0.2389 : val hss = -0.0117
Fold 4: train tss = 0.6589 : val tss = 0.6601 ::: train hss = 0.2664 : val hss = 0.3214
mean cv TSS: 0.1697
mean cv HSS: 0.1030
421/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6678 : val tss = 0.3445 ::: train hss = 0.2140 : val hss = 0.1366
Fold 2: train tss = 0.0000 : val tss = 0.0245 ::: train hss = 0.0000 : val hss = 0.0476
Fold 3: train tss = 0.5589 : val tss = 0.0125 ::: train hss = 0.2027 : val hss = 0.0090
Fold 4: train tss = 0.4150 : val tss = 0.7276 ::: train hss = 0.1760 : val hss = 0.3985
mean cv TSS: 0.2218
mean cv HSS: 0.1183
422/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7367 : val tss = 0.1637 ::: train hss = 0.1430 : val hss = 0.0543
Fold 2: train tss = 0.0038 : val tss = -0.0072 ::: train hss = 0.0075 : val hss = -0.0131
Fold 3: train tss = 0.6532 : val tss = 0.3699 ::: train hss = 0.1827 : val hss = 0.0788
Fold 4: train tss = 0.6285 : val tss = 0.6859 ::: train hss = 0.1990 : val hss = 0.3132
mean cv TSS: 0.2425
mean cv HSS: 0.0866
423/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7015 : val tss = 0.1737 ::: train hss = 0.1652 : val hss = 0.0433
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4224 : val tss = 0.0396 ::: train hss = 0.1286 : val hss = 0.0229
Fold 4: train tss = 0.4515 : val tss = 0.6990 ::: train hss = 0.1631 : val hss = 0.2540
mean cv TSS: 0.1825
mean cv HSS: 0.0640
424/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.1471 : val tss = 0.0000 ::: train hss = 0.1252 : val hss = 0.0000
Fold 1: train tss = 0.5877 : val tss = -0.0335 ::: train hss = 0.2712 : val hss = -0.0253
Fold 2: train tss = -0.0002 : val tss = -0.0007 ::: train hss = -0.0003 : val hss = -0.0013
Fold 3: train tss = 0.7057 : val tss = 0.0390 ::: train hss = 0.2390 : val hss = 0.0096
Fold 4: train tss = 0.4711 : val tss = 0.0142 ::: train hss = 0.2040 : val hss = 0.0235
mean cv TSS: 0.0038
mean cv HSS: 0.0013
425/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = -0.0108 : val tss = -0.0691 ::: train hss = -0.0120 : val hss = -0.0183
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5398 : val tss = 0.0607 ::: train hss = 0.1556 : val hss = 0.0206
Fold 4: train tss = 0.5005 : val tss = 0.6200 ::: train hss = 0.2145 : val hss = 0.3909
mean cv TSS: 0.1223
mean cv HSS: 0.0786
426/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6397 : val tss = 0.0886 ::: train hss = 0.6913 : val hss = 0.0598
Fold 2: train tss = 0.6212 : val tss = 0.6044 ::: train hss = 0.3592 : val hss = 0.4579
Fold 3: train tss = 0.7792 : val tss = 0.0050 ::: train hss = 0.4626 : val hss = 0.0050
Fold 4: train tss = 0.6421 : val tss = 0.5381 ::: train hss = 0.2639 : val hss = 0.4291
mean cv TSS: 0.2472
mean cv HSS: 0.1904
427/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5613 : val tss = 0.2598 ::: train hss = 0.3455 : val hss = 0.1236
Fold 2: train tss = 0.3834 : val tss = 0.4945 ::: train hss = 0.2426 : val hss = 0.4336
Fold 3: train tss = 0.6966 : val tss = -0.0004 ::: train hss = 0.3464 : val hss = -0.0005
Fold 4: train tss = 0.5744 : val tss = 0.7151 ::: train hss = 0.2542 : val hss = 0.3769
mean cv TSS: 0.2938
mean cv HSS: 0.1867
428/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5364 : val tss = 0.2082 ::: train hss = 0.6339 : val hss = 0.0785
Fold 2: train tss = 0.6118 : val tss = 0.6033 ::: train hss = 0.4229 : val hss = 0.3721
Fold 3: train tss = 0.6947 : val tss = 0.0972 ::: train hss = 0.3574 : val hss = 0.0598
Fold 4: train tss = 0.7302 : val tss = 0.7137 ::: train hss = 0.4359 : val hss = 0.4160
mean cv TSS: 0.3245
mean cv HSS: 0.1853
429/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6847 : val tss = 0.2933 ::: train hss = 0.7155 : val hss = 0.1271
Fold 2: train tss = 0.5352 : val tss = 0.2881 ::: train hss = 0.2061 : val hss = 0.3659
Fold 3: train tss = 0.6092 : val tss = -0.0004 ::: train hss = 0.1736 : val hss = -0.0002
Fold 4: train tss = 0.6239 : val tss = 0.7538 ::: train hss = 0.2890 : val hss = 0.3896
mean cv TSS: 0.2670
mean cv HSS: 0.1765
430/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7777 : val tss = 0.0571 ::: train hss = 0.6227 : val hss = 0.0247
Fold 2: train tss = 0.5739 : val tss = 0.5586 ::: train hss = 0.5229 : val hss = 0.3720
Fold 3: train tss = 0.8174 : val tss = 0.1522 ::: train hss = 0.5160 : val hss = 0.0517
Fold 4: train tss = 0.5350 : val tss = 0.6556 ::: train hss = 0.1863 : val hss = 0.2259
mean cv TSS: 0.2847
mean cv HSS: 0.1348
431/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7719 : val tss = 0.1255 ::: train hss = 0.6865 : val hss = 0.0572
Fold 2: train tss = 0.6482 : val tss = 0.6198 ::: train hss = 0.3949 : val hss = 0.5093
Fold 3: train tss = 0.7517 : val tss = 0.0612 ::: train hss = 0.3818 : val hss = 0.0383
Fold 4: train tss = 0.6031 : val tss = 0.6352 ::: train hss = 0.3347 : val hss = 0.2913
mean cv TSS: 0.2883
mean cv HSS: 0.1792
432/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7516 : val tss = 0.0719 ::: train hss = 0.4878 : val hss = 0.0337
Fold 2: train tss = 0.6737 : val tss = 0.7061 ::: train hss = 0.3599 : val hss = 0.4125
Fold 3: train tss = 0.7009 : val tss = 0.0338 ::: train hss = 0.2702 : val hss = 0.0148
Fold 4: train tss = 0.6999 : val tss = 0.5143 ::: train hss = 0.2964 : val hss = 0.2685
mean cv TSS: 0.2652
mean cv HSS: 0.1459
433/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7462 : val tss = 0.1177 ::: train hss = 0.5328 : val hss = 0.0592
Fold 2: train tss = 0.3737 : val tss = 0.6501 ::: train hss = 0.2299 : val hss = 0.3345
Fold 3: train tss = 0.6896 : val tss = 0.0336 ::: train hss = 0.3655 : val hss = 0.0208
Fold 4: train tss = 0.5106 : val tss = 0.5953 ::: train hss = 0.3168 : val hss = 0.3035
mean cv TSS: 0.2794
mean cv HSS: 0.1436
434/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7386 : val tss = 0.1512 ::: train hss = 0.3991 : val hss = 0.1211
Fold 2: train tss = 0.3858 : val tss = 0.4948 ::: train hss = 0.2783 : val hss = 0.3506
Fold 3: train tss = 0.7708 : val tss = 0.0485 ::: train hss = 0.3982 : val hss = 0.0665
Fold 4: train tss = 0.7534 : val tss = 0.4895 ::: train hss = 0.3948 : val hss = 0.2573
mean cv TSS: 0.2368
mean cv HSS: 0.1591
435/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7917 : val tss = 0.1964 ::: train hss = 0.5006 : val hss = 0.1139
Fold 2: train tss = 0.5538 : val tss = 0.6693 ::: train hss = 0.3249 : val hss = 0.3066
Fold 3: train tss = 0.7137 : val tss = 0.0124 ::: train hss = 0.3209 : val hss = 0.0089
Fold 4: train tss = 0.6661 : val tss = 0.6849 ::: train hss = 0.3199 : val hss = 0.3328
mean cv TSS: 0.3126
mean cv HSS: 0.1524
436/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7844 : val tss = 0.0978 ::: train hss = 0.5198 : val hss = 0.0701
Fold 2: train tss = 0.5283 : val tss = 0.5515 ::: train hss = 0.3274 : val hss = 0.3850
Fold 3: train tss = 0.7478 : val tss = 0.4115 ::: train hss = 0.3948 : val hss = 0.1461
Fold 4: train tss = 0.7273 : val tss = 0.6649 ::: train hss = 0.3946 : val hss = 0.2654
mean cv TSS: 0.3451
mean cv HSS: 0.1733
437/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7639 : val tss = 0.1209 ::: train hss = 0.6106 : val hss = 0.0390
Fold 2: train tss = 0.2454 : val tss = 0.5948 ::: train hss = 0.2529 : val hss = 0.3470
Fold 3: train tss = 0.6784 : val tss = 0.3307 ::: train hss = 0.3321 : val hss = 0.0965
Fold 4: train tss = 0.6342 : val tss = 0.6333 ::: train hss = 0.3476 : val hss = 0.2084
mean cv TSS: 0.3360
mean cv HSS: 0.1382
438/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6780 : val tss = 0.1840 ::: train hss = 0.4381 : val hss = 0.1048
Fold 2: train tss = 0.4978 : val tss = 0.6019 ::: train hss = 0.2864 : val hss = 0.3377
Fold 3: train tss = 0.6343 : val tss = 0.0127 ::: train hss = 0.3099 : val hss = 0.0042
Fold 4: train tss = 0.6484 : val tss = 0.7408 ::: train hss = 0.3109 : val hss = 0.3547
mean cv TSS: 0.3079
mean cv HSS: 0.1603
439/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6417 : val tss = 0.2805 ::: train hss = 0.4183 : val hss = 0.1221
Fold 2: train tss = 0.4687 : val tss = 0.6252 ::: train hss = 0.2636 : val hss = 0.4179
Fold 3: train tss = 0.6491 : val tss = 0.0391 ::: train hss = 0.3238 : val hss = 0.0223
Fold 4: train tss = 0.5803 : val tss = 0.6899 ::: train hss = 0.2984 : val hss = 0.2867
mean cv TSS: 0.3269
mean cv HSS: 0.1698
440/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7257 : val tss = 0.3333 ::: train hss = 0.4912 : val hss = 0.1168
Fold 2: train tss = 0.4634 : val tss = 0.6014 ::: train hss = 0.2697 : val hss = 0.3844
Fold 3: train tss = 0.6603 : val tss = 0.0643 ::: train hss = 0.3580 : val hss = 0.0203
Fold 4: train tss = 0.6518 : val tss = 0.5131 ::: train hss = 0.3394 : val hss = 0.3121
mean cv TSS: 0.3024
mean cv HSS: 0.1667
441/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7139 : val tss = 0.3404 ::: train hss = 0.4093 : val hss = 0.1193
Fold 2: train tss = 0.4745 : val tss = 0.5879 ::: train hss = 0.2814 : val hss = 0.3206
Fold 3: train tss = 0.6473 : val tss = 0.0322 ::: train hss = 0.3339 : val hss = 0.0138
Fold 4: train tss = 0.6303 : val tss = 0.7496 ::: train hss = 0.3219 : val hss = 0.3506
mean cv TSS: 0.3420
mean cv HSS: 0.1608
442/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7555 : val tss = 0.1756 ::: train hss = 0.6184 : val hss = 0.0674
Fold 2: train tss = 0.5325 : val tss = 0.6325 ::: train hss = 0.3510 : val hss = 0.4566
Fold 3: train tss = 0.6714 : val tss = 0.0681 ::: train hss = 0.3836 : val hss = 0.0226
Fold 4: train tss = 0.6831 : val tss = 0.6045 ::: train hss = 0.3791 : val hss = 0.3527
mean cv TSS: 0.2962
mean cv HSS: 0.1799
443/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7283 : val tss = 0.2235 ::: train hss = 0.6017 : val hss = 0.0919
Fold 2: train tss = 0.5246 : val tss = 0.6796 ::: train hss = 0.3561 : val hss = 0.4378
Fold 3: train tss = 0.7215 : val tss = -0.0078 ::: train hss = 0.4402 : val hss = -0.0099
Fold 4: train tss = 0.6336 : val tss = 0.6117 ::: train hss = 0.3453 : val hss = 0.3056
mean cv TSS: 0.3014
mean cv HSS: 0.1651
444/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7558 : val tss = 0.1323 ::: train hss = 0.3659 : val hss = 0.0851
Fold 2: train tss = 0.5854 : val tss = 0.6730 ::: train hss = 0.2096 : val hss = 0.4324
Fold 3: train tss = 0.7073 : val tss = 0.0739 ::: train hss = 0.2686 : val hss = 0.0143
Fold 4: train tss = 0.6055 : val tss = 0.6562 ::: train hss = 0.1979 : val hss = 0.2077
mean cv TSS: 0.3071
mean cv HSS: 0.1479
445/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6413 : val tss = 0.2827 ::: train hss = 0.2081 : val hss = 0.0766
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5463 : val tss = 0.0266 ::: train hss = 0.1836 : val hss = 0.0068
Fold 4: train tss = 0.5256 : val tss = 0.6548 ::: train hss = 0.1578 : val hss = 0.3400
mean cv TSS: 0.1928
mean cv HSS: 0.0847
446/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7558 : val tss = 0.1185 ::: train hss = 0.3991 : val hss = 0.0701
Fold 2: train tss = 0.0035 : val tss = -0.0082 ::: train hss = 0.0069 : val hss = -0.0146
Fold 3: train tss = 0.6208 : val tss = 0.1604 ::: train hss = 0.1903 : val hss = 0.0481
Fold 4: train tss = 0.6116 : val tss = 0.6561 ::: train hss = 0.1893 : val hss = 0.2963
mean cv TSS: 0.1853
mean cv HSS: 0.0800
447/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5392 : val tss = 0.1959 ::: train hss = 0.2207 : val hss = 0.0707
Fold 2: train tss = -0.0005 : val tss = 0.1317 ::: train hss = -0.0009 : val hss = 0.2126
Fold 3: train tss = 0.4450 : val tss = 0.0749 ::: train hss = 0.1271 : val hss = 0.0168
Fold 4: train tss = 0.4541 : val tss = 0.5600 ::: train hss = 0.1961 : val hss = 0.2138
mean cv TSS: 0.1925
mean cv HSS: 0.1028
448/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7175 : val tss = 0.1467 ::: train hss = 0.2734 : val hss = 0.0669
Fold 2: train tss = 0.1599 : val tss = 0.3375 ::: train hss = 0.1835 : val hss = 0.3470
Fold 3: train tss = 0.6641 : val tss = 0.0411 ::: train hss = 0.1832 : val hss = 0.0205
Fold 4: train tss = 0.6576 : val tss = 0.7533 ::: train hss = 0.2258 : val hss = 0.3135
mean cv TSS: 0.2557
mean cv HSS: 0.1496
449/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7275 : val tss = 0.1183 ::: train hss = 0.2631 : val hss = 0.0337
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.4916 : val tss = 0.0884 ::: train hss = 0.1164 : val hss = 0.0339
Fold 4: train tss = 0.3303 : val tss = 0.7821 ::: train hss = 0.1965 : val hss = 0.4561
mean cv TSS: 0.1977
mean cv HSS: 0.1047
450/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6680 : val tss = 0.3281 ::: train hss = 0.5387 : val hss = 0.1285
Fold 2: train tss = 0.6701 : val tss = 0.6031 ::: train hss = 0.2833 : val hss = 0.3584
Fold 3: train tss = 0.7379 : val tss = 0.0101 ::: train hss = 0.3281 : val hss = 0.0036
Fold 4: train tss = 0.7136 : val tss = 0.6114 ::: train hss = 0.3404 : val hss = 0.3276
mean cv TSS: 0.3105
mean cv HSS: 0.1636
451/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7247 : val tss = 0.4003 ::: train hss = 0.1943 : val hss = 0.0906
Fold 2: train tss = 0.4228 : val tss = 0.5440 ::: train hss = 0.2689 : val hss = 0.4132
Fold 3: train tss = 0.6841 : val tss = 0.0555 ::: train hss = 0.3367 : val hss = 0.0483
Fold 4: train tss = 0.5714 : val tss = 0.6785 ::: train hss = 0.2647 : val hss = 0.2640
mean cv TSS: 0.3357
mean cv HSS: 0.1632
452/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6038 : val tss = 0.2427 ::: train hss = 0.5654 : val hss = 0.0947
Fold 2: train tss = 0.3354 : val tss = 0.6627 ::: train hss = 0.3310 : val hss = 0.4470
Fold 3: train tss = 0.7043 : val tss = 0.1032 ::: train hss = 0.4075 : val hss = 0.0592
Fold 4: train tss = 0.6676 : val tss = 0.5230 ::: train hss = 0.3380 : val hss = 0.3478
mean cv TSS: 0.3063
mean cv HSS: 0.1897
453/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7590 : val tss = 0.3124 ::: train hss = 0.3592 : val hss = 0.1077
Fold 2: train tss = 0.3631 : val tss = 0.5126 ::: train hss = 0.2038 : val hss = 0.4374
Fold 3: train tss = 0.7054 : val tss = -0.0054 ::: train hss = 0.3620 : val hss = -0.0077
Fold 4: train tss = 0.6207 : val tss = 0.6679 ::: train hss = 0.2645 : val hss = 0.2572
mean cv TSS: 0.2975
mean cv HSS: 0.1589
454/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7748 : val tss = 0.0645 ::: train hss = 0.6536 : val hss = 0.0214
Fold 2: train tss = 0.5761 : val tss = 0.0901 ::: train hss = 0.2301 : val hss = 0.1563
Fold 3: train tss = 0.7462 : val tss = -0.0007 ::: train hss = 0.3323 : val hss = -0.0003
Fold 4: train tss = 0.6869 : val tss = 0.6345 ::: train hss = 0.3767 : val hss = 0.3116
mean cv TSS: 0.1577
mean cv HSS: 0.0978
455/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7781 : val tss = 0.1142 ::: train hss = 0.6299 : val hss = 0.0507
Fold 2: train tss = 0.4999 : val tss = 0.4881 ::: train hss = 0.1664 : val hss = 0.3343
Fold 3: train tss = 0.6100 : val tss = -0.0064 ::: train hss = 0.2485 : val hss = -0.0087
Fold 4: train tss = 0.6287 : val tss = 0.5678 ::: train hss = 0.3045 : val hss = 0.4454
mean cv TSS: 0.2327
mean cv HSS: 0.1643
456/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7330 : val tss = 0.1318 ::: train hss = 0.3875 : val hss = 0.0480
Fold 2: train tss = 0.5933 : val tss = 0.6777 ::: train hss = 0.3013 : val hss = 0.4018
Fold 3: train tss = 0.7422 : val tss = 0.0430 ::: train hss = 0.3805 : val hss = 0.0164
Fold 4: train tss = 0.6788 : val tss = 0.6935 ::: train hss = 0.2886 : val hss = 0.2739
mean cv TSS: 0.3092
mean cv HSS: 0.1480
457/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6872 : val tss = 0.1796 ::: train hss = 0.4996 : val hss = 0.0965
Fold 2: train tss = 0.5933 : val tss = 0.6413 ::: train hss = 0.3085 : val hss = 0.4387
Fold 3: train tss = 0.6400 : val tss = 0.0083 ::: train hss = 0.2516 : val hss = 0.0021
Fold 4: train tss = 0.6140 : val tss = 0.7073 ::: train hss = 0.2976 : val hss = 0.2692
mean cv TSS: 0.3073
mean cv HSS: 0.1613
458/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7481 : val tss = 0.2143 ::: train hss = 0.4072 : val hss = 0.0805
Fold 2: train tss = 0.0124 : val tss = 0.2263 ::: train hss = 0.0235 : val hss = 0.2660
Fold 3: train tss = 0.7318 : val tss = 0.1344 ::: train hss = 0.3772 : val hss = 0.0313
Fold 4: train tss = 0.7279 : val tss = 0.5348 ::: train hss = 0.3719 : val hss = 0.2625
mean cv TSS: 0.2220
mean cv HSS: 0.1281
459/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7621 : val tss = 0.1634 ::: train hss = 0.2842 : val hss = 0.0495
Fold 2: train tss = 0.4829 : val tss = 0.7051 ::: train hss = 0.3143 : val hss = 0.3650
Fold 3: train tss = 0.7607 : val tss = 0.0218 ::: train hss = 0.3402 : val hss = 0.0092
Fold 4: train tss = 0.5924 : val tss = 0.7198 ::: train hss = 0.2427 : val hss = 0.3447
mean cv TSS: 0.3220
mean cv HSS: 0.1537
460/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7584 : val tss = 0.1265 ::: train hss = 0.3555 : val hss = 0.0432
Fold 2: train tss = 0.5839 : val tss = 0.6487 ::: train hss = 0.3287 : val hss = 0.4083
Fold 3: train tss = 0.7684 : val tss = -0.0285 ::: train hss = 0.4340 : val hss = -0.0074
Fold 4: train tss = 0.6706 : val tss = 0.5732 ::: train hss = 0.3210 : val hss = 0.2687
mean cv TSS: 0.2640
mean cv HSS: 0.1426
461/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7586 : val tss = 0.1619 ::: train hss = 0.6843 : val hss = 0.0435
Fold 2: train tss = 0.0097 : val tss = 0.1857 ::: train hss = 0.0178 : val hss = 0.2113
Fold 3: train tss = 0.7457 : val tss = -0.0259 ::: train hss = 0.3876 : val hss = -0.0179
Fold 4: train tss = 0.6011 : val tss = 0.6875 ::: train hss = 0.2949 : val hss = 0.2556
mean cv TSS: 0.2018
mean cv HSS: 0.0985
462/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6803 : val tss = 0.2805 ::: train hss = 0.4655 : val hss = 0.1173
Fold 2: train tss = 0.4566 : val tss = 0.6367 ::: train hss = 0.2491 : val hss = 0.3386
Fold 3: train tss = 0.6866 : val tss = 0.0451 ::: train hss = 0.3465 : val hss = 0.0204
Fold 4: train tss = 0.6449 : val tss = 0.7187 ::: train hss = 0.3258 : val hss = 0.2979
mean cv TSS: 0.3362
mean cv HSS: 0.1548
463/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6523 : val tss = 0.2625 ::: train hss = 0.4402 : val hss = 0.1116
Fold 2: train tss = 0.4922 : val tss = 0.6405 ::: train hss = 0.2771 : val hss = 0.3653
Fold 3: train tss = 0.6591 : val tss = 0.0391 ::: train hss = 0.3081 : val hss = 0.0161
Fold 4: train tss = 0.6308 : val tss = 0.6541 ::: train hss = 0.3124 : val hss = 0.2980
mean cv TSS: 0.3192
mean cv HSS: 0.1582
464/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7248 : val tss = 0.2759 ::: train hss = 0.5402 : val hss = 0.1150
Fold 2: train tss = 0.5366 : val tss = 0.5769 ::: train hss = 0.3250 : val hss = 0.3163
Fold 3: train tss = 0.6965 : val tss = 0.0329 ::: train hss = 0.3757 : val hss = 0.0143
Fold 4: train tss = 0.5712 : val tss = 0.6432 ::: train hss = 0.3162 : val hss = 0.3237
mean cv TSS: 0.3058
mean cv HSS: 0.1538
465/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7399 : val tss = 0.2931 ::: train hss = 0.5063 : val hss = 0.1243
Fold 2: train tss = 0.4449 : val tss = 0.6653 ::: train hss = 0.2944 : val hss = 0.4150
Fold 3: train tss = 0.6852 : val tss = 0.0356 ::: train hss = 0.3799 : val hss = 0.0140
Fold 4: train tss = 0.6162 : val tss = 0.6446 ::: train hss = 0.3127 : val hss = 0.3410
mean cv TSS: 0.3277
mean cv HSS: 0.1789
466/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7103 : val tss = 0.1556 ::: train hss = 0.5935 : val hss = 0.0580
Fold 2: train tss = 0.5156 : val tss = 0.6903 ::: train hss = 0.3656 : val hss = 0.4615
Fold 3: train tss = 0.7403 : val tss = 0.0088 ::: train hss = 0.4076 : val hss = 0.0040
Fold 4: train tss = 0.7133 : val tss = 0.6353 ::: train hss = 0.4026 : val hss = 0.2947
mean cv TSS: 0.2980
mean cv HSS: 0.1636
467/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7673 : val tss = 0.2007 ::: train hss = 0.5929 : val hss = 0.0676
Fold 2: train tss = 0.6002 : val tss = 0.6867 ::: train hss = 0.3919 : val hss = 0.4661
Fold 3: train tss = 0.7130 : val tss = -0.0273 ::: train hss = 0.4377 : val hss = -0.0182
Fold 4: train tss = 0.5995 : val tss = 0.6331 ::: train hss = 0.4164 : val hss = 0.3004
mean cv TSS: 0.2987
mean cv HSS: 0.1632
468/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7069 : val tss = 0.1964 ::: train hss = 0.2807 : val hss = 0.1406
Fold 2: train tss = 0.4136 : val tss = 0.6894 ::: train hss = 0.1736 : val hss = 0.3890
Fold 3: train tss = 0.6992 : val tss = 0.0767 ::: train hss = 0.2215 : val hss = 0.0281
Fold 4: train tss = 0.6299 : val tss = 0.6871 ::: train hss = 0.2220 : val hss = 0.2749
mean cv TSS: 0.3299
mean cv HSS: 0.1665
469/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6247 : val tss = 0.3382 ::: train hss = 0.2492 : val hss = 0.1486
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5521 : val tss = 0.0498 ::: train hss = 0.1653 : val hss = 0.0245
Fold 4: train tss = 0.5614 : val tss = 0.7639 ::: train hss = 0.2015 : val hss = 0.3621
mean cv TSS: 0.2304
mean cv HSS: 0.1071
470/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7418 : val tss = 0.1338 ::: train hss = 0.1399 : val hss = 0.0848
Fold 2: train tss = -0.0000 : val tss = 0.0000 ::: train hss = -0.0001 : val hss = 0.0000
Fold 3: train tss = 0.6130 : val tss = 0.1830 ::: train hss = 0.1913 : val hss = 0.0438
Fold 4: train tss = 0.5438 : val tss = 0.6845 ::: train hss = 0.1632 : val hss = 0.2446
mean cv TSS: 0.2003
mean cv HSS: 0.0746
471/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5697 : val tss = 0.2556 ::: train hss = 0.1700 : val hss = 0.0533
Fold 2: train tss = -0.0084 : val tss = 0.5206 ::: train hss = -0.0100 : val hss = 0.3162
Fold 3: train tss = 0.6225 : val tss = 0.0382 ::: train hss = 0.1884 : val hss = 0.0180
Fold 4: train tss = 0.4860 : val tss = 0.7135 ::: train hss = 0.1494 : val hss = 0.2638
mean cv TSS: 0.3056
mean cv HSS: 0.1303
472/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7539 : val tss = -0.0597 ::: train hss = 0.1972 : val hss = -0.0338
Fold 2: train tss = 0.0000 : val tss = -0.0026 ::: train hss = 0.0000 : val hss = -0.0051
Fold 3: train tss = 0.6886 : val tss = 0.0880 ::: train hss = 0.2226 : val hss = 0.0243
Fold 4: train tss = 0.5845 : val tss = 0.5422 ::: train hss = 0.1734 : val hss = 0.2085
mean cv TSS: 0.1136
mean cv HSS: 0.0388
473/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7023 : val tss = -0.0024 ::: train hss = 0.1818 : val hss = -0.0009
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6188 : val tss = 0.1197 ::: train hss = 0.2064 : val hss = 0.0219
Fold 4: train tss = 0.3086 : val tss = 0.6821 ::: train hss = 0.1378 : val hss = 0.2490
mean cv TSS: 0.1599
mean cv HSS: 0.0540
474/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6839 : val tss = 0.0092 ::: train hss = 0.5904 : val hss = 0.0108
Fold 2: train tss = 0.5986 : val tss = 0.6552 ::: train hss = 0.3164 : val hss = 0.4855
Fold 3: train tss = 0.7489 : val tss = 0.0436 ::: train hss = 0.3472 : val hss = 0.0193
Fold 4: train tss = 0.6593 : val tss = 0.6857 ::: train hss = 0.2797 : val hss = 0.3573
mean cv TSS: 0.2787
mean cv HSS: 0.1746
475/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7074 : val tss = 0.0853 ::: train hss = 0.6216 : val hss = 0.0744
Fold 2: train tss = 0.2814 : val tss = 0.5016 ::: train hss = 0.1769 : val hss = 0.4108
Fold 3: train tss = 0.6326 : val tss = 0.0706 ::: train hss = 0.2565 : val hss = 0.0365
Fold 4: train tss = 0.5990 : val tss = 0.6142 ::: train hss = 0.2151 : val hss = 0.4107
mean cv TSS: 0.2543
mean cv HSS: 0.1865
476/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7818 : val tss = 0.0054 ::: train hss = 0.5433 : val hss = 0.0026
Fold 2: train tss = 0.6698 : val tss = 0.6738 ::: train hss = 0.3767 : val hss = 0.4256
Fold 3: train tss = 0.7601 : val tss = -0.0086 ::: train hss = 0.4290 : val hss = -0.0040
Fold 4: train tss = 0.7175 : val tss = 0.6152 ::: train hss = 0.3603 : val hss = 0.3156
mean cv TSS: 0.2572
mean cv HSS: 0.1480
477/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6279 : val tss = 0.2709 ::: train hss = 0.4093 : val hss = 0.1165
Fold 2: train tss = 0.4173 : val tss = 0.4854 ::: train hss = 0.3023 : val hss = 0.4345
Fold 3: train tss = 0.6391 : val tss = 0.0236 ::: train hss = 0.2637 : val hss = 0.0143
Fold 4: train tss = 0.6456 : val tss = 0.5166 ::: train hss = 0.3068 : val hss = 0.3211
mean cv TSS: 0.2593
mean cv HSS: 0.1773
478/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7762 : val tss = 0.0861 ::: train hss = 0.5946 : val hss = 0.0509
Fold 2: train tss = 0.5894 : val tss = 0.4403 ::: train hss = 0.2050 : val hss = 0.4597
Fold 3: train tss = 0.7098 : val tss = -0.0241 ::: train hss = 0.4204 : val hss = -0.0101
Fold 4: train tss = 0.7067 : val tss = 0.5440 ::: train hss = 0.3223 : val hss = 0.3932
mean cv TSS: 0.2092
mean cv HSS: 0.1787
479/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7795 : val tss = 0.2081 ::: train hss = 0.5772 : val hss = 0.0775
Fold 2: train tss = 0.0956 : val tss = 0.3444 ::: train hss = 0.1050 : val hss = 0.3101
Fold 3: train tss = 0.5435 : val tss = 0.0473 ::: train hss = 0.2830 : val hss = 0.0137
Fold 4: train tss = 0.6451 : val tss = 0.2198 ::: train hss = 0.2739 : val hss = 0.2821
mean cv TSS: 0.1639
mean cv HSS: 0.1367
480/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7287 : val tss = 0.1908 ::: train hss = 0.4737 : val hss = 0.0855
Fold 2: train tss = 0.6649 : val tss = 0.5887 ::: train hss = 0.2066 : val hss = 0.3894
Fold 3: train tss = 0.8091 : val tss = -0.0040 ::: train hss = 0.4347 : val hss = -0.0062
Fold 4: train tss = 0.7722 : val tss = 0.6994 ::: train hss = 0.4060 : val hss = 0.4236
mean cv TSS: 0.2950
mean cv HSS: 0.1785
481/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7540 : val tss = 0.2908 ::: train hss = 0.4655 : val hss = 0.1347
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7168 : val tss = 0.0166 ::: train hss = 0.3081 : val hss = 0.0135
Fold 4: train tss = 0.6152 : val tss = 0.7089 ::: train hss = 0.2416 : val hss = 0.3147
mean cv TSS: 0.2033
mean cv HSS: 0.0926
482/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7592 : val tss = 0.0989 ::: train hss = 0.5327 : val hss = 0.0689
Fold 2: train tss = 0.6584 : val tss = 0.5972 ::: train hss = 0.4146 : val hss = 0.4530
Fold 3: train tss = 0.7694 : val tss = 0.2126 ::: train hss = 0.4044 : val hss = 0.1217
Fold 4: train tss = 0.7169 : val tss = 0.6632 ::: train hss = 0.3871 : val hss = 0.4105
mean cv TSS: 0.3144
mean cv HSS: 0.2108
483/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7606 : val tss = 0.1277 ::: train hss = 0.6319 : val hss = 0.0657
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6958 : val tss = 0.0180 ::: train hss = 0.3156 : val hss = 0.0153
Fold 4: train tss = 0.6586 : val tss = 0.4415 ::: train hss = 0.3432 : val hss = 0.4599
mean cv TSS: 0.1175
mean cv HSS: 0.1082
484/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7906 : val tss = 0.0853 ::: train hss = 0.6174 : val hss = 0.0943
Fold 2: train tss = 0.6612 : val tss = 0.7048 ::: train hss = 0.3986 : val hss = 0.4574
Fold 3: train tss = 0.7859 : val tss = 0.1629 ::: train hss = 0.4680 : val hss = 0.1048
Fold 4: train tss = 0.7501 : val tss = 0.4614 ::: train hss = 0.4173 : val hss = 0.3331
mean cv TSS: 0.2829
mean cv HSS: 0.1979
485/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7567 : val tss = 0.1379 ::: train hss = 0.4483 : val hss = 0.0596
Fold 2: train tss = 0.4326 : val tss = 0.5509 ::: train hss = 0.2929 : val hss = 0.4310
Fold 3: train tss = 0.6710 : val tss = -0.0230 ::: train hss = 0.3739 : val hss = -0.0172
Fold 4: train tss = 0.5694 : val tss = 0.6063 ::: train hss = 0.3079 : val hss = 0.1821
mean cv TSS: 0.2544
mean cv HSS: 0.1311
486/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7428 : val tss = 0.1793 ::: train hss = 0.6265 : val hss = 0.1206
Fold 2: train tss = 0.6882 : val tss = 0.5967 ::: train hss = 0.4242 : val hss = 0.4758
Fold 3: train tss = 0.7885 : val tss = 0.0262 ::: train hss = 0.4685 : val hss = 0.0216
Fold 4: train tss = 0.7437 : val tss = 0.6238 ::: train hss = 0.4078 : val hss = 0.3357
mean cv TSS: 0.2852
mean cv HSS: 0.1907
487/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7279 : val tss = 0.1395 ::: train hss = 0.5925 : val hss = 0.1240
Fold 2: train tss = 0.6223 : val tss = 0.6131 ::: train hss = 0.4091 : val hss = 0.4523
Fold 3: train tss = 0.7726 : val tss = 0.0614 ::: train hss = 0.4581 : val hss = 0.0383
Fold 4: train tss = 0.7109 : val tss = 0.6969 ::: train hss = 0.3778 : val hss = 0.3346
mean cv TSS: 0.3022
mean cv HSS: 0.1898
488/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7680 : val tss = 0.0496 ::: train hss = 0.6040 : val hss = 0.0468
Fold 2: train tss = 0.6454 : val tss = 0.6575 ::: train hss = 0.4355 : val hss = 0.4810
Fold 3: train tss = 0.7852 : val tss = 0.0025 ::: train hss = 0.4837 : val hss = 0.0034
Fold 4: train tss = 0.7823 : val tss = 0.4305 ::: train hss = 0.4616 : val hss = 0.4116
mean cv TSS: 0.2280
mean cv HSS: 0.1886
489/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7647 : val tss = 0.1307 ::: train hss = 0.6247 : val hss = 0.0723
Fold 2: train tss = 0.6891 : val tss = 0.6279 ::: train hss = 0.4708 : val hss = 0.4095
Fold 3: train tss = 0.7933 : val tss = -0.0006 ::: train hss = 0.5125 : val hss = -0.0012
Fold 4: train tss = 0.7065 : val tss = 0.6052 ::: train hss = 0.4346 : val hss = 0.3039
mean cv TSS: 0.2726
mean cv HSS: 0.1569
490/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7709 : val tss = 0.1731 ::: train hss = 0.6642 : val hss = 0.1111
Fold 2: train tss = 0.7606 : val tss = 0.5029 ::: train hss = 0.4836 : val hss = 0.4502
Fold 3: train tss = 0.8377 : val tss = -0.0094 ::: train hss = 0.5247 : val hss = -0.0111
Fold 4: train tss = 0.7861 : val tss = 0.3110 ::: train hss = 0.4411 : val hss = 0.3094
mean cv TSS: 0.1955
mean cv HSS: 0.1719
491/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7673 : val tss = 0.1087 ::: train hss = 0.6810 : val hss = 0.0532
Fold 2: train tss = 0.6473 : val tss = 0.6050 ::: train hss = 0.1489 : val hss = 0.3770
Fold 3: train tss = 0.7060 : val tss = 0.0355 ::: train hss = 0.4529 : val hss = 0.0092
Fold 4: train tss = 0.7273 : val tss = 0.4336 ::: train hss = 0.4257 : val hss = 0.4397
mean cv TSS: 0.2366
mean cv HSS: 0.1758
492/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5899 : val tss = 0.1741 ::: train hss = 0.2263 : val hss = 0.1422
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5997 : val tss = 0.0611 ::: train hss = 0.2244 : val hss = 0.0267
Fold 4: train tss = 0.6160 : val tss = 0.6428 ::: train hss = 0.2174 : val hss = 0.2980
mean cv TSS: 0.1756
mean cv HSS: 0.0934
493/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = -0.0600 : val tss = 0.3243 ::: train hss = -0.0195 : val hss = 0.1007
Fold 2: train tss = 0.3274 : val tss = 0.3056 ::: train hss = 0.1550 : val hss = 0.3654
Fold 3: train tss = 0.4574 : val tss = 0.0471 ::: train hss = 0.1582 : val hss = 0.0150
Fold 4: train tss = 0.4273 : val tss = 0.7217 ::: train hss = 0.1665 : val hss = 0.2810
mean cv TSS: 0.2797
mean cv HSS: 0.1524
494/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6888 : val tss = 0.2197 ::: train hss = 0.1516 : val hss = 0.0555
Fold 2: train tss = 0.0214 : val tss = 0.0521 ::: train hss = 0.0311 : val hss = 0.0919
Fold 3: train tss = 0.5941 : val tss = 0.1088 ::: train hss = 0.1579 : val hss = 0.0378
Fold 4: train tss = 0.5961 : val tss = 0.7511 ::: train hss = 0.2018 : val hss = 0.3261
mean cv TSS: 0.2263
mean cv HSS: 0.1023
495/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7126 : val tss = 0.3009 ::: train hss = 0.1858 : val hss = 0.1050
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5821 : val tss = 0.0853 ::: train hss = 0.1797 : val hss = 0.0355
Fold 4: train tss = 0.3365 : val tss = 0.7511 ::: train hss = 0.1387 : val hss = 0.4614
mean cv TSS: 0.2275
mean cv HSS: 0.1204
496/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7619 : val tss = 0.0241 ::: train hss = 0.2842 : val hss = 0.0207
Fold 2: train tss = 0.0229 : val tss = 0.0000 ::: train hss = 0.0248 : val hss = 0.0000
Fold 3: train tss = 0.6639 : val tss = 0.0813 ::: train hss = 0.2157 : val hss = 0.0370
Fold 4: train tss = 0.5153 : val tss = 0.7352 ::: train hss = 0.1748 : val hss = 0.3002
mean cv TSS: 0.1681
mean cv HSS: 0.0716
497/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = -0.0060 : val tss = 0.0000 ::: train hss = -0.0035 : val hss = 0.0000
Fold 1: train tss = 0.6561 : val tss = 0.1193 ::: train hss = 0.1388 : val hss = 0.0319
Fold 2: train tss = 0.3266 : val tss = 0.1594 ::: train hss = 0.2335 : val hss = 0.1670
Fold 3: train tss = 0.5124 : val tss = 0.0812 ::: train hss = 0.1593 : val hss = 0.0230
Fold 4: train tss = 0.3158 : val tss = 0.6854 ::: train hss = 0.1517 : val hss = 0.2669
mean cv TSS: 0.2091
mean cv HSS: 0.0978
498/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7554 : val tss = 0.0935 ::: train hss = 0.6161 : val hss = 0.0683
Fold 2: train tss = 0.5741 : val tss = 0.5744 ::: train hss = 0.3813 : val hss = 0.2711
Fold 3: train tss = 0.8050 : val tss = 0.0131 ::: train hss = 0.4818 : val hss = 0.0191
Fold 4: train tss = 0.7434 : val tss = 0.6840 ::: train hss = 0.4065 : val hss = 0.3925
mean cv TSS: 0.2730
mean cv HSS: 0.1502
499/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7072 : val tss = 0.3680 ::: train hss = 0.1614 : val hss = 0.0858
Fold 2: train tss = 0.2119 : val tss = 0.5283 ::: train hss = 0.1148 : val hss = 0.2524
Fold 3: train tss = 0.6674 : val tss = 0.0728 ::: train hss = 0.3510 : val hss = 0.0288
Fold 4: train tss = 0.5033 : val tss = 0.6353 ::: train hss = 0.2052 : val hss = 0.2355
mean cv TSS: 0.3209
mean cv HSS: 0.1205
500/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7721 : val tss = 0.0831 ::: train hss = 0.5987 : val hss = 0.0589
Fold 2: train tss = 0.1154 : val tss = 0.4781 ::: train hss = 0.1820 : val hss = 0.3809
Fold 3: train tss = 0.6741 : val tss = 0.0856 ::: train hss = 0.3324 : val hss = 0.0158
Fold 4: train tss = 0.7374 : val tss = 0.5350 ::: train hss = 0.3602 : val hss = 0.3484
mean cv TSS: 0.2364
mean cv HSS: 0.1608
501/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7547 : val tss = -0.0170 ::: train hss = 0.4731 : val hss = -0.0147
Fold 2: train tss = 0.5670 : val tss = 0.5514 ::: train hss = 0.2362 : val hss = 0.4783
Fold 3: train tss = 0.6525 : val tss = 0.0603 ::: train hss = 0.3604 : val hss = 0.0368
Fold 4: train tss = 0.6644 : val tss = 0.5513 ::: train hss = 0.3438 : val hss = 0.4318
mean cv TSS: 0.2292
mean cv HSS: 0.1865
502/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8103 : val tss = 0.0760 ::: train hss = 0.6584 : val hss = 0.0377
Fold 2: train tss = 0.4101 : val tss = 0.5428 ::: train hss = 0.2004 : val hss = 0.2027
Fold 3: train tss = 0.7856 : val tss = -0.0017 ::: train hss = 0.4936 : val hss = -0.0019
Fold 4: train tss = 0.7992 : val tss = 0.4027 ::: train hss = 0.4439 : val hss = 0.4385
mean cv TSS: 0.2039
mean cv HSS: 0.1354
503/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7885 : val tss = 0.1581 ::: train hss = 0.5809 : val hss = 0.0630
Fold 2: train tss = 0.1388 : val tss = 0.1999 ::: train hss = 0.1392 : val hss = 0.2819
Fold 3: train tss = 0.6055 : val tss = 0.0665 ::: train hss = 0.3369 : val hss = 0.0383
Fold 4: train tss = 0.6055 : val tss = 0.6588 ::: train hss = 0.2843 : val hss = 0.4534
mean cv TSS: 0.2167
mean cv HSS: 0.1673
504/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6930 : val tss = 0.1448 ::: train hss = 0.4620 : val hss = 0.0948
Fold 2: train tss = 0.5866 : val tss = 0.4687 ::: train hss = 0.3828 : val hss = 0.4177
Fold 3: train tss = 0.8351 : val tss = 0.0018 ::: train hss = 0.4592 : val hss = 0.0023
Fold 4: train tss = 0.7515 : val tss = 0.5996 ::: train hss = 0.3792 : val hss = 0.3438
mean cv TSS: 0.2430
mean cv HSS: 0.1717
505/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6560 : val tss = 0.2746 ::: train hss = 0.3540 : val hss = 0.0979
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6872 : val tss = -0.0010 ::: train hss = 0.2652 : val hss = -0.0018
Fold 4: train tss = 0.4909 : val tss = 0.5984 ::: train hss = 0.2792 : val hss = 0.2810
mean cv TSS: 0.1744
mean cv HSS: 0.0754
506/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7520 : val tss = 0.0825 ::: train hss = 0.4438 : val hss = 0.0623
Fold 2: train tss = 0.3151 : val tss = 0.1354 ::: train hss = 0.2927 : val hss = 0.2270
Fold 3: train tss = 0.7313 : val tss = -0.0032 ::: train hss = 0.2988 : val hss = -0.0034
Fold 4: train tss = 0.7137 : val tss = 0.6469 ::: train hss = 0.3523 : val hss = 0.3922
mean cv TSS: 0.1723
mean cv HSS: 0.1356
507/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7483 : val tss = 0.2082 ::: train hss = 0.3199 : val hss = 0.0897
Fold 2: train tss = 0.0027 : val tss = 0.0427 ::: train hss = 0.0052 : val hss = 0.0813
Fold 3: train tss = 0.6478 : val tss = 0.0976 ::: train hss = 0.3063 : val hss = 0.0502
Fold 4: train tss = 0.6164 : val tss = 0.6147 ::: train hss = 0.2911 : val hss = 0.3533
mean cv TSS: 0.1927
mean cv HSS: 0.1149
508/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8626 : val tss = 0.1379 ::: train hss = 0.5742 : val hss = 0.1119
Fold 2: train tss = 0.7029 : val tss = 0.6332 ::: train hss = 0.4168 : val hss = 0.3539
Fold 3: train tss = 0.7393 : val tss = 0.2282 ::: train hss = 0.4675 : val hss = 0.1051
Fold 4: train tss = 0.7364 : val tss = 0.4896 ::: train hss = 0.3769 : val hss = 0.2674
mean cv TSS: 0.2978
mean cv HSS: 0.1677
509/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7316 : val tss = 0.1571 ::: train hss = 0.4580 : val hss = 0.1123
Fold 2: train tss = 0.3336 : val tss = 0.4692 ::: train hss = 0.2798 : val hss = 0.3787
Fold 3: train tss = 0.7100 : val tss = 0.0784 ::: train hss = 0.4181 : val hss = 0.0264
Fold 4: train tss = 0.5374 : val tss = 0.6997 ::: train hss = 0.2560 : val hss = 0.3729
mean cv TSS: 0.2809
mean cv HSS: 0.1780
510/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7337 : val tss = 0.1189 ::: train hss = 0.6213 : val hss = 0.0705
Fold 2: train tss = 0.7066 : val tss = 0.6284 ::: train hss = 0.4405 : val hss = 0.4433
Fold 3: train tss = 0.7861 : val tss = 0.0229 ::: train hss = 0.4441 : val hss = 0.0228
Fold 4: train tss = 0.7335 : val tss = 0.6570 ::: train hss = 0.4342 : val hss = 0.3437
mean cv TSS: 0.2854
mean cv HSS: 0.1760
511/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7558 : val tss = 0.1687 ::: train hss = 0.6221 : val hss = 0.1936
Fold 2: train tss = 0.5683 : val tss = 0.5804 ::: train hss = 0.3665 : val hss = 0.4346
Fold 3: train tss = 0.7607 : val tss = 0.0083 ::: train hss = 0.4696 : val hss = 0.0095
Fold 4: train tss = 0.7286 : val tss = 0.6494 ::: train hss = 0.4053 : val hss = 0.3536
mean cv TSS: 0.2814
mean cv HSS: 0.1983
512/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7666 : val tss = 0.0901 ::: train hss = 0.6657 : val hss = 0.0661
Fold 2: train tss = 0.6773 : val tss = 0.6189 ::: train hss = 0.1854 : val hss = 0.4544
Fold 3: train tss = 0.7831 : val tss = -0.0128 ::: train hss = 0.4660 : val hss = -0.0098
Fold 4: train tss = 0.7597 : val tss = 0.5595 ::: train hss = 0.4145 : val hss = 0.3677
mean cv TSS: 0.2511
mean cv HSS: 0.1757
513/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7749 : val tss = 0.1110 ::: train hss = 0.6549 : val hss = 0.1027
Fold 2: train tss = 0.6850 : val tss = 0.6080 ::: train hss = 0.3117 : val hss = 0.5052
Fold 3: train tss = 0.7866 : val tss = -0.0092 ::: train hss = 0.4825 : val hss = -0.0110
Fold 4: train tss = 0.7065 : val tss = 0.5910 ::: train hss = 0.4171 : val hss = 0.3453
mean cv TSS: 0.2602
mean cv HSS: 0.1885
514/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7815 : val tss = 0.0459 ::: train hss = 0.7035 : val hss = 0.0254
Fold 2: train tss = 0.7142 : val tss = 0.6900 ::: train hss = 0.5751 : val hss = 0.3169
Fold 3: train tss = 0.8145 : val tss = 0.1814 ::: train hss = 0.5404 : val hss = 0.0966
Fold 4: train tss = 0.7856 : val tss = 0.6088 ::: train hss = 0.4749 : val hss = 0.3585
mean cv TSS: 0.3052
mean cv HSS: 0.1595
515/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7709 : val tss = 0.1738 ::: train hss = 0.6629 : val hss = 0.0861
Fold 2: train tss = 0.5793 : val tss = 0.6668 ::: train hss = 0.5695 : val hss = 0.3145
Fold 3: train tss = 0.8246 : val tss = 0.0253 ::: train hss = 0.5244 : val hss = 0.0203
Fold 4: train tss = 0.7292 : val tss = 0.5095 ::: train hss = 0.4864 : val hss = 0.4372
mean cv TSS: 0.2751
mean cv HSS: 0.1716
516/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6366 : val tss = 0.3398 ::: train hss = 0.1430 : val hss = 0.0949
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6341 : val tss = -0.0069 ::: train hss = 0.2759 : val hss = -0.0063
Fold 4: train tss = 0.6223 : val tss = 0.6836 ::: train hss = 0.2170 : val hss = 0.3261
mean cv TSS: 0.2033
mean cv HSS: 0.0829
517/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6991 : val tss = 0.3604 ::: train hss = 0.1441 : val hss = 0.1319
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5513 : val tss = 0.0296 ::: train hss = 0.1924 : val hss = 0.0208
Fold 4: train tss = 0.4691 : val tss = 0.7357 ::: train hss = 0.1360 : val hss = 0.4469
mean cv TSS: 0.2251
mean cv HSS: 0.1199
518/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6836 : val tss = 0.1698 ::: train hss = 0.1302 : val hss = 0.0528
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6102 : val tss = 0.1567 ::: train hss = 0.1858 : val hss = 0.0560
Fold 4: train tss = 0.5592 : val tss = 0.7088 ::: train hss = 0.1532 : val hss = 0.2638
mean cv TSS: 0.2071
mean cv HSS: 0.0745
519/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5654 : val tss = 0.1548 ::: train hss = 0.1330 : val hss = 0.0540
Fold 4: train tss = 0.2951 : val tss = 0.7670 ::: train hss = 0.1315 : val hss = 0.3414
mean cv TSS: 0.1844
mean cv HSS: 0.0791
520/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6220 : val tss = 0.0111 ::: train hss = 0.1069 : val hss = 0.0024
Fold 2: train tss = -0.0001 : val tss = -0.0004 ::: train hss = -0.0002 : val hss = -0.0008
Fold 3: train tss = 0.7017 : val tss = 0.0189 ::: train hss = 0.2290 : val hss = 0.0076
Fold 4: train tss = 0.6534 : val tss = 0.6204 ::: train hss = 0.2500 : val hss = 0.3633
mean cv TSS: 0.1300
mean cv HSS: 0.0745
521/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3483 : val tss = 0.1351 ::: train hss = 0.1868 : val hss = 0.0232
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5112 : val tss = 0.0866 ::: train hss = 0.1115 : val hss = 0.0260
Fold 4: train tss = 0.0102 : val tss = 0.0262 ::: train hss = 0.0077 : val hss = 0.0339
mean cv TSS: 0.0496
mean cv HSS: 0.0166
522/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6682 : val tss = 0.1780 ::: train hss = 0.4771 : val hss = 0.0580
Fold 2: train tss = 0.6473 : val tss = 0.5825 ::: train hss = 0.1807 : val hss = 0.3314
Fold 3: train tss = 0.7787 : val tss = 0.0270 ::: train hss = 0.4065 : val hss = 0.0107
Fold 4: train tss = 0.7735 : val tss = 0.6780 ::: train hss = 0.3940 : val hss = 0.3462
mean cv TSS: 0.2931
mean cv HSS: 0.1493
523/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7981 : val tss = 0.0367 ::: train hss = 0.6784 : val hss = 0.0386
Fold 2: train tss = 0.5449 : val tss = 0.1999 ::: train hss = 0.1571 : val hss = 0.2325
Fold 3: train tss = 0.6451 : val tss = 0.0119 ::: train hss = 0.3088 : val hss = 0.0084
Fold 4: train tss = 0.6251 : val tss = 0.7653 ::: train hss = 0.3017 : val hss = 0.4679
mean cv TSS: 0.2028
mean cv HSS: 0.1495
524/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7617 : val tss = 0.0707 ::: train hss = 0.6537 : val hss = 0.0971
Fold 2: train tss = 0.3655 : val tss = 0.4772 ::: train hss = 0.2370 : val hss = 0.3157
Fold 3: train tss = 0.8171 : val tss = 0.0735 ::: train hss = 0.4474 : val hss = 0.0340
Fold 4: train tss = 0.7373 : val tss = 0.5907 ::: train hss = 0.3883 : val hss = 0.4180
mean cv TSS: 0.2424
mean cv HSS: 0.1730
525/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6700 : val tss = 0.0859 ::: train hss = 0.6746 : val hss = 0.0788
Fold 2: train tss = 0.0024 : val tss = 0.2619 ::: train hss = 0.0045 : val hss = 0.3294
Fold 3: train tss = 0.6683 : val tss = 0.0276 ::: train hss = 0.3106 : val hss = 0.0333
Fold 4: train tss = 0.6256 : val tss = 0.4522 ::: train hss = 0.3015 : val hss = 0.4407
mean cv TSS: 0.1655
mean cv HSS: 0.1765
526/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8162 : val tss = 0.0805 ::: train hss = 0.6911 : val hss = 0.0510
Fold 2: train tss = 0.6801 : val tss = 0.5042 ::: train hss = 0.4701 : val hss = 0.4743
Fold 3: train tss = 0.7052 : val tss = 0.1619 ::: train hss = 0.2960 : val hss = 0.1288
Fold 4: train tss = 0.7474 : val tss = 0.5702 ::: train hss = 0.5064 : val hss = 0.4317
mean cv TSS: 0.2634
mean cv HSS: 0.2172
527/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7893 : val tss = 0.1042 ::: train hss = 0.6800 : val hss = 0.0506
Fold 2: train tss = 0.1606 : val tss = 0.2038 ::: train hss = 0.2393 : val hss = 0.2709
Fold 3: train tss = 0.7288 : val tss = -0.0052 ::: train hss = 0.4147 : val hss = -0.0075
Fold 4: train tss = 0.7070 : val tss = 0.7603 ::: train hss = 0.4262 : val hss = 0.5201
mean cv TSS: 0.2126
mean cv HSS: 0.1668
528/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7148 : val tss = 0.2611 ::: train hss = 0.4174 : val hss = 0.1080
Fold 2: train tss = 0.4843 : val tss = 0.3357 ::: train hss = 0.3543 : val hss = 0.3440
Fold 3: train tss = 0.7875 : val tss = 0.0283 ::: train hss = 0.3584 : val hss = 0.0131
Fold 4: train tss = 0.7307 : val tss = 0.6210 ::: train hss = 0.3363 : val hss = 0.3223
mean cv TSS: 0.2492
mean cv HSS: 0.1575
529/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7026 : val tss = 0.1795 ::: train hss = 0.4727 : val hss = 0.1103
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7105 : val tss = 0.0191 ::: train hss = 0.3537 : val hss = 0.0167
Fold 4: train tss = 0.4920 : val tss = 0.5152 ::: train hss = 0.3419 : val hss = 0.3417
mean cv TSS: 0.1428
mean cv HSS: 0.0937
530/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7617 : val tss = 0.2036 ::: train hss = 0.5071 : val hss = 0.0854
Fold 2: train tss = 0.4028 : val tss = 0.2600 ::: train hss = 0.3577 : val hss = 0.2896
Fold 3: train tss = 0.7551 : val tss = 0.1389 ::: train hss = 0.4446 : val hss = 0.0367
Fold 4: train tss = 0.7247 : val tss = 0.4612 ::: train hss = 0.3983 : val hss = 0.3315
mean cv TSS: 0.2127
mean cv HSS: 0.1486
531/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7613 : val tss = 0.2542 ::: train hss = 0.3214 : val hss = 0.0912
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5356 : val tss = 0.0740 ::: train hss = 0.3089 : val hss = 0.0212
Fold 4: train tss = 0.3914 : val tss = 0.5075 ::: train hss = 0.2605 : val hss = 0.3040
mean cv TSS: 0.1671
mean cv HSS: 0.0833
532/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7843 : val tss = 0.2525 ::: train hss = 0.5836 : val hss = 0.1883
Fold 2: train tss = 0.3805 : val tss = 0.5806 ::: train hss = 0.3322 : val hss = 0.4159
Fold 3: train tss = 0.7821 : val tss = 0.3006 ::: train hss = 0.4620 : val hss = 0.1051
Fold 4: train tss = 0.7443 : val tss = 0.5138 ::: train hss = 0.4304 : val hss = 0.2731
mean cv TSS: 0.3295
mean cv HSS: 0.1965
533/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7608 : val tss = 0.1647 ::: train hss = 0.5577 : val hss = 0.0667
Fold 2: train tss = 0.3312 : val tss = 0.6001 ::: train hss = 0.3110 : val hss = 0.4400
Fold 3: train tss = 0.6579 : val tss = 0.0104 ::: train hss = 0.2723 : val hss = 0.0058
Fold 4: train tss = 0.5811 : val tss = 0.6749 ::: train hss = 0.2430 : val hss = 0.3170
mean cv TSS: 0.2900
mean cv HSS: 0.1659
534/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7237 : val tss = 0.2848 ::: train hss = 0.4656 : val hss = 0.1271
Fold 2: train tss = 0.4770 : val tss = 0.6659 ::: train hss = 0.2702 : val hss = 0.3363
Fold 3: train tss = 0.6717 : val tss = 0.0468 ::: train hss = 0.3276 : val hss = 0.0218
Fold 4: train tss = 0.6714 : val tss = 0.7159 ::: train hss = 0.3232 : val hss = 0.3121
mean cv TSS: 0.3427
mean cv HSS: 0.1595
535/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7122 : val tss = 0.2852 ::: train hss = 0.4851 : val hss = 0.1224
Fold 2: train tss = 0.5058 : val tss = 0.6440 ::: train hss = 0.2920 : val hss = 0.3673
Fold 3: train tss = 0.6921 : val tss = 0.0245 ::: train hss = 0.3446 : val hss = 0.0067
Fold 4: train tss = 0.6685 : val tss = 0.6750 ::: train hss = 0.3506 : val hss = 0.3115
mean cv TSS: 0.3257
mean cv HSS: 0.1616
536/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7625 : val tss = 0.2747 ::: train hss = 0.5851 : val hss = 0.1114
Fold 2: train tss = 0.5233 : val tss = 0.6627 ::: train hss = 0.3372 : val hss = 0.3499
Fold 3: train tss = 0.7150 : val tss = 0.1658 ::: train hss = 0.4034 : val hss = 0.0529
Fold 4: train tss = 0.7005 : val tss = 0.6492 ::: train hss = 0.3710 : val hss = 0.2873
mean cv TSS: 0.3505
mean cv HSS: 0.1603
537/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7110 : val tss = 0.2644 ::: train hss = 0.5300 : val hss = 0.1054
Fold 2: train tss = 0.4962 : val tss = 0.6549 ::: train hss = 0.3121 : val hss = 0.3369
Fold 3: train tss = 0.6937 : val tss = 0.0422 ::: train hss = 0.3769 : val hss = 0.0183
Fold 4: train tss = 0.6812 : val tss = 0.5612 ::: train hss = 0.3657 : val hss = 0.3144
mean cv TSS: 0.3045
mean cv HSS: 0.1550
538/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7699 : val tss = 0.2044 ::: train hss = 0.6421 : val hss = 0.0747
Fold 2: train tss = 0.6299 : val tss = 0.7265 ::: train hss = 0.4139 : val hss = 0.3962
Fold 3: train tss = 0.7269 : val tss = 0.0080 ::: train hss = 0.4227 : val hss = 0.0043
Fold 4: train tss = 0.7076 : val tss = 0.6222 ::: train hss = 0.4295 : val hss = 0.2937
mean cv TSS: 0.3122
mean cv HSS: 0.1538
539/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7762 : val tss = 0.2268 ::: train hss = 0.5957 : val hss = 0.0950
Fold 2: train tss = 0.6251 : val tss = 0.7034 ::: train hss = 0.4170 : val hss = 0.4350
Fold 3: train tss = 0.7561 : val tss = -0.0136 ::: train hss = 0.4672 : val hss = -0.0136
Fold 4: train tss = 0.7069 : val tss = 0.6946 ::: train hss = 0.4092 : val hss = 0.2993
mean cv TSS: 0.3222
mean cv HSS: 0.1631
540/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6425 : val tss = 0.1144 ::: train hss = 0.1356 : val hss = 0.1214
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6311 : val tss = 0.0641 ::: train hss = 0.2473 : val hss = 0.0255
Fold 4: train tss = 0.5795 : val tss = 0.5969 ::: train hss = 0.1710 : val hss = 0.2396
mean cv TSS: 0.1551
mean cv HSS: 0.0773
541/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5863 : val tss = 0.3425 ::: train hss = 0.1428 : val hss = 0.1273
Fold 2: train tss = 0.2729 : val tss = 0.2729 ::: train hss = 0.1650 : val hss = 0.3295
Fold 3: train tss = 0.4977 : val tss = 0.0429 ::: train hss = 0.1674 : val hss = 0.0145
Fold 4: train tss = 0.5420 : val tss = 0.7523 ::: train hss = 0.1680 : val hss = 0.3763
mean cv TSS: 0.2821
mean cv HSS: 0.1695
542/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6780 : val tss = 0.2090 ::: train hss = 0.1726 : val hss = 0.0615
Fold 2: train tss = -0.0037 : val tss = -0.0004 ::: train hss = -0.0059 : val hss = -0.0008
Fold 3: train tss = 0.6155 : val tss = 0.0298 ::: train hss = 0.1951 : val hss = 0.0210
Fold 4: train tss = 0.5366 : val tss = 0.7165 ::: train hss = 0.2009 : val hss = 0.3004
mean cv TSS: 0.1910
mean cv HSS: 0.0764
543/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5975 : val tss = 0.1716 ::: train hss = 0.2111 : val hss = 0.0620
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5870 : val tss = -0.0042 ::: train hss = 0.1976 : val hss = -0.0064
Fold 4: train tss = 0.3619 : val tss = 0.6251 ::: train hss = 0.1875 : val hss = 0.5286
mean cv TSS: 0.1585
mean cv HSS: 0.1168
544/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6333 : val tss = 0.1779 ::: train hss = 0.1982 : val hss = 0.0667
Fold 2: train tss = 0.0305 : val tss = 0.2348 ::: train hss = 0.0542 : val hss = 0.2070
Fold 3: train tss = 0.5993 : val tss = 0.1037 ::: train hss = 0.1765 : val hss = 0.0382
Fold 4: train tss = 0.5298 : val tss = 0.7444 ::: train hss = 0.1964 : val hss = 0.3039
mean cv TSS: 0.2522
mean cv HSS: 0.1231
545/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6636 : val tss = 0.1249 ::: train hss = 0.2410 : val hss = 0.0430
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5306 : val tss = 0.0367 ::: train hss = 0.2124 : val hss = 0.0315
Fold 4: train tss = 0.4486 : val tss = 0.7324 ::: train hss = 0.2309 : val hss = 0.4769
mean cv TSS: 0.1788
mean cv HSS: 0.1103
546/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7717 : val tss = 0.1322 ::: train hss = 0.5922 : val hss = 0.0518
Fold 2: train tss = 0.6530 : val tss = 0.5792 ::: train hss = 0.2086 : val hss = 0.4585
Fold 3: train tss = 0.7260 : val tss = 0.0201 ::: train hss = 0.4384 : val hss = 0.0113
Fold 4: train tss = 0.7116 : val tss = 0.6107 ::: train hss = 0.3644 : val hss = 0.2895
mean cv TSS: 0.2684
mean cv HSS: 0.1622
547/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5894 : val tss = 0.3551 ::: train hss = 0.6401 : val hss = 0.0997
Fold 2: train tss = 0.4461 : val tss = 0.5301 ::: train hss = 0.2100 : val hss = 0.4258
Fold 3: train tss = 0.7053 : val tss = 0.0618 ::: train hss = 0.3430 : val hss = 0.0274
Fold 4: train tss = 0.6061 : val tss = 0.5325 ::: train hss = 0.1953 : val hss = 0.3569
mean cv TSS: 0.2959
mean cv HSS: 0.1819
548/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7127 : val tss = 0.1683 ::: train hss = 0.4914 : val hss = 0.0691
Fold 2: train tss = 0.4378 : val tss = 0.6237 ::: train hss = 0.4031 : val hss = 0.3676
Fold 3: train tss = 0.7360 : val tss = 0.0317 ::: train hss = 0.4441 : val hss = 0.0118
Fold 4: train tss = 0.6765 : val tss = 0.7226 ::: train hss = 0.3993 : val hss = 0.3332
mean cv TSS: 0.3093
mean cv HSS: 0.1563
549/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7643 : val tss = 0.1879 ::: train hss = 0.3984 : val hss = 0.1048
Fold 2: train tss = 0.3674 : val tss = 0.5500 ::: train hss = 0.2530 : val hss = 0.4733
Fold 3: train tss = 0.6036 : val tss = 0.1273 ::: train hss = 0.3062 : val hss = 0.0360
Fold 4: train tss = 0.5816 : val tss = 0.7374 ::: train hss = 0.3159 : val hss = 0.4555
mean cv TSS: 0.3205
mean cv HSS: 0.2139
550/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7586 : val tss = 0.0700 ::: train hss = 0.6857 : val hss = 0.0486
Fold 2: train tss = 0.5396 : val tss = 0.4081 ::: train hss = 0.2596 : val hss = 0.4423
Fold 3: train tss = 0.8147 : val tss = 0.0473 ::: train hss = 0.5022 : val hss = 0.0125
Fold 4: train tss = 0.7057 : val tss = 0.6601 ::: train hss = 0.4309 : val hss = 0.4144
mean cv TSS: 0.2371
mean cv HSS: 0.1836
551/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7561 : val tss = 0.0396 ::: train hss = 0.7345 : val hss = 0.0147
Fold 2: train tss = 0.2836 : val tss = 0.3192 ::: train hss = 0.2860 : val hss = 0.3806
Fold 3: train tss = 0.6525 : val tss = -0.0049 ::: train hss = 0.3409 : val hss = -0.0073
Fold 4: train tss = 0.5804 : val tss = 0.7357 ::: train hss = 0.3719 : val hss = 0.3876
mean cv TSS: 0.2179
mean cv HSS: 0.1551
552/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6872 : val tss = 0.1507 ::: train hss = 0.4441 : val hss = 0.0748
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.7830 : val tss = -0.0044 ::: train hss = 0.4023 : val hss = -0.0044
Fold 4: train tss = 0.6957 : val tss = 0.6719 ::: train hss = 0.2523 : val hss = 0.2986
mean cv TSS: 0.1637
mean cv HSS: 0.0738
553/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6421 : val tss = 0.1681 ::: train hss = 0.6363 : val hss = 0.0762
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.5945 : val tss = 0.1837 ::: train hss = 0.2586 : val hss = 0.0582
Fold 4: train tss = 0.5850 : val tss = 0.6924 ::: train hss = 0.3202 : val hss = 0.3110
mean cv TSS: 0.2088
mean cv HSS: 0.0891
554/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7386 : val tss = 0.1140 ::: train hss = 0.4895 : val hss = 0.0464
Fold 2: train tss = 0.0011 : val tss = 0.0394 ::: train hss = 0.0021 : val hss = 0.0739
Fold 3: train tss = 0.7824 : val tss = 0.0379 ::: train hss = 0.4175 : val hss = 0.0211
Fold 4: train tss = 0.7085 : val tss = 0.7209 ::: train hss = 0.3636 : val hss = 0.3424
mean cv TSS: 0.1824
mean cv HSS: 0.0968
555/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6429 : val tss = 0.1487 ::: train hss = 0.5593 : val hss = 0.0641
Fold 2: train tss = 0.0000 : val tss = 0.0089 ::: train hss = 0.0000 : val hss = 0.0166
Fold 3: train tss = 0.5832 : val tss = 0.1198 ::: train hss = 0.2184 : val hss = 0.0218
Fold 4: train tss = 0.4234 : val tss = 0.6926 ::: train hss = 0.2934 : val hss = 0.2970
mean cv TSS: 0.1940
mean cv HSS: 0.0799
556/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8077 : val tss = 0.2264 ::: train hss = 0.6092 : val hss = 0.1506
Fold 2: train tss = 0.4656 : val tss = 0.5718 ::: train hss = 0.3138 : val hss = 0.4165
Fold 3: train tss = 0.7216 : val tss = 0.0425 ::: train hss = 0.3798 : val hss = 0.0218
Fold 4: train tss = 0.6961 : val tss = 0.4934 ::: train hss = 0.3221 : val hss = 0.2977
mean cv TSS: 0.2668
mean cv HSS: 0.1773
557/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7520 : val tss = 0.1815 ::: train hss = 0.4443 : val hss = 0.0925
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6731 : val tss = 0.0969 ::: train hss = 0.3255 : val hss = 0.0267
Fold 4: train tss = 0.5928 : val tss = 0.6716 ::: train hss = 0.3118 : val hss = 0.2468
mean cv TSS: 0.1900
mean cv HSS: 0.0732
558/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7074 : val tss = 0.2883 ::: train hss = 0.4781 : val hss = 0.1142
Fold 2: train tss = 0.4918 : val tss = 0.6862 ::: train hss = 0.2825 : val hss = 0.3619
Fold 3: train tss = 0.7021 : val tss = 0.0272 ::: train hss = 0.3686 : val hss = 0.0146
Fold 4: train tss = 0.6719 : val tss = 0.7260 ::: train hss = 0.3402 : val hss = 0.3456
mean cv TSS: 0.3455
mean cv HSS: 0.1673
559/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6829 : val tss = 0.3388 ::: train hss = 0.4997 : val hss = 0.1380
Fold 2: train tss = 0.5069 : val tss = 0.6395 ::: train hss = 0.3229 : val hss = 0.3588
Fold 3: train tss = 0.6869 : val tss = 0.0374 ::: train hss = 0.3568 : val hss = 0.0118
Fold 4: train tss = 0.6651 : val tss = 0.6968 ::: train hss = 0.3511 : val hss = 0.3034
mean cv TSS: 0.3425
mean cv HSS: 0.1624
560/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7595 : val tss = 0.2022 ::: train hss = 0.5371 : val hss = 0.0681
Fold 2: train tss = 0.5649 : val tss = 0.5877 ::: train hss = 0.3372 : val hss = 0.3415
Fold 3: train tss = 0.7149 : val tss = 0.0280 ::: train hss = 0.4061 : val hss = 0.0113
Fold 4: train tss = 0.6949 : val tss = 0.5672 ::: train hss = 0.3689 : val hss = 0.3074
mean cv TSS: 0.2770
mean cv HSS: 0.1456
561/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7612 : val tss = 0.2400 ::: train hss = 0.5636 : val hss = 0.0957
Fold 2: train tss = 0.5264 : val tss = 0.6032 ::: train hss = 0.3170 : val hss = 0.3201
Fold 3: train tss = 0.6983 : val tss = 0.0210 ::: train hss = 0.4317 : val hss = 0.0196
Fold 4: train tss = 0.6621 : val tss = 0.6904 ::: train hss = 0.3612 : val hss = 0.3373
mean cv TSS: 0.3109
mean cv HSS: 0.1545
562/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7676 : val tss = 0.1748 ::: train hss = 0.5984 : val hss = 0.0781
Fold 2: train tss = 0.6590 : val tss = 0.7028 ::: train hss = 0.3858 : val hss = 0.3827
Fold 3: train tss = 0.7981 : val tss = 0.1810 ::: train hss = 0.4961 : val hss = 0.1162
Fold 4: train tss = 0.7422 : val tss = 0.5838 ::: train hss = 0.4375 : val hss = 0.3789
mean cv TSS: 0.3285
mean cv HSS: 0.1912
563/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7775 : val tss = 0.1959 ::: train hss = 0.6192 : val hss = 0.0711
Fold 2: train tss = 0.6231 : val tss = 0.7281 ::: train hss = 0.4897 : val hss = 0.3672
Fold 3: train tss = 0.7594 : val tss = 0.0148 ::: train hss = 0.4793 : val hss = 0.0091
Fold 4: train tss = 0.7349 : val tss = 0.6950 ::: train hss = 0.4380 : val hss = 0.4601
mean cv TSS: 0.3268
mean cv HSS: 0.1815
564/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5636 : val tss = 0.2454 ::: train hss = 0.1943 : val hss = 0.0531
Fold 2: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 3: train tss = 0.6313 : val tss = 0.0535 ::: train hss = 0.2438 : val hss = 0.0184
Fold 4: train tss = 0.5451 : val tss = 0.7286 ::: train hss = 0.1943 : val hss = 0.2918
mean cv TSS: 0.2055
mean cv HSS: 0.0727
565/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5869 : val tss = 0.3379 ::: train hss = 0.1438 : val hss = 0.1249
Fold 2: train tss = 0.1516 : val tss = 0.4811 ::: train hss = 0.0996 : val hss = 0.3682
Fold 3: train tss = 0.5255 : val tss = 0.0453 ::: train hss = 0.1886 : val hss = 0.0179
Fold 4: train tss = 0.3484 : val tss = 0.7257 ::: train hss = 0.1488 : val hss = 0.2841
mean cv TSS: 0.3180
mean cv HSS: 0.1590
566/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6839 : val tss = 0.1806 ::: train hss = 0.0986 : val hss = 0.0434
Fold 2: train tss = 0.0004 : val tss = -0.0015 ::: train hss = 0.0008 : val hss = -0.0028
Fold 3: train tss = 0.5638 : val tss = 0.1638 ::: train hss = 0.1299 : val hss = 0.0335
Fold 4: train tss = 0.5445 : val tss = 0.7093 ::: train hss = 0.1419 : val hss = 0.2583
mean cv TSS: 0.2104
mean cv HSS: 0.0665
567/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6903 : val tss = 0.2270 ::: train hss = 0.1895 : val hss = 0.0535
Fold 2: train tss = 0.0700 : val tss = 0.4212 ::: train hss = 0.0528 : val hss = 0.3524
Fold 3: train tss = 0.6296 : val tss = 0.0842 ::: train hss = 0.1999 : val hss = 0.0345
Fold 4: train tss = 0.4295 : val tss = 0.6914 ::: train hss = 0.1362 : val hss = 0.2381
mean cv TSS: 0.2848
mean cv HSS: 0.1357
568/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6958 : val tss = -0.0188 ::: train hss = 0.0973 : val hss = -0.0070
Fold 2: train tss = 0.0017 : val tss = 0.0000 ::: train hss = 0.0034 : val hss = 0.0000
Fold 3: train tss = 0.5922 : val tss = 0.1109 ::: train hss = 0.1739 : val hss = 0.0356
Fold 4: train tss = 0.6010 : val tss = 0.6650 ::: train hss = 0.2065 : val hss = 0.3065
mean cv TSS: 0.1514
mean cv HSS: 0.0670
569/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6229 : val tss = 0.1746 ::: train hss = 0.1464 : val hss = 0.0549
Fold 2: train tss = -0.0002 : val tss = 0.0000 ::: train hss = -0.0003 : val hss = 0.0000
Fold 3: train tss = 0.4752 : val tss = 0.1961 ::: train hss = 0.1004 : val hss = 0.0235
Fold 4: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
mean cv TSS: 0.0741
mean cv HSS: 0.0157
570/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7122 : val tss = 0.1637 ::: train hss = 0.5484 : val hss = 0.0807
Fold 2: train tss = 0.6454 : val tss = 0.6633 ::: train hss = 0.2978 : val hss = 0.4216
Fold 3: train tss = 0.7294 : val tss = 0.0614 ::: train hss = 0.4360 : val hss = 0.0383
Fold 4: train tss = 0.6766 : val tss = 0.6547 ::: train hss = 0.2624 : val hss = 0.4766
mean cv TSS: 0.3086
mean cv HSS: 0.2034
571/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7111 : val tss = 0.3776 ::: train hss = 0.2633 : val hss = 0.0940
Fold 2: train tss = 0.2224 : val tss = 0.4464 ::: train hss = 0.2210 : val hss = 0.4084
Fold 3: train tss = 0.7647 : val tss = 0.0253 ::: train hss = 0.3989 : val hss = 0.0277
Fold 4: train tss = 0.6836 : val tss = 0.7164 ::: train hss = 0.2988 : val hss = 0.3579
mean cv TSS: 0.3131
mean cv HSS: 0.1776
572/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7826 : val tss = 0.0413 ::: train hss = 0.6312 : val hss = 0.0267
Fold 2: train tss = 0.2861 : val tss = 0.5683 ::: train hss = 0.3593 : val hss = 0.3727
Fold 3: train tss = 0.7519 : val tss = 0.0053 ::: train hss = 0.4944 : val hss = 0.0032
Fold 4: train tss = 0.7391 : val tss = 0.7320 ::: train hss = 0.4198 : val hss = 0.3867
mean cv TSS: 0.2694
mean cv HSS: 0.1578
573/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7608 : val tss = 0.2136 ::: train hss = 0.6357 : val hss = 0.0971
Fold 2: train tss = 0.1448 : val tss = 0.1886 ::: train hss = 0.1143 : val hss = 0.2560
Fold 3: train tss = 0.7198 : val tss = 0.0227 ::: train hss = 0.3496 : val hss = 0.0225
Fold 4: train tss = 0.6308 : val tss = 0.6376 ::: train hss = 0.2543 : val hss = 0.4114
mean cv TSS: 0.2125
mean cv HSS: 0.1574
574/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7659 : val tss = 0.0796 ::: train hss = 0.6497 : val hss = 0.0486
Fold 2: train tss = 0.6648 : val tss = 0.4302 ::: train hss = 0.4772 : val hss = 0.3083
Fold 3: train tss = 0.8240 : val tss = -0.0289 ::: train hss = 0.4375 : val hss = -0.0113
Fold 4: train tss = 0.5801 : val tss = 0.6554 ::: train hss = 0.3803 : val hss = 0.3388
mean cv TSS: 0.2273
mean cv HSS: 0.1369
575/768
{'batch_size': 4864, 'bce_pos_class_weight': 15, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7674 : val tss = 0.1705 ::: train hss = 0.6838 : val hss = 0.0727
Fold 2: train tss = 0.2975 : val tss = 0.5488 ::: train hss = 0.2767 : val hss = 0.2661
Fold 3: train tss = 0.7852 : val tss = 0.0214 ::: train hss = 0.3819 : val hss = 0.0203
Fold 4: train tss = 0.6887 : val tss = 0.7227 ::: train hss = 0.3570 : val hss = 0.3183
mean cv TSS: 0.2927
mean cv HSS: 0.1355
576/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.9274 : val tss = -0.0286 ::: train hss = 0.1641 : val hss = -0.0242
Fold 1: train tss = 0.8067 : val tss = 0.0776 ::: train hss = 0.3940 : val hss = 0.0427
Fold 2: train tss = 0.7312 : val tss = 0.6591 ::: train hss = 0.2444 : val hss = 0.3221
Fold 3: train tss = 0.8038 : val tss = 0.0236 ::: train hss = 0.2864 : val hss = 0.0179
Fold 4: train tss = 0.7682 : val tss = 0.6569 ::: train hss = 0.2108 : val hss = 0.2935
mean cv TSS: 0.2777
mean cv HSS: 0.1304
577/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.8812 : val tss = 0.0000 ::: train hss = 0.1817 : val hss = 0.0000
Fold 1: train tss = 0.8315 : val tss = 0.1072 ::: train hss = 0.4600 : val hss = 0.0462
Fold 2: train tss = 0.6499 : val tss = 0.5137 ::: train hss = 0.0994 : val hss = 0.2350
Fold 3: train tss = 0.6502 : val tss = 0.3022 ::: train hss = 0.1279 : val hss = 0.0353
Fold 4: train tss = 0.6708 : val tss = 0.6193 ::: train hss = 0.1495 : val hss = 0.2796
mean cv TSS: 0.3085
mean cv HSS: 0.1192
578/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.1995 : val tss = 0.0000 ::: train hss = 0.2850 : val hss = 0.0000
Fold 1: train tss = 0.7362 : val tss = 0.0885 ::: train hss = 0.2230 : val hss = 0.0443
Fold 2: train tss = 0.6852 : val tss = 0.7208 ::: train hss = 0.1403 : val hss = 0.3619
Fold 3: train tss = 0.7829 : val tss = 0.1022 ::: train hss = 0.2373 : val hss = 0.0247
Fold 4: train tss = 0.7884 : val tss = 0.5643 ::: train hss = 0.2400 : val hss = 0.3221
mean cv TSS: 0.2952
mean cv HSS: 0.1506
579/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8301 : val tss = 0.0578 ::: train hss = 0.3270 : val hss = 0.0175
Fold 2: train tss = 0.7079 : val tss = 0.7231 ::: train hss = 0.2141 : val hss = 0.3931
Fold 3: train tss = 0.7294 : val tss = 0.0499 ::: train hss = 0.2253 : val hss = 0.0211
Fold 4: train tss = 0.6842 : val tss = 0.6367 ::: train hss = 0.1443 : val hss = 0.2229
mean cv TSS: 0.2935
mean cv HSS: 0.1309
580/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.5430 : val tss = -0.0051 ::: train hss = 0.2468 : val hss = -0.0085
Fold 1: train tss = 0.8713 : val tss = 0.1889 ::: train hss = 0.3439 : val hss = 0.1230
Fold 2: train tss = 0.7449 : val tss = 0.6776 ::: train hss = 0.1788 : val hss = 0.2901
Fold 3: train tss = 0.7772 : val tss = 0.3162 ::: train hss = 0.2385 : val hss = 0.0397
Fold 4: train tss = 0.6275 : val tss = 0.5447 ::: train hss = 0.1144 : val hss = 0.2182
mean cv TSS: 0.3445
mean cv HSS: 0.1325
581/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.3449 : val tss = -0.0005 ::: train hss = 0.1999 : val hss = -0.0010
Fold 1: train tss = 0.8030 : val tss = 0.1582 ::: train hss = 0.4802 : val hss = 0.0682
Fold 2: train tss = 0.5609 : val tss = 0.5198 ::: train hss = 0.1741 : val hss = 0.1508
Fold 3: train tss = 0.7672 : val tss = 0.2725 ::: train hss = 0.2246 : val hss = 0.0463
Fold 4: train tss = 0.6846 : val tss = 0.4861 ::: train hss = 0.1657 : val hss = 0.1677
mean cv TSS: 0.2872
mean cv HSS: 0.0864
582/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7836 : val tss = 0.2335 ::: train hss = 0.3054 : val hss = 0.0898
Fold 2: train tss = 0.7351 : val tss = 0.5970 ::: train hss = 0.1928 : val hss = 0.4443
Fold 3: train tss = 0.7753 : val tss = 0.1172 ::: train hss = 0.2383 : val hss = 0.0275
Fold 4: train tss = 0.7030 : val tss = 0.6629 ::: train hss = 0.1556 : val hss = 0.2550
mean cv TSS: 0.3221
mean cv HSS: 0.1633
583/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7968 : val tss = 0.2614 ::: train hss = 0.2892 : val hss = 0.1175
Fold 2: train tss = 0.6538 : val tss = 0.6944 ::: train hss = 0.2132 : val hss = 0.3698
Fold 3: train tss = 0.7565 : val tss = 0.2837 ::: train hss = 0.2321 : val hss = 0.0895
Fold 4: train tss = 0.7360 : val tss = 0.6580 ::: train hss = 0.2022 : val hss = 0.3182
mean cv TSS: 0.3795
mean cv HSS: 0.1790
584/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.2989 : val tss = -0.0140 ::: train hss = 0.3416 : val hss = -0.0179
Fold 1: train tss = 0.7986 : val tss = 0.0539 ::: train hss = 0.4347 : val hss = 0.0252
Fold 2: train tss = 0.7198 : val tss = 0.6207 ::: train hss = 0.1604 : val hss = 0.2701
Fold 3: train tss = 0.7908 : val tss = 0.1703 ::: train hss = 0.2451 : val hss = 0.0366
Fold 4: train tss = 0.7176 : val tss = 0.4466 ::: train hss = 0.1937 : val hss = 0.2745
mean cv TSS: 0.2555
mean cv HSS: 0.1177
585/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8111 : val tss = 0.0385 ::: train hss = 0.3953 : val hss = 0.0201
Fold 2: train tss = 0.6791 : val tss = 0.6639 ::: train hss = 0.1457 : val hss = 0.2904
Fold 3: train tss = 0.6223 : val tss = 0.2359 ::: train hss = 0.1254 : val hss = 0.0357
Fold 4: train tss = 0.6994 : val tss = 0.6399 ::: train hss = 0.1690 : val hss = 0.2641
mean cv TSS: 0.3156
mean cv HSS: 0.1221
586/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.3483 : val tss = 0.0000 ::: train hss = 0.3398 : val hss = 0.0000
Fold 1: train tss = 0.8365 : val tss = 0.1385 ::: train hss = 0.4274 : val hss = 0.0701
Fold 2: train tss = 0.7955 : val tss = 0.6335 ::: train hss = 0.2704 : val hss = 0.3918
Fold 3: train tss = 0.7949 : val tss = 0.3004 ::: train hss = 0.2765 : val hss = 0.0417
Fold 4: train tss = 0.7891 : val tss = 0.3559 ::: train hss = 0.2585 : val hss = 0.2631
mean cv TSS: 0.2857
mean cv HSS: 0.1533
587/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.3468 : val tss = -0.0005 ::: train hss = 0.2618 : val hss = -0.0010
Fold 1: train tss = 0.8296 : val tss = 0.1746 ::: train hss = 0.4870 : val hss = 0.0622
Fold 2: train tss = 0.6970 : val tss = 0.6270 ::: train hss = 0.1355 : val hss = 0.3103
Fold 3: train tss = 0.7153 : val tss = 0.2593 ::: train hss = 0.2060 : val hss = 0.0387
Fold 4: train tss = 0.7344 : val tss = 0.6790 ::: train hss = 0.2186 : val hss = 0.2406
mean cv TSS: 0.3479
mean cv HSS: 0.1302
588/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.6795 : val tss = -0.0392 ::: train hss = 0.1332 : val hss = -0.0281
Fold 1: train tss = 0.7037 : val tss = 0.1892 ::: train hss = 0.1234 : val hss = 0.1449
Fold 2: train tss = 0.5931 : val tss = 0.6096 ::: train hss = 0.0811 : val hss = 0.2416
Fold 3: train tss = 0.7165 : val tss = 0.1261 ::: train hss = 0.1832 : val hss = 0.0274
Fold 4: train tss = 0.7253 : val tss = 0.6490 ::: train hss = 0.2018 : val hss = 0.2816
mean cv TSS: 0.3069
mean cv HSS: 0.1335
589/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.1463 : val tss = -0.0030 ::: train hss = 0.1083 : val hss = -0.0053
Fold 1: train tss = 0.7474 : val tss = 0.3467 ::: train hss = 0.2198 : val hss = 0.1641
Fold 2: train tss = 0.6032 : val tss = 0.7019 ::: train hss = 0.0917 : val hss = 0.3652
Fold 3: train tss = 0.5477 : val tss = 0.1210 ::: train hss = 0.0896 : val hss = 0.0177
Fold 4: train tss = 0.5950 : val tss = 0.5132 ::: train hss = 0.1044 : val hss = 0.1309
mean cv TSS: 0.3359
mean cv HSS: 0.1345
590/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6922 : val tss = 0.1446 ::: train hss = 0.0969 : val hss = 0.0335
Fold 2: train tss = 0.6808 : val tss = 0.6502 ::: train hss = 0.1154 : val hss = 0.2522
Fold 3: train tss = 0.5797 : val tss = 0.0918 ::: train hss = 0.1345 : val hss = 0.0107
Fold 4: train tss = 0.5944 : val tss = 0.4619 ::: train hss = 0.1032 : val hss = 0.1687
mean cv TSS: 0.2697
mean cv HSS: 0.0930
591/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6239 : val tss = 0.2642 ::: train hss = 0.0766 : val hss = 0.0512
Fold 2: train tss = 0.4946 : val tss = 0.6075 ::: train hss = 0.0636 : val hss = 0.2131
Fold 3: train tss = 0.4558 : val tss = 0.1808 ::: train hss = 0.0560 : val hss = 0.0227
Fold 4: train tss = 0.5476 : val tss = 0.5885 ::: train hss = 0.0813 : val hss = 0.1599
mean cv TSS: 0.3282
mean cv HSS: 0.0894
592/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.7877 : val tss = -0.0351 ::: train hss = 0.2300 : val hss = -0.0292
Fold 1: train tss = 0.8589 : val tss = 0.0637 ::: train hss = 0.2142 : val hss = 0.0431
Fold 2: train tss = 0.6038 : val tss = 0.6492 ::: train hss = 0.0800 : val hss = 0.3391
Fold 3: train tss = 0.6048 : val tss = 0.0269 ::: train hss = 0.0973 : val hss = 0.0064
Fold 4: train tss = 0.5785 : val tss = 0.2555 ::: train hss = 0.0925 : val hss = 0.0958
mean cv TSS: 0.1920
mean cv HSS: 0.0911
593/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 248673
Fold 0: train tss = 0.4419 : val tss = 0.1075 ::: train hss = 0.1861 : val hss = 0.1197
Fold 1: train tss = 0.7153 : val tss = -0.0538 ::: train hss = 0.1006 : val hss = -0.0114
Fold 2: train tss = 0.3753 : val tss = 0.5771 ::: train hss = 0.0267 : val hss = 0.2623
Fold 3: train tss = 0.6173 : val tss = 0.2005 ::: train hss = 0.1332 : val hss = 0.0324
Fold 4: train tss = 0.5765 : val tss = 0.6135 ::: train hss = 0.0948 : val hss = 0.1750
mean cv TSS: 0.2890
mean cv HSS: 0.1156
594/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7780 : val tss = 0.2061 ::: train hss = 0.4050 : val hss = 0.1463
Fold 2: train tss = 0.6291 : val tss = 0.6128 ::: train hss = 0.1015 : val hss = 0.2642
Fold 3: train tss = 0.7874 : val tss = 0.0314 ::: train hss = 0.3099 : val hss = 0.0132
Fold 4: train tss = 0.6850 : val tss = 0.7198 ::: train hss = 0.1491 : val hss = 0.3123
mean cv TSS: 0.3140
mean cv HSS: 0.1472
595/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7470 : val tss = 0.3572 ::: train hss = 0.2431 : val hss = 0.1407
Fold 2: train tss = 0.5396 : val tss = 0.5759 ::: train hss = 0.0795 : val hss = 0.3027
Fold 3: train tss = 0.6772 : val tss = 0.1359 ::: train hss = 0.1624 : val hss = 0.0259
Fold 4: train tss = 0.6263 : val tss = 0.5462 ::: train hss = 0.1217 : val hss = 0.1545
mean cv TSS: 0.3231
mean cv HSS: 0.1248
596/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.4879 : val tss = -0.0084 ::: train hss = 0.1501 : val hss = -0.0126
Fold 1: train tss = 0.8191 : val tss = 0.1255 ::: train hss = 0.1901 : val hss = 0.0477
Fold 2: train tss = 0.5450 : val tss = 0.3825 ::: train hss = 0.1442 : val hss = 0.0856
Fold 3: train tss = 0.7879 : val tss = 0.1317 ::: train hss = 0.2900 : val hss = 0.0773
Fold 4: train tss = 0.7504 : val tss = 0.5786 ::: train hss = 0.2105 : val hss = 0.2866
mean cv TSS: 0.2420
mean cv HSS: 0.0969
597/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.3378 : val tss = 0.3595 ::: train hss = 0.0934 : val hss = 0.1857
Fold 2: train tss = 0.5816 : val tss = 0.5873 ::: train hss = 0.1027 : val hss = 0.2908
Fold 3: train tss = 0.6726 : val tss = 0.1007 ::: train hss = 0.1827 : val hss = 0.0134
Fold 4: train tss = 0.6058 : val tss = 0.6380 ::: train hss = 0.1117 : val hss = 0.2703
mean cv TSS: 0.3371
mean cv HSS: 0.1520
598/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.4449 : val tss = -0.0074 ::: train hss = 0.2506 : val hss = -0.0114
Fold 1: train tss = 0.8346 : val tss = -0.0175 ::: train hss = 0.3799 : val hss = -0.0211
Fold 2: train tss = 0.6913 : val tss = 0.6391 ::: train hss = 0.2109 : val hss = 0.2641
Fold 3: train tss = 0.6627 : val tss = 0.3277 ::: train hss = 0.1508 : val hss = 0.0501
Fold 4: train tss = 0.6368 : val tss = 0.5840 ::: train hss = 0.1410 : val hss = 0.1639
mean cv TSS: 0.3052
mean cv HSS: 0.0891
599/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.8355 : val tss = 0.0000 ::: train hss = 0.2142 : val hss = 0.0000
Fold 1: train tss = 0.7636 : val tss = 0.2182 ::: train hss = 0.6049 : val hss = 0.1003
Fold 2: train tss = 0.5420 : val tss = 0.5596 ::: train hss = 0.1099 : val hss = 0.1829
Fold 3: train tss = 0.6856 : val tss = 0.2841 ::: train hss = 0.1476 : val hss = 0.0398
Fold 4: train tss = 0.6435 : val tss = 0.5870 ::: train hss = 0.1380 : val hss = 0.2000
mean cv TSS: 0.3298
mean cv HSS: 0.1046
600/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.9317 : val tss = -0.0100 ::: train hss = 0.1951 : val hss = -0.0143
Fold 1: train tss = 0.8426 : val tss = 0.1252 ::: train hss = 0.3255 : val hss = 0.0950
Fold 2: train tss = 0.7467 : val tss = 0.6646 ::: train hss = 0.2494 : val hss = 0.3659
Fold 3: train tss = 0.7981 : val tss = 0.1328 ::: train hss = 0.2374 : val hss = 0.0568
Fold 4: train tss = 0.7908 : val tss = 0.6947 ::: train hss = 0.2488 : val hss = 0.2526
mean cv TSS: 0.3215
mean cv HSS: 0.1512
601/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.6871 : val tss = 0.0000 ::: train hss = 0.1949 : val hss = 0.0000
Fold 1: train tss = 0.8284 : val tss = 0.1704 ::: train hss = 0.2396 : val hss = 0.0858
Fold 2: train tss = 0.7157 : val tss = 0.6996 ::: train hss = 0.2163 : val hss = 0.3469
Fold 3: train tss = 0.6993 : val tss = 0.0161 ::: train hss = 0.1502 : val hss = 0.0041
Fold 4: train tss = 0.7255 : val tss = 0.5479 ::: train hss = 0.1918 : val hss = 0.1583
mean cv TSS: 0.2868
mean cv HSS: 0.1190
602/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.5438 : val tss = -0.0038 ::: train hss = 0.2653 : val hss = -0.0067
Fold 1: train tss = 0.7903 : val tss = 0.0925 ::: train hss = 0.2370 : val hss = 0.0434
Fold 2: train tss = 0.7321 : val tss = 0.7376 ::: train hss = 0.1637 : val hss = 0.3778
Fold 3: train tss = 0.7746 : val tss = 0.1174 ::: train hss = 0.2384 : val hss = 0.0198
Fold 4: train tss = 0.7766 : val tss = 0.5413 ::: train hss = 0.2251 : val hss = 0.2617
mean cv TSS: 0.2970
mean cv HSS: 0.1392
603/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7834 : val tss = 0.1903 ::: train hss = 0.4556 : val hss = 0.0550
Fold 2: train tss = 0.7017 : val tss = 0.6827 ::: train hss = 0.1678 : val hss = 0.2747
Fold 3: train tss = 0.7587 : val tss = 0.3017 ::: train hss = 0.2174 : val hss = 0.0546
Fold 4: train tss = 0.6532 : val tss = 0.5527 ::: train hss = 0.1164 : val hss = 0.2594
mean cv TSS: 0.3455
mean cv HSS: 0.1288
604/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8898 : val tss = 0.1529 ::: train hss = 0.4808 : val hss = 0.0582
Fold 2: train tss = 0.7746 : val tss = 0.6587 ::: train hss = 0.2092 : val hss = 0.3552
Fold 3: train tss = 0.7916 : val tss = 0.2208 ::: train hss = 0.2721 : val hss = 0.0343
Fold 4: train tss = 0.6953 : val tss = 0.6105 ::: train hss = 0.1487 : val hss = 0.2388
mean cv TSS: 0.3286
mean cv HSS: 0.1373
605/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.3983 : val tss = -0.0006 ::: train hss = 0.3793 : val hss = -0.0012
Fold 1: train tss = 0.8616 : val tss = 0.0810 ::: train hss = 0.2534 : val hss = 0.0416
Fold 2: train tss = 0.6616 : val tss = 0.6745 ::: train hss = 0.1320 : val hss = 0.3168
Fold 3: train tss = 0.7565 : val tss = 0.3082 ::: train hss = 0.2530 : val hss = 0.0301
Fold 4: train tss = 0.7013 : val tss = 0.7345 ::: train hss = 0.1786 : val hss = 0.2994
mean cv TSS: 0.3595
mean cv HSS: 0.1373
606/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8026 : val tss = 0.0844 ::: train hss = 0.3388 : val hss = 0.0401
Fold 2: train tss = 0.7311 : val tss = 0.6301 ::: train hss = 0.1893 : val hss = 0.3277
Fold 3: train tss = 0.7577 : val tss = 0.2264 ::: train hss = 0.2357 : val hss = 0.0491
Fold 4: train tss = 0.7123 : val tss = 0.6390 ::: train hss = 0.1711 : val hss = 0.2037
mean cv TSS: 0.3160
mean cv HSS: 0.1241
607/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7999 : val tss = 0.3038 ::: train hss = 0.2683 : val hss = 0.1149
Fold 2: train tss = 0.7372 : val tss = 0.6746 ::: train hss = 0.2324 : val hss = 0.3568
Fold 3: train tss = 0.7842 : val tss = 0.3044 ::: train hss = 0.2689 : val hss = 0.0345
Fold 4: train tss = 0.7365 : val tss = 0.6641 ::: train hss = 0.1928 : val hss = 0.2679
mean cv TSS: 0.3894
mean cv HSS: 0.1548
608/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.4893 : val tss = -0.0042 ::: train hss = 0.1659 : val hss = -0.0072
Fold 1: train tss = 0.7819 : val tss = 0.2236 ::: train hss = 0.4408 : val hss = 0.0971
Fold 2: train tss = 0.7372 : val tss = 0.6066 ::: train hss = 0.2293 : val hss = 0.3491
Fold 3: train tss = 0.7701 : val tss = 0.0715 ::: train hss = 0.2503 : val hss = 0.0220
Fold 4: train tss = 0.7463 : val tss = 0.6162 ::: train hss = 0.2003 : val hss = 0.2120
mean cv TSS: 0.3027
mean cv HSS: 0.1346
609/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7918 : val tss = 0.1299 ::: train hss = 0.4127 : val hss = 0.0774
Fold 2: train tss = 0.6888 : val tss = 0.6727 ::: train hss = 0.1395 : val hss = 0.2829
Fold 3: train tss = 0.7398 : val tss = 0.0571 ::: train hss = 0.2047 : val hss = 0.0139
Fold 4: train tss = 0.7515 : val tss = 0.6021 ::: train hss = 0.2032 : val hss = 0.3544
mean cv TSS: 0.2924
mean cv HSS: 0.1457
610/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.2995 : val tss = 0.0041 ::: train hss = 0.3993 : val hss = 0.0079
Fold 1: train tss = 0.9140 : val tss = 0.2117 ::: train hss = 0.4628 : val hss = 0.0864
Fold 2: train tss = 0.6480 : val tss = 0.5915 ::: train hss = 0.0782 : val hss = 0.2070
Fold 3: train tss = 0.7993 : val tss = 0.1144 ::: train hss = 0.2599 : val hss = 0.0382
Fold 4: train tss = 0.7673 : val tss = 0.6184 ::: train hss = 0.2078 : val hss = 0.3727
mean cv TSS: 0.3080
mean cv HSS: 0.1425
611/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.3455 : val tss = 0.1434 ::: train hss = 0.2159 : val hss = 0.1601
Fold 1: train tss = 0.9024 : val tss = 0.1716 ::: train hss = 0.4760 : val hss = 0.0594
Fold 2: train tss = 0.7639 : val tss = 0.6630 ::: train hss = 0.2273 : val hss = 0.3973
Fold 3: train tss = 0.6660 : val tss = 0.2397 ::: train hss = 0.1642 : val hss = 0.0264
Fold 4: train tss = 0.7215 : val tss = 0.6452 ::: train hss = 0.1671 : val hss = 0.2348
mean cv TSS: 0.3726
mean cv HSS: 0.1756
612/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = -0.0307 ::: train hss = 0.0000 : val hss = -0.0275
Fold 1: train tss = 0.6705 : val tss = 0.3934 ::: train hss = 0.1370 : val hss = 0.0774
Fold 2: train tss = 0.5804 : val tss = 0.6468 ::: train hss = 0.1225 : val hss = 0.2493
Fold 3: train tss = 0.6456 : val tss = 0.0423 ::: train hss = 0.1238 : val hss = 0.0160
Fold 4: train tss = 0.7085 : val tss = 0.6782 ::: train hss = 0.1775 : val hss = 0.2271
mean cv TSS: 0.3460
mean cv HSS: 0.1085
613/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6247 : val tss = 0.3567 ::: train hss = 0.0802 : val hss = 0.0563
Fold 2: train tss = 0.5056 : val tss = 0.5555 ::: train hss = 0.0540 : val hss = 0.1704
Fold 3: train tss = 0.5625 : val tss = 0.4478 ::: train hss = 0.0936 : val hss = 0.0522
Fold 4: train tss = 0.5007 : val tss = 0.6403 ::: train hss = 0.0729 : val hss = 0.2022
mean cv TSS: 0.4001
mean cv HSS: 0.0962
614/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = -0.0380 ::: train hss = 0.0000 : val hss = -0.0301
Fold 1: train tss = 0.7115 : val tss = 0.2870 ::: train hss = 0.1107 : val hss = 0.0793
Fold 2: train tss = 0.6012 : val tss = 0.6242 ::: train hss = 0.0708 : val hss = 0.2353
Fold 3: train tss = 0.7348 : val tss = 0.1028 ::: train hss = 0.2155 : val hss = 0.0423
Fold 4: train tss = 0.6162 : val tss = 0.6099 ::: train hss = 0.0972 : val hss = 0.1756
mean cv TSS: 0.3172
mean cv HSS: 0.1005
615/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6774 : val tss = 0.3439 ::: train hss = 0.0722 : val hss = 0.0636
Fold 2: train tss = 0.5602 : val tss = 0.6325 ::: train hss = 0.0671 : val hss = 0.2340
Fold 3: train tss = 0.5438 : val tss = 0.1208 ::: train hss = 0.0821 : val hss = 0.0178
Fold 4: train tss = 0.4557 : val tss = 0.6941 ::: train hss = 0.0644 : val hss = 0.2375
mean cv TSS: 0.3583
mean cv HSS: 0.1106
616/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.4884 : val tss = 0.0212 ::: train hss = 0.1563 : val hss = 0.0062
Fold 1: train tss = 0.8056 : val tss = 0.0702 ::: train hss = 0.2464 : val hss = 0.0408
Fold 2: train tss = 0.4283 : val tss = 0.5879 ::: train hss = 0.0382 : val hss = 0.2961
Fold 3: train tss = 0.6140 : val tss = 0.0921 ::: train hss = 0.1071 : val hss = 0.0078
Fold 4: train tss = 0.6644 : val tss = 0.6813 ::: train hss = 0.1346 : val hss = 0.2690
mean cv TSS: 0.2905
mean cv HSS: 0.1240
617/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = -0.0090 : val tss = 0.0000 ::: train hss = -0.0038 : val hss = 0.0000
Fold 1: train tss = 0.7011 : val tss = -0.0334 ::: train hss = 0.0861 : val hss = -0.0046
Fold 2: train tss = 0.4116 : val tss = 0.5822 ::: train hss = 0.0380 : val hss = 0.1894
Fold 3: train tss = 0.5626 : val tss = 0.2598 ::: train hss = 0.0939 : val hss = 0.0177
Fold 4: train tss = 0.5348 : val tss = 0.5894 ::: train hss = 0.0774 : val hss = 0.1613
mean cv TSS: 0.2796
mean cv HSS: 0.0728
618/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.6371 : val tss = 0.0000 ::: train hss = 0.1820 : val hss = 0.0000
Fold 1: train tss = 0.7786 : val tss = 0.1492 ::: train hss = 0.3761 : val hss = 0.1577
Fold 2: train tss = 0.6414 : val tss = 0.6391 ::: train hss = 0.1441 : val hss = 0.2646
Fold 3: train tss = 0.7215 : val tss = 0.1659 ::: train hss = 0.2119 : val hss = 0.0400
Fold 4: train tss = 0.6971 : val tss = 0.6904 ::: train hss = 0.1823 : val hss = 0.2601
mean cv TSS: 0.3289
mean cv HSS: 0.1445
619/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.3464 : val tss = 0.0000 ::: train hss = 0.2431 : val hss = 0.0000
Fold 1: train tss = 0.7673 : val tss = 0.1801 ::: train hss = 0.2419 : val hss = 0.1455
Fold 2: train tss = 0.5952 : val tss = 0.6229 ::: train hss = 0.1017 : val hss = 0.3127
Fold 3: train tss = 0.5048 : val tss = 0.3023 ::: train hss = 0.0701 : val hss = 0.0328
Fold 4: train tss = 0.6355 : val tss = 0.6059 ::: train hss = 0.1225 : val hss = 0.1757
mean cv TSS: 0.3422
mean cv HSS: 0.1333
620/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.3924 : val tss = -0.0006 ::: train hss = 0.1725 : val hss = -0.0012
Fold 1: train tss = 0.7782 : val tss = 0.1304 ::: train hss = 0.5557 : val hss = 0.0909
Fold 2: train tss = 0.7041 : val tss = 0.6229 ::: train hss = 0.1222 : val hss = 0.3735
Fold 3: train tss = 0.7335 : val tss = 0.2184 ::: train hss = 0.2429 : val hss = 0.0517
Fold 4: train tss = 0.7529 : val tss = 0.5884 ::: train hss = 0.2268 : val hss = 0.2156
mean cv TSS: 0.3119
mean cv HSS: 0.1461
621/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.4407 : val tss = -0.0063 ::: train hss = 0.1663 : val hss = -0.0101
Fold 1: train tss = 0.6363 : val tss = 0.3110 ::: train hss = 0.0793 : val hss = 0.0515
Fold 2: train tss = 0.5756 : val tss = 0.6041 ::: train hss = 0.1298 : val hss = 0.2047
Fold 3: train tss = 0.5012 : val tss = 0.3343 ::: train hss = 0.0690 : val hss = 0.0370
Fold 4: train tss = 0.5965 : val tss = 0.3749 ::: train hss = 0.1137 : val hss = 0.0734
mean cv TSS: 0.3236
mean cv HSS: 0.0713
622/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.8883 : val tss = 0.0073 ::: train hss = 0.2652 : val hss = 0.0111
Fold 1: train tss = 0.8260 : val tss = 0.0417 ::: train hss = 0.3795 : val hss = 0.0229
Fold 2: train tss = 0.7514 : val tss = 0.6458 ::: train hss = 0.1681 : val hss = 0.3017
Fold 3: train tss = 0.7526 : val tss = -0.0388 ::: train hss = 0.2026 : val hss = -0.0108
Fold 4: train tss = 0.5469 : val tss = 0.5919 ::: train hss = 0.1127 : val hss = 0.1955
mean cv TSS: 0.2496
mean cv HSS: 0.1041
623/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.3462 : val tss = -0.0014 ::: train hss = 0.2388 : val hss = -0.0026
Fold 1: train tss = 0.8156 : val tss = 0.1313 ::: train hss = 0.5286 : val hss = 0.0680
Fold 2: train tss = 0.4450 : val tss = 0.6429 ::: train hss = 0.1086 : val hss = 0.2561
Fold 3: train tss = 0.4111 : val tss = 0.3479 ::: train hss = 0.0482 : val hss = 0.0211
Fold 4: train tss = 0.6506 : val tss = 0.7224 ::: train hss = 0.1502 : val hss = 0.3015
mean cv TSS: 0.3686
mean cv HSS: 0.1288
624/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.7656 : val tss = -0.0440 ::: train hss = 0.0954 : val hss = -0.0245
Fold 1: train tss = 0.7347 : val tss = 0.2366 ::: train hss = 0.2743 : val hss = 0.0675
Fold 2: train tss = 0.7138 : val tss = 0.6971 ::: train hss = 0.1728 : val hss = 0.3391
Fold 3: train tss = 0.7662 : val tss = 0.2203 ::: train hss = 0.2385 : val hss = 0.0426
Fold 4: train tss = 0.7135 : val tss = 0.6162 ::: train hss = 0.1651 : val hss = 0.2230
mean cv TSS: 0.3452
mean cv HSS: 0.1295
625/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7934 : val tss = 0.1731 ::: train hss = 0.2925 : val hss = 0.0728
Fold 2: train tss = 0.6172 : val tss = 0.6393 ::: train hss = 0.1033 : val hss = 0.2911
Fold 3: train tss = 0.7286 : val tss = 0.0097 ::: train hss = 0.1890 : val hss = 0.0039
Fold 4: train tss = 0.7031 : val tss = 0.5567 ::: train hss = 0.1866 : val hss = 0.1803
mean cv TSS: 0.2758
mean cv HSS: 0.1096
626/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7662 : val tss = 0.0655 ::: train hss = 0.2160 : val hss = 0.0201
Fold 2: train tss = 0.7057 : val tss = 0.6914 ::: train hss = 0.1767 : val hss = 0.3224
Fold 3: train tss = 0.7214 : val tss = 0.2333 ::: train hss = 0.1861 : val hss = 0.0367
Fold 4: train tss = 0.7537 : val tss = 0.6324 ::: train hss = 0.2114 : val hss = 0.2173
mean cv TSS: 0.3245
mean cv HSS: 0.1193
627/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7984 : val tss = 0.1027 ::: train hss = 0.3162 : val hss = 0.0401
Fold 2: train tss = 0.6649 : val tss = 0.7212 ::: train hss = 0.1907 : val hss = 0.3585
Fold 3: train tss = 0.7251 : val tss = 0.3545 ::: train hss = 0.2074 : val hss = 0.0674
Fold 4: train tss = 0.6557 : val tss = 0.6774 ::: train hss = 0.1243 : val hss = 0.2369
mean cv TSS: 0.3712
mean cv HSS: 0.1406
628/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.3418 : val tss = -0.0201 ::: train hss = 0.1455 : val hss = -0.0223
Fold 1: train tss = 0.8432 : val tss = 0.1299 ::: train hss = 0.3529 : val hss = 0.0548
Fold 2: train tss = 0.6815 : val tss = 0.7545 ::: train hss = 0.1497 : val hss = 0.4347
Fold 3: train tss = 0.7602 : val tss = 0.3474 ::: train hss = 0.2163 : val hss = 0.0486
Fold 4: train tss = 0.6838 : val tss = 0.5187 ::: train hss = 0.1530 : val hss = 0.1740
mean cv TSS: 0.3461
mean cv HSS: 0.1380
629/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.3957 : val tss = 0.0003 ::: train hss = 0.2513 : val hss = 0.0004
Fold 1: train tss = 0.8119 : val tss = 0.0595 ::: train hss = 0.3707 : val hss = 0.0213
Fold 2: train tss = 0.6723 : val tss = 0.6862 ::: train hss = 0.1299 : val hss = 0.2630
Fold 3: train tss = 0.7133 : val tss = 0.3527 ::: train hss = 0.1915 : val hss = 0.0303
Fold 4: train tss = 0.6762 : val tss = 0.5559 ::: train hss = 0.1564 : val hss = 0.1921
mean cv TSS: 0.3310
mean cv HSS: 0.1014
630/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7698 : val tss = 0.3371 ::: train hss = 0.2369 : val hss = 0.1180
Fold 2: train tss = 0.6598 : val tss = 0.6252 ::: train hss = 0.1489 : val hss = 0.2567
Fold 3: train tss = 0.6699 : val tss = 0.1183 ::: train hss = 0.1687 : val hss = 0.0156
Fold 4: train tss = 0.6819 : val tss = 0.6675 ::: train hss = 0.1550 : val hss = 0.2305
mean cv TSS: 0.3496
mean cv HSS: 0.1242
631/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7541 : val tss = 0.3318 ::: train hss = 0.2684 : val hss = 0.1017
Fold 2: train tss = 0.6207 : val tss = 0.6497 ::: train hss = 0.1460 : val hss = 0.3206
Fold 3: train tss = 0.6674 : val tss = 0.0872 ::: train hss = 0.1644 : val hss = 0.0162
Fold 4: train tss = 0.6258 : val tss = 0.5622 ::: train hss = 0.1251 : val hss = 0.1534
mean cv TSS: 0.3262
mean cv HSS: 0.1184
632/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7791 : val tss = 0.2566 ::: train hss = 0.2540 : val hss = 0.0703
Fold 2: train tss = 0.6448 : val tss = 0.6132 ::: train hss = 0.1610 : val hss = 0.2640
Fold 3: train tss = 0.7134 : val tss = 0.0497 ::: train hss = 0.1874 : val hss = 0.0105
Fold 4: train tss = 0.6702 : val tss = 0.6391 ::: train hss = 0.1474 : val hss = 0.2516
mean cv TSS: 0.3117
mean cv HSS: 0.1193
633/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7725 : val tss = 0.2540 ::: train hss = 0.3636 : val hss = 0.0895
Fold 2: train tss = 0.6239 : val tss = 0.5770 ::: train hss = 0.1448 : val hss = 0.2300
Fold 3: train tss = 0.7264 : val tss = 0.0013 ::: train hss = 0.2138 : val hss = 0.0003
Fold 4: train tss = 0.6793 : val tss = 0.6576 ::: train hss = 0.1583 : val hss = 0.2575
mean cv TSS: 0.2980
mean cv HSS: 0.1155
634/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8247 : val tss = 0.1672 ::: train hss = 0.3445 : val hss = 0.0517
Fold 2: train tss = 0.7310 : val tss = 0.5787 ::: train hss = 0.1967 : val hss = 0.2500
Fold 3: train tss = 0.7654 : val tss = 0.1976 ::: train hss = 0.2379 : val hss = 0.0298
Fold 4: train tss = 0.7312 : val tss = 0.5486 ::: train hss = 0.2161 : val hss = 0.1630
mean cv TSS: 0.2984
mean cv HSS: 0.0989
635/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = -0.0017 ::: train hss = 0.0000 : val hss = -0.0033
Fold 1: train tss = 0.7884 : val tss = 0.2070 ::: train hss = 0.3868 : val hss = 0.0706
Fold 2: train tss = 0.6704 : val tss = 0.5932 ::: train hss = 0.2084 : val hss = 0.2207
Fold 3: train tss = 0.7266 : val tss = 0.1680 ::: train hss = 0.2011 : val hss = 0.0357
Fold 4: train tss = 0.7479 : val tss = 0.6312 ::: train hss = 0.2210 : val hss = 0.2959
mean cv TSS: 0.3195
mean cv HSS: 0.1239
636/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7377 : val tss = 0.2846 ::: train hss = 0.1235 : val hss = 0.0964
Fold 2: train tss = 0.5937 : val tss = 0.6478 ::: train hss = 0.0774 : val hss = 0.2387
Fold 3: train tss = 0.7387 : val tss = 0.0668 ::: train hss = 0.2103 : val hss = 0.0109
Fold 4: train tss = 0.6049 : val tss = 0.5987 ::: train hss = 0.0950 : val hss = 0.1706
mean cv TSS: 0.3196
mean cv HSS: 0.1033
637/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6876 : val tss = 0.3776 ::: train hss = 0.1091 : val hss = 0.1570
Fold 2: train tss = 0.4995 : val tss = 0.5165 ::: train hss = 0.0647 : val hss = 0.1517
Fold 3: train tss = 0.6486 : val tss = 0.0988 ::: train hss = 0.1450 : val hss = 0.0215
Fold 4: train tss = 0.5516 : val tss = 0.4857 ::: train hss = 0.0868 : val hss = 0.1109
mean cv TSS: 0.2957
mean cv HSS: 0.0882
638/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.3453 : val tss = -0.0048 ::: train hss = 0.2093 : val hss = -0.0069
Fold 1: train tss = 0.6873 : val tss = 0.1322 ::: train hss = 0.1121 : val hss = 0.0334
Fold 2: train tss = 0.5838 : val tss = 0.6393 ::: train hss = 0.0762 : val hss = 0.2241
Fold 3: train tss = 0.6890 : val tss = 0.3753 ::: train hss = 0.1602 : val hss = 0.0577
Fold 4: train tss = 0.6699 : val tss = 0.6389 ::: train hss = 0.1420 : val hss = 0.2442
mean cv TSS: 0.3562
mean cv HSS: 0.1105
639/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6362 : val tss = 0.2663 ::: train hss = 0.0760 : val hss = 0.0515
Fold 2: train tss = 0.4984 : val tss = 0.4550 ::: train hss = 0.0592 : val hss = 0.1033
Fold 3: train tss = 0.6152 : val tss = 0.2344 ::: train hss = 0.1218 : val hss = 0.0213
Fold 4: train tss = 0.5242 : val tss = 0.4684 ::: train hss = 0.0797 : val hss = 0.1036
mean cv TSS: 0.2848
mean cv HSS: 0.0559
640/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8474 : val tss = 0.1376 ::: train hss = 0.2157 : val hss = 0.0511
Fold 2: train tss = 0.5806 : val tss = 0.6036 ::: train hss = 0.0876 : val hss = 0.2054
Fold 3: train tss = 0.6545 : val tss = 0.2798 ::: train hss = 0.1328 : val hss = 0.0272
Fold 4: train tss = 0.6004 : val tss = 0.6171 ::: train hss = 0.1133 : val hss = 0.1852
mean cv TSS: 0.3276
mean cv HSS: 0.0938
641/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.4933 : val tss = -0.0065 ::: train hss = 0.2321 : val hss = -0.0103
Fold 1: train tss = 0.7426 : val tss = 0.0248 ::: train hss = 0.1095 : val hss = 0.0050
Fold 2: train tss = 0.5137 : val tss = 0.5542 ::: train hss = 0.0574 : val hss = 0.1636
Fold 3: train tss = 0.4783 : val tss = -0.0474 ::: train hss = 0.0634 : val hss = -0.0017
Fold 4: train tss = 0.5627 : val tss = 0.5311 ::: train hss = 0.0930 : val hss = 0.1299
mean cv TSS: 0.2112
mean cv HSS: 0.0573
642/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 60257
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7962 : val tss = 0.1351 ::: train hss = 0.3264 : val hss = 0.0491
Fold 2: train tss = 0.6353 : val tss = 0.6601 ::: train hss = 0.1570 : val hss = 0.3490
Fold 3: train tss = 0.6693 : val tss = 0.1355 ::: train hss = 0.1490 : val hss = 0.0228
Fold 4: train tss = 0.6623 : val tss = 0.5803 ::: train hss = 0.1415 : val hss = 0.2137
mean cv TSS: 0.3022
mean cv HSS: 0.1269
643/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 60257
Fold 0: train tss = -0.0001 : val tss = 0.0000 ::: train hss = -0.0002 : val hss = 0.0000
Fold 1: train tss = 0.6359 : val tss = 0.3406 ::: train hss = 0.3636 : val hss = 0.1457
Fold 2: train tss = 0.5310 : val tss = 0.6000 ::: train hss = 0.0807 : val hss = 0.3281
Fold 3: train tss = 0.5859 : val tss = 0.0599 ::: train hss = 0.1019 : val hss = 0.0112
Fold 4: train tss = 0.6266 : val tss = 0.6758 ::: train hss = 0.1203 : val hss = 0.2455
mean cv TSS: 0.3353
mean cv HSS: 0.1461
644/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 125793
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7676 : val tss = 0.0981 ::: train hss = 0.4725 : val hss = 0.0511
Fold 2: train tss = 0.5825 : val tss = 0.6107 ::: train hss = 0.1665 : val hss = 0.2059
Fold 3: train tss = 0.7261 : val tss = 0.3251 ::: train hss = 0.1967 : val hss = 0.0697
Fold 4: train tss = 0.7150 : val tss = 0.6549 ::: train hss = 0.2002 : val hss = 0.2290
mean cv TSS: 0.3378
mean cv HSS: 0.1111
645/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 125793
Fold 0: train tss = 0.1484 : val tss = 0.0000 ::: train hss = 0.1649 : val hss = 0.0000
Fold 1: train tss = 0.7364 : val tss = 0.3004 ::: train hss = 0.1073 : val hss = 0.0445
Fold 2: train tss = 0.4942 : val tss = 0.5895 ::: train hss = 0.0695 : val hss = 0.3061
Fold 3: train tss = 0.6730 : val tss = 0.1655 ::: train hss = 0.1628 : val hss = 0.0284
Fold 4: train tss = 0.5008 : val tss = 0.5888 ::: train hss = 0.0735 : val hss = 0.1612
mean cv TSS: 0.3289
mean cv HSS: 0.1080
646/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 248673
Fold 0: train tss = 0.3439 : val tss = -0.0025 ::: train hss = 0.1786 : val hss = -0.0030
Fold 1: train tss = 0.7953 : val tss = 0.1340 ::: train hss = 0.5492 : val hss = 0.0629
Fold 2: train tss = 0.5698 : val tss = 0.5585 ::: train hss = 0.1116 : val hss = 0.2907
Fold 3: train tss = 0.7465 : val tss = 0.2070 ::: train hss = 0.2738 : val hss = 0.0298
Fold 4: train tss = 0.7769 : val tss = 0.5680 ::: train hss = 0.2584 : val hss = 0.2606
mean cv TSS: 0.2930
mean cv HSS: 0.1282
647/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 248673
Fold 0: train tss = 0.2956 : val tss = 0.0034 ::: train hss = 0.1907 : val hss = 0.0047
Fold 1: train tss = 0.7800 : val tss = 0.0805 ::: train hss = 0.4230 : val hss = 0.0456
Fold 2: train tss = 0.5234 : val tss = 0.5946 ::: train hss = 0.0673 : val hss = 0.2645
Fold 3: train tss = 0.6262 : val tss = 0.2737 ::: train hss = 0.1643 : val hss = 0.0421
Fold 4: train tss = 0.5886 : val tss = 0.5808 ::: train hss = 0.1014 : val hss = 0.1609
mean cv TSS: 0.3066
mean cv HSS: 0.1035
648/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 175969
Fold 0: train tss = -0.0005 : val tss = -0.0012 ::: train hss = -0.0008 : val hss = -0.0024
Fold 1: train tss = 0.7797 : val tss = 0.2004 ::: train hss = 0.3546 : val hss = 0.0638
Fold 2: train tss = 0.7293 : val tss = 0.6620 ::: train hss = 0.2035 : val hss = 0.2378
Fold 3: train tss = 0.7442 : val tss = 0.1028 ::: train hss = 0.2175 : val hss = 0.0151
Fold 4: train tss = 0.7407 : val tss = 0.4982 ::: train hss = 0.1879 : val hss = 0.1631
mean cv TSS: 0.2924
mean cv HSS: 0.0955
649/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8436 : val tss = 0.0802 ::: train hss = 0.3305 : val hss = 0.0396
Fold 2: train tss = 0.6885 : val tss = 0.6897 ::: train hss = 0.1431 : val hss = 0.3658
Fold 3: train tss = 0.6678 : val tss = 0.1341 ::: train hss = 0.1437 : val hss = 0.0289
Fold 4: train tss = 0.7044 : val tss = 0.6389 ::: train hss = 0.1616 : val hss = 0.2094
mean cv TSS: 0.3086
mean cv HSS: 0.1287
650/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7455 : val tss = 0.1802 ::: train hss = 0.1960 : val hss = 0.0515
Fold 2: train tss = 0.6566 : val tss = 0.6746 ::: train hss = 0.1233 : val hss = 0.2601
Fold 3: train tss = 0.7344 : val tss = 0.5491 ::: train hss = 0.1990 : val hss = 0.0557
Fold 4: train tss = 0.7268 : val tss = 0.6581 ::: train hss = 0.1809 : val hss = 0.2278
mean cv TSS: 0.4124
mean cv HSS: 0.1190
651/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7975 : val tss = 0.0759 ::: train hss = 0.1561 : val hss = 0.0237
Fold 2: train tss = 0.6989 : val tss = 0.6941 ::: train hss = 0.1516 : val hss = 0.3245
Fold 3: train tss = 0.5136 : val tss = 0.0895 ::: train hss = 0.0830 : val hss = 0.0160
Fold 4: train tss = 0.6215 : val tss = 0.6035 ::: train hss = 0.1155 : val hss = 0.2679
mean cv TSS: 0.2926
mean cv HSS: 0.1264
652/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7540 : val tss = 0.1371 ::: train hss = 0.1974 : val hss = 0.0446
Fold 2: train tss = 0.7088 : val tss = 0.6830 ::: train hss = 0.1378 : val hss = 0.3058
Fold 3: train tss = 0.7137 : val tss = 0.3589 ::: train hss = 0.1854 : val hss = 0.0382
Fold 4: train tss = 0.6500 : val tss = 0.5655 ::: train hss = 0.1349 : val hss = 0.1528
mean cv TSS: 0.3489
mean cv HSS: 0.1083
653/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8261 : val tss = 0.1614 ::: train hss = 0.3081 : val hss = 0.0608
Fold 2: train tss = 0.6204 : val tss = 0.6716 ::: train hss = 0.1248 : val hss = 0.2870
Fold 3: train tss = 0.6738 : val tss = 0.2742 ::: train hss = 0.1696 : val hss = 0.0270
Fold 4: train tss = 0.6567 : val tss = 0.6360 ::: train hss = 0.1305 : val hss = 0.2115
mean cv TSS: 0.3486
mean cv HSS: 0.1173
654/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7273 : val tss = 0.3368 ::: train hss = 0.2328 : val hss = 0.1139
Fold 2: train tss = 0.6555 : val tss = 0.6424 ::: train hss = 0.1507 : val hss = 0.2790
Fold 3: train tss = 0.6788 : val tss = 0.1900 ::: train hss = 0.1658 : val hss = 0.0273
Fold 4: train tss = 0.6966 : val tss = 0.6608 ::: train hss = 0.1664 : val hss = 0.2504
mean cv TSS: 0.3660
mean cv HSS: 0.1341
655/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = -0.0012 : val tss = 0.2974 ::: train hss = -0.0016 : val hss = 0.1862
Fold 1: train tss = 0.7400 : val tss = 0.2509 ::: train hss = 0.2621 : val hss = 0.0768
Fold 2: train tss = 0.6698 : val tss = 0.6632 ::: train hss = 0.1613 : val hss = 0.2778
Fold 3: train tss = 0.7262 : val tss = 0.0280 ::: train hss = 0.2010 : val hss = 0.0130
Fold 4: train tss = 0.6778 : val tss = 0.6206 ::: train hss = 0.1536 : val hss = 0.2403
mean cv TSS: 0.3720
mean cv HSS: 0.1588
656/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7592 : val tss = 0.2221 ::: train hss = 0.3101 : val hss = 0.0808
Fold 2: train tss = 0.6581 : val tss = 0.6181 ::: train hss = 0.1415 : val hss = 0.2915
Fold 3: train tss = 0.7236 : val tss = 0.2448 ::: train hss = 0.1935 : val hss = 0.0412
Fold 4: train tss = 0.7147 : val tss = 0.6446 ::: train hss = 0.1746 : val hss = 0.2798
mean cv TSS: 0.3459
mean cv HSS: 0.1387
657/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7964 : val tss = 0.2571 ::: train hss = 0.3281 : val hss = 0.0875
Fold 2: train tss = 0.6532 : val tss = 0.5605 ::: train hss = 0.1736 : val hss = 0.2192
Fold 3: train tss = 0.7214 : val tss = 0.0215 ::: train hss = 0.1933 : val hss = 0.0070
Fold 4: train tss = 0.6765 : val tss = 0.7012 ::: train hss = 0.1606 : val hss = 0.2685
mean cv TSS: 0.3081
mean cv HSS: 0.1164
658/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7931 : val tss = 0.1130 ::: train hss = 0.4674 : val hss = 0.0413
Fold 2: train tss = 0.7009 : val tss = 0.6401 ::: train hss = 0.2166 : val hss = 0.2445
Fold 3: train tss = 0.7489 : val tss = 0.0515 ::: train hss = 0.2194 : val hss = 0.0142
Fold 4: train tss = 0.7514 : val tss = 0.5675 ::: train hss = 0.2079 : val hss = 0.2253
mean cv TSS: 0.2744
mean cv HSS: 0.1051
659/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 741217
Fold 0: train tss = 0.3465 : val tss = 0.1905 ::: train hss = 0.2475 : val hss = 0.1287
Fold 1: train tss = 0.8253 : val tss = 0.1978 ::: train hss = 0.4427 : val hss = 0.0657
Fold 2: train tss = 0.7223 : val tss = 0.6663 ::: train hss = 0.1910 : val hss = 0.3105
Fold 3: train tss = 0.7645 : val tss = 0.3233 ::: train hss = 0.2376 : val hss = 0.0293
Fold 4: train tss = 0.6928 : val tss = 0.5827 ::: train hss = 0.1698 : val hss = 0.2640
mean cv TSS: 0.3921
mean cv HSS: 0.1597
660/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6458 : val tss = 0.3475 ::: train hss = 0.0822 : val hss = 0.0746
Fold 2: train tss = 0.6072 : val tss = 0.6828 ::: train hss = 0.0727 : val hss = 0.2532
Fold 3: train tss = 0.7095 : val tss = -0.0041 ::: train hss = 0.2007 : val hss = -0.0014
Fold 4: train tss = 0.5995 : val tss = 0.5509 ::: train hss = 0.1026 : val hss = 0.1434
mean cv TSS: 0.3154
mean cv HSS: 0.0940
661/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6828 : val tss = 0.2547 ::: train hss = 0.1380 : val hss = 0.1124
Fold 2: train tss = 0.4846 : val tss = 0.5346 ::: train hss = 0.0499 : val hss = 0.1787
Fold 3: train tss = 0.5618 : val tss = 0.2013 ::: train hss = 0.0942 : val hss = 0.0226
Fold 4: train tss = 0.5888 : val tss = 0.3757 ::: train hss = 0.1063 : val hss = 0.0737
mean cv TSS: 0.2733
mean cv HSS: 0.0775
662/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = 0.4744 : val tss = -0.0795 ::: train hss = 0.0787 : val hss = -0.0362
Fold 1: train tss = 0.6965 : val tss = 0.2826 ::: train hss = 0.0929 : val hss = 0.0454
Fold 2: train tss = 0.6348 : val tss = 0.6008 ::: train hss = 0.0849 : val hss = 0.2069
Fold 3: train tss = 0.6149 : val tss = 0.2417 ::: train hss = 0.1104 : val hss = 0.0423
Fold 4: train tss = 0.5965 : val tss = 0.5577 ::: train hss = 0.1008 : val hss = 0.1493
mean cv TSS: 0.3207
mean cv HSS: 0.0815
663/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6720 : val tss = 0.2587 ::: train hss = 0.0713 : val hss = 0.0504
Fold 2: train tss = 0.5022 : val tss = 0.6655 ::: train hss = 0.0546 : val hss = 0.2320
Fold 3: train tss = 0.5911 : val tss = 0.2053 ::: train hss = 0.1023 : val hss = 0.0191
Fold 4: train tss = 0.5374 : val tss = 0.3938 ::: train hss = 0.0760 : val hss = 0.0784
mean cv TSS: 0.3047
mean cv HSS: 0.0760
664/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 741217
Fold 0: train tss = 0.4404 : val tss = -0.0308 ::: train hss = 0.1631 : val hss = -0.0202
Fold 1: train tss = 0.7128 : val tss = 0.0497 ::: train hss = 0.0745 : val hss = 0.0111
Fold 2: train tss = 0.5764 : val tss = 0.5552 ::: train hss = 0.0900 : val hss = 0.1653
Fold 3: train tss = 0.6109 : val tss = 0.3112 ::: train hss = 0.1152 : val hss = 0.0231
Fold 4: train tss = 0.5594 : val tss = 0.5075 ::: train hss = 0.0826 : val hss = 0.1206
mean cv TSS: 0.2786
mean cv HSS: 0.0600
665/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.2206 : val tss = -0.0402 ::: train hss = 0.0332 : val hss = -0.0309
Fold 1: train tss = 0.6907 : val tss = 0.0186 ::: train hss = 0.0699 : val hss = 0.0016
Fold 2: train tss = 0.4599 : val tss = 0.5837 ::: train hss = 0.0499 : val hss = 0.1870
Fold 3: train tss = 0.5931 : val tss = 0.1905 ::: train hss = 0.1082 : val hss = 0.0170
Fold 4: train tss = 0.5229 : val tss = 0.4903 ::: train hss = 0.0770 : val hss = 0.1124
mean cv TSS: 0.2486
mean cv HSS: 0.0574
666/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 175969
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7719 : val tss = 0.1186 ::: train hss = 0.3102 : val hss = 0.1013
Fold 2: train tss = 0.6963 : val tss = 0.6595 ::: train hss = 0.1765 : val hss = 0.2858
Fold 3: train tss = 0.6412 : val tss = 0.3529 ::: train hss = 0.1421 : val hss = 0.0363
Fold 4: train tss = 0.6746 : val tss = 0.6402 ::: train hss = 0.1484 : val hss = 0.2046
mean cv TSS: 0.3542
mean cv HSS: 0.1256
667/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 175969
Fold 0: train tss = 0.1448 : val tss = -0.0019 ::: train hss = 0.0878 : val hss = -0.0034
Fold 1: train tss = 0.6406 : val tss = 0.3773 ::: train hss = 0.1010 : val hss = 0.1139
Fold 2: train tss = 0.6413 : val tss = 0.6371 ::: train hss = 0.1248 : val hss = 0.3372
Fold 3: train tss = 0.6076 : val tss = 0.3377 ::: train hss = 0.1223 : val hss = 0.0514
Fold 4: train tss = 0.5280 : val tss = 0.6600 ::: train hss = 0.0762 : val hss = 0.2132
mean cv TSS: 0.4020
mean cv HSS: 0.1424
668/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 372577
Fold 0: train tss = -0.0001 : val tss = -0.0005 ::: train hss = -0.0002 : val hss = -0.0010
Fold 1: train tss = 0.7112 : val tss = 0.2067 ::: train hss = 0.1831 : val hss = 0.0760
Fold 2: train tss = 0.6775 : val tss = 0.6844 ::: train hss = 0.1178 : val hss = 0.3661
Fold 3: train tss = 0.5136 : val tss = 0.1812 ::: train hss = 0.1074 : val hss = 0.0219
Fold 4: train tss = 0.6790 : val tss = 0.6943 ::: train hss = 0.1523 : val hss = 0.2727
mean cv TSS: 0.3532
mean cv HSS: 0.1471
669/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 372577
Fold 0: train tss = 0.3887 : val tss = -0.0092 ::: train hss = 0.1285 : val hss = -0.0134
Fold 1: train tss = 0.7707 : val tss = 0.1065 ::: train hss = 0.3263 : val hss = 0.0747
Fold 2: train tss = 0.4994 : val tss = 0.6261 ::: train hss = 0.0804 : val hss = 0.2685
Fold 3: train tss = 0.5215 : val tss = 0.2560 ::: train hss = 0.1108 : val hss = 0.0268
Fold 4: train tss = 0.6735 : val tss = 0.5866 ::: train hss = 0.1677 : val hss = 0.1633
mean cv TSS: 0.3132
mean cv HSS: 0.1040
670/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 741217
Fold 0: train tss = 0.4948 : val tss = 0.0008 ::: train hss = 0.2711 : val hss = 0.0010
Fold 1: train tss = 0.7924 : val tss = 0.1596 ::: train hss = 0.5106 : val hss = 0.0755
Fold 2: train tss = 0.6599 : val tss = 0.6167 ::: train hss = 0.1188 : val hss = 0.2276
Fold 3: train tss = 0.6117 : val tss = 0.1688 ::: train hss = 0.1185 : val hss = 0.0361
Fold 4: train tss = 0.7198 : val tss = 0.5583 ::: train hss = 0.1815 : val hss = 0.2679
mean cv TSS: 0.3008
mean cv HSS: 0.1216
671/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 16, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 741217
Fold 0: train tss = 0.3457 : val tss = -0.0090 ::: train hss = 0.2231 : val hss = -0.0115
Fold 1: train tss = 0.8271 : val tss = 0.1322 ::: train hss = 0.3345 : val hss = 0.0656
Fold 2: train tss = 0.6176 : val tss = 0.5728 ::: train hss = 0.0972 : val hss = 0.3728
Fold 3: train tss = 0.7024 : val tss = 0.2827 ::: train hss = 0.1907 : val hss = 0.0805
Fold 4: train tss = 0.6480 : val tss = 0.6245 ::: train hss = 0.1534 : val hss = 0.2656
mean cv TSS: 0.3206
mean cv HSS: 0.1546
672/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0496 : val tss = 0.0000 ::: train hss = 0.0827 : val hss = 0.0000
Fold 1: train tss = 0.8115 : val tss = 0.1661 ::: train hss = 0.2984 : val hss = 0.0760
Fold 2: train tss = 0.7348 : val tss = 0.6503 ::: train hss = 0.1970 : val hss = 0.3109
Fold 3: train tss = 0.7430 : val tss = 0.0604 ::: train hss = 0.1919 : val hss = 0.0151
Fold 4: train tss = 0.7690 : val tss = 0.6704 ::: train hss = 0.2218 : val hss = 0.2630
mean cv TSS: 0.3094
mean cv HSS: 0.1330
673/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7488 : val tss = 0.1962 ::: train hss = 0.2490 : val hss = 0.1133
Fold 2: train tss = 0.6608 : val tss = 0.6252 ::: train hss = 0.1384 : val hss = 0.4056
Fold 3: train tss = 0.7697 : val tss = 0.0577 ::: train hss = 0.2414 : val hss = 0.0278
Fold 4: train tss = 0.6154 : val tss = 0.5791 ::: train hss = 0.1051 : val hss = 0.1636
mean cv TSS: 0.2917
mean cv HSS: 0.1421
674/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7907 : val tss = 0.2202 ::: train hss = 0.2995 : val hss = 0.0885
Fold 2: train tss = 0.6936 : val tss = 0.7301 ::: train hss = 0.1465 : val hss = 0.4092
Fold 3: train tss = 0.7660 : val tss = 0.0720 ::: train hss = 0.2115 : val hss = 0.0223
Fold 4: train tss = 0.7632 : val tss = 0.6294 ::: train hss = 0.2096 : val hss = 0.2327
mean cv TSS: 0.3303
mean cv HSS: 0.1505
675/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0499 : val tss = 0.0000 ::: train hss = 0.0907 : val hss = 0.0000
Fold 1: train tss = 0.7896 : val tss = 0.2760 ::: train hss = 0.2350 : val hss = 0.1107
Fold 2: train tss = 0.6601 : val tss = 0.7293 ::: train hss = 0.1448 : val hss = 0.4415
Fold 3: train tss = 0.7397 : val tss = 0.4033 ::: train hss = 0.2099 : val hss = 0.0655
Fold 4: train tss = 0.6747 : val tss = 0.6750 ::: train hss = 0.1401 : val hss = 0.2347
mean cv TSS: 0.4167
mean cv HSS: 0.1705
676/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8536 : val tss = 0.2257 ::: train hss = 0.2676 : val hss = 0.1167
Fold 2: train tss = 0.7033 : val tss = 0.6269 ::: train hss = 0.1630 : val hss = 0.2803
Fold 3: train tss = 0.7238 : val tss = 0.1411 ::: train hss = 0.2003 : val hss = 0.0301
Fold 4: train tss = 0.7484 : val tss = 0.6275 ::: train hss = 0.2099 : val hss = 0.3067
mean cv TSS: 0.3242
mean cv HSS: 0.1468
677/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.5415 : val tss = -0.0027 ::: train hss = 0.2144 : val hss = -0.0031
Fold 1: train tss = 0.7870 : val tss = 0.0598 ::: train hss = 0.4488 : val hss = 0.0151
Fold 2: train tss = 0.5890 : val tss = 0.5894 ::: train hss = 0.1094 : val hss = 0.2120
Fold 3: train tss = 0.6009 : val tss = 0.1694 ::: train hss = 0.1269 : val hss = 0.0075
Fold 4: train tss = 0.7070 : val tss = 0.6999 ::: train hss = 0.1985 : val hss = 0.3013
mean cv TSS: 0.3032
mean cv HSS: 0.1066
678/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.1967 : val tss = 0.0000 ::: train hss = 0.1543 : val hss = 0.0000
Fold 1: train tss = 0.8558 : val tss = 0.1765 ::: train hss = 0.4076 : val hss = 0.1029
Fold 2: train tss = 0.6732 : val tss = 0.5927 ::: train hss = 0.2622 : val hss = 0.1911
Fold 3: train tss = 0.8102 : val tss = 0.3260 ::: train hss = 0.2971 : val hss = 0.0489
Fold 4: train tss = 0.7915 : val tss = 0.4772 ::: train hss = 0.2576 : val hss = 0.2578
mean cv TSS: 0.3145
mean cv HSS: 0.1201
679/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = -0.0004 : val tss = -0.0019 ::: train hss = -0.0006 : val hss = -0.0034
Fold 1: train tss = 0.8281 : val tss = 0.1342 ::: train hss = 0.4699 : val hss = 0.0671
Fold 2: train tss = 0.7817 : val tss = 0.6573 ::: train hss = 0.2097 : val hss = 0.3995
Fold 3: train tss = 0.8018 : val tss = 0.0301 ::: train hss = 0.2803 : val hss = 0.0214
Fold 4: train tss = 0.7615 : val tss = 0.6105 ::: train hss = 0.2090 : val hss = 0.2199
mean cv TSS: 0.2861
mean cv HSS: 0.1409
680/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.1994 : val tss = 0.0000 ::: train hss = 0.2750 : val hss = 0.0000
Fold 1: train tss = 0.7534 : val tss = 0.1677 ::: train hss = 0.2832 : val hss = 0.0673
Fold 2: train tss = 0.7478 : val tss = 0.6603 ::: train hss = 0.2128 : val hss = 0.3056
Fold 3: train tss = 0.6189 : val tss = -0.0546 ::: train hss = 0.1128 : val hss = -0.0093
Fold 4: train tss = 0.7833 : val tss = 0.5810 ::: train hss = 0.2202 : val hss = 0.3386
mean cv TSS: 0.2709
mean cv HSS: 0.1405
681/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 385569
Fold 0: train tss = 0.3958 : val tss = -0.0021 ::: train hss = 0.2513 : val hss = -0.0039
Fold 1: train tss = 0.7737 : val tss = 0.1728 ::: train hss = 0.4052 : val hss = 0.0758
Fold 2: train tss = 0.4623 : val tss = 0.5251 ::: train hss = 0.0937 : val hss = 0.2994
Fold 3: train tss = 0.7615 : val tss = 0.2482 ::: train hss = 0.2287 : val hss = 0.0331
Fold 4: train tss = 0.7371 : val tss = 0.5558 ::: train hss = 0.1753 : val hss = 0.3595
mean cv TSS: 0.3000
mean cv HSS: 0.1528
682/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.4451 : val tss = -0.0015 ::: train hss = 0.2580 : val hss = -0.0028
Fold 1: train tss = 0.8451 : val tss = 0.1568 ::: train hss = 0.4669 : val hss = 0.0817
Fold 2: train tss = 0.6912 : val tss = 0.6409 ::: train hss = 0.3295 : val hss = 0.2673
Fold 3: train tss = 0.7678 : val tss = 0.2142 ::: train hss = 0.2617 : val hss = 0.0493
Fold 4: train tss = 0.7756 : val tss = 0.6037 ::: train hss = 0.2017 : val hss = 0.3011
mean cv TSS: 0.3228
mean cv HSS: 0.1393
683/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.3960 : val tss = -0.0017 ::: train hss = 0.2597 : val hss = -0.0033
Fold 1: train tss = 0.8344 : val tss = 0.0885 ::: train hss = 0.4917 : val hss = 0.0398
Fold 2: train tss = 0.7912 : val tss = 0.5868 ::: train hss = 0.3631 : val hss = 0.1864
Fold 3: train tss = 0.7930 : val tss = 0.2146 ::: train hss = 0.3491 : val hss = 0.0339
Fold 4: train tss = 0.7765 : val tss = 0.3385 ::: train hss = 0.2466 : val hss = 0.2953
mean cv TSS: 0.2453
mean cv HSS: 0.1104
684/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6900 : val tss = 0.2568 ::: train hss = 0.0932 : val hss = 0.0510
Fold 2: train tss = 0.5934 : val tss = 0.6462 ::: train hss = 0.0637 : val hss = 0.2589
Fold 3: train tss = 0.6283 : val tss = 0.1168 ::: train hss = 0.1167 : val hss = 0.0176
Fold 4: train tss = 0.6362 : val tss = 0.6080 ::: train hss = 0.1236 : val hss = 0.1903
mean cv TSS: 0.3256
mean cv HSS: 0.1036
685/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0475 : val tss = -0.0099 ::: train hss = 0.0452 : val hss = -0.0141
Fold 1: train tss = 0.4833 : val tss = 0.3864 ::: train hss = 0.0871 : val hss = 0.0621
Fold 2: train tss = 0.4722 : val tss = 0.6056 ::: train hss = 0.0525 : val hss = 0.2145
Fold 3: train tss = 0.4788 : val tss = 0.1071 ::: train hss = 0.0745 : val hss = 0.0115
Fold 4: train tss = 0.5855 : val tss = 0.6306 ::: train hss = 0.0950 : val hss = 0.2006
mean cv TSS: 0.3440
mean cv HSS: 0.0949
686/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6994 : val tss = 0.1591 ::: train hss = 0.1099 : val hss = 0.0391
Fold 2: train tss = 0.6000 : val tss = 0.5608 ::: train hss = 0.0672 : val hss = 0.1884
Fold 3: train tss = 0.6501 : val tss = 0.2149 ::: train hss = 0.1244 : val hss = 0.0305
Fold 4: train tss = 0.6139 : val tss = 0.4080 ::: train hss = 0.1155 : val hss = 0.1366
mean cv TSS: 0.2686
mean cv HSS: 0.0789
687/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.4885 : val tss = -0.0017 ::: train hss = 0.1563 : val hss = -0.0027
Fold 1: train tss = 0.6418 : val tss = 0.2129 ::: train hss = 0.0755 : val hss = 0.0350
Fold 2: train tss = 0.5235 : val tss = 0.6516 ::: train hss = 0.0722 : val hss = 0.2571
Fold 3: train tss = 0.5326 : val tss = 0.1224 ::: train hss = 0.0942 : val hss = 0.0191
Fold 4: train tss = 0.5281 : val tss = 0.6291 ::: train hss = 0.0792 : val hss = 0.1917
mean cv TSS: 0.3229
mean cv HSS: 0.1000
688/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7021 : val tss = 0.0647 ::: train hss = 0.1040 : val hss = 0.0392
Fold 2: train tss = 0.5736 : val tss = 0.6709 ::: train hss = 0.0663 : val hss = 0.3185
Fold 3: train tss = 0.7290 : val tss = 0.0734 ::: train hss = 0.1841 : val hss = 0.0177
Fold 4: train tss = 0.7329 : val tss = 0.6591 ::: train hss = 0.1866 : val hss = 0.4186
mean cv TSS: 0.2936
mean cv HSS: 0.1588
689/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.1919 : val tss = -0.0066 ::: train hss = 0.0853 : val hss = -0.0105
Fold 1: train tss = 0.6409 : val tss = 0.0755 ::: train hss = 0.0639 : val hss = 0.0129
Fold 2: train tss = 0.5303 : val tss = 0.6050 ::: train hss = 0.0650 : val hss = 0.2122
Fold 3: train tss = 0.5596 : val tss = 0.2492 ::: train hss = 0.0921 : val hss = 0.0196
Fold 4: train tss = 0.4913 : val tss = 0.4760 ::: train hss = 0.0691 : val hss = 0.1093
mean cv TSS: 0.2798
mean cv HSS: 0.0687
690/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.7269 : val tss = 0.0029 ::: train hss = 0.1287 : val hss = 0.0034
Fold 1: train tss = 0.8072 : val tss = 0.1386 ::: train hss = 0.3404 : val hss = 0.0731
Fold 2: train tss = 0.4988 : val tss = 0.5619 ::: train hss = 0.1506 : val hss = 0.1955
Fold 3: train tss = 0.6875 : val tss = 0.3043 ::: train hss = 0.1376 : val hss = 0.0559
Fold 4: train tss = 0.7373 : val tss = 0.6083 ::: train hss = 0.1957 : val hss = 0.2240
mean cv TSS: 0.3232
mean cv HSS: 0.1104
691/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.3454 : val tss = 0.0000 ::: train hss = 0.2126 : val hss = 0.0000
Fold 1: train tss = 0.7582 : val tss = 0.1038 ::: train hss = 0.3839 : val hss = 0.0645
Fold 2: train tss = 0.6437 : val tss = 0.6320 ::: train hss = 0.1162 : val hss = 0.2593
Fold 3: train tss = 0.6823 : val tss = 0.1859 ::: train hss = 0.1805 : val hss = 0.0455
Fold 4: train tss = 0.5691 : val tss = 0.6075 ::: train hss = 0.1023 : val hss = 0.1761
mean cv TSS: 0.3058
mean cv HSS: 0.1091
692/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 385569
Fold 0: train tss = 0.8870 : val tss = -0.0014 ::: train hss = 0.2447 : val hss = -0.0026
Fold 1: train tss = 0.7568 : val tss = 0.1302 ::: train hss = 0.4490 : val hss = 0.0718
Fold 2: train tss = 0.7377 : val tss = 0.6540 ::: train hss = 0.1346 : val hss = 0.2973
Fold 3: train tss = 0.8456 : val tss = 0.1721 ::: train hss = 0.3556 : val hss = 0.0670
Fold 4: train tss = 0.7166 : val tss = 0.6275 ::: train hss = 0.1537 : val hss = 0.2830
mean cv TSS: 0.3165
mean cv HSS: 0.1433
693/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.7880 : val tss = 0.0000 ::: train hss = 0.2335 : val hss = 0.0000
Fold 1: train tss = 0.7983 : val tss = 0.1177 ::: train hss = 0.3956 : val hss = 0.0542
Fold 2: train tss = 0.6446 : val tss = 0.6563 ::: train hss = 0.1114 : val hss = 0.3747
Fold 3: train tss = 0.6803 : val tss = 0.0922 ::: train hss = 0.1799 : val hss = 0.0292
Fold 4: train tss = 0.6550 : val tss = 0.7034 ::: train hss = 0.1246 : val hss = 0.2996
mean cv TSS: 0.3139
mean cv HSS: 0.1515
694/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.9941 : val tss = -0.0019 ::: train hss = 0.4519 : val hss = -0.0035
Fold 1: train tss = 0.8871 : val tss = 0.1350 ::: train hss = 0.4982 : val hss = 0.0586
Fold 2: train tss = 0.6709 : val tss = 0.6193 ::: train hss = 0.2252 : val hss = 0.2960
Fold 3: train tss = 0.7562 : val tss = 0.4359 ::: train hss = 0.2304 : val hss = 0.0376
Fold 4: train tss = 0.7254 : val tss = 0.6035 ::: train hss = 0.2152 : val hss = 0.3338
mean cv TSS: 0.3584
mean cv HSS: 0.1445
695/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.8448 : val tss = 0.0000 ::: train hss = 0.4224 : val hss = 0.0000
Fold 1: train tss = 0.7708 : val tss = 0.0595 ::: train hss = 0.5774 : val hss = 0.0284
Fold 2: train tss = 0.5957 : val tss = 0.6037 ::: train hss = 0.1323 : val hss = 0.2497
Fold 3: train tss = 0.6370 : val tss = 0.2878 ::: train hss = 0.1537 : val hss = 0.0786
Fold 4: train tss = 0.6744 : val tss = 0.6720 ::: train hss = 0.1579 : val hss = 0.2565
mean cv TSS: 0.3246
mean cv HSS: 0.1226
696/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8051 : val tss = 0.1723 ::: train hss = 0.3289 : val hss = 0.0784
Fold 2: train tss = 0.7188 : val tss = 0.6286 ::: train hss = 0.1371 : val hss = 0.2734
Fold 3: train tss = 0.8109 : val tss = 0.0379 ::: train hss = 0.2745 : val hss = 0.0211
Fold 4: train tss = 0.7533 : val tss = 0.6643 ::: train hss = 0.1904 : val hss = 0.2602
mean cv TSS: 0.3006
mean cv HSS: 0.1266
697/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = -0.0001 ::: train hss = 0.0000 : val hss = -0.0002
Fold 1: train tss = 0.8076 : val tss = 0.3523 ::: train hss = 0.1590 : val hss = 0.1094
Fold 2: train tss = 0.6288 : val tss = 0.6804 ::: train hss = 0.1094 : val hss = 0.2804
Fold 3: train tss = 0.6546 : val tss = 0.0822 ::: train hss = 0.1567 : val hss = 0.0139
Fold 4: train tss = 0.7072 : val tss = 0.6596 ::: train hss = 0.1780 : val hss = 0.2578
mean cv TSS: 0.3549
mean cv HSS: 0.1323
698/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.2495 : val tss = -0.0001 ::: train hss = 0.3442 : val hss = -0.0002
Fold 1: train tss = 0.8391 : val tss = 0.0299 ::: train hss = 0.2471 : val hss = 0.0332
Fold 2: train tss = 0.6836 : val tss = 0.6116 ::: train hss = 0.1293 : val hss = 0.3635
Fold 3: train tss = 0.8381 : val tss = 0.1863 ::: train hss = 0.3355 : val hss = 0.0394
Fold 4: train tss = 0.7803 : val tss = 0.6416 ::: train hss = 0.2187 : val hss = 0.3133
mean cv TSS: 0.2939
mean cv HSS: 0.1498
699/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0178 ::: train hss = 0.0000 : val hss = 0.0272
Fold 1: train tss = 0.8301 : val tss = 0.0620 ::: train hss = 0.2449 : val hss = 0.0235
Fold 2: train tss = 0.6402 : val tss = 0.7263 ::: train hss = 0.1361 : val hss = 0.3566
Fold 3: train tss = 0.7359 : val tss = 0.3647 ::: train hss = 0.2120 : val hss = 0.0409
Fold 4: train tss = 0.6421 : val tss = 0.5406 ::: train hss = 0.1513 : val hss = 0.1343
mean cv TSS: 0.3423
mean cv HSS: 0.1165
700/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.7937 : val tss = -0.0079 ::: train hss = 0.3608 : val hss = -0.0120
Fold 1: train tss = 0.8778 : val tss = 0.0927 ::: train hss = 0.4485 : val hss = 0.0308
Fold 2: train tss = 0.7325 : val tss = 0.6270 ::: train hss = 0.1811 : val hss = 0.2643
Fold 3: train tss = 0.8356 : val tss = 0.1878 ::: train hss = 0.3235 : val hss = 0.0436
Fold 4: train tss = 0.7860 : val tss = 0.5395 ::: train hss = 0.2662 : val hss = 0.1932
mean cv TSS: 0.2878
mean cv HSS: 0.1040
701/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.5956 : val tss = -0.0001 ::: train hss = 0.3504 : val hss = -0.0002
Fold 1: train tss = 0.7238 : val tss = 0.2123 ::: train hss = 0.2824 : val hss = 0.0780
Fold 2: train tss = 0.6283 : val tss = 0.6941 ::: train hss = 0.1230 : val hss = 0.3605
Fold 3: train tss = 0.7138 : val tss = 0.0284 ::: train hss = 0.1836 : val hss = 0.0042
Fold 4: train tss = 0.6948 : val tss = 0.5600 ::: train hss = 0.1624 : val hss = 0.1762
mean cv TSS: 0.2989
mean cv HSS: 0.1237
702/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.4444 : val tss = -0.0001 ::: train hss = 0.2370 : val hss = -0.0002
Fold 1: train tss = 0.7784 : val tss = 0.1434 ::: train hss = 0.4086 : val hss = 0.0874
Fold 2: train tss = 0.7833 : val tss = 0.6542 ::: train hss = 0.2604 : val hss = 0.2923
Fold 3: train tss = 0.8156 : val tss = 0.0266 ::: train hss = 0.2959 : val hss = 0.0075
Fold 4: train tss = 0.7667 : val tss = 0.6309 ::: train hss = 0.2240 : val hss = 0.3042
mean cv TSS: 0.2910
mean cv HSS: 0.1382
703/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}

Total number of parameters: 534049
Fold 0: train tss = 0.4874 : val tss = 0.0627 ::: train hss = 0.1455 : val hss = 0.0712
Fold 1: train tss = 0.7831 : val tss = 0.1579 ::: train hss = 0.5009 : val hss = 0.1059
Fold 2: train tss = 0.6876 : val tss = 0.6583 ::: train hss = 0.1289 : val hss = 0.3087
Fold 3: train tss = 0.8155 : val tss = -0.0140 ::: train hss = 0.2836 : val hss = -0.0138
Fold 4: train tss = 0.7540 : val tss = 0.6681 ::: train hss = 0.2001 : val hss = 0.2372
mean cv TSS: 0.3066
mean cv HSS: 0.1418
704/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.4840 : val tss = -0.0024 ::: train hss = 0.1195 : val hss = -0.0043
Fold 1: train tss = 0.7907 : val tss = 0.1661 ::: train hss = 0.4418 : val hss = 0.0898
Fold 2: train tss = 0.7593 : val tss = 0.6682 ::: train hss = 0.1646 : val hss = 0.3907
Fold 3: train tss = 0.6710 : val tss = 0.0942 ::: train hss = 0.1669 : val hss = 0.0146
Fold 4: train tss = 0.8018 : val tss = 0.5863 ::: train hss = 0.2547 : val hss = 0.2424
mean cv TSS: 0.3025
mean cv HSS: 0.1467
705/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.3954 : val tss = -0.0040 ::: train hss = 0.2396 : val hss = -0.0068
Fold 1: train tss = 0.7785 : val tss = 0.1725 ::: train hss = 0.4498 : val hss = 0.1096
Fold 2: train tss = 0.7603 : val tss = 0.6482 ::: train hss = 0.2464 : val hss = 0.3787
Fold 3: train tss = 0.7391 : val tss = 0.3124 ::: train hss = 0.2503 : val hss = 0.0400
Fold 4: train tss = 0.7669 : val tss = 0.5644 ::: train hss = 0.2377 : val hss = 0.2750
mean cv TSS: 0.3387
mean cv HSS: 0.1593
706/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.4459 : val tss = -0.0049 ::: train hss = 0.2831 : val hss = -0.0082
Fold 1: train tss = 0.8443 : val tss = 0.0882 ::: train hss = 0.6347 : val hss = 0.0579
Fold 2: train tss = 0.7870 : val tss = 0.6725 ::: train hss = 0.4935 : val hss = 0.2881
Fold 3: train tss = 0.8613 : val tss = 0.3458 ::: train hss = 0.3978 : val hss = 0.0439
Fold 4: train tss = 0.7759 : val tss = 0.6295 ::: train hss = 0.1863 : val hss = 0.3078
mean cv TSS: 0.3462
mean cv HSS: 0.1379
707/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.4456 : val tss = -0.0011 ::: train hss = 0.2742 : val hss = -0.0022
Fold 1: train tss = 0.7919 : val tss = 0.1294 ::: train hss = 0.5645 : val hss = 0.0713
Fold 2: train tss = 0.7346 : val tss = 0.6743 ::: train hss = 0.1406 : val hss = 0.4104
Fold 3: train tss = 0.7548 : val tss = 0.1939 ::: train hss = 0.2207 : val hss = 0.0928
Fold 4: train tss = 0.8132 : val tss = 0.6053 ::: train hss = 0.3155 : val hss = 0.3850
mean cv TSS: 0.3203
mean cv HSS: 0.1915
708/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.5339 : val tss = -0.0276 ::: train hss = 0.1302 : val hss = -0.0238
Fold 1: train tss = 0.6406 : val tss = 0.3242 ::: train hss = 0.0669 : val hss = 0.0565
Fold 2: train tss = 0.5698 : val tss = 0.6398 ::: train hss = 0.0656 : val hss = 0.2372
Fold 3: train tss = 0.6137 : val tss = 0.3031 ::: train hss = 0.1070 : val hss = 0.0386
Fold 4: train tss = 0.6360 : val tss = 0.6236 ::: train hss = 0.1225 : val hss = 0.1924
mean cv TSS: 0.3726
mean cv HSS: 0.1002
709/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6536 : val tss = 0.3492 ::: train hss = 0.1025 : val hss = 0.0730
Fold 2: train tss = 0.4266 : val tss = 0.4717 ::: train hss = 0.0450 : val hss = 0.1077
Fold 3: train tss = 0.5045 : val tss = 0.3938 ::: train hss = 0.0754 : val hss = 0.0461
Fold 4: train tss = 0.5554 : val tss = 0.4651 ::: train hss = 0.0812 : val hss = 0.1021
mean cv TSS: 0.3360
mean cv HSS: 0.0658
710/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0496 : val tss = -0.0002 ::: train hss = 0.0827 : val hss = -0.0005
Fold 1: train tss = 0.6736 : val tss = 0.2028 ::: train hss = 0.0660 : val hss = 0.0350
Fold 2: train tss = 0.6457 : val tss = 0.6363 ::: train hss = 0.0832 : val hss = 0.2327
Fold 3: train tss = 0.6265 : val tss = 0.1537 ::: train hss = 0.1148 : val hss = 0.0222
Fold 4: train tss = 0.6244 : val tss = 0.5699 ::: train hss = 0.1064 : val hss = 0.2372
mean cv TSS: 0.3125
mean cv HSS: 0.1053
711/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6919 : val tss = 0.2340 ::: train hss = 0.0739 : val hss = 0.0872
Fold 2: train tss = 0.4696 : val tss = 0.5844 ::: train hss = 0.0447 : val hss = 0.1913
Fold 3: train tss = 0.5817 : val tss = 0.1793 ::: train hss = 0.0975 : val hss = 0.0179
Fold 4: train tss = 0.5391 : val tss = 0.5130 ::: train hss = 0.0745 : val hss = 0.1226
mean cv TSS: 0.3021
mean cv HSS: 0.0838
712/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.9247 : val tss = -0.0731 ::: train hss = 0.1504 : val hss = -0.0355
Fold 1: train tss = 0.7652 : val tss = 0.0128 ::: train hss = 0.0920 : val hss = 0.0046
Fold 2: train tss = 0.6201 : val tss = 0.6266 ::: train hss = 0.0871 : val hss = 0.2261
Fold 3: train tss = 0.6658 : val tss = 0.1902 ::: train hss = 0.1207 : val hss = 0.0252
Fold 4: train tss = 0.5575 : val tss = 0.4813 ::: train hss = 0.0805 : val hss = 0.1095
mean cv TSS: 0.2475
mean cv HSS: 0.0660
713/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = -0.0039 : val tss = 0.0000 ::: train hss = -0.0030 : val hss = 0.0000
Fold 1: train tss = 0.6896 : val tss = 0.0181 ::: train hss = 0.0630 : val hss = 0.0031
Fold 2: train tss = 0.5604 : val tss = 0.4672 ::: train hss = 0.0765 : val hss = 0.1119
Fold 3: train tss = 0.6022 : val tss = 0.0448 ::: train hss = 0.1063 : val hss = 0.0041
Fold 4: train tss = 0.4683 : val tss = 0.4684 ::: train hss = 0.0626 : val hss = 0.1040
mean cv TSS: 0.1997
mean cv HSS: 0.0446
714/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}

Total number of parameters: 534049
Fold 0: train tss = 0.6849 : val tss = -0.0032 ::: train hss = 0.1723 : val hss = -0.0057
Fold 1: train tss = 0.7371 : val tss = 0.1297 ::: train hss = 0.1866 : val hss = 0.1271
Fold 2: train tss = 0.5606 : val tss = 0.6195 ::: train hss = 0.0878 : val hss = 0.2615
Fold 3: train tss = 0.6284 : val tss = 0.1150 ::: train hss = 0.1121 : val hss = 0.0246
Fold 4: train tss = 0.6891 : val tss = 0.6328 ::: train hss = 0.1540 : val hss = 0.2199
mean cv TSS: 0.2988
mean cv HSS: 0.1255
715/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.7329 : val tss = -0.0031 ::: train hss = 0.1656 : val hss = -0.0055
Fold 1: train tss = 0.7485 : val tss = 0.1906 ::: train hss = 0.2121 : val hss = 0.1213
Fold 2: train tss = 0.4465 : val tss = 0.4575 ::: train hss = 0.0534 : val hss = 0.1615
Fold 3: train tss = 0.5432 : val tss = 0.0102 ::: train hss = 0.0902 : val hss = 0.0017
Fold 4: train tss = 0.6181 : val tss = 0.5898 ::: train hss = 0.1130 : val hss = 0.1694
mean cv TSS: 0.2490
mean cv HSS: 0.0897
716/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.7949 : val tss = -0.0031 ::: train hss = 0.4076 : val hss = -0.0055
Fold 1: train tss = 0.6937 : val tss = 0.1752 ::: train hss = 0.1248 : val hss = 0.0644
Fold 2: train tss = 0.7520 : val tss = 0.6739 ::: train hss = 0.2428 : val hss = 0.3033
Fold 3: train tss = 0.7284 : val tss = 0.3191 ::: train hss = 0.1792 : val hss = 0.0701
Fold 4: train tss = 0.7264 : val tss = 0.7311 ::: train hss = 0.1712 : val hss = 0.3305
mean cv TSS: 0.3792
mean cv HSS: 0.1526
717/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.7925 : val tss = -0.0022 ::: train hss = 0.3235 : val hss = -0.0041
Fold 1: train tss = 0.7134 : val tss = 0.2100 ::: train hss = 0.1532 : val hss = 0.0896
Fold 2: train tss = 0.4944 : val tss = 0.4667 ::: train hss = 0.0810 : val hss = 0.1908
Fold 3: train tss = 0.6988 : val tss = 0.0346 ::: train hss = 0.1849 : val hss = 0.0081
Fold 4: train tss = 0.6570 : val tss = 0.6056 ::: train hss = 0.1383 : val hss = 0.1748
mean cv TSS: 0.2629
mean cv HSS: 0.0918
718/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.9918 : val tss = 0.0030 ::: train hss = 0.3708 : val hss = 0.0055
Fold 1: train tss = 0.8792 : val tss = 0.0727 ::: train hss = 0.3922 : val hss = 0.0502
Fold 2: train tss = 0.7384 : val tss = 0.6284 ::: train hss = 0.2580 : val hss = 0.3195
Fold 3: train tss = 0.5556 : val tss = 0.1200 ::: train hss = 0.0846 : val hss = 0.0089
Fold 4: train tss = 0.6125 : val tss = 0.5420 ::: train hss = 0.1090 : val hss = 0.2044
mean cv TSS: 0.2732
mean cv HSS: 0.1177
719/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.05, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.8462 : val tss = -0.0002 ::: train hss = 0.4978 : val hss = -0.0005
Fold 1: train tss = 0.8317 : val tss = 0.0946 ::: train hss = 0.4630 : val hss = 0.0637
Fold 2: train tss = 0.4430 : val tss = 0.4592 ::: train hss = 0.0380 : val hss = 0.1696
Fold 3: train tss = 0.5677 : val tss = 0.3359 ::: train hss = 0.1339 : val hss = 0.0236
Fold 4: train tss = 0.7297 : val tss = 0.6601 ::: train hss = 0.2067 : val hss = 0.3561
mean cv TSS: 0.3099
mean cv HSS: 0.1225
720/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7847 : val tss = 0.2738 ::: train hss = 0.1934 : val hss = 0.0684
Fold 2: train tss = 0.7367 : val tss = 0.6936 ::: train hss = 0.2160 : val hss = 0.3751
Fold 3: train tss = 0.7698 : val tss = 0.1123 ::: train hss = 0.2348 : val hss = 0.0235
Fold 4: train tss = 0.7554 : val tss = 0.5946 ::: train hss = 0.1934 : val hss = 0.2303
mean cv TSS: 0.3349
mean cv HSS: 0.1395
721/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8007 : val tss = 0.0910 ::: train hss = 0.3064 : val hss = 0.0328
Fold 2: train tss = 0.6330 : val tss = 0.6446 ::: train hss = 0.1251 : val hss = 0.4085
Fold 3: train tss = 0.7378 : val tss = 0.1988 ::: train hss = 0.2116 : val hss = 0.0249
Fold 4: train tss = 0.6927 : val tss = 0.6159 ::: train hss = 0.1594 : val hss = 0.1929
mean cv TSS: 0.3101
mean cv HSS: 0.1318
722/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7763 : val tss = 0.1931 ::: train hss = 0.2321 : val hss = 0.0737
Fold 2: train tss = 0.7368 : val tss = 0.6744 ::: train hss = 0.2286 : val hss = 0.3369
Fold 3: train tss = 0.7730 : val tss = 0.4916 ::: train hss = 0.2220 : val hss = 0.0676
Fold 4: train tss = 0.7378 : val tss = 0.6906 ::: train hss = 0.1964 : val hss = 0.2481
mean cv TSS: 0.4099
mean cv HSS: 0.1453
723/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = -0.0001 : val tss = -0.0012 ::: train hss = -0.0002 : val hss = -0.0024
Fold 1: train tss = 0.8251 : val tss = 0.3071 ::: train hss = 0.1939 : val hss = 0.0757
Fold 2: train tss = 0.6163 : val tss = 0.7213 ::: train hss = 0.1113 : val hss = 0.4236
Fold 3: train tss = 0.6781 : val tss = 0.2412 ::: train hss = 0.1669 : val hss = 0.0447
Fold 4: train tss = 0.6843 : val tss = 0.6345 ::: train hss = 0.1514 : val hss = 0.2117
mean cv TSS: 0.3806
mean cv HSS: 0.1507
724/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8273 : val tss = 0.2064 ::: train hss = 0.1598 : val hss = 0.0962
Fold 2: train tss = 0.7015 : val tss = 0.5979 ::: train hss = 0.1486 : val hss = 0.2658
Fold 3: train tss = 0.7734 : val tss = 0.2460 ::: train hss = 0.2324 : val hss = 0.0397
Fold 4: train tss = 0.6784 : val tss = 0.3738 ::: train hss = 0.1510 : val hss = 0.2144
mean cv TSS: 0.2848
mean cv HSS: 0.1232
725/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}

Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8262 : val tss = 0.0585 ::: train hss = 0.3296 : val hss = 0.0219
Fold 2: train tss = 0.6602 : val tss = 0.6041 ::: train hss = 0.1190 : val hss = 0.2157
Fold 3: train tss = 0.6060 : val tss = 0.3275 ::: train hss = 0.1441 : val hss = 0.0343
Fold 4: train tss = 0.6016 : val tss = 0.6708 ::: train hss = 0.1050 : val hss = 0.2322
mean cv TSS: 0.3322
mean cv HSS: 0.1008
726/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = -0.0181 ::: train hss = 0.0000 : val hss = -0.0210
Fold 1: train tss = 0.7847 : val tss = 0.2982 ::: train hss = 0.2912 : val hss = 0.0813
Fold 2: train tss = 0.6881 : val tss = 0.6605 ::: train hss = 0.1720 : val hss = 0.2814
Fold 3: train tss = 0.7436 : val tss = 0.2185 ::: train hss = 0.2103 : val hss = 0.0417
Fold 4: train tss = 0.7242 : val tss = 0.6514 ::: train hss = 0.1857 : val hss = 0.2215
mean cv TSS: 0.3621
mean cv HSS: 0.1210
727/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.1738 ::: train hss = 0.0000 : val hss = 0.1924
Fold 1: train tss = 0.7790 : val tss = 0.1943 ::: train hss = 0.3788 : val hss = 0.0671
Fold 2: train tss = 0.6959 : val tss = 0.7225 ::: train hss = 0.1629 : val hss = 0.3386
Fold 3: train tss = 0.7134 : val tss = 0.0285 ::: train hss = 0.1841 : val hss = 0.0082
Fold 4: train tss = 0.6988 : val tss = 0.6642 ::: train hss = 0.1688 : val hss = 0.2563
mean cv TSS: 0.3566
mean cv HSS: 0.1725
728/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0500 : val tss = -0.0225 ::: train hss = 0.0952 : val hss = -0.0214
Fold 1: train tss = 0.7704 : val tss = 0.3220 ::: train hss = 0.4559 : val hss = 0.1106
Fold 2: train tss = 0.6105 : val tss = 0.5752 ::: train hss = 0.2462 : val hss = 0.1782
Fold 3: train tss = 0.7471 : val tss = 0.3637 ::: train hss = 0.2440 : val hss = 0.0478
Fold 4: train tss = 0.7575 : val tss = 0.6456 ::: train hss = 0.2138 : val hss = 0.2200
mean cv TSS: 0.3768
mean cv HSS: 0.1070
729/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0987 : val tss = 0.1523 ::: train hss = 0.1196 : val hss = 0.1486
Fold 1: train tss = 0.7728 : val tss = 0.2631 ::: train hss = 0.4817 : val hss = 0.0987
Fold 2: train tss = 0.5708 : val tss = 0.6091 ::: train hss = 0.2247 : val hss = 0.2054
Fold 3: train tss = 0.7290 : val tss = 0.0071 ::: train hss = 0.2005 : val hss = 0.0015
Fold 4: train tss = 0.7004 : val tss = 0.5959 ::: train hss = 0.1555 : val hss = 0.2428
mean cv TSS: 0.3255
mean cv HSS: 0.1394
730/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.3466 : val tss = 0.1793 ::: train hss = 0.2521 : val hss = 0.1052
Fold 1: train tss = 0.7874 : val tss = 0.1529 ::: train hss = 0.5622 : val hss = 0.0534
Fold 2: train tss = 0.7114 : val tss = 0.6369 ::: train hss = 0.1215 : val hss = 0.2424
Fold 3: train tss = 0.8042 : val tss = 0.2516 ::: train hss = 0.2850 : val hss = 0.0261
Fold 4: train tss = 0.7233 : val tss = 0.5904 ::: train hss = 0.1736 : val hss = 0.1750
mean cv TSS: 0.3622
mean cv HSS: 0.1204
731/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = -0.0076 ::: train hss = 0.0000 : val hss = -0.0117
Fold 1: train tss = 0.8374 : val tss = 0.1583 ::: train hss = 0.4355 : val hss = 0.0620
Fold 2: train tss = 0.5495 : val tss = 0.6689 ::: train hss = 0.2537 : val hss = 0.4309
Fold 3: train tss = 0.7913 : val tss = 0.2309 ::: train hss = 0.3295 : val hss = 0.0298
Fold 4: train tss = 0.7844 : val tss = 0.4412 ::: train hss = 0.2758 : val hss = 0.2148
mean cv TSS: 0.2983
mean cv HSS: 0.1452
732/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6692 : val tss = 0.3092 ::: train hss = 0.1122 : val hss = 0.0699
Fold 2: train tss = 0.5447 : val tss = 0.6370 ::: train hss = 0.0670 : val hss = 0.2260
Fold 3: train tss = 0.6868 : val tss = 0.0932 ::: train hss = 0.1561 : val hss = 0.0245
Fold 4: train tss = 0.5875 : val tss = 0.5974 ::: train hss = 0.0939 : val hss = 0.1711
mean cv TSS: 0.3274
mean cv HSS: 0.0983
733/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6074 : val tss = 0.3337 ::: train hss = 0.0643 : val hss = 0.0771
Fold 2: train tss = 0.5085 : val tss = 0.6082 ::: train hss = 0.0649 : val hss = 0.2106
Fold 3: train tss = 0.5651 : val tss = 0.0452 ::: train hss = 0.0899 : val hss = 0.0107
Fold 4: train tss = 0.5205 : val tss = 0.5883 ::: train hss = 0.0779 : val hss = 0.1599
mean cv TSS: 0.3151
mean cv HSS: 0.0917
734/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7551 : val tss = 0.2686 ::: train hss = 0.1191 : val hss = 0.0949
Fold 2: train tss = 0.5003 : val tss = 0.6333 ::: train hss = 0.0478 : val hss = 0.2262
Fold 3: train tss = 0.5830 : val tss = 0.2588 ::: train hss = 0.0947 : val hss = 0.0284
Fold 4: train tss = 0.6352 : val tss = 0.5861 ::: train hss = 0.1282 : val hss = 0.1799
mean cv TSS: 0.3494
mean cv HSS: 0.1059
735/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6479 : val tss = 0.2543 ::: train hss = 0.0872 : val hss = 0.0804
Fold 2: train tss = 0.5259 : val tss = 0.6550 ::: train hss = 0.0709 : val hss = 0.2399
Fold 3: train tss = 0.5673 : val tss = 0.2524 ::: train hss = 0.0960 : val hss = 0.0199
Fold 4: train tss = 0.5018 : val tss = 0.5125 ::: train hss = 0.0714 : val hss = 0.1213
mean cv TSS: 0.3349
mean cv HSS: 0.0923
736/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}

Total number of parameters: 754209
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7049 : val tss = 0.0881 ::: train hss = 0.2560 : val hss = 0.0283
Fold 2: train tss = 0.5107 : val tss = 0.5717 ::: train hss = 0.0589 : val hss = 0.1977
Fold 3: train tss = 0.5729 : val tss = 0.4886 ::: train hss = 0.0991 : val hss = 0.0376
Fold 4: train tss = 0.5894 : val tss = 0.5706 ::: train hss = 0.1120 : val hss = 0.1971
mean cv TSS: 0.3438
mean cv HSS: 0.0921
737/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.1680 : val tss = -0.0059 ::: train hss = 0.0235 : val hss = -0.0095
Fold 1: train tss = 0.6612 : val tss = 0.1151 ::: train hss = 0.0529 : val hss = 0.0147
Fold 2: train tss = 0.5121 : val tss = 0.5972 ::: train hss = 0.0675 : val hss = 0.2043
Fold 3: train tss = 0.5481 : val tss = 0.1119 ::: train hss = 0.0991 : val hss = 0.0128
Fold 4: train tss = 0.5632 : val tss = 0.6111 ::: train hss = 0.0821 : val hss = 0.1792
mean cv TSS: 0.2859
mean cv HSS: 0.0803
738/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 188961
Fold 0: train tss = 0.6296 : val tss = -0.0219 ::: train hss = 0.1247 : val hss = -0.0150
Fold 1: train tss = 0.7183 : val tss = 0.3669 ::: train hss = 0.2585 : val hss = 0.1295
Fold 2: train tss = 0.6517 : val tss = 0.6925 ::: train hss = 0.1514 : val hss = 0.3555
Fold 3: train tss = 0.6751 : val tss = 0.0488 ::: train hss = 0.1597 : val hss = 0.0203
Fold 4: train tss = 0.7035 : val tss = 0.6468 ::: train hss = 0.1665 : val hss = 0.2022
mean cv TSS: 0.3466
mean cv HSS: 0.1385
739/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 188961
Fold 0: train tss = 0.0483 : val tss = -0.0001 ::: train hss = 0.0552 : val hss = -0.0002
Fold 1: train tss = 0.6975 : val tss = 0.2869 ::: train hss = 0.1649 : val hss = 0.1219
Fold 2: train tss = 0.5571 : val tss = 0.5979 ::: train hss = 0.1224 : val hss = 0.2735
Fold 3: train tss = 0.6825 : val tss = 0.1013 ::: train hss = 0.1717 : val hss = 0.0243
Fold 4: train tss = 0.6651 : val tss = 0.6003 ::: train hss = 0.1375 : val hss = 0.1710
mean cv TSS: 0.3173
mean cv HSS: 0.1181
740/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 385569
Fold 0: train tss = 0.6396 : val tss = -0.0255 ::: train hss = 0.2150 : val hss = -0.0167
Fold 1: train tss = 0.7665 : val tss = 0.2340 ::: train hss = 0.1078 : val hss = 0.0304
Fold 2: train tss = 0.4466 : val tss = 0.5401 ::: train hss = 0.1709 : val hss = 0.2553
Fold 3: train tss = 0.8120 : val tss = 0.2480 ::: train hss = 0.3210 : val hss = 0.0599
Fold 4: train tss = 0.7495 : val tss = 0.6692 ::: train hss = 0.2333 : val hss = 0.2500
mean cv TSS: 0.3332
mean cv HSS: 0.1158
741/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 385569
Fold 0: train tss = 0.6395 : val tss = -0.0110 ::: train hss = 0.2132 : val hss = -0.0153
Fold 1: train tss = 0.7784 : val tss = 0.1309 ::: train hss = 0.4492 : val hss = 0.0575
Fold 2: train tss = 0.6539 : val tss = 0.6050 ::: train hss = 0.1246 : val hss = 0.2207
Fold 3: train tss = 0.6664 : val tss = 0.0534 ::: train hss = 0.1715 : val hss = 0.0109
Fold 4: train tss = 0.6425 : val tss = 0.6508 ::: train hss = 0.1231 : val hss = 0.2657
mean cv TSS: 0.2858
mean cv HSS: 0.1079
742/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 754209
Fold 0: train tss = 0.9801 : val tss = -0.0047 ::: train hss = 0.1931 : val hss = -0.0047
Fold 1: train tss = 0.8893 : val tss = 0.1057 ::: train hss = 0.4358 : val hss = 0.0366
Fold 2: train tss = 0.5925 : val tss = 0.6707 ::: train hss = 0.2386 : val hss = 0.3820
Fold 3: train tss = 0.5234 : val tss = 0.1169 ::: train hss = 0.1689 : val hss = 0.0256
Fold 4: train tss = 0.6816 : val tss = 0.6714 ::: train hss = 0.2139 : val hss = 0.2347
mean cv TSS: 0.3120
mean cv HSS: 0.1349
743/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 256, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 754209
Fold 0: train tss = 0.7867 : val tss = -0.0159 ::: train hss = 0.2170 : val hss = -0.0173
Fold 1: train tss = 0.8624 : val tss = 0.0604 ::: train hss = 0.4278 : val hss = 0.0146
Fold 2: train tss = 0.6525 : val tss = 0.5481 ::: train hss = 0.1480 : val hss = 0.2463
Fold 3: train tss = 0.6783 : val tss = -0.0053 ::: train hss = 0.1847 : val hss = -0.0011
Fold 4: train tss = 0.6174 : val tss = 0.6202 ::: train hss = 0.1346 : val hss = 0.2619
mean cv TSS: 0.2415
mean cv HSS: 0.1009
744/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8172 : val tss = 0.1998 ::: train hss = 0.2432 : val hss = 0.0615
Fold 2: train tss = 0.6897 : val tss = 0.7000 ::: train hss = 0.1514 : val hss = 0.3475
Fold 3: train tss = 0.7609 : val tss = 0.4322 ::: train hss = 0.2332 : val hss = 0.0748
Fold 4: train tss = 0.7271 : val tss = 0.6265 ::: train hss = 0.2087 : val hss = 0.1953
mean cv TSS: 0.3917
mean cv HSS: 0.1358
745/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7976 : val tss = 0.1677 ::: train hss = 0.2600 : val hss = 0.0698
Fold 2: train tss = 0.6163 : val tss = 0.7098 ::: train hss = 0.1094 : val hss = 0.3474
Fold 3: train tss = 0.7244 : val tss = 0.1220 ::: train hss = 0.1983 : val hss = 0.0164
Fold 4: train tss = 0.6633 : val tss = 0.6330 ::: train hss = 0.1447 : val hss = 0.1992
mean cv TSS: 0.3265
mean cv HSS: 0.1266
746/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.8240 : val tss = 0.0384 ::: train hss = 0.1846 : val hss = 0.0144
Fold 2: train tss = 0.6909 : val tss = 0.6821 ::: train hss = 0.1375 : val hss = 0.3318
Fold 3: train tss = 0.7681 : val tss = 0.3755 ::: train hss = 0.2263 : val hss = 0.0523
Fold 4: train tss = 0.7246 : val tss = 0.6400 ::: train hss = 0.1775 : val hss = 0.2127
mean cv TSS: 0.3472
mean cv HSS: 0.1222
747/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}

Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.7517 : val tss = 0.2671 ::: train hss = 0.2757 : val hss = 0.0987
Fold 2: train tss = 0.5517 : val tss = 0.6323 ::: train hss = 0.0843 : val hss = 0.2410
Fold 3: train tss = 0.7568 : val tss = 0.2442 ::: train hss = 0.2308 : val hss = 0.0388
Fold 4: train tss = 0.6004 : val tss = 0.4562 ::: train hss = 0.1206 : val hss = 0.0986
mean cv TSS: 0.3200
mean cv HSS: 0.0954
748/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.2480 : val tss = -0.0027 ::: train hss = 0.2420 : val hss = -0.0049
Fold 1: train tss = 0.8547 : val tss = 0.1716 ::: train hss = 0.2575 : val hss = 0.0767
Fold 2: train tss = 0.6820 : val tss = 0.6698 ::: train hss = 0.1378 : val hss = 0.2905
Fold 3: train tss = 0.7476 : val tss = 0.1714 ::: train hss = 0.1982 : val hss = 0.0217
Fold 4: train tss = 0.7057 : val tss = 0.5901 ::: train hss = 0.1799 : val hss = 0.1965
mean cv TSS: 0.3200
mean cv HSS: 0.1161
749/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.0489 : val tss = -0.0016 ::: train hss = 0.0652 : val hss = -0.0030
Fold 1: train tss = 0.8080 : val tss = 0.2250 ::: train hss = 0.2297 : val hss = 0.1478
Fold 2: train tss = 0.6674 : val tss = 0.5878 ::: train hss = 0.1421 : val hss = 0.1994
Fold 3: train tss = 0.6658 : val tss = 0.0562 ::: train hss = 0.1512 : val hss = 0.0110
Fold 4: train tss = 0.5749 : val tss = 0.3794 ::: train hss = 0.1030 : val hss = 0.0759
mean cv TSS: 0.2493
mean cv HSS: 0.0862
750/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = -0.0024 : val tss = 0.2846 ::: train hss = -0.0024 : val hss = 0.1625
Fold 1: train tss = 0.7499 : val tss = 0.2772 ::: train hss = 0.3058 : val hss = 0.1001
Fold 2: train tss = 0.6873 : val tss = 0.6789 ::: train hss = 0.1882 : val hss = 0.2788
Fold 3: train tss = 0.7426 : val tss = 0.0524 ::: train hss = 0.2147 : val hss = 0.0099
Fold 4: train tss = 0.7099 : val tss = 0.6340 ::: train hss = 0.1871 : val hss = 0.2238
mean cv TSS: 0.3854
mean cv HSS: 0.1550
751/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.0477 : val tss = 0.0398 ::: train hss = 0.0477 : val hss = 0.0275
Fold 1: train tss = 0.7441 : val tss = 0.3118 ::: train hss = 0.2621 : val hss = 0.0920
Fold 2: train tss = 0.6838 : val tss = 0.7143 ::: train hss = 0.1687 : val hss = 0.3029
Fold 3: train tss = 0.7228 : val tss = 0.0580 ::: train hss = 0.1880 : val hss = 0.0155
Fold 4: train tss = 0.6582 : val tss = 0.6385 ::: train hss = 0.1453 : val hss = 0.2066
mean cv TSS: 0.3525
mean cv HSS: 0.1289
752/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.0994 : val tss = 0.0262 ::: train hss = 0.1473 : val hss = 0.0293
Fold 1: train tss = 0.7864 : val tss = 0.2172 ::: train hss = 0.3714 : val hss = 0.0813
Fold 2: train tss = 0.6598 : val tss = 0.6686 ::: train hss = 0.1680 : val hss = 0.3089
Fold 3: train tss = 0.7574 : val tss = 0.2401 ::: train hss = 0.2423 : val hss = 0.0470
Fold 4: train tss = 0.7353 : val tss = 0.4602 ::: train hss = 0.1978 : val hss = 0.2192
mean cv TSS: 0.3224
mean cv HSS: 0.1371
753/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.1475 : val tss = 0.1854 ::: train hss = 0.1341 : val hss = 0.1338
Fold 1: train tss = 0.7651 : val tss = 0.2277 ::: train hss = 0.3720 : val hss = 0.0917
Fold 2: train tss = 0.6639 : val tss = 0.5912 ::: train hss = 0.1712 : val hss = 0.2606
Fold 3: train tss = 0.7329 : val tss = 0.5315 ::: train hss = 0.2200 : val hss = 0.0523
Fold 4: train tss = 0.7046 : val tss = 0.5849 ::: train hss = 0.1755 : val hss = 0.2540
mean cv TSS: 0.4242
mean cv HSS: 0.1585
754/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.2488 : val tss = -0.0097 ::: train hss = 0.2843 : val hss = -0.0140
Fold 1: train tss = 0.7952 : val tss = 0.1600 ::: train hss = 0.4449 : val hss = 0.0509
Fold 2: train tss = 0.7423 : val tss = 0.5671 ::: train hss = 0.3027 : val hss = 0.1721
Fold 3: train tss = 0.8015 : val tss = 0.2653 ::: train hss = 0.3702 : val hss = 0.0432
Fold 4: train tss = 0.7739 : val tss = 0.4975 ::: train hss = 0.2253 : val hss = 0.2186
mean cv TSS: 0.2960
mean cv HSS: 0.0942
755/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.005, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.2976 : val tss = 0.0361 ::: train hss = 0.2587 : val hss = 0.0361
Fold 1: train tss = 0.7854 : val tss = 0.2212 ::: train hss = 0.5333 : val hss = 0.0898
Fold 2: train tss = 0.5792 : val tss = 0.6717 ::: train hss = 0.0648 : val hss = 0.2958
Fold 3: train tss = 0.7907 : val tss = 0.3112 ::: train hss = 0.3593 : val hss = 0.0288
Fold 4: train tss = 0.7120 : val tss = 0.6032 ::: train hss = 0.1717 : val hss = 0.2812
mean cv TSS: 0.3687
mean cv HSS: 0.1463
756/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.6689 : val tss = 0.2998 ::: train hss = 0.1005 : val hss = 0.0696
Fold 2: train tss = 0.5564 : val tss = 0.6311 ::: train hss = 0.0677 : val hss = 0.2201
Fold 3: train tss = 0.6918 : val tss = 0.1449 ::: train hss = 0.1658 : val hss = 0.0294
Fold 4: train tss = 0.5680 : val tss = 0.5691 ::: train hss = 0.0846 : val hss = 0.1535
mean cv TSS: 0.3290
mean cv HSS: 0.0945
757/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = -0.0002 : val tss = -0.0007 ::: train hss = -0.0004 : val hss = -0.0014
Fold 1: train tss = 0.6590 : val tss = 0.4112 ::: train hss = 0.0895 : val hss = 0.0788
Fold 2: train tss = 0.5438 : val tss = 0.4218 ::: train hss = 0.0635 : val hss = 0.0963
Fold 3: train tss = 0.5866 : val tss = 0.4219 ::: train hss = 0.0992 : val hss = 0.0428
Fold 4: train tss = 0.4958 : val tss = 0.5487 ::: train hss = 0.0842 : val hss = 0.1422
mean cv TSS: 0.3606
mean cv HSS: 0.0717
758/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.0025}

Total number of parameters: 1123873
Fold 0: train tss = 0.4313 : val tss = -0.0337 ::: train hss = 0.0943 : val hss = -0.0286
Fold 1: train tss = 0.6926 : val tss = 0.1408 ::: train hss = 0.0868 : val hss = 0.0275
Fold 2: train tss = 0.4413 : val tss = 0.5492 ::: train hss = 0.0343 : val hss = 0.1484
Fold 3: train tss = 0.6539 : val tss = 0.1063 ::: train hss = 0.1288 : val hss = 0.0213
Fold 4: train tss = 0.6069 : val tss = 0.6361 ::: train hss = 0.1115 : val hss = 0.2012
mean cv TSS: 0.2798
mean cv HSS: 0.0740
759/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.0000 : val tss = 0.0000 ::: train hss = 0.0000 : val hss = 0.0000
Fold 1: train tss = 0.5943 : val tss = 0.1996 ::: train hss = 0.0570 : val hss = 0.0329
Fold 2: train tss = 0.5131 : val tss = 0.6239 ::: train hss = 0.0744 : val hss = 0.2058
Fold 3: train tss = 0.5283 : val tss = 0.2510 ::: train hss = 0.0826 : val hss = 0.0311
Fold 4: train tss = 0.5095 : val tss = 0.4626 ::: train hss = 0.0749 : val hss = 0.1015
mean cv TSS: 0.3074
mean cv HSS: 0.0743
760/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.3915 : val tss = -0.0272 ::: train hss = 0.1598 : val hss = -0.0165
Fold 1: train tss = 0.7226 : val tss = -0.0355 ::: train hss = 0.0900 : val hss = -0.0094
Fold 2: train tss = 0.5517 : val tss = 0.5724 ::: train hss = 0.0703 : val hss = 0.1865
Fold 3: train tss = 0.6180 : val tss = 0.0315 ::: train hss = 0.1153 : val hss = 0.0026
Fold 4: train tss = 0.5527 : val tss = 0.5868 ::: train hss = 0.0836 : val hss = 0.1637
mean cv TSS: 0.2256
mean cv HSS: 0.0654
761/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'adam', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = -0.0022 : val tss = -0.0110 ::: train hss = -0.0023 : val hss = -0.0153
Fold 1: train tss = 0.6573 : val tss = 0.1071 ::: train hss = 0.0710 : val hss = 0.0202
Fold 2: train tss = 0.3794 : val tss = 0.3993 ::: train hss = 0.0316 : val hss = 0.0922
Fold 3: train tss = 0.5093 : val tss = 0.2931 ::: train hss = 0.0746 : val hss = 0.0207
Fold 4: train tss = 0.5384 : val tss = 0.5951 ::: train hss = 0.0792 : val hss = 0.1657
mean cv TSS: 0.2767
mean cv HSS: 0.0567
762/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.0025}
Total number of parameters: 534049
Fold 0: train tss = 0.5262 : val tss = -0.0471 ::: train hss = 0.0923 : val hss = -0.0253
Fold 1: train tss = 0.6900 : val tss = 0.3551 ::: train hss = 0.1423 : val hss = 0.0831
Fold 2: train tss = 0.6471 : val tss = 0.5831 ::: train hss = 0.1656 : val hss = 0.2345
Fold 3: train tss = 0.5043 : val tss = 0.1306 ::: train hss = 0.0661 : val hss = 0.0133
Fold 4: train tss = 0.7698 : val tss = 0.6373 ::: train hss = 0.2517 : val hss = 0.2352
mean cv TSS: 0.3318
mean cv HSS: 0.1081
763/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 30, 'weight_decay': 0.05}
Total number of parameters: 534049
Fold 0: train tss = 0.4861 : val tss = -0.0014 ::: train hss = 0.1341 : val hss = -0.0023
Fold 1: train tss = 0.7927 : val tss = 0.3022 ::: train hss = 0.2440 : val hss = 0.1293
Fold 2: train tss = 0.4987 : val tss = 0.5535 ::: train hss = 0.0818 : val hss = 0.2025
Fold 3: train tss = 0.6852 : val tss = 0.1546 ::: train hss = 0.1723 : val hss = 0.0397
Fold 4: train tss = 0.6561 : val tss = 0.6719 ::: train hss = 0.1327 : val hss = 0.2228
mean cv TSS: 0.3362
mean cv HSS: 0.1184
764/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.0025}
Total number of parameters: 1123873
Fold 0: train tss = 0.5455 : val tss = -0.0227 ::: train hss = 0.3209 : val hss = -0.0237
Fold 1: train tss = 0.8387 : val tss = 0.0480 ::: train hss = 0.4461 : val hss = 0.0292
Fold 2: train tss = 0.5418 : val tss = 0.5477 ::: train hss = 0.0917 : val hss = 0.2398
Fold 3: train tss = 0.5639 : val tss = 0.2754 ::: train hss = 0.0879 : val hss = 0.0270
Fold 4: train tss = 0.6941 : val tss = 0.6755 ::: train hss = 0.1670 : val hss = 0.2383
mean cv TSS: 0.3048
mean cv HSS: 0.1021
765/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 60, 'weight_decay': 0.05}
Total number of parameters: 1123873
Fold 0: train tss = 0.6874 : val tss = -0.0032 ::: train hss = 0.1992 : val hss = -0.0057
Fold 1: train tss = 0.7531 : val tss = 0.1232 ::: train hss = 0.3783 : val hss = 0.0758
Fold 2: train tss = 0.5607 : val tss = 0.6420 ::: train hss = 0.1383 : val hss = 0.3206
Fold 3: train tss = 0.6466 : val tss = 0.2886 ::: train hss = 0.1650 : val hss = 0.0432
Fold 4: train tss = 0.6446 : val tss = 0.6838 ::: train hss = 0.1288 : val hss = 0.2506
mean cv TSS: 0.3469
mean cv HSS: 0.1369
766/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.0025}
Total number of parameters: 2229793
Fold 0: train tss = 0.8394 : val tss = -0.0325 ::: train hss = 0.2708 : val hss = -0.0224
Fold 1: train tss = 0.8814 : val tss = 0.0121 ::: train hss = 0.3302 : val hss = 0.0054
Fold 2: train tss = 0.7083 : val tss = 0.7275 ::: train hss = 0.1938 : val hss = 0.4081
Fold 3: train tss = 0.7205 : val tss = 0.1698 ::: train hss = 0.1801 : val hss = 0.0320
Fold 4: train tss = 0.7304 : val tss = 0.6641 ::: train hss = 0.2771 : val hss = 0.2671
mean cv TSS: 0.3082
mean cv HSS: 0.1381
767/768
{'batch_size': 4864, 'bce_pos_class_weight': 50, 'cnn_filters': 48, 'cv_folds': 5, 'dropout_p': 0.4, 'fc_size': 768, 'loss': 'bce', 'lr': 0.025, 'num_epochs': 15, 'optimizer_type': 'sgd', 'sequence_length': 120, 'weight_decay': 0.05}
Total number of parameters: 2229793
Fold 0: train tss = 0.9707 : val tss = -0.0110 ::: train hss = 0.1387 : val hss = -0.0153
Fold 1: train tss = 0.8542 : val tss = 0.1687 ::: train hss = 0.5200 : val hss = 0.0685
Fold 2: train tss = 0.4057 : val tss = 0.3051 ::: train hss = 0.0864 : val hss = 0.0589
Fold 3: train tss = 0.7196 : val tss = 0.0554 ::: train hss = 0.2538 : val hss = 0.0197
Fold 4: train tss = 0.6806 : val tss = 0.6805 ::: train hss = 0.1830 : val hss = 0.2592
mean cv TSS: 0.2398
mean cv HSS: 0.0782

,batch_size,bce_pos_class_weight,cnn_filters,dropout_p,fc_size,lr,optimizer_type,sequence_length,weight_decay,tss,hss
336,3584,50,48,0.40,256,0.005,adam,30,0.0025,0.4354,0.1377
753,4864,50,48,0.40,768,0.005,sgd,60,0.0500,0.4242,0.1585
675,4864,50,48,0.05,256,0.005,adam,60,0.0500,0.4167,0.1705
340,3584,50,48,0.40,256,0.005,adam,120,0.0025,0.4142,0.1262
650,4864,50,16,0.40,768,0.005,adam,60,0.0025,0.4124,0.1190
271,3584,50,16,0.40,768,0.005,sgd,30,0.0500,0.4109,0.1191
722,4864,50,48,0.40,256,0.005,adam,60,0.0025,0.4099,0.1453
667,4864,50,16,0.40,768,0.025,sgd,30,0.0500,0.4020,0.1424
362,3584,50,48,0.40,768,0.005,adam,60,0.0025,0.4010,0.1234
613,4864,50,16,0.05,768,0.025,adam,30,0.0500,0.4001,0.0962
345,3584,50,48,0.40,256,0.005,sgd,60,0.0500,0.3927,0.1392
659,4864,50,16,0.40,768,0.005,sgd,120,0.0500,0.3921,0.1597
744,4864,50,48,0.40,768,0.005,adam,30,0.0025,0.3917,0.1358
607,4864,50,16,0.05,768,0.005,sgd,30,0.0500,0.3894,0.1548
242,3584,50,16,0.40,256,0.005,adam,60,0.0025,0.3881,0.1388
284,3584,50,16,0.40,768,0.025,sgd,60,0.0025,0.3876,0.1169
72,3584,15,16,0.40,768,0.005,adam,30,0.0025,0.3860,0.1658
247,3584,50,16,0.40,256,0.005,sgd,30,0.0500,0.3860,0.1304
750,4864,50,48,0.40,768,0.005,sgd,30,0.0025,0.3854,0.1550
354,3584,50,48,0.40,256,0.025,sgd,30,0.0025,0.3852,0.1138

In [11]:
grid.sort_values(by=['hss', 'tss'], ascending=False).head(20)

,batch_size,bce_pos_class_weight,cnn_filters,dropout_p,fc_size,lr,optimizer_type,sequence_length,weight_decay,tss,hss
97,3584,15,48,0.05,256,0.005,adam,30,0.0500,0.3197,0.2223
34,3584,15,16,0.05,768,0.005,sgd,120,0.0025,0.3695,0.2187
402,4864,15,16,0.05,256,0.025,sgd,30,0.0025,0.3221,0.2176
526,4864,15,48,0.05,768,0.025,sgd,120,0.0025,0.2634,0.2172
44,3584,15,16,0.05,768,0.025,sgd,60,0.0025,0.3461,0.2139
549,4864,15,48,0.40,256,0.025,sgd,60,0.0500,0.3205,0.2139
35,3584,15,16,0.05,768,0.005,sgd,120,0.0500,0.2874,0.2136
416,4864,15,16,0.05,768,0.005,sgd,60,0.0025,0.2909,0.2113
482,4864,15,48,0.05,256,0.005,adam,60,0.0025,0.3144,0.2108
394,4864,15,16,0.05,256,0.005,sgd,120,0.0025,0.3100,0.2103
410,4864,15,16,0.05,768,0.005,adam,60,0.0025,0.2964,0.2081
68,3584,15,16,0.40,256,0.025,sgd,60,0.0025,0.2633,0.2075
141,3584,15,48,0.05,768,0.025,sgd,60,0.0500,0.3364,0.2067
2,3584,15,16,0.05,256,0.005,adam,60,0.0025,0.3140,0.2064
115,3584,15,48,0.05,256,0.025,sgd,30,0.0500,0.3049,0.2055
387,4864,15,16,0.05,256,0.005,adam,60,0.0500,0.2860,0.2053
570,4864,15,48,0.40,768,0.025,sgd,30,0.0025,0.3086,0.2034
46,3584,15,16,0.05,768,0.025,sgd,120,0.0025,0.3037,0.2030
124,3584,15,48,0.05,768,0.005,adam,120,0.0025,0.2422,0.2023
19,3584,15,16,0.05,256,0.025,sgd,30,0.0500,0.2644,0.2014

In [12]:
if grid.empty:
    print("grid empty")
else:
    grid.to_csv("cnn_overlap_hypertune_grid_output_5.csv")
    print("grid output successful, saved as cnn_overlap_hypertune_grid_output_5.csv")

grid output successful, saved as cnn_overlap_hypertune_grid_output_5.csv